### ISSUE TITLE
Provide built-in listener for getting notifications to external process

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#1006]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=1006) by bryan.oakley on 27 Nov 2011_

The SocetListener class that is part of RIDE has uses outside of RIDE. I think it should be made part of the robot framework core so people can use it even if they don't install RIDE.

**Comment by pekkaklarck** [comment]
I don't think this issue is important enough to keep open. Can be looked again if someone has a concrete use case.
