### ISSUE TITLE
Ease creating multiline documentation or metadata values.

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#1009]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=1009) by @spooning on 2 Dec 2011_

Creating multiline documentation is currently somewhat annoying as you need to include `\n` in the test data yourself:

```
*** Settings ***
Documentation    First line.\n
...              Second line.\n
...              Third line.
```

We can ease this by combining documentation specified in multiple cells using a newline character instead of space. If that is done, then the above can be written like this:

```
*** Settings ***
Documentation    First line.
...              Second line.
...              Third line.
```

**Comment by xanadiu** [comment]
In my opinion the multiline documentation feature still does not work in the keyword section.

This code:

<pre>
*** Keywords ***
Sign Out
  [Documentation]  Loggt den Benutzer aus. Dieses Keyword schlägt fehl wenn vor dem Ausloggen
  ...  das Logout-Formular nicht vorhanden ist oder nach dem Logout das Login-Formular nicht
  ...  vorhanden ist.
  Click Element  ${form_link_locator}
  Sleep  2
</pre>

results in only the first row being displayed (see attachment).

This affects RF 3.0 (we use it via PyPot / Python 2.7.11 on darwin and Python 2.7.9 on Linux).

![robotframework 3 0 truncates multiline keyword documentation](https://cloud.githubusercontent.com/assets/23736160/21043263/4f5d557a-bdf6-11e6-9f11-bec30df268c7.png)

**Comment by pekkaklarck** [comment]
Only the first row of the doc is shown in the report. This is on purpose to avoid increasing log file size to include long docs there. I guess we could consider changing the logic so that everything in the first paragraph is included. That would require a new issue and could safely be done only in a major release, though.

**Comment by xanadiu** [comment]
Thanks for the quick reply! I wonder where (at all) the multiline documentation of keywords is supposed to show up if not in the log. Opposed to keywords, the test case documentation is displayed in full length.

I created a new issue (#2491).

**Comment by pekkaklarck** [comment]
Full keyword docs are shown in outputs produced by Libdoc.
