### ISSUE TITLE
Passing list as arguments are treated as multiple arguments for each element in the list

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#1032]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=1032) by cxmadc on 12 Jan 2012_

Environment:
Robot Framework 2.6.1 (Python 2.7.2 on linux2)

Description of the problem:

Passing a list variable as an argument while importing a library do not work, instead it passes multiple arguments for each element in the list variable.

Expected:

A single list variable containing the elements set on robotframework should be passed to the library instead multiple arguments for each element.

**Comment by shivarajshivu** [comment]
Hi All,

I have one robot file which has to contain multiple libraries, i want to pass the library names as command line argument in robot command. How to pass and collect the command line arguments something like list.
