### ISSUE TITLE
Limit visibility of imported resources

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#1041]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=1041) by andreas.brain on 23 Jan 2012_

At the moment resources that are imported somewhere in a test suite, are available for all resources, regardless of the hierarchy.

Explanation of attachment:
The test suite imports two resouce files, "Resource 1" and "Resource 2"
In the keyword "Do something", the keyword "Click Button" is available from both resource files (1a and 2a), although the resource file 1 (in which the keyword "Do something" lives) only imported one of them (1a). 

See <a href="http://groups.google.com/group/robotframework-users/browse_thread/thread/9b8693f8b6b8ca81" rel="nofollow">http://groups.google.com/group/robotframework-users/browse_thread/thread/9b8693f8b6b8ca81</a> for complete discussion

**Comment by pekkaklarck** [comment]
Issue #2417 shows that this problem is continuously annoying users. Changing the import logic as proposed by this issue would be somewhat big and most likely backwards incompatible change. Probably adding keyword visibility modifiers like proposed by #430 would be a better idea.

**Comment by teschnei** [comment]
Could it be possible to have a resource imported privately?  Using the previous example, if resource 1 could "privately" import resource 1a, it would mean that 1a's keywords (Click Button) would be available to resource 1, but not to anything that imported resource 1 (the test suite in this case).  Similarly for resource 2 and 2a, it would resolve the ambiguities between which Click Button keyword to use inside resource 1 and 2.

If this were implemented as a new keyword or an option to `Resource`, then it should be able to maintain backwards compatibility
