### ISSUE TITLE
request new automatic variable ${KEYWORD_NAME}

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#1042]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=1042) by bryan.oakley on 23 Jan 2012_

I think it would be useful for ${KEYWORD_NAME} defined as an automatic variable.

My use case: when developing tests we often stub out a keyword during initial development. The keyword looks something like:

| My new keyword
| | log | Not implemented yet: My new keyword | WARN

We do this so that we can run the test and get a list of warnings for all of the stubbed out keywords. This makes it really easy to create a list of keywords that need to be developed. 

To make development a little easier, it would be nice if we could use a variable in the log message rather than retyping the name. For example:

| My new keyword
| | log | Not implemented yet: ${KEYWORD_NAME} | WARN

**Comment by elpollodiablo** [comment]
I also expected this feature to exist to build some proper automatic & context sensitive logging :/

**Comment by DiazMichael** [comment]
I see the issue is closed, but I was wondering if there is any workaround to get the name of the keyword that is been currently ran?

**Comment by boakley** [comment]
You can use a listener to set the variable in the `start_keyword` method, and unset it in the `end_keyword` method.
