### ISSUE TITLE
Space in path in Run command from OperatingSystem

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#1129]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=1129) by polusok on 14 May 2012_

i've created executable file by following path c:\Program Files\run.bat
then I would like to run it by following code, however it doesn't work

**\* Settings ***
Library           OperatingSystem

**\* Test Case ***
Test
    ${a}    Set Variable    c:\Program Files\run.bat
    Run And Return Rc    ${a}
    Log Variables

Nor this variant

**\* Settings ***
Library           OperatingSystem

**\* Test Case ***
Test
    ${a}    Set Variable    c:/Program Files/run.bat
    Run And Return Rc    ${a}
    Log Variables

Nor this variant

**\* Settings ***
Library           OperatingSystem

**\* Test Case ***
Test
    ${a}    Set Variable    c:${/}Program Files${/}run.bat
    Run And Return Rc    ${a}
    Log Variables

Nor this variant

**\* Settings ***
Library           OperatingSystem

**\* Test Case ***
Test
    ${a}    Set Variable    c:${/}Program${SPACE}Files${/}run.bat
    Run And Return Rc    ${a}
    Log Variables

**Comment by almahaja** [comment]
Adding the command in just a double quotes doesn't work for me.But when i add the double quoted command inside escaped double quotes works.

\""C:/Program Files/am Files/run.bat\"": this works

**Comment by pekkaklarck** [comment]
Everyone should use the `Run Process` keyword from the Process library to avoid problems with escaping altogether.
