### ISSUE TITLE
Need results exported into excel sheet column corresponding to each test case.

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#1169]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=1169) by snehabaid on 2 Jul 2012_

**Explain the new feature or other enhancement idea you have.**

 Robot Framework version=2.6.3, used interpreter=Python and its version=2.6, 
the operatingsystem=windows. 
"Need a new enhancement to export the results of test case execution into excel sheets.
Basically all our test cases are in excel sheets and we create corresponding test scripts for the same,so the end result would be to be able to export the test result to the same excel sheet.
Can this be done?

**Comment by jsivapatha** [comment]
Yes, we should build own tool or utility to convert output xml to excel based on project need.
