### ISSUE TITLE
Allow modifying test tags with `Fail` keyword

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#1218]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=1218) by @spooning on 3 Sep 2012_

When using `Fail` keyword to fail a test case, it would sometimes be useful to be able to modify tests tags. You can already now do that using `Set Tags` or `Remove Tags` before `Fail`, but being able to do that in a one go would be even easier, especially if you are failing the test based on a certain condition.

Prefixing tags with hyphen (e.g. '-regression') ought to be suitable syntax for removing tags. Tags without a hyphen would be added.

Examples:

```
# Fail test case unconditionally and add 'not-ready' tag.
Fail    Keyword not ready    not-ready

# Fail test case based on a condition and remove 'regression' tag.
${env ok} =    Verify test environment
Run Keyword If    not ${env ok}    Fail    Environment not OK    -regression
```

**Comment by nguyenthiphuong2** [comment]
I tried to add tag "regression" to the test-case after it's fail but it did not work. From RIDE i did not see the tag "regression" is added to tags area. Please help me to figure out the issue.
Here is my script
*** Test Cases ***
test
    [Tags]    test
    ${test}    Evaluate    1==2
    Run Keyword If    '${test}'=='False'    Fail    test fail    regression
