### ISSUE TITLE
add run repeat option

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#1232]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=1232) by cloudwingking84 on 16 Sep 2012_

to test aut Stability or script Stability, run scipts many times.
like : pybot a.txt --repeat 10

**Comment by amoxuk** [comment]
why rf3.2.1 is not contains this feature？

**Comment by amoxuk** [comment]
@pekkaklarck Could we discuss this feature agein? 
Through search, I found here are many reqirement for rerun testcase, just like times tag, command-line arg. In fact, we also need to repeat a test case many times in work.
Could'u provide a easy way to rerun test case?

**Comment by pekkaklarck** [comment]
I still believe it's better to handle orchestration like this outside the core framework. The main reason is that there's no single approach for re-executing tests that would work for everyone, and trying to cover all use cases can add lot of complexity. External tools can focus on a single use case and they also can be developed without strict backwards compatibility requirements the core has. For the end user it shouldn't matter is a feature provided by the core or tool you use with it.

The above said, if there would be some generic way to run tests that covers several use cases, it could be included in the core. Even then it would be better to develop such functionality outside the core until the feature set is stable.

If you want to discuss this further, I recommend using our Slack. You could start a discussion on the #devel channel, but if there's interest a dedicated channel could be created for this topic.
