### ISSUE TITLE
Add support for "here document" (heredoc) in tests

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#1245]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=1245) by bryan.oakley on 27 Sep 2012_

There are times when I need to enter long multiline strings in a test. Right now that's not particularly easy.

What I propose is "here document"-like syntax that preserves all whitespace except one leading and trailing newline. 

For example:

```
| Example test case
| | ${result}= | something that returns a multiline string
| | should be equal as strings | ${result} | {{{
This text has precisely
three lines separated with
two newlines
}}}
```

This would require a fairly trivial change to the parser, at the expense of a very tiny backwards incompatibility (tests that might already have a trailing {{{ as the last three bytes on a line)

I recommend supporting at least two sets of delimiters such as {{{ and }}}, and &gt;&gt;&gt; and &lt;&lt;&lt;

If you're concerned about the whole cross platform newline/carriage return issue, you could optionally support the desired separator after the opening delimiter:

```
| | should be equal as strings | ${result} | {{{\r
This text has precisely
three lines separated with
two carriage returns
}}}
```

**Comment by Hubro** [comment]
I would like this issue to be revisited, seeing as it's 6 years old things may have changed.

Also I want to make it clear `Catenate` is *not* equivalent to heredocs, as it doesn't preserve whitespace. For example:

```robot
Delete Endpoint
	${payload} =		Catenate	SEPARATOR=\n
	...	<input>
	...	  <identifier>25c48d1f-f2a4-44f7-a559-c5c0b8d9734e</identifier>
	...	</input>

	${expected-output} =	Catenate	SEPARATOR=\n
	...	<output>
	...	  <result>OK</result>
	...	</output>

	${result} =	Invoke Action	${payload}	inventory/actions/delete-endpoint

	Should Be Equal		${expected-output}		${result}
```

Results in error:

```
Delete Endpoint                                                       | FAIL |
Multiline strings are different:
--- first
+++ second
@@ -1,3 +1,3 @@
-<output>
-<result>OK</result>
-</output>
+<output>
+  <result>OK</result>
+</output>
```

Surely it must be possible to add support for a heredoc syntax without breaking backwards compatibility (?)

What about this syntax?

```robot
Delete Endpoint
	${payload} = <<XML
		<input>
		  <identifier>25c48d1f-f2a4-44f7-a559-c5c0b8d9734e</identifier>
		</input>
	XML

	${expected-output} = <<XML
		<output>
		  <result>OK</result>
		</output>
	XML
```

What I particularly like about this syntax is that it allows giving a hint to the editor as to what syntax highlighting it should use within the string, improving readability. Also it's much less boilerplate than the Catenate workaround.

But even if this syntax is problematic for backwards compatibility, any syntax that allows you to say "all lines between these two lines are a literal string" would be amazing, and even better if leading indentation was automatically removed, as assumed in my example above.

If this was implemented, there should probably be at least two different flavors, one where leading white space is removed and one where the text is untouched. The former flavor is probably preferable in 99.9% of cases as should be the "default", as it would be far more readable and how often do you need to define a string where the entire contents is indented?

Line break issues could be resolved by adding a command line option that controls which line break style is used within heredocs, for example `--heredoc-line-breaks` with the possible values `unix` or `dos`, or alternatively `"\n"`, `"\r"` or `"\r\n"`. The default should be the option used by most people, which I assume is `unix`.

I'm not really attached to any of the specifics in this post, I just really really want a nice and readable way to embed some snippets of XML, JSON or other text inside Robot files.

**Comment by pekkaklarck** [comment]
I can see benefits with heredocs but here are also lot of problems:

- It would require rewriting big parts of the tokenizing logic of the new parser. There are lot of more important features for me to spend my limited time, but someone else can obviously look how big task it would be.

- There aren't that big benefits compared to using `Catenate`. It's true that spaces aren't preserved, but they can be easily escaped with `\` or with `${SPACE}`. For example, the above example could be fixed by using `${SPACE * 2}<result>OK</result>`. When you have lot of spaces that's even more explicit way to mark them than using literal spaces.

- If you need bigger snippets of data such as XML or JSON, it's typically better to have this data in external files and refer to them like `${CURDIR}/result.xml`.

All the above said, having a way to embed data to Robot files would be handy. In addition to supporting data like XML or JSON, it would be convenient to be able to construct tables somehow.
