### ISSUE TITLE
Parsing modules should preserve ellipsis (...) denoting line continuation

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#1272]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=1272) by @pekkaklarck on 6 Nov 2012_

Currently parsing modules combine lines continues with ellipsis. This is means that tools using these modules, e.g. RIDE and Tidy, get the data in different format than originally on disk.

**Comment by pekkaklarck** [comment]
New parser (#3076) ought to support this. Adding to RF 3.2 scope.

**Comment by pekkaklarck** [comment]
This has been implemented by the new parser (#3076). APIs related to parsing are still partly under development, but the underlying lexer can preserve all tokens. This issue can be considered done.
