### ISSUE TITLE
Tidy should split ELSE, ELSE IF, and AND to own rows

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#1273]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=1273) by @jussimalinen on 6 Nov 2012*

Based on issue in ride: <a href="https://code.google.com/p/robotframework-ride/issues/detail?id=1067" rel="nofollow">https://code.google.com/p/robotframework-ride/issues/detail?id=1067</a>

In the Robot Framework 2.74, the Run Keyword If has optional ELSE and ELSE IF arguments. Tidy places these arguments in a single line:
Run Keyword If	'${status}'=='PASS'	Do something	ELSE IF	'${status}'=='FAIL'	Do other thing	ELSE	Fail

It would provide better reading, if tidy could place the these arguments in separate lines:
Run Keyword If	'${status}'=='PASS'	Do something
...	ELSE IF	'${status}'=='FAIL'	Do other thing
...	ELSE	Fail

**Comment by pekkaklarck** [comment]
Pull request #1889 was great otherwise, but it didn't split long lines before ELSE/ELSE IF. For example, 

```robotframework
*** Test Cases ***
Without ELSE
  Run Keyword If  expr  KW 1  1  2  3  4  5

With ELSE
  Run Keyword If  expr  KW 1  1  2  3  4  5  ELSE  KW 2  1  2  3  4  5
```

is currently split like

```robotframework
*** Test Cases ***
Without ELSE
    Run Keyword If    expr    KW 1    1    2    3    4
    ...    5

With ELSE
    Run Keyword If    expr    KW 1    1    2    3    4    5
    ...    ELSE    KW 2    1    2    3    4
    ...    5
```

It's inconsistent that KW 1 is split differently depending is there ELSE (or ELSE IF) after it, and also that KW 1 and KW 2 are split differently in the latter example.

I will fix this inconsistency myself, but I first want to clean up RowSplitter in general. It took me quite long time to understand how the original splitting worked in different corner cases and how new ELSE (IF) splitting fit into the bigger picture.

**Comment by pekkaklarck** [comment]
Commit 49b62d489f9a9d6daf462b10e9dad8b2fbeb1a59 fixes inconsistent splitting of long ELSE (IF) lines. Accidentally started commit message row with `#1273` and git considered that row to be a comment. Anyway, this issue is ready for final review and testing.

**Comment by pekkaklarck** [comment]
One more feature, splitting also AND rows, implemented by bbc7d87b2b70754b506f7027392c25178c129cb7. Also tested that it is possible to avoid splitting from ELSE (IF) and AND used as normal data by escaping them with a backslash in d38090be66cafeec5bd9cf8616661004504ed47a.

Now I promise not to touch this anymore unless someone finds a bug.

**Comment by guykisel** [comment]
@pekkaklarck I apologize, I had not considered those use cases.

**Comment by pekkaklarck** [comment]
@guykisel No worries! Thanks for the PR, this nice feature wouldn't be in 2.8.7 without that.
