### ISSUE TITLE
Built-in variable ${TEST_NAME} not present on a Mac

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#1299]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=1299) by c.martin.taylor on 4 Dec 2012_

This bug occurred with RIDE 0.51 running on Python 2.6.4. on a MacBook Pro running OS X 10.7.4.  I recently upgraded this Mac to wxPython '2.8.12.1 (mac-unicode)'.

As part of my standard Suite Teardown I create a memory usage log file with a file name based on the built-in Robot Framework variable ${TEST_NAME}.  This works fine when running Robot Framework under RIDE on a Windows PC.  However, when I do the exact same test run on a Mac, I get:

FAIL    Non-existing variable '${TEST_NAME}'.

Part of my standard Suite Teardown is to log all variables, the output of which is shown below.  Notice that ${TEST_NAME} is not present but ${PREV_TEST_NAME} and ${SUITE_NAME} are present.

KEYWORD: BuiltIn.Log Variables Expand All
Documentation:  
Logs all variables in the current scope with given log level.
Start / End / Elapsed:  20121204 08:31:00.248 / 20121204 08:31:00.256 / 00:00:00.008
08:31:00.249    INFO    ${/} = /
08:31:00.249    INFO    ${:} = :
08:31:00.250    INFO    ${\n} = 
08:31:00.250    INFO    ${APDOff} = True
08:31:00.250    INFO    ${BufferNavNet} = True
08:31:00.250    INFO    ${Build} = 1222
08:31:00.250    INFO    ${CaptureScreenOnError} = True
08:31:00.250    INFO    ${CaptureScreenOnPass} = False
08:31:00.250    INFO    ${DEBUG_FILE} = /var/folders/9c/qg38_v_d5kd2jygfp8bw2v_c0000gn/T/RIDEFvKete.d/debug.log
08:31:00.250    INFO    ${DevLogLevel} = 3
08:31:00.250    INFO    ${DevTransport} = Any
08:31:00.251    INFO    ${DoVerify} = True
08:31:00.251    INFO    ${EMPTY} = 
08:31:00.251    INFO    ${EXECDIR} = /Users/cmtaylor/_SVN_/Tests/TI-Nspire
08:31:00.251    INFO    ${False} = False
08:31:00.251    INFO    ${Host} = localhost
08:31:00.251    INFO    ${InitialSettings} = Default
08:31:00.251    INFO    ${Instance} = 1
08:31:00.251    INFO    ${IsActivated} = Activated
08:31:00.251    INFO    ${IsDesktop} = False
08:31:00.252    INFO    ${LOG_FILE} = /var/folders/9c/qg38_v_d5kd2jygfp8bw2v_c0000gn/T/RIDEFvKete.d/log.html
08:31:00.252    INFO    ${LogLevel} = -4
08:31:00.252    INFO    ${LogMem} = False
08:31:00.252    INFO    ${LogSerialInput} = True
08:31:00.252    INFO    ${ManualPause} = N
08:31:00.252    INFO    ${MaxDevWait} = 300
08:31:00.252    INFO    ${MaxSerialLines} = 10000
08:31:00.252    INFO    ${NavNetLogLevel} = 3
08:31:00.253    INFO    ${None} = None
08:31:00.253    INFO    ${null} = None
08:31:00.253    INFO    ${NumDevices} = All
08:31:00.253    INFO    ${OS} = Any Windows
08:31:00.253    INFO    ${OUTPUT_DIR} = /var/folders/9c/qg38_v_d5kd2jygfp8bw2v_c0000gn/T/RIDEFvKete.d
08:31:00.253    INFO    ${OUTPUT_FILE} = /var/folders/9c/qg38_v_d5kd2jygfp8bw2v_c0000gn/T/RIDEFvKete.d/output.xml
08:31:00.253    INFO    ${Platform} = Device
08:31:00.253    INFO    ${Port} = 8080
08:31:00.254    INFO    ${PREV_TEST_MESSAGE} = 
08:31:00.254    INFO    ${PREV_TEST_NAME} = 
08:31:00.254    INFO    ${PREV_TEST_STATUS} = 
08:31:00.254    INFO    ${REPORT_FILE} = /var/folders/9c/qg38_v_d5kd2jygfp8bw2v_c0000gn/T/RIDEFvKete.d/report.html
08:31:00.254    INFO    ${Retries} = 3
08:31:00.254    INFO    ${SerialCradle} = False
08:31:00.255    INFO    ${SerialPort} = COM1
08:31:00.255    INFO    ${SPACE} =  
08:31:00.255    INFO    ${StartClean} = True
08:31:00.255    INFO    ${SUITE_DOCUMENTATION} = Test suites for the TI-Nspire product line.
08:31:00.255    INFO    ${SUITE_MESSAGE} = 1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
08:31:00.255    INFO    ${SUITE_METADATA} = {u'Environment': u'Any connected BW &amp; CX CAS Devices', u'Version': u'${Version}.${Build}'}
08:31:00.255    INFO    ${SUITE_NAME} = TI-Nspire
08:31:00.255    INFO    ${SUITE_SOURCE} = /Users/cmtaylor/_SVN_/Tests/TI-Nspire
08:31:00.255    INFO    ${SUITE_STATUS} = FAIL
08:31:00.256    INFO    ${TEMPDIR} = /var/folders/9c/qg38_v_d5kd2jygfp8bw2v_c0000gn/T
08:31:00.256    INFO    ${True} = True
08:31:00.256    INFO    ${Variant} = Dev_CAS
08:31:00.256    INFO    ${Version} = 3.2.0
08:31:00.256    INFO    ${WithACK} = True
08:31:00.256    INFO    @&#8288;{EMPTY} = [ ]

**Comment by Vedashreejp** [comment]
@spooning I am still getting this issue on macOS getting error: Variable '${TESTNAME}' not found. Did you mean: ${PREV_TEST_NAME}. Same works on windows machine.
