### ISSUE TITLE
Introduction to Robot Framework screencast

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#131]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=131) by marcinet on 10 Oct 2008_

Prepare flash demos that would show how to use RobotFramwork, write
testcases, write resource files, use RobotIDE etc. Such demos could be
recorded from live usage, so that the person watching feels as if he/she
was sitting next to the presenting person and watching the screen.
Such flash movies could then be published on the project web.

**Comment by pekkaklarck** [comment]
We have various videos at https://www.youtube.com/RobotFrameworkChannel. I consider this issue done.
