### ISSUE TITLE
Log and Testdoc: Filtering tests by tags

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#1376]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=1376) by Raphael.Castaneda on 25 Feb 2013_

Currently, there is no option for filtering by tags on the testdoc or log pages. Additionally, the tags on the report page can filter by tags, but only a single tag at a time.

A more intuitive approach would be to make the tags on the testdoc and log pages clickable, and allow multiple tags to be clicked to further refine the filter.

I have implemented an example of this using javascript and css.
You can find the source here:

<a href="https://groups.google.com/forum/?fromgroups=#!topic/robotframework-users/pCzxf673Ii0" rel="nofollow">https://groups.google.com/forum/?fromgroups=#!topic/robotframework-users/pCzxf673Ii0</a>

**Comment by pekkaklarck** [comment]
Closing this because there hasn't been interest towards this since 2014 and because report has supported custom search based on tags (#1634) since RF 2.8.4.
