### ISSUE TITLE
Dictionary variable type

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#1450]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=1450) by deville.moodys on 31 May 2013_

It'd like to provide dictionaries (key/value) parameters to several functions of my librairies.
Consequently I'd like to have the possibility to create variables of type "dictionary".
I know it is possible to create such variables in a test case, but it could be more "user-friendly" if we could create them as currently scalar and list variables.
Thanks for your reply
Cheers

**Comment by pekkaklarck** [comment]
Forgot to mention this issue in few commits.

- 681c65e655913bd3b9fe513595be3ff9aa1cc17f added logging dict variable assignment and dict variable recommendations.
- 3da0db92ee9b9de62b4512f017916043043c83b7 implemented support for accessing dict values like `&{dict}[key]`.
