### ISSUE TITLE
"Message content over the limit has been removed" in robot html log files.

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#1499]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=1499) by lishuang990338 on 1 Aug 2013_

Using Robot 2.7.7, Jython 2.6.
There are some errors in the robot testcases we design. But it seems that there robot could not print all the fail log information just as below. I.e., just from 1) to  8) and then from 15) to the last one. 
There is a sentence which given that "[ Message content over the limit has been removed. ]", I don't know what's happened? Is it because the fail log is too long? How long is it for the error logs in the log summary? Is the length configurable? If not, why it omit the middle part and leave the begin and end part? Please find enclosed log for more details. 

Thank you very much!

TEST CASE: FEED6 
Full Name:  Robot.UT.David.FEED-6.FEED6
Start / End / Elapsed:  20130801 15:10:09.142 / 20130801 16:31:48.336 / 01:21:39.194
Status: FAIL (critical)
Message:    Several failures occurred: 1) unually the CMP_NME_ET value of the RIC should be 1, if it not 1, should confirm with Dev: 2 != 1 2) the MC_LABEL value of the RIC not match the dataview result: 2100 != 2101 3) the MC_REC_LAB value of the RIC not match the dataview result: 2100 != 2101 4) unually the CMP_NME_ET value of the RIC should be 1, if it not 1, should confirm with Dev: 2 != 1 5) the MC_LABEL value of the RIC not match the dataview result: 2100 != 2101 6) the MC_REC_LAB value of the RIC not match the dataview result: 2100 != 2101 7) unually the CMP_NME_ET value of the RIC should be 1, if it not 1, should confirm with Dev: 2 != 1 8) unually the CMP_NME_ET value of the RIC should be 1, if it not 1, should... [ Message content over the limit has been removed. ] 15) the MC_REC_LAB value of the RIC not match the dataview result: 2100 != 2101 16) unually the CMP_NME_ET value of the RIC should be 1, if it not 1, should confirm with Dev: 2 != 1 17) unually the CMP_NME_ET value of the RIC should be 1, if it not 1, should confirm with Dev: 2 != 1 18) the MC_LABEL value of the RIC not match the dataview result: 2100 != 2101 19) the MC_REC_LAB value of the RIC not match the dataview result: 2100 != 2101 20) unually the CMP_NME_ET value of the RIC should be 1, if it not 1, should confirm with Dev: 2 != 1

**Comment by shpaker** [comment]
Maybe should make this limit changeable without changing robot's source files?
