### ISSUE TITLE
merging of xml files 

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#1587]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=1587) by otlasanju on 26 Nov 2013_

Hi

I have a huge number of xml files generated out of individual test runs ,when i use rebot to combine them in to single output.xml file, the resulting file is cluttered,the child suites are considered as seperate testsuites and for each testcase a detailed statistics is presented which makes the log file look cluttered ,The reports are perfectly fine when run through RIDE (Attached are the files for your reference) .

Can any one give me hints towards merging of these xml files neatly ,I am currently looking at the source code of rebot.py but i am unable to follow what exactly is happenig with the code , the other option i would have is to write a custom script to merge the xml files seperately and parse it with rebot.

Any hints is highly appreciated

Regards
sanjay

**Comment by pekkaklarck** [comment]
Heh, after I closed this issue in Nov 2013, I opened very similar issue #1615 in Dec 2013 and `--merge` option was added to Rebot in RF 2.8.4. This issue is thus actually done.

**Comment by pekkaklarck** [comment]
Actually it was #1687 (RF 2.8.6) that introduced the general `--merge` functionality. #1615 only added `--rerunmerge` that was later generalized to `--merge`.

**Comment by dhoomakethu** [comment]
Thanks for the new option , we were using our own custom script for this all this time!
