### ISSUE TITLE
Variable assignment should not be part of keyword name with --removekeywords, in logs, in listener interface, or in other APIs

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#1611]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=1611) by kormbrek on 16 Dec 2013*

Given this line in a test,
${foo}=    Create Variable    bar
In order to remove the keyword using an exact match, the assignment portion is considered part of the keyword name, so something like this must be used:
    --removekeywords ${foo}=BuiltIn.CreateVariable
Where one would expect this to work:
    --removekeywords BuiltIn.CreateVariable
but it does not match.
I cannot think of a realistic use case where the assignment portion should be considered part of the keyword for --removekeywords.

Also since the matching is against the full keyword names, this example is misleading:
    pybot --removekeywords name:HugeKeyword --removekeywords name:resource.* tests.txt

It should have a library name like this:
    pybot --removekeywords name:MyLibrary.HugeKeyword --removekeywords name:resource.* tests.txt

**Comment by pekkaklarck** [comment]
As #1951 explains, this change needs to be done also in the listener interface.
