### ISSUE TITLE
Add option to remove keywords information from testdoc

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#1625]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=1625) by frankbp on 14 Jan 2014_

Now with testdoc the highest level of keywords information will be shown on the output file by default, it would be nice to have such option to totally remove the keywords but just keep the test name and/or documentation so that users can get even higher level view of the test repository. And in that case maybe no need to group the tests, just expand all.

**Comment by pekkaklarck** [comment]
No interest related to this in several years. Closing.
