### ISSUE TITLE
Support more general merging results with Rebot

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#1687]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=1687) by filip.noetzel on 24 Mar 2014_

Hey,

first, some background:

We're using RF to run selenium with ~100.000 test cases across 6 browsers. Obviously, that would take a while if we were to execute them in series. To speed things up, we're using Jenkin's matrix build ability to run test 1-1000 in on job, 1001-2000 in the second job, etc. After all individual jobs have run, we'd like to generate a report that looks _as if_ the tests were executed in series (i.e. parallelisation happens transparently).

second, here's a reduced test case 'split_testcases.robot':

**\* Testcases ***

Testcase A
    Log        A

Testcase B
    Log        B

When run like

$&gt; pybot split_testcases.robot

one gets a report that has the following hierarchy:

Split Testcases
- Testcase A
- Testcase B

However, when run like this:

$&gt; mkdir run{1,2}
$&gt; pybot --outputdir run1 --test 'Testcase A' split_testcases.robot
$&gt; pybot --outputdir run2 --test 'Testcase B' split_testcases.robot

.. and combined with

$&gt; rebot run{1,2}/output.xml 

i get a report that has this hierarchy:

Split Testcases &amp; Split Testcases
- Split Testcases
  - Testcase A
- Split Testcases
  - Testcase B

I tried using --rerunmerge, but that fails because the test reports contain disjoint testcases, am I missing a command line flag ?

I think I was able to adapt merger.py posted in <a href="https://code.google.com/p/robotframework/issues/detail?id=1615" rel="nofollow">https://code.google.com/p/robotframework/issues/detail?id=1615</a> to create a merged result that resembles my wanted output, simply by removing the check. I think I can work with that for now. However, such functionality sounds useful to other RF users.

Thanks again for Robot Framework :)

**Comment by simplyviks** [comment]
Hi,

i have a requirement where i need to break a single testcase in multiple in report.xml.

i have a testcases A(Scenarios A)under suit A.
now in this testcase A i am covering many more testcases say A1,A2..

but in the report as expected the testcase count is 1.

Expected report.xml in my case.

for example.
total test case:3(A+A1+A2)
passed:2
failed:1
how do i achieve this??

do i need to write a custom result writer and rebot script??

any leads is appreciated,Thanks in advance.
failed:1

**Comment by glgv** [comment]
Hi,

I am also having the same requirement as 'simplyviks' posted here. I need to generate multiple logs by splitting the log file from one testcase run. 

Any pointers are greatly appreciated. Thank you.

**Comment by simplyviks** [comment]
I tweaked the counting logic.though that's not the best solution.

**Comment by mkorpela** [comment]
I think you should use tags for reporting purposes (requiremetents etc.)  instead of counting test cases.
You can cover multiple tags with one test case and dynamically add and remove tags during test execution. Use "BuiltIn.Set Tags" and "BuiltIn.Remove Tags".

**Comment by glgv** [comment]
Hi, Thanks for sharing your comments.

@simplyviks, can you share how you tweaked the counting. In my case i'm using dummy testcases for getting the count and pass/fail result addressed. But for that dummy testcase, i also need to associate the respective log which is a snippet of the full log run in one major testcase. Are you also getting the log seperately?

@mkorpela, I am able to set/remove tags for sections of codes under same testcase. But i am unable to get seperate log files based on the tags. I tried rebot with different options like '--tagstatexclude', '--removekeywords tag:<MYTAG>' but with no luck. Is there a way i can extract logs for only the code part which is under defined TAG?

Thanks again.
