### ISSUE TITLE
Telnet.Write skips output results

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#1697]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=1697) by a3axapov on 18 Apr 2014_

Telnet.Execute Command and Telnet.Write skips all output data until receives _newline and only the rest of output will be stored in the result

Only usage of Telnet.Write Bare will help.

Robot Framework 2.8.4 (Python 2.7.5 on win32)

Example:
newline=CRLF
${result}=  Telnet.Execute command    help

OUTPUT:
supported commands:
\n
\r  quit - close connection
\r  help - print help information
\n
\r\n
PROMPT$

The ${result} will contains only PROMPT$

**Comment by GPCExplorer** [comment]
Something that worked out for me is adding an extra parameter on the **write** method for cases in which there's no echo from the server but for some reason the expected output has a part with the definition of newline.
```
def write(self, text, loglevel=None,dirty=False):
    newline = self._get_newline_for(text)
    if newline in text:
        raise RuntimeError("'Write' keyword cannot be used with strings "
                           "containing newlines. Use 'Write Bare' instead.")
    self.write_bare(text + newline)
    # Can't read until 'text' because long lines are cut strangely in the output
    if not dirty:
        return self.read_until(self._newline, loglevel)
```
