### ISSUE TITLE
Initialize or Start listener method

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#1699]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=1699) by jtbnnt on 24 Apr 2014_

There are several listeners that I utilize which need to scrape certain information from the command line to alter its execution down the line. It would be nice to have a Start or Initialize Listener method that's called before start_suite of the first test but after command line arguments have been handled and variables are accessible by BuiltIn. 

Currently I use a one time boolean flag in start_suite to accomplish this, but I believe a dedicated method would be cleaner and more consistent with the framework.

**Comment by pekkaklarck** [comment]
The earlier issue requesting this was #722.
