### ISSUE TITLE
data-driven test with no arguments throws an error

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#1717]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=1717) by bryan.oakley on 23 May 2014_

If I create a data-driven test but don't give each test case any arguments, I get the error "Test case contains no keywords". Technically this is not true since I do actually have a keyword. If I add a dummy argument, it works as expected.

For example, the following suite will fail:

```
*** Settings ***
| Library | Dialogs
| Test Template | Perform manual step

*** Test Cases ***
| Go to the fridge and grab a beer

*** Keywords ***
| Perform manual step
| | Execute Manual Step | ${TEST_NAME}
```

To make the suite pass I can give the keyword and test a bogus argument:

```
*** Test Cases ***
| Go to the fridge and grab a beer | bogus

*** Keywords ***
| Perform Manual Step | [Arguments] | @&#8288;{args}
| | Execute Manual Step | ${TEST_NAME}
```

I think a data driven test should be able to be written without requiring arguments.

**Comment by kahirrao** [comment]
Getting  error message test case contains no keyword 


*** Settings ***
Library    SeleniumLibrary
*** Variables ***
${url}     https://accounts.google.com/
*** Test Cases ***
TC001_Browser Start and Close
Open Browser   ${url}     Chrome==============================================================================
TC001 Start Close Browser                                                     
==============================================================================
TC001_Browser Start and Close                                         | FAIL |
Test case contains no keywords.
------------------------------------------------------------------------------
TC001 Start Close Browser                                             | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed

Please Help
