### ISSUE TITLE
 Facing [ ERROR ] Execution stopped by user without any hint for user what happened

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#1723]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=1723) by ram31886 on 31 May 2014_

I am facing the following error while running pybot from 32bit linux.
I want to know the exact reason why this happens and any means of more informations on these errors will help.

**Comment by thedog2y** [comment]
when i run ride ,at the cases those in some suites, test work break with error:  [ ERROR ] Execution stopped by user.
but use the same cases, put in other suites, everything will be ok
i am using robotframework 3.0.2 and ride 2.0a1

**Comment by HelioGuilherme66** [comment]
@thedog2y You are using a non-official version of RIDE. (And you should use the "abandoned" issue tracker at [here](https://github.com/robotframework/RIDE) )
The library you mention is inside RIDE package, so it may conflict with current robotframework.
In my fork I have updated the package to use newest robotframework API. You could try this unofficial fork/branch with:
`pip install -U https://github.com/HelioGuilherme66/RIDE/archive/python3.zip`

It will be version 1.7.1.
