### ISSUE TITLE
Standard libraries should not be importable in Python w/o `robot.libraries` prefix

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#1737]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=1737) by datakurre on 24 Jun 2014*

given robotframework 2.8.5

when I'm running a test for product, which imports the "Zope2 DateTime" library <a href="https://pypi.python.org/pypi/DateTime" rel="nofollow">https://pypi.python.org/pypi/DateTime</a> (which has existed longer than Python's built-in datetime)

then I get various errors, because robotframework.libraries.DateTime gets imported instead

* * *

Currently, the only workaround is to use &lt; 2.8.5.

Is is too late to rename the DateTime-library to not conflict with a popular existing library?

If it's too late to rename, is there a reason, why robot/pythonpathsetter.py adds robotframework dirs into the very beginning of sys.path instead of to the bottom?

**Comment by pekkaklarck** [comment]
This was implemented by a9d6e37b3537279f21f66986f0fe347dcda45fc9.

@datakurre, hopefully you can soon start to use the latest and greatest Robot version for testing Plone. This fix will be part of RF 2.9 alpha 1 that hopefully is ready next week.

**Comment by datakurre** [comment]
@pekkaklarck Good to know! Thanks for fixing this.
