### ISSUE TITLE
Support for Gherkin .feature files

### ISSUE THREAD

**Issue by njagadee** [robotframework/robotframework#1755]
We have many Gherkin scenarios written in the standard .feature file format. Can Robot Framework work with .feature files like other BDD frameworks do? It would be of great help if it does as we can be consistent in the way we write Gherkin scenarios no matter what BDD framework we use. That's the only limitation we have with using Robot Framework.

**Comment by joasilva** [comment]
Hi Pekka, just to make sure: is Robot still not supporting Gherkin .feature files? 

Cheers, João.

**Comment by pekkaklarck** [comment]
Yeah, Robot doesn't support exactly same syntax that Cucumber does. You can write similar tests, though.
