### ISSUE TITLE
Add public API to get allowable arguments

### ISSUE THREAD

**Issue by boakley** [robotframework/robotframework#1763]
It would be nice if there were a public API to get a list of valid pybot (and/or libdoc and rebot) arguments. This would make it possible to write tools that can validate argument files, or highlight them appropriately in a text editor.  

After a whole lot of digging I finally figured out I could get them this way:

    from robot.run import USAGE
    import robot.utils
    ap = robot.utils.ArgumentParser(USAGE)
    print ap._long_opts
    print ap._short_opts

Obviously, I can't rely on the private variables, plus that seems like a rather convoluted way to get the data. It would be nice if there were a public interface, such as something like this, perhaps:

    from robot.pybot import options
    print options.long
    print options.short

The public interface makes it possible to make use of the information without being tightly coupled to how robot manages the options internally.

**Comment by pekkaklarck** [comment]
No interest since 2014. Closing.

**Comment by boakley** [comment]
What do you mean "no interest"? I'm still interested. I don't know why I didn't respond two years ago, but I still would like to see this feature implemented. Being able to write a tool that can validate argument files would be very useful. If I had a way to get a list of arguments, and perhaps a simple regex or flag that denotes whether it takes a value or not, it would make writing such tools so much easier.

**Comment by pekkaklarck** [comment]
With "no interest" I meant that there were no answers to my question in two years. I don't have anything against this functionality but don't have need for it in the foreseeable future.

In general I don't want this tracker to be full with issues that would be nice but nobody needs them badly enough to actually do something about them. Instead I rather close them, and in the future I plan to do that even more aggressively than earlier. Issues can be reopened, or new issues submitted, if someone actually starts implementing a feature.

**Comment by boakley** [comment]
Just to clarify: you no longer want feature requests unless they are part
of a pull request?

**Comment by pekkaklarck** [comment]
Yes and no. In general all feature requests are fine, but I don't think it is worth keeping requests open for years if nobody is going to ever do anything for them. This is especially true for issues only a limited set of users. Having too many open issues in the tracker is a problem in itself. Issues can be easily reopened or new issues submitted if needed.

**Comment by pekkaklarck** [comment]
All the above said, we can open this issue if you think this would be a nice enhancement in RF 3.1 (needed API changes are too big for a minor release) and would be willing to work with it.
