### ISSUE TITLE
Listener interface should be able to alter keyword, test and suite status

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#177]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=177) by @pekkaklarck on 10 Dec 2008*

[ For more information about listener interface, see
<a href="http://robotframework.googlecode.com/svn/trunk/doc/userguide/RobotFrameworkUserGuide.html#using-listener-interface" rel="nofollow">http://robotframework.googlecode.com/svn/trunk/doc/userguide/RobotFrameworkUserGuide.html#using-listener-interface</a>
]

After enhancing listener interface to that methods get more information
(<a class="closed_ref" href="https://code.google.com/p/robotframework/issues/detail?id=88" title="Listener interface methods need more information about suites, tests and keywords"> issue 88 </a>) we should allow listener methods also to alter keyword, test and
suite status. The idea in <a class="closed_ref" href="https://code.google.com/p/robotframework/issues/detail?id=88" title="Listener interface methods need more information about suites, tests and keywords"> issue 88 </a> is to pass a dictionary with
documentation, status, tags, etc. to listener methods. We can make this
communication two-way so that if listener methods alter the dictionary
these changes are stored to actual keyword, test and suite instances. 

This mechanism would, for example, make following use cases possible:

1) end_test method could change test status to FAIL if it e.g. took too
much time.

2) end_keyword could change the keyword status to PASS if it wanted test
execution to be continued. It could store the error (or errors if multiple
keywords fail) internally, and end_test could then set the test status to
FAIL with appropriate error message. This would make it possible to
implement ContinueOnFailure (<a class="closed_ref" href="https://code.google.com/p/robotframework/issues/detail?id=137" title="Support continuing test execution regardless of failures"> issue 137 </a>) using listener interface.

3) start_test and start_keyword could set test/keyword status to PASS or
FAIL which would mean that that test/kw wouldn't be actually executed. This
would allow implementing "PASS keyword" (<a class="closed_ref" href="https://code.google.com/p/robotframework/issues/detail?id=174" title="New BuiltIn keyword to stop text execution with PASS status"> issue 174 </a>).

4) start_test/end_test could add tags to test cases based e.g. on failure
message, execution time, current date, ...

**Comment by pekkaklarck** [comment]
We have decided to implement a new listener API that gets real model and result objects as arguments (#1208) in RF 3.0 or possibly even in RF 2.9.x. That API makes it easy to alter execution status. Enhancing the old listener API to support that doesn't thus bring much benefits. Closing this issue as wontfix.
