### ISSUE TITLE
Remote Built-In library exception

### ISSUE THREAD

**Issue by flysun28** [robotframework/robotframework#1777]
Robot Framework 2.8.5 (Python 2.7.5 on win32)
RIDE 1.3

Problem:
While executing cases on Win7 Client, and using Remote library to call processes on Linux Server, it will occasionally occur exceptions like: FAIL  <type 'exceptions.AttributeError'>:'file' object has no attribute 'getvalue'
I really don't realize what happended at that time, and because it's not reproducable each time but just occasionally, could you please help to investigate into this exception?

**Comment by kasun0215** [comment]
Hi pekkaklarck and flysun28 ,

The PythonRemoteServer is a single-thread server, after i changed it to a multiple-thread server, i also met this issue, was there any solution for this issue? Thanks

from SimpleXMLRPCServer import SimpleXMLRPCServer
from SocketServer import ThreadingMixIn
class ThreadXMLRPCServer(ThreadingMixIn, SimpleXMLRPCServer):
    pass
...

class StoppableXMLRPCServer(ThreadXMLRPCServer):
    allow_reuse_address = True
    def __init__(self, host, port):
        ThreadXMLRPCServer.__init__(self, (host, port), logRequests=False,
                                    bind_and_activate=False)
