### ISSUE TITLE
For-loop "IN KEYWORD" (also with Python generators?)

### ISSUE THREAD

**Issue by edbrannin** [robotframework/robotframework#1788]
Much like we can currently make a for-loop [`IN RANGE`](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#for-in-range), it would be nice if we could loop `IN KEYWORD`.

It is my hope that this would also let us power a for-loop with a Python-defined keyword that's actually a generator function.

```
# FooLibrary.py
def trivial_range_example(arg):
    for x in xrange(arg):
        yield x

# Robot Suite
Library     FooLibrary

*** Test cases ***
Test My Keyword
    :FOR    ${x}     IN KEYWORD    Trivial Range Example    5
    \     Log    ${x}
```

This could be especially helpful with [for-loop-based Templated tests](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#templates-with-for-loops).

**Comment by pekkaklarck** [comment]
I don't think FOR IN KEYWORD is a good idea. Running a keyword first and then using its return values as for loop parameters is simple enough. That way it is possible to use different for loop flavors, not only the standard for loop. This is especially important when RF 2.9 will get new FOR IN ZIP and FOR IN ENUMERATE loops (#1952).

Additionally, for loops support generators already now. It's possible to assing an returned generator to a variable and then use it as a list variable in for loop parameters. The generator will be exhausted when the list variable is evaluated.
