### ISSUE TITLE
Contribution instructions

### ISSUE THREAD

**Issue by jussimalinen** [robotframework/robotframework#1805]
We should have CONTRIBUTING.md or similar instructing on how to contribute to the project.

**Comment by pekkaklarck** [comment]
We are creating alpha 2 today. After that getting contribution guidelines released is my highest priority.

**Comment by jussimalinen** [comment]
...and now moving to rc1..

**Comment by pekkaklarck** [comment]
I've merged PR #1805 by @guykisel and enhanced the initial guidelines considerably afterwards. Review by @jussimalinen, @guykisel and everyone else would be great. As a non-native English writer comments about used language are highly appreciated. Comments can be added to the individual commits or left here, and with larger changes PRs are probably the best approach.

I plan to proofread this myself once more before making RF 2.9 rc 1 tomorrow. Documentation changes are possible also after it.

**Comment by guykisel** [comment]
Looks pretty good! The enhancements are very helpful. Left a few comments on one of the commits with minor typo fixes.

**Comment by pekkaklarck** [comment]
Thanks a lot for the review @guykisel! Fixed the issues you found and also enhanced guidelines a little afterwards. I think this issue can be considered done. That obviously doesn't mean we couldn't enhance the guidelines in the future.

**Comment by laurentbristiel** [comment]
Thank for the work guys!
I did a quick review of the doc and found 2 typos.
Created https://github.com/robotframework/robotframework/pull/2066 to fix them.
