### ISSUE TITLE
Support for multiline comments

### ISSUE THREAD

**Issue by atcarmo** [robotframework/robotframework#1825]
Hi,

Currently it is only possible to make comments using the "#" syntax. It whould be very usefull if we could have multiline/block comments, like Java or C++ (or any other syntax):
/*
Ignore
these
lines
*/

And why this is usefull? The basic reason is obvious: I may have a large comment and I may want to split it in multipline lines. But there is other reason: if I need to comment a large number of LOC (actual Robot framework keywords) to ignore them for any reason, we should be able to comment them without having to comment line by line (yes, I know that IDEs and text editors make it easy). Every programming language or scripting language has its multiline comment syntax, I it would be great if Robot Framework could have its own.

Thanks in advance

**Comment by pekkaklarck** [comment]
No interest since 2014. Closing.

**Comment by Sergix555** [comment]
Hi there!
As I looked for. there is no multiple comment.
If I use # it is added/moved  to the previous code line (Why?).
Though, how  I can make comment to some part of RFW code?
