### ISSUE TITLE
Rebot merger is not working with different test suites

### ISSUE THREAD

**Issue by email2vimalraj** [robotframework/robotframework#1827]
I have two test suites:

**TestSuite1.robot**

``` python
*** Test Cases ***
Test Case 1
     Log  Test Case 1
```

**TestSuite2.robot**

``` python
*** Test Cases ***
Test Case 2
    Log  Test Case 2
```

Steps to reproduce:
1. Run: _pybot --timestampoutputs TestSuite1.robot TestSuite2.robot_
2. Then again  run only the TestSuite1: _pybot --timestampoutputs TestSuite1.robot_
3. Now run: _rebot --merge output-*.xml_

and getting the following error:

``` python
[ ERROR ] Cannot merge outputs containing different root suites. Original suite is 'TestSuite1 & TestSuite2' and merged is 'TestSuite1'.

Try --help for usage information.
```

I am expecting that the 2nd run of TestSuite1 should merge with the 1st run of TestSuite1.

**Comment by ghilainm** [comment]
I encounter the same issue here. I have two test suites, test case only failing for the first one, so the second report is not containing any test from the second one, so merge fails.
