### ISSUE TITLE
Rebot crash when parse output.xml

### ISSUE THREAD

**Issue by mmenchinelli** [robotframework/robotframework#1833]
We are using robot (2.8.1 very close to upgrade to 2.8.6) to test embedded system.
We have several stability tests that is running for days. The results are very big xml files (aprx 5G each one).

When rebot is parsing the output.xml to generate the log crash due to "Segmentation fault (core dumped)".

We are using a 64 bits PC with 16Gb of ram memory.
Looking the "top" command in the PC I have seen that the rebot is allocating memory incrementally up to 19% of RAM PC.

In system log I can see the following:
Oct 20 17:02:12 jubilo kernel: [11363.311489] rebot[4096]: segfault at 0 ip b6e9cd65 sp bf9bbbf0 error 6 in _elementtree.so[b6e99000+b000]

**Comment by pekkaklarck** [comment]
No new information lately, closing. We definitely are interested in enhancements related to parsing, so please submit a new issue if you have time to investigate this further and find something interesting.
