### ISSUE TITLE
Allow giving a custom name to keywords implemented using the static and the hybrid APIs

### ISSUE THREAD

**Issue by hellmanj** [robotframework/robotframework#1835]
Spawned from #1818:

> We add a support to give a custom name to keywords implemented using the static and the hybrid APIs. Dynamic libraries do not need this functionality because they already now can use whatever names they want.

> In practice functions/methods can have custom robot_name attribute that contains the name Robot should use. A separate issue needs to be submitted about this. Part of that issue is implementing a decorator that makes setting the attribute easy and clean. Details like where that decorator live (e.g. robot.utils.somewhere or robot.api.somewhere) can be discussed later as part of that issue.

Notes:
* add `name = getattr(method, 'robot_name', name)` before https://github.com/robotframework/robotframework/blob/master/src/robot/running/testlibraries.py#L180
* make sure LibDoc works with the change (with explicit test)
* need tests for both static and hybrid APIs

I should have time to implement this with @frishberg's help.  Does anyone have a preference for where the decorator lives?

**Comment by pekkaklarck** [comment]
RF 2.8.7 has been delayed do to family and holiday reasons. We want it out ASAP, and think this enhancement can wait until RF 2.9. This enhancement alone won't provide much benefits anyway, it's more of precondition for embedded arguments support in library keywords (#1818).

@hellmanj: It would be great if you could take a look at the comments to pull request #1835. I'm willing to merge it once it's ready, we got RF 2.8.7 out of the door, and can start looking at RF 2.9. Having it merged in the early phase of RF 2.9 development gives more time to implement more complex #1818.

**Comment by hellmanj** [comment]
Sure, I should be able to make some time this week or next to address the comments.

**Comment by pekkaklarck** [comment]
PR #1835 is not ready otherwise but we need to agree what is a good name and signature for the new decorator. Currently it is `robot_name(custom_name=None)`, but I started to thing `keyword(name=None)` would be better. What do others think about this?

**Comment by pekkaklarck** [comment]
We could also consider to support using the decorator without arguments when it's used as a marker:

```python
@keyword
def function(args):
    # ...
```

That shouldn't require more than this (plus some tests):

```python
def keyword(name=None):
    if callable(name):
        return keyword()(name)
    # old code here
```

**Comment by hellmanj** [comment]
Pretty neat, that's fine with me, this makes it more extensible too if we want to add other parameters later.

**Comment by hellmanj** [comment]
In fact, do you want to have a separate `is_robot_keyword` attribute always added instead of overloading `robot_name`?

**Comment by pekkaklarck** [comment]
I think it's enough to have robot_name.

Sent from my mobile.
21.1.2015 18.18 kirjoitti "Jared Hellman" <notifications@github.com>:

**Comment by pekkaklarck** [comment]
This functionality was implemented by PR #1844 by @hellmanj that was merged in 4274448ed2388f6c689a5c12e95c92f91f1feb5a. I'll still add some more tests, partly so see how this works in practice myself, before closing this issue.

**Comment by pekkaklarck** [comment]
I consider this issue done after test fixes and enhancements in commits above and API doc enhancements in 6d09db213b62c4f920a842df08a86e0dddad1b6c.

Thanks again @hellmanj! Looking forward to #1818. Let me know if you want to discuss it in IRC or elsewhere.

**Comment by hellmanj** [comment]
Sounds good, I plan to start work on it soon. Thanks again for the PR help!
