### ISSUE TITLE
Support using floats in FOR IN RANGE loop

### ISSUE THREAD

**Issue by nicolae-chedea** [robotframework/robotframework#1850]
Test steps: 
:FOR	${temperature}	IN RANGE	-40	86	11.5
          log ${temperature}

Expected results:
-40; -28.5; -17; -5.5 ...
Actual results:
-40; -29; -18; -7 ...

**Comment by pekkaklarck** [comment]
I merged pull request #1852 that contained the original implementation in 169e095b24cea207a75a1e463d320094668d0c06 and did some clean-up and added tests in ec787b86c48b19401a6c9fca788f1c3e617f5fa9. Combined changes can be seen in merge commit e3242ef2f68b1c3be75811616dac753fe236dfab.

Everything looks good to me now, but @jussimalinen will do one last round of review.

**Comment by jussimalinen** [comment]
Looks good. Cheers!

**Comment by pekkaklarck** [comment]
Thanks @nicolae-chedea for the pr! Let us know if you got any comments about the latest changes. Would also be great if you could test them in real-life.

**Comment by nicolae-chedea** [comment]
Thank you for your patience. It was a very educational experience for me. I looked over the changes you made and they are definitely an improvement.
