### ISSUE TITLE
[BUG] --test argument is not working when more than one suite specified

### ISSUE THREAD

**Issue by marc-** [robotframework/robotframework#1855]
When run robot with --test option and more that one test suite specified, robot can not find that test.
For instance: 

```
$ pybot --outputdir output --test Suite2.Suite2.MySuite.MyTest suite1 suite2
[ ERROR ] Suite 'Suite1 & Suite2' contains no tests named 'Suite2.Suite2.MySuite.MyTest'
```

Please note test name `Suite2.Suite2.MySuite.MyTest`. This how it appears in reports when several suites are specified.

Same for:

```
$ pybot --outputdir output --test Suite2.MySuite.MyTest suite1 suite2
[ ERROR ] Suite 'Suite1 & Suite2' contains no tests named 'Suite2.MySuite.MyTest'
```

Though

```
$ pybot --outputdir output --test Suite2.MySuite.MyTest suite2
```

works as expected.

This issue also affects `--rerunfailed` option:

```
-R --rerunfailed output  Select failed tests from an earlier output file to be
                          re-executed. Equivalent to selecting same tests
                          individually using --test option.
```

Tested on versions 2.8.5, 2.8.6 (Python 2.7.8, linux) .

**Comment by rickrribeiro** [comment]
Worked for me using --name Example! Thank you very much @pekkaklarck . I spent hours trying to resolve this problem!
