### ISSUE TITLE
Alternative to test case iteration

### ISSUE THREAD

**Issue by jaimefneis** [robotframework/robotframework#1856]
I have implemented an iteration for testcases in the framework core and I'd like your opinion if it is an acceptable solution. Tanks.

Ex:
MyTestCase.txt
**\* Settings ***
Test Template   My test case

**\* Test Cases ***
:ITER   5       My test case    Hello world!

**\* Keywords ***
My test case
    [arguments]     ${msg}
    Log     ${msg}
# Result:
# MyTestCase                                                                    
## My test case 5                                                        | PASS |

MyTestCase                                                            | PASS |
5 critical tests, 5 passed, 0 failed
#5 tests total, 5 passed, 0 failed

Solution:
in file parsing/datarow.py
class DataRow(object):

  def dedent(self):
        datarow = DataRow([])
        if self.starts_iter():
            datarow.cells = self.tail[2:]
        else:
            datarow.cells = self.tail
        datarow.comments = self.comments
        return datarow

  def starts_iter(self):
        if self.head and self.head.startswith(':'):
            return self.head.replace(':', '').replace(' ', '').upper() == 'ITER'
        return False

in file parsing/tablepopulators.py
class _TestCaseUserKeywordPopulator(Populator):
  def add(self, row):
        if row.is_commented():
            self._comment_cache.add(row)
            return
        if not self._test_or_uk:
            if row.starts_iter():
                for i in range(1, int(row.cells[1])+1):
                    self._test_or_uk = self._test_or_uk_creator(row.cells[2] + " " + str(i))
                    dedented_row = row.dedent()
                    if dedented_row:
                        self._handle_data_row(dedented_row)
                return
        self._test_or_uk = self._test_or_uk_creator(row.head)
        dedented_row = row.dedent()
        if dedented_row:
            self._handle_data_row(dedented_row)

**Comment by mahakmalik** [comment]
i want to execute my testcases n number of times. What to do?

**Comment by schinckel** [comment]
As a counter-point, Python unittest implemented subTest at some point, and it made writing loops in tests feasible (because you could iterate, and collect failures independently). That made writing some tests much more succinct.

**Comment by sanjaykolar** [comment]
As part of longevity testing I need to repeat same test case for hours/days which required to repeat the test case n number of time. 
How do we achieve that in robot? I feel a feature to repeat particular test cases really a very good feature to have.

**Comment by simplyviks** [comment]
One important use case.

In a single run i want to test two different plugins of different versions.
i don't want to run it differently because of time and resource constraint.

Running them on same runs gives me more time saving in CI pipeline. 

How do we handle this.?
