### ISSUE TITLE
Running python -m robot.run gives No module named robot error

### ISSUE THREAD

**Issue by anatighe** [robotframework/robotframework#1857]
I'm trying to install Robot Framework on a new Mac. I installed Python2.7 --framework and wxmac3.0 with Homebrew, and used pip to install robotframework. I get this error when trying to run robot:

$ python -m robot.run
/usr/bin/python: No module named robot

Tried adding a specific path and --version, not sure what is going on. I'm not sure if it's an issue with wxmac3.0? Not sure if it's a good idea to go back to 2.9 or if that will even fix it.

**Comment by Umesh2Patel** [comment]
I am getting same issue when i running command 
> robot test.robot
\miniconda3\python.exe: No module named robot.run

only thing I changed is i deleted some extra conda env.

**Comment by Umesh2Patel** [comment]
I updated the script miniconda3\Scripts\robot.bat to forcely find the run.py changing script.  As i got frustrated with this issue. It worked for me to run the robot tests.

**@echo off
cd c:\users\ume\application\miniconda3\Lib\site-packages
python -m robot.run %* **

**Comment by pekkaklarck** [comment]
@Umesh2Patel You may have encountered a variation of #2529. That problem shouldn't occur anymore with RF 3.1 when we use `robot.exe` instad of `robot.bat` (#2415 ).
