### ISSUE TITLE
Provide data-driven test case parameters from external file

### ISSUE THREAD

**Issue by mgrijalva** [robotframework/robotframework#1858]
We are currently trying to utilize data-driven testing using test templates in Robot. The issue is robot requires test case parameters to be hard-coded in the input file in some way. It is much easier for us to manage large test sets by storing the data in something more readable like a CSV file. It's relatively simple to build a quick and dirty python script that would generate the robot test file on-the-fly before running it, but this seems like something that could potentially be built directly into Robot

CSV File:

```
title,message
test case 1,hello world!
test case 2,this is a test
```

Robot test file:

```
*** Settings ***
Library  MyLibrary
Test Template  My Test Template

*** Test Cases ***
test_cases.csv

*** Keywords ***
My Test Template  [Arguments]  ${message}
  Log  ${message}
```

Generated Robot test file:

```
*** Settings ***
Library  MyLibrary
Test Template  My Test Template

*** Test Cases ***  message
test case 1         hello world!
test case 2         this is a test

*** Keywords ***
My Test Template  [Arguments]  ${message}
  Log  ${message}
```

**Comment by ayush235** [comment]
Can you please explain how the robot framework read test_cases.csv ?

**Comment by loadofwar** [comment]
Mark

**Comment by vinaybond** [comment]
This is already closed a long time back. But do have anything like @mgrijalva has mentioned. If not CSV then TSV, XMS or any other row/col format to read, which will generate TestCase on the fly as opposed to the hardcoded values right now. TestNG provides the same using [DataProvider ](https://4.bp.blogspot.com/-pH6I0LBNY7k/U3JIRb6HLKI/AAAAAAAAA40/HtDG0caKnsI/s1600/@DataProvider+annotation+result.PNG) and execute method as many time as many rows in the file. I think we should provide a way to do that in Robot, Be it a single way as @pekkaklarck  mention but a provision will be helpful and add vary useful feature in robot

**Comment by pekkaklarck** [comment]
As I've commented earlier, I don't think we can come up with a generic system how to read external data that would work in all or even most cases. Much better to have such functionality outside the core so that it's possible to implement different tooling for different needs. You could, for example, very easily create a script that reads data in CSV, XML, JSON, or whatever format and creates Robot tests based on that.

**Comment by markhu** [comment]
People are still fascinated by the prospect of loading in external test data: https://github.com/Snooz82/robotframework-datadriver

**Comment by prasoonmathur1654** [comment]
Hi Everyone , 

Any write for the API testing using the data driven approach in robot framework
