### ISSUE TITLE
Support disabling command line options accepting no values using `no` prefix (e.g. `--dryrun` -> `--nodryrun`)

### ISSUE THREAD

**Issue by peritus** [robotframework/robotframework#1865]
We're using Robot Framework in a continuous integration environment and all jobs do a ```--dryrun``` as part of their pre-flight-check before executing "the real thing" (that then takes a few minutes, uses selenium, etc.). We also have a parameterised job that allows developers to specify robot framework command line arguments to use for their run.

What we found is, specifying ```--dryrun``` twice, as in

```
./bin/pybot --dryrun --dryrun path/to/testfiles
```

actually disables dry run and the tests are executed in their entirety. We expected this would keep dry run enabled.

**Comment by jussimalinen** [comment]
It would seem most logical to add --no versions for all flags (and --statusrc also to be consistent). Same option given multiple times has not effect and the last value given should be the one that is used.

so --dryrun --dryrun --dryrun --nodryrun means no dryrun.
