### ISSUE TITLE
Possibility to turn off continue-on-failure in Teardown

### ISSUE THREAD

**Issue by bjornfor** [robotframework/robotframework#1871]
I have user keywords that expect errors to be handled by aborting; that's how things work normally (in test-cases). But when these keywords are used in Teardown contexts, and there is an error, things can go really bad, because the keywords may go on operating on bad data. See e.g. #1869.

I feel that a way to turn off the continue-on-failure mode in Teardown would be a good idea. The user can then opt-in to ignore certain errors with "Run Keyword And Ignore Error".

**Comment by markcloutier1212** [comment]
I second this -- a flag or something to restore this to how the teardown used to behave (pre 2.5) would be great.

**Comment by pekkaklarck** [comment]
Would a command line option disabling this behavior be OK? That ought to be pretty easy to implement, but it would then affect the whole test execution.

**Comment by aaronrodgers1212** [comment]
Not sure about OP's needs, but a command line parameter would work for mine.

**Comment by pekkaklarck** [comment]
@bjornfor, would a command line option turning this behavior off globally work for you? I could take a look at implementing it in RF 2.9.

Having more fine grained solution would have benefits in some cases, but that would likely be also more work to implement. Most importantly, I'm not sure what would be a good syntax to specify is this mode on or not. Using keywords like `Run Keyword With Some Special Mode` wouldn't be that nice.

**Comment by bjornfor** [comment]
A command line option would be a great start.

I understand that it may be cumbersome to come up with a syntax for turning it on/off per teardown block. The only downside I see with a command line option, is that the test data would effectively be written with the expectation of that command line option being set or not. So it feels like the option really should be settable from within the test data itself.

Whether the option is global or not matters less (IMHO) than whether it is settable on the command line or within the test data. I would prefer the latter (for the above reasons).

**Comment by pekkaklarck** [comment]
In addition to being able to turn continue-on-failure off in teardowns, it would be convenient to be able to turn it on in other places. Nowadays when keywords can have tags, that could possibly be implemented using special tags like `rf-continue-on-failure:yes`, `rf-continue-on-failure:no`.

**Comment by pekkaklarck** [comment]
This is covered by a more generic issue #2285.
