### ISSUE TITLE
Libdoc: Support searching keywords by name, arguments, and keywords

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#1872]
Especially with bigger libraries, it would be useful if Libdoc outputs had built-in search capability. It is possible to use browsers' search functionality, but it will search everywhere on the page. Dedicated search functionality could allow searching by name, arguments, documentation, and could show only the matching keywords.

Because Libdoc outputs is already now generated dynamically using Javascript, this shouldn't be too complicated to implement. We thus try to get it already into RF 2.8.7. Some kind of search functionality is a must latest in RF 2.9 when we plan to support keyword tags (#1840).

**Comment by pekkaklarck** [comment]
@rainmanwy: After revision 1dffe84 opening search always scrolls to shortcuts section. That was easy to implement and seems to work fine. Scrolling can be fine-tuned in future releases if needed.

**Comment by pekkaklarck** [comment]
After the latest fixes and enhancement @jussimalinen and I consider this issue done.

**Comment by rainmanwy** [comment]
Ok, thank you very much!
