### ISSUE TITLE
DateTime Library is not recognized as properly imported in RIDE

### ISSUE THREAD

**Issue by ikabelerma** [robotframework/robotframework#1881]
*I think this is a robot framework defect rather than a ride defect.

DateTime Library is included as part of the standard libraries available from RF 2.8.5 onward. However, when you import it in RIDE 1.3 using the library name DateTime, RIDE shows it in red which signifies that the library is not successfully imported.

However, when you run the test, keywords from the library are usable.

Basically the defect that even though the library has been imported successfully, the keywords from DateTime is not available in the autocomplete feature of RIDE nor does it show as dark blue which signifies that is is a keyword from a library.

**Comment by Ethies** [comment]
Thank you Pekka . this works for me
