### ISSUE TITLE
Add CLI option for re-running failed tests

### ISSUE THREAD

**Issue by guykisel** [robotframework/robotframework#1886]
Currently, if you'd like to rerun failed tests, you have to follow the steps at http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#merging-re-executed-tests 
```sh
pybot --output original.xml tests                          # first execute all tests
pybot --rerunfailed original.xml --output rerun.xml tests  # then re-execute failing
rebot --merge original.xml rerun.xml                       # finally merge results
```
This isn't really that bad, but if you start trying to do something more complex, like rerunning failed tests more than once, it gets a little more complex. This also isn't as friendly to less technical users.

I propose to modify the behavior of `--rerunfailed`, or to add a new command line option like `--rerunfailedandmerge`. This command line option would accept an integer (default 1) which represents the number of times to re-run failed tests. After finishing all the re-runs, if any were necessary, the results should be automatically merged.

If this seems like a reasonable feature, I'd be happy to implement it. I do understand that of the two options I've presented above, one breaks backwards compatibility, and the other adds another command line option, when there are already a lot of command line options. Neither of these is really ideal.

**Comment by pekkaklarck** [comment]
I can see that automatically re-running tests would be a useful feature, but my general thinking is that stuff like this should be done outside the core framework. The main reason is that, as you noticed, adding full generic support is not as easy as adding just a single command line option. There would be lot of new things to configure (how many times to re-run, what to do with intermediate results, etc.). In addition to making Robot's command line interface more complicated, there would be a risk that these options need to be changed in the future once the functionality is got into real use.

In my opinion it would be better to implement this functionality as a separate project similarly to Pabot. If that would require new public APIs, we definitely can add them. A separate project could be changed more easily than RF itself, and its development process and release schedule could also be independent. Once the functionality gets mature, we could then later consider incorporating it with the core.

**Comment by guykisel** [comment]
Sounds good, thanks for the comments.
