### ISSUE TITLE
Add support for background logger at Telnet library

### ISSUE THREAD

**Issue by vkruoso** [robotframework/robotframework#1887]
Hi!

I have posted a question at issue #1882 but as it is closed I'm assuming it won't be read.

The question is really about adding support to use another logger when using the Telnet library. I'm using the library in a bunch of threads, and it can get hard to debug as the library logs are lost.

I was thinking about adding a new option parameter to Telnet.open_connection to specify the logger to be used. Do you see any issues with it? I can try to provide a pull request with it if you think it's ok.

Thanks,
Vinicius

**Comment by jussimalinen** [comment]
What is your use case here? Are you using TelnetLibrary with Robot running in the background, or are you using TelnetLibrary from a python program with no Robot running..?

We are already planning asynchronous running of library keywords (issue #1791) for 2.9 and whatever solution we will use there, should solve your problem as well. The BackgroundLogger (or something similar) most likely should be used for all library keywords, but we dont want to commit to an api we might have to change in 2.9. So for 2.8.7 we are planning to revert the BackgroundLogger away and then implement a better threading support in 2.9..

**Comment by vkruoso** [comment]
I'm using the telnet library to maintain connections to all devices in a topology during a suite execution. As each connection runs in a thread, the messages generated by the library are lost. As a workaround I'm getting the command results and building an output similar to what the library would generate.

I'm guessing that the asynchronous running of library keywords would be enough to solve this problem.

**Comment by jussimalinen** [comment]
Maybe it would, but then again, having a control of all the connections in your own library (like you are doing) gives you more control. I think your use case is something that should be supported by the logging by default, and we will take that into account in 2.9.

**Comment by pekkaklarck** [comment]
We'd like to avoid making this kind of changes to individual libraries. Hopefully this will be supported in generic manner once #1791.
