### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by bimsoft** [robotframework/robotframework#1888]
I am using below..
robotframework (2.7.7)
robotframework-databaselibrary (0.6)
robotframework-selenium2library (1.1.0)
robotframework-sshlibrary (1.1)
selenium (2.31.0)
zope.interface (4.1.1)
 Trying to click on url that is inside the email body. So frame is structure like this.

![image](https://cloud.githubusercontent.com/assets/8725299/5595123/5f0a025e-9290-11e4-9c46-17698e143e09.png)

 i am clicking this by....
checking true to that particular email

Then content of email is showing in below frame.
moving focus on below frame
then Click Link    xpath=${xpath of url}

It is not clicking and showing message on console:
TypeError: string indices must be integers

Any help is much appreciated.

**Comment by laurentbristiel** [comment]
Hi. This is not looking like an issue in the product but rather a programming question related to your usage of the product. Could you close this issue and ask the question on the mailing list in https://groups.google.com/forum/?fromgroups=#!forum/robotframework-users please?

**Comment by bimsoft** [comment]
ok, thanks.
