### ISSUE TITLE
Builtin.Log: logging html to parent keyword context

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [robotframework/robotframework#1896]
when creating screenshots i'd like to be able to embedd the html link into the log of a parent keyword,
or even the test suite context directly in order to avoid having to navigate the keyword log tree

**Comment by laurentbristiel** [comment]
Did you consider using  [Suite Metadata](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#free-test-suite-metadata) for that purpose? 

You could create a custom keyword that does both the screenshot and set the path of the screenshot in the suite metadata. Something along those lines:

```
*** Keywords ***
custom capture
    [Arguments]  ${path}
    Capture Page Screenshot  ${path}
    Set Suite Metadata  Screenshot Path  ${path}
```

**Comment by RonnyPfannschmidt** [comment]
when more than one test fails it startsto create trouble, i cant see a per test thing - ideal case would be adding custom per test html thats direcly put under the expandable keyword logs or something in that manner

**Comment by pekkaklarck** [comment]
Could you use test documentation or message for this purpose?

**Comment by pekkaklarck** [comment]
No comments since January. Closing.

**Comment by RonnyPfannschmidt** [comment]
managed to miss the question

test documentation cant dynamically generate output
im not sure how message would help,

right now i have to navigate down a tree of passed keywords to get at the screenshots i logged

**Comment by pekkaklarck** [comment]
You can set test's documentation and message dynamically with BuiltIn `Set Test Documentation` and `Set Test Message` keywords, respectively. Documentation supports Robot's own wiki-like syntax and messages can be defined as HTML.
