### ISSUE TITLE
Improve error message for "Else" instead of "ELSE"

### ISSUE THREAD

**Issue by guykisel** [robotframework/robotframework#1898]
https://groups.google.com/forum/#!topic/robotframework-users/N_RogWjPBGg

The user got the error `FAIL 'Else' is a reserved keyword` because they weren't using it in all caps. As you can see in the discussion, the error message is misleading. Maybe something like `FAIL 'ELSE' and 'ELSE IF' are reserved keywords and must be all caps when used with 'Run Keyword If'`?

**Comment by pekkaklarck** [comment]
Sounds good to me. `Reserved` is a dynamic library and the current code contains this:

```python
    def run_keyword(self, name, args):
        raise Exception("'%s' is a reserved keyword" % name.title())
```

It could be changed to something like this:

```python
    def run_keyword(self, name, args):
        error = '%s' is a reserved keyword." % name.title()
        if name in ['else', 'else if']:
            error += " Must be in all-caps when used as a marker with 'Run Keyword'."
        raise Exception(error)
```

Any comments?

**Comment by wojciechtanski** [comment]
If there are no other ideas i will make this hard change. Anyone has something against this? Anyone has another idea for better text?

**Comment by wojciechtanski** [comment]
I would propose this:
error += " Thus '%s' must be in all-caps when used as a marker with 'Run Keyword'."

**Comment by guykisel** [comment]
I think any of the proposed wordings above are good.

**Comment by pekkaklarck** [comment]
I'm fine with all proposed wordings too. Is someone interested in creating a pull request?

**Comment by wojciechtanski** [comment]
Yes, I'll make pull request next week. Should be on Tuesday. Code is ready waiting for the pull request.

**Comment by jussimalinen** [comment]
@wojciechtanski, have you had a chance to finish the PR?

**Comment by wojciechtanski** [comment]
@jussimalinen : there is a code review waiting at https://github.com/wojciechtanski/robotframework/commit/3f2bc78d794e6726e59926cc5716874270197cfb

**Comment by pekkaklarck** [comment]
The problem is that we cannot merge an individual comment as easily as a PR. The commit itself looks good, though, but I added some comments there. If you can create a PR with my comments taken into account, I'll merge it right away.
