### ISSUE TITLE
Rebot crash when generating log

### ISSUE THREAD

**Issue by saarja** [robotframework/robotframework#1901]
When rebot is collecting data to generate the log crash due to "No such file or directory".

[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.3.2:exec (generate-log) on project robot: Command execution failed. Cannot run program "rebot" (in directory "..XXX/robot/target/robotframework-reports"): error=2, No such file or directory -> [Help 1]
[ERROR] 

Directory mentioned in error message can be found from in that url. Generating test report from run and collecting captured screenshots seems to work but log is missing

**Comment by pekkaklarck** [comment]
This error doesn't come from Robot or Rebot but seems to be caused by a configuration problem in your system. If I got it right, `rebot` command itself isn't found.
