### ISSUE TITLE
Can't run the testcase if its system path length is too long

### ISSUE THREAD

**Issue by DmiN-BY** [robotframework/robotframework#1907]
I try to run a testsuite in "E:\AutoTests\TestsForCE\06__Receiving\01__ReceivingBtn\02__ReceivingScr\02__EmptyLst\04__New\04__ChooseZoneScr\03__Done\02__SelectZone\03__ChooseVendorScr\03__SelectVendor\02__ProductReceivingScr\01__EmptyProductsLst\03__Add\02__Product" and got an "Suite contains no tests ..." error message. Testsuite successfully run only if I rename any folder to a shorter name.

**Comment by pekkaklarck** [comment]
How did you run it? What could be done in Robot to overcome this operating system restriction?

**Comment by DmiN-BY** [comment]
I run it from the .bat file using test name. My OS is Windows 7 x64. Are you shure that is an OS restriction?

**Comment by HelioGuilherme66** [comment]
Hi,

I tried to reproduce your problem but no success. (No drive E:)
Here is the test result (under Windows 7 x64):
C:\Robot\debug>path_test.bat
C:\Robot\debug>pybot
C:\AutoTests\TestsForCE\06__Receiving\01__ReceivingBtn\02__ReceivingScr\02__EmptyLst\04__New\04__ChooseZoneScr\
03__Done\02__SelectZone\03__ChooseVendorScr\03__SelectVendor\02__ProductReceivingScr\01__EmptyProductsLst\03__Add\02__Product\range_
test.robot
==============================================================================
Range Test
==============================================================================
float range                                                           |
PASS |
------------------------------------------------------------------------------
float range expr                                                      |
PASS |
------------------------------------------------------------------------------
manual loop expr                                                      |
PASS |
------------------------------------------------------------------------------
Range Test                                                            |
PASS |
3 critical tests, 3 passed, 0 failed
3 tests total, 3 passed, 0 failed
==============================================================================
Output:  C:\Robot\debug\output.xml
Log:     C:\Robot\debug\log.html
Report:  C:\Robot\debug\report.html

**Comment by DmiN-BY** [comment]
I'm using jybot to run testcases and using some tags to select tests to run.

**Comment by pekkaklarck** [comment]
Robot itself definitely doesn't have any limit like this, but I know that Windows has some limit. The final command that is used depends also on the Python interpreter that is used. I think `jython.bat` constructs the command so that it contains also `CLASSPATH` and that can get quite long.

I hope you can investigate this problem yourself and report what you find. If you find there's something really broken in Robot, please give instructions how to reproduce the problem and we can investigate it further.

**Comment by DmiN-BY** [comment]
I did some experiments and concluded that this is not a bug. This is OS limitation. If the path length exceeds 259 characters, then the test is not performed.

**Comment by pekkaklarck** [comment]
Ok. Have you already noticed --argumentfile option? It ought to provide a good workaround for you.

**Comment by DmiN-BY** [comment]
Thanks for the advice, but I always use an argument file and this approach does not help for that case.

**Comment by pekkaklarck** [comment]
I'm surprised argument files don't resolve this problem. Are you certain we are talking about the same feature? What I meant is this:
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#argument-files

**Comment by DmiN-BY** [comment]
Yes, that's what I meant. You can look for testsuite example here: https://www.dropbox.com/s/c5c0ae15whfkslr/12345678901234567890.ZIP?dl=0

**Comment by pekkaklarck** [comment]
Oh, I didn't realize your directory path was that long. You are hitting a Windows limitation there:
https://msdn.microsoft.com/en-us/library/aa365247(VS.85).aspx#maxpath

I thought you just have a very long command like `jybot --option value ... --more options path/to/tests.robot ... more/paths...`. Windows has a limitation for this too, and that's something where argument files can help. Anyway, definitely nothing Robot can do to fix or workaround the Windows limitation you encountered.
