### ISSUE TITLE
Telnet option negotiation loop

### ISSUE THREAD

**Issue by mwalle** [robotframework/robotframework#1908]
we are using the ser2net for a gateway between our network and the serial ports. If we use the telnet library to connect to ser2net we see endless IAC DONT/WONT/DO/WILL packets. Both processes run on the same machine and thus eats up the whole CPU.

I did a quick investigation and found out that this might the "nonterminating acknowledgment loop" which is mentioned in the telnet rfc854. I suspect this is because both sides (ser2net and the telnet library) are "dumb" implementations. Eg. they just answer by refusing/acknowledging the option. But the rfc says that:

> ```
>  b. If a party receives what appears to be a request to enter some
>  mode it is already in, the request should not be acknowledged.
>  This non-response is essential to prevent endless loops in the
>  negotiation.  It is required that a response be sent to requests
>  for a change of mode -- even if the mode is not changed.
> ```

Here is a short trace. Please note that this trace was done using the plain telnetlib, not the actual Telnet library.

> ```
>  # this is the initial sequence of ser2net
>  recv '\xff\xfb\x03\xff\xfb\x01\xff\xfe\x01\xff\xfd\x00'
>    IAC WILL 3  # this is the first command from the receive string from above
>  send DONT 3   # (1)
>    IAC WILL 1
>  send DONT 1
>    IAC DONT 1
>  send WONT 1
>    IAC DO 0
>  send WONT 0
>  recv '\xff\xfc\x03'  # (2) ser2net answers to (1)
>    IAC WONT 3
>  send DONT 3  # telnet library answers to (2), etc..
>  recv '\xff\xfc\x01\xff\xfe\x01\xff\xfe\x00'
>    IAC WONT 1
>  send DONT 1
>    IAC DONT 1
>  send WONT 1
>    IAC DONT 0
>  send WONT 0
>  recv '\xff\xfc\x03'
>    IAC WONT 3
>  send DONT 3
>  recv '\xff\xfc\x01\xff\xfe\x01\xff\xfe\x00'
>    IAC WONT 1
>  send DONT 1
>    IAC DONT 1
>  send WONT 1
>    IAC DONT 0
>  send WONT 0
>  recv '\xff\xfc\x03'
>    IAC WONT 3
>  send DONT 3
>  recv '\xff\xfc\x01\xff\xfe\x01\xff\xfe\x00'
>    IAC WONT 1
>  send DONT 1
>    IAC DONT 1
>  send WONT 1
>    IAC DONT 0
>  send WONT 0
>  recv '\xff\xfc\x03'
>    IAC WONT 3
>  send DONT 3
>  recv '\xff\xfc\x01\xff\xfe\x01\xff\xfe\x00'
>    IAC WONT 1
>  send DONT 1
>    IAC DONT 1
>  send WONT 1
>    IAC DONT 0
>  send WONT 0
>  [..]
> ```

**Comment by pekkaklarck** [comment]
Any ideas how to fix this?

**Comment by mwalle** [comment]
i guess we have to remember if we already send an response to an option, eg. send the response only once for a particular reply. but i'm not a telnet expert :)

**Comment by pekkaklarck** [comment]
Ok. Please submit a pull request if you manage to find a solution.

**Comment by pekkaklarck** [comment]
@jussimalinen: Can you take a look at this? If the PR is fine, we could even get this into RF 2.9 alpha 1 that is, hopefully, out next week.

**Comment by pekkaklarck** [comment]
Unfortunately @jussimalinen didn't have time to look at his before his longish holiday. He'll be back in April and we aren't going to get final RF 2.9 out before that, but I'll drop this from alpha 1 anyway.

**Comment by jussimalinen** [comment]
We are going to start creating alpha1 now. I will move this to alpha2.
