### ISSUE TITLE
Require exact number of keyword return value when assigning multiple scalar variables

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#1910]
Currently this works

``` robotframework
*** Test Cases ***
Example
    ${a}    ${b}    ${c} =    Create List    a    b    c    d    e
```

and the result is that `${c}` contains list `[c, d, e]`. This is a strange and also very hard to use feature. The reason it is hard to use is that the type of the last variable depends on how many items are returned. If there would be only three return values in the above example, the value of the last variable would be the last value itself, not a list containing it. If an unlimited number of return values is OK, it's much better to use

``` robotframework
*** Test Cases ***
Example
    ${a}    ${b}    @{c} =    Create List    a    b    c    d    e
```

which causes `@{c}` to always be a list. Notice that this second example accepts also only two values and `@{c}` will be an empty list in that case. If there should be at least three values, assignment should be something like `${a}  ${b}  ${c}  @{d} =`.

We will disallow assigning more values than scalar variables in RF 2.9. This is a backwards incompatible change, but we expect this weird functionality to be used so little that it shouldn't cause much problems. We can reconsider this decision and deprecate this functionality first if pre-releases indicate that our expectation is wrong.

**Comment by laurentbristiel** [comment]
so this means that something like this would not work anymore?
```
*** test cases ***
returned values
    ${result} =  Run Keyword and Ignore Error  should be equal  1  2
    log to console  status: ${result[0]}
    log to console  result: ${result[1]}   
```

**Comment by pekkaklarck** [comment]
Assigning to a single variable will work like earlier. In that case the return value is whatever you assing. Sorry for not making that clear.

**Comment by ndesai15** [comment]
@pekkaklarck Is there any specific declaration for long type of return variable ? Let me explain you.
Here's my script.
click at zoom in
    ${beforezoom} = returnZoom1
   Sleep2
And user keyword implementation for this is:
 public static long returnZoom1() {
		//doing something
		return beforezoom;
	}

I am getting this error: 
No keyword with name '${beforezoom} = returnZoom1' found.

Can you tell me where I am doing wrong ?
