### ISSUE TITLE
Expose `ERROR` log level to custom libraries

### ISSUE THREAD

**Issue by jaloren** [robotframework/robotframework#1916]
Here's the supported log levels in the logging api for robot: TRACE, DEBUG, INFO and WARN.

While there is no rule, it is a common convention to distinguish between a event that indicates something unexpected happened that could indicate a problem (WARNING) versus an event that is a serious problem that resulted in the failure of an operation (ERROR). For example, the official python documentation about the logging module and log4j make this distinction.

I believe that most engineers share this understanding and would treat events logged at ERROR differently then at warning. Consequently, I think it would be a good feature to support the ability to log at the ERROR log level in both test cases and custom libraries. The purpose would be to indicate that a serious problem has occurred that resulted in a failure.

**Comment by pekkaklarck** [comment]
The main reason ERROR level isn't officially exposed to custom keywords is that it could be confusing that a keyword that causes and error nevertheless passes. Do you think that is a problem? Or should an error automatically also fail a keyword?

**Comment by jaloren** [comment]
IMHO, whether a custom keyword passes or not should be determined by the implementation and context. My view is that ERROR indicates something has failed within the function, whether that means the keyword should fail or not would be context dependent.

**Comment by pekkaklarck** [comment]
I agree that error log messages should not automatically cause a keyword to fail. It's easy to raise an exception if/when failure appropriate.

I guess it's fine to officially expose the error level to custom libraries. I can see some valid use cases for it, and don't think the possibility that libraries can log too many errors is a good reason to prevent them altogether. I thus tentatively assigned this to RF 2.9 scope, but actually getting it in requires a bit changes than the current PR contains:

1. If a keyword logs something with the error level, the message on test execution errors in log file should automatically be linked to that keyword. We already have this functionality in place for warnings, and it ought to be easy to use it also with errors.

2. Should map messages originating from Python's `logging` module with level `logging.ERROR` or higher to the new error level. Nowadays anything above `logging.WARNING` is considered a warning.

3. Several acceptance tests are needed (some may also require more changes to code):
  - Libraries using `robot.api.logger.error()`.
  - Libraries using `logging.error()` or above.
  - Libraries using `print '*ERROR* Message`.
  - Using `ERROR` level with `Log` keyword.
  - Linking errors in execution errors to keywords causing them.

4. Error level needs to be documented in the User Guide.

Are you @jaloren interested to take care of the above? You should be able to get started by investigating how `WARN` level is handled/tested/documented currently, but I can also answer questions here or we can have a chat on #robotframework IRC channel.

**Comment by jaloren** [comment]
@pekkaklarck sorry for the delayed response. Yes, i would be interested in taking a swing at that. My next PR will attempt to incorporate all your feedback.

**Comment by pekkaklarck** [comment]
@jaloren great! No worries, there's still plenty of time to get this into RF 2.9. My plan is to get RF 2.9 alpha 1 out next week so that's already pretty close, though.

**Comment by stasiek** [comment]
How is the work with this going @jaloren ?

**Comment by jaloren** [comment]
@stasiek slowly unfortunately. My day job has been intruding and preventing me from doing much else. I'll try to dig into this in the next week.

**Comment by jaloren** [comment]
@pekkaklarck  so i have started digging into this. Can you point me to the modules that implement functionality you described in 1 and 2? I want to make sure I am looking at the right files.

**Comment by pekkaklarck** [comment]
Sorry for a bit late reply due to business trip.

Creating links from the execution errors section to actual keywords is in `jsmodelbuilders.py` and `jsbuildingcontext.py`. See especially `MessageBuilder.build` in the former. There may be other places that need to be modified, but this is a good place to start.

Mapping messages logged using `logging` module is in `pyloggingconf.py`. Probably don't need to edit other parts than `RobotHandler._get_logger_method`.

**Comment by jaloren** [comment]
@pekkaklarck thanks for the pointers. I'll take a look. Btw, i noticed that these two modules seem to be identical though presumably they are there for different purposes.

src/robot/output/librarylogger.py
src/robot/api/logger.py

Since they both seem to be doing the same thing (write at a certain log level), I added a function to handle the error leg to both. Is that okay or should i leave the librarylogger.py alone?

**Comment by jaloren** [comment]
@pekkaklarck I believe I have implemented changes for points (1) and (2) except for the fact that the actual report being generated does not show the keyword linking for error log levels like it does for warn. So clearly I am missing something. :) 

Note I am using the builtin log keyword to test this -- I am assuming that should not be a problem.

When I looked through through the jsmodelbuilders.py and jsbuildingcontext.py, the only place where I could see the linking being done is MessageBuilder.build function. So that's where I added the simple if block like so. And yet its still not working. 

I'll pop into the IRC robotframework channel this week...I suspect it would just be easier if we chatted.
 
```python
   def build(self, msg):
        if msg.level == 'WARN':
            self._context.create_link_target(msg)
	if msg.level == 'ERROR':
             self._context.create_link_target(msg)
	self._context.message_level(msg.level)
        return self._build(msg)
```

**Comment by pekkaklarck** [comment]
Yes, `src/robot/api/logger.py` and `src/robot/output/librarylogger.py` are pretty identical. The former is the public API we expose to test libraries and the latter pretty much an implementation detail. IIRC the latter was needed to avoid cyclic imports. Anyway, both need to be updated.

I expected some other changes to be needed to get errors linked in addition to modifying `MessageBuilder.build`. I don't remember exactly how the logic goes, but there's a change that javascript code that generates log files need to be updated too. That would mean updating either `src/robot/htmldata/rebot/log.html` or some javascript files included into it. Log file generation is somewhat complicated because it is so much performance, memory and file size optimized that understanding it can be difficult. If you cannot figure it out, chatting more on IRC is probably a good idea.

**Comment by pekkaklarck** [comment]
Any progress here? Can I help somehow?

**Comment by jaloren** [comment]
@pekkaklarck I'll look at the log.html and javascript and get back to you this week. I may need to chat in the IRC based on whether I can figure out the log.html on my own.

Apologies for the slowness -- day job keeps intruding.

**Comment by jaloren** [comment]
@pekkaklarck 

Actually, I am thinking it may not require any changes to the javascript. In the output.xml, there is an <errors> element. If  manually place a message generated with log keyword using error loglevel, then the log.html automatically places it in the test execution errors section and links it to the keyword. So I am thinking I just need to figure out how to get messages logged at error put in the output.xml...any pointers there?

Btw, any day or time you'd be around IRC? I am in central standard time. I'd really like to wrap this up in the next day or two and figure chatting there would bring this to a close pretty quick.

**Comment by jaloren** [comment]
@pekkaklarck  Once I got around the need  to hack javascript :), everything else fell into place. I believe I have implemented all the changes that have been outlined, including the test cases and documentation.

I am almost ready to submit the PR on this branch https://github.com/jaloren/robotframework/tree/ExposeErrorLog

However, there's one sticking point. I wasn't sure how to deliver the acceptance test cases. I simply wrote a robot test suite, where each test case demonstrates that error log level works in particular context. Is that sufficient? And if so, where do I put them in the src?

**Comment by pekkaklarck** [comment]
I decided to play with this myself and noticed that just changing `if msg.level == 'WARN'` to `if msg.level in ('WARN', 'ERROR')` in `output/logger.py` and in `reporting/jsmodelbuilders.py` was enough to get errors logged with the `Log` keyword shown correctly. On a quick look at your branch, it seems you've done the same, and also exposed the new `ERROR` level in other places too. Good job!

You are right that this new functionality needs tests. They belong to the `atest` directory where we have suites using certain functionality under `atest/testdata` and suites running them and verifying results under `atest/robot`. See [atest/README.rst](https://github.com/robotframework/robotframework/blob/master/atest/README.rst) and look at some of the existing suites for more information.

Notice that Robot has three different ways to log (stdout, `robot.api.logger` and Python's `logging`) that all need to support the `ERROR` level. That obviously means they all need to also be tested. I'd prefer adding the tests in suites already testing these logging approaches, but haven't looked at the existing suites does that actually make sense. If not, having a new suite just testing logging errors is fine too.

**Comment by jaloren** [comment]
@pekkaklarck  For the api logger and python logging, i have modified the test suites 
-  test_libraries/logging_api.robot 
- testdata/test_libraries/logging_with_logging.robot 

I have pushed that to my private branch. 

However, I didn't write a test case for the log keyword. In testdata/test_libraries/builtin/log.robot, there is a ‘Log with different levels’ test case. There is already a log keyword with the error log level. I am not sure what to make of that since presumably that level wasn’t exposed until the changes I put in. However, since that seems to be the test case I was going to write, can you please take a look and let me know if there needs to be a separate test case on top of that?

Assuming that's all good, I should be ready to submit a PR.

**Comment by pekkaklarck** [comment]
Interesting that `Log` is already tested with the ERROR level. Shows how this level hasn't been handled consistently and why it is a good idea to change the behavior as proposed here.

That existing test should nevertheless be updated to verify that the logged error ends up to execution errors too. Basically that requires adding something like this to the test case:

```
    Check Log Message    ${ERRORS[<index>]}    The message    ERROR
```

Obviously also other places where the new(ly enhanced) ERROR level is tested should verify the message both under the test and in execution errors. You apparently have already added tests for the programmatic logging APIs, but remember that  `print "*ERROR* The message"` needs to be tested too.

Please go ahead and submit a PR. We can continue discussion there once I've reviewed it. If more changes are needed, you can squash the commits when you are ready. For that to be easy, it's recommended to have a branch for the PR.

**Comment by pekkaklarck** [comment]
I was looking where adding a link from a warning in a log file to a keyword causing the warning is tested and only found unit test `test_message_linking` in `test_jsmodelbuilders.py`. Probably it's enough to either test also errors in that test or rename it to, for example, `test_warning_linking` and add new `test_error_linking`.

**Comment by jaloren** [comment]
Note I added test case Log Error Using Print in robot/test_libraries/logging_with_logging.robot. 

I took a look at the unit testcase. I originally attempted to modify the unit test to verify the linking however it kept failing. I then checked out git revision 495befccb8e which was prior to any of my commits. However, that unit test kept on failing, which leads me to believe someone else's commit caused a regression.  I decided not to try to modify the test case until whatever this issue is resolved.

```
======================================================================
FAIL: test_linking (test_jsmodelbuilders.TestBuildErrors)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jaloren/gitrepos/robotframework/utest/reporting/test_jsmodelbuilders.py", line 409, in test_linking
    (0, 3, 'Linkable', 's1-t1-k1')))
  File "/Users/jaloren/gitrepos/robotframework/utest/../src/robot/utils/asserts.py", line 182, in fail_unless_equal
    _report_unequality_failure(first, second, msg, values, '!=')
  File "/Users/jaloren/gitrepos/robotframework/utest/../src/robot/utils/asserts.py", line 245, in _report_unequality_failure
    _report_failure(msg)
  File "/Users/jaloren/gitrepos/robotframework/utest/../src/robot/utils/asserts.py", line 231, in _report_failure
    raise AssertionError(msg)
AssertionError: ((-1L, 5, 'Error'), (41L, 3, 'Warning'), (0L, 3, 'Linkable', 's1-t1-k1'), (-1L, 5, 'Linkable')) != ((-1, 5, 'Error'), (41, 3, 'Warning'), (0, 3, 'Linkable', 's1-t1-k1'))
```

**Comment by pekkaklarck** [comment]
That test is passing for me in updated master. Are you certain you didn't have your changes applied when you run it?
