### ISSUE TITLE
Creating Dictionary in "*** Variables ***" section

### ISSUE THREAD

**Issue by yahman72** [robotframework/robotframework#1920]
Found this:
<pre>
    *** Variables ***
    &{EXAMPLE}    key=value    key2=another value
</pre>
here https://code.google.com/p/robotframework/issues/detail?id=1450

This doesn't work - should it? ... or was the syntax changed?

**Comment by fabriziocucci** [comment]
Hi yahman72,

I think you missed that the enhancement [1450](https://github.com/robotframework/robotframework/issues/1450) is still open and will probably be addressed in the milestone 2.9.

Hope this help.

**Comment by yahman72** [comment]
Hi, yeah I missed that indeed - this is clear now = not supported yet i.e. I need to use Create Dictionary KW or use *.py variable files

**Comment by pekkaklarck** [comment]
@fabriziocucci is right, #1450 is under development. It's actually already implemented but not yet documented in User Guide. If you checkout the latest code you can test it. Hopefully we also get 2.9 alpha 1 out already next week.

**Comment by yahman72** [comment]
thanks for the info, I'll try it as soon as I can...
