### ISSUE TITLE
Screenshot library causes deprecation warning with wxPython 3.x

### ISSUE THREAD

**Issue by jussimalinen** [robotframework/robotframework#1922]
wx.PySimpleApp() has been deprecated in wx 2.9 and causes and warning to console: wxPyDeprecationWarning: Using deprecated class PySimpleApp

**Comment by pekkaklarck** [comment]
Did you already investigate how to avoid the problem?

**Comment by jussimalinen** [comment]
doing it right now...

**Comment by jussimalinen** [comment]
Replacing wx.PySimpleApp() with wx.App(False) seems to work on 2.8 without errors and should work the same on later versions as well.

**Comment by pekkaklarck** [comment]
Cool! Can you test this? Commit changes and add alpha1 label if everything is ok.

**Comment by jussimalinen** [comment]
tested with 2.8 and 3.0.3 on Windows, both worked.
