### ISSUE TITLE
Memory Error with Rebot

### ISSUE THREAD

**Issue by dhoomakethu** [robotframework/robotframework#1926]
Hi,

We are trying to generate reports and log out of a huge output.xml (>700MB) with rebot utility but unfortunately we are getting MemoryError (error trace below) .

I have already tried --splitlog, --removekeywords with out any success.
I tried searching the open and closed bugs for this issue and could found some options to avoid this issue while running the tests but We do not have much time to run these tests again . Any suggestions or hints to overcome this issue is highly appreciated.

Sanjay

###############################################################################
C:\Users\skvenkatesh\Desktop>rebot -d C:\Users\skvenkatesh\Desktop\parser --spli
tlog --removekeywords passed output.xml
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\lib\site-packages\robot\rebot.py", line 381, in <module>
    rebot_cli(sys.argv[1:])
  File "C:\Python27\lib\site-packages\robot\rebot.py", line 345, in rebot_cli
    Rebot().execute_cli(arguments)
  File "C:\Python27\lib\site-packages\robot\utils\application.py", line 44, in e
xecute_cli
    rc = self._execute(arguments, options)
  File "C:\Python27\lib\site-packages\robot\utils\application.py", line 94, in _
execute
    error, details = get_error_details()
  File "C:\Python27\lib\site-packages\robot\utils\error.py", line 45, in get_err
or_details
    details = ErrorDetails()
  File "C:\Python27\lib\site-packages\robot\utils\error.py", line 58, in ErrorDe
tails
    raise exc_value
MemoryError

**Comment by pekkaklarck** [comment]
We have tried to make output.xml processing as memory efficient as possible, but there's always a limit when memory runs out. I'm not particularly interested to do more memory profiling at the moment, but I'm definitely interested in findings if someone else wants to take a look at that.

You have some workarounds:

- Get more memory. It's so cheap nowadays that there's no excuse not to have 16GB on machines that need to process such big outputs. This is likely the easiest solution.

- Avoid constructs that create big nested keyword structures (and thus increase output.xml size) such as for loops and Wait Until Keyword Succeeds keyword. Try to replace them with code moved to test libraries.

- If you cannot avoid such structures, try using `--flattenkeywords` to flatten them. This option saves a lot more memory during output.xml processing than `--removekeywords`. See User Guide for details.

- Split test execution to smaller pieces. If you want to get one combined report, you need to post process those individual output.xml files before combination to avoid same memory error than when processing one big file, though.
