### ISSUE TITLE
Drop Python/Jython 2.5 support to ease adding support for Python 3

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#1928]
It's unlikely that we have time to add official Python 3 support (#1506) in RF 2.9. We should nevertheless drop Python/Jython 2.5 support already now to make it easier both to add Python 3 support later and to keep the [Python 3 port](https://pypi.python.org/pypi/robotframework-python3) updated with the official version.

The main reason why dropping Python/Jython 2.5 support is so important for Python 3 compatibility is that there are syntax incompatibilities in Python 2.5 and 3.x that make it unnecessarily hard to support both in the same code base. The biggest problem is that Python 2.5 syntax for catching exceptions `except Exception, exc` is incompatible with Python 3 syntax `except Exception as exc`. Python 2.6 and 2.7 supports both syntax, so after dropping 2.5 support we can switch to use the latter.

The reason we haven't dropped Python/Jython 2.5 support earlier is that the latest stable Jython release is 2.5.3. The recent [Jython 2.7 beta 4](http://fwierzbicki.blogspot.fi/2015/02/jython-27-beta4-released.html) is already so mature, though, that we are confident to recommend it to our Jython users. We also hope Jython 2.7 is at least in release candidate phase before RF 2.9 final is released.

RF 2.9 will continue to support Python 2.6. The main reasons are that it is the default Python version in still actively used RHEL 6, and supporting it along 2.7 and even 3.x should not be too much extra work. We recommend everyone who can to upgrade to Python 2.7, though.

**Comment by pekkaklarck** [comment]
Python/Jython 2.5 is not supported anymore. Still need to update installation instructions accordingly before closing this issue.

Suggestions how to make the code even more Python 3 compatible are appreciated, preferably in format of pull requests.

**Comment by userzimmermann** [comment]
I merged my Python 3 compatibility fork with 2.8.6:

https://github.com/userzimmermann/robotframework/commit/48aa73bcc56a614ac332c904a93a7a36f713137e

utest results unchanged. A few new atest FAILs.
I will fix them and then make a new [robotframework-python3](https://pypi.python.org/pypi/robotframework-python3) release (hopefully today).

Then I will go on to 2.8.7 and finally merge with latest commit, which should then be easy to merge back.

**Comment by pekkaklarck** [comment]
Cool! I don't expect much difficulties in merging changes up to 2.8.7, but after that things are going to get more interesting. It will be interesting to see how big diff there is after the latest changes.

Notice that although we definitely want Robot to support Python 3 in somewhat near future, having that support is not too high priority for our corporate sponsor and thus not initially planned for RF 2.9. We can consider that, though, if it turns out reaching Python 3 wouldn't be too complicated.

**Comment by userzimmermann** [comment]
https://pypi.python.org/pypi/robotframework-python3/2.8.6
https://github.com/userzimmermann/robotframework/releases/tag/python3-2.8.6

I also created issues for acceptance tests failing in Python 3, so anyone can participate in solving them:

https://github.com/userzimmermann/robotframework/issues

They don't reflect bugs in the framework itself. They are just related to some different behavior of Python 2 and 3 and to the tests themselves, which need further adaptions to deal with both major Python versions.

Is it a good idea to open a new issue in https://github.com/robotframework/robotframework/issues only for Python 3 compatibility discussion?

**Comment by userzimmermann** [comment]
https://pypi.python.org/pypi/robotframework-python3/2.8.7
https://github.com/userzimmermann/robotframework/releases/tag/python3-2.8.7

**Comment by pekkaklarck** [comment]
We have #1506 for Python 3 support. Better to use that for general Python 3 discussion than this issue that's only about dropping 2.5 support.

This issue is also done otherwise but installation instructions need to be updated.

**Comment by userzimmermann** [comment]
Of course! The original Python 3 issue where our discussion started... I somehow forgot about that :)
