### ISSUE TITLE
OperatingSystem: Enhance documentation about path separators

### ISSUE THREAD

**Issue by Ethies** [robotframework/robotframework#1929]
URL: http://robotframework.googlecode.com/hg/doc/libraries/OperatingSystem.html?r=2.8.3

Path separators

I was trying to search the ${dir}/example.txt, as like D:\Robot Works\TEST EXAMPLE\06 Test\Result

But this wasy I could my RIDE not able do execution, all time error occured.

Solution:
I given as ${dir}\\example.txt, as like "D:\\Robot Works\\TEST EXAMPLE\\06 Test\\Result\\example.txt"

This could helped me if this in the document.

**Comment by pekkaklarck** [comment]
Do you mean that we should add a note that using a single backslash as a separator doesn't work and you need to either use double backslash or `${/}`? I'm surprised that wasn't explicitly mentioned.

**Comment by Ethies** [comment]
Sorry Pekka, my suggestion was not properly posted.
Single backslash as separator is not working. System is working for double backslash ${\\} like D:\\Robot Works\\TEST EXAMPLE\\Result

**Comment by Ethies** [comment]
Oops... I just posted the directory path with *double backslash*, but after submitting these appears as single backslash :-1
(D:\\Robot Works\\TEST EXAMPLE\\Result)

**Comment by pekkaklarck** [comment]
Backslash is an escape character in Robot's test data so just having e.g. 'c:\temp` won't work but you need to escape the backslash like `c:\\temp`. This behavior obviously cannot change and it is also thoroughly documented in the User Guide. It definitely should be explained better in OparatingSystem library docs too.

**Comment by Ethies** [comment]
Thank you Pekka

**Comment by pekkaklarck** [comment]
Let's leave this open. I'll enhance OperatingSystem docs and close this when done.
