### ISSUE TITLE
When combining outputs (output.xml), result statics are changed

### ISSUE THREAD

**Issue by rafale3** [robotframework/robotframework#1932]
For example
Run test suite A including 10 TC. 
2 TC failed because TC teardown failed, other 8 TC failed also because of TC itself issue.

After combining outputs, combined report say that
8 TC failed because of TC itself issue, but 2 TC success.

I used below command for combining outputs.
rebot -l none -r \"$NAME.html\" --outputdir \"$TEST_DIR\" --reporttitle \"$STAGE_NAME\" --argumentfile \"$TEST_DIR/xmlfiles\""

**Comment by rafale3** [comment]
Before combining.

Start / End / Elapsed:
20150225 10:24:42.153 / 20150225 10:58:55.539 / 00:34:13.386 

Status:
22 critical test, 0 passed, 22 failed
22 test total, 0 passed, 22 failed 

Message:
Suite teardown failed:
Several failures occurred:


After combining 
Status:
22 critical test, 3 passed, 19 failed
22 test total, 3 passed, 19 failed 

Message:
Suite teardown failed:
Several failures occurred:

* Suite tear down failed

**Comment by pekkaklarck** [comment]
There are two natural possibilities for this:

1. You run tests with --critical or --noncritical options and don't use those when combining results. Criticality information is not stored in output.xml and thus you need to specify it again at this point. If you are only interested in combined results, you don't actually need to specify it during execution at all.

2. You are looking at status on console and there is a failure in suite teardown. Individual test results are logged to output.xml and to console after test itself passes. If suite teardown fails, tests in that suite are marked failed in reports/logs, but information on console or in the original output.xml cannot be updated.

If your situation matches either of the above, things work as expected. If not, please explain your situation in more detail.
