### ISSUE TITLE
remove obsolete robotframework-commit mailing list from user guide and .org site

### ISSUE THREAD

**Issue by laurentbristiel** [robotframework/robotframework#1938]
the mailing list [robotframework-commit](https://groups.google.com/forum/#!forum/robotframework-commit) is mentioned in:
* [User Guide](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#mailing-lists)
* [.org site Support and Contact](http://robotframework.org/#support-contact)

but this list seems to not be working anymore.
So we should probably remove references to this list.
(and maybe close the list itself).

I can do a PR for the cleaning. Quite straightforward.

**Comment by pekkaklarck** [comment]
Yes, that list isn't used by any active project anymore. Go ahead.

**Comment by laurentbristiel** [comment]
ok, I did 2 PR:
  * https://github.com/robotframework/robotframework/pull/1939
  * https://github.com/robotframework/robotframework.github.com/pull/6

**Comment by pekkaklarck** [comment]
Both PRs merged. Thanks!
