### ISSUE TITLE
Resources distribution

### ISSUE THREAD

**Issue by marc-** [robotframework/robotframework#1941]
Several of my projects are sharing common robot resources. Some of those resources can be rewritten on python, but some can not (like wrappers over Selenium library). I know that is not pretty much robotframework flavor, but is there a way to package and distribute robot resources, so it can be reused in other projects?

**Comment by pekkaklarck** [comment]
This kind of questions are better asked on robotframework-users mailing list. If you have concrete enhancement ideas, they can be submitted here.
