### ISSUE TITLE
libdoc is not generating the updated  keyword documentation

### ISSUE THREAD

**Issue by sayaara** [robotframework/robotframework#1944]
I am trying to create the keyword documentation for our python automation framework library.  libdoc is generating the keyword documentation for first time. But when I go and update the documentations in the code and re-run the utility, it doesn't pick up the changes and still generating the old documentation. Can someone help to resolve this? Thanks

**Comment by pekkaklarck** [comment]
I have never encountered this problem. My guess is that Libdoc is using installed version of your library. How do your run Libdoc?

**Comment by sayaara** [comment]
Issue was with my PYTHONPATH, it was incorrect.  After  updating it to the correct path everything worked as expected. Thanks
