### ISSUE TITLE
Run Keyword If  True  MyKwWithReturnValue returns value when not executed

### ISSUE THREAD

**Issue by yahman72** [robotframework/robotframework#1945]
Is this correct behaviour?

Running this:
<pre>
foo
    ${var}=     Set Variable        defaultValue
    Log   ${var}   WARN
    ${var}=     Run Keyword If      False           Catenate  NonDefaultValue
    Log   ${var}   WARN
    ${var}=     Run Keyword If      True            Catenate  NonDefaultValue
    Log   ${var}   WARN
</pre>

Prints this:
<pre>
[ WARN ] defaultValue
[ WARN ] None
[ WARN ] NonDefaultValue
</pre>

I would have expected to get:
<pre>
[ WARN ] defaultValue
<b>[ WARN ] defaultValue</b>
[ WARN ] NonDefaultValue
</pre>

I would have expected that the `${var}` is not modified if the condition does not match.

If this is desired (or it's too late to change this for backwards compatibility) then the documentation should mention something about this.

**Comment by laurentbristiel** [comment]
That's the way it works indeed.
To use "run keyword if" in variable assignments, you should always have a ELSE statement (or handle the fact that you will get a None when the IF does not pass).
Currently, the [keyword documentation](http://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Run%20Keyword%20If) does contain an example like that:
> Using ELSE and/or ELSE IF branches is especially handy if you are interested in the return value. This is illustrated by the example below that also demonstrates using ELSE IF and ELSE together:...

Do you think we should be more explicit and state that without ELSE we might get None?

**Comment by yahman72** [comment]
yes, this needs to be documented better - I just spend quite a long time figuring out why my default value is replaced with "none" :-)

**Comment by pekkaklarck** [comment]
I find it pretty natural that the return value of `Run Keyword If` is `None` if no keyword is actually executed. Documentation can still be enhanced to make that more explicit. Any suggestions how to improve it?

**Comment by laurentbristiel** [comment]
how about PL https://github.com/robotframework/robotframework/pull/1946?

**Comment by yahman72** [comment]
It's natural indeed after thinking about it for a while - at first I considered `Run Keyword If` as a control structure (i.e. "IF"-loop) not as a keyword (i.e. a function that has to return something). Now it sounds logical, because it is a keyword. 
Still there should be an example of this in the doc (like there are examples in the `Set Variable If`, `Get Variable Value` KWs).
#1946 is okayish, but I would make it even more dummy-proof by using a concrete example and improving the existing IF ELSE example. I find it a bit confusing, because the current one is not using "real" keywords, but strings instead (e.g. `Zero return value`)
Created PR #1947 for this

**Comment by laurentbristiel** [comment]
new proposition: https://github.com/robotframework/robotframework/pull/1949
I tried to be more explicit in the example and in the comments.

**Comment by pekkaklarck** [comment]
I agree documentation wasn't as clear as it could be. Merged the final PR #1949 proposed by @laurentbristiel and reviewed by @yahman72. Thanks guys!
