### ISSUE TITLE
Report for data driven test case

### ISSUE THREAD

**Issue by nguyenthiphuong2** [robotframework/robotframework#1950]
Currently we apply data driven test and expect the report will consider each data in the test case as a separated test case. This will give us a more detailed and accurate statistic about test successfull coverage.

E.g.

Username    Password    Status
User1       Pwd1        Pass
User2       Pwd2        Pass
User3       Pwd3        Pass
User4       Pwd4        Fail

Report: 1/4 fail instead of 1/1 fail as current

**Comment by laurentbristiel** [comment]
This is already possible. Look at the [Data-driven Style section of the User Guide](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#data-driven-style). The first example is what you want to do: "The (...) example has six separate tests, one for each invalid user/password combination". What you do is like the second example, for which you will get a single test.

**Comment by nguyenthiphuong2** [comment]
I knew the data driven using test template and already applied to my automation projects. What I mean here is the report. As the given example, the whole test case is fail if one of case fail (1/1). While we expect it would be 1/4. Do you have any suggestion on this laurentbristiel?

**Comment by laurentbristiel** [comment]
there are 2 patterns in this section and if you get a single test case, you must be using the second one. Let me show it here to be totally clear.

1) if you do this way:
```
*** Settings ***
Test Template  both_values_should_be_equal

*** test case ***
first test
    foo  bar

second test
    foo  foo
  
*** keywords ***
both_values_should_be_equal
    [arguments]  ${a}  ${b}
    should be equal  ${a}  ${b}
```
=> you get 2 tests in the report (what you want)
```
$ pybot test.robot
==============================================================================
Test
==============================================================================
first test                                                            | FAIL |
foo != bar
------------------------------------------------------------------------------
second test                                                           | PASS |
------------------------------------------------------------------------------
Test                                                                  | FAIL |
2 critical tests, 1 passed, 1 failed
2 tests total, 1 passed, 1 failed
==============================================================================
```

2) if you do this way:
```
*** test case ***
first test
    [Template]  both_values_should_be_equal
    foo  bar
    foo  foo
  
*** keywords ***
both_values_should_be_equal
    [arguments]  ${a}  ${b}
    should be equal  ${a}  ${b}
```
=> you get only one test in the report (what you get and don't want):
```
$ pybot test.robot
==============================================================================
Test2
==============================================================================
first test                                                            | FAIL |
foo != bar
------------------------------------------------------------------------------
Test2                                                                 | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
```

Hope this helps.

**Comment by nguyenthiphuong2** [comment]
Thanks Laurent. Yep we did following the opt2 and now it will takes a lot of time for revising the test case to opt1. However, we still prefer opt2 as it is more efficiency and convenient in managing test data/case. And also it is not really data driven if we design by opt1. So do you think it would be perfect if the report cover this?

**Comment by laurentbristiel** [comment]
I have more the user perspective and don't know how big/nice a change it would be from a code/product point of view. I leave it to @pekkaklarck or @jussimalinen (or any other knowledgeable person)

**Comment by pekkaklarck** [comment]
@laurentbristiel is right about the current behavior and the design behind it. This is definitely something that will not change. I also disagree that his option 1 above wouldn't be data-driven testing.

I'm not entirely against adding some way configure reporting when above option 2 is used, though. The problem is that I don't see any clear and simple syntax to define such configuration in test data, and I don't think this is something that could be configured from the command line globally. Specifying test names like in option 1 also requires so little extra effort that it may be as good as it gets. Let us know @nguyenthiphuong2 if you have ideas related to this.

**Comment by nguyenthiphuong2** [comment]
First of all, I would like to thank you so much for the quick feedback. And I will give you guy my current situation for clearing my idea about this.
We have to design automation to test if the "Eligible Assessment Visas pass/fail rule" from our website are correct against the requirement. The pass/fail rules for each visa are complex and contain a lot of and/or conditions. We applied boundary value analysis, equivalence partitioning to design test case. Thus, for each rule, it may result ten to hundred data rows. It's easier for reviewing the test data for each visa if we put it together in a test case (as a excel spreadsheet) than separate it to hundred test cases.
We provide visa services to 4 countries with hundreds visa type, and the test goes up to thousands cases/data now (running on 6 VMW daily). The current test design (script + data) is good and maintainable. What the test and management team want is a more accuracy about test successfull coverage, since 1/100 data in a case fail will result 1/1 fail. And we also want to get exactly how many data rows is created.
Hope that it makes sense.

**Comment by pekkaklarck** [comment]
It seems option 1 clearly is what you need. Notice that you can format tests also like this:

```robotframework
*** Settings ***
Test Template    Should be equal

*** Test Cases ***
First test     foo    bar
Second test    foo    foo
```

Or even add headers like:

```robotframework
*** Settings ***
Test Template    Should be equal

*** Test Cases ***    VALUE 1    VALUE 2
First test            foo        bar
Second test           foo        foo
```

**Comment by nguyenthiphuong2** [comment]
Huhu It seem that I could not expose what I really mean via above explanation. And I believe that some others facing with the same problem as well as have the same thought with me. I will post some pictures of my projects by tomorrow as soon as I get the office. 
Thank you guys so much again.

**Comment by nguyenthiphuong2** [comment]
http://www.shino.de/2010/07/06/parkcalc-automation-templates-for-data-driven-tests/

**Comment by pekkaklarck** [comment]
I think I understood your situation. What I don't understand is why it is a problem to add explicit names for each test you want to be reported separately. Even if there is a good use case, we would need to figure out some other way to configure that each test is reported separately. We absolutely cannot change the current behavior because there are very good use cases for it and the change would be backwards incompatible.

**Comment by nguyenthiphuong2** [comment]
Thank pekka, as you confirmed that you absolutely cannot change the framework we have no way other than update our test as you Laurent recommended. It's just take time and I hope no more than 1 week.
I will let you and people who may care about this if it work and satisfy our expectation as soon as I finish the task.

**Comment by nguyenthiphuong2** [comment]
I've just made a practice using opt1 and it works like charm. I went throught Laurent guide carelessly, and thought it's nothing special compare to our current test design. Sorry guy.
Pekka you can close this issue just right now :) I'm very appricated you all supportion.

**Comment by pekkaklarck** [comment]
Great that the existing functionality works for you. Notice that I'm not against changing the framework in general, on the contrary, but changing behavior in backwards incompatible way is something we try to avoid. This is especially true when there are valid use cases for the current behavior.
