### ISSUE TITLE
Listener Interface: name parameter includes return variable

### ISSUE THREAD

**Issue by vkruoso** [robotframework/robotframework#1951]
When keywords are called from the robot file with a expected return value, the `name` parameter  passed to the `start_keyword` and `end_keyword` methods includes the return value string. This is what I mean:

Calling:
```robotframework
${len}=  Get Length  test string
```

`start_keyword` and `end_keyword` `name` parameter:
```robotframework
${len} = BuiltIn.Get Length
```

The return variable should not be part of the keyword name, or the documentation should be enhanced to explain this situation.

**Comment by pekkaklarck** [comment]
This is pretty much a duplicate of #1611.

**Comment by jussimalinen** [comment]
The assignment was removed from the keyword name in 8d352252c62e2f880a0a00bc45f612fb7ea0fac0
