### ISSUE TITLE
Mulitple logger objects seen in robot framework

### ISSUE THREAD

**Issue by madhavan020985** [robotframework/robotframework#1953]
I am trying to understand robot framework (version 2.8.7) logging module to integrate it with our applicaton logging module,

I am struct at this piece of code: robot/output/logger.py - gitlink

````python
class Logger(AbstractLogger):
    def message(self, msg):
        """Messages about what the framework is doing, warnings, errors, ..."""
        for logger in self._loggers.all_loggers():
            logger.message(msg)
        *****more code*****
````
For logging a message in multiple places, it is the convention to use one logger with multiple handlers.  
But why has the author of this framework chosen to create one parent logger that has an array of child loggers & all of them invoked one after the other.

I am wondering, 1) if each logger object is just a log handler (or) is it more than that? 2) How does robot's log listener differ from the conventional logging handler?

**Comment by laurentbristiel** [comment]
Hello,
I think the [Robot Framework development](https://groups.google.com/forum/#!forum/robotframework-devel) would be a better place to ask this question rather than opening an issue.

**Comment by pekkaklarck** [comment]
Laurent is right that this isn't the right forum for general discussion and questions. I want to warn you that Robot's internal logging system is somewhat messed up. I hope we get it cleaned up at some point, and thus those loggers cannot be considered stable either. To be able to propose alternatives, we would need to know a bit more about your needs.
