### ISSUE TITLE
new feature: support network node that need to deal with heart beat or keep alive on the same socket

### ISSUE THREAD

**Issue by lzq420241** [robotframework/robotframework#1956]
Currently the network node are bound with a certain protocol, this prohibits the usage of
rammbock from end/terminal that equipped with alive detection mechanism.
Since alive detection packet normally are not compatible with interaction protocol on the same socket,
we need to do some ugly hacking in _receive_msg_ip_port function in _NetworkNode class in order to involving rammbock in that kinds of scenario.
I come from Nokia, and our team hopes that our test cases can keep synchronized with robot and rammbock update.

**Comment by pekkaklarck** [comment]
Could you please submit this to Rammbock's issue tracker?

**Comment by lzq420241** [comment]
ok. Sorry for the misinformation.
