### ISSUE TITLE
Data Driven Testing: Fixing arguments for template keywords

### ISSUE THREAD

**Issue by kidphys** [robotframework/robotframework#1960]
I'm running to a situation where I have multiple scenarios which correspond to just 1 workflow. In each scenarios, there are some arguments have fixed value (say a customer have debt, or not), and some arguments varies.

In robotframework, is there anyway we can fixed some input arguments for some test cases, and reuse the same template keyword? In this way we can just use 1 workflow keyword (with all arguments), but in test data, we have to input only a few arguments (instead of key in duplicated data for all fixed arguments in a specific scenario).

**Comment by Tattoo** [comment]
is this what you are looking for? http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#default-values-with-user-keywords

**Comment by pekkaklarck** [comment]
Yeah, default values for arguments ought to work in this use case. Notice that robotframework-users mailing list or other similar forums are better places to ask question than this issue tracker.
