### ISSUE TITLE
Maximum limit of started keywords exceeded - error 

### ISSUE THREAD

**Issue by yahman72** [robotframework/robotframework#1961]
I'm getting the `Maximum limit of started keywords exceeded.` error during test execution while running them on Win7 with Python 2.7.

In https://github.com/robotframework/robotframework/blob/master/src/robot/running/context.py
I found this line code for the error 
`_started_keywords_threshold = 42  # Jython on Windows don't work with higher`

According to that comment, it seems that the limit is relevant only for the Jython+Windows combination.

Shouldn't that limitation apply only if you are really running Jython on Windows?

Now the code seems apply the limit to all environments:
<pre>
   def start_keyword(self, keyword):
        self._started_keywords += 1
        if self._started_keywords > self._started_keywords_threshold:
            raise DataError('Maximum limit of started keywords exceeded.')
        self.output.start_keyword(keyword)
</pre>

**Comment by laurentbristiel** [comment]
This "42" looks almost like an easter egg to me (good timing to find it though). I suspect one has to set a limit anyway, for any platform, otherwise you might try go to on indefinitely and hit some OS/hardware limits anyway. 

@yahman72 I am going to answer by a question (sorry), but are you sure you really need to have more than 42 nested calls of keywords? That seems like a lot. Could you share your use case?

**Comment by pekkaklarck** [comment]
The limit of opened keywords was added to avoid hard crashes with recursive user keywords (#551). The limit was initially 100, but it wasn't enough on some platforms (at least Jython on Windows) and we dropped it. I think the actual limit was a little below 50, but we couldn't resist the temptation to use 42 as a bit safer value.

Did you @yahman72 encounter this limit in a valid case where you had 42 opened keywords at the same time? Or did you have infinite recursion that was stopped by this functionality?

If this limit is too low for real and valid use cases, we definitely can take a look at raising it. Now that RF 2.9 is going to require Jython 2.7, we could check does it handle higher limit than 42 on Windows. If not, we could consider making the limit platform dependent.

**Comment by yahman72** [comment]
Yes, this was triggered by a recursive KW. In my case that recursive KW is used to analyse a text file that is generated by the SUT. Usually that file is small enough for that limit of 42, but sometimes (depending on the system load) the file is bigger and that 42 is not enough. I'm not expecting the recursion to be deeper than 150 or so.
Of course, I could refactor the KW to be non-recursive or extend that limit on my fork but that sounds a bit odd, if the limit is much higher on other platforms...

IMHO a cmdline argument to override the default would be even better solution than platform specific values.
... and a perfect solution would be a combination of both.

**Comment by pekkaklarck** [comment]
It actually sounds like it would be a good idea to move the logic to a library. You would get a lot less keywords and thus your log.html and output.xml would be much smaller.

As I already commented, I'm fine with the limit to be raised or made platform dependent if Jython/Windows is still problematic. Could you investigate this and possibly provide a pull request? Some tests were added as part of #551, and they obviously need to be adjusted too.

I definitely would not like to make this limit configurable via a command line option.

**Comment by yahman72** [comment]
Yeah, to move it to a library is on my todo-list - but I don't have time for it in the current project schedule = need to get it working without a library first.

I'm not so sure that platform specific limit is a good idea in general, in the Jython/Windows case it makes sense because Jython seems to limit it somehow. But in general isn't it so that the maximum recursion depth is determined by the stack size and the maximum stack size depends on memory allocated to it (which is configurable). 

A bit off-topic: The #551 doesn't mention any details, but that Jython/Windows limit might also be higher if it would have a bigger stack size (i.e. start java with a bigger stack i.e. use the `-Xss` option).

**Comment by pekkaklarck** [comment]
Are you @yahman72 interested to investigate could the limit be raised now that Jython 2.7 is available? If yes, we can assign this issue to RF 2.9 scope and wait for possible pull request. We can also change the underlying logic if you have other ideas how to prevent crashes due to recursion.

**Comment by yahman72** [comment]
I could have a look, but it'll take a while as I'm busy with other stuff at the moment...
Is there already a release date/plan for RF 2.9?

About the implementation: 
I tend to agree with you about this being not a good idea as a command option. Increasing the limit is probaby very seldomly used, more "hidden" way of doing this would be better e.g. override the default by an envinroment variable.

**Comment by pekkaklarck** [comment]
Is this issue still relevant?

**Comment by yahman72** [comment]
I guess yes. I have already reworked my code so that I don't have an issue with the recursion anymore - but I did promised to check the Jython, unfortunately I have been and still am too busy too with other stuff (I guess it won't make it to the RF2.9)

**Comment by pekkaklarck** [comment]
Ok. If you don't have time to look at this in the foreseeable future, I consider this issue too low level to keep open.

**Comment by yahman72** [comment]
Finally found some time for this:
I did some research with jython 2.7.0 and it seems that the hardcoded limit of 42 started KW's is not needed anymore both jython & python trigger an exception at 120th KW when hitting the default python recursion limit (`sys.getrecursionlimit()`) without any side-effects like in #551

I won't bother sharing the details here, at least not yet.

Any preferences how to proceed? Open a new issue with more details about the results with jython 2.7.0? And attach a PR to that new issue?

**Comment by pekkaklarck** [comment]
I think it would be safest to raise the limit from 42 to 100. I don't see why anyone would need more. Without limits we can hit Python's recursion limit anywhere in Robot's code and that can crash the whole execution. If you are interested to provide a pull request, we can simply reopen this issue.

**Comment by yahman72** [comment]
okay, let's reopen this one.

Are you sure about the crashing? 
My test suite doesn't crash with python or jython (RF 2.9.3.dev20151009 and 2.8.7), see results below.

IMHO it would be better not to set a hard limit for the number of started KWs. This way it would be possible write recursive KWs (e.g. in resource files). 
Also the more "advanced" scenarios where the python's max recursion depth (1000) is not enough it would be easier to extend the recursion depth (i.e. only `sys.setrecursionlimit()`) i.e. the hard limit would eventually come from the OS's stack size. Jython 2.7.0 has also improved support for this, i.e. stack size, through environment variable `JAVA_STACK : Java stack size (sets via -Xss)`.
This would of course mean that the max. limits might be slightly different on different OS's, but that shouldn't be an issue, because if you know how to increase Python's max. recursion limit you know what you are doing (and you won't be blaming RF if it doesn't work).
In another words hard limit makes sense if the test execution crashes due to recursion exceptions - but doesn't seem to be the case anymore (at least not with my simple test suite).
 
**Detailed results:**

Modified context.py
<pre>
    _started_keywords_threshold = 4200
    
	...
	
	def start_keyword(self, keyword):
        self.output.info('started KWs: %s' % self._started_keywords)
        self._started_keywords += 1
</pre>

Test Suite
<pre>
*** Test Cases ***
Passing Test 1
    Pass Execution    Dummy Pass

Infinite recursion
        Recursive Keyword

Passing Test 2
    Pass Execution    Dummy Pass

*** Keywords ***
Recursive Keyword
        Call Recursive Keyword

Call Recursive Keyword
        Recursive Keyword
</pre>

Results Python (win8.1):
<pre>
> python -m robot.run -b debug.log recursion.robot & egrep -B3 "maximum recursion" debug.log | egrep -v "START KW| END KW"
==============================================================================
Recursion
==============================================================================
Passing Test 1                                                        | PASS |
Dummy Pass
------------------------------------------------------------------------------
Infinite recursion                                                    | FAIL |
maximum recursion depth exceeded
------------------------------------------------------------------------------
Passing Test 2                                                        | PASS |
Dummy Pass
------------------------------------------------------------------------------
Recursion                                                             | FAIL |
3 critical tests, 2 passed, 1 failed
3 tests total, 2 passed, 1 failed
==============================================================================
Debug:   C:\git\tmp_stuff\debug.log
Output:  C:\git\tmp_stuff\output.xml
Log:     C:\git\tmp_stuff\log.html
Report:  C:\git\tmp_stuff\report.html
20151014 07:13:45.581 - INFO - started KWs: 120
20151014 07:13:45.597 - FAIL - maximum recursion depth exceeded
</pre>

Results Jython (win8.1):
<pre>
> jython -m robot.run --version
Robot Framework 2.9.3.dev20151009 (Jython 2.7.0 on java1.8.0_60)

[13.10.2015 13:42:17 C:\git\tmp_stuff\]
> jython -m robot.run -b debug.log recursion.robot & egrep -B3 "maximum recursion" debug.log | egrep -v "START KW| END KW"
==============================================================================
Recursion
==============================================================================
Passing Test 1                                                        | PASS |
Dummy Pass
------------------------------------------------------------------------------
Infinite recursion                                                    | FAIL |
maximum recursion depth exceeded
------------------------------------------------------------------------------
Passing Test 2                                                        | PASS |
Dummy Pass
------------------------------------------------------------------------------
Recursion                                                             | FAIL |
3 critical tests, 2 passed, 1 failed
3 tests total, 2 passed, 1 failed
==============================================================================
Debug:   C:\git\tmp_stuff\debug.log
Output:  C:\git\tmp_stuff\output.xml
Log:     C:\git\tmp_stuff\log.html
Report:  C:\git\tmp_stuff\report.html
20151013 13:42:24.587 - INFO - started KWs: 121
20151013 13:42:24.602 - FAIL - maximum recursion depth exceeded
</pre>


More jython details:
- per default java is executed with 1MB stack size
- with default stack size the max. started KWs is ~120. That hits the python's default max. recursion limit (`sys.getrecursionlimit()`), and throws `maximum recursion depth exceeded` but does not crash test execution.
- with smaller stack size (e.g. 512KB) the limit is lower and causes `Java StackOverflowError` (i.e. python `maximum recursion depth exceeded (Java StackOverflowError)`) but does not crash test execution.

<pre>
[13.10.2015 13:42:26 C:\git\tmp_stuff\]
> jython --print -m robot.run -b debug.log recursion.robot
C:\java\jdk\v1.8.0_60\bin\java -Xmx512m -Xss1024k -classpath C:\jython2.7.0\jython.jar;. -Dpython.home=C:\jython2.7.0 -Dpython.executable=C:\jython2.7.0\bin\jython.exe -Dpython.launcher.uname=windows -Dpython.launcher.tty=true org.python.util.jython -m robot.run -b debug.log recursion.robot

[13.10.2015 13:42:26 C:\git\tmp_stuff\]
> C:\java\jdk\v1.8.0_60\bin\java -Xmx512m -classpath C:\jython2.7.0\jython.jar;. -Dpython.home=C:\jython2.7.0 -Dpython.executable=C:\jython2.7.0\bin\jython.exe -Dpython.launcher.uname=windows -Dpython.launcher.tty=true org.python.util.jython -m robot.run -b debug.log recursion.robot            & egrep -B3 "maximum recursion" debug.log | egrep -v "START KW| END KW"
==============================================================================
Recursion
==============================================================================
Passing Test 1                                                        | PASS |
Dummy Pass
------------------------------------------------------------------------------
Infinite recursion                                                    | FAIL |
maximum recursion depth exceeded (Java StackOverflowError)
------------------------------------------------------------------------------
Passing Test 2                                                        | PASS |
Dummy Pass
------------------------------------------------------------------------------
Recursion                                                             | FAIL |
3 critical tests, 2 passed, 1 failed
3 tests total, 2 passed, 1 failed
==============================================================================
Debug:   C:\git\tmp_stuff\debug.log
Output:  C:\git\tmp_stuff\output.xml
Log:     C:\git\tmp_stuff\log.html
Report:  C:\git\tmp_stuff\report.html
20151013 13:42:33.791 - INFO - started KWs: 63
20151013 13:42:33.797 - FAIL - maximum recursion depth exceeded (Java StackOverflowError)

[13.10.2015 13:42:34 C:\git\tmp_stuff\]
> C:\java\jdk\v1.8.0_60\bin\java -Xmx512m -Xss128k -classpath C:\jython2.7.0\jython.jar;. -Dpython.home=C:\jython2.7.0 -Dpython.executable=C:\jython2.7.0\bin\jython.exe -Dpython.launcher.uname=windows -Dpython.launcher.tty=true org.python.util.jython -m robot.run -b debug.log recursion.robot   & egrep -B3 "maximum recursion" debug.log | egrep -v "START KW| END KW"
==============================================================================
Recursion
==============================================================================
Passing Test 1                                                        | PASS |
Dummy Pass
------------------------------------------------------------------------------
Infinite recursion                                                    | FAIL |
maximum recursion depth exceeded (Java StackOverflowError)
------------------------------------------------------------------------------
Passing Test 2                                                        | PASS |
Dummy Pass
------------------------------------------------------------------------------
Recursion                                                             | FAIL |
3 critical tests, 2 passed, 1 failed
3 tests total, 2 passed, 1 failed
==============================================================================
Debug:   C:\git\tmp_stuff\debug.log
Output:  C:\git\tmp_stuff\output.xml
Log:     C:\git\tmp_stuff\log.html
Report:  C:\git\tmp_stuff\report.html
20151013 13:42:42.260 - INFO - started KWs: 18
20151013 13:42:42.266 - FAIL - maximum recursion depth exceeded (Java StackOverflowError)

[13.10.2015 13:42:43 C:\git\tmp_stuff\]
> C:\java\jdk\v1.8.0_60\bin\java -Xmx512m -Xss256k -classpath C:\jython2.7.0\jython.jar;. -Dpython.home=C:\jython2.7.0 -Dpython.executable=C:\jython2.7.0\bin\jython.exe -Dpython.launcher.uname=windows -Dpython.launcher.tty=true org.python.util.jython -m robot.run -b debug.log recursion.robot   & egrep -B3 "maximum recursion" debug.log | egrep -v "START KW| END KW"
==============================================================================
Recursion
==============================================================================
Passing Test 1                                                        | PASS |
Dummy Pass
------------------------------------------------------------------------------
Infinite recursion                                                    | FAIL |
maximum recursion depth exceeded (Java StackOverflowError)
------------------------------------------------------------------------------
Passing Test 2                                                        | PASS |
Dummy Pass
------------------------------------------------------------------------------
Recursion                                                             | FAIL |
3 critical tests, 2 passed, 1 failed
3 tests total, 2 passed, 1 failed
==============================================================================
Debug:   C:\git\tmp_stuff\debug.log
Output:  C:\git\tmp_stuff\output.xml
Log:     C:\git\tmp_stuff\log.html
Report:  C:\git\tmp_stuff\report.html
20151013 13:42:53.052 - INFO - started KWs: 48
20151013 13:42:53.060 - FAIL - maximum recursion depth exceeded (Java StackOverflowError)

[13.10.2015 13:42:54 C:\git\tmp_stuff\]
> C:\java\jdk\v1.8.0_60\bin\java -Xmx512m -Xss512k -classpath C:\jython2.7.0\jython.jar;. -Dpython.home=C:\jython2.7.0 -Dpython.executable=C:\jython2.7.0\bin\jython.exe -Dpython.launcher.uname=windows -Dpython.launcher.tty=true org.python.util.jython -m robot.run -b debug.log recursion.robot   & egrep -B3 "maximum recursion" debug.log | egrep -v "START KW| END KW"
==============================================================================
Recursion
==============================================================================
Passing Test 1                                                        | PASS |
Dummy Pass
------------------------------------------------------------------------------
Infinite recursion                                                    | FAIL |
maximum recursion depth exceeded (Java StackOverflowError)
------------------------------------------------------------------------------
Passing Test 2                                                        | PASS |
Dummy Pass
------------------------------------------------------------------------------
Recursion                                                             | FAIL |
3 critical tests, 2 passed, 1 failed
3 tests total, 2 passed, 1 failed
==============================================================================
Debug:   C:\git\tmp_stuff\debug.log
Output:  C:\git\tmp_stuff\output.xml
Log:     C:\git\tmp_stuff\log.html
Report:  C:\git\tmp_stuff\report.html
20151013 13:43:04.924 - INFO - started KWs: 108
20151013 13:43:04.931 - FAIL - maximum recursion depth exceeded (Java StackOverflowError)

[13.10.2015 13:43:06 C:\git\tmp_stuff\]
> C:\java\jdk\v1.8.0_60\bin\java -Xmx512m -Xss1024k -classpath C:\jython2.7.0\jython.jar;. -Dpython.home=C:\jython2.7.0 -Dpython.executable=C:\jython2.7.0\bin\jython.exe -Dpython.launcher.uname=windows -Dpython.launcher.tty=true org.python.util.jython -m robot.run -b debug.log recursion.robot  & egrep -B3 "maximum recursion" debug.log | egrep -v "START KW| END KW"
==============================================================================
Recursion
==============================================================================
Passing Test 1                                                        | PASS |
Dummy Pass
------------------------------------------------------------------------------
Infinite recursion                                                    | FAIL |
maximum recursion depth exceeded
------------------------------------------------------------------------------
Passing Test 2                                                        | PASS |
Dummy Pass
------------------------------------------------------------------------------
Recursion                                                             | FAIL |
3 critical tests, 2 passed, 1 failed
3 tests total, 2 passed, 1 failed
==============================================================================
Debug:   C:\git\tmp_stuff\debug.log
Output:  C:\git\tmp_stuff\output.xml
Log:     C:\git\tmp_stuff\log.html
Report:  C:\git\tmp_stuff\report.html
20151013 13:43:18.910 - INFO - started KWs: 121
20151013 13:43:18.929 - FAIL - maximum recursion depth exceeded

[13.10.2015 13:43:21 C:\git\tmp_stuff\]
> C:\java\jdk\v1.8.0_60\bin\java -Xmx512m -Xss2M -classpath C:\jython2.7.0\jython.jar;. -Dpython.home=C:\jython2.7.0 -Dpython.executable=C:\jython2.7.0\bin\jython.exe -Dpython.launcher.uname=windows -Dpython.launcher.tty=true org.python.util.jython -m robot.run -b debug.log recursion.robot     & egrep -B3 "maximum recursion" debug.log | egrep -v "START KW| END KW"
==============================================================================
Recursion
==============================================================================
Passing Test 1                                                        | PASS |
Dummy Pass
------------------------------------------------------------------------------
Infinite recursion                                                    | FAIL |
maximum recursion depth exceeded
------------------------------------------------------------------------------
Passing Test 2                                                        | PASS |
Dummy Pass
------------------------------------------------------------------------------
Recursion                                                             | FAIL |
3 critical tests, 2 passed, 1 failed
3 tests total, 2 passed, 1 failed
==============================================================================
Debug:   C:\git\tmp_stuff\debug.log
Output:  C:\git\tmp_stuff\output.xml
Log:     C:\git\tmp_stuff\log.html
Report:  C:\git\tmp_stuff\report.html
20151013 13:43:32.181 - INFO - started KWs: 121
20151013 13:43:32.201 - FAIL - maximum recursion depth exceeded

[13.10.2015 13:43:34 C:\git\tmp_stuff\]
>
[13.10.2015 13:43:34 C:\git\tmp_stuff\]
>
[14.10.2015  7:09:51 C:\git\tmp_stuff\]
> C:\java\jdk\v1.8.0_60\bin\java -Xmx512m -Xss2M -classpath C:\jython2.7.0\jython.jar;. -Dpython.home=C:\jython2.7.0 -Dpython.executable=C:\jython2.7.0\bin\jython.exe -Dpython.launcher.uname=windows -Dpython.launcher.tty=true org.python.util.jython -m robot.run -b debug.log recursion.robot     & egrep -B3 "maximum recursion" debug.log | egrep -v "START KW| END KW"
==============================================================================
Recursion
==============================================================================
Passing Test 1                                                        | PASS |
Dummy Pass
------------------------------------------------------------------------------
Infinite recursion                                                    | FAIL |
maximum recursion depth exceeded
------------------------------------------------------------------------------
Passing Test 2                                                        | PASS |
Dummy Pass
------------------------------------------------------------------------------
Recursion                                                             | FAIL |
3 critical tests, 2 passed, 1 failed
3 tests total, 2 passed, 1 failed
==============================================================================
Debug:   C:\git\tmp_stuff\debug.log
Output:  C:\git\tmp_stuff\output.xml
Log:     C:\git\tmp_stuff\log.html
Report:  C:\git\tmp_stuff\report.html
20151014 07:10:43.655 - INFO - started KWs: 121
20151014 07:10:43.842 - FAIL - maximum recursion depth exceeded

[14.10.2015  7:10:47 C:\git\tmp_stuff\]
>
</pre>

**Comment by pekkaklarck** [comment]
It depends in what code the max recursion error occurs. If it occurs in a library keyword, Robot catches it like any other exception. If it occurs in Robot's own code, execution is likely to crash like in #551. Do you want to study that further or be fine with rising Robot's internal limit?

**Comment by yahman72** [comment]
okay, that makes the situation a bit different - but I still think that removing the internal limit would make sense because:
- There's no difference between Python and Jython: with jython 2.7 we hit python's max. recursion limit (with jython 2.5 we hit the stack size limit and that was much earlier than python's recursion limit)
- In a way it's okay to crash when python's max. recursion limit is reached: it's either a) bug in the library or KW implementation or b) somebody really needs more recusion depth

In case of a) the library/KW developer just needs to fix the bug

In case of b) it would be better to allow the developer to fix this by simply increasing the recursion depth with `sys.setrecursionlimit()` in his/her own library. Currently that developer would need to modify the RF code (= increase the internal limit) and increase the recursion depth with `sys.setrecursionlimit()`
Another possibility could be environment (or global) variable that could be used to override the default internal limit.

**Comment by pekkaklarck** [comment]
No, I don't want the internal limit to be removed if it can cause crashes. Debugging crashes like that is very annoying and I see no valid use cases to more than 100 started kws.

**Comment by yahman72** [comment]
okay, then I'll come up with a PR with the new limit 100.

**Comment by pekkaklarck** [comment]
After thinking this a bit more, please submit a new issue about raising the limit and refer this issue in it.
