### ISSUE TITLE
TestSuit dependency resolving

### ISSUE THREAD

**Issue by stasiek** [robotframework/robotframework#1964]
## Motivation
While working with an awfully complicated tests that have been abandoned by their author I've wasted *tons* of time on fighting their dependencies. **This had to be done manually** which is even worse since **robotframework** is about automatisation.

## Problem
Currently there is no mechanism for test dependency resolution: libraries, robot resources, other resources.

## Solution
I propose two ideas. Both would need some way to be called maybe pybot --dependencies maybe some separate name for it.
Additionally version incompatibilities should be detected pre test run.

Maybe a `--dryrun` extension? I think it would go nicely with #1936. 

### 1st solution: inline
Since external resource imports are explicit we could modify the syntax of all imports
for example:
```robotframework
Library  SSHLibrary  @{LIB_ARGS}  ${LIB_VERSION}  ${LIB_LOCATION}
Resource  keywords.robot   ${RES_VERSION}  ${RES_LOCATION}
```
I'm aware it would make the imports uglier, so maybe some another way. It's just an idea.

### 2nd solution: import file
Yeah...Header files are evil and oh-so-not-pythonic but hear me out.
What if we left library/resource versions and locations in a specified file that would be looked into upon imports problem (missing/wrong version).
It wouldn't make the test file less readable and would be easy to parse.

**Comment by stasiek** [comment]
Depending on type of location it might look like
```
pip://somewhere.over.the/rainbow/LibraryName
ftp://bla.nab.bah/ResourceName.all
sftp://101.133.710.1/far/away/file
git://github.com/busyloop/lolcat/blob/master/bin/lolcat
```

It would be valuable to use custom pypi server addresses.

**Comment by guykisel** [comment]
If you use pip, requirements.txt files already have support for declaring dependencies in git repos, custom pypi servers, and so on.

For example: https://pip.pypa.io/en/latest/reference/pip_install.html#vcs-support

**Comment by pekkaklarck** [comment]
Unfortunately I didn't fully understand the motivation nor the proposed solutions. Could you @stasiek please clarify? Notice that we need to be very careful with any kind of syntax changes to avoid backwards compatibility issues.

**Comment by stasiek** [comment]
@pekkaklarck I've just been in a situation where a set of tests were needed to be run; but those tests were done 'once upon a time' by some 'guy' and they were run from his machine only (so no environment).
Now his old team needed to run those tests. There was no information about dependencies needed since there are only names in test files. It took lots of time to dig through multiple test repos just to locate those. Then even more time to find the right versions.
So this Issue came from my frustration because @WojtekKowaluk and I spent quite some time just to put those together.

Tomorrow I'll check if pip would be enough (thanks for mentioning it @guykisel).
Now I'm having second thoughts about this idea. : S

**Comment by pekkaklarck** [comment]
Ok, I got the motivation. This kind of issues are typically best solved outside RF core either by tooling used with Robot or by common guidelines and documentation. That doesn't mean we couldn't enhance this somehow in Robot itself if there are good ideas how.

**Comment by pekkaklarck** [comment]
Closing this because pip seems to handle the original needs pretty well.
