### ISSUE TITLE
Support yaml files as first class variable file

### ISSUE THREAD

**Issue by boakley** [robotframework/robotframework#1965]
We use dictionaries a lot on our team. We have created a variable file that lets us initialize dictionaries from YAML files, and we use a subclass of dictionary that supports dot notation. My testers love this. For example, I can define the variable `${LoginPage.user_details.username}` with this yaml file:

```
# LoginPage.yaml
user_details:
  username: id=usernameField
  password: id=passwordField
```

Right now we load this up as a variable file like this:

```
*** Settings ***
| Variables | YamlVariables.py | LoginPage.yaml
```

I would love for the yaml file to be a first class object in robot so that I could do this:

```
*** Settings ***
| Variables | LoginPage.yaml
```

If you think you might be willing to include this in the core, I'll create a pull request.

**Comment by pekkaklarck** [comment]
This sounds like a good idea to me. How do others see it?

Is there only one way a given yaml file can be interpreted? Would it always be so that top level items create variables and nested variables are objects with child value as attributes?

**Comment by boakley** [comment]
Is there only one way a yaml file can be interpreted? Yes. You can have
multiple top level items, if I understand what you're asking. However, the
way I have it implemented, everything in the file is wrapped up in a single
variable named after the file. So, if your yaml file was this:

    foo: one
    bar: two

you would have a single variable named ${the_file}, with elements foo and
bar (eg: ${the_file.foo}, ${the_file.bar})

**Comment by pekkaklarck** [comment]
For me it would feel logical that file like

```
foo: one
bar: two
```
would create two variables `${foo}` and `${bar}`. Is this unacceptable for you @boakley? What do others think about this?

**Comment by pekkaklarck** [comment]
Were you planning to parse YAML with your own code or use [PyYAML](https://pypi.python.org/pypi/PyYAML) or some other third party module?

**Comment by boakley** [comment]
Yes, It's unacceptable to me. I think it would end up making tests that
were difficult to understand.

For example, consider this suite:

    *** Settings ***
    | Variables | MyVariables.yaml
    | Variables | MoreVariables.yaml

    *** Test cases ***
    | Example
    | Open browser | ${browser}

Now, where did ${browser} come from? MyVariables.yaml? MoreVariables.yaml?
There's no way to know.

Now, assume that you get a single variable named after the file:

    | *** Test cases ***
    | Example
    | Open browser | ${MyVariables.browser}

Now it is completely obvious where the browser is defined.

**Comment by boakley** [comment]
I use pyyaml. It has an MIT license so it's safe to use.

**Comment by pekkaklarck** [comment]
I understand the problem with not knowing where variable originate from, but that same problem exists already now with normal variable files and resource files. One YAML variable file creating just one variable would be highly inconsistent with how other variable files work, and would also require having multiple variable files when you need multiple variables. I don't think that is a good idea. Could you consider having a convention to just have one variable per file if that is important for you?

The problem with not knowing where variables originate from is itself something I hope we could fix somehow. Should we perhaps allow using resource/variable file name as a prefix like we allow library/resource name as a prefix with keywords? That is a subject to a separate issue, though.

**Comment by pekkaklarck** [comment]
PyYAML seems to be a good choice. I don't think we should vendor or have it as a required dependency, but rather have it as a runtime dependency similarly as docutils is a dependency for reST support.

**Comment by guykisel** [comment]
One possible alternative to PyYAML is to use JSON instead, since Python has a built in `json` module and JSON is pretty similar to YAML.

**Comment by boakley** [comment]
We find yaml to be superior to JSON for this task. For relatively
non-technical users (which is the bulk of our testers, unfortunately), JSON
has too much syntax -- you spend too much time making sure your braces and
brackets are balanced.

**Comment by pekkaklarck** [comment]
I agree with @boakley that YAML is more human readable than JSON. That's the main difference between them listed here too: http://www.yaml.org/spec/1.2/spec.html#id2759572

I wouldn't see a problem supporting both YAML and JSON as first class variable files, though.

**Comment by boakley** [comment]
Honestly, the idea of a convention of having one variable per file isn't
very appealing to me. I consider the whole yaml file to be a single object,
and the data within are attributes of that object. The model of having  the
file represent multiple objects seems counter-intuitive to me. Treating it
as a single object means that users don't have to worry about overwriting
existing variables, or overwriting variables from other yaml files. Each
yaml file creates its own namespace, making it nearly impossible to
unintentionally redefine variables.

I do see it as somewhat inconsistent with variable files, but I think this
is the better solution. My testers constantly struggle to know where a
variable comes from using the traditional mechanisms. This completely
eliminates that problem.

**Comment by pekkaklarck** [comment]
I understand your reasoning but nevertheless think one variable file creating just one variable file is not a good idea. As already noted, it would be inconsistent with how other variable files behave. Even more importantly, I can see many good use cases where being able to create more than one variable would be preferable. Finally, making it easier to see where variables come from is a problem that should be solved in a generic manner. YAML variable files behaving differently than other variable files could potentially even make that harder.

I totally understand if variable files creating just one variable is so important feature for you that you are not interested to implement a solution that behaves differently. Luckily it's easy for you to keep using the solution that works for you, and you could even publish it on PyPI for others to use. I see YAML (and JSON) variable file support so good idea in general that I can take a look at implementing them myself some time in the future.

**Comment by boakley** [comment]
How about this: instead of hanging this feature off of the "Variables"
setting, add a new setting for "Object" (or something similar). "Object"
would return a single object (typically a dict, but could be an arbitrary
python object). This way it wouldn't be inconsistent with variable files,
plus be more clear that it's only returning a single object.

    *** Settings ***
    | Object | foo.yaml   <- returns a single object named ${foo}
    | Object | bar.json   <- returns a single object named ${bar}
    | Object | baz.py     <- returns an instance of baz.baz()
    | Object | fizz.yaml | WITH NAME | fizzbuzz    <- returns a single
object named ${fizzbuzz}

With this, variable files can continue to be used as collections of
variables, but we now have a way to instantiate individual objects. The .py
variant would be a nice way to add page object support. I could see
supporting XML as well, with the object being an instance of ElementTree.

**Comment by pekkaklarck** [comment]
This new `Object` setting would be same as `Variables` except that it just exposes one variable, right? The work involved in adding a new setting is so big that it ought to also bring big benefits. In this case I don't see too much benefits compared to having a special variable file, like you already have, that does the same thing:

```robotframework
*** Settings ***
Variables    Object    foo.yaml
Variables    Object    bar.json
Variables    Object    baz.py
Variables    Object    fizz.yaml    WITH NAME    fizzbuzz
```

**Comment by edbrannin** [comment]
I'd love to have this built-in -- I'm doing something similar with a Python variables-file in my own test cases already (I can ask about sharing that code if it would be helpful)

My (not-quite-robustly-tested) `load_yaml.py` also uses [AttrDict](https://pypi.python.org/pypi/attrdict/1.2.0) to deep-wrap any dictionary values in the YAML it loads, so with this YAML:

```yaml
items:
    key: value
    more: stuff
```

I can look up its values like `${items['key']}` or `${items.key}`

**Comment by pekkaklarck** [comment]
I prototyped adding support for YAML variable files and it turned out to be very straightforward. The code would still need better error handling, acceptance tests, and documentation, but that wouldn't be too much work.

The prototype works like Python variable files so that, for example,

```yaml
foo: 1
bar: 2
```

would create two variables `${foo}` and `${bar}`. Being able to refer to variables using variable or resource file name as a prefix like `${varfile.foo}` (or perhaps like `${varfile::foo}` to distinguish this from extended variable syntax) would be useful feature in its own right, but that's something that all variables should support.

I know @boakley wouldn't be happy with this kind of implementation, but what do others think about it? Should I go ahead and finish the current prototype and commit it?

**Comment by boakley** [comment]
Consider this yaml file:

    foo:
      a: xyz
    bar:
      a: abc

How would I reference the value "abc"? Can I use dot notation, like
${bar.a}?  If yes, I think it looks great.

**Comment by pekkaklarck** [comment]
That's a very good question. The new `&{dict}` variables introduced in 2.9a1 are implemented as [dot-accessible dict](https://github.com/robotframework/robotframework/blob/master/src/robot/utils/dotdict.py) that supports accessing keys using attribute access like `${dict.key}`. I decided not to convert Python dicts created in normal variable files to dotdicts automatically, but that can be triggered by prefixing the variable with `DICT__` prefix or you can construct a `DotDict` instance in the code yourself. The reason I didn't want to convert dicts automatically was that in some cases you might really want to have an actual `dict` instance, so there should anyway be a way to avoid automatic conversion.

In YAML variable files you aren't really creating Python data types but rather defining data. In that context automatically converting nested mappings to `DotDict` instances would probably be a good idea, and that's actually what my prototype already does.

Good to hear that you Bryan like the current plans. I'll include this issue into 2.9a2 scope and finish the prototype when I have some extra time.

**Comment by edbrannin** [comment]
When you revisit this, could you also add support for JSON files?  That seems like it would be a pretty small change atop the YAML handling.

**Comment by pekkaklarck** [comment]
YAML file support ought to be done. Anyone willing to look do the docs added in 860848d make sense? Code review won't hurt either.

What should we do with JSON? YAML is so much more human-friendly than JSON that I don't see anyone creating variable files using the latter if the can use the former. It would be useful in situations where same JSON files are also used by the system under test, though.

Anyone interested to implement JSON support based on the YAML implementation? Should we include it in this issue or submit a new one?

**Comment by pekkaklarck** [comment]
Thanks @guykisel for doc review! I consider this issue ready now. If someone is interested in JSON support, please submit a separate issue and preferably also a pull-request.

**Comment by rama-bornfree** [comment]
Dear all,

Currently pyyaml does not support path concatenation, cud a custom tag be available for path concatenation based on

http://stackoverflow.com/questions/2063616/how-to-reference-a-yaml-setting-from-elsewhere-in-the-same-yaml-file

import yaml

## define custom tag handler
def join(loader, node):
    seq = loader.construct_sequence(node)
    return ''.join([str(i) for i in seq])

## register the tag handler
yaml.add_constructor('!join', join)

## using your sample data
yaml.load("""
paths:
    root: &BASE /path/to/root/
    patha: !join [*BASE, a]
    pathb: !join [*BASE, b]
    pathc: !join [*BASE, c]
""")
