### ISSUE TITLE
Inverted --suite and --test flags to exclude tests from being run

### ISSUE THREAD

**Issue by bjornfor** [robotframework/robotframework#1966]
(This is a feature request.)

I'm looking at the various flags to include/exclude test cases to run:

```
--suite (includes by suite name)
--test (includes by test name)
--include (includes by tag name)
--exclude (excludes by tag name)
```

It seems that tests can only be _excluded_ by tag. I for one would have use for being able to exclude by suite name. And possibly test name too.

It feels a bit odd that we're able to include tests in 3 "dimmensions" (suite, test, tag), but can only exclude in 1 of them (tag).

**Comment by pekkaklarck** [comment]
The main reason the are no negative versions of --test and --suite options is that nobody has needed them bad enough to implement them. It's more common to unselect a group of tests and tags with --exclude work great for that. If someone would provide a pull request with implementation, tests, and documentation, I would be happy go merge it, though.

**Comment by pekkaklarck** [comment]
There doesn't seem to be interest for this. Closing.
