### ISSUE TITLE
setting global/suite variable which starts with $ cannot succeed

### ISSUE THREAD

**Issue by mpc2008cn** [robotframework/robotframework#1968]
```robotframework
${variable}    get text    ***
set global variable    ${variable}
```

then I use it on other place.It said "Non-existing variable"
I found the logs below:

20150413 10:41:59.551 :  INFO : ${variable} = $59
20150413 10:41:59.552 :  INFO : ${59} = 59

It's so weird.2nd log should be "${variable} = $59"

**Comment by pekkaklarck** [comment]
Could you create a full example demonstrating this problem? If you include it inline in a comment, please use [syntax highlighting](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) to make it easier to read.

**Comment by pekkaklarck** [comment]
No new information in a month. Closing,
