### ISSUE TITLE
tidy.py

### ISSUE THREAD

**Issue by SiddheshS** [robotframework/robotframework#1973]
I want to know more about tidy.py, this tool used to 
1) Inline the comments with the code
2) Standardize the sections order
3) Make the spacing between keywords and parameters 4 spaces.
I could not find the exact code for trimming 2+ spaces to 4 spaces. what if we want to neglect 4+ spaces?
How we can achieve that?

**Comment by pekkaklarck** [comment]
Please read the section about Tidy from the User Guide. If you have further questions, please ask them on robotframework-users mailing list or some other forum. This issue tracker is for bug reports and enhancement requests.

**Comment by SiddheshS** [comment]
Thanks for the replay.

Can't you treat it as a enhancement. I am writing a small text file for robot framework in which i use more than 4+ spaces to make my keywords as well as variables aligned, but using tidy it again trim it to 4 space which i think incorrect. after trimming it makes it unreadable or messy.
I know its designed just like this but really i think for more than 4+ space tidy.py should ignore it.

**Comment by pekkaklarck** [comment]
With the current design Tidy doesn't know the original source formatting so it cannot preserve it. I don't think that's going to change in the foreseeable future because Tidy uses Robot's parsing modules and Robot doesn't need that formatting.
