### ISSUE TITLE
Could not import Java keyword into RIDE and get it into use

### ISSUE THREAD

**Issue by nguyenthiphuong2** [robotframework/robotframework#1974]
I got the following error message while running my java keyword from RIDE:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\jython2.7b4\Lib\runpy.py", line 170, in run_module
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "C:\jython2.7b4\Lib\runpy.py", line 104, in _get_module_details
    if loader.is_package(mod_name):
AttributeError: 'ClasspathPyImporter' object has no attribute 'is_package'

My RF installation details
- window 7 - 64bit
- python-2.7.9
- jython2.7b4
- java 7 (jdk1.7.0_75)
- latest RF and RIDE

My step details:
1. Create SampleKeywordLibrary.jar and store it at C:\jython2.7b4\Lib\site-packages
2. Set Classpath= C:\jython2.7b4\Lib\site-packages\SampleKeywordLibrary.jar
3. Open RIDE and Import SampleKeywordLibrary as below
*** Settings ***
Library           SampleKeywordLibrary

*** Test Cases ***
test
    hello    world
4. From RIDE select execution profile=jybot and run

Could anyone please help me figure out what I went wrong. Thank you.

**Comment by nguyenthiphuong2** [comment]
Here is my java file content 

package org.robot.sample.keywords; 
public class SampleKeywordLibrary {
    public static final String ROBOT_LIBRARY_SCOPE = "GLOBAL";    
    public static final String ROBOT_LIBRARY_VERSION = "1.0.2";
    private int counter = 0;

    public int count() {
        counter += 1;
        return counter;
    }

    public void clearCounter() {
        counter = 0;
    }
    
    public void hello(String name) {
        System.out.println("Hello, " + name + "!");
    }
}

**Comment by laurentbristiel** [comment]
[Robot Framework Mailing List](https://groups.google.com/forum/#!forum/robotframework-users) is more appropriate to ask question about problems you encounter. Here is more for raising issues feature or bug request.

**Comment by pekkaklarck** [comment]
Laurent is right. This tracker is also for Robot Framework itself and the problem was with RIDE.

**Comment by nguyenthiphuong2** [comment]
Thank you for your very quick feedback. I've just posted this to robotframework-ride issue tracker site.
