### ISSUE TITLE
Compiling embedded arguments regexp failed ValueError: ('unsupported operand type', 'at')

### ISSUE THREAD

**Issue by siegcollado** [robotframework/robotframework#1975]
Hi, I keep on getting this weird error whenever the second test suite of my execution is run, 

```
Creating user keyword 'Some suite setup' failed: Compiling embedded arguments regexp failed: ValueError: ('unsupported operand type', 'at')
```

However, if I only run the second test suite, it doesn't show any errors.

Here is a brief sample of my keyword structure:
Test suite 1
```robotframework
*** Settings ***
Resource  ${PATH_TO_RESOURCE_FILE}
Suite Setup  Some suite setup

*** Test Cases ***
Test 1
  [Tags]  same-tag
  Resource keyword
```

Test suite 2
```robotframework
*** Settings ***
Resource  ${PATH_TO_RESOURCE_FILE}
Suite Setup  Some suite setup

*** Test Cases ***
Test 2
  [Tags]  same-tag
  Resource keyword

```

Resource file
```robotframework
*** Settings ***
Resource  ${PATH_TO_PAGE_OBJECT_FILE}

*** Keywords ***
Some suite setup
  Set Suite Variables  ${SUITE_VARIABLE}  value

Resource keywords
  Object keyword ${with embedded arguments}
```

Page object resource file
```robotframework
*** Settings ***
Resource  ${LOW_LEVEL_KEYWORDS_PATH}

*** Keywords ***
Object keyword ${with embedded arguments}
  Keywords here...
```

Is there any page where I can see any guidelines for writing/importing keywords with embedded arguments? This is the first time I've used them, and I feel I am doing something wrong with them.

**Comment by pekkaklarck** [comment]
I don't understand how your example could fail like that. Could you please create a simple executable example demonstrating the problem so that I can run it on my own machine?

See the User Guide for more details about embedded args:
http://robotframework.org/robotframework/#user-guide

**Comment by siegcollado** [comment]
Closing this, as this is related to an external library that I am using.
