### ISSUE TITLE
Support programmatic modifications of test data and results as part of normal execution

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#1976]
There are many command line options to alter the parsed test suite structure before executing it. You can, for example, use `--name` and `--doc` to set new name and documentation, respectively, or use `--test`, `--suite`, `--include` and `--exclude` to select which tests to execute. There are, however, sometimes needs for custom modifications.

For example, a team at Nokia recently wanted to way to run only every Xth test in one test run. This isn't supported using any command line options, but programmatically Robot's [public APIs](http://robot-framework.readthedocs.org/) make the basic implementation pretty simple:

```python
import sys
from robot.model import SuiteVisitor
from robot.running import TestSuiteBuilder

class RemoveEveryXthTest(SuiteVisitor):

    def __init__(self, x):
        self.x = int(x)

    def start_suite(self, suite):
        suite.tests = list(suite.tests)[::self.x]

if __name__ == '__main__':
    path, x = sys.argv[1:]
    remover = RemoveEveryXthTest(x)
    suite = TestSuiteBuilder().build(path)
    suite.visit(remover)
    suite.run()
```

A problem with the above solution is that it only runs tests and doesn't create logs and reports, but that would be pretty easy to implement too. A much bigger is that this script doesn't take same arguments as `pybot` does, and handling all same arguments would be a really big task.

A pretty simple but generic and powerful solution would be allowing registering visitors like `RemoveEveryXthTest` above to be used after parsing tests but before running them. This could work similarly as when registering listeners that get notifications during test execution:

    pybot --visitor RemoveEveryXthTest:2 tests.robot

The `:2` part of the the visitor name would specify arguments passed to the visitors `__init__` same way listeners accept them.

**Comment by pekkaklarck** [comment]
Things to consider:

- We probably want make it possible to give actual visitor instances, not only visitor names, to `robot.run` and `TestSuite.run`. This support is currently planned for listeners in #1969.

- Probably also want to support semicolon as an alternative argument separator similarly as with listeners (#1866).

**Comment by boakley** [comment]
Would this function run exactly once before the tests start running?

Instead, what about making it possible to define a function to be called immediately before running each test? That function could return True or False, and if False, that test is skipped? That would let you do everything described in this feature, plus allow dynamic skipping of tests.

**Comment by pekkaklarck** [comment]
Yes, this is executed once before execution. There are also other use cases than dropping certain tests.

I think modifications during execution are better done using the listener API. It obviously needed to be enhanced somehow to make dropping tests possible.

**Comment by zephraph** [comment]
So, using this interface could you programmatically build suites/tests? That would be extremely cool and something I've wanted to be able to do for a while. 

Also, skipping tests/changing the results of a test should definitely be doable from the listener interface.

**Comment by pekkaklarck** [comment]
You can build tests already now, but then you need to also take care of running tests, creating logs, etc. This API is planned to allow pre-run modifications so that execution etc. would be like normally.

**Comment by zephraph** [comment]
Right, that's more what I mean. I know I can build them, but it's very cumbersome to add them in to normal test execution.

**Comment by pekkaklarck** [comment]
What should the command line option to enable this be called? `--visitor` I used in earlier examples is too generic. My best idea so far is `--prerunvisitor` or `--previsitor`.

**Comment by boakley** [comment]
It's going to be used to initialize the test run, so something along the
lines of "--init" or "--initfunc" or "--initializer" makes sense to me.

**Comment by pekkaklarck** [comment]
I think `--init` is a bit too generic. The current implementation uses `--prerunvisitor`, but that visitor part doesn't really tell much. Perhaps something like `--prerunmodifier` would be better. It's pretty long, but options can be shortened (e.g. `--prerun`) when used  as long as they are unique.

I've also been thinking should we add similar `--postrunmodifier` to allow modifying results before logs and reports are created. It could also be used with Rebot, so perhaps it should be `--prerebotmodifier` in both sides.

**Comment by zephraph** [comment]
Sounds good to me.

**Comment by boakley** [comment]
--prebot and --postbot?

--bryan

**Comment by pekkaklarck** [comment]
The commit above (32e2a04) added support for custom result modifications. Command line options are now `--prerunmodifier` and `--prerebotmodifier`. Both User Guide and `--help` documentation missing but otherwise this functionality ought to be ready. This is a very powerful new feature!

Command line option names can still be updated if someone comes up with really good alternatives. I kind of like Bryan's `--prebot` and ` --postbot` but don't think they are generic enough. Especially the latter would be strange when used with Rebot.

**Comment by pekkaklarck** [comment]
Here's an example of a modifier that selects only every Xth test. It would work both with `--prerunmodifier` and `--prerebotmodifier`.

```python
from robot.model import SuiteVisitor


class RunEveryXthTest(SuiteVisitor):

    def __init__(self, run_every_xth, start_from=0):
        self.run_every_xth = int(run_every_xth)
        self.start_from = int(start_from)

    def start_suite(self, suite):
        suite.tests = suite.tests[self.start_from::self.run_every_xth]

    def end_suite(self, suite):
        suite.suites = [child for child in suite.suites
                        if child.test_count > 0]
```

**Comment by pekkaklarck** [comment]
This issue is now ready for review. Especially new docs committed in ce4d5fa (visitor API docs),  b26a664 (User Guide) and 54ad854 (--help) should be proof-read.

Review by anyone is more than appreciated, but I leave it for @jussimalinen to close this issue when he's reviewed the changes.

**Comment by jussimalinen** [comment]
Looks good.

**Comment by davekipfer** [comment]
Could you please clarify what this change currently supports?  You say at one point that this occurs once before exceution, but then you mention the Listener interface needs to be enhanced.  Does that mean that a keyword/test/suite listener can now make modifications on a listener event, or is that something tied to a different enhancement, or something not yet captured?

**Comment by pekkaklarck** [comment]
This functionality is documented in the User Guide:
http://robotframework.org/robotframework/2.9/RobotFrameworkUserGuide.html#programmatic-modification-of-test-data

Could you @davekipfer take a look at it and see is it adequate? If it isn't, please submit a new issue and tell what you don't understand and we'll enhance docs.
