### ISSUE TITLE
Where to file an installation issue? 

### ISSUE THREAD

**Issue by gigaimage** [robotframework/robotframework#1977]
Hi,

I am not sure where to file an installation issue, so posting the log message here (only once).

Python install: Python 3.4.2 (v3.4.2:ab2c023a9432, Oct  6 2014, 22:16:31) [MSC v.1600 64 bit (AMD64)] on win32
Both Python.exe and script folders are configured in system path env.

From command prompt : pip install robotframework

Log message: 

 Ignoring link https://pypi.python.org/packages/source/r/robotframework/robotframework-2.9a1.tar.gz#md5=018ccc926223131325bc413ba02b2ffb (from https://pypi.python.org/simple/robotframework/), version 2.9a1 is a pre-release (use --pre to allow).
  Using version 2.8.7 (newest of versions: 2.8.7, 2.8.6, 2.8.5, 2.8.4, 2.8.3, 2.8.2)
  Downloading from URL https://pypi.python.org/packages/source/r/robotframework/robotframework-2.8.7.tar.gz#md5=42a38054fb24787e6d767e0a96315627 (from https://pypi.python.org/simple/robotframework/)
  Running setup.py (path:C:\Users\<User_Name>\AppData\Local\Temp\pip_build_<User_Name>\robotframework\setup.py) egg_info for package robotframework
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "C:\Users\<User_Name>\AppData\Local\Temp\pip_build_<User_Name>\robotframework\setup.py", line 45
        for directory in 'rebot', 'libdoc', 'testdoc', 'lib', 'common'
                                ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "C:\Users\<User_Name>\AppData\Local\Temp\pip_build_<User_Name>\robotframework\setup.py", line 45

    for directory in 'rebot', 'libdoc', 'testdoc', 'lib', 'common'

                            ^

SyntaxError: invalid syntax

----------------------------------------
Cleaning up...
  Removing temporary dir C:\Users\<User_Name>\AppData\Local\Temp\pip_build_<User_Name>...
Command python setup.py egg_info failed with error code 1 in C:\Users\<User_Name>\AppData\Local\Temp\pip_build_<User_Name>\robotframework
Exception information:
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\pip\basecommand.py", line 122, in main
    status = self.run(options, args)
  File "C:\Python34\lib\site-packages\pip\commands\install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "C:\Python34\lib\site-packages\pip\req.py", line 1229, in prepare_files
    req_to_install.run_egg_info()
  File "C:\Python34\lib\site-packages\pip\req.py", line 325, in run_egg_info
    command_desc='python setup.py egg_info')
  File "C:\Python34\lib\site-packages\pip\util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command python setup.py egg_info failed with error code 1 in C:\Users\<User_Name>\AppData\Local\Temp\pip_build_<User_Name>\robotframework

**Comment by guykisel** [comment]
I think this is because you are running Python 3.x and Robot Framework does not yet support 3.x - https://github.com/robotframework/robotframework/issues/1506

Have you tried installing with Python 2.x?

**Comment by pekkaklarck** [comment]
Yes, Robot Framework doesn't officially yet support Python 3. There is a friendly Python 3 compatible fork, though.
