### ISSUE TITLE
Windows Installer

### ISSUE THREAD

**Issue by zephraph** [robotframework/robotframework#1980]
I'd like to see/help write a standalone windows installer for robotframework.

Is this something the core team wants to see? Would anyone like to support me on this effort?

**Comment by pekkaklarck** [comment]
First of all, this discussion originates from here:
https://github.com/rtomac/robotframework-selenium2library/issues/55#issuecomment-96036843

Based on the linked discussion, the question is about creating a standalone installer for Robot Framework and set of most important libraries and tools. I can see that it would be useful in environments not connected to the Internet, but there are several non-trivial problems in creating such an installer and maintaining it. I already listed some of these problems in the linked discussion, but here are they again:

- How to select what are the most commonly used libs and tools.
- How to handle binary dependencies (pycrypto w/ SSHLibrary, browser drivers with Se2Lib, etc.)
- Installer needs to be updated every time new version of any package or package dependency is released.
- All users may not want to have latest versions of all packages.
- 32bit vs 64bit Windows.
- Other operating systems.

These aren't impossible problems to solve, but they require someone spending time to come up with a good solution and also maintaining it in the future when there are new releases of included projects. The core team isn't interested on it, but we definitely have nothing against someone else taking this responsibility.

Notice that this issue has been discussed several times in the past. Unfortunately I'm too busy right now to search earlier issues here or earlier discussions on robotframework-users. Notice also that someone actually implemented an installer like this a year or few ago, but I don't know what is it's current status nor even remember where it is/was available. I think it never got mature enough to be listed on robotframework.org.

If I was to implement an installer like this, I would investigate using pip as the actual installer. It can install source distributions downloaded to a machine like `pip install package.tar.gz`, so it would be possible to get quite far by just having all needed packages bundled together into a zip file or similar.

Finally, this issue isn't directly related to Robot Framework core and thus actually invalid in this issue tracker. I close this issue but that doesn't mean you shouldn't create this kind of an installer if you think it is valuable. It would probably be a good idea to start a discussion on the mailing list to see what others think and see could you get someone else to work with you. Searching archives to find more about the earlier installer attempts before that would probably be a good idea too.
