### ISSUE TITLE
libdoc tool support reStructuredText format output

### ISSUE THREAD

**Issue by huangzhizhong** [robotframework/robotframework#1981]
Now we use a web service that can render html to show all test libraries documentation, because all the documentations must be convert to html format.

i hope we can use directly gitlab or github to display all test libraries dcoumentation. so there are two solutions:

   * gitlab or github support to render html
   * libdoc can support reStructuredTextformat output, and gitlab or github now support render reStructuredText format as html

**Comment by pekkaklarck** [comment]
Could you please explain a bit more thoroughly how this should work in practice?

Notice that Libdoc already now supports reST as input format. Couldn't you just use that and let your external tools render reST docs directly?

**Comment by huangzhizhong** [comment]
@pekkaklarck Thanks for your reply.

I use [gitlab](about.gitlab.com) for my test libraries source code management, issue tracking, code reviews.
I want to publish my test libraries documentation on gitlab, unfortunately, gitlab can render reST but can not render html. 

So I have to install another web server to show libraries documentation, just as apache http server.

A test library documentation can output a html file by libdoc tool, and i think it can output a reST file easily.

**Comment by pekkaklarck** [comment]
I'm not sure have I understood this correctly, but I don't think Libdoc could realistically convert docs e.g. in Robot's own documentation format to reST. If docs already are in reST, the we obviously could just output them as-is, but I don't know how much benefits what would give. Most of the value in Libdoc outputs is in its HTML formatting, and I don't see how we could change that to reST.

Do you have a concrete idea how reST output should work in practice? Would you be willing to implement such functionality yourself and provide a pull request.

**Comment by pekkaklarck** [comment]
I don't think implementing this enhancement is feasible.
