### ISSUE TITLE
PYTHONPATH environment variable should not be processed with Jython or IronPython

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#1983]
Currently we add entries in PYTHONPATH environment variable to `sys.path` regardless of the Python interpreter. This is a bit wrong because Jython and IronPython themselves use JYTHONPATH and IRONPYTHONPATH, respectively. Using the standard environment variables would be better and it would also be automatically done by the interpreter.

The main reason to change this would be that it seems [Jython 2.7 on Windows will mask PYTHONPATH](http://bugs.jython.org/issue2343). PYTHONPATH not working consistently would be annoying, so it would probably make more sense to drop special PYTHONPATH manipulation altogether. That would be backwards incompatible, but luckily using JYTHONPATH and IRONPYTHONPATH works also with older Robot versions.

The main benefit of using PYTHONPATH regardless the interpreter is that you only need to set one environment variable even if you were using multiple interpreters. If this is an often needed functionality, we can consider adding something like ROBOTPATH that we can always process ourselves.

**Comment by pekkaklarck** [comment]
@jussimalinen, could you review the doc changes in 7003198? This issue ought to be ready otherwise.

**Comment by jussimalinen** [comment]
looks good! This be done.

**Comment by krasoffski** [comment]
>  If this is an often needed functionality, we can consider adding something like ROBOTPATH that we can always process ourselves.
Hi,

We quite often used this functionality because our libraries were placed in different file system paths.  
Of course, we can specify
```
pybot -P ./ -P ~/lib 
```
but approach with ROBOTPATH will be very useful/helpful. 

Thank you.

**Comment by pekkaklarck** [comment]
You can also use `-P .:~/lib` to specify all locations in one go. Alternatively you can set `PYTHONPATH`, `JYTHONPATH` or `IRONPYTHONPATH` environment variable, depending on are you using Python, Jython or IronPython. What this issue changed was that `PYTHONPATH` is not used anymore when using Jython or IronPython.

**Comment by krasoffski** [comment]
Thank you,

Also I have one more question.
Following code has been removed from RF so it means that current directory (where we launch pybot) is no longer in the path where RF searches libs. Is it correct?
```
from robot import pythonpathsetter as _
add_path('.', end=True)
```

**Comment by pekkaklarck** [comment]
Yes, execution directory isn't anymore added to `sys.path` automatically either. See #2019 for details.

**Comment by nao921** [comment]
@pekkaklarck 
my code was on RF 2.8.6 and --pythonpath /some_path/ worked
just tried to upgrade to RF 2.9RC1 and the above no longer is working because of this particular change.

is there anyway thru command line options to set jythonpath to get it working on 2.9RC1?

**Comment by pekkaklarck** [comment]
This change affects only the `PYTHONPATH` environment variable, not the `--pythonpath` command line option. The latter ought to work exactly like it used to also with Jython and IronPython. It probably would have been a good idea to rename this to `--robotpath` or something similar. Can still consider that in the future releases.

What you are seeing may be caused by the execution directory not being added to the module search path automatically (#2019). If that's not the case and you are sure you have encountered a regression, please submit a new issue with explanations how to reproduce the problem.

**Comment by nao921** [comment]
@pekkaklarck indeed. it's good once i include currently directory thru --pathonpath command line option. Thanks.
