### ISSUE TITLE
Avoid Python 3 incompatible type checks

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#1990]
Although RF 2.9 is not planned to support Python 3, we want to turn the code as much Python 3 compatible as possible to ease maintaining the [friendly Python 3 compatible fork](https://pypi.python.org/pypi/robotframework-python3). We already dropped Python 2.5 support (#1928) in alpha 1 to make it easier to write Python 2 and 3 compatible code, and we also want to avoid Python 3 incompatible type checks.

In practice current `isinstance(item, basestring)` and similar checks will be turned to `is_string` utils that have different implementation on different Python versions. There's already PR #1988 implementing this and we hopefully can merge it before alpha 2.

**Comment by pekkaklarck** [comment]
PR #1988 has been merged and some fixes done to the code afterwards. This issue is done.

**Comment by userzimmermann** [comment]
Thanks again for merging and closing this topic. Makes merging for #1506 much easier :) But I would reopen this issue for continuing with converting `isinstance` checks in the tests...

**Comment by pekkaklarck** [comment]
If you only have changes to tests, just submit a PR. Otherwise you can open a new issue.
