### ISSUE TITLE
User Guide has outdated links to test templates

### ISSUE THREAD

**Issue by laurentbristiel** [robotframework/robotframework#1997]
In the User Guide, the section ["Test data templates"](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#test-data-templates) links to Google Doc that will [sunset in January 2016](http://google-opensource.blogspot.fr/2015/03/farewell-to-google-code.html). Should we move those template to GitHub or just remove this section altogether?

**Comment by pekkaklarck** [comment]
Templates themselves are already in GitHub under `templates` directory and they are included into the User Guide distribution too. We just haven't yet moved old wiki pages from Google Code to GitHub. These templates are pretty useless nowadays when HTML and TSV formats aren't used that much, but keeping them around doesn't really cost us anything either. Should we just update the link in the User Guide to point to https://github.com/robotframework/robotframework/tree/master/templates?

**Comment by laurentbristiel** [comment]
I find the templates useless as well. I don't think many people use them. I vote to remove them (and the section mentioning them in the User Guide).

**Comment by HelioGuilherme66** [comment]
I think that keeping the templates and changing the link is the best
solution. (remove only if there is a cost in maintaining them updated)

On Mon, May 18, 2015 at 11:01 PM, Laurent Bristiel <notifications@github.com

**Comment by pekkaklarck** [comment]
I think we should keep the templates at least in RF 2.9. Would you @laurentbristiel be willing to create PR fixing the link in the User Guide?
