### ISSUE TITLE
`--ExitOnFailure` does not work if test/suite setup/teardown fails

### ISSUE THREAD

**Issue by Tattoo** [robotframework/robotframework#2004]
As the title says, if a test case setup fails, the following test cases are run even though --exitonfailure command line flag has been used.

Here's a failing example:

```
# run with --exitonfailure
*** Test cases ***

TC
  [Setup]    Fail    hello world
  No operation

TC2
  No operation
```

**Comment by pekkaklarck** [comment]
It's surprising that nobody has noticed (or at least reported) this earlier. Looking at the code the same problem occurs also with test teardowns. Luckily both of these seem to be pretty easy to fix but will obviously need some tests.

There's also a related problem that if a suite setup or teardown fails when `--exitonfailure` is in use, tests in the subsequent suites are run even if the failed suite would contain critical tests. Fixing the problem with suite setups shouldn't be hard but with suite teardowns it can be more problematic.

**Comment by pekkaklarck** [comment]
Fixing the problem with suite teardown wasn't that complicated either. I have fixes and tests ready but will still see could I refactor related code a little before pushing.
