### ISSUE TITLE
Installation throw invalid syntax issue

### ISSUE THREAD

**Issue by jbkrishna** [robotframework/robotframework#2005]
C:\Users\bjayaram>pip install robotframework==2.9a1
Collecting robotframework==2.9a1
  Downloading robotframework-2.9a1.tar.gz (397kB)
    100% |################################| 401kB 413kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\bjayaram\AppData\Local\Temp\pip-build-4nq38mo5\robotframework\setup.py", line 44
        for directory in 'rebot', 'libdoc', 'testdoc', 'lib', 'common'
                                ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\bjayaram\AppData\Local\Temp\pip-build-4nq38mo5\r
obotframework

**Comment by pekkaklarck** [comment]
Are you using Python 3?

**Comment by jbkrishna** [comment]
yes. 
C:\Users\bjayaram>python
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (Intel)] on win32

**Comment by pekkaklarck** [comment]
Robot doesn't officially support Python 3 yet. You can either install Python 2.7 or use [unofficial fork](https://pypi.python.org/pypi/robotframework-python3).
