### ISSUE TITLE
PyUnit

### ISSUE THREAD

**Issue by mattben** [robotframework/robotframework#2011]
Can I write my PyUnit test with the robot framework as well?

**Comment by pekkaklarck** [comment]
How would you like to write them?

**Comment by mattben** [comment]
I'd like to write my normal pyunit class file `test.py` https://gist.github.com/mattben/90a9efd71dadc561dfd8

and then call it with test.txt
https://gist.github.com/mattben/cd432b1b9a821688a99a

where the function name is the keyword pretty much just having robot run all our test for us

**Comment by pekkaklarck** [comment]
I guess that could work. Did you test it? If it doesn't work out-of-the-box, implementing a library that handle PyUnit somehow shouldn't be too complicated.

**Comment by mattben** [comment]
Okay will try thank you
