### ISSUE TITLE
How can I make the case when I found error in a thread?

### ISSUE THREAD

**Issue by jufei** [robotframework/robotframework#2012]
hi:
   I wrote a TA case, in the case, I wrote a keyword to start a thread, in the thread, it would do some check continuously and I with when the thread find some error, the test case will be failed immediately.

So I raise an exception in the thread when error happened.

But when the exception happened, the case did not stop running.

So my question is: how can I stop the case running in a thread which was created by main process of pybot.

Thanks.

**Comment by pekkaklarck** [comment]
Questions like this are generally better asked on robotframework-users mailing list. Here's anyway two point instructions how to proceed:

- Child threads should communicate with the main thread about failures.
- You need a keyword that is run normally on the main thread that can report errors child threads have noticed.

See also https://github.com/robotframework/robotbackgroundlogger and #1882.
