### ISSUE TITLE
libdoc should handle Returns

### ISSUE THREAD

**Issue by djmille1** [robotframework/robotframework#2013]
`libdoc` evaluates the `[Arguments]` tags in a resource file and displays them in the Arguments column of the Keywords section.  Could it not also do the same for the `[Return]` tags?

Currently, the user is dependent upon well written documentation or code inspection to determine this.

Keyword | Arguments | Returns | Documentation
--- | --- | --- | ---
**Open Connection** | *host, alias=None, port=22* | *${index}* | Opens a new SSH connection to the given host and port.|
**Split String** | *string, separator=None, max_split=-1* | *@{substrings}* | Splits the string using separator as a delimiter string. |
**Get Points** | *label* | *${NumPts}, @{Coordinates}* | Examines the polygon with the specified *label* and returns the number of points and a list of those points' coordinates |

At least it should be able to determine the order and number of scalars and lists that are returned, e.g.

Keyword | Arguments | Returns | Documentation
--- | --- | --- | ---
**Open Connection** | *host, alias=None, port=22* | *scalar* | Opens a new SSH connection to the given host and port.|
**Split String** | *string, separator=None, max_split=-*1 | *list* | Splits the string using separator as a delimiter string. |
**Get Points** | *label* | *scalar, list* | Examines the polygon with the specified *label* and returns the number of points and a list of those points' coordinates |

**Comment by pekkaklarck** [comment]
It shouldn't be hard to show whatever value a user keyword has in its `[Return]` setting, but I'm not sure how well that would actually work in cases like these:

```robotframework
*** Keywords ***
Example 1
    ${something} =    Get something
    [Return]    ${something}

Example 2
    Run Keyword And Return    Get something
```

In the first example the value `${something}` wouldn't actually tell much, and in the latter case return is implemented using a keyword, not `[Return]`, and detecting that would be more work.

Even if we agreed that showing the return value is a good idea, I don't like the idea to dedicate a separate column for them. I wouldn't mind having them at the end of the documentation, though.

Any comments from others?

**Comment by aaltat** [comment]
I like the idea of getting the return value in keyword documentation. Currently I am writing the ags and return values in the keyword documentation, so that I get all in one place. For me documenting the return values in the keyword documentation is also good to go.

**Comment by pekkaklarck** [comment]
Is someone interested in investigating this further? A pull request with a working example would be best, but just specifying how to represent return values in the documentation would be a good start. Do you have ideas how to get information about return values from keywords implemented in Python?

**Comment by djmille1** [comment]
@pekkaklarck - I agree, ```${something}``` is not very useful - I would expect a sensible variable name, just the same as I would expect good documentation.  But I don't always get what I expect!

Also, w.r.t. ```Run_Keyword_and_Return```, good catch.  I guess you would have a similar issue with ```Return_From_Keyword```, and would have to parse for those as well as ```[Return]``` tags.

RE Python, I'm pretty much a Python noob, but I did find [this](https://docs.python.org/2/reference/simple_stmts.html#return), which indicates that there should be a way to parse this out.

@aaltat and @pekkaklarck, regarding the documentation format.  I have no preference for the html doc, but I think it would be nice if the XML handled them separately.  I am working on an MBSE approach to testing, where the library of keywords and their args and returns would be available in the model.  We have a tool that we developed that will consume libdoc's XML output to synchronize our keyword libraries to the model.  Currently we rely on there being the word "Returns" in the ```<doc>``` content, and we found will produce a _single_ output pin on our keywords object.  It would be preferable to have one pin per return, as it is with each ```<arg>```.

**Comment by pekkaklarck** [comment]
1. I'm OK with `[Return]` information being added to documentation somehow in HTML format. Could someone create a pull request so that we could see how it would work in practice?

2. I'm also fine with return value information being separately available in XML specs.

3. Python has `return` statement but I don't think there's any way to dynamically inspect its value. It could obviously be parsed from the source code, but because Libdoc currently doesn't parse source (it gets all information dynamically) that would be a really big task. Functions also often have multiple conditional `return` statements, which makes parsing the code non-trivial.

**Comment by pekkaklarck** [comment]
Is anyone interested enough about this functionality to implement or at least prototype it?

**Comment by pekkaklarck** [comment]
Closing due to lack of interest. Can be reopened if someone is willing to work on this.
