### ISSUE TITLE
2.9a2: Resource file does not exist

### ISSUE THREAD

**Issue by molsky** [robotframework/robotframework#2017]
Upgraded from 2.9a1 to 2.9a2 and after that all our tests are failing because for some reason RF fails with finding resource files that exists in right place (relative path).
`| FAIL | Resource file 'resources/environment.robot' does not exist.`
Installed version 2.9a1 back and everything works fine with it. 

OSX: 10.9.5
Python: 2.7.9

**Comment by pekkaklarck** [comment]
Is the path relative to the file where the resource is imported or is relative to a directory in PYTHONPATH? We changed handling PYTHONPATH (#1983) but that should only affect Jython and IronPython.

**Comment by molsky** [comment]
Relative to the file where the resource is imported.

Maybe I was too quick with this ticket.
The problem is with `Import Resource` keyword. We have our own high level keywords in `resources/keywords.robot'` file and one of the keywords there tries to import `environment.robot` variable file that is located in same folder with `resources/environment.robot'` path. 
Seems like now path handling is working correctly with alpha 2. Changed file path from `resources/environment.robot'` to `environment.robot'` and now it works with alpha 2 and with alpha 1 it fails because it can't find that file with path `environment.robot'`. But I can't find any mentions from release notes that there have been done changes to this.

**Comment by pekkaklarck** [comment]
Did I get it right that the second path was wrong, `resources/environment.robot` when it should have been `environment.robot`, and with the correct path import works both with a1 and a2? That might still be related to PYTHONPATH changes. I think we don't anymore add the execution directory (`.`) to the module search path automatically. Is `resources/environment.robot` relative to the directory where you run tests from?

**Comment by molsky** [comment]
`resources/environment.robot` works with alpha 1 and earlier versions but fails with alpha 2
`environment.robot` fails with all versions.

`resources/environment.robot` is relative to the directory where tests are run.

Folder structure.
![folder](https://cloud.githubusercontent.com/assets/1943521/8031239/7c669ca2-0dd5-11e5-87ea-071e2c82d1af.png)
So we are importing `environment.robot` file from `keywords.robot` file and they are in `resources` folder and tests are run inside from `our_tests` folder.

**Comment by pekkaklarck** [comment]
Above you wrote:

> Changed file path from `resources/environment.robot'` to `environment.robot'` and now it works with alpha 2.

but then added:

> Edit: And it fails still with alpha 2 even with the `environment.robot'` path.

I assume the latter statement is true and neither version works with alpha 2?

If `resources/environment.robot` is relative to the directory where tests are run, the change that broke importing it is likely that `.` is not added to PYTHONPATH automatically. You could verify that by setting `PYTHONPATH=.` before running tests.

Are you importing resource files in both places using `Import Resource` keyword? A limitation of that keyword is that paths relative to the directory where the file itself is are not supported. That would explain why `environment.robot` won't work in any version. A workaround is using `${CURDIR}/environment.robot` instead.

**Comment by molsky** [comment]
I did some assumptions and after I sent that message did the actual testing. Neither version works with alpha 2.

I set `PYTHONPATH=.` and now it works with alpha 2 when the path is `resources/environment.robot`.

Only place where `Import Resource` keyword is used is  in `keywords.robot` file. That your workaround suggestion seems like a best option so I am going to use it. Thanks.

**Comment by pekkaklarck** [comment]
OK. In your `keywords.robot` using

    Import Resource    resources/environment.robot

or

    Import Resource    environment.robot

can only work if the used path is relative to a directory in PYTHONPATH. Earlier the former worked because `.` was in PYTHONPATH but that was a coincident. A much better solution is using `${CURDIR}/environment.robot`.

You could also consider explicitly adding `resources` to PYTHONPATH to make it possible to import anything there from anywhere with just the file name. This avoids the need to update resource import paths if you reorganize your test data and move files to new directories.

Anyway, I don't think there's anything in Robot that needs to be changed. The fact that `.` is not in PYTHONPATH needs to be documented in the release notes, though.

**Comment by pekkaklarck** [comment]
Added separate #2019 about `.` not being in PYTHONPATH anymore and also added a note about it to alpha 2 release notes under backwards incompatible changes.

Thanks for reporting the issue @molsky. Although there was no actual bug, it's good that this change is now better documented.

**Comment by Dmitry-Boyko** [comment]
Hello,
Looks like same issue observed.
Taking a course on udemy.com. Created project with 4 files in Resources folder. Run it, got issue for each file:

[ ERROR ] Error in file '/Users/xx/Documents/workspace/robotscripts/Tests/access_tab.robot': Resource file 'Resources/Submenu_access.robot' does not exist.
==============================================================================
access tab :: This is some basic info about the whole suite               
==============================================================================
User must navigate to Access tab :: Clicking on all of the sub-men... | FAIL |
No keyword with name 'Tabs.Select Access Tab' found.
-------------------------------------------------------

**Comment by Swapnil-Tanpure** [comment]
Use relative paths for the resources.

For example, you should use:
Resource    ../Resources/testname.robot

**Comment by pyang-1981** [comment]
Why new version does not have backward compatibility. Poor testing.

**Comment by ChristanRTan** [comment]
hi all, I am also having the same issue. I cant import resource file with ride

![image](https://user-images.githubusercontent.com/7462742/44182781-fa0aff80-a13a-11e8-93ae-81eceb6184d5.png)
