### ISSUE TITLE
Tag patterns starting with `NOT`

### ISSUE THREAD

**Issue by jussimalinen** [robotframework/robotframework#2028]
Currently tag patterns can not start with `NOT`. It is possible to say `*NOTfoo`, which will match all tests that have some tag, but not `foo` (but it wont match tests without any tags). `NOTfoo` should match all tests not containing tag `foo`, even if the test has no tags.

**Comment by jussimalinen** [comment]
Pending a review still. If you could do the honours @pekkaklarck?

**Comment by pekkaklarck** [comment]
Looks good in general but added few comments. Can you look at them and see do you agree?

**Comment by jussimalinen** [comment]
NOTfooNOTbar matches is neither tag is present. This seems consistent with the way for example fooNOTbarNOTdar works: it matches if foo is present, but bar nor dar are.

**Comment by pekkaklarck** [comment]
Looks good.
