### ISSUE TITLE
When exiting gracefully, skipped tests should get automatic `robot-exit` tag

### ISSUE THREAD

**Issue by jussimalinen** [robotframework/robotframework#2029]
When pressing ctrl-c during test execution, or exiting the test run for some other reason like fatal error, the skipped tests should get an automatic tag like rf-exit and the generated report should automatically get `NOT rf-exit` tag statistics combination to see all tests that were not skipped.

**Comment by pekkaklarck** [comment]
I'm starting to think would `robot-` prefix be better than `rf-`. I liked `rf:` that we planned to use initially, but understand that it is very complicated from the command line with tag patterns etc. where the colon is a separator.

With a hyphen possible future tags like `robot-continue-on-failure` would, in my opinion, read,better than `rf-continue-on-failure`. We also use `ROBOT_` prefix with special exceptions (e.g. `ROBOT_CONTINUE_ON_FAILURE`) and `robot_` with library keyword attributes (e.g. `robot_name`).

What do you think @jussimalinen?

**Comment by jussimalinen** [comment]
I agree, `robot-` is more consistent with the attributes. I will change that.

**Comment by pekkaklarck** [comment]
Code, docs, and tests look good and the feature seems to work great also in practice! I'll do few cleanups to atests but I'll close this already now.

**Comment by pekkaklarck** [comment]
Noticed that `robot-exit` is not added if execution stopped due to a failure (`--exitonfailure`) or error (`--exitonerror`). Especially the former is very useful in combination with `--dotted`.
