### ISSUE TITLE
Notify listeners about library, resource and variable file imports

### ISSUE THREAD

**Issue by stasiek** [robotframework/robotframework#2030]
A new listener method that gets events when something is imported is needed.

> It must be possible to separate library and resource import and also get notification about variables. We could have separate library, resource and variables methods, but it's probably better to have imported method that gets the import type as the first argument. The listener API already has output_file method that works similarly.
> copied from: https://github.com/robotframework/robotframework/pull/2026#issuecomment-112553868

**Comment by pekkaklarck** [comment]
Have you had time to look at this? We are going to release beta 1 on Friday and there's no time to get this included into it anymore. We try to get beta 2 or perhaps even rc 1 out next week. We thus need to get this implemented early next week to be able to also get #1936 in. I can also take a look at this myself after we've got other issues done.

**Comment by jussimalinen** [comment]
In order to track transitive imports from resource files, the imported-method will need as an argument the origin of the import (the file in which the import happens as a path) and then probably also it would be a good idea to include the path to the imported file as a source. With that information it should be possible to map a tree about the imports.

**Comment by pekkaklarck** [comment]
@jussimalinen, I reviewed the final version of code and tests and everything looked good. I did a little clean-up for tests in the previous commit, though, and also added docs a little earlier. Please review my changes and we pretty close to cal this issue done.

When writing docs, I noticed keys in attribute dicts consisting of multiple words have earlier used `wordstogether` style like `starttime` and `totaltests`. Should we be consistent and change new `original_name` to `originalname` or `origname`?

**Comment by jussimalinen** [comment]
Consistency is good, so I it should be changed. I would prefer `originalname`  over `origname`.

**Comment by pekkaklarck** [comment]
Yeah, let's use `originalname`.
