### ISSUE TITLE
Use `setuptools` for installation when available

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#2033]
Installing 2.9a3 with pip 7.0.3 produces this warning:

> DEPRECATION: Uninstalling a distutils installed project (robotframework) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.

Apparently we need to update our packaging somehow. Hopefully there's a solution that works with Python 2.6-2.7, Jython 2.7 and IronPython 2.7.

**Comment by jussimalinen** [comment]
It turned out that this warning only occurs if earlier installation was done with ``python setup.py install``. Therefore lowering the priority.
