### ISSUE TITLE
Remove GLOBAL_VARIABLES workaround for Selenium2Library

### ISSUE THREAD

**Issue by zephraph** [robotframework/robotframework#2034]
There was some issues with S2L using private API's that caused an incompatibility with RF 2.9a3. A [workaround](https://github.com/robotframework/robotframework/commit/75568dd61cd6e56d331d8e31d310ec83463d247e) was added to address this in 2.9a3, but with the release of 1.7.1 of the Selenium2Library this workaround is no longer required. 

The purpose of this issue is to serve as a general reminder to remove that work around in a future release.

**Comment by pekkaklarck** [comment]
Thanks @zephraph for submitting this issue and especially for the quick S2L 1.7.1 release. I added a section about compatibility with other projects to RF 2.9 release notes and explicitly mentioned S2L there.
