### ISSUE TITLE
Consistent usage of Boolean arguments in standard libraries

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#2038]
Many keywords in libraries distributed with Robot Framework accept optional flag-like arguments that are defined like `option=False`. How to enable such option depends slightly on the library. To make the situation more consistent, we have decided to use implement a generic utility function that all libraries can use that behaves like this:
- With non-string values, just return results of `bool(value)`.
- Consider empty string and strings `false` and `no` (case-insensitively) to be `False` and other strings `True`.

All libraries using the new utility will also need a generic documentation section explaining the usage.

Libraries to go through:
- [x] BuiltIn
- [x] Collections
- [x] DateTime
- [x] Dialogs
- [x] OperatingSystem
- [x] Process
- [x] Screenshot
- [x] String
- [x] Telnet
- [x] XML

**Comment by jussimalinen** [comment]
Telnet tests are now passing

**Comment by pekkaklarck** [comment]
All libraries gone though, new section added to the User Guide. This issue can be considered done.
