### ISSUE TITLE
Inconsistant behavior in Builtin.Evaluate with leading zeros

### ISSUE THREAD

**Issue by DVeautour** [robotframework/robotframework#2044]
Evaluate will raise: SyntaxError: invalid token (<string>) with some strings with a leading zero. For example, 01-07 parse cleanly; 08 and 09 raise an error. 

Seen on PC and Mac:
C:\robot>pybot --version
Robot Framework 2.8.7 (Python 2.7.9 on win32)
test$ pybot --version
Robot Framework 2.8.6 (Python 2.7.6 on darwin)

To reproduce, run this code. The last 2 lines will raise an error. The 2 lines above that show a valid workaround.

======================================

*** Settings ***
Documentation     The purpose of this test is to demonstrate a leading zero bug in the Builtin.Evaluate keyword.

*** Variables ***
${deviceDayMin1}=          01
${deviceDayMin2}=          02
${deviceDayMin3}=          03
${deviceDayMin4}=          04
${deviceDayMin5}=          05
${deviceDayMin6}=          06
${deviceDayMin7}=          07
${deviceDayMin8}=          08
${deviceDayMin9}=          09

*** Test Cases ***
This Is The First Test Case
    ${deviceDayMinOutOfRange}=    Evaluate          ${deviceDayMin1}
    ${deviceDayMinOutOfRange}=    Evaluate          ${deviceDayMin2}
    ${deviceDayMinOutOfRange}=    Evaluate          ${deviceDayMin3}
    ${deviceDayMinOutOfRange}=    Evaluate          ${deviceDayMin4}
    ${deviceDayMinOutOfRange}=    Evaluate          ${deviceDayMin5}
    ${deviceDayMinOutOfRange}=    Evaluate          ${deviceDayMin6}
    ${deviceDayMinOutOfRange}=    Evaluate          ${deviceDayMin7}
    ${deviceDayMinOutOfRange}=    Evaluate          ${deviceDayMin8.lstrip('0')}
    ${deviceDayMinOutOfRange}=    Evaluate          ${deviceDayMin9.lstrip('0')}
    ${deviceDayMinOutOfRange}=    Evaluate          ${deviceDayMin8}
    ${deviceDayMinOutOfRange}=    Evaluate          ${deviceDayMin9}

**Comment by pekkaklarck** [comment]
This is due to how numbers are handled in Python:

```python
Python 2.7.3 (default, Feb 27 2014, 19:37:34) 
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 00
0
>>> 01
1
>>> 07
7
>>> 08
  File "<stdin>", line 1
    08
     ^
SyntaxError: invalid token
```

The reason you can use leading zero with 0-7 is that the leading zero actually marks the number to be octal. There is no octal number `8` or `9` and thus `08` and `09` causes an error. Notice that with bigger numbers the result you get may not be what you expect either:

`` python
>>> 010
8
```

You probably could use something like `Evaluate    int('${var}')` to avoid this problem, but using `Convert To Integer` keyword is probably a much better idea.
