### ISSUE TITLE
Terminal/console layout not correct using TextDialogs

### ISSUE THREAD

**Issue by johanhe** [robotframework/robotframework#2046]
I am using robot framework 2.8.6 with a third party TextDialogs library for purely text based dialogs (https://code.google.com/p/robotframework-textdialogslibrary/).

Using the library stand-alone works fine and I am able to create a full screen text dialog (in my case a yes/no choice menu). However, when I import it as a library in a test case and call my dialog, the dialog appears on the left of the terminal (SSH terminal to a remote machine running the tests) after executing the test using pybot. I have tried the --monitorwidth option but this has no effect on the dialog.

Since the stand alone python code in the library works just fine, I suspect an issue in pybot. Do you provide support for this?

**Comment by johanhe** [comment]
![textdialog](https://cloud.githubusercontent.com/assets/10895256/8377532/5595b824-1c12-11e5-9bfb-45c1570e181f.jpg)

**Comment by pekkaklarck** [comment]
We don't unfortunately have time to investigate problems with integration to third partly libraries or tools Please contact the developers of TextDialogs and ask how it should work. If there's something that should be changed in Robot Framework itself to make it work better, please submit a new issue.
