### ISSUE TITLE
Tag is not added to the test case by using "Set tags" and "Fail" keywords

### ISSUE THREAD

**Issue by nguyenthiphuong2** [robotframework/robotframework#2048]
I tried to add tag "regression" to the test-case after it's fail but it did not work. From RIDE i did not see the tag "regression" is added to tags area. Please help me to figure out the issue.
Here is my script
*** Test Cases ***
test
    [Tags]    test
    ${test}    Evaluate    1==2
    Run Keyword If    '${test}'=='False'    Fail    test fail    regression
    Set Tags    regression

**Comment by laurentbristiel** [comment]
Hello,

when you use "fail" keyword, the second argument is a tag you can set to the test, so you don't need to use "set tags" in the next statement. I tried this test:
```robotframework
*** Test Cases ***
test
  [Tags]  test
  ${test}  Evaluate    1==2
  Run Keyword If    '${test}'=='False'    Fail    test failed    regression
```
=> I do get the tag "regression" on the test

Side note: please use [Robot Framework Users Mailing List](https://groups.google.com/forum/#!forum/robotframework-users) to ask for help on your questions and raise an issue in GitHub only once you are confident you found a bug in the product.

**Comment by nguyenthiphuong2** [comment]
Thank Laurent, I use both keyword for sure if the bug from Fail or Set Tags.
So in your case, you saw tag "regression" is added? Could you please let me know your RIDE version?

**Comment by laurentbristiel** [comment]
> So in your case, you saw tag "regression" is added?
yes

> Could you please let me know your RIDE version? 
I am not using RIDE. I am looking at the report.html that is generated after test execution. Are you sure you are looking at the report/result of the execution? Don't expect the tag to be added on the test itself.. it is just a result/output thing.

**Comment by nguyenthiphuong2** [comment]
oh. So I misunderstood this keyword meaning. I thought of sort, it would add/remove tag from failed cases and then for the next execution I can run only these cases with assigned tag for a quick verification.
If it's for displaying on report only, could you let me know what's it actually usage? Thank

**Comment by laurentbristiel** [comment]
To understand the usage of tags, please report to the [User Guide section on tags](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#tagging-test-cases).

If you want to re-run the test that failed (for a quick verification), then what you want to use is [the --rerunfailed command line option](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#re-executing-failed-test-cases).

**Comment by nguyenthiphuong2** [comment]
I understand of usage of tag Laurent. But I do not understand the usage of setting tags in Fail keyword if it's for report only. Do you think it should actually add new/remove tag of the failed test-case?
And thank you for the suggestion of using re-executing failed.

**Comment by laurentbristiel** [comment]
> I do not understand the usage of setting tags in Fail keyword

"report only" is already very important. You may want to make some statistics on the different root cause of failures or whatever. Reports are important and having different/numerous tags is useful.

> Do you think it should actually add new/remove tag of the failed test-case?

No, we don't want the *source* of the test to be modified.

**Comment by nguyenthiphuong2** [comment]
OK. I'll use re-executing as a work-around solution. But the documentation of "Fail" or "Set tags" should be modified to make sure no one else will confuse like me.
You can close the issue. Thank.

**Comment by pekkaklarck** [comment]
@laurentbristiel is right, we definitely don't want to modify source files. Modifying tags dynamically at runtime is itself sometimes a useful feature.

**Comment by simplyviks** [comment]
Is there a way we can set the tags in the test source , so that next run i can call only the test cases .?
