### ISSUE TITLE
pybot command on Windows8 showing 'C:\Python27\python.exe: cannot import name is_dict_like'

### ISSUE THREAD

**Issue by sbhargav** [robotframework/robotframework#2053]
C:\Users\sbhargava>python --version
Python 2.7.9

C:\Users\sbhargava>pybot
C:\Python27\python.exe: cannot import name is_dict_like

**Comment by sbhargav** [comment]
C:\Users\sbhargava>rebot
C:\Python27\python.exe: cannot import name is_dict_like

**Comment by sbhargav** [comment]
C:\Users\sbhargava>jython
Jython 2.5.3 (2.5:c56500f08d34+, Aug 13 2012, 14:48:36)
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)] on java1.7.0_75
Type "help", "copyright", "credits" or "license" for more information.
>>> quit()

**Comment by pekkaklarck** [comment]
Installation seems to be broken somehow. Which Robot Framework version you are using? How did you install it?

**Comment by pekkaklarck** [comment]
No new info in 8 days. Closing.
