### ISSUE TITLE
'Else' is a reserved keyword

### ISSUE THREAD

**Issue by giri81** [robotframework/robotframework#2055]
I am getting error
***
'Else' is a reserved keyword
****
the code snipet goes as follows , can any guide me the resolution ?
    :FOR                ${key}                  IN                          @{keys}
    \                   ${item}=                Get From Dictionary         ${services}             ${key}
    \                   Run Keyword If          '${item}' == '1'            Log                     Service: ${key} is running
    \                   Else                    If '${item}' == '2'            Log
    \                   ...                     Service: ${key} is not running

**Comment by HelioGuilherme66** [comment]
You must use ELSE (not Else).

**Comment by pekkaklarck** [comment]
Yes, it must be `ELSE`, case-sensitively, and also it must be an argument to `Run Keyword If`. Now `Else` is used as a keyword.
