### ISSUE TITLE
Run Process on_timeout=kill not actually killing process

### ISSUE THREAD

**Issue by lespalt** [robotframework/robotframework#2056]
Hi,

I'm launching an external process with Run Process using a timeout (1 minute) and on_timeout=kill.  The process is faulty and hangs, so after a minute RF continues execution of the test suite as expected. However, the launched process is still running in the Task Manager.  This is on Windows 7, RF 2.8.7.

Thanks!

**Comment by pekkaklarck** [comment]
- Are you using Python, Jython or IronPython? Which version?

- Do you run the process directly or do you use a batch file or something else that starts the real process?

- Have you studied what Process library docs say about stopping processes under different circumstances?

**Comment by lespalt** [comment]
This is with Python 2.7.10.  There's no batch file involved but I'll have to do some investigation before I can be 100% sure whether it's launching any child processes.  But according to the docs it seems like both with and without child processes it should work as expected? I there any advantage to using Start/Wait/Terminate rather than Run Process (the docs seem to indicate it boils down to the same in terms of how a timed out process is killed).

Btw, is there a way to set Run Process's timeout parameter to the timeout set for the current test case?

**Comment by pekkaklarck** [comment]
From the docs:

> On Windows forceful kill only stops the main process, not possible child processes.

If you set test timeout using a variable, you can then use the same variable as a timeout also elsewhere. Most likely you want to have a timeout that is a little shorter than the test timeout.

**Comment by lespalt** [comment]
I will double check about the child processes next week. I was referring to this sentence from the Process docs that made me believe it wouldn't be an issue: 

"Terminating also possible child processes, including using CTRL_BREAK_EVENT on Windows, is new in Robot Framework 2.8.5."

Perhaps I didn't interpret that right ?

The variable approach would probably work. It would be more straightforward though if you could just refer to the current test timeout, e.g. with a ${TEST_TIMEOUT} built in variable. Any chance that could be added?

Thanks for a great tool.

**Comment by pekkaklarck** [comment]
Yes, terminating child process with `CTRL_BREAK_EVENT` is new in 2.8.5. That doesn't matter in your case, because you used `kill` which doesn't use it internally.

I guess `${TEST TIMEOUT}` variable could be added. Especially if someone submit a pull request with code, tests and docs.

**Comment by lespalt** [comment]
So to get the ctrl break behavior I would have to use 'terminate', right? But then there are situations where that is not enough and 'kill' is required. So is the most reliable way to make sure everything gets killed to do Start/Wait/Terminate/Terminate with one of the Terminate calls using 'kill=False' and the other 'kill=True' ? I guess even that wouldn't cover 100% of the cases, but should be better than just one ?

**Comment by pekkaklarck** [comment]
Why not just use terminate? Have you checked what library docs say about it?

**Comment by lespalt** [comment]
Because I didn't care for the extra 30 second wait. But either way the double terminate would hit that too, so just a single terminate should be fine as long as I'm not hitting the case where ctrl break doesn't cut it and it's a child process. Will need to confirm on Monday. Thanks for your help.

**Comment by lespalt** [comment]
Just to give an update on this, I did some more experiments, and it looks like the root of all evil was that I used test timeouts in combination with the timeout parameters on the Process functions. For some setups, the test timeout was set to the same as for the Process calls, and I assume that could lead to e.g. Run Process being interrupted before it got a chance to do its process-killing work (?). Perhaps that's something the documentation should warn about. Perhaps hitting the test timeout should also do an implicit Terminate All Processes?

I'm now using Run Process with on_timeout=terminate, and it seems to be working fine so far.

**Comment by pekkaklarck** [comment]
I don't think we should do anything automatically if a timeout occurs. There are teardowns for explicit cleanup activities.

I don't think documenting that test timeout can stop Run Process is a good idea either. The same problem occurs with all keywords that timeouts stop before they finish. The documentation of timeouts can be enhanced to make that more clear, though. If you have concrete ideas how to enhance it, please submit a separate issue.

Good that using terminate instead of kill and avoiding too short test timeouts works.
