### ISSUE TITLE
"Resource file does not exist" errors in 2.9b2 (regression as fine in 2.8.5)

### ISSUE THREAD

**Issue by markwinspear** [robotframework/robotframework#2058]
Since upgrading from version 2.8.5 to 2.9b2 to check out the new reports (note, I also upgraded the Selenium2Library so that it is compatible with that version), when executing tests, I am getting an error on executing my tests:
Resource file 'foo' does not exist

My Resource files are in the project directory under Resources/Common.robot (for example)
and are called in my Tests/Amazon.robot file in the *** Settings *** section with the code
Resource  Common.robot 
(also tried Resource  Resources/Common.robot with the same result

i have un-installed 2.9b2 and re-installed 2.8.5 and confirmed that the issue goes away

Project files - https://github.com/markwinspear/layered-sauce-start 

Can you please look into what has caused this?

**Comment by HelioGuilherme66** [comment]
I think you should use relative paths for the resources, from the test
suite path.

For example, you should have:
Resource    ../Resources/Common.robot # necessary for Setup & Teardown
Resource    ../Resources/Amazon.robot # necessary for lower level keywords
in test cases
and in ../Resources/Amazon.robot the paths are relative to the resource
file:

*** Settings ***Resource    ./PO/LandingPage.robotResource    ./
PO/TopNav.robotResource    ./PO/SearchResults.robotResource    ./
PO/Product.robotResource    ./PO/Cart.robotResource    ./PO/SignIn.robot

You could also use the ${CURDIR} referring to the test suite path.

**Comment by markwinspear** [comment]
Thanks very much @HelioGuilherme66 that solution works fine with 2.9b2.  Probably worth a documentation update under the breaking changes section though

**Comment by pekkaklarck** [comment]
The problem is most likely caused either #2019 or #1983. Both of them are already listed under Backwards incompatible changes in the release notes.
