### ISSUE TITLE
[2.9] Create Dictionary keyword prepends 'u' to keys and values

### ISSUE THREAD

**Issue by tkurdyna** [robotframework/robotframework#2060]
Here is my test:

*** Settings ***
Library        Collections
*** Test Cases ***
Test
    ${dict}=  Create Dictionary  key=value
    Log  ${dict}

In 2.8.6 I get:
13:51:07.076	INFO	{'key': u'value'}

In 2.9 I get:
13:53:56.571	INFO	{u'key': u'value'}

**Comment by pekkaklarck** [comment]
That `u` just denotes that keys and values are Unicode strings, not byte strings. If you look closely, you got `u` also in the value with 2.8.6. You only could create byte string keys when using `key=value` syntax with Create Dictionary then, but nowadays you get Unicode. That is definitely a feature, not a bug.

If you don't understand the difference between Unicode and byte strings, please study Python documentation about that topic.
