### ISSUE TITLE
Add note on test timeout vs process timeout to Process docs

### ISSUE THREAD

**Issue by lespalt** [robotframework/robotframework#2061]
See issue #2056 . I'd add something along these lines to the Run Process doc:

"Note that if a test timeout occurs before the process timeout has been reached, it may interrupt the Run Process keyword and thus not execute the on_timeout action completely. This may lead to processes not being terminated despite on_timeout being set to "terminate", for example. It is recommended to keep the Test Timeouts high enough to prevent them from interfering with processes that may time out."

**Comment by pekkaklarck** [comment]
As I commented in #2056, I don't think it is a good idea to document with each keyword that test timeout can stop it before it finishes. That's something you need to take into account when using timeouts in general.

Making this more explicit in the Timeouts section in the User Guide would be fine, though. If you think a note should be added there, please submit yet another issue about it. I'd especially appreciate if you could create a pull request adding the note.

**Comment by lespalt** [comment]
I never said it should be documented for each keyword. The interaction between test and process timeout isn't exactly intuitive, so it clearly makes sense to add more documentation somewhere. Remember that from the user's perspective, it's the Process keywords that display erroneous behavior, so it's those docs that the user will look into for help. Which is why a note concerning the interaction with other types of timeouts should be added there rather than in the test timeout docs.

**Comment by pekkaklarck** [comment]
My point is that test/keyword timeouts can stop any keyword. Timeouts can, for example, prevent files to be removed by `Remove File`, browser to be closed by `Close Browser`, etc. Documenting this possibility with all keywords makes no sense, but making this more explicit in documentation of timeouts themselves is a good idea.

When using `Run Process`, it ought to also be easy to see from the log file what has happened to the keyword. There's explicit message `Gracefully terminating process.` when a process is terminated and a message `Test timeout <timeout> exceeded.` if there is a timeout.

All this said, I understand it can be somewhat confusing that there are test/keyword timeouts and that there are totally unrelated timeouts used by Process library. If you can create a pull request explaining this better, I do'nt have anything against merging it.
