### ISSUE TITLE
Deprecate using same setting multiple times

### ISSUE THREAD

**Issue by adam-wypych** [robotframework/robotframework#2063]
I tried to get know how, what happen when in one test suite file co-exists few `Suite Setup` or just old version of setting name keyword executed on the very beginning of test -  `Suite Precondition` with new once `Suite Setup`, see example `RFsuite.robot` below:

```
*** Settings ***
Suite Setup             New 
Suite Setup             Old 

*** Test Cases ***
T1
                        Log     Test

*** Keywords ***
New
                        Log     "Running new"

Old
                        Log     "Running old"
```

I expected RF will take one of behaviour: 

<ul>
<li>that the last one declaration will be only used,</li>
<li>every setting keyword in sequence how they exists in file will be executed,</li>
<li>it will be an error or warning and information about problem.</li>
</ul>

What happen just supprise me - RF treat all other `Suite Setup` keywords and them arguments as an arguments for the first one keyword, so example above was equals to something like 

```
Suite Setup       New    Old
```

After test run I got only information that 'Keyword 'New' expected 0 arguments, got 1', which for ensure will be valid information for 

```
Suite Setup       New    Old
```

but not for test case presented above `RFsuite.robot`.

I didn't check other similary places in Setting table: `Suite Teardown`. `Test Setup`, `Test Teardown`, `Test Precondition`, `Test Postcondition`, `Test Template`, `Test Timeout` - where it could be the same situation.

**Comment by laurentbristiel** [comment]
Indeed, that is the way Robot works: basically when a setting is repeated multiple times, Robot parse the following lines as continuation of the first one.

So in the case of "Suite Setup" (and other setup/teardown), next lines will be arguments of the first statement (but it could be also another keyword if you use the AND to introduce a second keyword in the setup). In the case of "Force Tags", this is will just add other tags. In case of timeout, only the first value is kept.

Initially, I guess it was just a more explicit way to to "continue on next line" (in HTML files, there is no "..." needed, so first column is just empty).

So, today this:
```robotframework
*** Settings ***
Suite Setup    New 
Suite Setup    Old
````
is equivalent to
```robotframework
*** Settings ***
Suite Setup    New 
...            Old
````

Note that this can get a bit confusing when having interwoven lines like:
```robotframework
*** Settings ***
Suite Setup    keyword for setup
Force Tags    first tag
Suite Setup    argument for setup
Force Tags    second tag
````
I don't know what @pekkaklarck and @jussimalinen think about that. Should this be changed? or should it be better documented?

**Comment by adam-wypych** [comment]
Thanks for quick and valueable response, I am working with Robot few years and this is something new for me, btw could you show an example how use this ```AND``` I tried add it like this:

```
Suite Setup               New            AND         Old
```

but it gives me still and information that number of expected arguments is ```0```.

**Comment by pekkaklarck** [comment]
@laurentbristiel is right in his analysis. The support for continuing settings like this originates from the time before it was possible to continue lines using the `...` syntax. The main use case was specifying more tags than there were columns in HTML tables (the plain text format wasn't supported back then either), but for consistency the same approach worked also with other settings.

Nowadays this kind of continuation support makes no sense. It is especially confusing with setups/teardowns, as illustrated by the example in the original description,but also with tags `...` works better. To make matters even more inconsistent, `[Arguments]`, `[Return]` and `Metadata` are handled so that the last specify value overrides earlier and with templates values are concatenated into a single string.

We cannot obviously just remove this syntax because it is likely that someone still uses it. We need to deprecate it first, and because that looks pretty simple, we ought to be able to do that already in RF 2.9.

**Comment by pekkaklarck** [comment]
If you actually want to have a setup/teardown with multiple keywords without putting them into a user keyword, you can use `Run Keywords`:

    Suite Setup    Run Keywords    First    AND    Second    with    args    AND    Third

**Comment by adam-wypych** [comment]
Thanks for both of you guys for response. 
@pekkaklarck can you share what will be future Robot Framework behaviour in case of the twice occurs in example ```Suite Setup``` after it will be ```Deprecated```. Will it be an error or just warning and only last will be take place as final ```Suite Setup``` keyword?

**Comment by pekkaklarck** [comment]
My thinking is that it will be an error. Any reasons why not?

**Comment by adam-wypych** [comment]
@pekkaklarck I do not see any reason to be different :) thanks :+1:
