### ISSUE TITLE
Feature request: add ability to blacklist tests based on tag

### ISSUE THREAD

**Issue by lespalt** [robotframework/robotframework#2064]
It's often useful to "blacklist" tests, i.e. not execute them but still have them show up in the report (e.g. as "not run") so they don't fall through the cracks. Using --exclude doesn't work, because that hides the excluded tests from the report altogether. The most common workaround seems to be to mark the test as noncritical and make it fail using the "Fail" keyword, but that's not ideal and ambiguous... a failing noncritical test isn't the same as a blacklisted test.

This is somewhat similar to issue #812 (request for a "Skip" keyword), but I believe what I'm asking for is simpler. What's needed isn't a new keyword, but simply a command line option similar to --exclude, let's say --blacklist <tag>, which skips the affected tests and makes a note of that in the report.

Thanks!

**Comment by pekkaklarck** [comment]
Could you clarify how would blacklisting be different than skipping? For me they look exactly the same, and I'd definitely use the more common "skip" term.

Notice that the problem with skipping isn't adding a new keyword or command line option but rather how to present these tests in logs and reports, how they affect statistics, etc. For me the current pass/fail status and critical/non-critical separation has been enough, and I don't consider skipping that important. If someone is interested to design how it would work and also implement, test and document it, I won't have problems accepting the feature and merging a pull request.

**Comment by lespalt** [comment]
Right, the difference between this proposal and the skip keyword is indeed
just that one is a keyword and the other is tag-based selection on the
command line.  I used the term blacklist only because that's what I've
often encountered, but it doesn't matter if it's called skip or blacklist.

A keyword based solution would definitely work for us as well, though
personally I like the tag approach. A keyword feels more like something
that specifies the behavior of a test rather than a filter criterion.
Though I can see how a keyword would be more flexible, e.g. if you want to
decide at runtime whether to skip a test (though not sure if that's good
practice...). I also assumed that tags would be easier to do because it's a
pre-filter and very similar to --exclude, but sounds like that's not so.

I find skipping tests useful because it clarifies that someone triaged the
test and explicitly decided to exclude it from the run. A test being listed
as non-critical doesn't carry the same meaning, it implies that you're
running the test but don't care so much about the outcome. Also you have to
decide whether a non-critical test that e.g. can't run for some reason
(i.e. one you'd mark skip if the functionality existed) should show up as
failing or passing. Having it fail makes the report look more alarming than
it has to. Having it pass is even worse, it makes the report look like
everything ran correctly when really it didn't.

As for how the skipped tests affect the statistics, there are of course
many options, and I don't really see one standing out as clearly better
than the others. My guess is that one relatively simple way would be to add
a third state (PASS/FAIL/SKIPPED), and just treat it exactly like the
others, in all tables and statistics? Or even not count it against the
statistics at all, and just add another row in the main report page that
says "N tests skipped", with a link that takes you to the list of skipped
test names.  That's really all that's needed: the --exclude functionality
with the names of the excluded tests somehow visible in the report.
Perhaps --exclude can just be extended to provide that?

Thanks again for an awesome product.

**Comment by pekkaklarck** [comment]
OK, backlisting is just a different term for skip. I opened a separate issue about possible new SKIP status. Let's continue discussion there.

Changing how --exclude works is not an option.
