### ISSUE TITLE
Unable to import DatebaseLibrary onto my Maven project (Robotframework runs on JVM)

### ISSUE THREAD

**Issue by delipan** [robotframework/robotframework#2065]
I could not find maven dependency for https://github.com/ThomasJaspers/robotframework-dblibrary/ (Suggested via robotframework.org)
Therefore i downloaded the jars from the above link and manually imported the dblibrary-2-0.jar and dblibrary-2-0-server.jar

When i run a sample Database.txt which contains the following

*** Settings ***
Library         OperatingSystem
Library         DatabaseLibrary
*** Test Cases ***
Connect
        Connect To Database Using Custom Params  jaydebeapi  org.mysql.jdbcDriver  diliptest1  sa ${EMPTY}
        Execute SQL  create table testtable (myid integer not null primary key, name varchar(25))

I get the following error:

 Importing test library 'DatabaseLibrary' failed: ImportError: No module named DatabaseLibrary

Need Help! Thanks in advance!

**Comment by HelioGuilherme66** [comment]
Did you tried to run the Demo?
You consulted the project Wiki, right?
From there you can see that you must use Jython and jybot, and add the path to the JAR to CLASSPATH.
The example demo, import of the Library is like:
`Library    org.robot.database.keywords.DatabaseLibrary`

**Comment by delipan** [comment]
I have added the JAR file 'dblibrary-2-0.jar' to CLASSPATH, I have imported the Library as suggested by you : Library org.robot.database.keywords.DatabaseLibrary

But now i get the following 

Error in file '/Users/delipan.r/Downloads/Dilip_Robot/Database.txt': Importing test library 'org.robot.database.keywords.DatabaseLibrary' failed: ImportError: No module named robot

Traceback (most recent call last):
  None
PYTHONPATH:
  /Users/delipan.r/Downloads/Dilip_Robot/Complete-Robot-Runner-0.0.1-SNAPSHOT.jar/Lib/robot/libraries
  /Users/delipan.r/Downloads/Dilip_Robot/Complete-Robot-Runner-0.0.1-SNAPSHOT.jar/Lib
  /Users/delipan.r/Downloads/Dilip_Robot/Lib
  __classpath__
  __pyclasspath__/
  .
  /Users/delipan.r/Downloads/Dilip_Robot
CLASSPATH:
  Complete-Robot-Runner-0.0.1-SNAPSHOT.jar
[ ERROR ] Error in file '/Users/delipan.r/Downloads/Dilip_Robot/Database.txt': Importing test library 'jaydebeapi' failed: ImportError: No module named jaydebeapi
Traceback (most recent call last):
  None
PYTHONPATH:
  /Users/delipan.r/Downloads/Dilip_Robot/Complete-Robot-Runner-0.0.1-SNAPSHOT.jar/Lib/robot/libraries
  /Users/delipan.r/Downloads/Dilip_Robot/Complete-Robot-Runner-0.0.1-SNAPSHOT.jar/Lib
  /Users/delipan.r/Downloads/Dilip_Robot/Lib
  __classpath__
  __pyclasspath__/
  .
  /Users/delipan.r/Downloads/Dilip_Robot
CLASSPATH:
  Complete-Robot-Runner-0.0.1-SNAPSHOT.jar


Above is full error message i got, I am running the Database.txt file using the executable jar "Complete-Robot-Runner-0.0.1-SNAPSHOT.jar" with command

 java -jar Complete-Robot-Runner-0.0.1-SNAPSHOT.jar Database.txt 

What does not import the database library, i have also externally imported the dblibrary-2.0.jar in the project, also kept it in that CLASSPATH.

Why does it not recognise robot folder inside the  " dblibrary-2.0.jar" ?

**Comment by HelioGuilherme66** [comment]
So you made some progress?
I  think the important error is this:
>[ ERROR ] Error in file '/Users/delipan.r/Downloads/Dilip_Robot/Database.txt': Importing test library 'jaydebeapi' failed: ImportError: No module named jaydebeapi
(maybe adding jaydebeapi to CLASSPATH will solve?)

I would say that the dblibrary is an "abandoned" project, since:
- dated from 2012
- NO SOURCE CODE AVAILABLE!

I see that you are not running with jybot (Jython), where did you get Complete-Robot-Runner-0.0.1-SNAPSHOT.jar from? Obsolete?
(This is the current released version http://repo1.maven.org/maven2/org/robotframework/robotframework/2.8.7/)

I can't help you more with this, good luck.

**Comment by pekkaklarck** [comment]
This issue doesn't seem to have anything to do with Robot Framework core. Questions are better asked on robotframework-users or other such forums instead of this issue tracker in general.

I do agree with @HelioGuilherme66 that this DB library looks dead and abandoned. Should be removed from robotframework.org.
