### ISSUE TITLE
Robot file contains multiple keywords

### ISSUE THREAD

**Issue by uilianries** [robotframework/robotframework#2067]
When I execute pybot under a .rst file, I receive the follow error message:

Resource file 'Smoke.robot' contains multiple keywords matching name 'I send a data package from ${SECOND_INTERFACE} and MUST receive at ${FIRST_INTERFACE} and MUST NOT receive at ${THIRD_INTERFACE}':
    I send a data package from ${FIRST_INTERFACE} and MUST receive at ${SECOND_INTERFACE} and ${THIRD_INTERFACE}
    I send a data package from ${SECOND_INTERFACE} and MUST receive at ${FIRST_INTERFACE} and MUST NOT receive at ${THIRD_INTERFACE}

My Smoke.rst contains:

Test Cases
==========
Smoke/Self/Others
-----------------
Simple Smoke Test
################

.. code:: robotframework

*** Test Cases ***

   Simple Smoke Test
        [Tags]	smoke	self	others
        Given Switch ports ${GE_PORTS} are at VLAN ID ${VLAN_ID}
        When I send a data package from ${FIRST_INTERFACE} and MUST receive at ${SECOND_INTERFACE} and ${THIRD_INTERFACE}
        Then the egress packets from ${FIRST_INTERFACE} have a flood bridging
        When I send a data package from ${SECOND_INTERFACE} and MUST receive at ${FIRST_INTERFACE} and MUST NOT receive at ${THIRD_INTERFACE}
        Then the egress packets from ${SECOND_INTERFACE} have not a flood bridging
        But I send a data package from ${FIRST_INTERFACE} and MUST receive at ${SECOND_INTERFACE} and MUST NOT receive at ${THIRD_INTERFACE}, between ${AGING_INTERVAL} minutes, the egress packets have a flood bridging

.. code:: robotframework

    *** Settings ***

    Library            Smoke.py
    Resource        Smoke.robot

Then, my Smoke.robot is called. 
My Robot file contains:

*** Settings ***
Library         Smoke.py
Variables      Variables.py

*** Keywords ***

Switch ports ${GE_PORTS} are at VLAN ID ${VLAN_ID}
    Create vlan on switch  ${VLAN_ID}  ${GE_PORTS}

I send a data package from ${FIRST_INTERFACE} and MUST receive at ${SECOND_INTERFACE} and MUST NOT receive at ${THIRD_INTERFACE}, between ${AGING_INTERVAL} minutes, the egress packets have a flood bridging
    [Documentation]  The aging feature was not integrated in buildroot's recipe
    ${result} =  monitor aging  ${SOURCE_FIRST}  ${TARGET_SECOND}  ${AGING_INTERVAL}  ${TIME_INTERVAL}
    Should Be Equal  ${result}  ${True}

I send a data package from ${SECOND_INTERFACE} and MUST receive at ${FIRST_INTERFACE} and MUST NOT receive at ${THIRD_INTERFACE}
    send unicast  ${SOURCE_SECOND}  ${TARGET_FIRST}

I send a data package from ${FIRST_INTERFACE} and MUST receive at ${SECOND_INTERFACE} and ${THIRD_INTERFACE}
    send broadcast  ${SOURCE_FIRST}  ${TARGET_SECOND}

In this situation, have 3 keywords, that aren't equals, however start with the same words.  When the robot runs, it raise an error, that inform matching name.

I executed this same test an older version and runs fine.  

I'm calling a .rst file using the follow command:

$ pybot --loglevel DEBUG -d logs/smoke -T -b outputSmoke.txt tests/test/Smoke.rst

Inside at test.rst, there is the 

My version: Robot Framework Robot Framework 2.9rc1 (Python 2.7.6 on linux2)

**Comment by pekkaklarck** [comment]
Sounds like just would have multiple keyword implementations that match the keyword you used:
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#embedded-arguments-matching-too-much

Could you verify that? If that's not the case, could you try reformatting your the original description so that it is easier to study? Even better if you could create a simple executable example demonstrating the problem.

**Comment by pekkaklarck** [comment]
Closing due to lack of information. Can be reopened if we get more information and that information indicates there is something to be fixed.
