### ISSUE TITLE
java intergration run for python import module error

### ISSUE THREAD

**Issue by jaehokim00** [robotframework/robotframework#2070]
I have two python scripts that uses httplib2 and Json module and run with the pybot, it works fine

However, when I tried to use java  with a jar file that I created... have an issue... I tried to put the module path to the robotframework-2.8.7.jar   as jar -uf .. but still same issue comes back..  I need to have some suggestion what I need to do to make java command works ...?

java -Xbootclasspath/a:target/SegmentorHdfsTest-0.0.1-SNAPSHOT-jar-with-dependencies.jar  -jar robotframework-2.8.7.jar  -V profiles/QaInt.py  -i idsync_put_get idsync.robot
[ ERROR ] Error in file '/Users/jaehokim00/Documents/workspace/SegmentorHdfsTest/idsync.robot': Importing test library '/Users/jaehokim00/Documents/workspace/SegmentorHdfsTest/testlibs/RestLib.py' failed: SyntaxError: mismatched input 'as' expecting COLON (ssl.py, line 359)
Traceback (most recent call last):
  File "/Users/jaehokim00/Documents/workspace/SegmentorHdfsTest/testlibs/RestLib.py", line 1, in <module>
    import httplib2
  File "/Library/Python/2.7/site-packages/httplib2/__init__.py", line 68, in <module>
    import ssl # python 2.6
  File "/Library/Python/2.7/site-packages/httplib2/__init__.py", line 68, in <module>
    import ssl # python 2.6
PYTHONPATH:
  /Users/jaehokim00/Documents/workspace/SegmentorHdfsTest/robotframework-2.8.5.jar/Lib/robot/libraries
  /Users/jaehokim00/Documents/workspace/SegmentorHdfsTest/robotframework-2.8.5.jar/Lib
  /Users/jaehokim00/Documents/workspace/SegmentorHdfsTest/Lib
  __classpath__
  __pyclasspath__/
  .
  /Library/Python/2.7/site-packages
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7
  /Library/Python/2.7/site-packages/httplib2
CLASSPATH:
  robotframework-2.8.5.jar
[ ERROR ] Error in file '/Users/jaehokim00/Documents/workspace/SegmentorHdfsTest/idsync.robot': Importing test library '/Users/jaehokim00/Documents/workspace/SegmentorHdfsTest/testlibs/httpPost.py' failed: AttributeError: 'str' object has no attribute 'format'
Traceback (most recent call last):
  File "/Users/jaehokim00/Documents/workspace/SegmentorHdfsTest/testlibs/httpPost.py", line 9, in <module>
    import json
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 109, in <module>
    from .encoder import JSONEncoder
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 27, in <module>
    ESCAPE_DCT.setdefault(chr(i), '\\u{0:04x}'.format(i))
PYTHONPATH:
  /Users/jaehokim00/Documents/workspace/SegmentorHdfsTest/robotframework-2.8.5.jar/Lib/robot/libraries
  /Users/jaehokim00/Documents/workspace/SegmentorHdfsTest/robotframework-2.8.5.jar/Lib
  /Users/jaehokim00/Documents/workspace/SegmentorHdfsTest/Lib
  __classpath__
  __pyclasspath__/
  .
  /Library/Python/2.7/site-packages
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7
  /Library/Python/2.7/site-packages/httplib2
CLASSPATH:
  robotframework-2.8.5.jar
==============================================================================
Idsync                                                                        
==============================================================================
PUT VUID AND GET IT BACK                                              | FAIL |
No keyword with name 'Put Json' found.
------------------------------------------------------------------------------
Idsync                                                                | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed

**Comment by laurentbristiel** [comment]
I don't know the answer to you problem. But note that those questions don't belong in here but rather in the [User Mailing List](https://groups.google.com/forum/#!forum/robotframework-users).

**Comment by pekkaklarck** [comment]
You are using rf-2.8.7.jar which contains Jython 2.5. You try to use httplib2 under your Python 2.7 installation and that version uses syntax not compatible with Python/Jython 2.5. You may have better luck with rf-2.9rc1.jar that contains Jython 2.7. You can find the jar attached to 2.9 rc 1 release notes.

If you still got poblems,  mailing lists and other such foums are better suited for questions than ths issue tracker.
