### ISSUE TITLE
Console print problem with INFO log

### ISSUE THREAD

**Issue by davidherve** [robotframework/robotframework#2073]
Hi,

I have a little problem when I attempt to print INFO log on the console. i try to make INFO log like this:
![log](https://cloud.githubusercontent.com/assets/10501601/8903884/54e09686-345b-11e5-9e3a-a3607e2bfaa1.jpg)

During a function in the test library, in call my function to log a message:
![logcode](https://cloud.githubusercontent.com/assets/10501601/8903457/823488a2-3458-11e5-8f7f-3714035718db.jpg)

I expected this type of result:
![logtestexpected](https://cloud.githubusercontent.com/assets/10501601/8903553/30db5430-3459-11e5-996c-9ebddbcfc9d0.jpg)

But unfortunately I have two problems:
       -The name of the test case is automatically written before the first INFO log message.
       -I get a point at the beginning of every log message.

Here is my result:
![logtest](https://cloud.githubusercontent.com/assets/10501601/8903703/2a7676dc-345a-11e5-954b-1c63596d1544.jpg)

I have no problem with the log file generated automatically at the end of the process. Just with the console print!

any ideas? Thanks in advance for your assistance!

**Comment by jussimalinen** [comment]
The dots are generated by  monitor markers option.
See the commandline help:
                    -K --monitormarkers auto|on|off  Show `.` (success) or `F` (failure) on
                          console when top level keywords in test cases end.
                          Values have same semantics as with --monitorcolors.

In general if you dont want any printouts from robot on the console, just use --console quiet.

This isnt really a bug report. These sort of issues should be discussed in the users group. If you have further questions about logging and console, please ask them in the google users group.

**Comment by pekkaklarck** [comment]
I agree with everything Jussi wrote. Notice that `--console` option is new in RF 2.9, though.

**Comment by davidherve** [comment]
Ok, it's noted! Sorry for my mistake.

Thanks for your answer.
