### ISSUE TITLE
Release notes should be in code repository

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#2074]
Currently we use GitHub's [releases](https://github.com/robotframework/robotframework/releases) when writing release notes. They work fine with smallish releases, but with big releases like RF 2.9 what have long release notes there are problems:

1. Not possible to create table of contents. GitHub's Markdown doesn't support that automatically in general, but it isn't possible to create them manually either because headings don't create anchors.
2. No versioning.
3. Can only edit in a text area on a browser.
4. Notes are in GitHub itself making possible transition to other services harder.
5. We generally prefer reStructuredText over Markdown.

We can avoid all these problems by putting release notes under `doc/releasenotes` directory in reST format. We can then have shorter notes in GitHub's releases with a link to the actual release notes.

Tasks related to this:

- [x] Create a script to generate release notes templates based on the issues in the tracker and place it under `doc/releasenotes`. It can be based on the current Invoke tasks in `tasks.py`, but needs to be converted to use reST instead of Markdown. Having it as a standalone script makes `tasks.py` shorter and easier to maintain.
- [x] Update `tasks.py` to use the new standalone script.
- [x] As a test, create RF 2.9.1 release notes using the new approach.

Later we can convert also old release notes to the new format.

**Comment by jussimalinen** [comment]
We decided that tasks.py does not really need to call the generation script. It is enough to call that script directly.
