### ISSUE TITLE
How do I fix error “Invalid locator strategy: css selector” 

### ISSUE THREAD

**Issue by FGagneau** [robotframework/robotframework#2075]
I'm new to robotframework, I have just installed Python 2.7.9, wxpython2.8.1 unicode and ride 1.3 then appiumlibrary. When I run a test with the KeyWord "Click Element":

Click Element  id=fr.axa.soon.qa:id/subscription

I get an error message :

    WebDriverException: Message: Invalid locator strategy: css selector

I know it's not a css selector, but I'm on a native app and I don't understand why this isn't a AppiumDriver.

How do I fix this ?

**Comment by pekkaklarck** [comment]
This question is invalid here.

**Comment by FGagneau** [comment]
Why? When I do 'pybot _testAxa.txt' in commande line, I have the same error, so it's not a ride issue, but a robotframework issue.

**Comment by pekkaklarck** [comment]
1. This issue tracker is for bug reports and enhancement request. Questions belong to robotframework-users mailing list or other such forums.
2. This is issue tracker for Robot Framework core. You problem is related to AppiumLibrary that ought to have its own tracker.

**Comment by FGagneau** [comment]
Ok sorry.
