### ISSUE TITLE
Optional parameter to choose screenshot module.

### ISSUE THREAD

**Issue by mgladki** [robotframework/robotframework#2077]
Occasionally taken screenshots with wxPython fail on long runs, gtk seems not to have this problem.
Adding a parameter to choose which module should take the screenshot can fix it.

**Comment by pekkaklarck** [comment]
Sounds fine for me and shouldn't be too complicated to implement. I would assume it is enough to have this as a configuration parameter to the library and not have any separate keyword to alter it.

Anyone interested to provide a pull request?

**Comment by mgladki** [comment]
I'll take care of it.

**Comment by jussimalinen** [comment]
@mgladki what is the situation with this? We would hope to make 2.9.1 during next week if possible.

**Comment by jussimalinen** [comment]
Release will come out tomorrow most likely, so please make the pull request today if you want his included.
