### ISSUE TITLE
i had a perfectly working automation test but i am recieving following error

### ISSUE THREAD

**Issue by argunnn** [robotframework/robotframework#2081]
StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=44.0.2403.125)
  (Driver info: chromedriver=2.16.333243 (0bfa1d3575fc1044244f21ddb82bf870944ef961),platform=Windows NT 6.1 SP1 x86_64)

there were no problem in the css but in cs i have problem in click element. on a button but in 'ff' i am not recieving anything. could it be somekind of problem that is occured because of google chrome update ?

**Comment by pekkaklarck** [comment]
This issue tracker is for bug reports and enhancement requests related to Robot Framework itself. Selenium2Library has its own tracker but questions are better asked on robotframework-users mailing list or other such forums.
