### ISSUE TITLE
Libdoc document generation issue

### ISSUE THREAD

**Issue by Chaser** [robotframework/robotframework#2082]
Hello I am having issues creating documents of my python library with RF 2.8.7 

I have created a test repo to experiment with https://github.com/Chaser/robotlib

I have observed the following.

The package has the following layout
```
robotlib
|
|------  __init__.py
|------  moduleA.py
```
In the package `__init__.py`  I imported `from moduleA import *`

In `moduleA.py` I had a simple class and a few functions

```python
class moduleA(object):
    ROBOT_LIBRARY_SCOPE = 'GLOBAL'
    """Module A Class A.
    """

    def __init__(self):
        print 'This is Module A Class'
        pass

    @staticmethod
    def mod_class_a_method_a(self):
        """Does nothing."""
        pass

    def mod_class_a_method_b(self):
        """Does nothing."""
        pass


def module_a_fn_a():
    """Document Module A  Function A."""
    pass

def module_a_fn_b():
    """Document Module A  Function A."""
    pass
```

Now if I run python -m robot.libdoc robotlib list
```
robotlib
========
Scope:            global
Named arguments:  supported

initialization module.

Module A Fn A
-------------
Arguments:  []

Document Module A  Function A.

Module A Fn B
-------------
Arguments:  []

Document Module A  Function A.
```
Indicated that `moduleA.py` was imported correctly.

I am wondering why the class `moduleA` in `moduleA.py` was not imported.

**Comment by jussimalinen** [comment]
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#creating-test-library-class-or-module

You need to either import it robotlib.moduleA or change the name of package robotlib to moduleA. That is, classes are imported as libraries only if they match the entire path or the name of the imported module or package matches the class name.
