### ISSUE TITLE
Screenshot not included in logs on failure in RF2.9

### ISSUE THREAD

**Issue by deaglejv** [robotframework/robotframework#2083]
Previous stable release when any failure would happen a screenshot was included in the logs.  This is no longer happening and is a useful tool for determining why a failure happened.  The screenshots are being taken, but the link to the screenshot is not included in the logs.

Please add this feature back in.

**Comment by pekkaklarck** [comment]
This is Selenim2Library issue and thus invalid here. It might also be fixed already.
