### ISSUE TITLE
Process library Wait For Process keyword does not return when used with some adb commands

### ISSUE THREAD

**Issue by aaltat** [robotframework/robotframework#2085]
Ugh

I am using Robot Framework 2.8.7 (Python 2.7.6 on win32), on Windows 7 (64bit).

When I do this:
```
*** Settings ***
Library           Process

*** Test Cases ***
Example
    ${handle} =    Process.Start Process
    ...    adb
    ...    status-window
    ...    shell=yes
    ...    cwd=${OUTPUT_DIR}
    ${result}=    Process.Wait For Process
    ...    handle=${handle}
    ...    on_timeout=kill
    ...    timeout=15 s
```

Then the Wait For Process keyword hangs forever. I see this in the debug log (note removed the tilde characters from the log file keyword boundary because github did some fancy formatting): 
```
==============================================================================
20150804 10:49:34.472 - INFO - + START SUITE: Example [ ]
==============================================================================
20150804 10:49:34.473 - INFO - +- START TEST: Example [ ]
------------------------------------------------------------------------------
20150804 10:49:34.474 - INFO - +-- START KW: ${handle} = Process.Start Process [ adb | status-window | shell=yes | cwd=${OUTPUT_DIR} ]
20150804 10:49:34.474 - INFO - Starting process:
adb status-window
20150804 10:49:34.475 - DEBUG - Process configuration:
cwd = C:\workspace\system-test\tests
stdout_stream = -1
stderr_stream = -1
shell = True
alias = None
env = None
20150804 10:49:34.483 - INFO - ${handle} = 1
20150804 10:49:34.484 - INFO - +-- END KW: ${handle} = Process.Start Process (9)
20150804 10:49:34.485 - INFO - +-- START KW: ${result} = Process.Wait For Process [ handle=${handle} | on_timeout=kill | timeout=15 s ]
20150804 10:49:34.485 - INFO - Waiting for process to complete.
20150804 10:49:49.534 - INFO - Process did not complete in 15 seconds.
20150804 10:49:49.535 - INFO - Forcefully killing process.
```

The adb process is not killed and to recover I have manually kill the adb process. I did expect the adb process be killed after 15 and keyword not to hang forever. 

Adb is part of the Android SDK: http://developer.android.com/tools/adk/index.html

**Comment by pekkaklarck** [comment]
Sounds weird. Killing should definitely kill the process in all conditions. Sometimes the process is started by a wrapper and killing the wrapper doesn't kill the process, but in those cases `Wait For Process` should still return.

I have no idea why this problem occurs or is there any way to fix it. It would be great if you could test this with RF 2.9, although I don't remember there being much enhancements to the Process library since 2.8.7. After that it would be good if you could investigate this issue yourself. Reproducing it doesn't seem to be too easy, and I don't think I have a change to try it in the foreseeable future.

**Comment by aaltat** [comment]
I will try it also with 2.9 and I can run it with the debugger to see where it actually hangs.

If a miracle happens and I do find the reason for the issue and I am able to fixit, will you take pull request to 2.8 series?

**Comment by pekkaklarck** [comment]
We do not plan to make more 2.8 releases. They can be considered if there are critical bugs, but I don't consider this that urgent. Making a local fix shouldn't be hard for you if upgrading to 2.9 isn't possible. Should first find why this happens, though.

**Comment by pekkaklarck** [comment]
Have you tested using `terminate` instead of `kill`? See library docs for differences.

**Comment by aaltat** [comment]
Good point, I did only try with kill

**Comment by pekkaklarck** [comment]
You should also try redirecting stdout/stderr to files. There's a possibility that default streams get full and the process hangs.

**Comment by aaltat** [comment]
When adb is launch first time, as in my case it is, it will also launch ```adb server``` [1] in the background.  

On RF 2.8.7
1) The ```Terminate``` works as designed. The ```adb status-window``` process is terminated and ```adb server``` is kept running the background. 
2) ```kill``` hangs on robot\libraries\process.py line 785: ```return self._format_output(stream.read())```. 
3) Doing this almost works: 
```
*** Settings ***
Library           Process

*** Test Cases ***
Example
    ${handle} =    Process.Start Process
    ...    adb
    ...    status-window
    ...    shell=yes
    ...    cwd=${OUTPUT_DIR}
    ...    stdout=${OUTPUT_DIR}/log.log
    ...    stderr=STDOUT
    ${result}=    Process.Wait For Process
    ...    handle=${handle}
    ...    on_timeout=kill
    ...    timeout=15 s
```
The keyword returns but both ```adb server``` and ```adb status-window``` process are left running. 

In RF 2.9 result are same, but line number is 768: ```return self._format_output(stream.read())```.

As a summary: using force is not always good thing. But any idea, why the kill behaves badly on the _format_output?

[1] http://developer.android.com/tools/help/adb.html

**Comment by aaltat** [comment]
And this is how it looks when I run it from console:
```
D:\workspace\test\adb_and_process_lib>adb status-window
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
←[2J←[2HAndroid Debug Bridge
State: unknown
```
Those tiny arrows are really there, funny.

**Comment by pekkaklarck** [comment]
1. You shouldn't use `shell=yes`. It isn't a good idea unless you really need it in general, but here the started shell may actually interfere communicating with the process.

2. Looking at the commit logs, there doesn't seem to be any changes related to this between RF 2.8.7 and 2.9.

3. It would be great if you could try starting and terminating the process using the [subprocess module](https://docs.python.org/2/library/subprocess.html) directly. If that works, then the Process library does something stupid. That also allows you to play with different `Popen` configuration options. I'd especially recommend testing `close_fds=True`. Notice that, as explained in the docs, you cannot redirect `stdin`, `stdout` or `stderr` on Windows in that case.

**Comment by aaltat** [comment]
I will try with ```Popen``` options and lets see how that goes, but not today, it is time for some sleep.

**Comment by aaltat** [comment]
If I have similar setup, the ```adb server``` is not running and if I have this:
```
import subprocess
from time import sleep

f = open('C:\log.log')
p = subprocess.Popen(['adb', 'wait-for-device'], shell=True, stdout=f, stderr=subprocess.STDOUT)
print p.pid
sleep(5)
p.terminate()
f.close()
```

Or this: 
```
import subprocess
from time import sleep

f = open('C:\log.log')
p = subprocess.Popen(['adb', 'wait-for-device'], shell=True, close_fds=True)
print p.pid
sleep(5)
p.terminate()
f.close()
print 'Done'
```
Or any other combination of the Popen, which I could thing of. 
When I run the script from command line, it does not leave the python script hanging and the python scripts returns normally. I must say that the shell=True causes some problems, because also with Popen, there ```adb wait-for-device``` process does not die cleanly and must be manually cleaned.

So a a good workaround, from Robot Framework, is use ```on_timeout=kill``` and ```shell=False```. But what next? In my mind, this is a bug, but only a minor one.

**Comment by pekkaklarck** [comment]
Could you clarify what exactly is a bug?

**Comment by pekkaklarck** [comment]
Also, why do you use `shell=True`? That's `False` by default and I don't see any reason why you should enable it. In general there is very seldom need to use it on Windows. `subprocess` docs say this:

> The only time you need to specify shell=True on Windows is when the command you wish to execute is built into the shell (e.g. dir or copy). You do not need shell=True to run a batch file or console-based executable.

**Comment by aaltat** [comment]
1) Bug is that Robot Framework Wait For Process keyword hangs on certain combinations

2) I totally agree that shell=True is not needed.

Although it's a bug, in best case it's a minor one. Also when I did read the subprocess doc, it's clear that shell=True is not needed. Should we enhance the RF docs also to say similar things as the subprocess docs say?

**Comment by pekkaklarck** [comment]
Yeah, the keyword hanging is a bug. Processes possibly left running on the background wouldn't necessarily be.

What was the combination that hang? You originally reported using `on_timeout=kill` but later said that `on_timeout=kill` with `shell=False` is a good workaround? Was it `shell=True` that caused the whole problem? In that case I'd understand why the underlying process didn't die because killing just kills the started shell, hanging is still weird.

Adding a note that `shell=True` is very seldom needed on Windows is a good idea, especially if using that possibly causes problems. It's also a potential security risk, but that shouldn't be an issue with Robot.

**Comment by aaltat** [comment]
Made a copy/paste error when I did say this: 
```So a a good workaround, from Robot Framework, is use on_timeout=kill and shell=False.```
Should have said this: 
```So a a good workaround, from Robot Framework, is use on_timeout=terminate and shell=False.``` kill -> terminate. Sorry about the error. The process left in background is not a bug, at least not in my mind. 

Setting the ```shell=True``` is the root of the problem, if I do not change the default, it works like a charm. With both ```on_timeout=kill``` and ```on_timeout=terminate``` options. Although the Python subprocess is not the root cause, because with subprocess the shell=True works and does not hang.

I can write update to the documentation and make a pull request. I was thinking to write something to the Process configuration chapter and perhaps linking to the subprocess documentation.

Because there is better/correct way the configure the Start Process keyword and if we update documentation, I do not have an interest to debug the problem any further, why the Wait For Process keyword hangs (Although the tester inside me, is quite pissed off to me, because the root cause is not found and a perfect solution is not found to the bug). @pekkaklarck what you want to do?

**Comment by pekkaklarck** [comment]
The difference between `terminate` and `kill` on Windows with CPython is that the former sends `CTRL-BREAK` event and the latter ends up calling `TerminateProcess()` Win32 function. The `CTRL-BREAK` event is send also to possible child processes by default (typically a good thing) but the latter only affects the main process. 

It would be interesting to know where exactly the code related to `kill` hangs. Could you try running it on a debugger or putting  `import sys; sys.__stdout__.write('message\n')` inside `_kill` method around `process.kill()` and also somewhere inside `_process_is_stopped` method?

I do agree that this problem is pretty minor and not worth spending that much time. It could be argued that the problem is even caused by a user error because it doesn't occur in default configuration. That, then again, really tells us that the docs should be enhanced. Making it more explicit in *Running processes in shell* section that shell is very rarely needed on Windows is a good idea. Doc enhancements should perhaps get their own issue, tough.

**Comment by aaltat** [comment]
I did run it with debugger, download from here: https://www.dropbox.com/s/jt9kj8e987vuu6a/pdb.log?dl=0

I you want more details, just let me know and I will do it.

**Comment by pekkaklarck** [comment]
That debug log is pretty long and I'm not familiar with the format. Did it hang at the end? The last marked line is `return self._format_output(stream.read())` which would indicate that reading process output hangs. That could mean that the process isn't fully stopped or at least its output streams aren't closed.

Did you specify output files when running tests of not? If not, Process library uses `subprocess.PIPE` and these in-memory streams may become full (that ought to be documented). Did you already test running same hanging example with and without stdout/stderr redirected to files?

**Comment by aaltat** [comment]
Yeah, it is quite long. For me it seemed like Process library did call subprocess to kill the process and when formatting the output it did, for some reason, hang. I can try it make shorter, by not using pdb.step and by more using pdb.return. I did use winpdb [1] console for running the debugger and just stepped and listed the code over. But I am not that familiar with Python debugging, so if there is something that is needed point me to right direction. But it did hang on line ```return self._format_output(stream.read())``` and debugger did also freeze. 

I did not specify the output and but if I do it, it looks like this:
```
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
[2J[2HAndroid Debug Bridge
State: unknown

```

 

[1] http://winpdb.org/

**Comment by pekkaklarck** [comment]
It cannot be formatting that hangs but `stream.read()`. Does your latest example hang if you do not redirect stdout/stderr? How big is the output in log.log file?

**Comment by pekkaklarck** [comment]
Any new info about this?

**Comment by aaltat** [comment]
I did try to debug yesterday but I did not find out the reason why it failed. Mainly because the Popen and that part of the RF code is not familiar to me.

**Comment by lczub** [comment]
Hello Pekka and Tatu,

I struggle also about an equal failure in RF 2.8.7 , reproducible under RF 2.9.2 (Win8.1 64bit, Py 2.7.10).

It seams, that _Wait For Process_ waits , till all sub processes of an observed main process has finished (or maybe handles to logging streams are closed). If such a process starts via _subprocess.Popen_ additional server processes, _Wait For Process_ does not come back.

In my opinion, this implementation is wrong, _Wait For Process_ must come back, when the main process has finish, even when a sub process is still running.

To simulate and test such situation, I published on Gist

a) [dummy_worker.py](https://gist.github.com/lczub/22b0f2a12a27c30d0a14#file-dummy_worker-py), which simulates a longer running process, which starts a subprocess
b) RF test [wait_process_tests.txt](https://gist.github.com/lczub/22b0f2a12a27c30d0a14#file-wait_process_tests-txt) _Wait and Terminate running Process logging to STDOUT_, which fails, cause it waits till also the sub process is finished
c) [run_dummy_worker.py](https://gist.github.com/lczub/22b0f2a12a27c30d0a14#file-run_dummy_worker-py), which starts dummy_worker.py and uses equal args as _Wait and Terminate running Process logging to STDOUT_ . It come back much earlier than RF.

I'm not really sure, if my tests uses correct args to start the processes. But my hope is, that this  helps to discover the problem.

Regards Luiko

**Comment by pekkaklarck** [comment]
- Does your example pass if you write stdout to a file? 
- Process lib uses some additional config compared to your example. See its sourrce for details if you want to emulate its behavior with pure Python.
- I doubt I have time to look at this in more detail in the near future. It would be great if you could investigate this more and propose a fix if you find out what's causing the problem.

**Comment by lczub** [comment]
I updated [wait_process_tests.txt](https://gist.github.com/lczub/22b0f2a12a27c30d0a14#file-wait_process_tests-txt) with additional tests, redirecting STDOUT and STDERR.

Redirecting both STDOUT and STDERR helps, _Wait For Process_ comes back directly, after the main process has finished, even when the start sub process is still running (see _Wait For running Process with SubProcess logging to STDOUT - redirect STDOUT STDERR_ )

Redirecting only STDOUT does not helps, _Wait For Process_ waits, till also the sub process has finished (see _Wait For running Process with SubProcess logging to STDOUT - redirect STDOUT_)

So the workaround seams to be, that process, starting other processes , must be  started with a configuration redirecting STDOUT and STDERR. 

I will try to debug and understand  what happens in one or two weeks.

**Comment by pekkaklarck** [comment]
Sounds like process output streams would get full which causes the process to hang. You can try emulating how Start Process configures stdout/stderr by default on pure Python by setting `stdout=subprocess.PIPE` and `stderr=subprocess.PIPE`.

Process library docs mention that stdout/stderr can get full unless directed to files. Perhaps that note should be made more visible.

**Comment by aaltat** [comment]
For most of the time, diverting to stderr and stdout to file works for me (when I use adb). But at least once a week, there is a problem with ```Wait For Process``` which needs manual intervention. But I think I use process library few thousands times in a week so it is not bad ratio. And there usually is also problem with the adb/device which also needs some maintenance.

**Comment by lczub** [comment]
I think, the problem is not, that the process output streams get full. The problem is, that the streams are still in use by the  sub process. 
a) after the sub process has finished , _Wait For Process_ is able to return the complete content written to STDOUT from the process and the sub process.
b) the used example _dummy_worker.py_ creates an output of 21 lines (or 2k), which is not much

I update the samples with a new test 
-  _Wait For running Process with SubProcess logging to STDOUT - PIPE sub process streams_

It shows, that  starting the sup process using separate stdout and stderr streams also avoid the "endless waiting" situation. But in cases like the ADB we could not influence, how these process start there sub processes.

So a doc note seams to be the best way as a kind of safety tip. It should recommend, starting process with sub process should divert stdout AND stderr to a file

**Comment by pekkaklarck** [comment]
It seems there's nothing simple we could do on Process library itself other than possibly enhancing docs. If you have concrete ideas how to enhance the docs, please submit a new issue and/or pull request.

**Comment by putaodoudou** [comment]
i met the same issue
