### ISSUE TITLE
Cleanup Jython Interpreter when executing Robot Framework though Java API

### ISSUE THREAD

**Issue by jussimalinen** [robotframework/robotframework#2088]
If Robot is executed from Java entry point (org.robotframework.RobotFramework), the Jython interpreter object is not cleaned up manually. The cleanup happens latest when the system exists, but this can cause problems with Maven. Sometimes the cleanup of the interpreter would happen after the Maven classloader no longer allows loading new classes and this could cause ClassNotFoundException.

The fix is to ensure that cleanup happens after the execution immediately.

**Comment by jussimalinen** [comment]
Yeah, and this blocks MavenPlugin release.

**Comment by jussimalinen** [comment]
The cleanup of the API should be done in major version:  #2090

**Comment by pekkaklarck** [comment]
Updated the title of this issue and #2090 to underline that this issue was about cleaning up interpreter (i.e. releasing resources) after use and the latter is about cleaning up code.
