### ISSUE TITLE
`Should Be Equal` should show better multiline diffs

### ISSUE THREAD

**Issue by jussimalinen** [robotframework/robotframework#2089]
When calling `Should be equal` with multiline text, the error message is very difficult to read. There should be a cleaner diff in that case.

There could also be nicer diffs for lists.

**Comment by MoonSungHoon** [comment]
Good idea. :)

**Comment by jussimalinen** [comment]
Ready for review I think. @pekkaklarck would you check how this looks?

**Comment by pekkaklarck** [comment]
We decided to only add support for better multiline diffs at this point. Better list and dict comparison can be considered later.
