### ISSUE TITLE
Possibility to specify keyword timeout using variable provided as argument

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#2092]
Currently this doesn't work:

```robotframework
*** Test Cases ***
Example
    Keyword    timeout=1s

*** Keywords ***
Keyword
    [Arguments]    ${timeout}
    [Timeout]    ${timeout}
    Sleep    2s
```

The above will fail because variables in `[Timeout]` are resolved before handling arguments passed to the keyword. Instead you need to do this:

```robotframework
*** Test Cases ***
Example
    Set Test Variable    ${timeout}    1s
    Keyword

*** Keywords ***
Keyword
    [Timeout]    ${timeout}
    Sleep    2s
```

I'd like the former to work too and would like it to do it already in RF 2.9.1. On a quick look at the code it may require so much changes that it needs to wait for RF 3.0, though. The main problem is that we want to show the actual timeout in logs, and we currently log it before the keyword is executed and arguments are resolved. Changing that may require quite big changes and possibly also changing how timeout is actually written to output.xml.

**Comment by jussimalinen** [comment]
Fixing this requires backwards incompatible changes to the output xml and also quite big changes to running logic. Therefore we cant really make this in minor version. Moved to 3.0

**Comment by pekkaklarck** [comment]
Commit e6ce2f90407ae66711ab21088ce5c2f894bf2eae changed output.xml so that timeouts written as a separate element (e.g. `<timeout value="1 minute"/>`) and not as an attribute to the started `<test>` or `<kw>`.
