### ISSUE TITLE
After setting PYTHONPATH enviroment variable i got error like 'Resource file does not exist.'

### ISSUE THREAD

**Issue by Sumeet90** [robotframework/robotframework#2102]
RobotFramework version is 2.9

I want import resource file with only name in my test case.

In my test case i write resource file as 'Resource          general_resource.txt' with only file name. My resource file exist in '/home/Sumeet/RobotFramework/Common' folder. That path I already set in PYTHONPATH environment variable as export PYTHONPATH="/home/sumeet/RobotFrmework/Common"

And also i write following code as per below in 'pythonpathsetter.py' file (Location: /usr/local/lib/python2.7/dist-packages/robot)

# Default library search locations.
add_path(join(ROBOTDIR, 'libraries'))
add_path('.', end=True)

# Support libraries/resources in PYTHONPATH also with Jython and IronPython.
for item in os.getenv('PYTHONPATH', '').split(os.pathsep):
    add_path(abspath(item), end=True)

 Finally I ran test from RobotFramework folder as per below command:

sumeet@sumeet:~/RobotFramework$ pybot -d ~/tmp3/ -V Test/variable_files/variables_stage.py Test/test.txt

I got error as per below:

[ ERROR ] Error in file '/home/sumeet/RobotFramework/Test/est.txt': Resource file 'general_resource.txt' does not exist.

Please let me know if I something doing wrong or make any mistake.

**Comment by pekkaklarck** [comment]
I have no idea why importing the resource file would fail if it is in PYTHONPATH. We have explicit tests for this functionality and my guess is that there's something wrong in your environment. Notice that you do not need to run any extra code, just set PYTHONPATH environment variable in your system.

If you suspect there is a bug in Robot, you need to provide us more information about your context. It would be best if you could create a simple executable example we could try in our environment.

**Comment by pekkaklarck** [comment]
Closing due to lack of information.
