### ISSUE TITLE
debug mode support

### ISSUE THREAD

**Issue by lzq420241** [robotframework/robotframework#2107]
Our test scenario contains several devices controlled through RemoteLibrary.
It requires lots of keywords to get the devices to the suitable state that is conformed to the test requirement.
The process of setting several devices (let say A, B, C) to a required state(As, Bs, Cs) is very fragile, and takes about 20 minutes. Debug each state setting process separately is not an option, as Bs requires As is achieved, and some bizarre issues occasionally occurs only when As, Bs, Cs are achieved.

It is very painful to debug the keywords in that process since we have to rerun the whole case again to
find another bug. 

If robotframework can provide a debug mode, for example, auto pause when a keyword is failed, after click run in RIDE rerun the (refreshed) keyword and continue, that would be really appreciated.

**Comment by pekkaklarck** [comment]
We have decided not to include a debugger in Robot Framework itself. Debuggers can be implemented as external tools and there actually already exists some. RIDE's debugging capabilities can also be improved, but that would be RIDE's issue.
