### ISSUE TITLE
`Run Keyword If Test Failed/Passed` do not handle earlier ignored failures correctly

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#2108]
Running this example fails with error `Test should have passed`:

``` robotframework
*** Test Cases ***
Example
    No Operation
    [Teardown]    Teardown bug

*** Keywords ***
Teardown bug
    Run Keyword And Ignore Error
    ...    Fail    This error should be ignored
    Run Keyword If Test Failed
    ...    Fail    Test should have passed
```

The problem can be caused also by other keywords that ignore failures such as `Wait Until Keyword Succeeds`. Same problem occurs also with `Run Keyword If Test Passed`. This is a regression caused by a fix for #1270.

**Comment by jussimalinen** [comment]
..wrong issue number...
