### ISSUE TITLE
Explicitly state that shell shouldn't be used in Process library documentation

### ISSUE THREAD

**Issue by aaltat** [robotframework/robotframework#2109]
Because of the issue #2085, it would be best to enhance library documentation to more strongly say that shell=True should be avoided in most cases.

**Comment by pekkaklarck** [comment]
Could you @aaltat review enhancements in b5fcb15? I didn't find any single  place from subprocess docs to link to. The docs now pretty explicitly recommend against using the shell, though.

**Comment by aaltat** [comment]
Yes I can, but I have plans for the the next few days. So it will take at least that.

**Comment by pekkaklarck** [comment]
In that case I'll close this now. Comment later when/if you have time.

**Comment by aaltat** [comment]
it was shorter than it looked from a phone screen. For me it looks OK and good to go. There will be always exceptions where shell is actually needed (just ran in to one, cURL). But I think this is good to go.

**Comment by pekkaklarck** [comment]
Sure, there are use cases for `shell=True`, otherwise it wouldn't be supported at all. It's just that it can cause problems and in most cases you don't really need it.
