### ISSUE TITLE
Libdoc HTML - Shortcuts/links to keywords (having spaces) are not working with Internet Explorer (11 and others). 

### ISSUE THREAD

**Issue by HelioGuilherme66** [robotframework/robotframework#2110]
Shortcuts/links to keywords (having spaces) are not working with Internet Explorer (11 and others). 

The cause is the attribute "name" having spaces encoded. For example:
In IE 11 and Chrome "name" is encoded: `<a name="Encode%20String%20To%20Bytes" title="Link to this keyword" href="#Encode%20String%20To%20Bytes">Encode String To Bytes</a>`

In Firefox "name" is not encoded: `<a name="Encode String To Bytes" href="#Encode%20String%20To%20Bytes" title="Link to this keyword">Encode String To Bytes</a>` 

The problem is found in all docs produced after Robot Framework version 2.8.6. (for example 2.8.7, 2.9)
- Operating system name and version: Windows 7 x64 Professional

---

To fix, edit file `src/robot/htmldata/libdoc/libdoc.html` change line 347 from:
`            <a name="${encodeURIComponent(name)}" href="#${encodeURIComponent(name)}"`
to
`            <a name="${name}" href="#${encodeURIComponent(name)}"`

**Comment by pekkaklarck** [comment]
It seems `encodeURIComponent` was added in 9bd1e4987499eaaa0e8e38a5d14ab921249bdd7a to fix an issue with IE8. I'd much rather support IE11 than IE8 so changing this is OK. There have been issues like #1678 earlier so I'd like this to be tested a bit more.

Which browsers and operating systems have you @HelioGuilherme66 test the fixed version with? Have you also used non-ASCII characters in your tests?

**Comment by pekkaklarck** [comment]
I tested the proposed fix on Linux with Firefox and Chrome and on Windows with Firefox, Chrome and IE11. All of them worked fine. I don't have IE8 anywhere to test but IE11 is much more important and without the fix it is broken.

**Comment by pekkaklarck** [comment]
Notice that if you want to test the fix with a bit more complex data, including keywords with special characters in name, you can just open the aforementioned `libdoc.html` file into a browser.
