### ISSUE TITLE
Input Text is not working properly

### ISSUE THREAD

**Issue by yuzhangoscar** [robotframework/robotframework#2112]
I needed to input text into this field:

css=div[class='x-window x-layer x-window-default x-closable x-window-closable x-window-default-closable'] table[class='x-field platform-txt-username x-form-item x-field-default x-autocontainer-form-item'] td[class='x-form-item-body '] input

which is a text input field. 

    Wait Until Element Is Visible           ${USERNAME}           ${UNIVERSALWAIT}
    Log                                     ${TEMP}
    Input Text                              ${USERNAME}           ${TEMP}

According to the log, text is successfully input into this field, but all I could see is this text field was clicked as mouse cursor started to flash inside this text box, but no text was input at all. 

Below is the log message:

Documentation:	
Types the given `text` into text field identified by `locator`.
Start / End / Elapsed:	20150820 17:06:53.814 / 20150820 17:06:53.883 / 00:00:00.069
17:06:53.815	INFO	Typing text 'sdfsdf' into text field 'css=div[class='x-window x-layer x-window-default x-closable x-window-closable x-window-default-closable'] table[class='x-field platform-txt-username x-form-item x-field-default x-autocontainer-form-item'] td[class='x-form-item-body '] input'

In my tests, I have done a similar steps a few times, and they all worked except for this one.

**Comment by pekkaklarck** [comment]
Not related to Robot Framework core.
