### ISSUE TITLE
Feature request: [Setup/Teardown Append]

### ISSUE THREAD

**Issue by suonto** [robotframework/robotframework#2124]
Very often I find myself in situations, where I have a common Test Setup for tests in a suite, but I'd like to append a test specific keyword to that setup. Now that requires defining a new setup keyword with the existing setup + test specific keyword or using Run Keywords. In my opinion, it would sometimes be much cleaner to start the test definition with [Setup Append]  Test Specific Keyword. For example:

        *** Settings ***
        Test Setup  Open Browser To Landing Page

        *** Test Cases ***
        Test Logout
            [Setup Append]  Login  foo  bar
            Logout
            Landing Page Should Be Open

**Comment by pekkaklarck** [comment]
I can see this kind of concept would sometimes be useful, but benefits are pretty small considering the work related to adding new syntax (including changes to RIDE and other editors). To be honest, I'm not sure would I like to increase the overall complexity of the framework even if we would get this totally for free (i.e. someone would provide a pull request with code, tests and docs that could be merged without changes).

I also fail to see the benefits of this concept with test setups. If I got the proposal right, the original example would work exactly same way also if `Login  foo  bar` would be the first normal keyword. Things are different with test teardowns, but my earlier comments about new syntax and increased complexity hold there.

If you are convinced this would be a good enhancement, please provide some examples where this approach would be considerably more convenient than what is currently available.

**Comment by pekkaklarck** [comment]
Any new comments about this?

**Comment by suonto** [comment]
You are correct about the example, it would work in the same way if Login was the first keyword. In fact, that is the reason why often keywords that really belong to Setup/Teardown are written as part of the test case. Considering this, I retain my opinion that with the current syntax it is clumsy to append steps into existing setups and teardowns, and this feature would improve the distinction between the actual tested operations and the ones that would really belong to Setup/Teardown. However, I do see the cost of increased framework complexity and the indirect impact to other systems. So if you consider this request to be a lost cause, feel free to close the issue.

**Comment by pekkaklarck** [comment]
1. For me the benefits of the proposed syntax look very small compared to the increased overall complexity, changes required to RIDE and other tools, etc. This is especially true with setup where the difference between the first keyword and setup is only semantic. If you want to convince me that the enhancement is worth the effort, please provide concrete examples showing how the enhancement would make things better.

2. Even if we would agree this is a good idea, someone would need to implement it. In practice someone would need to provide a pull request or pay someone else to do it. It would be even better if there would be a separate PR for RIDE.

Is this important enough for you to take care of both of the above?

**Comment by suonto** [comment]
As much as I'd like to say yes, I fear the answer is no. Perhaps one day if I have the time.

**Comment by pekkaklarck** [comment]
OK. Please comment here or submit a new issue if this gets more urgent and you want to spend more time with it.
