### ISSUE TITLE
import variables from resource file

### ISSUE THREAD

**Issue by yahman72** [robotframework/robotframework#2128]
I think this would be a feature request.

It would be nice to import variables from a resource file as global python variables.
I know this would be possible when using py-variable files instead of RF resource files, but I'd prefer using resource files because they are more readable for the testers (that don't necessarily have python skills) and using predefined (e.g. `${CURDIR}`) variables is easier.

For example, let's assume that `resourcefile.txt` has `${DEFAULT_TIMEOUT}   10s`.
Using this as the default value for a argument is easy in a resource file e.g.
<pre>
Wait Until Something Happens
    [arguments]         ${expect_condition}      ${timeout}=${DEFAULT_TIMEOUT}
</pre>

I'd like to do the same in a Python library like this.
<pre>
def wait_until_something_happens(self, expect_condition, timeout=DEFAULT_TIMEOUT)
</pre>
For the above to work the resource file with the variables would need to be imported into the global (python) scope somehow, maybe with a new `import variables from resource file` keyword.

**Comment by yahman72** [comment]
hmmm - just started to wonder if this is possible:
the key question is that when does python assign the value for the `timeout`?
If during compilation (I guess this is the case) then the above will never work, because the `DEFAULT_TIMEOUT` would need to be assigned during runtime...

<pre>
Class MyClass:
    def __init__(self):
        import_variables_from_resource_file("resourcefile.txt)"
    
    def wait_until_something_happens(self, expect_condition, timeout=DEFAULT_TIMEOUT)
        print timeout
        print DEFAULT_TIMEOUT
</pre>
The above would print two different values if the assignment happens during compilation time...

**Comment by pekkaklarck** [comment]
I don't think this is a good idea nor would be really needed:

1. If you want your libraries to read information from external files, it's better to use some other format that Robot test data. I would try CSV or YAML.

2. You can already now dynamically access current Robot variables using, for example, `BuiltIn.get_variables` in your library code.

3. Default values for Python functions are evaluated when the function itself is evaluate for the first time.

Combining 2 and 3 above, you can do something like this:

```python
    from robot.libraries.BuiltIn import BuiltIn

    def example(timeout=None):
        if timeout is None:
            timeout = BuiltIn().get_variables()['${DEFAULT TIMEOUT}']
        # ...
```

**Comment by yahman72** [comment]
wrt. 2 & 3)
correct, but `def example(timeout=DEFAULT_TIMEOUT)` would have been cleaner, but because of 3) this is not going to work anyway --> sorry for the spam generated.

wrt. 1)
are CSV/YAML are they supporting supporting build-in and/or automatic RF variables? e.g.
<pre>
string:   Hello, world!
examplepath:   ${CURDIR}${/}${SUITE NAME}
integer:  42
</pre>

**Comment by pekkaklarck** [comment]
If you want, uou can do this:

```python
DEFAULT_TIMEOUT = object()

def example(timeout=DEFAULT_TIMEOUT):
    if timeout is DEFAULT_TIMEOUT:
            timeout = BuiltIn().get_variables()['${DEFAULT TIMEOUT}']
        # ...
```

No, external files do not directly support Robot's variables. You could use `BuiltIn.replace_variables` to resolve them, though.

**Comment by yahman72** [comment]
would that `BuiltIn.replace_variables` really work in combination with YAML file?
`BuiltIn.replace_variables` replaces variables in that file, and gives me a text object - but to import `BuildIn.import_variables` expects a path argument (not a text).
And the other way around is a bit cumbersome = `import_variables` and then go through all variables with `replace_variables`

Would optional variable replacement make sense for the imports? For example:`Variables  foo.yaml  expand_vars=True` and/or `BuildIn.import_variables("foo.yaml", expand_vars=True)`

**Comment by pekkaklarck** [comment]
You can first replace variables in the yaml source and the just use PyYaml module directly to parse it. Same with CSV and other such external files.

Automatically expanding variables at import doesn't sound too useful. It would also be quite a lot of work to implement and just using `expand_vars=True` would probably cause compatibility problems with arguments passed to variable files themselves. That's not something I would implement but you might be able to convince me to accept a pull request.

**Comment by yahman72** [comment]
I thought about this for while: `expand_vars=True` would be a nice feature but probably not really worth the effort - because you can achieve the same quite easy as you wrote (e.g. with PyYaml).
So, no PR coming from me...
