### ISSUE TITLE
Keyword 'Capture Page Screenshot' could not be run on failure: BadStatusLine: ''

### ISSUE THREAD

**Issue by markg58** [robotframework/robotframework#2137]
After upgrading to RF 2.9.1, when viewing test results in the report.html file I'm seeing the following reported "Keyword 'Capture Page Screenshot' could not be run on failure: BadStatusLine: ''".  Upon investigating, the screenshots are being captured and stored in the output/ along with the html (log and report), and output.xml files.  The screenshot doesn't appear in report.html, but does in log.html.  Looking at output.xml, I'm seeing

> <kw name="Capture Page Screenshot" library="Selenium2Library">
> <doc>Takes a screenshot of the current page and embeds it into the log.</doc>
> <msg timestamp="20150908 11:20:24.045" level="FAIL">BadStatusLine: ''</msg>
> <status status="FAIL" endtime="20150908 11:20:24.045" starttime="20150908 11:20:23.884"</status>
> </kw>
> <msg timestamp="20150908 11:20:24.046" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: BadStatusLine: ''</msg>
> <msg timestamp="20150908 11:20:24.062" level="FAIL">BadStatusLine: ''</msg>
> <status status="FAIL" endtime="20150908 11:20:24.062" starttime="20150908 11:20:23.877"</status>
> </kw>

Note:  the Selenium2Library being used is version 1.7.1.

**Comment by pekkaklarck** [comment]
This is S2L issue. Might be fixed in its latest release. Please upgrade S2L and report the issue into its tracker if it persists.
