### ISSUE TITLE
/tmp/ride.log collision when multiple users using the same host and running ride.py in unix enviroments

### ISSUE THREAD

**Issue by dgonyier** [robotframework/robotframework#2138]
In UNIX environments, if multiple users are runing ride.py from different VNC sessions, etc. on the same host, after the first session has created /tmp/ride.log, any other user trying to run ride.py will get a stack trace due to permissions denied error on /tmp/ride.log as the permissions are set by the first user running that file.  This is traced to code in robotide/context/logger.py in the '\__init_\_' and '_output' methods of the 'Syslog' class. 

As a workaround for UNIX environments, maybe prepend the ride.log filename with either the running userid or the PID of the ride.py process to create unique /tmp/*ride.log files per user or per session.

**Comment by pekkaklarck** [comment]
Please submit this to RIDE's tracker.

**Comment by dgonyier** [comment]
https://github.com/robotframework/RIDE/issues/1520
