### ISSUE TITLE
pybot --rerunfailed does not re-execute tests skipped due to a fatal error

### ISSUE THREAD

**Issue by CMTaylor** [robotframework/robotframework#2140]
One of my main purposes in trying to use pybot's --rerunfailed option is to automatically execute test cases from a previous run that were not run due to a fatal error in some previous test. Such test cases appear in the report.html file as:
    Status:	FAIL (critical)
    Message:	Test execution stopped due to a fatal error.
yet there are no records for these test cases in the output.xml file, so --rerunfailed does not re-execute them. This is a serious gap in the usefulness of --rerunfailed. If there can't be an immediate fix for this, can you suggest a way to have --rerunfailed know about the tests that were skipped due to a fatal error? Perhaps some data from report.html or log.html could be used? Perhaps an RF listener process running during the original run that had the failures could write some data somewhere that --rerunfailed could read and act on?

**Comment by pekkaklarck** [comment]
I cannot reproduce this problem. I just verified that output.xml gets information about all tests also when there are fatal errors and that `--rerunfailed` works fine with such output. Could you retry this on your environment?

**Comment by CMTaylor** [comment]
Was this a fix in RF 2.9? I’m still running 2.8.7…

**Comment by pekkaklarck** [comment]
I don't remember this ever being broken. Just tested with 2.8.7 and had no issues.

**Comment by pekkaklarck** [comment]
Have you @CMTaylor had a change to retest this?

**Comment by CMTaylor** [comment]
I think the problem was that the first run had
--include Tag1
And the –rerunfailed had
--include Tag2&Tag1

And this resulted in a very restricted set of tests being selected.  I’m trying a corrected run of this right now.
I modified my runner code so that if it was a first time run it would do the
--include Tag2&Tag1
And if it was a –rerunfailed run it would skip adding the --include of any kind and just drive it off the previous output.xml.

Hopefully this will fix the problem.

Thanks,
Martin

**Comment by CMTaylor** [comment]
Seems to have been a one-time glitch... cannot reproduce.
