### ISSUE TITLE
XML file doesn't have reason as "Parent suite setup failed" captured for test cases that failed due to suite setup fail

### ISSUE THREAD

**Issue by sanakyan** [robotframework/robotframework#2142]
As per log.html:
Two test suites are run. Of them 2nd suite has "failed at suite setup" due to which the test cases within are marked as FAIL with the reason "Parent suite setup failed".

As per XML file, there are no suite setup failures. 'status' is set to PASS for suites. But in log.html file, it is correctly marked as 'Suite setup failed'.

I am trying to parse XML file and retrieve information about test cases that failed (or not-run) due to suite setup failure and couldn't find this info in XML file.

Requesting you to help me with solution for this issue.

**Comment by jussimalinen** [comment]
Sorry, I could not follow your example. Could you clarify what exactly is the behaviour you expect and what you see? A simplified executable example would be best.

Note that if you are parsing the xml in python, there is also the robot framework's own api for going through the xml file: http://robot-framework.readthedocs.org/en/latest/autodoc/robot.result.html#robot.result.resultbuilder.ExecutionResult

**Comment by sanakyan** [comment]
I am using python to parse XML file and get 'test name'(test tag) and the associated result of it (from ''status' tag) for each test case. Then use push the data -'test name' and the 'result' to other external database.

Say the suite has 1 test case and suite-setup calls a keyword. Due to an expected cause, suite-setup has failed and due to which test case result is marked FAIL in log.html file. But when I parse the associated XML file, the 'status' of the associated test case is marked PASS (whereas the same test case is marked FAIL in log.html file). Hence test case result is incorrectly pushed as PASS to external database, which is wrong.

Somehow log.html file is able to identify that suite setup failed and correctly mark all the test case of suite as failed. Not sure, why XML file data is not in sync with log.html. I was assuming that log.html file is generated out of XML data only. 

My expectation is that - Result of test case 'status' should be FAIL, once its test suite has failed.

Is there any way to find from XML file that suite setup has failed for a suite from XML file.

Unable to attach the html file and XML file here as they are not supported file-types.

**Comment by pekkaklarck** [comment]
If suite setup fails, test status in output.xml is definitely FAIL. It's different with suite teardowns, though, because test status is written before suite teardown even starts. Robot's own result parsing separately checks suite teardown status because of that. As Jussi suggested, you should use them if you do parsing in Python.

If you are certain you have encountered a bug, please submit a separate issue explaining it with an example we can use to reproduce it. If you need more help parsing, please use robotframework-users mailing list or other support forums.
