### ISSUE TITLE
Add PyYAML to standalone jar

### ISSUE THREAD

**Issue by jussimalinen** [robotframework/robotframework#2143]
Standalone jar could include docutils and PyYAML packages. The invoke script could download known versions from both and embed those.

**Comment by jussimalinen** [comment]
docutils cant really work when embedded in a jar file. The docutils/writers modules try to load the template files using file path and then just open them as files. As the files are inside a jar file that fails.

That said, PyYAML works just fine. Therefore changing the scope to just include PyYAML for now.

**Comment by jussimalinen** [comment]
This would be ready for review. @pekkaklarck ?

**Comment by pekkaklarck** [comment]
Looks great. Added few nitpicky line notes, though. Should also mention that the the standalone jar contains PyYAML in installation instructions.
