### ISSUE TITLE
Depth of Keyword in Listeners

### ISSUE THREAD

**Issue by serhatbolsu** [robotframework/robotframework#2144]
As a developer of libraries in RF and using listeners to publish html based reports, I would like my users to see the same keyword structure as in RF (log.html). 

- Listener interface does not provide a way if the keyword is higher level keyword - mid level (custom keyword ) or a library keyword.
- There may be an depth attribute that is giving information about this keyword for `start_keyword`, `end_keyword` . 
- The developer using listener library shall use this depth and create the same architecture as in log.html.

**Comment by pekkaklarck** [comment]
This is same as #2145.

**Comment by serhatbolsu** [comment]
dont know how it happened to be twice, thanks
