### ISSUE TITLE
Depth of Keywords in Listeners

### ISSUE THREAD

**Issue by serhatbolsu** [robotframework/robotframework#2145]
As a developer of libraries in RF and using listeners to publish html based reports, I would like my users to see the same keyword structure as in RF (log.html). 

- Listener interface does not provide a way if the keyword is higher level keyword - mid level (custom keyword ) or a library keyword.
- There may be an depth attribute that is giving information about this keyword for `start_keyword`, `end_keyword` . 
- The developer using listener library shall use this depth and create the same architecture as in log.html.

There may be another solution to this problem then giving depth variable. Still thought the result is that, listener interface requires a way to differentiate the keyword level.

Best regards,
Thank you.

** note: I can help coding&test  if directed about solution.

**Comment by pekkaklarck** [comment]
1. It wouldn't be enough to tell is a keyword library keyword or a user keyword to determine does it have child keywords or not. There are special library keywords like `Run Keyword If` and `Wait Until Keyword Succeeds` that have children. Additionally a user keyword can be empty.

  If you anyway think it would be useful to know is a started keyword a library keyword or a user keyword, we can consider adding such information. In RF 2.9 `start_keyword` and `end_keyword` got a new attribute `libname` that is either the library or resource name. It could be changed to contain only possible library name and a separate attribute added that contains possible resource file name. Alternatively we could consider adding a Boolean attribute like `islib`. Please submit a separate issue if you think library and user keywords should be separated somehow. Be also prepared to provide a pull request to actually get it implemented and included in a release.

2. I don't think separate depth argument is very useful. It is trivial to a listener to keep track of the depth:

  ```python
  class Listener(object):
      def __init__(self):
          self.depth = 0
      def start_keyword(self, *args):
          self.depth += 1
      def end_keyword(self, *args):
          self.depth -= 1
  ```

  Additionally, #2115 proposes adding `id` to also to `start/end_keyword` methods. After that depth can also be got like `id.count('k')`.

**Comment by serhatbolsu** [comment]
I will try to find a solution with following start_keyword and end_keyword, looking throught if end is the started one and vise versa. I will post back, if any change could help during developing that

**Comment by pekkaklarck** [comment]
Any new info about this? Any concrete enhancements to be added?

**Comment by serhatbolsu** [comment]
I have implemented a way with depth and it worked to some extend. I will open a seperate ticket for understanding the user keywords
