### ISSUE TITLE
`Copy/Move File` fails if source and destination are same

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#2153]
For example this example fails with `IOError: No such file or directory`:

```robotframework
*** Test Cases ***
Copy File Bug
    Create File    ${CURDIR}/example.txt
    Copy File    ${CURDIR}/example.txt    ${CURDIR}/example.txt
```

Same problem occurs also with `Move File` and if the specified destination is a directory (e.g. just `${CURDIR}` in the above example). To make matters worse, a temporary directory is left into the directory where the file exists.

We should handle this that source and destination being same is not a failure at all. Preferably there should be a special log message telling that file was not copied/moved because destination was same.

**Comment by markwinspear** [comment]
Copy should be allowed to have the same source and destination folder. If the filename is also the same then either overwrite or throw a sensible error

**Comment by pekkaklarck** [comment]
This will be implemented so that if source and destination point to the same file, there will be no copying or moving whatsoever and the keyword will pass.
