### ISSUE TITLE
"Get Library Instance" doesn't work if library has space in name

### ISSUE THREAD

**Issue by boakley** [robotframework/robotframework#2156]
If I load a library using "WITH NAME", and the name I give it has a space, "Get Library Instance" cannot find the library. There are no restrictions in the user guide about using spaces in the name, and I can use the name with spaces when calling the keywords, so I assume this is a valid use case. 

Given a test library "mylibrary.py" with the following contents:

    def some_keyword():
        return "42"

This test will fail:

    *** Settings **** 
    | Library | mylibrary.py | WITH NAME | foo bar

    *** Test Cases ***
    | Example
    | | # this works as expected
    | | foo bar.some keyword
    | | 
    | | # this fails with "No library 'foo bar' found.
    | | Get library instance | foo bar

When I look in the code (namespace.py), `KeywordStore.get_library` removes spaces before looking up the name. Perhaps it should first look for the name with spaces, and if not found it should look for the name without spaces?

**Comment by pekkaklarck** [comment]
Related to this, `Get Library Instance` requires case to match, but when calling a keyword with a full name e.g. `builtin.log` works. Should probably use same logic in both places.

**Comment by pekkaklarck** [comment]
Were you @stasiek going to fix this? We plan to release RF 2.9.2 soon, possibly even this Friday but latest early next week, and would like to get this one in. If you are busy, we can implement it ourselves too.

**Comment by stasiek** [comment]
Sorry for being silent. I'm on a vacation, but I'll try providing a PR for this today.

**Comment by pekkaklarck** [comment]
No worries, enjoy your holiday! We can also easily do this ourselves. This is the last fix for 2.9.2 and I actually already started with it. If you have it already mostly done, I can wait for the PR too.

**Comment by stasiek** [comment]
If You already started I won't finish before You. I'm really curious about solution though.
Back then we started with:

```robotframework
Library  ParameterLibrary  third   WITH NAME  3rdSpace
Library  ParameterLibrary  fourth  WITH NAME  3rd Space
```

And then:

```robotframework
Library with a space in name
    ${lib} =  Get Library Instance  3rdSpace
    Should Be Equal  ${lib.parameters()[0]}  third
    ${lib} =  Get Library Instance  3rd Space
    Should Be Equal  ${lib.parameters()[0]}  fourth
```

And we talked about using `eq()` in `get_library_instance()`, but looking at this now, shouldn't imports with names varying by spaces be disallowed, not just getting the instance?

**Comment by pekkaklarck** [comment]
To make the change fully backwards compatible, I decided to use this approach:

- If the given name matches imported library name exactly, return that library.
- Otherwise get a list of libraries matching the given name in normalized format.
- If there is a single library that matches, return that library.
- Otherwise report a different error are there no matches or multiple matches.

The code I'll commit shortly will show the above in practice.
