### ISSUE TITLE
Remote Library Interface: only the library in the first/top import statement is actually imported

### ISSUE THREAD

**Issue by MichaelHallik** [robotframework/robotframework#2157]
Setup:

- Win7
- Python 2.7.10 (32b) 
- jrobotremoteserver 3.0
- RF 2.9.1 (32b)
- (RIDE 1.5a2)

Preconditions & actions

- Make sure to have at least two correctly functioning and properly named Java test class files, each implementing one or more keywords. It doesn't make a difference whether you package them in/as jars, just use stand-alone files or combine jars and files.
- Setup the jrobotremoteserver (v3.0).
- Give the proper command so as for the jrobotremoteserver to serve the created test classes (keyword libraries). E.g. (assuming no jars):

java -classpath <yourPathToFolderHoldingRemoteServerJar>\jrobotremoteserver-3.0-standalone.jar;<ypurPathToFolderContainingTestlib1>;<ypurPathToFolderContainingTestlib2> org.robotframework.remoteserver.RemoteServer --library <packageNameTestlib1>:/yourLogicalName1 --library <packageNameTestlib2>:/yourLogicalName2 --port 8270

- Optionally: open a browser to localhost:8270 (or whatever port you use). You will see that the remoteserver now serves the two test classes.
- Open RIDE (or the editor of your choice) and make sure to create the proper import statements for the two Java test libraries, as served by jrobotremoteserver. E.g.:

Library | Remote | http://localhost:8270/logicalName1
Library | Remote | http://localhost:8270/logicalName2

- Optionally: Use the WITH NAME argument for one or both
- Create a test case and make sure to call at least one keyword of each test library. Make sure to call at least one keyword from lib1 before the first call of a keyword from lib2.
- Run the test case

Expected results:

All tests run successful.

Actual result:

The first call to a keyword from lib 2 will fail, due to 'no such keywords'.

Remarks:

- When now making the import statement for lib 2 the first statement, then running the test case will fail at the point of the first call to a keyword from lib1.

**Comment by pekkaklarck** [comment]
1. Has this behavior changed between releases?

2. Does it happen also in other cases than when using Remote with jrobotremoteserver?

**Comment by MichaelHallik** [comment]
1. With 2.8.7 I did not have this problem. I did not use any release inbetween 2.8.7 and 2.9.1.

2. It appears to happen only with remote libs. But I have not used any other remote server than jrobotremote.

**Comment by pekkaklarck** [comment]
Sounds pretty weird. I don't remember there being any related changes to Remote so my guess is that this would still be related to library caching or something similar. Even if this would be limited to Remote, it definitely should occur also with other remote servers than jrobotremote.

It would be great if you could create a simple executable example demonstrating this problem and upload it somewhere. I doubt I have time to set up the required environment to investigate this myself in the near future otherwise.

**Comment by MichaelHallik** [comment]
"Even if this would be limited to Remote, it definitely should occur also with other remote servers than jrobotremote."

Right, Unfortnately, I haven't got a setup with e.g. the Python remote server or anything. 

But at least, I will create an archive file containing a one-click runnable setup and make sure you get it. I'll contact you over Slack for the details. I am busy as well,being on two assignments right now as well as having to prep a (RF) workshop for a conference next week in Amsterdam. So it'll take me a few days before having time for this.

I have a work around myself for the problem btw: I have created two test suites, each holding a set of test cases that only use the keywords from one library. Each of the test suites have one remote import statement (namely for the test lib that is required for the contained test cases). That way, the problem does not occur.

**Comment by pekkaklarck** [comment]
Yeah, everyone is busy. =) Hopefully you nevertheless have time to create an example. We are planning to create RF 2.9.2 soonish, probably next week, so there's still time to get a possible fix in. After that we'll then concentrate on RF 3.0.

**Comment by pekkaklarck** [comment]
Any new info about this?

**Comment by MichaelHallik** [comment]
Sorry, no. I will start with it now. :-)

**Comment by MichaelHallik** [comment]
OK, see the zip file I uploaded in Slack. Accompanying comment explains how to run remote + tests and reproduce the issue.

**Comment by pekkaklarck** [comment]
@MichaelHallik, was it so that the problem was in your setup? If yes, we can close this issue.

**Comment by MichaelHallik** [comment]
@pekkaklarck 

Yes, as discussed/explained on RF slack, I made a mistake after all. The issue can consequently be closed. Sorry again for the wasted time. :-)
