### ISSUE TITLE
Process Library and process interaction

### ISSUE THREAD

**Issue by mwalle** [robotframework/robotframework#2166]
There seem to be no way to interact with a process started by the Process library. Eg. there is no way to write to the stdin of a process or expect an output (analogues to Read Until). Do I miss something? How do you test CLI applications, for example?

**Comment by pekkaklarck** [comment]
You can interact with processes using signals, but you are right that there are no keywords to write to stdin. When designing the library, we weren't sure how it should work and decided not to implement it. Nobody has needed it badly enough so far to think about it any more. Do you have ideas how it should work? Would you be interested in providing a pull request if we can agree on the overall design?

**Comment by mwalle** [comment]
basically, the userinterface should be something like that:

    Start Process  cat
    Write To Stdin  foobar
    Read Until  foobar
    Terminate Process

Additionally, there should be Read Until Regexp. Should the keywords have other names than these from the Telnet library to avoid name clashes?

Further, we might choose that process interaction only works with buffered stdout/stderr, ie. not written to file, if this makes the implementation easier. Esp. since the Read keywords clears the read bytes from the buffer.

**Comment by pekkaklarck** [comment]
1. I don't think interacting with a process like that works in the general case. The main problem is that typically stuff the child process writes to its stdout is blocked unless the child explicitly flushes the output. I might be wrong about this and it might be possible to make communication non-blocking, but I do not have time to investigate this myself. Hopefully you have time to look at this yourself. Notice that any solution added to the Process library needs to be generic, work on all supported operating systems, preferably with all Python interpreter types and versions, and must not require cooperation by the child process.

2. Writing to the process stdin shouldn't be too complicated, though. It would probably be enough to allow passing stdin content to `Run Process` directly instead of adding a separate keyword to that. If that is done, we should think how to make it possible to create a pipeline where the stdout of one process is the stdin of another. It might be a good idea to submit a separate issue about writing to stdin.

3. If you need a custom solution, you can use `Get Process Object` keyword to get the underlying `subprocess.Popen` object. Alternatively you can create a totally custom library to interact with processes. You might also want to consider using [Pexpect](https://pexpect.readthedocs.org) instead of the plain subprocess.

**Comment by pekkaklarck** [comment]
Have you @mwalle had time to look at this? Adding full and generic interaction support to Process library may be impossible or just too much work to be worth the effort, but having a way to write to the stdin ought to be pretty easy. If that helps you, perhaps you could submit a separate issue about that and see could you create a pull request.

**Comment by mwalle** [comment]
Unfortunately I haven't found time yet. I already have a patch to write to the output of a stream:

    def write_to_stdin(self, text, handle=None):
        """Write the given text into the standard input of the process.
        
        New is Robot Framework 2.9.x.
        """
        self._processes[handle].stdin.write(text)

But this is only half the way of the interaction and having just this won't help us.

Regarding your comments:

1. of course you can use this only with cooperating processes. a shell for example or any process with user interaction, which AFAIK should flush its output because the user needs to see its output, too. The crux here is to be able to test such applications like shells.

2. see above

3. might be worth a try. Saying i won't copy the whole process spawning stuff which is already in the Process library. Is there an example in which one library extends another one or build on some keywords? Or should I use something like:

        Start Process
        ${obj}=  Get Process Object
        MyLibrary.Some Keyword  ${obj}

  Which seems rather ugly to me :)

**Comment by pekkaklarck** [comment]
I guess there could be a separate keyword for writing to the stdin, but I think it would generally be easier if you could just pass `stdin=some text` to `Run/Start Process`. It should also be somehow possible to read stdin content from a file to emulate `command < file` shell syntax. Probably even more important would be passing stdout/stderr of some other process to create a pipeline like `command | another`.

If general process interaction requires cooperation, I'm not sure is adding it into the Process library itself a good idea. If you create a custom library and notice there are some generic patterns, perhaps we can then later think about it again.

I agree getting the process object in test data and passing it to a custom keyword isn't that clean. Luckily your custom libraries can communicate with Process library directly if needed:

```python
from robot.libraries.BuiltIn import BuiltIn

def some_keyword():
    lib = BuiltIn().get_library_instance('Process')
    obj = lib.get_process_object()
```

See BuiltIn documentation and the User Guide for more details.

**Comment by pekkaklarck** [comment]
Any new info about this issue? It seems general interaction is a too big task but writing to stdin shouldn't be too hard. Should we perhaps close this issue and open a new one just for stdin? Even that would require some actually implementing it.

**Comment by mwalle** [comment]
Sorry, no news.

Frankly, this is low priority atm. And I'm still not sure if its worth to have only a stdin version. But you may close this bug, If we still need this, we may create a seperate library with the goal to integrate it into the process library once we agree on the solution.

**Comment by sgandon** [comment]
Too bad, I was looking for the possibility to write to stdin and read from the out of another process just to write a test for checking a Kafka was well setup and using a producer command line and a consumer one !
I there a workaround to send data to stdin and get from stdout ?

**Comment by mrwesleycrusher** [comment]
Here I am, almost a year later, and the best work-around I have seen is to use the ssh library, open an ssh connection to yourself, and do it that way. Although it has its limitations, it's the best I have seen floating around the web so far

**Comment by Ka55i0peia** [comment]
Are there suggestions welcome.

Recently I was faced to the same issue. I added the following keyword in a Utils library, but it can be/imho shall be integrated into robot.libraries.Process.

The following keyword does the trick for me:
```python
    def send_stdin_to_process(self, process_handle, data: str, press_enter: bool = True):
        """
        Sends `data` to process including finally an optional return key (if `press_enter` is 
        true).

        `process_handle` is the regular robot process handle returned by keyword `Start Process`
        (robot lib: Process)
        """
        press_enter = ParameterCast.asBool(press_enter)
        data = ParameterCast.asString(data)

        # get underlying process object calling the robot keyword
        process = process_lib.get_process_object(process_handle)

        if press_enter:
            data += "\n"

        process.stdin.write(data.encode())
        process.stdin.flush()
```
