### ISSUE TITLE
To append data from new Excel to mother excel

### ISSUE THREAD

**Issue by Albynok** [robotframework/robotframework#2171]
Hello,

I have started to use the Excel Library in Robot. One of my case is to take the data from an Excel and append it to mother excel sheet(main excel). Is it possible to do with my excel library?

Please suggest.
Excel Library version : '0.0.2'

Thanks and Regards,
Albyn

**Comment by pekkaklarck** [comment]
This tracker is for Robot Framework itself, not for external test libraries. Please submit issues about Excel library to its own issue tracker. General questions are typically better to be sent to robotframework-users mailing list or other support forums.
