### ISSUE TITLE
Telnet Library and binary transmission mode

### ISSUE THREAD

**Issue by mwalle** [robotframework/robotframework#2172]
The Telnet Library does not support binary transmission mode (RFC 856). In particular it discards '\x00' and '\x11' characters. 

Implementing this is easy, but there is one major drawback.. the part which throws away the characters is deep inside the process_rawq() method in telnetlib.py. So to support this we would have to overwrite this method, which essentially means copy it and replace two lines of code :( Or maybe one of you come up with another idea?

I've already filed a bug at the python issue tracker (http://bugs.python.org/issue25334) but I even this will be fixed, there will be a long time we have to support the older version.

A little bit of background, we are using the Telnet Library to connect to our serial console server and the said character are thrown away, which is no problem if you operate on a CLI only, but if you want to transfer binary data or have a binary protocol things get broken.

**Comment by pekkaklarck** [comment]
How do you propose this should be fixed?

**Comment by mwalle** [comment]
as i said, duplicating the process_rawq() method, but we should discuss this first, because:
- we won't get any updates/bugfixes for this method anymore (without manual backports)
- hopefully this method does not differ to much between the python versions

maybe some of you have another idea how to circumvent this :( you may have a cool idea what we can do before calling the process_rawq() method (replacing the characters in questions with some objects, which are converted back afterwards? dunno :( ) all of this sound like really ugly hacks.

**Comment by pekkaklarck** [comment]
Regardless how this would be implemented, couldn't not ignoring `\x00` and `\x11` potentially cause problems?

**Comment by mwalle** [comment]
of course you would still ignore it in non-binary mode. binary mode is enabled by telnet options. ie the server/client asks the other side to enable binary transmission mode.

**Comment by pekkaklarck** [comment]
Ok. How would that work in practice? AFAIK Telnet library doesn't currently know do you enable such more or not.

**Comment by mwalle** [comment]
the server asks for it and the telnet library will enable it and send a response, see _negotiate_options():

    def _negotiate_options(self, sock, cmd, opt):
        # We don't have state changes in our accepted telnet options.
        # Therefore, we just track if we've already responded to an option. If
        # this is the case, we must not send any response.
        if cmd in (telnetlib.DO, telnetlib.DONT, telnetlib.WILL, telnetlib.WONT):
            if (cmd, opt) in self._opt_responses:
                return
            else:
                self._opt_responses.append((cmd, opt))

        # This is supposed to turn server side echoing on and turn other
        # options off.
        if opt == telnetlib.ECHO and cmd in (telnetlib.WILL, telnetlib.WONT):
            self._opt_echo_on(opt)
        elif cmd == telnetlib.DO and opt == telnetlib.TTYPE and self._terminal_type:
            self._opt_terminal_type(opt, self._terminal_type)
        elif cmd == telnetlib.DO and opt == telnetlib.NEW_ENVIRON and self._environ_user:
            self._opt_environ_user(opt, self._environ_user)
        elif cmd == telnetlib.DO and opt == telnetlib.NAWS and self._window_size:
            self._opt_window_size(opt, *self._window_size)
        elif cmd == telnetlib.DO and opt == telnetlib.BINARY:
            self._opt_binary_on(opt)
        elif opt != telnetlib.NOOPT:
            self._opt_dont_and_wont(cmd, opt)

    def _opt_binary_on(self, opt):
        self._binary_transmission = True
        logger.info('Telnet server requested binary transmission.')
        return self.sock.sendall(telnetlib.IAC + telnetlib.WILL + opt)

if _binary_transmission transmission is true, no special character will be discarded.

**Comment by pekkaklarck** [comment]
Wouldn't that change the behavior too? We currently reject the binary mode and with this change it would be allowed? I don't know do servers in general try to enable binary mode, but it would be safer if there would be an option to control it.

**Comment by mwalle** [comment]
ah i now i get it. yes it would change the behaviour in case the server requests binary transmission, namely that we silently accept that mode. for me this was not a big deal, because we are just adding features, not mandates the binary mode or something like that.

but, if you connect to a server which sends you "DO BINARY-TRANSMISSION" will then get a "WILL BINARY-TRANSMISSON" instead of a "WONT BINARY-TRANSMISSON". So you'd propose a flag "accept_binary" or something similar?

For the ser2net daemon which we are using, it will try to enable it, but even if it is not negotiated as enabled, it will use it anyway.

On "normal" telnet daemons it seems that the user (ie the telnet client) has to enable the binary mode. (Just had a quick look at the BSD telnetd).

So there should be an "Enable Binary Transmission" keyword too, i guess.

**Comment by jussimalinen** [comment]
I think this can be done, assuming that the mode is strictly opt-in (`Enable Binary Transmission` works), that monkey patching of Python's telnetlib.py works in all python versions 2.6, 2.7, 3.3, 3.4, and 3.5 and that there are actually some automatic test for this functionality (monkey patching Python's own libraries is just a compatibility problem waiting to happen).

Would you be interested in doing a pull request for this? I think the automatic tests might be the most difficult part by far.

**Comment by jussimalinen** [comment]
FYI: #2230. I'm working on it.

**Comment by mwalle** [comment]
I already have the pieces together and currently working on a test case. The idea is to use a command like this:
echo -e He\x00llo

Because we know that '\0' is stripped the expected output would be:
- `Hello` if binary transmission is disabled (default)
- `He\x00llo` if binary transmission is enabled

Unfortunately, there seems to be a bug in the read_until method because:

    Write echo -e He\\\\x00llo

returns

    echo -e He\\\\x00llo
    Hello

(with a \x00 between e and l). That is, it reads until the second newline, but should only read until the first newline :(

**Comment by jussimalinen** [comment]
Are you sure that it is supposed to work? Echoing null byte to terminal?

What if you use `Write Bare` and pipe the output to a file

```
Write Bare     echo  he\\\\x00llo > output.out
``` 

And then check by hand if the content of that file contains a null byte?

**Comment by mwalle** [comment]
yeah, i've already tried that. i also verified it on the raw telnet stream that there is a null byte between "He" and "llo".
Everything seems to work, but for some reason (still evaluating) this one newline  "\r\n" is converted to "\n" by the telnetd (at least for me, i'm using the netkit-telnetd from debian jessie).

**Comment by mwalle** [comment]
i've created a request for comments pull request for this issue. tested only on python 2.7.9 at the moment.

**Comment by mwalle** [comment]
ping, any comments on the patch? :)

**Comment by pekkaklarck** [comment]
Sorry for a long delay with a reply. I looked at the changes briefly, and they look pretty simple except for the `process_rawq` part. Could you clarify why it needs to be overridden like that?

**Comment by mwalle** [comment]
Have a look at
https://github.com/python/cpython/blob/master/Lib/telnetlib.py#L434
and the following lines. I don't see any elegant solution to remove the "if char in (theNULL, '\021') continue" statement other than overriding the complete function. If you have any better idea, I'm glad to try it :)

**Comment by pekkaklarck** [comment]
Sorry for neglecting this issue for so long. Looked the patch again now and it looks good. Could you turn it into a pull request?

It's unfortunate that `process_rawq` needs to be overwritten like that but I don't see any other way to implement the binary mode either. I would prefer adding something like this to the beginning of the `process_rawq` method, though:

```python
def process_rawq(self):
    if not self._binary_mode:
        return telnetlib.Telnet.process_rawq(self)
    # Here a note about code below being (mostly) copied from telnetlib.Telnet and explaining what was changed.
    # Possibly also a reference to the Python bug you submitted.

**Comment by mwalle** [comment]
See https://github.com/robotframework/robotframework/pull/2235 for the pull request.

**Comment by pekkaklarck** [comment]
This issue and the related PR have been totally neglected due to lack of resources. Are you @mwalle still around to help if I'd now added this to RF 3.1 scope?

Notice also that after changes in `pyte` broke terminal emulation (#2693) , I've been thinking about moving Telnet outside Robot code to make it possible to develop and maintain it independently. If that's done, I'd like to do all further development outside RF.

**Comment by mwalle** [comment]
Sure. I'll try to rebase the pull request to the latest master.

**Comment by mwalle** [comment]
The last version actually works in the current master. So you could just pull it. Run the "Read And Write" testsuite with python 2.7 and python 3.5 on linux.

**Comment by JohnCC330** [comment]
Hi, all. Was this ever released?

**Comment by pekkaklarck** [comment]
We have decided to make the Telnet library an external library for reasons explained in #3537. As the result I'm closing all Telnet related issues and PRs (including this one) and linking them from #3537 as a reference. If you are interested in becoming maintainers of the new library and adding this functionality there, please comment #3537 or contact me otherwise.
