### ISSUE TITLE
"Run keyword if" cannot evaluate strings that contain EOL

### ISSUE THREAD

**Issue by impero78** [robotframework/robotframework#2174]
As in the following example:

Run Keyword If	'hello'	Log 	This works
Run Keyword If	'hello\r'	Log 	This doesnt
Run Keyword If	'hello\n'	Log 	This doesnt

It fails with the following error message:
Evaluating expression ''hello
'' failed: SyntaxError: EOL while scanning string literal (<string>, line 1)

In another situation, where i used the XML library and  for which unfortunately I cannot provide the test data (an xml containing carriage returns), a different error showed up:

${parsed_xml}	    Run Keyword If	'${xml}'	Parse Xml	${xml}

IndentationError: unindent does not match any outer indentation level (\<tokenize\>, line 4)

**Comment by pekkaklarck** [comment]
This ought to be explained pretty thoroughly in BuiltIn library docs:
http://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Evaluating%20expressions
