### ISSUE TITLE
Increase max. started KWs limit

### ISSUE THREAD

**Issue by yahman72** [robotframework/robotframework#2175]
With Jython v2.7 it's no more necessary to have the internal limit of 42. This could be increased to 100.
See #1961 for more details.

**Comment by yahman72** [comment]
FYI: The new limit is now 98, because python acceptance tests fail when `_started_keywords_threshold = 99` (with python's `maximum recursion depth exceeded` exception) , jython tests still pass.
Might be worth trying whether this limit is the same on other platforms.

**Comment by pekkaklarck** [comment]
I consider 98 too high if our tests fail with 99. There's so much variation with different platforms (OS, Python/Jython/IronPython, versions,  configs, ...) that we need a bigger safety margin.

**Comment by yahman72** [comment]
my two cents worth: 
this is probably caused by how the acceptance tests are executed i.e. with the python-test runner which takes it's share of the python's "recursion resources" - This would also explain why jython acceptance tests do not fail.
In a "real-life" scenario, i.e. starting tests with "python -m robot.run",  it fails around 120 started KWs, 

Anyway, what's the conclusion? Update the PR or are you able to test it on other platforms and update the limit accordingly? At the moment I have only win8.1 here...

**Comment by pekkaklarck** [comment]
First of all, sorry for not responding sooner. Some comments about this topic below:

1. I haven't personally seen any cases where the current limit of 42 open keywords would be an issue. Do you have any you could show?

2. I'm fine increasing the limit if it is safe. Clearly 98 is not safe is 99 is too much.

3. We some somewhat special way to run tests, but also others have such non-started solutions and could easily encounter this problem. In other setups the limit could be even lower.

4. I don't have time to investigate this issue nor test it on different operating systems and with different Python implementations and versions.

5. I'm still against the idea to add a command line option or environment variable to control the limit. That can be reconsidered if you can show valid examples where this is a problem (see 1.) and we cannot safely increase the hard-coded limit.

**Comment by yahman72** [comment]
No probs - this isn't really a burning issue...
1) see #1961:
"Yes, this was triggered by a recursive KW. In my case that recursive KW is used to analyse a text file that is generated by the SUT. Usually that file is small enough for that limit of 42, but sometimes (depending on the system load) the file is bigger and that 42 is not enough. I'm not expecting the recursion to be deeper than 150 or so."
2) okay 
3) correct, this should be considered
4) okay, me neither :-)
5) okay, my use case was somewhat special. This is not an issue for me anymore (I moved that logic into a Library), and my workaround before the library implementation was to update that hardcoded value in my fork of RF. A bit cumbersome but works also...

Conclusion? Set the limit to something lower? 80?

**Comment by pekkaklarck** [comment]
I'm not sure how good example a recursive user keyword is:
- Even if we raise the limit, you can easily exceed it. 
- In practice such keywords create so big output.xml files that you have other severe problems. It is much better to move the logic to a library like you did.

If we raise the limit, the new limit needs to be tested with all supported operating systems and Python interpreters. IIRC, there are tests for the current limit and updating and running them ought to be enough. Are you interested in it?

**Comment by yahman72** [comment]
I don't have the possibility to run those test on different OSs and/or interpreters. I only have win8 (64-bit) environments at hand...

**Comment by pekkaklarck** [comment]
Assuming you have admin rights, you can install Linux to a virtual machine. OSX ought to be close enough to Linux in this regard so we can ignore it. This kind of change should be tested at least with Python 2, Python 3, Jython, IronPython (only Windows) and PyPy, so there's anyway quite a lot to test. I don't think that's worth the effort, especially when we already know that we cannot raise the limit that much. If you disagree, please reopen the issue or submit a new one.

**Comment by pekkaklarck** [comment]
The limit will be increased in RF 5.0 (#4191).

**Comment by pekkaklarck** [comment]
RF 7.2 changes recursion prevention so that instead of there being a hard limit of started keywords and control structures, execution is stopped if we are close to Python's [recursion limit](https://docs.python.org/3/library/sys.html#sys.getrecursionlimit) (#5272). On my system this change raised the allowed number of started keywords and control structures to roughly 150. If that's not enough, you can increase Python's recursion limit to allow even deeper recursion.
