### ISSUE TITLE
Execution Timeout

### ISSUE THREAD

**Issue by serhatbolsu** [robotframework/robotframework#2178]
We have an system that other outside users can upload their test and run in our servers.
Sometimes a keyword (thats has no timeout) can run and it never returns response. In that case, it gets stuck. At this point the test case will never end so the execution will not.

I would really like an `argument` to robotframework run, so that I could append to user arguments. There could be two arguments, one for whole execution, one for each test case. This could be like hard timeout. 

Yes there is **[Test Timeout]** and **[Timeout]** however these require the user to put them there. What I would like is to release my server and it seems to go on without any stop right now. 

BR,

**Comment by pekkaklarck** [comment]
Did I get it right that you'd like to have a command line option to give a maximum time for the whole execution and for individual tests? Sounds OK to me, assuming you or someone else is willing to provide a pull request.

Notice also that max time for the whole execution could be easily controlled externally by a script/tool running Robot. It just needs to send SIGINT or SIGTERM signal to Robot if timeout occurs. Same functionality could then also be used to gracefully stop the execution by user.

**Comment by serhatbolsu** [comment]
Yes @pekkaklarck thats is true that I am looking for an command line option. 

for pull request, I dont assume myself qualified to enter robot code. 

Btw yes, shell script could be used however putting an full timeout is not ideal. Much better to force test timeout. Since if I put a hard time it might limit the user to put many test cases as well

**Comment by pekkaklarck** [comment]
You actually ought to be able to add a timeout for every executed test by using `--prerunmodifier`: http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#programmatic-modification-of-test-data

In general if you want new functionality in RF itself, you pretty much need to implement it yourself or find (and pay) someone else to implement it. You might get lucky that someone else needs same functionality and implements it, but I wouldn't count on that. If nobody is going to implement a feature request, we typically close the issue.

**Comment by serhatbolsu** [comment]
I see your point, if you and core team does not see the necassity I will look for alternative ways for now. Maybe other people need this feature, and raise hands in here.

BR,

**Comment by pekkaklarck** [comment]
Closing this for now. Can be reopened if someone needs this badly enough to either create a pull request or sponsor development.
