### ISSUE TITLE
Add newline control to `OperatingSystem.Get File`

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#2183]
If RF 2.9 and earlier `Get File` used `open()` to open files in binary mode and simply converted possible `\r\n` (Windows newline) into `\n` and didn't touch possible lone `\r`. To ease supporting Python 3, we have changed `Get File` to use `io.open` (see revision c3a9dd142596ab854676e03c57c5ab135884753d) which, by default, converts both `\r\n` and `\r` to `\n` (see docs at https://docs.python.org/2/library/io.html#io.open). That change is backwards incompatible and actually broke some of Robot's own acceptance tests that relied on `\r` being left intact.

Using `io.open` and by default converting also `\r` to `\n` is probably a good idea. What we should do is adding support for a new `newline` argument that controls newline handling. We can simply pass the value to `io.open` and use `None` as the default.

Unfortunately `Get File` still uses `open` with IronPython where `io.open` is buggy. We need to decide do we want to support this functionality with IronPython at all.

**Comment by pekkaklarck** [comment]
Other things to consider:
- Should we add newline control also to `Grep File`?
- Should we rather change the code so that only `\r\n` is converted to `\n`? Should we still support configurable newline control?

**Comment by jussimalinen** [comment]
We decided to not implement the `newline` argument for `Get File` in the end. We could not think of a use case where that would be needed. The default as it was earlier (`\n` and `\r\n` are newlines) seems good enough. You can always use `Get Binary File`...

**Comment by jussimalinen** [comment]
still should be documented how it works

**Comment by jussimalinen** [comment]
Actually current documentation is enough, but as nothing has changed in functionality, we should actually wont fix this.
