### ISSUE TITLE
SSH connection via SSH proxy command defined in ~/.ssh/config

### ISSUE THREAD

**Issue by jb185t** [robotframework/robotframework#2186]
Hi, there;

What I'm trying to do with RF is to remotely ssh to a server via a ssh proxy server using public/private key. 

machine-c  ------------> machine-p  ------------> machine-t
(ssh client)                   (ssh proxy)                  (target server)

From a ssh client machine-c, a ssh connection is first made to a ssh proxy machine-p then additional ssh connection to a target server machine-t. The ssh proxy is defined in ~/.ssh/config as below in client machine-c;

Host machine-p
  Hostname 10.10.10.10

Host machine-t.example.com
  ProxyCommand ssh machine-p nc  machine-t.example.com

On Linux CLI, giving  "ssh machine-t.example.com" takes me into machine-t successfully without asking password. And the log message in /var/log/secure at machine-t.example.com shows that a ssh connection came from ssh proxy machine-p.

However, if I do the same ssh connection request using Robotframework ssh library, it looks like it is not reading ~/.ssh/config and establishes connection directly to target machine-t. The log in /var/log/secure at machine-t.example.com tells me that it is from machine-c not from machine-p. Is this expected RF behavior or am I missing something?
 
I'm using Python 2.6, paramiko-1.9.0 and Robotframework 2.9.1 with SSH library 2.1.1. 

Would appreciate your response on this.

Joon.

**Comment by pekkaklarck** [comment]
This issue tracker is for Robot Framework itself. Please submit SSHLibrary issues to its own tracker.
