### ISSUE TITLE
Keyword argument multiple lists

### ISSUE THREAD

**Issue by sbrugman** [robotframework/robotframework#2187]
A keyword now only supports one single list, which is limiting in some cases where abstraction is desired, with multiple parameters.

Example: a keyword sets a few configuration items of different categories in one single screen. You would normally use @{argumentsType1} and @{argumentsType2} or something similar for this.

**Comment by pekkaklarck** [comment]
Please clarify. An example would be good.

**Comment by sbrugman** [comment]
When setting the configuration in a page where there are two or more lists of options. It is usefull to set this at once, because then it is not required to open the window again and apply again etc. You would expect robot framework to accept this, but it does not.

```
*** Keywords ***
Keyword with multiple list arguments
    [Arguments]   @{argumentsType1}     @{argumentsType2}
    Open window for configuration
    Set type 1 settings         @{argumentsType1}
    Set type 2 settings         @{argumentsType2}
    Click apply
    Click close
```

**Comment by pekkaklarck** [comment]
This cannot be implemented. There's no way Robot would know how to split arguments to the specified lists if the keyword would be called like

    Keyword with multiple list arguments    1    2    3    4    5    6    7    8    9

If you need two lists, you can just accept two normal arguments and make sure you pass in two lists:

    Keyword with multiple list arguments    ${list1}    ${list2}

**Comment by Tanmay-Agrawal** [comment]
Hello,

Based on the above comment i tried something like this:


***Settings***
Library  BuiltIn
Library  Collections
Library  String

***Variables***
@{Test}  1  2  3  4=

***Keywords***
Add Elements  
  [Arguments]  ${TestLength}  ${TestLength2}  
  #${Length2}  Get Length  ${TestLength}
  Log To Console  ${TestLength}
  #Set Test Variable  ${TestLength2}  None
  #${TestLength2}   Fetch From Left    ${TestLength}  4=
  #${Length2}  Get Length  ${TestLength}
  Log To Console  ${TestLength2}}

***Test Cases***

P1  
  Add Elements  @{Test}  5  6


**I am Getting the following error:**

Keyword 'Add Elements' expected 2 arguments, got 6.


What I am doing wrong here??

**Comment by Ashutosh-Chauhan93** [comment]
@Tanmay-Agrawal - i was facing the same issue , it got resolved by using **named arguments** as parameters 
by using named arguments robot fwk will know where exactly to split the 2 list arguments
Only thing we need to ensure that named argument should only come after unnamed ones

In your case, following workaround will work fine

*** Settings ***
Library BuiltIn
Library Collections
Library String

*** Variables ***
@{Test}  1 2 3 4

*** Keywords ***
Add Elements
    [Arguments]  @{TestLength2}  ${TestLength}
#${Length2} Get Length ${TestLength}
    Log To Console  ${TestLength}
#Set Test Variable ${TestLength2} None
#${TestLength2} Fetch From Left ${TestLength} 4=
#${Length2} Get Length ${TestLength}
    Log To Console  ${TestLength2}

*** Test Cases ***

P1
    Add Elements  5  6  TestLength=@{Test}


OUTPUT:
P1                                                                    **[u'1 2 3 4']**
**[u'5', u'6']**
P1                                                                    | PASS |
------------------------------------------------------------------------------
Trying2                                                               | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed
