### ISSUE TITLE
`${TEST_MESSAGE}` is not updated by `Set Test Message` keyword

### ISSUE THREAD

**Issue by osjc** [robotframework/robotframework#2188]
When you use BuiltIn.SetTestMessage to set or amend the message in the test, the ${TEST_MESSAGE} variable still shows the original test message. Additionally, the BuiltIn.SetTestMessage is confusing because in one sentence it states that "the original test message is available as a built-in variable ${TEST_MESSAGE}" but then proceed to show an example where the test message is altered and then ${TEST_MESSAGE} is checked to see that the alteration is in place.

Occurs in 2.9 and also found in the latest tip version.

I created a patch to fix this (the cause looks like omission in the code).

**Comment by pekkaklarck** [comment]
It really looks like we've just forgot to set the variable. Thank's for the report and a PR. Tests in the PR require still some work, but I comment the PR separately.

**Comment by pekkaklarck** [comment]
Fixed by PR #2191. Thanks @osjc both for reporting the issue and for the PR.
