### ISSUE TITLE
`BuiltIn.Import Resource` does not work on standalone jar when no directories in `sys.path`

### ISSUE THREAD

**Issue by ankit87** [robotframework/robotframework#2192]
I am trying to run a simple robot test which tries to import a resource file using "Import Resource" keyword using maven plugin 1.4.5 version (with robotframework 2.9.2 dependency) but it is failing with error message "Resource file <file name> does not exist".

I am using the Import Resource keyword in the following format:
Import Resource             ${CURDIR}${/}variables.tsv

Strange thing is that if i try to run the same test using jybot or pybot, the same test runs successfully. Please see robot report (import_resource_report_using_jybot) when tests are run using jybot. 

NOTE:
1. I have tried using maven 2.2.1 and 3.0.5 and it fails with both the versions
2. I am trying using maven plugin version 1.4.5 and robot 2.9.2/2.9.1
>			<plugin>
				<groupId>org.robotframework</groupId>
				<artifactId>robotframework-maven-plugin</artifactId>
				<version>1.4.5</version>
				<dependencies>
					<dependency>
						<groupId>org.robotframework</groupId>
						<artifactId>robotframework</artifactId>
						<version>2.9.2</version>
					</dependency>
				</dependencies>
>			</plugin>			

3. If I use robot framework 2.8.7 with same 1.4.5 maven plugin, the same test pass, that means it is a regression with 2.9.1/2.9.2 robot framework version.
4. If you observe the attached sample test file, I am also using OperatingSystem.Get File keyword which works fine without any issues.

Could you please take a look and suggest if we need to configure any additional properties to be able to run tests successfully using maven plugin. 
Due to this issue, a lot of our existing tests using Import Resource keyword (which were working with previous version) are failing and therefore couldn't use this version

Below is a snapshot of test implementation:
![importresourcetest](https://cloud.githubusercontent.com/assets/15625439/10902643/eb66d390-8226-11e5-871f-b1f43ecac25b.JPG)

Below is a snapshot of robot logs when run using jybot and robot framework 2.9.2 where Import Resource keyword pass.
![import_resource_report_using_jybot](https://cloud.githubusercontent.com/assets/15625439/10903622/b9fe41a2-8231-11e5-99de-3381e326a2de.JPG)

Below is a snapshot of robot logs when run using robot 2.9.2 and maven plugin 1.4.5 where Import Resource keyword fail.
![import_resource_report_using_maven](https://cloud.githubusercontent.com/assets/15625439/10903623/b9fe74d8-8231-11e5-8a89-28a47eed892a.JPG)

**Comment by ankit87** [comment]
just looking to know if anyone got any idea to this?

**Comment by pekkaklarck** [comment]
If it works correctly with Robot but not when you use it via the Maven plugin, the problem seems to be in the latter. Have you verified is the path to the imported resourse file correct?

**Comment by ankit87** [comment]
Yes, I am pretty sure that path to the imported resource file is correct as the same script without making any changes works fine when running tests directly using pybot oy jybot but not when running using maven plugin.
This issue is blocking us from upgrading to robot 2.9 (which we are eager to upgrade to as it contains a lot of enhancements/fixes)

**Comment by pekkaklarck** [comment]
If it works with RF itself but not with Maven plugin, you should submit the issue to Maven plugin's tracker. This is not easy to reproduce, so you should preferably create a simple example that we clould execute in our environments. For details why see http://sscce.org

One change in 2.9 was that the execution directory is not anymore set to Python's module search path. Robot uses that search path also when importing resources so it could cause issues like this. It shouldn't cause problems when importing with an absolute path and whatever problems it causes should occur also without the Maven plugin, though.

**Comment by ankit87** [comment]
I have created a simple example maven project but unfortunately i can't upload zip files on github. Do you know if there is any way to do so?
Btw, I am uploading sample robot test txt files here for reference and also pom.xml (as pom.txt) i am using.
[ImportResourceTest.txt](https://github.com/robotframework/robotframework/files/42842/ImportResourceTest.txt)
[variables.txt](https://github.com/robotframework/robotframework/files/42843/variables.txt)
[pom.txt](https://github.com/robotframework/robotframework/files/42844/pom.txt)

**Comment by pekkaklarck** [comment]
Could you @jussimalinen take a look at this?

**Comment by jussimalinen** [comment]
Yeah, I have replicated the issue. No idea what happens. I will continue debugging this. Thanks for the examples!

**Comment by jussimalinen** [comment]
This is not related to Maven. Currently the system that finds the resource files to import does not work if there are no directories in search path. Any local import will always have those as will any test run that uses --PYTHONPATH argument (like our own acceptance tests).

The commit a535ce9 fixes the issue, but some new tests or changes to old ones are definitely needed.

As a workaround just add any directory to path. In maven this can be done by adding `extraPathDirectories` setting with any path to an existing directory.

```xml
          <extraPathDirectories>
            <extraPathDirectory>${basedir}/any/path/that/exists</extraPathDirectory>
          </extraPathDirectories>
```

**Comment by ankit87** [comment]
Thanks, I can confirm that workaround is working and makes Import Resource keyword to work even when running tests using maven plugin and robot 2.9 version.

**Comment by gadechakrapani** [comment]
in this  case you have to use absolute path
example:C:/Development/robot-scripts/keyword-demochakritwo/Resourcestwo/Amazon.robot
