### ISSUE TITLE
Telnet: Read after Write Bare has null output

### ISSUE THREAD

**Issue by manycoding** [robotframework/robotframework#2193]
Was "Write Bare" made in the way to not return anything nor provide any output to Read?

Servlet Should Be Running
    Import Library    Telnet
    Open Connection    ${SERVER}    port=80  timeout=15
    ${result}=    Write Bare    GET / HTTP/1.1\n\n
    ${result}=    Read
    Should Contain    ${result}    Endpoint does not exist
    [Teardown]    Close All Connections

KEYWORD ${result} = Telnet . Write Bare GET / HTTP/1.1\n\n
Documentation: 	

Writes the given text, and nothing else, into the connection.
Start / End / Elapsed: 	20151105 13:02:11.413 / 20151105 13:02:11.414 / 00:00:00.001
13:02:11.413 	TRACE 	Arguments: [ 'GET / HTTP/1.1\n\n' ] 	
13:02:11.414 	TRACE 	send 'GET / HTTP/1.1\n\n' 	
13:02:11.414 	TRACE 	Return: None 	
13:02:11.414 	INFO 	${result} = None 	
00:00:00.000 KEYWORD ${result} = Telnet . Read
Documentation: 	

Reads everything that is currently available in the output.
Start / End / Elapsed: 	20151105 13:02:11.415 / 20151105 13:02:11.415 / 00:00:00.000
13:02:11.415 	TRACE 	Arguments: [  ] 	
13:02:11.415 	TRACE 	Return: '' 	
13:02:11.415 	INFO 	${result} =

**Comment by jussimalinen** [comment]
What do you expect to happen here? `Write Bare` will never return anything. It just writes the bytes you command it to. `Read` will just read the output currently available in socket, and that can be nothing if the server has not had time to respond.

I guess you could try to `Read until` or `Read until regexp`, if you know what you are waiting for. (Maybe `Read until   Endpoint does not exist` in your case?) But the correct handling on HTTP 1.1 would mean that you read first the server´s response for the length of the response and then read until that many bytes are out... And that sounds like a lot of work to do on top of this interface. Basically implementing HTTP1.1 stack over Telnet.

In general you probably shouldnt be interacting with a HTTP server over Telnet. There are specialised HTTP libraries available that make the interactions much easier.
