### ISSUE TITLE
setup.py fails to install robotframework for python 2.7 due to python 3 metadata class

### ISSUE THREAD

**Issue by jaloren** [robotframework/robotframework#2194]
I am on the latest version of RF source as of today. When I do a setup.py install, I see the following error.

```python
Extracting robotframework-2.9.3.dev20151102-py2.7.egg to /Users/jaloren/.virtualenvs/exclude/lib/python2.7/site-packages
  File "/Users/jaloren/.virtualenvs/exclude/lib/python2.7/site-packages/robotframework-2.9.3.dev20151102-py2.7.egg/robot/model/modelobject3.py", line 18
    class ModelObject(metaclass=SetterAwareType):
                               ^
SyntaxError: invalid syntax

Adding robotframework 2.9.3.dev20151102 to easy-install.pth file
Installing pybot script to /Users/jaloren/.virtualenvs/exclude/bin
Installing rebot script to /Users/jaloren/.virtualenvs/exclude/bin
```

**Comment by pekkaklarck** [comment]
Are you sure you have pulled the latest changes? This ought to be fixed a little time ago.

**Comment by jaloren** [comment]
I did an upstream pull a few minutes ago. Here's the last commit that I have. It looks like it matches the latest RF commit in github. I am on Mac with python 2.7 in a virtual environment. Not sure if that matters either way.

commit 4b543bd714b287bd7ad01ee83aabb4e48ec9bd58
Author: Jussi Malinen <jussi.ao.malinen@gmail.com>
Date:   Fri Nov 6 15:52:53 2015 +0200

    Python 3 compatibility, missing file form previous commit

**Comment by pekkaklarck** [comment]
That ought to be the latest commit or at least a commit after this was supposed to be fixed. Could you try removing build directory and pyc files?

**Comment by pekkaklarck** [comment]
This ought to be fixed in 5ddd5fe.

**Comment by jaloren** [comment]
I deleted build directory, removed all pyc files, did a git clean and a git reset, created a brand new virtual environment and then did the install. It worked this time. 

Sorry for the bother.

**Comment by pekkaklarck** [comment]
No worries!
