### ISSUE TITLE
date time-get current date, get wrong format

### ISSUE THREAD

**Issue by nurruden** [robotframework/robotframework#2195]
Hi,
Not sure if I have something wrong about get current date, i just want to get the date like 2015-11-09 12:52. so I define date1 as "${date1} =  Get Current Date   increment=00:02:00, date_format='%Y-%m-%d %H:%M'", but the date1 returns the format like 2015-11-09 12:52:53.123, so the date_format did not work, but I did not get any error message. Did I do something wrong? My datetime version is DateTime-4.0.1

**Comment by laurentbristiel** [comment]
Hi,

I am surprised by the DateTime version you mention.
The last version is 2.9.2 [on the official documentation](http://robotframework.org/robotframework/latest/libraries/DateTime.html#Get%20Current%20Date).

Now, for your problem, the second argument is not correctly named.
You use date_format instead of result_format

Here is an example:

```robotframework
*** Settings ***
Library  DateTime

*** test cases ***
date
  ${date1} =  Get Current Date  increment=00:02:00  result_format='%Y-%m-%d %H:%M'
  log to console  ${date1}    
```

The output:
```shell
$ pybot date.robot
==============================================================================
Date
==============================================================================
'2015-11-09 09:42'
date                                                                  | PASS |
------------------------------------------------------------------------------
```

Hope this helps.
(if so, please close the issue)

**Comment by nurruden** [comment]
Hi, 
Sorry for the version, I am just a green hand for robot framework. Actually I just used both date_format and result_format, however, I got same format 2015-11-09 12:52:53.123. here is my case:
*** Settings ***
Library     Selenium2Library
Library     DateTime
*** Variables ***

*** Keywords ***
Select Type
    click element  //*[@id="radio-1338-inputEl"]
Select Start Time
     ${date1} =  Get Current Date   increment=00:03:00, date_format='%Y-%m-%d %H:%M'
    Input Text  start   ${date1}
Select End Time
     ${date2} =  Get Current Date   increment=00:05:00, result_format='%Y-%m-%d %H:%M'
    Input Text  end   ${date2}
    sleep   2

**Comment by laurentbristiel** [comment]
${date2} should contain the value properly formatted.
Could you add a `log to console  ${date2}` statement to show us what you get?

**Comment by nurruden** [comment]
I can run your example successfully. but if I change my date2 to 
Select End Time
    ${date2} =  Get Current Date   increment=00:05:00, result_format='%Y-%m-%d %H:%M'
   # Input Text  end   ${date2}
    log to  console    ${date2}
I will run into the error:
No keyword with name 'log to' found. Did you mean:
    Selenium2Library.Go To
    Login_to_NS.Login To NS
you can check my code at https://github.com/nurruden/Robot_readable/blob/master/Resource/PO/SpecifyTime.robot

**Comment by laurentbristiel** [comment]
> No keyword with name 'log to' found
then it means that there is more than one space after "log to" 
you should write "log to console" with max 1 space between each word.

**Comment by nurruden** [comment]
Thanks
Output is:
Specify Schedule Time                                                 2015-11-10 10:20:12.749
Specify Schedule Time                                                 | PASS |
seems result_format not work.

**Comment by nurruden** [comment]
Now I know the root cause, extra comma wad added. My original code is :
${date2} = Get Current Date increment=00:05:00, result_format='%Y-%m-%d %H:%M'
Actually, it should be:
${date2} =  Get Current Date  increment=00:04:00  result_format=%Y-%m-%d %H:%M
Many thanks for you help.

**Comment by Muddesir** [comment]
Suppose today is 26/1/2016, but i want to select 25/1/2016 in my calendar.So how should i write the code for that.
And I wrote a code like this , buts its showing error 'Get Current Date deccrement 01/00/00' found
 ${date2}    Get Current Date deccrement 01/00/00    result_format %d/%m/%Y
    Input Text    ${STARTTIME}    ${date2}
Please help me solving this issue..

**Comment by Muddesir** [comment]
After changing the code to >> ${date2} Get Current Date deccrement=01/00/00, result_format=%d/%m/%Y
Input Text ${STARTTIME} ${date2} 
The next error is "ValueError: Unsupported timezone 'deccrement=01/00/00,'."

**Comment by Muddesir** [comment]
@marthaladhanusha   Please try the below code, it will work for you. 

Get User Time
    [Documentation]  Get the time
    ${Time}    robot.libraries.DateTime.Get Current Date
    Log to console    ${Time}
    ${Real}      DateTime.convert date	 ${Time}    result_format=%Y-%m-%d %H:%M:%S %p  


![image](https://user-images.githubusercontent.com/24763195/47787189-12e78200-dd34-11e8-86c8-842230933b6c.png)

**Comment by santoshhpgs** [comment]
how to convert  from Mon Nov 26 09:20:47 CET 2018 to   2018-11-26T09:20:47 format in robot
