### ISSUE TITLE
Changes to internal utility functions and classes

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#2200]
This issue tracks  changes to internal utility functions, classes, etc. in the `robot.utils` package in RF 3.0.

Changed | Replacement | Comment
---------|-------------|--------------
decode_output | console_decode |
encode_output | console_encode |
decode_from_system | system_decode |
encode_to_system | system_encode |
html_attr_escape | attribute_escape | Replacement has been available since RF 2.8.

Related to this, unnecessary aliases where removed from `robot.utils.asserts` as part of #2202.

**Comment by pekkaklarck** [comment]
There are no more changes planned so I'll close this issue. Possible changes can still be added here later.

**Comment by pekkaklarck** [comment]
Result related model objects `TestSuite`, `TestCase`, `Keyword` and `Message` were moved to common `robot.result.model` module. Old `robot.result.(testsuite|testcase|keyword|message)` modules have been removed. See 1622eea for details.

**Comment by robertr0** [comment]
http://askubuntu.com/questions/614657/install-gnome-desktop-ubuntu-15-04

sudo apt-get install ubuntu-gnome-desktop
sudo service gdm restart


http://www.techrepublic.com/blog/linux-and-open-source/how-to-install-gnome-38-on-ubuntu/

*sudo add-apt-repository ppa:gnome3-team/gnome3*

s*udo apt-get update && sudo apt-get install gnome-shell ubuntu-gnome-desktop*
