### ISSUE TITLE
Robotframework 2.9.2 The keyword "Set Variable" no longer works.

### ISSUE THREAD

**Issue by pdjouob** [robotframework/robotframework#2210]
After installing the 2.9.2 version I have a regression test cases. Indeed, the keyword "otot" is no longer recognized.

Exemple :+1: 
*** TestCase***
INT_PFA_SIS_SMM_OPER_CFG_INIT_251
   ...
   ${dut}=   Set Variable   ${ip_admin_dut}
   ${testuser}=   Set Variable   ${current_user}
  ....
=> I have an error "${dut} not found whereas before it worked

workaround in my case :+1: 
Use "Set Test Variable" instead of "Set Variable"
=> Set Test Variable   ${dut}   ${ip_admin_dut}
...

Best regards
Patrick

**Comment by jussimalinen** [comment]
You did not mention in which version the code worked, but most likely you were using a version before 2.9 and using the "feature" where variables leaked to lower level keywords. See #532.

This was removed in 2.9.

**Comment by pdjouob** [comment]
Thanks for the reply. :-)
It worked with version 2.8.7

**Comment by jussimalinen** [comment]
If your issue is not the one mentioned above we can reopen this issue, but otherwise you have to either update your tests or keep on using 2.8.7.

**Comment by pdjouob** [comment]
Actually I've updated my tests by replacing with "Test Set Variable" I find most suitable.

Regards, ;-)

**Comment by pdjouob** [comment]
I meant "Set Test Variable" :-)
