### ISSUE TITLE
Cannot recognize keyword "Resource"

### ISSUE THREAD

**Issue by nurruden** [robotframework/robotframework#2211]
Hi, sorry to broadcast, I know maybe it is not a bug, but I cannot find its root cause.
Here is my case:
*** Settings ***
Documentation    Add standalone LSP
Resource  Resource/Login_to_NS.robot
Resource  Resource/AddStandaloneLSP.robot
*** Test Cases ***
Login to NorthStar
    Login_to_NS.Login to NS
Add Stand-alone LSP
    AddStandaloneLSP.Add LSP
    AddStandaloneLSP.Submit
then run this case, error message pop up:
******************************************************************************************************************************
C:\Users\allanyang\Downloads\Python_file\Robot_readable>pybot -d Results Tests/testswinglibrary.robot
[ ERROR ] Error in file 'C:\Users\allanyang\Downloads\Python_file\Robot_readable\Tests\testswinglibrary.robot': Resource file 'Resource\Login
_to_NS.robot' does not exist.
*******************************************************************************************************************************
but the resource file just exist, not sure why pop this error message.

**Comment by jussimalinen** [comment]
Most likely you have some problem with paths. Either the parent folder of Resource has to be in PYTHONPATH or the Resource folder has to be in the same fodler where your test suite file is.

You should ask this kind of questions in the robot framework users group. Please continue the discussion there.
