### ISSUE TITLE
RobotFramework with dojo table, selenium.

### ISSUE THREAD

**Issue by HeiterB** [robotframework/robotframework#2212]
Hi!
I want to copy a text (a date) from a DOJO table, after that, I want to paste to a Text Field (on the same page)
My problem is that i cant right click to the table and inspect the element, so I have to click the border of the table where i can inspect, than i go down to the right place where the date is.
But there isn't a unique ID for that cell.

I tried a several things, like  Get Text    xpath=//td[@class='dojoxGridCell'][2]
                                                         driver.FindElement(By.CssSelector("div > dojoxGridRow:nth-child(1) > table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(2)")
Neither worked for me.

![wproblem](https://cloud.githubusercontent.com/assets/15831544/11144260/b1fa960a-89fb-11e5-9f16-58cbe75341b4.jpg)
![wproblem2](https://cloud.githubusercontent.com/assets/15831544/11144268/bab0418c-89fb-11e5-926f-7a6f849e0604.jpg)

Screenshots attached.
Any Idea?

Thanks!

Best regards.
Balázs Heiter

**Comment by HelioGuilherme66** [comment]
This is not really a bug. You should ask this kind of questions in the robotframework group [1].

Have you tried the ```Get Table Cell``` keyword? Read about it at [2].

[1] - http://groups.google.com/group/robotframework-users
[2] - http://robotframework.org/Selenium2Library/doc/Selenium2Library.html#Get%20Table%20Cell

**Comment by HeiterB** [comment]
I've already tried get table cell keywork. it isn't worked for me either.
at the google forum, i am waiting for the moderator. I have this message: "To avoid spam, first messages from new members are moderated"

**Comment by pekkaklarck** [comment]
@HelioGuilherme66 is right that questions like this belong to other forums than this issue tracker. Especially then the questions is about Selneium2Library, not Robot Framework itself. That said, sorry @HeiterB for a little lack in moderating your question. Should be approved now.
