### ISSUE TITLE
String: provide a strip keyword

### ISSUE THREAD

**Issue by mwalle** [robotframework/robotframework#2213]
Similar to the python [l,r]strip() method. This will eliminate hacks like:

    ${output}=  Evalutate  '${output}'.strip()

**Comment by pekkaklarck** [comment]
Good idea. I actually though String library would already have a keyword for this. Some comments:

1. I think `Strip String` would be a better name.

2. I like the idea to have just one keyword that can optionally strip only from left or right. Using it like like `Strip String | ${str} | left=no ` when you want to strip from right is a bit weird, though. @jussimalinen proposed adding using argument like `strategy` or `mode` that has default `both` but can be used with `left` or `right` too like `String String | ${str} | mode=right`. What do you think about that?

3. There are some smallish code and doc issues that I'll comment in the PR you created.

If you are interested to work with this a bit more, I don't see any reasons why we could add this in RF 3.0. I actually consider this such a good idea that I add into its scope already.

**Comment by mwalle** [comment]
1. ok
2. you are right, i couldn't come up with something better. i'd prefer `mode`. Should we raise a ValueError or a RuntimeError if mode isn't one of the expected values. Both error classes seem to be used for this kind of error.
3. ok

**Comment by pekkaklarck** [comment]
`ValueError` and `RuntimeError` are both OK. I'd probably use the former in this case because the value clearly is wrong. An easy way to dispatch is using something like this:

```python
try:
    method = {'BOTH': string.strip, 
              'LEFT': string.lstrip,
              'RIGHT': string.rstrip}[mode.upper()]
except KeyError:
    raise ValueErrror("Invalid mode '%s'." % mode)
return method(characters)
```

**Comment by pekkaklarck** [comment]
No we need to support an option that does no stripping? If yes, adding something like `'NONE': lambda chars: string` to the above dictionary ought to be enough.

**Comment by mwalle** [comment]
yeah already thought of this too. but the only case i could come up with, where you need mode=none would be something like this:

    ${mode}=<some computation>
    Strip String  mode=${mode}

Which could also be done with Run Keyword If/Unless. So i decided to keep it simple and don't baffle the user with `Strip String | mode=none` which equals `No Operation`. Your choice :)

**Comment by pekkaklarck** [comment]
The latest version of PR looks great. Most of my comments to it were pretty nitpicky, but at least the problem in examples should be fixed. Please add a new line under you name in AUTHORS too and this ought to be ready to be merged.

**Comment by mwalle** [comment]
Thats ok, i'll like to have a patch 'clean', too ;-)

**Comment by pekkaklarck** [comment]
Merged. Thanks for the PR @mwalle!!
