### ISSUE TITLE
How to handle Chinese in variable file

### ISSUE THREAD

**Issue by luisxiaomai** [robotframework/robotframework#2215]
Hi,

I wrote some Chinese words in variable file (data.py) like below:
```
#coding=utf-8
var1="中国"
var2=["中国","fdfd"]
var3={"usercode":"1","ming":"sfsfd"}
```
I imported this file into test suite, but it can't display Chinese correctly, it displays  Chinese "中国" to "\xe4\xb8\xad\xe5\x9b\xbd". Please help on this, thanks.

Thanks.
Luis

**Comment by jussimalinen** [comment]
This works just fine if you declare the variables as python 2 unicode strings with the `u` prefix.

```
#coding=utf-8
var1=u"中国"
var2=[u"中国",u"fdfd"]
var3={"usercode":"1","ming":"sfsfd"}
```

**Comment by luisxiaomai** [comment]
Thanks for your answer, it was ok.

But I want to know why I used python to run "print var1" without u prefix, it works. If it can be done from robot framework side?  I hope that , we don't need u prefix for Chinese in variable file.

**Comment by pekkaklarck** [comment]
That's how Python 2 handles Unicode:
https://docs.python.org/2/howto/unicode.html

In Python 3 strings are Unicode by default and the `u` prefix isn't needed anymore. We hopefully have RF 3.0 alpha 1 with Python 3 support released this week.
