### ISSUE TITLE
New `robot` start-up script to replace `pybot`, `jybot` and `ipybot`

### ISSUE THREAD

**Issue by jussimalinen** [robotframework/robotframework#2216]
Now that we start supporting more interpreter types, like python 3 and perhaps pypy in future, it starts to get quite a bit much to create a new starter script for each. (pybot, pybot3, pypybot...?) And what when there will be 3-versions of ironpython and jython?

It seems like a good time to go for the generic `robot` starter script, which would be for the version that was last installed. It is rather rare to need to run robot on multiple interpreters on the same machine. And if that is needed, there is always the option `jython -m robot.run`.

For now we should just install the new script along with the old scripts. Then maybe in future versions we can start deprecating the old scripts.

UPDATE: We also decided to use `rebot` with all interpreters. `jyrebot` and `ipyrebot` will continue to work as earlier for now.

**Comment by pekkaklarck** [comment]
Code changes look good and updating `r?bot.bat` wasn't as hacky as I was afraid. Doc changes are to be reviewed separately, but I still want to test the new Windows scripts with virtual environments.

**Comment by jussimalinen** [comment]
Also, now we tested this on all sorts of platforms, including virtualenv and everything works like a charm. The new `robot` script also now sets the complete path to actual interpreter, unlike `pybot`, `jybot` and others, which simply call `python` or `jython` and assume that the interpreter in path is the correct one.

**Comment by pekkaklarck** [comment]
Tested with virtual environments both on Linux and Windows. Worked great! I consider this issue done.
