### ISSUE TITLE
No more binary installers for Windows

### ISSUE THREAD

**Issue by jussimalinen** [robotframework/robotframework#2218]
Previous Robot versions have been distributed also as a Windows installer. Now that we start supporting Python 3, that would require us to create four distributions: 32bit python 2, 64bit python2, 32bit python 3, and 64bit python3. This starts to get quite cumbersome. Also pip starts to come with all new installations on python, so maybe it's the time to ditch windows installers.

If this causes too much trouble for the users we can consider still making the installers.

**Comment by pekkaklarck** [comment]
In 3.0 alpha 1 it is enough to mention that we do not plan to create Windows installers anymore. Updating installation instructions can wait until later.

**Comment by jussimalinen** [comment]
How to install:
1. use pip: `pip install robotframework`
2. use pip with a locally downloaded file (works without network): `pip install robotframework-3.0.tar.gz`
3. extract the source tar and install manually: `python setup.py install`

**Comment by pekkaklarck** [comment]
We now have #2222 that tracks installation related changes that must be done before the final 3.0 release. The plan not to create Windows installers is already documented in RF 3.0 alpha 1 release notes. This issue can be closed.

**Comment by pekkaklarck** [comment]
Notice that if you absolutely must have Windows installers, you can create them yourself. First you need to get the source code either by extracting the normal source distribution or checking out suitable tag directly from the version control. After that you just need to run:

    python setup.py bdist_wininst

For more information see https://docs.python.org/2.7/distutils/builtdist.html#creating-windows-installers.
