### ISSUE TITLE
I need to connect to the DB2 database

### ISSUE THREAD

**Issue by bhajojo** [robotframework/robotframework#2221]
I need to connect to the DB2 databse, I tried to use the Keyword "Connect To Database" but not sure what should be the value in dbapimodulename 

I am having Python 2.7.8 and working on 64 bit machine , I am not able to install the Pydb2 for this python version and the machine configuration 

Please suggest me any way by which the db2 database can be connected by robot scripts

**Comment by pekkaklarck** [comment]
This tracker is for bug reports and enhancements related to Robot Framework itself. This issue is a question about using Database Library and thus invalid. Questions are best asked on robotframework-users mailing list and other similar forums.
