### ISSUE TITLE
Update installation instructions

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#2222]
RF 3.0 contains some changes to installation that need to be documented in the installation instructions. These new docs cannot be fully finalized until the final release, though. This issue tracks such changes so that we don't forget about them:

- [x] Python 3 support (#1506). 
- [x] New generic `robot` and `rebot` start-up scripts (#2216)
- [x] `python -m robot` (#2223)
- [x] No more binary Windows installers (#2218)

**Comment by pekkaklarck** [comment]
It's not really about documentation, but we should also remove all artifacts related to generating Windows installers. We could do it right away, but there's always a risk that we need to revert the decision and create them anyway. Probably we should wait at least until RF 3.0 alpha 1 when the plan to not generate Windows installers is made more public.

Assuming we actually can stop generating Windows installers, the artifacts to remove include at least these:
- `robot.bmp`
- `robot_postinstall.py`
- Code related to `robot_postinstall.py` in `setup.py`.
- `wininst` task in `tasks.py`

**Comment by jussimalinen** [comment]
added missing mention of `python -m robot` in 959169aada0a2f4e6382e9a8f0d1ecdd9aa53859

**Comment by pekkaklarck** [comment]
Unfortunately I was already working with larger changes to INSTALL.rst when @jussimalinen committed his enhancements. Merging the changes to docs wasn't easy so b9842cf reverts all Jussi's changes. Review for my changes, with those reverted changes in mind, still needed.

**Comment by jussimalinen** [comment]
The new `INSTALL.rst` is much better than the slighly updated version I did. I updated a few links, but now it looks good!

**Comment by pekkaklarck** [comment]
Cool, I guess this issue can be considered done. RF 3.0 will be released tomorrow.
