### ISSUE TITLE
Support executing tests with `python -m robot`

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#2223]
We already support `python -m robot.run` (where instead of `python` you can have any other interpreter like `jython` or `ipy`) and it would be easy to add support also for `python -m robot`. Because `robot` is a package, the latter won't be compatible with Python 2.6 but that's not a big issue.

The main reason to add this is to make it a bit easier to execute tests with different installed interpreters regardless what start-up script is created and which start-up script is first in `PATH`. For example, on Windows you could use the [py launcher](https://docs.python.org/3/using/windows.html#launcher) like `py -2 -m robot` or `py -3 -m robot` to use Python 2 or Python 3, respectively.

**Comment by pekkaklarck** [comment]
This ought to be done otherwise than updating installation instructions that is tracked by #2222. Could you @jussimalinen do a review?

**Comment by jussimalinen** [comment]
Awesor!

**Comment by blueenergy** [comment]
Can we run test case with python -m pdb -m robot.run ... So we could enable pdb functionality with pybot easily?

**Comment by pekkaklarck** [comment]
I don't know. Is that generally supported by pdb? If yes, it ought to work.

**Comment by pekkaklarck** [comment]
The added `__main__.py` file also made it possible to run tests like `python path/to/robot/` in addition to `python path/to/robot/run.py`.
