### ISSUE TITLE
How to get variable file from commandline argument

### ISSUE THREAD

**Issue by luisxiaomai** [robotframework/robotframework#2228]
Hi,

I use command line to run test suite like "pybot --variablefile:path/xxx/xx.yaml  c:\robot\tests.txt ".
I want to get variablefile path (path/xxx/xx.yaml) from command line in test case, it's dynamic.
Can you help me on this?  

Thanks.
Luis

**Comment by pekkaklarck** [comment]
You can parse `sys.argv`. Please send questions to robotframework-users or other forums in the future.

**Comment by luisxiaomai** [comment]
Sorry for the wrong input place.
