### ISSUE TITLE
Robot scripts can't open IE11 browser (worked ok with IE8)

### ISSUE THREAD

**Issue by Gracie101** [robotframework/robotframework#2232]
Any thoughts? 

Error:
WebDriverException: Message: Unexpected error launching Internet Explorer. Protected Mode settings are not the same for all zones. Enable Protected Mode must be set to the same value (enabled or disabled) for all zones.

**Comment by HelioGuilherme66** [comment]
Just do what the error message says!
Protected Mode settings are not the same for all zones. Enable Protected
Mode must be set to the same value (enabled or disabled) for all zones.

This is a long time known feature of IEDriverServer.exe, and documented at
https://code.google.com/p/selenium/wiki/InternetExplorerDriver

**Comment by pekkaklarck** [comment]
This is not a bug report or enhancement request about Robot Framework itself.
