### ISSUE TITLE
Importing test library 'SSHLibrary' failed: ImportError: No module named 'SSHLibrary'

### ISSUE THREAD

**Issue by hubiao007** [robotframework/robotframework#2233]
I got this message when I run pybot with my test. Is SSHLibrary not yet supported in 3.0a1?

**Comment by jussimalinen** [comment]
Some more context would be good to have here. What Python version are you using? Do you have SSHLibary installed? Did the same tests work on earlier Robot Framework version on the same Python installation?

**Comment by hubiao007** [comment]
Hi Jussimalinen

In my workable context, with the same test case I am running Robotframework 2.9.2 with python 2.7. 

Then, I update to RBF 3.0a1 via command "pip3 install robotframework==3.0a1". With "pybot --version", it shows "Robot Framework 3.0a1 (Python 3.4.3 on linux)".

**Comment by hubiao007** [comment]
About SSHLibrary: I am trying to install it also for python3 with cmd "sudo pip3 install robotframework-sshlibrary". It reports the following error
===========================
Downloading/unpacking robotframework-sshlibrary
  Downloading robotframework-sshlibrary-2.1.2.tar.gz (93kB): 93kB downloaded
  Running setup.py (path:/tmp/pip_build_root/robotframework-sshlibrary/setup.py) egg_info for package robotframework-sshlibrary
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/robotframework-sshlibrary/setup.py", line 22, in <module>
        execfile(join(CURDIR, 'src', 'SSHLibrary', 'version.py'))
    NameError: name 'execfile' is not defined
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/robotframework-sshlibrary/setup.py", line 22, in <module>

    execfile(join(CURDIR, 'src', 'SSHLibrary', 'version.py'))

NameError: name 'execfile' is not defined

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/robotframework-sshlibrary
Storing debug log for failure in /home/local/GENEXISLOCAL/hyang/.pip/pip.log
==========

**Comment by pekkaklarck** [comment]
SSHLibrary doesn't yet support Python 3. Hopefully it will soon. An issue should be submitted to its tracker about that if there isn't one already.

Do you have problems using SSHLibrary with RF 3.0a1 on Python 2?

**Comment by hubiao007** [comment]
Hi Pekkaklarck

Thank you for your answer

In the context of RF3.0a1 and Python2, it has no problem with SSHLibrary.

**Comment by pekkaklarck** [comment]
OK. Then the issue is just that SSHLibrary doesn't yet support Python 3. There is a plan to add the support in the somewhat near future, though. You can submit an issue about Python 3 support to SSHLibrary tracker if there isn't one yet.

**Comment by bbpatel2001** [comment]
Today i installed Python3 , robotframework-selenium2library (3.0.0)
robotframework-seleniumlibrary (3.0.1) and trying to install ssh library. Getting error 

pip3 install robotframework-sshlibrary

Collecting robotframework-sshlibrary
  Using cached robotframework-sshlibrary-2.1.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\...user\AppData\Local\Temp\pip-build-rh99uou7\robotframewo
rk-sshlibrary\setup.py", line 22, in <module>
        execfile(join(CURDIR, 'src', 'SSHLibrary', 'version.py'))
    NameError: name 'execfile' is not defined

SHLibrary doesn't yet support Python 3????

**Comment by bkhouri** [comment]
@bbpatel2001  see @pekkaklarck's comment [here](https://github.com/robotframework/robotframework/issues/2233#issuecomment-159380991)

**Comment by bbpatel2001** [comment]
@bkhouri , thanks for update. I thought comment was in 2015 so might fixed today 👍

**Comment by bbpatel2001** [comment]
@bkhouri can you please review Python3 support #205. Now I can install SSHLibrary on python3.

**Comment by bkhouri** [comment]
@bbpatel2001 , it fails for me

```
$ which python
/Users/bassam.khouri/venv3/bin/python

$ which pip
/Users/bassam.khouri/venv3/bin/pip

$ python --version
Python 3.6.2

$ pip install robotframework-SSHLibrary
Collecting robotframework-SSHLibrary
  Using cached robotframework-sshlibrary-2.1.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/7_/sxs00wq119q_lb3z1n8wxkl8xb7q40/T/pip-build-vv2cn1do/robotframework-SSHLibrary/setup.py", line 22, in <module>
        execfile(join(CURDIR, 'src', 'SSHLibrary', 'version.py'))
    NameError: name 'execfile' is not defined
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/7_/sxs00wq119q_lb3z1n8wxkl8xb7q40/T/pip-build-vv2cn1do/robotframework-SSHLibrary/

```

**Comment by trogdor259** [comment]
I commented on the PR with a fix for that error @bbpatel2001 @bkhouri 
It seems like there is still a few things that need fixing before it is ready for merge

**Comment by Kvj92** [comment]
is this issue yet to be resolved because [ ERROR ] Error in file '/Users/bkr/Desktop/test/server.robot' on line 3: Importing library 'SSHLibrary' failed: ModuleNotFoundError: No module named 'SSHLibrary'
Traceback (most recent call last):
