### ISSUE TITLE
Sort feature at testcase level

### ISSUE THREAD

**Issue by vkosuri** [robotframework/robotframework#2240]
Feature Request

We have many keywords at testcase level, few them are consuming more time, if a sort methods like available for test suit level we can quickly identify time consumed keywords.

Many keywords snap shot

![manykeywords](https://cloud.githubusercontent.com/assets/13664257/11450557/4145eb78-95ca-11e5-9e93-203ded9c14a2.png)

Thanks
Malli

**Comment by pekkaklarck** [comment]
It's typically easier to get this data programmatically from the ouput.xml file. If you have ideas how the UI should look in the log fila and are interested to implememt this, I would be happy to review a pull request.

**Comment by vkosuri** [comment]
@pekkaklarck I am interested do this, could please guide me where exact the html log flow is going to achieve this task

**Comment by pekkaklarck** [comment]
I don't have exact idea how this could be implemented in the log file. Keywords aren't in a single table that could be sorted with the tablesorter plugin we have used in other places. You probably needed to modify the original model and re-render templates afterwards.

Personally I don't consider this worth the effort for various reasons:
- You only would be able to see what keyword inside a single test/keyword takes time.
- A test or keyword shouldn't have that many keywords directly inside it (I consider 10 to be too much already). With such small number of keywords you can easily see if some of them is taking lot of time also without sorting.
- The UI shouldn't add any extra clutter.
- This is likely to be hard to implement in general.
- All information about keyword execution times is much more easily available programmatically using the result model.

If you still think this is a good idea, we can keep the issue open for some time and see what you can get done.

**Comment by vkosuri** [comment]
Thanks @pekkaklarck i totally agree with you
