### ISSUE TITLE
BuiltIn: Support also timeout with `Repeat Keyword`

### ISSUE THREAD

**Issue by joongh** [robotframework/robotframework#2245]
Sometimes I need repeat keyword for specified seconds regardless of how many times it repeats.
I think that the first argument of 'Repeat Keyword', "times", can be extended accepting how many times or how long time. Also it need to add the argument "retry_interval".

Handling arguments can be exactly same as the way in the keyword "Wait Until Keyword Succeeds".
If it sounds good and you give me an exact guidelines, I would gladly help coding and testing.

Best regards,
Thank you.

**Comment by HelioGuilherme66** [comment]
If I am correct, you want to Repeat Keyword unconditionally. You just want to repeat, without caring if it succeeds or fails. If that is the case, then this keyword cannot be extended (and "retry_interval" should be renamed "repeat_delay").
If you really want to repeat keeping the existing behavior, I don't see the difference to "Wait Until Keyword Succeeds".

**Comment by joongh** [comment]
@HelioGuilherme66  Thanks for your opinion.
It's not without caring if it succeeds or fails. During the repetition, if the keyword repeating fails once, it fails. The difference between "Wait Until Keyword Succeeds" and extended "Repeat Keyword" is that the every execution of the keyword should success to pass the whole repetition, while "Wait Until Keyword Succeeds" would pass with only one succeeds before the timeout.

I agree with that "retry_interval" should be renamed "repeat_delay".

**Comment by pekkaklarck** [comment]
I can see supporting max time in addition of retry count could be useful. We cannot add additional `retry_interval` parameter, though, because it would cause backwards compatibility issues. A workaround would be adding additinal sleep to the end of the executed kw. Would you be fine with that?

**Comment by joongh** [comment]
@pekkaklarck Thanks for your reply.
Does "Supporting max time" mean that the first argument "times" would be treated same as the first argument of  "Wait Until Keyword Succeeds" which is "retry"?
If I'm right, I would be very satisfied with that.

Thank you.

**Comment by pekkaklarck** [comment]
Yes. Due to backwards compatibility constraints just using a number like `42` should be interpreted as a count, not as a max time, though. For example `42s` and `00:00:42` should be interpreted as a time.

Are you interested to implement this? It shouldn't be too hard. Need to be ready by the end of next week to make sure it gets to RF 3.0.

**Comment by joongh** [comment]
@pekkaklarck OK, I'll do implement this during the next week.

**Comment by pekkaklarck** [comment]
PR #2262 looks promising enough that I add this into RF 3.0 scope.

**Comment by pekkaklarck** [comment]
Thanks for PR #2262 @joongh!
