### ISSUE TITLE
Cannot connect to a remote server via XML-RPC

### ISSUE THREAD

**Issue by michel117** [robotframework/robotframework#2246]
I have the  problem, that when I try to connect to a XML-RPC Server, that get an error stating that TimeoutTransport has no __init__, which is only true, if python 2.6 would be used (according to Remote.py).

Actually it was working all the time and I am not sure what I changed to have these errors now (Python Interpreter version?)

My versions:
Python 2.7.10
RobotFramework 2.8.7

    In [8]: client = Remote.XmlRpcRemoteClient(uri="http://127.0.0.1:8080", timeout=1 )
    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    <ipython-input-8-59bde62e0a93> in <module>()
    ----> 1 client = Remote.XmlRpcRemoteClient(uri="http://127.0.0.1:8080", timeout=1 )

    /Library/Python/2.7/site-packages/robot/libraries/Remote.pyc in __init__(self, uri, timeout)
        184 
        185     def __init__(self, uri, timeout=None):
    --> 186         transport = TimeoutTransport(timeout=timeout)
        187         self._server = xmlrpclib.ServerProxy(uri, encoding='UTF-8',
        188                                              transport=transport)

    /Library/Python/2.7/site-packages/robot/libraries/Remote.pyc in __init__(self, use_datetime, timeout)
        229 
        230     def __init__(self, use_datetime=0, timeout=None):
    --> 231         xmlrpclib.Transport.__init__(self, use_datetime)
        232         if not timeout:
        233             timeout = socket._GLOBAL_DEFAULT_TIMEOUT

    AttributeError: class Transport has no attribute '__init__'

**Comment by michel117** [comment]
I'm pretty desperate now. Tried various RF versions. And found that when I connect to my server directly by using the python standard library xmlrpclib, I can actually connect to this xml-rpc server (get_keyword_names delievers a list of keywords).

Only when I try to include the "Remote" library in my robot test, I get the errors in my first post: 
AttributeError: class Transport has no attribute '__init__'

That was my tryout code with pure python:

```
import xmlrpclib

server = xmlrpclib.ServerProxy('http://127.0.0.1:8080', verbose=True)
print 'Ping:', server.get_keyword_names()
```

**Comment by pekkaklarck** [comment]
Works for me:

```python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from robot.libraries.Remote import XmlRpcRemoteClient
>>> client = XmlRpcRemoteClient('http://127.0.0.1:8270', timeout=1)
>>> client.get_keyword_names()
['Passing', 'Failing', 'Traceback', 'Returning', 'Logging', 'Extra stuff in result dictionary', 'Conflict', 'Should Be True']
```

Are you absolutely certain you are using Python 2.7? I see there is `Python/2.7` in the traceback, but that could be result of adding that to `PYTHONPATH` separately. What do you get if you run `import sys; print sys.version`?

**Comment by michel117** [comment]
I am certain, but it is the apple python it seems, sys.version leads to this:
        2.7.10 (v2.7.10:15c95b7d81dc, May 23 2015, 09:33:12) 
        [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

Should I switch to 2.7.6 and another python (Python.org) ?

**Comment by pekkaklarck** [comment]
It would be strange if different Python 2.7 variants would behave differently, but then again this whole issue seems pretty strange.

Do you need to actually use timeouts?  Also, why isn't using `xmlrpclib` enough for your needs?

**Comment by michel117** [comment]
Hi Pekka,
thanks. I want to use remote library from robotframework to connect directly to the XML-PRC Server. I don't want to create a layer between the test cases and the SUT.
I don't need timeouts and I am not using them. And this behaves really strange, as Remote.py actually uses the same xmlrpclib.py I am using for my small tests.
For now, I will setup a completely fresh MacOSX VM and try it out with that.

**Comment by pekkaklarck** [comment]
Any new info about this issue? Also, if you don't need timeouts, why are you using them?

**Comment by michel117** [comment]
Hi Pekka,
I tried what I wrote before and setup a fresh VM, and then it worked! It seems there was a problem with the systems python and not the library.
Sorry to write here and bother you guys.

**Comment by madhurabhogate** [comment]
@pekkaklarck : Hi I am using robot.libraries.Remote module and after the remote connection is done - 
 >> obj.stclib.get_keyword_names()
['apply', 'base_dir', 'config', 'connect', 'create', 'delete', 'disconnect', 'get', 'help', 'log', 'perform', 'push_file_to_artifactory', 'push_to_artifactory', 'release', 'reserve', 'sleep', 'subscribe', 'unsubscribe', 'waitUntilComplete', 'stop_remote_server']

How do we call the above exposed functions ?
