### ISSUE TITLE
Robot should (optionally) support flushing output.xml as a whole rather than writing it incrementally

### ISSUE THREAD

**Issue by emp302** [robotframework/robotframework#2247]
Using Robot in conjunction with a monitoring solution, the monitoring daemon acts on inode events.
As Robot writes the output.xml file incrementally, it is not recognized as a single file but collected in pieces when the same have been written. As it is possible to create the DOM in memory and flush it at the end, this would enable the monitoring daemon to correctly recognize the file being written. In addition, it would avoid corrupt (thus only partially written) output.xml files in case a basic issue happens (e.g. testing machine dies) while tests are running.

Is there already a way to configure this behavior?

**Comment by pekkaklarck** [comment]
Could you clarify what you mean with "flushing as a whole"?

**Comment by pekkaklarck** [comment]
Do you possibly mean that Robot should keep all the information in the memory and only write output.xml after execution is done? That would be a very big change internally and would likely to cause memory problems.

Perhaps something like this in a script that starts test execution would work instead:

```
    pybot --output output-in-progress.xml tests.robot
    mv output-in-progress.xml output.xml
```

**Comment by emp302** [comment]
Confirmed. This is the "DOM" method of creating XML files. You create and edit the tree in memory until it is completely defined and then flush (dump) it to disk.

Thanks a lot for your work-around. We´ll try.

**Comment by emp302** [comment]
Workaround successfully tested. Issue may be closed.
