### ISSUE TITLE
Rebot: Directory name is added multiple time in Title and Reports

### ISSUE THREAD

**Issue by vinaybond** [robotframework/robotframework#2251]
I has 20 suites, when i merge them using rebot, I saw directory name (in which output.xml is stored) is repeated N number of time (N=Number of suites). It is repeated in Report Title and Test Suite in Result table. 
Here are the attachment.

![testreport1](https://cloud.githubusercontent.com/assets/7723948/11650533/e37badb4-9daf-11e5-858c-a757c66f4f4c.png)
![testreport2](https://cloud.githubusercontent.com/assets/7723948/11650532/e3787dce-9daf-11e5-8229-b2095cb02b0c.png)

**Comment by vinaybond** [comment]
To Add, I am merging files by putting full path of output.xml into a file. 
i.e. rebot -A file.txt

**Comment by pekkaklarck** [comment]
Use `--name` option to give a custom name to the top level test suite.

**Comment by vinaybond** [comment]
Thank you very much. It solved the problem.
