### ISSUE TITLE
Rebot: Screenshot are not visible in merged result file

### ISSUE THREAD

**Issue by vinaybond** [robotframework/robotframework#2252]
After I merge my results using rebot, I don't see screenshot captured as the file is not moved to new directory. I am merging files by putting full path of output.xml into a file.

**Comment by pekkaklarck** [comment]
I don't think it is feasible for Rebot to try checking are there external files referenced in the output.xml and move them to new location if there are. You can try implementing such functionality, though, and provide a pull request if it works well. A simpler solution is just moving/copying files separately.

**Comment by vinaybond** [comment]
Moving images seems a good option. But problem is, screenshot name are same in all directories (i.e. selenium-screenshot-1.png), so file will be overwritten. I'll see if it they can be renamed and reference is renamed in output.xml files.

**Comment by pekkaklarck** [comment]
I was only thinking that it would be hard to scan every message for a possible reference for an external file, but you are right that duplicates cause another big problem. I honestly don't think that is worth the effort. Moving files wouldn't always be desirable either, so this would need to be configurable.

**Comment by pekkaklarck** [comment]
Any new info about this?

**Comment by vinaybond** [comment]
Not yet. I have reported a bug in selenium community today to provide unique screenshot name.

**Comment by pekkaklarck** [comment]
- No new info in 2.5 months. 
- I don't think this is feasible in general.
-> Closing.
