### ISSUE TITLE
Do we have assertion status some thing like test.status

### ISSUE THREAD

**Issue by vkosuri** [robotframework/robotframework#2253]
Hi,

Is there any option to get assertion(should_xx_xx) Keywords status using SuiteVisitor or some other class?

I am getting test.status using SuiteVisitor.

``` Python
class FailInfo(SuiteVisitor):

    def __init__(self, max_seconds):
        pass

    def end_test(self, test):
        if test.status == 'PASS':
            # test.status = 'FAIL'
            failed.log("Failed")
```

Thanks
Malli

**Comment by pekkaklarck** [comment]
There are also kw related methods in the visitor API that you can implement. Notice that questions belong to robotframework-users or other such forumns. This tracker is for bug reports and concrete enhancement requests.

**Comment by vkosuri** [comment]
Thanks @pekkaklarck
