### ISSUE TITLE
Unable To See Testcase Logs When Using Skip Execution Function.

### ISSUE THREAD

**Issue by jbkrishna** [robotframework/robotframework#2254]
The skip functionality is not working fine.  If we execute 2 testcases and skip 1st testcase then the logs for 2nd testcase is not getting displayed in html file.  Please advise ASAP on same.

Execute a script as given below and check log.html,   you can also see the issue
*** Settings ***
Documentation
...    Objective:  Test Skipped Testcase Reporting
...

Library          BuiltIn
#Default Tags     smoke_test

*** Keywords ***
Skip Test
    Set Test Variable    ${release}      R1
    Run Keyword If      '${release}' == 'R1'
    ...    Pass Execution   Skipping Testcase (it is not relevant to this image)

*** Test Cases ***
Test_Skip
    # Check if Testcase is Relevant (should be skipped)
    # -------------------------------------------------
    Skip Test

    Log  ===========> *** RUNNING TEST_SKIP *** <===========

Test_DSkip
    # Check if Testcase is Relevant (should be skipped)
    # -------------------------------------------------
    #Skip Test

    Log  ===========> *** RUNNING TEST_DSKIP *** <===========

**Comment by pekkaklarck** [comment]
I'm sorry but I didn't understand the description at all. What skip functionality are you talking about? Notice also that your example doesn't render too clearly. Please see the instructions how to use Markdown in the description and in comments on GitHub for more details about the formatting.

**Comment by jbkrishna** [comment]
Issue is we are unable to see testcase logs with log.html file.  It is due to using skip execution keyword.  

Please check the issue numbers 2087 and 2179. We pulled the code given by doug in below link and used it for testing skip functionality.  Utilize that code and test our script, open the log.html and you can understand the issue.

https://github.com/Doug8080/robotframework/commit/c31b6568c857d69b07569f2ea711790c1a6801c4#diff-7a343809e0eb58e506df7d941e80cb26R2202

**Comment by pekkaklarck** [comment]
I see. Issues related to proposed pull requests or other such changes don't belong to this issue tracker.

On this particular case the problem is that implementing skip functionality correctly and so that it works well with other functionality is a really big task. My paying clients haven't needed it badly enough and I'm not planning to implement it on my own time. If you need it, you can either look at implementing it yourself or pay me or someone else to do it.
