### ISSUE TITLE
Process library issue while running a java process.

### ISSUE THREAD

**Issue by JoeBmc** [robotframework/robotframework#2255]
*** Settings ***
Library           Process

*** Test Cases ***
TestCase001
        Start Process    java  -jar  target/customjar.jar  cwd=/etc/myplugins/    alias=First    stdout=stdout.txt
        ${result} =    Wait For Process    timeout=00:00:02
        Terminate All Processes
        Should Not Contain    ${result.stdout}    FAIL

The error that  I get while running the command: pybot robotfile.robot
Plugin-Test
==============================================================================
TestCase001                                                           | FAIL |
Resolving variable '${result.stdout}' failed: AttributeError: 'NoneType' object has no attribute 'stdout'
------------------------------------------------------------------------------
Inside the jar file, I am starting a thread which runs as an infinite loop and writes to stdout.
Hence terminating the process after 2 seconds.

Question1: Why the result object is none.

regards,
Jose

**Comment by pekkaklarck** [comment]
This ought to be explained in the library docs. Could you check them and comment here if they are not adequate?

**Comment by JoeBmc** [comment]
Thanks for your reply.
I do not see anything mentioned in the doc for threads in Process library. It is mentioned that the result object will be returned for Wait for Process & Terminate process call. But, I don't see that happening.
I am referring to the documentation - http://robotframework.org/robotframework/latest/libraries/Process.html#Terminate%20All%20Processes

**Comment by pekkaklarck** [comment]
The result object is returned by `Wait For Process`:
http://robotframework.org/robotframework/latest/libraries/Process.html#Wait%20For%20Process

**Comment by JoeBmc** [comment]
Once I added the property 'on_timeout=terminate' for the Wait For Process keyword, It worked fine.

Thanks for your help.
