### ISSUE TITLE
Disallow dot char in keyword & testcase as dot is special character for lib prefix

### ISSUE THREAD

**Issue by KrzysztofJozefowicz** [robotframework/robotframework#2258]
Currently dot ( . ) character can be used in keywords and testcases (eg.  check memmorydump.log ) but also as library prefix: SSHLibrary.Get File .

This border case complicates internal recognition what we are dealing with - either library/resource prefix or keyword name with dot and creates exceptions hard to maintain.
example of exception:
res1:
Keywords
test.test
test2

main_test:
res1.test.test => fail
test.test => ok
test2 => ok
res1.test2 => ok

dot should be handled as special char ONLY to indicate that leftside is lib/resource and right side is keyword, dot should be disallowed to be used in keywords.
It will remove unnecessary branches in code (Robot & RED) :)

**Comment by pekkaklarck** [comment]
It's true that using a dot as a separator between library/resource name and keyword name as well as allowing both library/resource names and keyword names to contain dots is somewhat confusing and also complicated to implement correctly. It is, however, absolutely impossible for us to change this at least do that a dot couldn't be used in a keyword or library names. Most important reasons are listened below:

- The change would be massively backwards incompatible. Such a huge breakage could be considered only if benefits would be even more huge and there would be a better way to accomplish the same thing. In this case I don't thing benefits would that big and, as the items below explain, there are valid reasons to have dots in names.
- Many libraries, especially ones implemented in Java, naturally have a dot in the name (e.g. `com.exampe.Library`).
- Longer keyword names can naturally use a dot as a sentence separator (e.g. `Do something. Then do something else.`) and a dot could also be used for other purposes (e.g. `Row should end with '...'`.)

I hope the above makes it clear why not allowing dot in names is not possible. I have sometimes been thinking that we should have chosen to use something else as a separator between a library/resource and a keyword, though. We could, for example, use something like `Library :: Keyword` or `Library -> Keyword`. Although I consider changing the separator more doable than disallowing dots in names, I doubt that it would actually be worth the effort:

- It would be a huge task.
- It would require a long deprecation period. During that we needed to support both the old and the new syntax.
- Regardless what separator we use, there could be valid usages for it in keyword names.

Another reason I'm not particularly interested in changing this behavior is that it is already implemented in Robot, it works fine, and it isn't in the end that complicated. You can see the code related to iterating over all possible `(library/resource, keyword)` combinations in here:
https://github.com/robotframework/robotframework/blob/master/src/robot/running/namespace.py#L369

The above said, I totally understand if implementing this in RED or other tools doesn't sound meaningful or is just too complicated. Personally I'm fine with tools having limits for how Robot can be used with them, though, so you can just decide not to implement this if you don't consider it important. You could, for example, always consider the first dot a separator and ignore others. If users aren't fine with that, they'll submit a bug report or an enhancement request, and you can decide then do you want to fix it or perhaps implement something even more important.
