### ISSUE TITLE
csv log support for debugger logs

### ISSUE THREAD

**Issue by vkosuri** [robotframework/robotframework#2261]
Hi

We are generating a massive debug log file around 10 MB, and it is very difficulty to find information in debug file, If we would have a csv file format then we could easily identify exact failures using different excel filters

``` Shell
pybot --help
 -b --debugfile file      Debug file written during execution. Not created
                          unless this option is specified.
```

I tried to export .log file into excel, I used delimited option each row with '-' ,

``` Log
==============================================================================
20151202 20:31:07.160 - INFO - + START SUITE: Generated [ ]
==============================================================================
20151202 20:31:07.405 - INFO - +- START SUITE: Generated.test test generated 1 [ ]
==============================================================================
20151202 20:31:07.405 - INFO - +-- START SETUP: Login [ ${USERNAME} | ${PASSWORD} | ${BASE_URL} | ${ALIAS} ]
20151202 20:31:07.406 - INFO - +--- START KW: BuiltIn.Create List [ ${USERNAME} | ${PASSWORD} ]
20151202 20:31:07.407 - INFO - ${auth} = [u'ADMIN', u'PASSWORD']
20151202 20:31:07.407 - INFO - +--- END KW: BuiltIn.Create List (1)
20151202 20:31:07.407 - INFO - +--- START KW: RequestsLibrary.Create Session [ ${ALIAS} | ${BASE_URL} | auth=${auth} ]
20151202 20:31:07.408 - INFO - Creating Session using : alias=3CRMT1JQU9, url=http://10.11.18.11/, headers={}, cookies=None, auth=<requests.auth.HTTPBasicAuth object at 0x37B7B4F0>, timeout=None, proxies=None, verify=False
20151202 20:31:07.408 - DEBUG - Creating session: 3CRMT1JQU9
20151202 20:31:07.408 - DEBUG - Argument types are:
<type 'bool'>
20151202 20:31:07.408 - INFO - +--- END KW: RequestsLibrary.Create Session (1)
20151202 20:31:07.409 - INFO - +-- END SETUP: Login (4)
------------------------------------------------------------------------------
```
It doesn't reflected as expected due to may *-*.

Thanks
Malli

**Comment by pekkaklarck** [comment]
Debug files weren't designed to be easy to open into a spreadsheet program. Their main purpose is following test execution while tests are running by using something like `tail -f debug.log`. I'm not against making them delimited so that opening to a spreadsheet program would work, though, as long as the original use case isn't affected. Are you willing to do that yourself?

**Comment by vkosuri** [comment]
I agreed totally with you, My intention was the debug.log file make useful after execution also, If we made it as an CSV file. By adding a csv file is worthwhile i'll try to explain indetail how it was, how the csv file will be look like
