### ISSUE TITLE
`Convert To Number` ignores precision if it is `${0}`

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#2268]
`BuiltIn.Convert To Number` accepts optional precision. The precision is ignored if it is number `0`. Luckily string `'0'` is handled correctly, and normal data passed to keywords is passed as strings, so this isn't too severe. 

``` robotframework
*** Test Cases ***
This works
    ${num} =    Convert To Number    3.14    precision=0
    Should Be Equal    ${num}    ${3} 
This fails
    ${num} =    Convert To Number    3.14    precision=${0}
    Should Be Equal    ${num}    ${3}
```

**Comment by kvenmoodys** [comment]
I have seen convert to number  0.90  precision  2  does not give 0.90 instead gives 0.9
