### ISSUE TITLE
[Question] Tear Down won't cause test case to fail

### ISSUE THREAD

**Issue by rarelam** [robotframework/robotframework#2274]
Hi, I would like to ask, do it possible to ignore tear down failure? currently if tear down fail and it will mark my test as fail. I would like to have run some steps on tear down stage, but it wouldn't affect the test status no matter the tear down is pass or fail.

I have tried quick google and robot framework doc. But I didn't get something from it. So sorry for asking a lazy question here.

**Comment by jussimalinen** [comment]
This has also been discussed before in issue tracker. For example #2135. Although that is about suite teardowns, the same logic applies to all teardowns. Questions in general should be asked in the users group.
