### ISSUE TITLE
Remove support for Python 2.6 and 3.3

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#2276]
It's time to drop Python 2.6 support in Robot Framework 3.1.

The main motivation:
- Python 2.6 hasn't been officially supported, even with security updates, since [October 2013](https://www.python.org/download/releases/2.6.9/).
- Supporting Python 2.6 requires some time. That time is better spent fixing bugs and developing new features.
- We get to use set literals, dict comprehensions, and other such syntax and modules not supported by Python 2.6.
- All test libraries and other code running on Python 2.6 ought to run unchanged on Python 2.7. Upgrading is thus only matter of upgrading the underlying Python version. If that is impossible, it is unlikely these users can upgrade to newer RF releases either.
- Users of older RedHat based Linux distributions that only contain Python 2.6 by default can easily install Python 2.7 from the official [Software Collections repository](https://www.softwarecollections.org/en/scls/rhscl/python27/).

For some more reasoning see http://www.snarky.ca/stop-using-python-2-6. Notice that we do not plan to drop Python 2.7 support in the foreseeable future.

**Comment by pekkaklarck** [comment]
Should we also drop official support from Python 3.3 at the same time? It [reached EOL at 2017-09-29](
https://www.python.org/downloads/release/python-337/). I doubt this would make any difference in code, but having one less Python versions to test against would be nice. Are there Linux distributions in wide use that have Python 3.3 by default and where installing newer version is inconvenient?

**Comment by HelioGuilherme66** [comment]
I agree that support for Python 3.3 should be dropped. I think that Python 3.4 came really fast to correct problems on 3.3. Don't know of any Linux distributions with Python 3.3.

**Comment by hugovk** [comment]
I agree to drop support for Python 3.3.

None of the currently-supported enterprise Linux distros ship 3.3:
![image](https://user-images.githubusercontent.com/1324225/31711628-73d761f0-b401-11e7-86c0-fa0c5442d098.png)
https://en.wikipedia.org/wiki/CPython#Enterprise_Linux

By the way, here's pip installs for robotframework from PyPI for the last month:
```
$ pypinfo --percent --pip robotframework pyversion
python_version percent download_count
-------------- ------- --------------
2.7              90.1%         74,397
3.6               5.1%          4,181
3.5               2.3%          1,879
3.4               1.5%          1,225
2.6               0.7%            538
3.3               0.3%            236
None              0.1%             57
3.7               0.0%             21
3.2               0.0%              1
```

**Comment by pekkaklarck** [comment]
Thanks for the info @hugovk. It really seems like dropping Python 3.3 support wouldn't be a problem. As I already commented, I don't think it would have any effect on code, at least as long as we need to support Python 2.7. I guess we can decide this based on how easy it is to test against Python 3.3 on CI.

**Comment by aaltat** [comment]
I am also happy to drop Python 3.3 support and support 3.4+.

**Comment by pekkaklarck** [comment]
I think we can keep Python 3.3 support as long as it requires no extra code and it can be easily tested. When we eventually can drop Python 2 support, I hope we can make Python 3.6 the minimum to be able to use features like f-strings and order preserving dicts.

**Comment by pekkaklarck** [comment]
After thinking this a bit more, I've decided to drop Python 3.3 support in RF 3.1. The main reasons are:

- It has reached end-of-life and is not supported anymore.
- It has so few users that we cannot justify any extra work related to it.
- We are going to setup new CI infrastructure to Robot. Adding jobs for Python 3.3 on Linux and Windows is extra work.

At least in the beginning it's unlikely that there are any code changes that actually prevent using Python 3.3. It is, however, not supported and we will do no testing with it.

**Comment by hugovk** [comment]
Should https://github.com/robotframework/robotframework/pull/2689 be merged to remove a load of now redundant 2.6 code?

**Comment by pekkaklarck** [comment]
Damn, I had forgotten about #2689 and did lot of the same changes in b060ba1. Do you @hugovk have time and interest to look did I miss something important and possibly create a new PR?

**Comment by pekkaklarck** [comment]
@hugovk The updated PR #2689 is great. I found two smallish problems with it, though. Do you have time to look at them or should I just fix them myself before or after merging the PR?
