### ISSUE TITLE
Enhance public API documentation related to parts exposed to model modifiers and listeners

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#2279]
Robot Framework's programmatic API is documented at http://robot-framework.readthedocs.org. The documentation is not that comprehensive and could be enhanced in many ways. This issue covers enhancing the parts that are exposed to pre-run and pre-Rebot modifiers (added in RF 2.9, #1976) and listener v3 (added in RF 3.0, #1208). In practice this issue covers enhancing documentation of running and result model objects and the visitor interface.

**Comment by pekkaklarck** [comment]
Tasks related to this issue:

- [ ] Review and enhance visitor documentation. On a quick look it seems to be in pretty good shape already.
- [ ] Add links to related execution and result objects into User Guide's pre-run and pre-Rebot modifier sections.
- [ ] Make sure all methods and attributes of running objects are documented. This includes also classes used by these objects.
- [ ] Same as the above but with result objects.

**Comment by pekkaklarck** [comment]
See #2275 for another issue making API docs better.

**Comment by pekkaklarck** [comment]
Enhanced API docs are now ready for review. You can see the commits containing changes above and http://robot-framework.readthedocs.org/en/master/ contains the latest generated version. Direct links to the most important docs related to the listener v3 and model modifiers are these:

- Execution related model objects: http://robot-framework.readthedocs.org/en/master/autodoc/robot.running.html#module-robot.running.model
- Result related model objects: http://robot-framework.readthedocs.org/en/master/autodoc/robot.result.html#module-robot.result.model
- Visitor interface: http://robot-framework.readthedocs.org/en/master/autodoc/robot.model.html#module-robot.model.visitor

Comments, enhancement ideas, fixes, etc. related the docs are highly appreciated!

**Comment by aaltat** [comment]
I did read the doc and couldn't think anything to improve. Mainly because I haven't used those functionalities that much.

**Comment by pekkaklarck** [comment]
Ok, thanks for the review @aaltat . You know where to submit issues/PRs if you later find ways to enhance the docs.

**Comment by jussimalinen** [comment]
Awesome stuff, a great improvement for the docs. It is a bummer that we the inherited attributes dont inherit the docs, but It is still a lot better than before...

I couldnt find anythig to improve, but to be honest it is difficult for me to read this api like I was a newcomer to this...
