### ISSUE TITLE
Make Report Page Responsive

### ISSUE THREAD

**Issue by vinaybond** [robotframework/robotframework#2281]
Current report have fixed width and when test suite name is bigger, the suite name goes in next line expanding row height. It would be great if we can make reporting page responsive so that it can adjust itself as per screen resolution.

**Comment by pekkaklarck** [comment]
Could you give a concrete example, e.g. a screenshot, about this problem? Even better if you could look at how styles could be enhanced to fix the problem too.

**Comment by vinaybond** [comment]
Here it is:

![nonresponsive report](https://cloud.githubusercontent.com/assets/7723948/12047730/824bfc8a-aef6-11e5-9928-3a85f703a571.png)

**Comment by pekkaklarck** [comment]
I see. It would be easy to allow statistics table to use the whole page width. I think the main reason it is limited is that it doesn't look good on wide displays, and matching suite names on left to stats on right is harder if they are far away from each others. Names wrapping like in your example isn't that big a problem either.

Could you test different approaches how fix this issue? We can then compare them with the current situation.

**Comment by pekkaklarck** [comment]
Have you had time to look at different solutions?

**Comment by vinaybond** [comment]
I have not done anything on this yet. Once done, I'll share the code change here.

**Comment by pekkaklarck** [comment]
Any new info? I'm fairly sure reports/logs could be enhanced in this regard, but different solutions need to be tested with different browsers. I'd like reports/logs look good on a laptop screen, on an extra wide external display, and on a phone.

**Comment by clarmso** [comment]
Would using responsive web libraries such as [Skeleton](https://github.com/dhg/Skeleton) be a potential solution?

**Comment by pekkaklarck** [comment]
I'm fine with all kind of enhancements. Robot's logs/reports are mainly viewed on "normal" browsers and bundling a whole responsive library into them may not be worth the effort and likely size increase. I would assume just changing the default CSS rules and possibly adding some Javascript is enough, but I encourage everyone to test different approaches!

**Comment by pekkaklarck** [comment]
We nowadays have also #2346 about enhancing logs/reports. Keeping two related issues is not worth the effort and this issue hasn't got any attention lately.
