### ISSUE TITLE
Robotframework syntax highlighting for Notepad++

### ISSUE THREAD

**Issue by vkosuri** [robotframework/robotframework#2283]
Hello, 

I have created a Robot framework syntax highlighting for Notepad++ which is located at https://github.com/vkosuri/lang-robot

Below screen shot summaries the how it looks and color represents

```
Blue - Keywords
Orange - Variables
Green - Comments
```

![syntax-highlighter](https://cloud.githubusercontent.com/assets/13664257/12018694/650545a2-ad8c-11e5-8bf2-52719ab60f0a.png)

Please have a look and update your suggestions/improvements/comments?

**Comment by pekkaklarck** [comment]
Very cool! This issue tracker is for Robot Framework core, though. To get more publicity to your plugin, please consider doing the following:

- Announce the plugin on robotframework-users mailing list and possibly on other forums.
- Submit an issue to https://github.com/robotframework/robotframework.github.com to get the plugin added to http://robotframework.org. Even better if you can can create a pull request there.
