### ISSUE TITLE
Add Python3 compatible Python Remote Library

### ISSUE THREAD

**Issue by w60001** [robotframework/robotframework#2287]
The official list of remote libraries (https://code.google.com/p/robotframework/wiki/RemoteLibrary) lists PythonRemoteServer as the reference for a Python-based remote server.

This server code works great with Python2, but is not compatible with Python3.  I attempted to port the code to Python3, and got through the simple changes, but am now running into "TypeError: a bytes-like object is required, not 'str'" when running tests.

I would submit this issue under the PythonRemoteServer project, but the project looks abandoned.  I believe it is the responsibility of the RF community to have an example Python-based remote keyword server available for folks to reference.

**Comment by pekkaklarck** [comment]
PythonRemoteServer project is not abandoned. Nobody just had need and time to add any new features to it. Python 3 support is a good idea. It may require dropping support for versions prior to 2.6, though. Anyway, this discussion belongs to that project's tracker, not here.

**Comment by w60001** [comment]
Since I see much faster response in this forum, quick plug for https://github.com/robotframework/PythonRemoteServer/issues/29.  I even uploaded code that works for me, but needs some additional testing.

Thanks!
