### ISSUE TITLE
Process library: Process configuration stdout and stderr does always overwrite if file name is same

### ISSUE THREAD

**Issue by aaltat** [robotframework/robotframework#2289]
When I have something like this: 
```
| *** keywords *** |
| Verify Process |
| | Wait Until Keyword Succeeds | 120 | 10 | Check Status With Process |
| |
| Check Status With Process |
| | Process.Start Process | some_command | stdout=${OUTPUT_DIR}${/}process.log | stderr=STDOUT | 
```
Now each time ```Start Process``` keyword is called, the ```${OUTPUT_DIR}${/}process.log``` file is opened with ```w``` option, which will overwrite the file. In some cases it could be useful to provide possibility append in the file, instead of overwrite. Would it be possible to make the mode configurable? If it would be possible make such feature, any good ideas, how the mode should be defined?

Something like this perhaps:
```
| Process.Start Process | some_command | stdout=${OUTPUT_DIR}${/}process.log | stderr=STDOUT  | mode=append | 
```
Should same mode be applied to both stdout and stderr or should there be separate configuration? I am on favor on using same mode for both stdout and stderr. 

By looking the the code, the mode is hard coded in the ```_new_stream``` function, in 2.9.2 (did not look in to 3.0). And by a quick glance, it should be possible to make it configurable, with reasonable effort.

**Comment by pekkaklarck** [comment]
I don't see much use case for such functionality, but I believe you have one and it wouldn't complicate things too much. `mode` is too generic argument name, though. Would probably be better to have separate `stdout_mode` and `stderr_mode` to be consistent with other configuration and to allow maximum flexibility. If this is only for controlling append/overwrite, it might be even better to have `stdout_append=False` and `stderr_append=False`.

**Comment by aaltat** [comment]
*_append sounds better and clearer, let's go with that.

My use case, is again adb, sometimes the adb does not work properly and there is error. But the full error is only visible on the first time the command is run. I could divert the stdout and stderr to unique file but it's easier to get overall picture by reading single file.

**Comment by pekkaklarck** [comment]
Ok. Sounds good.

**Comment by pekkaklarck** [comment]
Is this still relevant for you @aaltat? Are you interested to provide a PR?

**Comment by aaltat** [comment]
Yes it's relevant, but I haven't found time to implement it. More pressing matters have come, which needs to be done first, before I have time to provide a PR.

**Comment by aaltat** [comment]
It looks like waiting long enough did remove this need. I do not have a need for this feature, because it came too complex to handle parse ADB output with `String` and `Collections`libraries, specially when with all the different phone models available. I am writing a separate library to run ADB command and parse the output. Therefore I do not need this enhancement.

**Comment by pavlo-logvyn** [comment]
Hi, I would love to have this functionality implemented. How can I leave a request for it?
