### ISSUE TITLE
Remove File forcefully

### ISSUE THREAD

**Issue by vkosuri** [robotframework/robotframework#2293]
On windows If file was used by any process, we were getting WindowsError exception.

Brief description about os.remove function

os.remove(path)
**On Windows, attempting to remove a file that is in use causes an exception to be raised;** on Unix, the directory entry is removed but the storage allocated to the file is not made available until the original file is no longer in use.

instead if we would having a param force, which will remove forcefully, something like below

``` Python
def remove_file(self, path, force=False):
        """Removes a file with the given path.

        Passes if the file does not exist, but fails if the path does
        not point to a regular file (e.g. it points to a directory).

        The path can be given as an exact path or as a glob pattern.
        The pattern matching syntax is explained in `introduction`.
        If the path is a pattern, all files matching it are removed.
        """
        path = self._absnorm(path)
        matches = self._glob(path)
        if not matches:
            self._link("File '%s' does not exist.", path)
        for match in matches:
            if not os.path.isfile(match):
                self._error("Path '%s' is not a file." % match)
            try:
                os.remove(match)
            except WindowsError as w:                
                if force:
                    os.unlink(path)
                raise
            self._link("Removed file '%s'.", match)
```

Does it make sense?

**Comment by pekkaklarck** [comment]
Does it work?

**Comment by pekkaklarck** [comment]
I don't think the proposed solution works. From the of [os.remove documentation](https://docs.python.org/2/library/os.html#os.remove):

> Remove (delete) the file path. If path is a directory, OSError is raised; see rmdir() below to remove a directory. This is identical to the unlink() function documented below. On Windows, attempting to remove a file that is in use causes an exception to be raised; on Unix, the directory entry is removed but the storage allocated to the file is not made available until the original file is no longer in use.

Notice especially that:
- `os.remove` and `os.unlink` are identical. Calling latter if the former fails makes no sense.
- `os.remove` is documented to raise an exception if a file is in use on Windows.
