### ISSUE TITLE
Intermittent Issue with strings getting corrupted ("\x03" character)

### ISSUE THREAD

**Issue by alleblancnuv** [robotframework/robotframework#2295]
I come from a hardware background and I am somewhat new to Robot Framework, so I may not be familiar with some terminology. 

We are using Robot Framework version 2.9.2, Python version 2.7.9, on Ubuntu 15.04.

We have been noticing a very strange issue with strings. A "\x03" character (which is an ETX character, or Ctrl-C) has been appearing in strings. It always seems to appear in place of a " ", "p", "P", or "0" (space=0x20, zero=0x30, P=0x50, p=0x70). 

For example, In urllib, the safe_map dictionary sometimes has the element at key 'p' changed to "\x03", sometimes it's element at key 'P' or '0'. Sometimes it appears as a robot framework error such as "\x03<10 cannot be evaluated", where "\x03" should actually be "0". It seems like once this strange error, all hell breaks loose and everything fails.

The error seems to just happen at random, after some time. For regression testing of the test software, we start a pybot process, run a set of tests, then once it's over, start a new process, etc. The error seems to happen about once every 10-20 runs.

Given the intermittent nature of the problem, I was thinking it could be related to memory, so I investigated garbage collection, but enabling/disabling it didn't seem to change anything. The other thing I investigated was the string encoding (unicode vs ascii/utf-8), but I couldn't find any issues (and it wouldn't explain the intermittence).

**Comment by pekkaklarck** [comment]
First of all, sorry for slow reply. This problem seems *really* strange and I have no idea why it could occur. Do you have any more information about the setup? Have you debugged this problem further yourself?

**Comment by alleblancnuv** [comment]
Hello Pekka, 

It is indeed a strange problem. The PC on which this was occurring recently stopped working (behaves like a bad motherboard or CPU, i.e. powers up but does not POST), we are trying to reproduce the error on a new PC. I am working in a different office for a few weeks, so I am trying to guide my team into reproducing the error, but they have not yet been successful. 

This whole issue may all be related to a failing CPU. Once I get back to my regular office, I will run the new test system the exact same way I was when the issue was happening. I will post my findings.

If the problem is due to a bad CPU, the character substitution still seems like a very odd symptom.

**Comment by pekkaklarck** [comment]
Any new information about this issue?

**Comment by pekkaklarck** [comment]
Closing due to lack of new information.
