### ISSUE TITLE
Log exact location of keywords

### ISSUE THREAD

**Issue by jkohvakk** [robotframework/robotframework#2296]
Robotframework 3.0 improves logging of resource keyword calls by logging the resource file names as libraries. This is visible both in log.html and in output.xml (library attribute, e.g. <kw name="Another keyword" library="resource">).

This is good but not enough with ugly legacy test material. Our test material seems to have resource files with the same name in different paths, e.g. ./resource.robot and ./foo/resource.robot. In this situation, both are shown as library="resource". It would be better to know the exact location of the keyword.

This could be achieved either by adding full path to library both in output and in log.html (library="foo.resource" in output.xml) or separately printing the source filename in log.html and adding source attribute to keywords in output.xml.

**Comment by pekkaklarck** [comment]
The problem with this is the increased size of output.xml and to some extend also log.html files. Increased size may not be justifiable when most people probably wouldn't be interested in this information.

Could you consider using listeners to detect resource paths instead? Listeners got new methods to inspect library imports in RF 2.9 (#2030).

**Comment by jkohvakk** [comment]
Hi Peke,

Sorry for not replying to this promptly. Now I finally had some time to play with listeners.

I got somehow stuck to the very beginning, however. What I would need to do in my listener is to somehow create tracking on where the imported keywords are coming from to be able to log their full paths. I have following problems:

How do I know which keywords are implemented by an imported library? resource_import and library_import only get the source file exact location.

How do I know when an imported resource file or library goes out of scope?

**Comment by pekkaklarck** [comment]
Unfortunately import related listener methods don't get information about actually imported keywords or about library scope. They would both be a useful additions to the API.

Currently you probably should somehow get this kind of missing information somehow otherwise. One possibility is creating XML spec files using Libdoc separately and reading info from them.

**Comment by pekkaklarck** [comment]
I don't think adding the requested information is a good idea. Problems with other approaches to get this information can be solved elsewhere. Closing.
