### ISSUE TITLE
add "--include pattern" "--exclude pattern" to libdoc

### ISSUE THREAD

**Issue by yahman72** [robotframework/robotframework#2301]
The use case is more or less the same as in #430 

Adding these arguments libdoc should be much more straightforward that the implementation discussed in #430.

Usage:
- for example all private keywords start with an underscore e.g. `_my_private_kw`
- run `python -m robot.libdoc --exclude _* my_resource.txt my_resource_doc.html`
- my_resource_doc.html contains documentation for all KWs except the ones starting with "_"

**Comment by pekkaklarck** [comment]
The problem with this approach would be that those keywords would still be usable. I'd rather limit keyword visibility for real than just hide them from docs.

Notice that now when we have keyword tags, actually implementing #430 shouldn't be that hard anymore. We could, for example, use a tag like `robot:private` to mark keywords private. Better continue this discussion in #430, though.
