### ISSUE TITLE
Add pop to ItemList for Keyword Object

### ISSUE THREAD

**Issue by jaloren** [robotframework/robotframework#2303]
In a prerun modifier, you may want to remove the last item in the list of keywords. Right now you have to do that via slicing -- it would be cleaner to support the pop in the keyword object. This would require adding the pop method to the ItemList object which in turn is inherited by the keyword object.

**Comment by jaloren** [comment]
This may be used to implement #2302

**Comment by jaloren** [comment]
To implement this, do i just need to add the following function to the ItemList class in model/itemlist.py

```python
    def pop(self,item):
        return item[:-1]
````

**Comment by pekkaklarck** [comment]
`pop` should accept optional `index` and return the popped item like `list.pop` does. Easiest implementation would be converting the internal data to a list, popping it, and setting internal data again. Testing best done with unit tests.

You might also want to check are there other list methods that could be added.

**Comment by pekkaklarck** [comment]
Are you @jaloren interested to implement this? I can easily do it myself too.

**Comment by jaloren** [comment]
I am swamped at work right now -- please feel free to do the code submit.
