### ISSUE TITLE
Rebot Issue: Reading XML source 'output_errors_incompatible.xml' failed: Incompatible XML element 'errors'.

### ISSUE THREAD

**Issue by jimbojd72** [robotframework/robotframework#2304]
I have an error on Rebot script after upgrading all my system to Robot Framework 2.9.2:
The error seems to come from from the errors tags in the output.xml.

I have the error on both Linux srv-jenkins-master-1 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux and Windows 7.

Logs from the console command:

H:\Python test>rebot --nostatusrc --removekeywords all --log none --report none --output output_errors_incompatible_reduced.xml output_errors_incompatible.xml
[ ERROR ] Reading XML source 'output_errors_incompatible.xml' failed: Incompatible XML element 'errors'.

Try --help for usage information.

H:\Python test>rebot --version
Rebot 2.9.2 (Python 2.7.11 on win32)

[output_errors_incompatible.zip](https://github.com/robotframework/robotframework/files/97640/output_errors_incompatible.zip)

Thanks for your help

**Comment by HelioGuilherme66** [comment]
Something happened in the output production.
This is my initial analysis:
```
$ xmllint output_errors_incompatible.xml 
output_errors_incompatible.xml:12286: parser error : Opening and ending tag mismatch: kw line 12142 and robot
</robot>
        ^
output_errors_incompatible.xml:12287: parser error : Premature end of data in tag test line 12141
output_errors_incompatible.xml:12287: parser error : Premature end of data in tag suite line 3990
output_errors_incompatible.xml:12287: parser error : Premature end of data in tag suite line 3989
output_errors_incompatible.xml:12287: parser error : Premature end of data in tag suite line 5
output_errors_incompatible.xml:12287: parser error : Premature end of data in tag suite line 4
output_errors_incompatible.xml:12287: parser error : Premature end of data in tag suite line 3
output_errors_incompatible.xml:12287: parser error : Premature end of data in tag robot line 2
```
Looks like it failed at setup:
```
<status status="FAIL" endtime="20160120 10:17:43.908" starttime="20160120 02:55:07.278"></status>
```
And in the end we see:
```
<msg timestamp="20160120 10:17:43.909" level="ERROR">Execution stopped by user.</msg>
```

It is expected that output.xml is not reliable when execution is interrupted (or I am not aware of fix of this).

**Comment by jimbojd72** [comment]
Sorry, I though that a normal interrupt (without asking to stop twice in a row to force it) will let Robot do its teardown and closing correctly its xml tag.

**Comment by pekkaklarck** [comment]
@HelioGuilherme66 is right, the output is broken. Rebot is not designed to handle such errors, but you can try using [Fixml](https://pypi.python.org/pypi/robotfixml).

With just this information it is not possible to know why the output is broken. If that occurs again, please submit a new issue with more information to help us reproduce the problem.
