### ISSUE TITLE
DateTime: Document that locale aware directives like `%b` don't work with Jython on non-English locales

### ISSUE THREAD

**Issue by laurioikarinen** [robotframework/robotframework#2306]
In RF 2.9.2 and 3.0, DateTime library does not work with %b directive. This worked in 2.8.7. Running with Jython.

Test (finnish selected in regional settings in Windows):

```
${time}=    Set Variable    pe tammi 22 14:00:00 2016
${date}=    Convert_Date    ${time} date_format=%a %b %d %H:%M:%S %Y
```

Result:

``` python
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 18: ordinal not in range(128)

Traceback (most recent call last):
  File "G:\Programming\robotframework\robotframework-2.9.2.jar\Lib\datetime$py.class", line 1778, in strptime
    struct, micros = _strptime(date_string, format)
  File "G:\Programming\robotframework\robotframework-2.9.2.jar\Lib\_strptime$py.class", line 308, in _strptime
    format_regex = _TimeRE_cache.compile(format)
  File "G:\Programming\robotframework\robotframework-2.9.2.jar\Lib\_strptime$py.class", line 308, in _strptime
    format_regex = _TimeRE_cache.compile(format)
  File "G:\Programming\robotframework\robotframework-2.9.2.jar\Lib\_strptime$py.class", line 265, in compile
    return re_compile(self.pattern(format), IGNORECASE)
  File "G:\Programming\robotframework\robotframework-2.9.2.jar\Lib\_strptime$py.class", line 257, in pattern
    processed_format = "%s%s%s" % (processed_format,
```

**Comment by pekkaklarck** [comment]
Have you tested with Python?

**Comment by laurioikarinen** [comment]
Unfortunately no, we have only the jar-installation available.

**Comment by pekkaklarck** [comment]
I see. Providing more information would fasten investigating this. Also, I don't see why it would be `%b` that's causing the issue. Anyway, I'll look at this when I have time.

**Comment by laurioikarinen** [comment]
It is curious. Replacing 'tammi' with '01' and using 'date_format=%a %m %d %H:%M:%S %Y' works so name of weekday is not an issue, only month in text format. Also %c does not work in this case, but %c is exactly what described above.

**Comment by pekkaklarck** [comment]
Notice that if you really wanted to help debugging this, you could try how `datetime.strptime` works on Jython (and Python) without Robot Framework. This could easily be a Jython bug.

**Comment by pekkaklarck** [comment]
Any new information about this? I tried to debug this myself but the problem is likely also dependent on OS locale configuration. As I commented above, it would be good to test this with Jython alone to see how `datetime.strptime` works.

I'm also surprised that you got `UnicodeDecodeError` and not `ValueError`.

**Comment by laurioikarinen** [comment]
Unfortunately no new information. It doesn't work with Finnish locale in any of our PC, but I don't have the time to find out how to check this with Jython only. If you have some simple instructions that don't take too long to execute, maybe I can find the time to check them.

**Comment by pekkaklarck** [comment]
You can just start Jython interpreter and use [datetime.strptime](https://docs.python.org/2/library/datetime.html#datetime.datetime.strptime) there:

```
$ jython
Jython 2.7.0 (default:9987c746f838, Apr 29 2015, 02:25:11) 
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)] on java1.8.0_72
Type "help", "copyright", "credits" or "license" for more information.
>>> from datetime import datetime
>>> dt = datetime.strptime('2016-02-24 16:20:01', '%Y-%m-%d %H:%M:%S')
>>> dt
datetime.datetime(2016, 2, 24, 16, 20, 1)
>>> 
```

If you only have robotframework.jar, you need to first install Jython or get the standalone jython.jar. Notice that a big difference in robotframework-2.9.jar compared to the older versions is that it contains Jython 2.7 and not Jython 2.5(.3). You thus may want to test also with Jython 2.5 to see has the behavior possibly changed.

**Comment by laurioikarinen** [comment]
I think this is related to -Dsun.locale.formatasdefault=true flag. 

If I put only the two lines in original description to a robot tests case file test.txt like:

```
*** Settings ***
Library	DateTime

*** Variables ***
*** Test Cases ***

Test1
	${time}=	Set Variable	pe tammi 22 14:00:00 2016
	${date}=	Convert_Date	${time}	date_format=%a %b %d %H:%M:%S %Y
```

 and run the test like this:

```
$ java -Dsun.locale.formatasdefault=true -jar robotframework-3.0.jar test.txt
==============================================================================
Test
==============================================================================
Test1                                                                 | FAIL |
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 18: ordinal not in range(128)
------------------------------------------------------------------------------
Test                                                                  | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  G:\Programming\robotframework\output.xml
Log:     G:\Programming\robotframework\log.html
Report:  G:\Programming\robotframework\report.html
```

I get the UnicodeDecodeError. If I run the same test without the setformatasdefault flag then I get valueError since 'tammi' is not correct string for us locale. However I need the flag since I am parsing the times from a file created by the tested application and it prints the times like in the example.

I also managed to test this with Jython, and there this works as expected:

```
$ java -Dsun.locale.formatasdefault=true -jar jython.jar
Jython 2.7.0 (default:9987c746f838, Apr 29 2015, 02:25:11)
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)] on java1.7.0_80
Type "help", "copyright", "credits" or "license" for more information.
>>> from datetime import datetime
>>> dt = datetime.strptime('2016-tammi-24 16:20:01', '%Y-%b-%d %H:%M:%S')
>>> dt
datetime.datetime(2016, 1, 24, 16, 20, 1)
>>>
```

My current workaround for this issue is to manually replace all text representations of month with numbers and parse those, that is however quite an ugly workaround but works at least for the moment.

**Comment by pekkaklarck** [comment]
This seems to be related to system/Java configuration. I don't have much experience from setting locales and have never heard about the option you use. What do you get with Jython when you don't use it?

**Comment by laurioikarinen** [comment]
If I don't give that option, then both Jython and RF are using en_US locale and then Finnish texts don't obviously work in date strings. I my understanding that option tells Java to use the same locale that is selected in Windows' regional settings and not OS language.

**Comment by pekkaklarck** [comment]
Any new information about this issue?

**Comment by laurioikarinen** [comment]
I think I should be the one asking you that. There seems to be a bug in RF and it happens all the time in certain environments and it should be a RobotFramework developer who investigates this.

**Comment by pekkaklarck** [comment]
No, you definitely shouldn't be asking that. This is an open source project and you cannot expect anyone to investigate anything unless explicitly agree on a paid support contract. I cannot easily debug an issue that occurs in your environment and don't have interest to spent too much of my free time replicating your setup. This issue can be closed if it isn't important enough for you to investigate it.

**Comment by laurioikarinen** [comment]
It was a rethorical question, if it wasn't clear... I know this is open source project and I appreciate the work you are doing. 

This is important for us, but I don't have time either and more importantly knowledge to investigate it. With the knowledge that I have there is nothing more that I can do, that is why I said why I said: for investigation someone who knows the code behind the platform is needed. 

I have reported a bug and of course it is up to you to decide what to do with it. If you decide that you will not fix this then we just have to live with it.

**Comment by laurioikarinen** [comment]
Also on the reproducibility, it happens on every win7 pc with OS language being English and regional settings set to Finnish. Should be therefore reproducible in virtual machines as well.

**Comment by pekkaklarck** [comment]
I'm fairly certain there is no bug in Robot Framework. We simply call [datetime.strptime](https://docs.python.org/2/library/datetime.html#datetime.datetime.strptime) and it works fine in general. In your environment when using Jython and special `-Dsun.locale.formatasdefault` option it fails, and that looks more like bug in Jython or in your system configuration. The best way forward is trying to reproduce the problem without Robot in the environment where the problem occurs in the first place. I simply cannot do that.

**Comment by laurioikarinen** [comment]
If you look above, then you see that it doesn't reproduce with Jython only.

**Comment by pekkaklarck** [comment]
Yes, it didn't occur like that and you need to test other options. One thing that could make a difference is using a Unicode string as an argument to `strptime`. Text you specify in data is passed to keywords as Unicode and based on the resulting `UnicodeDecodeError` the problem is somehow Unicode related. In practice you just need to add `u` prefix to strings and try these:

```python
datetime.strptime(u'2016-tammi-24 16:20:01', u'%Y-%b-%d %H:%M:%S')
datetime.strptime('2016-tammi-24 16:20:01', u'%Y-%b-%d %H:%M:%S')
datetime.strptime(u'2016-tammi-24 16:20:01', '%Y-%b-%d %H:%M:%S')
```

**Comment by laurioikarinen** [comment]
Ok, so my original test was incomplete/incorrect, it could have been better to just start with that information. I am an end-user and can't know what information you want unless you ask specific questions that I can answer.

And you are right, the problem is in Jython when handling unicode format-strings, after removing the u the same command works.
`$ java -Dsun.locale.formatasdefault=true -jar jython-standalone-2.7.0.jar
Jython 2.7.0 (default:9987c746f838, Apr 29 2015, 02:25:11)
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)] on java1.7.0_71
Type "help", "copyright", "credits" or "license" for more information.
>>> from datetime import datetime
>>> datetime.strptime('pe tammi 22 14:00:00 2016', u'%a %b %d %H:%M:%S %Y')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "Z:\Lauri\jython-standalone-2.7.0.jar\Lib\datetime.py", line 1778, in strptime
  File "Z:\Lauri\jython-standalone-2.7.0.jar\Lib\_strptime.py", line 308, in _strptime
  File "Z:\Lauri\jython-standalone-2.7.0.jar\Lib\_strptime.py", line 308, in _strptime
  File "Z:\Lauri\jython-standalone-2.7.0.jar\Lib\_strptime.py", line 265, in compile
  File "Z:\Lauri\jython-standalone-2.7.0.jar\Lib\_strptime.py", line 257, in pattern
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 18: ordinal not in range(128)
>>>`

So you can close this and I will file a bug to Jython.

**Comment by pekkaklarck** [comment]
It didn't occur to me earlier that the problem occurs only with Unicode strings. It could have also be caused by the `-D` option you use (and it may still well be caused by that somehow) and using different values with it would have been another way to debug this further. Because I don't have same environment as you, I cannot easily do such debugging, and that's why I asked you to do it. I could have tried setting up a matching virtual machine, but I cannot realistically expect I do something like that every time some submits an issue here:

- This is a bug that bothers you. I would expect you to be interested to spent time investigating it.
- I don't get paid to investigate this bug. I would assume you are.

The good news is that now we know that the problem doesn't occur with byte strings ("normal" strings in Python 2) and could implement a workaround to convert Unicode strings to byte strings when possible.

**Comment by pekkaklarck** [comment]
The issue @laurioikarinen submitted to Jython tracker is http://bugs.jython.org/issue2503.

I thought again about adding a workaround to convert Unicode strings to byte strings in DataTime library, but it turned out that the locale aware `%b` directive doesn't work too well with Jython in general. There's a separate issue about that: http://bugs.jython.org/issue2285. In this situation workarounds in our code don't make much sense. Best we can do is documenting that `%b` doesn't really work.
