### ISSUE TITLE
Add Robot Framework Foundation as copyright holder for 2016->

### ISSUE THREAD

**Issue by aksenov007** [robotframework/robotframework#2309]
Please, update COPYRIGHT.txt: change the year. I know, this is a few "bug" :)

**Comment by lgc-sk** [comment]
Remove the end date.
http://stackoverflow.com/questions/2390230/do-copyright-dates-need-to-be-updated

**Comment by pekkaklarck** [comment]
We may also need to do changes to copyright holders and thus this is a bit bigger task. This situation is a bit unclear at the moment but ought to be clarified soon. Copyright year definitely needs to be updated before 3.0.1 so setting milestone accordingly. Omitting the end date like @lgc-sk proposed is probably a good idea.

**Comment by pekkaklarck** [comment]
Nokia doesn't anymore directly support Robot Framework but instead we have [Robot Framework Foundation](http://robotframework.org/foundation/) and RF 3.0.1 is the first project sponsored by them. We thus need to change copyrights so that they state:

    Copyright 2008-2015 Nokia Networks
    Copyright 2016- Robot Framework Foundation

**Comment by pekkaklarck** [comment]
Also need to update docs to mention the Foundation. This includes at least User Guide, robot/run.py and README.

**Comment by pekkaklarck** [comment]
Copyrights in source code and elsewhere as well as docs about the sponsor updated.
