### ISSUE TITLE
ELSE is executed for embedded Run Keyword If, even if parent Run Keyword If is FALSE

### ISSUE THREAD

**Issue by manycoding** [robotframework/robotframework#2316]
So even if the first condition is false, a keyword in ELSE is executed.  
```
  Run Keyword If    "${TRUE}" != "${TRUE}"    Run Keyword If    "${TRUE}" != "${TRUE}"    No Operation    ELSE    No Operation
```

```
KEYWORD BuiltIn . Run Keyword If "${TRUE}" != "${TRUE}", Run Keyword If, "${TRUE}" != "${TRUE}", No Operation, ELSE, No Operation
Documentation: 	Runs the given keyword with the given arguments, if condition is true.
Start / End / Elapsed: 	20160211 13:42:37.890 / 20160211 13:42:37.891 / 00:00:00.001
00:00:00.000 KEYWORD BuiltIn . No Operation
Documentation: 	Does absolutely nothing.
Start / End / Elapsed: 	20160211 13:42:37.891 / 20160211 13:42:37.891 / 00:00:00.000
13:42:37.891 	TRACE 	Arguments: [  ] 	
13:42:37.891 	TRACE 	Return: None 	
13:42:37.890 	TRACE 	Arguments: [ '"True" != "True"' | 'Run Keyword If' | '"${TRUE}" != "${TRUE}"' | 'No Operation' | 'ELSE' | 'No Operation' ] 	
13:42:37.891 	TRACE 	Return: None
```

I run embedded Run Keyword If because I needed some workaround for if else with null object.
When it actually is none, it verifies ELSE IF anyway and gives null object reference error.
```
   Run Keyword If    "${target_state}" == "${NONE}"    Target State Type Should Be    conditionNone   ELSE IF "${target_state.tag}" == "prereqTargetStateSet"
```

As a workaround to the workaround, I run another keyword. It looks something like this:
```
Some Keyword
...
    ${target_state}=    Get Elements    ${data}    tag
    Run Keyword If    "${target_state}" == "${NONE}"    Target State Type Should Be    none
    Run Keyword If    "${target_state}" != "${NONE}"    Check Some Logic    ${target_state}

Check Some Logic
    [Arguments]    ${target_state}
    Run Keyword If    "${target_state.tag}" == "state"    Expression Should Be    ${target_state}    ELSE    Some Other Keyword
```

**Comment by pekkaklarck** [comment]
The `ELSE` you used binds to your first `Run Keyword If`. It's condition is false, so the `ELSE` branch is executed. In other words, your example is exactly like this:

    Run Keyword If    False    Some Keyword    possible    arguments    ELSE    No Operation

The actual problem you seem to have is that you have quotes in your expression. For example, `"${target_state}" == "${NONE}"` is exactly same as `"${target_state}" == "None"` and that's likely not what you want. See BuiltIn library documentation for possible alternatives:
http://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Evaluating%20expressions

**Comment by haramjan** [comment]
How can we multiple condition is executed with && and || in one if?
