### ISSUE TITLE
Operating system library: Copy file to an existing directory

### ISSUE THREAD

**Issue by clarmso** [robotframework/robotframework#2319]
Robot Framework version: 2.9.2
Python Interpreter: Jython 2.7.0 on java1.8.0_65
Operating System: Windows 8.1

I have been trying to copy a file to an existing folder using "OperatingSystem.Copy File" but encounter the following error:

<timestamp> :  FAIL : OSError: [Errno 21] Is a directory: <destination directory>

The culprit is located in lines 806-807 of robotframework/src/robot/libraries/OperatingSystem.py.  The _atomic_copy function tries to remove the destination directory if it is already there.  

In my case, I do not have the permission to remove the destination directory.  In addition to the permission, we cannot assume that we are always copying files to an empty directory.  Some files may have already be there and are needed.

I suggest that lines 806-807 should not remove the existing directory.

**Comment by pekkaklarck** [comment]
[Those lines](https://github.com/robotframework/robotframework/blob/master/src/robot/libraries/OperatingSystem.py#L806) are there to remove possible destination file if it already exists. It seems you are trying to copy a file *over* an existing directory, not into an existing directory. The latter should definitely work.

**Comment by clarmso** [comment]
Yes, you read my mind.  I was trying to copy a file to an _existing_ directory.  From the [documentation](http://robotframework.org/robotframework/latest/libraries/OperatingSystem.html#Copy%20File), I should be able to specify the destination by its directory:

2) If the destination is an existing directory, the source file is copied into it. A possible file with the same name as the source is overwritten.

With [this line](https://github.com/robotframework/robotframework/blob/master/src/robot/libraries/OperatingSystem.py#L807), the destination directory is removed prior copying the file over.  @pekkaklarck , would you consider the bug to be in the code or in the documentation?

**Comment by pekkaklarck** [comment]
Based on the code you are copying *over* an existing directory, not into it. I'm fairly certain the latter is tested pretty thoroughly. Bugs are always possible, though. To know for sure, we'd need an example we can run ourselves.

**Comment by clarmso** [comment]
Thanks for getting back to me quickly.

It looks like the software that I've been testing is actively working on the same directory when the robot tests are running.  The error may be triggered by the fact that robot cannot carry out the copy file operation.  The following seems fine on both jybot and robot:
[RobotFrameworkIssue2319.txt](https://github.com/robotframework/robotframework/files/142842/RobotFrameworkIssue2319.txt)
