### ISSUE TITLE
robot 3: Version keyword?

### ISSUE THREAD

**Issue by emp302** [robotframework/robotframework#2323]
robot 3 now offers an independent start script with a "--version" option, which is great.
Is there also a way to extract this information using a keyword? This way custom libraries and test cases could instantly check whether they are run by a minimum version of robot.

**Comment by Tattoo** [comment]
`--version` has been part of Robot for a long time. Does this do what you want?

```
>>> from robot.version import VERSION
>>> VERSION
'3.0'
```
works for libraries while:
```
*** Test cases ***
TC
  ${version}=    Evaluate    robot.version.VERSION    robot
```
works for test cases

**Comment by pekkaklarck** [comment]
Standard `robot.__version__` works too and is less likely to change in the future. Notice that robotframework-users and other such forumns are generally recommended for asking quostions.
