### ISSUE TITLE
error too many files open

### ISSUE THREAD

**Issue by heicci** [robotframework/robotframework#2327]
When running test cases, and command "lsof -a -p 6233", there is constantly growing number of
unix domain sockets and eventually too many files open error occurs.  

This pattern is repeated hundred of times:
robot   6233 root  176u  a_inode                0,9         0    7250 [eventpoll]
robot   6233 root  177r     FIFO                0,8       0t0 2562350 pipe
robot   6233 root  178u     unix 0xffff8800c8919180       0t0 2564510 socket
robot   6233 root  179u     unix 0xffff8800c8918000       0t0 2564511 socket

Error happened with 24 tcs, is this why I should have no more than 10 tcs per suite?

**Comment by pekkaklarck** [comment]
Could you please clarify? I didn't understand the description fully, but Robot definitely shouldn't be opening extra files or domain sockets during execution. A library that you are using could do that, though.

**Comment by heicci** [comment]
yes, I mean the number of open files is growing when executing test cases in one suite. lsof command output looks like the example above, but there are 1000 entries like that. I think this leads to error at some point. 

I was wondering if anyone else have had similar problems, I don't know which library is causing this.
I am using sshlibrary and processlibrary. I can increase the maximum number of open files per process
and cope with this, but it would be nice to know what is causing it.

**Comment by pekkaklarck** [comment]
It's impossible for others to know what libraries you use and how. I recommend you to create as simple example as possible that demonstrates the problem. Unless that example uses just Robot Framework and standard libraries, this issue tracker isn't the right place for this issue.

**Comment by pekkaklarck** [comment]
Closing due to lack of new information.
