### ISSUE TITLE
Multiple keyword matching, even though they are different

### ISSUE THREAD

**Issue by utkjad** [robotframework/robotframework#2328]
Version - 
```
robotframework==3.0
robotframework-databaselibrary==0.6
robotframework-lint==0.6.2
robotframework-ride==1.5.2.1
robotframework-selenium2library==1.7.4
```
I have keywords  as follows-
```
Select "${control}" And Go To Next Screen
	Select From Multiselect		${control}
	click	btnNext

Select "${option}" In "${control}" And Go To Next Screen
	Select list item index	${control}	${option}
	Click	btnNext
```
and I am using following in Test case 
```
Select "${XXX}" In "YYY" And Go To Next Screen
```
The error log is -
```
	Resource file 'GettoHomeScreen.txt' contains multiple keywords matching name 'Select "${XXX}" In "YYY" And Go To Next Screen':
    Select "${control}" And Go To Next Screen
    Select "${option}" In "${control}" And Go To Next Screen
```

**Comment by HelioGuilherme66** [comment]
Usually telling what is the version of Robot Framework would help a lot.

**Comment by utkjad** [comment]
@HelioGuilherme66 : Thanks!
Also, if anybody can direct me to the code where it checks for comparison, I would really appreciate it. 
It may not a big fix after-all!
I guess, the code must be skipping the text in between. (Just a  wild guess)

**Comment by pekkaklarck** [comment]
I don't think there's a bug. It seems that the used keyword really matches both of the defined keywords. You could limit matching by defining a custom pattern:
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#using-custom-regular-expressions

**Comment by utkjad** [comment]
@pekkaklarck : Thank you very much for this. 
However, isn't it a bit inconvenient? May be we can treat this as feature for keyword/Test Case headings?

**Comment by utkjad** [comment]
@pekkaklarck : If we use -
```
*** Keywords ***
I execute "${cmd}"
    Run Process    ${cmd}    shell=True

I execute "${cmd}" with "${opts}"
    Run Process    ${cmd} ${opts}    shell=True
```
instead of 
```
*** Keywords ***
I execute "${cmd:[^"]+}"
    Run Process    ${cmd}    shell=True

I execute "${cmd}" with "${opts}"
    Run Process    ${cmd} ${opts}    shell=True
```
it would convenient for the tester, right?

We can find the concerned Test Case below this layer. Also, if somebody wants to go with regex, he should be allowed to do that as well. 
Having said this, we can limit this particular feature to naming of the test cases only.

**Comment by pekkaklarck** [comment]
How should that work in practise?

**Comment by pekkaklarck** [comment]
Closing due to lack of new information.

**Comment by krishnapython** [comment]
Hi pekkaklarck,

We have 2 repos with same resource file name in the git. While running testcases from one repo we are hitting multiple keywords error. Could any one give the solution for it.

Multiple keywords with name 'SSH-Set-Timeout' found. Give the full name of the keyword you want to use:
SSH-Wrapper.SSH-Set-Timeout
SSH-Wrapper.SSH-Set-Timeout

Thanks
Krishna
