### ISSUE TITLE
When a test case fails, show rest of the top-level keywords in log as gray

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#233]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=233) by @pekkaklarck on 16 Feb 2009_

When a test case fails rest of the keywords are not executed (except for
teardown), but we could still show what top-level keywords the test case
would have had.

I have earlier tried to implement this so that all keywords, also those
inside higher level keywords, are listed but that turned out to be very
hard. Showing only the top-level keywords ought to be relatively simple
since testdoc.py [1] can already do that.

[1] 
<a href="https://code.google.com/p/robotframework/wiki/TestDataDocumentationTool" rel="nofollow">https://code.google.com/p/robotframework/wiki/TestDataDocumentationTool</a>

**Comment by pekkaklarck** [comment]
There turned out to be users who wanted this in the end and this was implemented in RF 4.0 (#3842).
