### ISSUE TITLE
Method to Avoid Reading Keyword Execution Steps to Output xml

### ISSUE THREAD

**Issue by bejohn** [robotframework/robotframework#2335]
Hi,

Is there any way to avoid reading the keyword execution steps to the output xml? I want to run robot scripts in parallel, so I use pabot. But then again I wanted a pybot wrapper. The output.xml for the wrapper is faulty. I tried giving None for the report, output and log for the wrapper. The suite of testcases still breaks.

So is there anyway of disabling this?

[ ERROR ] Reading XML source '//output.xml' failed: ParseError: junk after document element: line 34, column 0

**Comment by pekkaklarck** [comment]
I don't understand the problem. Please clarify.

**Comment by bejohn** [comment]
Hi Pekka,
Thank you so much for responding. Basically I was trying to run nested Robot scripts and then combine the inner output to the outer script. 

 ---------------------------------------------
|       outer robot script                     |
|          --------------------------            |
|          |   inner robot script  |           |
|          --------------------------            |
|       rebot to combine inner output |
|        with outer output xml              |
_____________________________

The step for rebot failed because the outer output.xml is being created at the time. I later used a listener to do the output combine.

But the query I had was is there anyway to run a keyword without having the execution steps of the keyword written to the output.xml?

**Comment by pekkaklarck** [comment]
Is the problem that you are running multiple test runs at the same time and writing output always to same output.xml file that gets corrupted? If yes, why don't you configure the output file for different runs to avoid conflicts?

There is no way to avoid keywords logging to output.xml.

**Comment by bejohn** [comment]
Thank you. I used different output files and later used the close in the listener to combine the different results with the main output.xml. That worked out perfectly.
