### ISSUE TITLE
about installation on windows 7 need to add pybot to system path

### ISSUE THREAD

**Issue by z1yuan** [robotframework/robotframework#2336]
hi,

i installed rebot-framework on windows 7 with command "python setup.py install". It seems like after the installation, system could still not find pybot. After checking the files, i add  "C:\Python27\Lib\site-packages\robotframework-3.0.1.dev20151231-py2.7.egg\EGG-INFO\scripts;" into path of system variables, then the robot-framework runs as i expect. 
is it a issue or the setup.py is just so defined? or there are some steps i was missing?

**Comment by pekkaklarck** [comment]
This is documented thoroughly in the installation instructions:
https://github.com/robotframework/robotframework/blob/master/INSTALL.rst

**Comment by z1yuan** [comment]
Thanks you very much! I have go through the installation instruction and you are right, there is such description there (- Setting  PATH  on Windows). Is that possible that you put some words in install outout to let newbie user(like me) to know, that we must add such path to system variable :)?

**Comment by pekkaklarck** [comment]
What exactly should be added and where? Also, where did you get the package you installed? I'm surprised thag you have version 3.0.1.dev.
