### ISSUE TITLE
Repeat Keyword Until No Failure

### ISSUE THREAD

**Issue by claytonneal** [robotframework/robotframework#2340]
It would be good to have new keyword:
- Repeat Keyword Until No Failure

The idea being that it will repeat a specified keyword until:
- Max times is reached OR
- Keyword does not Fail

This then can be used for operations that may fail on first attempt, but should be retried until either the operation works or a max number of retries is reached

Arguments are:
- repeat : Either number of retries or a timeout
- name : name of keyword
- args : keyword args

**Comment by trogdor259** [comment]
Why not use the Wait Until Keyword Succeeds keyword? Seems to do exactly what you are wanting.
