### ISSUE TITLE
segmentation fault executing ride.py with python 2.7

### ISSUE THREAD

**Issue by mgr390** [robotframework/robotframework#2342]
Environment characteristics:
-------------------------------------
1. Latest version of robotframework and ride. They were installed using pip

mgr-pc:.ssh mgr$ ride.py
Segmentation fault: 11

Process:               Python [67030]
Path:                  /usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
Identifier:            org.python.python
Version:               2.7.6 (2.7.6)
Code Type:             X86-64 (Native)
Parent Process:        bash [78240]
Responsible:           iTerm [5239]
User ID:               504

Date/Time:             2016-03-15 20:42:28.396 +0100
OS Version:            Mac OS X 10.11.3 (15D21)
Report Version:        11
Anonymous UUID:        B2BD8DEA-05A5-4AF1-77BC-0E178639084D

Sleep/Wake UUID:       AA934ED3-80D8-4AC2-8CD6-2E0777498946

Time Awake Since Boot: 1100000 seconds
Time Since Wake:       42000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT

**Comment by HelioGuilherme66** [comment]
Like I mentioned in #2341 RIDE issues are not in this project.
You did see the [Install Instructions](https://github.com/robotframework/RIDE/wiki/Installation-Instructions)? The wxPython version should be 2.8.12.1 (with unicode). For the Mac OS 10.11.03 I know of success in using an experimental RIDE with wxPython 3.0.2. But you should try first the supported version.

**Comment by mgr390** [comment]
Thank you so much! I will try this.

**Comment by pekkaklarck** [comment]
Wrong tracker.
