### ISSUE TITLE
Tags with variables can't be included with command line arguments

### ISSUE THREAD

**Issue by KenHs** [robotframework/robotframework#2343]
I'm attempting to set my tags using variables, then include those tags with a --include flag on the command line. Here is the script:

```
*** Settings ***
Documentation    Testing Tags
Default Tags    test1    test2

*** Variables ***
${TEST1}    test1


*** Test Cases ***

TEST 1
    [Tags]    ${TEST1}
    Log    This is test 1

TEST 2
    [Tags]    test2
    Log    This is test 2

```

If I run with 'test2' I get the expected result:

```
pybot -i test2 tagtest.txt 
==============================================================================
Tagtest :: Testing Tags                                                       
==============================================================================
TEST 2                                                                | PASS |
------------------------------------------------------------------------------
Tagtest :: Testing Tags                                               | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed
==============================================================================
Output:  ...output.xml
Log:     ...log.html
Report: ...report.html
```

If I run with 'test1' the script fails

```
pybot -i test1 tagtest.txt 
[ ERROR ] Suite 'Tagtest' contains no tests with tag 'test1'.

Try --help for usage information.
```
Reference: Section 2.2.5 Tagging Test Cases 
It looks like this is supported, but not functional. (At least, not the way I am using it!)

**Comment by HelioGuilherme66** [comment]
It is not possible to use variables as tags. Even if you defined ${TEST1} = test1 (like in command line `--variable TEST1:test1`) it would not work.
But your assumption of Default Tag is wrong. If you delete the row [Tags] from TEST 1, only then the default tags will be applied to TEST 1 (TEST 2 would not apply default tags). Try to run the test with tag `test1` and only TEST 1 should run.

**Comment by KenHs** [comment]
Thanks for the update, I appreciate the response!
The Default Tags is not being used for this example. It works as expected in my regular testing. I simply included it here as part of my debugging process.

However I am guessing the documentation is wrong?

http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#tagging-test-cases

> Tags can be created using variables, assuming that those variables exist.

```
Own tags with variables
    [Documentation]    This test has tags host-10.0.1.42 and req-42.
    [Tags]    host-${HOST}
    No Operation

```

**Comment by HelioGuilherme66** [comment]
OK
I managed to have it working. You must have the variable defined in the Variables section, then you can use it.
This is my run example (see escaped $):
```
robot --variable TEST1:3 -i tag-\${TEST1} test.robot
```
This is the test file:
```
*** Variables ***
${TEST1}          ${EMPTY}

*** Test Cases ***
new
    [Tags]    tag-${TEST1}
    No Operation

new2
    [Tags]    tag2
    No Operation
```

Maybe there is potential for some improvement, for example, allowing to:
```
robot --variable TEST1:3 -i tag-3 test.robot
```

**Comment by KenHs** [comment]
I tried this out, and it does work, but wont necessarily work for my needs. I think I am trying to exceed the design of tags really, and probably need to go back to a more simple design. Basically, each tag was a list of either the product names it could be run against, OR version names it supported. Instead of hard coding each tag for the test cases, I was using variables for the tags. This way I could control which test cases were run for a new product relatively easily, by adding that product to the variable I was using for the tag.

REALLY I still have a valid solution, just hard code the tags. I think I'll take a closer look at my design instead of trying to force tags to do something it wasn't meant to.

Thanks again for your help! I really appreciate it.
