### ISSUE TITLE
suite status 'starttime' and 'endtime' are both N/A when merging re-executed (--rerunfailed) tests

### ISSUE THREAD

**Issue by elginpeteza** [robotframework/robotframework#2344]
I just upgraded from RF 2.8.5 to RF 2.9.1 (also tested with RF 3.0). I noticed that merging re-executed tests using `rebot -o output.xml --merge output0.xml output1.xml` generates an `output.xml` with the suite's `starttime` and `endtime` set to `N/A`. 
![rebot_merged_output_xml](https://cloud.githubusercontent.com/assets/15134604/13842272/4919ea76-ec68-11e5-8c07-06b7b90d4018.png)

In 2.8.5 these parameters have values equal to original (`output0.xml`) suite's `starttime` and `endtime`, disregarding re-executed suite's `starttime` and `endtime`.
Merged output in 2.8.5:
![rebot_285_merged_output_xml](https://cloud.githubusercontent.com/assets/15134604/13842596/fefa59a6-ec69-11e5-9647-06f3373b2e1f.png)
Original output in 2.8.5:
![rebot_285_original_output_xml](https://cloud.githubusercontent.com/assets/15134604/13842599/064c5c0e-ec6a-11e5-8ccb-b36cadcd6667.png)
Rerunfailed output in 2.8.5:
![rebot_285_rerunfailed_output_xml](https://cloud.githubusercontent.com/assets/15134604/13842719/b9db36c8-ec6a-11e5-955d-c9d8de8ce9a8.png)

Is this change in behavior of rebot intended?
Wouldn't it make sense to use the `starttime` of original suite and `endtime` of re-executed suite?

**Comment by elginpeteza** [comment]
Steps performed:
# first execute all tests
pybot --output output0.xml tests 
# then re-execute failing
pybot --rerunfailed output0.xml --output output1.xml tests 
# finally merge results
rebot --merge output0.xml output1.xml

**Comment by pekkaklarck** [comment]
The motivation for setting start and end times to N/A is that when new tests are added to the suite, original times don't really make sense anymore. Same happens if you use e.g. `--include` or `--exclude` with Rebot. I don't want to change the default behavior, but having a way to keep the original times would be nice. Notice also that Rebot already accepts `--starttime` and `--endtime`, but they only apply to the top level test suite.

**Comment by pekkaklarck** [comment]
Is someone interested to implement support for keeping the original times? I guess there could be a separate command line option to enable that. If there's no interest, this issue will be closed.

**Comment by pekkaklarck** [comment]
No interest. Closing.
