### ISSUE TITLE
Libdoc has problem with dynamic libraries and when using @keyword decorator

### ISSUE THREAD

**Issue by aaltat** [robotframework/robotframework#2345]
The libdoc can not parse the hybrid library keyword documentation if the @keyword decorator and dynamic discovery of keyword is used. Example if mode is ```tmp.py``` file and looks like this:
```
from robot.libraries.BuiltIn import BuiltIn
from robot.api.deco import keyword


class MyClassName(object):

    def get_keyword_names(self):
        return [name for name in dir(self) if hasattr(getattr(self, name), 'robot_name')]

    @keyword
    def keyword_here(self):
        print self.get_lib

    @property
    def get_lib(self):
        return BuiltIn().get_library_instance('Selenium2Library')
```
Now if I run the libdoc like this, from the folder where `tmp.py` is, I see this:
```
python -m robot.libdoc tmp.MyClassName list
Calling dynamic method 'get_keyword_names' failed: RobotNotRunningError: Cannot access execution context

Try --help for usage information.
```

I as workaround, I can do this, for the `get_lib`:
```
from robot.libraries.BuiltIn import BuiltIn
from robot.libraries.BuiltIn import RobotNotRunningError
from robot.api.deco import keyword


class MyClassName(object):

    def get_keyword_names(self):
        return [name for name in dir(self) if hasattr(getattr(self, name), 'robot_name')]

    @keyword
    def keyword_here(self):
        print self.get_lib

    @property
    def get_lib(self):
        try:
            lib = BuiltIn().get_library_instance('Selenium2Library')
        except RobotNotRunningError:
            lib = None
        return lib
```
And then libdoc works OK, output in below. But I was wondering would there be better solution to the problem and is this a bug? If there is not better way, perhaps the user guide could be updated to state the problem and provide some hints to overcome the problem. 
```
python -m robot.libdoc tmp.MyClassName list
Keyword Here
```
Tested with robotframework==2.9.2 and robotframework==3.0

**Comment by pekkaklarck** [comment]
This problem has nothing to do with the `@keyword` decorator. The reason for the error is twofold:

- Robot needs to call your `get_keyword_names` method to know what keywords the library implements.
- Your `get_keyword_names` indirectly executes get_lib property.

I don't think there's anything that could be changed on Robot side to fix this issue. Possible solutions in your library include blacklisting propertys and accessing attributes via class, not instance, to avoid property methods being called.

**Comment by aaltat** [comment]
The `get_keyword_names` implementation comes from the [User Guide](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#getting-keyword-names) and using the class variable, like this: 
```
from robot.libraries.BuiltIn import BuiltIn
from robot.api.deco import keyword


class MyClassName(object):

    get_lib = BuiltIn().get_library_instance('Selenium2Library')

    def get_keyword_names(self):
        return [name for name in dir(self) if hasattr(getattr(self, name), 'robot_name')]

    @keyword
    def keyword_here(self):
        print self.get_lib
````
does not solve the problem. 

This is quite corner case, but should there be enhancement to the documentation or somewhere, to explain the problem and solution to it.

**Comment by pekkaklarck** [comment]
The example in the UG doesn't have this problem because it doesn't use property. With a property that can only be accessed if RF is running you get this error if you do

   for attr in dir(self):
       getattr(self, attr)

regardless do you use @keyword or not.

I did not mean using class variabless but accessing propertys via class like `getattr(MyClassName, attr)`. That returns you the property object itself without calling it.

**Comment by aaltat** [comment]
I understand, least I think so. Thanks from the feedback and advice.

**Comment by yurii-levchenko-chegg** [comment]
"Robot needs to call your get_keyword_names method to know what keywords the library implements" - is there a way to skip looking to parent modules?

**Comment by yurii-levchenko-chegg** [comment]
created .robot file, which executes code robot.libdoc.libdoc().
In this case RF execution context is visible.

P.S. The architecture of the RF requires us to find strange solutions for our projects.
