### ISSUE TITLE
Disable Github Wiki for robotframework

### ISSUE THREAD

**Issue by EdHurtig** [robotframework/robotframework#2347]
This is a total nit pick, I just thought I would suggest disabling the wiki on this repo as it seems to be unused.  That's all, Thanks for all the work you have put into this project! I look forward to trying it out!

[Settings Page](https://github.com/robotframework/robotframework/settings)
<img width="753" alt="screen shot 2016-03-23 at 1 04 57 pm" src="https://cloud.githubusercontent.com/assets/1410448/13999101/e906465e-f0f7-11e5-9485-5c438cf00829.png">

**Comment by pekkaklarck** [comment]
Done. I guess we kept wiki visible because we though it could be actually used for something. Can obviously be made visible again if we actually find some usage for it.
