### ISSUE TITLE
libs imported from libs not visible with BuiltIn.run_keyword* 

### ISSUE THREAD

**Issue by yahman72** [robotframework/robotframework#2348]
I'm experiencing rather weird behaviour:
In certain scenarios keywords from Libs that are imported by my python libs are not visible.

Tried this with RF 2.9.2 & 3.0 - both have the same problem.

__Steps to reproduce__
MyLib (Python):
- import OtherLib (e.g. AppiumLibrary)
- in the constructor import the OtherLib instance with BuiltIn's import_library()
<pre>
        self._bi = BuiltIn()
        self._bi.import_library("OtherLib")
        self._otherLibInstance = self._bi.get_library_instance("OtherLib")
</pre>

In MyLib use a KW from the OtherLib with
  + `self._otherLibInstance.example_kw()` and
  + `self._bi.run_keyword_and_ignore_error("example kw")`

Use MyLib from Test Suite: src/mytests/sub_dir1/suite.robot

I tried the following combinations:
__results with `self._bi.run_keyword_and_ignore_error("example kw")`__
<pre>
OK   pybot src/mytests/sub_dir1/ + suite.robot imports MyLib
NOK  pybot src/mytests/          + suite.robot imports MyLib
OK   pybot src/mytests/sub_dir1/ + suite.robot imports MyLib & OtherLib
OK   pybot src/mytests/          + suite.robot imports MyLib & OtherLib
</pre>
__results with `self._otherLibInstance.example_kw()`__
<pre>
OK   pybot src/mytests/sub_dir1/ + suite.robot imports MyLib
OK   pybot src/mytests/          + suite.robot imports MyLib
OK   pybot src/mytests/sub_dir1/ + suite.robot imports MyLib & OtherLib
OK   pybot src/mytests/          + suite.robot imports MyLib & OtherLib
</pre>

--> *__The NOK one fails with "No keyword with name 'example kw' found."__*

**Comment by yahman72** [comment]
Found one more combination that does not work, this time with multiple suites in one directory
__results with `self._bi.run_keyword_and_ignore_error("example kw")`__
<pre>
OK   pybot src/mytests/suite1.robot imports MyLib
NOK  pybot src/mytests/suite2.robot imports MyLib
NOK  pybot src/mytests/suite3.robot imports MyLib
OK   pybot src/mytests/suite1.robot imports MyLib & OtherLib
OK   pybot src/mytests/suite2.robot imports MyLib & OtherLib
NOK   pybot src/mytests/suite3.robot imports MyLib
</pre>

I.e. the suite that is executed first works fine, the subsequent ones fails with "No keyword with name 'example kw' found." error (unless they directly import the OtherLib).

Originally I thought this is because of suites in subdirectories, but it looks like that RF gets confused also when the suites are in the same directory.
Only the first executed suite has the correct reference to the "OtherLib", for all suqsequent suites it fails.

FYI: "OtherLib" has ``ROBOT_LIBRARY_SCOPE = 'GLOBAL'``

**Comment by pekkaklarck** [comment]
Could you create a simple executable example that we could use to reproduce the problem? Try to make it so that it doesn't require any external libraries that need to be installed separately but rather libs that you can package with the tests into a single zip file.

**Comment by yahman72** [comment]
here it is:
[rf_#2348.zip](https://github.com/robotframework/robotframework/files/233904/rf_.2348.zip)

Found out one more thing:
with ``ROBOT_LIBRARY_SCOPE = 'TEST SUITE'`` it works  but with ``ROBOT_LIBRARY_SCOPE = 'GLOBAL'`` it doesn't

<pre>
> pybot -P libs suites/
==============================================================================
Suites
==============================================================================
Suites.Suite1
==============================================================================
Test_01a                                                              problem_kw() called
Test_01a                                                              | PASS |
------------------------------------------------------------------------------
Test_02a                                                              problem_kw() called
Test_02a                                                              | PASS |
------------------------------------------------------------------------------
Suites.Suite1                                                         | PASS |
2 critical tests, 2 passed, 0 failed
2 tests total, 2 passed, 0 failed
==============================================================================
Suites.Suite2
==============================================================================
Test_01b                                                              problem_kw() called
Test_01b                                                              | PASS |
------------------------------------------------------------------------------
Test_02b                                                              | FAIL |
No keyword with name 'Problem Kw' found.
------------------------------------------------------------------------------
Suites.Suite2                                                         | FAIL |
2 critical tests, 1 passed, 1 failed
2 tests total, 1 passed, 1 failed
==============================================================================
Suites                                                                | FAIL |
4 critical tests, 3 passed, 1 failed
4 tests total, 3 passed, 1 failed
==============================================================================
</pre>

**Comment by pekkaklarck** [comment]
The problem occurs because `MyLib.__init__` is only called when the library is first imported by `Suite 1` and the side effect of importing `ProblemLib` thus only occurs then. If `MyLib` has other scope than `GLOBAL`, then `MyLib` is initialized each time it is imported.

Notice that `__init__` having this kind of side effects is not a good idea in general.
