### ISSUE TITLE
 unicode issue

### ISSUE THREAD

**Issue by zyklonwu** [robotframework/robotframework#2352]
RF will encode all parameters to unicode,  eg, passed {'productCodes': ['01010569','01010575']} will be encode to {u'productCodes': u"['01010569','01010575']"}.
the dict's value must be list,how to fix it?

**Comment by pekkaklarck** [comment]
Could you please clarify? An example would help.

**Comment by zyklonwu** [comment]
sorry,my english is not good
this is my method:
lib.py
def query(self,api,**kwargs):
  xxxx

RF
${result}=	 query prameter1 productCodes=['01010569','01010575']

{'productCodes': ['01010569','01010575']} will be encode to {u'productCodes': u"['01010569','01010575']"}.
how to fix it?

**Comment by vkosuri** [comment]
@zyklonwu this could solve your problem

``` Python
import json

class mydict(dict):
    def __str__(self):
        return json.dumps(self)
```

**Comment by pekkaklarck** [comment]
Don't worry about your English @zyklonwu. The problem you have is that all normal text you use in Robot Framework test data is interpreted by the framework to be just text. If you need an argument that contains something else, like a list, you need to create a variable that contains it. You could do that in the variable table or dynamically by having a keyword that returns a list. I don't want to start explaining this more thoroughly here in the issue tracker, but for example Robot Framework User Guide explains variables thoroughly. If you need more help, please ask on robotframework-users mailing list or some other support forum.

**Comment by zyklonwu** [comment]
@vkosuri @pekkaklarck  thank you very much.
