### ISSUE TITLE
Row Count keyword in DataBase Library returns -1

### ISSUE THREAD

**Issue by ctchef** [robotframework/robotframework#2354]
Hello Everyone,

Issue:
When I use the default DataBase Library (pyodbc) and run a direct SQL Query to fetch the Row Count using the "Row Count" keyword, it returns -1 as the output. Request your thoughts over this issue. 

Sample documentation:
${var2}	Row Count	select * from XXXDB.dbo.tblYYY where ID = 1100

Workaround that I tried:
I achieved the same using the "Query" keyword using Count (*) in my query, but that one returns a list which I need to convert to an integer for further use. So this is not that a great hack.

Note: 
I have to work this out using the default library first; only when it is impossible to achieve, I can request some other data base library, hence I haven't tried any other database library.

**Comment by pekkaklarck** [comment]
This issue doesn't seem to have anything to do with Robot Framework core. If there is a problem in a database library, please submit an issue to its own tracker.
