### ISSUE TITLE
RobotFramework 3.0 isn't able to import Selenium2Library on ElCapitan

### ISSUE THREAD

**Issue by VitoAlbano** [robotframework/robotframework#2355]
Hi, 

I've just updated the version of my robot framework installation from 2.9 to 3.0 and it seems that now the only way i'm able to run the tests is python -m robot testname.txt.

As per documentation i should be able to run the tests even via robot command line : robot testname.txt, unluckily i get this error whenever i try it : 

> Importing test library 'Selenium2Library' failed: ImportError: No module named selenium
> Traceback (most recent call last):
>   File "/Library/Python/2.7/site-packages/Selenium2Library/__init__.py", line 2, in <module>
>     from keywords import *
>   File "/Library/Python/2.7/site-packages/Selenium2Library/keywords/__init__.py", line 3, in <module>
>     from _browsermanagement import _BrowserManagementKeywords
>   File "/Library/Python/2.7/site-packages/Selenium2Library/keywords/_browsermanagement.py", line 4, in <module>
>     from selenium import webdriver
> PYTHONPATH:
>   /usr/local/bin
>   /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip
>   /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7
>   /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
>   /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
>   /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
>   /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python
>   /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
>   /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old
>   /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload
>   /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC
>   /Library/Python/2.7/site-packages

But only changing the command (python -m roboto testname.txt) the test works perfectly.

Is there something wrong with my installation or something that i need to update or is a proper bug relative to El Capitan OS (my version is 10.11.4)?

All the installation was taken via pip .

**Comment by HelioGuilherme66** [comment]
The first error we see, is:
Importing test library 'Selenium2Library' failed: ImportError: No module named selenium

There should be some problem with Selenium2Library installation.

You should test Robotframework with a smaller example (and not using external libraries).

**Comment by pekkaklarck** [comment]
I'm fairly certain that you have multiple Python installations with Robot Framework installed on your system. Running `robot` and `python -m robot` could then end up running different Robot versions.

**Comment by VitoAlbano** [comment]
@pekkaklarck  Thanks for the suggestion, the problem was due the fact that MAC Os come out whit his own python version. After a long uninstalling and re-installing, everything works fine now.

**Comment by agirwalkar** [comment]
@VitoAlbano could you please suggest me what installation/re-installation you did here?
