### ISSUE TITLE
Dynamic Library @keyword name alias ignored

### ISSUE THREAD

**Issue by Chaser** [robotframework/robotframework#2359]
Hello, I am experimenting with the Dynamic Library capability and found and issue where `robot framework` and `libdoc` ignore the aliasing.

I created the following class 

```
class DynamicLibraryTemplate(object):
    def keyword_that_should_not_be_exposed(self):
        print "keyword_that_should_not_be_exposed"
    
    @keyword
    def robot_framework_keyword_one(self):
        print "robot_framework_keyword_one"
    
    @keyword("robot_framework_keyword_aliased")
    def robot_framework_keyword_two(self):
        print "robot_framework_keyword_two"

    def get_keyword_names(self):
        return [name for name in dir(self) if hasattr(getattr(self, name), 'robot_name')]

    def run_keyword(self, name, args):
        print "Running keyword '%s' with arguments %s." % (name, args)

if __name__ == '__main__':
    dynamic_lib = DynamicLibraryTemplate()
    print dynamic_lib.get_keyword_names()
```

When calling `libdoc` I get the expected result
- Robot Framework Keyword One
- robot_framework_keyword_aliased

When the method `run_keyword` is added to the class `libdoc` and `Robot Framework` start to ignore the alias
```
def run_keyword(self, name, args):
        print "Running keyword '%s' with arguments %s." % (name, args)
```
 `libdoc` result:
- Robot Framework Keyword One
- Robot Framework Keyword Two

This issue was witnessed with Robot Framework 2.9.2 and 3.0

**Comment by pekkaklarck** [comment]
With dynamic libs Robot and Libdoc use whatever you return from `get_keyword_names`. It seems you always return the method name, not possible `robot_name` these methods have.

Notice that with dynamic libs Robot itself doesn't use `@keyword` for anything. It is used with the hybrid libs, though.

**Comment by Chaser** [comment]
Hello @pekkaklarck. Thanks for the quick response. 

I am still a little confused after reading
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#getting-keyword-names
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#using-a-custom-keyword-name

It is correct I always return the `actual` method name but `libdoc` does return the **aliased** method name when `run_keyword` **does not exist**

**Comment by pekkaklarck** [comment]
Without `run_kwyword` you have a hybrid lib. Docs related to this could be enhanced. Any ideas how?

**Comment by Chaser** [comment]
Hello again, I am picking up what you are saying now. Let me investigate a solution and see what I can do to help with documentation clarity. 

Thanks for your prompt assistance!

**Comment by pekkaklarck** [comment]
I close this issue because functionality works as expected. Please submit a separate issue if you see ways how the documentation could be enhanced.
