### ISSUE TITLE
Support custom timestamp format with `--TimestampOutputs` option

### ISSUE THREAD

**Issue by martino-jelli** [robotframework/robotframework#2361]
Hi,
--timestampoutputs option is great but unfortunately it doesn't consider milliseconds, would be possible to add the to the file name? I am running test is parallel and some time they start at the same second and this will cause some errors as bot test are trying to use the same file.

Thanks for all your great contribution!

**Comment by pekkaklarck** [comment]
For backwards compatibility reasons we cannot change the file name format. You can pretty easily create custom file names in a script and set them with `--log/--report/--output` options, but having an option to set a custom format would be even more convenient. Would you @martino-jelli or someone else be interested to provide a pull request implementing a new option like `--timestampoutputformat` to specify an alternative formatting using, for example, [strftime](http://strftime.org/) format?

**Comment by pekkaklarck** [comment]
Anyone interested to implement `--TimestampOutputFormat`? If not, we'll close this issue.

**Comment by lgc-sk** [comment]
What's the ETA and what is the level of difficulty?  I am interested in doing something.

**Comment by pekkaklarck** [comment]
More active RF 3.0.1 development is now starting and the initial plan is to get it released in June. There's most likely going to be RF 3.0.2 later this year so missing that deadline is not a huge issue.

I don't think implementing this is too complicated. Just need to add a new command line option and change the current `--TimeStampOutputs` functionality to use the specified format. Tests and docs obviously needed too.

**Comment by pekkaklarck** [comment]
I consider this pretty low priority because you can already now create a custom timestamp and pass it explicitly to `--log/--report/--output`. Because we've added a way to add a timestamp automatically, having a way to control the format would be nice, though.

**Comment by pekkaklarck** [comment]
No interest lately. Closing.
