### ISSUE TITLE
Drag And Drop doesn't support Evaluated local variables.

### ISSUE THREAD

**Issue by snky1987** [robotframework/robotframework#2362]
Received and error when I tried to execute Drag And Drop keyword with local variables that are the result of math calculation (using Evaluate keyword).

Error: "UnboundLocalError: local variable 'elements' referenced before assignment"

Code:
`User multiselects keyframes from frame number ${startFrameNumber} to ${endFrameNumber} of ${layerNumber} layer `
`${dragStartFrame}=  Evaluate  ${startFrameNumber}-1`
`${dragEndFrame}=  Evaluate  ${endFrameNumber}-1`
`Drag And Drop  ${dragStartFrame}  ${dragEndFrame}`

**Comment by Tattoo** [comment]
`Drag and drop` is not a keyword in any of the Robot Framework core libraries. Please report this issue to the library's maintainers instead.

**Comment by pekkaklarck** [comment]
@Tattoo is right that this tracker is for Robot Framework itself only. That said, it seems you problem is not with Drag And Drop keyword but in how use use Evaluate. My guess is that you end up evaluating an invalid expression. This tracker isn't the right place to debug such issues further, though. If you cannot figure out the problem yourself, please send a question to robotframework-users mailing list or other such support forum.
