### ISSUE TITLE
Add *.pyc as an accepted listener

### ISSUE THREAD

**Issue by mkorpela** [robotframework/robotframework#2364]
Helps when calling robot framework from script

**Comment by pekkaklarck** [comment]
Some questions:

1. This refers to cases where listeners are taken into use using a path like `example/path/Listener.pyc`, right? I guess having just the pyc file would be enough if, instead, `example/path` was in PYTHONPATH and just the module name `Listener` was used when taking the listener into use.

2. This should also work with libraries, pre-run modifiers, and everything else that can be imported using a path, shouldn't it? I think the same change to the `utils.importer.ByPathImporter` would handle all these cases.

3. Should we also accept `*$py.class` files produced by Jython? I guess so.

4. Should we allow `*.pyc` files only with CPython (and possibly with PyPy and IronPython if they support them) and `*$py.class` only with Jython? Or should we support all regardless the platform? In the latter case e.g. `*.pyc` files would always work if the original `*.py` files exist too, but imports would fail at least on Jython if they don't. That's also the easier implementation so I vote for that.

**Comment by mkorpela** [comment]
So the use case is based on my observation when trying to use __file__ constant to pass the module I was in as a listener to robot framework.. At that point I noticed that I couldn't do that as the execution file was .pyc file.

**Comment by pekkaklarck** [comment]
I see. It's pretty easy to drop the `c` at the end, though.

**Comment by pekkaklarck** [comment]
Use cases are pretty limited and there are non-trivial design decisions to be made. Closing.
