### ISSUE TITLE
Possibility to limit parsing of test case file to certain file type like `--extension robot`

### ISSUE THREAD

**Issue by mkorpela** [robotframework/robotframework#2365]
Html parsing is one of the most time consuming things in RF. Would be beneficial to have a way to totally ignore html files as RF has more preferable input types (such as *.robot)

**Comment by pekkaklarck** [comment]
Some design decisions to be made:

1. What would be a good name for a command line option to select tests?
2. Should it select files that are parsed or files that are ignored? Or do we need support for both?
3. Should files be selected solely based on the extension or should we support patterns like `*.robot`?

**Comment by mkorpela** [comment]
1. You could start with something odd and big `--strict-robot-format-only` and make a shorter option later? This way deprecation or changes would not really spoil the namespace of possible command line options.
2. I would prefer parsed. Whitelisting and not blacklisting.
3. I would prefer also just extensions. Downside is that you might have to implement the pattern later and possibly deprecate this option but I think it would be a bigger problem to make a more complex to use pattern paced solution now assuming we have correctly identified the valuable parsing problem here.

**Comment by pekkaklarck** [comment]
`--strict-robot-format-only` could only be used to parse only `robot` files. Something like `--extension robot` would allow using also `--extension txt`. Been thinking we could soonish start parsing only `robot` files by default, and this option could then be used to specify an alternative extension if needed.

I got a prototype of this functionality already implemented. Still not sure should the option be `--extension`, `--dataextension`, `--data`, `--dataformat`, `--format` or something else.

**Comment by pekkaklarck** [comment]
My current plan is to use `--format`.

**Comment by pekkaklarck** [comment]
And now this is done. Code review and especially testing would be appreciated. Should be pretty quick because I try to get RF 3.0.1 out still this year (Finnish time) and this was the last feature. Gotta run some acceptance tests and get some sleep first, though.

**Comment by pekkaklarck** [comment]
`--format` I used is a bit ambiguous. Need to think would `--extension` or `--filetype` be better. Also, there's probably only going to be RF 3.0.1 release candidate this year. No need to rush with the final release and better get some feedback from users before too.

**Comment by pekkaklarck** [comment]
Renamed `--format` to `--extension`. No other good short option was available so decided to keep using `-F`. I've been thinking we could deprecate `--escape` and that would free `-E` in the future.
