### ISSUE TITLE
Officially register Remote Protocol default port 8270

### ISSUE THREAD

**Issue by cjnewman** [robotframework/robotframework#2367]
The default port number (8270) for robot framework remote protocol is not registered. A port number can be registered by filling out this form:
http://www.iana.org/form/ports-services
Registering will allow traffic type to be identified correctly by network monitoring tools, and prevent conflicts with other services.

**Comment by pekkaklarck** [comment]
Interesting. I didn't know registering port numbers doesn't require more work than this. Do you have experience how much work this is in practice and how fast are requests processed?

**Comment by cjnewman** [comment]
I've done it before and don't recall it taking very long, although the form has changed a bit since I last used it. I believe requests are typically processed in a few days. It's helpful to have a published spec (as RF has), and helpful to answer the question about security implications thoughtfully. If you do something wrong in the form, that's not a big deal and can be corrected after a brief discussion with the expert reviewer.

**Comment by pekkaklarck** [comment]
OK, I try to get this done. If we get the port registered, that ought to be mentioned also in the docs.

**Comment by pekkaklarck** [comment]
Forgot about this, hand *really* busy autumn, and now have hurry to get RF 3.0.1 out still this year.

**Comment by cjnewman** [comment]
If you tell me the assignee name and email you want to own the TCP port number in a comment here, then I'm willing to fill out the rest of the registration on behalf of the project.

**Comment by pekkaklarck** [comment]
That would be awesome @cjnewman! If you need a real person, I guess it's best to use me: Pekka Klärck <peke@eliga.fi>. If an organization is OK, then Robot Framework Foundation <http://robotframework.org/foundation/> would probably be even better.

**Comment by cjnewman** [comment]
Request submitted; I will add a note here when registration is complete. I used myself as contact and Robot Framework Foundation <robotframework-foundation@googlegroups.com> as the assignee. The assignee has authority over the contact person if there's a disagreement.

**Comment by pekkaklarck** [comment]
Cleared the milestone as this isn't really RF version specific. Just need to add a note to the User Guide if we get an approval.

**Comment by cjnewman** [comment]
Port 8270 is now registered as the "robot-remote" port in the IANA registry:

http://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=8270

So you can now document that the port is registered.

**Comment by pekkaklarck** [comment]
\o/

Awesome! Need to mention this in the docs. Will add that to 3.0.2 scope.

**Comment by pekkaklarck** [comment]
8270 being registered by ANSI is now documented both in the User Guide and here: https://github.com/robotframework/RemoteInterface

I guess this issue can be closed. Thanks @cjnewman!

**Comment by cjnewman** [comment]
Please change ANSI to IANA in the docs.

The registering organization is IANA (Internet Assigned Number Authority), an NGO. ANSI is the American National Standards Institute and is unrelated to IANA. For more information see http://www.iana.org/about.

**Comment by pekkaklarck** [comment]
Sent from my mobile.

27.1.2017 10.11 ip. "cjnewman" <notifications@github.com> kirjoitti:

**Comment by pekkaklarck** [comment]
Oh, that's kind of a typo. I do know the difference between ANSi and IANA. Good catch and thanks for reporting!

**Comment by pekkaklarck** [comment]
I had originally written ANSI into the User Guide for some reason and copied parts of that text to the RemoteInterface project. Anyway, ought to be fixed now. Thanks again @cjnewman!
