### ISSUE TITLE
Test case with template should continue if keyword timeout occurs

### ISSUE THREAD

**Issue by piglesiasm** [robotframework/robotframework#2373]
Pekka Klärck told me that this works at is expected and told me to submit a bug report asking to implement it for RF 3.0.1 cause he guess it would make sense to allow the next iteration to execute if a 
keyword timeout exceeds.

Some explanation about the problem of how it works now.

My test is just invoke a keyword called CheckPlatform for diferent urls. Im
using that keyword as template, and that keyword has a fixed timeout.

If one of the test asociated to an especial url exceeds that timeout, the
test finish without executing next Urls. So i think it could be a particular problem with the variables of that test case execution, and i would like it will follow with next test case.

Some code for more details:
I use timeout in template, and cause error if one execution from Test that invoque exceeds timeout. 

-> not continue with text1b,text2b values.

```robotframework
*** Test Cases ***
test Timeout
    [Template]    Template1
    text1a    text2a
    text1b    text2b

*** Keywords ***
Template1
    [Arguments]    ${varA}    ${varB}
    [Timeout]    15 seconds
    Sleep    30 seconds
    log        ${varA}    ${varB}
```

**Comment by pekkaklarck** [comment]
Yeah, it would be better to continue from the next iteration if one iteration fails due to a keyword timeout. Test timeouts should nevertheless end the whole test. This shouldn't cause backwards compatibility issues and ought to thus be a safe change in RF 3.0.1. I consider this a bug and will look at fixing this myself.

See also somewhat related #2376.

**Comment by piglesiasm** [comment]
Another question related with this issue.

Seleniun by default takes an screenshot when error. In case of template
timeout exceeded, that capture fails:

*WARN Keyword 'Capture Page Screenshot' could not be run on failure:
Keyword timeout 2 minutes exceeded.*

bye!

2016-05-31 12:25 GMT+02:00 Pekka Klärck <notifications@github.com>:
