### ISSUE TITLE
Robot Framework 3.0 Resource File Does Not Exist

### ISSUE THREAD

**Issue by derekjmoo** [robotframework/robotframework#2374]
When attempting to run a test with robot 3.0 in pycharm I am encountering the error: [ ERROR ] Error in file. Resource file"xxx" does not exist.

The resource file's path appears to be correct from what I can see. 

I have tried adding the path as ../Resources/etc and Resources/etc but no joy.

Any help would be greatly appreciated.

![1](https://cloud.githubusercontent.com/assets/18514632/15320681/cec4fee0-1c29-11e6-948a-1ac51fd58278.png)

**Comment by pekkaklarck** [comment]
Resource file path is relative to the directory where the file you use it is. You are using path relative to the project root.
