### ISSUE TITLE
for loop with large range problem

### ISSUE THREAD

**Issue by alexeigo** [robotframework/robotframework#2375]
*** Test Cases ***
00 Test
    : FOR    ${counter}    IN RANGE    1000000000
    \    Log To Console    counter = ${counter}
    \    Exit For Loop If    '${counter}' == '10'
    Log To Console    done

This keeps running until it runs out of memory. It works fine for smaller range and exits on 10th iteration.

**Comment by pekkaklarck** [comment]
I'm not surprised that your example running billions of keywords runs out of memory. Notice that even if it would run successfully, you probably wouldn't be able to open the resulting log file. You can try getting more memory, but in general you should move logic needing to operate with such huge data sets into a library.
