### ISSUE TITLE
Log is not working

### ISSUE THREAD

**Issue by MHShaikh** [robotframework/robotframework#2379]
Hi Team,

I am using robotframework of java version(please find maven dependency below for the same). Actually when i am using Log keyword its not displaying anything on my console. Also, i tried with Log To Console and i get error as No keyword defined.

<dependency>
	<groupId>org.robotframework</groupId>
	<artifactId>robotframework</artifactId>
	<version>2.8.1</version>
</dependency>

Can anyone help me to do it?

**Comment by pekkaklarck** [comment]
`Log` keyword is designed to log only to the log file, not to the console, by default. `Log To Console` and `console` argument to `Log` are both new in RF 2.8.2:
http://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Log
