### ISSUE TITLE
KWs that take list varibles as arguments don't break when no arguments are passed

### ISSUE THREAD

**Issue by JohnCharitoudis** [robotframework/robotframework#2382]
The following test suite won't break with error "Keyword 'Print List Items' expected 1 argument, got 0.", but moreover it will be passed. Is this a known issue?  

*Using Robot Framework 2.8.4 (Python 2.7.3 on linux2)

```
*** Keywords ***
Print List Items
	[Arguments]  @{list}
	:FOR  ${item}  IN  @{list}
	\  Log  ${item}

*** Test Cases ***
TestListArguments
    Print List Items

```

**Comment by HelioGuilherme66** [comment]
I confirm the same behavior with Robot Framework 3.0 (Python 2.7.10 on linux2):
```
Starting test: Arg Bug.TestListArguments
20160531 10:33:02.167 : TRACE : Arguments: [ @{list}=[] ]
20160531 10:33:02.169 : TRACE : Return: None
Ending test:   Arg Bug.TestListArguments
```

**Comment by pekkaklarck** [comment]
This is the designed and documented behavior:
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#varargs-with-user-keywords
