### ISSUE TITLE
[ ERROR ] Taking listener 'MyListener' into use failed:  Listener 'MyListener' does not have mandatory 'ROBOT_LISTENER_API_VERSION' attribute

### ISSUE THREAD

**Issue by Tset-Noitamotua** [robotframework/robotframework#2383]
Getting an error while running a listener example from [RF Userguide (Version 3.0)](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#listener-examples)

Content of MyListener.py:
```python
import os.path
import tempfile


class PythonListener:
	ROBOT_LISTENER_API_VERSION = 2
	def __init__(self, filename='listen.txt'):
		outpath = os.path.join(tempfile.gettempdir(), filename)
		self.outfile = open(outpath, 'w')

	def start_suite(self, name, attrs):
		self.outfile.write("%s '%s'\n" % (name, attrs['doc']))

	def start_test(self, name, attrs):
		tags = ' '.join(attrs['tags'])
		self.outfile.write("- %s '%s' [ %s ] :: " % (name, attrs['doc'], tags))

	def end_test(self, name, attrs):
		if attrs['status'] == 'PASS':
			self.outfile.write('PASS\n')
		else:
			self.outfile.write('FAIL: %s\n' % attrs['message'])

	def end_suite(self, name, attrs):
		self.outfile.write('%s\n%s\n' % (attrs['status'], attrs['message']))

	def close(self):
		self.outfile.close()
```

Command to start test in TESTS folder:
```shell
robot --listener MyListener TESTS
```

Output:
```shell
$ robot --listener MyListener TESTS
[ ERROR ] Taking listener 'MyListener' into use failed: Listener 'MyListener' does not have mandatory 'ROBOT_LISTENER_API_VERSION' attribute.
==============================================================================
TESTS
...
```

**Comment by pekkaklarck** [comment]
The reason is that you take the module to use as a listener, not the class. Change the module (i.e. file) name to match the class name and Robot ought to realize that you want to use the class as a listener. Alternatively you could import the listener by including both the module and class name in the listener name. Please let us know if you see that related docs could be enhanced somehow.

**Comment by Tset-Noitamotua** [comment]
@pekkaklarck Thank you so much. Once again you brought me back on the right track. Did PR #2388 to enhance related docs.

**Comment by pekkaklarck** [comment]
Cool, thanks for the doc PR. I comment it separately.
