### ISSUE TITLE
Robotframwork changes None parameter to [0]

### ISSUE THREAD

**Issue by MaZa78** [robotframework/robotframework#2384]
RIDE 1.5 running on Python 2.7.9. 
RF robotframework-2.9.2-py2.7.egg-info

I have a test case like these:

${metric}	Set Suite Variable	${FALSE}
Sleep Device Time	2s	
Log	${metric}	---> THIS PRINTOUT **None** --- Everything is OK
Check log another file

Then I have a another file what is imported and there is keyword
Check log another file
Log	${metric} ---> THIS PRINTOUT **[0]** --- Everything is NOT OK --- Before it prints **None**

There is a test cases where I have check
Run Keyword if    ${metric}    and do something    ---> The problem is that now it is doing and it should not to do anything. Every test cases fails of that.

**Comment by pekkaklarck** [comment]
Please clarify.

**Comment by MaZa78** [comment]
TEST CASE NAME
${metric} Set Suite Variable ${FALSE}
Sleep Device Time 2s
Log ${metric} ---> THIS PRINTOUT None --- Everything is OK
Check log another file (this is keyword to another file)


THis another file name temp.txt
*** Keyword ***
Check log another file
Log ${metric} ---> THIS PRINTOUT [0] --- Everything is NOT OK --- Before it prints None

**Comment by pekkaklarck** [comment]
You are using Set Suite Variable wrong. Please look its docs for proper usage.
