### ISSUE TITLE
[enhancement] Could suite execution order to be selected

### ISSUE THREAD

**Issue by juhoarvid** [robotframework/robotframework#2385]
Hi,

If I run robot like
pybot -s helloworld.helloworld -s arraytest.arraytest -s funnytest.funny testsuites
Robot runs testsuites in alphabetic order. If I would like to run those e.g. with prioirty order (helloworld most important) it is not possible. 
Could this be somehow solved?

**Comment by pekkaklarck** [comment]
You can already use a custom prefix to specify the test suite sort order:
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#test-suite-name-and-documentation

Alternatively you can use pre-run modifiers to manipulate the data before execution as needed:
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#programmatic-modification-of-test-data

Being able to control the order from the command line directly would obviously be convenient, but I'm not sure how a custom order could be easily specified. Let us know if you have ideas how it should work and interest to implement such functionality.

**Comment by juhoarvid** [comment]
Could it simply be so that suites are executed in same order than descriped in commanline command?
pybot -s helloworld.helloworld -s arraytest.arraytest -s funnytest.funny testsuites
->
would run first "helloworld.helloworld", then "arraytest.arraytest", then "funnytest.funny" at the beginning of course "testsuites" if it has something to execute.

prefix option seems not to suite my intrest. Priority order is not allways known/same so would be nicer to decide in command line.

pre-run modifier could be better, but how with it I can check command line order of suites?

**Comment by pekkaklarck** [comment]
I don't think we can change the behavior of the existing `--suite (-s)` option. It is used to specify which suites to be executed and shouldn't do anything else. Adding a new option to control the order isn't a problem, the hard part is designing how the option actually should behave.

With pre-run modifier you can come up with your own way to specify the order so that it is passed as an argument to the modifier. Something like `--prerunmodifier SuiteSorter:suite1-suite3-suite2`.

Another alternative is passing suites individually from the command line like `robot suite1.robot suite2.robot suite2.robot`.

**Comment by juhoarvid** [comment]
I understood. I suppose --suite (-s) option change would be one I expected. If it cannot be done, I think we survive with prerunmodifier. 

"robot suite1.robot suite2.robot suite2.robot" solution is not suitable. We want execute __init__.robot from testsuites folder in order to create Global setup and teardown for all tests

**Comment by pekkaklarck** [comment]
I'm afraid to change existing functionality of `--suite`, but adding a separate option to control the execution order would be possible. The main problem is coming up with a way how to actually do that. There has, for example, been discussion about ordering tests earlier (#329) but nobody figured a good way to actually do that.

A great thing about pre-run modifiers is that they allow users to sort suites/tests as needed. If you come up with a good way to do it in a generic manner, please submit an issue--or reopen this one--to propose adding it as a built-in feature.

**Comment by ninjaniko** [comment]
I'm aware the thread is closed but in case anyone looks here for guidelines, I had great success using a listener and rearrange the list of TestSuites whenever a new parent suite is started:

def sortByPriority(self, arr = [])
  arr = str(arr)
  # Sort array based on your priorities [helloword, arraytest, funnytest]
  return arr

def start_suite(self, data, suite):
  data.suites = self.sortByPriority(data.suites)

It's possible to establish the priorities in the __init__ part of the listener, possibly based on an analysis of the suite.

**Comment by pekkaklarck** [comment]
Notice that you can also pre-run modifiers to accomplish that. With listeners you can do sorting, or whatever, based on earlier execution, though.

**Comment by skchethan** [comment]
> 
> 
> I'm aware the thread is closed but in case anyone looks here for guidelines, I had great success using a listener and rearrange the list of TestSuites whenever a new parent suite is started:
> 
> ```
> def sortByPriority(self, arr = [])
>   arr = str(arr)
>   # Sort array based on your priorities [helloword, arraytest, funnytest]
>   return arr
> ```
> 
> ```
> def start_suite(self, data, suite):
>   data.suites = self.sortByPriority(data.suites)
> ```
> 
> It's possible to establish the priorities in the **init** part of the listener, possibly based on an analysis of the suite.

can you share me the command yourun,

**Comment by ninjaniko** [comment]
@skchethan I've added a more detailed description at stackoverflow:
https://stackoverflow.com/a/58660309
