### ISSUE TITLE
Variables table is not logged in the report

### ISSUE THREAD

**Issue by rbovill** [robotframework/robotframework#2390]
No where in the reports output by pybot is the Variables Table logged.  This makes reading the reports difficult for those without access to the test scripts (e.g. those not in QA).  I think the Variables Table should be logged at the top of the given suite section of log.html, along with the Suite Setup and Teardown fields, in a similar collapsible pane.

**Comment by vkosuri** [comment]
I think this issue goes to https://github.com/mkorpela/pabot/issues

**Comment by pekkaklarck** [comment]
I don't think this is a good idea. Variables in the variable table can be overridden from the command line and dynamically during execution and thus the values shown might not be real values that are used. In addition to that, there are also other similarly global variable that affect execution, and showing all of them would add lot of noise for everyone. 

If you are interested in variable values, you can log them using `Log Variables`. Adding it support to limit the scope of the logged variables, as proposed by #2389, is a good idea.
