### ISSUE TITLE
How to call Capture Page Screenshot keyword within robot framework listener

### ISSUE THREAD

**Issue by jagadishchandran** [robotframework/robotframework#2394]
I want to capture page screen shot for failed test cases. I want this to be implemented in Robot framework listener (end_test). I have previously setting a suite variable from the listener (start_suite) like BuiltIn().set_suite_variable('${Password}', xxxxx) by importing (from robot.libraries.BuiltIn import BuiltIn). Now looking for similar solution to capture page screen shot.

**Comment by pekkaklarck** [comment]
This tracker is for bug reports and enhancement requests. General questions belong to other forums.
