### ISSUE TITLE
Guide how to set relative path to command line

### ISSUE THREAD

**Issue by luisxiaomai** [robotframework/robotframework#2400]
Hi,

I run robot test suite via command line like **"pybot  --variablefile  c:\testSuite\data\test1.yaml --suite test1.txt "**, how I can replace absolute variablefile path to a relative path which is based on test Suite? I tried **"--variablefile   ${CURDIR}\data\test1.yaml"**, but it doesn't work.

B.R.
Luis

**Comment by rama-bornfree** [comment]
Should work on windows

`pybot -V ..\\data\\test1.yaml`

or 

`pybot --variablefile ..\\data\\test1.yaml`

**Comment by luisxiaomai** [comment]
@rama-bornfree , it doesn't work.

**Comment by rainmanwy** [comment]
You may check RF guide.
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#taking-variable-files-into-use

**Comment by rama-bornfree** [comment]
cud u try with the changes as corrected in previous comment. It shd work

**Comment by luisxiaomai** [comment]
@rama-bornfree, thanks a lot. Below statement takes effect.
```
-V .\\data\\test1.yaml
```
