### ISSUE TITLE
Can't select value of picker wheel with appiumlibrary

### ISSUE THREAD

**Issue by Pangp0nd** [robotframework/robotframework#2401]
## The problem

Hello,
I have issue for select value picker wheel with appiumlibrary with robotframework. I want to select value for picker wheel but I can't set value for picker wheel .

## Environment

* Appium v1.5.3 
* OSX 10.11.5
* Node v6.2.1
* iPhone 6 (9.3)
* emulator/simulator
* appiumlibrary for robotframework.

## Details

**I use appiumlibrary with robotframework.** 

I want to select value from picker wheel but i can't do it .

**cause 1:** May be use worng keyword, i try to use input value (It Pass but value not change), click element ( message : did not match any elements ), tap and scoll  have same message click element.

**cause 2:** May be locator element wrong, i try locator by ios (copy from UIAutomation), class (use UIAPickerWheel).

Do you have other suggestions, please?
Thanks.

**Comment by pekkaklarck** [comment]
This tracker is for Robot Framework itself, not for libraries in its ecosystem. Additionally, this is a place for bug reports and enhancement requests. Questions should be sent to robotframework-users or other such forums.

**Comment by Pangp0nd** [comment]
I don't know. I’m really sorry.

**Comment by pekkaklarck** [comment]
No need to be sorry. I hope you find a solution for your problem.
