### ISSUE TITLE
Modify BuiltIn string helpers for cleaner output

### ISSUE THREAD

**Issue by jimni** [robotframework/robotframework#2403]
@pekkaklarck suggested the following:
> There are extra quotes around the list of items but that's due to the _get_string_msg helper unconditionally adding them. I guess the helper could get a new config parameters like quote_str1=True and quote_str2=True to control that, and the new keywords could call it like quote_str2=False. What do you think?
> 
> Somewhat related to this, I'd prefer the _get_string_msg to add a full stop at the end of the default message.

**Comment by jimni** [comment]
I would generally like to take up this challenge as soon as we resolve the details.

My main concern is that the product of this helper might be indirectly used in other libraries (both RF and third party). The unconditional addition of a full stop might break others' tests which might be considered backwards incompatible. 

Am I correct in my guess?
If so, we could add the full stop as a parameter, but would it still be worth the effort this way?

**Comment by pekkaklarck** [comment]
It's good to think about backwards compatibility, but in this case there shouldn't bee too big risks. We aren't changing the API, only making the error message a bit better. I think we should just add `.` at the end without making it configurable.

Notice also that internal changes like this don't really need an issue. An issue is needed if the topic needs to be listed on the release notes because they are partly generated based on issues with a certain milestone.

**Comment by jimni** [comment]
I see your point. Nonetheless, we needed a place to discuss this compatibility risk, didn't we?
If you don't mind, I will address this issue, hopefully, this week.

**Comment by pekkaklarck** [comment]
Yeah, talking about possible compatibility issues is important. Slack would probably be best place for such discussion although I haven't lately been too active there. Definitely no harm using the tracker either, but I'll close this issue anyway as we anyway have #2120 about the actual issue at hand and PR #2393 implementing it. Just submit a new PR once you get `_get_string_msg` enhanced and then update #2393.

This week I finally have time to actually concentrate on work and should be able to review PRs and participate discussion on Slack and elsewhere.
