### ISSUE TITLE
Set Test Message with overrides param

### ISSUE THREAD

**Issue by vkosuri** [robotframework/robotframework#2408]
I am using RF Version: 3.0

The current implementation test failures overrides `User Custom Set Test Message` http://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Set%20Test%20Message

Instead can we have an optional param `override`, which will give to user display custom message instead RF builtin test failure message or etc in Messages block

For e.g

``` Robot
Set Test Message   *HTML*<table style="max-width:100%; padding: 10px; text-align: left"><thead style="background-color:#FF5733;"><tr><td>URI</td><td>Request Data</td><td>Response Data</td><td>Expected</td><td>Result</td></tr></thead>
Set Test Message  <tr><td>One</td><td>Two</td><td>Test</td><td>Test</td>   append=yes   override=yes
```

**Comment by pekkaklarck** [comment]
Sorry for ignoring this issue for so long. It was buried under a pile of other issues during summer time when I didn't have much time to follow this tracker.

In my opinion it is important that failures are clearly visible and don't think earlier test messages should override them. Could you clarify your use case a little and explain why you'd like that to happen? Also, have you considered using [test documentation](http://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Set%20Test%20Documentation) for reporting general information you'd like to be more clearly visibly?

**Comment by vkosuri** [comment]
@pekkaklarck Apologies, totally forgot about this feature. I am trying to recollect this http://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Set%20Test%20Message

> but otherwise failures override messages set by this keyword. Notice that in teardown the message is available as a built-in variable ${TEST MESSAGE}.

I don't need RF custom failure message, i need my custom message instead. For example 

``` Robotframework
*** test cases ***
  mytest
    Set Test Message   *HTML*<table style="max-width:100%; padding: 10px; text-align: left"><thead style="background-color:#FF5733;"><tr><td>URI</td><td>Request Data</td><td>Response Data</td><td>Expected</td><td>Result</td></tr></thead>
    ${color} =  set variable  Red
    Run Keyword If  '${color}' == 'Red'  Set Test Message <tr><td>One</td><td>Two</td><td>Test</td><td>Test</td>   override=yes
```

**Comment by pekkaklarck** [comment]
I still believe the failure message should override possible earlier message. If you have more complex needs, I'd recommend having the logic in a library where you can easily construct the error message as you need yourself.

**Comment by vkosuri** [comment]
Thanks @pekkaklarck
