### ISSUE TITLE
tag "COLOR" does not work

### ISSUE THREAD

**Issue by rafale3** [robotframework/robotframework#2411]
Ver : Robot Framework 2.8.7 (Python 2.7.3 on linux2)
tag "COLOR" does not work

TC_3732726
    [Tags]    Color    SWPARK

--exclude COLOR
--test TC_3732726
With this configuration, TC should not be run but executed.

Curious thing is, If I do this, it also does not work.
--exclude COLOR
--exclude SWPARK
--test TC_3732726

But If I do this, it works. TC does not executed.
--exclude SWPARK
--test TC_3732726

**Comment by trogdor259** [comment]
when adding your tag in command line use lowercase. --exclude COLOR will be read as colOR because the operants (AND OR NOT) are always capitalized. If you use exclude color it should work.

**Comment by rafale3** [comment]
Agree. I also observed this.
[ ERROR ] Suite 'std fw copy ACMS old' contains no tests without tags 'COL OR ' or 'SWPARK' and named 'TC_3732726'.

**Comment by pekkaklarck** [comment]
Accidentally using upper case `OR`, `AND` or `NOT` in tag names on the command line causes surprising issues like this. Very well spotted by @trogdor259! Should we perhaps check could the code be enhanced so that it would give a warning if there are upper case letters around these special words?

**Comment by trogdor259** [comment]
I think that would be brilliant. It would help some of the people on my team who are using Robot for the first time.
