### ISSUE TITLE
Use .exe wrappers instead of .bat under Windows

### ISSUE THREAD

**Issue by alexandrul** [robotframework/robotframework#2415]
The issue is better explained here: http://paul-moores-notes.readthedocs.io/en/latest/wrappers.html#making-executable-commands-on-windows

**Comment by pekkaklarck** [comment]
This is a good idea and would probably avoid problems like #2529 and would also make it easy to support wheel distributions (#1734). The main problem is that we support altogether six different Python interpreters (Python 2 and 3, Jython, IronPython, PyPy 2 and 3) and we need to test do all of them support setup tools entry points that creating `.exe` launchers in Python requires. This is also so big change that we can only do it in a major release.

I target this initially to RF 3.1 but cannot make promises will it be included. It would be great if people interested about this could test how different interpreters support entry points.

**Comment by pekkaklarck** [comment]
The link to actually generating `exe`s in the doc linked in the original description is outdated. This one works (at least now): http://setuptools.readthedocs.io/en/latest/setuptools.html#automatic-script-creation

Already tested that after applying the following changes changes to `setup.py`

```diff
-    scripts      = SCRIPTS,
-    cmdclass     = {'install_scripts': custom_install_scripts}
+    entry_points={'console_scripts': [
+        'robot = robot.run:run_cli',
+        'rebot = robot.rebot:rebot_cli',
+    ]}
```

and changing `run_cli` and `rebot_cli` like 

```diff
-def run_cli(arguments, exit=True):
+def run_cli(arguments=None, exit=True):
+    if arguments is None:
+        arguments = sys.argv[1:]
```

seems to be all we need. Still need to test with Jython and IronPython, but we can make the above changes conditional if we encounter problems with these interpreters.

**Comment by pekkaklarck** [comment]
Installation scripts have been changed to create `*.exe` files on Windows and also Python scripts created elsewhere have changed. To test the installation before RF 3.1 alpha 1, you can install the latest code directly from GitHub:

    pip install https://github.com/robotframework/robotframework/archive/master.zip

**Comment by pekkaklarck** [comment]
A related change to start-up scripts was that only scripts like `pybot` aren't supported anymore (#2818). Without that change implementing this issue would have been harder as well.
