### ISSUE TITLE
Add `-A/--argumentfile` support in Testdoc

### ISSUE THREAD

**Issue by vkruoso** [robotframework/robotframework#2420]
Using testdoc seems the best choice to me when trying to have a preview of tests selected by robot on a certain situation. There is no runtime dependency that we must have to run it, and at the moment I can't trust the tests to have no consequences when importing their test libraries to use the dry run mode.

We are heavily using the `--argumentfile` option to select tests using `--test` and `--suite`. The problem is that testdoc does not support that option. I need to manually build the command line based on the argument files to call testdoc at this point.

It would also be cool to accept or ignore any robot/rebot options, so we can use the exact same files with testdoc. Do you think this is reasonable?

I can try looking into implementing this if you can provide some guidelines.

This is somewhat related to #1876.

**Comment by pekkaklarck** [comment]
First of all, sorry for ignoring this issue for so long. It was buried under a pile of other issues during summer time when I didn't have much time to follow this tracker.

Good news is that adding argument file support to Testdoc is is trivial. Just need to add `--argumentfile` into Testdoc's usage similarly as in Robot's and Rebot's usages and the custom argument parsing logic takes care of the rest. Well, should add a test for it too and perhaps mention it also in the User Guide.

This is so trivial that I can do it for 3.0.2 that I plan to release this week. Let me know if you'd like to help, though!

**Comment by pekkaklarck** [comment]
Ignoring Robot's option isn't, in my opinion, a good idea. It can easily mask errors and could cause problems if some of those options were later added to Testdoc.

**Comment by vkruoso** [comment]
That was really fast, thanks! Sorry I did not had the time to look into it.

**Comment by pekkaklarck** [comment]
Well, it took 6 months before I noticed this issue. =) Figured I could as well implement it since it was so trivial. The biggest problem was trying to understand why `--ArgumentFile` didn't work which lead to #2535.
