### ISSUE TITLE
Incorrect sentence under 3.5.3   Splitting logs of RobotFramework Guide

### ISSUE THREAD

**Issue by negimeena** [robotframework/robotframework#2422]
Saw the problem that "T" is missing from the from this line from documentation "
When the amount of **he** test cases increases,
I dont know if there is anyway i can fix it by myself.
![1error](https://cloud.githubusercontent.com/assets/20467152/17312294/a7056fa2-581f-11e6-9dca-a1213d69003b.PNG)

**Comment by negimeena** [comment]
Saw the problem that "T" is missing from the from this line from documentation "
When the amount of **he** test cases increases,
I dont know if there is anyway i can fix it by myself.

![1error](https://cloud.githubusercontent.com/assets/20467152/17312253/604f8a48-581f-11e6-8d97-d38207d68112.PNG)

**Comment by pekkaklarck** [comment]
First of all, sorry for ignoring this issue for so long. It was buried under a pile of other issues during summer time when I didn't have much time to follow this tracker.

Thanks for the report. I can fix the typo myself. If you want to fix such typos yourself, see `CONTRIBUTING.rst` file in the project root for instruction how to edit documentation, how to create pull requests, and so on.

**Comment by negimeena** [comment]
Thanks @pekkaklarck . I will raise a pull request next time. I guess pull request will be addressed quickly..!! :)
