### ISSUE TITLE
Traceback information output.xml

### ISSUE THREAD

**Issue by sirex** [robotframework/robotframework#2426]
When I run tests I get output in vim's [quickfix](http://vimdoc.sourceforge.net/htmldoc/quickfix.html) window, where I can jump between files in traceback.

With Python this works out of the box, some template languages like Django and [Jinja2](https://github.com/pallets/jinja/blob/master/jinja2/debug.py) have this feature.

But RobotFramework does not have it.

It would be really useful if `output.xml` would have traceback information about failure, so that I could jump directly to a `.robot` file where test failed and also could jump to other places if failure happened somewhere in resource file or in a library.

**Comment by pekkaklarck** [comment]
First of all, sorry for ignoring this issue for so long. It was buried under a pile of other issues during summer time when I didn't have much time to follow this tracker.

Tracebacks are logged using the debug level and can be enabled by running tests with `--loglevel DEBUG` option.
