### ISSUE TITLE
robot command not found if installing robotframework with pip --user flag

### ISSUE THREAD

**Issue by manycoding** [robotframework/robotframework#2430]
-    Version information

        robotframework 3.0
        Python 2.7.12
        Xubuntu 16.04
        pip 8.1.2
-    Steps to reproduce the problem

        Make sure robotframework is not installed
        install it with pip install robotframework --user
        run robot --version
-    Possible error message and traceback.

         /usr/bin/robot: No such file or directory
         bash: robot: command not found...

**Comment by pekkaklarck** [comment]
I'm fairly certain this is an issue with `PATH`. Where does `pip --user` install scripts? It definitely cannot install them to the system wide `/usr/bin`.

**Comment by manycoding** [comment]
It goes to $HOME/.local/bin

**Comment by pekkaklarck** [comment]
Do you have that in PATH?

**Comment by manycoding** [comment]
Yep, ~/.local/bin is in PATH

**Comment by pekkaklarck** [comment]
Is it before `/usr/bin`? Does running `~/.local/bin/robot` work?

**Comment by manycoding** [comment]
~/.local/bin is after /usr/local/bin
I removed robotframework, the soft link, installed it with --user again, closed all terminal windows, and I cannot reproduce it again. I can try it in another machine.

**Comment by pekkaklarck** [comment]
If you have `~/.local/bin` in `PATH` after system directories where you have `robot` installed, the system will naturally pick the one in a system directory. I think operating systems sometimes even cache script locations somehow, which means that the script later in `PATH` is not found even if you remove the script that's there first. This happens on my Linux Mint when I simply delete `robot` script:

```
peke@kone ~ $ robot --version
Robot Framework 3.0 (Python 3.4.3 on linux)
peke@kone ~ $ sudo rm /usr/local/bin/robot
[sudo] password for peke: 
peke@kone ~ $ robot --version
bash: /usr/local/bin/robot: Tiedostoa tai hakemistoa ei ole
```

That `Tiedostoa tai hakemistoa ei ole` is `File or directory does not exist` in Finnish. =)

**Comment by manycoding** [comment]
Are you suggesting it is a caching issue? Let me verify it on my Xubuntu machine, robot wasn't available there a few days for sure, after it was installed with --user.
Also I will verify if soft links are created or not.

**Comment by manycoding** [comment]
Finally looked in Xubuntu laptop, ~/.local/bin/ simply was not in PATH. I think it is a pip issue.
