### ISSUE TITLE
variable work Scope is different between 2.8.7 and  3.0.1

### ISSUE THREAD

**Issue by z1yuan** [robotframework/robotframework#2431]
hi,

I find that the variable work scope is not the same between 
Robot Framework 2.8.7 (Python 2.7.11 on win32)
and 
Robot Framework 3.0.1.dev20151231 (Python 2.7.11 on win32)

In 3.0.1 the following case will fail and report
testv                                                                                    | FAIL |
Variable '${a}' not found.

but such kind of case will pass in 2.8.7
testv                                                                 | PASS |

robot case:
*** Settings ***
Library           C:/Python27/Lib/site-packages/XXXX/connections/testlib.py

*** Test Cases ***
testv
    ${a}    test
    mytest

*** Keywords ***
mytest
    log    ${a}

python lib file:
def test():
    return abc()

class abc(object):
    def __init__(self):
        self.first = "first"
        self.second = "second"

I am assuming that the variable which has been created by python class, will not work as variable in test scope(it can't be recognized in user keyword anymore). Is this a bug or you decide to make variable work scope stricter? Since this will lead a lot of our test cases fail.

**Comment by pekkaklarck** [comment]
This change is by design and done already in RF 2.9. See issue #532 and RF 2.9 release notes for more details:
https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-2.9.rst#variables-no-longer-leak-to-lower-level-keywords

**Comment by z1yuan** [comment]
got it, thank you!
