### ISSUE TITLE
How to run robotframework on server ?

### ISSUE THREAD

**Issue by Pangp0nd** [robotframework/robotframework#2434]
How to run robotframework on server **without interface** ?

server os : ubuntu

Guide, Please.

**Comment by pekkaklarck** [comment]
This is an issue tracker for bug reports and enhancement requests. If you have general questions, please send them to robotframework-users mailing list or other such forums. If you are totally new to the framework, please study information at and linked from http://robotframework.org. We can also discuss about paid support if you are interested.
