### ISSUE TITLE
--splitlog help

### ISSUE THREAD

**Issue by saurabhkukade** [robotframework/robotframework#2442]
When we pass this --splitlog argument.. It supposed to split the HTML log file in pieces but I am just getting javascript files with some index attached to it. Isn't it supposed to break HTML file and it should give me separate HTML files? If there is any other way to do it then please tell.

**Comment by pekkaklarck** [comment]
Works as designed and documented:
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#splitting-logs
