### ISSUE TITLE
Keyword tagging

### ISSUE THREAD

**Issue by pacan1** [robotframework/robotframework#2445]
Is it possible to TAG all keywords with 1 tag? Instead of adding 
[Tag]    tagname

to each keyword? 
Thanks

**Comment by pekkaklarck** [comment]
No, that's not possible. I guess it would be useful in some cases, but it would also be pretty complicated to implement. If you are interested, please submit a separate enhancement request. Notice also that robotframework-users and other similar forums are recommended for questions. This tracker is for bug reports and enhancement requests.

**Comment by pacan1** [comment]
Thanks - will do
