### ISSUE TITLE
Allow temporary printing to console

### ISSUE THREAD

**Issue by emanlove** [robotframework/robotframework#2449]
It would be nice to be able to temporarily print to console or print in place. For example, I would like to have output like

```
================================================
My Verbose Test Cases
================================================

Started Noisy Test Case
```

and then over time have it print out

```
Started Noisy Test Case ... Doing setup
```

```
Started Noisy Test Case ... Logging In
```

```
Started Noisy Test Case ... Entering Data
```

```
Started Noisy Test Case ... Submitted
```

```
Started Noisy Test Case ... Validating Results
```

```
Started Noisy Test Case ... Completed (and I am happy)
```

and then ends up like

```
================================================
My Verbose Test Cases
================================================

Started Noisy Test Case ... Completed (and I am happy)         | PASS |
------------------------------------------------------------------------------
My Verbose Test Cases                                                           | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed
==============================================================================
Output:  C:\sandbox\tooloud\output.xml
Log:     C:\sandbox\tooloud\log.html
Report:  C:\sandbox\tooloud\report.html
```

Each of these would be a log keyword call; something like

``` RobotFramework
  Log    Entering Data    temporary=${True}
```

``` RobotFramework
  Log    Completed (and I am happy)\n    in-place=${False}
```

or some other flag ?!?

**Comment by pekkaklarck** [comment]
Log keyword already has `console` argument for this purpose:
http://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Log

Or did I get your usecase wrong?

**Comment by HelioGuilherme66** [comment]
I suppose Ed wants a real time messaging to console, showing only the current log entry which would be end in the final message. This is usually done sending a Carriage Return (CR) char, like '\\r', in the beginning of log message. The problem with this is when output is redirected to file/stream not a display.

**Comment by emanlove** [comment]
Sorry, I was sloppy above as that should have been more like

```RobotFramework
  Log    Entering Data    console=${True}    temporary=${True}
```

```RobotFramework
  Log    Completed (and I am happy)\n    console=${True}    in-place=${False}
```

The use case is thinking beyond printing to console but printing in place, like a [flip-book](https://en.wikipedia.org/wiki/Flip_book). So given the robot file

```Robotframework
*** Test Cases ***
Print In Place
    Log    Started Noisy Test Case ...    console=${True}
    Log    Doing setup    console=${True}
    Comment   ... Setup ...
    Log    Logging In    console=${True}
    Comment   ... Log in ...
    Log    Entering Data    console=${True}
    Comment   ...
    Log    Submitted    console=${True}
    Log    Validating Results    console=${True}
    Log    Completed (and I am happy)    console=${True}
```

the output is

```
==============================================================================
Console
==============================================================================
Print In Place                                                        
Started Noisy Test Case ...
.Doing setup
..Logging In
..Entering Data
..Submitted
.Validating Results
Print In Place                                                        .Completed
 (and I am happy)
Print In Place                                                        | PASS |
------------------------------------------------------------------------------
Console                                                               | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed
==============================================================================
Output:  c:\sandbox\output.xml
Log:     c:\sandbox\log.html
Report:  c:\sandbox\report.html
```

Instead I want to see (again more of a flip book and each one in outputted over time)

```
==============================================================================
Console
==============================================================================
Print In Place                                                        
Started Noisy Test Case ...
```

```
==============================================================================
Console
==============================================================================
Print In Place                                                        
Started Noisy Test Case ... .Doing setup
```

```
==============================================================================
Console
==============================================================================
Print In Place                                                        
Started Noisy Test Case ...  ..Logging In
```

```
==============================================================================
Console
==============================================================================
Print In Place                                                        
Started Noisy Test Case ...  ..Entering Data
```

```
==============================================================================
Console
==============================================================================
Print In Place                                                        
Started Noisy Test Case ...  ..Submitted
```

```
==============================================================================
Console
==============================================================================
Print In Place                                                        
Started Noisy Test Case ...  .Validating Results
```

```
==============================================================================
Console
==============================================================================
Print In Place                                                        
Started Noisy Test Case ... Completed (and I am happy)
```

```
==============================================================================
Console
==============================================================================
Print In Place                                                        
Started Noisy Test Case ...  Completed (and I am happy)
Print In Place                                                        | PASS |
------------------------------------------------------------------------------
Console                                                               | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed
==============================================================================
Output:  c:\sandbox\output.xml
Log:     c:\sandbox\log.html
Report:  c:\sandbox\report.html
```

**Comment by emanlove** [comment]
@HelioGuilherme66: Not just a carriage return but a 'back to beginning of buffer' character. [Sorry been a long time since I havbe done console printing. Sure there is a technical term for this...]

**Comment by emanlove** [comment]
[Researching] Looks like I am meaning flushing stdout ... [How do I write output in same place on the console?](http://stackoverflow.com/questions/517127/how-do-i-write-output-in-same-place-on-the-console).

I am thinking out load here but also asking the community would they find this helpful and the core-developers if you see any issues with this idea.

**Comment by pekkaklarck** [comment]
I see. I'm afraid this kind of logic requires so low level control that using Log for it is hard and/or requires pretty complicated data. I'd rather try implementing this in a custom library first and then see could Log (or Log To Console) be enhanced without making data overly complicated.

**Comment by aaltat** [comment]
I do like Ed idea, it would be useful in many cases

**Comment by pekkaklarck** [comment]
After thinking this a bit more, I would rather leave `Log` alone because it already has so many configuration options, but enhancing `Log To Console` would be possible. Do you have concrete ideas how it could be enhanced?

**Comment by emanlove** [comment]
I would add a parameter -- something like "temporary", "flash", "remove_on_next_log", or ??? -- that when set to true would clear the current output buffer on the next print to log/console. I am still looking for the right terminology for this type of "printing in place" and thus base the optional parameter's name so this is obvious; maybe overwrite or overwrite_buffer??? But I know it is not "flushing" as I was starting to think above. That is the act of forcing the print buffer to be printed. 

I was looking at the internals of the printing and starting to see how this may be implemented. What concerns me is making sure I have all the ways one can print covered so as not to cause issues with the comsole output. I would think this could work for ```Log``` as well and essentially the to-be-named optional parameter could be used on either keyword. If used on ```Log``` is would by default set that keywords **console** parameter to true.

**Comment by pekkaklarck** [comment]
You actually can accomplish this already, at least to some extend, by using `Log Console` with newlines (`\n`) and carriage returns (`\r`) in the test data. Try, for example, this:

```robotframework
*** Test Cases ***
Example
  Log to console    \nFOO    no_newline=True
  Sleep    1
  Log to console    \r------    no_newline=True
  Sleep    1
  Log to console    \rBAR
```

As you can see if you test the above, there's a problem that `\r` doesn't erase the earlier text but just moves the cursor to the beginning of the line. Thus you end up with `BAR---` and not with `BAR` that you might expect/want. A solution is adding enough spaces at the end of the string. That could be done manually e.g. like `${SPACE * 10}`, but perhaps enhancing `Log To Console` to accept the amount of padding as an optional argument would be better.

Even better than making the padding optional would be accepting the same [format specification](https://docs.python.org/3/library/string.html#formatspec) that Python's `format()` function accepts. It would allow configuring padding, alignment, etc. What do others think, should we add `format_spec` to `Log To Console` and perhaps also to `Log` keywords`? Should we even consider adding a separate keywords just for string formatting?

**Comment by pekkaklarck** [comment]
Notice that even with the `format_spec` enhancement I proposed above, logging to console like this wouldn't be too convenient. You would need to add a newline when you write the first message, add a carriage return on the following, omit adding newlines at the end except with the last message, and overwrite previous messages with enough spaces (with the challenge knowing how much is "enough"). All these could be solved by a custom library that uses the library listener interface to automatically add newlines or carriage returns depending on the test execution phase, and keeps track on how long messages were written to know how much spaces are needed to overwrite them. Such a library could also be clever enough to disable this kind of formatting when output is redirected into a file and it generally wouldn't work anyway.

**Comment by pekkaklarck** [comment]
Is this still relevant to someone? Anyone interested to make a more concrete proposal how this should work?

**Comment by pekkaklarck** [comment]
No comments by others than I since October. Closing.

**Comment by abhishpj** [comment]
update the logger.py file
def write(msg, level='INFO', html=False):
    """Writes the message to the log file using the given level.

    Valid log levels are ``TRACE``, ``DEBUG``, ``INFO`` (default since RF
    2.9.1), ``WARN``, and ``ERROR`` (new in RF 2.9). Additionally it is
    possible to use ``HTML`` pseudo log level that logs the message as HTML
    using the ``INFO`` level.

    Instead of using this method, it is generally better to use the level
    specific methods such as ``info`` and ``debug`` that have separate
    ``html`` argument to control the message format.
    """

    if EXECUTION_CONTEXTS.current is not None:
        librarylogger.write(msg, level, html)
        stalog.info(msg)
    else:
        logger = logging.getLogger("RobotFramework")
        stdout_handler = logging.StreamHandler(sys.stdout)
        file_handler = logging.FileHandler(filename='stability.log')
        handlers = [file_handler, stdout_handler]
        level = {'TRACE': logging.DEBUG // 2,
                 'DEBUG': logging.DEBUG,
                 'INFO': logging.INFO,
                 'HTML': logging.INFO,
                 'WARN': logging.WARN,
                 'ERROR': logging.ERROR}[level]
        logger.log(level, msg)
