### ISSUE TITLE
Robotframework will not kill the chromedriver instance if the test failed

### ISSUE THREAD

**Issue by rcabreros** [robotframework/robotframework#2452]
If a test fails, the chromedriver instance is still running in the background. It seems that Robotframework only kills the chromedriver instance when a test passes.

OS: Ubuntu 16.04
Browser: Chrome 53.0
Chromedriver Version: 2.24
RobotFramework Version: Robot Framework 3.0
Python Version: Python 2.7.12

![stillrunningchromedriverinbackground](https://cloud.githubusercontent.com/assets/9004410/18947621/7580f922-8666-11e6-8fc0-b199b16dd0bd.png)
![failedtestcase](https://cloud.githubusercontent.com/assets/9004410/18947625/79454a0e-8666-11e6-846f-a59383449737.png)

**Comment by pekkaklarck** [comment]
It's not Robot's responsibility to close the browser automatically. You need to do it yourself, preferably in test or suite teardown to ensure the action is run regardless test status. If you would like fully automatic closing, that would be a responsibility of the library you use and should be reported to that library's issue tracker.

**Comment by rcabreros** [comment]
Thanks @pekkaklarck !
