### ISSUE TITLE
Need information on integrating Robot framework with espresso android app automation

### ISSUE THREAD

**Issue by arunku2x** [robotframework/robotframework#2453]
Hi,

Is it possible to integrate Espresso Android App automation framework with Robot Framework? If yes then could you please provide me some pointers.

Regards,

Arun Kumar Saini

**Comment by chriscallan** [comment]
It sure doesn't seem like anyone has created the RF libraries to tie into the Espresso tools.  If there's enough interest, it might be a valuable 3rd party library to turn into a working project.

**Comment by Tattoo** [comment]
[Robot Framework user group](http://groups.google.com/group/robotframework-users) is a better place to ask these kinds of questions. This issue tracker is intended for bugs and feature requests.
