### ISSUE TITLE
User Guide: Clarify that with module libraries imported functions become keywords

### ISSUE THREAD

**Issue by aaltat** [robotframework/robotframework#2455]
I have problem with libdoc exposing imports also as keywords. When I have the following code, library.py file: 

``` python
from tempfile import mkstemp
from shutil import move


def do_something(path):
    fh, abs_path = mkstemp()
    move(abs_path, path)
```

When I run libdoc like this python -m robot.libdoc ./library.py list

Then I get this:

```
Do Something
Mkstemp
Move
```

By reading the [User Guide](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#what-methods-are-considered-keywords), it's not clear that Imported methods are keywords from Robot Framework point of view.

More detailed discussion in the user group: https://groups.google.com/forum/m/#!topic/robotframework-users/FpwDXN9Pmy0

**Comment by pekkaklarck** [comment]
@aaltat, can you review the enhanced docs?

**Comment by aaltat** [comment]
From a mobile screen content looks better. It's in a better order and doesn't not try to say too much in a one sentence. Left a line comment consideration

**Comment by pekkaklarck** [comment]
Cool. Closing.
