### ISSUE TITLE
In the log file which are being generated , can the source of it be changed ?

### ISSUE THREAD

**Issue by sayantan94** [robotframework/robotframework#2458]
Is it possible to change the source URL/ destination ?

**Comment by sayantan94** [comment]
![capture](https://cloud.githubusercontent.com/assets/10296940/19342345/13e92d4e-914f-11e6-9f3d-a3958e248c68.PNG)

In test suite changing the source , to a different path. Is it possible ?

**Comment by pekkaklarck** [comment]
There's no built-in way, but you can use pre-Rebot modifiers or otherwise post-process outputs after execution. See the User Guide for more details and use robotframework-users or other such forums if you need more help. This tracker is for bug reports and concrete enhancement request.
