### ISSUE TITLE
Dialogs: Opening dialogs fails with Python on Linux if mouse button hold down

### ISSUE THREAD

**Issue by MisterChild** [robotframework/robotframework#2460]
Hi guys,
we have an issue with dialogs lib. If we do a mouse action with holding the left button (i.e. resize/move a window), the grab_set() function fails. (in _initialize_dialog in dialogs_py.py)

As workaround I used a try/except construction from a forum.

```
    while 1: 
        try: 
            self.grab_set() 
            break 
        except TclError: 
            sys.exc_traceback = None 
            widget.after(100) 
```

As sys.exc_traceback is deprecated and shouldn't be used at all, I tried to remove the line _self.grab_set()_ completely. I couldn't see a different behavior on our system (Ubuntu, Python 2.7.6). 

Maybe you find a solution which works for all systems.

Thank you and best regards.

**Comment by pekkaklarck** [comment]
Could you clarify how you can reproduce this problem and what happens when it occurs? I tested that I can move and resize at least the `Pause Execution` dialog without any issues on Linux Mint with Python 2.7.6. Could you also link the forum where you found the workaround so that I can study the discussion myself.

**Comment by MisterChild** [comment]
Argh... Sorry for the bad description. The Error happens when I hold down the mouse button when robot tries to create a dialog. This happens when moving a window, marking text or simply hold down the mouse button.

Example:
https://youtu.be/LzMJn1FBrBU

Code:
```
Dialogs.Pause Execution    Press ok and grab another window to move it. Hold the window for 5s minimum.
sleep    5s
Dialogs.Pause Execution    If this window appears, everything is fine.
```

Link to forum:
http://computer-programming-forum.com/56-python/5da02bfc2acf9df2.htm

I simply surrounded the grab_set() with try/except as I don't feel so comfortable with "while 1:" loop and the grab is not necessary for us, as long as the focus is on that newly created windows.
```
        try: 
            self.grab_set()  
        except TclError:
            None
```

**Comment by pekkaklarck** [comment]
Ok, I was able to reproduce the problem with these instructions. Don't have time to test the fix at the moment, but I'll include this into 3.0.1 scope anyway.

**Comment by pekkaklarck** [comment]
I was able to reproduce this on Linux both with Python 2 and 3, but there were no problems on Windows. The proposed fix also fixed the problem. Decided to implement the final fix so that there's 30s timeout to avoid hanging if `grab_set` always fails.
