### ISSUE TITLE
robot libdoc not working for robotframework-difflibrary

### ISSUE THREAD

**Issue by vkosuri** [robotframework/robotframework#2462]
Hi,

Unable to generate libdoc for this keyword.py file https://github.com/bulkan/robotframework-difflibrary/blob/master/src/DiffLibrary/keywords.py

``` Bash
python -m robot.libdoc src/DiffLibrary/keywords.py doc/DiffLibrary.html
```
Could you please let me know did i missed any thing

**Comment by pekkaklarck** [comment]
It would help if you would tell how this fails.

**Comment by vkosuri** [comment]
@pekkaklarck I was pointing libdoc to keywords 
```Bash
python -m robot.libdoc src/DiffLibrary/keywords.py doc/DiffLibrary.html
```
but it has dependency in other file, thats the reason i couldn't get keywords html file. It is working with
```Bash
python -m robot.libdoc src/DiffLibrary doc/DiffLibrary.html
```

Thanks, It was documented here http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#libdoc
