### ISSUE TITLE
Telnet-Robot Framework

### ISSUE THREAD

**Issue by kapalata** [robotframework/robotframework#2465]
In GNS3, i configured 2 routers & 1 host & i am able to ping from each other. So how can i excute this setup in Robot framework using python script [using Telnet library]. Please suggest me iam new to this Robot Framework .

In Advance,
  Thank you

**Comment by Tattoo** [comment]
This issue tracker is for enhancements and bug reporting of Robot Framework. Your question is better suited for the [Robot Framework user group](http://groups.google.com/group/robotframework-users)

**Comment by kapalata** [comment]
Ok Tattoo, Thank you
