### ISSUE TITLE
Handling signals

### ISSUE THREAD

**Issue by BalakumaranS** [robotframework/robotframework#2466]
We are using Ansible to power up one of the Custom library written in Python. Ansible API has to have a callback registered to tap into the Results so in handling this i noticed that in Ansible code, they actually have a hard coded time.sleep(0.0001) if they dont see a result and check back again

the problem is this triggers a signal to Robot and it stops execution. Can someone enlighten me on the signal handling mechanism in Robot? Pls point me to something if a doc/note already exists

Traceback (most recent call last):
23:11:33   File "/**/**/**/local/lib/python2.7/site-packages/ansible-2.1.0.0-py2.7.egg/ansible/executor/process/result.py", line 109, in run
23:11:33     time.sleep(0.0001)
23:11:33   File "/**/***_/_/local/lib/python2.7/site-packages/robotframework-3.0-py2.7.egg/robot/running/signalhandler.py", line 43, in **call**
23:11:33     self._stop_execution_gracefully()
23:11:33   File "/*****/local/lib/python2.7/site-packages/robotframework-3.0-py2.7.egg/robot/running/signalhandler.py", line 46, in _stop_execution_gracefully
23:11:33     raise ExecutionFailed('Execution terminated by signal', exit=True)
23:11:33 ExecutionFailed: Execution terminated by signal
23:11:44 Execution forcefully stopped.

**Comment by pekkaklarck** [comment]
`time.sleep()` shouldn't itself send signals, but apparently some code sends `SIGINT` or `SIGTERM`. How Robot handles them is explained here:
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#stopping-test-execution-gracefully

**Comment by pekkaklarck** [comment]
Closing due to lack of new information.
