### ISSUE TITLE
Support for LIVE Html logging

### ISSUE THREAD

**Issue by arunku2x** [robotframework/robotframework#2468]
Hi,

Currently in Robot Framework, HTML logs/reports are created once test suite execution is complete. If test suite execution is aborted in between, then these logs/reports are not generated as output.xml file doesn't contain closing tags. I have few queries in this regard.

- Is it possible to have HTML logs/reports for executed test cases if test suite execution is aborted?
- Is it possible to have LIVE HTML logs/reports which contains the information about the test cases being executed?

I feel that these would be cool features to implement in Robot Framework.

Regards,

Arun Kumar Saini

**Comment by nottyo** [comment]
@arunku2x 
   If you want to see some '**LIVE**' log messages while your test cases being executed, you can add an option '_--debugfile_' or '_-b_' to your robotframework command line arguments.

On the first terminal

    cmd$touch test_debug.log
    cmd$tail -f test_debug.log

Open another terminal

    cmd$robot -d result --debugfile test_debug.log path/to/your/testcases

Here is my sample test case

    *** Settings ***
    Library    RequestsLibrary
    
    *** Test Cases ***
    Sample
        Create Session    github    https://api.github.com
        ${response}=    Get Request    github    /users/nottyo
        Should Be Equal As Strings    ${response.status_code}    200
        ${json}=    To Json    ${response.text}
        Should Be Equal As Strings    ${json['login']}    nottyo
    

Then look back to the first terminal, you'll see your '**LIVE**' log message like this

    ==============================================================================
    20161103 15:54:52.597 - INFO - + START SUITE: Robot Log [ ]
    ==============================================================================
    20161103 15:54:52.597 - INFO - +- START TEST: Sample [ ]
    ------------------------------------------------------------------------------
    20161103 15:54:52.598 - INFO - +-- START KW: RequestsLibrary.Create Session [ github | https://api.github.com ]
    20161103 15:54:52.598 - DEBUG - Creating session: github
    20161103 15:54:52.611 - DEBUG - Argument types are:
    <type 'bool'>
    20161103 15:54:52.612 - INFO - +-- END KW: RequestsLibrary.Create Session (13)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    20161103 15:54:52.612 - INFO - +-- START KW: RequestsLibrary.Get Request [ github | /users/nottyo ]
    20161103 15:54:53.590 - INFO - Starting new HTTPS connection (1): api.github.com
    20161103 15:54:57.646 - INFO - /Library/Python/2.7/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
      InsecureRequestWarning)
    20161103 15:54:57.647 - INFO - ${response} = <Response [200]>
    20161103 15:54:57.647 - INFO - +-- END KW: RequestsLibrary.Get Request (5035)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    20161103 15:54:57.648 - INFO - +-- START KW: BuiltIn.Should Be Equal As Strings [ ${response.status_code} | 200 ]
    20161103 15:54:57.649 - INFO - Argument types are:
    <type 'int'>
    <type 'unicode'>
    20161103 15:54:57.649 - INFO - +-- END KW: BuiltIn.Should Be Equal As Strings (1)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    20161103 15:54:57.650 - INFO - +-- START KW: RequestsLibrary.To Json [ ${response.text} ]
    20161103 15:54:57.651 - INFO - ${json} = {u'public_repos': 4, u'site_admin': False, u'subscriptions_url': u'https://api.github.com/users/nottyo/subscriptions', u'gravatar_id': u'', u'hireable': None, u'id': 8110002, u'followers_url': u'https...
    20161103 15:54:57.651 - INFO - +-- END KW: RequestsLibrary.To Json (1)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    20161103 15:54:57.652 - INFO - +-- START KW: BuiltIn.Should Be Equal As Strings [ ${json['login']} | nottyo ]
    20161103 15:54:57.653 - DEBUG - Argument types are:
    <type 'unicode'>
    <type 'unicode'>
    20161103 15:54:57.653 - INFO - +-- END KW: BuiltIn.Should Be Equal As Strings (1)
    ------------------------------------------------------------------------------
    20161103 15:54:57.654 - INFO - +- END TEST: Sample (5057)
    ------------------------------------------------------------------------------
    20161103 15:54:57.659 - INFO - + END SUITE: Robot Log (5197)
    ==============================================================================

**Comment by pekkaklarck** [comment]
What you propose isn't directly and exactly supported, but these solutions exist:

- [Fixml](https://bitbucket.org/robotframework/fixml) tool supports fixing broken output files.
- If you [stop execution gracefully](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#stopping-test-execution-gracefully) logs and reports are generated.
- You can use the already mentioned [debug files](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#debug-file) to monitor execution.
- The [listener interface](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#listener-interface) allows building custom solutions for following execution.

You can submit a more concrete proposal if the above solutions aren't enough. If the feature you need is not trivial, you should be prepared to implement it yourself or to pay someone else to implement it, though. Notice especially that generating Robot's normal logs/reports already during execution would require rewriting the whole log/report generation logic and is in practice unfeasible.

**Comment by vkruoso** [comment]
I've made a prototype in the past using the listener interface to send data about test execution to a mongodb server and render it live as a robot log.html file as the information comes in. I did not had the time to explore more and made a better implementation, but the initial results were interesting.

For reference here is the related code:
 - [vkruoso/robot-dashboard](https://github.com/vkruoso/robot-dashboard)
 - [vkruoso/robot-watchdog](https://github.com/vkruoso/robot-watchdog)

**Comment by arunku2x** [comment]
Thanks everyone for the pointers. I shall have a look at debug files (LIVE recording) and Fixml tool to fix broken output.xml file.
