### ISSUE TITLE
Keywords in test case files with dots in name do not have precedence over imported keywords

### ISSUE THREAD

**Issue by adam-wypych** [robotframework/robotframework#2475]
I created resource `res.robot` like below:
```robotframework
*** Keywords ***
ok
	Log	This is external res.ok
res.keyword
	Log	This is external res.res.keyword
```

Then I created test suite `Test.robot`, which inside has keywords `res.res.keyword` and `res.ok` like below:
```robotframework
*** Settings ***
Resource	res.robot

*** Test Cases ***
Test Check
	res.ok
	res.res.keyword
	
*** Keywords ***
res.ok
	Log	This is internal res.ok
res.res.keyword
	Log	This is internall res.res.keyword
```

According to documentation http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#handling-keywords-with-same-names _1. Created as a user keyword in the same file where it is used. These keywords have the highest priority and they are always used, even if there are other keywords with the same name elsewhere._

What I see in the output is that RF call resource file keywords instead of corresponding internal, so I got message from `res.robot` file:
```
20161118 09:32:03.353 : INFO : This is external res.ok
20161118 09:32:03.355 : INFO : This is external res.res.keyword
```

Is it expected behaviour or a new issue?

**Comment by pekkaklarck** [comment]
Yeah, the code and docs don't agree here. You can see the current code here:
https://github.com/robotframework/robotframework/blob/master/src/robot/running/namespace.py#L285

We could easily fix the code, but the change would be backwards incompatible. I doubt it would in practice cause issues, but it would anyway be a bit safer to do it in RF 3.1 than 3.0.1. Alternatively we could fix the docs, but this would would be a pretty strange special case. My current thinking is that we should fix this in 3.0.1 but I need to think a bit more about possible consequences.

**Comment by adam-wypych** [comment]
Ok, so as I understand the statement from documentation is what should be expected. Am I right?

I wonder if will be possible somewhere in the future to replace separation of libraries/resources from keyword names by different sign than dot, like i.e. C++ has this arrow sign `->`. 

Thanks for direct link to code where Robot Framework has implementation of search what to call.

**Comment by pekkaklarck** [comment]
Yeah, I would say that docs make more sense than the current functionality. We could document that if there is a dot in the name, we always first check is there a keyword that matches `parent_name.keyword_name`, but that sounds like a weird special case. Much easier if "local" keywords always have the highers priority.

I've also sometimes been thinking should we replace `.` as the marker between parent and keyword names but don't think that's worth the effort. Deprecating the current behavior would take lot of time and require lot of changes to tests everywhere. We should then also forbid using the new marker (e.g. `->` or `::`) in keyword names to make the usage really explicit.

**Comment by pekkaklarck** [comment]
After thinking this a bit more, I don't think there's any real backwards compatibility risk in the fix. If you currently have a keyword like `foo.bar` in a test case file and also resource `foo` with keyword `bar`, there's no way to call the keyword `foo.bar` in the test case file. I seriously doubt anyone would have such keyword, and even if someone would have, simply removing that unused keyword would fix the problem.

**Comment by pekkaklarck** [comment]
After implementing the change, our own tests showed that it can break tests using embedded arguments. For example, if we have keyword like `${embedded} args` in a resource file and use it like 'resource.Embedded args`, variable `${embedded}` nowadays gets value `Embedded` but after the change it would get `resource.Embedded`. This would be too big change in a minor version, and I'm not sure would that really make sense even in a major version. I guess the current implementation is actually the best one. We just need to document it better.

**Comment by pekkaklarck** [comment]
Scrap that! We can fix the original problem by always first looking does the test case file have the specified keyword. This can be done regardless does the keyword name have dot or not. If the test case file doesn't have such keyword, we can then first look from resources/libraries if the keyword has a dot. This implementation ought to cause no backwards compatibility problems and ought to also be in sync with the documentation.
