### ISSUE TITLE
Wish add `--retry [times]` parameter to re-run the failed test cases.

### ISSUE THREAD

**Issue by wywincl** [robotframework/robotframework#2477]
like this:

`robot --retry 3  test_suites`

it will try 3 times to run the failed test cases.

**Comment by pekkaklarck** [comment]
We've decided not to implement this kind of logic in the core. Configuring various possibilities related to re-execution in generic manner would be complicated and/or add lot of new command line options making the whole framework more comples. Better to implement re-trying and other such orchestration in external tools.
