### ISSUE TITLE
Built-in Automatic Variable ${SUITE NAME} doesn't hold the actual name of the suite

### ISSUE THREAD

**Issue by JohnCharitoudis** [robotframework/robotframework#2478]
Let's assume the following simple test case.

```
*** Test Cases ***
my_test_case
	Log  ${SUITE_NAME}
	Log  ${TEST_NAME}
```

Saving the above to a file with name "my_test_suite.robot" and executing it, will result to "My Test Suite" be printed in contrast to "my test suite" that someone would expect. Moreover, saving and executing the same test case but now from a file with name "my_Test_suite.robot" will have as a result that "my Test suite" is printed. I'm attaching (*remove the .txt extension) two log files from the respective reproduction of this issue. 

PS: Robot Framework 3.0 (Python 2.7.5 on linux2) was used.

[my_test_suite.html.txt](https://github.com/robotframework/robotframework/files/606456/my_test_suite.html.txt)
[my_Test_suite.html.txt](https://github.com/robotframework/robotframework/files/606458/my_Test_suite.html.txt)

**Comment by Tattoo** [comment]
This is a documented feature, not a bug
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#test-suite-name-and-documentation
