### ISSUE TITLE
windows python 3 + robot fresh install throws syntax error

### ISSUE THREAD

**Issue by ringmod** [robotframework/robotframework#2479]
win 7 enterprise :(

**1) install https://www.python.org/ftp/python/3.5.2/python-3.5.2.exe, click "add to path"
2) download robot from github: https://github.com/robotframework/robotframework
2a) can't use pip, firewalled
3) open powershell, python setup.py install**

creating c:\users\langbl\appdata\local\programs\python\python35-32\lib\site-packages\robotframework-3.0.1.dev20151231-py
3.5.egg
Extracting robotframework-3.0.1.dev20151231-py3.5.egg to c:\users\langbl\appdata\local\programs\python\python35-32\lib\s
ite-packages
  File "c:\users\langbl\appdata\local\programs\python\python35-32\lib\site-packages\robotframework-3.0.1.dev20151231-py3
.5.egg\robot\running\timeouts\ironpython.py", line 56
    raise self._error[0], self._error[1], self._error[2]
                        ^
SyntaxError: invalid syntax

  File "c:\users\langbl\appdata\local\programs\python\python35-32\lib\site-packages\robotframework-3.0.1.dev20151231-py3
.5.egg\robot\running\timeouts\jython.py", line 55
    raise self._error[0], self._error[1], self._error[2]
                        ^
SyntaxError: invalid syntax

**5) robot --version works.. some issue with ironpy not being checked properly prior to the copy?**

PS C:\Users\<redacted>\Downloads\robotframework-master> robot --version
Robot Framework 3.0.1.dev20151231 (Python 3.5.2 on win32)

**Comment by pekkaklarck** [comment]
Did I got it right that you copied the repository directly? That installation approach isn't supported. You can, instead, download the source distribution from PyPI <https://pypi.python.org/pypi/robotframework>. Easiest way to install it is using pip locally like `pip install robotframework-3.0.tar.gz`, but you can also extract it and use `python setup.py install` instead. If either of these fail, please open a new issue.
