### ISSUE TITLE
Custom logger regression on 3.0

### ISSUE THREAD

**Issue by vkruoso** [robotframework/robotframework#2481]
When registering a custom logger using the code below the final ``output.xml`` file differs from robot 2.9.2 to 3.0 regarding log messages generated in the ``start_keyword`` and ``end_keyword`` methods. This causes rebot to fail with the following message:

```
[ ERROR ] Reading XML source 'path/output.xml' failed: Incompatible XML element 'msg'.
```

Here is a test suite file and a custom logger that can be used to reproduce the issue:

```robot
*** Settings ***
Library   ./custom_logger.py


*** Test Case ***
This is a test case
    Log  testing
```
```python
from robot.api import logger
from robot.output.logger import LOGGER


class CustomLogger(object):

    def start_keyword(self, kw):
        logger.debug("Started keyword '%s'" % kw.name)

    def end_keyword(self, kw):
        logger.debug("Ended keyword '%s'" % kw.name)


# Register logger
custom_logger = CustomLogger()
LOGGER.register_logger(custom_logger)


def keyword():
    pass

```
Below you can find both ``output.xml`` files:
[output.zip](https://github.com/robotframework/robotframework/files/613174/output.zip)

**Comment by pekkaklarck** [comment]
`robot.output` isn't part of the public API and thus changes to it are possible and even likely in major releases. I actually hope I would have time to rewrite it altogether at some point. This is even documented in the module docs:
http://robot-framework.readthedocs.io/en/3.0/autodoc/robot.output.html

If the old behavior can be restored easily and without affecting other features, I won't have anything against it. Can you investigate this yourself?

An alternative solution would be implementing some public and supported API for your custom logging needs. The example you provided could probably be implemented using the listener API, but perhaps you have some more complicated needs.

**Comment by vkruoso** [comment]
I'll take a look if I can figure out the reason for this change, but we have fixed our problem by not logging things in robot with those two methods.

We are using a custom logger at our internal modules to log not only to robot itself, but also to a custom formatted file (always with TRACE level). Also, our custom logger inherits from the BackgroundLogger because we issue log messages from multiple threads. Does this scenario fits well with the listener interface?

**Comment by pekkaklarck** [comment]
Logging to external sources works fine from listeners but logging from threads isn't really supported. BackgroundLogger should just enhanced and integrated better with the core to support it.

**Comment by vkruoso** [comment]
Looks like the feature of writing to a file all TRACE messages can not be implemented with listeners in RF 3.0 because the ``log_message`` method obeys the log level in place. We run lots of telnet sessions and at the TRACE level we log all data on the wire. This give us a very good debugging method without making Robot's output files huge (we were getting 1.5Gb logs per run at some point).

**Comment by pekkaklarck** [comment]
Hmm, I think we actually changed listeners to honor the specified log level in RF 3.0. I don't have time now to find the relevant issue, but I think the motivation was avoiding to spent time to actually construct those messages. Making the listener log level configurable either in listeners themselves or from the command line could be considered.

**Comment by pekkaklarck** [comment]
Have you @vkruoso inspected could the problem with custom loggers be fixed somehow? That would be only a temporary solution, though, because these internal modules are going to change also in the future.

A better solution would be using the normal listener API. As already discussed, `log_message` nowadays only gets same messages that actually are logged, and `TRACE` messages are thus logged only if running tests with `--loglevel TRACE`. The reasoning behind this changes is explained in #2242. The change was marked backwards incompatible, with a note that we could make the listener log level configurable if needed. In practice that could be done adding an option like `--listenerloglevel TRACE` or, perhaps better, by allowing listeners to set the level with an attribute like `ROBOT_LISTENER_LOG_LEVEL = 'TRACE'`. This would require a separate issue, though.

**Comment by pekkaklarck** [comment]
No new info since 2016. Closing.
