### ISSUE TITLE
jquery-tmpl is deprecated

### ISSUE THREAD

**Issue by MartinBorg** [robotframework/robotframework#2482]
Its author recommends JsRender instead.
I assume, that it would be good to migrate.

**Comment by pekkaklarck** [comment]
What kind of concrete benefits would it give? Would you be interested to do it?

**Comment by MartinBorg** [comment]
I'm not sure about concrete benefits, maybe there are none. Probably bugs in jquery-tmpl are not fixed anymore, while hopefully in JsRender they get fixed.

Also, I'm about to package robotframework for Debian and will package jquery-tmpl if necessary. But JsRender is already packaged for Debian, so there would be a little bit less packaging and maintenance effort.

Anyway, if you don't see much reason in migrating, I'm totally fine with it.

**Comment by pekkaklarck** [comment]
We haven't encountered any bugs in jquery-tmpl so far and it has worked very well for us in general. We also have the version we use as part of our code base and have done one minor change related to escaping HTML content. Is there a reason you couldn't include that?

Package to Debian sounds awesome by the way!

**Comment by MartinBorg** [comment]
OK, then please just close this issue and I will try my (Debians!) luck with jquery-tmpl - and robotframework!

**Comment by MartinBorg** [comment]
I just saw, that I can close it myself...

**Comment by pekkaklarck** [comment]
Hopefully it's fine to use the vendored jquery-tmpl.

**Comment by MartinBorg** [comment]
What exactly is the change? Is there a patch in the robotframework sources? Is it an incompatible change?

**Comment by pekkaklarck** [comment]
See https://github.com/robotframework/robotframework/blob/master/src/robot/htmldata/lib/versions.txt and this commit referenced from there https://github.com/robotframework/robotframework/commit/b72ff951fa8e06b1c336bc8447228904d8fdcc5d

**Comment by MartinBorg** [comment]
OK. From my understanding, I can patch this in as a Debian patch, so that it works with robotframework.

**Comment by pekkaklarck** [comment]
Are you going to handle also other javascript libraries as external dependencies? I guess it would work, but I'm worried about version compatibility in the future. If we update the libs we use, the dependencies should be updated also. Is it against some Debian policies to include the libraries in Robot's sources like they are at normally?

**Comment by MartinBorg** [comment]
I understand your worries, because I have seen such incompatibility problems in the past. If such bugs arise, we need to fix them.

Debian tries to eliminate embedded code copies as good as possible, but there is no strict embargo. As with all libraries (C or Python or JavaScript or Java), Debian likes to maintain as few versions as possible. If multiple versions are necessary, we maintain them under different names, libsomething-1 and libsomething-2 (major version number becomes part of the name). If, in the future, robotframework would need a specific version of a library, and some other package another one, I would probably package both - or try to make changes that allows them to share the same version.

Rational: If a bug, maybe even a nasty security bug, is found in one library, Debian likes to be able to publish a fixed library quickly and be done. In the Windows or in the Android ecosystems, such a fix would involve upgrading multiple programs or apps.

Furthermore, Debian is very strict about building all software from its original source code ("preferred form of modification"). The *.min.js files are already compiled. They are hard to read, understand or patch. You managed to patch jquery-tmpl.min.js anyway, but this is not for the faint of heart :~)

For robotframework, I plan to only package jquery-tmpl separately, because it is used by another Debian package ("ikiwiki"), too. jQuery and jQuery-tablesorter are already packaged for Debian, so I will depend on them. JSXCompressor is, like tmpl, already used by another Debian package ("jsxgraph"), but I wonder, whether it is needed/used by robotframework anyway? jQuery.highlight can just be embedded in robotframework, because there is no other use in Debian yet. Still, I need to build it from its original source code.

**Comment by pekkaklarck** [comment]
Ok, I thought you'd have a policy like this. JSXCompressor is used for unzipping larger strings in log when needed. We zip them on Robot side to make logs smaller.
