### ISSUE TITLE
Copying model objects doesn't always work

### ISSUE THREAD

**Issue by krizex** [robotframework/robotframework#2483]
When I want to copy test case, robot framework throw an exception as below:
[ ERROR ] Executing model modifier 'RepeatTestCase' failed: TypeError: type object argument after * must be a sequence, not Timeout
Traceback (most recent call last):
 File "/home/dqian/dev/cafe/calix/src/caferobot/robotmodifier/prerunmodifier/repeatcase.py", line 27, in start_suite
   self._create_repeat_testcase(suite, case)
 File "/home/dqian/dev/cafe/calix/src/caferobot/robotmodifier/prerunmodifier/repeatcase.py", line 50, in _create_repeat_testcase
   new_case = copy.copy(case)
 File "/opt/ActivePython-2.7/lib/python2.7/copy.py", line 96, in copy
   return _reconstruct(x, rv, 0)
 File "/opt/ActivePython-2.7/lib/python2.7/copy.py", line 346, in _reconstruct
   setattr(y, key, value)
 File "/opt/ActivePython-2.7/lib/python2.7/site-packages/robot/utils/setter.py", line 34, in __set__
   setattr(instance, self.attr_name, self.method(instance, value))
 File "/opt/ActivePython-2.7/lib/python2.7/site-packages/robot/running/model.py", line 107, in timeout
   return Timeout(*timeout) if timeout else None

My execution environment is:
OS: CentOS 6.7
Python: 2.7
Robot framework: 3.0

I think it's necessary to enable `copy` and `deepcopy` feature with these model objects.

**Comment by pekkaklarck** [comment]
It can be considered a bug that `copy.copy(test)` fails. The actual problem show in the traceback seems to be related to timeouts that are handled somewhat inconsistently. Need to investigate more closely what's the best approach to fix this. PR #2484 has one alternative, but could also look at fixing timeouts.

Related to this, it would be great to have a convenience method `test.copy()` and possibly also `test.deepcopy()`. Even better if it would be possible to set same attributes as in `__init__` directly like `test.copy(name='New name', tags=['new', 'tags'])`.

**Comment by krizex** [comment]
The root cause of this issue is we cannot set the `timeout` attribute by a `Timeout` type argument. There may be more issues like this when we invoke `copy` with sub class of `ModelObject`. So I implement the `__setstate__` to make it compatible with `copy` module.
We can customize the `copy` method of these classes by calling the `copy.copy(self)` in the implementation.
For example:
    def copy(name='New name', tags=['new', 'tags']):
        cp = copy.copy(self)
        # modify the attribute
        cp.name = name
        cp.tags = tags

**Comment by pekkaklarck** [comment]
Ok. I need to look at `__setstate__` more closely when I have time. I don't generally want to merge code I don't understand fully.

**Comment by krizex** [comment]
It will be helpful to understand it by reading the source code of copy.copy and copy.deepcopy.





On Fri, Dec 23, 2016 at 5:03 AM +0800, "Pekka Klärck" <notifications@github.com> wrote:












Ok. I need to look at __setstate__ more closely when I have time. I don't generally want to merge code I don't understand fully.

**Comment by pekkaklarck** [comment]
It turned out copying wasn't totally broken, but at least runnable tests with timeouts couldn't be copied. Now that bug has been fixed (thanks for the PR @krizex!) and I also added explicit `copy` and `deepcopy` methods to model objects (and that has its own issue #2510). This issue can be considered done.
