### ISSUE TITLE
Include first logical line of keyword documentation in log

### ISSUE THREAD

**Issue by xanadiu** [robotframework/robotframework#2491]
As mentioned in #1009, documentation of keywords is not fully displayed in generated test output. It would be desirable to also fully include keyword documentation (i.e. multiline documentation) in the same manner as it is done with test case documentation.

Example:

<pre>
*** Keywords ***
Sign In
  [Arguments]  ${username}=${default_username}  ${password}=${default_password}
  [Documentation]  Loggt den Benutzer mit Name _username_ und Passwort _password_ ein. Werden _username_ oder _password_
  ...  nicht angegeben, werden die Anmeldedaten des Demo-Benutzers benutzt. Dieses Keyword schlägt fehl
  ...  wenn vor dem Login das Login-Formular nicht vorhanden ist und nach dem Login das Logout-Formular
  ...  nicht vorhanden ist.
</pre>

The screenshot is right now missing the second and further lines of documentation:

![4f5d557a-bdf6-11e6-9f11-bec30df268c7](https://cloud.githubusercontent.com/assets/23736160/21066770/a88cb37c-be67-11e6-93e3-b35eacd9a00c.png)

**Comment by pekkaklarck** [comment]
Not showing full keyword documentation is by design. It would increase log file size too much. Currently we only include the first row of the docs in logs, but that could be changed so that we show the first paragraph. The would include everything in the example above, but omit the second paragraph in this example:

```robotframework
*** Keywords ***
Example
    [Documentation] Only the first line in shown in logs nowadays. Possibly we could
    ...    change that and show the whole first paragraph, including this second line.
    ...
    ...    Here we are in the second paragraph. This wouldn't be shown in logs anyway.
```

Even this change is somewhat backwards incompatible can can increase log sizes, so I wouldn't like to add it in a minor release.

**Comment by pekkaklarck** [comment]
How do you @xanadiu like my proposal above? Any comments from others?

**Comment by HelioGuilherme66** [comment]
I have a Neutral position about this. I rarely need long documentation on logs. If the proposed change does not impact much log size or delay in processing or reading, then go for it.

**Comment by pekkaklarck** [comment]
Showing the whole first logical line ought to be safe. Lets do it.
