### ISSUE TITLE
Extended variables seem not to work with lists

### ISSUE THREAD

**Issue by gliviu** [robotframework/robotframework#2492]
According to docs: 
> Extended variable syntax works also in list variable context. If, for example, an object assigned to a variable ${EXTENDED} has an attribute attribute that contains a list as a value, it can be used as a list variable @{EXTENDED.attribute}.

This seems not to  be true according to following test
```
    ${items}  Create List    1  2  3
    ${res}  Create Dictionary    items=${items}
    Log  ${res.items}
    Log  ${res['items']}
    Append To List    ${res['items']}  5 6 7
    Append To List    ${res.items}  5 6 7
```

![image](https://cloud.githubusercontent.com/assets/8597812/21140010/801f01cc-c13e-11e6-8da7-edbbfc254ccf.png)

Both 'Log  ${res.items}' and 'Append To List    ${res.items}  5 6 7' should work

Tested with CPython and Robot 3.0

**Comment by pekkaklarck** [comment]
When you use `res.items`, you actually refer to `items()` method every dictionary has. `res['items']` always refers to key `items`. In general `res.key` works only whem `key` doesn't match normal dictionary attribute.

**Comment by gliviu** [comment]
Thanks. That was clarified !!
