### ISSUE TITLE
Read Argument Supplied Include/exclude Tags

### ISSUE THREAD

**Issue by serhatbolsu** [robotframework/robotframework#2493]
Hello ,I am facing an issue that I could not find an answer with current feature set:

In real example: I have mobile test cases which include "tablet" test cases. I would like to run only "tablet" test cases so I give ` --include  tablet` as argument.
- I would like to understand if this is an "tablet" test run. So I could do something like this:
```robotframework
${status}    Run Keyword and Return Status    Should Contain    @{TAGS}   tablet
# do something if ${status} is True
```
- However there is no "@{TAGS}" that can read argument given tags. 
- If there would be a keyword that return either "arguments" or include/exclute"'d arguments, that would be a good solution.

Best regards,
Serhat

**Comment by pekkaklarck** [comment]
See built-in variables in Robot Framework User Guide:
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html

**Comment by serhatbolsu** [comment]
@pekkaklarck Built in variables, more specifically `@{TAGS}` do not include what user is selected using arguments. So maybe I was not able to explain the point here. 

I would like to know what is in `--arguments` inside `--include and --exclude`

**Comment by pekkaklarck** [comment]
I see. I though you tried using `@{TAGS}` when the variable is actually `@{TEST TAGS}`.

Information supplied with `--include` and `--exclude` isn't directly available. You can see all the command line options by accessing `sys.argv`, but then you need to handle different variants like `--exclude vs. -e` yourself.

There have been also some other requests to make the options used when starting execution available. I guess that would be a generally useful feature, but it's not exactly trivial to implement. I've been thinking about refactoring/rewriting internal option handling in general, though, and this could be done at the same time. If you think it would be important, please submit a new general issue about that. There probably should be a programmatic API that libraries could use, but there could also be a variable like `${OPTIONS}` that allows accessing individual options like `${OPTIONS.include}` or `${OPTIONS.dryrun}`.
