### ISSUE TITLE
HTML Creation omitting jQuery code in log.html

### ISSUE THREAD

**Issue by ryanceresani** [robotframework/robotframework#2499]
Hello. Been having this issue with version 3.0 and have not been able to find help or anyone else asking about the same issue. Is this in fact a bug? When trying to view a log.html file, it displays only a blank white screen and the browser console throws an "Uncaught ReferenceError: jQuery is not defined"

Comparing an older working log.html to a current non-working log, the broken HTML is missing code from the following 3 files in robot\htmldata\lib

jsxcompressor.min.js
jquery.min.js
jquery.tablesorter.min.js

Each is a single enormous function call which is why they are omitted.

Copying and pasting them into the non-working html file allows it to open with all of its actual result data. 

This occurs with both default output creation and using rebot to generate reports.

**Comment by pekkaklarck** [comment]
This definitely shouldn't happen with the normal installation. How did you install and where to you run tests?

**Comment by ryanceresani** [comment]
We had 2 different install methods yield the same issue, 1 was installed using PIP the conventional way, the other installing from source. The robot folder is located in the location that the test will be run.  The tests are used with Sikuli and thus are interpreted by Jython. A modified jybot.bat had to be created to tie in Sikuli. 

`@echo on
setlocal
set ROBOT_HOME=%~dp0
set JYTHON_HOME=%ROBOT_HOME%
set SIKULIX_HOME=%ROBOT_HOME%
REM echo %CLASSPATH%

set CLASSPATH=%SIKULIX_HOME%sikulixapi.jar;C:\Python27\;C:\Python27\Scripts\;C:\jython2.7.0\bin\;C:\jython2.7.0\lib\;C:\ProgramData\Oracle\Java\javapath\

REM;%CLASSPATH%
set JYTHONPATH=%SIKULIX_HOME%sikulixapi.jar\Lib

javaw -cp %JYTHON_HOME%jython-standalone-2.7.0.jar;% org.python.util.jython ^
    %ROBOT_HOME%robot\run.py ^
    --pythonpath=%ROBOT_HOME%program.sikuli ^
%*
endlocal `


I ran a compare htmldata folder of the 2.9.2 version and 3.0 version and there is some minor differences and an entire extra folder in the 2.9.2 one. Not sure if this is related or just part of the 3.0 update. 

The logs were working well originally until recently and actually never worked for the person installing with PIP (about a month ago)

**Comment by pekkaklarck** [comment]
The way you run tests with standalone Jython looks somewhat complicated so it could be related to that. Nobody else has been reporting this and RF 3.0 has been out for a year, so I'm fairly certain something funny is happening in your environment.

**Comment by ryanceresani** [comment]
Thank you Pekka! I appreciate the fast responses. I guess this issue can be closed since it is something specific on our part. 

Would you have any insight into the part of the output creation that handles inserting the jQuery functions? This is strangely the only thing that appears to be amiss with any part of Robot for us. 

Thanks again!

**Comment by pekkaklarck** [comment]
I know how that code works but I have absolute no clue why it won't work in your environment.

**Comment by ryanceresani** [comment]
Pekka, it appears that at some point during the deployment or through our source control software, those 3 files are being stripped on the testing machines. Thank you for the support. We should be able to solve it from here.

Thanks again.

**Comment by pekkaklarck** [comment]
Great that you got it sorted out!

**Comment by ryanceresani** [comment]
Thank you for your help and the great software!
