### ISSUE TITLE
Checking if a Listener is already registered.

### ISSUE THREAD

**Issue by kootstra** [robotframework/robotframework#2503]
The Allure Report adapter I'm working on is based on a Listener and a Library that spawns the listener. The pure Listener is started through the command line argument and the second is through the Library import in the Robot file.

The challenge I'm facing is when both options have been applied. In this case two listeners are active and this results in two files. Though it's an easy fix, remove the Library declaration, I'd like to prevent it by checking if the Allure Listener is already active in the Library initialization. Is there a way to do this? 

In the source code I see a few references, but nothing that stands out as clear way of accessing the Listener registry and what attributes/methods are then available.

**Comment by pekkaklarck** [comment]
There's no direct way to accomplish this via Robot API. Probably you could do it somehow, but you'd most likely need to use internal APIs that are not stable between (major) versions. Easiest solution you could do is using a class level attribute that you increment or modify otherwise when instances are created. This is so simple that I doubt creating a public API to access registered listeners makes sense.

**Comment by kootstra** [comment]
Your suggestion sparked the idea to use set a Robot Global variable using `BuiltIn().set_global_variable('${ListenerActive}', True)`. This variable I then read during the initialisation of the Library `BuiltIn().get_variable_value('${ListenerActive}', False)`. Using this boolean I then decide to initialize the Library Listener or not. This way I've been able to prevent the creation of duplicate log files.

It appears to me that the Listeners are processed in sequence of their initialisation. That would mean the Global Listener is initialised before the Library one and allows me to set a variable just before the Library are loaded. What do you think? I've checked this while running Robot and Pabot and all appears to be well.
