### ISSUE TITLE
Use ROBOT_OPTIONS to run a listener is failing

### ISSUE THREAD

**Issue by oca159** [robotframework/robotframework#2516]
I am using RobotFramework on windows 8.1.
I am trying to specify a listener in this environment variable, so I tried with the next command on the cmd:

**set ROBOT_OPTIONS="--listener Listeners/SomeListener.py"**

After that, I reopen my cmd and I tried to run robot:

**robot Example.robot**

But I am receiving the following error:

**[ ERROR ] option --listener listeners/somelistener.py not recognized**

**Try --help for usage information.**

I also tried using the backslash instead of forward slash when I defined the path to the Listener but it still not work.

Any Ideas?

Sorry if I have grammar errors, English is not my native language.

Thanks.

EDIT1: I defined the environment variable from the windows GUI and all is working now.

I will close this issue, sorry.

**Comment by pekkaklarck** [comment]
On the CLI it ought to work without quotes:

     set ROBOT_OPTIONS=--listener Listeners/SomeListener.py

**Comment by oca159** [comment]
Thanks  @pekkaklarck I will try it.
