### ISSUE TITLE
Test case optimization in Robot framework

### ISSUE THREAD

**Issue by revathyvarma** [robotframework/robotframework#2519]
Can any one please let me know if test case optimization is possible in robot framework.
As in..We have a set of manual test cases in a test case optimization tool.Can we feed those test cases into Robot framework?

**Comment by laurentbristiel** [comment]
Could you be more detailed about what you are trying to do? Like explaining/naming the different tools and the workflow you would like to achieve.

**Comment by pekkaklarck** [comment]
This kind of questions are best sent to robotframework-users mailing list or other such forums. You would need to include a bit more details about what you try to accomplish to get any valid answers too.
