### ISSUE TITLE
json content when passed in delete request changes the format to a different content

### ISSUE THREAD

**Issue by swarupiyer** [robotframework/robotframework#2522]
When the JSON content is generated and sent in the delete request the content is modified to a different format as shown below

Generated json payload using "To Json" command is:
	${replStr} = **{u'device': u'9e2c137a-cd2c-4882-a509-05f4899ca0b6', u'share': u'10d58e5e-3e7c-45ec-bca0-01e079e593e5'}**
But when the request is formed:
alias=url, uri=/api/v1/share-assets/share-pool, **data=device=9e2c137a-cd2c-4882-a509-05f4899ca0b6&share=10d58e5e-3e7c-45ec-bca0-01e079e593e5**,                     headers={u'Accept': u'application/json', u'Content-Type': u'application/json', u'Authorization': u' Bearer DoJYMEZlA1zGxhdjfVk4j8t9y9Qj7Nq0V06VJjeMr42EGQdwF5iMJjg3-TYbMYq5r0XIlbdcm-h8SWZYd5iI31R-f_WdYVjrTaxoPyehcvWqC7vVBwKlyqX8PXj8jQAsdmLHZjhdW8izHO6gO_KOgAz7hxNN1S2-W7akY95H-Dv2_XVHBpQSxjrWLRcUjOBfkdhA5i3_rmHWuh9L0J9ocJOpz4BUXQpCQBat1KphdQ7LXwqvA'}, allow_redirects=True 

pybot --version
Robot Framework 2.9.1 (Python 2.7.6 on linux2)

**Comment by vkruoso** [comment]
Are you using the ``RequestsLibrary`` library to issue your request? If positive, the docs states that the data parameter can be a dictionary or a binary data (check it [here](http://bulkan.github.io/robotframework-requests/)). Maybe you are not passing the JSON string?

Please provide more details. Anyway, it does not look like a RobotFramework issue.

**Comment by swarupiyer** [comment]
Yes, I'm using Request Library and I'm sharing a screen-shot of the data
that was processed. I'm converting the payload to Json format and passing
it to delete request.
This workis perfectly fine for Post and Put request but in case of Delete
Request. the format of the data is getting modified while sending the
request.
 [image: Inline images 1]

**Comment by pekkaklarck** [comment]
Doesn't seem to be related to Robot Framework core. Please submit this issue to relevant issue tracker or ask a question on robotframework-users mailing list or other such forum.

**Comment by swarupiyer** [comment]
I verified the function(delete Request) :
it contains the line: data = self._utf8_urlencode(data)
I had put logger.info to check the data conversion and below are change in the data format.
===============================================================
Delete Request- data before conversion: {u'assetuuid': u'61b82b2d-bb67-4b42-9ab8-cf602e733511', u'sharePoolUUID': u'b2be05b2-ad2d-4b92-9dd0-411fafaf4229'}	
================================================================
Delete Request- data after conversion: assetuuid=61b82b2d-bb67-4b42-9ab8-cf602e733511&sharePoolUUID=b2be05b2-ad2d-4b92-9dd0-411fafaf4229
========================================
urlencode is removing the flowerbraces.
I observed that in other functions like Post Request we use 
1. data = self._format_data_according_to_header(data,header)
Is there a specific reason as to why the same was not used for delete Request?
