### ISSUE TITLE
Installation using pip fails with IronPython

### ISSUE THREAD

**Issue by rkommine** [robotframework/robotframework#2527]
Hi,

I am trying to install Robotframework for Jython & Iron Python as mentioned in the Robotframework userguide 

http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#installing-pip-for-jython

But I am facing the below error:
```
Administrator@Testwin1 ~
$ ipy -X:Frames -m ensurepip
Ignoring indexes: https://pypi.python.org/simple
Collecting setuptools
Collecting pip
Installing collected packages: setuptools, pip
Successfully installed pip-8.1.1 setuptools-20.10.1

Administrator@Testwin1 ~
$ ipy -X:Frames -m pip install robotframework
Collecting robotframework
C:\bin\IronPython2.7\Lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py:1: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  from __future__ import absolute_import
  Could not fetch URL https://pypi.python.org/simple/robotframework/: There was a problem confirming the ssl certificate: [Errno errors while validating certificate chain: ] RemoteCertificateNameMismatch - skipping
  Could not find a version that satisfies the requirement robotframework (from versions: )
No matching distribution found for robotframework
```

Could you please let me know is this expected or robotframework with python is sufficient to execute test cases implemented using java & C#?

Regards,
Ramakrishna

**Comment by pekkaklarck** [comment]
This seems to be an IronPython issue. I tested that pip worked in my old IronPython 2.7.5 installation with pip 1.5.6, but after upgrading pip I couldn't use pip for anything. After that installed IronPython 2.7.7 and faced another problem. I reported the problem I encountered as IronLanguages/main#1572 and there's also IronLanguages/main#1570 about pip problems.

What problems you got with Jython?

**Comment by pekkaklarck** [comment]
Until pip on IronPython is fixed, a workaround is doing [old-school source installation](https://github.com/robotframework/robotframework/blob/master/INSTALL.rst#installing-from-source) with `ipy setup.py install`.

I keep this issue open although this issue isn't in Robot itself. This way others facing the issue can see that others have encountered the same problem and can use the above workaround. I'll also remove the reference to Jython in the issue title. Please submit a separate issue if you encounter problems with Jython installation too.

**Comment by pekkaklarck** [comment]
Planning to start providing source distributions in zip format to ease extracting them manually without pip on Windows. See #2542 for details.

**Comment by rkommine** [comment]
Hi Pekka,

Apologize for the late response. As per your comments I have used the command `ipy setup.py install`
But below error was observed.

```
rkommine@5CG4483H2K D:\userdata\rkommine\Downloads\robotframework-master\robotframework-master
> ipy setup.py install
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
  File "F:\Bin\IronPython2.7\Lib\site-packages\setuptools\__init__.py", line 11, in <module>
  File "F:\Bin\IronPython2.7\Lib\site-packages\setuptools\extern\__init__.py", line 1, in <module>
  File "F:\Bin\IronPython2.7\Lib\site-packages\pkg_resources\__init__.py", line 46, in <module>
  File "F:\Bin\IronPython2.7\Lib\site-packages\pkg_resources\extern\__init__.py", line 42, in load_module
  File "F:\Bin\IronPython2.7\Lib\site-packages\pkg_resources\_vendor\six.py", line 701, in <module>
  File "F:\Bin\IronPython2.7\Lib\site-packages\pkg_resources\_vendor\six.py", line 692, in exec_
AttributeError: 'module' object has no attribute '_getframe'
```
But after running the command with option `-X:Frames`, The installation was successful.
`ipy -X:Frames setup.py install`

This needs to be updated in the documentation.

With this now I am able to setup robotframework for Python, Ironpython & Jython.

```
rkommine@5CG4483H2K D:\userdata\rkommine\Downloads\robotframework-master\robotframework-master
> f:\Bin\IronPython2.7\Scripts\robot.bat --version
Robot Framework 3.0.3.dev20170213 (IronPython 2.7.7 on cli)

rkommine@5CG4483H2K D:\userdata\rkommine\Downloads\robotframework-master\robotframework-master
> f:\Bin\jython2.7.0\bin\robot.bat --version
Robot Framework 3.0.2 (Jython 2.7.0 on java1.8.0_121)

rkommine@5CG4483H2K D:\userdata\rkommine\Downloads\robotframework-master\robotframework-master
> f:\Bin\Python27\Scripts\robot.bat --version
Robot Framework 3.0.2 (Python 2.7.13 on win32)
```
Many thanks for the support.

Regards,
Ramakrishna

**Comment by rkommine** [comment]
Also to update, Jython has no issue. Robotframework for jython was installed successfully with pip.
Only Ironpython has issues. 

```
rkommine@5CG4483H2K D:\userdata\rkommine\Downloads\elementtree-1.2.7-20070827-preview\elementtree-1.2.7-20070827-preview
> jython -m ensurepip
Ignoring indexes: https://pypi.python.org/simple/
Requirement already satisfied (use --upgrade to upgrade): setuptools in f:\bin\jython2.7.0\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): pip in f:\bin\jython2.7.0\lib\site-packages
Cleaning up...

rkommine@5CG4483H2K D:\userdata\rkommine\Downloads\elementtree-1.2.7-20070827-preview\elementtree-1.2.7-20070827-preview
> jython -m pip install robotframework
Downloading/unpacking robotframework
  Downloading robotframework-3.0.2.tar.gz (440kB): 440kB downloaded
  Running setup.py (path:C:\Users\rkommine\AppData\Local\Temp\pip_build_rkommine\robotframework\setup.py) egg_info for package robotframework

    no previously-included directories found matching 'src\robot\htmldata\testdata'
Installing collected packages: robotframework
  Running setup.py install for robotframework

    no previously-included directories found matching 'src\robot\htmldata\testdata'
    changing mode of F:\Bin\jython2.7.0\bin\jybot.bat to 777
    changing mode of F:\Bin\jython2.7.0\bin\jyrebot.bat to 777
    changing mode of F:\Bin\jython2.7.0\bin\rebot.bat to 777
    changing mode of F:\Bin\jython2.7.0\bin\robot.bat to 777
    replacing interpreter in robot.bat and rebot.bat.
Successfully installed robotframework
Cleaning up...
```

**Comment by pekkaklarck** [comment]
My guess is that you need `-X:Frames` with `ipy setup.py install` if you got `setuptools` installed. Robot's install nowadays (#2033) always uses it when it's available and falls back to `distutils` only if it isn't. I doubt you get `setuptools` by default as part of IronPython installation, but your `pip` installation has added it. I guess adding a note that you may need to use `-X:Frames` also in this case would be a good idea.

**Comment by pekkaklarck** [comment]
This is IronPython issue rather than Robot issue. Closing.
