### ISSUE TITLE
Possibility to avoid executing keyword in dry-run based on special tag

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#2528]
I've recently encountered two separate cases where keyword is either failing or taking a lot of time then executed in the dry-run mode. Such problematic keywords cannot be dynamically skipped in dry-run using `Run Keyword If` because in the dry-run mode keywords inside `Run Keyword If` are executed regardless the expression. Additionally adding such complexity to tests just to avoid problems in dry-run would be a little questionable.

A simple solution to this problem is skipping keywords that contain a special tag like `robot-no-dry-run` or `rf: no dry-run`. We already add similar special `robot-exit` tag to tests when they are not run due to a graceful exit (#2029) and have planned to use similar approach to control when the continue-on-failure mode is in use (#2285).

**Comment by pekkaklarck** [comment]
The biggest question here is deciding how to name the tag and, even more importantly, what prefix we want to use with such tags in general. We have [documented](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#reserved-tags) that we'd use `robot-` prefix, but somehow I don't like it too much nowadays. Because the current only special tag `robot-exit` is added by Robot, we could still easily change it to something else. Once users start adding these tags to their tests, change would require all of them to be updated too.

When deciding about naming, we should take into account the current use case for `robot-exit`, this dry-run use case, and also the continue-on-failure use case in #2285. In addition to the prefix we should decide do we want to use a space, a hyphen, or something else between words. Some possibilities listed below:

- `robot-exit` vs. `robot: graceful-exit` vs.`rf: graceful exit`
- `robot-no-dry-run` vs. `robot: no-dry-run` vs. `rf: no dry run`
- `robot-continue-on-failure` vs. `robot: continue-on-failure` vs. `rf: continue on failure`

**Comment by pekkaklarck** [comment]
FWIW, [Subversion properties](http://svnbook.red-bean.com/en/1.7/svn.ref.properties.html) have a naming convention that properties used by Subversion itself start with `svn:` like in `svn:executable`. They also seem to use hyphens instead of spaces in name like`svn:mime-type` and `svn:needs-lock` Notice that although `svn` is an abbreviation of Subversion, it is also the command you use when executing it.

**Comment by aaltat** [comment]
I like most `robot-` syntax, but in the other hand I don't feel strongly on the matter. But I would like the syntax to be constant in the core framework.

**Comment by pekkaklarck** [comment]
I've started to like `robot:` prefix but don't feel too strongly about this either. I agree we should keep the syntax constant, but don't think changing `robot-exit` is a big issue because it's not a tag anyone should have in their data. I doubt anyone has tooling to check for this tag either, but I still wouldn't change it in RF 3.0.2 but wait for 3.1. If we would decide to keep using 'robot-` prefix, I'd still consider renaming this tag to `robot-graceful-exit` because it is more clear.

**Comment by pekkaklarck** [comment]
This was implemented, with tests, by the above commit. Uses `robot:no-dry-run` (case and space insensitive) as the special tag, but this can still be changed. Documentation missing.

**Comment by pekkaklarck** [comment]
Feature documented by the commit above. Also added #2539 about renaming `robot-exit` to use the `robot:` prefix.
