### ISSUE TITLE
Document that pip does not recreate `robot.bat` and `rebot.bat` if installing same version multiple times

### ISSUE THREAD

**Issue by lczub** [robotframework/robotframework#2529]
Installing RF 3.0.1 via pip on Windows creates the deprecated script _pybot.bat_ and the preferred script _robot.bat_

Difference between both is, that _robot.bat_ includes a python call with a hard full path, while _pybot.bat_  just includes a python call without any path details. 

For portable python / robot installations it would be helpfull, when _robot.bat_ also just includes a python call without any path details.

Example:

Install robotframework and compare content of _pybot.bat_ and _robot.bat_
```
set PYENV_DIR=d:\pyenv\robot_35
D:\Programme\Python35\Scripts\virtualenv.exe %PYENV_DIR%
call %PYENV_DIR%\Scripts\activate
pip install robotframework 
echo ### Content of %PYENV_DIR%\Scripts\robot.bat
more %PYENV_DIR%\Scripts\robot.bat
echo ### Content of %PYENV_DIR%\Scripts\pybot.bat
more %PYENV_DIR%\Scripts\pybot.bat
```

with RF 3.0.1 this creates

```
### Content of d:\pyenv\robot_35\Scripts\robot.bat
d:\pyenv\robot_35\scripts\python.exe -m robot.run %*
### Content of d:\pyenv\robot_35\Scripts\pybot.bat
python -m robot.run %*
```
Same result occurs using Py27

**Comment by pekkaklarck** [comment]
The problem with just having `python -m robot.run %` is that running `robot` on the command line would use whatever `python` that's first in `PATH`. We changed this on purpose when `robot.bat` start-up script was introduced in RF 3.0. I guess we didn't change `pybot.bat` for backwards compatibility reasons.

Do you encounter problems with the current approach if you install Robot using pip or is the problem you describe only with a custom installation? If the latter, I don't think changing the script is created by default is a good idea. If you create a custom installation, you can easily create a custom `robot.bat` too, or use `python -m robot` or `python path/to/robot/run.py` approach to start the execution.

**Comment by lczub** [comment]
Hello Pekka,
the problem occurs with pip in combination with a portable python installation on an USB stick.

My "personal" target is to get a portable collection of robot tools (the swiss testing knife). The USB stick will not be connected always to the same network drive letter, so _robot.bat_ will not find the portable python installation. 
Your suggested solution with a separate custom script is ok, cause such portable robot installation has the same problem like you to work with the correct python installation. Normally they uses scripts to adjust the PATH environment before calling _pybot.bat_ . So they also can adjust the robot call itself.

You should adjust your document [User Guide RF 3.0.1 - Setting PATH on Windows](http://robotframework.org/robotframework/3.0.1/RobotFrameworkUserGuide.html#configuring-path), cause it reflect currently still the old _pybot.bat_ behaviour also for _robot.bat_
```
Notice that if you have multiple Python versions installed, the executed robot or rebot runner script will always use the one that is first in the PATH regardless under what Python version that script is installed. To avoid that, you can always execute the installed robot module directly like C:\Python27\python.exe -m robot.
```
So this ticket is just an documentation issue.


Some additional hint:
Due to the currently hard dependency between Ride and a special wxPython version, which is not installable via pip, I created a collection of robot tools [PortablePythonWithRobot](https://github.com/lczub/PortablePythonWithRobot/blob/robot/config/Robot/scripts/README.rst). But in the near future, when wxPython is moved to [wxPython Phoenix](https://github.com/wxWidgets/Phoenix) which is installable via pip, a default portable python like [WinPython](http://winpython.github.io/) in combination with several additional pip statements can be used. The problem with the hard path in _robot.bat_ will than still exist, but maybe the above documentation section can include a hint, that portable python installation need a separate custom script.

**Comment by lczub** [comment]
Hello Pekka,
a much more serious problem occurs with pip in combination with multiple virtualenv installations, when pip is called without the `--no-cache-dir` option. In this case, the python path in _robot.bat_ always references the first created virtualenv environment.

Examples with Py2712:

create first pyenv robot_a
```
set PYENV_DIR_A=c:\pyenv\robot_a
C:\Python27\Scripts\virtualenv.exe %PYENV_DIR_A%
call %PYENV_DIR_A%\Scripts\activate
pip install robotframework

echo ### Content of %PYENV_DIR_A%\Scripts\robot.bat
more %PYENV_DIR_A%\Scripts\robot.bat
```
Output is
```
New python executable in c:\pyenv\robot_a\Scripts\python.exe
...
Successfully installed robotframework-3.0.1
### Content of c:\pyenv\robot_a\Scripts\robot.bat
c:\pyenv\robot_a\scripts\python.exe -m robot.run %*
```

ok, _robot_a - robot.bat_ references the wanted virtualenv robot_a

start a fresh win console and create a second pyenv robot_b
```
set PYENV_DIR_B=c:\pyenv\robot_b
C:\Python27\Scripts\virtualenv.exe %PYENV_DIR_B%
call %PYENV_DIR_B%\Scripts\activate
pip install robotframework 

echo ### Content of %PYENV_DIR_B%\Scripts\robot.bat
more %PYENV_DIR_B%\Scripts\robot.bat
```
Output is
```
New python executable in c:\pyenv\robot_b\Scripts\python.exe
...
Successfully installed robotframework-3.0.1
### Content of c:\pyenv\robot_b\Scripts\robot.bat
c:\pyenv\robot_a\scripts\python.exe -m robot.run %*
```

*FAILURE*, _robot_b - robot.bat_ references the unwanted virtualenv robot_a

Workaround (and maybe required hint for the installation instructions), pip must be called using the `--no-cache-dir` . Building robot_b virtualenv with `pip install --no-cache-dir robotframework` will create a _robot.bat_ file referencing the expected virtualenv robot_b. 

Details Pip Caching see https://pip.pypa.io/en/latest/reference/pip_install/#caching

**Comment by pekkaklarck** [comment]
Yeah, that's more severe. I need to think could we avoid the problem somehow, but that might be complicated/impossible with the current setup. Should switch to using setuptools entry points but that is a bigger change and can be done only in a major release. Should also test do entry points work with all supported interpreters.

As you commented, adding a note to the installation instructions is a good idea. Using `--no-cache-dir` is a good workaround once you know it. Alternatively you could just ignore the `robot.bat` script and use `python -m robot` instead.

**Comment by lczub** [comment]
I agree with you, updating the installation instruction is the pragmatical solution.

**Comment by Tset-Noitamotua** [comment]
I had a related issue[1] some time ago but I did not expected the failure to be on RF side :)

[1] https://github.com/bulkan/robotframework-requests/issues/144#issuecomment-270665962

**Comment by pekkaklarck** [comment]
Investigated this issue and here are my findings:

1. The problem is easy to reproduce by simply creating two different virtual environments and running `pip install robotframework` on both.

2. The problem seems to be caused by pip generating a wheel based on the source distribution, paths in scripts being updated at that point, and the same wheel reused when running `pip install robotframework` again.

3. Luckily same wheel is not used when installing using different Python versions. You shouldn't thus encounter this issue if you first install with Python 2.7 and then with Python 3.6.

4. As already discussed, using the `--no-cache-dir` option (e.g. `pip install --no-cache-dir robotframework`) is a good workaround. When that option is used, wheels are not got from the cache and the problem disappears. Alternatively `robot` and `rebot` scripts could be ignored altogether and `python -m robot` and `python -m robot.rebot` used instead.

5. I also tested that generating `robot.exe` instead of `robot.bat` (#2415) fixes the problem. Definitely need to do that in RF 3.1.

**Comment by lczub** [comment]
Many Thanks for your detailed investigations 👍
