### ISSUE TITLE
need keyword which will give input not enter along with that.

### ISSUE THREAD

**Issue by Sudhaker7** [robotframework/robotframework#2537]
Hi all,

I am working in  automation  using  RIDE, in my project i am automating on "CLI" commands.
I am using "write" keyword for giving input to cli  through write argument but write functionality is to give enter along with argument.
but cli is not expecting enter command along with argument due to this my scripts are getting failed.
Do we have any other RIDE keyword other than write which wont give enter thing along with arguments.

**Comment by rlucca** [comment]
If it's to test the output of several different flags combination, maybe you can have a lock at the atest folder. I think there they use a keyword called Run Process passing the several flags and compare the output.

**Comment by pekkaklarck** [comment]
This issue tracker is for bug reports and concrete enhancement requests. Please send questions to robotframework-users mailing list or other such forums. When reporting a problem or asking a question, it would be helpful to mention which library you use. There are various which have `Write` keyword. Also, it is very unlikely that RIDE would have anything to do with this. It is just one of the Robot Framework test data editors.
