### ISSUE TITLE
Add `get_keyword_tags` to dynamic library API and remote interface

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#2538]
Keyword tags have been supported since RF 2.9 (#925) only user keywords (`[Tags]  t1  t2`) and static/hybrid Python keywords (`@keyword(tags=['t1', 't2']`) support setting tags explicitly. With other library types tags need to be added to the end of the keyword documentation like `Tags: t1, t2`.

Having separate `get_keyword_tags` method in the dynamic library interface would ease passing tags from dynamic libraries to Robot. Should call that method before calling `get_keyword_documentation` to allow libraries to detect should the latter include embedded tags or not.

**Comment by pekkaklarck** [comment]
Same method needed also in the remote interface. Can add a new issue or update this to cover both.

**Comment by pekkaklarck** [comment]
`get_keyword_tags` in the dynamic API implemented, tested and documented by the above commits.

Implementing this in the remote API is easy and will be done as part of this issue.

**Comment by pekkaklarck** [comment]
Also remote interface now has `get_keyword_tags`. This issue is done.

**Comment by claytonneal** [comment]
https://github.com/claytonneal/nrobot-server/issues/2

**Comment by ombre42** [comment]
Going to wait and see if someone requests this for the Java server...

**Comment by pekkaklarck** [comment]
@ombre42 Yeah, no need to implement this if nobody needs it. Tags can already no be passed as part of the documentation, although the new method makes is a lot more convenient. Then there's also the question how to specify tags in Java (and C#, etc.) libraries in general. JavaLibCore doesn't know anything about tags either.

**Comment by claytonneal** [comment]
Just a question. Does libdoc when pointed at a remote library output keyword tags in the xml file, so that if the doc file is loaded into an editor, the editor can support showing tags?

**Comment by pekkaklarck** [comment]
Yeah, Libdoc writes keyword tags to its XML outputs:
https://github.com/robotframework/robotframework/blob/master/src/robot/libdocpkg/xmlwriter.py#L43

Not sure does any editor use that info yet, though. Keywords tags are in general a functionality that has lot of potential use cases but isn't used much yet.b
