### ISSUE TITLE
Rename `robot-exit` tag to use `robot:` prefix

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#2539]
The `robot-exit` tag is added to tests automatically when execution is stopped gracefully since RF 2.9 (#2029). When this special tag was added, we decided to reserve the `robot-` prefix to be used also with other special tags in the future.

We are now adding a possibility to disable dry-run by using a special tag in RF 3.0.2 (#2528), but like `robot:no-dry-run` better than `robot-no-dry-run`. We should use the same prefix with all special tags, but we cannot change `robot-exit` in a minor release. Prefixes should be unified in RF 3.1. This includes updating the documentation in the User Guide regarding to the reserved tags.

When we rename `robot-exit`, we don't necessarily need to use `robot:exit` but can use something more explicit like `robot:graceful-exit`.

**Comment by pekkaklarck** [comment]
The decision was to rename `robot-exit` to `robot:exit`.

**Comment by simplyviks** [comment]
how can we find who is sending the signal?

**Comment by sayoojmandodi** [comment]
I did a gracefull termination while a test case is running. I did it by sending an 'kill -INT pid' command
report is getting generated for the same test case but the reserved tag robot:exit is not showing up in the report.
