### ISSUE TITLE
Installing from cached versions breaks on windows with virtualenv

### ISSUE THREAD

**Issue by nicholasbailey** [robotframework/robotframework#2545]
On Windows 7, 8 and 10, naive installation of robotframework from pip in multiple virtual environments doesn't work as expected. Imagine the following workflow

`> virtualenv firstenvironment`
`> .\firstenvironment\Scripts\activate.ps1`
`(firstenvironment) > pip install robotframework`
`deactivate`
`virtualenv secondenvironment`
`.\secondenvironment\Scripts\activate.ps1`
`(secondenvironment) > pip install robotframework`
`> rm -Recurse .\firstenvironment`
`(secondenvironment)> .\secondenvironment\Scripts\robot.bat <some arguments here>`

One would expect this to work just fine, but it doesn't. Instead it fails with this message
`The system cannot find the path specified.`
Looking at the `robot.bat` created in the the second virtualenv, you'll see this

`@echo off`
`path\to\firstenvironment\scripts\python.exe -m robot.run %*`

The path to the Python executable is resolved at install time, not run time. This means that if `pip` uses a cached install, it installs a batch file pointing to a now obsolete virtualenvironment. This is frustrating to say the least.

The easiest solution would be just to scrap the batch file and the interpreter replacement and use powershell for windows runner scripts. We can leave the batch file around for anyone who's still running Windows 95 and doesn't have access to powershell.

**Comment by nicholasbailey** [comment]
I'm happy to pick this up and implement myself, it should only take a few minutes of my time, but it will save my team literally hours of frustrating debugging.

**Comment by pekkaklarck** [comment]
This exact same issue was reported as #2529 few weeks ago. Unfortunately we didn't find safe enough way to fix it in RF 3.0.2 and decided just to document the inconvenience. Luckily there's a workaround to use `--no-cache-dir`. See the aforementioned issue for details.

The real fix is starting to use `.exe` wrappers generated by setuptools entry points (#2415). The main task here is testing that these entry points work with all the supported Python interpreters, including Jython and IronPython.

**Comment by pekkaklarck** [comment]
@nicholasbailey If you have time and interest to help with this, it would be great if you could study how setuptool entry points work with Jython and IronPython. Let's continue discussing about that in #2415.
