### ISSUE TITLE
Support for multiline strings.

### ISSUE THREAD

**Issue by 1dziubo1** [robotframework/robotframework#2551]
Imagine xml tutorial. I want to put about 20 lines of simple xml to variable, so every student can see it directly. Due to I/O and access, files are not an option. Now I have two options:
1) Put all xml contents that to one line, super human unfriendly way
2) By Suite Setup and keyword Set Suite Variable, but I strongly insist, not to use keywords:
Set Suite Variable, Set Global Variable, as this breaks good practices ( Imagine situation, where all values, from every keyword are passed as Global Variables, no single '[Return]' is used, and you are assigned to maintenance that. - hell is quite nice place as now I see it ). So, rule is that suite/global variables are read-only. You force me to break this rule in tutorial. How can you sleep?

Sorry for this bit long intro, however you do understand how this support is important. Also, I think, that there should be an option to auto-add newline, for every line of multiline variable.

**Comment by pekkaklarck** [comment]
If I understand your needs correctly, this is already supported:
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#variable-table
