### ISSUE TITLE
pybot --version exit with code '251'?

### ISSUE THREAD

**Issue by fayndee** [robotframework/robotframework#2554]
When running `pybot --version` after the installation, it does print the version information correctly but it also exits with code `251`. I would expect the exit code to be `0`.

To reproduce:

```
pybot --version
echo $?
```

Output with robot 3:

```
Robot Framework 3.0.2 (Python 2.7.5 on linux2)
251
```

Output with robot 2:

```
Robot Framework 2.9.2 (Python 2.7.5 on linux2)
251
```

**Comment by pekkaklarck** [comment]
This is by desing and documented:
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#return-codes

We wanted to use 0 only when you run tests and no critical test fails.
