### ISSUE TITLE
No keyword with name 'Teardown Actions' found

### ISSUE THREAD

**Issue by jisnagadgeon** [robotframework/robotframework#2556]
[ERROR]
Also teardown failed:
No keyword with name 'Teardown Actions' found.

I Try to Run files given below

[example.zip](https://github.com/robotframework/robotframework/files/820358/example.zip)

Can you help me.

**Comment by pekkaklarck** [comment]
That error means that the keyword you try to use as teardown doesn't exist. Not sure why that happens, but I seriously doubt it would be a bug in Robot Framework. You would need to provide more information about how you run tests, where the error occurs etc. for anyone to be able to help you.
