### ISSUE TITLE
Robot Framework Custom Library Imports using WITH NAME

### ISSUE THREAD

**Issue by ratijha** [robotframework/robotframework#2557]
I have recently started using Robot Framework for my Automation Framework, using my existing python Libraries

*** Settings *** 
Library ../../lib/ServerAPI.py WITH NAME ServerAPI 
*** Test Cases *** 
  [TC-001]-Registering a device with INVALID SUBSCRIBER name to the server                 ServerAPI.subscriber  None                                                            
${resp} register device ${token} ${devid}                                               
LOG ${resp}                                                                              
Should Be Equal ${resp} ${True}

Its not recognising the ServerAPI keyword name for the library, can anybody help me, what i'm missing here?

**Comment by pekkaklarck** [comment]
This issue tracker is for bug reports and enhancement requests. Please use other forums like robotframework-users mailing list for general questions.

Notice also that at the moment your question doesn't contain enough information for others to help you. You don't, for example, at all explain what goes wrong in what you try to do. If you want too answers, you need to learn asking good questions. Busy professionals like me mostly ignore questions like this unless they come from paying clients. See this article for more information about asking smart questions:
http://www.catb.org/~esr/faqs/smart-questions.html
