### ISSUE TITLE
logger function was conflicted when run with Django

### ISSUE THREAD

**Issue by dickcarlee** [robotframework/robotframework#2558]
I've write a project based on Django & RobotFrameWork, Django use Logger in Setting to record issues, so when run this project, RF's [logger.info] won't work, can't print logs and the data in log.html is empty. what can I do to fix it ?

**Comment by pekkaklarck** [comment]
Do you mean that if you do `from robot.api import logger` and then `logger.info('Message')` that won't work? Does it work if you don't use Django?

**Comment by dickcarlee** [comment]
1. django+robotframework: log_message won't work, start_suite and other listener functions work .
2. Only robotframework: everything is good

I've tried to disable Django- setting-"disable-existing-logger" but nothing changes

**Comment by pekkaklarck** [comment]
Is this a listener interface you are talking about?? Or what Robot's API are you actually using? Please provide more information about what you are trying to do. Notice also that I have very little knowledge about Django and no basically nothing about its logging.

**Comment by dickcarlee** [comment]
In this project:
1.  Created a `listener.py` which contained `log_message` to get information,
2.  In logic parts I've written `from robot.api import logger` and `logger.info`,`logger.error`,

when run this project in Django:
Maybe the `logger` function has already been conflicted, it can't leave any message in the  log.html, and of cause the `listener.py` method `log_message` isn't work. In this case, `print` works, the log.html records all the `print` in one `INFO` log. 

when run without Django:
both `logger` and `log_message` work, log.html contains every single `INFO`,`Error` log

**Comment by pekkaklarck** [comment]
Any new info related to this issue? Are you sure you've used `robot.api.logger` for logging and not Python's `logging` module? Both work in general, but external modules like Django may configure the latter and cause issues like this. I cannot see how Django could affect Robot's own logger, though.

**Comment by louislewatcn** [comment]
I am using flask, log info does not work
I also tried django, the same issue as you have there, but the log WARN is till works

**Comment by pekkaklarck** [comment]
The referred Flask issue was due to using threads. No new info about the original Django issue. Closing.
