### ISSUE TITLE
Variables and keywords created or imported in initialization files are not available in the lower level test suites, why are they?

### ISSUE THREAD

**Issue by SylviaLan** [robotframework/robotframework#2559]
It is recommended that one suite has less than ten cases in the UserGuide, when I organise my suites and cases, I find it inconvenient to write cases as long as the restriction it is. 
My project is like this:
MyProject
	|_______ModuleSuites1
     	|		|_____FunctionSuite1(import Resources)
	|		|		|______FunctionCase1
	|		|		|______FunctionCase2
	|		|		|______….
	|		|
	|		|_____FunctionSuite2(import Resources)
	|		|	
	|		|_____FunctionSuite3(import Resources)
	|		|_____….
	|
	|_______Resources

As you can see, I must to import resources in every suite when writing cases. I really want to import resource once in ModuleSuites  and then they are available in many FunctionSuites.

Can you explain why variables and keywords created or imported in initialization files are not available in the lower level test suites?  Are there better solutions to my problem rather than repeatedly import?

**Comment by pekkaklarck** [comment]
This was a design decision to avoid keywords and variables in higher level accidentally causing issues in lower level suites. It has sometimes been debated was that a good decision, but personally I still think it is. Due to backwards compatibility issues it wouldn't be changed anyway, though.

**Comment by pekkaklarck** [comment]
Also, robotframework-users mailing list and other such forums are better for general questions that this issue tracker.
