### ISSUE TITLE
[ ERROR ] Error in test library 'pymysql': Creating keyword 'Connect' failed: Keyword with same name defined multiple times.

### ISSUE THREAD

**Issue by wodeta33** [robotframework/robotframework#2561]
> [ ERROR ] Error in test library 'pymysql': Creating keyword 'Connect' failed: Keyword with same name defined multiple times.

When i try to connect to mysql, i meet the problem. I hope someone can resolve the problem. Thank you.

**Comment by pekkaklarck** [comment]
There's already #2550 that you have commented? Why open a new issue?
