### ISSUE TITLE
Question on how to create PASS/FAIL in reports for each test case iteration.

### ISSUE THREAD

**Issue by mauiTester** [robotframework/robotframework#2563]
This is not an issue, but I hope somebody can help me out!
My test case and keywords are as below:

*** Settings ***
Test Template     Perform Login

*** Test Cases ***
Login TestCase
    TC1    user1    password1
    TC2    user2    password2
    TC3    user3    password3
    TC4    user4    password4

*** Keywords ***
Perform Login
    [Arguments]    ${tc#}    ${username}    ${password}
    Login using    ${username}    ${password}

Now while executing the 'Login TestCase' via RIDE, 'Perform Login' is run 4 times and the report generated shows

'Total 1 Pass 1 Fail 0'. 

My question is how can I get the report the generate Pass/Fail for each row, ie
'Total N Pass X Fail Y' , where N=4 and X+Y=N

**Comment by pekkaklarck** [comment]
This is an issue tracker for bug reports and enhancement requests. Please ask questions on robotframework-users mailing list or other such forums.
