### ISSUE TITLE
When using `--suite parent.child`, all test case files with name `child.robot` are parsed 

### ISSUE THREAD

**Issue by KrzysztofJozefowicz** [robotframework/robotframework#2564]
We came to this issue while investigating why robot returns errors from suites which are not being executed (RF 3.0.1).
Common point was that each reported file had the same filename but were in different folder.

From RF UserGuide:

> Test suites and test cases can be selected by their names with the command line options --suite (-s) and --test (-t), respectively. Both of these options can be used several times to select several test suites or cases. Arguments to these options are case- and space-insensitive, and there can also be simple patterns matching multiple names. If both the --suite and --test options are used, only test cases in matching suites with matching names are selected.

But more important part:

> Using the --suite option is more or less the same as executing only the appropriate test case file or directory. One major benefit is the possibility to select the suite based on its parent suite. 

As far as I understands, when running following command, Robot will execute selected suite and testcase (if specified by --test):
`python -m robot.run --suite A.B.Suite --test  myTest  <root_robot_test_folder>`

We observed when somewhere inside <root_robot_test_folder> there are multiple files with the same name ( Suite.robot) with fatal errors (for instance duplicated Documentation in Settings part), Robot reports each of those problems for files which in fact were not anywhere executed (different parent path).

> root_robot_test_folder structure:
> A/B/Suite.robot
> C/Suite.robot (with duplicated Docs)

Command output will run A.B.Suite tests but also will report errors inside C/Suite.robot (C.Suite), using --test does not change output.

Is it desired behavior to scan for files outside parent path even though Robot get exact path from command line? Looks like "too eager" for me.

**Comment by pekkaklarck** [comment]
Does this happen also if you don't specify `--test`?

**Comment by KrzysztofJozefowicz** [comment]
Yes,it produces the same output as with --test (suite name is searched regardless of parents). 

In zip you will find reproduction suite. in A/B/main.robot is a test to run, C/D/main.robot is a suite with Robot Error (duplicated docs section in settings), E/F/main.robot - a proper suite like in A/B. output reports for commands:
**python -m robot.run --suite A.B.main d:\robotTest**  => Report_justSuiteAB.zip , output: executed A\B\main,robot with 20170324 20:32:38.868 	ERROR 	Error in file 'd:\robottest\C\D\main.robot': Setting 'Documentation' used multiple times. 
**python -m robot.run --suite A.B.main --test t1 d:\robotTest** => Report_SuiteABwithTest.zip, output: executed A\B\main.robot with 20170324 20:34:32.812 	ERROR 	Error in file 'd:\robottest\C\D\main.robot': Setting 'Documentation' used multiple times.
**python -m robot.run  --test t1 d:\robotTest\A\B\main.robot** => Report_testWithFilePath.zip. output: executed A\B\main.robot, no Robot Error

[robotTest.zip](https://github.com/robotframework/robotframework/files/869009/robotTest.zip)

**Comment by KrzysztofJozefowicz** [comment]
@pekkaklarck can you comment if this is deliberate behavior or unwanted? We are investigating workarounds in RED using --test + robotsuite file, I would be grateful to know if our workaround would be permanent or temporary.

**Comment by pekkaklarck** [comment]
I can reproduce the problem. Apparently test case files are not skipped if you use `--suite` option with a parent name like `--suite example.suite` and your test case file has name matching the suite name like `suite.robot`. Suites are skipped in the end when selecting which tests to actually run, though.

Skipping suites altogether when using the `--suite` option is an optimization and I don't see that optimization failing in this special case too severe. It definitely could be fixed if someone would be interested to provide a pull request.

**Comment by KrzysztofJozefowicz** [comment]
> I can reproduce the problem. Apparently test case files are not skipped if you use --suite option with a parent name like --suite example.suite and your test case file has name matching the suite name like suite.robot. Suites are skipped in the end when selecting which tests to actually run, though.

That is correct, only additional cost is robot parsing files from testsuite root folder beforehand and reporting errors .

Is there a switch to suppress Robot errors such as this may be workaround for us (users does not want to know errors in suites which were not selected for running)?
--loglevel is for something else

```
D:\>python -m robot.run --suite A.B.main d:\robotTest
[ ERROR ] Error in file 'd:\robotTest\C\D\main.robot': Setting 'Documentation' u
sed multiple times.
```

**Comment by asgorh** [comment]
@pekkaklarck this issue is blocking us a lot with introducing new solution that uses this feature. Could you please provide a workaround (if applicable) to get it work for the time this issue is resolved ? Thanks in advance.

**Comment by pekkaklarck** [comment]
There's no option to disable errors. You can use `--console none`, but you lose all cli output then. Fixing those errors is probably the easiest solution.

**Comment by pekkaklarck** [comment]
I don't have workarounds for this problem. I also consider the problem so minor in the general case that I don't plan to spent my own time fixing it in the near future. If you could get Nokia joining Robot Framework Foundation, then minor problems that happen to be important for Nokia would get more priority.

**Comment by PWojtal** [comment]
Well.. i don't think it's a minor bug - lack of possibility of running test cases in proper way is rather big issue, especially in a situation when we're talking about supported Robot Framework feature.

**Comment by pekkaklarck** [comment]
This bug doesn't prevent anything. The only thing that happens is that some test case files are unnecessarily parsed into test suite objects because those suites will be later discarded anyway. Parsing time is typically so fast that it has no real effect for anything.

In your case your case the visible effect is that the files that are later discarded contain invalid syntax, and you see errors about them when these files are parsed. A very simple solution for this problem is fixing those syntax errors.

**Comment by pekkaklarck** [comment]
PR #2583 is pretty promising but there are few problems that need to be fixed. Most importantly, it needs tests.

**Comment by mihaiparvu** [comment]
Thank you @pekkaklarck for including this issue in 3.1! I will continue @andreeakovacs' work on this PR from now on. I'll let you know if I need help with the acceptance tests when I get to work on them.

**Comment by pekkaklarck** [comment]
It can be a bit hard to create tests for this feature, but without them we don't know it works and may very easily break it in the future. There ought to be existing tests for not parsing files that don't match --suite, though, and they can be used as examples.

**Comment by pekkaklarck** [comment]
PR #2583 is now in very good shape. Noticed few more things to fix/enhance. Do you @mihaiparvu have time to look at them before beta 1 that I try to release latest next Wednesday?

**Comment by mihaiparvu** [comment]
@pekkaklarck Done.

**Comment by pekkaklarck** [comment]
Thanks @mihaiparvu!

**Comment by pekkaklarck** [comment]
This change has caused a regression:
https://github.com/robotframework/robotframework/pull/2583#issuecomment-441212848

**Comment by pekkaklarck** [comment]
Regression fixed and tests enhanced.

**Comment by pekkaklarck** [comment]
Issue #3029 explains two serious regressions caused by PR #2583. I decided to revert the changes introduced by that PR, and this issue, for the following reasons:

- I didn't see any easy way to fix the severe problems that changes caused.
- I don't consider ignoring all possible files when `--suite` is used that important anyway. Parsing is generally pretty fast, and correct suites/tests are selected for execution anyway.
- The problem that syntax errors in files that could be skipped cause visible errors is easiest to fix by fixing those errors.
