### ISSUE TITLE
Not able to set custom location for WebDriver

### ISSUE THREAD

**Issue by n89rodri** [robotframework/robotframework#2567]
Hi,

I'm trying to change the Chromedriver location to run test cases but I'm always getting the error:
WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

I'm changing the webdriver location using an __init__.robot file, the keyword succeeds but still getting the error, I'm using this keyword to change the location path:

`Set Environment Variable | webdriver.chrome.driver | 'C:\WebDrivers\chromedriver.exe'`

Thanks for the help!!

**Comment by Tattoo** [comment]
This is not the [issue tracker for Selenium2Library](https://github.com/robotframework/Selenium2Library/issues), which is what you want to report this.
