### ISSUE TITLE
Python Package install does not download latest version

### ISSUE THREAD

**Issue by vairamsvsjdo** [robotframework/robotframework#2568]
Python Package install does not download latest version
pip installation does not install latest version of robotframework that supports selenium 3.3 and hence geckodriver latest that supports webdriver specification is not working with selenium2library

**Comment by laurentbristiel** [comment]
I was not able to reproduce your problem.
Could you give more details and show what you actually expect and see?

**Comment by vairamsvsjdo** [comment]
There was no issue. Was figuring out how to install 3.0.3.dev20170213. This is a sdist, source distro version and figured out how to do it.
