### ISSUE TITLE
output.xml is getting corrupted

### ISSUE THREAD

**Issue by vinaybond** [robotframework/robotframework#2570]
I have selenium test suite which is passing when I run but report is not generated. After troubleshooting I found that many time output.xml is corrupted. I observed some files and found that sometime it misses the double quotes, sometime half if the data is written and (i.e. time stamp) and tag is not completed. 

Note: File corruption happens randomly with multiple suites.

**Comment by pekkaklarck** [comment]
Most likely you have threads or processes in use and they somehow write to same file. Impossible for others to say anything more. You need to provide a *simple* example demonstrating the problem if you wont us to look at it. See http://sscce.org/ for information about creating such an example.

**Comment by vinaybond** [comment]
This is the way I am running the suite. 

`python -m robot mysuite.robot`

No other program is using output.xml. About example, not sure what exactly I need to put as that is the only command I am executing. Most this issue has happened with files with larger size. i,e. 850kb +

**Comment by pekkaklarck** [comment]
You needed to provide example `mysuite.robot` with all libs etc. needed so that we can run it. And the overall example needed to be really simple and shouldn't require us to do a lot of environment setup.

**Comment by vinaybond** [comment]
The issue is not always reproducible so simple steps wont solve the problem. output.xml generated for me is comparatively bigger. Also, I cant share the sample code or output.xml as organization policy does not allow me to do. I think we can close this issue. I'll try to find the root cause at my end and if I find something, I'll share it in case someone faces same problem.

**Comment by pekkaklarck** [comment]
I wasn't expecting you to share your real tests, I probably couldn't even run them. What you should do is creating as simple example as possible that still reproduces the problem, even if it only happens sporadically, and contains no confidential data. Without such example it is impossible for us to debug the problem. It seems you cannot create such an example and it is thus best to just close this issue.

**Comment by sanjeev5-hub** [comment]
Hi, It is getting corrupted for me too.  I am using threads. Is there a way to make the test not fail of the output.xml is corrupted?
