### ISSUE TITLE
Error Capture Page Screenshot' could not be run on failure 

### ISSUE THREAD

**Issue by cdasadiya74** [robotframework/robotframework#2571]
[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: Multiple keywords with name 'Capture Page Screenshot' found. Give the full name of the keyword you want to use:
AppiumLibrary.Capture Page Screenshot
Selenium2Library.Capture Page Screenshot
I have got the issue while run the pybot demo_8_0_full_workflow.robot for odoo automation test case purpose

**Comment by pekkaklarck** [comment]
You have two libraries with same keyword in use. Like the error message says, you need to explicitly specify which one you want to use. If this happens in some demo, please report the issue to the demo project directly. General questions are best sent to robotframework-users mailing list, to Slack, or other such forums. This issue tracker is for bug reports and enhancement requests.

**Comment by NiveditaMirjikar** [comment]
How to specify explicitly which library to be used, please give an example

**Comment by Noordsestern** [comment]
Like it says in the warning message:
```robot
# Use 'capture screenshot' from Appium:
AppiumLibrary.Capture Page Screenshot
# Use 'capture screenshot' from Selenium library:
Selenium2Library.Capture Page Screenshot
```

**Comment by NiveditaMirjikar** [comment]
> Like it says in the warning message:
> # Use 'capture screenshot' from Appium:
> AppiumLibrary.Capture Page Screenshot
> # Use 'capture screenshot' from Selenium library:
> Selenium2Library.Capture Page Screenshot

Thank you for the quick response

**Comment by JoelDelumen** [comment]
do this test setup ""Set Library Search Order  AppiumLibrary  SeleniumLibrary""
