### ISSUE TITLE
No warning if parsing whole file fails when scanning files from directory

### ISSUE THREAD

**Issue by tantaipa** [robotframework/robotframework#2572]
Robot gives an error that 'docutils' >= 0.9 is needed when a full path to a reStructuredText test case is given. That is very helpful. But when a directory with reStructuredText test cases is supplied, no warning is given that the docutils module is missing. I guess it's a design decision to show a warning, because the *.rst files can also be anything else than robot framework files. Still, giving a warning to the user gets a big up from me!

```
~/tests$ robot 000__Login/00000__Login_page.rst 
[ ERROR ] Parsing '000__Login/00000__Login_page.rst' failed: Using reStructuredText test data requires having 'docutils' module version 0.9 or newer installed.

Try --help for usage information.
```

```
~/tests$ robot .
[ ERROR ] Suite 'Manager' contains no tests.

Try --help for usage information.
```

**Comment by pekkaklarck** [comment]
I'm not sure should there be a warning by default, but there definitely should be if you use the newish `--extension` option. Similar situation occurs also if a test case file cannot be opened at all due to permission or encoding issues. Need to think more about this before RF 3.1.

**Comment by pekkaklarck** [comment]
Forgot we already had this issue and submitted #2857 about the same root cause. That issue has more information so I close this as its duplicate.
