### ISSUE TITLE
Maximum number of Arguments Supported by a Keyword

### ISSUE THREAD

**Issue by n89rodri** [robotframework/robotframework#2575]
Is there any limit for the maximum number of Arguments that a Keyword can take, that comes from a Variable File?

I'm asking this because I found issues trying to run a keyword that takes more than 5 Arguments from a variable file.

**Comment by pekkaklarck** [comment]
No there isn't.

Please send questions to robotframework-users mailing list, to Slack channels, or other such support forums. This tracker is for bug reports and enhancement requests.
