### ISSUE TITLE
Tidy should not merge continued lines

### ISSUE THREAD

**Issue by cjnewman** [robotframework/robotframework#2579]
The robot.tidy utility will always re-wrap continuation lines (with txt format files). I tend to use continuation lines with SEPARATOR=\n, so having each field on a separate line in the file is important for readability of the multi-line test data. Right now robot.tidy will combine the separate lines onto the same line. This makes the test file less readable.

I can think of several acceptable ways to fix this:
1. When SEPARATOR=\n is present, always put the fields on separate lines.
2. have robot.tidy leave the *** Variables *** section unchanged (or make this an option);
3. add an option to robot.tidy to leave line continuations unchanged when producing a new file.

Anyway, I'd like to be able to use robot.tidy without harming readability of test data. Thanks.

**Comment by pekkaklarck** [comment]
It would be best if Tidy would preserver ellipsis used for line continuation, but that isn't possible until parsing modules preserver them. Until that adding some kind of heuristic to write data in nicer format is possible. Would you like this handling to be done only when using `SEPARATOR=\n` or when using `SEPARATOR=` in general? Would you be interested to implement this?

**Comment by cjnewman** [comment]
I'd say put each item on a separate line if SEPARATOR contains \n. If you can give me your thoughts on where in the code this logic slot in cleanly, then I'm game to try the implementation.

**Comment by mikeleppane** [comment]
Is there any plans to improve this issue in robot.tidy? It would be good to have this feature. I have been looking in to this. However, I’m having some difficulties to locate the exact place in code where the rows are been combined(continuation lines)? Can someboby help what would be the correct approach here?

**Comment by pekkaklarck** [comment]
New parser (#3076) doesn't anymore remove continuation markers (`...`) and thus Tidy can preserve them as well. That ought to fix the underlying issue reported here as well.
