### ISSUE TITLE
Robot.api call to tags.populate() generates deprecation warning for using [Tags] multiple times.

### ISSUE THREAD

**Issue by daveesposito** [robotframework/robotframework#2584]
First, I'm sorry if this is a duplicate.  I searched but didn't find this logged yet.
Second, hopefully this isn't PEBCAB (problem exists between chair and keyboard).

I have a script that is trying to update test data (source files) with new tags and when I call tags.populate() I get the warning about not using the [Tags] setting multiple times.  I know this usage is deprecated and when manually creating files we can avoid it, however, I don't have control of how this function call adds the tags and so this feels like a robot.api bug.  Here's my script:

`
from robot.api import TestData

def main():
    '''Must run in same directory as "test_suite_file.txt"
    '''
   
    testdata = TestData(source="test_suite_file.txt")
    testdata.testcase_table.tests[0].tags.populate(["tag2"])
    testdata.save()

if __name__ == '__main__':
    main()
`

test_suite_file.txt looks like this to start with:

`
*** Test Cases ***
test_1
    [Tags]    tag1
    Log    Test!
`

Run the script in the same directory as the test suite and it should print the deprecation warning.  I'm using Robot Framework 2.9.2.

Please let me know if more info is needed.

**Comment by daveesposito** [comment]
The code syntax above isn't formatting correctly for me but I think you can tell what's going on.  The test suite data is actually on separate lines despite how it is shown.

**Comment by pekkaklarck** [comment]
The error is there to detect invalid test data like this:

```robotframework
*** Test Cases ***
Example
    [Tags]    my    tags
    [Tags]    this is not valid
    ...
```

The parsing API generally isn't meant to be used programmatically, so there can be rough edges like this. I guess we could try fixing this, but I'd rather rewrite the whole parsing logic at some point. Have you looked could the problem be easily fixed or did you find any other API to modify tags? Also, modifying tags could possibly be a useful feature to the built-in Tidy tool.

**Comment by pekkaklarck** [comment]
This issue isn't valid anymore after the new parser (#3076) is taken into use.
