### ISSUE TITLE
External Libraries link to AutoItLibrary broken

### ISSUE THREAD

**Issue by mh182** [robotframework/robotframework#2585]
The link of AutiItLibrary in the http://robotframework.org/#libraries section points to https://code.google.com/archive/p/robotframework-autoitlibrary/ which returns a 401 error.

I alternatives version of the library on GitHub but I do not know which one is the migrated version from Google Code.

**Comment by mh182** [comment]
https://github.com/HW71/AutoItLibrary seems an active copy of the orginal project on Google Code.

**Comment by pekkaklarck** [comment]
Thanks for the report. This tracker is for Robot Framework itself, though, and issues about stuff at http://robotframework.org belong to https://github.com/robotframework/robotframework.github.com. Could you please submit an issue there? Even better if you could ask on robotframework-users and/or Slack about the status of this library.

**Comment by mh182** [comment]
I moved the issue as asked and i'm closing this one.

Sorry, I have no idea where i can find "robotframework-users" nor what Slack is.

**Comment by HelioGuilherme66** [comment]
@mh182 All the needed info is at [Support page at RobotFramework.org](http://robotframework.org/#support)
