### ISSUE TITLE
Telnet lib 'read' keyword does not have delay argument similar to sshlibrary 'read'

### ISSUE THREAD

**Issue by mverma-va** [robotframework/robotframework#2586]
Telnet library "read" keyword does not have delay argument, similar to what we have in sshlibrary "read" keyword. It would be nice to have that so that we can read the whole output even when there is some delay.

**Comment by pekkaklarck** [comment]
Can be added if someone provides a pull request.

**Comment by pekkaklarck** [comment]
There doesn't seem to be much interested towards this. Closing.
