### ISSUE TITLE
Unable to Get Window Position Using Selenium2Library Keyword

### ISSUE THREAD

**Issue by vnkarthik87** [robotframework/robotframework#2587]
When Fetching xaxis and yaxis value using Get Window Position, the keyword returns an error:
**'WebDriverException: Message: Failed to interpret x as integer'**

pip list information:
**robotframework (3.0.2)
robotframework-selenium2library (1.8.0)
selenium (3.0.2)**

**Comment by ombre42** [comment]
Selenium2Library has its own issue tracker: https://github.com/robotframework/Selenium2Library/issues/new
