### ISSUE TITLE
Linking test cases to another test suite

### ISSUE THREAD

**Issue by edsdame** [robotframework/robotframework#2591]
I was wondering, if there is a chance to do something like that:
I have a multiple suites, and lets say three of them contains the same test case. Question is, if I can "link" one test case to another suite, so if I change one, the other automatically changes too. It's hard to keep track of the changes if I need to change the same case in multiple suites.

**Comment by bkhouri** [comment]
Maybe my comment doesn't make sense, but are the test steps the same for each test case?  if so, can't you just create a Keywords in a resource file and have each suite test case call the keywords?

**Comment by edsdame** [comment]
I get what you mean. My tcs are all keyword-focused, so that's not an issue, but there's a fair amount of old ones made by different people which have keywords and separate steps. It would be still a solution to make  a mega-keyword from each of the old cases and let them handle the changes.

**Comment by pekkaklarck** [comment]
No, this is not possible. You can only share keywords, not tests. Depending on your actual use case, generating tests based on a model might be one solution as well.
