### ISSUE TITLE
Transpile or compile robot scripts to byte code

### ISSUE THREAD

**Issue by vairamsvsjdo** [robotframework/robotframework#2592]
In order to accelerate performance of large volume of unit test scripts written, need a python and jython compiled script generator. So, during automated testing, two steps of robot scripts to python and python to byte code steps can be saved.

**Comment by pekkaklarck** [comment]
Could you please clarify?

**Comment by vairamsvsjdo** [comment]
Robot Framework parses "English Like test cases" created to matching library keywords in Python libraries. If these keyword calls and hence the keywords and test cases as well within a robot file can be "transpiled" to Python and in turn to python byte code, this can reduce the time in parsing. This will reduce in time to parse. Hence, test automation execution for large applications can be in shorter cycle than otherwise

**Comment by pekkaklarck** [comment]
I see. Probably the easiest way to get something like this done would be serializing the internal test suite structure using e.g. the Pickle module. Because this is a rather big task and because the parsing time isn't typically too big a problem, I don't consider this too high priority. Are you @vairamsvsjdo or someone else interested to implement this or sponsor the development?

**Comment by vairamsvsjdo** [comment]
Yes, I am working for Jay DevOps Organization and interested in this feature implemented.

**Comment by pekkaklarck** [comment]
Cool. If serializing the test suite structure is enough for your needs, then the first step would probably be adding method like `serialize` or `save` to the `robot.running.TestSuite` object. I guess it could serialize the suite structure into a `*.robotc` file, which could then be an input to the standard `robot` command.

**Comment by pekkaklarck** [comment]
No interest towards this lately. Closing.
