### ISSUE TITLE
Robot Scrip Variable Python Class does not convert nested dictionaries to DotDic.

### ISSUE THREAD

**Issue by kootstra** [robotframework/robotframework#2593]
When a Python Variable Class file returns values in the structure of type `OrderedDict` it will convert this and the second level to the `DotDic` structure. However, when the `OrderedDict` structure has more levels, the conversion will not convert those levels to `DotDic` objects even though at first glance this is expected behavior.  

This issue can be circumvented by manually converting the structure to `DotDic` with a converter function (Example below: `dict_to_dotdict`) to convert the more readable dict code to the desired `DotDict` structure. However, this adds a dependency to an internal library which would be nice if we can avoid. 

```from robot.utils import DotDict

class DotDic(object):
    def get_variables(self):
        G = {
                u'H':
                    {
                    u'I':
                        {
                            u'key':  u'value'
                        }
                    }
            }
        return {u'G': self.dict_to_dotdict(G)}

    def dict_to_dotdict(self, dct):
        dd = DotDict({})
        for key, val in dct.items():
            if isinstance(val, dict):
                dd[key] = self.dict_to_dotdict(val)
            else:
                dd[key] = val
        return dd```

**Comment by pekkaklarck** [comment]
The problem is real but the description of this issue was not exactly correct. Instead of explaining this in comments here, decided to submit a new issue #2600 that explains the problem a bit more thoroughly.
