### ISSUE TITLE
[Android 7] Test blocked after closing dialog

### ISSUE THREAD

**Issue by lolotoms** [robotframework/robotframework#2595]
Hello,

I am testing an app on android 7 with robotframework and appium library. When I disconnect user, there is a confirm dialog. So I close this with a "Click element" which wokrs fine. Then nothing append.. Test don't stop, next instruction is send to appium node but there is no answer.

My configuration:

Appium 1.6.4
Robot 3.0.1
AppiumLibrary 1.4.3

Here are the last instructions log by robotframework console:

INFO : </td></tr><tr><td colspan="3"><a href="appium-screenshot-25.png"><img src="appium-screenshot-25.png" width="800px"></a>
INFO : Clicking element 'xpath=//android.widget.Button[@text="Oui"]'.
   
And a part of the appium node log. At the end you will see the last instruction send to appium after closing Dialog :

[debug] [MJSONWP] Responding to client with driver.findElements() result: [{"ELEMENT":"22"}]
[HTTP] <-- POST /wd/hub/session/85bf921d-8be1-45b6-872f-6a52f3cb6160/elements 200 70 ms - 90 
[HTTP] --> POST /wd/hub/session/85bf921d-8be1-45b6-872f-6a52f3cb6160/elements {"value":"(//android.widget.Button[@text=translate(\"Oui\",\"abcdefghijklmnopqrstuvwxyzéè\",\"ABCDEFGHIJKLMNOPQRSTUVWXYZÉÈ\")] | //android.widget.Button[@text=\"Oui\"])[1]","sessionId":"85bf921d-8be1-45b6-872f-6a52f3cb6160","using":"xpath"}
[debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["xpath","(//android.widget.Button[@text=translate(\"Oui\",\"abcdefghijklmnopqrstuvwxyzéè\",\"ABCDEFGHIJKLMNOPQRSTUVWXYZÉÈ\")] | //android.widget.Button[@text=\"Oui\"])[1]","85bf921d-8be1-45b6-872f-6a52f3cb6160"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"(//android.widget.Button[@text=translate(\"Oui\",\"abcdefghijklmnopqrstuvwxyzéè\",\"ABCDEFGHIJKLMNOPQRSTUVWXYZÉÈ\")] | //android.widget.Button[@text=\"Oui\"])[1]","context":"","multiple":true}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"(//android.widget.Button[@text=translate(\"Oui\",\"abcdefghijklmnopqrstuvwxyzéè\",\"ABCDEFGHIJKLMNOPQRSTUVWXYZÉÈ\")] | //android.widget.Button[@text=\"Oui\"])[1]","context":"","multiple":true}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding '(//android.widget.Button[@text=translate("Oui","abcdefghijklmnopqrstuvwxyzéè","ABCDEFGHIJKLMNOPQRSTUVWXYZÉÈ")] | //android.widget.Button[@text="Oui"])[1]' using 'XPATH' with the contextId: '' multiple: true
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[CLASS=android.widget.Button, INSTANCE=1]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements selector:UiSelector[CLASS=android.widget.Button, INSTANCE=1]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Selector ends with instance.
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [MJSONWP] Responding to client with driver.findElements() result: [{"ELEMENT":"23"}]
[HTTP] <-- POST /wd/hub/session/85bf921d-8be1-45b6-872f-6a52f3cb6160/elements 200 137 ms - 90 
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":[{"ELEMENT":"23"}]}
[HTTP] --> GET /wd/hub/session/85bf921d-8be1-45b6-872f-6a52f3cb6160/screenshot {}
[debug] [MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["85bf921d-8be1-45b6-872f-6a52f3cb6160"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/laure/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","ad071603092a1b2a4a","shell","/system/bin/rm","/data/local/tmp/screenshot.png;","/system/bin/screencap","-p","/data/local/tmp/screenshot.png"]
[debug] [ADB] Running '/Users/laure/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","ad071603092a1b2a4a","pull","/data/local/tmp/screenshot.png","/var/folders/s1/fscrgwn10ws3krxx7tw251lc0000gn/T/appium117417-22763-w969lo.t23uq2rzfr.png"]
[debug] [ADB] Device API level: 24
[debug] [MJSONWP] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAABDgAAAeACAYAAAArYecKAACAAElEQVR4AezBCWDP9f/A8efru+/ue27D5syx1lIpV0m5I7oQRZdUqH78pCRXKFRKp37lSuhgISQaac7cSs7cc2522v3+/76//b/57Guz67vtO3s/HoJ7gELTNE0rHEXuBK1IBM3xCblTODYRcqQUdiVCrpSiwETIlVLkTsiZouCEwlEUnKCVBYrcCWWYUG4IuVNojkTQcmFC0zRN0zRN0zRN0zStjDOhaZqmaZqmaZqmaZpWxpnQNE3TCk/QNE3TNE3TNM0BmNA0TdOKRriaoGnlgiJnCs1KKXKkFI5BcFyCVlYIORO0skKRM4WmlRkmNE3TtKITrhA0rVxRZKcoG5TiKkpRLJQiG6VwLEL+CYUn5J+glTVCdoJW1iiyU2iOSKHlwoymaZpmH4KmlVsKEEBRtihFiVEKREApHJMAitwJ9iFkUeRO0MoqARQgaGWVAgRQaI5MkUXQDMxomqZpmqbZgULLi1I4NqHkCJqjU1wh5J+glXUKraxQaFYCJjRN0zRN0zRN04wU2Sk0TdMcmwITmqZpmqZpmqZpVgpN07QyyYSmaZqmaZpWZihyptA0OxG0/xE0TStbTGiapmmapmlligIUWRSg+C+FptmPkJ2gaZrm8ExomqZpmqZpZZLi/yk0zf6ELEI5JGiaVvaY0bTyRAGCVhgKEDRNy4koHIISNDsThWMQ/qHQtJIjlGGC5igUIGjFQMidonQJ16awOzOaVh4orlCAoBWEIosii6BpmoUoHIooUIJmJ6JwHAoQNM3+hCsU+SdkUTgeQXMUiisUWQTNDoS8CaAoHUKpMKFp1zvF1RRafimuptA0TRQOSRSaHYjC8Sg0zb6E7IT8Ea4QHIugadc9If+Ekifkj2B3ZkqByWTCw8Mdi6Sky2RmZqJpmgNSaJpWFokCJWiFJArHpQBBu/64uLhQIcAfLy9PvL28sBWfkEBCQiIXo2NITU2l+AigyJ1w...
[HTTP] <-- GET /wd/hub/session/85bf921d-8be1-45b6-872f-6a52f3cb6160/screenshot 200 1599 ms - 235850 
[HTTP] --> POST /wd/hub/session/85bf921d-8be1-45b6-872f-6a52f3cb6160/elements {"value":"(//android.widget.Button[@text=translate(\"Oui\",\"abcdefghijklmnopqrstuvwxyzéè\",\"ABCDEFGHIJKLMNOPQRSTUVWXYZÉÈ\")] | //android.widget.Button[@text=\"Oui\"])[1]","sessionId":"85bf921d-8be1-45b6-872f-6a52f3cb6160","using":"xpath"}
[debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["xpath","(//android.widget.Button[@text=translate(\"Oui\",\"abcdefghijklmnopqrstuvwxyzéè\",\"ABCDEFGHIJKLMNOPQRSTUVWXYZÉÈ\")] | //android.widget.Button[@text=\"Oui\"])[1]","85bf921d-8be1-45b6-872f-6a52f3cb6160"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"(//android.widget.Button[@text=translate(\"Oui\",\"abcdefghijklmnopqrstuvwxyzéè\",\"ABCDEFGHIJKLMNOPQRSTUVWXYZÉÈ\")] | //android.widget.Button[@text=\"Oui\"])[1]","context":"","multiple":true}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"(//android.widget.Button[@text=translate(\"Oui\",\"abcdefghijklmnopqrstuvwxyzéè\",\"ABCDEFGHIJKLMNOPQRSTUVWXYZÉÈ\")] | //android.widget.Button[@text=\"Oui\"])[1]","context":"","multiple":true}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding '(//android.widget.Button[@text=translate("Oui","abcdefghijklmnopqrstuvwxyzéè","ABCDEFGHIJKLMNOPQRSTUVWXYZÉÈ")] | //android.widget.Button[@text="Oui"])[1]' using 'XPATH' with the contextId: '' multiple: true
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[CLASS=android.widget.Button, INSTANCE=1]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements selector:UiSelector[CLASS=android.widget.Button, INSTANCE=1]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Selector ends with instance.
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":[{"ELEMENT":"24"}]}
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [MJSONWP] Responding to client with driver.findElements() result: [{"ELEMENT":"24"}]
[HTTP] <-- POST /wd/hub/session/85bf921d-8be1-45b6-872f-6a52f3cb6160/elements 200 365 ms - 90 
[HTTP] --> POST /wd/hub/session/85bf921d-8be1-45b6-872f-6a52f3cb6160/element/24/click {"sessionId":"85bf921d-8be1-45b6-872f-6a52f3cb6160","id":"24"}
[debug] [MJSONWP] Calling AppiumDriver.click() with args: ["24","85bf921d-8be1-45b6-872f-6a52f3cb6160"]
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:click","params":{"elementId":"24"}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:click","params":{"elementId":"24"}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: click
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":true}
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [MJSONWP] Responding to client with driver.click() result: true
[HTTP] <-- POST /wd/hub/session/85bf921d-8be1-45b6-872f-6a52f3cb6160/element/24/click 200 3146 ms - 76 
[HTTP] --> POST /wd/hub/session/85bf921d-8be1-45b6-872f-6a52f3cb6160/elements {"value":"//android.widget.TextView[@text=\"BIENVENUE\"]","sessionId":"85bf921d-8be1-45b6-872f-6a52f3cb6160","using":"xpath"}
[debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["xpath","//android.widget.TextView[@text=\"BIENVENUE\"]","85bf921d-8be1-45b6-872f-6a52f3cb6160"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//android.widget.TextView[@text=\"BIENVENUE\"]","context":"","multiple":true}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//android.widget.TextView[@text=\"BIENVENUE\"]","context":"","multiple":true}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding '//android.widget.TextView[@text="BIENVENUE"]' using 'XPATH' with the contextId: '' multiple: true
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.3","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 12 ms - 83 
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.3","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 8 ms - 83 

When I click on screen manually, the test continue...  

Do you have an idea?? 

Thanks:)

**Comment by pekkaklarck** [comment]
This doesn't seem to be an issue in Robot Framework itself. If you suspect it's a bug in AppiumLibrary, please submit this to its own issue tracker. If this is more like a question how to use the library, please use robotframework-users mailing list or other such forums.
