### ISSUE TITLE
Robot framework test case timeout doesn't work consistently. 

### ISSUE THREAD

**Issue by arunku2x** [robotframework/robotframework#2596]
Hi,

Robot framework test case timeout doesn't work consistently.  In case there is an infinite loop in a python library keyword which is imported into the test case, test case doesn't timeout after invoking this keyword. 

My expectation from timeout is that this can prevent infinite hogging of the host machine even though imported library has infinite loop.

Could you please provide your comments on this topic.

Regards, 

Arun

**Comment by arunku2x** [comment]
As per robot framework documentation, timeout doesn't apply to steps in the teardown section.  Since it is possible that a library function called in teardown section contains a for loop, is it possible to implement a timeout applicable for the whole test case.

**Comment by pekkaklarck** [comment]
Stopping executing code is very hard and how Robot does it depends on the operating system and the Python interpreter. Unfortunately it isn't possible to do that reliably on all platforms.

If you want to have timeout in teardown, have a user keyword as a teardown and add timeout to it.

I don't think there's anything we can do to this issue.
