### ISSUE TITLE
I want a function that can let the failed case retry ,can you help me?

### ISSUE THREAD

**Issue by hqf007** [robotframework/robotframework#2597]
hello,
        I want a function that can let the failed case retry.
        when I type a command like ''pybot.bat --retry 3 e:\robot\test",one case is failed ,it can retry run this failed case and the max retry number is 3 ,so it can Improve the operational efficiency.
        it is very important for me and the others thats do the UI testing ,thanks very much.

**Comment by chriscallan** [comment]
There isn't anything in the API currently that does this, but I have done this very thing in one of my past projects.  System was very "twitchy", aka sensitive to small timing differences, and would fail/pass cases for no easily discernible reason.  Multiple passes on the same test worked great.
Basically, I created a bash script to drive the initial execution of the test set, then use a loop to re-execute the pybot command 'x' times with the flag --rerunfailed and a pointer to the last test results.
Worked like a charm on the project I used it for.

**Comment by pekkaklarck** [comment]
We've made a decision to keep test orchestration stuff like this outside the core framework. As @chriscallan commented, it's typically easy to create custom solutions for different needs. If someone is interested, implementing some kind of a generic re-execution tool would be possible too.
