### ISSUE TITLE
Dry Run fails if library keywords use embedded arguments

### ISSUE THREAD

**Issue by kormbrek-rally** [robotframework/robotframework#2599]
Reproduced in 2.9, 3.0.1, 3.0.2. Python 2.7.10 on OS X (10.12.4/Sierra)

When executing a dry run, keyword calls to library keywords with embedded arguments always fail with a message similar to:

> Keyword 'Library.Log ${number} Times' expected 1 argument, got 0.

If the test run is not a dry run, the keyword is called and executes as expected.

The [user guide](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#embedding-arguments-into-keyword-names) does not mention this shortcoming.

Below is a library and test suite, library, and command to reproduce:

Library.py
```
from robot.api.deco import keyword
@keyword("Log ${number} Times")
def log(number):
    for i in range(int(number)):
        print "Log #{}".format(i + 1)
```

Tests.robot
```
*** Settings ***
Library    Library.py
*** Test Cases ***
Bug
    Log 4 Times
```

Execute: `robot --dryrun Tests.robot`

**Comment by pekkaklarck** [comment]
Thanks for the report and an example making reproducing the problem easy. Apparently dry run wasn't taken into account when implementing the support for embedded arguments with library keywords. Luckily this seems to be easy to fix.

**Comment by kormbrek-rally** [comment]
Wow that was fast! Thank you Pekka!

**Comment by pekkaklarck** [comment]
No problem. As you can see the fix was pretty trivial. Not sure when 3.0.3 is out, though. I was hoping we wouldn't even need it and could start 3.1 development, but not it seems there are enough fixes/features to warrant one more minor release still.

**Comment by Abhiramborige** [comment]
Hii, thanks for the framework support. I got a small issue in the usage of embedded arguments. I request to please help me out.

In python file:
```python
class Temp:
def __init__(self):
    self.valid_methods = ['call_func1', 'call_func2']
    
@keyword('${function_name}', types=[str])
def process_call(self, function_name, *args, **kwargs):
     if function_name not in self.valid_methods:
            raise KeywordError(f"Keyword '{function_name}' not found.")
    print(function_name)
```

In robot file:
```robot
*** Settings ***
Library            Temp.py
*** Test Cases ***
[Demo1]
    Call_func1            123      123
[Demo2]
    blahblah           
```

When I execute normally, Demo2 gets failed. But when I use the dryrun option, even though "blahblah" keyword is not to be expected as a keyword, Demo2 is pass.
I want the list of valid_methods to be treated as valid methods along with parameter check in the dryrun, so that "blahblah" usage is detected as wrong usage and fails the dryrun.
