### ISSUE TITLE
Accessing nested list and dictionary variable items like `${var}[key][0]`

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#2601]
Currently it is possible to access list and dictionary variable items like `@{list}[0]` and `&{dict}[key]` but this syntax has two limitations:

1. It isn't possible to access nested values like `@{list}[0][2]` or `&{dict}[nested][key]`. A workaround is using the extended variable syntax to access the value like `${list[0][2]}` and `${dict['nested']['key']}` but this is somewhat ugly. Alternatively the internal value could be assigned to a separate variable but this is verbose:

    ```
    @{internal} =    Set Variable    @{list}[0]
    Log    @{internal}[2]
    &{nested} =    Set Variable    &{dict}[nested]
    Log    &{nested}[key]
    ```
 
2. The referred value is always used as a scalar, even if the value itself would be a list or dictionary. For example, these logs the internal list and dictionary themselves, not individual items in the containers:

    ```
    Log Many    @{list}[0]
    Log Many    &{dict}[nested}   
    ```

    A verbose workaround is, again, assigning the nested structure into a separate variable:

    ```
    @{internal} =    Set Variable    @{list}[0]
    Log Many    @{internal}
    &{nested} =    Set Variable    &{dict}[nested]
    Log Many    &{nested}
    ```

**Comment by pekkaklarck** [comment]
My proposal to fix the problems described in the original description is this:

1. Support accessing nested items in lists and dictionaries using syntax `${var}[x][y][z]` where the `x`, `y` and `z` are indices or keys, depending on is the referred value a list or a dictionary. For backwards compatibility reasons, we may consider accessing items only if the original `${var}` is a list or a dictionary.

2. Change the meaning of `@{var}[0]` to mean using variable `${var}[0]` as a list variable and `&{var}[key]` to mean using `${var}[key]` as a dictionary. This is backwards incompatible change and thus somewhat questionable. In my opinion it's worth it but requires graceful deprecation. I explain how I think it could be done in the next comment.

**Comment by pekkaklarck** [comment]
Changing the meaning of `@{var}[x]` and `&{var}[x]` is backwards compatible and requires graceful deprecation. My proposal is to do it like this:

1. In RF 3.0.3 add the support for using `${var}[x]` and also `${var}[nested][x]` with variables containing lists and dictionaries. Don't change `@{var}[x]` and &{var}[x]` syntax.

2. In RF 3.1 deprecate using `@{var}[x]` and &{var}[x]`. Issue a warning if the syntax is used but don't change the functionality yet.

3. In RF 3.2 change `@{var}[x]` and &{var}[x]` to mean using variable `${var}[x]` as a list or dictionary, respectively.

**Comment by aaltat** [comment]
I am pretty happy with the extended variable syntax. But I agree that it's quite painful to remember which way to write the square brackets in the variables. I think supporting `${var}[x][y][z]` is a good idea.

**Comment by ombre42** [comment]
This would be a good feature to have. Even with this new feature I would probably still use and advocate using extended variable syntax (using scalar prefix $) for accessing nested data.

- avoid confusion with varargs and kwargs
- avoid confusion over whether the arg will be converted to a string or use the variable value directly - i.e. if it starts with `${` and ends with `}`, no conversion

**Comment by DMCHatRally** [comment]
I think introducing backwards incompatibility over something that works but is "somewhat ugly" is unwarranted.  The ugliness is a personal perception, I, for one do not find this ugly at all and therefore would not support a compatibility breaking change to fix a non-issue.

**Comment by pekkaklarck** [comment]
I agree that backwards compatibility is important. I also think that consistency is important and in this case achieving it requires backwards incompatible change. In my opinion that's worth it especially if we handle deprecation gracefully. I'm willing to reconsider this if there are more people who disagree with it, though.

**Comment by pekkaklarck** [comment]
Somewhat related to this, we should also support assignment like

```
${var}[x] =    Keyword    args
${var}[x][y][z] =    Keyword    args
```
assuming that `${var}` exists and is a (nested) dict/list.

**Comment by bplimp** [comment]
+1 on this feature.  Would like to be able to access nested dictionary keys without having to reassign variables

**Comment by rdroog** [comment]
For me this change results in using:

`${xpathVariable}[not(contains(@class,'class'))]`

I get an error:

> Variable '${xpathVariable}' is string, not list or dictionary, and thus accessing item 'not(contains(@class,'class'))' from it is not possible.

I don't see why my old syntax was wrong (we are using it throughout our project), and there is no hint into how this syntax should be improved. Maybe it would be good to give at least some kind of hint (I'm now using catenate, but not sure if that's the best way to go).

**Comment by pekkaklarck** [comment]
Enhancing the error to mention escaping is a good idea. Could you submit an issue about it so that we don't forget it?

**Comment by wujie4620038** [comment]
HI, pekka, 

From this ticket, I see ${var}[x] is supported in version RF3.1. My robotframework version is 3.1.2 based on python3.6. However I encountered below issue when using the format "Should Be Equal    ${output}[1]    ${0}    Command returned non-zero code", while actual output is ['6cd6745c8df6ce19b4102ccecca03f7a1585c311', 0][0].
ute@rt316-nj:~/lfs-ci-test$ robot --variable CONSOLE:fzm --suite bluetooth fzm_tests/all_other
/opt/ute/python3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py:163: CryptographyDeprecationWarning: OpenSSL version 1.0.1 is no longer supported by the OpenSSL project, please upgrade. The next version of cryptography will drop support for it.
  utils.CryptographyDeprecationWarning
==============================================================================
All Other :: LFS CI test initialization.                                      
==============================================================================
Running common setup for suites
ncat found OK (/usr/bin/ncat)
console found OK (/usr/bin/console)
Common setup for suites completed!
All Other.Bluetooth :: Bluetooth unit tests.                                  
==============================================================================
Verify Bluetooth Service Activation Through Dbus                      | FAIL |
Command returned non-zero code: ['', 0][1] != 0
------------------------------------------------------------------------------
Test Reset and Check Bluetooth                                        | PASS |
------------------------------------------------------------------------------
All Other.Bluetooth :: Bluetooth unit tests.                          | FAIL |
2 critical tests, 1 passed, 1 failed
2 tests total, 1 passed, 1 failed
==============================================================================
Running common teardown for suites
All Other :: LFS CI test initialization.                              | FAIL |
2 critical tests, 1 passed, 1 failed
2 tests total, 1 passed, 1 failed
==============================================================================
Output:  /home/ute/lfs-ci-test/output.xml
Log:     /home/ute/lfs-ci-test/log.html
Report:  /home/ute/lfs-ci-test/report.html
ute@rt316-nj:~/lfs-ci-test$ 
ute@rt316-nj:~/lfs-ci-test$ 
ute@rt316-nj:~/lfs-ci-test$ 
ute@rt316-nj:~/lfs-ci-test$ ls -l venv/lib/python3.6/s
shutil.py         site-packages/    site.py           sre_compile.py    sre_constants.py  sre_parse.py      stat.py           struct.py         
ute@rt316-nj:~/lfs-ci-test$ cd venv/lib/python3.6/site-packages/
ute@rt316-nj:~/lfs-ci-test/venv/lib/python3.6/site-packages$ ls -l
total 796
drwxr-xr-x. 3 ute ute     87 May 14 11:13 bcrypt
drwxr-xr-x. 2 ute ute    131 May 14 11:13 bcrypt-3.1.3.dist-info
drwxr-xr-x. 3 ute ute   4096 May 14 11:13 cffi
drwxr-xr-x. 2 ute ute    155 May 14 11:13 cffi-1.11.4.dist-info
-rwxr-xr-x. 1 ute ute 731352 May 14 11:13 _cffi_backend.cpython-36m-x86_64-linux-gnu.so
drwxr-xr-x. 5 ute ute    144 May 14 11:13 cryptography
drwxr-xr-x. 2 ute ute    131 May 14 11:13 cryptography-2.8.dist-info
-rw-r--r--. 1 ute ute     33 May 14 15:31 easy-install.pth
-rw-r--r--. 1 ute ute    126 May 14 15:30 easy_install.py
drwxr-xr-x. 4 ute ute    265 May 14 11:13 nacl
drwxr-xr-x. 3 ute ute   4096 May 14 11:13 paramiko
drwxr-xr-x. 2 ute ute    150 May 14 11:13 paramiko-2.7.1.dist-info
drwxr-xr-x. 5 ute ute     95 May  9 16:49 pip
drwxr-xr-x. 2 ute ute    130 May  9 16:49 pip-18.1.dist-info
drwxr-xr-x. 5 ute ute     94 May  9 15:23 pkg_resources
drwxr-xr-x. 2 ute ute     93 May 14 11:13 __pycache__
drwxr-xr-x. 4 ute ute    271 May 14 11:13 pycparser
drwxr-xr-x. 2 ute ute    131 May 14 11:13 pycparser-2.10.dist-info
drwxr-xr-x. 2 ute ute    131 May 14 11:13 PyNaCl-1.1.2.dist-info
drwxr-xr-x. 4 ute ute     35 May 14 15:31 robotframework-3.1.2-py3.6.egg
drwxr-xr-x. 2 ute ute    118 May 14 11:13 robotframework_scpcompat-0.1.0.dist-info
drwxr-xr-x. 2 ute ute    106 May 14 11:17 robotframework_sshlibrary-3.4.0.dist-info
drwxr-xr-x. 2 ute ute    131 May 14 11:13 scp-0.13.2.dist-info
drwxr-xr-x. 3 ute ute     62 May 14 11:13 SCPLibrary
-rw-r--r--. 1 ute ute  20255 May 14 11:13 scp.py
drwxr-xr-x. 6 ute ute   4096 May 12 15:04 setuptools
drwxr-xr-x. 2 ute ute    199 May 14 15:29 setuptools-21.2.1.dist-info
drwxr-xr-x. 2 ute ute    170 May 14 15:31 setuptools-40.6.3.dist-info
drwxr-xr-x. 2 ute ute    131 May 14 11:13 six-1.10.0.dist-info
-rw-r--r--. 1 ute ute  30098 May 14 11:13 six.py
drwxr-xr-x. 3 ute ute   4096 May 14 11:17 SSHLibrary
drwxr-xr-x. 7 ute ute   4096 May 12 15:04 wheel
drwxr-xr-x. 2 ute ute    174 May 14 15:29 wheel-0.29.0.dist-info
drwxr-xr-x. 2 ute ute    130 May 14 15:31 wheel-0.33.6.dist-info

Is it related with python version for robotframework during using? If I changed it to ${output[1]}, then the case could be passed.

Thanks in advance.

**Comment by wujie4620038** [comment]
Hi， 
 I  have solve this issue by myself, it is because I ran it in wrong path with another RF version 3.0.4.  
Thanks.

**Comment by wujie4620038** [comment]
Hi， 
 I  have solve this issue by myself, it is because I ran it in wrong path with another RF version 3.0.4.  
Thanks.
