### ISSUE TITLE
Gherkin style embedded variables is not working with builtin library keyword like Log

### ISSUE THREAD

**Issue by vairamsvsjdo** [robotframework/robotframework#2602]
Gherkin style embedded variables is not working with spaces, but works with |
from source control below: 

1. gherkin.robot and gherkin.3.rst is working
2. gherkin.1.robot and gherkin.2.rst are not working.

https://github.com/vairamsvsjdo/gherkinstyle-robot

**Comment by vairamsvsjdo** [comment]
i updated the commits. Identified the problem that there were mix use of formatting within a keyword.
However, I found that unable to use gherkin style with builtin keywords.
Is this expected behavior?

**Comment by pekkaklarck** [comment]
Could you clarify what works and what doesn't? What error do you get?

**Comment by vairamsvsjdo** [comment]
Error Message: No keyword with name 'Log "another then keyword"' found.

All keywords written works except the following keyword that makes a gherkin style call to a built in keyword.
| Validate builtin with gherkin call
| | Log "another then keyword"

Two cases:
working: Example of how to use keyword with embedded arguments working
not working Example of how to use keyword with embedded arguments NOT working


| Example of how to use keyword with embedded arguments NOT working
| | Given Todo "value1" expected
| | ${output}= | When user "bob" is logged in with the following password: "superSecret!"
| | And Variable at the end kw "value1"
| | And Variable in "value1" "value2" the middle continuous
| | And Variable in the end continuous "value1" "value2"
| | Then Variable "${output}" is correct
| | Then Keywords below this keywords fail
| | Then Validate "${output}" calling another keyword
| | Then Validate builtin with gherkin call

**Comment by vairamsvsjdo** [comment]
updated the script to use 4 spaces instead of pipe.
This KW works:
Validate "${arg1}" calling another keyword at end
    Variable at the end kw "${arg1}"

This KW fails:
Validate builtin with gherkin call "${arg1}"
    Log "${arg1}"

Example of how to use keyword with embedded arguments working
    Given Todo "value1" expected
    ${output}=    When user "bob" is logged in with the following password: "superSecret!"
    And Variable at the end kw "value1"
    And Variable in "value1" "value2" the middle continuous
    And Variable in the end continuous "value1" "value2"
    Then Variable "${output}" is correct
    Then Validate "${output}" calling another keyword
    Then Validate "${output}" calling another keyword at end
    
Example of how to use keyword with embedded arguments NOT working
    Given Todo "value1" expected
    ${output}=    When user "bob" is logged in with the following password: "superSecret!"
    And Variable at the end kw "value1"
    And Variable in "value1" "value2" the middle continuous
    And Variable in the end continuous "value1" "value2"
    Then Variable "${output}" is correct
    Then Validate "${output}" calling another keyword
    Then Validate "${output}" calling another keyword at end
    Then Validate builtin with gherkin call "successful"

**Comment by pekkaklarck** [comment]
Could you please tell what error you get? Also, could you reformat the examples? See here for information about the supported syntax:
https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown

**Comment by vairamsvsjdo** [comment]
No keyword with name 'Log "${arg1}"' found.

stylized :
https://github.com/vairamsvsjdo/gherkinstyle-robot/blob/master/gherkin.4.robot

Example of how to use keyword with embedded arguments NOT working
    Given Todo "value1" expected
    ${output}=    When user "bob" is logged in with the following password: "superSecret!"
    And Variable at the end kw "value1"
    And Variable in "value1" "value2" the middle continuous
    And Variable in the end continuous "value1" "value2"
    Then Variable "${output}" is correct
    Then Validate "${output}" calling another keyword
    Then Validate "${output}" calling another keyword at end
    Then Validate builtin with gherkin call "successful"

**Comment by pekkaklarck** [comment]
Have you defined a keyword that ought to match `Log "${arg1}"`? If you try to use the BuiltIn `Log` keyword, you need to pass the message to it as a positional argument like `Log    ${arg}`.

**Comment by vairamsvsjdo** [comment]
Ok, I identified what the problem is. Gherkin style does not work with Keywords having [Arguments].
