### ISSUE TITLE
There should be a way to mark known failures and they should be reported as XFAIL

### ISSUE THREAD

**Issue by baid86** [robotframework/robotframework#2604]
I did lot of research but could not found a convenient way of marking a test as XFAIL. 
I am pretty sure there must have been some though around it but Just wondering why its not been implemented.

There could be something under setting OR there could be keyword which can allow to set test status as XFAIL.
I am not sure if it can be done by using ResultWriter but that could also be an alternative.

**Comment by pekkaklarck** [comment]
What is XFAIL? I've never heard about it earlier.

**Comment by baid86** [comment]
XFAIL is expected Failure. For example we have test which fails and there is defect for it. So in next run I may will expect it to Fail. I need not to analyze the failures which are XFAIL. Rather while analyzing the failure I would only focus only on New Failures.

**Comment by pekkaklarck** [comment]
I see. With Robot Framework the approach you can take is using tags. You could use something like `xfail`, `known-issue`, `bug` and possibly add the defect id into it like `xfail-243` or `bug: 243`. You can then use `--noncritical` option to mark these tests non-critical. See the User Guide for details.

**Comment by baid86** [comment]
Thats exactly I have thought of doing as a workaround.
