### ISSUE TITLE
Content Security Policy (CSP) causes problems with report

### ISSUE THREAD

**Issue by PeerMueller** [robotframework/robotframework#2606]
I noticed a javascript error in report.html when [Content Security Policy](https://content-security-policy.com/) (CSP) is enabled and "sandbox allow-same-origin" is not set. CSP is activated in Jenkins by default since Jenkins 1.641 / Jenkins 1.625.3.

When clicking a tag in the report.html the report output should be filtered by the selected tag and the result shown below "Test Details". However with recent browsers (Edge & Firefox 48+) the result remains empty and the Console shows the error "SecurityError: The operation is insecure.".

As a workaround this can be circumvented by disabling CSP or setting "sandbox allow-same-origin". 

However, the javascript should not fail at this point only because the access to the browser's localStorage is prevented. The report should still work and be more robust in this case.

I have created a fix and will add a pull request.

**Comment by pekkaklarck** [comment]
This is definitely bad behavior and needs to be fixed.
