### ISSUE TITLE
[Help] How test library get current running test suite name?

### ISSUE THREAD

**Issue by luisxiaomai** [robotframework/robotframework#2612]
Hi guys,

I have a test suite which imports my custom test library, if I can get my test suite name in test library when the test suite is running?  

Thanks.
B.R.

**Comment by bkhouri** [comment]
The suite name, and even the test name, is made available via automatic variables. http://robotframework.org/robotframework/3.0/RobotFrameworkUserGuide.html#automatic-variables

You should be able to use the `BuilIt().get_variable_value("${SUITE NAME}")` to get the suite name, or `BuilIt().get_variable_value("${TEST NAME}")` to get the test case name.

**Comment by luisxiaomai** [comment]
@bkhouri , great. It solved my problem, thanks a lot.
