### ISSUE TITLE
SSHLibrary Import Error

### ISSUE THREAD

**Issue by rishabhjohn001** [robotframework/robotframework#2614]
Whenever i try to add SSHLibrary in robotframework , it gives me an error. Although the SSHLibrary is pre-installed using pip install robotframework-sshlibrary
![error_sshlibrary](https://user-images.githubusercontent.com/24391452/27022658-8eb5b1b0-4f6c-11e7-84c1-28ce86334829.JPG)

**Comment by vanpire110** [comment]
I also met this in ubuntu, it seemed that "pip install robotframework-sshlibrary" did not work well.
I fixed this after I installed paramiko and pycrypto.

**Comment by rishabhjohn001** [comment]
@vanpire110 Even after installing paramiko and pycrypto modules explicitly i am facing the same error .
It is showing the unicodedecode error.
![capture](https://user-images.githubusercontent.com/24391452/27033291-48f11686-4f96-11e7-8662-337eeeffe21b.JPG)

**Comment by pekkaklarck** [comment]
Does this happen also when using Robot Framework only or only when using RIDE? In the latter case this belongs to RIDE's tracker, not here.

**Comment by vanpire110** [comment]
I suggest that you can use "import SSHLibrary" in python shell, then you can get more detail logs, It seems that you did not install other libs that leads the sshlibrary import error.

**Comment by xrcm** [comment]
These are the dependencies of ssh library (with install order...)
(useful if you have no direct internet to install... (without pip))

pycparser-2.17.tar.gz
enum34-1.1.6-py2-none-any.whl
cffi-1.10.0-cp27-cp27m-win_amd64.whl
ipaddress-1.0.18-py2-none-any.whl
idna-2.5-py2.py3-none-any.whl
asn1crypto-0.22.0-py2.py3-none-any.whl
cryptography-1.9-cp27-cp27m-win_amd64.whl
pyasn1-0.2.3-py2.py3-none-any.whl
paramiko-2.1.2-py2.py3-none-any.whl
robotframework-sshlibrary-2.1.3.tar.gz

**Comment by pekkaklarck** [comment]
Doesn't look like Robot issue.
