### ISSUE TITLE
copy files doesnt work as expected

### ISSUE THREAD

**Issue by ImmoWetzel** [robotframework/robotframework#2616]
Ubuntu:16:04, RF 3.0.2, Python 2.7.12
I like to copy a file from /tmp/RIDEhjkhj to a CIFS mount share /mnt/bla/blubb/

but Robot fails although a cp in user shell works fine

KEYWORD os . Copy Files ${OUTPUT_DIR}/*.drf, ${QCtestResultDir}
Documentation: 	

Copies specified files to the target directory.
Start / End / Elapsed: 	20170614 11:40:06.312 / 20170614 11:40:06.394 / 00:00:00.082
11:40:06.312 	TRACE 	Arguments: [ '/tmp/RIDErUiPpD.d/*.drf' | '/mnt/bla/blubb/' ] 	
11:40:06.392 	TRACE 	Return: None 	
11:40:06.393 	FAIL 	OSError: [Errno 1] Operation not permitted: '/mnt/bla/blubb/tmpZcSejT/TestResult.drf' 	
11:40:06.393 	DEBUG 	Traceback (most recent call last):
  File "/usr/lib/python2.7/shutil.py", line 120, in copy
    copymode(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 91, in copymode
    os.chmod(dst, mode)

And why robot likes to use a subdir .../tmpabc/.. first ?

**Comment by pekkaklarck** [comment]
1. Do you run Robot as the same user as that you tested this with `cp`?

2. `Copy Files` uses Python's `shutil.copy` to copy the file into the destination file system. Does using that work for you?

3. See comments at https://github.com/robotframework/robotframework/blob/master/src/robot/libraries/OperatingSystem.py#L788 and issue #1502 for details about why the file is first copied into a temporary directory. I doubt that it is related to this problem but you never know.

**Comment by pekkaklarck** [comment]
No new info since last summer. Closing.
