### ISSUE TITLE
set test variable doesnt work with keywords

### ISSUE THREAD

**Issue by ImmoWetzel** [robotframework/robotframework#2617]
robotframework==3.0.2

set test variable doesnt work with keywords
These both test fail after changeVar

*** Test Cases ***
test
    [Setup]    tsetup
    log    ${var1}
    log    ${var2}
    Run Keyword unless    "${var1}"=="1"    Fail    var1 not equal
    Run Keyword unless    "${var2}"=="2"    Fail    var2 not equal
    ${var1}    Set Variable    3
    Run Keyword unless    "${var1}"=="3"    Fail    var1 not equal
    log    ${var1}
    changeVar
    log    ${var1}
    Run Keyword unless    "${var1}"=="4"    Fail    var1 not equal
    [Teardown]    tteardown

test2
    [Setup]
    ${var1}    Set Variable    1
    Set Test Variable    ${var1}
    Set Test Variable    ${var2}    2
    log    ${var1}
    log    ${var2}
    Run Keyword unless    "${var1}"=="1"    Fail    var1 not equal
    Run Keyword unless    "${var2}"=="2"    Fail    var2 not equal
    ${var1}    Set Variable    3
    Run Keyword unless    "${var1}"=="3"    Fail    var1 not equal
    log    ${var1}
    changeVar
    log    ${var1}
    Run Keyword unless    "${var1}"=="4"    Fail    var1 not equal
    [Teardown]    tteardown

*** Keywords ***
tsetup
    ${var1}    Set Variable    1
    Set Test Variable    ${var1}
    Set Test Variable    ${var2}    2

tteardown
    Run Keyword unless    "${var2}"=="2"    Fail    var1 not equal

changeVar
    log    ${var1}
    ${var1}    Set Variable    4
    log    ${var1}

**Comment by aaltat** [comment]
Gave a short explanation why this happens[1]. But I think the documents could be enhanced because I think it's not explained when the variable scope is lost.

[1] https://groups.google.com/forum/m/#!topic/robotframework-users/PZ2YlDLpCz4

**Comment by ImmoWetzel** [comment]
not a bug
