### ISSUE TITLE
When variable scope is removed is not clearly documented

### ISSUE THREAD

**Issue by aaltat** [robotframework/robotframework#2618]
When variable is created with `global/suite/test` scope it's not clearly documented that using the `Set Variable` keyword clears the previously defined scope

**Comment by aaltat** [comment]
I did look the documents and I found some explanations in: http://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Set%20Variable http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#using-set-test-suite-global-variable-keywords and http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#variable-scopes

At least the BuildIn keyword documentation could explicitly say that if variable did have global/suite/test scope, it is removed. Now it's implied but may people may not understand the document.

But should it be mentioned also in somewhere else too? Should the user guide say something more generic that scope may be also lost, in certain conditions?

**Comment by aaltat** [comment]
Discussed originally in user group: https://groups.google.com/forum/m/#!topic/robotframework-users/PZ2YlDLpCz4

**Comment by pekkaklarck** [comment]
It would be wrong to say that test/suite/global variable is removed. What happens is that a local variable ia created and it shadows the variable in the higher scope. I doubt BuiltIn docs are the correct place to explain this because the same happens with all kws returning values. Docs in the UG related could be enhanced, though.

**Comment by pekkaklarck** [comment]
This documented in the [Variable priorities](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#variable-priorities) section:

> Variables set during the test execution either using return values from keywords or using Set Test/Suite/Global Variable keywords always override possible existing variables in the scope where they are set. In a sense they thus have the highest priority, but on the other hand they do not affect variables outside the scope they are defined.

I consider that good enough. If others disagree and have ideas how the docs could be enhanced, this issue can be reopened.
