### ISSUE TITLE
Press Key is not working as argument for run_keyword function if send 'Enter' (\13)

### ISSUE THREAD

**Issue by SerhiiAksiutin** [robotframework/robotframework#2619]
test.robot
```
*** Settings ***
Documentation     This test will ...
Library           Selenium2Library
Library           keywords.py
Test Teardown     Close All Browsers

*** Test Cases ***
    Create Webdriver  Safari  executable_path=${technology_preview}
    Maximize Browser Window
    Set Selenium Speed  .5 seconds
    Go to  http://google.com
    Search it
```

keywords.py
```
from robot.libraries.BuiltIn import BuiltIn
import pdb

bi = BuiltIn()
s2l = bi.get_library_instance('Selenium2Library')

def search_it():
    bi.run_keyword('Input Text', 'id=lst-ib', 'biology')
    bi.run_keyword('Press Key', 'id=lst-ib', '\13') # does nothing! Expected: It should press "Enter" key
    pdb.set_trace()
```

**Comment by pekkaklarck** [comment]
This seems to be related to Selenium2Library and belongs to its issue tracker.

**Comment by bmartyniuk** [comment]
@SerhiiAksiutin the ASCII code of enter key is \\13

**Comment by pekkaklarck** [comment]
Yeah, on a closer look that problem is that `\` is an escape character in Python and `\13` is actually same as `\x0b` i.e. byte 13. As commented above, you need to escape `\` and use `\\13` instead.

**Comment by SerhiiAksiutin** [comment]
I have tried both \ and \\ before posting it here. Same actual result.

**Comment by SerhiiAksiutin** [comment]
Already double checked it on 3 different sites for 3 different browsers. It is not working if it sent by `run_keyword()` function

`bi.run_keyword('Input Text', 'xpath=//*[@id="q"]', anything)`
`bi.run_keyword('Press Key', 'xpath=//*[@id="q"]', '\\13')`

Actual output/result:
`[ INFO    ] Wait until element 'xpath=//*[@id="q"]' is visible.`
`[ INFO    ] Typing text 'lipstick' into text field 'xpath=//*[@id="q"]'`
`[ INFO    ] Wait until element 'xpath=//*[@id="q"]' is visible.`

Pass. No enter key was pressed

**Comment by PraveenYarraguntlaTR** [comment]
I tried similar approach.

Press Key  xpath=//input[@name='metadatastate']  \\13


Still Enter is not working on input text filed.
