### ISSUE TITLE
${SUITE SOURCE} enhancement

### ISSUE THREAD

**Issue by claytonneal** [robotframework/robotframework#2624]
Hiya, 
the automatic variable:
"{SUITE SOURCE} An absolute path to the suite file or directory. "
is it possible to make this definite by adding a new automatic variable like
${SUITE DIRECTORY}, ${SUITE FILE}
The reason being we need ${SUITE DIRECTORY} is that we store XLS files in the same dir as the .robot file and need to build an absolute path to them
Thanks

**Comment by pekkaklarck** [comment]
I don't think adding these variables would bring enough benefits. You typically can use `${CURDIR}` in cases like these and it's also easy to split `${SUITE SOURCE}` into directory and file name using, for example, OperatingSystem keywords.

**Comment by Tattoo** [comment]
Another option is to have these kind of additional files in a folder and you introduce the absolute path to it in the test execution. This way, you always have one simple way to refer to the files.

For example:
`robot --variable XLS_DIR:/path/to/folder my_tests/`
