### ISSUE TITLE
Suite variable defined in parent suite setup not recognized in children suite

### ISSUE THREAD

**Issue by geyzer63** [robotframework/robotframework#2628]
In the following test structure, suite variable _FOO_ is not recognized in _ChildFile.robot_ suite
```
ParentSuite
|--> __init__.robot
|       *** Settings ***
|       Resource    foo_resource.robot
|       Suite Setup    Foo Setup
|--> foo_resource.robot
|       *** Settings ***
|       Library    BuiltIn
|
|       *** Keywords ***
|       Foo Setup
|           Set Suite Variable    ${FOO}    foo
|
|--> ChildSuite 
|----> ChildFile.robot
|       *** Settings ***
|       Resource    ../foo_resource.robot
|
|       *** Test Cases ***
|       Foo Test
|           Log To Console    Show suite variable ${FOO}
 ```
Executing _ParentSuite_, _ChidSuite_ or _ChildFile.robot_ resuls in error
```
Foo Test                                                              | FAIL |
Variable '${FOO}' not found.
```
Suite tree attached
[SuiteVariableBug.zip](https://github.com/robotframework/robotframework/files/1108222/SuiteVariableBug.zip)

**Comment by pekkaklarck** [comment]
Existing functionality provided by Set Suite Variable ought to already cover this:
http://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Set%20Suite%20Variable

**Comment by geyzer63** [comment]
@pekkaklarck It works within a file suite - but in the structure described above it fails. It is a scope issue.

Could you please try my example?

**Comment by pekkaklarck** [comment]
Did you read the documentation I linked above? Especially the bit about using the special `children` argument?

**Comment by bkhouri** [comment]
I agree with @pekkaklarck  that this is a test issue.  Read the documentation related to the `Set Suite Variable` keyword.

**Comment by geyzer63** [comment]
@pekkaklarck, sorry - missed that part

**Comment by pdumais** [comment]
For those looking for the example requested by OP:
In my test setup, I set: 
`Set Suite Variable      ${var_to_use_in_suite}   ${var_defined_in_init}    children=true`
