### ISSUE TITLE
page title check failed in python3

### ISSUE THREAD

**Issue by sleagon** [robotframework/robotframework#2629]
```
    [Arguments]   ${SERVER}=http://www.baidu.com    ${BROWSER}=Chrome
    [Documentation]    this is a test documents
    Open Browser    ${SERVER}    ${BROWSER}
    Title Should Be    百度一下，你就知道
    Input word   test
    Submit word
    Title Should Be    test_百度搜索 //this line failed...

```
should i wait for some seconds when jumping to another page?

by the way, python3 and chrome, vsersion 59,  are used in this test.

**Comment by sleagon** [comment]
i just added a delay to s2l,  the keywords passed...

is there any switcher for testing the case until page fully loaded?

**Comment by pekkaklarck** [comment]
This issue tracker is for RF itself, S2L issues belong to its own tracker. Questions are best sent to robotframework-users list, Slack or other such forums.
