### ISSUE TITLE
Getting message Connect to [endpoint]:443 failed: Connection refused: connect to external server in robot framework script

### ISSUE THREAD

**Issue by Riyakk** [robotframework/robotframework#2630]
Getting message IO exception: Connect to [endpoint]:443 failed: Connection refused: connect to external server in robot framework script

Create session    DP    URL    debug=True    verify=False
${resp} = Get Request    DP    URL
Should be equal as strings    ${resp.json ["groupHeader"]["httpCode"]}    200.0

When I run the above script then am getting below error
**IO exception. Message: Connect to URL:443 [URL] failed: Connection refused: connect**

The above URL I am trying to connect outside of our work network. Can anyone please have look  and provide a fix or workaround solution. Thanks

**Comment by pekkaklarck** [comment]
This doesn't seem to be related to Robot Framework core or any of the standard libraries distributed with it. Please submit the issue to issue tracker of the relevant test library.
