### ISSUE TITLE
maximum call stack size exceeded error in chrome using jquery templates

### ISSUE THREAD

**Issue by lanquarden** [robotframework/robotframework#2631]
I use the jquery templates to log some array data, this works as expected for small arrays but when the array size increases the _maximum call stack size exceeded_ error is thrown in chrome.

The issue is explained in more detail in https://stackoverflow.com/questions/15908000/maximum-call-stack-size-exceeded-error-in-chrome-using-jquery-templates

I attached a minified jquery template library with this fix implemented:
[jquery.tmpl.min.js.zip](https://github.com/robotframework/robotframework/files/1124471/jquery.tmpl.min.js.zip)

**Comment by Tattoo** [comment]
I don't think this is at all related to Robot Framework. If I'm misunderstanding and it is a problem with Selenium2Library, please create that issue to [that library's issue tracker](https://github.com/robotframework/Selenium2Library/issues)

**Comment by lanquarden** [comment]
As far as I understand, the jquery.tmpl library included in the produced html logs comes from src/robot/htmldata/lib/jquery.tmpl.min.js. The jquery tmpl library is not under active development as far as I could see. Neither did I find it fixed somewhere.

That's why I suggest updating the file with the fixed one provided.
