### ISSUE TITLE
How to Import Variables at Local Test Scope

### ISSUE THREAD

**Issue by jwasserzug** [robotframework/robotframework#2635]
I would like to be able to import variables into the local scope of a test case. This is to prevent other test cases from accidentally using variables imported by a different test. Is this possible? 

Currently "import variables" imports the variables inside the suite scope
```
*** Test Cases ***
Test1
    # var1.py has the variable 'var' defined
    import variables  /home/var1.py
    log  ${var}

Test2
   # I would like to this fail
    log  ${var}
```

**Comment by pekkaklarck** [comment]
This isn't possible. If you only have few variables, you can easily create a keyword that returns the needed values:

```
${var1}    ${var2} =    Keyword
