### ISSUE TITLE
Drop Down Value with Opostrophe not Selected - Issue with Opostrophe

### ISSUE THREAD

**Issue by vanaokar** [robotframework/robotframework#2636]
We need Select Value from Drop Down. So we are using text with apostrophe in it - example ****EXAMINER'S REPORT**** We tried all the option like Backlash, putting in Double Quotes but in vain. We hard coded the Index value, but didn't pick up. It picks up other value with normal text.   So we thought it could be Robot Issue.

**Comment by trogdor259** [comment]
You need to take this to the [selenium2library](https://github.com/robotframework/Selenium2Library) github

**Comment by pekkaklarck** [comment]
Yeah, wrong issue tracker.
