### ISSUE TITLE
Update Button Popup Window on IE sometimes sometimes click and sometimes doesn't click

### ISSUE THREAD

**Issue by vanaokar** [robotframework/robotframework#2637]
We need IE to run application and on IE Browser we get "Update" mandatory which is normal function required for our application. However it has some issue with it.
Update Button Issue works differently on different operation system version
Windows 7
: FOR	${index}	IN RANGE	1	26
	Send Tab Key			
Send Enter Key	
--------------------------------------------------------------------------------------------------------------------------
Windows 10
This code works good for windows 10 and not Windows 7. But it doesn’t 
not always necessarily clicks the button for Windows
Select Window	{Window Name}	
Press Key	xpath=//*[@name='update']	\\13
However, the above code doesn’t work for windows 7 doesn’t work for windows 10.

[Update Button Issue works differently on different operation system version.docx](https://github.com/robotframework/robotframework/files/1163697/Update.Button.Issue.works.differently.on.different.operation.system.version.docx)

**Comment by trogdor259** [comment]
You need to take this to the [selenium2library](https://github.com/robotframework/Selenium2Library) github

**Comment by pekkaklarck** [comment]
Yeah, wrong issue tracker.
