### ISSUE TITLE
Implicitly convert "True" and "False" to bool when passed from the command line

### ISSUE THREAD

**Issue by Alexspayne** [robotframework/robotframework#2638]
I'm considering submitting a PR that will have any variable passed with the string value "True" or "False" from the command line to Python's bool objects True and False.

`robot -v my_var:True .`
at present will set ${my_var} to the string "True".
I'm proposing that instead it set ${my_var} to the bool type object True (or False, for "False").

I'm uncertain if this change would be considered, so I would like feedback on this idea before I write up the PR.

**Comment by boakley** [comment]
This would be backwards-incompatible. It would make it impossible to pass the literal string "True" or "False".

My recommendation is to change the argument parsing to allow for type hints. For example:

    robot -v my_var:bool:True ...

While that still has backwards compatibility issues, the chances are very slim that it would affect anyone. The only people it affects would be people trying to pass the literal string "bool:True" on the command line. That can be solved by using a new argument, e.g.  `robot --typedvariable my_var:bool:True ...` , which would be 100% backwards-compatible.

**Comment by Alexspayne** [comment]
Thanks for taking the time to share this solution.
It seems like this requirement is unique to me and that the general consensus in the community is to handle the string conversion at the library level.  Because of that, I decided to implement a workaround using variable files and not to try modifying robot itself.

**Comment by pekkaklarck** [comment]
As discussed on the mailing list earlier, we prefer passing strings as-is and keywords converting them to other types if needed. That's how keywords work as well. In the test data you can then also use variables to pass non-string values, and we could consider supporting variables also on the command line. For example, Robot's built-in variable `${TRUE}` could be used to create a variable with a Boolean value like `--variable 'my_var:${TRUE}'`. If that's desired, a separate issue can be submitted.
