### ISSUE TITLE
Lists Should Be Equal    @{testcasenames_3}    @{testcasenames_3} Failing

### ISSUE THREAD

**Issue by MsDcross** [robotframework/robotframework#2639]
I'm comparing two lists or trying to.  I  couldn't understand the failure so I compared the same variable
it failed saying the lengths are different

Lengths are different: 34 != 33

list content is

[ QueryNamesAndTags.TestCases.Test 1 | QueryNamesAndTags.TestCases.Test2 ]

**Comment by trogdor259** [comment]
is there supposed to be a space between Test and 1? Because there is and the space will add to the length.

**Comment by terokinnunen** [comment]
When comparing lists, you need to pass list variables as `${list}`. If you pass it as `@{list}`, it will become expanded so that first item in list will be first argument and so on.

    Lists should be equal   ${testcasenames_3}    ${testcasenames_3}

**Comment by pekkaklarck** [comment]
This is exactly how using the list variable syntax `@{var}` works. As @terokinnunen already explained, you need to refer to the variable as a scalar like `${var}`. See the Variables section in the Robot Framework User Guide for more details.
