### ISSUE TITLE
need to support run [FOR LOOP] in [Run Keyword If]

### ISSUE THREAD

**Issue by wuwentao** [robotframework/robotframework#2641]
Robot can support this format:
```

:FOR     ${var}      IN     @{values}
\\      Run Keyword IF     '${var' == 'EXIT' .     EXIT For Loop
\\      Do Something         ${var}

```
But how to support run  [FOR LOOP] in [Run Keyword If] :

```
Run Keyword IF    "${var_list}"  is not "${None}"       :FOR     ${var} .   IN .   ${var_list}
...                                                                                     \\      Do Something         ${var}
ELSE                    Do Nothing
```

seems robot can't support add for loop after `run keyword if` ?  
as I don't want to add more keywords, it's really a very simple line.

Why I need this feature?
1.  I'm writing more keywords with this format, the input keyword argument will have  empty vaule/list value
2.  In my keyword content,I need to do check ,if the value is not None, then do `for loop` to use the list value in `${var}`
3.  if the value is None, do nothing.

We have too many this types keywords, I know we can add for loop in another keyword and add this keyword after `run keyword if ` , it just can work for 1 or 2 keywords,  if we need to write 20+ keyword in this format, we will add 40+ keywords to do it?
seems it's not a good solution.

Thanks!
Wentao

**Comment by trogdor259** [comment]
Create a keyword containing your for loop then call that keyword in the RUN KEYWORD IF keyword.

**Comment by wuwentao** [comment]
We have too many this types keywords, I know we can add for loop in another keyword and add this keyword after run keyword if , it just can work for 1 or 2 keywords, if we need to write 20+ keyword in this format, we will add 40+ keywords to do it?
seems it's not a good solution.

**Comment by pekkaklarck** [comment]
I don't think this would be a good idea. Implementation would be pretty complex and resulting test data wouldn't be too clear either. As @trogdor259 already commented, you can move the for loop into a library and run that from `Run Keyword If`. My general recommendation would be moving both the loop and the if/else logic into a custom library. Python (or Java) is much better programming language than Robot's test definition syntax.

**Comment by mrunalbodhe** [comment]
I was trying to look for a similar solution, so the trick that you can use is give a exit condition in the Run keyword If.... and give the FOR loop after that -
Example:

   Run Keyword If    ${value}==${0}
    ...    Pass Execution     *** Skipping for loop***

# This will only run if value !=0 ->
    : FOR  ${var}  IN    @{List1}
          \    Do something
         \     Do something else
