### ISSUE TITLE
Issue with SSHLlibrary ride

### ISSUE THREAD

**Issue by lolobvt** [robotframework/robotframework#2642]
Hello,

I have an issue on windows 7 with ride : 

I install python 2.7.13 and wxpython 2.8.12.1 x64 py27

After i write on a terminal : 

pip install robotframework-sshlibrary
pip install robotframework-ride
pip install robotframework-faker

When i start ride my SSHLibrary is red...

What can i do ?

Thanks for your help

Loïc BOUVET

**Comment by pekkaklarck** [comment]
Closing because:
- this issue isn't related to Robot Framework core itself, and
- questions are generally better asked on robotframework-users or other such support forums.
