### ISSUE TITLE
robot --argumentfile xxxx.txt , how to  program to set up metadata in the report ? 

### ISSUE THREAD

**Issue by vincenzheng** [robotframework/robotframework#2644]
hi, I am struggling to get this done.
We have a few test suite A.robot, B.robot.  and I have an agurmentfile to run the test suites in sequence as following:
--output  output.xml
A.robot
B.robot 

the I got a report output.xml. then I want to set up some metadata in the report html file, other than 'Start Time', 'End Time', 'Status' ..., I want to add something like 'Browser', 'Version' ...,  but those metadata value are retrieved in the test suites running,  

I know a keyword 'Set Suite Metadata' , and if I run the test suite A, or B only, the report has such information in the html. 

it just doesn't work when we run the test suites with -argumentfile  

Best Regards
VIncent

**Comment by terokinnunen** [comment]
You can add your metadata to the argumentfile with [--metadata option](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#setting-metadata).
```
--output output.xml
--metadata Browser:xxx_yyy
--metadata Version:1.2.3
A.robot
B.robot
```
Or with `Set suite metadata` keyword you can put the metadata to top-level report with `top=True` option.
```
Set suite metadata   Browser    xxx yyy    top=True
```

**Comment by pekkaklarck** [comment]
@terokinnunen is right, you can use `--metadata` option in argument files as well as on the command line.
