### ISSUE TITLE
Date Picker Logic

### ISSUE THREAD

**Issue by vanaokar** [robotframework/robotframework#2647]
I just have on my xpath img and src. there is no class, id, name to identify the object for Date Picker image. 
How to put xpath for the same.

<img alt="Date Picker" src="images/calender.gif" onclick="popUpCalendar(this, 'remitDate', 'mm/dd/yyyy')" width="35" height="23" border="0">

**Comment by pekkaklarck** [comment]
This seems to be related to Selenium2Library or some other non-standard library and thus isn't in the scope of this project or issue tracker. Notice also that we generally recommend robotframework-users mailing list or other such forums for questions.
