### ISSUE TITLE
Replace captured screenshot on failure under logs.

### ISSUE THREAD

**Issue by SamyQAZ** [robotframework/robotframework#2649]
Robot framework, AppiumLibrary replaces screenshot on failure.[Python]
Is there a way to rename capture screenshot on failure and save it along with log.html for each test cycle.

`Set new screenshot directory
    ${Date}=  Get DateTime
    Set Screenshot Directory    /mobile_automation/xxx_automation/iOS_automation/ios_screenshots/screenshot${Date}
     Capture Page Screenshot     ios_screenshot${Date}`
This is how above keyword create directory in myresource.robot and called in test.robot

Is there a keyword to save log.html dynamically after each test?

Currently `robot -T -l /mobile_automation/xxx_automation/iOS_automation/ios_logs/logfile` help to save logfile, however its not dynamic for captured screenshot. Screenshots always get replaced.

**Comment by pekkaklarck** [comment]
Robot itself doesn't replace screenshots, it's the AppiumLibrary that does it in this case. Perhaps the library could optionally or automatically increment a counter in the file name to make sure old screenshots aren't removed. Alternatively the library could have an option to embed those images into the log file itself, but that might increase the log file size too much. Anyway, this issue belongs to AppiumLibrary tracker, not here.
