### ISSUE TITLE
Xpath works with UIautomator but same xpath does not work with UIautomator 2

### ISSUE THREAD

**Issue by abhasingh1** [robotframework/robotframework#2650]
xpath which does not work with Uiautomator2
 @FindBy(xpath="//android.widget.EditText[@resource-id='com.test.android.app:id/edit_text'][@NAF='true']")

Please help.

Appium version- 1.6.5(command line)
uiautomator2 version-
appium-uiautomator2-driver@0.4.2 
appium-uiautomator2-server@0.1.8

**Comment by pekkaklarck** [comment]
This issue doesn't seem to be related to Robot Framework itself.
