### ISSUE TITLE
Calling listener method 'log_message' of listener 'C:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py' failed: error: [Errno 10053] #1

### ISSUE THREAD

**Issue by etiaxie** [robotframework/robotframework#2651]
robotframe work version:2.8.5
RIDE version:1.5
the detail traceback:
Traceback (most recent call last):
File "C:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py", line 207, in _send_socket
self.filehandler.flush()
File "C:\Python27\lib\socket.py", line 309, in flush
self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10053]

this error will occur when in my testcase have sleep action like "sleep 4" longer than 4 seconds
use pybot cmd to run also have this problem

**Comment by pekkaklarck** [comment]
On a very quick look it seems error 10053 means some kind of a network error. Not sure is the problem in RIDE or in your environment. Anyway, this is a RIDE issue and thus belongs to its issue tracker, not here.
