### ISSUE TITLE
Run Keyword And Ignore Error captures screenshot of an error

### ISSUE THREAD

**Issue by pavoltravnik** [robotframework/robotframework#2652]
I am trying to click all visible elements found on the page and only way is to select all in loop, however in every round is page reloaded and filters are rearranged.
So I would like to ignore an error and Capture of screenshot. I expected, that Run Keyword And Ignore Error really ignores error, but after 20 rounds I have twenty selenium screenshots .png images and there is no other option except to turn off capture screenshot for all tests.

Edit: I found a nasty workaround - https://stackoverflow.com/questions/26853939/refactoring-a-test-case-to-stop-logging-an-error

**Comment by trogdor259** [comment]
This is a function of the robotframework-selenium2library. You can turn off the screenshots on test failure. To turn off screenshots on test failure, use the import option run_on_failure=Nothing when importing selenium2library. See the [user guide, "Importing" section](http://rtomac.github.io/robotframework-selenium2library/doc/Selenium2Library.html).

**Comment by pekkaklarck** [comment]
Yeah, not an issue for this project.
