### ISSUE TITLE
README.rst Slack channel invite is not working anymore

### ISSUE THREAD

**Issue by aaltat** [robotframework/robotframework#2653]
I think README.rst Slack channel invite is not anymore working. Based on the user group discussion[1], the link should be https://robotframework-slack-invite.herokuapp.com I could create PR to fix it but I do know where to get the image for the link.

[1] https://groups.google.com/forum/#!topic/robotframework-users/f5kjLvCz2dE

**Comment by pekkaklarck** [comment]
True. Forgot that we don't have Slack link only at http://robotframework.org but also here in the README. I try to get it fixed ASAP.

**Comment by pekkaklarck** [comment]
The badge on the top of the README is provided by [Slackin](https://github.com/rauchg/slackin) and it seems that [Slack Invite Automation](https://github.com/outsideris/slack-invite-automation) we nowadays use doesn't have them. I don't consider that badge a must so it's easiest simply to remove it. We have a link to Slack under the Support section in the README anyway.
