### ISSUE TITLE
Calling Keywords with parameters after Run keyword if

### ISSUE THREAD

**Issue by JTV1** [robotframework/robotframework#2654]
I've function

new_value | [Arguments]	 | ${value}
   | ${s} = | do something with	${value}
   | [Return]|${s}

And I call it elsewhere
...
Run keyword if | '${expected}' == 'changing'	|  ${changed_value}=  | new_value | ${orig_value}
...
Now  ${changed_value} should get the return value of function new_value, but RFW gives an error
Variable '${changed_value}' not found.
I think that it tries to set new_value to ${changed_value}, not value of the function new_value.
How can I group those function & argument so that RFW understands it?

-j-

**Comment by pekkaklarck** [comment]
Reading the docs would help:
http://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Run%20Keyword%20If
