### ISSUE TITLE
User guide: Incorrect link to google code repo in extending framework section

### ISSUE THREAD

**Issue by chbndrhnns** [robotframework/robotframework#2655]
In the section [Extending Robot Framework](https://github.com/robotframework/robotframework/blob/master/doc/userguide/src/ExtendingRobotFramework/CreatingTestLibraries.rst#supported-programming-languages), a Google code repo is referenced under the 'TIP' section [1] which is no longer active.

[1] http://code.google.com/p/robotframework/wiki/PythonTutorial

**Comment by pekkaklarck** [comment]
That tutorial is outdated. Should remove all references to it as well the actual tutorial under `doc/python`.

**Comment by pekkaklarck** [comment]
The reference to the Python tutorial was removed as part of general documentation cleanup in 83cc5695c8b51e87deb111e63dd124dc88a8a45a
