### ISSUE TITLE
ROBOT_EXIT_ON_FAILURE not functional inside "Call Method" calls

### ISSUE THREAD

**Issue by Chris-sc** [robotframework/robotframework#2657]
If a method called using "Call Method" raises a fatal exception (ROBOT_EXIT_ON_FAILURE=TRUE), fatal errors do not stop test execution.

**Comment by pekkaklarck** [comment]
Could you elaborate?

**Comment by Chris-sc** [comment]
I have a class that I instantiate. Specific methods of this class are critical, and upon failure point to a complete failure of the test jig itself, not the DUT. Therefore, when these methods fail, test execution needs to end so I can service the jig. To implement this critical failure I have defined a fatal error exception, wherein ROBOT_EXIT_ON_FAILURE=True. However, if these methods are called using the _Call Method_ keyword, the exception is raised, the current test fails, but the next test is started. 

Other functions that raise this error that are not part of a class and as such do not use _Call Method_ to invoke will completely stop test execution as intended when this fatal exception is raised.

**Comment by Tattoo** [comment]
Here is an example demonstrating the bug(?):

```### var.py
class FooEx(RuntimeError):
    ROBOT_EXIT_ON_FAILURE = True

class thing(object):
    def foo(self):
         raise FooEx()

MY_THING = thing()

### test.robot
*** Settings ***
Variables    var.py

*** Test cases ***
TC
    Call method    ${MY THING}     foo

TC2
    No operation```

When running, the first test case fails but second test case passes.

This example also works if you replace `Call method` with `Evaluate    $MY_THING.foo()`

This works as expected:
```### test2.robot
*** Settings ***
Library    var.thing

*** Test cases ***
TC
    foo

TC2
    No operation```

This behaviour in RF 3.0

**Comment by pekkaklarck** [comment]
Could you please provide an example?

**Comment by pekkaklarck** [comment]
The reason for the behavior is that `Call Method` and `Evaluate` both catch the exception and report it further and they don't check `ROBOT_EXIT_ON_FAILURE` or any other such special attribute. Those attributes are only checked by the core framework when a keyword it calls raises an exception. In these cases keywords raise exceptions but those exceptions don't contain any special attributes.

My current thinking is that the current behavior is fine. Various other keywords also directly or indirectly call methods of the objects passed to them as arguments, and all of them checking some special attributes would complicate the code unnecessarily. Using `Call Method` is not generally even recommended, it's typically better to create dedicated keywords instead.

If you can provide some good use cases showing that this behavior is really desired, we can consider adding that functionality. Even in that case I wouldn't call it a bug but an enhancement request for the selected keywords.

**Comment by Chris-sc** [comment]
Well, in my case I have a objects that maintain a device IP and various other attributes to get and set SNMP OIDs. If one of these get or sets fail, I want test execution to stop.

**Comment by pekkaklarck** [comment]
Is there a reason you don't expose this functionality as keywords instead of using Call Method?

**Comment by Chris-sc** [comment]
This is what I've gone with now

But the original setup was that different objects of this class housed the device specific information (IP etc)
and the handles to those devices were instantiated and called with call method.

**Comment by pekkaklarck** [comment]
Objects containing device info sounds good but I don't understand how that would require you to use Call Method. You can easily pass those objects to your custom keywords too.

**Comment by Chris-sc** [comment]
I must be misunderstanding something.

Object 1: Device 1
Object 2: Device 2

I want Object 1 oid response. Call Method on object 1 "Get response"
I want Object 2 oid response. Call method on object 2 "Get response"

Without call method how can I run get response on the two different objects instantiated from this class that houses the IP?

**Comment by pekkaklarck** [comment]
You create a keyword that does it. Something like this:

```python
def get_response(device):
    return device.get_response()
```

**Comment by Tattoo** [comment]
Shouldn't the documentation be enhanced, though? To me, it seems to pretty directly give the impression that `ROBOT_EXIT_ON_FAILURE` always stops execution.

**Comment by pekkaklarck** [comment]
Execution does stop if you raise an exception from a keyword with that attribute set. In this case its `Call Method` that raises the exception because calling a method fails.

**Comment by Chris-sc** [comment]
So, I need to create a wrapper function to take the object and return its get_response, To me that wrapper function is just sidestepping Call Method, but is inherently just doing the same thing (taking an object and calling a method from that object)

If methods inside Call Method can't critically fail as all other keywords, what is the use Call Method in the first place in an environment where particular methods are critical?

**Comment by pekkaklarck** [comment]
You should always design libraries to that tests using them are as clear as possible. Using

        ${response} =    Get Response    ${device}

is much cleaner than

        ${response} =    Call Method    ${device}    get_response

Call Method is there to help in cases where you need to call some method of some object once and creating a library just for that purpose is an overkill. You should never design your tests so that you need to use it all the time.

If you underlying use case is stopping execution if the environment is not OK, it's easiest that you simply create a keyword like `Environment Should Be OK` that raises an exception stopping the whole execution if it's not.

**Comment by pekkaklarck** [comment]
After thinking this a bit more, I'm even more convinced that Call Method shouldn't handle this situation. Closing.

**Comment by Chris-sc** [comment]
But in the case where the environment can go down at any point, this seems redundant to call Environment Should Be OK before any outbound communication.

I'll rethink the design of the test library.

Thanks
