### ISSUE TITLE
Keyword with functional annotation is not work

### ISSUE THREAD

**Issue by mralien** [robotframework/robotframework#2658]
if a keyword method use functional annotation (https://www.python.org/dev/peps/pep-3107/), Robot failed test with msg: No keyword with name '..' found

This:
@keyword('Send Message')
    def send_message(self, message)
        self.put(message)

*** Test Cases ***
	Send Message 	message

works normally, but this NOT:

@keyword('Send Message')
    def send_message(self, message) -> None:
        self.put(message)

*** Test Cases ***
	Send Message 	message

**Comment by pekkaklarck** [comment]
There's already #2627 about this.
