### ISSUE TITLE
Bad error if using `TestSuite.configure` with a non-root suite

### ISSUE THREAD

**Issue by Brian-Williams** [robotframework/robotframework#2659]
# Summary

When configure is called on a non-root suite it fails because it has a parent and is therefore not allowed to set criticality tags. This is true even if the configure is not changing criticality.

## Workaround

You can go in and manually and alter what is needed how visit would. For example instead of `suite.configure(name=new_name)` do `suite.name = new_name`. However, if we are reimplementing the visit component any time we need to alter a non-root suite it is questionable.

## Possible solutions

This limitation on configure effectively means that `TestSuite.configure` will always fail if not the root suite and we should consider failing earlier with a better error message.

We could simply skip `suite.set_criticality` if the user isn't changing anything.
```
# robot/result/configurer.py
def visit_suite(self, suite):
    model.SuiteConfigurer.visit_suite(self, suite)
    self._remove_keywords(suite)
    self._set_times(suite)
    suite.filter_messages(self.log_level)
    if self.critical_tags or self.non_critical_tags:
        suite.set_criticality(self.critical_tags, self.non_critical_tags)
```

Alternatively in the result test suite's `set_criticality` could send the information to its parent instead of failing. This could be a problem if a suite is configured multiple times. Also, I'm uncertain, but this looks like it would remove any criticality tags set beforehand.

```
def set_criticality(self, critical_tags=None, non_critical_tags=None):
    """Sets which tags are considered critical and which non-critical.

    :param critical_tags: Tags or patterns considered critical. See
        the documentation of the ``--critical`` option for more details.
    :param non_critical_tags: Tags or patterns considered non-critical. See
        the documentation of the ``--noncritical`` option for more details.

    Tags can be given as lists of strings or, when giving only one,
    as single strings. This information is used by tests to determine
    are they considered critical or not.

    Criticality can be set only to the root test suite.
    """
    if self.parent:
        # raise TypeError('Criticality can only be set to the root suite.')
        self.parent.set_criticality(critical_tags, non_critical_tags)
    self._criticality = Criticality(critical_tags, non_critical_tags)
```

## Trace
```
File "/Users/brianwilliams/PycharmProjects/robottools/robottools/rename.py", line 29, in start_suite
    self.config_suites(suite)
  File "/Users/brianwilliams/PycharmProjects/robottools/robottools/rename.py", line 24, in config_suites
    suite.configure(name=originallongname)
  File "/Library/Python/2.7/site-packages/robot/result/model.py", line 286, in configure
    self.visit(SuiteConfigurer(**options))
  File "/Library/Python/2.7/site-packages/robot/model/testsuite.py", line 160, in visit
    visitor.visit_suite(self)
  File "/Library/Python/2.7/site-packages/robot/result/configurer.py", line 65, in visit_suite
    suite.set_criticality(self.critical_tags, self.non_critical_tags)
  File "/Library/Python/2.7/site-packages/robot/result/model.py", line 255, in set_criticality
    raise TypeError('Criticality can only be set to the root suite.')
```

###### Additional information
Opened as a result of #2640 discussion.

**Comment by pekkaklarck** [comment]
The `configure()` method exists to configure the whole suite structure in one go. The current situation that it fails half way when called using a non-root suite is definitely not good. In my opinion failing immediately would be fine, though, because there are other ways to modify the suite if there are custom needs. Failing immediately is also the easiest fix so I vote for that.
