### ISSUE TITLE
Ignore error on using --rerunfailed when all tests are passed

### ISSUE THREAD

**Issue by senram** [robotframework/robotframework#2662]
I run my robotframework test suite as a teamcity/jenkins build with two simple steps as below

    build step #1: pybot <Test Folder>
    build step #2: pybot --rerunfailed Results\output.xml  <Test Folder>

When all the tests in step-1 are passed, the build fails because step-2 (--rerunfailed) triggers an error ( **_[ ERROR ] Collecting failed tests from 'Results\output.xml' failed: All tests passed._**) .

Could someone please suggest how to ignore or overcome this error, so that I can show the build as passed in this case ?

**Comment by pekkaklarck** [comment]
Just change your script so that you don't run tests again if all tests pass.

Notice also that robotframework-users and other such forums are better places to ask questions. This issue tracker is for bug reports and concrete enhancement requests.
