### ISSUE TITLE
Dry Run does not fail on error due to missing Python modules?

### ISSUE THREAD

**Issue by helinjan** [robotframework/robotframework#2665]
I am using --dryrun to quickly syntax check my Robot FW suites as a Jenkins step.

`sh 'robot --dryrun --pythonpath . --outputdir res-syntax *.robot'`

When I run this, I get following error in Jenkins console:

`[ ERROR ] Error in file '/home/jenkins/workspace/ession-multi-branch_develop-WEFTNXTN5KLOKQRWYCQV2NOJRC7DY36KNSOO6IPBIEX25JYIOIUA/robotfw-ttf-library/androidchat.robot': Using YAML variable files requires PyYAML module to be installed. Typically you can install it by running 'pip install pyyaml'.`

This in itself is a valid finding: I am missing PyYAML in the environment where I am running this.

However, I would expect the run to fail and Jenkins to report failed job. But in this case the run passes and all test cases are reported as 'PASS'. Thus this error has gone undetected for some time as the suite in question is not run in our regression pipeline for the moment.

Is this a bug or feature? I would expect Dry Run to return an error in case there is clear error such as missing Python module.

Robot FW version:
Robot Framework 3.0.2 (Python 2.7.6 on linux2)

**Comment by pekkaklarck** [comment]
Dry-run unfortunately doesn't validate variables so variables that couldn't be created because PyYAML was missing don't cause any failures. We already have #2322 about adding variable validation support but because it requires lot of work there are no estimates if/when it would be implemented.

**Comment by helinjan** [comment]
Thanks for super-quick response!

I understand that variable validation would be a heavy feature to implement. But I am a bit loss here: Where does the "Using YAML variable files requires PyYAML module to be installed..." error originate from? Couldn't the Dry Run catch this kind of errors (that seem to be detected anyway) and just abort with error? Or are there plenty of cases where this kind of errors happen in Dry Run but they are not really errors as such...?

**Comment by pekkaklarck** [comment]
As you've seen dry-run already catches and reports the error. Such errors in importing libraries, resource files or variable files don't automatically cause test case failures even without dry-run, though. Tests fail only if they actually use keywords/variables that failed to be imported. If that's a problem, you can use `--exitonerror` option.

**Comment by pekkaklarck** [comment]
Damn GitHub UI with "reopen" and "comment" buttons next to each others.

**Comment by helinjan** [comment]
'--exitonerror' works perfectly for my case, should have tried that myself in the first place. Thanks for the help!
