### ISSUE TITLE
Drag And Drop By Offset and Press Key issues

### ISSUE THREAD

**Issue by xulongchen** [robotframework/robotframework#2667]
Just found the issue with drag and drop by offset and press key.

Pre-condition:
find a webpage with horizontal scroll bar within the page (not the ones as part of the browser, like the side ones or bottom ones on the browser) the one that you can find its elementid, xpath...

You will need to add a tetsing url to the below steps where fits.

Reproduce Steps:
Library                           Selenium2Library						15
*** Variables ***
${Administration SS MaxDiskUsage}				name=MaxDiskIOUsagePercent //or you can use id, etc
*** Keywords ***
Config the server value
Drag And Drop By Offset		${Administration SS MaxDiskUsage}		500            0
*** Test Cases ***
Server Configuration
        Config the server value

I expected the scroll bar drag to the right by 500px, but actually it moved to the center of the slider and stayed there whether the bar is sitting most left or most right of the slider initially.

**Comment by bkhouri** [comment]
The problem description, along with the code snippet provided, indicates this is an issue with the Selenium2Library module, which is an open-source project on it's own.  

Open the defect with the respective project please.

@pekkaklarck I think this can be closed as it's not an issue with robot framework itself.

**Comment by pekkaklarck** [comment]
Yep, wrong tracker.

**Comment by bkhouri** [comment]
In the Selenium2Library orbSeleniumLibrary github project.                                                                                                                                                                         Sent from my BlackBerry - the most secure mobile device                                                                                                                                                                            From: notifications@github.comSent: September 1, 2017 5:20 AMTo: robotframework@noreply.github.comReply-to: reply@reply.github.comCc: bassam.khouri@gmail.com; comment@noreply.github.comSubject: Re: [robotframework/robotframework] Drag And Drop By Offset and Press Key issues (#2667)  Can you please point me where should I direct the issue to?

Thanks very much.

Xulong
