### ISSUE TITLE
Logging Python keywords to log.html

### ISSUE THREAD

**Issue by Tommy2991** [robotframework/robotframework#2670]
Hello, I would like to ask If there is a possibility to log python keywords to log.html like robot keywords. If we executin Robot/Python keyword from robot file it's ok - there is a "node" for keyword. When we run python keyword and if that keyword contain other keywords inside, these keywords are not logged properly - doesn't have own node. In log.html that keywords are under one "node" (parent), executed from robot file.
Is there any decorator for keywords or other method to "tell" for robot that methods inside that keyword are too keywords?

Robot:                                                                
- Run Something                                              
    + Run other keyword
    + Execute command

Python:
- Run something
   ....
   ....

Thank you in advance for your help.
Br, Tomasz

**Comment by pekkaklarck** [comment]
You ought to be able to use `BuiltIn.run_keyword()` to accomplish this.

This issue doesn't seem to contain any concrete enhancement request or bug report so closing. Notice that questions are best sent to robotframework-users mailing list or other such support forums.
