### ISSUE TITLE
Record video of test runs with test steps as subtitles

### ISSUE THREAD

**Issue by duongnapham** [robotframework/robotframework#2671]
Hi,

I've come across [Katalon Studio](https://www.katalon.com/) and found that it can record video of test runs with test steps as subtitles (https://docs.katalon.com/display/KD/Video+Capturing). I imagine this feature would be helpful and save my time on defect investigation and reporting. Is there any way I can achieve this with Robot Framework? If it requires programming, could anyone give me some hints for getting started (libraries, API, etc.)?
Please refer the attached file: 
![image](https://user-images.githubusercontent.com/12078334/30155564-5a52abf2-93e7-11e7-800b-8309324ac285.png)

**Comment by pekkaklarck** [comment]
Recording a video is nice, but I don't think it's something that could be added to Robot Framework core. Video only makes sense if you test an application with UI on the same machine where you run tests, and Robot Framework is not at all limited to only this kind of usage. Having a separate library that implements this kind of functionality would be nice, but it should be implemented as a separate project.
