### ISSUE TITLE
Is it possible add the same option "strip_prompt" in Telnet to "Read Until Prompt" keyword in SSHlibrary 

### ISSUE THREAD

**Issue by DavidKalandarishvili** [robotframework/robotframework#2672]
Will be great to have the same functionality "strip_prompt"  as is in Telnet.Read Until Prompt in SSHLibrary.Read Until Prompt
Is it possible to add it ?

Reference issue for Telnet: https://github.com/robotframework/robotframework/issues/1874

Thanks,
David

**Comment by bkhouri** [comment]
Are you proposing a change to the SSHLibrary?  If so, it is developed in an independent project.  Please raise the issue with the SSHLibrary project, which can be found here: https://github.com/robotframework/SSHLibrary

@pekkaklarck  I believe this can be closed.

**Comment by DavidKalandarishvili** [comment]
Apologize, will raise this issue in the SSHLibrary project.

Thanks,
David
