### ISSUE TITLE
Modulus function in Robot Framework

### ISSUE THREAD

**Issue by vanaokar** [robotframework/robotframework#2673]
Do we have Modulus function in Robot Framework

**Comment by HelioGuilherme66** [comment]
You should not use this issue tracker to ask questions.
This is to report errors or improvements. Please use our Google groups or Slack.

PS: Yes we have all the Python functions, with `Evaluate`

**Comment by pekkaklarck** [comment]
As @HelioGuilherme66 commented, general questions are best sent to mailing list, Slack or other such forums. If you'd like to have more math related keywords, please submit a concrete enhancement request.
