### ISSUE TITLE
Import resource file failed

### ISSUE THREAD

**Issue by niuniutest** [robotframework/robotframework#2678]
I wrote a function for extending file types to support the format of markdown，The problem now is that I run this file(the file type is markdown) without problems, but in setting import it as source failed.A month ago,in setting import it as source successed ,i cann't find the reason
![1](https://user-images.githubusercontent.com/31948949/30415319-26929728-995a-11e7-8373-57f19d85f1c3.png)

the function of running the file i writed is to convert .md files to HTML files and then run them,So I guess  the code for source have changed recently

**Comment by niuniutest** [comment]
![3](https://user-images.githubusercontent.com/31948949/30421049-214ea20c-996e-11e7-93f0-168460c9f02d.png)
this is the coding

**Comment by HelioGuilherme66** [comment]
Can you propose a full Pull Request (PR)? This way we all could review your code and benefit from it.
Thanks.

**Comment by niuniutest** [comment]
#!/usr/bin/env python3
import sys
import os.path
import os
import traceback
from robot import run_cli
from io import BytesIO
from markdown import markdown
from robot.parsing.htmlreader import HtmlReader
from robot.parsing.populators import READERS


class MarkdownReader(object):
    """扩展Robotframework支持Markdown格式的测试用例"""
    def read(self, md_file, raw_data):
        """转换markdown到html"""
        html_str = markdown(self.read_unicode(md_file),
                            extensions=['markdown.extensions.tables'],
                            ouput_format='html')
        #print(html_str)
        if '<html>' not in html_str:
            html_str = ('<html><head><meta http-equiv="Content-Type" content="text/html; ' +
                        'charset=utf-8"></head><body>' + html_str + '</body></html>')
        try:
            return HtmlReader().read(self.write_unicode(html_str, BytesIO()), raw_data)
        except Exception as excp:
            traceback.print_exc()
            raise excp

    def read_unicode(self, file_io):
        """从文件中读取unicode编码的字符串"""
        try:
            return file_io.read().decode('utf-8')
        except Exception as excp:
            traceback.print_exc()
            raise excp

    def write_unicode(self, text, bytes_io=None):
        """以unicode编码将字符串写入到文件"""
        try:
            text_bytes = text.encode('utf-8')
            if bytes_io is not None:
                bytes_io.write(text_bytes)
                bytes_io.seek(0)
                return bytes_io
            return text_bytes
        except Exception as excp:
            traceback.print_exc()
            raise excp


READERS['md'] = MarkdownReader
ARGV = ['--pythonpath', './keywords'] + sys.argv[1:]
if '--outputdir' not in ARGV and '-o' not in ARGV:  # set default output directory to output
    ARGV.insert(0, 'local')
    ARGV.insert(0, '--outputdir')
elif '--include' not in ARGV and '-i' not in ARGV: # set default include select tag to draft
    ARGV.insert(0, 'draft')
    ARGV.insert(0, '--include')

try:
    running_file = os.path.join('local', 'running')
    if not os.path.isdir('tests'):
        raise ValueError('非法的测试项目仓库，仓库中不包含tests目录')
    if not os.path.isdir('local'):
        os.mkdir('local')
    with open(running_file, 'w'):
        pass
    run_cli(ARGV)
except ValueError as excp:
    print(excp, file=sys.stderr)
except Exception as excp:
    raise excp
finally:
    if os.path.isfile(running_file):
        os.remove(running_file)



this is full the file to convert .md files to HTML files and then run them  ,and This is a company project, so it can not to propose a full Pull Request ,thanks.

**Comment by pekkaklarck** [comment]
I have no idea what's going wrong, but as AFAIK there's no bug in Robot Framework but you just have problems using its internal APIs. I'm thus going to close this issue.

Notice also that we already have issue #2610 about supporting test cases in Markdown files. The idea is to have tests in code blocks using the plaint text format, not to convert those files to HTML first. We are actually planning to drop the support for test data in HTML files, and thus it isn't a good idea to build anything that uses it.

It would be great if you would be interested to help with #2610 and provide a PR.

**Comment by niuniutest** [comment]
This problem indicates that your HTML format file has bug when it is used in source
