### ISSUE TITLE
How to make 'Register Keyword To Run On Failure' run globally?

### ISSUE THREAD

**Issue by cbaldan** [robotframework/robotframework#2679]
Hello.

I'd like to have the keyword registered through `Register Keyword To Run On Failure` to run in case of any kind of failures that may happen.

The documentation of that keyword says:
```
Sets the keyword to execute when a Selenium2Library keyword fails.
     (...)
```
So, it seems it only runs the registered keyword if the method which failed is within **Selenium2Library** folder.

I'd like to have the registered keyword executed when a test fails for any reason; e.g. it ran `lists_should_be_equal()` from **Collection.py** and failed. Currently, no screenshot is taken.

Am I missing something? Can it be achieved some other way?

Thanks,
Cleber.

**Comment by cbaldan** [comment]
http://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Run%20Keyword%20If%20Test%20Failed

**Comment by pekkaklarck** [comment]
You are right that it's possible to get this behavior by using `Run Keyword If Test Failed` in test teardown. Having some explicit way to set a keyword that is executed when a test fails would, however, be useful too. I'm not sure how it should work in practice, though.

**Comment by cbaldan** [comment]
Hi @pekkaklarck 

Thanks for looking at my ticket :)
I think such a functionality would be a great addition to **Robot** itself.

To me, feels like it would a great addition having a way to register a keyword to be run in case of a keyword failure, just like SeleniumLibrary has (`Register Keyword To Run On Failure`), I'm sure people would find usage for it rather quickly.

My situation is: I want to have a Screenshot of the browser taken right after a TC fails, to get the very current state of the browser, before the test teardown kicks in and changes it.
So I had to create a new keyword, in Python, that checks if the current Test Teardown is being run on a test failures (`${TEST STATUS} == FAIL`), else no screenshot is needed.
But then, it comes with the cost of having to register a **Test Teardown** for every single TC, and making sure that the screenshot keyword is the first one being called.

Sure enough it works, but having this ready made as a functionality within the framework would easy things a lot.

Regards,
Cleber.

**Comment by pekkaklarck** [comment]
If this would be implemented in Robot, I'd like this to be enabled using settings similarly as you specify setups and teardowns. You should be able to set it also for individual user keywords. Implementation shouldn't be overly complicated but definitely not trivial either. One hard part would be deciding what to call this new setting.

**Comment by cbaldan** [comment]
Definitely, it has to beconfigurable like you said.

I just didn't get what you mean when you say **individual user keywords**.
You mean there should be a new _[Tag]_ to apply it?

Perhaps I'm interested in doing this improvement, if you'd like help.

**Comment by pekkaklarck** [comment]
Each keyword should be able to have its own failure handler similarly as keywords can have their own teardown. Possibly the handler should be able to suppress the failure too, allowing to continue execution. This would be more complicated to design and implement well, but it would also make the functionality a lot more powerful.

Great to hear you are interested to do this! I'd definitely help wirh design and would also review the code.

**Comment by cbaldan** [comment]
Great, where do I start? :)

**Comment by pekkaklarck** [comment]
To get fully started, we needed to design how we'd want this functionality to work, but unfortunately I'm too busy with SeleniumLibrary to concentrate on that in the immediate future. What you could do in the meantime is getting more familiar with the code base, doing some prototyping, and possibly proposing 
a design based on what we discussed above.

Notice also that this kind of a change is so big that it can land only in a major version like 3.1. I hope we could start real RF 3.1 development soon, but there's still SeleniumLibrary, SSHLIbrary's Python 3 support, and also RF 3.0.3 between that.

**Comment by pekkaklarck** [comment]
You could also submit a new issue proposing to add functionality to run a specified keyword when a failure occurs. Alternatively we could just reopen this one, but I think a new one could be better.
