### ISSUE TITLE
__init__.txt won't be executed when specifying the test suite file under the directory

### ISSUE THREAD

**Issue by niexiongfang** [robotframework/robotframework#2680]
i.e.,
for test suite structured this like:
tests/
        \_\_init\_\_.txt
        demo1.txt
        demo2.txt
        real1.txt

the setup/teardown in \_\_init\_\_.txt won't get executed when running tests as below:
robot tests/demo*

When running any part of a test suite (here 'tests' is a test suite in RF), the suite setup/teardown should always be executed as by definition.
Think the current behavior breaks the concept of a test suite in RF.

**Comment by pekkaklarck** [comment]
This is by design. Robot cannot really start going through parent directories for init files. You can run the directory and use --suite option to select the child suite you want.
