### ISSUE TITLE
Installing RF with pip in a virtualenv "pollutes" some .bat files for future installs

### ISSUE THREAD

**Issue by CMTaylor** [robotframework/robotframework#2682]
Robot Framework Version: 3.0.2
Python Version: Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
Windows Version: Windows 10 Pro Version 1703 Build 15063.608
pip Version: 9.0.1

I use Robot Framework (RF) in multiple different Python virtual environments (virtualenv). When you use pip to install RF the first time it goes out to PyPi and downloads it. Then, as part of the install process, it caches a modified version of the .whl file with some files (robot.bat and rebot.bat) containing hard-coded paths to the virtual environment just used.  For example, in my Windows 10 environment the pip install created:
%APPDATA%\..\Local\pip\cache\wheels\b4\9b\b2\75d7e5f88f21673eed3472266a1f4e72672328cc174655a1b6\robotframework-3.0.2-cp27-none-any.whl\robotframework-3.0.2.data\scripts\robot.bat that contained these 2 lines:

@echo off
c:\_bb_\autotests_20\tests\rf_tests\nymi_20\env_rftester\scripts\python.exe -m robot.run %*

The 2nd line invokes the python interpreter from the hard-coded path into the virtual environment where I first installed RF.

If you then create a new virtual environment and install RF there, pip will pick up the cached .whl file with the hard-coded modification to robot.bat and install that file into the new virtual environment. This means that one virtualenv is cross-referencing another virtualenv.

A similar file in the same .whl location is pybot.bat. It does NOT have this bug and contains the following 2 lines:

@echo off
python -m robot.run %*

This correctly invokes whatever python is in the %PATH% at the time, which will pick up the correct one from the currently activated virtual environment. The robot.bat and rebot.bat files should follow this same model.

**Comment by CMTaylor** [comment]
Here's a ZIP copy of the cached .whl file that pip produced, containing the robot.bat and rebot.bat files with hard-coded python executable paths:

[robotframework-3.0.2-cp27-none-any.whl.zip](https://github.com/robotframework/robotframework/files/1338701/robotframework-3.0.2-cp27-none-any.whl.zip)

**Comment by pekkaklarck** [comment]
This is a known issue documented in #2529 that will be fixed by #2415 and introducing `robot.exe`. Workarounds listed in #2529 include installation with `--no-cache-dir` and running tests like `python -m robot`.
