### ISSUE TITLE
Second level list comprehension fails to work

### ISSUE THREAD

**Issue by VVasyaev** [robotframework/robotframework#2686]
I thought that Evaluation just bypass code to the python as is...

    * Test Cases
    Steps
    	${l1}	Create List	1	2	3
    	${d1}	Create Dictionary	list=${l1}
    	${l2}	Create List	${d1}
    	${d2}	Create Dictionary	dictlist=${l2}
    	${l3}   Create List     ${d2}
    	${res}	Evaluate	[l for l in dl['dictlist'] for dl in $l3]

fails with Evaluating expression '[l for l in dl ['dictlist']for dl in RF_VAR_l3 ]' failed: NameError: name 'dl' is not defined

however, python can successfully calculate it:

    l3 = [{u'dictlist': [{u'list': [u'1', u'2', u'3']}]}]
    [list for list in dl['dictlist'] for dl in l3]

returns

    [{u'list': [u'1', u'2', u'3']}]

**Comment by pekkaklarck** [comment]
I got the same NameError in Python interpreter as you get when running the example:

```python
>>> L3 = [{u'dictlist': [{u'list': [u'1', u'2', u'3']}]}]
>>> [l for l in dl['dictlist'] for dl in L3]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
```
You seem to have nested loops in wrong order:

```python
>>> [l for dl in L3 for l in dl['dictlist']]
[{u'list': [u'1', u'2', u'3']}]
```

**Comment by VVasyaev** [comment]
thank you very much! and sorry for disturb :((

**Comment by pekkaklarck** [comment]
No worries.

By the way, I would recommend moving this kind of logic into a test library.
