### ISSUE TITLE
How to compare two images using robot framework .

### ISSUE THREAD

**Issue by dipakbachhav** [robotframework/robotframework#2687]
I am new to robot framework and I have requirement to compare two images. One i will provide from my local drive and another one from application under testing.

I did some R&D and found that w can use RobotAppEyes library for the same. But I am not able to compare two images with it. 

** Settings ***
Library                 Selenium2Library
Library                 RobotAppEyes

*** Test Cases ***
RobotAppEyes 1.0 Test
    Open Browser    http://www.google.com.uk    gc      
    Maximize Browser Window     
    Open Eyes Session   http://www.google.com.uk    RobotAppEyes_Test   NaviNet_RobotAppEyes_Test1  JkaJK50dp1NTEhPufx08SaztsXmfBZasdsaljkasdkl73475  
    # ${isOpen}=    Eyes Session Is Open                    
    # Log    ${isOpen}
    Compare Image        C:\\Users\\Downloads\\logo.png       C:\\Users\\user\\Downloads\\logo.png     ignore_mismatch=False    includeEyesLog=False     httpDebugLog=False
    Check Eyes Region   .//*[@id='splash']/div[1]       500     120     logo
    Run Keyword If  ${isOpen}==True Close Eyes Session
    Close Eyes Session

Link1 : http://navinet.github.io/Robot-AppEyes/RobotAppEyes-KeywordDocumentation.html#Compare%20Image

Link2: https://github.com/NaviNet/Robot-AppEyes

I am using same library to compare images but facing below issue while comparing two images.

Error :
RobotAppEyes 1.0 Test                                                 | FAIL |
TypeError: _create_match_data_bytes() takes at least 6 arguments (5 given)

Can anyone please help me with comparing two images with robot framework?

**Comment by bkhouri** [comment]
This is an issue with the library you are using and not an issue with RobotFramework core.  Open the ticket against the respective library.

**Comment by dipakbachhav** [comment]
@bkhouri I know this issue specific to library but i am looking for solution related to robot framework. I don't want to stick to particular library and if you know any solution for comparing two images then let me know

**Comment by pekkaklarck** [comment]
We use this tracker only for bug reports and enhancement requests related to Robot Framework itself. There are separate support forums like mailing lists and Slack channel listed at http://robotframework.org.
