### ISSUE TITLE
Variable values in log.html

### ISSUE THREAD

**Issue by mohrod** [robotframework/robotframework#2692]
When running tests with keywords which have variables e.g. **Login to application    $username   $password**,  the log.html displays the same keyword with those variables. To review the test execution, and see what actual values have been used in the test run, one should enable loglevel TRACE prior to the test run. In addition, (s)he would need to click on that line in log.html file and expand it to see the actual value used in test run. This is very annoying when the test reviewer would need to go through a long run test and click each and every keywords which had variables! Is there anyway we could have the actual values exposed to log.html, so when opening it all the keywords would be displayed with the variable values? 
If this is not currently supported, I would say it is very needing feature. And if someone would have a workaround, I would appreciate if it could be shared.

**Comment by pekkaklarck** [comment]
I'm sure there's already issue or two related to this. Couldn't find one so I summarize the reasoning for the design and why it's not likely to be changed.

1. Variable names are often easier to understand that values. For example. `${LOGIN URL}` is explicit but `http://10.1.2.3/path` isn't.
2. Variable values are sometimes huge. For example, if you have `${content}` with contents of huge binary file and pass that as an argument, you definitely don't want to see the binary content there.
3. Variable values sometimes contain confidential information. Not everyone wants their `${password}` variable's value to be disclosed.
4. Keywords can easily log arguments they get. They know their context so they can avoid logging if values are potentially large or confidential. In libraries you just use something like `print "Got arg '%s'." % arg` or `logger.info( "Got arg '%s'." % arg)`, and with user keywords you can use the `Log` keyword.

**Comment by mohrod** [comment]
Well I would say this depends on the use-cases, you might be right that some project might not like to expose the values directly to their test reports, but most of them actually need to do so. For example almost all the acceptance test and test procedure auditors require to see the expected and actual values directly from the test report. And currently I would say robot framework is missing this feature to enable/disable the value display on the test reports.

**Comment by pekkaklarck** [comment]
Yes, there are use cases where showing variables would be useful. But as I already commented, there are use cases where that can make logs harder to read, make them too big to open, and even disclose confidential information. The default functionality is not going to change, but if someone is interested to make it configurable we can discuss about the design. Keywords logging arguments is a lot easier solution, though, and they can at the same time log whatever other relevant information they have.

**Comment by Bhav1408** [comment]
Hi ,

I am facing the same issue and it would be really helpful if this feature could be made optional. So by default it does not log the value of the argument passed. I want to use Robot Framework log files to provide stakeholders with the test report. Variable names passed in the keywords does not provide much value to stakeholders and customers. Its become quite a blocker for me now and I need to use some other form of reporting. 

Is there any other workaround to resolve this please?

**Comment by pekkaklarck** [comment]
The solution is logging argument values in keywords where it makes sense.

**Comment by Franz333** [comment]
I think this feature would be super useful in many cases to make reports more readable
It could be super useful to be able to trigger it at least for the first high level keywords in the .robot file
I vote for it :-)
