### ISSUE TITLE
Terminal emulation in Telnet library is not compatible with latest `pyte` versions

### ISSUE THREAD

**Issue by KrzysztofJozefowicz** [robotframework/robotframework#2693]
It seems that pyte library after v0.5.2 has changed constructor for class Stream which now does not accept argument "encodings" (file streams.py from pyte).
To verify this, try to run following suite:
```
*** Settings ***
Library  Telnet     terminal_emulation=YES      

*** Test Cases ***
Try Telnet
    Open Connection     localhost     port=22  
```
error is thrown: TypeError: \__init\__() got an unexpected keyword argument 'encodings'

Temporary workaround is to downgrade pyte to ver 0.5.2.
Pyte release notes: [https://github.com/selectel/pyte/releases](https://github.com/selectel/pyte/releases)

**Comment by pekkaklarck** [comment]
Thanks, need to take a look at this in RF 3.0.3. We should also think should we make `Telnet` an external library to make it easier to create new releases and develop it further in general. There were benefits in having it as a standard library earlier, but now that pip works so well it could be an external library too.

**Comment by pekkaklarck** [comment]
There seem to also other API changes in newer pyte versions. I hope I can make Telnet compatible both with 0.5.2 and with the latest version. In the future the support for the old versions can be dropped altogether.

**Comment by pekkaklarck** [comment]
There are quite a few changes in pyte APIs. I was hoping to be able to support both old and new versions, but that is too much work. Decided to support only the latest version which makes this change backwards incompatible. 

This has also made it clear that Telnet should be developed as a separate project in the future.
