### ISSUE TITLE
Mouse click inside "Windows OS" cmd.exe window causes robot tests to timeout

### ISSUE THREAD

**Issue by ghost** [robotframework/robotframework#2695]
Robot Version: 3.0.2
OS: Windows 10

Description: 
Given: Robot test running in "Windows 10" cmd.exe window with "QuickEdit" mode enabled
When: The user hovers the mouse over the window and clicks inside the window
Then: The window changes to "Select" state and robot tests pause execution and in some cases the test(s) timeout

Possible cause:
When the user mouse clicks in the cmd.exe window and the window has "QuickEdit" enabled then the mouse click puts the cmd.exe mode into "Select" meaning the window is now waiting for the user to copy or paste in the window. This causes the robot test to appear to hang. If the user waits to long to get the window out of this "Select" state then the robot test execution can timeout. 

Work Arounds:
1) As a user, if QuickEdit mode is enabled and if you mouse click inside the cmd.exe window then you need to press <Enter> immediately to get the window out of the "Select" state.
2) With the cmd.exe window already open or with the cmd.exe shortcut Select "Properties" and uncheck the "Edit Options->QuickEdit Mode" checkbox
3) Regedit.exe and edit the [HKEY_CURRENT_USER\Console] "QuickEdit"=dword:0  #0=Disable 1=Enable If you use this method shortcuts to cmd.exe that already exist will not be affected so you will also need to do workaround #2

**Comment by pekkaklarck** [comment]
Does this happen with all tests or only when some specific library is in use? Have you already looked the code to see where it could be fixed?

**Comment by tyorkco** [comment]
Here are the robot libraries I'm using:
robotframework (3.0.2)
robotframework-csvlibrary (0.0.2)
robotframework-lint (0.9)
robotframework-selenium2library (1.8.0)
robotframework-seriallibrary (0.2.4)
robotframework-sshlibrary (2.1.3)

I have not looked into the robot code for fix. My current fix is to disable the mode in Windows. 

I did try removing the call to write.flush() in def console in  C:\Python27\Lib\site-packages\robot\output\librarylogger.py line 75. I saw a thread about the possibility of this flush interfering with robot. In my testing the removal of this call did not help. Code snippet from C:\Python27\Lib\site-packages\robot\output\librarylogger.py is below

def console(msg, newline=True, stream='stdout'):
    msg = unic(msg)
    if newline:
        msg += '\n'
    stream = sys.__stdout__ if stream.lower() != 'stderr' else sys.__stderr__
    stream.write(console_encode(msg, stream=stream))
    stream.flush()    #Tom York I removed this line thinking it would fix the problem but it didn't fix

**Comment by pekkaklarck** [comment]
Are you still seeing this error? Does it happen in all machines or just one? Does it occur always or only sporadically? If you still encounter the issue, you could try does RF 3.0.3 RC 1 with a fix to somewhat related issue #2709 help. You can install it with `pip install --pre --upgrade robotframework`.

**Comment by pekkaklarck** [comment]
Closing due to lack of new info.
