### ISSUE TITLE
Remote library continuable exceptions does not stop test case execution.

### ISSUE THREAD

**Issue by gsumano** [robotframework/robotframework#2696]
How can I stop a test case from executing other keywords on a Continuable exception from a Remote library?    The remote library can only throw Fatal and Continuable Exceptions.   Fatals stops suite execution and Continuable continues to execute all keywords within the test case.  I want the test case to stop at the fail keyword.   

Any suggestions?

**Comment by pekkaklarck** [comment]
I don't understand this problem at all. Could you clarify? Remote interface supports normal failures as well. In fact, failures are normal unless explicitly declared continuable or fatal.

**Comment by gsumano** [comment]
My fault, for some reason I thought that the remote server can only throw Fatal or Continuable Exceptions.  I did not know normal failures were supported.  Thank you for the response.
