### ISSUE TITLE
help to add log info to xunit

### ISSUE THREAD

**Issue by zaipingy** [robotframework/robotframework#2697]
i'm a student to learn the robot framework, and a have a problem recently.
i add a listener to listen the test case, and in the listener i want to print the case's  tag to xunit-file, how can i do it?
below is my listener code:
class Show_Author_Listener(object):
    ROBOT_LISTENER_API_VERSION = 2

    def __init__(self, pattern=None):
        self.pattern = pattern

    def end_test(self, name, attributes):
        if attributes['status'] != 'FAIL':
            return
       tags = attributes.get('tags', None)
       author = ''
        for tag in tags:
            tag = tag.encode('ASCII', 'ignore').strip()
            m = re.match(r'@author\s+=(.+)', tag, re.IGNORECASE)
            if m is None:
                return
            author = m.group(1).strip()
            break

        LOGGER.error('\n{line}\nAuthor:{author}\nMessage:{message}\n{line}'.format(
            line='=' * 20,
            message=message,
            author=author))

but it does not work.
Anyone can help me?
thanks!

**Comment by pekkaklarck** [comment]
This issue tracker is for bug reports and enhancement requests. Use support forums like mailing lists or Slack listed at http://robotframework.org for general questions.
