### ISSUE TITLE
Assertion Error can be caught in teardown, but it cant be handle so that my other testcase passes.

### ISSUE THREAD

**Issue by sgerrard123** [robotframework/robotframework#2701]
I have 5 TC in my Test suite.If one TC fails with **AssertionError** then all other Testcases are failing with a message "**Test execution stopped due to a fatal error.**".

I can handle the assertion error in the teardown by using a keyword "**Run Keyword and continue on failure**"So that the other TCs will pass.

But unfortunately, my all test cases are failing with the fatal error.

Note: If AssertionError cant be handled then wats the use of having retry method?.Bcoz even though it run 3 times(Retry) ....it will fail all the tc once assertionerror occurs.

*** Test Cases ***
Testing
    [Setup]    Open New Session    ${URL}
    #####Assertion error occur in testcase level##########
    [Teardown]    Generic Test Case Teardown

*** Keywords ***
Generic Test Case Teardown
    # Catch of Try Catch Finally
    Run Keyword If Test Failed    Test Case Catch
    # Finally of Try Catch Finally
    #    RKITS is only executed when test passed.
    Run Keyword If Test Passed    Test Case Finally
    #    Always executed regardless of test execution status.
    Log To Console    I am always executed.

Test Case Catch
    Log To Console    Test Case Catch
    **Run Keyword and continue on failure**    Fail    

Test Case Finally
    Log To Console    Test Case Finally

**Comment by pekkaklarck** [comment]
That message

> Test execution stopped due to a fatal error.

means that some keyword you have executed has used an exception explicitly telling that the whole test execution must be stopped. If you don't want that to happen, you need to find the offending keyword and remove or change it. See the User Guide for more information about fatal exceptions.
