### ISSUE TITLE
Channel Exception: (4 ,'Resource shortage')

### ISSUE THREAD

**Issue by rockkn1992** [robotframework/robotframework#2704]
i'm using Robot Framework to run commands of Cisco Switch. But, i get this error Channel Exception: (4 ,'Resource shortage') while getting back the command's output.

**Comment by pekkaklarck** [comment]
Based on the provided information, the only thing I can say is that there is shortage of resources.

**Comment by rockkn1992** [comment]
what is shortage of resources actually.?

**Comment by pekkaklarck** [comment]
I have no idea.

**Comment by bkhouri** [comment]
What command are you using to send commands to the Cisco Switch?   Also, that error message does not appear to be coming from robot framework core, but without more information o. The error messages, it's very difficult to diagnose.

**Comment by rockkn1992** [comment]
i'm using "Show IP interface brief" command for cisco 3750 switch.

**Comment by bkhouri** [comment]
so I suspect you have an issue with a library that is not part of the robot framework core.  Is it the cisco switch that is reporting the "Resource Shortage" or robot framework?  Can you provide a sample screenshot of the log.html that is showing the failure?

**Comment by pekkaklarck** [comment]
Not sure have you noticed, but it's impossible for us to know what's going on when you don't provide any more information. For example, you said you "run commands of Cisco Switch" but don't tell how you actually run them.

**Comment by rockkn1992** [comment]
*** Settings ***
Library           SSHLibrary
Library           mylibrary

*** Test Cases ***
Ip_address
    open connection    192.168.1.1    timeout=1minute
    login    darshan    cisco
    ${v}=    initializeconnection
    Ip_address_Validate    172.19.254.240    ${v}
    Ip_address_Validate    192.168.1.1    ${v}
    close connection

*** Keywords ***
Ip_address_Validate
    [Arguments]    ${ip_address}    ${v}
    ${ip_address}=    Set Variable    ${ip_address}
    Log    The expected output is ${ip_address}
    Log    The observed results is ${v}
    Should Contain    ${v}    ${ip_address}

**Comment by rockkn1992** [comment]
This is how i execute commands..
now its working fine..
but, still i want to know why that error..?

**Comment by pekkaklarck** [comment]
Some problem in the environment.

**Comment by rockkn1992** [comment]
Thank you everyone for your responses..
