### ISSUE TITLE
Report file generation failed with jybot test execution

### ISSUE THREAD

**Issue by rkommine** [robotframework/robotframework#2707]
Hi,

While executing the testcases using the jybot I am getting the following error:

[ ERROR ] Writing report file 'c:\users\rkommine\appdata\local\temp\RIDEeduw9e.d\report.html' failed: No such file or directory: C:\Tools\Jython2.7.0\Lib\site-packages\robot\htmldata\rebot\report.css

I got the same error when executing from ride as well as command prompt.

```
C:\Workspace\JavaSE\ReadExcel>jybot C:\Workspace\RobotFramework\Training12\Testsuite1.robot
==============================================================================
Testsuite1
==============================================================================
TC1                                                                   | PASS |
------------------------------------------------------------------------------
Testsuite1                                                            | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed
==============================================================================
Output:  C:\Workspace\JavaSE\ReadExcel\output.xml
Log:     C:\Workspace\JavaSE\ReadExcel\log.html
[ ERROR ] Writing report file 'C:\Workspace\JavaSE\ReadExcel\report.html' failed: No such file or directory: C:\Tools\Jython2.7.0\Lib\site-packages\robot\htmldata\rebot\report.css

```
When I check the directory C:\Tools\Jython2.7.0\Lib\site-packages\robot\htmldata\rebot\ there is no report.css present

C:\Tools\Jython2.7.0\Lib\site-packages\robot\htmldata\rebot>dir
 Volume in drive C is System
 Volume Serial Number is 66C1-7D9D

 Directory of C:\Tools\Jython2.7.0\Lib\site-packages\robot\htmldata\rebot

26-09-2017  23:32    <DIR>          .
26-09-2017  23:32    <DIR>          ..
26-09-2017  23:32             4,341 common.css
26-09-2017  23:32             1,487 fileloading.js
26-09-2017  23:32             7,304 log.css
26-09-2017  23:32            14,147 log.html
26-09-2017  23:32             6,409 log.js
26-09-2017  23:32            10,589 model.js
26-09-2017  23:32               701 print.css
26-09-2017  23:32            30,035 report.html
26-09-2017  23:32             9,638 testdata.js
26-09-2017  23:32             7,165 util.js
26-09-2017  23:32             6,202 view.js
              11 File(s)         98,018 bytes
               2 Dir(s)  349,158,809,600 bytes free

Could you please help how to fix the issue? Where can I get the report.css file?

Installation details:

Jython 2.7.0
C:\Tools\Jython2.7.0\Lib\site-packages\robot\htmldata\rebot>jybot --version
Robot Framework 3.0.2 (Jython 2.7.0 on java1.8.0_144)

Please let me know if any other details are required.

Thanks in advance.

Regards,
Ramakrishna

**Comment by pekkaklarck** [comment]
report.css is is part of Robot's installation. It thus seems that installation has failed somehow. Unfortunately I have no idea what has gone wrong. You could try reinstallation and see are there any errors or warnings during it.

**Comment by rkommine** [comment]
Hi,

After uninstalling & installing the robotframework, the issue was not present. So this issue can be closed.

`c:\Tools\Jython2.7.0\bin>jython -m pip install robotframework
Downloading/unpacking robotframework
  Downloading robotframework-3.0.2.tar.gz (440kB): 440kB downloaded
  Running setup.py (path:C:\Users\rkommine\AppData\Local\Temp\pip_build_rkommine\robotframework\setup.py) egg_info for package robotframework

    no previously-included directories found matching 'src\robot\htmldata\testdata'
Installing collected packages: robotframework
  Running setup.py install for robotframework

    no previously-included directories found matching 'src\robot\htmldata\testdata'
    changing mode of C:\Tools\Jython2.7.0\bin\jybot.bat to 777
    changing mode of C:\Tools\Jython2.7.0\bin\jyrebot.bat to 777
    changing mode of C:\Tools\Jython2.7.0\bin\rebot.bat to 777
    changing mode of C:\Tools\Jython2.7.0\bin\robot.bat to 777
    replacing interpreter in robot.bat and rebot.bat.
Successfully installed robotframework
Cleaning up...

c:\Tools\Jython2.7.0\bin>cd C:\Workspace\JavaSE\ReadExcel

C:\Workspace\JavaSE\ReadExcel>jybot C:\Workspace\RobotFramework\Training12\Testsuite1.robot
==============================================================================
Testsuite1
==============================================================================
TC1                                                                   | PASS |
------------------------------------------------------------------------------
Testsuite1                                                            | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed
==============================================================================
Output:  C:\Workspace\JavaSE\ReadExcel\output.xml
Log:     C:\Workspace\JavaSE\ReadExcel\log.html
Report:  C:\Workspace\JavaSE\ReadExcel\report.html

C:\Workspace\JavaSE\ReadExcel>`

Regards,
Ramakrishna

**Comment by pekkaklarck** [comment]
Good that the problem was resolved.
