### ISSUE TITLE
Listener for after suite start

### ISSUE THREAD

**Issue by teschnei** [robotframework/robotframework#2710]
The current start_suite listener fires before Suite Setup is executed.  Makes sense, because it has the capability of modifying the suite setup.  However, I have a case where I want to do something externally after the suite setup has run (backing up the database so I can restore it between test cases).  I wasn't able to find a way to do this other than having my test case writers remember to put it in each suite setup (which is doable, but I'd like to keep that burden off of them if possible).  In the same vein, there doesn't seem to be a way to have a hierarchy of suite setups (a top level folder does some setup, and then a subfolder does some more setup, etc), rather the final setup just overrides the first.

At any rate, I can probably take a stab at implementing a listener for after Suite Setup, if the functionality is desired (and the name/arguments are decided).

**Comment by pekkaklarck** [comment]
Couldn't such action simply be executed in first `start_test` after `start_suite`? It shouldn't be too hard to keep track on that.

**Comment by teschnei** [comment]
Yeah, that would work for my case.

If there's no desire then for another listener to make that functionality easier, I'll close this issue.

**Comment by pekkaklarck** [comment]
I don't think it's a good idea to add this kind of hooks to the API itself when it's so easy to implement them in listeners. Having a separate project implementing a base class that adds such hooks might be useful.
