### ISSUE TITLE
Robotframework sometimes hang (without result, no pass or fail) while web browser appear alert/confirm window.

### ISSUE THREAD

**Issue by cath1227** [robotframework/robotframework#2711]
Keep to running the following test case, robotframework sometimes will hang while the alert/confirm window popup.
During hang, if user move mouse or keyboard, the robot script will continue to running.
During hang, if user doesn't do anything, it will keep the "hang" status a long time (over the weekend),  robotframework has no result, no pass or fail.
We find the situation in web code based on **html 5**. Only observer the issue when web test.
In the following test case, after executing "Click Element    link=Sign out", the alert/confirm window popup, however, it will hang ...
The probalility is about 15%~20%.

Environment : 
CentOS 6.4 x86_64
robotframework : 3.0
robotframework-selenium2library : 1.8.0
selenium : 2.53.1
firefox : 45.0.2

*** Settings ***
Library     Selenium2Library

*** Test Cases ***
Test
   login webgui
   logout webgui

*** Keywords ***
logout webgui
    Wait Until ElementIs Not Visible    xpath=.//*[@id='processing_image']/div[2]    timeout=30
    Click Element    css=span.username
    Click Element    link=Sign out
    Dismiss Alert
    Wait Until Page Contains Element    id=main    15    waited too long to login
    Close Browser

**Comment by Tattoo** [comment]
This seems to be the problem of SeleniumLibrary, which has [its own issue tracker](https://github.com/robotframework/SeleniumLibrary/issues). Could you please report the issue there instead?
