### ISSUE TITLE
Execute robot framework test suite multiple times ?

### ISSUE THREAD

**Issue by tucpham** [robotframework/robotframework#2725]
Is there any way config to run the robot testsuite many time ?  Thanks

**Comment by pekkaklarck** [comment]
Yes, you can, for example, create a batch file or a shell script with contents like:

    robot tests.robot
    robot tests.robot

There are many other approaches as well, but you need to tell a bit more about your use case for others to be able to help. Notice also that this issue tracker is for bug reports and enhancement requests. Mailing lists, Slack channel, or other forums listed at http://robotframework.org/#support should be used for general questions.

**Comment by tucpham** [comment]
I tried your solutions but it just run the first testsuite and generate the report so the other TS didnot execute.
my batch file : 

cd C:\RFworkspace\FirstDemo\TestCases
pybot --timestampoutputs LoginFeature.txt
pybot --timestampoutputs LoginFeature.txt
pybot --timestampoutputs LoginFeature.txt
pybot --timestampoutputs LoginFeature.txt
pause

**Comment by tucpham** [comment]
`There are many other approaches as well, but you need to tell a bit more about your use case for others to be able to help. Notice also that this issue tracker is for bug reports and enhancement requests. Mailing lists, Slack channel, or other forums listed at http://robotframework.org/#support should be used for general questions.`
👍  many thanks..I have joined
