### ISSUE TITLE
pybot Incorrectly Evaluates Set Length in External Python Libraries

### ISSUE THREAD

**Issue by iysaleh** [robotframework/robotframework#2726]
Alright, so I finally traced down whats causing my code to halt and have created a minimal test case that can reproduce the issue.

When I run this keyword in pybot which calls the external library, it loops infinitely. When I run the external library myself in python, it works as expected. I have no idea why pybot is interfering with the way python executes code in external libraries but that seems to be the case 😠 ...

Here is the code below.

Code for RobotSetCompareBugLib.py:
```
from random import *
class RobotSetCompareBugLib(object):
        ROBOT_LIBRARY_SCOPE = 'GLOBAL'
        def __init__(self):
                pass
        def get_n_numbers_from_set(self,n_numbers=1):
                all_numbers = set()
                while(len(all_numbers) < n_numbers):
                        all_numbers.add(randint(1,999999))
                return tuple(all_numbers)
```
Code for Robot test case: robot_set_length_bug.robot
```
*** Settings ***
Library           RobotSetCompareBugLib

*** Test Cases ***
Robot Set Compare Bug
    [Documentation]    'Simple test case to reproduce set compare bug that happens with external libs called from  pybot.'
    ${int_one}    ${int_two}=    Get N Numbers From Set    2
    Log    If you get here, this bug doesn't exist or is fixed!    level=WARN
```

To execute:
* Set PYTHONPATH to directory with the RobotSetCompareBugLib.py library file
* pybot robot_set_length_bug.robot

Bug Reproduction Environment:
OS: Red Hat Enterprise Linux Workstation release 7.3 (Maipo)
gcc -dumpmachine: x86_64-redhat-linux
python --version : python 2.7.5
pybot --version:  Robot Framework 3.0 (Python 2.7.5 on linux2)

**Comment by iysaleh** [comment]
Wow I'm dumb... it's just because robot is passing it as a string/unicode...and here I've been using this for over a year now  derp... shame.

**Comment by pekkaklarck** [comment]
Yeah, args are passed to keywords as strings (unless you use variables) and generally keywords should convert strings to numbers internally. The main reason you don't notice the problem immediately is that Python 2 is dump:

```python
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 1 < '2'
True
>>> 1 < '-1'
True
>>> 1 < 'any string whatsoever'
True
```

Python 3 works much better:

```python
Python 3.6.2 (default, Jul 29 2017, 00:00:00) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 1 < '2'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: '<' not supported between instances of 'int' and 'str'
```
