### ISSUE TITLE
Issue:Installing Eclipse IDE for Robot framework Not able to install 

### ISSUE THREAD

**Issue by Savita49** [robotframework/robotframework#2727]
specifications:
Eclipse neon 4.6.3
robot framework 3
windows 10

Error:There are no categorized items

**Comment by nikhilrajgarhia** [comment]
Can you post the error which you are getting? Probably you might be facing some network related error that needs permissions.

**Comment by pekkaklarck** [comment]
This is tracker for Robot Framework itself, not for Eclipse IDE.
