### ISSUE TITLE
Allow stacked keyword decorators in dynamic libraries

### ISSUE THREAD

**Issue by chbndrhnns** [robotframework/robotframework#2729]
I would like to achieve the following which does not seem possible at the moment. It would help to keep the library clean and to easily allow for spelling variants of keywords in addition to using regexes which (as a disadvantage in this case) can only be used in arguments.

```
@keyword('I cannot reach ${dst}')
@keyword('I can't reach "${dst}"')
@keyword('I cannot reach "${dst}"')
def network_address_negation_implicit_context(self, dst=None):
    pass
```

**Comment by pekkaklarck** [comment]
I'm fine with the idea that a keyword has multiple different names, but I'm not sure is it a good idea to implement it by stacking decorators like this. `@keyword` behaving differently depending on does the decorated function already have `robot_name` somehow doesn't feel right. Being able to use `@keyword` to override existing `robot_name` sounds more useful.

In my opinion a better solution would be either specifying the name as a list like `@keyword(['I cannot reach ${dst}', 'I can\'t reach "${dst}"'])` or having some a way to specify the whole name as a regexp. Either way, this would need a PR.

Also, what do you mean with "dynamic libraries" in the title? Dynamic libraries don't even directly support `@keyword` as they return keyword names from the special `get_keyword_names` method.

**Comment by pekkaklarck** [comment]
No interest towards this in two years. Closing.
