### ISSUE TITLE
Add support for **kwargs for keyword methods supporting embedded arguments

### ISSUE THREAD

**Issue by chbndrhnns** [robotframework/robotframework#2731]
Example: 

```python
@keyword('${variable} ${operator:is set to|contains} ${value}')
    def environment(self, variable=None, operator=None, val=None):
    
```

could become something like:

```python
@keyword('${variable} ${operator:is set to|contains} ${value}')
    def environment(self, **kwargs):
        for arg, val in kwargs.items():
            check_arg(arg, val)
    
```

Instead of having to specify all necessary arguments in the function header, I would like to be able to iterate over them easily. Then **kwargs seems useful because in the decorated, the arguments are named anyway.

**Comment by pekkaklarck** [comment]
Sounds good to me. Needs a PR.

**Comment by pekkaklarck** [comment]
Seems to be no interest. Closing.
