### ISSUE TITLE
Robot profiler

### ISSUE THREAD

**Issue by im2geek4you** [robotframework/robotframework#2733]
Hi there,

I don't know if there is already a better tool for doing profiling on robot execution but as far as I know there isn't and IMHO there should be one. There are many keywords that have similar functionality but very different execution times. For example 'Run Keyword If' usually is very slow but 'Should Be True' and other of type 'Should *' are usualy much faster. I've made a smal C# open source tool to analyse rebot/robot logs that allows to analyse the execution of many tests at once and as helped me a lot in making small adjustments that have reduced the execution times by as much as 50%. My tool is on my github account if someone is interested. 

PS: This might not be the right place to post this, but I could not find a way to contact the robot framework developers directly to make them aware of this. I understand this looks like an advertisement to my tool but honestly it is not. I'm just tired of seeing people making bad code and blaming Robot for being slow.  I consider this as giving back to the community.

**Comment by pekkaklarck** [comment]
Such a profiler sounds very useful! Advertising your Robot Framework related tools is totally fine, but you are right that this issue tracker is not the right place. I'd recommend you to announce the project on various [support channels](http://robotframework.org/#support) such as on Twitter (we'll re-tweet as `@robotframework`), robotframework-users mailing list, and/or Slack. If the tool is already mature, you can also ask it to be added to http://robotframework.org pages under tools at https://github.com/robotframework/robotframework.github.com.

Notice also that Robot has public APIs that allow getting information about keyword execution times etc. easily from Python. If you know any Python, or are interested to learn, these APIs would probably make that part easier than parsing output.xml using C#. On the other hand, output.xml parser implemented using C# would be a nice separate component as well!

**Comment by im2geek4you** [comment]
I will use those support channels in the future. Wasn't aware of the Python API, have to check it out. My goal was just to create something that could be simple to use and could provide a graphical representation of the information (there are many interesting patterns when you plot all executions of the same keyword), hence the use of C#, and also because I'm not as proficient doing GUI apps with Python.

**Comment by pekkaklarck** [comment]
The previously mentioned API is documented here:
http://robot-framework.readthedocs.io/en/3.0.2/autodoc/robot.result.html

If you need help using it, just as on the mailing list or Slack. Notice that you could read the data using Python and write it to a sqlite database or a CSV file, and then use C# or anything else to present it.
