### ISSUE TITLE
Desired capabilities is not working for IE11

### ISSUE THREAD

**Issue by mrinalnandi** [robotframework/robotframework#2734]
As per our company policy Security Tab is not enable in IE 11.  We tried to add desired capability for IE for standalone execution in local system but still getting error "WebDriverException: Message: Unexpected error launching Internet Explorer. Protected Mode settings are not the same for all zones. Enable Protected Mode must be set to the same value (enabled or disabled) for all zones."

Code we are using to initiate IE
` ${caps}=    Evaluate    sys.modules['selenium.webdriver'].DesiredCapabilities.${dc name}   
 sys,selenium.webdriver
    
Set To Dictionary    ${caps}    ignoreProtectedModeSettings    ${True}
Set To Dictionary    ${caps}    version   11

 Open browser    ${LOGIN URL}    ${BROWSER}       desired_capabilities=${caps}
`
Enable Enhanced Protected mode is not selected in Advance Tab.

We are using Python 3.6 with 
robotframework (3.0.2)
robotframework-selenium2library (3.0.0b1)
robotframework-seleniumlibrary (3.0.0rc2)
selenium (3.7.0) fetched from pip List.

Could you help us out to resolve this issue.

**Comment by pekkaklarck** [comment]
Wrong issue tracker. Also, we generally use issue trackers only for bug reports and enhancement requests. There are [other support channels](http://robotframework.org/#support) for general questions.
