### ISSUE TITLE
Connect to a Wireless WIFI Network through Robot Framework  ( Windows and Ubuntu)

### ISSUE THREAD

**Issue by momo007** [robotframework/robotframework#2736]
Hello, i have an Issue : 
i want to connect to another WIFI during a Test,

in Windows Command Line , this is working: 
> netsh wlan connect name=name_of_wifi

and in ubuntu:
> nmcli c down connection_Name

but how i can run these through Robot Framework as a Test Step, when i'm in windows or ubuntu: 

*** Settings ***
Library           Selenium2Library
Library           Process
*** Variables ***
*** Test Cases ***
Login in
    Run Process    python    -c    print 'Hello, world!'
    ?

**Comment by pekkaklarck** [comment]
Yeah, we have other forums for general support. And we probably should add issue templates to make that more clear.
