### ISSUE TITLE
ExecutionResult().statistics.total.critical has incorrect statistics -- it has the statistics for all tests instead of for critical tests

### ISSUE THREAD

**Issue by ben-g-** [robotframework/robotframework#2744]
My robot framework XML results file contains the following statistics:

```
<statistics>
<total>
<stat fail="1" pass="75">Critical Tests</stat>
<stat fail="7" pass="75">All Tests</stat>
</total>
...
</statistics>
```

I load that results file and inspect the statistics for critical tests:
```
>>> from robot.api import ExecutionResult
>>> result0 = ExecutionResult("c:/tmp/robotframework-test-results.xml")
>>> stats0 = result0.statistics
>>> stats0.total.critical.total
82
>>> stats0.total.critical.failed
7
```

As you can see, I get the values for all tests instead of for critical tests.

I'm using robotframework 3.0.2, Python 2.7.3 (64-bit), Windows 7 Professional. I've also observed the bug with robotframework 3.0 on a Linux system.

**Comment by pekkaklarck** [comment]
The reason is that ExecutionResult considers all tests critical unless you tell it otherwise. This is same if you'd post-process results with Rebot. Try, for example, this:

>>> result0.suite.set_criticality('your critical tag')

**Comment by ben-g-** [comment]
@pekkaklarck wrote:
> ExecutionResult considers all tests critical unless you tell it otherwise.

But the results file from which I constructed the ExecutionResult contains the information about which tags are non-critical.
`<stat info="non-critical" fail="6" pass="0">inprogress</stat>`

Shouldn't that qualify as 'telling it otherwise'?

This still looks like a bug to me.

**Comment by pekkaklarck** [comment]
Using existing info would be problematic when results are combined or merged. We did that ages ago but it was so complicated that the functionality was removed.

**Comment by ben-g-** [comment]
Thanks for the info, @pekkaklarck. I followed your suggestion to call `set_criticality()`, and it works.
