### ISSUE TITLE
How can I add formatter like %(thread)d, %(funcName)s, %(lineno)d  when I use robot.api.loger?

### ISSUE THREAD

**Issue by xixiaocheng** [robotframework/robotframework#2745]
The default log just show timestamps, log level and msg.

Could I show more information

**Comment by pekkaklarck** [comment]
This issue tracker is for bug reports and enhancement requests. Questions are best asked on mailing lists, Slack channel, or other support forums listed at http://robotframework.org. In this case I don't really understand the question either, so couldn't really answer this question anyway.
