### ISSUE TITLE
in some situations,it will not exit normally but hung up in some sub thread.

### ISSUE THREAD

**Issue by jiangbingo** [robotframework/robotframework#2747]
https://github.com/robotframework/robotframework/blob/3ac75d5212f544018ef1cc99a8b68c222715df5f/src/robot/utils/application.py#L48

**Comment by jiangbingo** [comment]
import os;os.exit(rc) will be ok after verification.

**Comment by pekkaklarck** [comment]
Could you please clarify.

**Comment by pekkaklarck** [comment]
Closing due to lack of information.
