### ISSUE TITLE
execution stuck in continious loop after timeout exceeded error on windows

### ISSUE THREAD

**Issue by baid86** [robotframework/robotframework#2748]
My execution is stuck in following while loop.
I am also wondering why there is an infinite loop witout any exit condition.
Also `time.sleep(0)`  leads to 100% CPU utilization.
there should be some delay in sleep so it CPU gets a breathing time.
`windows.py`
```
def _wait_for_raised_timeout(self):
        if self._timeout_occurred:
            while True:
                time.sleep(0)
```

**Comment by pekkaklarck** [comment]
This code waits for the exception that has been raised in a timer thread to actually occur. `time.sleep(0)` ought to be fine as it still allows other threads to execute. The last time this particular code has been touched was commit 1a5eeaa7f58a90021fa08bef23ce90855a7a8ffd two years ago. Nobody else has reported problems with it so I doubt it's totally broken. You can obviously test changing `0` to, for example, `0.0001` to see does it help.

It's impossible to tell why the problem occurs when you don't provide any more information. Could you tell at least the following:

- Robot Framework, Python and OS versions
- Does this happen always when timeouts expire or only sporadically?
- Do you use test or keyword timeouts?
- Do you get any error messages anywhere?
- How do you know it hangs exactly in this code?

**Comment by baid86** [comment]
> Robot Framework, Python and OS versions

Robot Framework 3.0.2, Windows 7, IE 9 Browser, Python 2.17.3

> Does this happen always when timeouts expire or only sporadically?

I have observed this everytime when timeouts expires but only with IE9, I am certain I dont see this issue with Chrome or firefox on windows.

>Do you use test or keyword timeouts?

Yes I do

>Do you get any error messages anywhere?

Just timeout error.

>How do you know it hangs exactly in this code?

Used pycharm debuuger and attach to running process. There is feature Attach to Running Process.

**Comment by pekkaklarck** [comment]
Some further questions and comments below.

1. Do you use test *or* keyword timeouts? Or are you possibly speaking about some Selenium specific timeout?

2. Which error do you get?

3. It's strange that this would only occur with certain browser. Robot Framework itself doesn't know anything about them. Or is it so that only IE timeouts in general?

4. Does the execution hang forever? How do you stop it?

5. Could you try modifying the code so that you remote the whole `while True` loop?

**Comment by pekkaklarck** [comment]
Closing due to lack of new information.
