### ISSUE TITLE
Parsing failed: UnicodeDecodeError: 'utf8' 

### ISSUE THREAD

**Issue by johanno** [robotframework/robotframework#2749]
If a Testcase has some special characters, such as (ä, ü, ö), the execution of pybot  TestTestSuite.robot fails with this Error:
[ ERROR ] Parsing 'TestTestSuite.robot' failed: UnicodeDecodeError: 'utf8' codec can't decode byte 0xe4 in position 41: invalid continuation byte

Try --help for usage information.

Debbuging this error i've found out, that changing in the"_decode" method in: 
https://github.com/robotframework/robotframework/blob/master/src/robot/utils/utf8reader.py
        return content.decode('UTF-8')    to         return content.decode('UTF-8', 'replace')
fixes this issue.
But i'm not sure if this is the right solution.

**Comment by pekkaklarck** [comment]
You should save the file as UTF-8.

**Comment by johanno** [comment]
Thanks, the problem was in the eclipse settings.

**Comment by anbarasanv** [comment]
> Thanks, the problem was in the eclipse settings.

Hi, Could you please let me, How did you resolve this issue?

**Comment by johanno** [comment]
> > Thanks, the problem was in the eclipse settings.
> 
> Hi, Could you please let me know, How did you resolve this issue?

uff. that was over two years ago. Probably you should just google "eclipse change encoding"
