### ISSUE TITLE
`PYTHONIOENCODING` is not honored with Python 2

### ISSUE THREAD

**Issue by michalanglart** [robotframework/robotframework#2750]
Interpreter: CPython 2.7.13
OS: Windows 7
RF: 3.0.2

As far as I understand the [`PYTHONIOENCODING`](https://docs.python.org/2/using/cmdline.html#envvar-PYTHONIOENCODING) environment variable can be used to enforce the encoding used when writing to stdout/stderr. It does not work however when stdout/stderr is redirected to non-TTY stream under python 2.7.

Following experiments performs print-based debugging. It will mangle the output, but will show the problem. 

1. Modify `console_encode` function in `robot\utils\encoding.py` by adding simple print:

```python
def console_encode(string, errors='replace', stream=sys.__stdout__):
    encoding = _get_console_encoding(stream)
    print('>> ' + encoding)
    if PY3 and encoding != 'UTF-8':
        return string.encode(encoding, errors).decode(encoding)
    if PY3 or IRONPYTHON:
        return string
    return string.encode(encoding, errors)
```
2. open `cmd.exe`
3. run `c:\python27\python -m robot.run test.robot` in the output on console you will see (in my case):
```
>> cp437
```
4. run `c:\python27\python -m robot.run test.robot >out.txt` in the out.txt file you get:
```
>> mbcs
```
5. `set PYTHONIOENCODING=utf8`
6. run  `c:\python27\python -m robot.run test.robot`
```
>> utf8
```
7. run `c:\python27\python -m robot.run test.robot >out.txt`
```
>> mbcs
```

So despite setting `PYTHONIOENCODING` to `utf8` still mbcs is used when stream is redirected to file. This does not happen with python 3.6. Same scenario as above with python 3.6 results in:

```
>> utf8
>> cp1252
>> utf8
>> utf8
```

This whole problem comes from RED Robot Editor issue; https://github.com/nokia/RED/issues/160 . In RED we allow users to start tests from eclipse/RED. When python process is starting, its stdout/stderr streams are taken by parent process and read in order to display the output in `Console` view. Those streams are not TTY, so RF 3.0.2 under python 2.7 encodes everything using `mbcs` codec which results in characters being displayed wrongly since we're trying to decode them using utf-8 encoding. 

From our point of view it would be the best if we could somehow tell robot that it should use utf8 encoding when doing output, so `PYTHONIOENCODING` variable could do it, however it only fixes the problem for us when python 3.6 is used.

The logic which finds encoding to use in RF 2.9.x was different and the characters were displayed properly when process was started from RED even without using PYTHONIOENCODING.

**Comment by pekkaklarck** [comment]
The code responsible on detecting the encoding is at https://github.com/robotframework/robotframework/blob/master/src/robot/utils/encodingsniffer.py

As you can see, Robot tries various approaches to find the encoding. First Robot tries to read encoding from `sys.__stdout__.encoding` but that doesn't work with Python 2 if outputs are redirected. The next attempt depends on the OS. On Windows Robot calls `GetOEMCP` method on the Windows API. The value it gets there doesn't take possible `PYTHONIOENCODING` into account.

One simple sounding solution would be Robot looking `PYTHONIOENCODING` if `sys.__stdout__.encoding` doesn't work. It would need to be tested does Python actually use the value set by `PYTHONIOENCODING` in that case, though.

**Comment by pekkaklarck** [comment]
Do you @michalanglart have ideas how to fix the problem on Robot side?

**Comment by michalanglart** [comment]
Hi,

to be honest I was occupied with different tasks and haven't looked into this since January. I'll try to take a look later this week.

**Comment by michalanglart** [comment]
Ok I had a look at this issue. In my opinion the problem is not located inside encoding detection done in [`encodingsniffer.py`](https://github.com/robotframework/robotframework/blob/master/src/robot/utils/encodingsniffer.py) but rather in `_get_console_encoding` function in [`encoding.py`](https://github.com/robotframework/robotframework/blob/master/src/robot/utils/encoding.py) module.  In case of python 2.x this function at line 76 will choose `SYSTEM_ENCODING` instead of `CONSOLE_ENCODING` for non-tty stream despite the fact `PYTHONIOENCODING` is provided.

If it would choose `CONSOLE_ENCODING` then the `sys.__stdout__.encoding` would be used which is properly set depending on `PYTHONIOENCODING` env variable. To sum up I would propose to make following change in this function:

```
def _get_console_encoding(stream):
    if PY3 or isatty(stream):
        encoding = getattr(stream, 'encoding', None)
        if encoding:
            return encoding
    return CONSOLE_ENCODING if isatty(stream) or 'PYTHONIOENCODING' in os.environ else SYSTEM_ENCODING
```

With function modified this way I was able to have same results as with python 3.x in the experiments above. Do you think this is acceptable as a fix for this issue?

**Comment by michalanglart** [comment]
Another idea I have is to leave [`encoding.py`](https://github.com/robotframework/robotframework/blob/master/src/robot/utils/encoding.py) module as is but based on the fact that either `CONSOLE_ENCODING` or `SYSTEM_ENCODING` is chosen based on stream being `TTY` or not, we could change the way those two are computed. Overall the idea is to have both `CONSOLE_ENCODING` and `SYSTEM_ENCODING` initialized with encoding set in `PYTHONIOENCODING` variable.

Thus [`encodingsniffer`](https://github.com/robotframework/robotframework/blob/master/src/robot/utils/encodingsniffer.py) may be modified:

```
def get_system_encoding():
    platform_getters = [(True, _get_enforced_encoding),
                        (True, _get_python_system_encoding),
                        (JYTHON, _get_java_system_encoding),
                        (UNIXY, _get_unixy_encoding),
                        (WINDOWS, _get_windows_system_encoding)]
    return _get_encoding(platform_getters, DEFAULT_SYSTEM_ENCODING)


def get_console_encoding():
    platform_getters = [(True, _get_enforced_encoding),
                        (True, _get_stream_output_encoding),
                        (UNIXY, _get_unixy_encoding),
                        (WINDOWS, _get_windows_output_encoding)]
    return _get_encoding(platform_getters, DEFAULT_CONSOLE_ENCODING)


def _get_enforced_encoding():
    if 'PYTHONIOENCODING' in os.environ:
        # value of PYTHONIOENCODING can be given with syntax: encodingname:errorhandler
        encoding = os.environ['PYTHONIOENCODING'].split(':')[0]
        if _is_valid(encoding):
            return encoding
    return None
```

@pekkaklarck Any of those two ideas makes sense to you? Or possibly there is another way to enforce Robot to use encoding provided with `PYTHONIOENCODING`??

**Comment by michalanglart** [comment]
I would say IMO first proposal is better. It clearly states, that `CONSOLE_ENCODING` is used whenever stream is `TTY` or when user enforced encoding with `PYTHONIOENCODING`.

In this second proposal code semantics is broken because when `PYTHONIOENCODING` is set we return it in `get_system_encoding` function which should return encoding used by the underlying file system, but `PYTHONIOENCODING` has actually nothing to do with file system - it only overrides stdin/stdout/stderr encodings.

**Comment by pekkaklarck** [comment]
This requires a bit more thinking and I don't have time for that at the moment. I feel the change would anyway be too risky for a minor release, especially when we want to get RF 3.0.3 out ASAP, but I add this initially to RF 3.1 scope.

**Comment by michalanglart** [comment]
Ok, lets leave that for 3.1.

If you will revisit this issue in the future please have a look at potential solutions I've described above. I can provide Pull Request once we agree what can be changed.

**Comment by pekkaklarck** [comment]
There are encoding detection problems also when using Python 3.6 on Windows due to it using [UTF-8 as the console encoding](https://www.python.org/dev/peps/pep-0528/). This encoding works fine if using Python API to communicate with the OS, but if we get content from the system as bytes and try to encode it as UTF-8 it fails due to Windows not really using it. Getting all this right may require larger changes and possibly also a separate issue.

**Comment by pekkaklarck** [comment]
This issues is caused by Robot not even looking at stream's encoding when using Python 2 and the stream is not a TTY. The reason is that typically the encoding is `None` in that case, and with IronPython and Jython the encoding is set incorrectly. It turned out that the encoding is always set if `PYTHONIOENCODING` is enabled and that also makes the encoding correct with Jython. I got a fix with tests ready.
