### ISSUE TITLE
Jybot not recognized as internal or External Command

### ISSUE THREAD

**Issue by apurvabaj** [robotframework/robotframework#2754]
Hi,

While executing our robot framework scripts, we get error "jybot is not recognized as internal or external command"

Steps followed for installation:
1) installed python and set path in environment variables
2) installed jython and set path in environment variables
3) installed robotframework using robotframework-2.9.1.win-amd64.exe

while installing robotframework only two files were created "pybot" ,"rebot" and "robot" . We created jybot .bat file and set path of run.py file created in python\lib\site-packages\robot folder

our application has build over java swing, so we have created one wrapper file in python. we have placed everything in jython folder and trying to execute test cases.

error while execution -- jybot is not recognized as internal or external command.

could you please suggest a solution to this issue

**Comment by apurvabaj** [comment]
Hey any update on the issue

**Comment by pekkaklarck** [comment]
Your PATH configuration is somehow wrong. Also, I'd recommend using RF 3.0.2 and installing directly with Jython. `jython -m pip install robotframework` ought to work.
