### ISSUE TITLE
Change Selenium2Library to SeleniumLibrary in user guide documentation. 

### ISSUE THREAD

**Issue by aaltat** [robotframework/robotframework#2755]
There are few places in the user guide where the Selenium2Library is used. But the Selenium2Library name was changed to SeleniumLibrary in the 3.0 release. Therefore it would be good to update the user guide too.

**Comment by aaltat** [comment]
The #2746 provides a fix for this problem.

**Comment by pekkaklarck** [comment]
Fixed by PR #2746.
