### ISSUE TITLE
FAIL : MemoryError

### ISSUE THREAD

**Issue by emilyed** [robotframework/robotframework#2757]
Hi, 
I have been running some test for a few month now. I recently came across this error:
FAIL : MemoryError
Step in the script : Passing a list of 3576 items.
The test abort and the error raises.
How can I clear this error?
Thank you really much for your help.

**Comment by pekkaklarck** [comment]
The Python process is running out of memory. Simple fix is increasing the amount of memory on your machine. If you already have lot of memory (16GB or more) your tests are most likely doing something that wastes a lot of memory. For example, large lists are best handled in libraries using Python, preferably using  modules implemented in C.

If you run out of memory, there's not much the framework can do. If you are certain this is an issue in the framework itself and it wastes a lot of memory, please provide an example demonstrating the problem.
