### ISSUE TITLE
`Take Screenshot` keyword causes warning when using wxPython 4

### ISSUE THREAD

**Issue by Teddy12090** [robotframework/robotframework#2760]
A warning message is shown of the keyword `Take Screenshot` when using wxPython 4. The message is as below:

*Screenshot.py:352: wxPyDeprecationWarning: Call to deprecated item EmptyBitmap. Use :class:`wx.Bitmap` instead
  bitmap = wx.EmptyBitmap(width, height, -1)*

**Comment by pekkaklarck** [comment]
PR #2759 fixes this. Need to test changes locally before (or at least after) merging it and don't have time for that now.
