### ISSUE TITLE
Log and report are broken if top-level suite has empty name (e.g. running  `_.robot`)

### ISSUE THREAD

**Issue by Tattoo** [robotframework/robotframework#2761]
If one would create a suite file with the character underscore as its name `_.robot`, no warning or error is given.

Since underscore is synonymous to a space, both log.html and report.html do not function correctly -- in report.html for example there is no Test Statistics- nor Test Details tables at all, just headers.

Furthermore, I encountered this issue when creating Robot Framework test cases programmatically through RF API; I had a programming mistake on the construction of the file name, where I created suite name by catenating to string variables together with underscore between -- and of course both string variables happened to have empty string in them. So in this very edge case, it would have been nice for the tool to notify me that this suite file name does not make sense

**Comment by pekkaklarck** [comment]
All files and directories starting with an underscore or a dot are ignored when executing a directory (e.g. `robot tests`), so this problem can only occur when you run the file alone (e.g. `robot _.robot`). I guess we could simply make that an error to avoid problems later on. Not sure should we make it an error to run only `_.robot` or should we do that if file starts with `_` or `.` in general. The latter would be potentially backwards incompatible but ought to be fine in RF 3.1.

**Comment by pekkaklarck** [comment]
It turned out this was easy to fix. Decided to do that instead of preventing running `_.robot`.
