### ISSUE TITLE
inheritance issue when using python inherited function in keywords 

### ISSUE THREAD

**Issue by protatremy** [robotframework/robotframework#2762]
Hi, I'm facing an issue using python inheritance and I don't know if it's a normal behaviour or not. Here is my example:

**in a file ParentClass.py:**

```
from robot.api import logger

Class ParentClass(object):

     def __init__(self, param_one):
         self.one_param = param_one
     def print_my_param(self):
         logger.console("my param:%s" % self.one_param)

```
**in a python file Example.py**

```
from ParentClass import ParentClass

Class Example(ParentClass):

     def __init__(self):
          super(Example, self).__init__()
```

**in a testfile.robot:**

```
*** Settings ***
Library            Example

*** Test Cases ***
I want to print my param
       print_my_param
```

Executing my testcase return an error:
No keyword with name 'print_my_param' found.

Does inheritance not token into account when passing keywords method trough python inheritance?

**Comment by pekkaklarck** [comment]
Do you get errors about importing the library?

**Comment by protatremy** [comment]
No error with the import

**Comment by protatremy** [comment]
Oups yes I have an import issue... my mistake
 **in my test case:
   in a testfile.robot:**
```

*** Settings ***
Library            Example

*** Test Cases ***
I want to print my param
       Example.print_my_param

```
works!
You can close my issue. Sorry for the trouble...
