### ISSUE TITLE
Timeouts do not stop execution if they occur during execution of `log_message` listener method

### ISSUE THREAD

**Issue by skhomuti** [robotframework/robotframework#2763]
Hello,
Test timeout correctly stops long keywords or infinity loops, but certain error from listener's log_message makes test executing much higher timeout.
I found these errors in my prod-system under high load, but this little example also demonstrates the problem:

Test Case:
```
*** Settings ***   
Library  lib.TimeoutLibrary
*** Test Cases ***
Passed Case
    [Timeout]  30 sec
    lib.TimeoutLibrary.Sleep With Logging
```
Library:
```
import logging


class TimeoutLibrary(object):

    def sleep_with_logging(self):
        i = 0
        while True:
            logging.info(i)
            i += 1
```

Listener:
```
class SomeListener(object):
    ROBOT_LISTENER_API_VERSION = 2
    msg = ''

    def log_message(self, message):
        self.msg += message.get('message')
```

The error in the listener is probably a separate bug, but in our system we found both of these errors together. 
Obviously, it arises because of the large amount of data in the operated variable. Separation of this variable into smaller variables, allows to avoid this error in the listener and, accordingly, the timeout error
```[ ERROR ] Calling method 'log_message' of listener 'src.some_random_listener.SomeListener' failed: TimeoutError```

Is this behavior normal, or does it require corrections, in your opinion?

OS: Windows 10, RH7
Robot Framework: 3.0.2
Listener API V2
Python 27, 36

**Comment by pekkaklarck** [comment]
Sorry, I didn't fully understand your problem, especially the problem in the listener.

Does your example fail with TimeoutError? If yes, that sounds right to me.

**Comment by skhomuti** [comment]
Yes, this example fail with TimeoutError (and not in a 30-second timeout), but keyword executing does not stop, it hangs. Such hangs can last up to an hour

**Comment by pekkaklarck** [comment]
OK, now I got it. Apparently the timeout occurs while Robot is running a listener method and thus it doesn't kill the keyword that was being executed. This probably can only occur with the `log_message` listener method. This is definitely a bug.

**Comment by pekkaklarck** [comment]
Been looking at this problem but cannot reproduce it. Does it happen for you always or only sporadically?

**Comment by skhomuti** [comment]
No not always. But our big test run this error is quite frequent.

**Comment by pekkaklarck** [comment]
In the end I was able to reproduce the problem few times but not reliably. This obviously makes debugging and testing possible fixes rather hard. I can emulate the failure by raising `TimeoutError` from `log_message` itself but that's not exactly the same thing.

Good news is that fixing this may be pretty easy, but because I cannot reproduce the real situation I cannot be sure is the fix correct. Could you @skhomuti edit your Robot Framework installation to contain possible fix so that we'd know does it solve it for you? The fix to test can be seen in this diff:

```diff
--- a/src/robot/output/listenermethods.py
+++ b/src/robot/output/listenermethods.py
@@ -13,6 +13,7 @@
 #  See the License for the specific language governing permissions and
 #  limitations under the License.
 
+from robot.errors import TimeoutError
 from robot.utils import get_error_details, py2to3
 
 from .listenerarguments import ListenerArguments
@@ -100,6 +101,8 @@ class ListenerMethod(object):
         try:
             ListenerMethod.called = True
             self.method(*args)
+        except TimeoutError:
+            raise
         except:
             message, details = get_error_details()
             LOGGER.error("Calling method '%s' of listener '%s' failed: %s"
```

**Comment by skhomuti** [comment]
Yes, I'll try it on one of our stands. Be sure to report the result in the next two days.

**Comment by pekkaklarck** [comment]
My plan is to release RF 3.0.3 RC 1 on Thursday around noon UTC. Hopefully you have results before that!

**Comment by skhomuti** [comment]
It's like solving a problem. I added additional logging before Raisa to be sure that I'm catching this problem, and I see the correct completion of the test:
```
==============================================================================
Demo Test                                                                     
==============================================================================
Demo Test.Listener                                                            
==============================================================================
Listener Test                                                         | FAIL |
Test timeout 40 seconds exceeded.
------------------------------------------------------------------------------
Demo Test.Listener                                                    | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Demo Test                                                             | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  C:\Temp\TORS\output\output.xml
[ ERROR ] TimeoutError. Raising...
Log:     C:\Temp\TORS\output\log.html
Report:  C:\Temp\TORS\output\report.html

Process finished with exit code 1
```
Let's add this fix to 3.0.3

**Comment by pekkaklarck** [comment]
Sounds good. Is that `[ ERROR ] TimeoutError. Raising...` message printed by you or some side-effect of the change?

**Comment by skhomuti** [comment]
Yes, it was printed by me. Thank you for solving this problem :)

**Comment by pekkaklarck** [comment]
OK. Please take the forthcoming RF 3.0.3 release candidate into use as widely as possible to make sure the fix works and hasn't caused any side effects.
