### ISSUE TITLE
Title Should Be  should take a message parameter

### ISSUE THREAD

**Issue by rubygeek** [robotframework/robotframework#2765]
Many tests allow you to pass a message on failure, this function is lacking that. Though you can do something similar in other ways, it should be part of the function

One solution might be:
```
${title}=     Get Title
Should Be Equal   My Homepage    ${title}     Page didn't go to the right location
```

But better if we could do 

```
Page Title Should Be  My Homepage  message=Page didn't go to the right location
```

**Comment by bkhouri** [comment]
the `Title should be` keyword doesn't appear to be part of the robot framework core library.  This keyword sounds more to be in the SeleniumLibrary project.  

Can you please confirm which library provides this keyword?
