### ISSUE TITLE
documentation should say librarys defined in initialisation file are not available to lower level tests 

### ISSUE THREAD

**Issue by osde8info** [robotframework/robotframework#2766]
python 3
robotframework 3

http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#initialization-files

documentation should say librarys defined in initialisation file are not available to lower level tests 

ie you must reference your library in every testfile not just __init__.robot

related to #1851

**Comment by pekkaklarck** [comment]
The docs your referred has this:

> Variables and keywords created or imported in initialization files are not available in the lower level test suites. If you need to share variables or keywords, you can put them into resource files that can be imported both by initialization and test case files.
