### ISSUE TITLE
${SUITE NAME} variable does not give correct suite name.

### ISSUE THREAD

**Issue by bbpatel2001** [robotframework/robotframework#2768]
Hello,
I have following folder structure in my framework and **testsuites**  folder has `**__init__.robot**` file in it. Suite Setup keyword called from init file. When I use ${SUITE NAME} variable when I run feature1.robot file. it always gives me  `<projectname>.testsuites` but never gives me `<projectname>.testsuites.module-1.sub-module-1.feature1` or `feature1.robot` file.

When we have init file in folder structure and when we run feature1.robot file, it is difficult to get the suite name.

`__init__.robot`

```
*** Settings ***

Suite Setup   Log To Console    ${SUITE NAME}
```

**Folder Structure**

```
|---------- /testsuites
    |            |------ /module-1 
    |            |         |------- /sub-module-1
    |            |         |         |------- feature1.robot 
    |            |         |------- /sub-module-2 
    |            |         |         |------- feature1.robot 
    |            |         |         |------- feature2.robot 
    |            |         |------- /sub-module-3 
    |            |         |         |------- feature1.robot 
    |            |         |         |------- feature2.robot 
```

**Comment by pekkaklarck** [comment]
If you have directory `testsuites`, it is going to create a test suite `Testsuites` and `${SUITE NAME}` used in the `__init__` file there is going to have exactly that name. This variable contains the so called full name of the test suite that contains the parent suite name as a prefix, and thus if the `testsuites` is itself a child test suite, the `${SUITE NAME}` is going to have a value like `Parent.Testsuites`. If you use `${SUITE NAME}` in some other suite, then the value is going to be the full name of that suite.
