### ISSUE TITLE
Dates of first commits are wrong

### ISSUE THREAD

**Issue by khink** [robotframework/robotframework#2769]
The first two commits: 
- 5b3d4b111501913722c4b835f8a9e1814dd049fb
- 5b5ff277885f9e43e5670f27d1201fdb1abe44e1

Have a date of January 1980. This makes the timeline on the overview page look weird, because graphs start in that year.

**Comment by pekkaklarck** [comment]
Yes, this is true. This is due to a PR we accepted while still being on Google Code that had some dates messed up. Cannot be fixed without rewriting history which would require everyone forking or cloning this project to re-do it. I don't think that's worth it.
