### ISSUE TITLE
RED Plugin - Test Runner Agent: connection failed, Unable to open socket to localhost, Errno 10061 Connection Refused

### ISSUE THREAD

**Issue by pmandayam** [robotframework/robotframework#2770]
With the RED plugin, I am getting the error listed below when I run Robot tests. This error occurs before the tests are run. The tests can be run successfully despite the error coming up. 

The RED eclipse plugin tries to connect to the live message log; it tries a total of 10 times (10 trials), and when it fails to connect on each trial, it outputs the following message in the Eclipse console:

```
TestRunnerAgent: connection trial #[trial number] failed
	Unable to open socket to "localhost:58160"
	error: [Errno 10061] Connection refused
```
Here is my system configuration:

**Operating system:** 64 bit Windows 10
**Python interpret type:** Jython 2.7.0.
**Robot Framework version:** 3.0.2 (I believe). We are using Robot maven plugin 1.4.7.
**RED Plugin version:** 0.8.3.

Robot tests are run with a custom made batch script which contains these commands:

```
@ECHO OFF
SETLOCAL enabledelayedexpansion

SET "removePath=Src.Test.Resources.Robot."
SET man1=%1
SET man2=%2

SHIFT & SHIFT

:loop
IF NOT "%1"=="" (
    IF "%1"=="--listener" (
        SET listener=%2
        SHIFT
    )
	IF "%1"=="-s" (
		SET suitesPath=%2
		SET "suites=!suitesPath:*%removePath%=!"
        SHIFT
    )
	IF "%1"=="-t" (
        SET tests=%2
		SET "tests=!tests:%suitesPath%.=!"
        SHIFT
    )
	IF "%1"=="-i" (
        SET "includes=%2,%includes%"
        SHIFT
    )
	IF "%1"=="-e" (
        SET excludes=%2,%excludes%
        SHIFT
    )
    SHIFT
    GOTO :loop
)

mvn -Dlistener=%listener% -Dsuites=%suites% -Dtests=%tests% -Dincludes=%includes% -Dexcludes=%excludes% generate-resources robotframework:run

:theend
```

My test case is as simple as this:

```
* Test Cases *
Test 1
	Log To Console	hi
```

**Comment by trogdor259** [comment]
It looks like you are referring to the [RED Plugin for Eclipse](https://github.com/nokia/red). I would recommend communicating with the developers of the plugin there. This site is for tracking issues with the base Robot Framework platform and not for third party libraries or extensions.

**Comment by pekkaklarck** [comment]
Yep, this is RED issue.
