### ISSUE TITLE
MAC- Robotframework : WebDriverException: Message: 'chromedriver' executable needs to be in PATH 

### ISSUE THREAD

**Issue by robotTester** [robotframework/robotframework#2772]
Not able to run chrome with robotframework on MAC.
WebDriverException: Message: 'chromedriver' executable needs to be in PATH

Safari browser working fine.

**Comment by bkhouri** [comment]
This is an environment issue and not related to robot framework core.

If you open a terminal, and enter `echo $PATH`, make sure the directory where `chromedriver` is located is displayed.

Also, another way to ensure your environment is setup correctly is that entering `which chromedriver` in a terminal should return something.

If you have any other questions, check www.robotframework.org and go to the Support section to re schedule out to the community for assistance.

**Comment by aaltat** [comment]
Because this is a support issue related to Selenium setup in Mac and not related to the Robot Framework core, I am closing the issue. Please ask help from the user group mailing list or from the Slack as was instructed here: https://github.com/robotframework/SeleniumLibrary/issues/1051
