### ISSUE TITLE
java.lang.IllegalArgumentException: Browser name must be htmlunit (but that is the browser name I passed in)

### ISSUE THREAD

**Issue by pmandayam** [robotframework/robotframework#2776]
I am getting this error:

`java.lang.IllegalArgumentException: Browser name must be htmlunit`

However, that IS the browser name:

`Open Browser	url=https://www.google.com/	browserName=htmlunit`

Here is my system configuration:

Operating system: 64 bit Windows 10
Python interpret type: Jython 2.7.0.
Robot Framework version: 3.0.2 (I believe). We are using Robot maven plugin 1.4.7.
RED Plugin version: 0.8.3.

**Comment by aaltat** [comment]
This is same as this one: https://github.com/Hi-Fi/robotframework-seleniumlibrary-java/issues/36

Therefore I am closing the issue. If you feel that we are incorrect, please send a message and explain why we are incorrect.
