### ISSUE TITLE
Tag name which contains "OR" (uppercase only) is not getting excluded

### ISSUE THREAD

**Issue by arunselvarajdb** [robotframework/robotframework#2778]
Hi,

I'm seeing an issue where tags are not excluded properly when I used tag name `TRANSFORM`. After some trial and error, it looks like any tag which contains "OR" word will have this issue. I looked at the reserved tags and it is not listed.

**Robot Framework Version:**
`robotframework==3.0.2`

**Python interpreter type:**
`Python 2.7.10`

**OS Version:**
Mac OS Sierra - 10.12.6

Repro Steps:
1.) Create a robot file (test.robot) with the below content.
```
*** Settings ***
Force Tags    TRANSFORM
Suite Setup    Suite Setup Test

*** Keywords ***
Suite Setup Test
    Sleep   10

*** Test Cases ***
Test Something
    log    test
```
2.) `pybot -e TRANSFORM test.robot`
3.) You can see tag is not excluded and tests will run

**Comment by arunselvarajdb** [comment]
I think this is happening because of "OR" and robot parses the exclude as `TRANSF` OR `M`.

**Comment by trogdor259** [comment]
@arunselvarajdb is correct. I run all tags in lowercase to avoid this exact situation. This is explained in the [User's Guide](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#tag-patterns).

**Comment by drobota** [comment]
This what I did to fix it in our project. We keep some tags in capital case but run pybot with lowercase tags. Tags are case-insensitive and space-insensitive, so it solves issue.
f.e.
```
*** Test Cases ***
Test Something
    [Tags]     TRANSFORM
    No Operation
```
*run:*
```
pybot -e transform ...
```

**Comment by pekkaklarck** [comment]
Yeah, `OR`, `AND` and `NOT` are considered operators when used with `--exclude` and other tag related options. Easy solution is specifying tags using lower case letters with these options. As @trogdor259 already commented, this is thoroughly explained in the User Guide.

**Comment by arunselvarajdb** [comment]
Thanks guys. We converted tags to lowercase.

**Comment by pekkaklarck** [comment]
Notice that tags in tests can be uppercase like `PORT` or `RANDOM`. It's just with `--include/--exclude` when `OR`,  `AND` and `NOT` are considered operators.
