### ISSUE TITLE
`robot.libdoc` doesn't support specifying doc format although its docs say it does

### ISSUE THREAD

**Issue by shieni** [robotframework/robotframework#2779]
When using the `libdoc` function from from `robot.libdoc` per 
http://robot-framework.readthedocs.io/en/3.0.2/_modules/robot/libdoc.html#libdoc

as `libdoc(library_or_resource, outfile, name, format='reST')`

The documentation states one should be able to pass documentation source parameter `format` like:
```
    :param format: Documentation source format. Possible values are ``ROBOT``,
        ``reST``, ``HTML`` and ``TEXT``. Default value is ``ROBOT`` but
        libraries can override it themselves.
```

But when calling the function with argument `reST` an error message `Format must be 'HTML' or 'XML', got 'REST'` appears. So it would seem the `_verify_format` method of class `LibDoc` is called with the wrong arguments.

**Comment by pekkaklarck** [comment]
Thanks for the report. You've encountered a documentation bug and a missing feature:

- The `format` argument accepted by `robot.libdoc()` is not the the documentation source format but the format Libdoc ought to use when writing the output (i.e. same as `--format` command line option). The docs are clearly wrong.

- It seems that `robot.libdoc()` doesn't support specifying the source format (i.e. `--docformat` option). This functionality needs to be added.

Hopefully it's possible for you to specify the source format in the library source code.
