### ISSUE TITLE
Close All Browsers and alert js beforeunload

### ISSUE THREAD

**Issue by pstefanowski** [robotframework/robotframework#2787]
Hi
I have website with recently added event beforeunload
simply example 
    <script>
        window.addEventListener('beforeunload', (e) => {

            var confirmationMessage = "Are you sure?";

            e.returnValue = confirmationMessage;
            return confirmationMessage;
        })
    </script>

and Close All Browsers takes 50-60 seconds

I have founded workaround for me :
Execute Javascript    window.open('', '_self', ''); window.close();
and
Run    sudo killall chrome
and
Terminate All Processes    kill=true

but for me is not perfect, it is any nicer way?

**Comment by pstefanowski** [comment]
uhh suppose to create an issue here https://github.com/robotframework/SeleniumLibrary/issues

**Comment by pekkaklarck** [comment]
Yeah, this is not about Robot itself but about SeleniumLibrary. Also, questions are best asked on various support forums listed at robotframework.org. We use isse trackers only for big reports and enhancement requests.
