### ISSUE TITLE
Enhancement: Add execution times for each case, default is 1

### ISSUE THREAD

**Issue by huaping** [robotframework/robotframework#2789]
I have a test request for executing some test cases multiple times in robotframework and have the test cases pass/fail status individually in report. Now I use for loop to execute but I get only one Pass/Fail status for all executions.

**Comment by pekkaklarck** [comment]
We've got similar requests also earlier, but so far nobody has been abke to design how this should work without making the test data overly complex. Do you have ideas how this should in practise?

**Comment by pekkaklarck** [comment]
Closing due to lack of new info. Notice that in general we believe that orchestration belongs to external tools and not to the core framework.
