### ISSUE TITLE
Question:Which IDE you recommend for developing robot cases in python3 env

### ISSUE THREAD

**Issue by luisxiaomai** [robotframework/robotframework#2790]
Hi,

I want to know which IDE you recommend for developing robot cases in python3 env. RIDE is out of maintenance and I can't find a good tool to develop, run and debug cases. 

B.R.
Luis

**Comment by pekkaklarck** [comment]
Good question with no single right answer. Because this issue tracker is only for bug reports and enhancement requests, the question should be be asked on the [available support forums](http://robotframework.org/#Support).
