### ISSUE TITLE
Show line numbers in log.html

### ISSUE THREAD

**Issue by gliviu** [robotframework/robotframework#2791]
Identifying the exact place an error occurs from the output of a test execution can be pretty difficult for complex scripts.
Usually we get the stack trace (python, java, ...) but with robotframework we have to match the content of log.html with our actual robot file.
My suggestion is to add line numbers in logging report.
For example
```
*** Test Cases ***                                   # Line 1
test                                                 # Line 2
    ${expected}  Set Variable    2                   # Line 3
    ${actual}    Set Variable    3                   # Line 4
    Should Be Equal    ${expected}    ${actual}      # Line 5
```
would log something like
![image](https://user-images.githubusercontent.com/8597812/37966170-4c53e214-31d0-11e8-84d8-53b5436eb679.png)

**Comment by pekkaklarck** [comment]
I'm afraid it would be hard to add this information without adding too much noise, especially because with nested keywords also needed to show the file where the keyword is defined. Perhaps having such information inside keyword like `Documentation` would work. Anyway, a precondition is preserving line numbers during parsing #549 which is not likely to happen in the near future. I close this issue and we can look at it again once #549 is done.

**Comment by sachinthakare-cohesity** [comment]
There is a way to do this. 
If you are using Python to write TCs, use traceback in your python code.
-----------------
import traceback

try:
    <python code>
except Exception as e:
    traceback.print_exec()
--------------------
So, whenever u get exception, print_exec() will print the stack trace for you.

**Comment by koffie** [comment]
@pekkaklarck it seems that #549 is solved now. It would be awesome if this could be looked at again since it would make looking where the error occurred significantly easier.

**Comment by koffie** [comment]
Actually it seems that with #549 fixed some thirdparty already created a tool for this that shows the line numbers in the command line output (sadly not in log.html). See https://pypi.org/project/robotframework-stacktrace/

**Comment by pekkaklarck** [comment]
Line numbers are preserved in the running model with test, keywords and control structures, but in the result model that is used when generating the log file line numbers are stored only for tests (#4202). With keywords and control structures line numbers wouldn't be enough without source information. All this information then would need to be stored in output.xml files making their size considerably bigger. I'm afraid the increased file size would be too big problem considering the benefits, but this can certainly be discussed.
