### ISSUE TITLE
Use new logo as favicon in output files

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#2793]
The cool new logo should be taken into use as a favicon of log, report and Libdoc and Testdoc result files.

**Comment by pekkaklarck** [comment]
The new favicon takes more space than the earlier. The difference isn't big enough to really matter, but if someone with better image editing skills can create a smaller variant that would be great. The original logo (which obviously needs to be cropped) can be found from here: https://github.com/robotframework/visual-identity/blob/master/logo/robot-framework.png

**Comment by HelioGuilherme66** [comment]
I did some operations on your favicon.ico, removed transparency layer (changed to white) and reduced the number of colors. This is the resulting link:
```
<link rel="icon" type="image/x-icon" href="data:image/x-icon;base64,AAABAAEAEBAQAAEABAAoAQAAFgAAACgAAAAQAAAAIAAAAAEABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAHB4dACMlIwA6PDsASkxLAFRWVQB2eXcAh4qIAJOXlQChpKIAur27AMvOzADf4uAA7fDuAPz//QAAAAAA7lAAAAAABe7kASIiIiIQTlA+7u7u7uMFA+7u7u7u7hAD7oiIiIjeIAPmAAAAAC4gA+67u7u77iAD7u7u7u7uIAPqfonmru4gA+MLEeAE7iAD7AAJ7jBuIAPu587u7e4gA+7u7u7u7iBQTu7u7u7kBOQDMzMzMzA+7lAAAAAABe4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA">
```
Also attach the file
[robot-framework2.zip](https://github.com/robotframework/robotframework/files/1860360/robot-framework2.zip)
.

**Comment by HelioGuilherme66** [comment]
I will re-do it, then.

**Comment by pekkaklarck** [comment]
Great! If making smaller favicons without lowering quality too much turns too complicated, we can simply keep using the current ones. If we want to make logs/reports smaller, time would be better spent in studying how could HTML, Javascript and CSS be minified.

**Comment by HelioGuilherme66** [comment]
So this is the final edit of the favicon.ico. From my previous icon size increased from 318 bytes to 894 bytes.
```
<link rel="icon" type="image/x-icon" href="data:image/x-icon;base64,AAABAAEAEBAAAAEAGABoAwAAFgAAACgAAAAQAAAAIAAAAAEAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/1UA/1UAAwEAAgAAAgAAAgAAAgAAAgAAAgAAAgAAAgAAAgAAAgAAAwEA/1UA/1UA/1UAAwEAAgAAAgEAAgAAAgAAAgAAAgAAAgAAAgAAAgAAAgAAAgEAAgAAAwEA/1UAAwEAAgAAAwEA/1UA/1UA/1UA/1UA/1UA/1UA/1UA/1UA/1UA/1UAAwEAAgAAAwEAAgAAAwEA/1UA/1UA/1UA/1UA/1UA/1UA/1UA/1UA/1UA/1UA/1UA/1UAAgEAAgAAAgAAAwEA/1UA/1UACQUACQUACQUACQUACQUACQUACQUACQUAKg4A/1UAAgAAAgAAAgAAAwEA/1UABgIAAgAAAgAAAgAAAgAAAgAAAgAAAgAAAgAAAgAA/1UAAgAAAgAAAgAAAwEA/1UA/1UADwUADwUADwUADwUADwUADwUADwUADwUA/1UA/1UAAgAAAgAAAgAAAwEA/1UA/1UA/1UA/1UA/1UA/1UA/1UA/1UA/1UA/1UA/1UA/1UAAgAAAgAAAgAAAwEA/1UACwQABgIA/1UACQUACAMA/1UABgIACwQA/1UA/1UA/1UAAgAAAgAAAgAAAwEA/1UAAwEAAgAADwUAAgEAAgEA/1UAAgAAAgAAAwEA/1UA/1UAAgAAAgAAAgAAAwEA/1UAGAgAAgAAAgAAAgAACAMA/1UA/1UAAwEAAgAABgIA/1UAAgAAAgAAAgAAAwEA/1UA/1UA/1UABgIAGAgA/1UA/1UA/1UA/1UAKg4A/1UA/1UAAgAAAgAAAgAAAwEA/1UA/1UA/1UA/1UA/1UA/1UA/1UA/1UA/1UA/1UA/1UA/1UAAgAAAgAAAwEAAgAAAwEA/1UA/1UA/1UA/1UA/1UA/1UA/1UA/1UA/1UA/1UAAwEAAgAAAwEA/1UAAwEAAgAAAwEAAwEAAwEAAwEAAwEAAwEAAwEAAwEAAwEAAwEAAgAAAwEA/1UA/1UA/1UAAwEAAgAAAgAAAgAAAgAAAgAAAgAAAgAAAgAAAgAAAgAAAwEA/1UA/1XAAwAAgAEAAB/4AAA//AAAP/wAACAEAAA//AAAP/wAAD+8AAAkjAAAMcQAAD/8AAA//AAAH/gAAIABAADAAwAA">
```
Again attach the file:
[robot-framework2.zip](https://github.com/robotframework/robotframework/files/1864338/robot-framework2.zip)

**Comment by pekkaklarck** [comment]
This version isn't as good quality as the current version. In the example below, the one on left is the current and the one on right the new one.

![favicons](https://user-images.githubusercontent.com/114985/38251723-ed1731e4-375a-11e8-8c9a-2095d044fc10.png)

After base64 encoding this version is 1192 characters while the current one is 1536. The new one is clearly smaller, but in my opinion the difference in size isn't big enough to compensate the difference in quality.

**Comment by HelioGuilherme66** [comment]
I agree.
I will do one more attempt.

**Comment by HelioGuilherme66** [comment]
@pekkaklarck Here my final attempt (it was hand edited).
![imagem](https://user-images.githubusercontent.com/2866630/38335737-4e47244a-3857-11e8-8542-6b0bd5fab5dc.png)
[robot-framework.zip](https://github.com/robotframework/robotframework/files/1877753/robot-framework.zip)

**Comment by pekkaklarck** [comment]
The current version still looks quite a bit better for me. It seems we'd need some very special favicon minimizing magic to make it smaller without affecting quality.
