### ISSUE TITLE
Process library keywords leave file descriptors open on Python 2

### ISSUE THREAD

**Issue by slxiao** [robotframework/robotframework#2794]
Hi,

I meet such an "address in use" issue:

In robot case (main process), we first start a thread listening to port 12345, then we start a process (child process) listening to another port.

However, after we stop the above thread, the child process will be listening to 12345, making the re-start of the thread failed with "address in use error".

When we add an argument (close_fds=True) to Popen call in Process.py. The above error will not occur.

So, can you add close_fds as a new parameter to the "Run Process" keyword? So we can control the value of close_fds. Or, we can have other solutions ?

Thanks.

**Comment by pekkaklarck** [comment]
We probably could just use `close_fds=True` outside Windows where it cannot be used if stdin/out/err are redirected (which we do). The default has actually been changed to True in Python 3 (outside Windows) so the change would only affect Puthon 2. If our tests pass with the change, it can be included in RF 3.0.3.

**Comment by slxiao** [comment]
Hi, got it. Thank you very much for the quick response.

**Comment by pekkaklarck** [comment]
Tested `close_fds=True` on Linux with Jython and Python versions 2.6-3.6 and encountered no problems. Creating test that would have validated the fix reliably would have too complicated so decided to just comment the code to avoid someone changing it later.

**Comment by slxiao** [comment]
OK. Thank you very much -:)
