### ISSUE TITLE
output.xml is not getting created properly. <msg> tag does not have closing tag at times

### ISSUE THREAD

**Issue by baid86** [robotframework/robotframework#2797]
I have recently started using pyscreenshot for getting desktop screenshots.
The XML being generated properly most of the times.

```
> <msg timestamp="20180327 17:48:22.295" level="DEBUG">running "None" in child process</msg>
> <msg timestamp="20180327 17:48:22.551" level="DEBUG">STREAM 'IHDR' 16 13</msg>
> <msg timestamp="20180327 17:48:22.551" level="DEBUG">STREAM 'IDAT' 41 65536</msg>
> 
```

But at time I see XML like this. It is happening frequently but not always. And I dont have a consistently reproducible scenario at this time.

```
<msg timestamp="20180327 18:04:54.346" level="DEBUG">Cannot Take Browser Screenshot, Taking Monitor screen shot instead</msg>
<msg timestamp="20180327 18:04:54.346" level="DEBUG">running "None" in child process</msg>
<msg timestamp="20180327 18:04:54.350" level="DEBUG"></doc>
```

The messaged being printed are the log.debug messages from pyscreenshot library.
which causing error at the end while generating reports from it.  If you see in laer case <msg> does not have closing tag.

Workaround for this is to use fixxml before generating xmls

**Comment by pekkaklarck** [comment]
Closing due to lack of information.
