### ISSUE TITLE
robot framework builtin function does not support multiple thread?

### ISSUE THREAD

**Issue by xczhang07** [robotframework/robotframework#2800]
class Test(object):
    
    def __init__(self):
        self._thread_pool = {}
    
    def run_keyword(self, keyword, *args):
        BuiltIn().run_keyword(keyword, *args)

    #def runner(self, keyword, *args):
    #    print keyword
    #    BuiltIn().run_keyword(keyword, *args)
    
    @keyword
    def run_keyword_async(self, keyword, *args):
        
        def runner(*args):
            BuiltIn().run_keyword(keyword, *args)
        
        t = threading.Thread(target=runner, args=args)
        t.start()

I write the above program, it seems does not work when I call  Test.Run Keyword Async (report error that cannot find out argument); however, it works if I call Test.Run Keyword, what can I do to fix this issue?

**Comment by pekkaklarck** [comment]
Robot Framework isn't thread safe and thus running keywords in parallel isn't possible. We already have issue #1792 about this. With the limited development resources we unfortunately cannot give any estimates when this could be fixed.
