### ISSUE TITLE
variable value with special characters like =,>,< 

### ISSUE THREAD

**Issue by Hariniravi8** [robotframework/robotframework#2801]
Hello,
I want to pass value "0,>6,<100" to a textbox, so when I define the same, am getting an error like"got positional argument after named arguments." How to resolve this.

**Comment by HelioGuilherme66** [comment]
You don't even say what keyword you are using. But most probably you need to escape with '\' those symbols, search documentation about this.

You are not really reporting an Issue, and this issue tracker is only for bug reports and enhancement requests, the question should be be asked on the [available support forums](http://robotframework.org/#Support).

**Comment by pekkaklarck** [comment]
As I already replied on the mailing list, the `=` character is causing a problem with our keyword and needs to be escaped like `\=`.
