### ISSUE TITLE
How to get text in dialogs.

### ISSUE THREAD

**Issue by truyenkv** [robotframework/robotframework#2803]
Hi All,
In my webapp, after clicking deleted button, a confirm dialogin is shown. I need confirm that the text displays in dialog correctly or incorrectly. How can I do it?
I tried use Dialogs library with keyword "

Execute Manual Step | message, default_error=
 but it isn't useful for me. please give me some suggestion for resolve my issue.
Thank so much!

This is my dialog (copy and paste in new tab)
[https://drive.google.com/file/d/1CaCyQ7iyGom-v_dDLqVyc0rcUoEZpXaN/view?usp=sharing](image)

**Comment by pekkaklarck** [comment]
This tracker is for bug reports and enhancement request. For general questions we have other support forums like the robotframework-users mailing list and the very active Slack community. See the support section at http://robotframework.org for more details.

Finally, it would be good to tell a bit more about the problem you are facing when asking for help. Without telling what kind dialog you get it's impossible to help. At least I'm not interested to open external and somewhat random links just to find out.
