### ISSUE TITLE
Can't goback to xxxx-report.html from xxxx-log.html with the button 'REPORT' on the  top right corner

### ISSUE THREAD

**Issue by tsbxmw** [robotframework/robotframework#2808]
# I can go to the log page 'FlashDailyBuildlog.html' with the button 'LOG' 
![log_1](https://user-images.githubusercontent.com/15834891/38801932-ba68968c-419d-11e8-96f2-aeb1b58e5e2d.PNG)
# But I can't go back to the report page 'Flash Daily Build.html' with the button 'REPORT'
![log_2](https://user-images.githubusercontent.com/15834891/38802157-4cf09fea-419e-11e8-80b0-1be4da8a1131.PNG)
# any help would be appreciated.

**Comment by tsbxmw** [comment]
`function addReportOrLogLink(myType) {
    var url;
    var text;
    var container = $('#report-or-log-link');
    if (myType == 'Report') {
        url = window.settings.logURL;
        text = 'LOG';
    } else {
        url = window.settings.reportURL;
        text = 'REPORT';
    }
    if (url) {
        container.find('a').attr('href', url);
        container.find('a').text(text);
    } else {
        container.remove();
    }
}`

**Comment by tsbxmw** [comment]
## I have found something in the source of log html.
> reportURL : is setting to 'report.html' which cause the problem.
> splitLogBase : is seeting to 'FlashDailyBuildlog' which is right.
> I am confusing now. any help would be appreciated.
```javascript
window.settings = {"defaultLevel":"TRACE","minLevel":"INFO","reportURL":"report.html","splitLogBase":"FlashDailyBuildlog","title":""};
```

**Comment by pekkaklarck** [comment]
This happens with all reports/logs or with some? Any specific command line options you use?

**Comment by tsbxmw** [comment]
I am using the python code to run the testcases now.

```python
suite = TestSuiteBuilder().build('FlashDailyBuild.robot')
result = suite.run(output='./output/output.xml')
ResultWriter('./output/output.xml').write_results(report='./report/report.html', log='./report/FlashDailyBuildlog.html')
```
```robot
*** Variables ***
${ip}    10.16.129.27

*** Settings ***
Documentation       [test]
Library     flash_slamware.py

*** Test Cases ***
Flash Daily Build
    [Documentation]     Flash Daily Build to Zeus
    ${sign}     FlashDailyBuild
    Log to console      ${sign}
    should be equal     ${sign}    success
```

**Comment by tsbxmw** [comment]
Sorry for all of this issue:
I have used command to rename report.html!!!
```shell
move report.htm 'Flash Daily Build.html'
```
