### ISSUE TITLE
Enhancement Request:Add keyword level tag filtering during robot run

### ISSUE THREAD

**Issue by toniah** [robotframework/robotframework#2810]
Similar to test tag with which we can decide which test to run test tags inclusion/exclusion, we would like to decide which keyword(python or robot keyword) to run using keyword tags. For example, below are 2 test cases:
Plan LT Case1
- plan lt TYPEA

Plan LT Case2
- plan lt TYPEA
- plan lt TYPEB         
      
keyword:            plan lt TYPEA is with tagA, 
keyword:            plan lt TYPEB is with tagB
we hope that with exclude-tag tagA,  plan lt TYPEA is skipped in above 2 cases
with exclude-tag tagB, plan lt TYPEB is skipped in case PLAN LT Case2
with exclude-tag tagC, no keywords are skipped in above 2 cases
Analysis:
1. if else judgement is not sound solution for us, since we do not want so many if else judgements in places where we want to differentiate which keyword to run
2. dynamic library only works for python keyword(namely python library)
Conclusion:
We hope keyword tag can work during test run for keyword skipping

**Comment by pekkaklarck** [comment]
You'd want to be able to select, from the command line, which keywords are executed, right? Skipping a keyword entirely isn't possible at the moment, but there are various ways to execute a different keyword dynamically. If you'd need this only few times, simply using `Run Keyword If` would be a good solution, but in larger usage that adds lot of noise. What I'd propose instead is implementing same keyword multiple times with different implementation and using a variable to select which library or resource file to import:

```robotframework

**Comment by toniah** [comment]
Thanks!
In our case, we have many existing keywords implemented for a kind of LT type.Now we have a new kind of LT type, some of old keywords are not applicable to the new LT type. We do not want to change existing cases and keywords ,so we used prerun modifier to remove some kws in start_suite/start_test accoridng to our rules.To make it a more general solution, we also want to remove some kws in start kw, but find we can't. So come to robotframe work for help.

**Comment by pekkaklarck** [comment]
It sounds like having different implementation for these keywords depending on the LT type would work very well here. Same changes to tests to make the keywords more generic might be needed but in general you ought to be able to use same tests. For me this sounds much more straightforward and easier to understand than automatically skipping some keywords.

**Comment by pekkaklarck** [comment]
I don't consider skipping tests automatically based on tags a good idea. I'm sure there are better solutions, like the one I proposed above, to solve the same use case.
