### ISSUE TITLE
Document that importing library implemented as module with absolute path requires no trailing slash

### ISSUE THREAD

**Issue by modrz** [robotframework/robotframework#2821]
Documentation says:

> If the library is a file, the path to it must contain extension. For Python libraries the extension is naturally .py and for Java libraries it can either be .class or .java, but the class file must always be available. If Python library is implemented as a directory, the path to it must have a trailing forward slash (/).

But both paths are accepted:

```
Library    C:/path/to/libraries/py_module
Library    C:/path/to/libraries/py_module/
```
Is it inconsistency between documentation and actual behavior, or different problem?
I checked Robot Framework 3.0.2 with different python interpreters.

**Comment by pekkaklarck** [comment]
Needed to look at the code and test this myself to see how it actually works. If the path is absolute, like in the examples above, it doesn't matter does it end with a trailing slash or not, but if it's relative then the slash is needed. We have three options what to do:

1. Require the trailing slash also with absolute paths. This would be backwards incompatible and I don't think it's a good idea.
2. Never require the slash. The main problem is that you cannot tell does a name like `Example` refer to an importable module (e.g. `SeleniumLibrary`) or is it a relative path to a directory. This is the exact reason we decided to require the slash.
3. Update the docs to tell that the slash is only needed with relative paths. This is probably the best solution. Do you @modrz have time and interest to look how the docs could be enhanced?
