### ISSUE TITLE
Add a generic string format keyword

### ISSUE THREAD

**Issue by elyssonmr** [robotframework/robotframework#2822]
I would like to propose a generic string format keyword giving a more clean and generic way to format strings.
As suggested by @pekkaklarck in Slack this keyword could be something like this example:
```
${result} =    Format String    Template with {x} and {y}    x=foo    y=bar
```

This enhancement should solve some substituitions issues like this [gist](https://gist.github.com/mayribeirofernandes/104595f2a92fe2b6939b0b7ba6ca3a61) from @mayribeirofernandes.

**Comment by pekkaklarck** [comment]
Yeah, let's do this. Ought to be easy by using [str.format](https://docs.python.org/3.6/library/stdtypes.html#str.format).

The main use case is having a template in a file and replacing values in it. Could even consider supporting passing the template as a path to an existing file in addition to passing it as a string.

**Comment by pekkaklarck** [comment]
This ought to be pretty easy to implement. If there's someone interested to do it, this issue can be added to RF 3.1 scope.

**Comment by elyssonmr** [comment]
I've added the keyword but I haven't added any tests, where can I find them?

Is my documentation clear enough? I don't know if everyone using Robot Framework knows Python well so I change the "args" and "kwargs" to anothers names.

**Comment by pekkaklarck** [comment]
PR #2831 looks pretty good, but there are still few issues that need to be fixed (see my review) before it can be merged. Do you @elyssonmr have time to look at the changes? I try to get RF 3.1 RC 1 out in two weeks.

**Comment by elyssonmr** [comment]
Yes I do. I'm doing it today or tomorrow.

**Comment by pekkaklarck** [comment]
Thanks for updates @elyssonmr. Added some more comments to the PR.
