### ISSUE TITLE
Need Help: "sh: robot: command not found" when trying to execute Robot tests from a Python file.

### ISSUE THREAD

**Issue by ChandrasekarRangasamy** [robotframework/robotframework#2823]
Hi,

I am pretty new to Robot framework and facing below error when trying to execute Robot command from a Python file using Eclipse Pydev.

**`sh: robot: command not found`**

And below is the simple code used in my python file to execute all robot files in the directory which is not working.

```
import os

robot_cmd = "robot *.robot"
os.system("ls")
os.system(robot_cmd)
```
NOTE: 
- Robot test cases are executed successfully when I try the command from a terminal. 
- "subprocess.Popen" is also not working from python file.

On running "os.system("echo $PATH")" found that the path is not the same used in terminal, and updating the path from the script is also not working.

Completely blocked with this. It would be a great help if anyone can guide me on this.. Thanks..!

**Comment by trogdor259** [comment]
what happens if you try `python -m robot *.robot`?

**Comment by ChandrasekarRangasamy** [comment]
Thanks mate for your quick response :-)
Getting below error on try your command..

`  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site.py", line 177
    file=sys.stderr)
        ^
SyntaxError: invalid syntax`

**Comment by trogdor259** [comment]
If you're using python3, use `python -m robot *.robot`

**Comment by ChandrasekarRangasamy** [comment]
Cheers. 👍 that resolved the problem.. Thanks for your valuable inputs..
