### ISSUE TITLE
SSHLibrary.Execute Command never hang up

### ISSUE THREAD

**Issue by manticorps** [robotframework/robotframework#2824]
I am trying to Execute Command on remote target. 

This is working every times on my server, but fail most of the time with exactly the same server when installed on VSphere (the VSphere is manage by my custumer)

I can't give a easy way to reproduce the problem. But I have identify where the problem occurs.

In pythonclient.py

```
class RemoteCommand(AbstractCommand):

    def read_outputs(self):
        stderr, stdout = self._receive_stdout_and_stderr()
        rc = self._shell.recv_exit_status()

        self._shell.close()
        return stdout, stderr, rc
```

The following line never return:
`        rc = self._shell.recv_exit_status()`

As I have read in paramiko documentation :
[paramiko documentation](http://docs.paramiko.org/en/2.4/api/channel.html#paramiko.channel.Channel.recv_exit_status)

The problem can occurs on some system and the recv_exit_status must be receive only after recv.

 I have check the code of SSHLibrary :
- recv is call on stdout
- recv is NOT call on stderr

But I have the same behavior on working server. I have do a quick and dirty workaround and replaced the original read_outputs by :
```
    def read_outputs(self):
        stderr, stdout = self._receive_stdout_and_stderr()
        if self._shell.exit_status_ready():
            rc = self._shell.recv_exit_status()
        else:
            no_rc_available = 1
            rc = no_rc_available
        self._shell.close()
        return stdout, stderr, rc
```

But I silently loose the "return code" information in case of error... This is fine for my usage, as I doesn't use it.

SSHLibrary (tested on 3.0.0 and current master)
Robot Framework version : Robot Framework 3.0.2 (Python 3.6.5 on linux)
Target SSH : VSphere client with Dropbear server v2016.72

**Comment by pekkaklarck** [comment]
Yeah, wrong issue tracker.
