### ISSUE TITLE
Have command line option to display full console output instead of just WARN and FAIL/ERROR

### ISSUE THREAD

**Issue by ozn0417** [robotframework/robotframework#2832]
As of Robot 3.0.2, there is no mechanism to display the "print" or "logging" package messages in the  console output unless they are "WARN" or "FAIL" severity/level.

Requesting feature/option in the command line options to display/stream the full console output as the test executes.

**Comment by pekkaklarck** [comment]
This is pretty much the same request as #1393. Hopefully more verbose output is included in RF 3.1.
