### ISSUE TITLE
Screenshot library enhancements

### ISSUE THREAD

**Issue by piotrpruski** [robotframework/robotframework#2835]
Hello,

On behalf of my team I would like to ask you to implement new features/enhancements in Screenshot library. When using Take Screenshot we would like to have possibility to change format of saved file for example for *.png and have a possibility to change compression ratio - this would help to reduce size of files generated during bigger suites where a lot of Take Screenshot is triggered.

**Comment by ksokolowski** [comment]
Hello.
Yes, the possibility to change file format and compression level would be really helpful. Even with existing default JPG file format it would be great to be able to change compression level. In my team, any larger RF test round is currently generating now about 100 MB of data and most of it are screenshots. Cutting this in half would be great improvement, 
https://blog.codinghorror.com/a-comparison-of-jpeg-compression-levels-and-recompression/
We could safe a lot of disk space on our Jenkins servers, if we could already choose specific compression/quality ratio for JPG files. This could be an option when importing Screenshot library.
When considering new file formats IMO it would be great to also to add support for new WebP files. 
https://developers.google.com/speed/webp/

**Comment by piotrpruski** [comment]
We are using pygtk module.
Seems that in Screenshot library there is used "gdk_pixbuf_save ()" which can be parametrized for format and quality like:
gdk_pixbuf_save (pixbuf, handle, "**jpeg**", &error, "**quality**", "100", NULL);
( https://developer.gnome.org/gdk-pixbuf/2.36/gdk-pixbuf-File-saving.html ).
But for jpeg and png there is different approach/numbers for quality factor. This could be perhaps made somehow like this:
When importing Screenshot library with PyGTK there would be default jpeg format with default compression, but this could be optionally parametrized. When parametrizing user would choose format and compression ratio, for example png and compression ratio between 0-9. Then inside in case of jpeg format compression ratio would be scaled for example multiplied by 11.

**Comment by pekkaklarck** [comment]
Can we come up with config that has a good balance between quality and file size? If yes, I'd be fine just using that without making it possible for users to configure it further.

**Comment by pekkaklarck** [comment]
The problem with making quality configurable is that we have many different backends (Java and .NET native APIs, wxPython, PyGTK, PIL, Scrot, OS screencapture) and supporting them all the same is lot of work and may not even be possible. Creating images that are good enough for normal usages (no visible compression artifacts) but not overly big is a lot simpler solution. If more features are needed, it would probably be better to create a new external library that only supports a single backend like PyGTK.

**Comment by pekkaklarck** [comment]
We now have PR #2868 implementing both PNG support and image quality. That's awesome, but I'm still not certain is making image quality configurable worth the effort. As I've commented above few times, I'd much rather change the code so that created images have a good balance between the image size and quality. That would be easier to implement and test, would require less documentation, and would provide benefits for users without they changing their tests at all. Could someone promoting the idea to make quality configurable comment why that wouldn't work and why configurable quality would be better?

**Comment by ksokolowski** [comment]
Hello. 
This PR #2868 looks great for me and my team. I have already listed all arguments why it is needed in my project. Thanks to configurable quality we can directly influence the size of generated screenshots. And our test suites are taking hundred of them, and we already have quite strict rules, when to take screenshot. So what argument is not to improve this library?

**Comment by pekkaklarck** [comment]
I totally understand the need to get smaller images, but I'm not sure is making the image quality configurable the best solution. Why not just change the code to create smaller images? Would you need to use different quality in different tests or why is *configurability* that important? I've already listed problems I see with that earlier.

**Comment by ksokolowski** [comment]
Hello.
We want to go with compression as high as possible to save space:
https://blog.codinghorror.com/a-comparison-of-jpeg-compression-levels-and-recompression/
In this simple example you have normal quality small jpg file **compression factor 10**  with size 39 kb. And with changing compression level/quality you go down to **compression factor 50** and reduce size to 9 KB. This is totally fine (quality acceptable) for our testing scenario, but i guess in other project it might not be ok.  As I do understand with new PR #2868, those new arguments for Take Screenshot keywords are optional, and we only pass our desired compression level if needed. If we don't pass this argument, Take Screenshot will still work in the old way (automatic compression ratio/quality  based on jpg/png library implementation). 

Please, take a look from 28 days ago when I'm giving two E2E use cases. We might need to save space, we might also need to avoid ANY compression artifact if possible. If we don't care about it we can still use Take Screenshot in the old way.

**Comment by pekkaklarck** [comment]
This library is designed to be used as a simple tool documenting the state of the desktop. Part of that is supporting different backends to remove or at least ease the burden of installing a dedicated tool/module for taking a screenshot. Reducing the image quality a little while considerably reducing the image size, and doing that without any extra configuration, would fit that design extremely well. For me that sounds a lot better than supporting different compression levels, which even aren't supported by all backends, and requiring users to configure them separately every time they use these keywords.

We could obviously both change the default compression level and make compression configurable by the user. Before we do that, I'd like to get some concrete data about differences in quality and size when using different compression levels. Based on the referenced blog post, using compression factor 15 ought to yield images with very little compression artifacts but with highly reduced image size. Could you test is that adequate for your needs? If not, could you explain is the problem with image quality or with size? Is size, how much smaller files you'd get with highest compression level producing good enough images?

**Comment by piotrpruski** [comment]
I don't see this as complicating it's simplicity of usage. I don't understand why you're against this idea. Still it will be easy to use (exactly the same for people who are fine with current size), but it will give an extra option for those who want to reduce size of some/most of their screenshots. Making worse quality as fixed is not a good solution in my opinion. Sometimes that perfect screenshot quality could be desired. Not all backends have to support this, it's not required. 

We could go with both reducing image size&quality and making it configurable.  I'm sorry but I don't have time right now for such tests with enough quality and smaller size, perhaps Robot team could do it. If not then I could do such tests, but I'm not able to do it just now, sorry.

**Comment by ksokolowski** [comment]
Hello.
It looks like discussion here is not very productive. We still need to optimize disc space and we need option to reduce screenshots file size. I guess we might need to take this code into external library, that can be developed and maintained outside of Robot Framework project.

**Comment by pekkaklarck** [comment]
Creating a separate library that has more functionality is a very good idea for various reasons:

- There are lot of other possible enhancements such as taking a screenshot of a certain application or area, having a delay before taking a screenshot (possibly on background), taking multiple consecutive screenshots, recording a video, and so on.

- No need to support all same backends that this library supports. Preferably there should be only one external module or tool that the library uses that could then be declared as a mandatory requirement. This library tries to avoid the need to have a certain external dependency and tries to use modules/tools that are available by default on different platforms.

- Development and releases are not tied to Robot Framework's development schedule.

**Comment by ksokolowski** [comment]
Hello.

New ScreenCapLibrary, has been created by Mihai and is working very well. We can see huge saving in our Jenkins servers when we need to store any test reports with screenshots. Right now with WebP format we are using 50-70% less disk space. In case of one of our subproject we are using about 35 MB per one test suite execution. With regular Screenshot library we needed about 100 MB for the same. If you will multiply this by number of builds that we have, savings are accounted in GBs. 
Even if there are arguments about not doing any improvements to Screenshot library, I guess it would be worth to advertise ScreenCapLibrary on Robot Framework Library page.

**Comment by pekkaklarck** [comment]
Let's keep Screenshot as its now. Those who want more features can use https://pypi.org/project/robotframework-screencaplibrary/.
