### ISSUE TITLE
debug log via robot.api.logger is not filed in output.xml or debug.log

### ISSUE THREAD

**Issue by CharmingYang0** [robotframework/robotframework#2840]
The system invoke robot framework (which was upgraded from v3.0.3 to v3.0.4 recently) in python code as below:
```
from robot import run as robot_run
exe_result = robot_run(test_script,
					   variable=self.rf_variables,
					   exitonerror=True,
					   loglevel='DEBUG',
					   outputdir=outputdir,
					   report=None,
					   debugfile='debug.log',
					   listener=listener_path,
					   include=self.include_tags,
					   quiet=self.rf_quiet_run)
```

And the customized library invoke robot api to logging into RF log file.
```
from robot.api import logger
class MyLibrary(object):
    def execute_ssh_command(self, command):
        ...
        logger.debug("COMMAND {} is executed.".format(command))
        ...
```
The DEBUG text invoked via robot.api.logger cannot be found in either output.xml or debug.log, which worked normally in Robot Framework v3.0.3.

**Comment by pekkaklarck** [comment]
Did I get it right that this worked until RF 3.0.3 but not anymore in RF 3..0.4. That sounds pretty strange because there were no changes to related on between these versions. Can you double check this? If the problem still occurs, please provide a simple example I can use to test it myself.

**Comment by CharmingYang0** [comment]
@pekkaklarck 
Sorry for my late response, I'll try to double check it soon.

**Comment by CharmingYang0** [comment]
It was confirmed that the issue didn't result from robotframework upgrade to 3.0.4.
Close it.
