### ISSUE TITLE
Differentiate "Log" keyword and other keyword logs (add extra attributes to "message" dictionary object)

### ISSUE THREAD

**Issue by ozn0417** [robotframework/robotframework#2841]
If i were to have a script like:
```
*** Settings ***
Resource          ../Resource/Parameter.txt
Library     Test.py


Library    Collections
*** Keywords ***
Read Node detail
    ${step_count_end} =    Set Variable    4
    LOG   "Testing_keyword"
    Set Global Variable     ${step_count_end}
    Should Be Equal     45     456
    text_xyz
    # test_xyz is from Test.py that does print statements.

```

I want to be able to differentiate the "log_message" messages that come in robot listener from "LOG" keyword and something like "Should Be Equal".  The problem I face is that all these messages (including default python print() statements) come as "INFO" severity.  I know I can choose the LOG message to be something other than INFO (like DEBUG or TRACE) but I have requirements to use INFO only.

In the 'log_message' message input argument (this is a dictionary object), it has the following attributes:

- timestamp
- message
- level
- html

Can we add another attribute that provides more info about the type of log message it is?

**Comment by pekkaklarck** [comment]
You can easily see which keyword causes logged messages by implementing `start_keyword` and storing the keyword name there.
