### ISSUE TITLE
Deprecate using `--escape` to escape characters problematic on console

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#2846]
Certain characters like space or semi-colon are problematic on console when giving command line arguments because they need to be quoted or escaped. To make matters worse, escaping rules depend on the console. 

Robot has its own `--escape` option to allow escaping like `--escape SPACE:_` meaning that all occurrences of `_` are replaced with a space. This is kind of handy, but also pretty cumbersome and generally it's easier to just use normal escaping/quoting. This system had real use cases earlier when jython.bat on Windows didn't handle arguments correctly, but that was fixed ages ago and Jython has since switched to jython.exe avoiding the problem altogether.

In my opinion the old `--escape` functionality can be deprecated in RF 3.1 and removed later. If there turn out to be valid uses cases for it during the preview-release period, we can remove deprecation and keep the functionality as-is.

**Comment by nixuewei** [comment]
I just have one test cases.  I want to run our test scripts by jenkins.  and I input the mock json from jenkins param and json files have space.  such as item name is "aaa bbb_c".  I use -E on 3.0.4 is working but if Deprecated, how to success in this scenarios? thanks

**Comment by pekkaklarck** [comment]
Depends on the shell/terminal but typically
```
-v "mockjson:aaa bbb_c"
```
works.

**Comment by maciejep** [comment]
Hi. I use the same stuff -E space:SP -v mockjson:aaaSPbbb_c in argument line in RIDE 1.7.4.1 running on Python 3.7.6.  
"" do not solve this issue

regarding the message:
[ WARN ] Option '--escape' is deprecated. Use console escape mechanism instead
-> how to find the console escape mechanism ??

**Comment by pekkaklarck** [comment]
Console escape mechanism to use depends on the console. Typically quoting valued works.

**Comment by maciejep** [comment]
In fact it do not… maybe it should not be deprecated.
As workaround, I put my path in an argumentfile
