### ISSUE TITLE
`ModuleNotFoundError` when importing a local module from within a function in a Python library

### ISSUE THREAD

**Issue by apolotsk** [robotframework/robotframework#2848]
When we have `test.robot`:

```
*** Settings ***
Library  a/b.py

*** Test cases ***
My Test case
    My Function
```

and `a/b.py`:

```
import c # c.py and b.py are in the same directory.

def my_function():
  pass
```

then `robot test.robot` runs successfully.

However, if `a/b.py` is changed to:

```
def my_function():
  import c # c.py and b.py are in the same directory.
  pass
```

then `robot test.robot` fails with:

```
Traceback (most recent call last):
  File "/home/alex/Downloads/rb/a/b.py", line 3, in my_function
    import c
ModuleNotFoundError: No module named 'c'
```

The reason is in `robot/utils/importer.py`:

```
class ByPathImporter(_Importer):
    ...
    def _import_by_path(self, path):
        module_dir, module_name = self._split_path_to_module(path)
        sys.path.insert(0, module_dir) # This is why import on the top works.
        try:
            return self._import(module_name)
        finally:
            sys.path.pop(0) # This is why import from within a function does not work.
```

**Comment by pekkaklarck** [comment]
I don't consider this a bug. Modifying `sys.path` permanently as part of imports could have hard to debug side effects later. Is there a reason you cannot have `import c` in the module top level? Also, setting `a` into PYTHONPATH before starting execution would solve the problem and allow you to import the library with just `Library    b`.

**Comment by apolotsk** [comment]
> Is there a reason you cannot have `import c` in the module top level?

No critical reason. I prefer to put imports inside functions (even though PEP8 tells to "[always put [imports] at the top of the file](https://www.python.org/dev/peps/pep-0008/#id23)") because it enforces modularity and usability of functions that do not depend to imported non-installed module.

**Comment by pekkaklarck** [comment]
I fully agree with PEP-8 in this case, but you obviously can structure your code as you wish. In that case you just need to make sure the directory containing your libraries is in PYTHONPATH. As I wrote earlier, modifying `sys.path` as part of imports can have annoying side effects.
