### ISSUE TITLE
Question: Testing Web Components (Shadow DOM)

### ISSUE THREAD

**Issue by Georgegriff** [robotframework/robotframework#2858]
We are making heavy use of Web Components in our applications now, which make use of Shadow DOM. I've done a bit of reading around but couldn't find any official statements/advice on how to handle the issue of not being able to easily target keywords at elements in the shadow dom. Would be great to get some thoughts

**Comment by baid86** [comment]
Does not look like robot framework related issue.
you need to check on selenium forums
can also check
https://stackoverflow.com/questions/23920167/accessing-shadow-dom-tree-with-selenium
