### ISSUE TITLE
test case cannot load keyword in resource file that import in the test suite's parent test suite folder

### ISSUE THREAD

**Issue by kanchi240** [robotframework/robotframework#2859]
https://i.stack.imgur.com/LzkEv.png
Hi, I am using robot framework to automate testing of a website, and the image above is the structure of test in the RIDE:

Test: a test suite folder, and I import resource file here, which is in the "init.robot" under the folder
Sub1: a sub test suite, import nothing
test: a test case
My problem is: in the test case "test", robot cannot recognize the keyword that imported in the "Test" test suite folder, because there will be more sub test suites, like sub2, sub3, how can I import resource in one place? I don't want to import the resource file in every test suite, is there a way to do that?

**Comment by kanchi240** [comment]
I see the user guide as below:
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#initialization-files

> A test suite created from a directory can have similar settings as a suite created from a test case file. **Because a directory alone cannot have that kind of information, it must be placed into a special test suite initialization file. An initialization file name must always be of the format __init__.ext,** where the extension must be one of the supported file formats (for example, __init__.robot or __init__.html). The name format is borrowed from Python, where files named in this manner denote that a directory is a module.

Initialization files have the same structure and syntax as test case files, except that they cannot have test case tables and not all settings are supported. **Variables and keywords created or imported in initialization files are not available in the lower level test suites. If you need to share variables or keywords, you can put them into resource files that can be imported both by initialization and test case files.**

I am already put my keyword into the resource file, and import in the top test suite folder, but sub test suite cannot see my keyword and result of test running is fail: No keyword with name 'mykeyword' found.

**Comment by kanchi240** [comment]
@pekkaklarck 
Yes, it is! 
So I need to import my resource file into all the sub test suites one by one? 
And import resource file into their parent test suite directory is not available to the lower test suites/cases?
Means lower test suite can not inherit the imported resource file at the parent test suite directory ?

**Comment by pekkaklarck** [comment]
Yes, individual files need to import everything they need themselves. If you have lot of imports, you can create a resource file that imports everything you need and then import that resource file only in your test case files.

**Comment by kanchi240** [comment]
Thank you for your reply.
