### ISSUE TITLE
__all__ is not working and displays the listner function as well

### ISSUE THREAD

**Issue by p74** [robotframework/robotframework#2862]
When i click in Ride search keywords and select the library
then the listener function is displayed but the "private" function c not
i expect that the listener function is not displayed as well

I try to do `__all__` but it did not work
Is this option(`__all__`) removed as i did use it 2-3 years ago?

how can i hide the listener and other functions?

from robot.libraries.BuiltIn import BuiltIn
from robot.api.logger import info, warn, error

```
__all__ = ['a', 'b']

class ab:

    ROBOT_LIBRARY_SCOPE = 'TEST SUITE'
    ROBOT_LISTENER_API_VERSION = 2

    def __init__(self):
        self.ROBOT_LIBRARY_LISTENER = self
        warn('init')

    def start_suite(self, data, result):
        warn('Listner')

    def a():
        warn('a')

    def b():
        warn('b')

    def _c():
        warn('c')
```

**Comment by pekkaklarck** [comment]
This is all documented in the User Guide. If you want general support, please use the forums listed at robotframework.org. This issue tracker is for bug reports and enhancement requests.
