### ISSUE TITLE
SchemaGenerationError while posting rest API through RobotFramework

### ISSUE THREAD

**Issue by anikamath** [robotframework/robotframework#2863]
We are trying to post one url with json body – 
Post    ${URL}    body=${updatedJSON}
It is throwing this error – 
SchemaGenerationError: Could not find matching type for object: 1528206166000L
Where 1528206166000 is a time stamp in json received by post method.
We are getting JSON response like this (got this using postman) –
"numberType": "TollFree",
                "phoneNumber": "+99999999999",
                "FriendlyName": "(999) 999-5633",
                "purchasedTime": 1528206166000,
                "IsoCountry": "US",
                "Capabilities": {
                    "SMS": "true",
                    "MMS": "false",
                    "Fax": "true",
                    "Voice": "true"
                },
                "organizationID": "2",
Where purchase time is a time stamp in epoch format, while posting it using robotfrmaework it is throwing schemageneration error and adding “L” suffix at the end of number .

**Comment by pekkaklarck** [comment]
This clearly isn't an issue in Robot Framework itself and thus doesn't belong into this issue tracker. That `L` post-fix is most likely added because the value happened to be Python `long`, not `int`. The code creating your `${updatedJSON}` should take `long` type into account.
