### ISSUE TITLE
Keywords from library sensitive to underscore/space with named parameters

### ISSUE THREAD

**Issue by bartkl** [robotframework/robotframework#2866]
Hello,

From what I've experienced and read in the docs, anywhere in robot source code I can interchange spaces and underscores.  However, it turns out that when using named parameters with the user keywords defined in a self-written library, it *does not* accept spaces, only underscores.

Am I missing something here, or is this a bug?

I'm using Robot Framework 3.0.4.

Thanks.
Bart

**Comment by pekkaklarck** [comment]
Named arguments being both case ans space sensitive is documented in the User Guide:
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#named-arguments
