### ISSUE TITLE
How to set date from datepicker in robot framework with ride ide

### ISSUE THREAD

**Issue by swapnali42** [robotframework/robotframework#2869]
How to pick a automated date from datepicker using robot framework with ride ide. 

I have html code like below
`<input _ngcontent-c3="" class="form-control ng-pristine ng-valid ng-touched" formcontrolname="startDate" id="StartDate" name="startDate" tabindex="9" type="date" ng-reflect-name="startDate">`

And I want to pick a date from that datepicker with robot framework for automation testing purpose. 
Please help

**Comment by pekkaklarck** [comment]
This tracker is for bug reports and enhancement requests. Please send general questions to support forums listed at robotframework.org.

**Comment by fbt045** [comment]
but as a library, why seleniumLibrary does not have keyword to handle datepicker?
