### ISSUE TITLE
Add [Before Each] and [After Each] functionality.

### ISSUE THREAD

**Issue by sebastianciupinski** [robotframework/robotframework#2870]
As RF does not support threading now I have idea which my somehow imitate this functionality.
As we cannot create thread which will perform some actions in background, workaround is to execute some keyword before/after each step.
To explain in more, lets assume we are interacting with webpage, but we should fail test case when warning modal window appear. This modal window appears in unpredictable manner.  Now to deal with that, keyword checking this must be manually placed in test scenario. Whith stanzas [Before Each] and [After Each] would be possible to avoid typing keyword many times, but only after proposed controlling sequence:

instead of:
```
TEST_A
    login
    there should be no warning
    type name
    there should be no warning
    click button
    there should be no warning
    page should contain sth
    there should be no warning
```

it can look like this:

```
TEST_B
    [After Each]       there should be no warning
    login
    type name
    click button
    page should contain sth
```

**Comment by pekkaklarck** [comment]
It's possible to implement something like this using listeners. Have you looked at them? Anything special that wouldn't support?

**Comment by sebastianciupinski** [comment]
@pekkaklarck - I didn't know about that. Listeners will resolve my problems as far I can use get BuiltIn().get_library_instance(), but there should not be problems, I assume.

But anyway - I believe that adding option to implement exposed listeners directly in RF files, rather than (or together with) CLI argument will be beneficial for framework itself.

**Comment by pekkaklarck** [comment]
Libraries can register listeners, so it is already now possible to use them without specifying CLI arguments.
