### ISSUE TITLE
[Collection library]  the keyword "List Should Not Contain Duplicates" accepts scalar variable not list variable

### ISSUE THREAD

**Issue by learningandworking** [robotframework/robotframework#2876]
Hi all,

 I am using RF to practice and there is a robot file as below
```
*** Settings ***
Library     Collections

*** Variables ***

*** Test Cases ***
#Example
#    ${index} =    Find Index    baz    @{LIST}
#    Should Be Equal    ${index}    ${1}
#    ${index} =    Find Index    non existing    @{LIST}
#    Should Be Equal    ${index}    ${-1}


Check Value
    @{list}=    Create List     foo     bar     bar
    List Should Not Contain Duplicates      @{list}


*** Keywords ***
```
As the Collection library documentation, the keyword "List Should Not Contain Duplicates" gets 1 argument - "list" to check. But when running this file, I got an issue 
`Keyword 'Collections.List Should Not Contain Duplicates' expected 1 to 2 arguments, got 3.
`
If I change "@{list}" to "${list}", the issue is gone away. 

Had reading user guide, the scalar and list variable are stored in the same internal storage, from what I understand, these 2 kinds of variables have the same behavior when working with a list. So, why does the scalar works well in the code above BUT list?

Please share your ideas and correct for me If I am wrong.

Thanks

**Comment by pekkaklarck** [comment]
This ought to be explained in the User Guide:
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#list-variables

If you have further questions, please send them to support forums listed at http://robotframework.org. This issue tracker is targeted for bug reports and enhancement requests. That said, if the documentation in the User Guide is not clear, submitting issues about enhancing it is totally fine. Do you have ideas how the docs could be enhanced?
