### ISSUE TITLE
Setting relative path as mentioned in robot framework guideline doesnot work

### ISSUE THREAD

**Issue by Amy-Azazel** [robotframework/robotframework#2878]
Hi
![relative_path](https://user-images.githubusercontent.com/29564050/41761922-9afe4ed8-7616-11e8-8797-c5784b7a1542.png)

I am facing this issue on robot framework 3.0.4.
As per the robot framework guide, resource files should be accessible via the following two methods too:
1. Resource     file_name.robot
2. Resource     ../folder_name/file_name.robot

On using, the method 1, the file import is found, however upon executing test-case the following error is displayed:
**_"Error in file 'file_path_for_file_used_for_execution': Resource file 'file_name.robot' does not exist"_**
On using, the method 2, **_the file import is not found_**. Hence, navigating to the resource file clicking the file_path provided or the keyword associated with the files is not possible. But upon executing tests, the tests did run.

Please help me with resolving issues in either of the issues.

Robot Framework v3.0.4
Python v3.6
IDE: PyCharm 2017.3.6
OS: Windows 10 Pro v1803

**Comment by pekkaklarck** [comment]
This is a problem in the IDE or plugin you use. If test execution works fine, then there's no problem in Robot Framework itself.

**Comment by Amy-Azazel** [comment]
Hi @pekkaklarck 
In method 1 the test does not run. Please have a look at the error I have receive and let me know whether it's an issue with IDE or plugin or robot-framework itself.

**Comment by Tattoo** [comment]
It is not an issue in Robot Framework.

In your first example, `Resource     file_name.robot` is a relative path pointing to same folder as the test suite file. Obviously, you do not have the resource file in the same folder. This is also explained in the User Guide.
