### ISSUE TITLE
Is it possible to work wrap value of a dictionary variable key?

### ISSUE THREAD

**Issue by amritansh-diwakar** [robotframework/robotframework#2886]
I would like to word wrap the value of a key while declaring dictionary variable in variable table. Is it somehow possible?

For Ex: Something like below (This is giving error)

*** Variables ***
&{Parameter_Values}
...    url=https://api/getnumberrange/sap/?format=xml
...    verify=False
...    message=<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" 
...  <soapenv:Header/>
...  <soapenv:Body><ain:NumberRangeRequestMessage>
...  <SendingSystem>WDSTCK_TEST</SendingSystem>
...  <RequestRandomizedNumbers>X</RequestRandomizedNumbers>
...  </ain:NumberRangeRequestMessage></soapenv:Body></soapenv:Envelope>

**Comment by pekkaklarck** [comment]
Closing this because I don't understand the question and question in general belong to robotframework-users mailing list, Slack, or other such support forums listed at http://robotframework.org. This tracker is for bug reports and enhancement requests.
