### ISSUE TITLE
User Guide: Adjust Python code examples to be Python 3 compatible

### ISSUE THREAD

**Issue by HelioGuilherme66** [robotframework/robotframework#2895]
In user guide there are many examples of code that would not run on Python 3.

For example the `print 'text'` statement, instead of the `print('text')` function.

**Comment by pekkaklarck** [comment]
Sounds good to me. I don't want the examples to be complicated by adding any Python 2/3 compatibility code, though.

**Comment by pekkaklarck** [comment]
Are you @HelioGuilherme66 working on this?

**Comment by HelioGuilherme66** [comment]
No, I have not started.

**Comment by pekkaklarck** [comment]
Ok, I can take care of `print` myself. Have you seen other "Python 2"isms?
