### ISSUE TITLE
Urgent Need help Robot Framework Selenium

### ISSUE THREAD

**Issue by rheahh** [robotframework/robotframework#2901]
![img_7818 1](https://user-images.githubusercontent.com/41202794/42703236-fc3c15e8-8699-11e8-8eaa-674d660f92ce.JPG)
![img_7819 1](https://user-images.githubusercontent.com/41202794/42703257-105feafe-869a-11e8-98d5-b6a5eb7da6d0.JPG)

Hi, 
In my workplace they have started using Robot framework selenium (python)so  can anyone help me in creating robot framework test scripts please I need to write test scripts for the following scenario:

1.log into a webpage 
2.search for a product 
3.select the quantity of the product
![img_7821 1](https://user-images.githubusercontent.com/41202794/42703344-543cbbbc-869a-11e8-91d1-02c867634172.JPG)

4.click on add to cart (cart/proceed to check out page is displayed )
5.when cart button is clicked proceed to checkout page is displayed

![img_7804 1](https://user-images.githubusercontent.com/41202794/42703168-b389cade-8699-11e8-895a-7da8edb1264b.JPG)
![img_7813 1](https://user-images.githubusercontent.com/41202794/42703184-c6aee2b6-8699-11e8-9c8e-f64b4b82ea5d.JPG)
![img_7816 1](https://user-images.githubusercontent.com/41202794/42703200-db698986-8699-11e8-9840-cda427d3df8f.JPG)

**Comment by trogdor259** [comment]
This is for reporting bugs in the Robotframework platform. It appears like you are looking for assistance in writing codes. There are many guides available online. I would suggest using some of those or finding a usergroup for RF that may help.
Here is a site that may help https://stackoverflow.com/questions/16013692/how-to-write-test-cases-in-robot-framework-with-selenium-library

**Comment by pekkaklarck** [comment]
Yeah, this issue tracker is for bug reports and enhancement requests related to Robot Framework itself. Questions are best asked on dedicated [support channels](http://robotframework.org/#support). Possible SeleniumLibrary issues would also belong to its own tracker.
