### ISSUE TITLE
Get Clipboard method for appium library

### ISSUE THREAD

**Issue by jaskaran0001** [robotframework/robotframework#2902]
We need to use  clipboard method in Appium Library as mentioned in the following link:
https://appium.readthedocs.io/en/latest/en/commands/device/clipboard/get-clipboard/

Can some one please add this method in Appium library for robotframework?

Thanks

**Comment by pekkaklarck** [comment]
Please submit this issue to the issue tracker of the Appium library. This tracker is for Robot Framework itself, not for third party libraries.
