### ISSUE TITLE
Add note in documentation about `${SPACE}` to clarify that it means the ASCII space

### ISSUE THREAD

**Issue by laurentbristiel** [robotframework/robotframework#2903]
From @pekkaklarck : "The above said, the documentation of `${SPACE}` could probably be enhanced to clarify that it means the ASCII space (`\x20`) and other spaces should be specified using the aforementioned escape sequences"

**Comment by laurentbristiel** [comment]
https://github.com/robotframework/robotframework/pull/2904

**Comment by pekkaklarck** [comment]
Thanks for the PR #2904! Not sure would this have required an issue, but since you added it let's include it into RF 3.1 scope as well.

**Comment by pekkaklarck** [comment]
Nice to get a reference to "Yucca's" pages by the way. He was working for Helsinki University of Technology back in the day when I studied there.

Also, didn't know there are *that* many spaces: http://jkorpela.fi/chars/spaces.html
