### ISSUE TITLE
log details like "INFO" is missing when the test runs in FLask

### ISSUE THREAD

**Issue by louislewatcn** [robotframework/robotframework#2914]
I have try to create an api to run robot framework tests
My code goes like below:
```

1 Flask app:

    from flask import Flask
    from testrob import test_robot
    from flask import request
    from robot import run
    app = Flask(__name__)

    @app.route("/test")
    def test():
      request_args = request.args
      rc = test_robot(request_args)
      return str(rc)
```
    
```
    def test_robot(request_args):
      params = parse_reqest_args(request_args)  # logic goes elsewhere
      rc = run(robot_script_path, test=params["testname"], variable=params["inner_args"])
      # robot_script_path is the ./test/robot_test/xxx.robot test file, 
      # params["inner_args"] is the params for the test like  ["scopename:common_test", "suitename:test_login", "testname:OpenBrowser"]
    
    if __name__ == '__main__':
      app.run(host="0.0.0.0")
```

when I hit the url 127.0.0.1:5000/test?&arg1=xx&arg2=xx&arg2=xx
the test will run and logs will be generated but the log is not complete.

Log details:

>     Key Word SeleniumLibrary . Open Browser ${baseurl}, Chrome
>         Documentation:	
>         Opens a new browser instance to the given url.
>         Start / End / Elapsed:	20180727 13:22:17.734 / 20180727 13:22:33.846 / 00:00:16.112

But if create a file, run.py, and run it, the log is complete

```
     from robot import run
     robot_script_path = "./test/robot_test/foo.robot",
     testname= "test_login"
     inner_args=["browser:Chrome", "url:https://www.google.com"]
     rc = run(robot_script_path, test=testname, variable=inner_args)
```

Log details:

```
    Key Word SeleniumLibrary . Open Browser ${baseurl}, Chrome
        Documentation:	
        Opens a new browser instance to the given url.
        Start / End / Elapsed:	20180727 13:22:17.734 / 20180727 13:22:33.846 / 00:00:16.112
        13:22:17.735	INFO	Opening browser 'Chrome' to base url 'https://www.google.com'.
```

The last line log info will missing if the test is called within Flask
![info is missing](https://user-images.githubusercontent.com/23356201/43356163-20f6f73c-925b-11e8-8fed-1c0ee184063a.png)
![normal log](https://user-images.githubusercontent.com/23356201/43356164-212d3626-925b-11e8-8c09-cda207ca34df.png)

**Comment by pekkaklarck** [comment]
I have no idea why logged messages aren't actually logged. If you cannot find the reason yourself, I would need to be able to debug this myself. Can you create a [simple example demonstrating the problem](http://sscce.org/) that I can run locally?

**Comment by louislewatcn** [comment]
@pekkaklarck 
Hi, I think I have found the problem.
The official document has declared that we must  communicate with the robot logs **using main thread**.
Actually, when a request is sent to Flask app, flask will start a thread to run robot tests, which is not the main thread.
I guess this is where the problem lies.

**Comment by louislewatcn** [comment]
[flask.zip](https://github.com/robotframework/robotframework/files/2276570/flask.zip)

**Comment by pekkaklarck** [comment]
Threads are definitely the problem. Can Flask use processes instead?

**Comment by louislewatcn** [comment]
I will have a try with process

**Comment by filug** [comment]
> Threads are definitely the problem. Can Flask use processes instead?

@pekkaklarck Can you give me link with some description to understand this `Threads vs. Logging` issue?

I have this same problem in my solution where I have PyQt based application to configure & execute & monitor execution of RobotFramework tests.

GUI application connects custom `listener version 2` object to monitor tests and show current status to the user; robot is running in separate thread and data between robot and Gui are exchanged via thread-safe Qt signal/slot mechanism.
Everything works perfectly except logs in the log file created by robot.

It's much simpler to establish communication between threads than two separate processes therefore I'd like to understand this _logging_ issue before app refactoring.

**Comment by Treasure17** [comment]
Your (debug) logging messages are getting suppressed by Flask as you're not running in debug mode. If you set the following flag to True, your code will work.

    app.run(debug=True)

Please kindly refer to the link : https://stackoverflow.com/questions/28925451/flask-logging-not-working-at-all

**Comment by HenrikJo** [comment]
@filug Did you find any work around using threads? I am having the same problem: https://stackoverflow.com/questions/52832044/robot-framework-test-inside-a-qthread-does-not-show-variable-values-in-log-file

**Comment by filug** [comment]
@HenrikJo nope. In addition I've found that (because RF is working as a thread not as process) [timeouts](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#timeouts) are also not working.

Right now I'm going to reimplement my app and change QThread by QProcess.

**Comment by pekkaklarck** [comment]
The problem with logging when using threads is discussed in the [User Guide](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#communication-when-using-threads). The problem occurs both when a library uses threads internally and when you you have a controller that runs RF itself in a thread. The best solution to the latter problem is using processes whenever possible.
