### ISSUE TITLE
Keywords are not identified/not auto complete/doens't come for process library.

### ISSUE THREAD

**Issue by vnvbsudhakar** [robotframework/robotframework#2916]
Hello guys,

I don't see any of process keywords are working on my machine. Please let me know if I need to do change my system setup or what is the issue exactly.
None of the keywords are identified from process library. In curious I copied and pasted the example test from Process keyword documentation page (http://robotframework.org/robotframework/latest/libraries/Process.html#Run%20Process), There also I don't see any keyword is recognized in pycharm. Please check attachment for better understanding of my issue.

Thanks,
Sudhakar
8123456633

**Comment by pekkaklarck** [comment]
What Robot version did you use? Can you provide a simple example demonstrating the problem?

**Comment by pekkaklarck** [comment]
Closing due to lack for information.
