### ISSUE TITLE
Init keyword for resource files which runs on import, also supporting parameters

### ISSUE THREAD

**Issue by bartkl** [robotframework/robotframework#2917]
I would love to have the equivalent of Python's `__init__` method for custom initialization of imported resource files. I was thinking maybe adding a `Init` to the `*** Settings ***` table would do the trick. I realize currently this won't be possible due to the import caching, but from what I've read in other issues it seems likely that in the future reimporting will be possible. So this might be a nice feature to take along.

*Example use case*:
Suppose I have a certain table on a web page, which occurs on different pages of the website, and dependent on that page its parent frame is different.

```robot
# Test Page A.robot
*** Test cases ***
Get table title on page A
    Import resource  Table.robot  current page=Page A
    ${title}=  Get table title
    Log  ${title}

Get table title on page B
    Import resource  Table.robot  current page=Page B
    ${title}=  Get table title
    Log  ${title}
```

*** 
```robot
# Table.robot
*** Settings ***
Init  My Init keyword  @{args}  &{kwargs}  # Or it could implicitly assume it gets args and kwargs

*** Variables ***
${CONTAINER FRAME}        //iframe[@name="${CURRENT PAGE} frame"]

*** Keywords ***
My Init keyword
    [Arguments]  ${current page}=${EMPTY}
    Set test variable  ${CURRENT PAGE}
    SeleniumLibrary.Select frame  ${CONTAINER FRAME}

Get table title
    ${title}=  //table/th/td[1]  # No need to select the parent frame, it's done on initialization.

    [Return]  ${title}
```

I may not have thought everything through very well, but I just wanted to start a discussion if maybe I'm onto something useful.

Thanks,
Bart

**Comment by bartkl** [comment]
Hi Pekka,

I might have bothered too much with trying to suggest a solution. Especially with regards to (3) I completely agree using `Set test variable` is a bad idea.

To be more to the point regarding my problem: at import time I sometimes want a resource file to set some variables, the values of which can be different depending on the state of the application. For example the locators of the recurring table and its controls, based on which page it's currently being displayed on. If you still think solving this with passing parameters when importing which are handled by some `Init` keyword is a bad idea, do you (or someone else) perhaps have a good idea to combat this problem?

**Comment by pekkaklarck** [comment]
How would doing something at the import time be different to doing something in suite setup?

**Comment by bartkl** [comment]
Two issues with Suite setup:

1. It is not always an option. I might want to import some resource file in several resource files which all will get imported/used at some point during the same run, but every time I import it I want it to re-create several of the variables it used.
I think my table import example above is fairly demonstrative of what I mean: `${CURRENT PAGE}` will change throughout the run, so variables depending on it such as `${CONTAINER FRAME}` have to be re-evaluated.
2. The logic for setting variables described in (1) would potentially have to be copied to all places where the resource file is imported, instead of being centralized in some sort of 'on import initialization'.

Hope that clarifies what problem I'm bumping into.

**Comment by pekkaklarck** [comment]
If your needs are only related to variables, have you considered using variable files instead of resource files? They make creating variables much more flexible than resource files, and dynamic argument files allow passing arguments already now.

**Comment by bartkl** [comment]
That's a good suggestion. I have used variable files before, but not in the dynamical sense yet. To be honest I'm somewhat pessimistic this will solve my problem, but I'm certainly going to give it a try.
Thanks.

**Comment by pekkaklarck** [comment]
I hope variable files work for you. If not, I'm still not convinced that the proposed functionality would be that useful. Another big problem is that implementing this functionality would be pretty big task and at least I don't that much interest and even less time for that. Are you interested to implement this feature yourself? If yes, then we can continue discussing is it really needed (I still don't understand why suite setups won't work for you) and how it should actually work. Otherwise it's better to close this issue and possibly reopen it if someone is actually interested to implement it.

**Comment by bartkl** [comment]
There's a reasonable chance the proposed variable files solution will work, and I understand your hesitation and problems with my proposal too. It indeed is pretty fundamental and time consuming.

I'll close the issue and hope for the best.
Thanks again.

**Comment by pekkaklarck** [comment]
Dynamic variable files should work fine in this case. A possible problem with them is that are cached i.e. non imported again if you take them into use with same arguments. That's something we've been planning to change (see #2101), and if that causes problem in your use case it makes changing the logic higher priority. Could be something to consider in RF 3.2.

**Comment by bartkl** [comment]
Yes, I am aware of that caveat. Luckily the whole point of my problem was to have differing parameters ;).
