### ISSUE TITLE
Not able to rerun failed TestSuites/Testcases created dynamically

### ISSUE THREAD

**Issue by rs03** [robotframework/robotframework#2918]
I have created suite and testcases in suite dynamically . I want to rerun failed test cases using
pybot --rerunfailed C:\Users\GS-0815\PycharmProjects\Apex\out1.xml --output C:\Users\GS-0815\PycharmProjects\Apex\Failed\out1.xml "+suite.name
Result:

but it says sanity suite not found

PFA for test script (not able to attach rtf/txt file),How I can I provide suitepath which is created dynamically or else any other way

------------------------------------------------------
pasting code here.........
--------------------

```python
import os
from robot.libraries.BuiltIn import BuiltIn
from robot.libraries.BuiltIn import *
from robot.api import TestSuite
from robot.api import ResultWriter
from robot.parsing.model import TestData
#from robot.output import TestSuite
from robot.running.context import EXECUTION_CONTEXTS



class TestRunner():
    ROBOT_LISTENER_API_VERSION = 2
    ROBOT_LIBRARY_SCOPE = 'TEST SUITE'
    def __init__(self):
        print "in init"

    def func(self,a):
        BuiltIn().log_to_console("in testrunner.py")
        self.ROBOT_LIBRARY_LISTENER = self

        #suite=EXECUTION_CONTEXTS.current.suite
        suite = TestSuite(name='Sanity',source=a)
        suite.configure()
        BuiltIn().log_to_console(suite)
        #BuiltIn().import_resource("C:/Users/GS-0815/PycharmProjects/Apex/demo.robot")
        print a

        suite.resource.imports.library('OperatingSystem')
        suite.resource.imports.library('C:/Users/GS-0815/PycharmProjects/Apex/keyw.py')
        #BuiltIn().import_resource('C:/Users/GS-0815/PycharmProjects/Apex/TestSuites/test.robot')
        suite.resource.imports.resource("C:/Users/GS-0815/PycharmProjects/Apex/TestSuites/test.robot")
        suite.keywords.create("t1",args=['in suite setup'],type="setup")
        
        
        test = suite.tests.create('WirelesswithSegmentation', tags=['smoke','abc'])
        test.keywords.create("abc", args=["hi","there","ddgdgd"])
        #test.keywords.create('Environment Variable Should Be Set', args=['SKYNET'])

        test = suite.tests.create('Test2', tags=['smoke'])
        #test.keywords.create('abc', args=['test2'],type='setup')
        test.keywords.create('Log to Console', args=['EXECUTION_CONTEXTS.current.suite'], type='setup')
        test.keywords.create('Log to Console', args=['&&&&&&&&&&&&&&&'])
        test.keywords.create('Log to Console', args=['test21'])


        test = suite.tests.create('Test3', tags=['xyz'])
        test.keywords.create('Log to Console', args=['hi there3'])






        suite2 = TestSuite('regression')
        suite2.resource.imports.library('OperatingSystem')
        #suite2.resource.imports.library('demo.robot')
        #suite.resource.imports.library('C:/Users/GS-0815/PycharmProjects/Apex/keyw.py')
        test = suite2.tests.create('WirelesswithSegmentation2', tags=['he','abc'])
        test.keywords.create('Log to Console', args=['hi there'])
      
    
    
    

        #suite.filter(included_tags=['xyz'])
        result =suite.run(output='out1.xml')
        result2=suite2.run(output='out2.xml')
        **os.system("pybot --rerunfailed C:\Users\GS-0815\PycharmProjects\Apex\out1.xml --output C:\Users\GS-0815\PycharmProjects\Apex\Failed\out1.xml "+suite.name**

         os.system('rebot -d C:\Users\GS-0815\PycharmProjects\Apex\TestSuites out1.xml out2.xml')


ob = TestRunner()
ob.func('C:\Users\GS-0815\PycharmProjects\Apex\TestSuites\suite1.robot')
```

**Comment by pekkaklarck** [comment]
You create the suite dynamically during test execution, right? Unfortunately `--rerunfailed` is processed already when test execution starts, so suites/tests you create later naturally aren't available. It's not possible to resolve this problem without fully rewriting the rerun functionality so that the evaluation is the test run is done at runtime. I don't think that's worth the effort because it would be a really big task and would also make the execution logic more complicated.

Possible solutions for your problem:

- Implement rerun functionality for your test generator directly. You can probably utilize the existing `robot.conf.gatherfailed.GatherFailedTests` class for that, but remember that it's not part of the public API and may be changed or removed in future versions.

- Unless you have really good reasons to generate tests dynamically, you could consider generating tests before execution. If you'd generate tests in normal Robot format in `*.robot` files, then you could use the existing rerun functionality as-is.

**Comment by pekkaklarck** [comment]
If you have CSV file with content like

```
Number 1    Operator    Number 2    Expected
1           +           2           3
2           -           1           1
```

you can easily create a script that reads it and then produces Robot test case in `*.robot` file with content like

```robotframework
*** Settings ***
Library            CalculatorLibrary

*** Test Cases ***
Test 1
    Calculate    1 + 2    3
Test 2
    Calculate    2 - 1    1
```

How exactly you'd generate the file obviously depends on your context. Further discussion about this belongs to robotframework-users, Slack, or other such forums.
