### ISSUE TITLE
Problems with Python 3.7 and/or Eclipse Photon with RED plugin

### ISSUE THREAD

**Issue by idomoni** [robotframework/robotframework#2920]
Hi I have installed Eclipse Photon with RED plugin and also installed new Python 3.7 and it did not worked.
I couldn't run test cases.
Then I installed Python 3.6 and Eclipse Oxygen (also with red plugin) and everything worked as before.
My question is is this known issue? Is the problem in new Python 3.7 not supporting robotframework (from my side more likely version) or it is that new Eclipse Photon doesn't fully support RED plugin (less likely).

![image](https://user-images.githubusercontent.com/42203202/43827482-3613cbde-9afa-11e8-9b4c-2fa9f4fd974e.png)

**Comment by pekkaklarck** [comment]
Seems to be an environment related problem:
https://stackoverflow.com/questions/43124775/why-python-3-6-1-throws-attributeerror-module-enum-has-no-attribute-intflag

**Comment by idomoni** [comment]
You shouldn't close this issue. You should assign to me for verification of your answer.

**Comment by HelioGuilherme66** [comment]
@idomoni Did you tested robotframework from command line outside of any IDE?
This is an issue tracker only for robotframework.
I also recommend reading the [CONTRIBUTING.rst](https://github.com/robotframework/robotframework/blob/master/CONTRIBUTING.rst) document.

**Comment by idomoni** [comment]
:)

**Comment by pekkaklarck** [comment]
Could you @idomoni explain why this issue should not be closed? The problem clearly isn't in Robot Framework but in the environment, either in your Python installation or in the IDE.

**Comment by idomoni** [comment]
I'm old school tester and I would like to close it after your answer :) . 
You can leave this as closed because it is not issue regarding to RF it self.
My main question was do you know if there is issue that RF is not working properly under new Python 3.7 and that is all.

@HelioGuilherme66 thank you mate, I will do that.

Cheers,
