### ISSUE TITLE
Importing by path interferes with sys.argv changes caused by library imports

### ISSUE THREAD

**Issue by DanielPBak** [robotframework/robotframework#2923]
I have made the following PR to fix this issue: https://github.com/robotframework/robotframework/pull/2922

On robot 3.2 (I have tried other versions too), importing a module by path that prepends to sys.path causes the extra path added by the importer to not be deleted, and instead deletes the externally prepended path.

I have fixed this by using remove() instead of pop()

**Comment by pekkaklarck** [comment]
Sounds good to me. I would say imported modules shouldn't mess up with `sys.path` or at least clean it up afterwords like Robot does, though.

**Comment by DanielPBak** [comment]
Thank you!
