### ISSUE TITLE
"ValueError: No JSON object could be decoded" when I use the latest(3.14.0) selenium docker as remote url

### ISSUE THREAD

**Issue by wck821829906** [robotframework/robotframework#2926]
@LSumbler 

- RobotFramework:
    robotframework==3.0.4
    robotframework-seleniumlibrary==3.1.1
    selenium==3.13.0

- Docker-Selenium
  Image Version:
   1. Image: selenium/hub & selenium/node-chrome-debug
   2. Version: 3.14.0

- Docker Version:
   docker version: 1.13.1

- OS version:
   Centons 7

- Steps：
  1. deploy selenium hub & selenium/node-chrome-debug docker container according to the methods as Readme
  2. use robotframework Open Browser keyword to connect selenium hub
  3. execute pybot command

- Expected Behavior
  chrome debug node can open chrome browser to exec UI web automation test

- Actual Behavior
  chrome debug node can not open chrome browser and "ValueError: No JSON object could be decoded" error occurs on command line

**Comment by pekkaklarck** [comment]
This issue tracker if for enhancement requests and bug reports related to Robt Framework core. This issues looks more like a question belonging to some actual support group and, more importantly, is related to external tools.

**Comment by wck821829906** [comment]
@pekkaklarck Could you make sure this issue is related to external tool problem ?
