### ISSUE TITLE
Support reloading library

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#293]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=293) by @jrantanen on 19 Apr 2009*

Currently it is not possible to import library multiple times with
different arguments using WITH NAME. Current implementation needs
refactoring to support reimports.

**Comment by jussimalinen** [comment]
There at least two different levels of reloading/reimporting.

One way of doing this is that the robot requests the implemented keywords again from the library, and updates the namespace. This would still keep the very same library instance in use. We can call this reloading.

Another one would be to do a full reimport, where the robot will create a new object instance from the library. I dont know if robot should then even recheck the library scope. This could then be called reimporting.

RemoteSwingLibrary would require the first kind of reloading and I think it should be enough for most cases. Therefore for now this issue will be about reloading a library and if necessary we can later create a separate issue about reimporting.
