### ISSUE TITLE
Reading XML source '/app/output.xml' failed: ParseError: not well-formed (invalid token)

### ISSUE THREAD

**Issue by tigranav** [robotframework/robotframework#2934]
Hi. i have error 
`Reading XML source '/app/output.xml' failed: ParseError: not well-formed (invalid token): line 136, column 0\n\nTry --help for usage information.`
online xml validator also shows error in this position. It is tagets to </pre> tag. seems there is has no open tag for him.

**Comment by pekkaklarck** [comment]
`output.xml` file is corrupted for some reason. We cannot do anything for it unless you can provide a simple example that demonstrates the problem. For more information why this kind problems can occur, search this issue tracker for `ParseError` to find similar issues.

**Comment by tigranav** [comment]
i seached simmilar issues but dont find them.
peace of invalif xml there 
`<var>${MASTER}</var>
</assign>
<msg level="INFO" timestamp="20180816 07:02:19.637">${MASTER} = {'api_version': None,
 'kind': None,
 'metadata': {'annotations': {'openshift.io/deployment-config.latest-version': '1',
                              'openshift.io/deployment-config.name': 'pg-common...</msg>
<status status="PASS" starttime="20180816 07:02:19.010" endtime="20180816 07:02:19.637"></status>
</kw>
<kw name="Log To Console" library="BuiltIn">
<doc>Logs the given message to the console.</doc>
<arguments>
<arg>Master pod: "${MASTER.metadata.name}"</arg>
</arguments>
<status status="PASS" starttime="20180816 07:02:19.637" endtime="20180816 07:02:19.639"></status>
</kw>
<status status="PASS" starttime="20180816 07:02:18.942" endtime="20180816 07:02:19.659"></status>
</kw>
<kw name="Check replica count" library="openshift.common">
<tags>
<tag>check-installation</tag>
</tags>
<arguments>
<arg>pg-common-node</arg>
<arg>Running</arg>
</arguments>
<kw name="Get Environment Variable" library="OperatingSystem">
<doc>Returns the value of an environment variable with the given name.</doc>
<arguments>
<arg>PG_NODE_QTY</arg>
<arg>default=2</arg>
</arguments>
<assign>
<var>${pg_node_qty}</var>
</assign>
<msg level="INFO" timestamp="20180816 07:02:19.707">${pg_node_qty} = 2</msg>
<status status="PASS" starttime="20180816 07:02:19.660" endtime="20180816 07:02:19.707"></status>
</kw>
<kw name="Convert To Integer" library="BuiltIn">
<doc>Converts the given item to an integer number.</doc>
<arguments>
<arg>${pg_node_qty}</arg>
</arguments>
<assign>
<var>${pg_node_qty}</var>
</assign>
<msg level="INFO" timestamp="20180816 07:02:19.763">${pg_node_qty} = 2</msg>
<status status="PASS" starttime="20180816 07:02:19.710" endtime="20180816 07:02:19.763"></status>
</kw>
<kw name="Get Pods" library="pgsLibrary">
<arguments>
<arg>status=Running</arg>
<arg>repl_name=pg-common</arg>
</arguments>
<assign>
<var>@{pods}</var>
</assign>
<msg level="INFO" timestamp="20180816 07:02:20.130">@{pods} = [ {'api_version': None,
 'kind': None,
 'metadata': {'annotations': {'openshift.io/deployment-config.latest-version': '1',
                              'openshift.io/deployment-config.name': 'pg-comm...</msg>
<status status="PASS" starttime="20180816 07:02:19.764" endtime="20180816 07:02:20.130"></status>
</kw>
<kw name="Get Length" library="BuiltIn">
<doc>Returns and logs the length of the given item as an integer.</doc>
<arguments>
<arg>${pods}</arg>
</arguments>
<assign>
<var>${count}</var>
</assign>
<msg level="INFO" timestamp="20180816 07:02:20.132">Length is 1</msg>
<msg level="INFO" timestamp="20180816 07:02:20.209">${count} = 1</msg>
<status status="PASS" starttime="20180816 07:02:20.131" endtime="20180816 07:02:20.210"></status>
</kw>
<kw name="Should Be Equal" library="BuiltIn">
<doc>Fails if the given objects are unequal.</doc>
<arguments>
<arg>${count}</arg>
<arg>${pg_node_qty}</arg>
</arguments>
<msg level="FAIL" timestamp="20180816 07:02:20.213">1 != 2</msg>
<status status="FAIL" starttime="20180816 07:02:20.211" endtime="20180816 07:02:20.213"></status>
</kw>
<status status="FAIL" starttime="20180816 07:02:19.659" endtime="20180816 07:02:20.214"></status>
</kw>
<status status="FAIL" starttime="20180816 07:02:18.939" endtime="20180816 07:02:20.214"></status>
</kw>
<status status="FAIL" starttime="20180816 07:02:18.938" endtime="20180816 07:02:20.214"></status>
</kw>
<status critical="yes" status="FAIL" starttime="20180816 07:02:18.928" endtime="20180816 07:02:20.221">1 != 2</status>
</test>
<doc>Check scaledown slave</doc>
<status status="FAIL" starttime="20180816 07:02:14.022" endtime="20180816 07:02:20.223"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat name="Delete master robot-test" pass="0" fail="1" id="s1">Delete master robot-test</stat>
</suite>
</statistics>
<errors>
</errors>
</robot>
</arg>
<arg>select * from test_insert_robot where id=${RID}</arg>`

136 th line is  penultimate line

**Comment by pekkaklarck** [comment]
Seeing the broken XML won't really help. What we'd need is an example that we could run to replicate the problem.

**Comment by pekkaklarck** [comment]
Notice also that there's Fixml tool that can be used to fix broken output.xml files: https://bitbucket.org/robotframework/fixml

**Comment by pekkaklarck** [comment]
Cannot do anything for this issue based on the provided information. Notice that we have #2839 about broken output.xml that also has a example reproducing the problem. If also this issue is caused by timeouts, fixing that issue will fix this one as well.

**Comment by jeffwright13** [comment]
FWIW I ran into this error when I ran two tests simultaneously, and by accident I used the "-d <dir_name>" command line option to point both runs to the same directory with the results.
