### ISSUE TITLE
Run Keyword And Continue On Failure should return status and message

### ISSUE THREAD

**Issue by tomas-mhsl** [robotframework/robotframework#2942]
In the same way as "Run keyword and Ignore Error", "Run Keyword and Continue on Failure" should be able to return the keyword status (PASS or FAIL) and the keyword result or the error message if the keyword fails.
In this case, you can use the result of the keyword for some other checkings, instead of using:
`${check_result}    ${check_message}=    Run Keyword And Ignore Error ...`
`Run Keyword And Continue On Failure    Should Be True    '${check_result}'=='PASS'    ${check_message}`
`...`
`Run Keyword If    '${check_result}'=='FAIL'    ...`
you will be able to use:
`${check_result}    ${check_message}=    Run Keyword And Continue on Failure ...`
`...`
`Run Keyword If    '${check_result}'=='FAIL'    ...`

**Comment by pekkaklarck** [comment]
Do I get it right that you'd like to know has some continuable failure occurred? I agree that would be sometimes useful. Changing the return value of `Run Keyword And Continue On Failure` is not possible, though, because it would break all usages of that keyword that currently use the return value for something.

**Comment by tomas-mhsl** [comment]
Maybe a new keyword something like `Run Keyword And Continue On Failure Returning Status` could be implemented

**Comment by pekkaklarck** [comment]
I don't want to add yet another keyword to handle this situation. Instead it would be better to update existing `${TEST STATUS}` and `${TEST MESSAGE}` variables when there are continuable failures. We already have #2078 about that.
