### ISSUE TITLE
`--timestampoutputs` generates files with different timestamps

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#2945]
Executed tests with `--timestampoutputs` and got these output files:

```
Output:  /tmp/output-20180828-101726.xml
Log:     /tmp/log-20180828-101727.html
Report:  /tmp/report-20180828-101727.html
```

Should definitely use the same timestamp with all output files.

**Comment by akshbn** [comment]
I will take this up.

**Comment by pekkaklarck** [comment]
Have you made any progress @akshbn?

**Comment by pekkaklarck** [comment]
Want to get this into RF 3.1 so decided to look at the problem myself. It seems that the timestamp for the output file is got when execution starts, but the log/report timestamps only when log/report are generated. Timestamps can thus differ quite a bit. Luckily pretty easy to fix but also want to create a test for the problem.
