### ISSUE TITLE
Unable to POST multiple files with different content type and names

### ISSUE THREAD

**Issue by salungh** [robotframework/robotframework#2948]
I'm trying to post two files that corresponds to a part of one message with content-type application/xml and bodytext/plain. In postman I go to form data POST and give the key=metadata and value=file1 path (xml) and Key=0 and value=file2 path(txt) and it works fine and I'm able to insert. I'm supposed to use the same name for the files while inserting i.e. metadata and 0 respectively. This is what I have done through robot to imitate this behavior and it always returns a 500 Internal server error.
Insert Data
${auth}= Create List ${ID} ${SECRET}
${params}= Create Dictionary Key=${value} app=${apps}
${headers}= Create Dictionary Content-Type=multipart/form-data
Create Session mysession ${URL} auth=${auth} max_retries=10 backoff_factor=0.2
${metadata}= get binary file ${CURDIR}${/}insert.xml
${0}= get binary file ${CURDIR}${/}messageInsertion1.txt
${fileParts} create dictionary file1=${metadata} file2=${0}
${resp}= Post Request retain /messages params=${params} headers=${headers} files=${fileParts}
Response Code Should Be Success ${resp}

**Comment by pekkaklarck** [comment]
This tracker is for bug reports and enhancement requests. Please send questions to mailing lists or other support forums listed at robotframework.org. Notice also that you should explain background in somewhat more detail. Should at least mention the libraries you use.
