### ISSUE TITLE
Windows path separator at the end of string variable seems to not be comparable

### ISSUE THREAD

**Issue by juhoarvid** [robotframework/robotframework#2949]
Path value read from registry, but simplified example for easier understand
CODE:
***Test Case***
Test1
    ${myprogdata}=        Set Variable  C:\\ProgramData\\MyProgram\\
    Run Keyword If  "${myprogdata}" == "${EMPTY}"  Fail  Path should not be empty

OUTPUT:
Test1                                                                     | FAIL |
Evaluating expression '"C:\ProgramData\MyProgram\" == ""' failed: SyntaxError: EOL while scanning string literal (<string>, line 1)

Is last "\" handled as escape char?

**Comment by pekkaklarck** [comment]
Have your read the section about evaluating expressions in the BuiltIn library documentation?

**Comment by pekkaklarck** [comment]
This ought to be explained in the aforementioned documentation. Closing.
