### ISSUE TITLE
Official linter ? 

### ISSUE THREAD

**Issue by rgarrigue** [robotframework/robotframework#2950]
Hi

What's the official way to lint *.robot ? I found https://github.com/boakley/robotframework-lint/ but is that it ? 

Best regards,

**Comment by bkhouri** [comment]
I don't think there is an official linter, but the link you pointed too was
the best one I found as it's already has predefined rules, and allows you
to create your own rules too.

---
"What we can or cannot do, what we consider possible or impossible, is
rarely a function of our true capability. It is more likely a function of
our beliefs about who we are." - Tony Robbins

**Comment by rgarrigue** [comment]
OK thanks bkhouri, I'll go with that
