### ISSUE TITLE
--rerunfailed only includes suites with failed tests in rerun.xml, which makes it impossible to merge with original.xml

### ISSUE THREAD

**Issue by MichaelFriis-Github** [robotframework/robotframework#2953]
If running a test with 3 suites pybot suite1 suite2 suite3 and a testcase fails in suite 2
pybot --rerunfailed original.xml only includes suite 2 in rerun.xml
Merging original.xml and rerun.xml is no longer possible
rebot --merge original.xml rerun.xml
[ ERROR ] Cannot merge outputs containing different root suites.

Is it possible to make --rerunfailed include the passed suites, without running them in the rerun.xml, so they can be merged to one report?

**Comment by pekkaklarck** [comment]
The problem is that the automatically created name of the top-level test suite changes depending on which suites are run. A simple solution is providing a custom name like `--name Example` in both runs.
