### ISSUE TITLE
Issue with Mainframe Testing using Robot Framework

### ISSUE THREAD

**Issue by deepa2603** [robotframework/robotframework#2956]
When i try to run mainframe testing from robot framework, its opening terminal correctly..but when any input being passed or try to get string, it throws below error. But, able to run and connect to mainframe server from python script. Only from robot framework script, facing this issue.

A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied

Using lib for mainframe: https://github.com/pedrommvv/x3270-robot

Using RIDE and Pycharm-Intellibot for connecting to mainframe. 

Please share idea/solution if any.

**Comment by pekkaklarck** [comment]
This tracker is for bug reports and enhancement requests related to Robot Framework core. Generic questions should be submitted to mailing lists, Slack, or other such support forums listed at http://robotframework.org. If you have an issue with the library you use, submit a bug report to its tracker.

Notice also your description is so vague that at least I couldn't possibly help you. You mention "below eror" but I see no such error. Also, there probably aren't that many who do mainframe testing. At least I know next to nothing about that.
