### ISSUE TITLE
avoid setting new StringIO to sys.stdout at every testcase

### ISSUE THREAD

**Issue by siming85** [robotframework/robotframework#2959]
`sys.stdout` is being changed to a new `StringIO` object for every testcase.

while that might work for... many, it doesn't work where `sys.stdout` is explicitly stored as a reference.

eg:

```python
logger = logging.getLogger(__name__)
logger.addHandler(logging.StreamHandler(sys.stdout))
```

this logger's prints will go into the void because after 1 testcase, `sys.stdout` is swapped out by robot framework.

there is a root logger to capture propagated logs, but sometimes there is a distinct need to write directly to the screen on a non-propagating logger

**Comment by pekkaklarck** [comment]
Do you have ideas how to avoid this? Only thing I can think of is changing the referred logging code to use `sys.__stdout__` instead.

**Comment by siming85** [comment]
changing the logging code to `sys.__stdout__` would simply write to the actual screen, and make the pretty PASS/FAIL table look like garbage.

`sys.stdout` was changed to `StringIO` so that the messages to "screen" is logged in `output.html`. bypassing that would mean any output to screen is not logged in log file

**Comment by pekkaklarck** [comment]
I don't understand what you wan try to do. If your code tries to write to console, using `sys.__stdout__` is what you should use. If you try to write to Robot's log file, then you should use `print`, `robot.api.logger` or `logging`.

**Comment by siming85** [comment]
i am using logging :)

```python
logger.addHandler(logging.StreamHandler(sys.stdout))
logger.propagate = False

logger.info('this is a log message')
```
if this logger is created at init, and logger.info is called within testcase's keywords, it will not show up in robot log

i want robot log to include log message that are handled by ``logging.StreamHandler``. But as it stands, this won't work because ``sys.stdout`` is replaced per testcase, and in a ``StreamHandler``, ``self.stream`` stores ``sys.stdout``.

**Comment by pekkaklarck** [comment]
Why don't you just use `logging.info('this is a log message')`?

**Comment by siming85** [comment]
we are, but the logging is to screen.

the root logger you install in robot framework covers most situations but not all.

consider this - logging handler inserts termination `\n` automatically after handling each log record.
you can disable this (set it to ''), but this also means each log message needs to contain its own `\n`.

but - sometimes some applications (especially say, interactive ones) don't always print out one line at a time. in those cases we need to inject the log output directly into the stream.

such cases we need certain amount of customization at the handler level (to insert `\n` conditionally).
this means a non-propagating logger. there's no other way around it.

hence the above issues - we use logging, but we log to stdout and file using our own handlers. 
if robot framework is to intercept sys.stdout, it should do so once, and not replace it every testcase. that's highly non standard

**Comment by siming85** [comment]
the fix is simply to replace sys.stdout with say..

```python
class RobotStdout:
    def __init__(self):
        self._stream = io.StringIO()

    def __getattr__(self, attr):
        return getattr(self._stream, attr)

    def reset(self):
        self._stream =io.StringIO()

# and do this only once
sys.stdout = RobotStdout()

# where you want to reset, do:
sys.stdout.reset()
```

**Comment by pekkaklarck** [comment]
I still don't understand what you try to accomplish. Do you want to log to the stdout or to Robot's log?

Anyway, if you want this ti be changed, please provide a pull request so that we can see how big changes there would be for real. If I don't understand your use case, the changes need need to be really simple for me to merge the pr, though.

**Comment by siming85** [comment]
most applications instantiates by storing the stream, eg `sys.stdout` as a reference in their object.
for example, `logging.StreamHandler` does that - https://github.com/python/cpython/blob/3.7/Lib/logging/__init__.py#L957

Robot tries to capture stdout by replacing with StringIO - so that stdout shown in the final output log file. But the implementation is wrong - `sys.stdout` is replaced per testcase, and breaks most code, including pythons own.

**Comment by pekkaklarck** [comment]
In my opinion code that stores a reference to `sys.std*`, including `logging.StramHandler`, is wrong. Only exception I can think is storing a reference to the original values to be able to restore them. If you want to use the real standard streams, you should always use `sys.__std*__`. If you want to use the current streams, you should use the current `sys.std*`, not values you've stored earlier.

If you disagree with me and feel it's important to handle this situation differently, please provide a pull request changing the functionality. If it's not overly complicated, I'm fine incorporating the changes. Personally I don't consider this important enough, in fact I don't consider there is an issue at all, so I'm not going to spent time changing the code.

Finally, it's still unclear to me whether you want to log to stdout or to Robot's log file.

**Comment by pekkaklarck** [comment]
Are you @siming85 looking can this be fixed in Robot side or should we just close this issue? Remember that changes on Robot side should be pretty simple, and there should be tests, for the PR to be acceptable.

Notice that if you want to create a stream that always uses the current `sys.stdout` so that you can pass it to `logging.StreamHandler` or use otherwise, you shouldn't need more than this:

```python
class StdoutWrapper(object):

    def __getattr__(self, name):
        return getattr(sys.stdout, name)
```

**Comment by siming85** [comment]
i'm not looking to work a PR right now.

it's a definitely a bug in Robot, whether you want to admit to it or not is a different issue. If you think python logging does it wrong, then you should at least have a reference bug# in python side before closing this one.

which begs the question, it would be easier for you to fix that in robot with your snippet... than to write elaborate discussions here.
