### ISSUE TITLE
Support other than glob patterns with `Run Keyword And Expect Error`

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#2967]
Currently `Run Keyword And Expect Error` considers the given expected message to be a [glob pattern](https://en.wikipedia.org/wiki/Glob_(programming)). This is typically very handy allowing usages like

    Run Keyword And Expect Error    ValuError: *    My keyword    args    here

but causes problems if the expected error contains characters that are considered to be wildcards in glob patterns. Earlier this meant only `*` and `?`, but #2471 added support for `[...]` making also `[` and `]` special characters and causing problems with usages like this:

    Run Keyword And Expect Error    No match for '//input[@type="text"]'    Keyword    args

A simple workaround for the above problem is replacing problematic characters with `?` that matches any single character:

    Run Keyword And Expect Error    No match for '//input?@type="text"?'    Keyword    args

The main problem with this solution is that the specified message looks strange, but the wildcard could also match some wrong character making the test false positive.

A better solution would be making it possible to configure how `Run Keyword And Expect Error` should interpreter the provided message. We cannot add any new arguments to this keyword, but we can prefix the provided message with the message type. For example, something like this could be used to specify that the message should be interpreted as a literal value that must match the actual error as-is:

    Run Keyword And Expect Error    EQUALS:No match for '//input[@type="text"]'    Keyword    args

Implementation of this functionality shouldn't be too complicated (thus the `good first issue` label), but we need to do some design decisions first:

- What matching styles should we support? Robot's own acceptance tests have similar functionality, and there we support exact match, glob patterns, regexp patterns, and validating that the actual message starts with the given message. I think these would all be useful also with `Run Keyword And Expect Error`.

- How to specify the matching style? The aforementioned system in Robot's acceptance tests uses style like `REGEXP: <msg>` and `STARTS: <msg>` which is pretty good. Then we have `Catenate` that supports `SEPARATOR=<sep>` and SeleniumLibrary uses `locator:value` nowadays but still supports legacy `locator=value`. The equal sign has also other usages in Robot's data, so probably the colon works better. That leaves us to decided should we use `REGEXP:` or `regexp:` and how to spell each of the options.

**Comment by aaltat** [comment]
I prefer the style used in [status checker](https://github.com/robotframework/statuschecker), which mean uppercase and colon. Example `REGEXP:` is fine by me.

**Comment by pekkaklarck** [comment]
After thinking this a bit more, decided to go with `EQUALS`, not `EQUAL`. It's consistent with `STARTS` and just feels better in general. Also decided not to spend time enhancing error reporting at least now.
