### ISSUE TITLE
Telnet: `Write Control Character` does not work with numeric values on Python 3

### ISSUE THREAD

**Issue by gazsiazasz** [robotframework/robotframework#2968]
In telnetlib, control characters are no more 'char' type, but 'bytes' type.

So if you try to issue command:
Write Control Character   26 # CTRL-Z
then it gives the error: TypeError: can't concat str to bytes

**Comment by tapioreijonen** [comment]
Find out this same problem in telnet library while change from Python 2.7 -> 3.x

**Comment by tapioreijonen** [comment]
Currently, yes. But, this also was our first try to move Python 2.7 -> 3.x.

**Comment by pekkaklarck** [comment]
Found the problem. The code is converting an integer to a byte using `chr`, but in Python 3 that yields a Unicode strings. Luckily this is easy to fix.
