### ISSUE TITLE
Python->Robot passed list gets unicode characters transformed

### ISSUE THREAD

**Issue by tueksta** [robotframework/robotframework#2975]
Robot Framework 3.0.4 (Python 3.7.0 on darwin)

I have a file that has ジ (U+30B7, U+3099) in the name.

I have robot test that calls a python function to list files in a given path recursively including the file above. That function returns a list of all the full pathes like this:

```
    @keyword('List Files Recursively')
    def list_files_rec_filtered(path, regexp_filter="^(?!\.).+$"):
        file_list = []
        filename_filter = re.compile(regexp_filter)
        for root, dirs, files in os.walk(path, topdown=True):
            for file in files:
                if filename_filter.match(file):
                    file_list.append(os.path.abspath(os.path.join(root,file)))
        return file_list
```

When calling this function from a robot keyword like this:

```
    ${files}=    file_utils.List Files Recursively  ${path}  ${FILE_TYPES}
```

I can see that I get a different result than what was in the list in python.

Where the filename has ジ (U+30B7, U+3099) in the name before it's returned, the returned value is instead ジ (U+30B8). I took both characters from the robot test's logfile, first one is a debug message I generated with python's `print()`, the second one is from robots own `TRACE	Return:` value.

I have no encoding marker in the python file or the robot file. 
These env variables are set:

```
LC_ALL=en_US.UTF-8
LANG=en_US.UTF-8
LC_CTYPE=UTF-8
```

I spend a lot of time already trying to pin this down, but no success. Also stackoverflow couldn't help with that. I found this hint in https://stackoverflow.com/questions/25254063/python-os-walk-make-it-support-unicode-utf-8?rq=1 

Any help is appreciated.

**Comment by pekkaklarck** [comment]
When you use Python, do you use Python 2 or Python 3? If the former, do you pass the path like `'my/path/here'` (`str` type i.e. basically bytes) or `u'my/path/here'` (Unicode text)? If the former, then the difference is that you use bytes in Python, but Robot passes argument to your keyword as Unicode. This makes a difference because Python file system APIs return you bytes when you pass them bytes but return you Unicode text when you pass them Unicode.

**Comment by pekkaklarck** [comment]
Oh, you are using Python 3 but are on OSX. Then the problem is most likely due to different Unicode normalization OSX file system has compared to other OSes. Robot normalizes Unicode strings to NFC.

**Comment by pekkaklarck** [comment]
Here's a demonstration that this is most likely due to OSX file system using NFD normalization but Robot normalizing Unicode strings to NFC that's used by pretty much everywhere else:

```python
Python 3.6.6 (default, Jun 28 2018, 00:00:00) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> e = '\u30b7\u3099'
>>> f = '\u30b8'
>>> print(e, f)
ジ ジ
>>> e == f
False
>>> import unicodedata
>>> unicodedata.normalize('NFC', e) == f
True
>>> unicodedata.normalize('NFD', f) == e
True
```

For more information about Unicode equivalence and normalization see https://en.wikipedia.org/wiki/Unicode_equivalence.

I don't think anything can really done to this issue.

**Comment by tueksta** [comment]
Thanks for the very informative feedback.

I'm on Python 3 with Mojave. If I run the same test on El Capitan or Sierra they run fine, weirdly enough. Did OS X change normalization in High Sierra/Mojave? All other interactions with robot and this file work fine.

Is it possible to enforce NFC by encoding inside the robot test? Or do I have to ditch this character from all my tests?

**Comment by tueksta** [comment]
Ah, it's an APFS bug, I get it :-( 

https://eclecticlight.co/2017/04/06/apfs-is-currently-unusable-with-most-non-english-languages/

**Comment by pekkaklarck** [comment]
I agree APFS behavior is more like a bug than a feature, but OSX in general using NFD is a strange decision as well, and I'm not sure is NFD that good an idea in the Unicode spec in the first place. As if Unicode (and bytes) wasn't hard enough. Anyway, once you are aware of this stuff, it ought to be pretty easy to workaround it in your library code.

**Comment by tueksta** [comment]
Yes, thanks, I worked around it by not specifying the copy-target by name (which would include the combined unicode character) but by directory path only. But your feedback about Robot only using NFC was the key to unlocking this mystery, this should be documented somewhere. I couldn't find anything about this topic in the Robot documentation.

**Comment by pekkaklarck** [comment]
I would say NFC can be considered the default/expected normalization, but explicitly mentioning it would be a good idea nevertheless. I think there's something related to the data being Unicode in the Test data syntax section in the User Guide, and I'm sure the Creating test libraries section explains that arguments are passed as Unicode to keywords. Do you have interest to look could NFC be mentioned there somewhere? If you find a good place, please submit an issue and/or PR about it.

**Comment by tueksta** [comment]
Yeah, I've been looking around during investigating it, and there's a lot of mentioning of unicode vs bytecode, but nowhere does it say which kind of unicode normalization form is used.

I think it would be worth mentioning in:
* UserGuide: The note in "Forming escape sequences"
* UserGuide: The note in "Scalar variables"
* UserGuide: The note in "Returning values" (most important, as this is where the implicit conversion happens)
* BuiltIn Lib: Description of "Convert To String"
* String Lib: Probably throughout

I can open a PR once we agree where to add this information.
