### ISSUE TITLE
Unload Dynamic/Remote library?

### ISSUE THREAD

**Issue by Aufschlauer** [robotframework/robotframework#2976]
Hi!

Is it possible to unload the Dynamic/Remote library?

Background:
We have several hardware modules that are assembled to one system. Each hardware module has its own ROBOT file using RPC server specific to this hardware module. If a single module test run on its own everything is fine. But if we run all module tests in a single run we get a error message saying "Keyword not found".

The ROBOT file looks basically like this:
```
    Copy Files To Target And Start Rpc    ${IP}    MODULE1    Module1Rpc.py
    Import Library       Remote    http://${IP}:${PORT}    WITH NAME    uut
    uut.Do Something
    uut.Stop Remote Server

    Copy Files To Target And Start Rpc    ${IP}    MODULE7    Module7Rpc.py
    Import Library       Remote    http://${IP}:${PORT}    WITH NAME    uut
    uut.Do Something Completely Different
    uut.Stop Remote Server
````
The call on the second block ```uut.Do Something Completely Different``` causes "Keyword not found" error. Renaming ```uut``` to ```uut1``` and ```uut7``` doesn't solve the problem.
I can see that the keywords of the second block are transferred via network from target to host according to wireshark.

Versions:
Python 3.5.2 (default, Nov 23 2017, 16:37:01)
robot-extensions             0.1                   
robotframework               3.0.4                 
PythonRemoteServer     commit 8047b40

Any ideas?

Thanks.

**Comment by pekkaklarck** [comment]
Could you try using `Reload Library` keyword?

**Comment by Aufschlauer** [comment]
Yes, too easy... I must have overlooked the `Reload Library` keyword.
