### ISSUE TITLE
Fix xUnit compatibility with 3rd party tooling

### ISSUE THREAD

**Issue by rasjani** [robotframework/robotframework#2978]
Jenkins addon https://wiki.jenkins.io/display/JENKINS/xUnit+Plugin has recently changed their xml schema to be more strict about testsuite attributes. 

Previously attribute "skip" was acceptable but in the latest schema verification, support for skip has been dropped and same attribute is now called "skipped". 

This bug/issue report is continuation from #2292

**Comment by pekkaklarck** [comment]
Based on the discussion in #2292 this change definitely makes sense. Compatibility with 3rd party tools that consume xUnit outputs that are more strict nowadays is very important.

Changing `skip` to `skipped` is obviously backwards-incompatible affecting tools that expect exactly that attribute name, but such tools should be anyway changed to support the current industry standard.

**Comment by pekkaklarck** [comment]
Issue #1408 originally introduced the `skip` attribute. #1801 proposed renaming it to `skipped`, but back then all tools supported also `skip` and it was decided not to change it.

**Comment by pekkaklarck** [comment]
Fixed by PR #2977. Thanks @rasjani!
