### ISSUE TITLE
evaluate tags also from results when --rerunfailed

### ISSUE THREAD

**Issue by yahman72** [robotframework/robotframework#2981]
**Enhancement Request/Idea**

It would cool if the `--rerunfailed` would also read/import the tags from the previous results (output XML).
This way it would be possible to use "dynamic" tags (e.g. set by the `Set Tags` KW) to filter the Tests for the re-exection.

My current Use Case:
- there are "front-end" test steps that test the UI
- then there are also back-end test steps that take quite a lot of time (15-30 minutes) e.g.
  + because they wait for an file/DB entry to show up (from async message queue)
  + require a lot of processing power

If things don't work then
- it might be a front-end issue - quite often due to flaky things (e.g. selenium timing issues) --> I want to re-execute these Tests
- it might be a back-end problem - in practise always a persistent back-end problem  --> I do not want to re-execute these tests, because it's just a waste of time

I.e. the tests would look like this:
```
mytest
    # front end verification test steps
    Set Tags      backend_verification
    # backend verifcation test steps
```
and the re-execution would be:
`robot ... -R output.xml -e backend_verification ...`

Somewhat related to #2798

PS.
Would this be possible now with a `--prerunmodifier` i.e. do I have access there to the "-R output.xml" argument so that I could read and parse the output.xml.... or even better, have direct access to the output.xml without first figuring out the filename and parsing it.
(that output XML in my case is not always called "output.xml" = I'd need to find the file name that was given to the "-R" argument)

**Comment by yahman72** [comment]
and now I saw also this #2645 - it documents pretty well the considerations that came to my mind in the evening after submitting this issue...

In Short: this would be nice feature, but handling the (dynamic) tags from the previous execution might get quite complex - and there are easier/simpler ways/workarounds to achieve the same.

Closing also this one.

**Comment by pekkaklarck** [comment]
Yeah, #2645 is pretty similar. In both cases the proposed change would work well in a certain context, but would be problematic in others. Luckily we have `--prerunmodifier` to do more complex, context specific modifications.
