### ISSUE TITLE
Can logging Python keywords to log.html like robot keywords?

### ISSUE THREAD

**Issue by XiaoyaoRay** [robotframework/robotframework#2993]
I would like to ask If there is a possibility to log python keywords to log.html like robot keywords.Like the images:
![image](https://user-images.githubusercontent.com/25135479/47443654-6a8f6600-d7e7-11e8-8ffe-2672ba38f6aa.png)
#### Python Code
```python
  from robot.api.deco import keyword
  from robot.api import logger 

  def decorator():
       ....
       do something
       ....

  class Tester(object):
      @keyword
      def run_hello(self):
          self.hello()

      @decorator
      def hello(self):
          logger.info("hello word")
```

#### Robot Code
```
*** Settings ***
Library    Test.py 

*** Test Cases ***
Run Hello
    Run Hello
```
The python code `decorator()` how to do? Someone can help me?

**Comment by pekkaklarck** [comment]
This is generally not supported, but if Robot knows about the method you'd like to use, you ought to be able to use `BuiltIn.run_keyword` inside the keyword that's executed. If you or someone else would like to see this implemented, please submit a concrete enhancement request explaining the use case in more detail.
