### ISSUE TITLE
`Run Keyword If` and `Run Keywords` do not work correctly in dry-run if used with `Given/When/Then` prefixes

### ISSUE THREAD

**Issue by mjarmstr** [robotframework/robotframework#2994]
Looking to upgrade to from version 2.9 to version 3.0.2 on Ubuntu and when I ran a dryrun on our suite I found that preceding 'Run Keyword If' with an 'ELSE' clause with a Gherkin keyword causes the ELSE clause to be ignored and it to be used as arguments to the keyword.  
This example test runs and dry runs fine on 2.9, and runs fine on 3.0.2, but fails during a dry run on 3.0.2.  
```
*** Test Cases ***

Gherkin
    [Documentation]  This test case fails a dry-run
    Given Run Keyword If  3 == 4  Fatal Error  ELSE  No Operation
    When Run Keyword If  3 == 4  Fatal Error  ELSE  No Operation
    And Run Keyword If  3 == 4  Fatal Error  ELSE  No Operation
    Then Run Keyword If  3 == 4  Fatal Error  ELSE  No Operation

No Gherkin
    [Documentation]  This test case works just fine
    Run Keyword If  3 == 4  Fatal Error  ELSE  No Operation
```

```
# pybot --version
Robot Framework 3.0.2 (Python 2.7.12 on linux2)
# pybot --dryrun ./run_keyword_if.robot 
==============================================================================
Run Keyword If                                                                
==============================================================================
Gherkin :: This test case fails a dry-run                             | FAIL |
Several failures occurred:

1) Keyword 'BuiltIn.Fatal Error' expected 0 to 1 arguments, got 2.

2) Keyword 'BuiltIn.Fatal Error' expected 0 to 1 arguments, got 2.

3) Keyword 'BuiltIn.Fatal Error' expected 0 to 1 arguments, got 2.

4) Keyword 'BuiltIn.Fatal Error' expected 0 to 1 arguments, got 2.
------------------------------------------------------------------------------
No Gherkin :: This test case works just fine                          | PASS |
------------------------------------------------------------------------------
Run Keyword If                                                        | FAIL |
2 critical tests, 1 passed, 1 failed
2 tests total, 1 passed, 1 failed
```

**Comment by mjarmstr** [comment]
To be honest, I didn't write the test so I'd have to talk to the dev who
did to come up with the reasoning as why they did it.  I agree with you
that it is pretty ugly, and it is actually worse because the place it is
used is in a test case using a template.  We do some parsing of our tests
to produce a test document so I'd have to look to see what it ends up
looking like.  Of the approximately 1,700 test cases we have this only
happens in one place so changing the test or marking it to be skipped
during a dry run would be easy, but I figured I should at least report it
since I didn't see it as a known issue and it appears to be a regression
between 2.9 and 3.0.2.

**Comment by pekkaklarck** [comment]
This turned out to be so easy to fix that I can do it even though I'm still not certain about the use case. The fix will be only in RF 3.1 beta 2, so if you are planning to migrate to 3.0.2 or 3.0.x in general you won't get it.

**Comment by mjarmstr** [comment]
Great, thanks.

**Comment by shadowmimosa** [comment]
> I can reproduce this in dry-run mode but it doesn't occur when executing tests normally. Most likely wouldn't be too complicated to fix, but to be honest I don't think that's worth the effort. The reason to use the gherkin style is to create extremely readable test cases, and `Run Keyword If` is extremely unreadable and generally shouldn't even be used in the test case level. Could you clarify the use case for such a strange combination?

I also encountered this problem.I am now migrating the company's test cases from Python2 to Python3.And now,all test cases are reported wrong: Keyword 'BuiltIn.Run Keyword If' expected at least 2 arguments, got 1. 
How should I change now, and all test cases need to be changed " BuiltIn . Run Keyword If"?

**Comment by HelioGuilherme66** [comment]
@shadowmimosa Is it really the exact same problem? Do you have the errors when using dry-run and Gherkin steps? Can you test with latest 3.1beta1?

**Comment by pekkaklarck** [comment]
This problem is not Python version dependent. It's fixed now but the fix is not in beta 1 yet.

**Comment by shadowmimosa** [comment]
@HelioGuilherme66 Sorry, I was a little mistaken. It's not the same problem.
This is not a question of "Run Keyword If", but of the keyword "Get Json Value" in the "HttpLibrary. HTTP" library.
I heard that HttpLibrary.HTTP was abandoned in Python3, so it was not used.
Is there any good way to replace it?
