### ISSUE TITLE
Changes in the in dictionary eveluation. 

### ISSUE THREAD

**Issue by aaltat** [robotframework/robotframework#2996]
This issue is found be running SeleniumLibrary acceptance tests. When I have [this:](https://github.com/robotframework/SeleniumLibrary/blob/master/atest/acceptance/create_webdriver.robot#L35) 
```
*** Keywords ***
Set Driver Variables
    ${drivers}=    Create Dictionary    ff=Firefox    firefox=Firefox    ie=Ie
    ...    internetexplorer=Ie    googlechrome=Chrome    gc=Chrome
    ...    chrome=Chrome    opera=Opera    phantomjs=PhantomJS    safari=Safari
    ...    headlesschrome=Chrome    headlessfirefox=Firefox
    ${name}=    Evaluate    "Remote" if "${REMOTE_URL}"!="None" else ${drivers}["${BROWSER.lower().replace(' ', '')}"]
```
Then in RF 3.1 Beta 1 `Evaluate` fails on error: `Dictionary '${drivers}' has no key '"headlesschrome"'.`,  when `${REMOTE_URL}` contains `None` and `${BROWSER}` is `headlesschrome`. Same test works with earlier RF versions. 

I see that there has been changes in this area, at least by https://github.com/robotframework/robotframework/issues/2601 Was this intentional or is this regression?

**Comment by aaltat** [comment]
Talked with Pekka in slack and this is intentional. Closing due invalid.

**Comment by pekkaklarck** [comment]
Yeah, this was caused by #2601. A fix is escaping the opening square bracket after a variable name like `${drivers}\[...]`.
