### ISSUE TITLE
Generate log.html after each testcase in test suite

### ISSUE THREAD

**Issue by KOLO41a** [robotframework/robotframework#2997]
Hi,
I would like to generate log.html after each test case in test suite but during test execution. Do you know any solution for this?
I tried copy output.xml during test (after testcase finish) but even I fix the xml format and generate log.html using rebot command but I get incomplete log.
Is there any way to do that?

**Comment by pekkaklarck** [comment]
This isn't supported. Please use mailing lists, Slack, or other such forums for further discussion and questions. This issue tracker is for bug reports and concrete enhancement requests.
