### ISSUE TITLE
Robot is not working without any fails log or track list information

### ISSUE THREAD

**Issue by shiminyang** [robotframework/robotframework#2998]
Dear Experts:
I am a normal user. Actually, I find a strange phenomena that when robot framework runs my test case( my test case includes some of keywords I developed by the Python)  and  I don't know why that the robot is stopped with no reason and warning , fails , exceptions after it runs a period of time and I make sure my keyword is right and robot does not call my keyword when it finished above all keywords.
You can see the running status in robot framework ride interface when this problem is happened , Maybe it will be running forever if you have the enough confidence ：（
And, this a strange phenomena does not happened for every times， other words ，it is low probability event.  
So，It's a very tricky problem for me and I have never met it before..!!
I hope to get a favor from the expert and friend who has been able to accomplish when this a strange problem is occurred..
I very mush hope to get any suggestions from all friends for this problem whatever you meet this problem or not..

sincerely

Hope to get your favor of anyone..!!

Smy

**Comment by HelioGuilherme66** [comment]
@shiminyang We cannot help you here. This is an Issue tracker, and it is only to report bugs or possible improvements suggestions. You can see what better ways to communicate in the [support](http://robotframework.org/#support) page. I recommend the Slack chat, because there is always someone there to help.
