### ISSUE TITLE
Clarify documentation related to options that have an effect with `TestSuite.run()`

### ISSUE THREAD

**Issue by ben-g-** [robotframework/robotframework#2999]
Version info: Robot Framework 3.0.4 (Python 3.5.2 on win32)

The `--prerunmodifier` option works when I pass it on the command line to the robot script, and it also works when I pass it as a named argument to `robot.run()`, but it seems to be ignored when I pass it as a named argument to `TestSuite.run()`.

I've constructed a toy example.

My test suite is called robot-toy\toy.tsv and contains this:
```
*Test Cases*
toy	Comment	this is a comment
```

I can run that via any of (a) the robot script, (b) `robot.run()`, or (c) `TestSuite.run()`, and it passes as expected.

Now I create a module called `toyPreRunModifier` that contains this:
```
from robot.api import SuiteVisitor
from robot.running.model import Keyword

class ToyPreRunModifier(SuiteVisitor):
    def start_test(self, test):
        teardown = Keyword(name='Fail', type='teardown')
        test.keywords.append(teardown)
```

If I run my test suite with `toyPreRunModifier.ToyPreRunModifier` as a prerunmodifier via (a) the robot script or (b) `robot.run()`, then it fails as expected. But if I do so via (c) `TestSuite.run()`, then it passes just as if I hadn't specified any prerunmodifier.

Via the robot script:
```
C:\tmp>pipenv run robot --prerunmodifier=toyPreRunModifier.ToyPreRunModifier robot-toy\toy.tsv
==============================================================================
Toy
==============================================================================
toy                                                                   | FAIL |
Teardown failed:
AssertionError
------------------------------------------------------------------------------
Toy                                                                   | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
```

Via `robot.run()`:
```
C:\tmp>pipenv run python -c "import robot; robot.run('c:/tmp/robot-toy/toy.tsv', prerunmodifier='toyPreRunModifier.ToyPreRunModifier')"
==============================================================================
Toy
==============================================================================
toy                                                                   | FAIL |
Teardown failed:
AssertionError
------------------------------------------------------------------------------
Toy                                                                   | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
```

Via `TestSuite.run()`:
```
C:\tmp>pipenv run python -c "from robot.api import TestSuiteBuilder; TestSuiteBuilder().build('c:/tmp/robot-toy/toy.tsv').run(prerunmodifier='toyPreRunModifier.ToyPreRunModifier')"
==============================================================================
Toy
==============================================================================
toy                                                                   | PASS |
------------------------------------------------------------------------------
Toy                                                                   | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed
==============================================================================
```

Is that a bug or is that not supposed to work?

**Comment by pekkaklarck** [comment]
This isn't supposed to work. Modifiers are meant for higher level APIs. When you got a `TestSuite` object, you can modify it using other means. For example, you could pass your modifier to `TestSuite.visit` method.

Do you see docs that could be explained to make this more clear?

**Comment by pekkaklarck** [comment]
Thanks for the proposed documentation enhancements! I'll use the first as-is but use slightly different wording with the latter. Since this is only a documentation change, this is safe still before RF 3.1.
