### ISSUE TITLE
How to get test/suite variables from inside a custom robot library

### ISSUE THREAD

**Issue by PhilippeTrounev** [robotframework/robotframework#3012]
I am wondering if it is possible to get access to custom test/suite variables from inside the python code of the custom keyword such as a keyword

GET USER can grab global variables defined in Robot Suite. I've looked for an answer to this but was never able to find an answer..

**Comment by pekkaklarck** [comment]
Typically such information is passed to keywords as arguments.If that's not adequate for some reason, there are BuildIn library keywords that you can use as regular Python methods to get that information.

This issue tracker is for bug reports and enhancement requests and thus closing this issue. If you got further questions, please use the support channels listed at http://robotframework.org.
