### ISSUE TITLE
 `Run Keyword And Continue On Failure` doesn't work if keyword teardown fails

### ISSUE THREAD

**Issue by myjniak** [robotframework/robotframework#3015]
Here's the simplest code that can reproduce the issue:

```
*** Test Cases ***
Test
    Run Keyword And Continue On Failure  A

*** Keywords ***
A
    Log  Hi  console=True
    [Teardown]   Fail
```

Executing the above code results in message "maximum recursion depth exceeded while calling a Python object"
Shouldn't teardowns be allowed to fail inside keywords?
Tested with robotframework version 3.0.2

**Comment by pekkaklarck** [comment]
I can reproduce the problem. Seem to be a combination of using `Run Keyword And Continue On Failure` and keyword teardown failing. Shouldn't be hard to fix.

We just released RF 3.1 rc 1 and I'm not sure is this severe enough to warrant rc 2. Let's see are other problems found and decide then is this included in 3.1 or does it need to wait for 3.1.1.

**Comment by myjniak** [comment]
Maybe this could help you decide on the severity:
The **Run Keyword And Continue On Failure** will **not** continue on failure in this scenario.
Try this:

```
*** Test Cases ***
Test
    Run Keyword And Continue On Failure  A
    Log To Console    Hi again

*** Keywords ***
A
    Log  Hi  console=True
    [Teardown]   Fail

```

**Comment by pekkaklarck** [comment]
I know it won't continue but the test would fail anyway. The bug is definitely worth fixing but I'm not sure is it t worth including into 3.1 this late. The good news is that fixing seems to be pretty simple and safe. Would still require rc 2.

**Comment by pekkaklarck** [comment]
Decided to fix this and create rc 2 early next week.
