### ISSUE TITLE
User Guide: Clarify using newlines in documentation in test data

### ISSUE THREAD

**Issue by robinmackaij** [robotframework/robotframework#3021]
When running the examples found at
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#id818
through robot.testdoc, the output is not as expected. Note that the orange border is most likely not a parsing output issue but rather an issue in the example; as far as I know, '...    ' is a continuation of a line of text so
`...      Second paragraph, this time`
`...      with multiple lines.`
should in fact be on a single line, contrary to what the example text suggests.

![test_documentation](https://user-images.githubusercontent.com/45491813/49386559-206f9d80-f720-11e8-8195-3431f3581ec0.png)

**Comment by pekkaklarck** [comment]
Explanation is kind of right that `\n` and `...` both create a newline. The reason this doesn't show is that when you have a paragraph of text, lines separated with a single newline form a single paragraph where lines in practice are combined. This is actually explained in the next section in the User Guide:
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#paragraphs

It's obviously somewhat confusing to explain how `\n` creates a newline with an example where the newline doesn't actually matter. Some ideas what we could do to enhance the documentation:

- Change the example to use e.g. lists where newlines actually matter.
- Add a note into the problematic section that single newlines don't actually affect how paragraphs are rendered with a link to the paragraph section.

**Comment by pekkaklarck** [comment]
Clarified the documentation in the commit above. Let me know if you think the docs could still be enhanced.

**Comment by Zarhrezz** [comment]
The examples look good now (outside the missing space that I've commented)
and extra explanation helps.

What remains is the issue that the line breaks do not seem to work for the
Documentation for the test cases however. I guess that's something that'll
require a change to testdoc.

Cheers,
Robin

**Comment by pekkaklarck** [comment]
That missing space was a good catch! Could you clarify the remaining issue you have with test cases?
