### ISSUE TITLE
robot tag for teardown fail

### ISSUE THREAD

**Issue by juhoarvid** [robotframework/robotframework#3022]
Hi,

Would it be valuable to add robot prefixed tag if failure happens in teardown? I mean cases which fails due to teardown failure, but would elsewhere be passing.

This is similar than https://github.com/robotframework/robotframework/issues/2135, but with difference that failures are done.

I suppose in many cases teardown are used for enviroment state restoring. Verification part is done inside tests and test steps(not test or suite teardown).

If tags would be added to cases, which are failing due to suite/testcase teardown failure(could be different tag for test and suite level), it would give value when results are analysed.

**Comment by pekkaklarck** [comment]
Interesting idea. I'm not sure would it be a good idea with test teardowns, but explicitly marking tests taht fail because suite teardown fails could be useful. I guess such a tag should only be added to tests that otherwise passed?

**Comment by juhoarvid** [comment]
You understand exactly my case. So for those cases which are otherwise PASS, but due to suites teardown(or setup) are FAIL, should be somehow be tagged. When analyzing big amount of testresults I face cases failing due to suite setup/teardown and that would help to separate those situation away

**Comment by pekkaklarck** [comment]
Sound good to me. Don't want to change functionality in a minor relase but definitely doable in RF 3.2. Are you interested in implementing this? Ought to be pretty easy.

**Comment by pekkaklarck** [comment]
Is @juhoarvid or anyone else interested in implementing this?

**Comment by pekkaklarck** [comment]
Apparently there's not enough interest towards this for anyone to implement it. Closing. Can be reopened later if needed.
