### ISSUE TITLE
Regression in string concatenation with the item access

### ISSUE THREAD

**Issue by tminakov** [robotframework/robotframework#3028]
When trying to construct a new value by using a string variable plus suffix enclosed with `[]`, the framework throws an error:

> Variable '${the_var}' is string, not list or dictionary, and thus accessing item '1' from it is not possible.

In my code I use this for constructing xpath locators - either having a common root that's shared across a number of locators, or to append a predicate.

An example:

```
*** Variables ***
# the first type of error, constructing a variable by concatenating a preexisting one with a suffix
# error in the initialization
${LOC HOME CHART BOX INFO}                      xpath=//div/div/table[@class="c3-tooltip"]//tr
${LOC HOME CHART BOX DATE PLACEHOLDER}          ${LOC HOME CHART BOX INFO}[1]/th[text()="PLACEHOLDERselenium"]       # the first type of error, in the Variables section

# the second one - on this value a predicate is to be appended
${CLIENT DDL MENU OPTIONS}          xpath=//nav[contains(@class,"topnavbar")]//div[@class="Select-menu"]/div

*** Test Cases ***
A test case
    Log To Console      ${CLIENT DDL MENU OPTIONS}[1]     # the actual keyword doesn't matter (it's usually "Click Element")

```

Running this sample produces the following errors:

> Error in file 'the_file.robot': Setting variable '${LOC_SEARCH_RESUTLS_TABLE_COLUMN_NAME_PLACEHOLDER}' failed: Variable '${LOC_SEARCH_RESULTS_TABLE_HEADING}' is string, not list or dictionary, and thus accessing item 'text()="PLACEHOLDERselenium" or .//*[text()="PLACEHOLDERselenium"' from it is not possible.

and
> Variable '${CLIENT DDL MENU OPTIONS}' is string, not list or dictionary, and thus accessing item '1' from it is not possible.

This is a regression from 3.0.4, where this automatic concatenation syntax worked without issues. I have literally hundreds of constructs like this, on which I'm currently looking for a stable workaround (probably something involving xpath's `self` axis).

---
A solution would be to exclude during parsing string-like variables from item access (or, to limit it to dict and list derivatives); there won't be functionality loss - even though a code like `"string 1"[1]` is perfectly fine python idiom, Robot Framework doesn't support it (as obvious from the error messages), so the current state will be preserved.

**Comment by pekkaklarck** [comment]
This is caused by #2601 and explained in the release notes under backwards-incompatible changes:
https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-3.1.rst#id113

**Comment by pekkaklarck** [comment]
After re-reading I noticed you proposed limiting item access to lists and dicts. That, and just excluding access with strings, can be considered if there turn out to be a lot of problems caused by this. Escaping with `\` is easy, but obviously somewhat annoying if you need to do it in many places.

I'll reopen this issue and we can discuss what to do.

**Comment by tminakov** [comment]
Thanks for the workaround suggestion, I actually haven't thought of using escaping (`\`). Checked it, and the produced string is what I expect; that will take care of most of the occurrences of this issue.  
Another workaround is to use whitespace - e.g. `${CLIENT DDL MENU OPTIONS} [1]`, which as it turns out is insignificant in this locations for xpath (I'll have to use this one in more complex situations, like concatenating two variables  - `${var_a}${var_b}`, where the escape character is not usable). As my situation is a corner case (hopefully), I'll workaround it on my end as a change will not come immediately.

---
To summarize, for anyone that might face the same issue - the workarounds are either:

- escape the `[` character, e.g. `${variable}\[1]`
- for xpath, put an extra whitespace character b/n the variable and the `[`, it's of no difference for it - `${variable} [1]`

---

As for excluding access in strings, here's a naive solution (**disclaimer**: haven't checked it fully for side effects, nor ran the framework's cases) - in variables/replacer.py, `_get_variable()`:

```
138a139,142
>         # item access is not supported for string variables, return the string as-is
>         if is_string(variable):
>             return variable
> 
```

**Comment by tminakov** [comment]
And, looking at the code, doing the reverse - actually allowing item or slices access to string variables is trivial. Here's a sample:
https://github.com/tminakov/robotframework/commit/bc7b14ae04c52bf46338b003e7bb06e894c14b82

@pekkaklarck  if you find this valuable, and won't cause confusion to the users, we might work an adding it?

**Comment by pekkaklarck** [comment]
Could you clarify why would you need to use a space for escaping? Depending in the context it mat work, but you shouldn't need to use it.

Supporting item access with strings is definitely possible and could be useful. Don't want to so such changes in a minor version, so it would need to wait until RF 3.2, through. If we consider that, the current behavior that item access syntax with strings is an explicit error is actually a good thing.

**Comment by joaonc** [comment]
I'm also hitting this issue and _many_ test cases where I set XPaths started to fail when upgrading to RF 3.1.
IMO, this warrants a minor version fix (ex. 3.1.1) as I'm pretty sure this will break many other people using XPaths as well. Doing `${X}=    Set Variable    ${Xpath}[${i}]` is pretty common.

Reverting to 3.0.4 until this is dealt with.  If the official solution is to escape, I'll update the tests then.

**Comment by pekkaklarck** [comment]
You are @tminakov right that `${var1}${var2}` doesn't initiate item access even if `${var2}` would look like `[something]`. Similarly it isn't considered named argument syntax even if `${var2}` would contain `=value`. Such special syntax must always be used literally in test case level.

As I wrote earlier, supporting item access with strings is something that we definitely can consider in RF 3.2. We could actually try it with all values to make it possible to use this syntax with custom objects implementing `__getitem__`.

**Comment by pekkaklarck** [comment]
We were @joaonc aware of backwards-incompatibility problems when designing the new functionality involving this syntax. If you go through the discussion in #2601, we in the end considered the benefits bigger that problems. We didn't realize that syntax like `${xpath}[${predicate}]` is so common, though.

I still think that the new item access syntax itself is useful. How to handle item access with strings is something we still can discuss. Personally I like it that this syntax always mean item access and escaping is needed if you want to use the literal syntax. That makes understanding the data easier, and also allows adding the actual item access syntax to strings later if we consider it a good idea.

The above said, if there are lot of reports about problems with the new syntax, we can consider changing it so that `${var}[whatever]` isn't item access if `${var}` is a string. There would need to be quite a bit more such reports, though. My current thinking is that escaping is easy enough that changes aren't needed. In other words, that's the current "official solution".

**Comment by tapioreijonen** [comment]
We also detect this problem:
xpath=(//body/${headingTag}[text()='${text}'])

And fixed using Catenate KW:
${heading xpath}=    Catenate    SEPARATOR=    //body/${headingTag}    [text()='${text}']

**Comment by lennartq** [comment]
I had this problem after upgrading. Apparently it's mostly a matter of coding style; the only tests broken in our codebase were written by me.

Escaping is trivial and the affected rows are easy to find. No need for changes imo.

**Comment by pekkaklarck** [comment]
It seems backwards compatibility problems caused by #2601 aren't severe enough, especially when compared with benefits, that the functionality should be changed.

I also submitted #3182 about supporting `${var}[item]` syntax with all objects, including strings.
