### ISSUE TITLE
Regression using `--suite` when executing multiple data sources or `--name` option (affects Pabot)

### ISSUE THREAD

**Issue by modrz** [robotframework/robotframework#3029]
Hi.
It looks like multiple data source running with --suite selector raises errors now.

Take a look into following structure:
```
C:\
|__A
    |__test1.robot
    |__test2.robot
|__B
    |__test3.robot
    |__test4.robot
```

In version 3.1 following error is raised:
```
python -m pip install robotframework==3.1
>> Successfully installed robotframework-3.1

python -m robot.run --version
>> Robot Framework 3.1 (Python 2.7.14 on win32)

python -m robot.run --console dotted -s "A & B.A.Test1" -s "A & B.B.Test3" C:\A C:\B
>> [ ERROR ] Suite 'A & B' contains no tests in suites 'A & B.A.Test1' or 'A & B.B.Test3'.
```

However in version 3.0.4 and below such multi data source run did not cause any problems:
```
python -m pip install robotframework==3.0.4
>> Successfully installed robotframework-3.0.4

python -m robot.run --version
>> Robot Framework 3.0.4 (Python 2.7.14 on win32)

python -m robot.run --console dotted -s "A & B.A.Test1" -s "A & B.B.Test3" C:\A C:\B
>> 
==============================================================================
..
==============================================================================
Run suite 'A & B' with 2 tests in 30 milliseconds.

PASSED
2 critical tests, 2 passed, 0 failed
2 tests total, 2 passed, 0 failed
```

It looks like it was changed in 3.1b1 (probably connected to #2583). 
Is it expected behavior?

**Comment by pekkaklarck** [comment]
This is definitely a regression and you are right that it's caused by PR #2583 i.e. issue #2564. Can you @mihaiparvu see any easy or even possible way to fix the regression? If not, perhaps we should just revert the change. The benefits of omitting parsing of certain files is quite small, especially in the future when only `*.robot` files are parsed by default, and definitely not worth breaking functionality.

**Comment by pekkaklarck** [comment]
This issue ought to now be fixed. My plan is to create RF 3.1.1 rc 1 on Monday, December 31 and it would be great if those who have encountered this issue could verify the fix then. If you want, you can test it already now by installing the latest code directly from GitHub with this command:

    pip install https://github.com/robotframework/robotframework/archive/master.zip

**Comment by modrz** [comment]
I have checked latest code. It fixes problem I reported in this issue. Thanks.
