### ISSUE TITLE
Not able to use Listener with Robot/python

### ISSUE THREAD

**Issue by karakotimanoj77** [robotframework/robotframework#3031]
Hi I have written test cases in robot/python, in one of the scenario I want to copy the test case result (.html) in some other folder based on the execution time,
for this I used Listener in python, but somehow I am not able to execute the test cases with listener from command line:

 C:\Robot_Framework\Desktop-Automation\TestCases>robot --listener MyListner CallControl_Suit.robot
[ ERROR ] Taking listener 'MyListner' into use failed: Importing listener 'MyListner' failed: ImportError: No module named MyListner
Any help is greatly appreciated...

**Comment by karakotimanoj77** [comment]
`class MyListner:
    ROBOT_LISTENER_API_VERSION = 2

    def __init__(self, filename='listen.txt'):
        self.ROBOT_LIBRARY_LISTENER = self
        outpath = os.path.join(tempfile.gettempdir(), filename)
        console(outpath)
        self.outfile = open(outpath, 'w')

    def start_suite(self, name, attrs):
        self.outfile.write("%s '%s'\n" % (name, attrs['doc']))

    def start_test(self, name, attrs):
        tags = ' '.join(attrs['tags'])
        self.outfile.write("- %s '%s' [ %s ] :: " % (name, attrs['doc'], tags))

    def end_test(self, name, attrs):
        if attrs['status'] == 'PASS':
            self.outfile.write('PASS\n')
        else:
            self.outfile.write('FAIL: %s\n' % attrs['message'])

    def end_suite(self, name, attrs):
        self.outfile.write('%s\n%s\n' % (attrs['status'], attrs['message']))

    def close(self):
        self.outfile.close()'

**Comment by pekkaklarck** [comment]
The listener you use doesn't seem to be in Python module search path. See the User Guide for more information about taking listeners into use. If you still got problems, please send questions to support forums listed at http://robotframework.org. This tracker is for bug reports and enhancement requests.
