### ISSUE TITLE
Execution paused by `Comment` keyword which content start with '#'

### ISSUE THREAD

**Issue by kanchi240** [robotframework/robotframework#3032]
Test:
![2_20181220173136](https://user-images.githubusercontent.com/4908696/50276567-34840080-047d-11e9-9c23-57cd818657ec.png)

Execution Paused:
![1_20181220173126](https://user-images.githubusercontent.com/4908696/50276587-436ab300-047d-11e9-9190-79a1c3ae2fd1.png)

robot version: 3.1
python version: 3.7.1
os: windows 10

**Comment by pekkaklarck** [comment]
Does this happen also without RIDE?

**Comment by kanchi240** [comment]
No, test execution passed when use command.

**Comment by pekkaklarck** [comment]
In that case this  is a bug in RIDE and should be reported to its issue tracker.
