### ISSUE TITLE
xpath function last() not working correctly in version 3.1

### ISSUE THREAD

**Issue by nigotiator** [robotframework/robotframework#3035]
In KW I would like to get text from the last element. 
So I use 
` ${element} = //div[contains(@class,"s-alert-info")]
 ${n} = SeleniumLibrary.Get Text     ${element}[last()]//div[@class="title"] 
`
in 3.0 I get the element text correctly.

But in 3.1 I get error
`Variable '${element}' is string, not list or dictionary, and thus accessing item 'last()' from it is not possible.`

**Comment by pekkaklarck** [comment]
See release notes:
https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-3.1.rst#square-brackets-after-variable-like-var-xxx-is-considered-item-access

**Comment by pekkaklarck** [comment]
There's discussion related to this going on in #3028.
