### ISSUE TITLE
Nested Inner classes are not visible in Robot Framework

### ISSUE THREAD

**Issue by 1dziubo1** [robotframework/robotframework#3038]
```
class MainClass(object):
    class InnerClass(object):
       @staticmethod
       def innerClassMethod():
           return None

if __name__ == '__main__':
    MainClass.InnerClass.innerClassMethod
```

Robot Framework:
No keyword with name 'MainClass.InnerClass.innerClassMethod' found.

**Comment by pekkaklarck** [comment]
Could you please clarify? What's the problem and how does it affect Robot?

**Comment by pekkaklarck** [comment]
See my reply to #3039. Notice also that within a library you can access attributes of the library using normal Python logic.
