### ISSUE TITLE
Catching textbox labels

### ISSUE THREAD

**Issue by kenworthTulod** [robotframework/robotframework#3049]
Hi, it's my 1st post in GitHub so please help. I was assigned on a project to automate a website, now the question is how do you catch textbox label/s (Please enter a number) as a sign of error. I already used 'Page should contain' and 'Element should contain' of SeleniumLibrary but I still can't fix it, also stating in the report 'Page should have contained text 'Please enter a number.' but did not.'. Please help. Thank you.

![selenium-screenshot-1](https://user-images.githubusercontent.com/25452875/50867932-38ee6a00-13e8-11e9-924b-b1d51ebb9633.png)

**Example Suite**
```robot
*** Keywords ***
Error phone_number
    Page should contain     Please enter a number.
```

**System Info**
Robot version: 3.1.1
Installation tool: pip v18.1
Interpreter: Python 3.7.1
OS: Windows 10.0 Build 17134.472

**Comment by pekkaklarck** [comment]
This is a SeleniumLibrary issue and doesn't belong to this issue tracker. For questions you should generally use mailing list, Slack or other support forums listed at robotframework.org.
