### ISSUE TITLE
Run Keyword And Return Status fails if given keyword timeout occurs

### ISSUE THREAD

**Issue by myjniak** [robotframework/robotframework#3059]
If a keyword inside Run Keyword And Return Status fails by timeout, the Run Keyword And Return Status fails too.

```
*** Test Cases ***
Test
    ${status}=   Run Keyword And Return Status   A

*** Keywords ***
A
    [Timeout]  1
    Sleep  2
```
Tested with: Robot Framework 3.1.1

**Comment by myjniak** [comment]
I didn't read the documentation well enough. Sorry.

**Comment by myjniak** [comment]
Could you just comment the reason it is designed like that?
We could make use of handling timeouts like that.

**Comment by pekkaklarck** [comment]
Robot's timeouts kill the executing keyword in such way that environment can be left into unstable state. You should only use them when absolutely necessary. When they occur, we don't want to hide that.
