### ISSUE TITLE
macos10.13,Successfully installed robotframework-3.1.1,-bash: pybot: command not found&jybot --version -bash: jybot: command not found

### ISSUE THREAD

**Issue by gaga128** [robotframework/robotframework#3065]
![image](https://user-images.githubusercontent.com/18659947/51530271-84d3f100-1e75-11e9-8354-6892b3366dbc.png)
localhost:~ jia$ sudo -H pip install robotframework
Collecting robotframework
  Using cached https://files.pythonhosted.org/packages/36/c6/6f89c80ac5a526a091bd383ffdfc64c9a68d9df0c775d4b36f03d8e0ac25/robotframework-3.1.1-py2.py3-none-any.whl
Installing collected packages: robotframework
Successfully installed robotframework-3.1.1
localhost:~ jia$ robot --version
Robot Framework 3.1.1 (Python 2.7.10 on darwin)
localhost:~ jia$ rebot --version
Rebot 3.1.1 (Python 2.7.10 on darwin)
localhost:~ jia$ pybot --version
-bash: pybot: command not found

**Comment by pekkaklarck** [comment]
RF 3.1 dropped `pybot` scripts for reasons explained in #2818. This change is explained also in the release notes:
https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-3.1.rst#old-start-up-scripts-like-pybot-are-removed

**Comment by gaga128** [comment]
> RF 3.1 dropped `pybot` scripts for reasons explained in #2818. This change is explained also in the release notes:
> https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-3.1.rst#old-start-up-scripts-like-pybot-are-removed


So the following command represents successful installation?
localhost:~ jia$ robot --version
Robot Framework 3.1.1 (Python 2.7.10 on darwin)
localhost:~ jia$ rebot --version
Rebot 3.1.1 (Python 2.7.10 on darwin)
