### ISSUE TITLE
Profiling of gherkin keywords

### ISSUE THREAD

**Issue by p74** [robotframework/robotframework#3070]
Hi,

 I found the tool https://bitbucket.org/robotframework/robottools/src/master/keywordtimes/
 but when i run it the output of the profiling is not what i expect

 for example i have a keyword rebootDut(nr)

 given  reboot dut "1"
 given  reboot dut "2"
 given  reboot dut "3"

 will result in

 Total time (s) |   Calls | Avg time (s) | Median time (s) | Stdev (s) | Stdev/avg time % | Keyword name
        730.834 |       1 |      730.834 |      731199.417 |       0.0 |              0.0 | given  reboot dut "1"
        207.187 |       1 |      207.187 |      207290.593 |       0.0 |              0.0 | given  reboot dut "2"
         90.488 |       1 |       90.488 |       90533.244 |       0.0 |              0.0 | given  reboot dut "3"

 but what i expect is something like this:

 Total time (s) |   Calls | Avg time (s) | Median time (s) | Stdev (s) | Stdev/avg time % | Keyword name
       x |       x |     x |     x |     x |             x | rebootDut(nr)

 It are the same function calls but with different arguments. Is there another tool available to do some profiling on gherkin keywords?

 Thx Ruud

===============================================
This tool could be enhanced to handle this situation better. I won't
personally have time for that in the near future, but perhaps someone
else has. At least an issue should be submitted.

If development is actually done, then the project should probably be
moved to GitHub first. This particular tool could actually be moved
into its own repository.

Cheers,
    .peke

===============================================

**Comment by pekkaklarck** [comment]
Issues related to the keyword-times tool belong to its issue tracker, this tracker is only for Robot Framework core. In general it would be best to move the tool into a dedicated project on GitHub to make it easier to develop it further. Unfortunately I don't have time for that in the near future. Anyone else interested could do it as well.
