### ISSUE TITLE
Empty suite should not be an error

### ISSUE THREAD

**Issue by gvarga-lmi** [robotframework/robotframework#3071]
pybot (as well as pabot) treats empty suites as an error.
Running tests selectively (with tag exclusion) is part of development/troubleshoot activity, should not err out.

Steps to reproduce:

--- Suite file ---
  *** Settings ***
Force Tags   temptest   skipped

*** Test Cases ***
Foo
    No operation
--- end suite file ---

run the above suite file with tag inclusion+exclusion:
pybot [...] --include temptest --exclude skipped [...]

[ ERROR ] Suite 'TestSuite' contains no tests with tag 'temptest' and without tag 'skipped'.

**Comment by gvarga-lmi** [comment]
It works, maybe this should be the default behavior.
(pabot still does not handle this well, but that's a different repo)

**Comment by pekkaklarck** [comment]
I don't think it would be a good default and change would be backwards incompatible. It's easy to add this option to start-up scripts when it makes sense. Pabot can also use it when running tests if needed.

**Comment by t-my** [comment]
This was the first google hit when googled `robot framework --runemptysuite` so providing a link to an another issue where robot returns an error code if you try to process an empty test suite: https://github.com/robotframework/robotframework/issues/3862
