### ISSUE TITLE
"Set Log Level" works as not expected

### ISSUE THREAD

**Issue by tysonite** [robotframework/robotframework#3072]
`Set Log Level` behaves improperly:
1. `${log_level_tmp}   Set Log Level  NONE` does not log (in `log.html`) previous log level, however, I expect it to be logged in case previous log level was >= `INFO`;

A Robot test script to reproduce observations above:
```
*** Test Cases ***
Test_01
   ${log_level_tmp}   Set Log Level  NONE
```

Command used to run script: `robot --loglevel TRACE <script>`.

**Comment by pekkaklarck** [comment]
If I understand this correctly, logging is disabled before the old level is logged. In my opinion that's just fine. If you really want to see the old level, use this:

```
${old} =    Set Log Level    INFO
Set Log Level    NONE
```
