### ISSUE TITLE
The problem with "Message content over the limit has been removed." feature

### ISSUE THREAD

**Issue by myjniak** [robotframework/robotframework#3073]
It is probably a recurring theme here, but here is my scenario:
- I use a python library that I cannot change
- I call one of the library's functions, expect it to fail and give me a long error message
- I need to grep the contents of the error message
- I cannot do that because the message saved to the robot variable is cut out.

I understand the idea of clear logging, but it should not affect the python function output.

Here is a reproduction of the problem. The code below will fail:
```
*** Settings ***
Library   failing_lib.py

*** Test Cases ***
Find String In Error Message
    ${status}  ${result}=  Run Keyword And Ignore Error  A
    Should Contain  ${result}  find me
```
failing_lib.py:
```
def a():
    x = "aaaaaa"
    for i in range(30):
        x = x + "aaaaaaaa\n"
    x = x + "find me"
    for i in range(30):
        x = x + "aaaaaaaa\n"
    raise ValueError(x)
    return x
```

PS: If this is still somehow an intended behavior, should the user parse the output.xml file?

**Comment by myjniak** [comment]
> ...but I'd be fine changing the logic so that error message is cut only when the final error message for the test is created so that keywords like Run Keyword And Ignore Error would still see the full message.

That is exactly my point here :)
I think the content of the variables should not be affected. I would greatly appreciate this change.
I will use --maxerrorlines in the meantime.

**Comment by pekkaklarck** [comment]
I personally won't have time to look at this in the foreseeable future. I'll leave this open for some time in case someone else is interested to look at it.

**Comment by pekkaklarck** [comment]
Closing because there doesn't seem to be interest to fix this and `--maxerrorlines` is a good workaround.
