### ISSUE TITLE
Deprecate FOR loops starting with case-insensitive `:FOR`

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#3080]
RF 3.1 made it possible to start FOR loops with `FOR` (case-sensitive) in addition to `:FOR` (case-insensitive) (#2990). Same style will also be used with IF/ELSE (#3074) and TRY/EXCEPT (#3075). Having multiple supported syntax variants is confusing and makes it harder to implement tooling that understands the test data. We thus want to remove the old syntax as soon as possible but cannot do that without deprecating it first.

The plan is to deprecate the old syntax in RF 3.2 and then remove it in RF 3.3. As a result the new parser that will be introduced in RF 3.2 (#3076) still needs to support also `:FOR`.

See also highly related #3078 about deprecating FOR loops without explicit `END` marker.

**Comment by DirkRichter** [comment]
If lower-case is used in new FOR-loop style like this:
`For    ${element}    IN    @{elements}`
you will get this strange error message: **Reserved.For ${element}, IN, @{elements}: Variable '${element}' not found.**

While reading this error message you assume the keyword *For* is *reserved* and understood as FOR-loop keyword. But in fact, this is wrong. *Uppercase* is required and works well. We faced this while migration from old FOR-loop style to new style. Thus i suggest to **improve the error message** in this case to e.g. **Keyword  'For'  is unknown**.

**Comment by pekkaklarck** [comment]
The reason this happens is that we have a library called [Reserved](https://github.com/robotframework/robotframework/blob/master/src/robot/libraries/Reserved.py) that contains some special keywords we don't want to be used as normal keywords. `For` is one of them, and thus when you use `For`, not `FOR`, that is used. In your case calling this keyword fails because `${element}` variable doesn't exist, but otherwise you'd get an error saying `For is a reserved keyword.`.

I agree that this situation should be handled better. It would be pretty easy to change the Reserved library so that variables wouldn't be resolved when its keywords are called. That and enhancing the error message with `For` could be enough.
