### ISSUE TITLE
How to call a link in a list (Robotframework/Silenium2Library)

### ISSUE THREAD

**Issue by LoryJolina** [robotframework/robotframework#3088]
Hi, 

i use Robotframework with Silenium2Library since 1 Week for automatic tests. 
Now i have a problem with clicking a link within a list. 
Can you help me? 

Here is the .html code of the website: 
`<aside class="hidden-xs col-sm-3">`
	       `<nav class="subnavigation">`
		`<ul class="nav">`
			`<li data-user-groups="18" style="display: list-item;">`
				`<a href="Link">`
					`Text`
				`</a>`
`</li>`

I want to open the "Link" in this Element: 
**a <href="Link">**

![python](https://user-images.githubusercontent.com/47355569/52275790-ce7e0a80-2950-11e9-8bca-78e61afa8a1c.PNG)

Any tips for me? 

Thanks, 
Lory

**Comment by pekkaklarck** [comment]
This issue tracker is for bug reports and enhancement request. Please send general questions to mailing list, Slack, or other such forums listed at http://robotframework.org/#support.
