### ISSUE TITLE
Add `Set Local Variable` keyword

### ISSUE THREAD

**Issue by mihaiparvu** [robotframework/robotframework#3091]
Below is a request from library developers in my organization that would benefit from the addition of a new keyword to set a local scope variable.

I will act as a proxy on their behalf and here is some context from their side:

------------------------------------------------------------------------------------------------------------
Currently there are BuiltIn keywords for setting variables for the scopes `global`, `suite` and `test`:

``` robotframework
Set Global Variable  ${global_var}  global_value
Set Suite Variable  ${suite_var}  suite_value
Set Test Variable  ${test_var}  test_value
```

but no keyword:
``` robotframework
Set Local Variable  ${local_var}  local_value
```
for the scope `local`.

Instead this case is covered by a different syntax:
``` robotframework
${local_var}=  Set Variable  local_value
``` 
A consequence of this is, that the `local` scope case cannot be covered by `Run Keyword If`, but requires a separate keyword `Set Variable If`, which has a different syntax (see `ELSE IF`/`ELSE`).

Furthermore, as a library keyword developer, I want to be able to get/set Robot variables of all scopes from Python. Currently this can be achieved by calling:
```python
BuiltIn().get_variable_value()
BuiltIn().set_global_variable()
BuiltIn().set_suite_variable()
BuiltIn().set_test_variable()
BuiltIn()._variables["${local_var}"] = obj
```
The last call for setting a local variable requires to use a protected attribute of `BuiltIn()`, which as such is not part of a stable public API. If there would be a keyword `Set Local Variable` in BuiltIn, then it would be possible to set a local Robot variable from a library keyword by calling `BuiltIn().set_local_variable()` in Python.

There might be different opinions about whether it is a good idea to call Robot keywords from Python or whether a keyword should have a side effect on a Robot variable, but in practice we have such cases.

---------------------------------------------------------------------------------------------------------------
Our team will happily provide a pull-request for this keyword if it is decided to be included in a future release.

**Comment by pekkaklarck** [comment]
My initial reaction was that on test data it's cleaner to only have assignment syntax for this purpose and for libraries we should have some better API for variable handling. On the other hand, `Set Local Variable` would be consistent with existing `Set Test/Suite/Global Variable` and adding this single keyword is a lot easier than creating a new API for variables. An added benefit of this keyword would be that it ought to support creating variable using a variable in the name like

    Set Local Variable    ${Field_Number_${i}}    value

which isn't possible (at least at the moment) using assignment. This was just discussed on the mailing list: https://groups.google.com/d/msg/robotframework-users/3s_qECTwhgQ/hVlUe7-CBAAJ

**Comment by sebastianciupinski** [comment]
Moreover, I have deeper thoughts about it. I think current keyword `Set Variable` should be rather named `Assign Value`. I know this change would introduce huge backwards compatibility (and abandon support for python 2.7 probably) and require refactoring of thousands test cases and libraries. But whole approach could looks like this:

```
${x}=    Assign Value    some
```
And  `Set Variable` keyword could be implemented like this:

```
def set_variable (self, *values, scope='LOCAL'):
    #implementation

```

Then creating variables would work like this:

```
Set Variable    ${scalar}     some_value
Set Variable    @{list}     some    some_other    scope=GLOBAL
```

Also "promoting" variable to wider scope would work just like this:

```
Set Variable    ${global}    value     scope='TEST'
```

Instead of current approach:

```
${x}=    Set Variable    value
Set Test Variable    ${x}    ${x}
```

Also other improvement (but not so important as you are planning to rearrange syntax parser for IF instead of `Run keyword If`) would be possible. For now such code is invalid:

```
Run Keyword If    ${a}==${b}    Run Keywords
...    Log    blah    AND
...    ${var}=     Set Variable     val
```

But after described change such approach will be possible:

```
Run Keyword If    ${a}==${b}    Run Keywords
...    Log    blah    AND
...    Set Variable    ${var}     val
```

**Comment by pekkaklarck** [comment]
`Assign Value` actually sounds pretty good but I doubt renaming current `Set Variable` is worth the effort or at least it would require a very long deprecation period. Even if we'd do that, I still think `Set Local Variable` would be a better name for the proposed keyword.

If it wasn't clear from my previous comment, I'd be fine `Set Local Variable` being added. Possibly renaming `Set Variable` to `Assign Value` or something else. or even coming up with new syntax to assign variables like that, requires its own issue. Probably even better to start discussion on Slack or robotframework-users before that.

**Comment by pekkaklarck** [comment]
Are you @mihaiparvu still interested in this? Could be easily added in RF 3.2.

**Comment by mihaiparvu** [comment]
Yeah, we are already working on it. Hope it's ready by next week and would definetly want to have it included in RF 3.2.

**Comment by pekkaklarck** [comment]
Sorry for the long delay with PR reviews. I now looked a PR #3191 and it was great. I added some comments about doc and test enhancements and it would be great if they could be addressed.

**Comment by pekkaklarck** [comment]
Great PR #3191 by @cristii006 has been merged and this issue is done!
