### ISSUE TITLE
Errors with inspect in chrome

### ISSUE THREAD

**Issue by EthanKing96** [robotframework/robotframework#3095]
Upon opening any web page with robot, then inspecting an element it always brings you to the top of the body element. This didn't seem to happen last week, before it would actually take you to the element you inspected. What is the issue here?

This error makes selecting elements in a webpage impossible.

Is anyone else having this issue?

**Comment by aaltat** [comment]
This issue tracker is reserved for the Robot Framework core bugs or enhanced request. Your problem is more of a support request and for support please see https://github.com/robotframework/robotframework/blob/master/README.rst#support-and-contact

**Comment by pekkaklarck** [comment]
It's somewhat rude to comment that free support you get is a joke.

**Comment by bkhouri** [comment]
I've personally used the Slack channel numerous times to give, and get support and I find it a wonderful way to get answers.  You just need to formulate your questions correctly, and ask in the correct channel.
