### ISSUE TITLE
Template is mandatory alone in a Test

### ISSUE THREAD

**Issue by jbesace** [robotframework/robotframework#3099]
Hi,
Actually, we try to use Robotframework on a way that permit us to convert it to user manual.

RF allow it with embeded arguments like that : 
`User ${use_name} open ${section_name} section`
`User Bryan open Communication section`

But, we want to use "Template" feature.
We don't have problem to use it but it's mandatory to use it single in a test like that : 

```
*** Test Cases ***
Test 1
     Open Url

Test 2
     [Template] Fill tab
          Data 1        Value 1
          Data 2        Value 2
          Data 3        Value 3

Test 3
     Save data
```

I understand why we can't put keyword after this template because it cannot known where the template end, but why we can't put keyword before this template like that : 

```
*** Test Cases ***
Test 1
     Open Url
     [Template] Fill tab
          Data 1        Value 1
          Data 2        Value 2
          Data 3        Value 3

Test 2
     Save data
```

This way allow more flexibility to organise our tests

______

Other problem, why we can't use Template in a keyword like that : 

```
*** Test Cases ***
Test 1
     Fill the tab   @{list}
     [Template] Fill tab
          Data 1        Value 1
          Data 2        Value 2
          Data 3        Value 3

*** Keywords ***
Fill the tab
     [Arguments]   @{list}
     [Template] Fill tab
          @{list]
```
or easier

```
*** Test Cases ***
Test 1
     Fill the tab


*** Keywords ***
Fill the tab
     [Template] Fill tab
          Data 1        Value 1
          Data 2        Value 2
          Data 3        Value 3
```

Thanks for the answer

**Comment by MaciejWiczk** [comment]
Use [Setup] in thr beggining of test. It will create a step as Test Setup, which will be executed before templates instances:

*** Test Cases ***
Test 1
          [Setup]    Open URL
          [Template]   Fill tab
          Data 1        Value 1
          Data 2        Value 2
          Data 3        Value 3

**Comment by pekkaklarck** [comment]
@MaciejWiczk is right, you can use setup (and also teardown) to run additional keywords besides the template. I guess templates with keywords could be useful sometimes as well (haven't needed them personally so far), but would need someone to design and implement it. I can help but don't have time to do it myself.

**Comment by jbesace** [comment]
I see what both of you mean but actually, this solution can't correspond to what we expect.
The problem is that we use the robot file to generate specification tests documentation.

So we found a custom solution : 

```
*** Test Cases ***
Test 1
     Fill data with these values : 
     -     Data 1        Value 1
     -     Data 2        Value 2
     -     Data 3        Value 3

*** Keywords ***
Fill data with these values
     [Arguments]   ${data}    ${value}
     Input text    xpath=xxxx     ${value}

${function} : 
     Set Suite Variable    ${action to repeat}   ${function}

-
     [Arguments]    @{mandatory args}   &{optional args}
     Run Keyword   ${action to repeat}    @{mandatory args}    &{optional args}
```

**Comment by pekkaklarck** [comment]
Wow, that's pretty clever! I don't see how this example alone would work differently than just using a template, but I guess the idea is that you can have now also other keywords before/after the "template" section.

Notice also that you could use`Run Keyword And Continue On Failure` instead of `Run Keyword` to emulate how templates work in this regard.

**Comment by chaussen** [comment]
in this situation i normally just use dictionary &{data_value} to pass in data and value pairs like 

Test 1
     Fill data with these values : 
     ...   Data 1=Value 1
     ...   Data 2=Value 2
     ...   Data 3=Value 3

but your way is really clever and new to me. thanks.

**Comment by pekkaklarck** [comment]
If someone is looking at the example above and doesn't understand it, that's OK as it is really clever. And I don't mean that in bad way.

The key is that the `${function} :` keyword uses [embedded arguments](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#embedding-arguments-into-keyword-name) and registers a keyword that the `-` keyword then uses when it's called. Both `${function} :` and `-` are reusable.

**Comment by williamoget-sl** [comment]
This is clever for sure. It took me a while to get it. The key for me was to realize the impact of `  :` (or`${SPACE}:` ).
That said, if I were to use this I would have to document it well to ensure new coders get it.
Certainly creative.

**Comment by jbesace** [comment]
Really happy that you like this solution.

Just to explain why we use that : 

Our first problem was to fill the data of differents forms and we want to use a generic keyword who can adapt even if it's an input, a checkbox, a radio button, a select...

But for the specification tests documentation, we need to have a clear test and put all the technic keywords in other file (resources.robot).

Moreover, we want to have a generic keyword for list of data, even if the datas is in a form or in a table and where we can use mandatory or/and optional datas.

In that way, we can give this tests documentation to our client and they can see a test like that : 

```
***Tests cases***
Fill the registration form
     Fill the form with theses datas : 
     -    Last Name      Martin
     -    First Name      Paul
     -    Age                 20
     -    Sex                 M

     Fill the tab with your exam notes : 
     -    Math              15                Remarks=Good
     -    English          12
     -    History           13                 Remarks=Can be better
```

**Comment by pekkaklarck** [comment]
I guess this issue can be closed. Thanks again for a great example!
