### ISSUE TITLE
Creating scalar variables in resource files with custom separator does not work correctly

### ISSUE THREAD

**Issue by MrBIN89** [robotframework/robotframework#3102]
Used RF Version: 3.0.2

Scalar variable `${CATENATE_VAR}` from resource file, it has been created using catenation syntax with empty SEPARATOR argument, has different values:
 1. proper string `aaabbbcccddd` for the first test suite 
 2. and `aaa bbb ccc ddd` for the second suite (for some reasons it contains spaces!). 

Though that variable has just one initialization in common resource file.

Example:
**first_suite.robot** suite file content:
```
*** Settings ***
Resource          ${CURDIR}${/}common.robot

Default Tags      check_catenate
Suite Setup       Suite Setup
Suite Teardown    Suite Teardown

*** Variables ***

${SHOULD_BE}    aaabbbcccddd

*** Test cases ***
Check Catenate Functionality
    [Setup]    Should Be Equal    ${CATENATE_VAR}    ${SHOULD_BE}
    Should Be Equal    ${CATENATE_VAR}    ${SHOULD_BE}
    [Teardown]    Should Be Equal    ${CATENATE_VAR}    ${SHOULD_BE}

*** Keywords ***
Suite Setup
    Log  ${CATENATE_VAR}
    Should Be Equal    ${CATENATE_VAR}    ${SHOULD_BE}

Suite Teardown
    Should Be Equal    ${CATENATE_VAR}    ${SHOULD_BE}
```
**second_suite.robot** suite file content:
```
*** Settings ***
Resource          ${CURDIR}${/}common.robot

Default Tags      check_catenate
Suite Setup       Suite Setup
Suite Teardown    Suite Teardown

*** Variables ***

${SHOULD_BE}    aaabbbcccddd

*** Test cases ***
Check Catenate Functionality
    [Setup]    Should Be Equal    ${CATENATE_VAR}    ${SHOULD_BE}
    Should Be Equal    ${CATENATE_VAR}    ${SHOULD_BE}
    [Teardown]    Should Be Equal    ${CATENATE_VAR}    ${SHOULD_BE}

*** Keywords ***
Suite Setup
    Log  ${CATENATE_VAR}
    Should Be Equal    ${CATENATE_VAR}    ${SHOULD_BE}

Suite Teardown
    Should Be Equal    ${CATENATE_VAR}    ${SHOULD_BE}
```
**common.robot** resource file content
```
*** Settings ***

*** Variables ***
${CATENATE_VAR}    SEPARATOR=
            ...    aaa
            ...    bbb
            ...    ccc
            ...    ddd

*** Keywords ***
```

Results: 
Both suites work perfect in case separated run.
But in case run together (at one time) it fails:
`Parent suite setup failed: aaa bbb ccc ddd != aaabbbcccddd`

PS: I didn't check it for the latest RF version.

**Comment by pekkaklarck** [comment]
I have no idea what's going on here, but I can reproduce the problem with RF 3.1.1 as well. Don't have time to debug this more now (or in the immediate future) but I'll add this to RF 3.1.2 scope so that it won't be forgotten.

**Comment by pekkaklarck** [comment]
I'm not working with RF 3.1.2 with a plan to have at least a release candidate out in April. I was able to find the root cause for this problem and after that the fix was pretty trivial.

In practice this issue meant that it wasn't possible to create scalar variables in resource files using the `SEPARATOR=` syntax. I consider that pretty severe and raised the priority.
