### ISSUE TITLE
Custom section linking in documentation 

### ISSUE THREAD

**Issue by TusAuto** [robotframework/robotframework#3103]
Currently we are developing custom libraries for our project. We are able to create custom libraries but unable to link it.  We are using robot= 3.1b2 version and python 2.7 version. Please help . Please find the attached screenshot for more information.
[linking error.docx](https://github.com/robotframework/robotframework/files/2894125/linking.error.docx)

**Comment by pekkaklarck** [comment]
Could you please clarify the problem you hav encountered? Notice that I'm not going to open any external `docx` file or similar.

**Comment by TusAuto** [comment]
![image](https://user-images.githubusercontent.com/47890381/53620001-681a9e00-3c17-11e9-99b9-ea3d90b776c1.png)



1.In above screenshot we need to link custom section ‘XDLC API date”. Currently we are unable to link it.  We are using robot documentation format to display.

**Comment by TusAuto** [comment]
1. Below is the Class for which we want to generate Robot Keyword documentation [ Doc Format ='ROBOT']
2. In Below Class we want to link custom section  "XYZ API Data" in robot documentation format. Currently we are able to see all the documentation in robot format as mentioned below but unable to create link to custom section. We are expecting that once user click on "XYZ API Data" link in robot documentation user should be able to navigate to respective page. which is currently not happening. 
3. In Class Sample we are linking "XYZ API Data" which will link to respective api data section. Which is not happening.
4. Even it has been observed that , In Robot in build Builtin library Custom section linking is not working.  Please refer sample custom linking of  'Boolean arguments' in builtin library.
5. Please help us , how we can link custom section so that user can navigate to respective page.

Class Dummy (parameter)
"""
 = XYZ API Data =
       Use respective api data to generate corresponding event
    | *Event* | *API Data* |
    | Cold | srcStatus |
    | Hot | srcTrbl |
    | Output Activate | outState |
    | Z1 Open | z1Open |
    | Z1 Short | z1Short |
	
	Example:
    | *Setting* |
    | Library   | SimNgInterface |
    

    ROBOT_LIBRARY_VERSION = 1
    ROBOT_LIBRARY_SCOPE = 'TEST SUITE'
    ROBOT_LIBRARY_DOC_FORMAT = 'ROBOT'
	
"""
	
Class Sample(parameter)
"""
please click on ' XYZ API Data '  to get more info on api data.


   Example:
    | *Setting* |
    | Library   | SampleInterface |
    """

    ROBOT_LIBRARY_VERSION = 1
    ROBOT_LIBRARY_SCOPE = 'TEST SUITE'
    ROBOT_LIBRARY_DOC_FORMAT = 'ROBOT'
"""

**Comment by pekkaklarck** [comment]
Have you read the User Guide section about [internal linking](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#id386)?

Also, it would be a good idea to format messages to make the more readable. Click the `Styling with Markdown is supported ` link below the comment box for more details.

**Comment by sharadw1986** [comment]
We have gone through that link and following exact same thing but not able to get links for custom sections. Its OK for keyword linking.
I have checked with some of the libraries such as Rammbock. For those libraries also, linking of custom sections is not working. We are not able to see links for custom sections. is there is any issue with robot library version I am using?
Version of robot library I am using is:
Robot Framework 3.1b2.dev1 (Python 2.7.9 on win32)

**Comment by pekkaklarck** [comment]
Did you use backticks or single quotes?

**Comment by sharadw1986** [comment]
We are using backticks and not single quotes.

**Comment by pekkaklarck** [comment]
The example you provided seems to use single quotes. Can you provide one that doesn't and also doesn't work? Please format it so that it's easier ti read as well.

**Comment by sharadw1986** [comment]
def activateInput(self, addr, state):
        """`Activate Input` event for either 'device' or 'submodule'

        The Argument *addr* is absolute address of input on which event need be generated

        The *addr* shall be separated by ":"

        The sequence for address is

        addr1:addr2:addr3:addr4:addr5

        `Sample API Data`

        The argument *state* is the state of input event

        Possible Values of state:

        Value1, Value2, Value3, Value 4

        """

Here in this example we have link `Sample API Data` to custom section.

Custom section is written like this:
     = Sample API Data =
       Use respective api data to generate corresponding event
    | *Event* | *API Data* |
    | Event1| Event1Value|
    | Event2| Event2Value|
    | Event3| outState |
    | Event4| Open |
    | Event5| Short |

but link is not clickable and its shown as simple text `Sample API Data`

**Comment by pekkaklarck** [comment]
Could you please provide an example I can just copy and try out myself? The above example would still require me to construct an example file myself. For reasons why creating simple executable examples is important see http://sscce.org/.

**Comment by pekkaklarck** [comment]
No new info in two months. Closing.
