### ISSUE TITLE
Click is "missing" the target

### ISSUE THREAD

**Issue by ripper17** [robotframework/robotframework#3109]
In my robot tests, sometimes (about 50% of the time) this simple test fails (it works fine in the other 50%). It might have to do with the loaded advertising in the background, so when trying to reproduce this, please try this without any ad-blocker (sorry!):

```
*** Settings ***
Suite Setup       Run Keywords    SuiteSetup
Library           Selenium2Library    timeout=15.0    implicit_wait=0.3    run_on_failure=Nothing

*** Keywords ***
SuiteSetup
    Open Browser    https://dict.leo.org/englisch-deutsch    chrome
    # Window size:
    Set Window Size    1800    1000
    # Clear Localstorage:
    Execute Javascript    window.localStorage.clear();
    # Cookie handling:
    Delete All Cookies
    
TestSetup
    #    How long to wait between each test step?
    Set Selenium Speed    0 seconds
    #    How long to wait until an element is visible, the page contains an element etc.? (for commands like "Wait Until ...")
    Set Selenium Timeout    15 seconds

*** Test Cases ***
Dict - searchresults - centerColumn - icons - logged in
    #    Load page:
    Go To    https://dict.leo.org/englisch-deutsch/hölle
    #    Check icon "Mehr Informationen":
    Wait Until Element Is Visible    xpath=//div[@id='section-subst']//table//tr[1]/td[2]//i[@title='Mehr Informationen']
    Click Element    xpath=//div[@id='section-subst']//table//tr[1]/td[2]//i[@title='Mehr Informationen']
    Wait Until Element Is Visible    xpath=//div[contains(@class,'ui-dialog')]//span[text()='LEO: Zusatzinformationen']
    Click Element    xpath=//div[contains(@class,'ui-dialog')]//span[text()='LEO: Zusatzinformationen']/../button[@title='Close']
    Element Should Not Be Visible    xpath=//div[contains(@class,'ui-dialog')]//span[text()='LEO: Zusatzinformationen']
```

Expected result: 
- The overlay should close

Actual result:
- A new tab with the advertising-goal is opened

Reproducible:
- Sometimes (I'd say about 50%)

Tried workarounds:
I've tried to add a "Sleep" for two seconds before the click but that doesn't help.

Suspicions:
It might have something to do with *when* exactly the ad is appearing beneath the "X"-Button (that should be clicked), but obivously, this is nothing I can control. The "sleep" workaround kind of refutes that, though.

**Comment by pekkaklarck** [comment]
Not issue in RF core. I think this was already submitted to SeleniumLibrary tracker as well.

**Comment by ripper17** [comment]
Thanks for looking into this, just for future reference: the issue was indeed submitted to the SeleniumLibrary tracker at https://github.com/robotframework/SeleniumLibrary/issues/1317
