### ISSUE TITLE
Robot framework logger not adding info to debugfile if used inside resource file

### ISSUE THREAD

**Issue by dineshsivaji** [robotframework/robotframework#3112]
I am having a Robot suite in the following structure
```
S_SUITE
├── datasource.txt
├── dinesh.robot
├── __init__.py
└── test.py
```
**dinesh.robot**
```
 *** Settings ***
Library        test.py
Resource    datasource.txt
*** Test Cases ***
DEMO
    Log    "Testcase start"
    sample
    Log    "Testcase end"
```
**test.py**
```
from robot.api import logger
def sample():
    # Only the below logger.info is added into debug_record.txt
    logger.info('THIS IS INSIDE SAMPLE')
```
**datasource.txt**
```
*** Settings ***
Library   __init__.py
```
**__init__.py**
```
from robot.api import logger
from robot.libraries.BuiltIn import BuiltIn
# These below messages are not seen in debug_record.txt
logger.info('Expected to see this!!!')
logger.error('At least this in debug_record')

def hai():
  # These below messages are also not seen in debug_record.txt
  BuiltIn().log("this is an info message", "INFO")
  logger.info('this is an info too')

hai()
```
I am running this suite as  
`robot --loglevel debug --debugfile debug_record.txt S_SUITE/`. 

When I run this suite, the message `THIS IS INSIDE SAMPLE` alone is getting added into the `debug_record.txt`. The `datasource.txt` from `dinesh.robot` is including `__init__.py` file. This file has few `logger.info` statements which are never getting logged into the `debug_record.txt`.

Along with `logger.info`, I have also tried `logger.error` & `BuiltIn().log` as well. But no luck. I have noticed that `logger.error` is printing error in console and also sending the same info to `log.html`, but not `debug_record.txt`

It looks like logger is adding info to `debug_record.txt `only in the places where logger is used inside the testcase (i.e while the testcase running) and if used by Resource of a suite, it is not adding the info to `debug_record.txt`.

How can I rectify this issue ?

Re-post of https://stackoverflow.com/questions/55036759/robot-framework-logger-not-adding-info-to-debugfile-if-used-inside-resource-file

[S_SUITE.zip](https://github.com/robotframework/robotframework/files/2939831/S_SUITE.zip)

**Comment by pekkaklarck** [comment]
Normal log messages not going to log or possible debug file is by design and [explained in the User Guide](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#logging-during-library-initialization). Warnings and errors occurring during imports not going to the debug file is a bit strange and that could be changed. If you consider that important, please submit a new issue about that.
