### ISSUE TITLE
Exit if specific test case is failed

### ISSUE THREAD

**Issue by nefethael** [robotframework/robotframework#3113]
Hi,

I wish I could define some fatal tests that stops suite execution. For now, I run robot with `-X -c fatal` and I tag some tests with `[Tags] | fatal`. It is ok, but when another test without critical tag fails, suite status stays at `PASSED` status instead of `FAILED`. 

Is it possible to achieve this behaviour with current RFW or should we add a --exitonfatal and --fatal for this purpose?

**Comment by nefethael** [comment]
Maybe what I want could be done without exitonfailure, by calling `| Run Keyword If Test Failed | Fatal Error` in test teardown?

**Comment by sebastianciupinski** [comment]
Maybe **[Fatal Error](http://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Fatal%20Error)** keyword is what you need?

**Comment by pekkaklarck** [comment]
I agree `Fatal Error` ought to be enough to handle cases like this. You could use something like this with tests you want to stop the whole execution:

```robot
[Teardown]    Run Keyword If Test Failed    Fatal Error    Some message
```

**Comment by pekkaklarck** [comment]
Notice also that questions are best sent to support forums such as Slack or robotframework-users mailing list. This issue tracker is for bug reports and concrete enhancement requests. You may get answers to questions as well, but on the aforementioned forums you are likely to get them a lot faster.

**Comment by nefethael** [comment]
@pekkaklarck That's indeed with "Fatal Error" KW I finally manage to do what i wanted, so closing is ok for me. Thanks for pointing me RFW forums/ML I didn't know about.
