### ISSUE TITLE
Combine Tags in Robot Files

### ISSUE THREAD

**Issue by gitCWS** [robotframework/robotframework#3114]
Is it possible in robot files to need several tags, to run a test case?

Similar to calling from console with option "-i tag1ANDtag2".

Example:
```robot
*** Test Cases ***
Test 1
    [Tags]    tag1
    do something...
Test 2
    [Tags]    tag2
    do something....
Test 3
    [Tags]    tag1ANDtag2
    do something....
```
I would like to run all thee tests with including the tags "tag1" and "tag2" (e.g. with `robot -i tag1 -i tag2 ./test_suite.robot`\
If I specify only the tag "tag1", then only the first test should be executed. (e.g. with `robot -i tag1 ./test_suite.robot`)

Is there any solution for me?

**Comment by pekkaklarck** [comment]
I'm not certain did I understand what you try to do, but if you just want to give multiple tags to a single tests, use

    [Tags]    first    second

Anyway, this tracker is for bug reports and concrete enhancement requests. Questions are best asked on dedicated support forums such as robotframework-users mailing list or on our Slack community.

**Comment by trogdor259** [comment]
doing `-i tag1ANDtag2` will only run tests with BOTH `tag1` AND `tag2` set. What you want s to use the `OR` operator. `-i tag1ORtag2` This will run any test with either the `tag1` or that `tag2` tags set. You can further exclude tags by either adding more tags to the `-i` argument with  `NOT` or use the `-e` argument to exclude any tags listed just like `-i` includes tags. See the [documentation](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#tag-patterns) for more information.
