### ISSUE TITLE
Looping through dictionary keys and values

### ISSUE THREAD

**Issue by Bowbear** [robotframework/robotframework#3119]
Hi,
it would be great if it's possible to loop through a dictionary getting keys and values like
:FOR ${key} ${value} IN ${dictionary}

This would easy the work immense!

Thanks a lot in advance!
Günther

**Comment by pekkaklarck** [comment]
Yeah, it would be convenient to be able to iterate over dictionary keys and values like this. A natural syntax for that would be:

```
FOR    ${key}    ${value}    IN    &{dictionary}
    # ...
END
```

I'm too busy with the new parser implementation to be able to look at this in the near future. Anyone else interested to implement it? Shouldn't be overly complicated and I can help if needed.

**Comment by pekkaklarck** [comment]
Notice also that you can already now loop over dictionary keys like:

```
FOR    ${key}    IN    @{dictionary}
    # ...
END
```

**Comment by poojatrivedi7** [comment]
Hi @pekkaklarck 

I am a new contributor and would like to take up this task. In the current Robot Framework implementation (3.1.2)

For the dictionary : {'FirstName': 'John', 'LastName': 'Smith'}

:FOR ${var1} ${var2} IN @{dictionary} 
\     Log   ${var1} ${var2} 

Above statement will iterate over keys of the dictionary and output (i.e FirstName, LastName).
With respect to the output of this issue; expected result of the above is expected to be Key Value (i.e FirstName, John) 

I wanted to know, is this implementation expected to override the current implementation? If not; then how is it to be decided which of the above two needs to be used?

**Comment by yo-ga** [comment]
@pekkaklarck  I think this issue is duplicated with #3485 and the feature has already existed in 3.2 version.

**Comment by pekkaklarck** [comment]
Good catch! This feature is already implemented. Apparently nobody remembered this issue when #3485 was submitted.

**Comment by karthik5959-hub** [comment]
Any update on this use of the Key and value from python dict?
