### ISSUE TITLE
Braking up by selecting element (check box)

### ISSUE THREAD

**Issue by Bowbear** [robotframework/robotframework#3120]
Hi,

I'm using RF with firefox. On the website I'm testing I select/unselect a checkbox. In the beginning of the project it worked fine. Now, I can see that RF is selecting it but brake up with the error:
ElementNotInteractableException: Message: Element <element> could not be scrolled into view. It is also curios because there is no need for scrolling.
Colleagues in an other project had the same issue but solved it with "set window size"(?). This does not work for me, unfortunately. 
This happend on RF 3.0.4 and SeleniumLibrary 3.2.0

**Comment by pekkaklarck** [comment]
This issue tracker is for bug reports and concrete enhancement requests related to Robot Framework itself. Please submit SeleniumLibrary issues to its tracker. Questions like this are best sent to support forums listed at http://robotframework.org.
