### ISSUE TITLE
Avoid using deprecated PyYAML API

### ISSUE THREAD

**Issue by DirkRichter** [robotframework/robotframework#3122]
Robotframework 3.1.1 works fine with PyYaml **3.13** on Python 3.7.2 Win64. Now switching to   new version of PyYaml **5.1**, deprecated YAMLLoadWarning is reported:

`robot\variables\filesetter.py:77: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  variables = yaml.load(stream)`

**Comment by chaussen** [comment]
same issue happens to python2.7 pyyaml and robot
