### ISSUE TITLE
How to mock date in robotframework?

### ISSUE THREAD

**Issue by sgrillon14** [robotframework/robotframework#3127]
My robotframework test need silulate today is a friday and read a text (friday in my case) on my application. After this mock I use `Get Time` and `Textfield Value Should Be`

My angular target application use:

```
import * as moment from 'moment';
today = moment();
```

**Comment by trogdor259** [comment]
This isn't the place to ask for assistance as GitHub is meant for reporting bugs. You'd be better off asking in the slack channel. 

As for your question, try using the [DateTime](http://robotframework.org/robotframework/latest/libraries/DateTime.html) library.

**Comment by sgrillon14** [comment]
I want simulate that my integration test takes place on a Friday even if it is a Tuesday for example. My app does not have the same behavior on Fridays. to test this case you have to run the test on a Friday. As I want to test every case every day, I need to simulate that my integration test takes place on a Friday even if we are another day.

**Comment by pekkaklarck** [comment]
@trogdor259 is right, we use this issue tracker only for bug reports and enhancement requests. Questions like mocking a data in certain application belong to mailing lists, Slack, or other such support forums listed at https://robotframework.org/#support.
