### ISSUE TITLE
add support for python statement

### ISSUE THREAD

**Issue by jcyrss** [robotframework/robotframework#3128]
robotframework is great in many aspects. 

But IMO the biggest defect is  the test cases syntax it created.  
Original intent is to make writting test cases easier, but actually it makes it harder.

For example, we need to validate a variable equal to a long string like this

```py
the submited orders are:
     Roy        20190314    $34
     Patrick   20190510    $23
```

It's not convinient to use  RF syntax to check it.

Why not just use python syntax?? It will make writing test cases  much easier.

**Comment by pekkaklarck** [comment]
Could you clarify your proposal? Also, if Python syntax works better for you, there's nothing wrong using Python directly without using Robot Framework.

**Comment by jcyrss** [comment]
There are test framework like pytest which we could write test cases in python directly.
But I think RF has its advantages over pytest. For example, I think the way RF organize test suite and test cases is more intuitive, and the way RF conduct setup teardown is also more intuitive. 

It's perfect for me (maybe also a lot of RF users)  that RF could support writing test cases in python directly.

I know it's a big work for the developer team, and almost impossible for you guys to accept ti. But really a lot of engineers around me give up RF just for its test cases syntax.

I submit it also because I want to check how many people have the same thought like me.

**Comment by pekkaklarck** [comment]
Do you have concrete examples how this syntax should work?

**Comment by jcyrss** [comment]
My quick thought it as the following.

Like, we have a test suite file written in RF like the following,

```robotframework
*** Settings ***
Library    pylib.SchoolClassLib
Variables   cfg.py

*** Test Cases ***
addclass1 - tc000001
    [Setup]    add_school_class    ${g_grade_7_id}     classA     60   3\
    
    ${ret1}=    add school class    ${g_grade_7_id}     1班     60
    should be true     $ret1['retcode']==0

    ${ret2}=    list school class    ${g_grade_7_id}
    ${fc}=   evaluate   $ret2['retlist'][0]
    should be true    $fc['id']==$ret1['id']
    should be true    $fc['invitecode']==$ret1['invitecode']

    [Teardown]    delete_school_class   &{ret1}[id]
```

if we also could write it in python like this

```py
from pylib.SchoolClassLib import  *
from cfg import *
from robot.robotpython import *

class testcase(RFSuite):
    name = 'addclass1 - tc000001'
    def setup(self):
        add_school_class(g_grade_7_id,'classA',60,3)

    def test_steps(self):
        ret1 = add_school_class(g_grade_7_id, 'classA', 60, 3)
        self.addid = ret1['id']
        RFAssert(ret1['retcode']==0)

        ret2 = list_school_class(g_grade_7_id)
        fc = ret2['retlist'][0]
        RFAssert(fc['id']==ret1['id'])
        RFAssert(fc['invitecode']==ret1['invitecode'])

    def teardown(self):
        delete_school_class(self.addid)
```

The good points are:

1.  much easier for pythoneer to write it without need to learn RF syntax  like list/dictionary variable,  variables pass in are string not number, string with more than 2 space need to escape, long string spanning multiple line not easy to define, etc.

2.  we could write multiple line python code in setup and teardown easily

3.  loop and conditional state are much more strong than RF syntax.

Overall, that is again, we have the power of python. 

Why bother we create another one syntax which is much week than it ?

Someone had told me RF syntax is more close to human language for newcomer. But belive me, that's when the test case is simple itself.  If it is simple, written in python is also very simple and easy to understand. 

If it's complex, written in python is much easier than in RF.

**Comment by pekkaklarck** [comment]
Your Robot test is too low level and complex. Check out How To Write Good Test Cases guidelines and slides from robotframework.org for some ideas how to improve it. In general you should move more of the logic to a library implemented in Python and just have the test description in Robot syntax. If you want to discuss this more, that's possible in robotframework-users, Slack, or elsewhere. This tracker is for bug reports and concrete enhancements and not for general discussion.

If you want to avoid Robot syntax altogether you are obviously free to do that as well. Just write your tests in Python or whatever language works for you. Or is your point that you'd like to write tests in Python but get Robot's logs and reports? That could be useful sometimes, but it would need someone else than me to design and implement it. At least in the beginning it should also live as a separate project to avoid tying its development to Robot's releases and pretty tight backwards compatibility requirements.

**Comment by jcyrss** [comment]
Thanks， what I like Robotframework are the way it organizing test suite and test case, the way it setup and teardown, and the logs and report.  

As you suggested, I could move all the test cases logic to python code, and make RF test cases just a entry point to them. But still I have legacy test cases to maintain, they are WEB API test cases written in RF syntax, with many complex data strucure to manipulate. That very painful for me to maintain.

Anyway, thanks you for creating RF, it did help us  a lot.

**Comment by pekkaklarck** [comment]
While maintaining those tests, move more and more logic to your Python libraries. Not so that the test on Robot side would look like

```robotframework
*** Test Cases ***
Example
    Run some test
```

but so that it looks like

```robotframework
*** Test Cases ***
Example
    Do something
    Do something else
    Result should be something
```
