### ISSUE TITLE
ouput.xml corrupted in combination with pyscreenshot and output > 8kb

### ISSUE THREAD

**Issue by groegerj** [robotframework/robotframework#3129]
In certain situations, output.xml is getting corrupted.
I have created a simple example that demonstrates the problem.
My system is Debian 10 "buster" with Python 3.7.3rc1, and using
Robot Framework 3.1.1.

To reproduce: Unzip the files to one directory and invoke the
test run via the provided script ./runrobot.sh
(after fixing the robot framework path),
which just calls robot/run.py with suitable parameter.

The corrupted output.xml is provided in the zip file
under the name output_bad.xml.
One can see that the first line

xml version="1.0" encoding="UTF-8"

exists twice in that file (in other tests, I got four or more
repetitions).

Prerequisites for that problem to occur:
* output should be larger than roughly 8kb
* the Python pyscreenshot module has been imported and used
  (see alib.py in the example provided).

I suppose the problem might be related to some bug related to
to Python's internal buffer for files.
Analysing the robot code, I came to the following observation.
The problem does NOT occur if you modify robot at one of two
places (see output_good.xml):
* In robot/utils/markupwriters.py, modify the method _write
  such as to add a flush at the end:

    def _write(self, text, newline=False):
        self.output.write(text)
        if newline:
            self.output.write('\n')
        self.output.flush()

* second possibility: At the place where output.xml is opened for
  writing (I have forgotten where exactly), use a buffering=large_enough
  argument.

In both cases, the problem does not occur. The second solution is
not good since, usually, the output size is not known in advance.

The first solution should not be necessary as I would expect the
buffering stuff to be handled internally in a correct way.

Can you reproduce the problem?

[test.zip](https://github.com/robotframework/robotframework/files/3002869/test.zip)

**Comment by pekkaklarck** [comment]
I don't have time to test this right now but possibly later today. Does this happen for you every time or only sporadically? Have you tested with other Python versions?

Adding `flush()` would be a horrible fix/workaround because it would make writing output.xml and thus the whole execution I/O bound.

**Comment by groegerj** [comment]
I did not really mean to suggest flush() as a fix...
this was just to provide you some hint on where the problem is rooted.
It might as well be some buffering problem in CPython.

And yes, this happens _every_time_.
I will test it with other Python versions, probably later this week.

**Comment by pekkaklarck** [comment]
Do you have any new info related to this strange issue?

**Comment by groegerj** [comment]
Sorry no, I have been busy with some other project...

**Comment by pekkaklarck** [comment]
No new info in close to two years. Closing.
