### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe4 in position 705: invalid continuation byte

### ISSUE THREAD

**Issue by gargoura** [robotframework/robotframework#3130]
Hi, 

I am facing in error everytime I run a test case. I am using:
[INFO]: Found Robot Framework version 3.0.4 from 'C:\Python27\lib\site-packages\robot'.
[INFO]: Started RIDE 1.5.2.1 using python version 2.7.14 with wx version 2.8.12.1 in win32.

 Below a screenschot of cmd:

![UnicodeError](https://user-images.githubusercontent.com/8859685/54984588-7017f480-4faf-11e9-9ab6-e5332d4f65b9.png)

Any help to correct this encoding problem?

**Comment by pekkaklarck** [comment]
RIDE has it's own issue tracker. Please submit this issue there.
