### ISSUE TITLE
Manipulating original dictionary in a keyword when passing it as an argument

### ISSUE THREAD

**Issue by rickvargas** [robotframework/robotframework#3138]
I checked a functionality few strange to me and I wanna confirm if it is right or not.

I did a test creating a _dictionary_, the _test_ calls a _keyword_ passing this dictionary as argument and consequently the keyword receives the dictionary in a _variable_ in [Arguments]. **When I remove keys from the dictionary in the keyword, it changes the dictionary in the test.**

My questions are:
Is it supposed to occurs? The dictionary when an argument of a keyword should or should not be a copy from the "first" variable? If not, are they supposed to be a pointer to the "first" variable?

Below follows my test:
```
*** Settings ***
Library    Collections

*** Test Cases ***
Test example
    ${test}=    Create Dictionary    test1=value1    test2=value2    test3=value3
    Example:Remove Dictionary Keys    ${test}

*** Keywords ***
Example:Remove Dictionary Keys
    [Arguments]    ${dictionary}
    ${keys}=    Get Dictionary Keys    ${dictionary}
    Remove From Dictionary    ${dictionary}    @{keys}
```

**Comment by aaltat** [comment]
Yes, what you experience is correct. The answer lies in Python and how it handles objects and is the object immutable or mutable. This behaviour is explained example in this blog post https://medium.com/@meghamohan/mutable-and-immutable-side-of-python-c2145cf72747

**Comment by pekkaklarck** [comment]
Tatu is right, this is how mutability works in general. We could have decided to make copies of mutable objects like dicts and lists when they are used as arguments, but that would have been some extra work, detecting all mutable objects would have been hard, and, most importantly, there are various benefits in being able to use mutable objects like this. If you don't want this to happen with your dict or list, you need to make a copy of it first. See the Collections library for related keywords.
