### ISSUE TITLE
Exception if run test on chrome using remote webdriver with desired_capabilities

### ISSUE THREAD

**Issue by phamtantho** [robotframework/robotframework#3139]
Hi,

I did some tests on browser chrome using remote webdriver with desired_capabilities. However, it always through exception:
`Starting test: Demo.Testsuite1.Test1
20190401 18:10:56.961 : INFO : Opening browser 'chrome' to base url 'https://github.com/nokia/RED' through remote server at 'http://xx.xxx.xxx.xx:4444/wd/hub'.
20190401 18:10:57.133 : INFO : Cannot capture screenshot because no browser is open.
20190401 18:10:57.144 : FAIL : SessionNotCreatedException: Message: Unable to create session from {
  "desiredCapabilities": {
    "server:CONFIG_UUID": "4a579b2d-cc49-464f-9354-2babea3630e2",
    "platform": "WINDOWS"
  },
  "capabilities": {
    "firstMatch": [
      {
        "platformName": "windows",
        "server:CONFIG_UUID": "4a579b2d-cc49-464f-9354-2babea3630e2"
      }
    ]
  }
}
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'PC', ip: 'xx.xxx.xxx.xx', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_171'
Driver info: driver.version: unknown
Stacktrace:
    at org.openqa.selenium.remote.server.NewSessionPipeline.lambda$null$4 (NewSessionPipeline.java:76)
    at java.util.Optional.orElseThrow (Optional.java:290)
    at org.openqa.selenium.remote.server.NewSessionPipeline.lambda$createNewSession$5 (NewSessionPipeline.java:75)
    at java.util.Optional.orElseGet (Optional.java:267)
    at org.openqa.selenium.remote.server.NewSessionPipeline.createNewSession (NewSessionPipeline.java:73)
    at org.openqa.selenium.remote.server.commandhandler.BeginSession.execute (BeginSession.java:65)
    at org.openqa.selenium.remote.server.WebDriverServlet.lambda$handle$0 (WebDriverServlet.java:235)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
    at java.lang.Thread.run (Thread.java:748)
Ending test: Demo.Testsuite1.Test1`

**Setup:**
PC1: Start selenium hub and node (this node for local chrome test)
PC2: Start selenium node

Both node & hub: Use standalone selenium-server-standalone-3.141.59.jar
On node: Chrome version 73, use chromedriver for chrome v73 (https://chromedriver.storage.googleapis.com/index.html?path=73.0.3683.68/)

Robotframework version: 3.1.1

**This is my test:**
`*** Settings ***
Library    SeleniumLibrary
Suite Teardown    Close Browser

*** Variables ***
${desired caps} =     Create Dictionary    platform:WINDOWS
${hub_url} =     http://xx.xxx.xxx.xx:4444/wd/hub
*** Test Cases ***

##Original test case
Test1
    Open Browser    https://github.com/nokia/RED    browser=chrome    remote_url=${hub_url}    desired_capabilities=${desired caps}

##Test with other browsers: firefox, safari, edge
Test2
    Open Browser    https://github.com/nokia/RED    browser=firefox    remote_url=${hub_url}    desired_capabilities=${desired caps}

##Remove desired_cap
Test3
    Open Browser    https://github.com/nokia/RED    browser=chrome    remote_url=${hub_url}

##Test chrome locally
Test4
    Open Browser    https://github.com/nokia/RED    browser=chrome      desired_capabilities=${desired caps}`

**Test results:**
Test 1: FAIL --> exception SessionNotCreatedException: Message: Unable to create session from
Test 2: PASS. Also pass with safari, edge
Test 3: PASS
Test 4: PASS

**Summary: This issue only happens on chrome and with remote driver. The test will PASS if run locally or using other browsers.**

I've searched this issue whole day but not found any clue. Please help to check if this issue robot framework issue, chrome issue or my setup issue. Thanks!

**Comment by aaltat** [comment]
This issue tracker is reserved only for reporting bugs or submitting enhancement proposal for Robot Framework core. You are requesting support for SeleniumLibrary and support for SeleniumLibrary is explained in here https://github.com/robotframework/SeleniumLibrary/blob/master/README.rst#support Because of the above, I am closing this issue.

**Comment by phamtantho** [comment]
Hi @aaltat,

Yes, it's likely an selenium/selenium grid issue. I found a workaround by adding 1 more desired_cap: browserName:chrome. Therefore, the desired_cap should be `desired_capabilities=platform:WINDOWS,browserName:chrome`
Hope it helps others who have the same issue.
