### ISSUE TITLE
Get Length on empty JSON array returns 1, expected 0

### ISSUE THREAD

**Issue by ppazos** [robotframework/robotframework#3141]
# Test example:

```
** Settings ***
Library    REST    http://cabolabs.com

*** test cases ***
test length
  REST.GET   /test.json
  Output   $

  Array   $.empty_array
  Set Test Variable    @{arr}    $.empty_array
  Output    @{arr}

  ${type}=    evaluate    type(${arr}).__name__
  Output    ${type}

  ${sz}=    Get Length    ${arr}
  Output    ${sz}
```

The first output is the complete response, second is [], third is "list" and fourth is 1.

If I change this:

`  ${sz}=    Get Length    ${arr}`

To this:

`  ${sz}=    Get Length    @{arr}`

The size is 13 :-/

Not sure what is going on.

# env

RF 3.1.1 Python 3.6.7 on Linux.

**Comment by pekkaklarck** [comment]
Try adding

   Log    ${arr}

and you ought to see what's wrong.

**Comment by ppazos** [comment]
Did you tried the test? 

I'm a doing output and don't know what the issue is.

**Comment by pekkaklarck** [comment]
`Output` is from REST lib and outputs the part of the response that matches the locator you give it. `Log` shows the actual value given to it.

**Comment by ppazos** [comment]
![Screenshot_2019-04-07_22-38-00](https://user-images.githubusercontent.com/1278556/55693508-d9bbd980-5985-11e9-986a-08ccca0d481a.png)

**Comment by pekkaklarck** [comment]
You have created a list `@{arr}` with a single string `$.empty_array` as its content. When you do
```
Get Length    ${arr}
```
you thus naturally get value 1. When you do
```
Get Length    @{arr}
```
it's same as
```
Get Length    $.empty_array
```
and naturally you get 13 (the length of string `$.empty_array`). In other works, `Get Length` works as expected.

What you do when you pass `${arr}` or `@{arr}` to some other keyword depends on that keyword.
