### ISSUE TITLE
Log file is not created if output file is disabled in robotframework 3.1.1

### ISSUE THREAD

**Issue by shufenl** [robotframework/robotframework#3142]
In robotframework userguide, it says output file can be disabled separately above Robot Framework 2.8, by using '--output NONE'.
But now log file is also not created if I use '--output NONE' to disable output file, is there any solutions to solve the problem?
I just don't want to generate output file because it's so large.

**Comment by pekkaklarck** [comment]
There's no solution. Creating the log file requires output file because not enough information is stored in memory to create it. Report can be created also without it. This ought to be explained in the User Guide. If not, let us know where exactly you read the info and we can try enhancing it.

**Comment by shufenl** [comment]
Thanks for your prompt reply!
I get the info from below address, maybe it's not official...
https://robotframework-userguide-cn.readthedocs.io/zh_CN/latest/ExecutingTestCases/OutputFiles.html?highlight=output#output-file

**Comment by pekkaklarck** [comment]
That's not an official resource but it's certainly highly appreciated. This is what the official User Guide says: http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#output-file

**Comment by shufenl** [comment]
OK, thanks a lot.
