### ISSUE TITLE
RobotFramework TeamCity integration with Java desktop application issue 

### ISSUE THREAD

**Issue by karusha** [robotframework/robotframework#3143]
Dear RobotFramework gurus,

We have desktop java application and running Robot tests as a standalone jar using standard RF libraries and RemoteSwing libraries via IntelliJ Idea RunConfiguration. Locally all works fine.

But when I'm trying to run the same tests via TeamCity as IntelliJ Idea project and submitted RunConfigurations, in TeamCity some of the tests look like successfully executed, but I do not see that the application has been started on this windows server and additionally all screenshot which have been done during test execution are black.

Did someone have similar experience in running RF test this way?
Any ideas about it?

Many thanks in advance.

**Comment by pekkaklarck** [comment]
Sounds like an issue with the virtual display. Definitely not a bug in Robot Framework itself.
