### ISSUE TITLE
React issue - Cannot recognize locators on React panels

### ISSUE THREAD

**Issue by jaxjeanne** [robotframework/robotframework#3144]
The base of our website uses angular but on top of that we have implemented React panels for most of our new features. We cannot get robotframework to interact with any of the elements/ locators on these panels. Are there any suggestions for how to work around this? Or anything planned for improvements around React + robotframework?

**Comment by sebastianciupinski** [comment]
I do not think anyone can help without any code snippet...

**Comment by pekkaklarck** [comment]
This issue tracker is for bug reports and enhancement requests related to Robot Framework itself. Issues related to external libraries and tools belong to their trackers and questions are typically better asked on dedicated support forums listed at http://robotframework.org.
