### ISSUE TITLE
Add robot command used to run script into HTML log

### ISSUE THREAD

**Issue by tysonite** [robotframework/robotframework#3146]
It would be nice to have a complete robot command used to run test script in a HTML log file. This will simplify understanding of how script was run when sharing test results.

**Comment by pekkaklarck** [comment]
A problem is that Robot doesn't know how exactly it was called. Nothing done in shell is visible to Python code making it very likely that the what would be shown in log wouldn't match what actually was used. Showing such information by default wouldn't be a good idea and having an option to show something doesn't sound like a good idea either.

 If you want to add info like this to logs, you can do it yourself by using the `--metadata` option.

**Comment by tysonite** [comment]
Thanks for pointing to `--metadata` option.

However, I didn't get your point that nothing is visible to Python code. For example, `robot.bat` file is just a wrapper around Python function:
```
@echo off
python -m robot.run %*
```
So I suppose command lines options are passed as is into Python code. If options are passed into Python code as I see, they could be logged into HTML log. Do I miss something?

**Comment by pekkaklarck** [comment]
Most of the time teams use a start-up script that runs tests with possible options. If you, for example, run tests like `tests/run.sh --option value` you'd like *that* to be shown as the execution command. Also, I doubt we could separate calls like `robot args`, `python -m robot args`, `python2 -m robot args`, etc. from each others to construct the exact original call to Python.

**Comment by yahman72** [comment]
my two cents worth: 
first of all - this would be indeed useful information in the report/log.

IMHO The command itself (`run.sh args`, `robot args`, `python -m robot args` etc.) is not that important. 

More important are the `args` because they could have major impact of the test results e.g. when you run a suite in different environments and you define the environment to use from command line with variable override or variable files.

**Comment by pekkaklarck** [comment]
I would say it depends on the context. If your start-up script always sets certain command line options, seeing them in log probably isn't that useful. Also, if you have a start-up script, making whatever information is relevant to you visible by using `--metadata` is very easy.

Although I don't like the idea to automatically show the execution command, having some way to make configuration visible could be nice.  There are now and then also requests about making settings available at run time, and perhaps these two needs could be handled together. One possibility would be making settings available as a built-in variable like `&{CONFIG}` supporting also access like `${CONFIG.variables}`. If the config object has a nice string representation, it could be easily logged or used as a value to `Metadata` setting. Using something like `--metadata Config:${CONFIG}` would also be handy, but that would require variables from command line to be able to refer to other variables. Definitely doable but requires a separate issue. If you consider something like this to be worth the effort, please submit issue(s). If you are also interested to provide a pull request, we could have these in already in RF 3.2.
