### ISSUE TITLE
Error in file .... Unrecognized table header

### ISSUE THREAD

**Issue by Kocarik** [robotframework/robotframework#3149]
Hello,

Here is my test, where i read only .html file and i get this error in log

`*** Settings ***
Library  OperatingSystem
Library  String

*** Test Cases ***
Connect_To_AmazonS3
    remove file  ./unziped/testik.html
    unzipAndReadAndWriteFile  ./myLocalfromDowloaded.html.gz  ./unziped/testik.html
    ${content} =  get file  ./unziped/testik.html
    log to console  ${content}
    should contain  ${content}  Anti-1-AGP acyltransferase 4 antibody`

Here is the error what i get:
Error in file 'X:\abavavavav\eafaefaefaef\unziped\testik.html': Unrecognized table header 'Application'. Available headers for data: 'Setting(s)', 'Variable(s)', 'Test Case(s)', 'Task(s)' and 'Keyword(s)'. Use 'Comment(s)' to embedded additional data.

![Capture](https://user-images.githubusercontent.com/15687687/55871054-2bcd4c80-5b8a-11e9-9dce-df380848400d.PNG)

And some code from 2005 year from nokia ...
in https://github.com/robotframework/robotframework/blob/master/src/robot/parsing/model.py like Unrecognized table header

**Comment by pekkaklarck** [comment]
Earlier unrecognized tables in test data files were silently ignored, but that was changed in RF 3.1 as explained in #2860. You need to find the file that uses `Application` header and change it. Notice also that HTML test data is deprecated and won't be supported in RF 3.2 anymore. You should switch to plain text format.

**Comment by Kocarik** [comment]
@pekkaklarck I have this in my html file:
<table class="table">
      <thead>
        <tr>
          **<th class="name">Application</th>**
          <th class="value value1--addon">Abreviews</th>

**Comment by pekkaklarck** [comment]
That's considered a table header by Robot. If that's not a test case file, use `--extension` setting to limit what files are parsed.
