### ISSUE TITLE
Log test cases in HTML log even if they were excluded from run

### ISSUE THREAD

**Issue by tysonite** [robotframework/robotframework#3153]
With help of `--include` and `--exclude` options test cases can be either run or not. The final HTML log contains only matched test cases and do not show test cases that were never run.

#2087 has a long story about `SKIP` status and I am not atcually sure if my suggestion overlaps with it or not. However, I would like to have a command line option to log all test cases in a suite(s) including test cases that were not intended to run. Might be they may have `SKIP` status.

The general idea is to observe logs/reports in a complex environments / setups with evidence that some test cases were not missed by, for example, any kind of mistake.

But may be I miss something and similar functionality is already present.

**Comment by pekkaklarck** [comment]
This is would be of the use cases of the SKIP status. If/when it is implemented, I expect there to be an option like `--skip` that works like `--exclude` but matching tests are shown in log/report as skipped. This is already covered by #2087.
