### ISSUE TITLE
suite.tests.create("my_test", timeout="1") does not set timeout

### ISSUE THREAD

**Issue by manosnoam** [robotframework/robotframework#3158]
At first I tried: 
`suite.tests.create("my_test", timeout=1)`

This has 

> TypeError: type object argument after * must be an iterable, not int

So I tried:
`suite.tests.create("my_test", timeout="1") `
Which I assume sets: `testCase.timeout.value = 1`
I guess it should have set it as 1 minute timeout, but I'm not sure.

Although, it has no effect, and when the test runs - it has no timeout at all.

**Comment by pekkaklarck** [comment]
I wouldn't be surprised if this particular API wouldn't work that well. Could you provide a concrete but as simple as possible example I could try myself?

**Comment by manosnoam** [comment]
I think I undrstand why the timeout doesn't work - since timeout is relevany only for the keyward function, but not for the init() function of my keyword class. For example:

```
suite = TestSuiteBuilder().build('test_suite.robot')
suite.resource.imports.library('OpenshiftClient.py'))
test = suite.tests.create('Test 1', timeout='1')
test.keywords.create('connect_to_ocp')
result = suite.run()
```

**OpenshiftClient.py** 

```
import yaml
from kubernetes import client, config
from openshift.dynamic import DynamicClient

class OpenshiftClient():
    """ class for OCP Client """
    ROBOT_LIBRARY_SCOPE = 'GLOBAL'
    
    def __init__(self):
        k8s_client = config.new_client_from_config()
        dyn_client = DynamicClient(k8s_client)
        
        v1_services = dyn_client.resources.get(api_version='v1', kind='Service')
        
        service = """
        kind: Service
        apiVersion: v1
        metadata:
          name: my-service
        spec:
          selector:
            app: MyApp
        ports:
          - protocol: TCP
            port: 8080
            targetPort: 9376
        """
      
        service_data = yaml.load(service)
        resp = v1_services.create(body=service_data, namespace='default')
              
    def connect_to_ocp(self):
        # resp is a ResourceInstance object
        print(resp.metadata)
```

**Execution hangs on connection attempts, with no timeout:**

> \#\#\#  Running Test Suite: OCP_TC_1 (nmanos.tlv.csb)  \#\#\#
>  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f00f4bcae10>: 
>  Failed to establish a new connection: [Errno 110] Connection timed out',)': /version
>  
>  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f00f4bcae10>: 
>  Failed to establish a new connection: [Errno 110] Connection timed out',)': /version
> 
>  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f00f4bcd550>: 
>  Failed to establish a new connection: [Errno 110] Connection timed out',)': /version
> 
>  ...

Perhaps the timeout should also cover the class init() ?

**Comment by pekkaklarck** [comment]
Could you create a simple example I could try myself without a need to install anything extra? See http://sscce.org for details.

**Comment by pekkaklarck** [comment]
If the issue is that timeouts don't affect library `__init__`, then it has nothing to do with using API to set it. That is certainly true and changing that would be a very big task and, in my opinion, not worth the effort.

**Comment by manosnoam** [comment]
Thanks for quick response!

The cause is in the `__init__(self)`  of the keyword library (in my example: OpenshiftClient.py).
To reproduce, you can simply replace its logic with a sleep of 100 seconds, and run the test with a timeout of 10 seconds. In my environment it does not timeout on 10 seconds:

```
suite = TestSuiteBuilder().build('test_suite.robot')
suite.resource.imports.library('OpenshiftClient.py'))
test = suite.tests.create('Test 1', timeout='10')
test.keywords.create('connect_to_ocp')
result = suite.run()
```

\# OpenshiftClient.py :
```
class OpenshiftClient():
   def __init__(self):
           import time
           time.sleep(100)

   def connect_to_ocp(self):
           print ('connected')
```

To workaround, I have to move the init() logic into the keyword.
Although I prefer to leave the init() as is, since OpenshiftClient class is being used by other python frameworks as well.

**Comment by manosnoam** [comment]
Thanks for quick response!

The cause is in the `__init__(self)`  of the keyword library (in my example: OpenshiftClient.py).
To reproduce, you can simply replace its logic with a sleep of 100 seconds, and run the test with a timeout of 10 seconds. In my environment it does not timeout on 10 seconds:

```
suite = TestSuiteBuilder().build('test_suite.robot')
suite.resource.imports.library('OpenshiftClient.py'))
test = suite.tests.create('Test 1', timeout='10')
test.keywords.create('connect_to_ocp')
result = suite.run()
```

\# OpenshiftClient.py :
```
class OpenshiftClient():
   def __init__(self):
           import time
           time.sleep(100)

   def connect_to_ocp(self):
           print ('connected')
```

To workaround, I have to move the init() logic into the keyword.
Although I prefer to leave the init() as is, since OpenshiftClient class is being used by other python frameworks as well.

**Comment by pekkaklarck** [comment]
First of all, you ought to get same results with normal tests in `*.robot` files and this issue shouldn't be related to building tests programmatically.

Timeouts simply aren't enabled during library initialization. Timeouts are per test or keyword but libraries are imported already before any test is run. We should basically add a new setting to add timeouts to library inits and I don't think that's worth the effort.

Finally, if it's your code, you should write it so that it cannot hang. Timeouts are the last resort when using libraries you cannot easily modify.

**Comment by pekkaklarck** [comment]
I don't think we can make current timeouts active during normal library imports/initialization nor do I think it's worth the effort implementing some new timeouts that could be used at that point. One workaround that hasn't yet been discussed is using the `Import Library` keyword instead of the `Library` setting.
