### ISSUE TITLE
Use of evaluate function

### ISSUE THREAD

**Issue by mruds1101** [robotframework/robotframework#3161]
i am using evaluate function in robot framework to evaluate 6 * 0.05 it is giving me an output of 0.30000000000000004 , can someone explain why this is happening?

I need an output of 0.3 but not 0.30000000000000004

**Comment by thinmanj** [comment]
You need to round it, as you have a operand with 2 decimals, probably you
should round to 2 representative decimals:

In [6]: 6*.05
Out[6]: 0.30000000000000004

In [7]: round(6*.05,2)
Out[7]: 0.3

Regards

Julio

**Comment by sebastianciupinski** [comment]
This in not issue of RF but python itself - even more - floating point operations just works like this on computers

**Comment by pekkaklarck** [comment]
Yes, floating point math is hard:
https://randomascii.wordpress.com/2012/02/25/comparing-floating-point-numbers-2012-edition/

**Comment by pekkaklarck** [comment]
If you want to avoid the problems of floating point math, you can use [decimal module](https://docs.python.org/3/library/decimal.html) in Python. You probably can use it via `Evaluate`, but if you need anything more complicated I'd recommend you to create a custom library instead.
