### ISSUE TITLE
Not able to create a List Variable with Global Scope

### ISSUE THREAD

**Issue by naagf5** [robotframework/robotframework#3162]
My requirement is to have a List Variable with pre-defined strings. I should be able to use it in each test case. 
So i decided to create a Global Variable (or Suite Level ). But i couldn't because it seems there is no feasibility.
**Any one suggest a solution**?

`*** Settings ***
Documentation     iRule based on HTTP request

*** Variables ***
${MyList}=    BuiltIn.Create List    one	two	three

`

 **----- OR  ---**

`*** Settings ***
Documentation     iRule based on HTTP request
Suite Setup       createAllListVariables

*** Variables ***
${MyList} 

*** Keywords ***
Clear Em Log And Open Browser
	${MyList}     BuiltIn.Create List    one	two	three
`

**Comment by pekkaklarck** [comment]
You cannot use keywords in the variable section. Notice also that this issue tracker is for bug reports and enhancement requests. Questions are best sent to support forums listed at http://robotframework.org.
