### ISSUE TITLE
When keywords are run in threads, the order of keywords in the log is not the same as they are in the script

### ISSUE THREAD

**Issue by sudarsesh** [robotframework/robotframework#3163]
My requirement is to create a keyword that can run any other keyword in thread.
I require a bunch of keywords to be run in threads and so I have defined such a keyword.

**Script**

```robotframework
*Settings*

Library    thread_apis.py


*Test Cases*

Run multiple threads

    run kw in thread    thread-1    sample kw   hello   world  1  2
    run kw in thread    thread-2    sample kw   abc  4  5
    ${ret}=  wait for threads
    Log  ${ret}

```
**Contents of thread_apis.py**

```python

import threading
from datetime import datetime
from robot.libraries.BuiltIn import BuiltIn

thread_list = []

class thread_that_runs_kw(threading.Thread):
    def __init__(self, name, kwname, *args):
        threading.Thread.__init__(self)
        self.name = name
        self.kw = kwname
        self.args = args
        self.result = None

    def run(self):
        print("starting thread: %s" % self.name)
        self.result = BuiltIn().run_keyword(self.kw, *self.args)

def wait_for_threads():

    return_dict = {}
    for thread_obj in thread_list:
        thread_obj.join()
        return_dict[thread_obj.name] = thread_obj.result

    return return_dict

def run_kw_in_thread(thread_id, kw, *args):
    t = thread_that_runs_kw(thread_id, kw, *args)
    thread_list.append(t)
    t.start()

def sample_kw(*args, **kwargs):
    print("inside sample_kw")
    print("args = %s, kwargs = %s" %(args, kwargs))
    return str(datetime.now())
```

**LOG**
![image](https://user-images.githubusercontent.com/12856088/56742622-b751fa80-6792-11e9-8dac-fbc0bd572694.png)

My problem:

I have specified the keywords in the following order 

1.  run kw in thread    thread-1    sample kw   hello   world  1  2
        1.1    sample kw    hello   world   1   2
2.  run kw in thread    thread-2    sample kw   abc  4  5
        2.1    sample kw     abc    4   5
3.  ${ret}=  wait for threads
4.  Log  ${ret}

But I dont get the logs of the keywords in the same order as you can see from the log,

1.  run kw in thread    thread-1    sample kw   hello   world  1  2
        1.1    sample kw    hello   world   1   2
2.  run kw in thread    thread-2    sample kw   abc  4  5
3.  ${ret}=  wait for threads
        2.1    sample kw     abc    4   5
4.  Log  ${ret}

I keep hitting this issue often. Is there a way to get the keywords in the log in the same order as they are called from the script?

@pekkaklarck : Please help

**Comment by pekkaklarck** [comment]
Unfortunately Robot Framework isn't currently thread safe. We hope to get all the offending global state removed at some point, but there's no concrete plan for that and I cannot thus give promises when it could happen. You should actually consider yourself lucky that you are able to use keywords in threads in the first place, but don't be surprised if output.xml gets corrupted sometimes or there are other strange problems. 

Because running keywords in threads isn't supported in general, there's no support to get keywords executed like that into log in certain order either.

**Comment by sudarsesh** [comment]
Thanks @pekkaklarck ,

For now, I have overridden the start_keyword, end_keyword, log_message, info, debug functions of the LOGGER instance and postpone the logging to my custom created keyword "wait_for_threads". It goes like this,

{
'thread-1': [
    {'fn': <start_keyword>, 'args': [kw]},
    {'fn': <_log_message>, 'args': [msg]},
    {'fn': <_log_message>, 'args': [msg]},
    {'fn': <end_keyword>, 'args': [kw]}, 
    ],
'thread-2': [
    {'fn': <start_keyword>, 'args': [kw]},
    {'fn': <_log_message>, 'args': [msg]},
    {'fn': <_log_message>, 'args': [msg]},
    {'fn': <end_keyword>, 'args': [kw]}, 
    ]
}

And when the "wait_for_threads" is called, all these functions will be called for each thread. This however works only when there are threads created from the MainThread and not when threads are created within child threads.

**Comment by flora077** [comment]
Hello, thank you very much for your questions and answers, but there are still some confusions I want to ask you, specifically, how do you rewrite the stard_keyword, end_keyword, log_message and info functions?
