### ISSUE TITLE
cannot use "Append To List" keyword

### ISSUE THREAD

**Issue by rainydew** [robotframework/robotframework#3165]
RobotFrameWork 3.0.4 python 2.7.16, Pycharm+IntelliBot and RIDE 1.7.3.1 tested

*** Settings ***
Documentation     For demo(MultiThread Decorator)
Library           testlib/temp/testLibrary.py
Library           collections

*** Test Cases ***
TP-02 Demo Case
    [Documentation]    gitignore
    ${argLi}    create list
    :FOR    ${tno}    IN RANGE    ${4}
    \    ${arg}    parseArg    Arg${tno}
    \    Append To List    ${argLi}    ${arg}

When I ran it, I got like this (the arguements were written in Chinese, I replaced them above):
Starting Suite: Mtlab  E:\gits\cross\autotest\test\temp\mthreadFunction\mtlab.robot
Starting test: TP-02 Demo Case
20190428 22:36:27.548	TRACE	Arguments: [  ]
20190428 22:36:27.548	TRACE	Return: []
20190428 22:36:27.548	INFO	@{argLi} = [ ]
20190428 22:36:27.549	TRACE	Arguments: [ '\u7ebf\u7a0b0' ]
20190428 22:36:27.549	TRACE	Return: (('\u7ebf\u7a0b0',), {})
20190428 22:36:27.549	INFO	${arg} = ((u'\u7ebf\u7a0b0',), {})
20190428 22:36:27.551	FAIL	No keyword with name 'Append To List' found.
Ending test:  Mtlab.TP-02 Demo Case
Test Result is : FAIL

any help with this Keyword?

**Comment by bkhouri** [comment]
Python has a `collections` module, so in your robotframework test suite file, when you do

```
Library  collections
```
it's importing the standard python module `collections`.  If you want to import the roblot framework standard library `Collections`, you need to do:  (notice the lower case `c` vs the uppercase `C`)

```
Library    Collections
```

```
>>> import collections
>>> dir(collections)
['Callable', 'Container', 'Counter', 'Hashable', 'ItemsView', 'Iterable', 'Iterator', 'KeysView', 'Mapping', 'MappingView', 'MutableMapping', 'MutableSequence', 'MutableSet', 'OrderedDict', 'Sequence', 'Set', 'Sized', 'ValuesView', '__all__', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '_abcoll', '_chain', '_class_template', '_eq', '_field_template', '_get_ident', '_heapq', '_imap', '_iskeyword', '_itemgetter', '_repeat', '_repr_template', '_starmap', '_sys', 'defaultdict', 'deque', 'namedtuple']
>>> 
```

**Comment by bkhouri** [comment]
also, this issue tracker is meant for tracking defects with robotframework.  for support requests, you should reach out to the mailing list, the slack workspace, or any other means documented here: https://robotframework.org/#support
