### ISSUE TITLE
TIMEOUT exception when use Close All Browsers

### ISSUE THREAD

**Issue by wck821829906** [robotframework/robotframework#3166]
selenium version: 3.141.59
chrome driver version: 73.0.3683.68
robotframework version: 3.1.1
seleniumlibrary version: 3.2.0

Configurations:
    config selenium2grid to release node machine in 300 seconds
Steps:
    1. open browser first time at a random node machine.
    2. open browser second time at a random node machine.
    3. Close All Browsers
Expect:
    Close All Browsers successfully
Current:
    Timeout exception happens
    
![image](https://user-images.githubusercontent.com/17002975/56875382-2cfbe600-6a73-11e9-84a1-c28a1c5aafd2.png)

**Comment by aaltat** [comment]
The core Robot Framework doesn't interact with browser and therefore this is wrong project to report this kind of bugs. Also you have opened an issue in SeleniumLibrary,  https://github.com/robotframework/SeleniumLibrary/issues/1378 which is correct place to report this kind of bugs. Therefore I am closing this issue.
