### ISSUE TITLE
Set ROBOT_LIBRARY_SCOPE dynamically

### ISSUE THREAD

**Issue by manosnoam** [robotframework/robotframework#3167]
Is there a way to define ROBOT_LIBRARY_SCOPE = 'GLOBAL' when creating TestCase dynamically ?
Currently I have to define ROBOT_LIBRARY_SCOPE in the class of my library, but I'd like to have it defined during the creation of the test case.

For example, I tried this:
```
suite.resource.imports.library('MyLib.py')
# Add to Library a class property:
suite.resource.imports[-1].__class__.ROBOT_LIBRARY_SCOPE = 'GLOBAL'
setattr(suite.resource.imports[-1].__class__, 'ROBOT_LIBRARY_SCOPE', 'GLOBAL')

testCase = suite.tests.create('MyTest') 
# Add to the TestCase a class property:
setattr(testCase.__class__, 'ROBOT_LIBRARY_SCOPE', 'GLOBAL')
testCase.__class__.ROBOT_LIBRARY_SCOPE = 'GLOBAL'
```

But when running this testCase, it ignores these class properties, and it has no effect on ROBOT_LIBRARY_SCOPE.

Thanks!

**Comment by pekkaklarck** [comment]
This isn't possible. Could you explain your use case?

**Comment by manosnoam** [comment]
When dynamically creating Test suite with an external python script, It usually required to import some libraries too, and it is done in that external script. 
So it would be useful to set ROBOT_LIBRARY_SCOPE = 'GLOBAL', outside the library class definition, and avoid the need to add scope in every library, that might be imported later.
That's why it would be a nice option to set the library scope, when importing a library dynamically.

**Comment by pekkaklarck** [comment]
Could you please clarify? Also, are you interested to implement this functionality if we agree it would be a good idea?

**Comment by manosnoam** [comment]
I think to implement it, we'll need to set for example
lib._libcode.ROBOT_LIBRARY_SCOPE = 'GLOBAL'

inside _import_library of namespace.py.

But it is only possible during runtime, not during suite.resource.imports.library.

How can we import namespace, and use import_library() method, before suite.run() ?

**Comment by manosnoam** [comment]
I figure how to implement it, and I can add a new pull request. Which branch to clone, and how do I add my commit (git push) ?

**Comment by manosnoam** [comment]
Hi @pekkaklarck, did you see my PR https://github.com/robotframework/robotframework/pull/3189
?

**Comment by pekkaklarck** [comment]
Could you clarify the use case for this functionality? I don't see any reason why you'd like to set the library scope externally. Anything I can think of would be better handled by the existing library listener functionality.

**Comment by manosnoam** [comment]
See my [previous comment ](https://github.com/robotframework/robotframework/issues/3167#issuecomment-491585703) for the use-case.

I guess it will be useful mostly if it is required to import pre-existing python classes, which where not initially created for robot-framework. 
This will prevent duplicating the same file (class) just for adding ROBOT_LIBRARY_SCOPE into it, as you'll be able to import the the file as library, and add the ROBOT_LIBRARY_SCOPE from the caller (outside the library file context).

**Comment by pekkaklarck** [comment]
Sorry, that comment didn't make the use case clear for me. Notice that I [commented about that](https://github.com/robotframework/robotframework/issues/3167#issuecomment-492641276) already earlier.

You now comment that the main use case is making it easier to use Python code that hasn't been designed to be a Robot Framework library as a library. Being able to use such code as libraries is sometimes works well, but I still don't think this feature is useful. If you just need to set the scope, you can do this:

```
from some.python.code import ClassNotDesignedToBeUsedWithRobot

class MyLibrary(ClassNotDesignedToBeUsedWithRobot):
    ROBOT_LIBRARY_SCOPE = 'GLOBAL'
```

A big benefit of this approach is that you can then add features to the library that make it easier to use with Robot without the need to touch the non-Robot code. I would assume something like that is needed in most cases anyway, so the benefit of not needing to specify `ROBOT_LIBRARY_SCOPE` are very small.

Also, and very importantly, this feature would only benefit people who use the programmatic API for creating tests.

**Comment by manosnoam** [comment]
Looks like easier approach! I will check if it resolves it for me.

**Comment by pekkaklarck** [comment]
Did it work?

**Comment by yahman72** [comment]
My two cents worth - only because I was thinking about this kind of dynamic scenario yesterday. A bit different thing than this PR...

My use-case would be for libraries that maintain some sort of a state or cache something - it would be great to have the possibility reset that state/cache "automatically" with dynamic library scope (as opposed of creating explicit "reset()" KW and calling it when needed - from the test suite or library listener).
I.e. in some cases I want my library state/cache span across suites & tests (= global scope) and in other cases across tests (= suite scope).

**Comment by manosnoam** [comment]
> Did it work?

Sorry, I wasn't able to test it through, as I moved to a new project now (my python env with robot is not installed). But I don't see any reason your suggestion will not work.
However, I believe that my PR might me useful as an alternative way, if we don't want to create a new class just to inherit other class and add library scope in it, as you suggested:

```
from some.python.code import ClassNotDesignedToBeUsedWithRobot

class MyLibrary(ClassNotDesignedToBeUsedWithRobot):
    ROBOT_LIBRARY_SCOPE = 'GLOBAL'
```

I think my PR is added feature, which afaik does not hold disadvantages or risks, but just a new optional usage to set ROBOT_LIBRARY_SCOPE dynamically.

**Comment by pekkaklarck** [comment]
@yahman72 Don't library listeners already provide that functionality?

**Comment by pekkaklarck** [comment]
@manosnoam I'm still not convinced the feature is useful in the first place. It would only help if you dynamically build test suites, not when creating test cases in `*.robot` files normally, and even when dynamically creating tests explicitly using `ROBOT_LIBRARY_SCOPE` feels a lot cleaner to me.

Even if I'd consider the enhancement useful, the PR could not be merged in the current state. It doesn't have any documentation so its very unlikely that anyone would ever find this feature it and know how to use it. It doesn't have any tests either so future changes would be very likely to break it.

My decision is to not add this functionality. My [earlier comment](https://github.com/robotframework/robotframework/issues/3167#issuecomment-505813759) explains the reasoning pretty well.
