### ISSUE TITLE
Collections: `Dictionary Should Contain Item` and some other kws have confusing documentation related to `values`

### ISSUE THREAD

**Issue by romanrovensky** [robotframework/robotframework#3169]
Currently, `Dictionary Should Contain Item` and some similar keywords from `Collections` do not support `values` argument.

This `values` argument could either be added
OR
enhance the documentation. The documentation for that keyword says: "See [Lists Should Be Equal](http://robotframework.org/robotframework/latest/libraries/Collections.html#Lists%20Should%20Be%20Equal) for an explanation of `msg`." .. and by following that link to that keyword documentation, you can read the details that describe how `msg` together with `values` argument work, which can cause confusion

**Comment by pekkaklarck** [comment]
I agree this is pretty confusing. It might be a good idea to add `values` argument to all these keywords, but I don't have time for that now and it would be better to do larger cleanup to Collections at the same time. Better to just enhance the docs to avoid this kind of confusion.
