### ISSUE TITLE
Less verbose and quiet console outputs

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#317]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=317) by @pekkaklarck on 4 May 2009*

In addition to the current console output, it would be nice to have 

1) A less verbose output similar to dots shown by xUnit runners. Not sure
should we write failures at the end like these runners do or print then out
when they happen (possibly to stderr).

2) Totally quiet output. Probably still want to print out errors and
warnings in execution itself.

**Comment by pekkaklarck** [comment]
How should less verbose and quiet options be activated?

1. My current thinking is adding new `--ConsoleOutput` option that accepts `verbose` (default, same outputs as earlier), `dots` (jUnit style `...F...`) and `quiet` (only errors and warnings). How does this sound to you? I initially thought about `--ConsoleType`, but that kind of indicates we'd be telling Robot is our console a TTY or something.

2. Assuming we use `--ConsoleOutput`, are there any better ideas for the short option than `-O`?

3. I'm planning to deprecate existing `--MonitorColors`, `--MonitorWidth` and `--MonitorMarkers` in favor of `--ConsoleColors`, `--ConsoleWidth` and `--ConsoleMarkers`, respectively. The word `console` is much more explicit than `monitor` and would be consistent with `--ConsoleOutput` (which I don't want to call `--MonitorOutput`). The short options (`-C`, `-W`, `-K`) would stay the same and help ease transitioning. Would that be OK?

**Comment by pekkaklarck** [comment]
After some prototyping we ended up this kind of implementation:

- Option is just `--console`.
- Possible values are `verbose`, `dotted`, `quiet` (no output except warnings and errors) and `none` (no output whatsoever). `none` can be useful if someone wants to implement a custom output using e.g. listeners.
- Option `--dotted` is shortcut for `--console dotted` and `--quiet` for `--console quiet`. The former even has a shortcut `-.`.
- Because most common usages have separate convenience versions, `--console` itself needs no short option.

**Comment by pekkaklarck** [comment]
TODO:
- [ ] Tests.
- [ ] Documentation in User Guide.
- [ ] Rename `--monitorxx` options to `--consolexxx` and deprecate old versions.
- [ ] Investigate not reporting failures in dotted mode after stopping with Ctrl-C or signal.
- [ ] Possible animation when a keyword is executed to get some action to screen with long running tests.

**Comment by pekkaklarck** [comment]
I prototyped animation when a keyword is executed. Wasn't hard to implement but I'm not sure how much benefits it brings. Probably not something we should include into alpha 3.

**Comment by pekkaklarck** [comment]
@jussimalinen, what's the status of not reporting tests skipped at exit? At least it seems to work already. I'd prefer `x` without color, though. That's style we decided to use with `f` and not using color would avoid color bleeding to characters logged to stderr. At lest I get one `[` in in `[ WARN ]` colored with red after `x`s when I run `atest/misc/` and hit Ctrl-C.

I'm done with renaming `--monitorxxx` to `--consolexxx`, documentation, and tests. Tests could be more comprehensive, but this kind of stuff is anyway more efficiently tested manually.

**Comment by jussimalinen** [comment]
For my part, done

**Comment by pekkaklarck** [comment]
Looks good to me too! Closing.
