### ISSUE TITLE
Suggestion of "Does Something", "Are Something" and "Is Something" keywords group

### ISSUE THREAD

**Issue by sebastianciupinski** [robotframework/robotframework#3171]
Currently RF contains many "Something Should" and "Somethin Should Not" keywords like:
**Should Contain**, **Should Not Contain**, **Should be Equal As Numbers**, **Should Not Be Equal As Numbers**, etc.

Those keywords are obviously perfect for checking assertions, but are not so useful for conditional steps executions. Let's consider following example. We are going to perform some action depending on presence some item in list. Now code looks like this:

```
${is_in_list}=    Run Keyword And Return Status
...    List Should Contain Value    ${some_list}    ${desired_item}
Run Keyword If    ${is_in_list}
...    Log    Item is in list
```

This is not so complicated, but assuming that keyword **Does List Contain** exists and return bool values, the same code could be written as:

```
${is_in_list}=    Does List Contain    ${some_list}    ${desired_item}
Run Keyword If    ${is_in_list}
...    Log    Item is in list
```

This is - form my perspective - much closer to natural language and simplifies code.

Summarizing, proposed keywords might looks like:
**Does List Contain** (from Collections library)
**Does List Not Contain** (from Collections library)
**Are Equal As Numbers** (from BuiltIn library)
**Are Not Equal As Numbers** (from BuiltIn library)
**Is Element Visible** (from SeleniumLibrary)
**Is Element Not Visible** (from SeleniumLibrary)

etc.

**Comment by pekkaklarck** [comment]
This kind of keywords are sometimes useful, but creating `Is` keywords for all `Should` keywords would mean that the number of keywords increases too much. Unless they'd be added somehow dynamically, adding them would also be too much work.

The current solution to use `Run Keyword And Return Status` is technically simple but I agree its verbosity is a problem. We could try to come up with some special syntax to support this like adding `?` or some other special character to the keyword name to allow RF to change its behavior automatically. I got a feeling using something like `List Should Contain Value?` is too much magic, though.

**Comment by pekkaklarck** [comment]
We don't add new keywords but can think could we add some special syntax to turn assertions into true/false later. I'd like to see how the forthcoming IF/ELSE syntax (#3074) and possibly added inline keyword call syntax (#3187) affects the usage in general.

**Comment by sebastianciupinski** [comment]
@pekkaklarck

in meantime I created library called DoesIsLibrary, which is looking for all keywords containing `should` among imported libraries and adding `Is` `Does` keywords respectively.

I know this is not excellent piece of code, but works. I would like to utilize `load_library` listener, but seems not working for me...

You can take a look:

https://github.com/sebastianciupinski/robotframework-doesislibrary

or install with

`pip install robotframework-doesislibrary`
