### ISSUE TITLE
Run a custom keyword when Setup has failed

### ISSUE THREAD

**Issue by gloriachen** [robotframework/robotframework#3174]
Is there anyway for us to run a custom keyword if a [Suite Setup] fails?  

We have disabled Selenium2Library's feature to automatically run the Capture Screenshot keyword by setting `run_on_failure` to `Nothing` on import.  Instead, in our default test teardown we are using `Run Keyword If Test Failed` to run the `Capture Screenshot` keyword from there.

However, that isn't called if there are any Suite Setup failures, is there a way for us to check whether a Setup has failed, and if so, run a keyword?

Currently I'm implementing a workaround where in our `Suite Teardown` we check for the ${SUITE MESSAGE}, and if it includes `Suite setup failed`, we run `Capture Screenshot`, but I'm wondering if there's a more direct way of doing that without relying on having a `Suite Teardown`

**Comment by pekkaklarck** [comment]
There's no built-in support for something like this, but you could use `Run Keyword And Return Status` to run certain keyword and then run another only if the first one failed. You can do all this in your suite setup.

If you got further questions, I recommend sending them to robotframework-users mailing list or joining the discussion on our Slack. This tracker is for bug reports and enhancement requests and those actual support forums have a lot bigger audience to help you.
