### ISSUE TITLE
Suggestion for [Alias] metadata

### ISSUE THREAD

**Issue by sebastianciupinski** [robotframework/robotframework#3175]
Currently there is possibility of aliasing keywords form libraries with decorators, but there is no possibility for aliasing keywords from resources. When there are two keywords doing the same thing, wrapping is only way for aliasing them, see example:

```
Send File To Server
    [Arguments]    ${file}    ${ip}
    Implementation KW 1
    Implementation KW 2

Upload File To Server
    [Arguments]    ${file}    ${ip}
    Send File To Server    ${file}    ${ip}

Send File "${file}" To Server "${ip}"
    Send File To Server    ${file}    ${ip}

Upload File "${file}" To Server "${ip}"
    Send File To Server    ${file}    ${ip}
```

With [Alias] it could be just like this:

```
Send File To Server
    [Arguments]    ${file}    ${ip}
    [Alias]    Upload File To Server
    [Alias]    Send File "${file}" To Server "${ip}" 
    [Alias]    Upload File "${file}" To Server "${ip}"
    Implementation KW 1
    Implementation KW 2
```

**Comment by pekkaklarck** [comment]
Questions/comments:

1. How common need is this? Common enough that wrapping is a real problem?

2. We are very conservative about adding new syntax. It needs to be then supported by external tools like editors as well. There need to be really big benefits for that.

3. When using embedded arguments, you actually can already now how something like this with custom regexps. For example, this ought to work:

    ```robot
    *** Keywords ***
    ${action:(Send|Upload)} File "${file}" To Server "${ip}"
        Implementation KW 1
        Implementation KW 2 
    ```

4. In the above example, it's a bit annoying that you need to define variable `${action}` that you are not going to actually use. It would be more convenient to be able to declare that the whole name is a regexp and use name like `(Send|Upload)} File "${file}" To Server "${ip}"`. If there was a way to allow this, then same approach could be used with keywords accepting normal arguments like `(Send|Upload) File To Server`. Can we come up with simple syntax to allow this that wouldn't require changes to external tools?

**Comment by pekkaklarck** [comment]
I don't think adding new syntax to support this use case is worth the effort. Specifying the name as a regexp is something we could consider but needs its own issue.
