### ISSUE TITLE
Inline Python evaluation support using `${{expression}}` syntax

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#3179]
See #3100 for motivation and earlier discussion.

The main functionality would be evaluating Python expression inline without using the `Evaluate` keyword. It must be possible to use variables inside the expression using the `$var` syntax similarly as `Evaluate` does (#2040).

Based on a quick prototype implementation isn't overly complicated. The main thing to decide is that do we want to allow taking external modules into use somehow (`Evaluate` does that) or should we import some modules automatically (`Run Keyword If` and others import `os` and `sys`).

**Comment by pekkaklarck** [comment]
Should also support `@{{expression}}` and `&{{expression}}` variants.

**Comment by pekkaklarck** [comment]
Issue #3187 proposes adding somewhat similar inline keyword call syntax. These two features need to be designed together so that the actual syntax used with them is consistent. See #3187 for different syntax alternatives.

**Comment by pekkaklarck** [comment]
Some examples making this functionality easier to understand:

**Comment by aaltat** [comment]
`json` could be useful too.

**Comment by stdedos** [comment]
`os`, `sys`, `math`, `random`, `datetime`, `platform` (as proposed on Slack) do sound like good candidates. Perhaps there are more

Kindly add one point of reference "somewhere" (keep re-editing the issue description?), so that this discussion has a "current status" invariant somewhere, until it goes for a PR.

**Comment by pekkaklarck** [comment]
The current status is that the base functionality ought to be done. I need to review it once more and then I can commit and push it.

I still haven't made a decision about automatically included modules. At the moment there are none, but adding support for them isn't hard. Bigger question is what to include. The mentioned `os`, `sys`, `math`, `random`, `datetime`, `time`, `platform` and `json` are all good candidates, but should probably take a look at the standard library reference to see is there anything else that would be useful.

A possible problem with importing all those modules is that each import always takes some time and that can slow down execution start-up time a bit. We import most of the aforementioned modules already, though, and with them additional imports are cheap. Need to still think should these imports be done only when this new syntax is used.

Yet another question is do we want to support additional modules. It would make it possible to use standard library modules we don't import as well as custom or third party modules we cannot even automatically import. I don't know are these that important use cases, though, because you can anyway use `Evaluate` that supports custom modules or switch to using variable files or libraries instead.

If we were to support additional modules, we needed to decide the syntax. My first idea was to allow adding extra modules to the end like `${{ expression | modules }``, but that's problematic because `|` is a valid operator in Python. Could use some characters like `:`, but that needed to be done on the token level because any character can occur inside a string. Another possibility would be supporting some magic syntax like `@module` to mean that `module` needs to be imported. If we'd do that, we possibly didn't need to import any modules automatically and instead require usage like `${{@random.randint(100)}}`.

**Comment by pekkaklarck** [comment]
The commit above contains the basic implementation without any support (automatic or explicit) for additional modules. You can experiment with it by installing the latest code directly from GitHub. Feedback is appreciated!

**Comment by pekkaklarck** [comment]
`M=os,sys,random` looks strange when you see it the first time. Similar `modules=os,sys` would be more clear, and if it was the the end it would also look same as with `Evaluate` that has `modules` as an optional parameter:

```
${result} =    Evaluate    expression    modules=os, sys
Log    ${result}
# vs
Log    ${{ expression modules=os,sys }}
```

This is definitely one option, although I'm not sure is a space alone enough as a separator between the expression and `modules=`.

If you look at the commit closely, you'll notice that namespaces and additional modules supported by the new `evaluate_expression` function are already used by the `Evaluate` keyword. I copied its old functionality to the new utility (and needed to add some code to support expressions in the variables section). Tests for this functionality are pretty dense but ought to show different ways how it can be used.

**Comment by stdedos** [comment]
The reason I preferred `modules=os,sys expression` vs the `expression modules=os,sys` (or whatever separator scheme, is because parsing it would be more straightforward.

It would also look more Unix way of "chaining" multiple commands together e.g. `timeout 1m docker exec cont_id bash -s "echo hello world"`.

**Comment by pekkaklarck** [comment]
I got a new idea how we could support modules in expressions like `${{datetime.date.today()}}`. We could simply intercept the lookup for variables like `datetime` in the expression and import a module based on the name when needed. It means we wouldn't need to decide what modules to add to the evaluation namespace nor did we need to think about possible syntax to import custom modules. You could simply use `mymod.whatever` and it would just work. Because we already provide both the global and local namespace to the [eval()](https://docs.python.org/3/library/functions.html#eval) function, and because locals is a custom mapping already now, this would also be trivial to implement.

Because I implemented the support for inline Python evaluation so that also BuiltIn keywords like `Evaluate` and `Run Keyword If` use the same logic, these keywords would be enhanced at the same time. These keywords supporting all importable Python modules automatically would be handy, but there would be two side effects with the change:

1. Using `modules` with `Evaluate` wouldn't have any effect anymore. Using `Evaluate  math.pi` would work exactly like `Evaluate  math.pi  modules=math` because the `math` module would be imported automatically. Because modules that are specified with `modules` are put into the global namespace and the automatic import would need to be in the local namespace (global namespace must be an actual `dict` while the local can be a custom mapping), whatever that would be used with `modules` would be totally ignored but the expression would still be evaluated fine. Basically we should deprecate `modules` with `Evaluate`.

2. The error message with expressions using variables that do not exist would change. Currently they fail with something like `NameError: name 'nonex' is not defined` but in the future they'd fail like `ImportError: No module named nonex`. The latter may be somewhat surprising error if you make a typo, but compared to the benefits I think that's OK.

If we agree this kind of "auto import" functionality would be good, I'll submit a separate issue about it because it also changes how some of the BuiltIn keywords work. Comments about this idea or simply :+1: or :-1: depending on do you like it are appreciated!

**Comment by stdedos** [comment]
I cannot think of counter-examples right now, but it seems a bit ... radical change to make. However, if it happens only at `${{ }}` and not on the normal `${ }`, then I guess it could be fine.

If not, maybe it needs a bit more thought on when to put it on effect.

**Comment by pekkaklarck** [comment]
It would happen with `${{ ... }}` and with BuiltIn keywords like Evaluate and Run Keyword If. But only in places where the expression is evaluated in Python. It could be strange if something like
```
Rin Keyword If    foo == 42    Keyword
```
would fail with ImportError about module `foo`, but we could make it so that such errors are reported exactly like now if we wanted to. Behavior wouldn't change with any valid expression.

**Comment by stdedos** [comment]
Maybe report both of them? Like:

`RobotEvaluateError: name 'nonex' is not defined (or no such module to import)`

I usually prefer if "all the common errors" are reported on the error message given, and they are not overloaded (i.e. `NameError` OR `ImportError` when _actually_ it's a bit of both

If you'd go with `RobotEvaluateError`, then you could write a bunch of "separate" documentation for this feature, its nuisances, and give usage examples of edge cases.

**Comment by pekkaklarck** [comment]
I submitted #3349 about importing used modules automatically with `Evaluate`, `Run Keyword If`, and others.

It's a good idea to construct a custom error message if a variable in an expression isn't found and cannot be imported as a module either. Probably it should be used only when a module import fails with ImportError, not if import fails due to a syntax error in the imported module. These details can be fine tuned later.

**Comment by stdedos** [comment]
> I cannot think of counter-examples right now, but it seems a bit ... radical change to make. However, if it happens only at `${{ }}` and not on the normal `${ }`, then I guess it could be fine.

Found a potential issue? How about:
```robot
    ${chrome options} =     Evaluate    sys.modules['selenium.webdriver'].ChromeOptions()
    ...                     sys, selenium.webdriver
```

**Comment by pekkaklarck** [comment]
Why would you do that and not `selenium.webdriver.Chromeoptions()`?

**Comment by stdedos** [comment]
That is a very good question! I have no idea :sweat_smile: 
Google finds so many examples for the former, and not the latter one.

Maybe it is not as important then.

**Comment by pekkaklarck** [comment]
There's actually some truth about `selenium.webdriver.Whatever` causing problems. I comment that more in #3349 where we in general should move discussion about the automatic imports.

**Comment by stdedos** [comment]
Is this supposed to work in `Documentation` sections?

Like `[Documentation] | Do ${thing} in ${{x.name for x in resources}}`, and have it rendered appopriately?

**Comment by pekkaklarck** [comment]
Did you try?

**Comment by stdedos** [comment]
"It is not planned to update to 3.2", so I cannot honestly test it.
I was thinking to put together a dummy test tomorrow, and I didn't want to forget a possibly good enhancement request.

Apologies if that ^^^ is spamming you

**Comment by pekkaklarck** [comment]
It's not really spamming but this is so easy to test that I'm surprised if you haven't done it. Even if you couldn't upgrade to 3.2, you could install it to a temporary virtual environment. Anyway, I guess this ought to work in settings as well.

**Comment by shanebishop** [comment]
Is this new feature documented somewhere in the Robot Framework documentation?

**Comment by shanebishop** [comment]
> Is this new feature documented somewhere in the Robot Framework documentation?

My mistake, inline evaluation is documented [here](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#inline-python-evaluation).

**Comment by angus-she** [comment]
I have just upgraded my application to use robotframework-3.2.2.jar. However, when I tried to use the python inline expression ${{}} in my test case, it failed to identify the expression.

e.g.
Invalid variable name '${{len('123')}'

Any idea with what's missing? some config missing?
