### ISSUE TITLE
Total number of failed (and passed) tests should be shown on console

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#318]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=318) by @pekkaklarck on 4 May 2009*

We should should show the total number of failed tests on the console all
the time to make it easier to see what's the current execution status. Need
to decide should we show both all and critical tests, only the number of
failed critical tests, and should we also show the number of passed tests.

**Comment by pekkaklarck** [comment]
Closing this issue as wontfix because

- this is very hard to implement platform independent manner,
- custom solutions based on listeners can be implemented pretty easily, and
- new `--dotted` console output (#317) make it easy to see the overall status.
