### ISSUE TITLE
Multiple instances of a library does not work with embedded arguments

### ISSUE THREAD

**Issue by kylekizirian** [robotframework/robotframework#3181]
Multiple instances of a library using ```WITH NAME``` syntax does not work if the library's keywords have embedded arguments. All uses of keywords with embedded arguments are treated like the same instance of the library. Here is an example library with three keywords, the first keyword has embedded arguments

```python
from robot.api import deco, logger


class test:

    def __init__(self):
        logger.console('')
        self._sum = 0

    @deco.keyword('Add [${num}] to my sum')
    def add_to_sum(self, num):
        self._sum += int(num)
        logger.console(f'Sum = {self._sum}')

    @deco.keyword('Add 1 to my sum')
    def add_one_to_sum(self):
        self._sum += 1
        logger.console(f'Sum = {self._sum}')

    def add_to_my_sum(self, num):
        self._sum += 1
        logger.console(f'Sum = {self._sum}')
```

Here's an example test case demonstrating the issue, the first test case does not behave as expected, both Test1 and Test2 are treated as the same object. The next two test cases work as expected

```
***Settings***
Library  test.py  WITH NAME  Test1
Library  test.py  WITH NAME  Test2


***Test Cases***
Test With Embedded Arguments
    # this test behaves incorrectly, expected output is
    # sum = 1, sum = 2, sum = 1, sum = 2
    # actual output is
    # sum = 1, sum = 2, sum = 3, sum = 4
    Test1.Add [1] to my sum
    Test1.Add [1] to my sum
    Test2.Add [1] to my sum
    Test2.Add [1] to my sum

Test Without Embedded Arguments
    Test1.Add 1 to my sum
    Test1.Add 1 to my sum
    Test2.Add 1 to my sum
    Test2.Add 1 to my sum

Test Normal Syntax
    Test1.Add To My Sum  1
    Test1.Add To My Sum  1
    Test2.Add To My Sum  1
    Test2.Add To My Sum  1
```

**Comment by pekkaklarck** [comment]
Thanks for the great bug report making it easy to reproduce the problem. It took a while for me to understand why it happens, but after that coming up with an initial fix wasn't too complicated. Hopefully I have time already later today to finalize the fix and create some tests.

The related code is pretty old and not too good. Hopefully we can get it rewritten at some point.

**Comment by kylekizirian** [comment]
Awesome, thank you Pekka!
