### ISSUE TITLE
Support variable index access like `${var}[2]` with all sequences (incl. strings and bytes)

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#3182]
RF 3.1 added support for accessing variable items using syntax `${var}[item]` (incl. nested access `${var}[x][y][z]`, #2601) but *only* when variable is a list or a dictionary. This is a nice syntax and it would be good to extend it to cover all objects, including strings. Since RF 3.1. this syntax causes an error with other objects than lists or dicts (see e.g. #3028), so changing it to mean item access should not cause backwards compatibility issues. Should at the same time add support also for slice access `${var}[2:]` similarly as lists support (#2973).

One problem is that with custom objects we don't know should `${var}[42]` mean item access with `42` as a string or as an integer. We probably should just use strings with objects that aren't list-like and let users use `${var}[${42}]` is the really need an integer. Support with custom objects isn't likely that important anyway, the most important functionality is access characters and slices in strings.

-----

**UPDATE:** This was implemented so that accessing an item from a variable like `${var}[item]` so that `item` is an index now works with all sequences (incl. lists and bytes), not only with objects Robot considers list-like normally. The item is not considered an index *only* if the variable is a dictionary. In other words, the `${var}[item}` syntax works with custom objects *only* if these custom objects expect items to be indices.

**Comment by pekkaklarck** [comment]
It's probably better to wait a bit more until we change the meaning of `${var}[item]` when `${var}` isn't a list or dictionary. This syntax currently causing an error makes it easier to spot places that still use this syntax to mean variable `${var}` followed with a literal string `[item]`. If we implement this functionality in RF 3.2, those who migrate from RF 3.0.x or older to it won't see an error but instead the behavior changes and understanding what happens can be hard.

**Comment by pekkaklarck** [comment]
We have #3350 implementing this feature. Added this issue back to RF 3.2 scope.

**Comment by pekkaklarck** [comment]
In the end decided to move this back to RF 3.3 for the following reasons:

- Although PR #3350 is in pretty good shape there are still changes to be done. See my review and comments after that for more information.

- I would like to have RF 3.2 out still this year (getting unlikely) or at least before [RoboCon](https://robocon.io) in mid January. This means I don't have time for further reviews even if PR #3350 would be developed further.

- We only changed `${var}[x]` to mean item access with lists and dicts in RF 3.1 (#2601). It was a backwards incompatible change and there are still quite often questions and bug reports related to it. At the moment this syntax causes an explicit error when `${var}` isn't a list or dict making it somewhat easy to understand what's going on. When we change this so that the syntax works also with strings and other objects, there may not be a clear error and debugging problems will be harder. Post-poning this feature to RF 3.3 gives users more time to update their tests.

- There's a simple workaround to use the extended variable syntax like `${var['x']}`,  `${var[0]}` or `${var[1:]}` to access items based on a key, an index or a slice, respectively.

**Comment by pekkaklarck** [comment]
RF 3.2 still isn't ready (we got beta 1 out before RoboCon...) and #3350 has gotten better so I'll give this a chance.

**Comment by pekkaklarck** [comment]
PR #3350 is in very good shape, but we still need to decide when `${x}[item]` should use sequence access where `item` is considered an index or a slice and when use generic item access. I moved the discussion about it here to make it more visible.

When accessing items from a sequence like `${x}[1]` we need to do integer conversion and with something like `${x}[2:]` we want to convert `2:` to a slice. In all other cases with `${x}[item]` we don't do anything to the `item` other than replacing possible variables.

There are several possibilities with different benefits and problems for detecting when to use which access:

1. The current implementation works like this:
    - Mappings (detected with `utils.is_dict_like()`) use the generic access.
    - List-like objects _not_ including strings or bytes (detected with `utils.is_list_like()`) use the sequence access.
    - With all other objects item access causes an error.

   The main problem with this approach, and the reason we have this issue in the first place, is that item access doesn't work with strings and bytes. Supporting it with other sequences that `utils.is_list_like()` explicitly rejects (e.g. files) would be nice and supporting the generic item access with objects having `__getitem__` could be useful as well.

2. We can decide to use sequence access only if the original item is an instance of [Sequence](https://docs.python.org/3/library/collections.abc.html#collections.abc.Sequence) and then use the generic access with other items having `__getitem__`.

   This works well otherwise, but we'd use the generic access with list-like objects that don't inherit `Sequence`. That would be a backwards incompatible change affecting also our own acceptance tests because our `ExecutionErrors` is iterable but not a sequence and it is used in tests like `${ERRORS}[0]`. It ought to be easy to change `ExecutionErrors` to inherit `Sequence`, but the change would still be backwards incompatible for others.

3. We could decided to use the generic item access with mappings and the sequence access with others. The problem with this approach is limiting the generic `${x}[item]` syntax without index/slice conversion only to dictionaries. That's how the code works now, so there wouldn't be backwards incompatibility problems.

4. It's also possible to first use the generic access and if that fails then use the sequence access. That's how the PR #3350 currently works, but I consider it too complicated and error prone.


My current thinking about this is that the option 3. above would be the best. It wouldn't have backwards compatibility concerns and would be easy to implement and explain. The question is, are there valid use cases for custom objects with `__getitem__` that aren't mappings or list-like. If there are, the next question is that are these use cases important enough to require support by RF. Personally I think in most cases it would be better to use `${x.item}` than `${x}[item]` with custom objects that aren't mappings or sequences.

**Comment by JasperCraeghs** [comment]
I've just now changed PR #3350 to follow option 3. instead of 4.

**Comment by pekkaklarck** [comment]
Did you @JasperCraeghs look at my latest comments to #3350? I try to get RF 3.2 rc 1 out this week and all changes planned to the final release need to be included. This is so close to be done that I'd like this in.

**Comment by pekkaklarck** [comment]
This has now been implemented by PR #3350, more precisely commit 1c949ef881ad4366b6871591ef6135f4f86eac08. I'll do some minor enhancements to docs and tests but this issue can already be considered done. Thanks a lot for your hard work @JasperCraeghs and @bollenn!

I like to acknowledge people submitting PRs in release notes. You have @JasperCraeghs and @bollenn both worked with PR #3350. Apparently the final squashed commit is attributed only to @bollenn, most likely because he initially opened the PR. I guess acknowledging you both in the release notes is fine?

**Comment by bollenn** [comment]
Agree, I think @JasperCraeghs needs special mentioning as he did most of the work :wink: thanks for accepting the PR btw. Looking forward to upgrade to this release!
