### ISSUE TITLE
Error Importing test library 'Selenium2Library' failed: ModuleNotFoundError: No module named 'SeleniumLibrary'

### ISSUE THREAD

**Issue by manjugb** [robotframework/robotframework#3183]
Hi ,
I got issue while i am running my robot scripts in jenkins
Importing test library 'Selenium2Library' failed: ModuleNotFoundError: No module named 'SeleniumLibrary'
Traceback (most recent call last):
steps i followed
-----------------
1.Added robot framework plugin
2.Python plugin
3.accessing scripts from local workspace
do i need to setup anything apart from above?
Operating Sytem is Linux(Ubuntu)
Please note: Locally all my robot scripts were successfully executed

Here is the Full log
[ ERROR ] Error in filemporting test library 'Selenium2Library' failed: ModuleNotFoundError: No module named 'SeleniumLibrary'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/Selenium2Library/__init__.py", line 19, in <module>
    from SeleniumLibrary import SeleniumLibrary

**Comment by pekkaklarck** [comment]
This tracker is for bug reports and enhancement requests related to Robot Framework itself. External libraries have their own issue trackers, and general questions are best sent to actual support forums listed at http://robotframework.org.
