### ISSUE TITLE
CLI arguments are lazily parsed

### ISSUE THREAD

**Issue by ntwrkguru** [robotframework/robotframework#3184]
Running a robot CLI command with an invalid argument should produce an error. Instead, it seems to ignore invalid arguments and attempt execute the command anyway. This was observed when there was a typo in a command (`-nostatusrc` was used when it should be `--nostatusrc`) and the exit code on a failure was still 1. Subsequently, I was able to reproduce this using an argument of `-no`.

I haven't found it in the code, but it seems that the CLI is taking the `-n` and ignoring the rest. An argument of `-foo` emits an error, while `-doo` creates an output dir called `oo`. Perhaps the entire argument (up to the first whitespace) should be evaluated?

**Comment by pekkaklarck** [comment]
When you use `-nostatusrc` it's actually equivalent to `-n ostatusrc` which is valid. I'm not the biggest fan of using short options like this, but it's pretty common behavior. In our case we get this functionality via the [getopt](https://docs.python.org/2/library/getopt.html) module. I don't think trying to fight against getopt is worth the effort, especially when changing this would be backwards incompatible.

**Comment by ntwrkguru** [comment]
I don't think that's accurate. I believe it's equivalent to -n oncritical, which would yield different results.

```
-n --noncritical tag *   Tests with given tag are not critical even if they
                          have a tag set with --critical. Tag can be a pattern.
```

Perhaps the entire arguments section can be re-evaluated to be more uniform? I don't mind short, nor long, but some consistency would be good.

**Comment by pekkaklarck** [comment]
No, `--nwhatever` is equivalent to `-n whatever` which is equivalent to `--noncritical whatever`. But if you have ideas how to enhance the docs, we certainly can do that.

**Comment by pekkaklarck** [comment]
At least the User Guide explains this pretty thoroughly: http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#short-and-long-options

**Comment by ntwrkguru** [comment]
> No, --nwhatever is equivalent to -n whatever which is equivalent to --noncritical whatever. But if you have ideas how to enhance the docs, we certainly can do that.

But it's not, that's what I'm trying to say. `--nostatusrc` has no short code, so `-nostatusrc` will translate to the `-n` short code, which translates to `--noncritical`. That is my point here. :-) If `-n` and `--nostatusrc` were the same, this wouldn't be an issue.

**Comment by pekkaklarck** [comment]
First of all, reporting problems is always appreciated. In this case the problem is caused by a feature in an external module, which makes it hard to fix. I don't like the idea to remove all short options because it would be backwards incompatible and because short options are handy. Migrating to argparse would be great, but it would be rather big task and I wouldn't be surprised if argparse would handle this case same way as getopt.
