### ISSUE TITLE
Element with locator 'xpath=//*[@id="app"]/div[1]/div[3]/div[1]/button' not found.

### ISSUE THREAD

**Issue by arvingoing** [robotframework/robotframework#3185]
![image](https://user-images.githubusercontent.com/30926518/57825117-1b833f80-77d0-11e9-9722-8a9e102d85fd.png)
![image](https://user-images.githubusercontent.com/30926518/57825152-41a8df80-77d0-11e9-9efa-2cd8774a1d0a.png)

**Comment by pekkaklarck** [comment]
This tracker is for bug reports and enhancement requests related to Robot Framework itself. External libraries have their own issue trackers, and general questions are best sent to actual support forums listed at http://robotframework.org.
