### ISSUE TITLE
Can't exclude tests using Robot API

### ISSUE THREAD

**Issue by ejd** [robotframework/robotframework#3188]
I'm having a problem using the Robot API to exclude tests from a test suite built programmatically.

I expect the attached program to cause only Test B to run.  Instead, both Test A and Test B run.  Can you tell me if I'm misusing the API to have this result?  If this is a bug, I'd love to work on fixing it.  

Example program:

```python
from robot.api import TestSuite, TestSuiteBuilder
from robot.conf.settings import RobotSettings

suite = TestSuiteBuilder(extension='robot').build('example.robot')

root = TestSuite('Root')
root.suites.append(suite)
root.run(settings=RobotSettings(options={
    'exclude': ['exclude-me']
}))
```

Example test data:

```robot
*** Test Cases ***
Test A
    [Tags]    exclude-me
    No Operation

Test B
    No Operation
```

Here's the output from the example for reference:

```
==============================================================================
Root                                                                          
==============================================================================
Root.Example                                                                  
==============================================================================
Test A                                                                | PASS |
------------------------------------------------------------------------------
Test B                                                                | PASS |
------------------------------------------------------------------------------
Root.Example                                                          | PASS |
2 critical tests, 2 passed, 0 failed
2 tests total, 2 passed, 0 failed
==============================================================================
Root                                                                  | PASS |
2 critical tests, 2 passed, 0 failed
2 tests total, 2 passed, 0 failed
==============================================================================
Output:  /home/ejd8183/projects/scratch/robot/filtering_mwe/output.xml
```

I wrote a program that uses the Robot API to build a test suite containing multiple copies of the same suite.  The copies, represented in my example by `suite`, are appended to a wrapper suite (like `root` in the example).  After building the suite, my program tries to exclude tests by tag across all of the copies using `RobotSettings`.

I'm using `robotframework-3.1.1` under Python 2.7.15.  I get the same result under Python 3.6.0 and Python 3.7.2.  I'm using Red Hat Enterprise Linux 7.  I tried running the example with 
Robot versions back to 2.8.2 and the behavior doesn't change.

**Comment by pekkaklarck** [comment]
`exclude` not working with `suite.run()` is actually by design. Only settings that affect the actual execution matter there. If you want to modify the suite that's executed, you can use `suite.filter(excluded_tags=['exclude-me'])` before execution instead. This is documented in the API docs, but it's nevertheless somewhat annoying there's no explicit error. The question is, is it annoying enough that we should do something to it.

**Comment by pekkaklarck** [comment]
Would be nice to do something to this but I got a feeling there's too much work compared to benefits.
