### ISSUE TITLE
Not able to run scripts in two different tabs of same browser,simultaneously 

### ISSUE THREAD

**Issue by vinnuvhugar** [robotframework/robotframework#3190]
Say i have written two scripts in one project, one is to open my gmail and one is to open my linked in . I want those two to run simultaneously in two different tabs of same browser, say chrome.

**Comment by sebastianciupinski** [comment]
stop spamming please

**Comment by pekkaklarck** [comment]
This is an issue tracker, not a support forum. For that purpose we have dedicated forums listed at robotframework.org. That said, I don't think you can do that.

**Comment by pekkaklarck** [comment]
What spamming do you mean @sebastianciupinski?
