### ISSUE TITLE
Feature request: add older YAML file extension (.yml - Variable file as YAML)

### ISSUE THREAD

**Issue by hunkisslaszlo** [robotframework/robotframework#3195]
Hi!

We want to use robotframework for testing out project. One of our test would be a YAML structure validation. 

I know, that the suggested file extension for YAML files is `.yaml` ([YAML faq](https://yaml.org/faq.html)) but several other projects (ex. Ansible) use it with extension `.yml`. 

I know you guys mention this in your [documentation](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#variable-file-as-yaml) but is it possible to add support older `.yml` extension?

robotframework/src/robot/variables/filesetter.py (line 44)
```
- if path_or_variables.lower().endswith('.yaml'):
+ if path_or_variables.lower().endswith('.yaml') or path_or_variables.lower().endswith('.yml'):
```

**Comment by pekkaklarck** [comment]
Sounds good to me. Would require a PR with
- code changes,
- new test or just change to existing test to use `.yml` and not `.yaml`, and
- documentation update.

**Comment by pekkaklarck** [comment]
There were some problems with tests and docs in PR #3200. It took me so long to review it that instead of asking @hunkisslaszlo to update the PR, I can do changes myself.
