### ISSUE TITLE
can we install Robot Framework  on centos 7

### ISSUE THREAD

**Issue by Atif0519** [robotframework/robotframework#3196]
I am trying to install robot framework and i ran into errors every time.I tried multiple times but unsuccessfull so basically i was thinking if it possible to install it on centos ? ,if yes then which versions and dependencies should be installed with it .Kindly guide me,details are follow

CentOS Linux release 7.6.1810
Python 2.7.5
pip 19.1.1 from /usr/lib/python2.7/site-packages/pip (python 2.7)
Robot Framework 3.1.2 (Python 2.7.5 on linux2)
Following Error occur during installation on Robot Framework-ride :
error: no matching distribution found for pywin32 (from robotframework-ride)

**Comment by Atif0519** [comment]
CentOS Linux release 7.6.1810 
Python 2.7.5
pip 19.1.1 from /usr/lib/python2.7/site-packages/pip (python 2.7)
Robot Framework 3.1.2 (Python 2.7.5 on linux2)
Following Error occur during installation on Robot Framework-ride :
error: no matching distribution found for pywin32 (from robotframework-ride)

**Comment by pekkaklarck** [comment]
That's an issue with RIDE. It has its own issue tracker. This is only for Robot Framework core.
