### ISSUE TITLE
Permission error in robot framework 

### ISSUE THREAD

**Issue by Atif0519** [robotframework/robotframework#3198]

**Comment by Atif0519** [comment]
I am using 
python 2.7.16, 
pip 19.1.1 from c:\python27\lib\site-packages\pip (python 2.7)
Robot Framework 3.1.1 (Python 2.7.16 on win32)
Rebot 3.1.1 (Python 2.7.16 on win32)
wxpPython 2.8.1.2 
on windows 10 
whenever i try to run a test example containing external library like seleniumlibrary it shows permission error and whenever i try to run it without importing any library it runs smoothly based on internal keywords.Kindly guide me in this situation i have tried even by changing file location in different drives

**Comment by pekkaklarck** [comment]
This is an issue tracker for concrete bug reports and enhancement requests. Questions like this are best asked on robotframework-users mailing list, our Slack, or other such support forums listed at robotframework.org. Notice also that when asking help related on an error, it would be good to tell the exact error message you get.
