### ISSUE TITLE
`Log List` and some other keywords in Collections and BuiltIn fail with tuples

### ISSUE THREAD

**Issue by malinat0r** [robotframework/robotframework#3201]
**Steps to reproduce:**

1. Create a tuple.
2. Create a list having only one element - the tuple.
3. Call "Collections.Log List" keyword for the list.

**Expected result:** The list length and contents should be logged using given level.
**Actual result:** An error has occurred: *"TypeError: not all arguments converted during string formatting"*
**Software versions:** Robotframework 3.1.2 running under CPython 3.7.3 under windows 7 x64.

**Sample test:**
```
*** Settings ***

*** Test Cases ***

Log List test
    ${L1}    Evaluate    ('a', 'ddjk', 12)
    ${L3}    Evaluate    ('table', 'date', 6)
    ${L2}    create list    ${L1}
    Comment    ${L2}    create list    ${L1}    ${L3}
    ${a}    evaluate    isinstance(${L2},list)
    ${a}    evaluate    isinstance(${L2[0]},list)
    ${a}    evaluate    isinstance(${L2[0]},tuple)
    Log Many    @{L2[0]}    level=DEBUG
    Log Many    @{L2}    level=DEBUG
    Log List    ${L2}
```
**Test log:**
```
Starting test: Workspace.Log List test
20190530 15:03:44.628 :  INFO : ${L1} = ('a', 'ddjk', 12)
20190530 15:03:44.628 :  INFO : ${L3} = ('table', 'date', 6)
20190530 15:03:44.628 :  INFO : ${L2} = [('a', 'ddjk', 12)]
20190530 15:03:44.675 :  INFO : ${a} = True
20190530 15:03:44.675 :  INFO : ${a} = False
20190530 15:03:44.675 :  INFO : ${a} = True
20190530 15:03:44.690 :  INFO : a
20190530 15:03:44.690 :  INFO : ddjk
20190530 15:03:44.690 :  INFO : 12
20190530 15:03:44.690 :  INFO : level=DEBUG
20190530 15:03:44.690 :  INFO : ('a', 'ddjk', 12)
20190530 15:03:44.690 :  INFO : level=DEBUG
20190530 15:03:44.706 :  FAIL : TypeError: not all arguments converted during string formatting
20190530 15:03:44.706 : DEBUG : 
Traceback (most recent call last):
  None
Ending test: Workspace.Log List test
```

**Comment by pekkaklarck** [comment]
This is caused by code `'List has one item:\n%s' % list_[0]` because when formatting with `%` tuple as the formatted value has special meaning. This line should be changed to `'List has one item:\n%s' % (list_[0],)` to avoid the problem. Should also check does Collections or our code in general have more places where this could happen.

**Comment by pekkaklarck** [comment]
I went through Collections and also rest of the code base to see where we use string formatting like `'something %s' % arg` and `arg` is given by user. There were quite a few such places, but I don't think we need to care about such usages in places where tuples are in general totally invalid (e.g. when a keyword expects a path as an argument) especially when creating a tuple in Robot data isn't that easy. In places where the value can be anything (e.g. with Collections) and especially if the value is expected to be iterable, tuples should naturally work. Luckily such usages were mostly limited to Collections but there were few in BuiltIn as well.

All affected keywords in Collections were:
- `Log List`
- `Remove From Dictionary`
- `Get From Dictionary`
- `Dictionary Should Contain Key`
- `Dictionary Should Not Contain Key`
- `Dictionary Should Contain Value`
- `Dictionary Should Not Contain Value`

In BuiltIn these keywords were affected:
- `Should Be Empty`
- `Should Not Be Empty`
