### ISSUE TITLE
Extend 'Log' keyword functionality

### ISSUE THREAD

**Issue by sebastianciupinski** [robotframework/robotframework#3204]
For now **Log** keywords adds entries into Test Execution Errors only when `level` argument is set to `ERROR` or `WARN`. I think that:

- Test Execution Errors section could be renamed to Test Execution Messages and

- Additional argument, for example `summary` could be added to add possibility to log other severities into Test Execution Messages, e.g:
```
Log     some message     summary=True
```

**Comment by pekkaklarck** [comment]
1. Could you clarify the use case for this functionality?

2. Just enhancing `Log` wouldn't be enough. We'd first of all need an API that allows this and should expose it also to libraries.

3. Are you interested to implement this feature or sponsor the development if someone else would do it?

**Comment by kblomqvist** [comment]
I have similar need. I was looking for NOTE level logging to log Python package version on top of the result.html.

**Comment by pekkaklarck** [comment]
Logged messages aren't shown in report at all at the moment. Been thinking that showing messages in the execution errors section (that this issue proposes to be changed to test execution messages) in report somehow would be a good idea. That would require its own issue, though.

At the moment the best way to get messages shown in report is probably using test suite metadata. See the User Guide for details.

**Comment by pekkaklarck** [comment]
My questions, most importantly the use case, was never answered. Closing.

For getting info shown at the top of reports, I recommend suite metadata.
