### ISSUE TITLE
Seeing Version Conflict Error on doing pip install extendedselenium2library

### ISSUE THREAD

**Issue by ssheetal** [robotframework/robotframework#3205]
I am seeing the following error on doing pip install for extendedselenium2library
pip install robotframework-extendedselenium2library
Collecting robotframework-extendedselenium2library
  Downloading https://files.pythonhosted.org/packages/66/b7/4d3230c1f67eaf21c922b5bedba4334bb70f4407425f65cbaf1f810b06d1/robotframework-extendedselenium2library-0.9.2.tar.gz (107kB)
    100% |████████████████████████████████| 112kB 468kB/s
Requirement already satisfied: selenium>=2.46.1 in c:\users\username\appdata\local\programs\python\python37\lib\site-packages (from robotframework-extendedselenium2library) (3.141.0)
Collecting robotframework-selenium2library==1.8.0 (from robotframework-extendedselenium2library)
  Downloading https://files.pythonhosted.org/packages/0a/d4/5bd64ce78d66e1a4d69457a12c90887cd468dc4de94709e35d12abe3c2ed/robotframework-selenium2library-1.8.0.tar.gz (118kB)
    100% |████████████████████████████████| 122kB 1.1MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\username\AppData\Local\Temp\pip-install-pfx27cjv\robotframework-selenium2library\setup.py", line 7, in <module>
        from ez_setup import use_setuptools
      File "C:\Users\username\AppData\Local\Temp\pip-install-pfx27cjv\robotframework-selenium2library\src\ez_setup.py", line 106
        except pkg_resources.VersionConflict, e:
                                            ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\username\AppData\Local\Temp\pip-install-pfx27cjv\robotframework-selenium2library\
You are using pip version 19.0.3, however version 19.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

How can I overcome the version conflict?

**Comment by pekkaklarck** [comment]
This issue tracker is for Robot Framework core and you problem is with an external library. More importantly, issue trackers are for bug reports and enhancement requests. Questions are better sent to dedicated support forums.

**Comment by pekkaklarck** [comment]
The above said, it seems you try to install library that only supports Python 2 using Python 3.

**Comment by ssheetal** [comment]
With support for Python2 ending soon, I wanted to check for Python3's compatibility with this external library for a certain application needs. Thanks for pointing out on the version not supported for this external library.
