### ISSUE TITLE
Formatters are not supported when logging using the `logging` module

### ISSUE THREAD

**Issue by Ka55i0peia** [robotframework/robotframework#3208]
**UseCase:** see [this answer](https://stackoverflow.com/questions/50843636/using-a-python-root-logger-with-robot-framework/56627468#56627468).

When using the [RobotHandler class](https://github.com/robotframework/robotframework/blob/master/src/robot/output/pyloggingconf.py#L57) as custom handler for python's logging module, the formatters of the config wouldn't be supported.

**Fix:**
Getting the message str from log record as described [here](https://dzone.com/articles/python-custom-logging-handler-example):
```
message = self.format(record)
```

**EDIT**
While providing a fix as branch, I got a 403 (Permission to robotframework/robotframework.git denied)
Here is the patch:
[0001-apply-logging-formatter-as-stated-here-https-dzone.c.patch.zip](https://github.com/robotframework/robotframework/files/3296453/0001-apply-logging-formatter-as-stated-here-https-dzone.c.patch.zip)

**Comment by pekkaklarck** [comment]
I don't have time to study this right know. Anyway, if you want to provide a fix, please provide a pull request.

**Comment by Ka55i0peia** [comment]
I can't provide a branch. 

>I got a 403 (Permission to robotframework/robotframework.git denied)

**Comment by pekkaklarck** [comment]
Either you do something wrong or GitHub is experimenting problems. Have you created GitHub PRs earlier? If not, please check its instructions first. They are linked, for example, from our contribution guidelines that contain also other valuable information.

**Comment by Ka55i0peia** [comment]
@pekkaklarck : It's open.

**Comment by pekkaklarck** [comment]
The PR definitely needs some tests. They are needed for me to understand the actual problem better and, more importantly, to make sure we don't break the fixed functionality later.

**Comment by pekkaklarck** [comment]
Original PR #3210 never got tests but new PR #4147 by @Robtom5 has them and looks so good that I add this issue to RF 5.0 scope. Smallish changes needed to the new PR still, though.

**Comment by pekkaklarck** [comment]
PR #4147 by @Robtom5 merged and this issue closed. Thanks for contribution!
