### ISSUE TITLE
`Wait Until Keyword Succeeds`: Support retry time with strict interval 

### ISSUE THREAD

**Issue by Schwaneberg** [robotframework/robotframework#3209]
We use the Robot Framework to execute tests on embedded systems in our company.
Doing so, we have timing problems when using the *wait_until_keyword_succeeds* keyword.
The problem is, that the execution of certain (custom) keywords takes 50-150ms on our embedded targets and the keywords shall be re-executed at a precise rate of 5Hz / 200ms interval time.

The keyword *wait_until_keyword_succeeds* simply waits for the given *retry_interval* time after the keyword has finished. For the example above, this results to interval times of 250ms to 350ms, instead of the desired 200ms.

I'd like to contribute a solution to that problem: [PR3177](https://github.com/robotframework/robotframework/pull/3177/files).

**Comment by pekkaklarck** [comment]
I understand your need but I'm not sure can we change the implementation like that. The current implementation matches the documentation of the keyword that says this:

> ``retry_interval`` is the time to wait before trying to run the  keyword again after the previous run has failed.

I'm fairly certain there are use cases that depend on this behavior and changing it would be a backwards incompatible change.

A possible solution is making it possible to configure how the `retry_interval` argument is interpreted. This keyword cannot take any new arguments, but we could allow embedding the type of the interval to the argument itself. The format could be, for example, `type:value` similarly as how SeleniumLibrary allows specifying locator types. Alternatively could use something like `value (type)`. Regardless the syntax, needed to decide what to call this `type`.

Finally, it might be a good idea to consider implementing functionality that has such strict timing requirements in a custom library. That would avoid overhead by the framework has between keyword calls.

**Comment by Schwaneberg** [comment]
Ok, I see your point, but I don't like the idea of a `type:value` parameter very much.
So, we could just add a new keyword like `repeat at fixed rate until keyword succeeds` - the problem here is to find a name that describes the difference to the known `wait until keyword succeeds`.

Alternatively, we could implement this in our own library, but I would prefer to contribute this feature to the community.

Please let me know what you prefer.

**Comment by pekkaklarck** [comment]
I wouldn't like to add a new keyword to BuiltIn just for this use case. Much better to make the existing `Wait Until Keyword Succeeds` configurable one way or the other.

In a custom library I wouldn't implement similar keyword that executes other keywords. Instead I'd do polling directly in that library keyword.

**Comment by Schwaneberg** [comment]
Ok, so putting an option into the parameter is the way to go. I will modify my PR so that interval time can be set as e.g. `strict:250ms` to switch to the alternative behavior. The current behavior will be the default.

**Comment by pekkaklarck** [comment]
`strict:<value>` sounds good to me. [SeleniumLibrary supports](https://github.com/robotframework/SeleniumLibrary/blob/master/src/SeleniumLibrary/locators/elementfinder.py#L235) optional spaces around `:` with locators and this keyword probably should support them as well. Definitely no need to support both `=` and `:` similarly as SeleniumLibrary does for legacy reasons.

**Comment by Schwaneberg** [comment]
Ok, I implemented it accordingly and updated my PR with a second commit.

**Comment by Schwaneberg** [comment]
I updated my PR accordingly to our discussion. @pekkaklarck please review my PR, if you got time for it.

**Comment by pekkaklarck** [comment]
Not sure why the PR wasn't reviewed again in 2019. Probably it has been summer holiday season and then the PR and this issue were buried below other issues/PRs in this tracker. Anyway, the enhancement still sounds valid. No time to look this more closely before RF 4.0 anymore, but I add this to RF 4.1 scope so it won't be forgotten again.

**Comment by pekkaklarck** [comment]
The PR looks pretty good but there are few things to be changed in the code and also changes e.g. to release notes should be removed. Are you @Schwaneberg still interested in this issue and the PR? If yes, I could do a more thorough review and list things that should be changed. We have still enough time to get this into RF 4.1 but RF 5.0 is an option too. If there's no interest anymore, we can just close the issue and the PR.

**Comment by Schwaneberg** [comment]
I merged the latest master into my PR, removed the temporary change log and AUTHORS.txt.
Please let me know if you see more things that need to be changed.

PS: We experienced crashes caused by the TCL/TK dialogues (e.g. with `execute manual step`) like
`Tcl_AsyncDelete: async handler deleted by the wrong thread, Process finished with exit code 134 (interrupted by signal 6: SIGABRT)`
We fixed it by replacing all builtin dialogues with Qt/QML dialogues. I could also provide a PR for this change. Please let me know if you like that.

**Comment by pekkaklarck** [comment]
This was implemented by @Schwaneberg in PR #3177. Thanks for contribution!

I did few fixes/enhancements in fbcd40f4caf4717ef79bfa0f9f4fdffc18f74766. The only functional change is that the warning about too long execution time is logged also if the keyword succeeds.
