### ISSUE TITLE
Getting message "Robot framework installation not found" while running TC.

### ISSUE THREAD

**Issue by anilrawat1984** [robotframework/robotframework#3211]
Hi,

I have installed:

pypubsub==3.3.0
robotframework==3.1.1
robotframework-ride==1.7.3
robotframework-seleniumlibrary===dev
urllib3==1.25.3

I am using selenium2library as i am not able to use seleniumlibrary. When I am running the test, I am getting Message : "Robot Framework installation not found. To run tests, you need to install Robot Framework separately. See http://robotframework.org for installation instructions".

On ride interface getting error: 
command: "no pybot" --argumentfile c:\users\anil~1.raw\appdata\local\temp\RIDE_tbdp_.d\argfile.txt --listener C:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py:5187:False D:\Robot\Demo
[Error 2] The system cannot find the file specified

**Comment by pekkaklarck** [comment]
Your installation is somehow messed up. Could be you have multiple user accounts and have installed Robot only on one of them. Anyway, this issue tracker is for bug reports and enhancement requests. Use support forums listed at http://robotframework.org for questions.
