### ISSUE TITLE
Is there a way to bypass tag pattern keywords for robot?

### ISSUE THREAD

**Issue by chriscallan** [robotframework/robotframework#3215]
In running my test suite, I have a few tests tagged with 'CORE-BVT', guess what they're denoting.  After updating to the 3.x version my robot command now returns with, "[ ERROR ] Suite 'PycharmProjects' contains no tests matching tag 'C OR E-BVT'."
I suppose it would be simple enough to change all the "offending" tags or just refer to my tags as "C??E-BVT", but it would seem like there should be a way to bypass this so that it's not parsing things that don't need to be parsed.

Any help is much appreciated.

**Comment by chriscallan** [comment]
Seems like there's no way to disable this, so I'll have to set in on changing my scripts to not call the capitalized version that matches my supplied tags but rather to use the case insensitive version that doesn't match.  Easy enough to workaround I guess, but takes a bit to figure out since this behavior is one of the least intuitive that I've encountered.

**Comment by pekkaklarck** [comment]
You are right, there's no way to disable this behavior. This ought the be documented in detail in the User Guide.

**Comment by chriscallan** [comment]
It is documented in the User Guide, once I found that.  The behavior was just so bizarre and non-intuitive when I came across the issue that it appeared to be a bug until I found the documentation and figured my way through someone's suggested workaround for this new "feature".

**Comment by pekkaklarck** [comment]
Supporting Boolean logic with tags like `--include fooANDbar` is definitely a feature, not a "feature". It was known that it causes problems with tags like `STANDARD`, but it was considered that using tags in lower case like `--include standard` is easy enough.
