### ISSUE TITLE
Keyword "Set Variable If" does not have ELSE IF

### ISSUE THREAD

**Issue by leosaldanha** [robotframework/robotframework#3216]
It would be awesome if you guys could include support to ELSE IF on "Set Variable If". 

Currently, this behavior was implemented for "Run Keyword If" but not for the aforementioned keyword. I noticed that [an issue was opened back in 2014](https://github.com/robotframework/robotframework/issues/90), but nothing was implemented since then.

<img width="1662" alt="Screen Shot 2019-06-25 at 17 19 16" src="https://user-images.githubusercontent.com/13903117/60130310-61d3a300-976d-11e9-8184-863dbab3e80a.png">

**Comment by pekkaklarck** [comment]
I don't understand. The issue you referred is about implementing "else if" functionality and it was done already in RF 2.0.2.
