### ISSUE TITLE
Friendly json view in log.html

### ISSUE THREAD

**Issue by ruanwenjun** [robotframework/robotframework#3220]
when i use **Log** keywork to write some log in log.html, i find it is hard to knowledge the json string.
![image](https://user-images.githubusercontent.com/22415594/60228621-dd486800-98c5-11e9-8fa2-bc1731569308.png)
I hope  can make the json string format like 

> { 
       "xx" : "xx"
}

**Comment by sebastianciupinski** [comment]
I think you need to create your own keyword, or use evaluate to do something like this:
https://stackoverflow.com/questions/12943819/how-to-prettyprint-a-json-file/12944035#12944035

**Comment by ruanwenjun** [comment]
@sebastianciupinski 
Fine, thank you , this can solve my problem. 
But i think if it can automatic formatting , it will be perfect.

**Comment by pekkaklarck** [comment]
Did you try `repr=True` or `formatter=repr` (RF 3.1.2+)? It doesn't split short items like in the description to own lines, but it ought to do pretty good job with large JSON structures.

It would be really nice if we could also syntax highlight JSON, XML, and other such formats. It would require using something like [Pygments](http://pygments.org/) and including Pygments CSS files in our log, but I guess it ought to be doable. Anyone interested on implementing it? First step would be submitting an issue about it.

**Comment by pekkaklarck** [comment]
No interest towards this lately. Closing.
