### ISSUE TITLE
Possibility to consider only methods decorated with `@keyword` keywords

### ISSUE THREAD

**Issue by cristii006** [robotframework/robotframework#3221]
Right now when using test libraries you have the possibility to configure what methods will become  keywords by importing modules or by using the module level `__all__`. It would be a nice addition to have a class attribute `ROBOT_AUTO_KEYWORDS` which will be used to avoid all public methods that are not decorated to become keywords.

```python
class MyLibrary:
        ROBOT_AUTO_KEYWORDS = False

        def my_keyword(self, name):
            # this will not be available as keyword
            return name

        @keyword
        def my_decorated_keyword(self, name):
             # this will be available as keyword
             return name
```

**Comment by sebastianciupinski** [comment]
AFAIK when you start your method name with underscore, then it will not be exposed as keyword:

```
class MyLibrary:

        def _this_is_not_keyword(self, name):
            # this will not be available as keyword
            return name

        @keyword
        def this_is_keyword(self, name):
             # this will be available as keyword
             return name
```

**Comment by pekkaklarck** [comment]
This issue is a spin-off from issue #3019 that proposes `@library` decorator that allows configuring certain library features and, very importantly, by default changes introspection so that only methods explicitly decorated with `@keyword` become keywords. This issue covers the part of making it possible to make only `@keyword` decorated methods keywords and #3019 implements the decorator. The `@library` decorator is expected to be the main way to enable this functionality.

**Comment by pekkaklarck** [comment]
Once thing to decide is should this feature affect also libraries implemented as modules. The `@library` decorator only works with classes, but this functionality would be useful also with modules to avoid unrelated functions becoming keywords. For example, the `@keyword` decorator is itself a function and becomes a keyword when used like this:

```python
from robot.api.deco import keyword

@keyword
def actual_keyword():
    pass
```

Current solutions to this issue include importing only the `deco` module like

```python
from robot.api import deco

@deco.keyword
def actual_keyword():
    pass
```

and using Python's `__all__` attribute like

```python
from robot.api.deco import keyword

__all__ = ['actual_keyword']

@keyword
def actual_keyword():
    pass
```

Keeping `__all__` updated with larger libraries can be somewhat annoying, and being able to use

```python
from robot.api.deco import keyword

ROBOT_AUTO_KEYWORDS = False

@keyword
def actual_keyword():
    pass
```

would be nice.

**Comment by pekkaklarck** [comment]
You are @sebastianciupinski right that methods starting with an underscore don't become keywords. That works fine in most cases, but sometimes you may want to have a library that has also methods not starting with an underscore that aren't keywords. This is an opt-in feature that either requires using this proposed attribute or the `@library` decorator that sets it. Old code won't be affected.
