### ISSUE TITLE
Choose File is not working on Safari 12

### ISSUE THREAD

**Issue by ramonmedeiros** [robotframework/robotframework#3223]
Hi, I have the following scenario;
```
macOs High Sierra
Safari 12
RF 3.1.2
RF-S2L 3.0.0
RF-SL  3.3.1
selenium 3.141.0
```

I'm not able to upload files in a form. My tests running on chrome uses the keyword:

```
Choose File   <locator>    <file_path>
```

The error I got is:

```
InvalidArgumentException: Message: One or more files could not be selected.
```

**Comment by pekkaklarck** [comment]
This tracker is for bug reports and enhancement requests related to Robot Framework core only. Issues related to specific library should be submitted to their issue trackers. Questions are best asked on support forums such as mailing list and Slack listed at http://robotframework.org.

**Comment by pekkaklarck** [comment]
Notice that if the same test works with Chrome, the problem is most likely in Safari driver.
