### ISSUE TITLE
robot command not found if installing robotframework with pip --user

### ISSUE THREAD

**Issue by Bajibabup** [robotframework/robotframework#3227]
Hi, my Organization Infra team installed Python in C:\Python27, I installed ROBOT framework and all required libraries using "python -m pip install -U setuptools --user, python -m pip install -U robotframework --user", as we are not authorized to install anything in "c", all libraries were installed successfully, but when I try to execute the scripts through CMD then getting error " 'robot' is not recognized as an internal or external command,operable program or batch file"
Please help me.
Note:
1.All Robot Libaries are installed in "C:\Users\bab\AppData\Roaming\Python\Python27\site-packages"
2.I did set up the Env variables with above path
3.Scripts are working through ECLIPSE and eclipse is using below command
C:\Python27\python.exe -m robot.run --listener C:\Users\bab\AppData\Local\Temp\RobotTempDir2497069958731862237\TestRunnerAgent.py:61106 --argumentfile C:\Users\bab\AppData\Local\Temp\RobotTempDir2497069958731862237\args_c4fe2372.arg C:\Users\bab\Robot_Sframe\OMMS_E2EAutomation

**Comment by pekkaklarck** [comment]
Apparently the location where the `robot` command is installed when using `--user` isn't in your PATH. My guess is that you need to add it there yourself, but consulting pip documentation might be a good idea as well.
