### ISSUE TITLE
Is there a way to search for a child WebElement via a parent WebElement?

### ISSUE THREAD

**Issue by d7orenji** [robotframework/robotframework#3228]
I see that `find_element()` provided by the class `ContextAware` has the parameter `parent`. 
`parent` comment is "Optional parent `WebElememt` to search child elements from. By default search starts from the root using `WebDriver`".
I found that most of the keywords will be called `find_element()`, but I didn't find any keyword methods with the parameter `parent`.
Why is this?

**Comment by pekkaklarck** [comment]
This tracker is for bug reports and enhancement requests related to Robot Framework core only. Issues related to specific library should be submitted to their issue trackers. Questions are best asked on support forums such as mailing list and Slack listed at http://robotframework.org.
