### ISSUE TITLE
Libdoc not generating lists with multiple lines correctly

### ISSUE THREAD

**Issue by joaonc** [robotframework/robotframework#3230]
Per the documentation [here](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#lists), we can have more than one line in a list in the `[Documentation]` and it will render html as one line.

### Expected
Per documentation:
![image](https://user-images.githubusercontent.com/11450769/60539600-eff5df00-9cc1-11e9-96ad-653e0cc1fdb2.png)

### Actual
```
My Keyword
    [Documentation]  This is the documentation.
    ...
    ...  - A list (first first item).
    ...  The first item is continued here.
    ...  - Second item.
```
![list_code](https://user-images.githubusercontent.com/11450769/60539620-fd12ce00-9cc1-11e9-9dd5-a55020fef0e0.png)

Renders this:
![list_html](https://user-images.githubusercontent.com/11450769/60539627-02701880-9cc2-11e9-858a-099ecb064bf0.png)

The line _The first item is continued here._ is not part of the list.

**Comment by pekkaklarck** [comment]
A crucial part from the docs didn't fully fit into your the image above:
>  List items can be split into multiple lines by indenting continuing lines with one or more spaces.

A problem with indenting using spaces is that spaces are also used as a separator and thus indenting spaces aren't seen by Robot/Libdoc. I assume you could escape these spaces with `\` or by using `${SPACE}`.

**Comment by joaonc** [comment]
Oh, I see.

This worked:
```
My Keyword
    [Documentation]  This is the documentation.
    ...
    ...  - A list (first first item).
    ...  \ The first item is continued here.
    ...  - Second item.
```
This did not work (using `${SPACE}` rendered the string _${SPACE}_):
```My Keyword
    [Documentation]  This is the documentation.
    ...
    ...  - A list (first first item).
    ...  ${SPACE}The first item is continued here.
    ...  - Second item.
```
Might be worthwhile to update the documentation with this example. If you agree, keep this issue open as a means to track the doc update task, otherwise close it.

Tx for the quick reply!

**Comment by joaonc** [comment]
No need to leave this open..  if documentation needs to be updated, we can open a separate issue.
