### ISSUE TITLE
Log: Automatically formatted URL do not handle `{` and `}` correctly

### ISSUE THREAD

**Issue by stdedos** [robotframework/robotframework#3231]
```robot
*** Variables ***
&{dict}=     a=B    b=https://127.0.0.1/     c=https://127.0.0.1/


*** Test Cases ***
Test
    Log It    &{dict}

*** Keywords ***
Log It
    [Arguments]     &{dict}
    Log  ${dict}
```

Then, in log.html:
![image](https://user-images.githubusercontent.com/133706/60668333-62a6bc00-9e74-11e9-9017-6b9c851a36ab.png)

```html
<tr class="message-row">
    <td class="time">14:46:39.017</td>
    <td class="info level">
        <span class="label info">INFO</span>
    </td>
    <td class="message">{'a': 'B', 'b': '<a href="https://127.0.0.1/">https://127.0.0.1/</a>', 'c': '<a href="https://127.0.0.1/'}">https://127.0.0.1/'}</a>
    </td>
    <td class="select-message" onclick="javascript:selectMessage('element-id-3')" title="Select message text">
        <div/>
    </td>
</tr>
```

**Comment by pekkaklarck** [comment]
Yeah, that doesn't look right. Strange that the first URL is shown correctly. Anyway, the issue is likely in our `html_escape` utility function. Anyone interested to try fixing this?

**Comment by stdedos** [comment]
Could it be that the regex is somehow off?

Digging further, I don't see this
https://github.com/robotframework/robotframework/blob/c76a119babf2a3c534756f2d129f39909c14174c/src/robot/utils/markuputils.py#L28-L32

as having much significance over
https://github.com/robotframework/robotframework/blob/c76a119babf2a3c534756f2d129f39909c14174c/src/robot/utils/htmlformatters.py#L24-L28

or

https://github.com/robotframework/robotframework/blob/c76a119babf2a3c534756f2d129f39909c14174c/src/robot/utils/htmlformatters.py#L33-L43

(and the rest of the called functions)

**Comment by pekkaklarck** [comment]
Probably the regexp has issue. This util ought to have unit tests, and some more should be added to cover this case.

**Comment by stdedos** [comment]
I am not sure if unit tests can cut it ...

See that, the for first url
```html
'b': '<a href="https://127.0.0.1/">https://127.0.0.1/</a>', 
```
it has stopped consuming it exactly where it should be, whereas for the second one

```html
'c': '<a href="https://127.0.0.1/'}">https://127.0.0.1/'}</a>
```

it just consumed everything (even though it contains even more ... no-no characters for a URL)

An initial guess would be if `${SPACE}` is breaking the regex (and stops in time to also exclude the `'`), and `}` is somehow matching it (along with the `'`)

**Comment by pekkaklarck** [comment]
Looked the code and it seems the regexp detecting links doesn't handle `{` and `}` correctly. Ought to be trivial to fix.
