### ISSUE TITLE
Suite Variables with a value beginning with @ symbol cannot be overwritten

### ISSUE THREAD

**Issue by Steish** [robotframework/robotframework#3233]
When I set a suite variable to a value beginning with '@', then i cannot overwrite it with a different value.

**Repro code**
```robotframework
test
    Set Suite Variable            ${test}         @testname1
    ${name2}                      set variable    anothername
    Set Suite Variable            ${test}         ${name2}
    Should Be Equal As Strings    ${test}         ${name2}
```
**Console output**
test                                                                  | FAIL |
@testname1 != anothername

**ENV**
robotframework==3.1.2
Python 3.7
Windows 10

**Comment by pekkaklarck** [comment]
Does using `$test` instead of `${test}` with Set Suite Variable resolve the issue?

**Comment by Steish** [comment]
using $test works as long as ${name2} is set that way.

eg this works
```robotframework
Set Suite Variable             ${test}         @testname1
    ${name2}                      set variable    anothername
    Set Suite Variable         $test         ${name2}
```
but this does not 
```robotframework
Set Suite Variable             $test         @testname1
    ${name2}                      set variable    anothername
    Set Suite Variable         ${test}         ${name2}
```

**Comment by pekkaklarck** [comment]
This is strange but actually documented behavior. The docs of [Set Suite Variable](http://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Set%20Suite%20Variable) first say this:

> The name of the variable can be given either as a normal variable name (e.g. `${NAME}`) or in escaped format as `\${NAME}` or `$NAME`. Variable value can be given using the same syntax as when variables are created in the Variable table.

and later there's this note:

> NOTE: If the variable has value which itself is a variable (escaped or not), you must always use the escaped format to set the variable:

The reason for the behavior is that the name of the variable to be set can be given to `Set Suite Variable` as a variable and thus that variable needs to be resolved to get the real variable name. Here's a simple example:

```
*** Test Cases ***
Example
    Set Variable To X    $first
    Set Variable To X    @second

*** Keywords ***
Set Variable To X
    [Arguments]    ${name}
    Set Suite Variable    ${name}    X
```

It probably be clearer if you'd always need to use `$var` or `\${var}` syntax with this keyword and if you use `${var}` then that variable would be resolved and the resulting value would be used as variable name. Changing it would be backwards incompatible, though, and I don't think that's worth the effort.

**Comment by pekkaklarck** [comment]
Forgot to mention that your example ended up creating new variable `@{testname}` with value `['anothername']`. The should be a log message showing that.
