### ISSUE TITLE
 Arguments not passed to variable file

### ISSUE THREAD

**Issue by reyelts** [robotframework/robotframework#3234]
The User's Guide topic on variable files (https://tinyurl.com/yyvglyul) talks 
about passing arguments to variable files. It even gives two examples:

Settings table:
`   Variables    taking_arguments.py    arg1    ${ARG2}`

Command line:
`   --variablefile taking_arguments.py:arg1:arg2`

We've tried this and aren't having much luck. It seems our variable file can 
only see the arguments to launch the test. Here's an example:

vartest.robot
   ```
*** Settings ***
   Documentation     Demonstrate variable vs variablefile issue
   Library           OperatingSystem
   Variables         vartest.py  xyz
   
   *** Variables ***
   ${MY_VAR}  value from vartest.robot
   
   *** Test Cases ***
   My Test
       [Documentation]    MY_VAR=${MY_VAR}
       My Keyword         /tmp
   
   *** Keywords ***
   My Keyword
       [Arguments]    ${path}
       Directory Should Exist    ${path}

```
vartest.py:
```
   #!/usr/bin/python
   import sys
   for x in range(len(sys.argv)):
       print "vartest.py arg["+str(x)+"] = '"+sys.argv[x]+"'"
   MY_VAR="value from vartest.py"
```

Sample run:
```
   $ robot --version
   Robot Framework 3.1.2 (Python 2.7.15+ on linux2)
   $ robot --variable MY_VAR:value_from_cmdline vartest.robot
 > vartest.py arg[0] = '/usr/local/bin/robot'
 > vartest.py arg[1] = '--variable'
 > vartest.py arg[2] = 'MY_VAR:value_from_cmdline'
 > vartest.py arg[3] = 'vartest.robot'
   ==============================================================================
   Vartest :: Demonstrate variable vs variablefile issue                         
   ==============================================================================
   My Test :: MY_VAR=value_from_cmdline                                  | PASS |
   ------------------------------------------------------------------------------
   Vartest :: Demonstrate variable vs variablefile issue                 | PASS |
   1 critical test, 1 passed, 0 failed
   1 test total, 1 passed, 0 failed
   ==============================================================================
   Output:  /home/mdtest/tony/vartest/output.xml
   Log:     /home/mdtest/tony/vartest/log.html
   Report:  /home/mdtest/tony/vartest/report.html

```
For the highlighted lines, the documentation suggests we should rather get 
something like this:

```
 > vartest.py arg[0] = 'vartest.py'
 > vartest.py arg[1] = 'xyz'
```

We get the same result whether we use the settings table or the command line 
method to launch our variable file. Any thoughts?

**Comment by pekkaklarck** [comment]
- Did you read about `get_variables()` that you need to implement in your variable file to be able to accept arguments?
- `sys.argv` contains command line arguments and is populated by the Python interpreter.
- Variables from the CLI override variables in variable files.

**Comment by reyelts** [comment]
Thank you Pekka! I had read about `get_variables()`, but did not make the connection. It doesn't say anything about the arguments for get_variables() are those from the command line/settings table. And the command line/settings table discussion doesn't mention anything about having to use get_variables(). Plus, the fact that the section for get_variables() is labeled "special function" didn't help... we didn't think simply accessing the arguments was all that "special". :)

**Comment by pekkaklarck** [comment]
Good that the problem was resolved. Do you have concrete ideas how to enhance the docs?

**Comment by reyelts** [comment]
Yes, now that I understand it better, I will draft some updates.

**Comment by pekkaklarck** [comment]
Great! You can submit a new issue or re-open this one. Or just submit a PR referring this issue.

**Comment by reyelts** [comment]
Thanks Pekka, I may take you up on going the PR route in the future. Since this is my first time out, I decided to put together a set of proposed changes and see what you think. It may be more than what you asked for... :)

**2.8.2 Variable files**

- I would rename "Creating variables directly" to "Simple variable creation with a Python script file". Other alternatives would be maybe "...simple Python script command" or "...simple Python code block". (I suggest one of these terms based on https://docs.python.org/3/reference/executionmodel.html#structure-of-a-program.) And then I would replace the description with something like this:  

> **Simple variable creation with a Python script file**
> Python objects defined within the script become variables. For example, `MY_VAR='my value'` creates a variable `${MY_VAR}` with the value `my value`. You can include some logic to build the objects and you can use object names to control which objects are used as variables. However, you cannot use variable file arguments using this method.

  **Note that I used the word "objects" here. I did that because the current Python data model refers to everything as an object (https://docs.python.org/3/reference/datamodel.html#objects-values-and-types). For example, `MY_VAR` above would be considered a Python object of type immutable sequence/string. (Yes, it seems ugly to say it that way... but it is how their documentation reads.) 

- I would rename "Creating variables from a special function" to "Advanced variable creation with a Python function". And then I would replace the description with something like this:

> **Advanced variable creation with a Python function**
> The variable file function (`get_variables` or `getVariables`) provides a more refined approach. When the function is called, it is passed variable file arguments that can be used to control variable definition. When the function is complete, it returns a discrete list of variables. 

**2.8.2 Variable files -> Taking variable files into use -> Setting table**
- First paragraph:
  Replace "If an argument file..." with something like this:

> If a variable file takes arguments, the arguments are specified in the cells after the path to the imported variable file. The arguments can be constants or references to other variables. In the example below, `taking_arguments.py` is passed two arguments, `arg1` and the _value_ of `${ARG2}`. To process these values, `taking_arguments.py` must be implemented using a `get_variables` function. 

**2.8.2 Variable files -> Taking variable files into use -> Command line**
- First paragraph:
  Replace "Variable files are referenced..." with something like this:

> The path to the variable file can be relative to the current working directory or you can specify an absolute path. If a variable file takes arguments, the arguments are specified in the cells after the path to the imported variable file. In the example below, `taking_arguments.py` is passed two arguments, `arg1` and `args`. To process these values, `taking_arguments.py` must be implemented using a `get_variables` function.

**2.8.2 Variable files -> Taking variable files into use -> Order of precedence** (new section)
- Rather than trying to describe the relationship of the different ways variables can be specified, it would be simpler to provide a small section that describes the overall relationship. Based on our exploration of the feature, I believe this example text is correct:

> The same variable name can be defined in more than one place. However, only one value is assigned to the variable for the duration of the test. Variable assignments are made based on the following priority: 
>
>    `--variable`
>    `--variablefile`
>    `*** Settings ***/Variables`
>    `*** Variables ***`
>
> If the same variable name is defined in the same kind of place more than once (ie within the same variable file or within two variable files), the first occurrence wins.  
>
> Consider the following example: 
>
>     Incantation: 
>        `robot --variable VAR1=V1_CMDLINE --varfile varfile1.py myvars.robot`
>   
>     varfile1.py:
>        `VAR1=V1_VARFILE1`
>        `VAR2=V2_VARFILE1A`
>        `VAR2=V2_VARFILE1B`
>   
>     varfile2.py:
>        `VAR1=V1_VARFILE2`
>        `VAR2=V2_VARFILE2`
>        `VAR3=V3_VARFILE2`
>   
>     myvars.robot:
>        `*** Settings ***`
>        `Variables varfile2.py`
>	 
>        `*** Variables ***`
>        `VAR1=V1_VARIABLES`
>        `VAR2=V2_VARIABLES`
>        `VAR3=V3_VARIABLES`
>        `VAR4=V4_VARIABLES`
>
> Given the above, the robot would be run with `VAR1=V1_CMDLINE`, `VAR2=V2_VARFILE1A`, `VAR3=V3_VARFILE2`, and `VAR4=V4_VARIABLES`.

**Comment by pekkaklarck** [comment]
Thanks for the suggestions. Unfortunately it's not that easy to read and fully understand them when they are here as a comment. A pull request would make that *a lot* easier. Notice also that it's not technically correct to say that variables are got from a "Python script file" when the framework actually imports the file as a module.

I read the variable file section again with the above suggestions in mind and did some changes that were committed in b4b53d36bfb4e4b415242e63ca7398e9621a5d3e. I did changes like changing section title from "Creating variables directly" to "Getting variables directly from a module" and also added a note that when using this approach you cannot use arguments. Otherwise how to use arguments seems to be pretty well explained.

If you think documentation could/should still be enhanced, please submit a separate issue and/or PR. All kind of enhancements to the User Guide are very highly appreciated.
