### ISSUE TITLE
When use robotframework-run-keyword-async face error

### ISSUE THREAD

**Issue by k870611** [robotframework/robotframework#3237]
I write a test case - 
 
*** Settings ***
Library           runKeywordAsync

*** Test Case ***
async_test
    Run Keyword Async    Log    Hello

And it will cause error - 
20190711 09:00:44.663 : FAIL : AttributeError: Can't pickle local object 'runKeywordAsync._threaded..wrapped_f'

Then I remove  wrapped_f of def _threaded (runKeywordAsync - runKeywordAsync.py) to outside, it will report (but test result is pass)

async_test
"Hello back in main process and waiting for threads"
.
"Done with execution with output"
async_test                                                            | PASS |

Async Test                                                            | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed

Output:  D:\robotframework\robot_framework\output.xml
Process Process-1:
Traceback (most recent call last):
  File "d:\python35\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "d:\python35\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "d:\python35\lib\site-packages\runKeywordAsync\runKeywordAsync.py", line 78, in wrapped_f
    ret = BuiltIn().run_keyword(keyword, *args)
  File "d:\python35\lib\site-packages\robot\libraries\BuiltIn.py", line 1616, in run_keyword
    print(self._context)
  File "d:\python35\lib\site-packages\robot\libraries\BuiltIn.py", line 61, in _context
    return self._get_context()
  File "d:\python35\lib\site-packages\robot\libraries\BuiltIn.py", line 68, in _get_context
    raise RobotNotRunningError('Cannot access execution context')
robot.libraries.BuiltIn.RobotNotRunningError: Cannot access execution context

How to solve this error??

**Comment by pekkaklarck** [comment]
I don't know the runKeywordAsync library, but this looks more like a bug in that library than in Robot. Have you reported the problem to its issue tracker or contacted its developers otherwise?

**Comment by pekkaklarck** [comment]
This is unlikely to be a problem in RF itself. If it is, or if this library needs some new API, this issue can be reopened or new one created.
