### ISSUE TITLE
move keyword completion functionalilty to core framework

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#324]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=324) by bryan.oakley on 5 May 2009_

I would like a method on a FileSuite object that can return a list of all
the possible keywords, taking into consideration libraries and whatnot. In
effect, I want a single call that can return all the information needed to
implement the keyword completion feature used in RIDE.

I assume this code already exists in RIDE, but I think it would be better
to move it into the core framework. This would make it easier to write
additional tools that manipulate robot test suites. For example, one could
easily build a tool that checks that all keywords used in a test file are
valid. 

For example, to display a list of keywords valid for a file I would like to
be able to do something like this:

```
suite = TestSuite("foo.tsv")
print "all valid keywords for foo.tsv:"
for keyword in suite.valid_keywords:
    print keyword.name, keyword.args, keyword.description
```

**Comment by pekkaklarck** [comment]
I don't think this makes sense. Python packaging system has improved and keyword completing logic could be made available separately. We should rather try removing extra functionality from the core framework.
