### ISSUE TITLE
BuiltIn: Support stripping whitespace with `Should Be Equal` and other comparison keywords

### ISSUE THREAD

**Issue by lucielavickova** [robotframework/robotframework#3240]
Would it be possible to add "**trim**" parameter to keyword "**Should Be Equal As Strings**" (+related keywords)? 
Many times I need to compare two strings, but there are some trailing or leading whitespaces in the actual value, which I don't care about, so I always have to trim them before. Having trim as a parameter in these keywords would help me a lot :)

**Comment by pekkaklarck** [comment]
This is a good idea. Should also have an option to collapse internal spaces and to normalize spaces so that newlines, tabs, and non-ASCII spaces are all converted to spaces. Also, should support trimming/stripping from both ends and only from left/right.

Implementing something like this is very easy by using Python's string methods (and regexps when normalizing whitespace). The hard part is designing how to configure all this, but perhaps it would be fine to have separate options like `strip_spaces=False`, `collapse_spaces=False`, and so on. Exact argument names (`strip` vs `strip_spaces` vs `strip_whitespace`) are also subject to some discussion.

Would you @lucietriskova be interested to implement this enhancement? As I already wrote, implementation ought to be pretty easy and I can help if needed.

**Comment by lucietriskova** [comment]
ok, I think next week I could start working on it

**Comment by pekkaklarck** [comment]
Great! Let me know if I can help somehow. We can discuss about the design here or on the `#devel` channel on our Slack.

**Comment by sohum** [comment]
Hey guys! I'd be happy to take a stab at this, @lucielavickova have you had a chance to get started on it?

**Comment by lucielavickova** [comment]
hey @sohum, feel free to do it, I did not find time to have a look yet. Thank you!!!

**Comment by sohum** [comment]
> This is a good idea. Should also have an option to collapse internal spaces and to normalize spaces so that newlines, tabs, and non-ASCII spaces are all converted to spaces. Also, should support trimming/stripping from both ends and only from left/right.
> 
> Implementing this is pretty easy by using Python's string methods (and regexps when normalizing whitespace). The hard part is designing how to configure all this, but perhaps it would be fine to have separate options like `strip_spaces=False`, `collapse_spaces=False`, and so on. Exact argument names (`trim` vs `strip` vs `strip_spaces` vs `strip_whitespace`) are also subject to some discussion.
> 
> Would you @lucietriskova, or someone else, be interested to implement this enhancement? As I already wrote, implementation ought to be pretty easy and I can help if needed. This could easily be included in RF 3.2 if we found someone interested to contribute.

Hey @pekkaklarck ! Just want to make sure I've understood the task correctly, the following are the options we want to add to Should Be Equal As Strings

- `strip_leading_spaces`: Strips all leading spaces.
- `strip_trailing_spaces`: Strips all trailing spaces.
- `strip_spaces`: Strips all leading and trailing spaces.
- `collapse_spaces`: Strips any non-leading or non-trailing (ie. internal) spaces..
- `normalize_string`: Converts newline characters, tabs, and non-ASCII characters to spaces.

Is it correct to assume that when wanting to strip and/or collapse spaces, that we'd also like to strip newline characters, tabs, etc.? Or do we want to preserve them? Would love your opinion on the suggested option names above as well, or we can take that discussion to `#devel`.

**Comment by pekkaklarck** [comment]
Good question. I haven't thought about all the details so we can design this together. I'd like configuration to be flexible but also easy to use. The latter means wr shouldn't add too many new arguments. Perhaps these would be enough:

- `strip_spaces=False`: Possible values `True` (strip leading and trailing spaces), `leading` (only leading) and `trailing` (only trailing)
- `normalize_spaces=False`: When set to true, convert all whitespace characters to normal spaces, strip leading and trailing spaces (this coul be configurable but I doubt it's useful), and collapse consequtive internal spaces to a single space

What do others think?

**Comment by anshks** [comment]
@lucielavickova in which file can i find this keyword? I would like to add the trim param.

**Comment by anshks** [comment]
@sohum looking up to you (y)

**Comment by connnywilmeringBA** [comment]
https://www.youtube.com/watch?v=uFYQv9HDAXk

**Comment by vokiput** [comment]
Looks like it was not implemented yet.
I have started my implementation of this and have questions:
1. In this feature, we are talking about whitespace only. New-line is not whitespace. 
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#space-separated-format
2. strip_spaces
2.1. False - do not stripe anything
2.2. leading - stripe leading whitespaces
2.3. trailing - stripe trailing whitespaces
2.4. True - stripe leading and trailing whitespaces
3. collapse_spaces
3.1. False - do not collapse whitespaces
3.2. True - Collapse consecutive whitespaces into one space
4. Impacted keywords:
4.1. should be equal - if we compare 2 strings
4.2. should not be equal - if we compare 2 strings
4.3. should be equal as strings
4.4. should not be equal as strings
4.5. should start with
4.6. should not start with
4.7. should end with
4.8. should not end with
4.9. should contain
4.10. should not contain
4.11. should contain x times

**Comment by humbienri** [comment]
Wouldn't this all be achievable using the Extended Variable Syntax approach and just leveraging straight up Python?

**Comment by pekkaklarck** [comment]
Answers/comments to questions by @vokiput:

1. Newline is generally considered whitespace. In practice this implementation should simply call `strip()`, `lstrip()`, or `rstrip()` as needed. Notice that I'd still use `strip_spaces`, not `strip_whitespace` as argument name as the latter is so long. Explaining that all whitespace is stripped can be done in the documentation.

2. Looks good to me. `leading/trailing` should be case-insensitive.

3. Looks good to me.

4. On a quick look the list looks good. Basically these options should be added to same keywords that got `ignore_case` option in RF 3.0 (#2439).

**Comment by pekkaklarck** [comment]
You are @humbienri right that stripping spaces can be implemented using extended variable syntax. That's not true with collapsing spaces, though, but you could use the new inline Python evaluation syntax. Having built-in support in Robot makes the data easier to understand as these examples demonstrate:

```
    Should Be Equal    ${result.strip()}    expected result
    Should Be Equal    ${result}    expected result    strip_spaces=True

    Should Be Equal    ${{' '.join($result.split())}}    expected result
    Should Be Equal    ${result}    expected result    collapse_spaces=True

    Should Be Equal    ${{' '.join($result.rstrip().split())}}    expected result
    Should Be Equal    ${result}    expected result    strip_spaces=TRAILING    collapse_spaces=True
```

**Comment by pekkaklarck** [comment]
We have #3585 implementing this. I don't have time to review it now, but I add this to RF 3.2.2 scope so that I don't forget about it. RF 3.2.2 is mainly for bug fixes, but this ought to be safe to be included. If it looks too risky, we then can include it in RF 3.3.

**Comment by pekkaklarck** [comment]
PR #3583 has some problems making it impossible to merge it before RF 3.2.2. I hope we get the PR fixed or a new one created before the next release that's going to be RF 4.0. Introducing this kind of relatively big changes in a major release and not a patch release is probably better anyway.

**Comment by pekkaklarck** [comment]
No new activity related to this issue lately. I'll remove this from RF 4.0 scope now but if someone is interested to look at creating a PR adding this back can be considered.

**Comment by vokiput** [comment]
Hi, I did MR for the issue one more time.
https://github.com/robotframework/robotframework/pull/3813
Sorry for the delay.

**Comment by pekkaklarck** [comment]
I've been busy with RF 4.0 work and [RoboCon](https://robocon.io) planning but finally had time to look at PR #3240. I didn't have high hopes to get it into RF 4.0 anymore, but turned out that the PR was in such a great shape that it can be merged right away. I'll do some fine tuning to the code and docs afterwards.

Great work @vokiput!

**Comment by pekkaklarck** [comment]
Notice support for collapsing spaces was not added. A separate issue can be submitted about it.

**Comment by vokiput** [comment]
Okay, I will do it soon.
