### ISSUE TITLE
Keywords running other keywords and checking their status don't handle `Pass Execution` correctly

### ISSUE THREAD

**Issue by MariuszJanczura** [robotframework/robotframework#3243]
Hello,
The below code

Pass Execution due to documentation:
"Skips rest of the current test, setup, or teardown with PASS status." so when using Run Keyword And Return Status with only Pass Execution keyword in it should return True (if Pass Execution returns PASS status).

I've tried the code:

```
*** Settings ***

Documentation
...    Testing Pass Execution

*** Test Cases ***

Testing pass execution
    ${PE_status}=    Run Keyword And Return Status    PE test
    Log To Console    PE_status: ${PE_status}

*** Keywords ***

PE test
    Pass Execution    All features available in this version tested
```

I've got the result:

> 
> ==============================================================================
> PE status :: Testing Pass Execution
> ==============================================================================
> Testing pass execution                                                .PE_status: False
> Testing pass execution                                                | PASS |
> ------------------------------------------------------------------------------
> PE status :: Testing Pass Execution                                   | PASS |
> 1 critical test, 1 passed, 0 failed
> 1 test total, 1 passed, 0 failed

The PE_status if False and I think it should be True as this was executed successfull.y

**Comment by pekkaklarck** [comment]
Interesting. My guess is that in addition to `Run Keyword And Return Status` also `Run Keyword And Ignore Error` and `Wait Until Keyword Succeeds` are also affected. Not sure how `Run Keyword And Expect Error` even should behave in this case.

**Comment by pekkaklarck** [comment]
My initial analysis was wrong and Robot actually behaves as expected here. `Pass Execution` promises that the test passes no keywords are executed afterwards (except for teardows). In the original example `Log To Console` is thus never executed. As I already wrote, this is by design.

**Comment by MariuszJanczura** [comment]
Hello,
what about executing particular keyword (for example with Loop/Loops), passing it's output to a variable and checking condition in the loop? 

```
${passed} =    Run Keyword And Return Status    Example_Keyword
Run Keyword If    ${passed}    Another_Keyword

*** Keywords ***

Example_Keyword
    :FOR    ${s}    IN    @{something}
      \    Run Keyword If    ${s}'=='0')    Pass Execution    Passing
```

If the condition is true (example '${s}'=='0') then I would like to pass the execution for the whole keyword to stop executing loop and give the feedback that at least one of the elements have met my condiditons.
Having that I would have passed keyword and variable having "True" value and that would could give a possibility to use it in this example. Wouldn't it be helpful?

Also: https://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Pass%20Execution
documentation is not telling about that my example is not supported. Also, it should be also "True" for the sake of meaningfulness of PASSing something. What do you think?

**Comment by pekkaklarck** [comment]
Idea of this kw is to stop the test and mark it passed. Docs say that rest of the kws are not executed. If you want to exit a keyword, use `Return From Keyword (If)` instead.
