### ISSUE TITLE
Create a shim logging API, to unify `logging` and `robot.api.logger`

### ISSUE THREAD

**Issue by stdedos** [robotframework/robotframework#3248]
https://robotframework.slack.com/archives/C3C28F9DF/p1564039943037200

@pekkaklarck 
> You mean an API like logger.debug('foo %s', 'bar') that the logging module has?  'I doubt performance benefits would be that big and it wouldn't work with f-strings. Such support could be added if someone demonstrated it's actually useful and would also provide a PR.

@(me)
I cannot seriously argue one way or another; it's just both loggers have small differences between them; robot has TRACE level, logger (and other logging frameworks) seem to prefer lazy format evaluation than a pre-formatted string.

@pekkaklarck 
> We could pretty easily make it possible to use "lazy logging" by allowing messages to be logged to be callables that return the actual message and that are called only if that particular messages is actually used. We already use that approach internally and could expose it publicly if there are concrete needs.

@(me)
I have really no concrete case myself; in a way, I feel that, if I wanted performance, I wouldn't be writing python (I believe that "lazy logging" is a performance thing? mostly?)

I simply don't like the segregation (I forgot the proper word) of how to format a string between `Exception`s, `logging`, `logger`, `print` etc etc ...

@pekkaklarck 
```python
try:
     from robot.api.logger import logging_facade as logging
except ImportError:
    import logging
```

**Comment by pekkaklarck** [comment]
Do you @stdedos remember what this issue was about? Is there some concrete enhancement to be made?

**Comment by stdedos** [comment]
Improve `robot.api.logger.info` calls to be compatible to `logging.info` calls.
Specifically, `logger.lvl` calls should accept `('%s', *args)` and autoformat them.

Calling like that makes the concatenated string evaluation lazy, and helps when a loglevel is disabled.

PS:
* I know that `robot` is fine with `logging.lvl` calls, but I am not sure "how much". e.g. `logging.trace` does not exist
* I understand that `%s` is the Python2 soon-to-be EOL way, but for some reason `logging` package hasn't been updated.

**Comment by pekkaklarck** [comment]
I don't want to add arguments to Robot's logger just to make it compatible with `logging`. A better idea would be creating a separate higher level logger that delegates to either one of them, depending on is Robot running or not. I don't think it belongs to RF core, though, it could be a separate project instead.

An alternative is just always using `logging`, messages logged with end up to Robot's log automatically anyway. Only feature it lacks compared to Robot's own logger is the ability to log HTML messages. That limitation could be lifted pretty easily, but it would need a separate issue.

I think this issue can be closed.
