### ISSUE TITLE
Listeners cannot add/remove tests in their `start/end_test` methods

### ISSUE THREAD

**Issue by mikaukora** [robotframework/robotframework#3251]
### Overview

Default Robot FW running logic doesn't allow
modification of test/task case execution order after
case execution has been started. In other words,
it is not possible to make decision about the
next executed test/task case after executing a case.

For example, consider a test script file defining following
test/task cases: case A, case B, case C.
The default logic executes the cases in order: A, B, C.

Some use cases would require different kind of logic to decide
the execution order. E.g. the case A would run, and then a
decision would be made whether B or C should be run: A -> B or A -> C. 
Or a case would be repeated based on some condition: A, A, B, C, C, C etc.

An example of this kind of required functionality would be
RPA task flow where the task case execution
is like a flow chart. There are dependencies between
cases and the order of cases depends on the result
of previous cases. A decision about the next executed
case can be done only after executing the previous case.

Other examples would be looping scenarios (same case is 
executed multiple times based on some logic such as status check) and 
model based testing (tests are generated dynamically during the execution)
to name a few.

### Implementation details

Current implementation is as follows, for reference.

**run.py**
class RobotFramework(Application) builds test suite
and calls suite.run().

**model.py**
class TestSuite(model.TestSuite) implements run() method
and visits suite with self.visit(runner). Runner's type is
class Runner(SuiteVisitor).

**testsuite.py**
class TestSuites(ItemList) collects suites of type
class TestSuite(ModelObject). TestSuite implements
visit() method, called by model.py:

```
    def visit(self, visitor):
        """:mod:`Visitor interface <robot.model.visitor>` entry-point."""
        visitor.visit_suite(self)
```

**visitor.py**
SuiteVisitor class implements visit_suite method:

```
class SuiteVisitor(object):
    def visit_suite(self, suite):
        if self.start_suite(suite) is not False:
            suite.keywords.visit(self)
            suite.suites.visit(self)
            suite.tests.visit(self)
            self.end_suite(suite)
```

Call to suite.tests.visit causes all tests in class TestCases(ItemList)
to be visited. This logic is problematic in this case. Also it seems that
it is not possible to modify this functionality via listener interface,
as it doesn't allow overwriting visit_suite method.

I've experimented by implementing own visit_suite method in 
class Runner(SuiteVisitor) (runner.py). This allows writing
own logic for visiting suite.tests.

### Change proposal

One way to allow users to control test execution more freely would 
be to add visit_suite method to listener interface. I'm creating
this issue to figure out other options for implementation. The end
goal would be to make it possible to overwrite the test/task case
execution logic for special use cases such as RPA.

**Comment by pekkaklarck** [comment]
Did I get it right that what you try to do is modifying executed tests in listener `start_test` and/or `end_test` methods and that doesn't work?` If yes, then the issue doesn't have anything to do with the visitor interface because listeners don't use that API.

Anyway, the underlying issue is real and has caused problems also earlier. Luckily it also seems to be relatively easy to fix. I did some prototyping and got a simple example working with the changes below. I still need to create more tests before committing changes, and it will take a little time due to me just returning from holidays and the new parser work having higher priority. Anyway, if you are interested to test this just make these changes yourself:

```diff
diff --git a/src/robot/model/itemlist.py b/src/robot/model/itemlist.py
index 16713ec..f4d2c89 100644
--- a/src/robot/model/itemlist.py
+++ b/src/robot/model/itemlist.py
@@ -68,11 +68,14 @@ class ItemList(object):
         self._items = ()
 
     def visit(self, visitor):
-        for item in self._items:
+        for item in self:
             item.visit(visitor)
 
     def __iter__(self):
-        return iter(self._items)
+        index = 0
+        while index < len(self._items):
+            yield self._items[index]
+            index += 1
 
     def __getitem__(self, index):
         if not isinstance(index, slice):
```

Notice also that modifying executed tests in `start_suite` method is possible already now.

**Comment by mikaukora** [comment]
I have following example code but it doesn't work as expected.
Assume the script defines following cases: 'Start', 'End'.
Now I'm running 'Start' successfully but it is not possible to modify
test case list _after_ 'Start' case has completed. The idea would be
to insert other cases dynamically, like 'End' has been added below.
Now, I suppose because of list iteration, the 'End' is not taken into
account in the list.

`""" Usage:
robot --listener LiveMod.py test.robot
"""
import copy


class LiveMod(object):

    ROBOT_LISTENER_API_VERSION = 3

    def str2test(self, testname, tests):
        """ Return test case object based on testname. """
        for t in tests:
            if testname == t.name:
                return t
        return None

    def start_suite(self, data, result):
        print("Running suite: {}".format(data))
        print("Available tests: {}".format(data.tests._items))
        
        # Copy available tests and clear the actual execution list
        self.orig_tests = copy.deepcopy(data.tests)
        data.tests.clear()
        
        # Append some case to execution list
        test_case = self.str2test('Start', self.orig_tests)
        data.tests.append(test_case)
        
    def start_test(self, data, result):
        print("Running test: {}".format(data))
        print("Available tests: {}".format(data.parent.tests._items))
            
    def end_test(self, data, result):
        print("Ending test: {}".format(data))
        
        # Append some case to execution list.
        # This doesn't work
        test_case = self.str2test('End', self.orig_tests)
        data.parent.tests.append(test_case)
        print("Available tests: {}".format(data.parent.tests._items))
`

**Comment by pekkaklarck** [comment]
Did you try that with changes in my previous comment?

**Comment by pekkaklarck** [comment]
Below is a simpler example demonstrating the same problem. It works with the above changes but not without.

```python
class TestAdder:
    ROBOT_LISTENER_API_VERSION = 3

    def end_test(self, test, result):
        suite = test.parent
        if test == suite.tests[-1] and test.name != 'Added':
            suite.tests.create(name='Added')
```

**Comment by mikaukora** [comment]
You are correct, there was some issue when applying the patch.
My example code works now as expected. 

Now it is possible to modify tests during execution, for example in
- start suite; e.g. to define what case should be run first, and in
- end_test; e.g. to define what case should be executed next

This allows extending the default running logic for special purposes such as RPA.

**Comment by pekkaklarck** [comment]
Great to hear that the fix works! I'll add some tests for it and commit changes once they are ready.

**Comment by pekkaklarck** [comment]
Although I changed the title to be listener specific and the listener interface doesn't use the visitor API, the problem also affected visitors to same extend. The change to the `visit()` method fixes that as well.
