### ISSUE TITLE
How to upload file using window dialog box in Robot Framework?

### ISSUE THREAD

**Issue by mohamedece09** [robotframework/robotframework#3253]
In my application I have a dropzone(Which is not having input type = file) where I can upload files using window dialog box. But using Choose File Keyword, I am not able to upload file, because which is not pointing to .

Below is the xpath for that element, //*[@id="scroller"]/div[3]/xyz-dropzone

Can someone please help me to solve this ? Do we have any keyword to upload file for dropzone ?

I have tried below which is not working, Choose File //*[@id='scroller']/div[3]/xyz-dropzone C:\Users\User1\Desktop\Skype issue.png./

Below is the xpath for that element, //*[@id="scroller"]/div[3]/xyz-dropzone

Getting below error,

"Element not interacted".

**Comment by mohamedece09** [comment]
Hi,

Any update on this ?

**Comment by sebastianciupinski** [comment]
This is not forum. Ask on stackoverflow.

**Comment by pekkaklarck** [comment]
Yeah, this issue tracker is for bug reports and enhancement requests. Questions are best asked on mailing lists, Slack, or other such support forums listed at http://robotframework.org. Also, this tracker is only for Robot Framework itself. For example SeleniumLibrary has its own tracker for its bug reports and enhancement requests.
