### ISSUE TITLE
I had a problem，Ask for advice

### ISSUE THREAD

**Issue by clclclclclclcl** [robotframework/robotframework#3256]
[ WARN ] Error in file 'd:\k0171221\Desktop\Tzpt_AutoTest\TZPT\Keywords\YWKeywords.robot': Invalid syntax in keyword '新建T+1投资建议书': In '[Arguments]' setting: Ignoring lines with only continuation marker '...' is deprecated.   

I don't know why this other case is not a problem. They are basically the same.

**Comment by Thomas-Baeckeroot** [comment]
This is a new warning caused by a change in last v5.1.2 RF syntax.
As it says: most likely caused by a continuation line that contained no command (empty or only comment).
Simply remove the '...' or replace them by '#'.
