### ISSUE TITLE
get_keyword_names failing because of connection to remote server port changing for each run

### ISSUE THREAD

**Issue by gamer20052** [robotframework/robotframework#3258]
Hello,
I am trying to get a Jenkins server to run my local RF script. The library being used is Sikuli. Based on the error, I may need to set the port for IP address 127.0.0.1, which I thought was already defaulted. From the RF Sikuli Library github, I tried starting the Sikuli process manually but it provided the same error. The script itself is successful when ran from the command line.

The Jenkins project itself is very simple and has all required environmental variables to run any shell scripts called. A short snippet of the report from Jenkins is shown below.

+ robot test5.robot
[ WARN ] Test get_keyword_names failed! Connecting remote server at http://127.0.0.1:46775/ failed: <Fault 0: 'Failed to invoke method get_keyword_names in class org.robotframework.remoteserver.servlet.ServerMethods: java.lang.RuntimeException'>
[ ERROR ] Error in file '/home/ale/robot/test5.robot': Initializing test library 'SikuliLibrary' with no arguments failed: Failed to get_keyword_names!
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/SikuliLibrary/sikuli.py", line 54, in __init__
    self.start_sikuli_process(port)
  File "/usr/lib/python2.7/site-packages/SikuliLibrary/sikuli.py", line 93, in start_sikuli_process
    self.remote = self._connect_remote_library()
  File "/usr/lib/python2.7/site-packages/SikuliLibrary/sikuli.py", line 208, in _connect_remote_library
    self._test_get_keyword_names(remote)
  File "/usr/lib/python2.7/site-packages/SikuliLibrary/sikuli.py", line 225, in _test_get_keyword_names
    raise RuntimeError('Failed to get_keyword_names!')

**Comment by pekkaklarck** [comment]
This looks more like SikuliLibrary issue and should be reported to its tracker. Or do you think the problem is somehow on Robot's side?

**Comment by gamer20052** [comment]
Thank you, I was hoping for a confirmation as I wasn't sure whether the remote server connection was a Sikuli or Robot Framework issue.
