### ISSUE TITLE
Document that Tidy with `--recursive` doesn't process resource files

### ISSUE THREAD

**Issue by lynhbn** [robotframework/robotframework#3260]
Environment:

> Robot Framework 3.1.2
> Mac OS 10.13.6
> Python 2.7.10

I'm now using robot.tidy tool to apply the new FOR loop syntax for my project

Tidy still works properly with the normal mode 
`python -m robot.tidy --inplace keyword_sample.robot`

But `python -m robot.tidy --recursive <project_folder>` does not work at all. Nothing happens after executing this command

Please help to take a look.

Thank you!

**Comment by pekkaklarck** [comment]
Works for me.

**Comment by lynhbn** [comment]
> Works for me. Can you test again? If it still fails, you'd need to provide some more information.

I think I could reproduce this one.
I tried mode --recursive with robot file containing ***Test Cases*** -> it works normally
I tried mode --recursive with robot file only containing ***Keywords*** or ***Variable*** -> nothing happens

**Comment by pekkaklarck** [comment]
I think that's a known limitation/bug occurring also with earlier versions.

**Comment by pekkaklarck** [comment]
Yeah, this is a known issue. One problem with processing resource files has been that if you were changing format, also imports would have need to be updated like `resource.html` -> `resource.robot`. Now that we will only support the plain text format in RF 3.2, that problem isn't anymore relevant. Another problem is that resource imports can lead to files outside the directory given as an argument to Tidy and it's a bit questionable is that fine or not. Separate command line option could be added to control the behavior if needed, though, and it could perhaps be used also when tidying a single file.

Things we can do:

- Document that `--recursive` doesn't process resource files. I changed the title of this issue to cover that.

- Actually add the functionality to process resource files. Separate issue should be submitted about it.
