### ISSUE TITLE
Robot Tests taking time to actually kick off after batch file has been kicked off

### ISSUE THREAD

**Issue by VarunJoshi** [robotframework/robotframework#3262]
I am not sure if people here can answer this but worth a try.

We have a bamboo script that kicks of some automated robot tests (About 100) but after they have been kicked off, it takes about 2 hours for them to actually start running (Executing). It appears its not the host machine where the tests are started but the machine where the keywords are processed (our keyword server) which is causing this delay in executing the test's setup step. 

I wasn't able to find anything on the logs.

Appreciate the help!

**Comment by pekkaklarck** [comment]
This is most likely some kind of environment issue. With this information and without access to your environment it isn't possible for others to help you. If you have some more information, you may want to ask on mailing lists or Slack has anyone else had similar issues. This issue tracker is for concrete bug reports and enhancement requests.
