### ISSUE TITLE
Tidy does not preserve data before first section

### ISSUE THREAD

**Issue by ptman** [robotframework/robotframework#3263]
Currently it seems to strip comments. (robot 3.1.2)

**Comment by pekkaklarck** [comment]
Works for me. Can you provide an example that doesn't work?

**Comment by ptman** [comment]
python -m robot.tidy issue3263.robot

issue3263.robot:
```
# Copyright foo
*** Settings ***

*** Variables ***

*** Test Cases ***

*** Keywords ***
```

output has the comment stripped

**Comment by pekkaklarck** [comment]
This is due to the current parser ignoring everything before the first section. The new parser (#3076) ought to fix it. Otherwise comments ought to be preserved.
