### ISSUE TITLE
`--test/--suite/--include/--exclude` don't affect tests added by pre-run modifiers

### ISSUE THREAD

**Issue by JockeJarre** [robotframework/robotframework#3265]
I was testing an interesting plugin for Robot Framework called https://github.com/Snooz82/robotframework-datadriver which can generate tests automatically using different input files. This works great, but if you want to involve pabot (using --testlevelsplit) there is a problem which I want to describe here.

I try starting the test both, as described in robotframework-datadriver as a library which activates a listener and I also tried modifying robotframework-datadriver to use the --prerunmodifier, to get the test generation run "earlier" in the process.

But both these tests fail because pabot starts the robot instances with the --test "Test Name" parameter and robot framework cannot find the automatically generated tests at this "early stage".

Would it be possible to get the --test parameter to filter the tests to run, after the prerunmodifier has finished? I assume the library listener is far to late in the process though...

**Comment by pekkaklarck** [comment]
I don't remember was there some reason why we decided to do filtering based on `--test/--suite/--include/--exclude` first and only then run pre-run modifiers. Now that I think about it, running modifiers first and allowing using standard options to filter possibly added tests afterwards makes more sense. Changing the order is obviously trivial and updating tests and docs shouldn't be too much work either. The change would be backwards incompatible, but doing it in a major release ought to be fine.

Have you @JockeJarre tested does changing the order actually fix the issue? If it does, would be you be interested in creating a PR?

**Comment by JockeJarre** [comment]
The problem comes up when using pabot together with the datadriver plugin. I am discussing with mkorpela (pabot) and René (datadriver) on slack and we (actually they) try to solve it between these two components and call robot differently. It would mean we would not have to change anything in robot.
Anyway good to hear your thought on maybe changing it here.
Depending on how far we come with the ideas from above I would try to make a PR.

**Comment by pekkaklarck** [comment]
Yeah, I saw that discussion as well. The problem is that data-driver is a listener (i.e. used at execution time) and `--test` and others need to be used before execution starts. If it could be changed to pre-run modifier then this change ought to help.

**Comment by JockeJarre** [comment]
The issue is now fully solved between Pabot and datadriver https://github.com/mkorpela/pabot/issues/187 so this issue can be closed!

So with datadriver we can dynamically create variations of tests from a datafile and pabot is able to start them all in parallel. 

Thanks for your support

**Comment by pekkaklarck** [comment]
It's great that the original issue is resolved. I still think running modifiers before filtering based on cli options should be considered. I'll reopen this issue to use it as a reminder.

**Comment by JockeJarre** [comment]
shall we change the title then to reflect more what is meant?

**Comment by manishkumar112** [comment]
@pekkaklarck I am using prerunmodifier and facing this issue - dynamically generated tests does not gets included/excluded or failed test rerun gets those tests.
Is this issue being planned to be fixed soon or suggestion to workaround it?

**Comment by pekkaklarck** [comment]
Added this to RF 3.2 scope.

**Comment by pekkaklarck** [comment]
The change was as trivial as I expected. I was a bit surprised that we actually had tests for running modifiers after other config, but because there was no reasoning why that decision was done initially I simply updated those tests. All other tests passed with these changes. I'll still take a look should the User Guide be updated, but otherwise this is about to be ready.
