### ISSUE TITLE
Unable to connect Cassandra DB due to "invalid literal for int() with base 10: '4-E001'" error

### ISSUE THREAD

**Issue by gelato7311** [robotframework/robotframework#3266]
In our company we have a customized Cassandra version (i.e. [cqlsh 5.0.1 | Cassandra 3.11.4-E001 | CQL spec 3.4.4 | Native protocol v4]). 

As a result It is showing us error while we are trying to connect with Cassandra. As I can interpreter that the standard library function is expecting integer and it is not getting integer value and thus this error is showing. I tried to find that library function, but couldn't get that detail. Please help to fix this. 

The Error is showing like: 

Keyword 'KW_Connect_to_Cassandra_DB_GUI' failed after retrying 2 times. The last error was: Connect to Cassandra error: ('Unable to connect to any servers', {'10.210.156.142:30060': ValueError("invalid literal for int() with base 10: '4-E001'",)})

![Cassandra connection error](https://user-images.githubusercontent.com/40338396/62921694-09ad3a80-bdc7-11e9-8203-6dbd51d18cdd.jpg)

**Comment by pekkaklarck** [comment]
This issues seems to be in the CasandraLibrary, not in Robot Framework itself. It should be reported to its issue tracker.

**Comment by gelato7311** [comment]
There is no such active group for CasandraLibrary or I am unable to find any. Since this library is for Robot Framework, It would be great if any one can help to resolve this.

**Comment by pekkaklarck** [comment]
You can use Robot Framework mailing lists, Slack, or other such support forums for questions. This issue tracker is nevertheless only for bugs and enhancement requests related to RF itself.
