### ISSUE TITLE
Robot scripts can be run using octane?

### ISSUE THREAD

**Issue by NarasimhaMokara** [robotframework/robotframework#3270]
Hi All,
can someone explain me how to execute ROBOT scripts using Octane.
can you also share the sample code, if you have any.

Thanks & Regards,
Narasimha Mokara

**Comment by pekkaklarck** [comment]
This issue tracker is for bug reports and enhancement requests, questions should be sent to mailing lists, Slack, or other such forums listed at http://robotframework.org. Also, I have no idea what Octane is.
