### ISSUE TITLE
Unable to reuse library alias outside of library scope

### ISSUE THREAD

**Issue by EagleZR** [robotframework/robotframework#3272]
The library scope is set to `Test Case`, but when a test tries to implement a library using an alias that was previously used in another test, the original instance is used.

Test:
```
*** Settings ***

*** Test Cases ***
MyTest1
	[Documentation]    Instantiating with an alias.
	import library  pack1.pack2.TestLib    test1    WITH NAME    Lib1
	Lib1.Print Message

MyTest2
	[Documentation]    Reusing library alias outside of scope.
	import library  pack1.pack2.TestLib    test2    WITH NAME    Lib1
	Lib1.Print Message
```

Library:
```python
import logging


class TestLib:
    ROBOT_LIBRARY_SCOPE = 'TEST CASE'
    
    def __init__(self, arg):
        self.message = arg
    
    def print_message(self):
        logging.warn(self.message)
```

Results:
```
==============================================================================
MyTest
==============================================================================
[ WARN ] test1
MyTest1 :: Instantiating with an alias.                               | PASS |
------------------------------------------------------------------------------
[ WARN ] test1
MyTest2 :: Reusing library alias outside of scope.                    | PASS |
------------------------------------------------------------------------------
MyTest                                                                | PASS |
2 critical tests, 2 passed, 0 failed
2 tests total, 2 passed, 0 failed
==============================================================================
```

Since the scope is set to `Test Case`, I would expect the message printed in MyTest1 to be "test1", however "test`" is printed from the library instantiated in MyTest`.

**Comment by pekkaklarck** [comment]
First of all, why do you need to reuse the same alias? Anyway, this behavior doesn't look right, but I'm not sure would the behavior you expect be correct either. I would actually say that it should be an error to use the same alias twice a single suite.

Notice that although you use `Import Library` in a specific test, the keywords in that library are visible also for subsequent tests in that suite. In that regard there's no real difference between using `Import Library` and the normal `Library` setting. The main motivation for using `Import Library` is that you can do some other actions before it to make sure the library actually can be imported. That could possibly be changed, but it would need someone needing it to implement the change and provide a pull request.

**Comment by pekkaklarck** [comment]
Just noticed we actually already have #2377 that describes the same problem. Somewhat related  #2106 was also just added to RF 3.2 scope. We can continue discussion about this issue in #2377.
