### ISSUE TITLE
Minor typo in userguide/src/Appendices/CommandLineOptions for --skipteardownonexit

### ISSUE THREAD

**Issue by kylekizirian** [robotframework/robotframework#3274]
There appears to be a minor typo in the CommandLineOptions.rst file for 

--skipteardownonexit    `Skips teardowns` is test execution is prematurely stopped.

It looks like the "is" should be an "if" i.e.

--skipteardownonexit    `Skips teardowns` if test execution is prematurely stopped.

**Comment by pekkaklarck** [comment]
Thanks!
