### ISSUE TITLE
[Feature Request] Enable separating concerns of file/folder naming and test suite names in output.xml

### ISSUE THREAD

**Issue by Tset-Noitamotua** [robotframework/robotframework#3279]
# File/Folder Names vs. Test Suite Names

When it comes to organizing big test suites on the hand you have to deal with naming of folders and files on your file-system on the other hand this directly impacts the look of RF's output results (log.html and report.html). See examples below

![image](https://user-images.githubusercontent.com/5635462/63635413-9925d980-c662-11e9-8b3e-3e8e9b2e98be.png)

![image](https://user-images.githubusercontent.com/5635462/63635478-78aa4f00-c663-11e9-8079-b96006557154.png)

It would be great if one would have more control about separating this concerns. I can think of at least three options:

## Option 1
When you use folders (and sub-folders) to organize your tests the log and report can become a bit hard to read (see screenshot below). Thus it would be handy to define test suite names via settings table of the test suite file - like this:

```robot
*** Settings ***
Name        What Ever Name You Want
```

## Option 2
Of course if you have 100 test suites (files) in a folder it could become tedious to set suite names that way. In that case it should be possible to do it in a `__init__.robot` file. But this would require to set the names dynamically, e.g. by taking only a substring of related filename(?) or any other approach.  Examples:

```robot
*** Settings ***
Name          ${no path}         # omitting relative path
Name          fetch from right ${*)}
Name          other ideas?
```

![image](https://user-images.githubusercontent.com/5635462/63634337-337f2080-c655-11e9-8795-5eed9e7d7441.png)

## Option 3
Alternatively I could think of a cli option like `--log-no-path` or `--report-short-suite-name` to omit the relative path of deepest test suite from log/report (green part in screenshot above).

**Comment by pekkaklarck** [comment]
First of all, it would be easy to clean up the suite names already now:
- Don't run that `robot` folder but instead run `contribution tests` directly.
- Rename `contribution tests` to something shorter or use `--name` option to rename it.

That said, being able to use `Name` setting to set a custom name to a suite would have its benefits. Most importantly it would allow using characters that cannot be used in  filesystem paths. If anything more complicated would be needed, it's possible to use pre-run modifier.

**Comment by Tset-Noitamotua** [comment]
@pekkaklarck  applied your suggestions :+1: 

![image](https://user-images.githubusercontent.com/5635462/64050082-4757e480-cb77-11e9-85a2-e2a6edb38be8.png)

**Comment by pekkaklarck** [comment]
Apparently you got it working well? If you still think `Name` setting to override suite name would be useful, please submit a separate issue covering only that (i.e. Option 1 in your original description).
