### ISSUE TITLE
Libdoc: Support automatic generation of table of contents when using "robot format"

### ISSUE THREAD

**Issue by aaltat** [robotframework/robotframework#3280]
It would be nice enhancement if `libdoc` could automatically generate table of contents in the keyword documentation. Although it's small amount of work to maintain, it's still something to be remembered when updating `__intro__` documentation.

It could be good idea to parse all first level headings (meaning `= heading one =`) from the `__intro__` documentation and turn those heading as toc. It could problematic to please the toc in the right spot, but that could be done by adding a marker in the documentation, example like `%TOC%`. 

SeleniumLibrary made an automatic [toc generation](https://github.com/robotframework/SeleniumLibrary/pull/1433/files#diff-40c471e982a520769c6721ee04a812cdR499) and there is a [marker](https://github.com/robotframework/SeleniumLibrary/pull/1433/files#diff-40c471e982a520769c6721ee04a812cdR499) where the toc is placed.

For more details about the SeleniumLibrary implementation, please see https://github.com/robotframework/SeleniumLibrary/issues/1430

**Comment by pekkaklarck** [comment]
Are you @aaltat interested to turn the SL solution into a PR?

**Comment by aaltat** [comment]
Well it sounds possible. I want to push SL 4.0 out first, one PR to close first and then making release candidate. But after that it should be possible.

**Comment by pekkaklarck** [comment]
Are you @aaltat still interest in creating a PR to implement this?

**Comment by aaltat** [comment]
I did forget this one, I have been having too much fun with the SL project, sorry. The SL does not have anything urgent at the moment, so I guess I could take a look. There is also the https://github.com/robotframework/PythonLibCore/pull/16 but I guess it can wait because it does not have a deadline. 

Do you recall the SL [implementation](https://github.com/robotframework/SeleniumLibrary/blob/master/src/SeleniumLibrary/__init__.py#L491-L505)? It works automatically and by using the dynamic library API, but I think the basic idea is OK. But how it should work with libdoc?  Should TOC be automatic or should it be controlled by a command line switch?

**Comment by pekkaklarck** [comment]
Great if you can help with this one. For me RF 3.2 has higher priority than PythonLibCore, but we can discuss that separately.

About the implementation:

- In my opinion the toc being generated automatically if there's a marker is fine. SL used `%TOC%` which is OK, but we could consider something more explicit (and even less likely to match accidentally) such as `%TABLE OF CONTENTS%`.

- I think it's fine if we only support the Robot format, not reST, HTML, or TXT. Others would be a lot more complicated, reST has its own toc support, I doubt these would be useful in general, and it's always possible to add support for them in the future if needed.

- It probably should work only with the generic library documentation. I don't see benefits individual keywords or `__init__` having a toc.

- Should work (and be tested) regardless how the doc is got: directly from the class, via the dynamic `get_keyword_documentation`, or from a resource file.

**Comment by aaltat** [comment]
Good work, sorry that I could not find time to properly finalize this one.

**Comment by pekkaklarck** [comment]
No worries!
