### ISSUE TITLE
When use listener version 3 i got   failed: TypeError: 'TestCase' object is not subscriptable

### ISSUE THREAD

**Issue by Chris19871003** [robotframework/robotframework#3282]
`I` am using robot framework 3 and trying to add a listener to test case, all i do is as below, 

```
class TestCaseListener:
    # ROBOT_LISTENER_API_VERSION = 2

    # IS_LOGIN = False

    ROBOT_LISTENER_API_VERSION = 3

    def __init__(self):
        self.TEST_CASES_MAP = None
        self.TEST_CASE_STS_MAP = {
            'PASS': 1,
            'FAIL': 2
        }

    def start_test(self, data, result):
        logger.warn(data)
        logger.warn(result)

    def end_test(self, data, result):
        tags = result['tags']
        sts = result['status']
```

and get a error response 
`[ ERROR ] Calling method 'end_test' of listener  failed: TypeError: 'TestCase' object is not subscriptable`

**Comment by pekkaklarck** [comment]
Objects passed to listener methods in listener v2 and v3 are different. You are using API v3 but use the object you get as if it was v2. This ought to be documented in the User Guide. If you cannot make it work, please send further questions to mailing list, Slack, or other such support forums. This issue tracker is only for bug reports and enhancement requests.
