### ISSUE TITLE
Resume Robot running with updated case version

### ISSUE THREAD

**Issue by JerryGeng1216** [robotframework/robotframework#3283]
I have a question about Robot Framework:

For example, I have 2 cases in a suite and I trigger the suite running for the 2 cases. After case 1 running finishes, I pause the running. Then I make some modification for case 2 and resume the running. However the Robot still run case 2 with the old version.

Is there any way to have Robot run case 2 with the updated version when resuming? I'm asking the question because it's important for my automation case writing/debugging. In some situation the automation suite setup requires about 20 minutes and I really hope to stay in the suite environment to write new case and make update based on the previous running result.

**Comment by yahman72** [comment]
FYI: some discussion about similar problem (long suite setup) and possible solution ideas in #3104 i.e. starting from comment https://github.com/robotframework/robotframework/issues/3104#issuecomment-469164339

**Comment by JerryGeng1216** [comment]
Thanks a lot for your information. For the following requirement:

==============================================================
At minimum it would good to maintain the execution context (e.g. global variables, and libraries) which could be used to store the "state" of the SUT. The rest could remain the same e.g. one output-file per rerun etc. In short: --rerunfailed automatically within the same execution context as the original suite.
==============================================================

It looks it's still not implemented, right?

**Comment by pekkaklarck** [comment]
There's no built-in functionality to support this and I don't think something like this belongs to the core framework. Such features could be provided by external tools, and Robot's public APIs (e.g. listeners) ought to make it possible to implement such a tool already now. If there would be concrete enhancements needed to the APIs, they can be addressed separately.
