### ISSUE TITLE
select  Datepicker wheel with appiumlibrary with robotframework.

### ISSUE THREAD

**Issue by zalie4869** [robotframework/robotframework#3287]
hi all , I have issue for select value picker wheel with appiumlibrary with robotframework. I want to select value for picker wheel but I can't set value for picker wheel .

![image](https://user-images.githubusercontent.com/29116619/63922644-40de4580-ca6f-11e9-9b65-d33ecbc88519.png)

**Comment by HelioGuilherme66** [comment]
This does not seem related with Robot Framework.

**Comment by pekkaklarck** [comment]
This tracker is for bug reports and enhancement requests related to Robot Framework itself. Issues related to external libraries and tools should be submitted to their own trackers and questions are typically best sent to mailing list, Slack, or other such support forums.
