### ISSUE TITLE
Can we use Python and Jython both as Suite executor in Robot Framework ?

### ISSUE THREAD

**Issue by cahshashank** [robotframework/robotframework#3298]
Requirement is to process a custom Java library and get a particular value(A).
Pass A to a python library which uses pandas module to process certain dependent files.

**Comment by pekkaklarck** [comment]
I doubt pandas works on Jython, but this ought to be possible by utilizing the remote library interface.

This issue tracker is for bug reports and enhancement requests. Please use robotframework-users mailing list, our active Slack community, or other such forums listed at robotframework.org for general questions and discussion.
