### ISSUE TITLE
Import protobuf generated descriptors class to Robot Framework

### ISSUE THREAD

**Issue by mmikirtumov** [robotframework/robotframework#3304]
I am trying to implement RPC call based on Protobuf. 
Could you please help me how can I import pb2.py descriptors python file into Robot Framework?
I created library which call remote server (based on Protobuf serialization), I need only to import descriptor classes and serialize and desalinize using pb2.py files.

**Comment by pekkaklarck** [comment]
I have no experience with Protobuf and don't understand what you are trying to do. Anyway, this issue tracker is for bug reports and enhancement requests. Questions and general discussion belongs to our mailing lists, Slack, or other such forums.
