### ISSUE TITLE
pip install robotframework-kafkalibrary gives error with python 3.7.4

### ISSUE THREAD

**Issue by koolestkrystal** [robotframework/robotframework#3310]
Hi,

I am getting the below error while trying to install the KafkaLibrary in Robot Framework on a Python 3.7.4.
Looking in indexes: https://pypi.python.org/simple
Collecting robotframework-kafkalibrary
  Downloading https://files.pythonhosted.org/packages/ad/10/f406e37b827a15125a27
0ca87e5894152885eb25da0875540b5bfbad8434/robotframework-kafkalibrary-0.0.2.tar.g
z (56kB)
     |████████████████████████████████| 61kB 491kB/s
    ERROR: Command errored out with exit status 1:
     command: 'c:\python3.7.4\python.exe' -c 'import sys, setuptools, tokenize;
sys.argv[0] = '"'"'C:\XXXXXXX~1\\AppData\\Local\\Temp\\pip-install-9ymoy2
38\\robotframework-kafkalibrary\\setup.py'"'"'; __file__='"'"'C:\\XXXXXX~
1\\AppData\\Local\\Temp\\pip-install-9ymoy238\\robotframework-kafkalibrary\\setu
p.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().repl
ace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'ex
ec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\XXXXXX~1\AppData\Local\Temp\pip-install-9ymoy238\robotfra
mework-kafkalibrary\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\XXXXXX~1\AppData\Local\Temp\pip-install-9ymoy238\robotframe
work-kafkalibrary\setup.py", line 6, in <module>
        execfile(join(dirname(__file__), 'KafkaLibrary', 'version.py'))
    NameError: name 'execfile' is not defined
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check th
e logs for full command output.

**Comment by pekkaklarck** [comment]
Apparently this library isn't Python 3 compatible. This problem should be reported to its issue tracker. This tracker is only for issues related to Robot Framework itself.

**Comment by asyrjasalo** [comment]
@koolestkrystal: Suggest them https://github.com/asottile/pyupgrade and https://github.com/brettcannon/caniusepython3 if you want to ease their work 😉.
