### ISSUE TITLE
single test in suite blocks all other - timeout available to skip and continue?

### ISSUE THREAD

**Issue by meuchel** [robotframework/robotframework#3311]
I have the problem when startinmg a few tests e.g. based on tags.
In some circumstances a single test in the middle may hang for ever for some reason. (e.g. hanging teststep in ssh session or in case of using selenium library Browser hangs forever ...)

I want now tell RF that it should fail this hanging tests after a certain timespan and continue with the next.
Is this possible?
I looked the documentation and command line parameters but found nothing usable.
When I ctrl+c this testrun the hanging test will fail and also all remaining tests will be set to fail also. But I want that it continues with the remaining tests instead of failing them.
How to manage this?
THX

**Comment by rajsheaker99498** [comment]
Hello,
Have you tried this keyword [Run Keyword If Timeout Occurred](https://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Run%20Keyword%20If%20Timeout%20Occurred), Here you can declare the timeout delay to wait until the hang to become normal ( browser to become responsive).
If timeout reached, it will fail only the particular test/script

**Comment by meuchel** [comment]
Thanks, but I fear this will not work. Its written in the documentation:

...This keyword can only be used in a test teardown. Trying to use it anywhere else results in an error...

Because the test may hang during execution before the Teardown can ever happen. So this will not have the expected result.

**Comment by p74** [comment]
You can use  Test Timeout      

https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#test-case-timeout

**Comment by meuchel** [comment]
Thanks, this is exactly what I need.
But now I have another problem.


We use for our hundrets of test suites just one global resource files which is included in every test suite.
When I try to set the timeout e.g. in this resource file under Settings I get: 
"[ ERROR ] Error in file '.../resource.robot': Non-existing setting 'Test Timeout'."
Its only working when I put this into the Suite files where the test cases are present.

This would mean I have to update every suite files.
What I have to do to set the Timeout globaly when I have a global resource file.


So this works, here one Suite file: (I dont want to do this)


*** Settings ***
Resource          ${RESHOME}/resource.robot
Test Timeout     1 Min

*** Variables ***

*** Keywords ***

*** Test Cases ***
my test x .......



But this works NOT: (this is what I want, Test Timeout is set at one single point)

*** Settings ***
Resource          ${RESHOME}/resource.robot       <- Test Timeout     1 Min      is defined in this resource file


*** Variables ***

*** Keywords ***

*** Test Cases ***
my test x .......

**Comment by p74** [comment]
You can write a script that can parse all your test suite files, but as far as i know there is no global test-timeout paramter,

**Comment by pekkaklarck** [comment]
Test or keyword timeouts are the feature to use. As explained in the User Guide, timeouts can have side effects and I wouldn't use them with all tests unless absolutely necessary. Better to try to isolate keywords that can actually hang and add keyword timeouts to them. Even better to find the root cause and fix that. That said, I think you can set test timeout already in suite initialization files and get them applied to all child suites and tests in them.

Notice also that this issue tracker is for bug reports and enhancement requests. Better to use robotframework-users mailing list, our super active Slack, or some other forums for questions.
