### ISSUE TITLE
Appropriately marking test suites pass/fail

### ISSUE THREAD

**Issue by sharkwsk** [robotframework/robotframework#3312]
Hi Experts,

I wanted to know what is the best way to handle on how to mark a test suite pass/fail based on the test case status

Attached has two test cases, however the Open Connection fails due to connectivity issues to the server. When I run this and I can see the Test Suite is marked as pass.

I am sure there is a better way to write this test suite, would like to get your views

Thank you
[health.txt](https://github.com/robotframework/robotframework/files/3633938/health.txt)

**Comment by pekkaklarck** [comment]
This issue tracker is for bug reports and enhancement requests. General questions should be sent to robotframework-users mailing list, our super active Slack, or to other such support forums listed at robotframework.org.
