### ISSUE TITLE
How should I parse this file ？

### ISSUE THREAD

**Issue by zhangjl99111** [robotframework/robotframework#3316]
the file 'kw.robot' has following contents：

*** Settings ***
Library           RequestsLibrary
*** Keywords ***
testkeywords1
    log    test1
testkeywords2
    log    test2
testkeywords3
    log    test3

my code is:
`
import os, sys
from robot.api import TestData

def print_keword(keword):
    print('kewords:',keword.name) 
    for z in keword.keyword_table:
        print('-', z.name)
keword = TestData(source='kw.robot')
print_keword(keword)
`

the log：
============== RESTART: C:\Users\Administrator\Desktop\test.py ==============
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\test.py", line 36, in <module>
    keword = TestData(source='kw.robot')
  File "C:\Python37\lib\site-packages\robot\parsing\model.py", line 52, in TestData
    return TestCaseFile(parent, source).populate()
  File "C:\Python37\lib\site-packages\robot\parsing\model.py", line 179, in populate
    self._validate()
  File "C:\Python37\lib\site-packages\robot\parsing\model.py", line 184, in _validate
    raise NoTestsFound('File has no tests or tasks.')
robot.parsing.populators.NoTestsFound: File has no tests or tasks.

How should I parse this file ？it does not have test case.

**Comment by pekkaklarck** [comment]
This issue tracker is for bug reports and enhancement requests. General questions should be sent to robotframework-users mailing list, our super active Slack, or to other such support forums listed at robotframework.org.

Anyway, in this case you should use some ResourceFile specific API. Depending on what you are actually trying to do, using Libdoc's APIs might be best. Especially when Robot's test data parsing has been totally rewritten and everything under `robot.parsing` has changed.
