### ISSUE TITLE
Execute Tags based on previous Tag 

### ISSUE THREAD

**Issue by sridharrajendran1** [robotframework/robotframework#3318]
Test 1
[Tags]  Sanity  Regression

Test 2
[Tags]  Regression

Test 3
[Tags]  Sanity

I have categorized the tags as mentioned above and I'm able to execute the specific tests by adding -i "Sanity" in the parameter. Now I've another condition to be added. Based on the Tags it has to pick another Tag.

Eg : 
If the Tag is Sanity, then I wanted the test to be Non-Critical
If the Tag is Regression, then I wanted the test to be Critical

Can you suggest your thoughts in achieving this?

**Comment by rajsheaker99498** [comment]
I'm not sure whether this works for you, but this is the other way which I'm using currently.
Setting dummy tag at starting:

SET dummy_tag = dummy
SET test_tag = Sanity (your tag to test)
IF "%test_tag%" EQU "Sanity" (SET dummy_tag=Non-Critical)
IF "%test_tag%" EQU "Regression" (SET dummy_tag=Critical)

Now you can include these both tags in the test, 
pybot -i test_tag -i dummy_tag /*.robot

**Comment by sridharrajendran1** [comment]
Thanks @rajsheaker99498 for the idea. Based on this I have decided to go with the below approach.

Test Suite1

Test 1
[Tags] Sanity  Regression

Test 2
[Tags] Regression

Test 3
[Tags] Sanity

Recently I found there is a method to set the tags in suite level itself. So I'm planning to execute a keyword to set the tag as Critical or Non-Critical in suite level. But for that decision making, I need to know the Tags which is going to be executed [ex: -i Sanity].
If I'm able to retrieve the given Tag details in Test Suite, I can handle this condition. 

Is there any way to read the Tags which is given as part of the parameter?

**Comment by rajsheaker99498** [comment]
Yes there is method to set tag inside [SET TAG](https://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Set%20Tags). But I don't think there is a way to get the tag which we running [(Get Tag) ](https://groups.google.com/forum/#!topic/robotframework-users/NHLk_vDwAIU) 

Keep exploring, Thanks

**Comment by pekkaklarck** [comment]
I'm not sure did I understand this issue fully, but we have separate `--critical` and `--noncritical` options to mark tests critical/non-critical based on tags. For more complex cases we also have `--prerunmodifier` functionality (see the User Guide) that allows full control on what tests are run, which tests are critical, and so on.

This issue tracker is for bug reports and enhancement requests but this issue looks more like a question. They are best sent to robotframework-users mailing list, our super active Slack, or to other such support forums listed at robotframework.org. If you have a bug report or a concrete enhancement request, please submit a new issue.
