### ISSUE TITLE
Ctrl+B shortcuts key does not work in python 3

### ISSUE THREAD

**Issue by mecanda12** [robotframework/robotframework#3320]
Ctrl+B shortcuts key does not work python 3 with robot-framework-selenium library 4.0.0.
Mostly CTRL+B used to see the custom code or keyword to explore. It is used to work in previous version 3.3.1 but not in current version.
![image](https://user-images.githubusercontent.com/32083604/65729863-cc0e2380-e08d-11e9-8c2d-6488782bf408.png)
![image](https://user-images.githubusercontent.com/32083604/65729871-d29c9b00-e08d-11e9-93c9-8bf16e45578a.png)

**Comment by pekkaklarck** [comment]
This isn't related to RF core and I noticed this issue was already submitted to SL as well. Closing.
