### ISSUE TITLE
Read Until Prompt is not reading properly on windows 

### ISSUE THREAD

**Issue by basa74** [robotframework/robotframework#3321]
Hi,

I have simple code connecting to Windows Host (Through ssh) and trying to read .
Here is what i did
ENV_VAR on Windows Host is HELLO
Open Connection <win_host_ip> Prompt=>
${written}=Write echo %ENV_VAR%
${read_out}= Read Until Prompt
Log ${read_out}

I see following output : HELLO  ELLO LLO LO O 

On unix host i see HELLO 

Why read until is reading ELLO LLO LO O characters.

when i pass newline=CRLF in open connection, Read Until Prompt never reads and timesout.

**Comment by pekkaklarck** [comment]
You are using SSHLibrary, right? In this case this should be submitted to its issue tracker.
