### ISSUE TITLE
Behavior of keyword is different when making library scope as 'GLOBAL' instead of 'TEST SUITE'

### ISSUE THREAD

**Issue by sharadw1986** [robotframework/robotframework#3322]
I have one keyword 'ATF_INIT' and have following statement in that keyword. this keyword is responsible for initialization of my library instance.

@keyword(atfKeyword.ATF_INIT, types=[str, str])
def initATF(self, configFilePath, ConfigFileName):
    **logfilename = 'logs/' + suite_name + '_' + test_name + '_' + timestatmp + '.log'**

**When I am having my library scope 'TEST SUITE':**
I am calling this keyword from test suites .robot file and its working fine. if I am calling this keyword from __init__.robot file in that case also it works.

But
**When I am having my library scope 'GLOBAL':**
if I am calling this keyword from __init__.robot file, it gives following error:
**TypeError: coercing to Unicode: need string or buffer, NoneType found**

and if I am calling same keyword from suites .robot file there is not any error.
to make it work from __init__.robot file I have modified my keyword as 

@keyword(atfKeyword.ATF_INIT, types=[str, str])
def initATF(self, configFilePath, ConfigFileName):
    **logfilename = str(str('logs/') + str(suite_name) + str('_') + str(test_name) + str('_') + str(timestatmp) + str('.log'))**

and it works.

I am not sure why its behave like that. Please suggest resolution for that.

**Comment by pekkaklarck** [comment]
I didn't understand. Please clarify.

**Comment by sharadw1986** [comment]
My custom library is having 'GLOBAL' scope and having following keyword in that library.
@Keyword(atfKeyword.ATF_INIT, types=[str, str])
def initATF(self, configFilePath, ConfigFileName):
            ts= time.time()
            timestatmp = datetime.datetime.fromtimestamp(ts).strftime('%Y-%m-%d_%H%M%S')
            test_name = BuiltIn().get_variable_value("${TEST_NAME}")
            suite_name = BuiltIn().get_variable_value("${SUITE_NAME}")
            BuiltIn().log("Init _initLogger_5", console=YES)
            # Create target Directory if don't exist
            if not os.path.exists('logs'):
                os.mkdir('logs') 
            logfilename = 'logs/' + suite_name + '' + test_name + '' + timestatmp + '.log'

I have one test suite file which test1.robot I am using keyword ATF_Init in test1.robot file. at that time keyword works and not giving any error. But when I am using this keyword in __init__.robot file, keyword gives error "TypeError: coercing to Unicode: need string or buffer, NoneType found". This error is for line **logfilename = 'logs/' + suite_name + '' + test_name + '' + timestatmp + '.log'**.

If I rewrite this line with following line:
**logfilename = str(str('logs/') + str(suite_name) + str('') + str(test_name) + str('') + str(timestatmp) + str('.log'))**

keyword works in __init__.robot file also.

I am not able understand why same implementation is not working with __init__.robot file. why its giving TypeError?

**Comment by pekkaklarck** [comment]
It's very hard to read these comments when they aren't properly formatted. Anyway, what do you think `test_name` is during suite setup or teardown when no test is running?

**Comment by sharadw1986** [comment]
Thanks for clarification, I got it. And sorry for improper formatting. I will take care of it in future.  Thank you once again.
