### ISSUE TITLE
Variables resolution shall be delayed

### ISSUE THREAD

**Issue by sebastianciupinski** [robotframework/robotframework#3328]
For now having such script:

```
*** Variables ***
${var}      //*[@id='${sth}']

*** Keywords ***
Some Action
    [Argument]        ${arg}
    ${sth}        Set Variable     ${arg}
    Click Element       ${var}      
```

Will not work, variables from ```*** Variables ***``` section are resolved immediately and during this process nested variable ```${sth}``` is not available, so whole variable ```${varl}``` is not created, causing last ```Click Element     ${var}``` will fail.

If variables form mentioned section would be resolved just before accessing them, then example above will work.

Other concept is resolving variables if they exists, and leaving them as literal string if any nested variable cannot be resolved to its value.

**Comment by pekkaklarck** [comment]
I don't think this is a good idea. Variable value changing based on other variables just feels wrong. The change would also be backwards incompatible. You can also do this already today:

```robotframework
*** Variables ***
${TEMPLATE}      //*[@id='\${sth}']

*** Keywords ***
Some Action
    [Argument]        ${sth}
    ${value} =    Replace Variables    ${TEMPLATE}
    Click Element       ${value}
