### ISSUE TITLE
"Run Keyword and Return status" does not work properly

### ISSUE THREAD

**Issue by Pawci3oo** [robotframework/robotframework#3334]
Hi,

I have upgraded Robot Framework from 3.0.4 to 3.1.2 (python to 3.7.4) and the keyword "Run Keyword and Return status" in my framework does not work properly.
There is no keyword "Table should not contain" so I decided to use the following workaround.
In the 3.0.4 version the keywords worked well:

${status}=     **Run Keyword And Return Status**      Table Should Contain     ${table}    ${op_id}    loglevel=NONE
**Run Keyword If**    '${status}'=='True'    **Run Keywords**    **UTake Page Screenshot**    AND    **Fail**    "Operation ${op_id} exists in the Table, but it shouldn't!"

But, in the **3.1.2** version ${status} is always True. If I do not use "Run Keyword And Return Status" there is of course FAIL "The Table '${table}' did not contain text '${op_id}'", so it means keyword "Run Keyword And Return Status" should return False.(but returns True)

Could you check this case?

Paweł

**Comment by pekkaklarck** [comment]
Please provide a simple executable example demonstrating the problem. And with somole I mean an example not using other that Robot's standard libraries.

**Comment by Pawci3oo** [comment]
Maybe there is a problem with some "SeleniumLibrary" keywords only, because with BuiltIn it does work well.

Example **Built In** keyword:

![image](https://user-images.githubusercontent.com/26310305/66542799-dd4a3c00-eb33-11e9-8879-b14e30aa897a.png)
**Result:**

![image](https://user-images.githubusercontent.com/26310305/66542812-e89d6780-eb33-11e9-8caf-eaf8b8d91067.png)

Example **SeleniumLibrary** keyword with keyword "Run Keyword and Return Status":

![image](https://user-images.githubusercontent.com/26310305/66542886-171b4280-eb34-11e9-8d20-ad4d9a85f326.png)
**Result:**
![image](https://user-images.githubusercontent.com/26310305/66542914-24d0c800-eb34-11e9-8243-adc4c2a0ef0e.png)

Example **SeleniumLibrary** keyword without keyword "Run Keyword and Return Status":

![image](https://user-images.githubusercontent.com/26310305/66542928-30bc8a00-eb34-11e9-9b33-f7ecb015e0ea.png)
**Result:**

![image](https://user-images.githubusercontent.com/26310305/66542990-5f3a6500-eb34-11e9-95db-1af67d59ddfc.png)

**Comment by pekkaklarck** [comment]
It would be strange if the behavior of `Run Keyword And Return Status` would depend on the keyword executed with it. Anyway, I need an [simple executable example](http://sscce.org/) to debug this problem further.

**Comment by Pawci3oo** [comment]
Probably I know where is an issue. Table Should Contain does not work properly. If there is given text on the page and even I provide ID of table for this keyword, then this keyword returns True if the text exists on the page (not in table). Probably, but you need to check this case:

*** Settings ***
Library    SeleniumLibrary    #4.0.0

*** Variables ***
${url}    https://www.w3schools.com/html/html_tables.asp
${customer_table}    //table[@id='customers']

*** Test Cases ***
Sample test
    Open Browser    ${url}    browser=chrome
    Maximize browser window
    Element Should Be Visible    ${customer_table}
    ${status}=    Run Keyword And Return Status    Table Should Contain    ${customer_table}    Each    loglevel=None
    Log    ${status}

Is it enough example for you?

**Comment by pekkaklarck** [comment]
This issue tracker is for Robot Framework. SeleniumLibrary issues belong to its issue tracker. Also, if you suspect `Table Should Contain` doesn't work correctly, you shouldn't wrap that to some other keyword but use directly.

**Comment by Pawci3oo** [comment]
It doesn't matter whether I use "Run Keyword And Return Status" or not. `Table Should Contain` doesn't work too for the above case if I do not use "Run Keyword And Return Status". `Table Should Contain` is useless because I can also use `Page Should Contain` to find text on the page.
I have two tables on the page where one record is moved to the second table and i need to verify that.

Anyway, I'm going to report that bug for "Issue tracker" for SeleniumLibrary.
Thanks.
