### ISSUE TITLE
Improve 'Set Log Level' keyword

### ISSUE THREAD

**Issue by Pawci3oo** [robotframework/robotframework#3335]
Hi,

I use the `Set Log Level` keyword for a lot of keywords that do not have that option. (log level)
I mainly use this keyword (and `Wait Until Keyword Succeeds`) in the process of waiting for the curtain to disappear. 
The file (output.xml) that I checked this on is 100MB. (It contains 18000 records of this keyword)

`<kw name="Set Log Level" library="BuiltIn">
<doc>Sets the log threshold to the specified level and returns the old level.</doc>
<arguments>
<arg>NONE</arg>
</arguments>
<status status="PASS" starttime="20191010 19:06:24.303" endtime="20191010 19:06:24.304">
</status>
</kw>`

Is there a possibility not to register keywords, results, etc. in output.xml if log level is set to None?

**Comment by pekkaklarck** [comment]
No, log level only affects the actual log messages. What you want is basically #2603 and I close this issue as its duplicate. Until that feature or something similar is implemented, you can use `--removekeywords` or `--flattenkeywords` options.

**Comment by pekkaklarck** [comment]
Implementing some of your most used keywords in a library, if possible, would also be a good solution.
