### ISSUE TITLE
Run keyword and ignore error changes the type of variable

### ISSUE THREAD

**Issue by MariuszJanczura** [robotframework/robotframework#3343]
Hello,
I have a problem related to the changing of the variable type when using Run Keyword and Ignore Error.     
I'm getting the epoch time type from DateTime:    

> ${start_time}=    DateTime.Get Current Date    result_format=epoch

which is float (due to epoch time from specs regarding DateTime: Epoch time is returned as a floating point number.)

But when I'm executing:

> Run Keyword And Ignore Error    Get and Check Startup Time '${start_time}'

I've got unicode type.

The python script executed inside "Get and Check Startup Time '${start_time}'" keyword is demanding float numbers, so:

- if I'm using above KW without Run Keyword And Ignore Error I got passing keyword because ${start_time} is floating type,
- if I'm using above KW with Run Keyword And Ignore Error I got an error because ${start_time} is a unicode type.

I think using Run Keyword And Ignore Error should just hide the result, not change it so it cannot be executed in similar situations like mentioned above. Thanks!

**Comment by pekkaklarck** [comment]
Although `${start_time}` would be a float, `'${start_time}'` is a Unicode string.

Also, if this `Get and Check Startup Time` is your own keyword, it would be a good idea to either make it configurable like `ignore_errors=False` or possibly adding a separate keyword. `Run Keyword And Ignore Error` hides all errors, even bugs in your library, and should be used only with external libraries.

**Comment by pekkaklarck** [comment]
No, `'${x}'` is always a string in Robot's data regardless what `${x}` is. There's nothing about changing argument types in `Run Keyword And Ignore Error` documentation simply because it doesn't do anything like that.

**Comment by MariuszJanczura** [comment]
Well, my proposition is to execute the below code.

Execute the code, please:

```
At least please check it
	${start_time}=    get something
	check something ${start_time}

*** Keywords ***
get something
    ${start_time}=    DateTime.Get Current Date    result_format=epoch
    Log    epoch: ${start_time}
    [return]    ${start_time}
	
check something ${start_time}
	<execute python script which needs float variable here and use ${start_time}>
```

and then execute:
```

At least please check it
	${start_time}=    get something
	Run Keyword And Ignore Error    check something ${start_time}

*** Keywords ***
get something
    ${start_time}=    DateTime.Get Current Date    result_format=epoch
    Log    epoch: ${start_time}
    [return]    ${start_time}
	
check something ${start_time}
	<execute python script which needs float variable here and use ${start_time}>
```

See the difference, please.
My code returns below when I use the Run Keyword And Ignore Error (the <type 'unicode'> is printed by python):

13:01:08.881 | INFO | <type 'unicode'>
-- | -- | --


13:01:08.885 | FAIL | TypeError: unsupported operand type(s) for -: 'float' and 'unicode'
-- | -- | --


In the example without using Run Keyword and Ignore Error:

13:22:13.504 | INFO | <type 'float'>
-- | -- | --


Well, I see the problem and I want to know why is this change happening. Execute this, please.

**Comment by pekkaklarck** [comment]
Oh, you are using embedded arguments. That wasn't clear from the original description. This is a known problem that is unfortunately complicated to fix. See #1595 for details.

**Comment by MariuszJanczura** [comment]
Thank you for pointing right issue :).
