### ISSUE TITLE
Documentation in Dash format docset

### ISSUE THREAD

**Issue by damien122** [robotframework/robotframework#3344]
Hi,

is it possible to get the Robot Framework Dokumentation (http://robotframework.org/robotframework/) in a docset format as docset feed or dash listed (https://github.com/Kapeli/Dash-User-Contributions#readme)?
A lot of tools can list this offline documentations now, also for linux and windows and it is very handy to search with them.
Here you can find a way how to convert the documentation in docset https://kapeli.com/docsets.

Here you can see possible tools which support docs like that. https://alternativeto.net/software/dashexpander/

**Comment by pekkaklarck** [comment]
I don't know the docset format or Dash. What benefits would it bring? Would it be new format or should it replace something we already have? What would this require? Are you interested to contribute?

**Comment by damien122** [comment]
Hi @pekkaklarck,

the docset format allow to use documentation with the supported tools. This tools give you the possibility to download the documentation and use it offline and also a much easier way to search for keywords. As much as I understand the docset format is just HTML with a SQLite Database which contains all keywords and much more. Then it is possible to use fuzzy search in the frondend tools which helps a lot at the daily work.
In this link https://kapeli.com/docsets#dashDocset it is explained how to convert any html documentation to an docset format. And here https://github.com/Kapeli/Dash-User-Contributions#readme you can see how to contribute your documentation to a third party dash channel which can be used by the documentation viewer tools.
My favorite tool is "Velocity" but "Zeal" is also very good.

I am not sure that I can contribute because my python knowledge is very limited but if there is a way I will try.

**Comment by MaciejWiczk** [comment]
@damien122, have You tried [rfhub2](https://github.com/pbylicki/rfhub2)? Take a look at [demo](https://rfhub2-demo.herokuapp.com/) if it's something You are looking for.

**Comment by damien122** [comment]
@MaciejWiczk thx for your hint. This is also a very good solution! This helps me very much.

**Comment by pekkaklarck** [comment]
New documentation formats are possible but probably best handled as external tooling.
