### ISSUE TITLE
Rename `Tags._normalize`

### ISSUE THREAD

**Issue by stdedos** [robotframework/robotframework#3347]
Rename `Tags._normalize` to `Tags._deduplicate_normalized` (?)

_Originally posted by @pekkaklarck in https://github.com/robotframework/robotframework/pull/3245#issuecomment-543598440_
> You are right that it's not possible to use the existing `self._normalize` to implement this. That method, by design, preserves the original format of tags and just removes duplicates, empty tags, and 'NONE'. When comparing equality, you want to actually normalize the tags. Perhaps the existing `self._normalize` should be even renamed.

**Comment by pekkaklarck** [comment]
This doesn't need a separate issue. Can be done as part of #3245 if needed.
