### ISSUE TITLE
Log files size

### ISSUE THREAD

**Issue by povar81** [robotframework/robotframework#3351]
I'm using rebot to generate logs. I run same 217 cases on older (python 2) version of robotframework and the size is about 17 mb, while on newest version of robotframework  for python 3(robotframework==3.1.2) it is 474mb and output.xml is even larger= about 2 gb!

**Comment by pekkaklarck** [comment]
There must be something else that's different as well. Output and log file sizes don't change much between Robot Framework versions and even less with Python versions. If you can reproduce this issue so that the problem certainly is in Robot Framework itself, please submit a new issue with more details. If you just try to understand what's going on, it's better to send questions to robotframework-users mailing list, our active Slack, or other such support forums listed at robotframework.org.

**Comment by povar81** [comment]
It turned out I was using jybot.bat (jython) on older version.
Logfile and output.xml is a lot smaller, can it be because of some specific log4j.properties settings?
I run it via custom script like this:
set _JAVA_OPTS=-Duser.language=en -Duser.country=US -Dconsole.encoding=UTF-8 -Dfile.encoding=UTF-8 -Djava.ext.dirs=%IUM_TEST%\lib;%IUM_TEST%\lib\axis2\lib -Dlog4j.configuration=file:./log4j.properties 
call %PYTHONPATH%\Scripts\jybot.bat  --loglevel TRACE -C off -d %RF_RUNNER_HOME%\out1 -l NONE -r NONE  %RF_ARGS%

**Comment by pekkaklarck** [comment]
log4j shouldn't affect Robot's logging at all.

**Comment by povar81** [comment]
Can you please give me a hint about what else can be influencing the log size? 
I'm using rebot.bat, not jrebot to generate a log from output.xml. Here's the full code of custom  script:

set _JAVA_OPTS=-Duser.language=en -Duser.country=US -Dconsole.encoding=UTF-8 -Dfile.encoding=UTF-8 -Djava.ext.dirs=%IUM_TEST%\lib;%IUM_TEST%\lib\axis2\lib -Dlog4j.configuration=file:./log4j.properties 
call %PYTHONPATH%\Scripts\jybot.bat  --loglevel TRACE -C off -d %RF_RUNNER_HOME%\out1 -l NONE -r NONE  --variable RESOURCE_FILE:%IUM_TEST%\suits\resources\local\Resources_local.txt %RF_ARGS%
call %PYTHONPATH%\Scripts\rebot.bat  -d %RF_RUNNER_HOME%\out1 %RF_RUNNER_HOME%\out1\output.xml

**Comment by povar81** [comment]
Can you please give me a hint about what else can be influencing the log size?
I'm using rebot.bat, not jrebot to generate a log from output.xml. Here's the full code of custom script I'm using on python2:

set _JAVA_OPTS=-Duser.language=en -Duser.country=US -Dconsole.encoding=UTF-8 -Dfile.encoding=UTF-8 -Djava.ext.dirs=%IUM_TEST%\lib;%IUM_TEST%\lib\axis2\lib -Dlog4j.configuration=file:./log4j.properties
call %PYTHONPATH%\Scripts\jybot.bat --loglevel TRACE -C off -d %RF_RUNNER_HOME%\out1 -l NONE -r NONE --variable RESOURCE_FILE:%IUM_TEST%\suits\resources\local\Resources_local.txt %RF_ARGS%
call %PYTHONPATH%\Scripts\rebot.bat -d %RF_RUNNER_HOME%\out1 %RF_RUNNER_HOME%\out1\output.xml

**Comment by pekkaklarck** [comment]
I don't know your environment and cannot help you. You are the only one being able to debug this further.
