### ISSUE TITLE
--removekeywords wuks doesn't work

### ISSUE THREAD

**Issue by povar81** [robotframework/robotframework#3352]
I'm using custom script:

call "%PYTHONPATH%\Scripts\robot.exe"  --loglevel TRACE -C off -o %RF_RUNNER_HOME%\out\output.xml -d %RF_RUNNER_HOME%\out -l NONE -r NONE  --removeKeywords wuks --variable RESOURCE_FILE:%TEST%\suits\resources\local\Resources_local.txt %*

however when I added --removekeywords wuks nothing's changed: I still get all the failing keywords withing wait until keywords succeed keyword.

**Comment by pekkaklarck** [comment]
Have you looked what docs say about using it with `robot` vs. using it with `rebot`?

**Comment by povar81** [comment]
Yes, thank you. 
I have a custom script which has 2 commands: 
1. robot
2. rebot
It worked when I used it with rebot.

**Comment by pekkaklarck** [comment]
Great! If you'd create log and report as part of the execution, this option would also affect them. It just doesn't affect the output.xml file created during execution.
