### ISSUE TITLE
How to distinguish Robot variable and KSH Variable?

### ISSUE THREAD

**Issue by JerryGeng1216** [robotframework/robotframework#3356]
I tried to use Robot to do the following operation in KSH to remove the ".auto" postfix in a directory:

Write    for file in *.auto; do mv $file ${file%.*}; done

The ${file%.*} is for KSH variable however Robot always considered it as Robot variable and gave the error message: "Resolving variable '${file%.*}' failed: Variable '${file}' not found."

Is there any way to tell Robot that the ${file%.*} is not for a Robot variable?

**Comment by pekkaklarck** [comment]
Escape `${file%.}` like `\${file%.}`.

**Comment by JerryGeng1216** [comment]
Thanks for your info!
