### ISSUE TITLE
User documentation still referes to custom timeout messages even though they are depreciated

### ISSUE THREAD

**Issue by fheineIDBS** [robotframework/robotframework#3357]
As of version 3.1.2, the Robot Framwork user documentation still refers to Custom timeouts messages, even though they have been depreciated since version 3.0.1.

http://robotframework.org/robotframework/3.1.2/RobotFrameworkUserGuide.html#timeouts

**Comment by pekkaklarck** [comment]
Good catch! Custom timeout message won't be supported anymore in RF 3.2 (#2291) but it seems the User Guide still hasn't been updated. I'll reopen #2291 with a note that the UG should be updated.
