### ISSUE TITLE
Tests stops but does not produces output files while stopped via CTRL C through Listener

### ISSUE THREAD

**Issue by iamdhanabalan** [robotframework/robotframework#3361]
On sending "CTRL+C" keys via listener interface using pyautogui hotkeys, the test exection stops but does not produces the output files. However it works manually.

**Comment by pekkaklarck** [comment]
What are pyautogui hotkeys?

**Comment by iamdhanabalan** [comment]
I'm sending CTRL+C using [Pyautogui](https://pyautogui.readthedocs.io/en/latest/cheatsheet.html)

**Comment by pekkaklarck** [comment]
I have no experience with that tool and thus don't know how it actually sends CTRL-C.

When you manually press CTRL-C, Python maps it to a KeyboardInterrupt exception and Robot handles that separately. Raising that from a listener would be a good way to stop execution from a listener, but I'm not sure does it work. Have you tested that? If it doesn't work, are you interested to study how it could be made to work?

**Comment by pekkaklarck** [comment]
Any updates?

**Comment by pekkaklarck** [comment]
We actually already have #2940 about same/similar issue. Closing this as its duplicate.
