### ISSUE TITLE
Get subsuite by rebot

### ISSUE THREAD

**Issue by LikHait** [robotframework/robotframework#3363]
I have test suites in follow order:
```
└───top_suite
    ├───suite1
    ├───suite2
    └───suite3
```
I want to get result for suite2 by `rebot --suite suite2 output.xml`. When I execute the command I get the result:
```
└───top_suite
    └───suite2
```
But "top_suite" is excess information. Can it be removed from result?
```
└───suite2
```
If no can we see this feature in the future?

**Comment by pekkaklarck** [comment]
There's no built-in feature that supports this. It is, however, possible to accomplish this by using Robot's result/reporting APIs by creating a custom tool. Possibly this could be done also by using a custom pre-rebot modifier (see the User Guide for details about them), but I'm not entirely sure can they drop the root suite.

In general it would be possible to add a feature that enables this from the command line somehow. Implementation wouldn't be complicated but coming up with a good design how it actually should work can be. Do you have any ideas how it could work? If we can agree about the design, we'd then need someone to implement it. Do you have interest for that?

**Comment by pekkaklarck** [comment]
There doesn't seem to be interest designing/implementing this in generic manner. For custom solutions Robot's APIs ought to be enough.
