### ISSUE TITLE
`Run Process:` Ignore timeout if it is zero, negative or string `None`

### ISSUE THREAD

**Issue by stdedos** [robotframework/robotframework#3366]
Make `timeout` named argument accept the same values as keyword `[Timeout]` does.

Any falsy, zero, or negative values are treated the same way as `[Timeout]` (i.e. ignored aka infinity)

See also #3365

**Comment by pekkaklarck** [comment]
Ignoring timeouts when they are `None` or not positive is a good idea, but I don't think supporting `timeout=False` makes much sense.

**Comment by pekkaklarck** [comment]
Thanks to PR #3367 by @stdedos this has now been implemented. I raised priority from low to medium because there earlier weren't any clean way to specify a timeout value that means timeout shouldn't be activated.
