### ISSUE TITLE
log.html mixes latin and utf8

### ISSUE THREAD

**Issue by osiworx** [robotframework/robotframework#3368]
When having a look into the log.html file I find that there is an issue with äöü as example.
They show up in utf8 and sometimes as latin1 in the same document which makes it hard to display the file correct.

![image](https://user-images.githubusercontent.com/47136303/68279889-b28cce00-0074-11ea-90b2-efbd76029a7b.png)

In the screenshot you see my problem.

text=äöü
or 'text=\xe4\xf6\xfc'

Is there any way to tell the framwork to stick to one encoding?
At runtime there seems to be no issue, my test gets executed correctly.

I run the framework on a windows 10 box with jython 2.7.1 its robot framework 3.1.2

**Comment by pekkaklarck** [comment]
Arguments are logged on trace level using customized variant of Python's `repr`. When using Python/Jython 2, non-ASCII characters shown as escape sequences:

```
Jython 2.7.0 (default:9987c746f838, Apr 29 2015, 02:25:11) 
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)] on java1.8.0_201
Type "help", "copyright", "credits" or "license" for more information.
>>> print repr(u'äöü')
u'\xe4\xf6\xfc'
```
