### ISSUE TITLE
Reimport library dynamically with arguments not __init__ properly

### ISSUE THREAD

**Issue by h75lu** [robotframework/robotframework#3370]
I was trying to reimport the same python library with different arguments at test setup. However, I noticed that my python class is not initialized properly. The class seems was only initialized on first import, and then `__init__` was not called anymore. 

I found a Note in the user guide that "If a library is imported multiple times with different arguments, a new instance is created every time regardless the scope". 
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#test-library-scope

Based on that, I should have my class initialized every time I reimport it. I am wondering what is going on for this? Thank you.

**Comment by pekkaklarck** [comment]
With this information alone it's impossible to know what goes wrong. It would be best if you could create a simple example demonstrating the problem. See http://sscce.org/ for details.

**Comment by h75lu** [comment]
Example:
Say I have a class called MyClass in myclass.py and a another library called anotherlib.py
![image](https://user-images.githubusercontent.com/53126992/68495562-7c8b4d80-021e-11ea-81c3-a6e2bea37c0c.png)
The first test case worked out fine, but the second test case failed due to the `__init__` of MyClass was not executed. ie. `self.another_lib = anotherlib` is not happening.
![image](https://user-images.githubusercontent.com/53126992/68495883-17842780-021f-11ea-8a33-2d28ff67dcd0.png)

I hope this example is helpful. Thank you!

**Comment by pekkaklarck** [comment]
You aren't showing all the code so it's still hard to understand what's going on.

**Comment by pekkaklarck** [comment]
Any updates related to this?

**Comment by pekkaklarck** [comment]
No new info. Closing.
