### ISSUE TITLE
String compare in keyword like "Set Variable If" get SyntaxError: invalid character in identifier (<string>, line 1)

### ISSUE THREAD

**Issue by hidebear** [robotframework/robotframework#3371]
I get an issue about Set Variable If "${My string}" != "${EMPTY}" got invalid error issue, and then I've tried even simple string comparing "abc" != "def" did not work as well.

![image](https://user-images.githubusercontent.com/21049399/68570217-12cba780-049b-11ea-89e7-6eab852b5074.png)

![image](https://user-images.githubusercontent.com/21049399/68570267-37278400-049b-11ea-97bb-2392906a8e9c.png)

But digital number comparison is totally fine. (like 123 != 234 worked)

I've been using Python2 RF for years and this is my first time using Python3 version RF, not sure if it's Python3 related issue or some other misconfigurations?

**Environment:**
1. OS:  Mac OS 10.15.1
2. Robot version: Robot Framework 3.1.2 (Python 3.7.3 on darwin)

**Comment by rajsheaker99498** [comment]
I just executed same in my system, it worked fine as usual.
OS: Windows 10
RF version: 3.1.2, Python 3.7
![image](https://user-images.githubusercontent.com/55488266/68657600-0bb79e80-055a-11ea-998b-afcdba437469.png)

I feel there is issue with the double quotes you used. Please check that and try again.
Or try this by copy: ${test}    Set Variable If    "abc" != "efg"    test1    test2

**Comment by pekkaklarck** [comment]
When evaluating an expression in Python like `Set Variable If` does, you need to follow Python syntax. In Python you need to quote strings using normal double quotes like `"foo"` or single quotes like `'foo'`. If you look your example screenshot closely, you notice you've used some kind of curved quotes like `“foo”`.

**Comment by hidebear** [comment]
@rajsheaker99498 
Thank you!  exactly the issue of the double quotes format!
I found that I type the double quotes inside the grid cell of RIDE, it changes the format. (but edit it in text editor won't), maybe it's RIDE's issue I guess, and I'll file an issue on the RIDE repo..
Thanks for your help!
![image](https://user-images.githubusercontent.com/21049399/68722622-035e7280-05f1-11ea-83bf-888ac0fd57ee.png)

**Comment by pekkaklarck** [comment]
RIDE definitely shouldn't do that. I also doubt RIDE itself does it, but instead guess that it's done by the underlying GUI widget. If that's the case, such functionality should be disabled.

**Comment by hidebear** [comment]
@schaefer01 yes I've reported [here](https://github.com/robotframework/RIDE/issues/2050).
