### ISSUE TITLE
alternative call of python method which employs **kwargs

### ISSUE THREAD

**Issue by georgeOikonom** [robotframework/robotframework#3372]
Hello all,

I’ve been faced with the issue of calling “a user-defined python method which employs free named arguments (i.e. **kwargs)” – a topic already documented https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#free-keyword-arguments-kwargs in the Robot FW. doc. 
The examples offered in order to utilize the option to specify the desired args-names for such a call are of the type
 
Various Args a=1 b=2 c=3
 
i.e. one explicitly should write the name/value pairs referring to **kwargs of the method.
 
However in order for me to be able to craft some “multi-purpose wrapper” keyword, I needed a Robot FW statement which would pass the various name/value pairs via a single variable, eg of list data type. After thorough searching I could not find anything referring on this “tweak” and through trial and error I managed to get such a statement working.
 
With respect to the signature of the following method:

def various_args(arg, *varargs, **kwargs):
 
this does the trick:
 
Various Args ${scalar_var_1} &{dict_var_1}
 
Where scalar_var_1 is a scalar var relating to named arg arg and dict_var_1 is a var of type dictionary whose keys are passed to the names and its values to the values of the **kwargs. 
 
Since this is not documented in the Robot FW user guide I am raising it as something that needs documenting (in my opinion).

Robot Framework User Guide Version 3.1.2

Br, George

**Comment by pekkaklarck** [comment]
Could you clarify what isn't documented? Even better if you could propose where new documentation should be added?

Some places where these topics are already discussed:
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#free-named-arguments
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#dictionary-variable

**Comment by georgeOikonom** [comment]
Hello,

With respect to the Robot FW guide

Paragraph 2.2.2   Using arguments
Free named arguments
How keywords specify that they accept free named arguments depends on the keyword type. For example, Python based keywords simply use **kwargs and user keywords use &{kwargs}.

So here a discrimination is made on the keyword-type by example, i.e. python-based and user-keywords; and **kwargs and &{kwargs} refer to the signature/definition of the method/key, not their invocation.

In the Examples section there is an example using the non-user defined Run Process keyword, i.e.

Run Process    program.py    @{args}    &{config}

And there is also a mention to user-defined libs invoked as keywords:

See Free keyword arguments (**kwargs) section under Creating test libraries for more information about using the free named arguments syntax in your custom test libraries.

The link points to the section I included in my original post in which there is no keyword-usage example illustrating the &{ some_dict_for_kw_args} syntax.

Bottomline: I’d rather for an example to exist as well in the section describing the topic in focus, i.e. python method defined in user-created lib and its invocation through Robot; it would certainly help a lot an non-expert like me who has not gone through the entire robot doc and has instead conducted a search using google and in the end landed in a Robot FW doc section which looks relevant to the topic, i.e. http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#free-keyword-arguments-kwargs

So let’s expose its use a bit more by including here http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#free-keyword-arguments-kwargs
An example of 

Kwargs
    Various Args    a=1    b=2    c=3             # Logs 'kwarg: a 1', 'kwarg: b 2' and 'kwarg: c 3'.
    Various Args    c=3    a=1    b=2             # Same as above. Order does not matter.
    Various Args    &{dict_var}                   # ‘kwarg’ will be logged according to contents of each item of the dictionary


With best regards, George

**Comment by pekkaklarck** [comment]
The example at the end of the comment above looks good but I don't think http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#free-keyword-arguments-kwargs is a good place for it. The example is about using keywords with (free) named arguments, but that User Guide section is part of larger *Creating test libraries* section and it should concentrate on the library API, not Robot's keyword calling syntax.

A better place for the example would be under http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#using-arguments that discusses about how to call keywords using different approaches. Perhaps a separate section could be added there about using `@{args}` and `&{named}` syntax? Do you @georgeOikonom have interest to look at that more closely? It would be especially great if you could provide a pull request.

**Comment by georgeOikonom** [comment]
Hello,

Considering your input regarding the scope of the various doc sections, I think that the following would mark an improvement (again I am also putting into the perspective the “custom test libs and py methods with **kwargs” issue).

1.	In the section that you mentioned, i.e. $2.2.2, under Free named arguments -> Examples

	_*** Test Cases ***
	Free Named Arguments
    		Run Program    arg1    arg2    cwd=/home/user
    		Run Program    argument    shell=True    env=${ENVIRON}
		Run Program    &{dict_holding_named_args_with_their_values}_


Since _Run Program_ is user-defined and not built-in (so the read understands that he/she can use it in his/her own keywords.
	http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#using-arguments


2.	In the section regarding test-libs -> python **kwargs there is a reference to 1 via the link

_Robot Framework supports Python's **kwargs syntax and extends that support also to Java._

	So there’s a good chance that the reader would not miss the example there (in 1) and relate it to the python **kwargs use-case.
	

However, I am still in favour of the adaptation I provided earlier in section 2 even when considering that
Quote: “but that User Guide section is part of larger _Creating test libraries_ section and it should concentrate on the library API, not Robot's keyword calling syntax.” 
since it helps the uninitiated as I wrote earlier and secondly since, in my opinion, this addition does not “dilute” the focus of this section (…concentrate…library API…) – it’s simply another line in the examples.

For certain experts of the doc and its scope need to decide; I am offering a view of an “average user” here.

Br, George

**Comment by pekkaklarck** [comment]
Could you turn these enhancements into a pull request?

**Comment by georgeOikonom** [comment]
Hello, I am completely new to github and the Robot FW project. Could you please share a link to some instructions on "how to make a pull request"?

I thank you in advance.

**Comment by pekkaklarck** [comment]
https://github.com/robotframework/robotframework/blob/master/CONTRIBUTING.rst

**Comment by pekkaklarck** [comment]
No updates lately. Closing.
