### ISSUE TITLE
Want to use "#" symbol to input in the password field using Robot Framework - However it is considering "#" as comment.

### ISSUE THREAD

**Issue by rh00454289** [robotframework/robotframework#3374]
Want to use "#" symbol to input in the password field using Robot Framework - However it is considering "#" as the comment.

I am using Eclipse IDE to develop my robot test.
For all my test passwords starts with "#".

*** Variables ***
${User_Pass}  //input[@type="password" and contains(@name ,"p")]
${Login_Pass}		#123456789

*** Keywords ***
input text    ${User_Pass}    ${Login_Pass}

It is not entering anything inside the password text field. Kindly suggest.

**Comment by rajsheaker99498** [comment]
Just add a backward slash( \ ) before your password.
${Login_Pass}    \#123456789

**Comment by pekkaklarck** [comment]
Yeah, `#` starts a comment but it can be escaped with a backslash. For details see the User Guide:
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#comment

**Comment by rh00454289** [comment]
> Just add a backward slash( \ ) before your password.
> 
> ```
> ${Login_Pass}    \#123456789  
> ```

Thank you so much. It worked like a charm.

**Comment by rh00454289** [comment]
> Yeah, `#` starts a comment but it can be escaped with a backslash. For details see the User Guide:
> http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#comment

Thank you.
