### ISSUE TITLE
harmonize docu formatting *.rst vs. *.py

### ISSUE THREAD

**Issue by DirkRichter** [robotframework/robotframework#3378]
Some common robot/rebot options has different specification in *.rst and rebot.py. Please harmonize.

Samples: flattenkeywords, removekeywords, expandkeywords, ...

RST:
``` 
--flattenkeywords <for|foritem|name:pattern|tag:pattern>
--removekeywords <all|passed|name:pattern|tag:pattern|for|wuks>
--expandkeywords <name:pattern|tag:pattern>
``` 
rebot.py:
``` 
--flattenkeywords for|foritem|name:<pattern>|tag:<pattern> *
--removekeywords all|passed|for|wuks|name:<pattern>|tag:<pattern> *
--expandkeywords name:<pattern>|tag:<pattern> *
```

**Comment by pekkaklarck** [comment]
I would prefer the latter format, but I think it would cause a syntax error in reST files. I don't mind formats being slightly different but would be fine unifying them as well. Are you interested to study how it could be done?

**Comment by pekkaklarck** [comment]
Do you @DirkRichter have interest to look at this? For me it is dine that we use slightly different syntax in different places. In reST files we must follow reST syntax but that doesn't work in other context so well.

**Comment by pekkaklarck** [comment]
Apparently no interest. Closing.
