### ISSUE TITLE
The timestamp of xml, report and log is equal

### ISSUE THREAD

**Issue by aitormars** [robotframework/robotframework#3379]
Environment:
OS: Windows10
Robot Framework: Robot Framework 3.1.2 (Python 2.7)

Description:
When ride finish the execution the log, the report and the xml files have the same timestamp for all files. The 3.0.4 version set the timestamp with end of execution to report and log.

Output: C:\LogsRide\output-20191113-155339.xml
Log: C:\LogsRide\log-20191113-155339.html
Report: C:\LogsRide\report-20191113-155339.html

**Comment by pekkaklarck** [comment]
This was explicitly fixed by #2945. Do you have reasons why the old behavior was better?

**Comment by pekkaklarck** [comment]
No reasons why we should return to the old behavior provided. Closing.
