### ISSUE TITLE
Feature Request: Tidy --preserve-empty-lines

### ISSUE THREAD

**Issue by james-powis** [robotframework/robotframework#3380]
Empty(blank) lines drastically improve readability. Tidy also helps with readability and standardization. 

Unfortunately Tidy removes all whitespace that is not spaces inbetween keywords and arguments.

Would it be possible to implement a --preserve-empty-lines option?

**Comment by pekkaklarck** [comment]
Empty rows used to be ignored during parsing, but the new parser in RF 3.2 preserves them (#645) so implementing this feature is possible. At least I won't, however, have time for such enhancements in the near or even foreseeable future, but if someone else is interested to look at that I'd be happy to help and review pull requests. Another problem is that Tidy related APIs are still changing (see #3373), but if there's enough interest such enhancements could even make it to RF 3.2.

We already have issue #3353 about Tidy not touching whitespace. That's so related to this issue that I'll close this one as its duplicate.
