### ISSUE TITLE
Unable to import package created in one directory to other directory after successful installation of python package in Robot Framework

### ISSUE THREAD

**Issue by ankitaverma1201** [robotframework/robotframework#3381]
Hello,
My query is regarding creating Python package(which contains .robot test suite) so that I can reuse the keywords in that particular package to any other project by simply importing the Library anywhere
I have successfully created and installed package(named as Resources which contains some .robot test suites). Now I want to use the keywords from 'Resources' package to some other Robot project. Here, problem is when I write below statement:
**Library    Resources** 
I am not able to use the keyword given in Resources package. But If I import that particular robot file, them I am able to access the keyword: e.g
**Resource    ../../../../Documents/MyWorkspace/RobotFramework/Resources/PostLoginSearch.robot**
Here I do not want to import using above absolute path. So is it possible to use keywords by only importing Resources package.
Also I have successfully created and installed "Resources" package and I could see the version also. I am able to call the python methods but unable to access the keyword in Resources .robot file after importing "Resources" package

And this **"Resources"** is in some other project

**Comment by ankitaverma1201** [comment]
![Uploading image.png…]()

**Comment by ankitaverma1201** [comment]
Closed by mistake

**Comment by pekkaklarck** [comment]
Is this a feature request or a question? In the former case please explains in concrete terms what you are proposing. In the latter case this is in a wrong place, this issue tracker is only for bug reports and enhancement requests. I'd nevertheless recommend you to read what the User Guide says about resource imports:
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#taking-resource-files-into-use

**Comment by ankitaverma1201** [comment]
@pekkaklarck  sorry for posting at wrong place. I did not notice. Can you please recommend where can I post my query apart from slack

**Comment by pekkaklarck** [comment]
Slack and the robotframework-users mailing list are most active public support forums. If you don't get helpful replies, you may want to spend some time making your question easier to understand. I needed to read it twice and still didn't fully understand what you try to do.
