### ISSUE TITLE
View HTML renderings in the console /  Method to recover the logs of the Browser / Python import problem

### ISSUE THREAD

**Issue by ialata** [robotframework/robotframework#3387]
Good evening,
I had a Robotframework question on the log display in the console. I'm working on a project, the client wants to see the HTML renderings in the console.
This is to report events that occur during the normal operation of a program (for example to track a status or review malfunctions)
Can you help me please?

**Comment by ialata** [comment]
Voici mes résultats : 
Fermeture application WEB
| PASS |
------------------------------------------------------------------------------
Fermeture application WEB
Parcours Vente Espace Client :: Suite de tests pour valider les fo... | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed
==============================================================================
Output:  C:\Users\robotframework\output.xml
Log:     C:\Users\robotframework\log.html
Report:  C:\Users\robotframework\report.html

**Comment by ialata** [comment]
Voici le script : 

SRX Vente Hors Ordonnance test
    [Documentation]    Vente Hors Ordonnance avec client payée avec deux modes de règlement
    ...    Dispensation de plusieurs produits hors liste
    [Tags]    Vente    Vente_ticketAImprimer
    ######################################################################
    # Parcours Ventes:
    ######################################################################
    Log to console    Lancement du parcours : "SRX Vente Hors Ordonnance avec operation solde ticket à imprimer".
    #Ouvrir application Web    ${URL_HTTP}    ${BROWSER}    ${TITLE_ACCUEIL}
    Ouvrir application Web methode 2    ${URL_HTTP}    ${BROWSER}    ${TITLE_ACCUEIL}
    Aller en Vente Espace de Travail WEB
    Se connecter    ${num_vendeur}
    Demander facture sans ordonnance F4
    Selectionner client sans adresse    &{client_1}[nom]
    Verifier informations client    &{client_1}[nom]    &{client_1}[addresse]    &{client_1}[tel]
    [Teardown]    Finalise_TC

**Comment by ialata** [comment]
Ouvrir application Web methode 2
    [Documentation]    Ouvre le navigateur WEB avec les options définies pour le Browser et vérifie le titre de l'accueil
    [Arguments]    ${URL_HTTP}     ${BROWSER}   ${TITLE_ACCUEIL}
    Set Screenshot Directory    ${EXECDIR}/Screenshot
    Log to console    \n
    Log to console    Ouverture application WEB et verification du titre : ${TITLE_ACCUEIL}
    ${options}=                 config_driver_chrome
    Log to console      Open Browser ${BROWSER} avec desired_capabilities : ${options}
    Open Browser           ${URL_HTTP}       browser=${BROWSER}      desired_capabilities=${options}
#    #Open URL with Local Chrome private mode   ${URL_HTTP}
#    #Maximize Browser Window
    Wait Until Keyword Succeeds	    30s	5s       Select Window	NEW
#    #Get Window Titles
    Close Window
    Wait Until Keyword Succeeds	    30s	5s       Select Window    MAIN
    ${Get_title}=    Get Title
    Should Be Equal As Strings     ${Get_title}   ${TITLE_ACCUEIL}
    Sleep    5s
    #Verifier Logs       texte a verifier dans les logs
    Recuperer Logs

**Comment by ialata** [comment]
from SeleniumLibrary import SeleniumLibrary
from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.options import Options


class ChromeConfiguration():

    def config_driver_chrome(self):
        options = webdriver.ChromeOptions()
        #options.chromever=("73.0.3683.68")
        options.add_argument("--disable-extensions")
        options.add_argument("--disable-extensions")
        options.add_argument("--start-maximized")
        # options.add_argument("--disable-web-security")
        options.add_argument('disable-component-cloud-policy')
        # options.add_argument("--no-proxy-server")
        options.add_argument("--disable-impl-side-painting")
        # options.add_argument("--enable-automation")
        # options.add_argument("--incognito")
        options.add_experimental_option('useAutomationExtension', False)
        options.add_experimental_option('excludeSwitches', ['enable-automation'])
        # options.add_experimental_option("prefs", {
        #     "download.default_directory": r"C:\PDF_SYNTHESE_CAISSE",
        #     "download.prompt_for_download": False,
        #     "download.directory_upgrade": True,
        #     "always_open_pdf_externally": True,
        #     "safebrowsing.enabled": True
        # })
        options.add_experimental_option("prefs", {
            "download.prompt_for_download": False,
            # "download.default_directory": r"C:/Users/esouris/workspace/robotframework/PDF",
            "plugins.always_open_pdf_externally": True,
            "download.directory_upgrade": True})
        #
        # options.add_experimental_option("prefs", {
        #     "download.default_directory": r"C:\Users\xxx\downloads\Test",
        #     "download.prompt_for_download": False,
        #     "download.directory_upgrade": True,
        #     "safebrowsing.enabled": True
        # })

        # options.add_experimental_option('prefs', {
        #     'credentials_enable_service': False,
        #     'profile': {
        #         'password_manager_enabled': False
        #     }
        # })
        capabilities = options.to_capabilities()
        capabilities['goog:loggingPrefs'] = {'performance': 'ALL'}
        #capabilities['loggingPrefs'] = {'performance': 'ALL'}
        return capabilities

**Comment by ialata** [comment]
# Methode pour recuperer les logs du Browser
    def recuperer_logs(self):
        se2lib = BuiltIn().get_library_instance('SeleniumLibrary')
        try:
            for entry in se2lib._current_browser().get_log('performance'):
                entry = entry['message']
                entryjson = json.loads(entry)
                # Format : dict_keys(['message', 'webview'])
                message = entryjson['message']
                # print(type(message))
                # print(message.keys())
                method = message['method']
                params = message['params']
                if method == 'Network.webSocketFrameSent':
                    print('Message Sent: ', params)
                elif method == 'Network.webSocketFrameReceived':
                    print('Message Receive: ', params)

            return params
        # issues while retrieving logs: return empty
        except Exception as e:
            print(str(e))
            return []

**Comment by pekkaklarck** [comment]
En valitettavasti ymmärrä ranskaa eikä kääntäjästä oikein ollut apua. Pystyisitkö kertomaan asian englanniksi?

**Comment by pekkaklarck** [comment]
In other words, I don't understand any French and the automatic translator didn't really help. Could you explain the problem in English (or Finnish or Swedish)?

Notice also that this issue tracker is for bug reports and enhancement requests. If you have a question, they are best asked on our Slack or on the robotframework-users mailing list. I'm sure both have also French speaking users.

**Comment by ialata** [comment]
I just translate in English, thanks in advance.

**Comment by pekkaklarck** [comment]
Do I get it right you'd like to show more information about the execution on the console? There's not built-in way to accomplish that, but you could create a [listener](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#listener-interface) that logs all the relevant information to the console. One of messages to the console can be logged using the `Log To Console` keyword or from test libraries using approaches explained in the [User Guide](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#logging-to-console).

Since there doesn't seem to be any concrete enhancement request or a bug report here, I close this issues. Please send questions to the support forums I mentioned earlier in the future.
