### ISSUE TITLE
"Lists Should Be Equal" cannot compare list with ${EMPTY} since 3.1

### ISSUE THREAD

**Issue by apallier** [robotframework/robotframework#3388]
**Description**
`Lists Should Be Equal` keyword doesn't work anymore when comparing a list with ${EMPTY} since Robot Framework 3.1

**Steps to reproduce**
Execute following testcase with Robot Framework 3.1.2:

```robotframework
*** Settings ***
Library           Collections

*** Test Cases ***
Test
    # I use "Create List" to be more concise but it may be a "real" keyword returning an empty list
    @{list}=    Create List
    Lists Should Be Equal    ${list}    ${EMPTY}
```

**Result**
Testcase fails with this error:
`TypeError: Expected argument 2 to be a list or list-like, got string instead.`

**Excepted result**
Testcase should pass

**Remarks**

1. This test passes with Robot Framwork 3.0.4 (last 3.0)
2. I known... I should use `Should Be Empty` :)

**Version information**
- Python 3.4 win32
- Robot Framework 3.1.2, try 3.1.0 too

**Comment by pekkaklarck** [comment]
This functionality changed when fixing #2580. It was also mentioned in the [RF 3.1 release notes](https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-3.1.rst#other-issues-possibly-causing-backwards-incompatibility-problems) under backwards incompatible changes.
