### ISSUE TITLE
Robot cannot find a locator saved from Katalon Studio 7

### ISSUE THREAD

**Issue by 95rade** [robotframework/robotframework#3389]
Hi,

I am stuck trying to figure out why is it that robot returns error:

"Element with locator 'xpath=//div[@id='root']/div/div[2]/div[2]/div/div[2]/div/div[2]/div[3]/div[10]/div/div/div' not found."

The test was recorded from Katalon Chrome plugin and it executes fine from there. There are several other links in that app that return similar error. Please, please help me resolve this. I am stuck and have no workaround for this. Any suggestions or ideas would be much appreciated. 

Robot Framework 3.1.2 (Python 3.7.1 on darwin), robotframework-seleniumlibrary 4.1.0

thanks,   RM

**Comment by aaltat** [comment]
This issue tracker is reserved for Robot Framework core issues and enhanced request. You are asking support for a SeleniumLibrary library, which is not handled in this GitHub project. For support, please see https://robotframework.org/#/support

**Comment by pekkaklarck** [comment]
Yeah, this is a wrong tracker for SeleniumLibrary related issues. This also looks more like a question than a bug report or an enhancement request.

At least I could't help with this particular issue even if this was the right support forum. Only thing I could say would be to recommend adding ids for more elements. An xpath with anything like `div[2]/div/div[2]/div[3]/div[10]/div` is *very* fragile.

**Comment by 95rade** [comment]
Thanks @aaltat. Will post in the Selenium forum.
