### ISSUE TITLE
Unable to fetch values from red.xml variables

### ISSUE THREAD

**Issue by deepaleekhare31** [robotframework/robotframework#3391]
In my red.xml I have declared a variable ${path}.
![image](https://user-images.githubusercontent.com/50138350/69504389-36d1c300-0f48-11ea-88a6-05de33e9921a.png)

When I try fetching the same in my test suite settings section.
Variables    ${path}/Generic_Configurations/Generic_Config.py
or
Resource    ${path}/Resource_Files/Keywords.robot

It does not show any error from the eclipse editor, even if i do Ctrl+Click, it traverse to the respective file.
But while execution of a testcase I'm getting below error:
Replacing variables from setting 'Variables' failed: Variable '${path}' not found. 

Could u please tell me, why the path value is not being fetched from red.xml?

**Comment by pekkaklarck** [comment]
As far as I can see this is a RED issue. RED has it's own issue tracker where this should be reported. Alternatively you could try asking help on robotframework-users or on our Slack. The latter has a dedicated `#red` channel.

**Comment by deepaleekhare31** [comment]
Thank you so much :)
