### ISSUE TITLE
Automate suite result prefix

### ISSUE THREAD

**Issue by LikHait** [robotframework/robotframework#3392]
In my case I should run each suite one by one.
In this case I have issue - I should manually set results name manually or results will be rewritten.
My proposal is to add command line option as "--automate_results_prefix" which will add prefix for all output files depend on suite name (should work fine with test_name.robot and test_folder)
Usage:
```
robot -x xoutput.xml -o output.xml --automate_results_prefix test_name.robot
```
Result:
```
test_name_xoutput.xml
test_name_output.xml
test_name_log.html
```

**Comment by pekkaklarck** [comment]
I can see this would be useful in some cases, but for the following reasons I don't think it's useful/generic enough to be added:

- It is easy to create a custom script that sets whatever output file names automatically.
- If you want to preserve existing outputs, it's generally best to send files to a dedicated output directory using `--outputdir`. It's easy to give it a custom value using a custom scripts and even manually like `robot --outputdir test_name test_name.robot`.
- We already have `--timestampoutputs` to avoid overwriting existing files. (It has a limitation that you cannot specify a custom timeout format, though.)
- The proposed option wouldn't avoid overwriting output files if you run same tests again.
- The proposed option doesn't allow configuring the format more. Someone might want to have a postfix, not a prefix.

**Comment by pekkaklarck** [comment]
Although I don't think the proposed solution is useful enough to be added, I'm not against enhancing the how output files can be configured. If we add something, that just needs to be more generic. One possibility would be allowing using markers like `%suite%-output.xml` or `<suite>-output.xml` that are replaced with concrete values automatically. That would allow creating custom formats freely, and we could later add other markers, for example, for operating system, Python version, and so on. Anything like this requires a separate issue, though. To get it actually implemented, someone would also need to provide a PR.

**Comment by LikHait** [comment]
> It is easy to create a custom script that sets whatever output file names automatically.

I think I have enough custom scripts. 
The current framework is too sluggish in customization

> If you want to preserve existing outputs, it's generally best to send files to a dedicated output directory using --outputdir. It's easy to give it a custom value using a custom scripts and even manually like robot --outputdir test_name test_name.robot.

I see no difference in the need to set the name of the output file or output folder

> We already have --timestampoutputs to avoid overwriting existing files. (It has a limitation that you cannot specify a custom timeout format, though.)

This name useless for post processing

> The proposed option doesn't allow configuring the format more. Someone might want to have a postfix, not a prefix.

I agree with `%suite%-output.xml` and `<suite>-output.xml` but if it is hard for implementation - I chose the wrong framework

**Comment by pekkaklarck** [comment]
I know something like `%suite%-output.xml` is harder to implement than just adding a prefix. It is also a lot more useful and generic feature. The goal of this framework has always been providing generic solutions, not one-off features that fix one limited use case. Exceptions can be made if generic functionality is really hard to implement, but in this particular case it wouldn't be.
