### ISSUE TITLE
`Process`: Add option to disable stdout and stderr

### ISSUE THREAD

**Issue by atiqrehman10** [robotframework/robotframework#3397]
The option should be added to 'Run Process' arguments to use stdout=NULL or stdout=NONE to disable writing stdout/stderr in general. Same that you can do in shell with > /dev/null.

**Comment by pekkaklarck** [comment]
This would be handy. You obviously can already now redirect stdout/stderr to a temp file and remove it after execution, but if you aren't interested in output at all, discarding it altogether is even more convenient.

The `subprocess` module that the Process library uses internally has [DEVNULL](https://docs.python.org/3/library/subprocess.html#subprocess.DEVNULL) constant for this exact purpose and we could use it the same way we already support [STDOUT](https://docs.python.org/3/library/subprocess.html#subprocess.STDOUT) like `stderr=STDOUT`. A problem is that Python 2.7 doesn't have that constant, but [StackOverflow shows](https://stackoverflow.com/questions/11269575/how-to-hide-output-of-subprocess-in-python-2-7) how to use `os.devnull` in that case. 

Anyone interested to implement this? Could still make it to RF 3.2. It's very unlikely I have time for it but would be happy to review PRs.

**Comment by pekkaklarck** [comment]
The new config should be `DEVNULL` to be consistent with subprocess. It should work both with `stdout` and ` stderr`.

**Comment by adrianyorke** [comment]
PR is on it's way once I've updated the docs and added comments and tests.  Preliminary coding and testing looks good.

**Comment by adrianyorke** [comment]
My third attempt: https://github.com/robotframework/robotframework/pull/3412.  This one incorporates the recommendations @pekkaklarck gave me and I think it is really close to final.  All tests including new tests are passing on both Windows and OSX platforms so looking good.  The documentation has been updated with a paragraph describing the new DEVNULL option for stdout and stderr.  There is also an example showing how to use this new functionality.

**Comment by pekkaklarck** [comment]
Thanks @adrianyorke for the great PR! Third time’s the charm. :smiley:
