### ISSUE TITLE
execute test fail if test case name contains square brackets

### ISSUE THREAD

**Issue by Pastel001** [robotframework/robotframework#3399]
error in python3, console log is like this:
E:\ProgramData\Anaconda3\Scripts>robot.exe --pythonpath E:\ProgramData\Anaconda3\Lib\site-packages --suite Demo.Bug --test Demo.Bug.[bug]test E:\demo
[ WARN ] Automatically parsing other than '*.robot' files is deprecated. Convert 'E:\demo\bug.txt' to '*.robot' format or use '--extension' to explicitly config
ure which files to parse.
[ ERROR ] Suite 'Demo' contains no tests matching name 'Demo.Bug.[bug]test' in suite 'Demo.Bug'.

Try --help for usage information.

E:\ProgramData\Anaconda3\Scripts>pip.exe list | findstr robotframework
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.con
f under the [list] section) to disable this warning.
robotframework (3.1.2)
robotframework-requests (0.4.6)
robotframework-ride (1.7.3.1)
robotframeworklexer (1.1)

E:\ProgramData\Anaconda3\Scripts>cd ..

E:\ProgramData\Anaconda3>python.exe --version
Python 3.6.3 :: Anaconda, Inc.

E:\ProgramData\Anaconda3>

normal in python2,console is like this:
C:\Python27\Scripts>pybot.bat --pythonpath C:\Python27\Lib\site-packages --suite Demo.Bug --test Demo.Bug.[bug]test E:\demo
==============================================================================
Demo
==============================================================================
Demo.Bug
==============================================================================
[bug]test                                                             | PASS |
------------------------------------------------------------------------------
Demo.Bug                                                              | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed
==============================================================================
Demo                                                                  | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed
==============================================================================
Output:  C:\Python27\Scripts\output.xml
Log:     C:\Python27\Scripts\log.html
Report:  C:\Python27\Scripts\report.html

C:\Python27\Scripts>pip.exe list | findstr robotframework
robotframework              3.0.2
robotframework-excellibrary 0.0.2
robotframework-hub          0.9
robotframework-requests     0.4.6
robotframework-ride         1.5.2.1

C:\Python27\Scripts>
C:\Python27\Scripts>
C:\Python27\Scripts>python --version
Python 2.7.12

C:\Python27\Scripts>

**Comment by pekkaklarck** [comment]
The reason is that the value given to `--test` is interpreted as a pattern where `[...]` has a special meaning:
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#simple-patterns

You can, for example, replace `[` with `?` and it ought to work.

**Comment by pekkaklarck** [comment]
This was changed by #2471 in RF 3.1 and also documented in the release notes as a backwards incompatible change:
https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-3.1.rst#changes-to-pattern-matching-syntax

**Comment by Pastel001** [comment]
Thank you
