### ISSUE TITLE
Corrupt XML when dynamically creating test suite

### ISSUE THREAD

**Issue by JanPotma** [robotframework/robotframework#3400]
Hello!
I'm trying to dynamically create a test suite within a keyword, but this results in the output XML of the original test case not completing properly. This seems to be a bug in Robot Framework.

This is the error I'm getting:
`[ ERROR ] Reading XML source 'C:\RobotXMLbug\outeroutput.xml' failed: Incompatible XML element 'statistics'.`

And this is the XML file of the outer test run (i.e. not the dynamically generated one, that one is normal):
```
<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.1.2 (Python 3.7.4 on win32)" generated="20191203 13:32:07.352" rpa="false">
<suite id="s1" name="RobotXMLbug" source="C:\RobotXMLbug">
<suite id="s1-s1" name="Outer" source="C:\RobotXMLbug\Outer.robot">
<test id="s1-s1-t1" name="OUTER_TC">
<kw name="Run Dynamic" library="Dynamic">
<statistics>
<total>
<stat pass="1" fail="0">Critical Tests</stat>
<stat pass="1" fail="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="1" fail="0" id="s1" name="RobotXMLbug">RobotXMLbug</stat>
<stat pass="1" fail="0" id="s1-s1" name="Outer">RobotXMLbug.Outer</stat>
</suite>
</statistics>
<errors>
</errors>
</robot>
```

As you can see, the opening tags in lines 3-6 do not have closing tags, which causes the error.

I've created a small test case and library which produces the bug, which can be found below:
[RobotXMLbug.zip](https://github.com/robotframework/robotframework/files/3916857/RobotXMLbug.zip)
(The folder is intended to be placed in C:\\. To execute elsewhere, you need to adjust the paths in Dynamic.py and run.bat)

Finally, some version information:
Robot Framework 3.1.2
Python 3.7.4 on win32
Windows 10 Enterprise LTSC, version 1809

**EDIT: Description of the example**

This is the code for the keyword library (Dynamic.py):
```
from robot.api import TestSuite
class Dynamic:
    def run_dynamic(self):
        suite = TestSuite("INNER")
        suite.resource.imports.library("Dialogs")
        test = suite.tests.create("Inner")
        test.keywords.create("Pause Execution")
        suite.run(output="C:\\RobotXMLbug\\inneroutput.xml")
```

I'm calling the test with `C:\Python37\Scripts\robot.exe -o C:/RobotXMLbug/outeroutput.xml C:\RobotXMLbug`

Finally, this is the test suite (Outer.robot):
```
*** Settings ***
Library           Dynamic.py

*** Test Cases ***
OUTER_TC
    Run Dynamic
```

**Comment by pekkaklarck** [comment]
Could you clarify how do you add that test suite? I'm on mobile and cannot open the zip. Such basic info should preferably be visible in the issue in general.

**Comment by JanPotma** [comment]
Apologies, I've updated the issue with the contents of the files.

**Comment by pekkaklarck** [comment]
Your keyword ends up creating and running a new test suite and that execution round apparently uses same output.xml file as the tip level execution. As the result they write to same file and the file gets corrupted.

You can run the inner suite so that it uses some other output file.

**Comment by JanPotma** [comment]
I must be overlooking something, since that's exactly what I tried to do. The outer suite writes to outeroutput.xml, and the inner suite writes to inneroutput.xml. What am I doing wrong?

**Comment by pekkaklarck** [comment]
Oh, didn't realize you used different output.xml files. In that case my guess is that this is due to the fact that you cannot really run multiple tests execution rounds in parallel in same process. We have an old issue #1083 about that, and although I hope it will be resolved some day I cannot give promises when.

A workaround to this problem is running tests using external processes. In your case you could have a separate Python script that you run via Robot and that then constructs a test suite and executes it. Depending on your actual use case, you could possibly also use the listener or pre-run modifier APIs to add tests dynamically to the executed suite. Discussing about possible alternatives belongs to actual support forums, though, not to this issue tracker.
