### ISSUE TITLE
Invalid sytax for suite format but without error

### ISSUE THREAD

**Issue by yo-ga** [robotframework/robotframework#3402]
### Description
In a robot file, the user can execute the following content without error

```robot
*** Setting ***
Library    SSHLibrary
Library    Screenshot
Library    DateTime
Library    Process

*** Variable ***
${var1}=  10

*** Keyword ***
Test Keyword
    Log  ${var1}

*** Test Case ***
Test
    Test Keyword
```

According to the document, it should be
```robot
*** Settings ***
Library    SSHLibrary
Library    Screenshot
Library    DateTime
Library    Process

*** Variables ***
${var1}=  10

*** Keywords ***
Test Keyword
    Log  ${var1}

*** Test Cases ***
Test
    Test Keyword
```

### Environment
- Robotframework: 3.1.2
- Python: 3.5.4
- OS: macOS Catalina 10.15.1

**Comment by pekkaklarck** [comment]
Is the difference that the first one uses headers like `*** Setting ***` while the latter adds `s` at the end like `*** Settings ***`? If yes, that's a [documented feature](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#test-data-sections).

**Comment by yo-ga** [comment]
I missed this part of the document. Both of them are able to generate the same result.
I'll close the issue. Thanks for your comment.
