### ISSUE TITLE
AppiumLibrary

### ISSUE THREAD

**Issue by Adi-2020** [robotframework/robotframework#3404]
I am using appiumlibrary-robot framework in eclipse.
I am using my real device and have few queries as I stuck there.

1. While running my script in eclipse I am opening appium studio and then launch real device is that right practice else how to add and view real device interface in eclipse. In run configuration of eclipse I am not able to set my device under robot preference. any solution?
2. The app under test is opening properly with selected field for user name but keyboard is not displaying till I tab to password field. How to open keyboard and select the user id.
I dont want to Input Text directly.

Thanks 
Adi

**Comment by HelioGuilherme66** [comment]
@Adi-2020 This is issue tracker for problems or enhancements, not for questions (like you already did on Slack).
