### ISSUE TITLE
String Operations using \ not working consistently

### ISSUE THREAD

**Issue by Sumitdeshmukh05** [robotframework/robotframework#3406]
I tried to replace \ with / using following code but it added / before every character

Code : 

${UpdatedPath}    Replace String    C:\Users\Dummy\eclipse-workspace\ExcelManipulation    \    /     Log to console    \nUpdated Path : ${UpdatedPath}

Output 

Updated Path : /C/:/U/s/e/r/s/D/u/m/m/y/e/c/l/i/p/s/e/-/w/o/r/k/s/p/a/c/e/E/x/c/e/l/M/a/n/i/p/u/l/a/t/i/o/n/

Also when I replaced \ with   double \   it eliminated all \ and gave the output as follows

Code

${UpdatedPath}    Replace String    C:\Users\Dummy\eclipse-workspace\ExcelManipulation    \\    /    
 Log to console    \nUpdated Path : ${UpdatedPath}

Output 

Updated Path : C:UsersDummyeclipse-workspaceExcelManipulation

**Comment by pekkaklarck** [comment]
These examples are formatted somewhat strangely, so it's impossible to tell what exactly happens. That said, have you looked what the User Guide says about using `\` as an escape character?

**Comment by pekkaklarck** [comment]
I'm now looking this now on a bigger screen, not on mobile, and it's easy to see that the problem. Find the aforementioned section about escaping in the User Guide and/or try this to understand what's going one:

```
    Log to console    C:\Users\Dummy\eclipse-workspace\ExcelManipulation
```
