### ISSUE TITLE
Add `--maxassignlength` to control how much to automatically log when assigning variables

### ISSUE THREAD

**Issue by CharterMitch** [robotframework/robotframework#3410]
Similar to #2576 I have a use case that requires increasing the _MAX_ASSIGN_LENGTH variable in Utils/text.py when running robot tests.

The implementation and CLI flag --maxassignlength would mimic --maxerrorlines.

--maxassignlength documentation would show the default MAX_ASSIGN_LENGTH of 200 words and allow the value to be increased when running robot.

It would also be nice to set the default behavior of format_assign_message(cut_long=True) to cut_long=False. Perhaps as a --assignlogall flag?

**Comment by pekkaklarck** [comment]
Quick comments:

1. I'd prefer only increasing the value of `_MAX_ASSIGN_LENGTH` from 200 characters to something like 400. Trivial to implement and updating tests and docs shouldn't be a big task either. Could still make it to RF 3.2 if someone would create a pull request.

2. Adding `--maxassignlength` (or possibly `--maxassignmessage` or even `--maxassignmessagelength`) that works similarly as `--maxerrorlines` is possible but a lot bigger task than 1. If someone finds this important enough to create a pull request, I'd be happy to review it. I won't have time for that before RF 3.2, though.

3. I absolutely don't want to have more than one setting to control this behavior. That one option could have way to tell everything to be logged, for example, like `--maxassignlength -1`. I think `--maxerrorlines` had such a feature and this one should be consistent.

4. In general keywords should log information that is important themselves. Relaying on automatic logging when variables are created feels a bit strange for me, especially when no such logging occurs if there's no variable assignment.

**Comment by wuwentao** [comment]
Hi Robot support team.

we are also want to get full log in robot log file.
For example, robot script will run in linux server, and do an tcp socket to windows pc, then execute python script in windows remote PC for GUI automation, it's out of the linux/robot/windows command line control.
this python script will return all the execute log and response to robot, and robot can check/confirm all the steps/error/exception.

without robot, we can manual run this python script, but it's a part of robot script, we want to run all these script in robot test suite.

is there any option can be add to robot script content and enable the full log?  command line is not a good solution, it's a hard code solution and need manual add action when we run all scripts at the same time. 


Thanks

**Comment by MitchellMahan** [comment]
+1 for this feature. I am using Robot Framework for a lot of network validation cases where the log.html becomes an artifact.
I have had to forke the repo internally and set trim_long=False in utils/text.py but not diverging would be more ideal.

**Comment by pekkaklarck** [comment]
`--maxerrorlines` (#2576) has turned out to be useful so let's add `--maxassignlength` in RF 4.1 as well. Probably could increase the default at the same time as well.

**Comment by pekkaklarck** [comment]
I want to get RF 4.1 released soon and don't consider this important enough to be included into it. I move this into RF 5.0 scope. Unless someone provided a pull request implementing the functionality, there's a risk this issue will be descoped from it as well.

**Comment by pekkaklarck** [comment]
There's a new PR #4261 implementing this which means we could still get this into RF 5.0.

**Comment by pekkaklarck** [comment]
This was implemented in PR #4261 by @miktuy and then enhanced slightly in the commit above. Thanks for contribution!
