### ISSUE TITLE
[Collections] Count Values In List when list is empty

### ISSUE THREAD

**Issue by nefethael** [robotframework/robotframework#3413]
Would it be possible `Count Values In List` returns 0 when given list is empty?

Example of usage:
```
| Check Stuff
| | [Arguments] | ${excl_elt_lst}=@{EMPTY}
| | FOR | ${cnt} | IN RANGE | 1 | ${NBELEM}+1
| | | ${nbm}= | Count Values In List | ${excl_elt_lst} | ${cnt}
| | | Run Keyword If | ${nbm} > 0 | Check Other Stuff
| | END
```

Current workaround is to add a check on list length and execute counting if not zero.

**Comment by pekkaklarck** [comment]
It should already work like that. Can you create a simple example demonstrating your problem? No for loops or anything else, just usage of this keyword with an empty list.

**Comment by nefethael** [comment]
@pekkaklarck Sorry, it's working as intended, I just had a problem comparing values between integers and strings
