### ISSUE TITLE
default setup in __init__.robot cause exception

### ISSUE THREAD

**Issue by jcyrss** [robotframework/robotframework#3416]
I put 4 files in test cases dir like the following:

![image](https://user-images.githubusercontent.com/10496014/70994728-cdd60900-2109-11ea-82e6-823dccc8a261.png)

the content in ```function1.robot```  is like the following

```c
*** Settings ***

Library  function1.py   WITH NAME  F

Library  function1.c1   WITH NAME  c1


*** Test Cases ***

add order - 00001

  c1.teststeps
```

the content in ```__init__.robot``` is like the following

```c
*** Settings ***

Library  __st__.py   WITH NAME  D

Suite Setup    D.suite_setup

Test Setup    D.test_setup
```

so, when I run test, robotframework will call suite setup and default setup before executing the case ```add order - 00001```.

But robot could run suite setup successully, while run default setup failed and report ```No keyword with name 'D.test_setup' found.```

![image](https://user-images.githubusercontent.com/10496014/70995253-104c1580-210b-11ea-8283-4788b1184c9a.png)

also,  the whole test cases directory attached.

[cases.zip](https://github.com/robotframework/robotframework/files/3973236/cases.zip)

**Comment by pekkaklarck** [comment]
Having test setup/teardown in suite init file is supported, but it only specifies the keyword to use. That keyword then needs to be available *where* that setup is actually executed. In other words, you need to import the library `D` in the test case file or in a resource file imported by that test case file.

Could you check what the User Guide says about this and could it be enhanced?

**Comment by jcyrss** [comment]
I get it. 

But imaging if we have multiple levels suites with multiple test setup, we need to import every neccery libraries in very test cases file carefully.

Could RF be enhanced to be free from that limitation? That would be really convinient.

**Comment by pekkaklarck** [comment]
Could you clarify what exactly is the problem of test case files needing to import libraries they use? Do you have concrete idea how RF should be enhanced? If we agree on that, are you interested to provide a pull request?

**Comment by jcyrss** [comment]
Because test case file does not use default setup explicitly, I mean there is no any keyword from that library you could find in test cases file.  Developer need to check what libraries are used for default setup in test case file carefully.  

Sorry I'm not familiar with the source code of RF. So I could not modify it for now.

Anyway, RF it great, and has really help me a lot already, Thank you.

**Comment by pekkaklarck** [comment]
In my opinion the confusing feature is being able to specify default test setup/teardown in higher level suites in the first place. The fact that the setup/teardown keyword then needs to be available in the suite where it is actually used isn't that strange in my opinion. It also means that you can specify some setup/teardown name in an init file, and in different files in that same directory import different resources/libraries so that the actually executed keyword is different.

Anyway, this logic won't be changed.
