### ISSUE TITLE
Import ABCs from 'collections' Python 3.8+ Deprication

### ISSUE THREAD

**Issue by datGryphon** [robotframework/robotframework#3419]
The abstract base classes that were part of the top level `collections` library were moved into the `collections.abc` module as part of Python 3. 

In Python <=3.7 there is a mapping in place that allows backward compatability with the old Python 2.7 import. 
```python 
from collections import Mapping, UserString
```
However, this format is not supported for Python 3.8+. Import statement of this variety are at least present in robot.utils.robottypes3 and robot.utils.normalizing. They can be switched to import statements of the following form without modifying the rest of the file. 

```python
try:
    from collections import Mapping, UserString
except ImportError as err:
    from collections.abc import Mapping, UserString
```

**Comment by pekkaklarck** [comment]
This is already fixed by #3213.
