### ISSUE TITLE
Continuous integrating (CI)

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#3420]
Our project hasn't had CI since the Nokia Network days when we had a Jenkins based system that was running tests on Linux and on Windows using Python, Jython and IronPython.

Luckily all our acceptance tests run in less than 10 minutes (at least on my not-so-new-anymore Linux laptop) so it's easy to run them before commits. Differences between OSes and Python interpreters are also relatively small (and we have great utils hiding differences) so typically running tests on a single OS/Python combination is enough. A good CI system would, nevertheless, have lot of benefits:

- Run tests in all/most supported OS/Python combinations to reveal problems on all of them faster. Nowadays issues with, for example, Jython and IronPython are typically noticed closer to releases and fixing them can take some extra time.
- Make it possible to commit "safe" changes without running all tests locally: the CI will soon tell if there are problems. With any larger change running tests locally would be a good idea anyway.
- Allow running tests against pull requests. This would be very nice.

There has been quite a lot of discussion about adding CI support. There are many different possible solutions, but common ideas have been:

- Use Travis or some other freely available CI system. This would be pretty setup and integrate with GitHub. Unfortunately such free solution typically only support Linux and Python, not Windows, Jython and IronPython that are important for us. Adding Windows to the mix might be possible but requires paying and/or using some other service. Having a Linux/Python only solution doesn't give much benefits compared to running tests locally before a commit.

- Build a custom CI using Jenkins, Azure Pipelines, or some other option. Our old Jenkins based CI system worked well, but maintaining it took some effort and there were also costs related to virtual machines. Setting up (and paying for) such a service has been on the [Robot Framework Foundation](https://robotframework.org/foundation/) agenda for a long time, but so far there hasn't been much concrete progress.

- Use [GitHub actions](https://github.com/features/actions). This is a new but very interesting looking solution. It seems to be about as easy to configure as Travis but also supports Windows and even OSX out-of-the-box. And it naturally has built-in GitHub integration. We even have PRs #3386 and #3390 demonstrating how it could be used. At the moment this looks the best solution for me and definitely something we should investigate more. 

One problem with all this is that my personal knowledge about CI systems is somewhat limited. Another problems is that I don't have that much time available and I'd rather use that for Robot Framework development than studying CI systems in detail. Luckily several companies in the Robot Framework Foundation have extensive CI experience and they ought to be able to help. I've already briefly discussed with @IsNoGood, @Tattoo and @Hi-Fi and hope that some of them, or possibly them as a group, could take the main responsibility driving this forward. Can you guys comment what's your current status and do you think you'd have time to look at this in the near future? The GitHub Actions work already done by @tysonite in the aforementioned PRs also looks really good and I assume he'd be willing to continue that work. The first step would thus be studying those PRs.

Let's use this issue for general discussion about CI and save more detailed discussion to the existing or new PRs. We can also use the #devel channel on our [Slack](https://robotframework-slack-invite.herokuapp.com/) for more interactive chatting.

**Comment by Hi-Fi** [comment]
I think those PRs are good start, and as mentioned in #3386, #3390 is better one to merge and start using CI. It might be that acceptance test run is needed e.g. for the PRs already, but currently I think it's good to get started and to see if that 12 hour interval is OK for acceptence testing.

At some point also releasing should be added to those, but I think multi-OS testing brings great value.

One issue that I faced with Github actions is that the test results are not coming to PR from forked repo in a way that those results could be used for enforcing passed tests (e.g. https://github.com/robotframework/JavalibCore/pull/25/commits doesn't show results for commit, even those are made and visible at https://github.com/Hi-Fi/JavalibCore/commits/general_varargs). This is know "security feature" (https://github.community/t5/GitHub-Actions/GitHub-Action-workflow-is-executed-for-a-PR-from-a-forked-repo/m-p/29683#M176). But still, I thin this is not reason to delay taking Github actions to use.

**Comment by cclauss** [comment]
> Use Travis or some other freely available CI system. This would be pretty setup and integrate with GitHub. Unfortunately such free solution typically only support Linux and Python, not Windows, Jython and IronPython that are important for us. Adding Windows to the mix might be possible but requires paying and/or using some other service. Having a Linux/Python only solution doesn't give much benefits compared to running tests locally before a commit.

I think there are many out-of-date statements in this paragraph when it comes to GitHub Actions, Travis CI, CircleCI, and Azure Pipelines...   All of these systems now support free out-of-the-box testing on Linux, macOS, and Windows for Open Source projects like this one.  On Travis CI (and probably others) even legacy platforms such as IronPython and Jython can still be tested.

**Comment by cclauss** [comment]
#3390 Demonstrates IronPython and Jython testing on GitHub Actions.

**Comment by pekkaklarck** [comment]
Yeah, I already commented that GItHub Actions has great platform support. Didn't know also Travis nowadays would support Windows, though.

**Comment by pekkaklarck** [comment]
:loudspeaker: We made a decision that @Hi-Fi will drive this work forward in collaboration with the contributors. He has maintainer access to this repo so he can merge PRs once he considers them ready. It seems we'll use GitHub Actions but he can make the final decision about that as well.

**Comment by tysonite** [comment]
JFYI. The latest updates on acceptance and unit tests runs for those who interested:
1. Unit tests are [passing](https://github.com/robotframework/robotframework/commit/256844cd946a9fdee19f4319874812d4a72897e9/checks?check_suite_id=371323664) on all OSes and Python interpreters except IronPython, and thus IronPython disabled.
2. Acceptance tests are [passing](https://github.com/robotframework/robotframework/commit/256844cd946a9fdee19f4319874812d4a72897e9/checks?check_suite_id=371323674) on all OSes and CPython + PyPy with some flakiness:
a. `Robot.Running.Timeouts With Logging.Timeouts with programmatic logging` test: https://github.com/tysonite/robotframework/runs/360272931#step:5:83
b. `Robot.Running.Timeouts With Logging.Timeouts with programmatic logging` test: https://github.com/tysonite/robotframework/runs/360073530#step:5:81
c. `stopping_with_signals.robot` test were [disabled](https://github.com/robotframework/robotframework/commit/409e35a6819374e4e97c1b79b657952c97152456#diff-bc77d9acb76c4b766d6d4aae5552dd22R4) on Windows

Acceptance tests for [IronPython](https://github.com/tysonite/robotframework/commit/d6195f8efd0a8c688837e13272dd1df9b3ef3363/checks?check_suite_id=370798242) and [Jython](https://github.com/tysonite/robotframework/commit/d6195f8efd0a8c688837e13272dd1df9b3ef3363/checks?check_suite_id=370798249) are unstable / failing.

**Comment by pekkaklarck** [comment]
We now have CI running on master. I guess this issue can be closed and others opened to track further enhancements.

**Comment by pekkaklarck** [comment]
Huge thanks @tysonite and @Hi-Fi for your work!
