### ISSUE TITLE
CI: "Robot.Running.Timeouts With Logging.Timeouts with programmatic logging" acceptance tests fail from time to time

### ISSUE THREAD

**Issue by tysonite** [robotframework/robotframework#3430]
Related to [PR](https://github.com/robotframework/robotframework/pull/3428).

The test `Robot.Running.Timeouts With Logging.Timeouts with programmatic logging` fails randomly on any combination of Python and OS. Either this is test case flakiness, or robot misbehaviour.

Logs are there: https://github.com/robotframework/robotframework/pull/3428/checks?check_run_id=365059240

**Comment by pekkaklarck** [comment]
Has this happened lately? Or were those tests just disabled?

**Comment by tysonite** [comment]
I think you have fixed them here: 698fb2e51 ("Refactor tests to hopefully prevent strange issues on CI.", 2020-01-04). I haven't seen they were failing after that.

**Comment by pekkaklarck** [comment]
Ok, I guess we can close this then.
