### ISSUE TITLE
CI: stopping_with_signal suite fails on Windows

### ISSUE THREAD

**Issue by tysonite** [robotframework/robotframework#3431]
When running tests from `stopping_with_signal` suite on Windows, output of robot stops and exit code is not equal to 0 even if all tests pass.

Related to [PR](https://github.com/robotframework/robotframework/pull/3428/files#diff-bc77d9acb76c4b766d6d4aae5552dd22).

**Comment by pekkaklarck** [comment]
This has been fixed.
