### ISSUE TITLE
Add best practices to user guide

### ISSUE THREAD

**Issue by atiqrehman10** [robotframework/robotframework#3432]
The user guide should contain best practices for writing robot tests. I have an initial set of best practices which can be improved and enhanced.

1. Write all tests in Behaviour Driven Development (BDD) style i.e using Given, When and Then.
2. Take advantage of robot framework's tracing i.e write as much behaviour as possible in robot instead of python
3. Use appropriate abstraction level in keywords and test case names 
4. The tests should show WHAT is being tested, not HOW!
5. Tests should not contain complex logic; no FOR loops or IF-ELSE blocks. These can be used in the keywords though.
6. Use Join Path and avoid many slashes in the path
7. One test case should test one thing
8. Use Consistent variable names, avoid hard coding
9. Document reusable keywords
10. Use proper indentation
11. Reuse and extend the keywords already defined in common resource files
12. Use Suite Setup and Tear Down to speed up execution
13. Use Test Setup and Tear Down
14. Maximum 10 tests in a suite are recommended if they are not data driven
15. Maximum 10 steps in a test case are recommended, preferably less
16. Avoid sleeping, use polling where possible

**Comment by pekkaklarck** [comment]
Guidelines are important but I don't think the User Guide is the right place for them. We actually already have [HowToWriteGoodTestCases](https://github.com/robotframework/HowToWriteGoodTestCases/blob/master/HowToWriteGoodTestCases.rst) which could be enhanced or even recreated if needed.

Notice also that it is hard or even impossible to create string guidelines that match all context. For example, I disagree all tests should be written using Given/When/Then style and think it is very often a good idea to move logic to Python.
