### ISSUE TITLE
New to robot framework and I've got questions

### ISSUE THREAD

**Issue by Quietbeat** [robotframework/robotframework#3434]
My manager wants to use RF and I'm use to better 3rd-party apps like TestComplete so I'm trying to figure out how to get some usefulness out of RF.

- How can I set a global variable then have it overridden in a script?

- We're using PyCharm and I want to know if there's a better UI that allows managing the numerous scripts so I can 1) see the run history of any script, 2) select scripts from multiple folders to be included in a test run (no tags), 3) 

- How to change the Report so it's not so ugly

**Comment by trogdor259** [comment]
I'd suggest starting with the [documentation](https://robotframework.org/). There are instructions for everything. This github project is for reporting bugs only. There is also a slack server you can go to for help.
