### ISSUE TITLE
Robot 3.1.2: rebot --merge not working for tests failed with different reason

### ISSUE THREAD

**Issue by GouthamD** [robotframework/robotframework#3435]
We use below command for merging tests after re-run -
 `rebot --outputdir results --output merged.xml --nostatusrc --merge --noncritical skipped results/original.xml results/rerun.xml` 
It used to work fine with the Robot Framework version we used previously i.e. 3.0.2

After upgrading Robot Framework to 3.1.2, we face below issue.
In re-run, when test fails with a different reason then, the final report after merging gives two entries in the Robot report as shown in below screenshot.

![Rebot-NotMerged](https://user-images.githubusercontent.com/25796353/72347713-bedd7900-36fe-11ea-914c-4dc78cccae1b.png)

But, when test fails with same reason in re-run then, result is getting merged as shown in below image.

![Rebot-MergedResult](https://user-images.githubusercontent.com/25796353/72347761-d6b4fd00-36fe-11ea-9550-879340e4dc44.png)

Can anyone please address this issue?

**Comment by pekkaklarck** [comment]
This should not happen. Please provide a simple executable example demonstrating the issue so that we can investigate it.

**Comment by GouthamD** [comment]
@pekkaklarck Thanks for your reply. 
We observed that this issue is happening due to duplicate folders in the repository. When we merged these duplicate folders, the issue not appeared again. Hence, I'm closing this ticket.
