### ISSUE TITLE
robotfixml support for py3

### ISSUE THREAD

**Issue by ashishk-mfe** [robotframework/robotframework#3438]
Can robotfixml be supported for py3. currently it is using beautifulsoup3 , and that is not supported for py3. we are using [robotfixml](https://pypi.org/project/robotfixml/) in our automation, and it broke due to py3 migration.

with bs4 , the fixxml tool is giving issues that needs to be checked.

**Comment by pekkaklarck** [comment]
It certainly can but that tool has its own project and issues related to it belong there. The project seems to still be on BitBucket and I guess the first step would be moving it to GitHub. I won't have time for anything like that in the near future. Do you @ashishk-mfe have time and interest to help with it?

**Comment by pekkaklarck** [comment]
Discussion about this external tool can continue somewhere else. This tracker is for Robot Framework core issues only.
