### ISSUE TITLE
How to pass **kwargs to robot and use them in Test Setup?

### ISSUE THREAD

**Issue by viennacruise** [robotframework/robotframework#3444]
Hi,

I'd like to pass keyword arguments to ROBOT by calling the following line in Python:

`result = robot.run(SuitFolder, **kwargs)`

My wish is to pass some user-specific initialization variables into the **kwargs and initialize the test suite in the robot "Test Setup" function as given within the **kwargs. 

Does anybody know if this can be done and how?

Thanks in advance!

Harry

**Comment by laurentbristiel** [comment]
Hi @viennacruise! If you have question about usage of Robot Framework the Issues of GitHub are not the right place. You should rather pick one of the different channels mentioned in ["Support and Contact" section of the README](https://github.com/robotframework/robotframework#support-and-contact). For example, the [Slack](https://robotframework-slack-invite.herokuapp.com/) is quite active and would be a good place to engage discussion. If you end up with an improvement request, then you can raise an issue in GitHub.

**Comment by viennacruise** [comment]
Hi @laurentbristiel,
sorry for that, I understand your point! Sorry for the inconvenience! I've added my question to Slack and Google Groups, hoping for an answer...
