### ISSUE TITLE
Parsing and saving TestData is inconsistent 

### ISSUE THREAD

**Issue by epavese** [robotframework/robotframework#3450]
I would expect that parsing a Test and immediately writing it to file produces the same output
The results is indeed functionally the same, but comments and other elements get mixed and/or shifted. This is confusing when producing a tool intended to automatically process pre-written files but also keep them readable as intended 

Some examples. The input file has been processed with the snippet:
```
import sys
from robot.api import TestData
from io import StringIO

suite = TestData(source="test_file.robot")
s = StringIO()
suite.save(output=s)
print(s.getvalue())
```
input file:
```
*** Settings ***
Resource          setup.robot
Force Tags        ISSUE-10945

# This is a comment
# This too

*** Comments ***
This is a comment

*** Comment ***
    This is also a comment

*** Test Cases ***
Basic test 2
    [Tags]    tag_number_1    tag_number_2    tag_number_3    tag_number_4    tag_number_5    tag_number_6    tag_number_7    tag_number_8
    Then    1 == 1

*** Test Cases ***
Basic test 1
    [Tags]    tag_number_1    tag_number_2    tag_number_3    tag_number_4    tag_number_5    tag_number_6    tag_number_7    tag_number_8
    Then    1 == 1
```

result after running code
```
*** Settings ***
Force Tags        ISSUE-10945    # This is a comment    # This too
Resource          setup.robot

*** Test Cases ***
Basic test 2
    [Tags]    tag_number_1    tag_number_2    tag_number_3    tag_number_4    tag_number_5    tag_number_6
    ...    tag_number_7    tag_number_8
    Then    1 == 1

Basic test 1
    [Tags]    tag_number_1    tag_number_2    tag_number_3    tag_number_4    tag_number_5    tag_number_6
    ...    tag_number_7    tag_number_8
    Then    1 == 1
```

Issues:
* Comment tables are not output
* Elements (Force Tags, Resource) get reordered
* Inline comments get mixed into other elements and in the same line
* Separate tables are merged
* Tags lines are broken into more lines

**Comment by pekkaklarck** [comment]
This is true and also one of the main reasons the old parser has been rewritten (#3076). The new parser is part of RF 3.2 that is expected to be released in March. If you interested to build tools on top of the new parser, I recommend you to test the preview releases (beta 1 is the latest one) and give us feedback. At last simple enhancements are still possible before the final release.

**Comment by epavese** [comment]
Thanks! I'll be sure to check the beta features
