### ISSUE TITLE
Expose test line number via listener API v2

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#3451]
Nowadays executed `TestCase` objects have line numbers available (#549). This means they are automatically exposed via listener API v3 and we should also expose them via listener API v2.

Unfortunately we cannot easily expose keyword line numbers via listeners. API v3 doesn't even have the `start/end_keyword` methods due to technical reasons (#3296) and same reasons prevent exposing them via API v2.

**Comment by boakley** [comment]
_"Unfortunately we cannot easily expose keyword line numbers via listeners."_ - this seems to make no sense. If you have the line numbers in the object, and the objects are available when the listener is called, why can't they be exposed to the listener? Why can't you just add additional keys in the `attributes` argument? 

This is disappointing, because it makes the addition of line numbers virtually useless.

**Comment by boakley** [comment]
I did some quick experimenting, and it _seems_ that to support listerner v2 only requires changing a dozen or so lines of code. Admittedly, I have a very, very shallow understanding of the internals of robot so maybe I'm missing something. However, I was able to write a v2 listener that could log the source file and line number of both a library keyword and user keywords in the test file and in a resource file. 

Of course, that "dozen lines" will balloon into a hundred or so when we add in tests and documentation of course, but at it seems like a very straightforward change at first blush. So I'm wondering if you're open to a PR, or are you simply opposed to exposing line numbers to a v2 listener for a philosophical reason.

**Comment by pekkaklarck** [comment]
There's absolutely no philosophical reason why line numbers weren't added to `start/end_keyword` methods of v2 listeners. When I looked it at earlier, it just didn't look too easy. The main reason is that the code creating the `attributes` dictionary gets results objects that don't have line numbers. It probably wouldn't be too hard to add line numbers to those objects but I don't think _that_ is a good idea. It would be strange if keyword result objects had line numbers during execution but not if they are read from output.xml. And I don't think it makes sense to add that info there. Anyway, if you want to work on this it would be great.

**Comment by boakley** [comment]
I may submit a PR, though the only solution seems to be to add line numbers to the result objects and you seem opposed to that. I don't want to put in a bunch of effort just to have it rejected.

**Comment by pekkaklarck** [comment]
There are two ways how to implement this:

1. Add line numbers to result objects. They should be added to all result objects, not only to keywords. They should then also be added to output.xml to be able to construct same result objects based on it. The problem is that this will increase the output.xml size and slow down processing it.

   I don't know how big the effect would be in real life, but it needed to be measured. It could very well be that adding line numbers to result objects just isn't worth it. Personally I'm not interested to test this at least in RF 3.2, but if you are that's great. The first step would be submitting an issue about adding line numbers to result objects. The next would be doing the changes and measuring what kind of performance impact there is.

2. Change the code so that we can pass both the data and the result object to listeners. After that we could then trivially support `start/end_keyword` with listener v3 as well (#3296). This would be awesome but unfortunately the changes needed to the execution side are quite big. After the total parsing rewrite I don't have interest or energy look at that anymore before RF 3.2. Bigger execution side changes are planned in RF 4.0 and after them implementing this will be easy.
