### ISSUE TITLE
Possible changes to tokens returned by new parser

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#3458]
The new parser (#3076) seems to work pretty well but there is still room for improvements. Improvements discussed in this issue are related to tokens that the lexer component of the parser produces. Changes would not affect the execution side at all but could benefit external tools using the parser.

-----------------------

**UPDATE:** Possible enhancements enumerated in this description (1.-4.) and in later comments. This is the summary of them:

- [x] 1. Tokenizing settings: Done in ba896707519c2bc73cba914435d8fe79a5ffe847.
- [x] 2. Tokenizing `WITH NAME`. Done in c75e480ebecaa7185f2c082258fd8a3b668887bc.
- [x] 3. Handling test case section in resource and suite initialization files when using resource/init specific entry points. Done in a6ec45e28acb787b768c4017b4137c2bb6adc86d.
- [x] 4. Handling test case section in suite initialization files when using `get_tokens/model`. Won't be done. See the [comments below](https://github.com/robotframework/robotframework/issues/3458#issuecomment-583607615) for details.
- [x] 5. Variable name and value validation. Done in 0b96c35ed7e8c61d972f6bf5d0170bfa0b1aba39 and 673535a79b28ff1af94d201c8a471c42df674e55.
- [x] 6. FOR loop header types. Done in 84c43027aaf370fb4bf43bee08de5a23d5d8a21f.
- [x] 7. FOR loop validation. Won't be done for RF 3.2. Can (and should) be done later when IF/ELSE support is added and we probably want to validate that.
-----------------------

### 1. Tokenizing settings

At the moment settings like

```robotframework
*** Settings ***
Library          ExampleLibrary
Test Setup       Keyword    argument
Force Tags       tag1    tag2
```

are tokenized so that the setting name gets a specific token type (`LIBRARY`, `TEST_SETUP` and `FORCE_TAGS` in the above cases) and all setting values get the `ARGUMENT` type. This means, for example, that `Keyword` and `argument` both have the `ARGUMENT` type while the former is actually a keyword name. Also `ExampleLibrary` would be categorized as an argument while it's actually a name and libraries actually can have their own arguments. With tags all values getting the `ARGUMENT` type is probably ok.

Should we change this logic so that with settings that have a value that itself consists of a name and values, we'd tokenize the name differently? In my opinion that sounds like a good idea. It would not be a big change for our lexer and would also simplify further processing on the AST level a bit.

If we do the above change, we still need to decide what new tokens to introduce. Possibilities include:

- Add separate tokens tokens for library name, resource file name, keyword name in setup/teardown, etc. I don't think that's a good idea because it would increase the number of tokens unnecessarily and because there's already the setting specific token like `LIBRARY` or `TEST_SETUP`.

- Use the `NAME` type with all these name tokens. This sounds pretty good, but we already use the `NAME` type with test and user keyword names. These token types should probably be changed in that case.

- Use the `KEYWORD` type with setup/teardown names (we use that already with normal keyword calls), introduce new `IMPORT` type for libraries, resources and variable files, and some other new type for suite metadata. Small benefit compared to using just `NAME` would be that all keywords would have same type and could thus be easily syntax highlighted with the same color. A problem would be that setup/teardown keywords are special because their name can contain variables. That would make it harder to implement generic tokenization of variables in token values (#3449).

### 2. Tokenizing `WITH NAME`

This is basically a special case of the above discussion related to tokenizing settings:

```robotframework
*** Settings ***
Library          ExampleLibrary    argument    WITH NAME    Custom Name
```

At the moment the above is tokenized to a `LIBRARY` token and four `ARGUMENT` tokens and recognizing the `WITH NAME` syntax is done only later by the parser. In my opinion it would be better if there would be a separate `WITH_NAME` token the parser could then recognize without anymore looking at the token value.

If we introduce the new `WITH_NAME` token, then the question is what type to use with the token following it. Adding yet another type like `WITH_NAME_VALUE` for this special case doesn't sound like a good idea but this token clearly isn't an `ARGUMENT` token either. My thinking is that it would be best to use the same type with it that we use with the original library name. In other words, the example above could then be parsed to these tokens:

LIBRARY
NAME
ARGUMENT
WITH_NAME
NAME

### 3. Handling test case section in resource files

At the moment the lexer accepts test case section regardless is `get_tokens` or `get_resource_tokens` used. When parsing resource files, the parser then later reports a test case section in a resource file an error.

It would be more logical if a test case section would be an error when using `get_resource_tokens`.

### 4. Handling test case section in suite initialization files

If a suite initialization file (`__init__.robot`) has tests, it is reported as an error by the parser, but actually the lexer should already detect that. We don't have a separate entry point to tokenize an init file, but `get_tokens` could detect this situation automatically based on the file name. **Update:** Separate `get_init_tokens` was added by 45cbe2883d024095f20b0bd2f4f5f77d02a172c4 to allow detecting valid settings in init files and since a6ec45e28acb787b768c4017b4137c2bb6adc86d also test case sections are considered invalid when using it.

**Comment by pekkaklarck** [comment]
Do you @fabioz have comments about these changes related to the LSP project? What about @yanne?

**Comment by fabioz** [comment]
@pekkaklarck I think those are nice changes (i.e.: adding more info to what's generated is definitely nice)...

The only one I don't think is really needed at this point is 4. (in general, we'll be working with a dirty buffer, so, we can't really rely on the name as the API will usually just receive the contents... we could change `get_model` to receive the contents with a name when it's available, but I'm not sure it's worth it). 

I think knowledge like that may fit better in a code analysis step which will be done later, after the AST is already generated.

**Comment by pekkaklarck** [comment]
Good point about `__init__.robot` files. `get_tokens/model` can be called with data only and in that case it doesn't know anything about the file name. The feature that init files cannot contain tests is also somewhat artificial and we could easily change that in the future. Let's forget about that for now.

**Comment by pekkaklarck** [comment]
The commits above implement points 1. (ba896707519c2bc73cba914435d8fe79a5ffe847) and 2. (c75e480ebecaa7185f2c082258fd8a3b668887bc) from the original description. The description left some design decisions open. This is how I implemented them:

- Settings that logically have name and value (Metadata, Suite Setup, Library, ...) are now tokenized so that the name has `NAME` type and values have `ARGUMENT`.
- The above required changing test case and keyword name types because they used `NAME` earlier. Now they have `TESTCASE_NAME` and `KEYWORD_NAME`. I would assume they having different types is a benefit in itself.
- The "WITH NAME" syntax is tokenized so that the "WITH NAME" token itself gets type `WITH_NAME` and the value after it gets type `NAME`. Didn't feel that assigning a separate type for that token would bring much benefits.

**Comment by pekkaklarck** [comment]
Ping @datakurre. You probably should know about these changes as well.

**Comment by pekkaklarck** [comment]
Realized there are some more syntax that could be validated already by the lexer. I continue with numbering used in the original description.

### 5. Variable name and value validation

Currently the lexer doesn't report any errors from this data:

```robotframework
*** Variables ***
INVALID       Value       # Invalid variable name
&{DICT}       invalid     # Values should be in format `key=value` or `&{dict}`
```

The lexer could validate variable names as well as dictionary variable values. Other variable types cannot really have invalid values.


### 6. FOR loop header types

At the moment this FOR loop header
```
FOR    ${x}    IN    foo    bar
```
is tokenized to these tokens

```
FOR (FOR)
ARGUMENT (${x])
FOR_SEPARATOR (IN)
ARGUMENT (foo)
ARGUMENT (bar)
```

It would be a lot better to tokenize variables so that they have the `VARIABLE` type. This would be a simple task and doing it before RF 3.2 would avoid changing token types in future versions.

### 7. FOR loop validation

The lexer doesn't really validate FOR loops at all. Things it could do:

- Validate that FOR loop variables use correct syntax.
- Validate that FOR loop header has variables, correct separator, and values.
- Validate that FOR loop has body and END.

This is probably quite a big task. May not be worth the effort before RF 3.2.

**Comment by pekkaklarck** [comment]
Tokenizing FOR loop header was enhanced by 84c43027aaf370fb4bf43bee08de5a23d5d8a21f.

**Comment by pekkaklarck** [comment]
Variable related validation was done by 0b96c35ed7e8c61d972f6bf5d0170bfa0b1aba39 and 673535a79b28ff1af94d201c8a471c42df674e55.

**Comment by pekkaklarck** [comment]
Test case section is now considered invalid in resource files (when using `get_resource_tokens/model` entry points) and in suite init files (when using newish `get_init_tokens/model`). Needed to add a new `FATAL_ERROR` token type to make it easy to implement this without changing old functionality. See a6ec45e28acb787b768c4017b4137c2bb6adc86d for details.

**Comment by pekkaklarck** [comment]
The only open issue related to this (unless we encounter something new) is validating for loops. That's too big for beta 2 that I want to get out before my holiday next week. I probably look at that after holidays but it may also be much work for RF 3.2 in general.

**Comment by pekkaklarck** [comment]
Decided not to enhance FOR loop validation before RF 3.2. This can still be changed if @fabioz or someone else considers it important. Otherwise we can return to it when adding IF/ELSE support and when we probably want to add some validation for it.

**Comment by pekkaklarck** [comment]
FOR loop validation was added and error detection enhanced also otherwise in RF 4.0.
