### ISSUE TITLE
Cannot run scripts in IE11: SessionNotCreatedException: Message: Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by cmarcqa1** [robotframework/robotframework#3459]
Hi, I would like to ask if you guys encountered the error in the title? if yes, are there any resolutions available (including steps to do)? thank you.
Robot Framework 3.1.2 (Python 2.7.17 on win32)
robotframework-selenium2library==3.0.0

**Comment by pekkaklarck** [comment]
Not a valid issue.
