### ISSUE TITLE
plural_or_not method return "s" for value "-1"

### ISSUE THREAD

**Issue by IlfirinPL** [robotframework/robotframework#3460]
robot/utils/misc.py 
method plural_or_not  return "s" for value -1

**Comment by pekkaklarck** [comment]
Could you clarify what's the problem?

**Comment by IlfirinPL** [comment]
When ask method plural_or_not for values  (0) or (-1) return "s" , 
in example message size is
-1 element plural_or_not(-1) -> "-1 elements", and i think it should be 
"-1 element"

**Comment by pekkaklarck** [comment]
I'm not a native English speaker, but AFAIK you need to use the plural form with zero items.

**Comment by IlfirinPL** [comment]
OK, maybe I jump the gun, its more complex then i was previously expected
there is zero element
http://mathworld.wolfram.com/ZeroElement.html
also 
https://www.grammar-monster.com/lessons/singular_plural_number.htm

I think it should stay as is.

**Comment by pekkaklarck** [comment]
Yeah, the behavior with zero shouldn't change. The situation with -1 is a lot less clear, but apparently it is more often considered singular. I'm fine that being changed.

**Comment by IlfirinPL** [comment]
update in code #3461

**Comment by pekkaklarck** [comment]
I commented the PR. Can you please also update the issue title?
