### ISSUE TITLE
Add support for svg image link

### ISSUE THREAD

**Issue by osrjv** [robotframework/robotframework#3464]
There's a feature in documentation fields where it converts image links to img tags, e.g. [mypic.jpg|Title] -> &lt;img src="mypic.jpg" title="Title"/&gt;. It'd be nice if it supported svg files.

Related to PR: #3462

**Comment by pekkaklarck** [comment]
Sounds good to me!

**Comment by pekkaklarck** [comment]
This was implemented by #3462. Thanks @osrjv!
