### ISSUE TITLE
robotframework integration with python

### ISSUE THREAD

**Issue by NKGUPTA26** [robotframework/robotframework#3468]
raise RobotNotRunningError('Cannot access execution context')
robot.libraries.BuiltIn.RobotNotRunningError: Cannot access execution context

This errror arises when i try to run the python script to upload multiple .

**Comment by laurentbristiel** [comment]
Hello. The Issue section of GitHub is to raise bug/requests, not to ask for help on an issue. Please use one of the [support channel described in the README](https://github.com/robotframework/robotframework#support-and-contact)

**Comment by pekkaklarck** [comment]
That error occurs when using something that requires RF to be running when it isn't running. You either need to use thar thing via RF or somehow get the code changed.
