### ISSUE TITLE
Mouse Over does not work on IE11 (windows10)

### ISSUE THREAD

**Issue by rave-apps** [robotframework/robotframework#3470]
I have many test cases which includes Mouse Over and are failing repeatedly in IE. I am using Selenium2Library. This works fine on Firefox and Chrome. 
I can see that similar issue is been raised for SeleniumLibrary but according to closing comment, the issue should have been disappeared but it's still there.

**Comment by pekkaklarck** [comment]
This is wrong tracker for SeleniumLibrary issues.
