### ISSUE TITLE
letter 'U' appended in front of the key and value

### ISSUE THREAD

**Issue by raghunar-git** [robotframework/robotframework#3474]
Hello All,

I have this simple code as below:

*** Settings ***
Library  Collections
Library  RequestsLibrary
Library  JSONLibrary

*** variables ***
${base_url} =  	https://reqres.in

*** Test Cases ***
First_Post_Requets
	Create Session 	 AddData	  ${base_url}  
	${data}=        Create Dictionary        name=abc      job=xyz   
	${header}=    Create Dictionary       Content-Type=application/json
        

the result when the data and header are logged is as below:
${data} = {u'name': u'abc', u'job': u'xyz'}
${header} = {u'Content-Type': u'application/json'}

Why is the letter 'U' appended in front of the key and value?

**Comment by laurentbristiel** [comment]
See https://stackoverflow.com/questions/2081640/what-exactly-do-u-and-r-string-flags-do-and-what-are-raw-string-literals
