### ISSUE TITLE
Post Request responds with error message as Argument Types are Int and Unicode

### ISSUE THREAD

**Issue by raghunar-git** [robotframework/robotframework#3482]
Hi All,

I have this simple code below:

*** Settings ***
Library   Collections
Library   RequestsLibrary
Library   JSONLibrary

*** variables ***
${base_url} =  	https://reqres.in

*** Test Cases ***
First_Post_Requets
	Create Session 	 AddData	  ${base_url}  
	${data}=      Create Dictionary    name=abc    job=xyz   
	${header}=    Create Dictionary    Content-Type=application/json  
	${response}=   Post Request   AddData   /api/users   data=${data}   headers=${header}
	Should Be Equal As Strings  ${response.status_code}  201

But when i execute i get the below warning and the request fails:
 ${data} = {u'name': u'abc', u'job': u'xyz'}
 ${header} = {u'Content-Type': u'application/json'}
 Deprication Warning  Use Post Request in the future
 ${response} = <Response [400]>
 Argument types are:
<type 'int'>
<type 'unicode'>

I had earlier asked for clarification of the letter 'U' in front of the key and value pair in #3474 and from the response i understand that it is because of unicode strings.

1. If the data and header are in the form of unicode strings, then why do i get the error of the argument types as int and unicode?
Should the datatype of the data and header be changed before the Post Request, if so how?(Though I have never come across this kind of thing being done for variables created using 'Create Dictionary')
How can i overcome this error and do a successfull post request?

2. Their is also a deprication warning 'Use Post Request in the future'. 
How to get over this? Or is my request failing with the arguments error because of this warning?

Sorry for the long message. Kindly help.

Thank you

**Comment by pekkaklarck** [comment]
This is pretty confusing issue and I don't understand it fully. Some comments about it:

- Log message about argument types isn't an error. It's there for debugging purposes.
- That deprecation warning comes from some external library. This issue tracker is only for Robot Framework itse.f
- In the future please format the messages better. See [these instructions](https://guides.github.com/features/mastering-markdown/) for details.
- For questions it's better to use mailing lists, Slack, and other such support forums. This tracker is only for bug reports and concrete enhancement requests.
