### ISSUE TITLE
Allow using `@{list}[index]` as a list and `&{dict}[key]` as a dict

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#3487]
Earlier it was possible to access items from lists and dicts using syntax `@{list}[index]` and `&{dict}[key]`, respectively. In RF 3.1 this was unified and `${var}[item]` introduced to access items from both lists or dicts, including nested access like `${var}[item1][item2]` (#2601). RF 3.2 deprecated the old `@{list}[index]` and `&{dict}[key]` syntax (#2974) in favor of the new generic syntax.

In the future the old `@{var}[item]` and `&{var}[item]` syntax is thus not anymore valid and we can give it a new meaning. The plan is to make it work like this:

- Both `@{var}[item]` and `&{var}[item]` will first make a normal variable item lookup, exactly like when using `${var}[item]`. Nested access like `@{var}[item1][item2]` will be allowed as well.
- When using the `@{var}[item]` syntax, the found item must be a list or list-like. It is expanded exactly like `@{var}` is expanded normally.
- When using the `&{var}[item]` syntax, the found item must be a mapping. It is expanded exactly like `&{var}` is expanded normally.

In practice the above means that if we have, for example, a variable `${var}` with value `{'items': ['a', 'b', 'c']}`, we could use it like this:

```
FOR    ${item}    IN    @{var}[items]
    Log    ${item}
END
```

At the moment item access needs to be done separately:

```
@{items} =    Set Variable    ${var}[items]
FOR    ${item}    IN    @{items}
    Log    ${item}
END
```

In addition to being convenient in some use cases, this enhancement makes the variable usage more consistent.

**Comment by pekkaklarck** [comment]
This is backwards incompatible change because the meaning of `@{var}[item]` and `&{var}[item]` syntax will change. The old usage has already been deprecated so doing the change in RF 4.0 ought to be fine. If we think that's too early, then we should at least remove the support for the old syntax altogether.

**Comment by mkorpela** [comment]
Linked pull request:
https://github.com/robotframework/robotframework/pull/3693

**Comment by pekkaklarck** [comment]
Part of this enhancement is making it possible to use the slice notation originally added in RF 3.1 (#2973) also like `@{list}[1:]`.

**Comment by mkorpela** [comment]
I believe this is done now after cd78e90110358766a0866a523bc9988fe1d87f5e
