### ISSUE TITLE
Allow to import variables with different namespace

### ISSUE THREAD

**Issue by bhirsz** [robotframework/robotframework#3488]
Recently I've discovered neat RF feature: import variables from yaml file. Example:

```
*** Settings ****
Variables  my_vars.yaml
```

For my_vars.yaml file:
```
some_var: 1    
some_dict_var:    
    key: value    
```

Variables import that way will be directly accessible in Robot. I would like to be able to assign some 'namespace' to them though - same as I can do it with libraries. Of course I can do this:

```
my_namespace:    
    some_var: 1    
    some_dict_var:    
         key: value    
```

But it's not as flexible - I can't assign two 'namespaces' to one file. 
Proposal:

```
**** Settings ***    
Variables  my_vars.yaml  AS  some_mapping    
```
This will get me variable ${some_mapping} (dict like) that will contain all variables inside file. 

By looking at source code here https://github.com/robotframework/robotframework/blob/master/src/robot/variables/filesetter.py#L63 I see that it's enough to change following lines to somehow like (that's only some quick dirty code, it needs polishing etc):

```
    def import_variables(self, path, args=None):    
        variables = self._import(path)    
        yaml_variables = [('${%s}' % name, self._dot_dict(value))    
                for name, value in variables]    
        if not args:    
            return yaml_variables    
        if (len(args) != 2) or (args[0].lower() != 'as'):    
             raise DataError('YAML variable files do not accept arguments.')    
        return  ('${%s}'  % args[1], yaml_variables)    
```

**Comment by pekkaklarck** [comment]
I understand the problem but don't think fixing it only with YAML files is a good idea. We already have #1999 that proposes an alternative solution. Would that work for you?

**Comment by bhirsz** [comment]
Apologies for delayed response. Proposed feature is not exactly what I wanted. But after I analysed this problem I can just go with I used before:
```
my_namespace:    
    some_var: 1    
    some_dict_var:    
         key: value   
```
(in yaml file) instead using proposed AS my_namespace.
