### ISSUE TITLE
RF unable to generate log and report from 1.5 G output.xml

### ISSUE THREAD

**Issue by vkosuri** [robotframework/robotframework#3497]
Hello,

My current RF version is 3.1.2

> I am unable to share ``output.xml``a lot of prosperity tests are executed.

**Question:**
I have 1.5G output.xml files but I unable to generate log.html and report.html both ``rebot `` and ``robot``, We can't re-execute all tests again because it will take another 48hours. 

Please any alternative approaches?

After executing 656 tests it got failed. 

```Bash
----------------------------------------------------------------------------
Tests 99Test                                                     | FAIL |
300 critical tests, 147 passed, 153 failed
300 tests total, 147 passed, 153 failed
==============================================================================
Tests XYZ                                                          | FAIL |
656 critical tests, 347 passed, 309 failed
656 tests total, 347 passed, 309 failed
==============================================================================
Output:  /home/jenkins/product-tests/REPORT_2020-03-07/output.xml

Killed
(venv) jenkins@virtual-machine:~/product/system-tests$
```
Size output.xml
``` Bash
-rw-rw-r-- 1 jenkins jenkins 1.4G Mar  8 17:52 output.xml
```
After it failed to generate log.html and report.html i tried to reduce output.xml using ``rebot`` but it killed again.

``` Bash
(venv) jenkins@adtran-virtual-machine:~/product/system-tests/REPORT_2020-03-07$ rebot --removekeywords passed  --log log.html --report report.html --output removed.xml output.xml

Killed
```

**Comment by tysonite** [comment]
Your Linux box probably runs out of memory. Try to add more swap space, or increase RAM.

**Comment by vkosuri** [comment]
After 4GB to 16GB it works fine. Thank you very much @tysonite
