### ISSUE TITLE
Does it have support for mobile/tablet?

### ISSUE THREAD

**Issue by gauravgandhi15** [robotframework/robotframework#3502]

**Comment by laurentbristiel** [comment]
Hello. Your question is not very clear. If you want to know if Robot Framework is able to test a mobile/tablet application, yes it is possible with libraries like https://github.com/serhatbolsu/robotframework-appiumlibrary. Note that this "issue@github" section is for bug or enhancement requests, if you have question, please use mailing list or slack.
