### ISSUE TITLE
Robot.run in for loop - issue

### ISSUE THREAD

**Issue by jura84** [robotframework/robotframework#3503]
We ran robot.run in for loop in python code.
We provided all kind of arguments to run function e.g. output dir which changed in every loop.

When second execution happened the first defined output dir was still there.
We found out that when we fetched outpudir with following command it returned value defined in previous run.

If I remember correctly when we had three runs in loop then last one still had first one output dir value.

```python
output_dir = BuiltIn().get_variable_value('$OUTPUT_DIR')
```

**More details:**
- During execution we import python libraries for plotting like in this example.
- Some of python libraries have class variables like this outputdir explained below.
  - This class variable is not cleared after first execution
  - In this class some functions are static

When we use this class/module, we do not instantiate this instantiation is not needed when all methods are static and variables are in class (outside of init). We just import this python module and access this variable.

However if we move this variable to **init** method and we instantiate this class when use it, then this output_dir works OK, even tho as you see the code outside of init is same like it is in **init**.

![image](https://user-images.githubusercontent.com/34338587/76628781-f40f1780-6545-11ea-9794-5926b243d382.png)

**The class which uses this static one:**
![image](https://user-images.githubusercontent.com/34338587/76628858-14d76d00-6546-11ea-837e-4dd033f02619.png)

![image](https://user-images.githubusercontent.com/34338587/76628884-21f45c00-6546-11ea-9a6e-5c9fa3759820.png)

**Comment by pekkaklarck** [comment]
It's certainly possible some global state is left over. It would help debugging this if you could create a bit more complete example. Would also be good to know are there problems with other options other than the output dir.

**Comment by jura84** [comment]
Description updated. :)

**Comment by pekkaklarck** [comment]
This seems to work as expected. Class variables are set only once when the class is created and within the same _Python_ execution classes aren't recreated.

**Comment by jura84** [comment]
To understand you comment.. no bug?

But when calling robot.run twice for example, should all classes which are created in first run still remain when exeuting robot.run second time? I would say no, those are two different executions. Now in this case the first exeution creates these classes and uses them and second execution have same classes even though execution is totally different from testing point of view. 

I assumed that robot.run executions are happenning in different processes and are not related to each other. :)

**Comment by jura84** [comment]
One confirmation from our end:
If we execute robot in our loop using **os.system** then this works ok and older classes are not there after first run.

**Comment by pekkaklarck** [comment]
No, we cannot realistically force recreating all classes. That would be fighting against how Python works. I'm not sure would it even be possible but if it was, it would slow down the overall execution speed.

In general with Python (and all other languages I know) you should use instance attributes with values you want to be different when instances are created and class attributes only if you want them to be same all the time. If you want total independency, running each execution round as a separate process is a good idea.

Based on this discussion there's no bug in Robot or in Python. I initially thought the value of `${OUTPUT_DIR}` would be same on different rounds even if it shouldn't, but the problem clearly is that it's only fetched once.

**Comment by jura84** [comment]
Hmm.. I still disagree or we are talking about different thing here.

**Explanation in other words:**

Now when we run robot.run in loop and at first it e.g. executes test1.robot.

This test1.robot file says **Library pythonlibraryA** where this pythonlibraryA uses other python library let's call that like libraryB which contains class variables and staticmethods.  Also this libraryB reads output_dir and saves it class variable.

Now when we run robot.run second time which e.g. executes test2.robot.
This test2.robot file says same **Library pythonlibraryA** where this same pythonlibraryA uses this same libraryB, but output_dir which are read in this class is having same output_dir value what's been set in first run.

I still assume these own python libraries used in tests to be re-instantiated and re-set again in next runs when using robot.run. I would not concider to let these instances be there after first execution because we are talking about two different test runs.

That's why os.system works for us because all instances are wiped out after one process ends. :)

If you still think this how it's behaves is OK then that's fine.
Maybe like you said, everything else is OK but output_dir is not set correctly even tho we set that as an arg for robot.run. :)

**Comment by jura84** [comment]
" Class variables are set only once when the class is created and within the same Python execution classes aren't recreated."

So you mean that when we run this from python then all classes creared by robot.run remains as long as we are in this python library? Then it would make sense.. on other hand then setting output_dir is the issue.. we reset that in all robor.run executions..

**Comment by pekkaklarck** [comment]
This is how classes work in Python. You have two easy ways to avoid the problem.

**Comment by jura84** [comment]
Yes, somehow I missed this one and I was only concentrating into those test executions and keeping those as a separate. Thanks for help! :)
