### ISSUE TITLE
keyword decorator with two parameters without any  separator will be recognized as one parameter

### ISSUE THREAD

**Issue by kanchi240** [robotframework/robotframework#3506]
Library keyword:
```
@keyword(name='get${risk}${config}')
    def get_risk_config(self, risk, config):
        return self._get_risk_config(risk, config)
```

Then I pass two values to this keyword, it will be recognized as only one value passed to the first argument `${risk}`. And it is OK if two arguments has some separator, such as `@keyword(name='get ${risk}'s ${config} values')`

**Comment by pekkaklarck** [comment]
How do you use this kw and how do you expect Robot to be able to separate these arguments? Have you read about using a custom pattern with embedded arguments in the User Guide?

**Comment by kanchi240** [comment]
@pekkaklarck Could separate multiple arguments by the `$` ?

**Comment by pekkaklarck** [comment]
Could you please clarify? And also answer my earlier questions.

**Comment by MaciejWiczk** [comment]
@kanchi240 how about parameters escaping like:
`@keyword(name='get${risk:\w+}${config\w+}')`

**Comment by kanchi240** [comment]
Thank you, not an issue, can be found at user guide: http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#embedded-arguments-matching-too-much
