### ISSUE TITLE
How to set SeleniumLibrary as a remote library?

### ISSUE THREAD

**Issue by yuhang222** [robotframework/robotframework#3508]
# For issues
I want to set SeleniumLibrary as a remote server,so I add scripts "
import sys
from robotremoteserver import RobotRemoteServer
if __name__ == '__main__':     
    RobotRemoteServer(SeleniumLibrary(),*sys.argv[1:])"
in '/SeleniumLibrary/__init__.py'.
After I run the __init__.py,the error message "SeleniumLibrary.errors.NoOpenBrowser: No browser is open." arises.

## Steps to reproduce the issue
1.download 'robotremoteserver.py' to 'site-package/SeleniumLibrary'.
2.add scripts "
import sys
from robotremoteserver import RobotRemoteServer
if __name__ == '__main__':     
    RobotRemoteServer(SeleniumLibrary(),*sys.argv[1:])"
in 'SeleniumLibrary/__init__.py'.

## Error messages and additional information

C:\Users\dell\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\Seleni
umLibrary>python __init__.py
Traceback (most recent call last):
  File "__init__.py", line 642, in <module>
    RobotRemoteServer(SeleniumLibrary(),*sys.argv[1:])
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37-32\Lib\site-package
s\SeleniumLibrary\robotremoteserver.py", line 73, in __init__
    self._library = RemoteLibraryFactory(library)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37-32\Lib\site-package
s\SeleniumLibrary\robotremoteserver.py", line 259, in RemoteLibraryFactory
    return DynamicRemoteLibrary(library, get_keyword_names, run_keyword)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37-32\Lib\site-package
s\SeleniumLibrary\robotremoteserver.py", line 362, in __init__
    HybridRemoteLibrary.__init__(self, library, get_keyword_names)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37-32\Lib\site-package
s\SeleniumLibrary\robotremoteserver.py", line 355, in __init__
    StaticRemoteLibrary.__init__(self, library)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37-32\Lib\site-package
s\SeleniumLibrary\robotremoteserver.py", line 280, in __init__
    self._names, self._robot_name_index = self._get_keyword_names(library)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37-32\Lib\site-package
s\SeleniumLibrary\robotremoteserver.py", line 285, in _get_keyword_names
    for name, kw in inspect.getmembers(library):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python37-32\lib\inspect.py",
 line 341, in getmembers
    value = getattr(object, key)
  File "__init__.py", line 549, in driver
    raise NoOpenBrowser('No browser is open.')
SeleniumLibrary.errors.NoOpenBrowser: No browser is open.

I have downloaded geckodriver to PATH.When I use SeleniumLibrary as local library,it can open firefox normally.
## Expected behavior and actual behavior

When I follow those steps, 
I was expecting "Robot Framework remote server at 127.0.0.1:8270 started."

## Environment

Operating System: Name and version (Win7 32)
The libraries downloaded via 'pip install ' are up to data.
Thanks for everyone.

**Comment by pekkaklarck** [comment]
This is a wrong issue tracker for SeleniumLibrary or RobotRemoteServer issues. We also use issue trackers for bug reports and enhancement requests, not for general questions.
