### ISSUE TITLE
Unable to run __init__.robot file using run command

### ISSUE THREAD

**Issue by deepaleekhare31** [robotframework/robotframework#3509]
I have an __init__.robot file inside a testcase folder: it contains Test Setup, which contains steps to fetch a test case name and use in further steps.
I have multiple test cases in the same folder. and I want the init file to execute before every testcase.

While executing from eclipse i.e. right click -> Run As robot Test --- It is working fine.

But when i execute the same using python, using run command, as below, it does not consider the init file while execution:
run(*str_tc_list, outputdir=timestamp_path, stdout=stdout)

***str_tc_list:** The testcase names are in an XML file, and i'm fetching the same one by one and appending it in a list.

Could you please help?

**Comment by deepaleekhare31** [comment]
@pekkaklarck  Could you please help ?

**Comment by pekkaklarck** [comment]
I don't fully understand this question but it could be that you need to run the top level test suite and them use `--suite` option. Anyway, this issue tracker is for bug reports and enhancement requests. Please use mailing lists, Slack or other such support forums for further questions.
