### ISSUE TITLE
Dynamic API: Support returning real default values from `get_keyword_arguments`

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#3514]
Currently `get_keyword_arguments` in the dynamic library API returns the argument specification as a list of strings like `['mandatory', 'optional=default', '**kws']`. This works fine otherwise, but because all items in the spec are strings, something like `['x=1', 'y=None', 'z=True']` is interpreted so that `1`, `None` and `True` are all strings. This isn't typically a big problem because default values are mainly used for validation argument counts and for documentation purposes, but there are two cases where Robot Framework not getting the real default values causes issues:

1. Type information got from default values is used for automatic argument conversion starting from RF 3.1 (#2932). This is especially useful with common default values `None`, `True` and `False`, and obviously doesn't currently work at all with dynamic libraries. This is a problem, for example, for the SeleniumLibrary.

2. If the `run_keyword` method doesn't accept `kwargs` and the named argument syntax is used so that optional arguments are skipped, the given default values are passed to the executed keyword as part of `args`. This is a pretty rare situation (it was more common before #2930) and probably wouldn't alone be worth changes.

**Comment by pekkaklarck** [comment]
I propose this to be fixed so that we allow returning argument that accept a default value from `get_keyword_arguments` as a tuple containing the argument name and the default value like `[('x', 1), ('y', None), ('z', True)]`. For consistency reasons we could also allow passing arguments that don't have a default value as a single item tuples like `[('mandatory',), ('optional', 'default')]`. For backwards compatibility reasons we should support the old syntax as earlier and I don't think it makes sense to deprecate it even in the future.

**Comment by aaltat** [comment]
This looks nice and is not difficult to do in PythonLibCore side. Added issue so that it gets done in next PythonLibCore release.

**Comment by pekkaklarck** [comment]
This was implemented by 4cb35cbb4880c1190d5829630de31f0702b76b70 which accidentally referred to #3541, not this #3514 (i.e. this issue) as it should have.

**Comment by pekkaklarck** [comment]
While reviewing a [somewhat related pull request for PythonLibCore](https://github.com/robotframework/PythonLibCore/pull/22) I realized this enhancement doesn't yet work as it should. Currently if `get_keyword_types` returns `None`, we still do argument conversion based on default values. With static libraries such explicit type information being `None` means not doing automatic conversion at all. Need to change the dynamic API to work like that as well.
