### ISSUE TITLE
Dynamic API: Add new `get_keyword_source` method

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#3516]
This is needed to make it possible to add source information to Libdoc spec files (#3507) as well as to Libdoc's model objects (#3448). External tools like editors can then use this information to implement "go to definition" functionality.

This method needs to be able to return both the path to the source file and the line number, and we need to decide which format to use. Good alternatives include a tuple `(source, lineno)` as well as a string `source:lineno`. Not sure why, but I like the latter approach better.

**Comment by pekkaklarck** [comment]
Ping @aaltat. This needs to be added to PythonLibCore as well.

**Comment by aaltat** [comment]
I would prefer the (named) tuple better, but I don't feel strongly about the matter. The correct answer greatly depends on the downstream use case. If lsp server prefers `/path/to/file.py:xx` format or tuple, I am happy with both solutions. 

But another thing pops in to my mind, performance. Instead of querying single keyword at the time, would it be possible to do bulk query. Example query source for hundred keyword with single API call? Although all this is querying within a single Python process, which is fast, would there be performance gains if bulk query would be done instead? I recall seeing similar request for the remote library API.

**Comment by aaltat** [comment]
Only thing to decide is it full path or relative to something?

**Comment by pekkaklarck** [comment]
1. It cannot be a namedtuple because we need to support Java. Basically either a string or a tuple/list. Info doesn't go directly to Libdoc spec files so whatever format is used there doesn't matter.

2. It would be very inconsistent to get all source info in a single method call when other info is asked one-by-one. I seriously doubt it would affect performance either, the lib needs to get info for all kws anyway so we'd basically save a method call per kw. Things are totally different with the remote API as there each call is a HTTP request. Probably the best solution to that problem would be introducing separate `get_keyword_info` to return all kw info or possibly even `get_library_info` to get all possible info in one call. That's a topic for a totally different discussion.

3. Related to the above, I don't think we need to add `get_keyword_source` to the remote API in RF 3.2. It would be quite a bit of more work and remote source paths wouldn't always be that useful. Let's just handle the common cases first.

4. Absolutely vs. relative path is a very good point. I think this method should return an absolute path and Libdoc can then make it relative if needed. Otherwise we needed to know to what directory the paths are relative to.

**Comment by aaltat** [comment]
1) I always forget the Java, let's take tuple then.
2) Agreed, consistency is better and problems in the remote library API should be handed separately
3) Agreed.
4) Full path it is then.

**Comment by pekkaklarck** [comment]
This has been mostly implemented (incl. tests and docs) by 1ddf21a0269e9b276f551e341396a93f719932b7. Decided to make it so that the source info is returned as a string (or `None` if there's no source info). Valid format are `path` alone, `path:lineno` and `:lineno`.

The only missing thing I can think of (doesn't mean there couldn't be others), is making a decision should we ask for source information for `__init__` like we do with keyword arguments and docs. We get the source info of the library itself like we get with other libraries, but it might be useful to get the path and especially the line number of the `__init__`  as well. We could also think about getting the library source info dynamically to allow overriding the value we get via introspection directly. Both of these are something that can be added later if needed as well but that will cause backwards compatibility concerns.

**Comment by pekkaklarck** [comment]
I tested how library `__init__` source info is seen with normal and dynamic libraries. It turned out we can see it fine in both cases, except that there was a bug in handling old-style classes. That was fixed and test coverage increased in dae5f8144328116ae8faaadd534f367a16e39862.

Because we can see the source info from `__init__` also with dynamic libraries directly, I don't think it makes sense to add support to query that via the new `get_keyword_source` method. I feel the same with querying the source info of the library dynamically. If there are concrete use cases later, this support can be added. That would most likely mean Robot calling `get_keyword_source` with string `'__init__'` and then either something like `'__intro__'` (that's what we use with `get_keyword_documentation`) or possibly more explicit `'__library__'`. Tools who want to prepare for this possible change can simply return `None` if `get_keyword_source` is called with a name that the library doesn't have and that starts and ends with `__`.

**Comment by aaltat** [comment]
I have question, if my keywords method looks like this: 
```
@keyword
def my_keyword(self, arg):
    return arg
```
Where the line number should point to? In the line where the method method definition (`def my_keyword(self, arg):`), in line containing the `keyword` decorator (there might be multiple decorators) or somewhere else, where? 

The Python [getsourcefile](https://docs.python.org/3/library/inspect.html#inspect.getsourcefile) returns the line where first decorator is. But I am more thinking that it should return the line which contains the method definition, but I do not feel strongly on the matter.

**Comment by pekkaklarck** [comment]
I'd be fine with whatever `getsourcelines` returns but returning the line with the `def` is fine as well.

**Comment by aaltat** [comment]
I did go with solution that returns the `def`.

**Comment by pekkaklarck** [comment]
OK. Should we change Robot's own logic to work the same way? At the moment it returns just whatever `getsourcelines` returns, but it could also find the `def` line.

**Comment by pekkaklarck** [comment]
Realized the current implementation doesn't handle decorators correctly. This isn't the problem that we return the line where the first decorator is but rather that if the decorator returns a different function (`@keyword` returns the original), we get that function's source lines. Need to call `inspect.unwrap` first when using Python 3. With Python 2 I guess we can just live with this.

**Comment by pekkaklarck** [comment]
Actually, this issue wasn't affected by the problem with not handing decorators correctly. The issue about adding source info to Libdoc (#3507) is.

**Comment by aaltat** [comment]
Hmmm, so I should look into this problem in the PythonLibCore side.

**Comment by pekkaklarck** [comment]
Yeah, it would be good if PythonLibCore handled this as well. There are currently two problems:

1. If a function is decorated with a decorator replacing the original function, PythonLibCore returns source info of the wrapper. This can be fixed on Python 3 with `inspect.unwrap`, assuming that the decorator uses `functools.wraps` (as it should). I wouldn't care about that with Python 2. This issue is both with the source and the line number.

2. If a keyword is created without `def `, line number will be incorrect. It could actually be that line number becomes string `None` which then causes an exception when calling `get_keyword_source`.

Both of the above issues were fixed on Robot side in 5333be9997317abeaedb31dda95b44589a667629.
