### ISSUE TITLE
FOR LOOP on EMPTY LIST stopped working in RIDE 1.7.4.1 with Robotframework 3.0.4

### ISSUE THREAD

**Issue by IAmWebSA** [robotframework/robotframework#3519]
I had in old RIDE 1.5.2.1 with Robotframework 3.0.4 the following syntax, to not break the workflow if I  none defined value.

`@{emptyList}=	Create List
${temp}	Get Variable Value	@{users}	@{emptyList}

${length}	Get Length	${temp}	
Log	Got following users: @{temp}		
Log	Length of user List is ${length}		
: FOR	${user}	IN	@{temp}
	Log	${user.name}	`

**but now with RIDE 1.7.4.1 I get errors that the variable "${user}" is undefined if the list is empty**

Are For Loops not supported anymore on empty lists?
How to change this to be compatible with old RIDE 1.5.2.1 and RIDE 1.7.4.1?

**Comment by pekkaklarck** [comment]
1. Can you reproduce this without RIDE?

2. What exactly is the error and where do you get it?

3. Could you please create a simple but concrete example others can use to reproduce the problem? Please [format the example](https://guides.github.com/features/mastering-markdown/) to make it easier to read.

**Comment by IAmWebSA** [comment]
This a simple case for trying to loop on empty list:

1. 
If I run it via cmd shell it is the same result.

2.
20200330 07:09:11.616 :  FAIL : 
Resolving variable '${test}' failed: Variable '${test}' not found. 

3. 

RIDE 1.5.2.1:
```
Delete test
    [Documentation]    Delete test
    @{emptyList}=    Create List
    : FOR    ${test}    IN    @{emptyList}
    \    Log   ${test}
```

RIDE 1.7 has removed ":" and "\"
```
Delete test
    [Documentation]    Delete test
    @{emptyList}=    Create List
    FOR    ${test}    IN    @{emptyList}
        Log   ${test}
```


So if I manually add again the ":" and "\"  via an external editor it works via RIDE 1.7 and cmd line.
But if I save it again via RIDE 1.7 it removes the ":" and "\" again and stops working.

**Comment by pekkaklarck** [comment]
Apparently RIDE tries to convert the FOR loop from the old syntax with `:FOR` as the marker and `\` used for indentation to new syntax with just `FOR` as the marker and without `\`. The new syntax requires a closing `END`, though, and it seems RIDE doesn't add it. If that's the case, then this should be reported to RIDE's issue tracker.

For details about the FOR loop syntax changes see, for example, RF 3.1 release notes:
https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-3.1.rst#for-loop-enhancements
