### ISSUE TITLE
Robot Framework HTML log generation hangs after testing is complete.

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#352]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=352) by bugspot on 23 Jun 2009_

Running the attached script and looping 5000 times on various systems hangs
the log generation process. The XML file looks intact.
The attached script is intended as a stress test on a base host system.
System 1 and 3 hang in the command window without errors. System 2, which
has more memory and CPU power generates error messages.

In all cases observed, the memory and CPU are stable while running the
script. System 1 &amp; 3 use about 38 - 40&#37; CPU and 8648kB memory, System 2
reports 32&#37; CPU use and similar memory use. Log compilation then increases
the use of each.

/******************************************************************/
Error Messages from System 2 (Windows XP)
Performance Results on Gold Build computer:

W:\SQA_Library\tools\Robot_Framework\Verification\Procedure\PQtest&gt;pybot
# --variable RUNS:5000 RobotFramework_Performance_V2-1.html
# Robotframework Performance V2-1
## Logging Resource Check :: Force Variable Checks                       | PASS |

Robotframework Performance V2-1                                       | PASS |
1 critical test, 1 passed, 0 failed
#1 test total, 1 passed, 0 failed

Output: 
w:\sqa_library\tools\robot_framework\verification\procedure\pqtest\outp
ut.xml
Traceback (most recent call last):
  File "c:\python26\lib\site-packages\robot\runner.py", line 311, in &lt;module&gt;
    robot.run_from_cli(sys.argv[1:], **doc**)
  File "C:\Python26\lib\site-packages\robot__init__.py", line 37, in
run_from_cli_run_or_rebot_from_cli(run, args, usage, pythonpath='pythonpath')
  File "C:\Python26\lib\site-packages\robot__init__.py", line 61, in
_run_or_rebot_from_cli   error, details = utils.get_error_details()
  File "c:\python26\lib\site-packages\robot\utils\error.py", line 71, in
get_error_details    details = _get_python_details(exc_value, exc_traceback)
  File "c:\python26\lib\site-packages\robot\utils\error.py", line 144, in
_get_python_details   tb = traceback.extract_tb(exc_tb)
  File "C:\Python26\lib\traceback.py", line 101, in extract_tb    line =
linecache.getline(filename, lineno, f.f_globals)
  File "C:\Python26\lib\linecache.py", line 14, in getline    lines =
getlines(filename, module_globals)
  File "C:\Python26\lib\linecache.py", line 40, in getlines    return
updatecache(filename, module_globals)
  File "C:\Python26\lib\linecache.py", line 129, in updatecache    lines =
fp.readlines()
MemoryError

W:\SQA_Library\tools\Robot_Framework\Verification\Procedure\PQtest&gt;

/******************************************************************/
Report from System 3 (Linux) Test:

When I ran 5000 loops of your test program, it was CPU bound during the
actual test, then switched to disk bound.  The CPU bound phase, which
coincided with the writing of output.html, took exactly one hour, from
20:24 to 21:24.

It is still in the disk bound phase after more than 2 hours.  The disk
activity is almost entirely due to swapping, with nearly 1 GB of physical
memory and nearly 1 GB of virtual memory in use.  I discovered that by
turning off an energy saving feature (athcool) in the CPU I could improve
system response considerably, but here it is close to midnight and it is
still chugging away.

I noticed that the only file written during the CPU bound phase was
output.xml -- about 400 meg.  I suspect that the program is in the process
of creating the html outputs, but is formatting them in memory before
writing them to disk.  If the machine had about 2 GB of physical memory,
that would eliminate swapping and make this go orders of magnitude faster.
 With 1 GB, it might work better if Robot Framework wrote the HTML directly
to disk, instead of formatting in RAM since that is actually disk in this case.

Robot Framework Version 2.1
Python Version 2.6
Systems:
/*****************************************************************_/
System 1 Information
System Information report written at: 06/16/09 09:59:17
[System Summary]
Item Value
OS Name Microsoft Windows XP Professional
Version 5.1.2600 Service Pack 2 Build 2600
OS Manufacturer Microsoft Corporation
System Manufacturer Dell Computer Corporation
System Model OptiPlex GX270
System Type X86-based PC
Processor x86 Family 15 Model 3 Stepping 4 GenuineIntel ~2793 Mhz
Processor x86 Family 15 Model 3 Stepping 4 GenuineIntel ~2793 Mhz
BIOS Version/Date Dell Computer Corporation A04, 5/17/2004
SMBIOS Version 2.3
Windows Directory C:\WINDOWS
System Directory C:\WINDOWS\system32
Boot Device \Device\HarddiskVolume1
Locale United States
Hardware Abstraction Layer Version = "5.1.2600.2180 (xpsp_sp2_rtm.040803-2158)"
User Name 
Time Zone Eastern Daylight Time
Total Physical Memory 1,024.00 MB
Available Physical Memory 636.45 MB
Total Virtual Memory 2.00 GB
Available Virtual Memory 1.95 GB
Page File Space 2.40 GB
/**_***********************************************************/
System 2 Information
System Information report written at: 06/17/09 10:36:31
System Name: LCSGOLDBUILD
[System Summary]

Item    Value  
OS Name Microsoft Windows XP Professional  
Version 5.1.2600 Service Pack 2 Build 2600  
OS Manufacturer Microsoft Corporation  
System Name LCSGOLDBUILD  
System Manufacturer ASUSTek 
System Model    NCT-D  
System Type X86-based PC  
Processor   x86 Family 15 Model 4 Stepping 1 GenuineIntel ~2800 Mhz 
Processor   x86 Family 15 Model 4 Stepping 1 GenuineIntel ~2800 Mhz 
Processor   x86 Family 15 Model 4 Stepping 1 GenuineIntel ~2800 Mhz 
Processor   x86 Family 15 Model 4 Stepping 1 GenuineIntel ~2800 Mhz 
BIOS Version/Date   American Megatrends Inc. 1003.001, 6/29/2004  
SMBIOS Version  2.3 
Windows Directory   C:\WINDOWS  
System Directory    C:\WINDOWS\system32 
Boot Device \Device\HarddiskVolume1 
Locale  United States  
Hardware Abstraction Layer  Version = "5.1.2600.2180
(xpsp_sp2_rtm.040803-2158)" 
User Name   ANALOGIC\dsawyer  
Time Zone   Eastern Daylight Time  
Total Physical Memory   2,048.00 MB 
Available Physical Memory   1.56 GB 
Total Virtual Memory    2.00 GB 
Available Virtual Memory    1.95 GB 
Page File Space 3.85 GB 
Page File   C:\pagefile.sys 

/******************************************************************/
System 3 Information
[X RobotFramework]$ cat /proc/cpuinfo
processor       : 0
vendor_id       : AuthenticAMD
cpu family      : 6
model           : 8
model name      : AMD Athlon(tm) XP 1700+
stepping        : 1
cpu MHz         : 1469.994
cache size      : 256 KB
fdiv_bug        : no
hlt_bug         : no
f00f_bug        : no
coma_bug        : no
fpu             : yes
fpu_exception   : yes
cpuid level     : 1
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic mtrr pge mca cmov
pat pse36 mmx fxsr sse syscall mmxext 3dnowext 3dnow up
bogomips        : 2939.98
clflush size    : 32
power management: ts
[sawyer@&#8288;steinmetz RobotFramework]$ cat /proc/version
Linux version 2.6.27.24-170.2.68.fc10.i686
(mockbuild@&#8288;x86-4.fedora.phx.redhat.com) (gcc version 4.3.2 20081105 (Red
Hat 4.3.2-7) (GCC) ) #1 SMP Wed May 20 23:10:16 EDT 2009

Physical memory is 1 GB, and swap memory is 2 GB.

**Comment by putaodoudou** [comment]
i met the same issue

**Comment by hnlypczyc** [comment]
I also met this issue, when parse the xml file to log file, Memory Error is occurd. Does anyone have a resolve way? Thanks.

**Comment by Zaki-2** [comment]
Maybe this answer is useful for the people who had the same issue: https://groups.google.com/g/robotframework-users/c/zlO3cHAo55Y
