### ISSUE TITLE
Expose keyword line numbers via listener API v2

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#3538]
Test line numbers were exposed already in RF 3.2 (#3451) via `start/end_test` methods but for technical reasons we couldn't add this info to `start/end_keyword` methods. The technical reason is that the execution side code didn't make this possible, and it also the reason why we haven't been able to add `start/end_keyword` methods to the listener API v3 (#3296).

**Comment by pekkaklarck** [comment]
We have PR #3518 about adding the keyword source information to `start/end_test` methods. It is compatible with RF 3.2, but unfortunately it cannot be merged due to the [reasons explained in its comments](https://github.com/robotframework/robotframework/pull/3518#issuecomment-608361005). If you happen to need this information badly, you can use the version in the PR until this feature is added to Robot Framework itself.

**Comment by pekkaklarck** [comment]
Probably the biggest benefit of getting keyword source information via the listener API (v2 or v3) would be making it a lot easier to create debuggers. If there are lot of needs for that, or for this functionality in general, we can consider creating RF 3.3 where the main enhancement would be cleaning up the execution code so that this and #3296 could be implemented. The current RF 4.0 has also many other big enhancements which means that it will take quite long time until it is released. RF 3.3 with better execution side logic would directly benefit other features planned for RF 4.0 (e.g. IF/ELSE), so it shouldn't post-pone RF 4.0 release much. Having an intermediate release with important features like this one might very well be worth that.

**Comment by mkorpela** [comment]
line number and source would also be extremely beneficial to show on stdout when a test fails.
Now showing only the failure reason.

**Comment by mkorpela** [comment]
Related draft.
https://github.com/robotframework/robotframework/pull/3672

**Comment by mkorpela** [comment]
This is now added to development-4.0 branch as https://github.com/robotframework/robotframework/commit/76c821f0e1b8b4d25effa44e290b3429677431af

**Comment by pekkaklarck** [comment]
This has been implemented by 67fd7f76203f94402977bb8b53a8a415a6897f5a. The version in alpha 3 didn't report line numbers correctly with the new IF/ELSE and this apparently isn't yet documented in the User Guide either.

**Comment by pekkaklarck** [comment]
It turned out source information isn't reported correctly in all cases. Fixing that is somewhat complicated and we decided to post-pone it to beta 2. If we get `start/end_keyword` added to listener v3 (#3296), supporting source with listener v2 will be easy and the current line number number implementation can be simplified as well.
