### ISSUE TITLE
Error in importing "asammdf" in python library mentioned in Robot file

### ISSUE THREAD

**Issue by shyamdb** [robotframework/robotframework#3541]
i have written a custom Library in python, which imports a package named "asammdf". But, when i import my custom Library in Robot code, it shows error in importing "asammdf" in python. It says: "Error in File *.robot. Importing test Library *.py failed. Import Error: DLL load failed: the specified module could not be found."

"asammdf" package is available in one of the PYTHONPATH it mentions during executions.

Can someone please help me doing this and let me know, what have i done wrong? 

My python File (example.py):

import asammdf
...
...
...

My robot file (test.robot):

*** Settings ***
Library example.py

*** Test Cases ***
TC1
   DO THIS
   DO THAT

===> I think, it is the issue because of Relative imports give in asammdf package. If it's true, How can i resolve it? Is there any way to import python scripts as a library, which has relative imports mentioned inside?

Thanks in Advance.

**Comment by pekkaklarck** [comment]
You apparently don't have the DLL in the load path. Set the path correctly before running tests and it should work.
