### ISSUE TITLE
Getting error Old page did not go stale within 10s when opened new browser window after clicking link in application and trying access control on new popup page

### ISSUE THREAD

**Issue by shripadoka** [robotframework/robotframework#3542]
Getting error Old page did not go stale within 10s when opened new browser window after clicking link in application and trying access control on new popup page.

In my application there is link which opens a new browser window but when I am trying to access controls or close that browser getting following error
TimeoutException: Message: Old page did not go stale within 10s

**Comment by pekkaklarck** [comment]
This issue tracker is for bug reports and enhancement requests related to Robot Framework itself. Issues related to external libraries or tools should be submitted to their trackers and general questions send to actual support forums such as robotframework-users mailing list or our Slack.
