### ISSUE TITLE
issue with  SudsLibrary  'Create Soap Client'  with pyhton 3.7.7

### ISSUE THREAD

**Issue by remicharleslageixarena** [robotframework/robotframework#3544]
Hi,
I must to migrate RobotFramework tests for SOAP  writing with python 2.7 to python 3.7.7 with a new version of RobotFramework.
The problem when I use the keyword “**Create Soap Client**” like after
**“${Soap_Id}      Create Soap Client          ${A_URL_WSDL}             alias=Infg”**

This syntaxe is running on **Python 2.7**
But
not running on  **Python 3.7.7** .   The result is the following error

*************************************************
KEYWORD ${Soap_Id} = SudsLibrary . **Create Soap Client** ${A_URL_WSDL}, alias=Infg
Documentation: | Loads a WSDL from the given   URL/path and creates a Suds SOAP client.
FAIL | **AttributeError: module   'urllib' has no attribute 'pathname2url'**
Start / End / Elapsed: | 20200412 14:36:36.188 / 20200412 14:36:36.190 /   00:00:00.002
*************************************************
**Have you got some ideas to fix this issue?
Do you know somebody to help me?**
Thanks in advance

PS: I saw in Python2 urllib.request  will be come usrlib.request.request, but I don't know kown to use this information in the robotframework library.
*************************************************
my configuration is:
-	OS : windows 10 professionnal
-	Python 3.7.7
-	**requests                       2.23.0**
-	requests-toolbelt              0.9.1
-	requests3                      0.0.0
-	robotframework                 3.1.2
-	robotframework-databaselibrary 1.2.4
-	robotframework-jsonlibrary     0.3.1
-	robotframework-python3         2.9
-	**robotframework-requests        0.6.6**
-	robotframework-ride            1.7.4.1
-	robotframework-seleniumlibrary 4.3.0
-	robotframework-sshlibrary      3.4.0
-	**robotframework-sudslibrary3    1.0**
-	robotframework-zeeplibrary     0.9.2
-	….
-	suds-jurko                     0.6
-	**suds3                          0.1**
-	tox                            3.0.0
-	**urllib3                        1.25.8**
*************************************************

**Comment by pekkaklarck** [comment]
This issue tracker is for bug reports and enhancement requests related to Robot Framework itself. Issues related to external libraries or tools should be submitted to their trackers and general questions send to actual support forums such as robotframework-users mailing list or our Slack.
