### ISSUE TITLE
Pywinauto does not recognize desktop elements when used in Custom Library 

### ISSUE THREAD

**Issue by Tungalasriharibabu** [robotframework/robotframework#3551]
I use Pywinauto library to automate the desktop app.  When I simply use Pywinauto methods in python scripts it works fine. But when I convert those scripts into keywords using the custom library Pywinauto fails to work (unable to recognize desktop application).

Custom Library Code - https://gist.github.com/Tungalasriharibabu/d177449969120d72c9fb88ba9b6c9ae1

**Comment by pekkaklarck** [comment]
I don't know Pywinauto well enough to help at all. The only thing I can say is that the issue certainly isn't in Robot Framework itself. This being Robot Framework issue tracer I close this issue.
