### ISSUE TITLE
Is there a way to programatically add tagstatlink ?

### ISSUE THREAD

**Issue by xNok** [robotframework/robotframework#3553]
I would like to add links on tags that point to the url of the corresponding issue in our issue tracker.

`--tagstatlink`  performed the desired task but it is very tedious to define every links manually. Therfore I'd like to be able to add those links at run time.

I believe using a listener could do the job but I did not figure out the link between the tag in the *TestCase* or *TestSuite* and the *TagStat* used to create the report.

**Comment by pekkaklarck** [comment]
This isn't possible and I personally don't see big benefits with it. Why isn't it enough to create a start-up script like `run.py` that calls `robot.run_cli()` or possibly `robot.run()` to run tests?

**Comment by pekkaklarck** [comment]
Closing due to lack of information.
