### ISSUE TITLE
After generating output.xml, report, log and debug file getting error after the generation of xunit xml in robot framework.

### ISSUE THREAD

**Issue by akanksha1811** [robotframework/robotframework#3564]
I am using robot framework for testcase writing and execution. I am using it with python to generate output.xml, debug, log and report after the test case is executed from robot. But after the generation of xunit XML, I am getting below error.

Using:
robot framework 3.1.2
robot framework-sshlibrary  3.4.0
python 3.5.3
 

Debug:   C:\dev\ifxaster\results\IntTest_Crc_debug.log
Output:  C:\dev\ifxaster\results\IntTest_Crc.xml
XUnit:   C:\dev\ifxaster\results\IntTest_Crc_Xunit.xml
Log:     C:\dev\ifxaster\results\IntTest_Crc_log.html
Report:  C:\dev\ifxaster\results\IntTest_Crc_report.html
[ INFO ] Done execution using Robot Framework
[ ERROR ] Reading XML source 'C:\dev\ifxaster\results\IntTest_Crc_Xunit.xml' failed: Incompatible XML element 'testsuite'.

**Comment by pekkaklarck** [comment]
You didn't show the command you used, but based on the error it seems like you'd tried to use the Rebot tool with Robot's xunit output. Rebot understands only Robot's own output.xml.

**Comment by akanksha1811** [comment]
I have enabled Robot's Xunit command, and it is taking data from Robot's output.xml. But after the generation of Xunit.xml, With the help of junitparser and etree.Elementtree library of python I have modified the generated Xunit.xml by adding few tags and attributes to it at the time of generation using python scripting

**Comment by pekkaklarck** [comment]
You got this error:

> [ ERROR ] Reading XML source 'C:\dev\ifxaster\results\IntTest_Crc_Xunit.xml' failed: Incompatible XML element 'testsuite'.

It comes from Rebot when it tries to parse an incompatible XML file and that incompatible `testsuite` element gives a hint that this incompatible XML file is an xunit output file. The xunit file could have been created by Robot or some other tool. I can easily reproduce this with Robot:

    $ robot --xunit xunit.xml example.robot
    [normal console output]
    $ rebot xunit.xml
    [ ERROR ] Reading XML source 'xunit.xml' failed: Incompatible XML element 'testsuite'.

    Try --help for usage information.

There's clearly something wrong in your setup. I don't know exactly what, but discussing about that is not something that belongs to this issue tracker. If you cannot get the issue resolved, send a question to robotframework-users mailing list or ask on our Slack. Notice that you need to tell a bit more about your context for anyone to be able to help.
