### ISSUE TITLE
Execution can crash if `stdin` is closed

### ISSUE THREAD

**Issue by szborows** [robotframework/robotframework#3565]
After upgrading from `3.1.2` to `3.2.` some of our code stopped working with peculiar exception:

```
...
/usr/local/lib/python3.7/site-packages/robot/__init__.py in <module>
/usr/local/lib/python3.7/site-packages/robot/rebot.py in <module>
/usr/local/lib/python3.7/site-packages/robot/conf/__init__.py in <module>
/usr/local/lib/python3.7/site-packages/robot/conf/settings.py in <module>
/usr/local/lib/python3.7/site-packages/robot/output/__init__.py in <module>
/usr/local/lib/python3.7/site-packages/robot/output/output.py in <module>
/usr/local/lib/python3.7/site-packages/robot/output/pyloggingconf.py in <module>
/usr/local/lib/python3.7/site-packages/robot/utils/__init__.py in <module>
/usr/local/lib/python3.7/site-packages/robot/utils/argumentparser.py in <module>
/usr/local/lib/python3.7/site-packages/robot/utils/encoding.py in <module>
/usr/local/lib/python3.7/site-packages/robot/utils/encodingsniffer.py in get_console_encoding()
/usr/local/lib/python3.7/site-packages/robot/utils/encodingsniffer.py in _get_encoding()
/usr/local/lib/python3.7/site-packages/robot/utils/encodingsniffer.py in _get_stream_output_encoding()
/usr/local/lib/python3.7/site-packages/robot/utils/compat.py in isatty()
ValueError: I/O operation on closed file
```

It looks like Robot now calls `isatty()` at `sys.__stdin__` object. That leads to aforementioned exception. MWE from JupyterLab in case someone wants to double-check:

```python
def process():
    import sys; sys.__stdin__.isatty()

import dask.distributed
with dask.distributed.Client("[REDACTED]") as executor:
    next(dask.distributed.as_completed([executor.submit(process)])).result()
```

There are lots of moving parts in our setup, so in case you have additional questions (like Dask version, JupyterLab version), please ask.

**Comment by szborows** [comment]
for the record I believe this is the culprit:
https://github.com/robotframework/robotframework/commit/ae0d0a3f1d72dbafaabf59b2d3c37e63343e1f13

**Comment by pekkaklarck** [comment]
I don't know the JupyterLab setup that well myself but perhaps @datakurre can comment this. Based on the experimenting below I can easily believe the `isatty()` call is causing this:
```python
>>> f = open('README.rst')
>>> f.isatty()
False
>>> f.close()
>>> f.isatty()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: I/O operation on closed file
```
We can easily enhance our `isatty()` utility to catch that ValueError and return False in that case. Could you @szborows possibly try does that fix the issue in your environment?

Kind of good news is that we need RF 3.2.1 soon anyway (planned for next Monday) so we'll get a fix out soon.

**Comment by pekkaklarck** [comment]
Adding guard for closed files to the `isatty()` util felt like so good idea that I decided to do it in the above commit. You can know install the latest version with the fix using this command:

    pip install https://github.com/robotframework/robotframework/archive/master.zip

**Comment by datakurre** [comment]
Thanks for heads up. Curious that I did not run into this while using the latest JupyterLab with 3.2.

**Comment by pekkaklarck** [comment]
The code where the error occurs is here:
https://github.com/robotframework/robotframework/blob/master/src/robot/utils/encodingsniffer.py#L87

Apparently one of `sys.__stdout__`, `sys.__stderr__` and `sys.__stdin__` is closed and thus `steam.isatty()` inside the `isatty()` util raises a ValueError. Closed stdout or stderr sounds pretty strange, so I'm guessing the closed stream is stdin.

**Comment by szborows** [comment]
@pekkaklarck 
yup, that's `stdin`, look at my original MWE (or rather MNWE):

```python
def process():
    import sys; sys.__stdin__.isatty()
```

anyway.. thanks for such a quick reaction. I will try to confirm ASAP that the fix works.

**Comment by szborows** [comment]
I've tested the fix on local dask cluster and it obviously works!

**Comment by szborows** [comment]
from my POV the issue is resolved, hence I'm closing it. Thanks!

**Comment by pekkaklarck** [comment]
Great that the fix works! RF 3.2.1 with this fix as well fix for #3561 will be released next Monday.

**Comment by pekkaklarck** [comment]
The error occurs when Robot tries to detect console encoding from standard streams and it won't happen in these cases:

- Windows with Python 3.6+. In this situation we don't look at standard streams at all because their encoding is always UTF-8 and we want the real encoding the system uses.
- If stdout or stderr have encoding set. Then we just use that and don't look at stdin.

My understanding is that this only occurs if stdout/stderr are redirected and stdin is closed. That's pretty rare, but the whole execution crashing is so severe that this issue deserves high priority.

**Comment by szborows** [comment]
reproduction steps are below, just for the record. Maybe this is rare, idk. The setup is JupyterLab + Dask cluster.

```shell
python3 -mvenv venv
. ./venv/bin/activate
pip3 install "dask[distributed]"
```

```python
from dask.distributed import Client
def process():
    import sys; sys.__stdin__.isatty()
Client().submit(process).result()
```
