### ISSUE TITLE
problem using decorators in libraries with robotframework 3.2

### ISSUE THREAD

**Issue by scathaig** [robotframework/robotframework#3567]
When using robotframework 3.2 it seems that decorators in libraries are broken. In the attached example robot fails with "Keyword 'MyLibrary.My Keyword' expected 2 arguments, got 1." Downgrading to robotframework==3.1.2 fixes this. Did I miss something in the release notes for 3.2?

[example.zip](https://github.com/robotframework/robotframework/files/4565559/example.zip)

**Comment by pekkaklarck** [comment]
Have you looked at #3561?

**Comment by scathaig** [comment]
thanks, that is the same issue. I tried robotframework-3.2.1.dev1 and there it is working again.

**Comment by pekkaklarck** [comment]
Thanks for testing!
