### ISSUE TITLE
A way to run robot Keywords without a Testcase

### ISSUE THREAD

**Issue by damien122** [robotframework/robotframework#3569]
Hi,
is there a way to run robot Keywords without any Testcase or Testsuite?
The problem is that I can't use Tags for that. Every thing I want is to just start the `robot.exe` with some parameters to execute one Keyword form a File, nothing more.
Maybe with `--prerunmodifier`? I use this `--prerunmodifier` to exlude testcases by name, so maybe it is possible to execute only keywords?

**Comment by pekkaklarck** [comment]
No, you cannot run keywords alone. If you aren't really creating and running tests, you can create tasks instead. See the User Guide for details.

**Comment by damien122** [comment]
I have found a solution, a small python script for temp test suites.

```
# How to Use:
# python.exe .\KeywordExecutor.py KEYWORD ARGUMENT

from robot.api import TestSuite
import sys
import os

keywordPath = "./PATH/TO/YOUR/KEYWORDS/"
allKeywordFiles = os.listdir(keywordPath)

# Set Test Suite Name from Keyword
suite = TestSuite(sys.argv[1])

# Import Dependencies
suite.resource.imports.library('BuiltIn')
suite.resource.imports.library('Collections')
suite.resource.imports.library('OperatingSystem')
suite.resource.imports.library('Process')
suite.resource.imports.library('String')

# Import all Keyword files as Resource
for val in allKeywordFiles:
    suite.resource.imports.resource(keywordPath + val)

# Create empty Test with name like suite
test = suite.tests.create(sys.argv[1])

# Create the keyword in the test case 
test.keywords.create("Remote Wrapper", args=sys.argv[1:])

# You can set some suite variables in the RUN method
result = suite.run(variable='VARIABLE:VALUE', output='keyword-execute.xml', outputdir='result/KeywordExecute')
exit(result.return_code)

```

also a small keyword is needed the `Remote Wrapper`:

```
*** Settings ***
Library     BuiltIn

*** Keywords ***
Remote Wrapper
    [Arguments]     ${KeywordExec}      @{KeywordArgs}
    ${_res}=        Run Keyword     ${KeywordExec}      @{KeywordArgs}
```

afterwards you need a small application or keyword to modify the output.xml and remove the keyword `Remote Wrapper` and `Run Keyword` and set the status and message from `Remote Wrapper` to your test. This is my solution to execute a single keyword in robot, it is used to execute single keywords for client server tests.
