### ISSUE TITLE
Is there one easy method to continue all test cases and steps after step is fail

### ISSUE THREAD

**Issue by mmclwd** [robotframework/robotframework#3573]
As we all know, one test step is fail this case will stop immediately. Sometimes I want all test steps for all suite should continue if step is fail. I know there is one way to make it is using 'Continue on failure', but I need to add it for every step as I know.
Is there one easy command provided for us to fullfill this condition, eg. '--continue', or similar like it.
Because I want to feel free to enable or disable this function before test without modifying test case.

**Comment by pekkaklarck** [comment]
No there isn't. We do have #2285 about making it easier to control the continue-on-failure mode but nobody has shown much interest towards it lately.
