### ISSUE TITLE
How to catch signals inside listener from pybot?

### ISSUE THREAD

**Issue by paul105** [robotframework/robotframework#3575]
Hi, I'm having a following problem:
I'm running some tests within suite which are using Python library. This library is a listener
`def __init__(self):
        self.ROBOT_LIBRARY_LISTENER = self`
This library is communicating with some external resource and starts something there.
The problem is that if the pybot will be closed by some kind of a signal (SIGTERM, Keyboard Interruption, SIGINT) I would like to know that inside my listener and be able to close what was started externally.
Is it possible?

**Comment by pekkaklarck** [comment]
Listeners have `close` method but I'm not certain is it called in this case. If not, we could take a look can that be changed. Other alternatives include handling the signal yourself and using `__del__` or `atexit`.

**Comment by paul105** [comment]
Thanks for info Pekka! Handling signals "as usual" works. At the end `close` is called anyway and the last one is `atexit`. I dont' see anything from `__del__`. I'm closing the issue.
