### ISSUE TITLE
Ping executed with run process has very high latency

### ISSUE THREAD

**Issue by buscseik** [robotframework/robotframework#3576]
Hi All, 

I try to check ping from robotframework, but noticed strange behaviour whit "run process" keyword.
See sample script to demonstrate the problem:

Robot test:

    *** Settings ***
    Library             Process
    
    *** Test Cases ***
    test-001
      Run Process       powershell.exe     ping 192.186.0.1   alias=pingprocess
      ${pingresult}=   Get Process Result      pingprocess
      Log to console   ${pingresult.stdout}

This will produce the following output:

    ==============================================================================
    Stability.MV1
    ==============================================================================
    test-001                                                              ..
    Pinging 192.186.0.1 with 32 bytes of data:
    Reply from 192.186.0.1: bytes=32 time=312ms TTL=242
    Reply from 192.186.0.1: bytes=32 time=313ms TTL=242
    Reply from 192.186.0.1: bytes=32 time=311ms TTL=242
    Reply from 192.186.0.1: bytes=32 time=310ms TTL=242
    
    Ping statistics for 192.186.0.1:
        Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
    Approximate round trip times in milli-seconds:
        Minimum = 310ms, Maximum = 313ms, Average = 311ms
    test-001                                                              | PASS |
    ------------------------------------------------------------------------------
    Stability.MV1                                                         | PASS |
    1 critical test, 1 passed, 0 failed
    1 test total, 1 passed, 0 failed
    ==============================================================================
    Output:  D:\CodeProjects\CpeTestAutomation\StabilityTests\report\output.xml
    Log:     D:\CodeProjects\CpeTestAutomation\StabilityTests\report\log.html
    Report:  D:\CodeProjects\CpeTestAutomation\StabilityTests\report\report.html

I have created a small alternative Python script which will do the same:

   
    import subprocess
    
    def execute_bash_cmd(cmd_str):
        process = subprocess.Popen(cmd_str.split(), stdout=subprocess.PIPE)
        output, error = process.communicate()
        return output.decode('utf-8').strip()
        
    result=execute_bash_cmd("powershell.exe ping 192.186.0.1")
    for next_line in result.split('\n'):
        print(next_line)

This will create the following output:

    Pinging 192.168.0.1 with 32 bytes of data:
    Reply from 192.168.0.1: bytes=32 time=2ms TTL=64
    Reply from 192.168.0.1: bytes=32 time=16ms TTL=64
    Reply from 192.168.0.1: bytes=32 time=1ms TTL=64
    Reply from 192.168.0.1: bytes=32 time=1ms TTL=64
    
    Ping statistics for 192.168.0.1:
        Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
    Approximate round trip times in milli-seconds:
        Minimum = 1ms, Maximum = 16ms, Average = 5ms

As you can see, I have avg 5ms respone time, but when ping executed via Robotframework, the response time is increased by over 300ms. 

Am I doing someting wrong?

**Comment by pekkaklarck** [comment]
I've never tried running ping with Run Process and don't have any idea what would cause the delay. I hope you can debug this further and report here if you find something. You should first make sure you run the exact same command and ping the same host, though.

**Comment by buscseik** [comment]
I did modify the ticket with the same command, as you recommended.
If you have any idea, what should I test, let me know.

**Comment by pekkaklarck** [comment]
It's still not exactly the same. With Robot you pass two arguments "powershell.exe" and "ping 192.186.0.1" but with Python you use three args "powershell.exe", "ping" and "192.186.0.1". Not sure does it matter but good to test anyway. You could also see what's the speed if you call `Process.run_process()` directly from Python w/o RF (I hope that works) or just look at the `Process` code and see what extra it does compared to your direct Python code.

**Comment by buscseik** [comment]
I have just noticed a very strange thing which can help to understand this issue.

I have at home a network with 192.168.2.0/24. My gateway is 192.168.2.1.
If I ping 192.168.2.1 from  powershell console, I'll get response.
If I ping 192.168.0.1 from  powershell console, I won't get response.

If I ping 192.168.2.1 from above mentioned robot script, I won't get response
If I ping 192.168.0.1 from above mentioned robot script, I will get response with high latency.

If I ping 192.168.2.1 from above mentioned python script I will get response
If I ping 192.168.0.1 from above mentioned python script I won't get response

(It looks like, it is wrapped in some kind if nat or virtual layer)
I do not have the same problem if I run directly from python

**Comment by buscseik** [comment]
I have investigated further away and I made a type-o:
I have pingged  192.186.0.1  instead of 192.168.0.1 and it seems 192.186.0.1 is some special ip on my system.

So this is not an issue
