### ISSUE TITLE
Drop Python 3.4 support

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#3577]
Python 3.4 has reached its end-of-life already in 2019. RF 3.2.x still supports it but there's no point in RF 3.3 or newer supporting it anymore. What this mean in practice:

- Remove Python 3.4 from officially supported versions in setup.py and README.
- Stop testing with Python 3.4. We actually haven't tested it on CI at all, but I've had Python 3.4 on my old laptop and tested it there.
- No immediate code changes. As long as we still support Python 2.7 and 3.5 (#3457) we cannot really take modern Python features into use anyway.

If someone happens to still need Python 3.4 support, please test RF in your environment and submit pull requests if we break something. PRs fixing Python 3.4 support will be accepted assuming they are simple and don't cause problems with other interpreters.

**Comment by hugovk** [comment]
Please see PR #3653.

**Comment by pekkaklarck** [comment]
PR #3653 implements this. Because it updates the docs shown on GitHub by default I'll wait until we are about to release RF 4.0 alpha 1 before merging it.
