### ISSUE TITLE
`--exitonfailure` option ignores dynamic changes to criticality

### ISSUE THREAD

**Issue by saer227** [robotframework/robotframework#3584]
If you switch a test tag from critical to noncritical during execution then `--exitonfailure` option will still consider the test critical and activate exitonfailure mode.
Code for reproducing the bug:

    *** Settings ***
    Documentation     A test suite to check criticality changes

    Default Tags      critical

    *** Variables ***

    *** Test cases ***
    First Critical Test Case
        Log  First test body done
        Should Be True    ${TRUE}

    Second Critical Test Case Switched To Noncritical
        [Setup]    Switch To Noncritical
        Log  Second test body executed
        Should Be True    ${FALSE}

    Third Critical Test Case
        Log  Third test body done
        Should Be True    ${TRUE}

    *** Keywords ***
    Switch To Noncritical
        Remove Tags    critical
        Set Tags       noncritical

I ran it with `-c critical -n noncritical --exitonfailure` options.
RF Version:  3.1.2 (Python 3.6.0 on win32)
Selenium Version:  3.141.0
SeleniumLibrary Version: 4.3.0

**Comment by pekkaklarck** [comment]
Confirmed. Luckily easy to fix.
