### ISSUE TITLE
--expandkeywords fails in some cases

### ISSUE THREAD

**Issue by DirkRichter** [robotframework/robotframework#3585]
On large files log.html concurrent expanding is processed for **failed keywords** and argument **expandkeywords** in order to show them initially when log.html is opened. This concurrent expanding fails in some cases due to conflicting concurrency. 

### Sample and Details
While using robot argument 

`--expandkeywords name:SeleniumLibrary.CapturePageScreenshot `

setting css via jquery has no effect in some rare cases:

`children.css({'display': 'block'});`

Result: some screenshots are not visible.

**Comment by zlanaz** [comment]
Hi there,

Guys is there a way to disable the auto expand of failed cases?
I just want to see all tests closed and expand them as I need

Thank you!
Lily

**Comment by DirkRichter** [comment]
you can use report.html instead (no expansion) and click on the tests, which failed.
