### ISSUE TITLE
Libdoc should format argument names, defaults and types differently

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#3586]
Libdoc shows argument names in format `name: type=default` (e.g. `count: int=1`) where both `: type` and `=default` are used only when needed. Currently all this is in same font, but adding some styles would be a good idea. If someone has ideas about good styles to use, please tell your ideas in comments or provide a PR!

This is somewhat related to #3578 but because this issue affects only HTML outputs there are no backwards incompatibility concerns. Implementing this already in RF 3.2.2 is thus possible.

**Comment by pekkaklarck** [comment]
Moved to 3.3 scope because:
- This requires changes to Libdoc's model that are a bit too big for a patch release like 3.2.2.
- Libdoc model changes are also needed by #3578. Better to design them together.

**Comment by aaltat** [comment]
Well, I don't have any suggestions for styles, but would it be good idea to look few examples from IDE or how GitHub does colouring for Python type hints. Example GitHub leans to orange with white background and perhaps default values could be bluish. I would lead the argument itself to black.

**Comment by rasjani** [comment]
Sorry if this is not applicable to this issue but it talked about formatting arguments in libdoc.  

I have type hints like this within my source code:
```python
def drag_and_drop(self: "SeleniumTestability", locator: LocatorType, target: LocatorType, html5: bool = False) -> None:
```
Where LocatorType previously defined as:
```python
from selenium.webdriver.support.event_firing_webdriver import EventFiringWebElement, EventFiringWebDriver
LocatorType = Union[WebElementType, EventFiringWebElement, str]
```

In the docs this looks this:

```
locator: typing.Union[selenium.webdriver.remote.webelement.WebElement,selenium.webdriver.support.event_firing_webdriver.EventFiringWebElement, str], 
target: typing.Union[selenium.webdriver.remote.webelement.WebElement,selenium.webdriver.support.event_firing_webdriver.EventFiringWebElement, str], 
html5: bool=False
```

For me, having the full path to the type declaration is fine but for some this sort of presentation might be "scary" or not very readable. At least when generating html docs, it would be a bit nicer if the paths were to be shown only on tooltips and the "readable" part of the arguments would be like:

```
locator: Union[WebElement,EventFiringWebElement, str], 
target: Union[WebElement,EventFiringWebElement, str], 
html5: bool=False
```

and then, when hovering on, say, "WebElement" string, there would be tooltip (for example, with span tag and title) shown with full type information.

**Comment by pekkaklarck** [comment]
That definitely doesn't look good. I think it would be best if the doc just showed `locator: LocatorType` instead of resolving `LocatorType` but I don't know is implementing that possible. It probably would be better to submit a separate issue about this.

**Comment by pekkaklarck** [comment]
Could you @rasjani test does `from __future__ import annotations` help? For more details about it and why it could help see https://www.python.org/dev/peps/pep-0563/.

**Comment by rasjani** [comment]
@pekkaklarck i dont know enough about type annotation internals to make any statements what so ever but if "test" by adding that future import to libdoc is enough, it did not have any effect.

**Comment by xylix** [comment]
I think just changing the splitting of arguments makes (at least in our project, but I would expect similar readability in other KWs with a lot of arguments) the arg doc much more readable. See 
![Screenshot 2020-08-13 at 11 01 50](https://user-images.githubusercontent.com/13387304/90109937-2ae79480-dd55-11ea-9fa1-2d2bd6efb69f.png)
![Screenshot 2020-08-13 at 11 01 42](https://user-images.githubusercontent.com/13387304/90109945-2c18c180-dd55-11ea-8ea9-b1f7cadf7f10.png)

Was there agreement on what sort of syntax highlighting was desired and does it require libdoc model changes that are incompatible with old format?

**Comment by Snooz82** [comment]
@xylix Kerkko,

You changed this already in libdoc, right?
Could you do a PR, then Maybe @pekkaklarck could put it this min improvement to 3.2.2

**Comment by pekkaklarck** [comment]
Do I get it right that the enhancement by @xylix just splits arguments to multiple lines? Something like that could be done already in 3.2.2. Could possibly be done conditionally depending on argument count or the length of the whole argument spec. Another alternative would be adding max width to the argument column.

Actual syntax highlighting requires bigger changes to Libdoc model. Don't think it's safe in 3.2.2.

**Comment by aaltat** [comment]
Generally speaking I would prefer a constant style with arguments (all formated in the same way, regardless of the number or length), because constant style makes it easier to read. From the users point of view, they may prefer current style or each argument splitted to own line and it might make better to provide a command line argument to choose which style is they prefer. 

Other option could be that if library uses typing hints then all keywords arguments would be splitting to own lines. This makes easier to read the arguments and their types. And if typing hints are not present,  arguments would use the current style.

**Comment by rasjani** [comment]
@aaltat from my pov, showing typing hints is really good. Even in a long run too because that exposes a bit of python land to people and exposing same syntax is good. But there are few angles, first: How the type hints are rendered atm is IMO a bit hard to read (this is my main issue) Second: would the "Python bleed" to documentation be considered bad cuz it would give indication that core prefers python ? I don't remember seeing keyword docs made from java or remote libs having the type information shown even thou in java that most likely is very easy to implement.  Which also makes me think that from POV of tester writing test data, having 2 different styles for type hints would be a bit weird ?

**Comment by xylix** [comment]
https://github.com/robotframework/robotframework/pull/3638 @pekkaklarck Do you have any input on how we should put a part of the HTML template behind a command line flag. Should we do this html base change on python side and only if flag is set?

**Comment by xylix** [comment]
Made a tracking issue at #3639

**Comment by pekkaklarck** [comment]
Libdoc getting some kind of built-in help explaining the argument syntax would be great as well. It could get a separate issue or be implemented as part of this one.

**Comment by mkorpela** [comment]
<img width="752" alt="Screenshot 2020-10-28 at 10 16 57" src="https://user-images.githubusercontent.com/136885/97409692-b8736300-1906-11eb-8792-a522fe2a8f4d.png">

**Comment by Snooz82** [comment]
Done
