### ISSUE TITLE
'Create Dictionary' keyword generates simple quoted JSON

### ISSUE THREAD

**Issue by rahendatri** [robotframework/robotframework#3588]
Hello,
[Create Dictionary keyword](http://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Create%20Dictionary) generates a simple quoted JSON but the right JSON format is double quoted. This behaviour could create conflicts especially if the dictionary is given to Python which expects double quoted string.
So is this on purpose ? If yes, is there any Robot library to manipulate JSON instead ?

**Comment by pekkaklarck** [comment]
`Create Dictionary` creates a Python dictionary, not JSON. If you want to convert that dictionary to JSON, you need a separate keyword. There are external libs for that purpose but we could consider adding a JSON lib to Robot's standard libs as well.
