### ISSUE TITLE
Set logging level for a certain library

### ISSUE THREAD

**Issue by danashevskiy** [robotframework/robotframework#3589]
I'm importing custom library in my test based on some other python modules which are using python `logging`. In certain situations python `logging` inside python packages emits `ERROR` message which I would like to disable. The problem is I've tried different ways but all of them are not working:

1. Set log level inside custom library for imported python module
    ```python
    imported_logger = logging.getLogger('<name of imported python module>')
    imported_logger.setLevel(logging.INFO)
    ```
2. Set log level inside custom library for both current file and imported python module
    ```python
    imported_logger = logging.getLogger('<name of imported python module>')
    imported_logger.setLevel(logging.INFO)
    current_logger = logging.getLogger(__name__)
    current_logger.setLevel(logging.INFO)
    ```
 
3. Set log level for robot framework
   ```bash
   robot --loglevel INFO test.robot
   ```
4. Set log level inside a test case:
    ```
    Set Log Level INFO
    ```
All together these actions are not working. I still receiving `ERROR` messages from `logging`.
Could you please help me to solve this issue?

**Comment by pekkaklarck** [comment]
Closing this because this issue tracker is only for bug reports and enhancement requests and I don't know the logging module well enough to be able to help anyway. If you cannot resolve the problem yourself, try asking help on support forums listed at robotframework.org.
