### ISSUE TITLE
docker container not updated for latest release

### ISSUE THREAD

**Issue by isaacegglestone** [robotframework/robotframework#3592]
Any reason the docker container version has not been updated for 3.2?

https://hub.docker.com/r/robotframework/rfdocker/tags

I'm aware it's a different repo, issue was posted there over a month ago however so also posting one here.

Just basically things do not exist these days unless they are dockerized so if whomever is maintaining that repo is not maintaining it then maybe this team should?

Ah its @asyrjasalo Whom appears to have contributed a lot on this repo.

Probably some missing automation I'm guessing a new release here should probably trigger a new container build there no?

**Comment by pekkaklarck** [comment]
That Docker container is a separate project and not automatically updated when we create new RF releases. We basically need to wait until @asyrjasalo updates the project or someone forks it and creates an updated version. He hasn't been that actively working with Robot lately so I don't know if/when such update would happen.

This issue isn't really related to RF core so I'll close it. You may want to continue discussion about the Docker situation on other forums like our mailing list or Slack.

**Comment by isaacegglestone** [comment]
Thanks.

Its fine I just used the python 3.7 container and add it to requirements.txt.
I guess thats what most people are doing who use it as a container anyway.

**Comment by siredmar** [comment]
I've set up a Github/Dockerhub chain that builds every release that is tagged with 'v[0-9a-zA-Z.]+' and creates the corresponding docker image here: https://hub.docker.com/repository/docker/siredmar/robot/general
Please feel free to use it.
@pekkaklarck would you please ensure that your tags are named always in this format? There are several tags that miss the leading 'v' in the version.

**Comment by isaacegglestone** [comment]
> I've set up a Github/Dockerhub chain that builds every release that is tagged with 'v[0-9a-zA-Z.]+' and creates the corresponding docker image here: https://hub.docker.com/repository/docker/siredmar/robot/general
> Please feel free to use it.
> @pekkaklarck would you please ensure that your tags are named always in this format? There are several tags that miss the leading 'v' in the version.

Nice work thanks for that! Maybe I'll use your container in my next iteration instead of my custom built one.

**Comment by siredmar** [comment]
I just wanted to inform you guys that i enabled multi arch builds on my docker hub account for amd64, arm64v8, arm32v6 and arm32v7. I do provide docker image for those platforms for for all major releases since 3.0.

**Comment by pekkaklarck** [comment]
First of all, thanks for setting up automatic Docker image generation @siredmar! Please announce that more publicly as well. Probably should also be mentioned at robotframework.org. You can find instructions there how to get it added.

All newer tags use the `v` prefix and we have no plans dropping it. Just didn't bother to update old tags when we took that convention into use. If that would somehow help with Docker images I could change them. Somewhat unlikely anyone would be interested in such old versions.
