### ISSUE TITLE
importing test library "json" failed

### ISSUE THREAD

**Issue by zyy98** [robotframework/robotframework#3594]
It seems a silly question, but I've googled online and found nothing. Why would importing test library "json" failed, what packages should I install?

**Comment by yo-ga** [comment]
@zyy98 This library is the RF library not Python module.
If you need json-related keyword, you can try the `Collections` library or use the `Evaluate` keyword.

[The documents of native RF library](https://robotframework.org/robotframework/)
[The document of Collections](https://robotframework.org/robotframework/latest/libraries/Collections.html)
[The document of Evaluate](https://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Evaluate)

**Comment by pekkaklarck** [comment]
Was the problem already solved @zyy98? If not, could you clarify what you actually tried to do?

**Comment by zyy98** [comment]
Thanks for answering my questions. It stills shows failure in robot framework ide as it appears in red, but the code runs just fine.
