### ISSUE TITLE
test execution order does not work per spec

### ISSUE THREAD

**Issue by schaefer01** [robotframework/robotframework#3595]
macosx 10.14.6, ride v1.7.4b2, and the latest robotframework returned by using pip install

I followed the steps here: https://seleniummaster.com/sitecontent/index.php/selenium-robot-framework-menu/selenium-robot-framework-python-menu/222-run-tests-in-certain-order-in-robot-framework-python

I then change the test names, I named renamed 001_TC1 to 003_TC1, and 003_TC3 to 001_TC3, reran and the execution order did not change.

copying and pasting from the ride run page:

Starting test: Test Case Order.TestCaseOrder.003__TC1
20200611 10:15:26.333 :  INFO : tc1
Ending test:   Test Case Order.TestCaseOrder.003__TC1

Starting test: Test Case Order.TestCaseOrder.002__TC2
20200611 10:15:26.335 :  INFO : tc2
Ending test:   Test Case Order.TestCaseOrder.002__TC2

Starting test: Test Case Order.TestCaseOrder.001_TC3
20200611 10:15:26.336 :  INFO : tc3
Ending test:   Test Case Order.TestCaseOrder.001_TC3

copying and pasting from the log page:

SUITE TestCaseOrder
Full Name:	Test Case Order.TestCaseOrder
Source:	/Users/rps/projects/aerovista/robot/Test_Case_Order/TestCaseOrder.robot
Start / End / Elapsed:	20200611 10:15:26.329 / 20200611 10:15:26.338 / 00:00:00.009
Status:	3 critical test, 3 passed, 0 failed
3 test total, 3 passed, 0 failed
00:00:00.001TEST 003__TC1
00:00:00.001TEST 002__TC2
00:00:00.001TEST 001_TC3

Any help?

**Comment by pekkaklarck** [comment]
Test case names don't affect the execution order. The trick to add `XXX__` prefix works only with suites.

**Comment by pekkaklarck** [comment]
For details see the User Guide:
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#execution-order
