### ISSUE TITLE
`:FOR` still used in BuiltIn library docs

### ISSUE THREAD

**Issue by jeroen1602** [robotframework/robotframework#3596]
Since robot framework version 3.2.0 the FOR loop has changed, but in the python documentation :FOR is still used instead of the new FOR ending with END.

I found instance of :FOR at these places.
src/robot/libraries/BuildIn.py
line 2278 `| :FOR | ${var}         | IN                     | @{VALUES}         |`
line 2296 `| :FOR | ${var}               | IN                     | @{VALUES} |`
line 2310 `| :FOR | ${var}         | IN                 | @{VALUES}     |`
line 2328 `| :FOR | ${var}         | IN                 | @{VALUES}     |`
line 2371 `|    :FOR    ${item}    IN    @{items}`
line 2401 `|    :FOR    ${item}    IN    @{items}`
line 2517 `| :FOR | ${var}            | IN                     | @{VALUES}               |`

**Comment by pekkaklarck** [comment]
Good catch. Needs to be fixed in 3.2.2. Interested to provide a PR?

**Comment by jeroen1602** [comment]
Sure I'll get on that

**Comment by jeroen1602** [comment]
I made a pull request #3597

**Comment by pekkaklarck** [comment]
Thanks for the report and the already merged PR!
