### ISSUE TITLE
library collections, get slice from list fails

### ISSUE THREAD

**Issue by schaefer01** [robotframework/robotframework#3599]
I created this test under ride=v.7.4b2, with 3 variations, so I don't know if this is a ride problem or a framework problem. I commented out each line I tested and  kept them together for better visualization of the parameter change to error message change:

the first fails with this error:
 TypeError: Expected argument 1 to be a list or list-like, got string instead.
2nd:
Keyword 'Collections.Get Slice From List' expected 1 to 3 arguments, got 4.

3rd:
TypeError: Expected argument 1 to be a list or list-like, got string instead.
lists
    @{list}=    create list    Hello,    world!
    log    ${list}
    #@{first}=    get slice from list    @{list}    end=1
    #@{first}=    get slice from list    @{list}    0    1
    @{first}=    get slice from list    @{list}    0

**Comment by jeroen1602** [comment]
I think your problem is that you use `@{list}` in the last 3 steps instead of `${list}`. If you use `@{list}` then it will pass all the items in the list as separate values, so in this case only `Hello, world!` because there is only one item in the list. But if you use `${list}` you pass the actual list as a parameter, so `[Hello, world!]` in this case.

**Comment by schaefer01** [comment]
thank you, 
  It is weird that @{list} is used to create but ${list} is used everywhere else.

**Comment by jeroen1602** [comment]
It depends what you need I guess.

**Comment by schaefer01** [comment]
I need simplicity, symmetricity, and intuitiveness (that comes from simplicity and symmetricity) in my programming languages. Where are Djikstra's heirs?

**Comment by pekkaklarck** [comment]
When you create a list based on a keyword return value both of these are valid:
