### ISSUE TITLE
Merge libdoc output

### ISSUE THREAD

**Issue by Ka55i0peia** [robotframework/robotframework#3600]
Hey,

_this is more or less a feature request, I guess._

We are faced to the problem that we have spreaded keywords over a (custom python) robot library (providing basic keywords) and keywords in robot resource files (using the basic keywords from the robot library). So this keywords from lib and keywords from resource files belongs conceptional together and thus might be inside **one html** output of libdoc. (Emphasize by: The library is included by the resource file. The test includes the resource file only.)

Libdoc is will create one html/xml per

* Library
* Resource file

Anyway issue https://github.com/robotframework/MavenPlugin/issues/28 looks it has the same or a similar intention. But the fix addresses Maven (java world only).

**I currently have several ideas in mind to fix**

1. Extending `libdoc` doing this job (harvesting several input files into one xml/html. The input parameter allow e.g. a path or some regular expression matching input files rather then one input file.)
2. Extending `rebot` to merge libdoc xml files.
3. Simply writing a small script using libdoc as module or merging the xml outputs into one xml file.

**For 1:**

The idea is to extent the CLI of libdoc, currenlty [supporting two arguments for writing output](https://github.com/robotframework/robotframework/blob/5dc9affd4aee31703a58ad105ed49579b1ca7067/src/robot/libdoc.py#L155) only.

A technical solution can be this way: Extent `class LibdocModelWriter` to support a list of `LibraryDocumentation`, thus [`JsonConverter` constructs a compound/join list of keywords](https://github.com/robotframework/robotframework/blob/5dc9affd4aee31703a58ad105ed49579b1ca7067/src/robot/libdocpkg/htmlwriter.py#L40) (and joined list of doc summary) from every resource specfied in CLI _within one json object_.

**For 2:**

I thought maybe rebot can do that. It has [`--merge`](https://github.com/robotframework/robotframework/blob/5dc9affd4aee31703a58ad105ed49579b1ca7067/src/robot/rebot.py#L88)  parameter. From scratch that jobs end up with a message like:  

```
rebot --merge docs/MyLib.xml docs/resources/mylibsresource1.resource.xml --outputfile docs/MyLibFramework.xml

[ERROR ] Reading XML source 'docs/MyLib.xml' failed: Incompatible XML element 'keywordspec'.
```

So its not desigend for libdoc xml's. 

Idea to to fix: [more handlers](https://github.com/robotframework/robotframework/blob/master/src/robot/result/xmlelementhandlers.py) needs to be implemented.

**For 3**

Looks like [this post](https://github.com/robotframework/MavenPlugin/issues/28#issuecomment-304668150) had the similar idea ;) 

What do you think about this plans? Does one maybe overlaps with some roadmap? Is one preferred over the other (especially 1 vs 2)?

**Comment by pekkaklarck** [comment]
I agree it would be convenient to be able to create a combined Libdoc outputs (both XML and HTML). Comments about the proposed solutions below:

1. Enhancing Libdoc itself is fine as long as changes aren't overly complicated.

2. Rebot isn't the right tool for this job.

3. External tool would be the most flexible solution. I got a feeling there would be a lot of different features that such a tool could have, and there would be lot of benefits of implementing it externally. It would, for example, allow experimenting without strict backwards compatibility requirements RF itself has and would allow development and releases independently from RF release schedule. In this scenario Libdoc's APIs could naturally be enhanced to make it easier to implement such tooling.

**Comment by Ka55i0peia** [comment]
Thanks @pekkaklarck !

I completely agree with you (since this issue is now some days open and I had time for further investigation).

1. I've started with point 1, but finally stopped work here, because libdoc's output(s) especially the `*.libspec` format and the `*.xml` have a taste of beeing designed for one resource file. (Recent changes in RF3.2).
_In the root tag `<keywordspec>` we now have attributes `source` and `lineno`, that smells very much for a good prework to go further towards a linter support (like https://github.com/tomi/vscode-rf-language-server/issues/48) :)_
Thus this solution would require more changes in libdoc and probably makes things more complicated then expected in the first view (schema changes, ... ?).

2. Good that I don't tried this ;)

3. With point 3 I stopped for similar reason as point 1 + the following reason: The root tag `<keywordspec>` contains an attribute like `format` (which is a hint for the used markdown/markup language) and keeps the markdown as is in `<doc>` tag. Once we join/merge libdoc outputs of a python kw library (`format="REST"`) and some robot resource files (`format="ROBOT"`) we need to also implemented/reuse some markup language parser to overcome this. No impossible but my teams schedule does not loved this >_<

**As a result I can highly recommend this project: https://github.com/boakley/robotframework-hub which we then integrated to solve the request.**

(PS: Since a longer time I am in talk/"bothering" the leads in within my company thus we/me can officially support/bring back changes and new feature to the RF community -- since we benefit from RF as well! See you tomorrow.)

**Comment by pekkaklarck** [comment]
Yeah, Libdoc would need quite big changes to support this properly and thus an external tool is probably the best solution. An existing solution like the mentioned Hub could work well enough out-of-the-box or be enhanced, or possibly a new tool could be created. Whatever the solution, I guess this issue can be closed as we only track issues related to RF core itself here.
