### ISSUE TITLE
Merging results from different suites error

### ISSUE THREAD

**Issue by mosheronen** [robotframework/robotframework#3604]
Hello,

I'm executing robot by test cases: robot --test <test name> --suite <suite name>. Having multiple and different top level suites.
I'm trying to do: rebot --merge to the output.xml files got error:
[ ERROR ] Cannot merge outputs containing different root suites

What I'm doing wrong?
Is there any way to combine all output.xml to one report even if having different suites?

Best Regards,
Moshe

**Comment by pekkaklarck** [comment]
Merge only works if the root suite is same but you can always combine. Just leave `--merge` out from the `rebot` invocation and it ought to work.

Notice that actual support forums like our Slack or email lists are better places to ask questions. If you encounter bugs or have concrete enhancement requests, then this issue tracker is the right place.
