### ISSUE TITLE
Information of keyword is not shown when holding Ctrl on the selected keyword

### ISSUE THREAD

**Issue by LilyNL** [robotframework/robotframework#3605]
Hi,
I am using RIDE 1.7.4.2 running on Python 3.6.8. 
I have a library with extra keywords and write test case in RIDE using those keywords.
In tab Edit, when I select one of those extra keyword, pressing Ctrl, it shows "Keyword was not detected by RIDE". Built-in keywords do not have that issue.
The added keywords are well detected in running and the test case runs well.

I have tried the followings but the problem still occurs. Thank you in advance for your help.

1.
Define PYTHONPATH = C:/Lib, in environment system variable, and also user variable, where c:/Lib contains .py files which define the keywords

2.
Define PYTHONPATH = C:/Lib/file.py, where file.py contains keyword definitions

3.
Define paths in Tools/Preferences/Importing, with value of directory or file as above

4.
Produce xml and libspec using command python -m robot.libdoc and set PYTHONPATH to directory contains these files or pointing directly to one these files

None of these works.

In the past, with older version of RIDE, it works automatically once the library of keywords is set.

**Comment by aaltat** [comment]
This is a Robot Framework core issue tracker, but your issue seems to be related with  RIDE. Instead please raise an issue to https://github.com/robotframework/RIDE/issues

**Comment by pekkaklarck** [comment]
Yeah, RIDE issues belong to RIDE's tracker.
