### ISSUE TITLE
OperatingSystem Run does not put output into variable

### ISSUE THREAD

**Issue by schaefer01** [robotframework/robotframework#3606]
Hi,
  I'm using the lastest robot framework that can be retrieved from pip install on macOS mojave 10/14/6,
  and ride v1.7.4b2

the ping works but the results are not assigned to the ${results} variable

${result} = PING localhost (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.053 ms
64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.093 ms
64 bytes from 127.0.0.1: icmp_seq=2 ttl=64 t...
20200625 08:53:26.656 :  FAIL : Keyword name cannot be empty.

thx
  bob s.

*** Settings ***
Library           OperatingSystem
Library           Process
Library           Dialogs
Library           String

*** Test Cases ***
ping
    ${success}    set variable    64 bytes
    ${ipaddr}=    Get Value From User    input IP address    localhost
    ${result}    set variable    “”
    ${result}=    Run    ping ${ipaddr} -c 5
    ${log}    ${result}
    ${lines}=    Get Lines Containing String    ${result}    ${success}
    ${length}=    Get Length    ${lines}
    Should Be True    ${length}>0

**Comment by pekkaklarck** [comment]
I don't understand the description so please clarify. Also, consider using the Process library instead of OperatingSystem for executing processes.

**Comment by schaefer01** [comment]
The Process library fails for the Run command that returns a value. 
Can you provide me an example that returns a value that works?
If the Run command cannot return a value, then the documentation should show that returning a value is not supported.

The OperatingSystem library for the equivalent function does work, and I switched to this library.

**Comment by pekkaklarck** [comment]
Both `OperatingSystem.Run` and `Process.Run Process` certainly can return the command output and their docs ought to contain relevant examples. You need to explain more thoroughly what you actually try to do, what you expect to happen, and what actually happens. You've wrote you cannot return value but the only failure message I see is "FAIL : Keyword name cannot be empty.".

**Comment by schaefer01** [comment]
I withdraw the issue. I see the problem, my fault. I needed "log", I used "$log"
