### ISSUE TITLE
Listener interface method for writing files is not working

### ISSUE THREAD

**Issue by tlolkema** [robotframework/robotframework#3609]
**1. Version information**
- robotframework==3.2.1
- python 3.7.7
- tested on both Ubuntu 20.04 and Windows 10

**2. Steps to reproduce**

Example.robot

```robotframework
*** Settings ***
Library  LibraryListener.py

*** Test Cases ***
Sample Testcase
    Log To Console   LOG
```

LibraryListener.py

```python
class LibraryListener:

    ROBOT_LIBRARY_SCOPE = 'TEST CASE'
    ROBOT_LISTENER_API_VERSION = 3

    def __init__(self):
        self.ROBOT_LIBRARY_LISTENER = self    

    def _end_suite(self, data, result):
        print('END_SUITE')

    def _report_file(self, path):
        print('REPORT_FILE')
```
Result:

**_end_suite** is working properly, however **_report_file** never gets called.
I'm encountering the same issue with the other write file interface methods (output_file, log_file, report_file)

https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#listener-version-3

**Comment by Snooz82** [comment]
@tlolkema 

This should be normal.
A library listener only lives in the suite where it is imported. The writing of reports is definitely out of execution scope.

Imho you need to use a CLI listener.

`robot --listener Listener.py .`

**Comment by pekkaklarck** [comment]
Yeah, library listeners aren't notified about these events since they aren't anymore alive. This ought to be documented in the User Guide as well.
