### ISSUE TITLE
Screenshots attached to log.html file 

### ISSUE THREAD

**Issue by akozyreva** [robotframework/robotframework#3610]
Hello everyone!
I have a question. 
I use robotframework and it works fine. Every time, when tests finished, standard log.html and screenshots (in the same folder) of failed tests are generated. The point is, that I want screenshots attached automatically to log.html, I don't want to open new screenshot every time and switch again to log.html file. Is there any mechanism for it?

**Comment by pekkaklarck** [comment]
This is something libraries need to handle themselves. They can log messages showing images so that images are on disk or even embed them to log files themselves. Anyway, this is something the core framework doesn't have any control over.
