### ISSUE TITLE
Old FOR loop syntax in the v3.2.1 document description

### ISSUE THREAD

**Issue by yo-ga** [robotframework/robotframework#3615]
In the latest document, there are many examples using the old syntax.

Link:
- http://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Continue%20For%20Loop
- http://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Pass%20Execution%20If
- http://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Return%20From%20Keyword%20If

**Comment by pekkaklarck** [comment]
Thanks for the report! This was already reported as #3596 and ought to now be fixed.
