### ISSUE TITLE
Support validation for more types from `typing`

### ISSUE THREAD

**Issue by xylix** [robotframework/robotframework#3616]
Working on `robotframework-browser` library, I've noticed some missing pieces in the currently supported type conversions in RF.

Depending on the usage profile supporting some of the newer higher order types from `typing` should be quite easily implementable and with good improvements to user experience on validation of keyword argument inputs.

I personally would consider TypedDict and Optional high priority, both because of their relatively high usage in modern typed python and the fact that they should be quite easily implementable. (Optional doesn't actually do anything to the type since robot literal_eval:s most values.) TypedDict is just a Dict with specified permitted keys.

Literal's should be easily supportable, since they can be easily validated. Sometimes they are a much more elegant solution on the developer's side, and they would probably be easier to in-line in type signatures compared to Enum contents.

Union types could be nice to have but probably hard to implement (would need to check if the argument fits into one of the possible types, and make some decisions if there's overlap).

- [ ] Optional
- [ ] TypedDict
- [ ] Literal
- [ ] Union

**Comment by pekkaklarck** [comment]
All this sounds good to me. Should we have separate issues for different types or just have this one for all? Implementation is probably easiest so that one type is handled by one commit or PR.

I'd be fine adding trivial/easy features in RF 3.2.2 in August but anything bigger needs to wait for 3.3 (ater this year.

**Comment by xylix** [comment]
I wouldn't mind either way, whichever is easier to organize. Maybe list them here and create own issues if they require design / other significant discussion. I added a list of the proposed new converted types to the main message.

Waiting for feature release for bigger changes makes sense. In theory some of these could change behaviour of existing RobotFramework libraries if they use these types and currently to the converision from string to any of these types by hand.

**Comment by pekkaklarck** [comment]
This is too broad issue. I submitted #3738 about Union support and separate issues can also be submitted for other types.
