### ISSUE TITLE
[ ERROR ] Suite 'SB IMS NN GUI' contains no tests matching name 'SB IMS NN GUI.GUI_Test' in suite 'SB IMS NN GUI'.

### ISSUE THREAD

**Issue by Kalyan-Nk** [robotframework/robotframework#3617]
Hello,
i am trying to create a small suite and under that two test cases in RoboFramework, hwile trying to Run Test under Suite facing "[ ERROR ] Suite 'SB IMS NN GUI' contains no tests matching name 'SB IMS NN GUI.GUI_Test'".
could some one help me with it.
C:\Users\mkalyani>ride --version
1.7.4.2
Python 3.6.5

 
<img width="953" alt="Test" src="https://user-images.githubusercontent.com/68810989/88478044-b645e500-cf62-11ea-854a-96b6805daea5.PNG">

**Comment by pekkaklarck** [comment]
Can you reproduce the problem without RIDE? If not, then this is a RIDE issue and should be submitted to its issue tracker.

**Comment by Kalyan-Nk** [comment]
Thanks pekkaklarck for your time, I hvae fixed the above problem,
