### ISSUE TITLE
Tidy adds trailing whitespace in multi-paragraph `Documentation`

### ISSUE THREAD

**Issue by pfctdayelise** [robotframework/robotframework#3618]
Using RF 3.2.1 with Python 3.8.1 on Windows 10.

This is a bit ugly, and also upsets robotframework-lint (which I realise is not an "official" tool).

Minimal example .robot file:

```
*** Settings ***
Documentation     Example of
...
...               multi-paragraph documentation.

```

Note the third line has no trailing whitespace.

I ran: `python -m robot.tidy .\tests\features\tidy.robot > .\tests\features\tidy-out.robot`

Output:

```
*** Settings ***
Documentation     Example of
...           
...               multi-paragraph documentation.


```

If you highlight the third line, you will see 11 spaces were added by tidy.

**Comment by pekkaklarck** [comment]
Extra whitespace is added to the line otherwise containing only `...`, right? This is clearly a bug and needs to be fixed in the next release.

**Comment by pfctdayelise** [comment]
Thanks. That's right, I only saw the superfluous whitespace in the `...` line.

**Comment by pekkaklarck** [comment]
My guess is that the extra whitespace is a separator between the continuation marker and the data but in this case there's no data and there shouldn't be that separator either. Ought to be easy to fix. I can take a look at it myself after holidays but if someone else is interested to provide a PR that would be awesome.
