### ISSUE TITLE
getting issue: Caused: java.lang.IllegalArgumentException: Could not instantiate {delegate={$class=RobotPublisher, outputPath=../robotReport, outputFileName=aggregate_output.xml, reportFileName=report.html, logFileName=log.html, disableArchiveOutput=false, passThreshold=100, unstableThreshold=80}} for org.jenkinsci.plugins.workflow.steps.CoreStep

### ISSUE THREAD

**Issue by kkbhatt78** [robotframework/robotframework#3619]
When i ran scripts in jenkins i am getting below errors:

java.lang.UnsupportedOperationException: no known implementation of interface jenkins.tasks.SimpleBuildStep is named RobotPublisher

Caused: java.lang.IllegalArgumentException: Could not instantiate {delegate={$class=RobotPublisher, outputPath=../robotReport, outputFileName=aggregate_output.xml, reportFileName=report.html, logFileName=log.html, disableArchiveOutput=false, passThreshold=100, unstableThreshold=80}} for org.jenkinsci.plugins.workflow.steps.CoreStep

**Comment by pekkaklarck** [comment]
Could you clarify what exactly did you do to get this error? Are you sure the problem is in Robot Framework and not e.g. in its Jenkins Plugin? In the latter case the problem should be reported to that project.
