### ISSUE TITLE
Dictionary variable not accepting the list values which is starting with float or string

### ISSUE THREAD

**Issue by sakthivelsubramani** [robotframework/robotframework#3620]
Finding some difficulty in dictionary variable assignment. Below python code want to convert in robot framework.

Dict = {'t1':[1, 2, 3], 't2':[1.2, 2.8, 5.1, 7.8], "t3":['python', 'RF']}
print(Dict['t3'][0])

But while making in robot framework with following manner,
*** Variables ***
&{Dict}         t1=@{1,2,3}  t2=@{1.2,2.8,5.1,7.8}  t3=@{'python','RF'}

*** Test Cases ***
TestCase1
    log to console  ${Dict.t3[0]}

I don't think any error in above script, but I am getting error with "Variable '&{Dict}' not found". 
The reason for the error, dictionary in RF is not accepting the list which is starting with float or string value (see index 1 & 2 of &{Dict}). 

If the dictionary assignment like below, it is working fine.
&{Dict}         t1=@{1,2,3}  t2=@{1,1.2,2.8,5.1,7.8}  t3=@{8,'python','RF'}

But we need to ignore index 0 in both t2 & t3 value section for further processing.
Please let me know any solution to overcome this issue.

**Comment by pekkaklarck** [comment]
The syntax you use isn't correct. Unfortunately it isn'tthat convenient to create nested lists and dicts nor integers in Robot Framework data, but something like this ought to work:

```robotframework
*** Variables ***
@{t1}       ${1}        ${2}        ${3}
@{t2}       ${1.2}      ${2.8}      ${5.1}    ${7.8}
@{t3}       python      RF
&{DICT}     t1=${t1}    t2=${t2}    t3=${t3}
```

Another solution would be using inline variable evaluation support that was introduced in RF 3.2 (#3179). If you need lot of such variables, using variable files or creating needed variables in libraries would probably work even better.

**Comment by sakthivelsubramani** [comment]
@pekkaklarck Thanks! for the reply.
I do have tried creating separate list and using it inside dictionary and it is working fine for me. But i have moved from single variable assignment to dictionary because in my application i need to use lots of variable and also don't want to create variable file to reduce code complexity. Please suggest if any solution for this issue.
