### ISSUE TITLE
Documentation error in 'Robot Framework User Guide' online manual

### ISSUE THREAD

**Issue by bullsbb** [robotframework/robotframework#3621]
Hi Team,

An error found in [Robot Framework User Guide](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html) online manual.

In section "**Free keyword arguments (\*\*kwargs)**", an example shows how normal arguments, varargs, and kwargs work together. But unfortunately, the 3rd test case `**Kwargs**` is not correct: the keyword "Various Args" expects at least 1  non-named argument but actually got 0 in example. 

![image](https://user-images.githubusercontent.com/67827510/88810411-e225cc80-d1e7-11ea-8b29-fb0fd71f7062.png)

**Comment by pekkaklarck** [comment]
Good catch and thanks for the report! Need to decide what's the best way to fix this. I see two easy solutions:

1. Add a positional argument to `Kwargs` example and change the comment about logging accordingly. Something like:

    ```
    Kwargs
        Various Args    mandatory    a=1    b=2    c=3
        Various Args    mandatory    c=3    a=1    b=2
    ```

    A problem is that then this is pretty much same as the `Positional and kwargs` example.

2. Change the keyword implementation to make `arg` optional:

    ```python
    def various_args(arg=None, *varargs, **kwargs):
        if arg is not None:
            print('arg:', arg)
        # rest of the function like earlier
    ```

    A benefit of this approach is that examples don't need to be touched.
