### ISSUE TITLE
When "run keyword and return if" is used for a keyword taking an Argument, can't use ELSE block

### ISSUE THREAD

**Issue by arnabpandit** [robotframework/robotframework#3623]
below is the snippet. two keywords. 
the first keyword works well without the "ELSE" section.
when I uncomment ELSE line, getting error - "Keyword 'Open A Page And Return Title' expected 1 argument, got 5."

*** Keywords ***
Open ${APP_NAME} and Get Page Title
    run keyword and return if    '${APP_NAME}' == 'Bics CRM'    Open A Page And Return Title    ${CRM_URL}
#    **...         ELSE     log    ${APP_NAME} URL is not yet configured!!!      ERROR**

Open A Page And Return Title
    [Arguments]    ${Any_URL}
    go to   ${Any_URL}
    ${title}=   get title
    log     ${title} page opens      DEBUG
    [Return]    ${title}

**Comment by pekkaklarck** [comment]
`Run Keyword And Return If` simply doesn't support `ELSE` branch, only `Run Keyword If` does. Because we are planning to add native `IF/ELSE` support in the future, I don't think adding `ELSE` to new keywords makes sense.

**Comment by arnabpandit** [comment]
Thanks a lot. Agreed.
