### ISSUE TITLE
Line number reported by test libraries using class decorators is different in Python 3.9 than earlier

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#3628]
RF 3.1 added support for library source and line numbers (#3507). Testing Python 3.9 it seems that there are small differences how libraries using class decorators are handled in this regard. For example, if we have a library like

```python
@example_decorator
class ExampleLibrary:
    ...
```

earlier the line number of the library would be the line containing `class ExampleLibrary` but with Python 3.9 its the line containing `@example_decorator`. My guess is that [inspect.getsourcelines](https://docs.python.org/3/library/inspect.html#inspect.getsourcelines) that we use internally has changed and nowadays it returns also possible class decorators. That's probably a good idea because it has already earlier worked that way with functions and methods.

We have several ways how to handle this change:

1. Try to follow Python 3.9 semantics also with earlier versions. That's pretty much impossible as this information isn't returned by `getsourcelines` earlier and we don't have any other way to find it.

2. Follow old semantics with Python 3.9 and newer. This is pretty easy as we can simply ignore lines containing decorators before the actual `class` statement. We also already do this with decorated keywords so the behavior would be consistent. Consistency is always good.

3. Do nothing and let different Python versions report different line numbers. Probably not a good idea because behavior would be inconsistent both between Python versions and when looking library and keyword line numbers. Would also require having conditional tests.

Option 2 sounds best to me and will be the way this is fixed.

**Comment by pekkaklarck** [comment]
Ping @aaltat. How did PythonLibCore end up handling line numbers of decorated keywords and libraries?

**Comment by aaltat** [comment]
In here https://github.com/robotframework/PythonLibCore/blob/master/src/robotlibcore.py#L148

**Comment by pekkaklarck** [comment]
Same solution as with RF with keywords. Should then probably add same handling for the library itself like RF will do to fix this issue. Very low priority, though.
