### ISSUE TITLE
I have successfully installed RF, but it prompts that RF is not installed when I run the test case

### ISSUE THREAD

**Issue by starmissw** [robotframework/robotframework#3631]
- The environment I installed is  

Ubuntu16.04；python3.7.5；wxPython-4.0.7-post2；robot framework 3.1.2；robot framework-ride1.7.4.2；

- My question ：

In terminal，I run command `python -m robot --version` and get the following result
![image](https://user-images.githubusercontent.com/36070505/89972267-f958c580-dc8f-11ea-8808-be1a8dc33cb8.png)

But when using robot framework-ride, an error will be reported，
![image](https://user-images.githubusercontent.com/36070505/89972414-62d8d400-dc90-11ea-9a4c-e430a921bd0d.png)

![image](https://user-images.githubusercontent.com/36070505/89972570-bb0fd600-dc90-11ea-99ea-01008fdb5564.png)

**Comment by xylix** [comment]
I think the problem is that the script `robot` which works as a shell entry point for robot (and apparently RIDE) could not be found.

If you try `which robot` on the command line can the command be located? If it can not be, something like `~/.local/bin` might contain the robot executable and not be on your PATH. Did you install robot by doing `pip install` or `pip install --user`?

**Comment by starmissw** [comment]
Thank you for your reply.
I try `which robot ` on the command line , the command can not be lacated. And I do not find the robot executable in `~/.local/bin`. 
I install robot by doing` pip install`.
In the terminal, I try the command `python -m robot /home/wd/coding/test/myTest.robot`, it works. 
![image](https://user-images.githubusercontent.com/36070505/90496300-3c2b0980-e178-11ea-8ebb-f46a17abf9e6.png)

But when using ride, the reported errors are the same as before.

**Comment by starmissw** [comment]
I installed  python, robot framework and robot framework-ride in  the `/opt` directory.
Should I install them by doing `pip install --user`  or choose `/home` directionary?

**Comment by pekkaklarck** [comment]
This seems to be a RIDE issue and should be reported to its tracker. It could also be just a configuration issue (you could e.g. have multiple Python installations and have RF installed to one and RIDE to the other) in which case it would be best to ask help on actual support forums such as our Slack or robotframework-users mailing list. These issue trackers are mainly for bug reports and concrete enhancement requests.
