### ISSUE TITLE
Process interactive write/read

### ISSUE THREAD

**Issue by axi92** [robotframework/robotframework#3633]
Is there a way to run a Process and write/read interactive to it, like in the [SSHLibrary](http://robotframework.org/SSHLibrary/SSHLibrary.html#Interactive%20shells)

If not, the only workaround would be to login on the local ssh port and do it with the sshlibrary?...

**Comment by pekkaklarck** [comment]
No, there's no such support. If you have concrete ideas how it should work and could be implemented on top of Python's subprocess, please submit an issue.
