### ISSUE TITLE
Show members of enum argument types in Libdoc HTML

### ISSUE THREAD

**Issue by Snooz82** [robotframework/robotframework#3637]
It would be very nice if libdoc would documents valid enum values of an Enum that is used as a typehint of an keyword argument.

Because Enums can have many members and they can be used in multiple Keywords of one library i would recommend that there will be a new table for DataTypes.
In this table all enums of a library can be listed together with their members and maybe with a link to the keywords which use them.
It would also be nice, if the Enum Type within the arguments section of the keyword table link to the Enum definition.

This Feature will at the moment help most for the Browser library, because this uses a lot of Enums.
Once Enums are even more supported by Robot Framework and also implemented in Libdoc XML and the LSP, i can imagine that more libraries will switch to Enum usage.

**Comment by pekkaklarck** [comment]
I agree showing enum members in Libdoc HTML output is a good idea. I also agree they should be added to Libdoc XML output but we already have #3607 covering that. Let's thus concentrate on HTML here and I'll update the issue title accordingly.

Enhancing libspec files (XML) has backwards compatibility concerns and thus #3607 is targeted for RF 4.0. Enhancing HTML outputs doesn't have such restrictions so at least simple and safe enhancements would be fine already in RF 3.2.2.

**Comment by pekkaklarck** [comment]
After arguments now being split to their own rows (#3639) showing members like `color: Color { RED | GREEN }` (i.e. the code above) works much better than earlier. I'd be fine doing that in RF 3.2.2 and then returning this again in RF 4.0.

**Comment by Snooz82** [comment]
@pekkaklarck could you try your prototype with the current release of Browser?
We do have a lot of enums. Some have four members some 15 or so. but they are typically short.

Would be nice to see how it looks like.
At the moment i would assume that Browser is the only library using enums, but we would like to see them in Libdoc.
So i think the impact to community wouldn't be big except of Browser.

So if it doesn’t look good with Browser, i would say it is not worth the effort.
i can not imagine how it looks like.
Could you upload an example? (best would be Browser library)

But great idea!

**Comment by pekkaklarck** [comment]
Apparently creating docs for Browser requires installing Node and all other dependencies. I don't have time for that but here's a screenshot of how this looks with a dummy example with column width changes discussed in #3639:
![enums](https://user-images.githubusercontent.com/114985/91153545-07173d80-e6c9-11ea-86f5-288e4d393d07.png)

If we can agree this is better than the current situation, I can polish the code and commit it so that you can test it with Browser and then fine-tune as needed.

**Comment by pekkaklarck** [comment]
I committed the change to show enum members in arguments in 162a353030f5b63abf0965f776afac5a80fe7572 and column width changes have been committed as well. Let me @Snooz82 know how the results look with Browser and could something simple still be done before 3.2.2 to make it even better. If results are bad, I can still revert the changes.

**Comment by pekkaklarck** [comment]
Do you @Snooz82 have ideas for simple further enhancements or should we consider this ready for RF 3.2.2? A separate issue can be submitted for other enum enhancements such as automatically adding a section listing all the members.

**Comment by pekkaklarck** [comment]
I guess we can consider the current implementation good enough for RF 3.2.2.
