### ISSUE TITLE
Does it support to show all keyword from the output.xml

### ISSUE THREAD

**Issue by chaooe** [robotframework/robotframework#3641]
When i try to get the keywords from the output.xml files. From the test case level, it will only show the keywords which i used in this cases, but this keywords which i defined on another robot file, and resouce into this test cases file.

python code as below:

`
ret = {}

def parse_robot_test_result(xml_path):

    def walk_testcase(suite):

        for test in suite.tests:

            yield test
        for sub_suite in suite.suites:
            for test in walk_testcase(sub_suite):
                print(test.keywords)
                yield test
    result = ExecutionResult(xml_path)
    for test in walk_testcase(result.suite):
        print(test.keywords)`

**Comment by pekkaklarck** [comment]
Each keyword has a list of child keywords that you'd need to go through as well. Creating a visitor would make that easier:
https://robot-framework.readthedocs.io/en/latest/autodoc/robot.model.html#module-robot.model.visitor

If you have further questions, please ask then on robotframework-users mailing list, on our Slack, or on other such support forums. This issue tracker is for bug reports and enhancement requests.
