### ISSUE TITLE
XML: Setup element with text none doesn't work

### ISSUE THREAD

**Issue by Kaflak** [robotframework/robotframework#3649]
We need to setup some parameters in XML as none. As we tested it is not possible as none text is evaluated to None. 

Example code:
```
*** Settings ***
Library    XML
Force Tags    test

*** Test Cases ***

Test
    [Documentation]    _
    ...    Test

    ${none_text}    BuiltIn.Convert To String    none
    ${example}    XML.Parse Xml    /usr/tmp/example.xml
    ${text}    XML.Get Element Text    ${example}    xpath=text
    BuiltIn.Log    ${text}
    XML.Set Elements Text    ${example}    text=${none_text}    xpath=text
    ${text}    XML.Get Element Text    ${example}    xpath=text
    BuiltIn.Log    ${text}
    BuiltIn.Should Be Equal    ${text}    ${none_text}
```

```
cat /usr/tmp/example.xml
<?xml version='1.0' encoding='UTF-8'?>
<example>
  <text>Example text should be changed to none</text>
</example>
```

Is there any way to setup text to none in xml ?

**Comment by pekkaklarck** [comment]
Interesting bug. A bit simpler way to reproduce it here:

```robotframework
*** Settings ***
Library     XML

*** Test Cases ***
Example
    ${x} =    Parse XML    <x>text</x>
    Set Element Text    ${x}    none
    Element Text Should Be    ${x}    none    
```


This is why the bug occurs:
- `Set Element Text` keyword has arguments `text` and `tail` that both have default value `None`.
- Robot's automatic type conversion (new in RF 3.1) automatically converts string `NONE` (case-insensitively)` to `None` if an argument has default value `None`.
- `Set Element Text` doesn't set `text` or `tail` if the value is `None`.

This is easy to fix. Two alternatives:
- Configure `Set Element Text`to not use automatic conversion. Decorating it with `@keyword(types=None)` ought to be enough.
- Change the default value of `text` and `tail` to some unique sentinel value to avoid using `None`.

Good news is that there's a pretty simple workaround to assign the `text` attribute directly:

 ```robotframework
*** Settings ***
Library     XML

*** Test Cases ***
Example
    ${x} =    Parse XML    <x>text</x>
    ${x.text} =    Set Variable    none
    Element Text Should Be    ${x}    none    
```

**Comment by pekkaklarck** [comment]
The exact same bug affects also the highly related `Set Elements Text` and to some extend also `Get Element Attribute`. Should also look are keywords in other libraries affected.

**Comment by pekkaklarck** [comment]
Keywords from other libraries that are affected listed below. Luckily none of those seem to be too serious but worth fixing anyway.

- `get_variable_value` (BuiltIn)
- `get_environment_variable` (OperatingSystem)
- `convert_to_title_case` (String)
- `split_string`(String)
- `split_string_from_right` (String)
- `strip_string` (String)
