### ISSUE TITLE
Support embedded python code with a new *** Python *** table

### ISSUE THREAD

**Issue by Nickheythatsme** [robotframework/robotframework#3650]
## Description
There are several different types of [tables](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#test-data-sections) in robotframework, each offers unique functionality. 

Robotframework also has several ways of extending functionality with python or java code, however each of these require creating a new file and individually importing that file as a library. Sometimes what's needed is only one keyword to be implemented in python, due to complex logic, branching, or iterating. Each of these operations is verbose and difficult to read in robotframework. Existing methods of extending robotframework can be cumbersome and overkill when the user only needs to implement 1-3 keywords in python.

In addition, when calling a python method from robotframework, it is sometimes difficult to find that method, as it exists in a different file and may use a different case style (`snake_case`, ex: "my_keyword", vs `regular case`, ex: "My Keyword"). It would be useful to be able to embed the python keyword in the robot file from which it is called, so that the user can easily locate and reference the python implementation of the keyword.

## Example

Here is an example, where the site being tested has an experiment on the login page. Branching in robotframework is verbose and hard to read, so it makes sense to implement this keyword in python.

```robotframework
*** Settings ***
Resource    ../common.robot

*** Python ***
def sign_in(username, password):
    driver = BuiltIn().get_library_instance('SeleniumLibrary').driver
    is_treatment = BuiltIn().run_keyword_and_return_status('Page Should Contain Element', 'id:NewLogIn')
    if is_treatment:
        return BuiltIn().run_keyword('Sign In Experiment', username, password)
    return BuiltIn().run_keyword('Sign In No Experiment', username, password)

*** Test Cases ***
My Test Case
    Given I am Signed in
    Then a link to the the profile page is present
```

**Comment by Nickheythatsme** [comment]
I would be happy to create a demonstration of this functionality if you think it has any potential!

**Comment by pekkaklarck** [comment]
I can see having both the test and the related Python code would have some benefits, but there would also be lot of problems. The biggest problem is that test case files should in general be easy to read and including larger junks of Python code would have a negative effect. The code could be moved to a resource file, but then it can as easily be moved to a normal library. Unless editors are enhanced, you'd also lose all editor support in Python code. I'm also afraid really supporting all Python features such as imports would be really hard.

I can see that sometimes creating a new keyword in an external file can be an overkill, but we already have the `Evaluate` keyword for running small Python snippets. The problem with finding keyword implementation when it can be used like `My keyword` but defined like `my_keyword` is also real, but this is something where better editor support helps. The newish LSP project already looks really promising in that regard: https://github.com/robocorp/robotframework-lsp

In my opinion there are too many problems and too few benefits that adding this functionality would be a good idea.

**Comment by Nickheythatsme** [comment]
Thanks for the response, makes sense to me!
