### ISSUE TITLE
String: `Should Be Tittle Case` is not consistent with `Convert To Title Case`

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#3651]
`Convert To Title Case` was added in RF 3.2 (#2706). Unfortunately its not fully compatible with the old `Should Be Title Case` keyword. For example, the second test below fails with `'This Is Not OK!' is not titlecase.`:

```robotframework
*** Settings ***
Library        String

*** Test Cases ***
Passes
    ${title} =    Convert To Title Case    This is ok.
    Should Be Title Case    ${title}

Fails
    ${title} =    Convert To Title Case    This is not OK!
    Should Be Title Case    ${title}
```

The reason for the failure is that `Should Be Title Case` simply uses Python's [str.istitle()](https://docs.python.org/3/library/stdtypes.html#str.istitle) function while `Convert To Title Case` uses a lot more sophisticated and configurable algorithm. Most importantly, `Convert To Title Case` leaves words like `XML`, `OK` or `iPhone` as-is and but `str.istitle()` doesn't consider them to be in title case.

The best way to fix this is probably changing `Should Be Title Case` so that it it uses `Convert To Title Case` internally and compares the result with the original value. Because `Convert To Title Case` allows configuration, `Should Be Title Case` probably should too.

**Comment by pekkaklarck** [comment]
Should also rename functions implementing `Should Be Title/Lower/Upper Case` keywords to use style `should_be_title_case` instead of `should_be_titlecase`. We did that with conversion keywords in RF 3.2 (#3484) and for consistency reason it should be done also with these validation keywords. Not sure does that require a separate issue or could it be done as part of this issue.

**Comment by pekkaklarck** [comment]
This is a backwards incompatible change as the behavior of the keyword will change. We could avoid that my using the old behavior by default and switching to the new functionality only if some optional argument is given. I don't think that's worth the effort and being incompatible with `Convert To Title Case` by default would anyway be bad.

**Comment by mikesmith** [comment]
Hi @pekkaklarck! If no one has already taken this, would it be OK if I take it on?

**Comment by pekkaklarck** [comment]
Go aheead @mikesmith! There was PR #3684 but it had some problems and it was never finished.

**Comment by mikesmith** [comment]
Thanks @pekkaklarck! And, thanks for pointing me towards PR #3684. I didn't realize there was a PR already.

I took a look at the PR and the comments. I was thinking along the same lines but I wanted to check if you had anything specific in mind for handling bytes related to your comment:

> ...we perhaps should also think what's the best way to handle bytes.

Is there a better way to handle the bytes? Should we also be handling bytes in the `exclude` parameter?
