### ISSUE TITLE
How to run selected test cases for specific times

### ISSUE THREAD

**Issue by DanielTian90** [robotframework/robotframework#3654]
I want to execute some of test cases for specific times, how to do that?
Is there any easier way to do that? Like command line, etc.

**Comment by pekkaklarck** [comment]
This is something that external tools must handle. Depending on your actual use case you can, for example,create custom script, use a CI system or utilize Pabot. Notice also that questions should be sent to Slack, email list, or other such support forums listed at robotframework.org. This issue tracker is for bug reports and enhancement requests.
