### ISSUE TITLE
pybot is not recognized as an internal or external command

### ISSUE THREAD

**Issue by ingriddbritok3** [robotframework/robotframework#3657]
I have installed on my machine
Python 2.7.17
pip 19.2.3

I set the environment variables
C:\Python27\
C:\Python27\Scripts

When I run pybot --version I get: "'pybot' is not recognized as an internal or external command,
operable program or batch file."

Any help is really appreciated.

**Comment by pekkaklarck** [comment]
`pybot` has been removed already in 3.1. See #2818 and #2216.
