### ISSUE TITLE
Run process hangs on large outputs

### ISSUE THREAD

**Issue by anton264** [robotframework/robotframework#3661]
RF-version 3.2
When doing "Run process" keyword that produces a large amount of output the keyword will hang.
This seems to be related to this issue in python 
https://stackoverflow.com/questions/39477003/python-subprocess-popen-hanging
This used to work in rf 3.1

There is a workaround to the issue:
`Run process     myVeryLargeOutputCommand    stdout=False    stderr=False`

**Comment by pekkaklarck** [comment]
Quick comments:
- Process library documentation explains that `Run Process` can hang if there's lot of output and the output is not redirected to a file.
- Redirecting is done using `stdout` and `stderr` arguments but I don't understand why you set them to `False`.
- Are you certain this worked with RF 3.1? I don't remember any changes that ought to be able to affect this.

**Comment by anton264** [comment]
Setting `stdout` and `stderr` to False only writes it to a file so I guess it's a bit weird to do this.

We have been running the same tests for a very long time (years) and never had a problem with `run process` before but I guess the fault is on my side for not reading the documentation. It was however after we upgraded that we started to see problems with this keyword. It might be related to other libraries though and not robots fault, hard to say.

**Comment by pekkaklarck** [comment]
Any new information related to this? Can you confirm the exact same tests works in exact same environment with RF 3.1 but not with 3.2? Can you provide a simple example I could run locally to reproduce and debug the issue?

**Comment by csphoenix1** [comment]
Hi, I have the same problem if I do a `cat /tmp/foo` with foo as a text file wich contain a `dpkg -l` stdout command (ie. 2000 lines).

I code a workaround bellow. What do you think about it?

[modified_file_with_workaround.txt](https://github.com/robotframework/robotframework/files/7649807/modified_file_with_workaround.txt)
[original_file_with_problem.txt](https://github.com/robotframework/robotframework/files/7649808/original_file_with_problem.txt)
.

**Comment by pekkaklarck** [comment]
Could you @csphoenix1 clarify your problem? How did you use `Run Process`?

Could you also make your proposed changes available so that it would be easier to see them? If you there aren't much changes, you could just include them into a comment here with formatting. If there are more changes, you could create a branch with changes. It could then later be turned into a pull request if needed.

**Comment by bhorkarg** [comment]
Can confirm that this happens with Robot Framework 4.1.2 (Python 3.8.10 on linux). We gather Kubernetes pod logs using the following keyword.

`${result} =    Run Process    kubectl logs pod-name -c container    shell=yes`

When the resulting stdout is huge, the `Run Process` keyword hangs.

**Comment by csphoenix1** [comment]
Hello,

Sorry for my late.

I've just sent a pull request (https://github.com/robotframework/robotframework/pull/4205).

Inside it, there is my solution (hope it will be accepted), and the description of my test.

**Comment by KyleTheScientist** [comment]
I can confirm that `run_process` still hangs in `robotframework==5.0` when the output size is greater than 4096 characters.

You can replicate this easily with the following script (on Windows)
```python
from robot.libraries.Process import Process


path = "beeg_boy.txt"
# Write 4096 bytes to the file
with open(path, 'w') as file:
    file.write("*" * 4096)
# Run process to print the file contents
response = Process().run_process("type {}".format(path), shell=True)
print("Run process didn't hang when the output length was 4096")

# Write 4097 bytes to the file
with open(path, 'w') as file:
    file.write("*" * 4097)
# Run process to print the file contents
response = Process().run_process("type {}".format(path), shell=True)
print("This message will never be printed because the process will become unresponsive.")
```

If it's possible to get a fix for this, it would save my team a lot of head scratching in the future.

**Comment by pekkaklarck** [comment]
Nobody jas come up with a proper fix and to be honest I'm afraid such a fix would be rather complicated. Luckily you can easily redirect outputs to a file, or DEVNULL, by using the `stdout/err` arguments and avoid the problem.

**Comment by pekkaklarck** [comment]
This issue was about a possible regression in RF 3.2 compared to 3.1. Nobody was able to provide an example of that would work woth the latter but not the former, so I close this issue.
