### ISSUE TITLE
Execution side refactoring on v4.0

### ISSUE THREAD

**Issue by mkorpela** [robotframework/robotframework#3668]
Many issues reference execution side refactoring needs in version 4.0.
At least https://github.com/robotframework/robotframework/issues/3296 , https://github.com/robotframework/robotframework/issues/3074 ,
https://github.com/robotframework/robotframework/issues/3538

This refactoring will cover at least the following:

1. Keyword does not currently have an easy way to reference test that it is being executed in and it should.
2. Global EXECUTION_CONTEXTS should be removed and replaced with non global passed on contexts that better support parallel execution.

**Comment by pekkaklarck** [comment]
Issue #3749 covers these changes.
