### ISSUE TITLE
Libdoc localizations

### ISSUE THREAD

**Issue by mkorpela** [robotframework/robotframework#3676]
One of the key features of Robot Framework is good accessibility.
We have many users accross the globe. Most of them (including my self) are not native english speakers.
To make Robot Framework more accessible we should support multiple languages in library documentation. This would allow a much larger audience to understans what keywords do.

**Comment by mkorpela** [comment]
Questions:
Ux: How should this be in code comments?
Tech: How should it be stored in libdoc outputs?
Ux: How should language choice be shown in libdoc.html.

**Comment by pekkaklarck** [comment]
Better l10n would be great but I think we should look at RF in general and not only Libdoc.

**Comment by mardukbp** [comment]
RF 6 already supports localization. However, the headings in the documentation generated by libdoc are still in English. That is, libdoc is missing a --language parameter.

**Comment by pekkaklarck** [comment]
RF 6 started the localization efforts but there's lot of work still. Localizing Libdoc's HTML output would be a good step forward, but there's a problem that we are planning to rewrite them altogether (#4304) and as the result most of the current texts are likely to change. The work to enhance the current outputs to support localization would also be mostly wasted when they'd be replaced soonish anyway.

I believe it's best to wait until we have the new Libdoc tech (#4304) in place before we add localization support. It is, however, very important to take localization into account when deciding about the new tech and taking it into use.

**Comment by yanne** [comment]
This is now done.

**Comment by yanne** [comment]
Portuguese translations provided by @HelioGuilherme66 , French by @hassineabd, and Dutch by @leeuwe and @JFoederer. 

Thanks for your contributions!
