### ISSUE TITLE
`xmlschema` is missing in requirements-build.txt

### ISSUE THREAD

**Issue by Snooz82** [robotframework/robotframework#3677]
Hi Peke,

xmlschema is missing in the requirements.
So all libdoc atests fail.

Cheers

**Comment by mkorpela** [comment]
https://github.com/robotframework/robotframework/blob/master/atest/requirements-run.txt

**Comment by Snooz82** [comment]
🤦🏻‍♂️ Too much different requirements.txt...
Sorry

**Comment by mkorpela** [comment]
I know
