### ISSUE TITLE
Expose special exceptions via `robot.api`

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#3685]
By default exceptions raised by library keywords stop executing the current test (except for possible teardown) and move execution to the next test. We have, however, some special exceptions that change this logic:

- Continuable failures allow execution to continue. The test will be marked failed in the end anyway.
- Fatal errors stop the whole test execution.
- Skip marks the test skipped, not failed. This is currently under development as #3647.

The way users can mark exceptions continuable or fatal is by adding special attribute `ROBOT_CONTINUE_ON_FAILURE`  or `ROBOT_EXIT_ON_FAILURE`, respectively, and the plan is to support the same approach with skip as well. There have been two reasons for using special attributes instead of exposing custom exceptions via the `robot.api` module:

- Attributes work also with Java based exceptions when using Jython.
- We wanted it to be possible to write library code without needing to have a dependency to the `robot` module.

Both of the above reasons are still valid, but it would nevertheless often be useful to be able to import custom exceptions directly without a need to create them. I propose the following:

- Create custom exceptions for continuable failures, fatal errors and skip.
- Expose them via the `robot.api` module.
- Internally keep using the special attributes for detecting these special exceptions. This means that all old code will continue to work.

**Comment by pekkaklarck** [comment]
The hardest part of implementing this issue is, as it often is, naming:

1. Where exactly to put these exceptions? Should they go directly to `robot.api` or possibly a submodule like `robot.api.error`? Most of the API is exposed directly via `robot.api` (most of the stuff is implemented elsewhere) but we also have `robot.api.logger` and `robot.api.deco`. I consider these somewhat special cases and believe it would be best to put exceptions directly to `robot.api`.

2. What exception names to use?

   1. `FatalError` sounds like a good name for fatal errors.

   2. Continuable failure could be simply `ContinuableFailure` but we could also consider something like `SoftFailure` to use terminology other tools (at least TestNG) uses. This terminology change would require updating the User Guide and would require its own issue.

    3. Skipping could be implemented with with `SkipExecution` or just `Skip`.

   Regardless the names we decide to use, I believe all exceptions should use another special attribute `ROBOT_SUPPRESS_NAME` to avoid showing the actual exception name in the final error message.

 the exception names and where they are exposed.

**Comment by aaltat** [comment]
I vote for `ContinuableFailure`

**Comment by pekkaklarck** [comment]
Other things to consider:

1. If we add and expose exceptions for special cases, should we also add and expose keywords for normal failures? We could add `Failure` that extends `AssertionError` to match `ContinuableFailure` (or `SoftFailure`) and `FatalError` (or `FatalFailure`).

2. If we add `Failure` to be used with normal failing validations, should we also add `Error` to be used with invalid usages and other non-validation related failures? Robot doesn't separate failures and errors but on library level there's a semantic difference.

3. Should we expose existing `PassExecution`? It's used by the `Pass Execution` keyword and can mark the test passed without executing it fully. The idea has been that libraries shouldn't be allowed to do that, but they can already now import this exception from `robot.errors` which _is not_ considered to be part of the public API and this functionality isn't documented either. I don't see any harm with this but I'm not sure is this worth the effort either.

4. Should we expose existing `ContinueForLoop`, `ExitForLoop` and `ReturnFromKeyword`? I think that's not a good idea as these exceptions are used for internal communication related to Robot syntax.

**Comment by pekkaklarck** [comment]
The more I think about it, the more I like the term "soft failure" over "continuable failure". I submitted #3692 about changing the terminology with an idea to do that already in RF 4.0. If there are objections, the decision can still be reverted.

**Comment by pekkaklarck** [comment]
These exceptions were created in 02bf41434dac155acc7d1fd1ad1695c81d2cfed8:

- Failure
- ContinuableFailure
- Error
- FatalError
- SkipExecution

Failure and Error are basically aliases for AssertionError and RuntimeError, respectively, but they also act as base classes for ContinuableFailure and FatalError.

Decided to use ContinuableFailure, not SoftFailure, because there weren't that much interest towards renaming the terminology (#3692). ContinuableFailure also better explains how the exception behaves.

These exceptions are implemented in new `robot.api.exceptions` module but they are also exposed directly via the `robot.api` package.

**Comment by adiralashiva8** [comment]
Need html message format support while raising exceptions

Example:
```
 from robot.api import SkipExecution
 
 def skip_execution():
     raise SkipExecution('<b>Skipped from execution</b>', html=True)
```
Current implementation doesn't support this.

**Comment by pekkaklarck** [comment]
@adiralashiva8 You ought to be able to prefix the message with `*HTML*` like `*HTML* <b>Skipped from execution</b>` like you can with all error messages. I like the idea to add a separate `html` argument, though. If you submit an issue about it, we could add it in the future.

**Comment by pekkaklarck** [comment]
#3866 was submitted about supporting HTML messages. I think that's a good idea and it's so easy to implement that I'll do that still be fore RF 4.0.

**Comment by pekkaklarck** [comment]
HTML support was added by the commit above. A functional change caused by this change is that these exceptions now require a message. That means, for example, that

    raise SkipExecution

doesn't work anymore and you need to use

    raise SkipExecution('Some message')

instead. I consider that good but if someone has use cases for raising these exceptions without a message changing this can be still changed.
