### ISSUE TITLE
Libdoc html UX responsive improvements.

### ISSUE THREAD

**Issue by mkorpela** [robotframework/robotframework#3687]
To better support modern browsers and mobile devices as a keyword documentation viewing tool, libdoc html documentation is now split to overview and details parts. This all should result in a documentation that is more available and easy to use to people using different devices.

Main goals in this work have been:

- Improved mobile UX
- Improved library document navigation
- Improved discoverability for the search and filtering functionalities

The implementation has been tested with Chrome, Firefox and Safari. Also tested with ios and android devices.
Most of the work is with standard modern css. Also the implementation is checked to be compatible with IE11 (meaning that documentation can be viewed and html does not break).

There are some known problems with current browser, but these are not separately handled as they seem to be minor problems (only some IE11 related cases have special css). For example Webkit (Safari) scroll-margin bug https://bugs.webkit.org/show_bug.cgi?id=179379 will mean that scrolling on Safari will currently behave a bit worse than with Chrome and Firefox. I believe it is better to follow the official CSS standard and let browsers evolve to support those as libdoc should work for a long time.

**Comment by pekkaklarck** [comment]
This issue is already done, right? Could you @mkorpela explain the changes that were done briefly? Linking to examples might be enough as well. If you consider this done, please close this. I include this in the alpha 1 release notes anyway.

**Comment by pekkaklarck** [comment]
I removed the backwards incompatibility label as this is a UI change (for better) and shouldn't affect external tools. Tools interested to parse library information should anyway use Libdoc specs.

**Comment by mkorpela** [comment]
Changes done as part of v4.0.

**Comment by mkorpela** [comment]
Responsive Libdoc html:
Improved libdoc generated documentation format to better work on range of screen sizes, from mobile to bigger desktops. Library documentation navigation has also been improved with always available menu with navigation bar with a search and filtering options.
