### ISSUE TITLE
Libdoc: Escape backslashes, spaces, line breaks etc. in default values to make them Robot compatible

### ISSUE THREAD

**Issue by Snooz82** [robotframework/robotframework#3697]
Assuming you have a keyword that has the following default values:
```python
def funnystrings(emp='a\t\tHello', regex=r"^(?!\\s*\\.\\.\\.)", mulspec='Log   This has two ${space}', mulmulspec='c:\\windows\\system32', onlynormal="te  st\nHe'll'o    "):
     pass
```

This is currently written in libdoc.xml like this:
```xml
<arguments>
    <arg>emp=a		&lt;b&gt;Hello&lt;/b&gt;</arg>
    <arg>regex=^(?!\\s*\\.\\.\\.)</arg>
    <arg>mulspec=Log   This has two ${space}</arg>
    <arg>mulmulspec=c:\windows\system32</arg>
    <arg>onlynormal=te  st
He'll'o    </arg>
</arguments>
```

Which would be fine in general. But this leads to the situation that these strings are correct, but not Robot Framework compatible.
If these strings are used in an Editor they are resulting in different functionality then originally expected. Specially the line break...
This is specially an issue because these string are not shown properly in Libdoc html as well. in that case all non printable characters like `\n`, multiple spaces and `\t` are not shown at all.
![image](https://user-images.githubusercontent.com/41592183/95059100-bdbf0280-06f8-11eb-8056-4b9065cb6928.png)

### Proposal

i would propose to fix that by documenting robot compatible strings.
Otherwise all editors, users, and documentation platforms have to fix that separately.

![image](https://user-images.githubusercontent.com/41592183/95060143-28bd0900-06fa-11eb-8a96-14da2a71e16c.png)

So in new Libdoc format it would look like that:
```xml
<arguments repr="emp=a\t\t&lt;b&gt;Hello&lt;/b&gt;, regex=^(?!\\\\s*\\\\.\\\\.\\\\.), mulspec=Log \ \ This has two \${space}, mulmulspec=c:\\windows\\system32, onlynormal=te \ st\nHe'll'o \ \ \ \">
    <arg kind="POSITIONAL_OR_KEYWORD" required="false" string_repr="emp=a\t\t&lt;b&gt;Hello&lt;/b&gt;">
        <name>emp</name>
        <default>a\t\t&lt;b&gt;Hello&lt;/b&gt;</default>
    </arg>
    <arg kind="POSITIONAL_OR_KEYWORD" required="false" string_repr="regex=^(?!\\\\s*\\\\.\\\\.\\\\.)">
        <name>regex</name>
        <default>^(?!\\\\s*\\\\.\\\\.\\\\.)</default>
    </arg>
    <arg kind="POSITIONAL_OR_KEYWORD" required="false" string_repr="mulspec=Log \ \ This has two \${space}">
        <name>mulspec</name>
        <default>Log \ \ This has two \${space}</default>
    </arg>
    <arg kind="POSITIONAL_OR_KEYWORD" required="false" string_repr="mulmulspec=c:\\windows\\system32">
        <name>mulmulspec</name>
        <default>c:\\windows\\system32</default>
    </arg>
    <arg kind="POSITIONAL_OR_KEYWORD" required="false" string_repr="onlynormal=te \ st\nHe'll'o \ \ \ \">
        <name>onlynormal</name>
        <default>te \ st\nHe'll'o \ \ \ \</default>
    </arg>
</arguments>
```

That fix has min 3 dimensions.

- [x] Escaping control characters like \n \t etc.
- [x] Escaping spaces if they are leading, trailing or consecutive.
- [x] Escaping of variable names. This should also be \${varname} because as part of a real default it would't be resolved as well.

**Comment by Snooz82** [comment]
at the moment i would categorize the current situation as Bug.

**Comment by Snooz82** [comment]
can be closed!

This is fixed now for python Libraries. Was right for Resource files.

**Comment by pekkaklarck** [comment]
This is only done with library keywords. User keywords can have e.g. variables in default values and they need to be shown as-is.
