### ISSUE TITLE
Import Variables keyword is not overwriting existing value if executed a second time

### ISSUE THREAD

**Issue by moliveras** [robotframework/robotframework#3700]
robotframework version: 3.2.1
OS: centos7, python 2.7.5

I am keyword "Import Variables" to import a python variable file consisting of several dictionaries.

Test case #1 imports the file and performs some actions

Test case #2  import the same variable file, however the variables are not overwritten, they are what they were at the end of test case #1.

This appears to be the same behavior described in bug #940.  It appears that as was the case in #940 that the Import Variables is only being performed the first time and ignored when it is performed in the second test case.

**Comment by bhirsz** [comment]
I believe it's not the bug but the feature described in the docs (duplicated import will not replace previous value, first value will be used). Similiar issue #3760

**Comment by pekkaklarck** [comment]
This looks like a duplicate of #2970. Can you @moliveras check does the description there match?

**Comment by moliveras** [comment]
@pekkaklarck , yes, it does appear to be a duplicate.

**Comment by pekkaklarck** [comment]
Ok, closing this. Please take a look at the comment I wrote to #2101 about possible workarounds.
