### ISSUE TITLE
If doc_format of a library or libdoc xml is HTML, the shortdoc of Keyword contains all doc

### ISSUE THREAD

**Issue by Snooz82** [robotframework/robotframework#3701]
The `getshortdoc` method only works when the doc is "normal" text.
and line breaks are `\n`.

For HTML docs the first paragraph, which is the shortdoc is within a <p>.

i would propose to get the content of the <p> and removes all <b/>, <i/> and <code/> for better readability.

**Comment by pekkaklarck** [comment]
I believe this issue is real but the description formatting is so messed up that understanding it fully is pretty hard. Also, do you have a concrete example demonstrating the problem?
