### ISSUE TITLE
Support method of failing current keyword/test and continuing in python 

### ISSUE THREAD

**Issue by KotlinIsland** [robotframework/robotframework#3706]
I have a Python function `keyword` described as `A context manager that runs as a Robot keyword` that supports `continue on error`. 
```py
@keyword
def test(): # will show as passed in log
    with keyword("will fail", continue_on_error=True): # will show as failed in log and will fail the test
       BuiltIn().fail("foo")
    logger.info("bar") # will run
```
But the report looks janky because it doesn't make `test` failed and the error needs to be raised in cleanup.

I guess it boils down to: I want a pure python implementation of "Run Keyword And Continue On Failure" 

Here's a rough implementation of `keyword`:
```py
from contextlib import contextmanager

from robot.libraries.BuiltIn import BuiltIn
from robot.running.statusreporter import StatusReporter

exception_store = None


@contextmanager
def keyword(name, continue_on_error=False):
    """A context manager that runs as a Robot keyword

    continue_on_error: if an error occurs in this keyword, exit and report as failed but continue test
    """
    try:
        with StatusReporter(BuiltIn()._context, Keyword(kwname=name)):
            yield
    except Exception as err:
        if continue_on_error:
            global exception_store
            exception_store = err
            return
        raise err


def cleanup():
    if exception_store:
        raise exception_store
```

**Comment by KotlinIsland** [comment]
```py
def test():
    BuiltIn().run_keyword_and_continue_on_failure("bar")
    logger.info("foo")  # doesn't run

def bar():
    BuiltIn().fail("bar")
```

**Comment by bhirsz** [comment]
Did you think about using custom exception?
```
class MyCustomError(Exception):
    ROBOT_CONTINUE_ON_FAILURE = True
```

There are also ROBOT_EXIT_ON_FAILURE and ROBOT_SUPPRESS_NAME  attributes - check them out from UserGuide.

**Comment by pekkaklarck** [comment]
First of all, sorry for missing this issue earlier. Could you @KotlinIsland please explain what you try to accomplish? If you want a pure-Python `Run Keyword And Continue On Failure`, why isn't using `BuiltIn.run_keyword_and_continue_on_failure()` enough? Alternatively your libraries could use continuable failures as @bhirsz already mentioned. Starting from RF 4.0 you can simply import `ContinuableFailure` from `robot.api` (#3685).

**Comment by KotlinIsland** [comment]
@pekkaklarck
`Run Keyword And Continue On Failure`  doesn't continue the python function:
```py
rf = BuiltIn()

def keyword1() -> None:
    rf.run_keyword_and_continue_on_failure("bar")
    rf.log("foo")  # doesn't run


def bar() -> None:
    raise ContinuableFailure("hi")
```
![image](https://user-images.githubusercontent.com/65446343/111578129-3e813f00-87ff-11eb-9962-6ae682ec4a0f.png)

# What I want
I want to be able to write:
```py
def keyword1() -> None:
    rf.log("start")
    with keyword("kw1"):
        rf.log("in kw1")
        raise ContinuableFailure("hi")
        rf.log("unreachable")
    rf.log("end")
```
Currently my keyword function produces the following report:
![image](https://user-images.githubusercontent.com/65446343/111578462-e991f880-87ff-11eb-9f14-9e86627c96a8.png)
Issues with this:
- the test passes
- all calling keywords are marked as passed

**Comment by pekkaklarck** [comment]
It's certainly true that in the first example i.e. in

```python
rf = BuiltIn()

def keyword1() -> None:
    rf.run_keyword_and_continue_on_failure("bar")
    rf.log("foo")  # doesn't run
```
the last line won't be run. I don't know what we could do with that nor why you just don't use `try/except` instead.

The second example I don't understand at all.

**Comment by KotlinIsland** [comment]
I can't use `try/except` because then the test would pass, that would involve wrapping everything with boilerplate eg:

```py
rf = BuiltIn()

def keyword1() -> None:
    err = None
    try:
        rf.run_keyword_and_continue_on_failure("bar")
    except e:
        err = e
    rf.log("foo")  # doesn't run
    if err: 
        raise err
```

I want nested keywords within python code where the report looks nice and the python looks nice. I also want to be able to raise assertion errors within those keywords that will fail the keyword, the keyword will exit early, but will not exit anything else, and will make the entire testcase fail.

I want this because it makes the report and code logically structured and look similar.
```py
def foo():
    with keyword("outer"):
        with keyword("inner1"):
            assert 1 == 2
        with keyword("inner2"):
            assert 1 == 2
        rf.log('blah blah")
```
Currently I would have to introduce boilerplate to achieve what I want.

**Comment by pekkaklarck** [comment]
Supporting something like
```python
some_code_that_raises_an_exception()
code_that_nevertheless_continues()

**Comment by KotlinIsland** [comment]
Here is my keyword function:
```py
@contextmanager
def keyword(name: str, continue_on_fail) -> Iterator[None]:
    kw = Keyword()
    kw.name = name
    try:
        with StatusReporter(kw, KeywordResult(kwname=name), rf._context):
            yield
    except Exception as err:
        if not continue_on_fail:
            raise err
```
This is how it's used:
![image](https://user-images.githubusercontent.com/65446343/111717306-85287500-88a3-11eb-9ce5-6322cee4e149.png)


The issue is that I'm not sure how to make `outer`, `Foo`, and the test fail.

So currently what I do is store a variable saying that the test should fail and raise it in cleanup.

**Comment by KotlinIsland** [comment]
```py
def foo() -> None:
    with keyword("outer"):
        with keyword("inner1"):
            raise ContinuableFailure("hi")
        rf.log("inner1 should fail")

        with keyword("inner2"):
            rf.log("this should be passed")
        rf.log("inner2 should pass")

        with keyword("inner3"):
            raise ContinuableFailure("hi")
        rf.log("inner3 should fail")
    rf.log("outer should fail")
    rf.log("foo should fail")
    rf.log("test should fail")
    global status
    if err := status:
        status = None
        raise err


status: Optional[Exception] = None


@contextmanager
def keyword(name: str) -> Iterator[None]:
    global status
    previous_status = status
    kw = Keyword()
    kw.name = name
    try:
        with StatusReporter(kw, KeywordResult(kwname=name), rf._context):
            yield
            if not previous_status and status:
                raise status
    except Exception as err:
        status = err
```

This works correctly and fails the test as I want, the only downside is that I need to put this boilerplate on every function
```py
    global status
    if err := status:
        status = None
        raise err
```

**Comment by KotlinIsland** [comment]
@pekkaklarck So I guess the last piece of what I need is to add a wrapper to every user keyword. Is there a way I can hook the test library import process and wrap all the functions that get imported?

**Comment by KotlinIsland** [comment]
@pekkaklarck I think I've found a way to get the desired outcome, does this look right to you?
```py
from contextlib import contextmanager
from functools import wraps
from typing import Optional, Iterator

from robot.libraries.BuiltIn import BuiltIn
from robot.api import ContinuableFailure
from robot.result import Keyword as KeywordResult
from robot.running import Keyword
from robot.running.statusreporter import StatusReporter

rf = BuiltIn()


def foo() -> None:
    with keyword("outer"):
        with keyword("inner1"):
            raise ContinuableFailure("hi")
        rf.log("inner1 should fail")

        with keyword("inner2"):
            rf.log("this should be passed")
        rf.log("inner2 should pass")

        with keyword("inner3"):
            raise ContinuableFailure("hi")
        rf.log("inner3 should fail")
    rf.log("outer should fail")
    rf.log("foo should fail")
    rf.log("test should fail")


status: Optional[Exception] = None


@contextmanager
def keyword(name: str) -> Iterator[None]:
    global status
    previous_status = status
    kw = Keyword()
    kw.name = name
    try:
        with StatusReporter(kw, KeywordResult(kwname=name), rf._context):
            yield
            if not previous_status and status:
                raise status
    except Exception as err:
        status = err


def set_up():
    def wrapper(fn):
        @wraps(fn)
        def inner(*args, **kwargs):
            fn(*args, **kwargs)
            global status
            if err := status:
                status = None
                raise err

        return inner

    for l in rf._namespace.libraries:
            for h in l.handlers._normal.values():
                h._method = wrapper(h._method)
```

**Comment by pekkaklarck** [comment]
I still don't fully understand what you try to accomplish. Based on the above and newer #4038 it seems like you want to run Python code so that you get keywords created in the log file. As I just commented #4038, we could have an API for that purpose but someone needed to design (and implement it).

**Comment by pekkaklarck** [comment]
It seems to me that what this issue originally asks i.e.

> Support method of failing current keyword/test and continuing in python

isn't in out scope. Having an API to create keywords that are shown in the log file would probably be a good idea, though, and a separate issue should be submitted about that. Or did I miss something here?

**Comment by pekkaklarck** [comment]
The underlying feature request seems to be same as proposed in #4252. Closing this one.

**Comment by KotlinIsland** [comment]
> The underlying feature request seems to be same as proposed in #4252. Closing this one.

Unfortunately #4252 is unrelated to the underlying request 😔. I have re-raised this issue as #4276.

**Comment by pekkaklarck** [comment]
This issue proposes adding new context manager that would create nested keywords under a library keyword exactly like #4252 proposes. I thought that was the main point.

**Comment by KotlinIsland** [comment]
No, the `keyword` context manager was just to illustrate the desire to fail current keyword and continue.
