### ISSUE TITLE
Enhanced type conversions

### ISSUE THREAD

**Issue by mkorpela** [robotframework/robotframework#3710]
- Support for Union (and at the same time Optional)
- Support for int and float as input to int, float, datetime and timedelta
- None type support improved: None string is not anymore default converted as Union (and Optional) are now supported.
- Fixed None string with Enum handling

**Comment by mkorpela** [comment]
Related pull request: https://github.com/robotframework/robotframework/pull/3699

**Comment by mkorpela** [comment]
Related to https://github.com/robotframework/robotframework/issues/3616

**Comment by pekkaklarck** [comment]
We now have dedicated issues for topics covered by this issue:
- Union support #3738
- Non-string argument conversion (incl. int and float) #3735
- Stricter None conversion #3729 (fixes also problem with None and enums)
