### ISSUE TITLE
Support dark theme with report and log

### ISSUE THREAD

**Issue by KotlinIsland** [robotframework/robotframework#3725]

**Comment by pekkaklarck** [comment]
Do you have concrete examples how it should look like? Are you interested to help with development?

**Comment by psaikkonen** [comment]
Opened a draft PR regarding this: https://github.com/robotframework/robotframework/pull/4190

**Comment by pekkaklarck** [comment]
PR #4190 seems to be in such a good shape that we'll get dark mode already in RF 7.0. Thanks for contribution @psaikkonen already now and thanks also for @Snooz82 who promised review/finalize the PR.

**Comment by pekkaklarck** [comment]
There has been some style changes related to the theme toggle button, but now this feature is in good enough shape to be considered ready. Styles can still be fine-tuned after the release candidate is out.
