### ISSUE TITLE
For Process lib, use returncode instead of rc

### ISSUE THREAD

**Issue by Spaceless007** [robotframework/robotframework#3741]
In the [Process library](https://robotframework.org/robotframework/latest/libraries/Process.html), it indicates that:
> This library utilizes Python's subprocess module and its Popen class.

If we check the documentation of the [Popen class](https://docs.python.org/3/library/subprocess.html#popen-constructor) inside subprocess Python module, we can check what a Popen object contains. In this case, I'm interested in these:
- Popen.stdout
- Popen.stderr
- Popen.returncode

The thing is, the Process library of Robotframework doesn't expose the same API, which I find confusing. If we check the [Result object](https://robotframework.org/robotframework/latest/libraries/Process.html#Result%20object) returned with the Process lib, we see these:
- rc
- stdout
- stderr

So I was wondering why this library is using `rc` for the return code instead of using the same name as used in the Python Popen library, which is `returncode`.

I find this confusing for two reasons. Firstly, it is confusing because the documentation of the Process library points to the Popen documentation, and if someone tried to search for `rc`, they won't find anything because it actually returns `returncode` and not `rc`.

Secondly, I did a custom library for Robot and I'm also using the `subprocess` Python module to run process with a remote device. When using this custom library, I just return the object that the `subprocess` object returns me, which contains `returncode`. So it becomes confusing when I use `Run Process` from the robotframework library and my custom `Execute Command` because `Run Process` will return `rc` and  `Execute Command` will return `returncode`. 

**I know this will be a breaking change, but I really do think that it is a great enhancement.**

**Comment by pekkaklarck** [comment]
The Process library uses it's custom result object which doesn't even try to be compatible with `Popen` and it using `rc` is also documented explicitly. I can see that using `Popen` compatible `returncode` instead of `rc` would have same benefits, but for the backwards incompatibility reasons renaming is not possible. I don't have anything against adding `returncode` as an alias for the `rc` as a read-only property, though. If you consider that important, please provide a pull request with updated code, tests and docs.

**Comment by Spaceless007** [comment]
All right thank you for your response! I agree with your proposal, and if I have the time, a pull request will be done.

**Comment by pekkaklarck** [comment]
This would be an easy enhancement. Adding the property is trivial, adding new test is easy, and it only needs to be documented in the table explaining result object attributes. The hardest part is probably figuring out how our test system works but that's explained here:
https://github.com/robotframework/robotframework/blob/master/atest/README.rst
