### ISSUE TITLE
Enhancement: Allow using of test variables in suite setup

### ISSUE THREAD

**Issue by anton264** [robotframework/robotframework#3742]
Sometimes I have set up keywords for test setup in one suite which work well. 

Upon creating a new test suite I realize that this keyword would work very well but instead in the suite setup. This does not work however because I used the "set test variable" keyword in the setup which will be denied in the suite setup stage. I cannot change it to "set suite variable" since that would break my earlier suites. This forces me to duplicate the code and only changing one line.

I propose that the keyword "set test variable" would be allowed in suite setup and only be reachable within the suite setup stage.

**Comment by pekkaklarck** [comment]
Set Suite Variable affects only the current suite so it cannot earlier or forthcoming suites.

**Comment by anton264** [comment]
I'm not sure I understand your reply @pekkaklarck 
Are you saying it wont be possible to implement this functionality?

**Comment by pekkaklarck** [comment]
It means I see no point adding this functionality. Could you please explain your use case a bit more? Why cannot you use Set Suite Variable? How'd you like Set Test Variable to work in this context?
