### ISSUE TITLE
Libdoc: Support argument types with multiple possible values

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#3748]
RF 4.0 alpha 2 added support for argument conversion based on multiple types (#3738) and Libodc should support that as well both in specs and in HTML. In specs it's probably best to store info for each possible type separately (i.e. instead of having just `<type>int</type>` make it valid to have `<type>int</type><type>float</type>`) and in HTML it might be a good idea to use something like `<int> or <float>` as the type info.

When getting argument info from Robot, Libdoc should support both unions and tuples (i.e. `Union[int, float]` and `(int, float)`) like the execution side does.. We need to decide should we normalize this information already at the execution side or should Libdoc just handle both cases. When reading specs and recreating models, Libdoc can read multiple types into a tuple.

**Comment by mkorpela** [comment]
Union support has been added.
