### ISSUE TITLE
Refactor execution and result side model objects

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#3749]
The `TestSuite` structures we use on the execution and result sides (`robot.running.model` and `robot.result.model`, respectively, with a common base classes in `robot.model`) have certain things that need to be changed:

- [x] Remove `keywords` and `messages` from execution side `Keyword` objects. These keywords never actually have child keywords or messages, they just represent the keyword call with the keyword name and arguments. Basically this means moving the related code from the common base class to the result side model objects.

- [x] `TestSuite` objects should not have `keywords` attribute but instead should have `setup` and `teardown` directly. Suites having keywords is odd in general and being able to use e.g. `suite.setup` instead of `suite.keywords.setup` is convenient.

- [x] `keywords` attribute used by `TestCase`, `For`, `If` (new in RF 4.0) and `UserKeyword` objects should be renamed to `body`. The body can contain FOR loops and soon also IF/ELSE in addition to keywords so `body` is a much better name than `keywords` and that's also the term parsing side model uses. The forthcoming `IfElse` objects should naturally have `body`, not `keywords`, as well.

- [x] Add `setup` and `teadown` directly to `TestCase` and `UserKeyword` objects. Accessing `test.setup` is more convenient than the current `test.keywords.setup` and `test.body.setup` would be just wrong.

- [x] Make `setup` and `teardown` objects, not `None`, also when they are not defined. This makes it easier for external code like pre-run modifiers to modify them. Their initial truth value should be false to make it possible to use code like `if test.setup:`.

This kind of changes are naturally backwards incompatible but in my opinion better model is worth that. We should, however, preserve `keywords` as a deprecated read-only property that is generated based on `body` and `setup/teardown` when accessed.

----

**[Update on 2021-01-18]**  Everything discussed above has now been done, but doing these changes has uncovered other highly related problems in the model that also need to be changed:

- [x] On the execution side make `For` and `If` independent classes instead of extending `Keyword`. They don't need keyword related attributes like `name` or `args`, but instead they should have context specific attributes like `For.flavor` and `If.condition`. Earlier those context specific attributes were implemented as properties but they should be normal attributes. Old keyword specific attributes should probably be preserved as deprecated properties for backwards compatibility.

- [x] Add separate `visit/start/end_for` and `visit/start/end_if` methods to the visitor interface. Earlier `For` and `If` were visited using `visit/start/end_keyword` but that doesn't work anymore when they don't extend `Keyword`.

- [x] Add separate `For` and `If` classes on result side. Currently FOR and IF construct are reported as keywords with `type` set accordingly. This makes inspecting FOR/IF hard because their context specific information is not directly available and need to be parsed from keyword attributes. For example, all FOR information is in keyword name in format like `${x} IN [ a | b | c ]`. This change requires some changes to output.xml as well and I added a [separate comment](https://github.com/robotframework/robotframework/issues/3749#issuecomment-762233437) about that.

- [x] On the result side move keywords' messages to `body` to preserve their relative order with keywords and FOR/IF constructs. This makes it easier to preserve their order also in log (2086). The old `messages` attribute should be preserved as a property to make accessing only messages easy.

**Comment by pekkaklarck** [comment]
These changes affect also pre-run modifier examples in the User Guide:
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#example-skip-setups-and-teardowns

Related to those examples, we need an easy way to disable setup/teardown.

**Comment by pekkaklarck** [comment]
Important things to decide:

- Should visitor and listener APIs be changed? They both currently have `start/end_keyword` method which are called also with FOR and IF constructs. Should we add separate `start/end_for` and `start/end_if` methods? If we do, they could call `start/end_keyword` by default to avoid backwards incompatibly problems.

- Should we change `<keywords>` to `<body>` also in output.xml? It would make this change even more backwards incompatible, but output.xml being inconsistent with internal model would also be a smallish problem. If we would decide to change output.xml format, we need to submit a separate issue about it and enhance output.xml also otherwise. For example, attributes currently using values `yes` or `no` should be changed to use `true` or `false` (i.e. `xsd:boolean` type).

**Comment by prescod** [comment]
Relevant to your refactor: 

I'm trying to measure and log the execution time of tests with Setup and Teardown subtracted. I'm having a tough time using the current Listener V3 Results object to do so.

Given this test:

```
Test Perf Measure
    [Teardown]      Sleep   0.5
    [Setup]         Sleep   0.5
    [Tags]  perf
    Log       Noop
```

And this code:

```
    def end_test(self, data, result):
        print(type(result), len(result.keywords))
        print(type(data), len(data.keywords))
```

I get:

```
<class 'robot.result.model.TestCase'> 0
<class 'robot.running.model.TestCase'> 3
```

So the result model thinks I have 0 keywords and the running model thinks I have 3. 

But the running model has no start-time or end-time. So I have not figured out how to get a hold of the elapsed time for the Setup and Teardown in the end_test listener hook.

**Comment by pekkaklarck** [comment]
That problem is due to keyword results being only written to output.xml and not stored in memory during execution. That's not really related to this issue, but we need to do something to that if/when we add `start/end_keyword` methods to the listener v3 (#3296). If you are interested in execution times, it's easiest to read them after execution using result models. If you really need that info during execution, you need to use listener v2.

**Comment by prescod** [comment]
Thank you. I've switched to an XML post-process system.

**Comment by pekkaklarck** [comment]
This issue has turned out to be bigger than originally anticipated. Everything discussed in the original description is now done, but these enhancements have uncovered other highly related problems in the model that also need to be changed. I'll update the description to list these other changes as well.

Had we seen how big change this is, we might have postponed it to future releases. Because we've already done so much, and because changes are really good, I strongly believe we should finish this still before RF 4.0.

**Comment by pekkaklarck** [comment]
The main remaining task is adding `For` and `If` to the result side instead of reporting FOR and IF as keywords. This isn't itself that big a task, but because results are saved to output.xml, and we need to be able to read that info back, we need to think what kind of changes to do there. I see two possibilities:

- Introduce new `<for>` and `<if>` elements that contain FOR/IF related information. I believe this is the best approach in general, but such a big change to output.xml would affect many external tools and I'm not sure is that a good idea anymore in RF 4.0. If we do this, we should also cleanup some other problems in output.xml at the same time.

- Keep using `<kw>` with `type` attribute differentiating FOR/IF from normal keywords and store FOR/IF information into them. We could add new attributes to `<kw>` or add new elements under it, and tools processing output.xml ought to in general just ignore them. Changes would be smaller but output.xml wouldn't directly represent model used internally and there would be some unnecessary cruft. We could do bigger output.xml cleanup in some future release, though.

**Comment by pekkaklarck** [comment]
A decision was made today to add separate `<for>` and `<if>` elements to output.xml. We also decided to cleanup output.xml otherwise a bit and I'll submit a new issue about all that.

**Comment by pekkaklarck** [comment]
Commits above have added separate `<if>` and `<for>` elements to output.xml. Commit dc881131af866d8e0419e5a4721a4afe22e8a3e5 changed IF/ELSE to be stored in output.xml as a nested structure like
```
<if condition='$x > 0' type='if'>
    <if type='else'>
        <kw>...</kw>
        <status status='PASS' branch='PASS'/>
    </if>
    <status status='PASS' branch='NOT_RUN'/>
</if>
```
instead of storing using a sequence like
```
<if condition='$x > 0' type='if'>
    <status status='NOT_RUN'/>
</if>
<if type='else'>
    <kw>...</kw>
    <status status='PASS''/>
</if>
```
This matches the internal model better is consistent with how other such elements are stored. This change requires adding new `branch_status` attribute to the `If` class and `branch` attribute to the `<status>` element used inside `<if>`. The normal `status` is the status of the whole IF/ELSE structure.

**Comment by pekkaklarck** [comment]
After all these changes this issue is about to be ready and ought to be in good enough shape for the long overdue beta 2.It's likely some tuning is still done after the beta.

**Comment by pekkaklarck** [comment]
Things to be still consider include:
- How to store FOR loop variables and values in output.xml? Currently they are stored using `<assign>` and `<arguments>` elements that also keywords use, but using something more FOR related might be a better idea.
- How to store FOR loop iterations in output.xml and also in the result model? Currently the model has `Iteration` class with only `info` attribute and output.xml has `<iter info=''>`. The `info` contains variables and values used in that iteration as a single sting like `${x} = 1` or `${x} = 1, ${y} = 2` if there are multiple variables. It's not possibly to reliable parse such a string, so it might be better to store them as a dictionary in `Iteration` and like `<var name='${x}'>1</var>` in output.xml. That would make `Iteration` and `<iter>` non-generic but that ought to fine.

**Comment by pekkaklarck** [comment]
I'm started to think about representing IF/ELSE in the model and in output.xml. We currently do it so that the model has have a root `If` object with the IF branch in `body` and the next ELSE IF or ELSE branch in `orelse`. ELSE IF and ELSE branches have their own `body` and the next branch in `orelse`. In output.xml these branches are nowadays nested like discussed in the [above commit](https://github.com/robotframework/robotframework/issues/3749#issuecomment-769201691). We use the same design also in the parsing model and that was inspired by how Python itself stores `if/else` structures in its AST.

Another approach would be storing IF/ELSE structures so that we have a root model with `branches` attribute (or possibly `body` that other model objects have) that contains actual IF/ELSE branches. Then in output.xml we could use something like this:
```
<if>
    <if condition='$x > 0' type='if'>
        <status status='NOT_RUN'/>
    </if>
    <if type='else'>
        <kw>...</kw>
        <status status='PASS'/>
    </if>
</if>
```
This approach might feel more natural than the current approach with `orelse` and could also simplify some internal code related to IF/ELSE. There are, however, some problems as well:
- Representing a single IF without ELSE IF or ELSE would require using two objects, the root and the branch object, compared to one.
- In output.xml we'd also need `<if><if type='if'>...</if></if>` instead of just `<if type='if'>...</if>`.
- Extra layer would likely require changes to the visitor interface.
- All changes require more work and it would be great to get RF 4.0 out at some point.

Although this could still be changed, it certainly won't be changed before RF 4.0 beta 2.

**Comment by boakley** [comment]
Having an `<if>` inside an `<if>`, and having `<if>` both represent an "if" and "else" seems very odd. Why not a single tag such as `<block>` or `<compound>` which could be used for all statements that start a block of statements? For example, `<block type='for'>`, `<block type='if'>`, `<block type='else'>`, etc? Then, if robot ever gets a "with" or "while" or "try" statement, we don't have to invent more tags.

**Comment by pekkaklarck** [comment]
A problem with a generic element like `<block>` is that IF and FOR need to store different information. This means that depending on the usage `<block>` would have different attributes and/or child elements. This makes, for example, creating a schema harder.

**Comment by pekkaklarck** [comment]
Some more work to be done still:

- [ ] Change IF/ELSE structure to use `If` object with all its branches in `body` and not the next ELSE IF or ELSE in `orelse`. Also change output.xml accordingly. This was discussed in the [comment above](https://github.com/robotframework/robotframework/issues/3749#issuecomment-771080151).
- [ ] Better type constant names and values.
- [ ] Consistent naming of internal classes, visitor methods, etc.
- [ ] Store FOR loop iteration information in output.xml so that it can be fully recovered.

**Comment by pekkaklarck** [comment]
IF/ELSE model model and type constants were enhanced by the comments linked above. Class, method and attribute names were enhanced in https://github.com/robotframework/robotframework/commit/00c282f2816b01b36689efa3b54baca206a3bf68

**Comment by pekkaklarck** [comment]
Everything listed above now done. Closing this again.

**Comment by pekkaklarck** [comment]
External tools using something like `test.keywords.create()` need to be updated because `keywords` is nowadays only a read-only property and doesn't allow updating. The new way to write that is `test.body.create_keyword()`. This code is compatible both with the old and new model:

```python
if hasattr(tc, 'body'):    # RF >= 4.0
    create_keyword = tc.body.create_keyword
else:    # RF < 4.0
    create_keyword = tc.keywords.create
create_keyword(name=kwname, args=args)
