### ISSUE TITLE
Error with directory name that starts with "U"

### ISSUE THREAD

**Issue by MichielYKamp** [robotframework/robotframework#3754]
We are having some unicode issues since we migrated to Python3.

When I run the following code (this is simplified just to demo the issue):

```
*** Settings ***

*** Test Cases ***
Test Case
    run keyword if  '${EXECDIR}'!='${EMPTY}'
    ...  log to console   execdir is not empty
```

I get the following error:

```
C:\Users\al15487\PycharmProjects>robot TestMK.robot
==============================================================================
TestMK
==============================================================================
Test Case                                                             | FAIL |
Evaluating expression ''C:\Users\al15487\PycharmProjects'!=''' failed: SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (<string>, line 1)
------------------------------------------------------------------------------
TestMK                                                                | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
```

The problem appears to be the "U" in de directory name "Users". If I move this test to a different directory path without a dir that starts with "U" this runs fine.

A workaround to get the above to work is to do the evaluation on a 'raw' string, like so:

```
run keyword if  r'${EXECDIR}'!='${EMPTY}
```

While this is not a complicated fix I believe it shouldn't be necessary to do so if you happen to have a directory name that starts with "U", especially since I am using native Robot Framework code here which supports Python3. I also wonder what other characters in a string evaluation might fail on Python3.

Windows version =Windows 10 1809
Robot Framework version = 3.2.1
Python version = 3.8.2

**Comment by pekkaklarck** [comment]
Run Keyword If uses internally uses the `eval()` function to evaluate Python expressions. 

It seems Python syntax has changed:
