### ISSUE TITLE
exit code 251 with robot --version

### ISSUE THREAD

**Issue by ionutnechita** [robotframework/robotframework#3759]
Hi Robotframework team,

I observe this issue:
python -m robot --version
Robot Framework 3.1.2 (Python 2.7.12 on linux2)
echo $?
251

or 
robot --version
Robot Framework 3.1.2 (Python 2.7.12 on linux2)
echo $?
251

cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

Is normal for this robotframework version; this exit code?

Thanks.

**Comment by xylix** [comment]
https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#return-codes 

It's documented in return-codes section of user guide.

**Comment by ionutnechita** [comment]
I read now user guide, and observer for 251: 251 | Help or version information printed.
So that's predefined.
I was expecting exit code with 0. But I understand now.
It depends on the number of tests passed and failed.


RC | Explanation
-- | --
0 | All critical tests passed.
1-249 | Returned number of critical tests failed.
250 | 250 or more critical failures.
**_251 | Help or version information printed._**
252 | Invalid test data or command line options.
253 | Test execution stopped by user.
255 | Unexpected internal error.

Thank you for help.

This ticket can be closed.
