### ISSUE TITLE
Variables are read from one file while it's used in a keyword defined in a second file

### ISSUE THREAD

**Issue by HafezM** [robotframework/robotframework#3760]
Variables are read from one file while it's used in a keyword defined in a second file.

For example: if you have a file 'x' that has a keyword and that keyword has a variable 'a', and another file 'y' that has the same variable name 'a'. Both of them are imported as resources in test file 'z'. When using the keyword in file 'x', it will run it but with the value of the variable 'a' which is defined in file 'y'.

**Comment by pekkaklarck** [comment]
Could you please clarify this?

**Comment by HafezM** [comment]
So consider you have project with a test file and 2 helper files. Both of the helper files "x' & 'y' ,which have a variable with the same name  "name" but different values, and the test file imports both the helper files. 
When calling in the test file a keyword from file 'x' that uses variable "name", Then it will not use the assigned value for 'name' in file 'x' but the value of 'name' in the file 'y'.

Hope this makes any sense.
Thank you.

**Comment by bhirsz** [comment]
Does it adhere to this statement from UserGuide or not?

```
All variables from a variable file are available in the test data file that imports it. If several variable files are imported and they contain a variable with the same name, the one in the earliest imported file is taken into use. Additionally, variables created in Variable tables and set from the command line override variables from variable files.
```

So if you have variable `${a}` defined in x.robot:
```
*** Variables***
${a}  4
```
and y.robot
```
*** Variables***
${a}  5
```
and test.robot:
```
*** Settings ***
Resource    x.robot
Resource    y.robot

Test
    Log    ${a}
```
It should print 4.

**Comment by HafezM** [comment]
So I have to keep the variables names unique across the whole project!

**Comment by bhirsz** [comment]
Variable names does not need to be unique - but if you're using multiple imports they should be unique (or you need to be aware of how it works). If you're depending in import order to resolve variable value it will quickly create kind of spaghetti code. I've encountered such situation where I saw multiple (and nested too) imports and if there was not unique variable name I was not able to guess its value without running the code. 

Example of reusing variable name:

imp.resource
```
*** Variable ***
${common_value}    10

*** Keywords ***
My Common Keyword
    Should Be True  ${common_value} < ${common_but_different}
```
test1.robot
```
*** Settings ***
Resource  imp.resource

*** Variables ***
${common_but_different}  5

*** Test Cases ***
Test
    My Common Keyword
```
test2.robot
```
*** Settings ***
Resource  imp.resource

*** Variables ***
${common_but_different}  15

*** Test Cases ***
Test
    My Common Keyword
```

So it's safe to reuse as long you're aware how it will behave.

**Comment by HafezM** [comment]
Noted, thank you :)

**Comment by pekkaklarck** [comment]
The current design related to handling variables isn't great in this regard, but changing it is both a lot of work and pretty badly backwards incompatible. I'm pretty sure we need to do something to it in the future, but we already have #2970 about it so this issue can be closed.
