### ISSUE TITLE
Which API function in Robot 3.2 is the repalcement of TestData in robotframework 3.1?

### ISSUE THREAD

**Issue by caoxianke** [robotframework/robotframework#3764]
I create an offline script to extract the hierarchy of a robot test suite using "TestData()" based on API Robot 3.1 robot.parsing package. But this method disappears in Robot 3.2. Does anybody know if there is a replacement of TestData() in Robot 3.2.1 and later?

Thanks in advance

**Comment by pekkaklarck** [comment]
There's no direct replacement. See the docs here:
https://robot-framework.readthedocs.io/en/latest/autodoc/robot.parsing.html
