### ISSUE TITLE
Libdoc: XML spec files should have info about all tags used by keywords

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#3770]
Keywords listed in XML specs have tags, but having all tags that have been used listed separately would make working with them a bit more convenient. The new JSON specs already have all tags listed like that because that info is need by HTML outputs that nowadays use JSON specs internally. Both spec formats should have same content.

**Comment by MaciejWiczk** [comment]
@pekkaklarck I'm interested in that one. I will take a look into it.

**Comment by pekkaklarck** [comment]
Go ahead! @Snooz82 was going to look at this but I think he hasn't started yet.

**Comment by MaciejWiczk** [comment]
I created PR for this issue, let me know if this matches intention

**Comment by pekkaklarck** [comment]
The PR looks good to me. Can you @Snooz82 take a look as well?

**Comment by Snooz82** [comment]
I can do!

**Comment by Snooz82** [comment]
@MaciejWiczk @pekkaklarck 

I reviewed it. implementation is fine, but XSD and Tests need some changes.

**Comment by pekkaklarck** [comment]
Thanks @Snooz82! Let me know when changes are done and I'll take one final look and merge the PR.

**Comment by MaciejWiczk** [comment]
@pekkaklarck @Snooz82 , Pr fixed and ready for another review round.
