### ISSUE TITLE
How to package scripts of robotframework as an executable file?

### ISSUE THREAD

**Issue by fengnex** [robotframework/robotframework#3777]
When we want to package rf's scripts and all their related libraries into a fold, so that this fold can be copied to other machines and then be run smoothly, are there any ways can implement that?

**Comment by fengnex** [comment]
I think this should be a common requirement and robot's scripts are actually python programs, so maybe there are some ways and could anyone be so kind as to provide some solutions?

**Comment by pekkaklarck** [comment]
This issue tracker is for bug reports and enhancement requests related to Robot Framework core. Questions should be asked on other supports forums such as our Slack.

**Comment by fengnex** [comment]
Where is your slack?
Many people of us don't know that, or we have no way to access it because of all kinds of reasons such as the national firewall of some governments.

**Comment by fengnex** [comment]
And maybe that's one of those main reasons why the star number of RF is still just so much now.

**Comment by pekkaklarck** [comment]
You can find links to various support forums, including Slack, from robotframework.org.
