### ISSUE TITLE
Libdoc: List enums and TypedDicts used as argument types in HTML automatically

### ISSUE THREAD

**Issue by Snooz82** [robotframework/robotframework#3783]
Libdoc does now store data types like Enums and TypedDicts in the JSON and XML output.
These data types shall be readable in Libdoc HTML

- [x] List of custom DataTypes shall be part of the Keyword list

- [x] Data types shall be searchable

- [x] Data types shall be linked from floating text and from argument interface

- [x] Data types shall show the __doc__ information that is stored in them.

**Comment by pekkaklarck** [comment]
This functionality still needs to be documented in the User Guide.

**Comment by pekkaklarck** [comment]
I documented this functionality in cd8a0b19fc46ab51fb126a00fa6199c106097adb. Could you @Snooz82 take a look and close this issue if you consider it good enough?

**Comment by pekkaklarck** [comment]
No feedback but I guess docs are good enough.
