### ISSUE TITLE
Libdoc: Add standalone `libdoc` command

### ISSUE THREAD

**Issue by Snooz82** [robotframework/robotframework#3785]
Libdoc is very useful, but many people do not know about it and it is too complex to use.

`python -m robot.libdoc Library lib.html` is just too complex.

adding the command `libdoc` to the console_scipts would make it easier to use.
Online reserches for libdoc mostly shows robot framework libdoc and some really old stuff.
There is not APT package with that name, so i think it is safe to use it.

**Comment by pekkaklarck** [comment]
Sounds good to me. The main risk of adding a new entry point like this is that on Unixy machines it's installed under `/usr/bin` or equivalent unless using per-user installation or virtual environments. @Snooz82 has already researched that `libdoc` shouldn't conflict with other tools with same name so this ought to be safe.
