### ISSUE TITLE
working with python enum

### ISSUE THREAD

**Issue by AsafDin** [robotframework/robotframework#3786]
Do someone have an example how to work with python enums in robot ?
I have this enum class in python :

from enum import Enum

class enumsMonitor(Enum):
    snmp = "snmp"
    rest = "rest"
    log = "log"
    demo = "demo" 

I tried to use it like this :
[‎11/‎30/‎2020 5:04 PM]  Aviran Bakal:  
*** Settings ***

Library           ../../Tools/monitor/enumsMonitor.py   WITHNAME  enum

*** Variables ***

*** Test Cases ***

Test 1 - Check Type param
    [Tags]  SID_1  Check
    log  ${enum.log} 
 
this doesn't work

**Comment by pekkaklarck** [comment]
You are importing a library but then try to use the enum as a variable. Not sure what you actually try to do, but perhaps using a variable file would work. Check out the Robot Framework User Guide for more information about them.

Notice also that this issue tracker is for bug reports and enhancement requests. Questions are best asked on support forums listed at http://robotframework.org.
