### ISSUE TITLE
Add public APIs to allow modifying parsing model

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#3791]
Currently we expose these parsing related functions and classes via our explicit public API `robot.api`:

- `get_tokens` for parsing test data to tokens.
- `get_model` for parsing test data to a higher level model.
- `Token` to expose token types and to allow creating new tokens.

The current API is enough for inspecting data and existing data can also be modified. It isn't, however, possible to add new data to the exposed higher level model. This functionality is important for external tools working with the parsing model such as the new [RoboTidy](https://github.com/MarketSquare/robotframework-tidy).

Things to decide include:

- What APIs to expose? Basically we need to expose everything so that RoboTidy can use only `robot.api` and not `robot.parsing`. The model has lot of node classes like `File`, `TestCaseSection`, `Keyword`, `If`, `IfHeader`, and `End`. We can either expose them all individually or we can expose factories that allow creating different nodes. With statement nodes we already have our internal `Statement` that has `from_tokens`, but with block nodes we don't have anything similar. If we could add e.g. `Block.from_statements` then exposing just `Statement` and `Block` could be enough.

- Should we expose these APIs via `robot.api` directly or should we add `robot.api.parsing`? I think the latter is a must if we end up exposing all node classes, but it may also be a good idea otherwise.

**Comment by pekkaklarck** [comment]
I've been prototyping creating `Block.from_statemens` and now, for example, this works:

```python
test = Block.from_statements([
    Statement.from_tokens([Token(Token.TESTCASE_NAME, 'Example')]),
    Statement.from_tokens([Token(Token.SEPARATOR, '  '),
                           Token(Token.KEYWORD, 'Log to console'),
                           Token(Token.SEPARATOR, ' '),
                           Token(Token.ARGUMENT, 'Hello, world!')]),
    Statement.from_tokens([]),
])
```

Does that look fine for RoboTidy developers and others? If yes, I can finalize this work and expose both `Block` and `Statement` publicly.

**Comment by pekkaklarck** [comment]
Although the above works, I'm starting to think it's not a good idea. The same example can be written like this already now:

```python
test = TestCase(
    header=TestCaseName([Token(Token.TESTCASE_NAME, 'Example')]),
    body=[
        KeywordCall([Token(Token.SEPARATOR, '  '),
                     Token(Token.KEYWORD, 'Log to console'),
                     Token(Token.SEPARATOR, ' '),
                     Token(Token.ARGUMENT, 'Hello, world!')]),
        EmptyLine([Token(Token.EOL)])
    ]
)
```

I like this latter example more because it's more explicit. Supporting it is also easy, we just need to expose all nodes used in the parsing mode. Because there's lot to expose, I believe we should do that via `robot.api.parsing` instead of directly via `robot.api`. We can also move other public parsing APIs there (we can leave them in `robot.api` as deprecated) and can move lot of the API docs in `robot.parsing` to that module as well.

**Comment by bhirsz** [comment]
From what I've seen 99% (made up number, based on few different companies I've been in) people are using `robot.api` for logger and decorators and that's it. That's why I would prefer to use something like `robot,api.parsing` especially if we're going to expose a lot. 

For me using api is doesn't have any benefit right now - but I understand the necessity (it's better to have one stable API, in case something in parsing change its name or place). And it will help to reduce amount of imports - sometimes I need to think what's statement and what's block to decide where to import from, ie [here](https://github.com/MarketSquare/robotframework-robocop/blob/63bf9523d0a85183f851023f16d2b9f3e1d99e0d/robocop/checkers/lengths.py#L4).

From those two examples I prefer the more explicit one - I can see from quick glance what's actually created.

**Comment by pekkaklarck** [comment]
The decision  now is to expose all nodes used in the model explicitly via `robot.api.parsing`. Also parsing stuff currently exposed via `robot.api` will be made available via that module. The module will also get comprehensive API docs based on the current docs of `robot.parsing`.

An additional task is thinking can the model be simplified somehow. For example, it seems we could just have single `SectionHeader` instead of separate section header classes for each section.

**Comment by pekkaklarck** [comment]
Parsing model objects as well as visitors that can be used to traverse the model were exposed in 6df70f66d14118b44f3ccf4e099a081f0bbfe089. The new `robot.api.parsing` module still needs API docs and should also add a note that `get_tokens`, `get_model` and `Token` should be in the future imported via `robot.api.parsing` instead of `robot.api` directly. Otherwise this issue ought to be done. I hope people interested on these APIs, especially the new Tidy devs, would test do we now expose everything needed.

**Comment by pekkaklarck** [comment]
API docs for `robot.api.parsing` were added by the above commit and they are visible [here](). Things to do:

- [ ] Proof-reading. Hopefully others interested in these APIs can help!
- [ ] Mentioning`robot.api.parsing` in `robot.api`.
- [ ] Mention that `get_tokens` etc. should be imported via `robot.api.parsing` in RF 4+.
- [ ] Simplify `robot.parsing` docs. They can mostly refer to `robot.api.parsing.

**Comment by pekkaklarck** [comment]
Everything planned has now been done and all updated docs can be accessed via https://robot-framework.readthedocs.io/en/master/index.html. Proof-reading of the docs is still highly appreciated!

If something else should still be exposed, or exposed APIs somehow changed, comment here or submit a new issue!

**Comment by pekkaklarck** [comment]
Creating statements was further enhanced by PR #3808 created by @bhirsz that adds `from_params` to statements allowing usage like `SuiteSetup.from_params(name='Example', args=['a1', 'a2'])`. Related documentation needs to still be enhanced.
