### ISSUE TITLE
Robot runner supports java based keywords.?

### ISSUE THREAD

**Issue by simplyviks** [robotframework/robotframework#3794]
I am trying to use robot runner to run java based keywords, how ever its not working, do we still need jython to run it? i am passing extra path dir from command line however its not finding the java modules(imported library)

i am able to run as below, however its not considering the pythonpath at all, the library.class file has to be in current directory/

sudo jython -m robot --include tag1 --pythonpath /home/XXX/code/xxx/target/libs:/home/XXX/code/xxx/target/jars/*.jar:/home/XXX/code/xxx/target src/test/robotframework/acceptance/tests/testPythonModuleImport.robot

https://github.com/robotframework/robotframework/issues/2216

**Comment by pekkaklarck** [comment]
Jython is still supported and the usage you describe ought to work fine. Are you certain you are specifying correct directories with `--pythonpath`? Have you tested would using `CLASSPATH` environment variable work? If you still cannot make it work and suspect there's a bug, you need to create a simple example demonstrating the problem that we can run ourselves.

**Comment by simplyviks** [comment]
@pekkaklarck Thanks for replying, it gave me some hope. :)

[robot-utils4j.zip](https://github.com/robotframework/robotframework/files/6195860/robot-utils4j.zip)

Attaching the sample zip file with a robot test and a java lib.


why i am looking for this support.
-----------------------------------------------

we are using robot framework as a automation framework as a whoe, out test cases are a combination of keywords based on python and java, this was working fine and we were able to run it using robotframework-maven plugin(jython-2.7.0 inbuilt?), but recently the python modules we were using got some new keywords which depends of some cython based modules(lxml.etree), now we are not able to import those modules as jython doesn't support cython based modules, now this is a blocker for us.

To come out of this we were looking to use a global runner profile "robot" and if it is able to run java based keywords along with python keywords with cython dependency we are out of this situation.

is our expectation right? currently i am not able to use "robot" to run the robot test case with java keywords , attached sample project, tried setting CLASSPATH also but no luck, please help!!

command used to run:

vikashks@host-30-1-1-104:~/code/robot-utils4j$ robot --pythonpath=/home/vikashks/code/robot-utils4j/target/robot-utils4j-1.0.0.jar JavaHello.robot
