### ISSUE TITLE
Passing --form data as part of ROBOT Framework

### ISSUE THREAD

**Issue by chidambaranathan-r** [robotframework/robotframework#3797]
I am trying to pass the below API request in ROBOT framework:

`curl --request POST --url <API End Point>  --form 'mldata={"id": “idname”, "author": “author name, "title": “title name, "description": “description details“, "version": "0.0.4", "image": “/path/to/image”, "icon": "base64 encoded image"};type=application/json' --header "Authorization: <Bearer Token>”`

Written the same in ROBOT framework [Version: 3.2.2].

```
Onboard ML From External Repo
    [Arguments]    ${token}=default
    Create Session    session    ${host}
    ${data}=    Create Dictionary    id=${id}    author=${author}    title=${title}    description=${description}    version=${version}    image=${repo_path}
    ${form_data}=    Evaluate    {'mldata=': ${data}}
    ${header}=    Create Dictionary    Authorization=${token}    Content-Type=application/json
    ${response}=   Post Request    session    /v1/ml    data=${form_data}    headers=${header}
    Should Be Equal As Strings    ${response.status_code}    200
```

Was getting error: `"status=400, reason=Bad Request  body={"message":"Request is not a multipart request!"}"`

I reframed the above as per suggestions from stackoverflow https://stackoverflow.com/questions/65252836/passing-form-data-as-part-of-robot-framework/65261768#65261768:

```
Onboard ML From External Repo
    [Arguments]    ${token}=default
    Create Session    session    ${host}
    ${data}=    Create Dictionary    id=${id}    author=${author}    title=${title}    description=${description}    version=${version}    image=${repo_path}    icon=${icon}
    ${form_data}=    Evaluate    {'mldata=': "'"+${data}"'"}
    ${header}=    Create Dictionary    Authorization=${token}    Content-Type=application/json
    ${response}=   Post Request    session    /v1/ml    data=${form_data}    headers=${header}
    Should Be Equal As Strings    ${response.status_code}    200
```
This time I am getting error: `Evaluating expression '{'mldata': "'"+{'id': 'idname', 'author': 'author name', 'title': 'title name', 'description': 'description details', 'version': '0.0.1', 'image': '/path/to/image', 'icon': 'base64 encoded image'}+"'"}' failed: TypeError: can only concatenate str (not "dict") to str`

**How should I pass in the right way? or Is it a bug?**

Request for help in passing the form data `'mldata={"id": “idname”, "author": “author name, "title": “title name, "description": “description details“, "version": "0.0.1", "image": “/path/to/image”, "icon": "base64 encoded image"};type=application/json'` in robot framework.

**Comment by MaciejWiczk** [comment]
You could try:
- creating dictionary with: 
```
    ${data}=    Create Dictionary    id=${id}    author=${author}    title=${title}    description=${description}    version=${version}    image=${repo_path}    icon=${icon}
    ${form_data}=    Create Dictionary    mldata=${data}
```
- using json.dumps or similar method

**Comment by chidambaranathan-r** [comment]
Thanks for the response.Sorry for the late response. Actually I got the way forward as given below. This is the one worked for me after trying multiple options:

Highlighted the key portions that make it worked.

```
Onboard ML From External Repo
    [Arguments]    ${token}=default
    Create Session    mxesession    ${host}
    **${data}=    Create Dictionary    id=${id}    author=${author}    title=${title}    description=${description}    version=${version}    image=${repo_path}    "icon": ${icon_image}
    ${form_data}=    Evaluate    {'mldata=': str(${data}).replace("'",'"')}**
    ${header}=    Create Dictionary    Authorization=${token}
    ${response}=   Post Request    mxesession    /v1/ml    **files=${form_data}**    headers=${header}
    Should Be Equal As Strings    ${response.status_code}    200
```
