### ISSUE TITLE
Tidy adds redundant new line when parsing DDT

### ISSUE THREAD

**Issue by mnojek** [robotframework/robotframework#3805]
When I run `tidy` on file containing data-driven tests it injects a new line after each test case. It relates only to the scenario when `Test Template` is declared in `Settings` section for a whole suite. 

For example this code:
```
*** Settings ***
Test Template  Login To Page

*** Test Cases ***      USERNAME        PASSWORD
Valid Login             robot           secret
Invalid Login           robot           wrong
Another Login           robot2          pass
```
is transformed by `tidy` into this:
```
*** Settings ***
Test Template     Login To Page

*** Test Cases ***    USERNAME    PASSWORD
Valid Login           robot       secret

Invalid Login         robot       wrong

Another Login         robot2      pass
```

I debugged this issue and figured out that Robot API parses each line under `TestCaseSection` as separate `TestCase` (which is fine) but it injects `EmptyLine` after it (which is strange).

**Comment by pekkaklarck** [comment]
I guess Tidy makes sure there's always a single empty line between tests. I agree adding it with data-driven tests is not generally a good idea and this could be changed. The main question is, is such a change worth the effort when we now have the new [external Tidy project](https://github.com/MarketSquare/robotframework-tidy).

**Comment by bhirsz** [comment]
It will be covered in https://github.com/MarketSquare/robotframework-tidy/issues/31

**Comment by pekkaklarck** [comment]
Since the new Tidy is going to handle this problem, this issue related to the old Tidy can be closed.

**Comment by pekkaklarck** [comment]
Tidy is dead, long live Tidy!
