### ISSUE TITLE
How do I setup multiple keywords with robot api

### ISSUE THREAD

**Issue by littlekeith** [robotframework/robotframework#3811]
from robot.model.keyword import Keyword, Keywords
from robot.api import TestSuite

s1, s2, kw = Keyword(type='setup'), Keyword(type='setup'), Keyword()
kws = Keywords(keywords=[kw])
# kws.setup work
kws.setup = s1
# suite.keywords.setup not work
suite.keywords.setup = s1

# Got follows problems:
TypeError: Only Keyword objects accepted, got Keyword.

**Comment by littlekeith** [comment]
one way is:
put multiple keywords into python function which as keyword, and then setup it.

Have other way to setup?

**Comment by pekkaklarck** [comment]
You are using `Keyword` and `Keywords` from `robot.model`, but `TestSuite` from `robot.api` which is same as `robot.running` in this case. Running side model must be created from running side objects. Easiest is using `suite.keywords.create()` that creates correct objects automatically, but notice that this API is changing in RF 4.0 as explained in #3749. Notice also that our Slack (you can find a link via robotframework.org) is generally better place to ask questions like this.
