### ISSUE TITLE
screenshot of the current page not embedded  into  log file.

### ISSUE THREAD

**Issue by HavenChen** [robotframework/robotframework#3821]
SeleniumLibrary keyword-[Capture Page Screenhot] used in robot script, but the screenshot PNG doesn't show in robot log.html.

In output.xml, the keyword output is like this:

\<kw name="Capture Page Screenshot" library="SeleniumLibrary"\>
\<doc\>Takes a screenshot of the current page and embeds it into a log file.\</doc\>
\<status status="PASS" starttime="20210111 15:52:35.566" endtime="20210111 15:52:35.871"\>\</status\>
\</kw\>

But in correct casees, it shoud be like this:

\<kw name="Capture Page Screenshot" library="SeleniumLibrary"\>
\<doc\>Takes a screenshot of the current page and embeds it into a log file.\</doc\>
\<msg timestamp="20210111 16:24:01.458" level="INFO" html="yes"\>&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td colspan="3"&gt;&lt;a href="selenium-screenshot-1.png"&gt;&lt;img src="selenium-screenshot-1.png" width="800px"&gt;&lt;/a&gt;\</msg\>
\<status status="PASS" starttime="20210111 16:23:59.226" endtime="20210111 16:24:01.458"\>\</status\>
\</kw\>

As you can see, the <msg> is lost.

Do you know the reason of this issue? Robot version is Robot 3.2.2 (Python 3.7.4 on win32)

Thank you.

--------------------------------------
![image](https://user-images.githubusercontent.com/57041712/104160350-f07d4300-542b-11eb-9f08-439764eab2c1.png)

**Comment by pekkaklarck** [comment]
What log level did you use? Is there any kind of post-processing of results?

**Comment by pekkaklarck** [comment]
Closing due to lack of information.
