### ISSUE TITLE
Search keyword in results page

### ISSUE THREAD

**Issue by stdedos** [robotframework/robotframework#3826]
I would like to be able to search for a keyword (that I know it has executed) on an execution, but I don't want to find out under which keyword it is hiding.

More ideas. Search box with:
* Search only keyword names
* Search on Fully Qualified Keyword Names
* Search on visible log level
* Search on all log levels

**Comment by pekkaklarck** [comment]
Search in log would be great. We already have #3799 about that so let's continue discussion there.
