### ISSUE TITLE
AST classes no longer hashable.

### ISSUE THREAD

**Issue by fabioz** [robotframework/robotframework#3830]
It seems that AST classes now implement `__eq__` and `__ne__` (added in https://github.com/robotframework/robotframework/commit/fd641abe368fa5eb02708225e0fc64b63d33d373), but don't provide a `__hash__` and thus the AST classes are no longer hashable.

Is it possible to make them hashable again? (this is breaking the Robot Framework Language Server)

My suggestion would be to not even add `__eq__` and `__ne__` and leave the `__eq__` / `__hash__` by `object id` as it doesn't really seem that useful as cases probably vary quite a bit on what needs to be used to actually consider that one AST equals another -- considering only the structure or actual lines/columns comes to mind (so, if someone has a special case for comparing ASTs I think that in general that should be done by who is doing that compare -- possibly providing one helper function for the current use-case if needed).

**Comment by fabioz** [comment]
@bhirsz pinging since it seems you did this change... I think you just added this for the test cases, is that right? In that case, do you think you could change those to have a helper compare function and restore the `hash` for the AST?

**Comment by bhirsz** [comment]
Uh! I wasn't aware it would break it. Yes I only added it for test cases - I used helper compare function before and switched it for `__eq__` statements. 
We could probably add proper `__hash__` method but then we would need to also extend it to check for line numbers (so it would not match with the same statements in different lines). So like you said - cases vary quite a bit on our needs. 

Pinging @pekkaklarck - what do you think, should I fallback to my previous solution? (with helper method)

**Comment by pekkaklarck** [comment]
This definitely needs to be fixed. Making `__eq__` and `__hash__` work when statements aren't immutable is hard and likely to cause more subtle bugs. `__eq__` was added to make testing easy, but similar helpers can be added to tests pretty easily instead. Probably best to remove `__eq__`.

**Comment by bhirsz** [comment]
Sure, I will take care of it
