### ISSUE TITLE
Color of skip / skipped test cases - `--skip` vs. `--skiponfailure`

### ISSUE THREAD

**Issue by wlad** [robotframework/robotframework#3833]
When looking at the log.html it would be great to see at a glance which tests were skipped by `--skip` from command line and which tests were marked as skipped via `--skiponfailure` without having to unfold / open a test case. This could be achieved by having different colors, for example:

- `--skip`: grey (like untested or not executed)
- `--skiponfailure`: yellow/orange (like executed but (partially) failed)

![image](https://user-images.githubusercontent.com/64201310/105232252-68541780-5b68-11eb-80f6-ceb25c3ea663.png)

**Comment by pekkaklarck** [comment]
This is covered by #3625.
