### ISSUE TITLE
Does it support Dameng database (Chinese localized database) connection? What libraries need to be installed? how to use?

### ISSUE THREAD

**Issue by weizhi123** [robotframework/robotframework#3839]
Does it support Dameng database (Chinese localized database) connection? What libraries need to be installed? how to use?

**Comment by pekkaklarck** [comment]
I'm not sure do you mean using Dameng database in testing somehow or using it to localize Robot Framework itself. If the former, then that's certainly possible via libraries. I'm not sure are there any ready-made libraries available but creating custom libraries for Robot is pretty easy. If you mean the latter, then that's not supported. Localization would be great, though.
