### ISSUE TITLE
pass argument to user keyword repeated

### ISSUE THREAD

**Issue by kanchi240** [robotframework/robotframework#3840]
![image](https://user-images.githubusercontent.com/4908696/106111831-7f59c180-6187-11eb-99ad-9d565dd6a845.png)
![image](https://user-images.githubusercontent.com/4908696/106111897-93052800-6187-11eb-829c-7a0858536755.png)

Hi,
Please see images above, user keyword argument can be passed twice(repeated), is there a way to avoid it?
Thanks.

**Comment by pekkaklarck** [comment]
This is by design. When using the named argument syntax and giving value multiple times, the last value wins. The way to avoid it is not passing the argument more than once.
