### ISSUE TITLE
Setting custom name to resource

### ISSUE THREAD

**Issue by xapn** [robotframework/robotframework#3841]
I propose to generalize the aliasing facility of libraries to resources: as it is possible to [set a custom name to libraries](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#setting-custom-name-to-test-library) by using the `WITH NAME` syntax, it would be very convenient to do the same thing for resources.

For example:
```
*** Settings ***
Resource    SomeResource.resource    WITH NAME    R1
Resource    OtherResource.resource    alpha12345    ${9876}    WITH NAME    R2

*** Test Cases ***
My Test
    R1.Some Keyword
    R2.Some Keyword    arg1    arg2
    R1.Another Keyword
```

**Comment by pekkaklarck** [comment]
There's no technical reason why this couldn't be done but I don't see much benefits. With libraries the main benefit is being able to use same library with different arguments like
```

**Comment by pekkaklarck** [comment]
No new info about possible benefits. Closing.
