### ISSUE TITLE
There is no information about Reserved Keywords('IF' , 'WHILE') 

### ISSUE THREAD

**Issue by sandhyakunamneni** [robotframework/robotframework#3847]
There is no proper information about usage of reserved keywords 

![Capture3](https://user-images.githubusercontent.com/47234023/107218225-582bab80-6a35-11eb-8dd0-7733d4fb2af6.PNG)

**Comment by pekkaklarck** [comment]
Where do you expect to see such information?

**Comment by pekkaklarck** [comment]
Closing due to lack of information. If this is related to RIDE, this should be submitted to its issue tracker.
