### ISSUE TITLE
Remove unnecessary container elements from output.xml

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#3853]
We currently represent lists of items such as keyword arguments in output.xml so that there's a container element like `<arguments>` around the individual items:

```
<arguments>
<arg>first</arg>
<arg>second</arg>
</arguments>
```
These containers are totally unnecessary. In fact, when we parse the output.xml ourselves, we need to skip over the containers so there's just a little extra work. In addition to that, they increase the size of output.xml unnecessarily.

I tested how not writing these container elements would affect the output.xml size and the time needed for parsing it. I run Robot's own acceptance tests with and without the change (also validated that the change didn't break anything) and the results were these:

File                         | Size (b)    |  Time (avg. of 3)
------------------------- | ------------- | ------------------------------
With containers      | 24016670 | 9.35s
Without containers | 22468001 | 9.15s

The difference in size is about 6% and the difference in performance is about 2%. Not huge savings but considering that the change is easy (and already mostly done) it's definitely something to consider.

The obvious problem with the change is backwards compatibility with external tools that are processing output.xml. This kind of  changes are not to be made lightly, but RF 4.0 is a major release where such changes are OK and we have already needed to change output.xml otherwise (#3726). Changing the structure a bit now when tools anyway need to adapt would probably be better than doing that change in future releases.

**Comment by pekkaklarck** [comment]
Another benefit of removing these containers would be consistency. The newly added `<for>` element has its variables and values listed directly as `<var>` and `<value>` elements and we've never had containers around lists of `<test>` or `<kw>` elements either. Removing containers would also make the output.xml schema a bit simpler.

**Comment by pekkaklarck** [comment]
We currently use containers in the following cases:

1. Keyword arguments, assign and tags. Individual items have names `<arg>`, `<var>` and `<tag>`, respectively, and I guess we could just use them. Changing `<var>` to `<assign>` could be considered but it would make adapting to the new structure a bit more work.
2. Test tags. They are `<tag>` elements and would work just fine without containing `<tags>`.
3. Suite metadata. Currently they are represented like `<metadata><item name='Name'>Value</item></metadata>`. I don't think `<item>` is a good name to be used on its own so it would need to be renamed. `<metadata>` would be natural name, but using the same name that is nowadays used with the container may not be a good idea. Perhaps `<meta>` would be better.

**Comment by pekkaklarck** [comment]
I added this tentatively to RF 4.0 scope. Easy performance enhancements are always tempting and increased consistency would be nice too. Still need to think about the backwards compatibility aspect, though. Please comment if you you have opinions either way!

**Comment by bitcoder** [comment]
Well, on this topic, if it helps performance then I think it’s a good way forward. My only concern is backward compatibility. we need to flag this schema (i.e the generate XML reports) in a way that tools can understand and differentiate the previous format from the new one

**Comment by pekkaklarck** [comment]
I agree backwards compatibility is important but because we have already changed output.xml and benefits are not insignificant I think this change is a good idea. I run some more tests and got about 9% smaller output.xml files than with RF 3.2.2.

I agree we need separate schema for RF 4 and RF 3 but we have #3726 about that. This also needs to be mentioned in the RF 4 release notes.

**Comment by pekkaklarck** [comment]
Ok, let's do this! There seldom are as cheap changes that reduce output.xml size this much and these containers really are just useless. Yes, this breaks backwards compatibility, but there are already other changes to output.xml in RF 4.0 so external tools relying to it need to adapt anyway.

**Comment by pekkaklarck** [comment]
This is what changed:

- `<arguments>`, `<assign>` and `<tags>` containers inside `<kw>` elements were all removed. Their old child elements `<arg>`, `<var>` and `<tag>` are used directly inside `<kw>` and they haven't changed at all.
- `<tags>` container inside `<test>` was removed and `<tag>` used directly.
- `<metadata>` container insider `<suite>` was removed. Its old `<item>` child element was renamed to `<meta>` and used directly inside `<suite>`.
