### ISSUE TITLE
Parsing API error handling does not detect fatal errors properly

### ISSUE THREAD

**Issue by d-biehl** [robotframework/robotframework#3857]
Hello,

Just playing around with the parsing Model of Robotframework.
I've noticed that the Error statement does not read Token.FATAL_ERROR in errors property, but it is defined to handle both Token.Error and Token.FATAL_ERROR.

The following code:

```python
import io

from robot.api.parsing import ModelVisitor, get_resource_model


class ErrorReporter(ModelVisitor):
    # Implement `generic_visit` to visit all nodes.
    def generic_visit(self, node):
        if node.errors:
            print(f'Error on line {node.lineno}:')
            for error in node.errors:
                print(f'- {error}')
        ModelVisitor.generic_visit(self, node)


text = "*** Test Cases ***"

with io.StringIO(text) as data:
    model = get_resource_model(data)

    ErrorReporter().visit(model)
```

should return like:

    Error on line 1:
    - Resource file with 'Test Cases' section is invalid.

but it doesn't.

See code from Master Branch:

https://github.com/robotframework/robotframework/blob/fb355fbc99bd8ced392017a4317ea9a9dff4b659/src/robot/parsing/model/statements.py#L914

**Comment by pekkaklarck** [comment]
First of all, it's great to see these APIs investigated and used by others! Secondly, great catch! I can fix this myself but if you are interested to provide a PR that obviously works too. I try to get RF 4.0 rc 1 out early next week and this definitely needs to included.

**Comment by pekkaklarck** [comment]
This error reporting was added in 2127623386f43e5a536b55ae1f27d8be1a6b0800 with some tests in `test_model.py`. It seems that the bug was introduced in 0194b6271b8512464c0149cb604df3dea2a7c4f2 when handling token types was changed and the `Error` statement started to handle both `ERROR` and `FATAL_ERROR` tokens. Ought to be trivial to fix with enhanced/new tests in `test_model.py`.

**Comment by d-biehl** [comment]
just add added the PR #3861 to correct this issue, also added/modified the unittests for it.

**Comment by pekkaklarck** [comment]
Thanks for the PR @d-biehl!
