### ISSUE TITLE
When I  defined my custom library by python module，The robotframework  made this error that  "Adding keyword 'Pointer' failed: Keyword with same name defined multiple times."

### ISSUE THREAD

**Issue by xietingitng** [robotframework/robotframework#3863]
The robotframework  made this error that  "Adding keyword 'Pointer' failed: Keyword with same name defined multiple times."
But There was no keywork 'Pointer' in my custom library。

env info:
robotframework          3.2.2
python    3.7.4

**Comment by xietingitng** [comment]
I founded the reason.

Because  I used  "from ctypes import *" in my python file.I changed it to 'from ctypes import CDLL'.So the symbol * cannot be used.

**Comment by pekkaklarck** [comment]
`from x import *` is generally considered bad practice in Python but that doesn't directly cause this problem. If you implement a library as a module, all functions in the module will be considered keywords. This includes also functions you import elsewhere. I'm fairly certain the `ctypes` module has a function named `Pointer` or something similar that conflicts with the function you create. Notice also that all other functions you import would become keywords as well.

In this particular case importing only `CDLL` is definitely the best solution. You could, however, explicitly tell Robot what functions become keywords if you wanted to. To learn more about the, check the User Guide.
