### ISSUE TITLE
API: SkipExecution to support html argument

### ISSUE THREAD

**Issue by adiralashiva8** [robotframework/robotframework#3866]
Need html message format support while raising exceptions

Example:
```
 from robot.api import SkipExecution
 
 def skip_execution():
     raise SkipExecution('<b>Skipped from execution</b>', html=True)
```
Current implementation doesn't support this.

**Comment by pekkaklarck** [comment]
This was implemented by the commit above. I consider this issue to be part of #3685 and won't add this into RF 4.0 scope explicitly.
