### ISSUE TITLE
Enhance documentation of splitting long variables to multiple rows in Variable section

### ISSUE THREAD

**Issue by xbreak** [robotframework/robotframework#3870]
Apologies if this has been answered before but I don't find an existing issue describing my problem.

I'd be happy with a quick clarification if this is even possible or not in v3.1.2.

Many thanks!

## tl;dr
How do break up long single arguments, including that sometimes it's required that no extra whitespaces are introduced, in `Set Variable` or directly as argument to a keyword?

## Verbose

I have several cases where individual arguments are long enough so they require line breaks. We are using v3.1.2 and from the 
[manual](https://robotframework.org/robotframework/3.1.2/RobotFrameworkUserGuide.html) it says

> If there is more data than readily fits a row, it possible to use ellipsis (...) to continue the previous line. In test case and keyword tables, the ellipsis must be preceded by at least one empty cell. In settings and variable tables, it can be placed directly under the setting or variable name. In all tables, all empty cells before the ellipsis are ignored.
> ...
> All the syntax discussed above is illustrated in the following examples.

Now, there's no example of a long single argument line as far as I can see, only "pretty long" arguments. So maybe the behaviour is undefined?

Latest version has a different wording so maybe things has changed (I have not tried it)?
> In most places split lines have exact same semantics as lines that are not split. Exceptions to this rule are suite, test and keyword documentation as well suite metadata. With them split values are automatically joined together with the newline character to ease creating multiline values.

Anyway, from what I can tell `...` behaves differently in different contexts (not the special cases mentioned in the manual about documentation).

```robot
*** Settings ***
Library  Process

*** Variable ***

${long_arg}  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    ...  YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY


*** Test Cases ***

Variable Table
    Comment  When using ellipsis in ***variable*** it space-separated
    Log   ${long_arg}
    Should Be Equal  ${long_arg}  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY

Process
    Comment  When using ellipsis as argument in e.g. process it is also space-separated
    ${r} =  Run Process  echo  -e  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    ...   YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
    ...   shell=True
    Log   ${r.stdout}
    Should Be Equal  ${r.stdout}  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY

Set Variable
    Comment  When used as an argument to Set Variable  it becomes a list of strings
    ${local}  Set Variable  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    ...  YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
    Should Be Equal  ${local}  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY

    Comment  Converting list of strings to string doesn't work either
    ${conv} =  Convert To String  ${local}
    Should Be Equal  ${conv}  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
```
Running that I get:
```
==============================================================================
Long
==============================================================================
Variable Table                                                        | FAIL |
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY != XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
------------------------------------------------------------------------------
Process                                                               | FAIL |
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY != XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
------------------------------------------------------------------------------
Set Variable                                                          | FAIL |
['XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY'] != XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
------------------------------------------------------------------------------
Long                                                                  | FAIL |
3 critical tests, 0 passed, 3 failed
3 tests total, 0 passed, 3 failed
==============================================================================
```
## Version 

```
robot --version
Robot Framework 3.1.2 (Python 3.7.6 on linux)
```

**Comment by pekkaklarck** [comment]
How joining lines split with `...` works in the variables section is explained here:
https://robotframework.org/robotframework/3.2.2/RobotFrameworkUserGuide.html#variable-table

Is that documentation clear? Should it or possibly the docs related to handling `...` in general be enhanced somehow? If you have concrete proposals, let me know and I can update the docs. Even better if you can create a PR that I can just merge.

**Comment by xbreak** [comment]
Many thanks, I think that section was clear regarding the behaviour in the variable table, now I can do:

```robot
*** Variable ***
${long_arg}  SEPARATOR=${EMPTY}  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    ...  YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
```

Variable-table should maybe be added to the list of exceptions in [[1]](https://robotframework.org/robotframework/3.2.2/RobotFrameworkUserGuide.html#dividing-data-to-several-rows)?

At this point, as there are many exceptions, maybe a having a table that describes the behaviour of `...` in each context would be really helpful.

Regarding long arguments to keywords (joined by space) and `Set Variable` (creates a list of strings), are those also exceptions from the following?:

> In most places split lines have exact same semantics as lines that are not split.

\-[[1]](https://robotframework.org/robotframework/3.2.2/RobotFrameworkUserGuide.html#dividing-data-to-several-rows)


\[1\]: https://robotframework.org/robotframework/3.2.2/RobotFrameworkUserGuide.html#dividing-data-to-several-rows
