### ISSUE TITLE
'robot is not recognized as an internal or external command'

### ISSUE THREAD

**Issue by Empathineer** [robotframework/robotframework#3875]
Hi there,

**Problem:** I am trying to running my Dummy.robot test script in the terminal via cmd line: `robot -d results tests/dummy.robot`. However, it is returning the error 'robot' is not recognized as an internal or external command. I sensed that perhaps the robotframework was not properly installed or in the correct directory because the keywords "Open Browser" (see below) was already detected as invalid syntax prior to running. 

**Troubleshooting Methods:** 
1) Checked that both robotframework and robotframework-seleniumlibarary were installed 
2) Installed intellibot on PyCharm and restarted IDE 
3) Made sure I provided the correct path to the script within my project directory as shown below. 
4) Checked that Python 39 and Python39/Scripts was added to my PATH although I am not sure if this is relevant because it just allows me to use pip for installing robotframework later. 
5) Selected the interpreter for this "dummy" project from where that python.exe is located. 

Thanks for any feedback in advance!

**Source Screenshots:** 

File Structure
![image](https://user-images.githubusercontent.com/57867200/110170651-69a37180-7daf-11eb-93a2-b1b897e285ec.png)

Source Code 
![image](https://user-images.githubusercontent.com/57867200/110170600-52648400-7daf-11eb-95ba-d5be0b59330c.png)

Terminal 
![image](https://user-images.githubusercontent.com/57867200/110170817-9bb4d380-7daf-11eb-9694-545963bf69c8.png)

**Comment by pekkaklarck** [comment]
Something is wrong in the installation, most likely in PATH configuration. This issue tracker is for bug reports so I'm closing this issue.
