### ISSUE TITLE
Grep File does not accept SYSTEM or CONSOLE as encoding

### ISSUE THREAD

**Issue by jens4Dev** [robotframework/robotframework#3878]
The doc for Grep File from Operation System states that the parameters "encoding and encoding_errors [are] similarly as Get File". Thus I would expect that Grep File accepts SYSTEM or CONSOLE with Robot Framework 3.0(+).
When you try to use SYSTEM or CONSOLE like in Get File, you get an 

````
| ${matchLine} | Grep File | test.txt | myPattern | SYSTEM
LookupError: unknown encoding: SYSTEM
````
Or similiar:
````
| ${matchLine} | Grep File | test.txt | myPattern | CONSOLE
LookupError: unknown encoding: CONSOLE
````

Looking into the code of https://github.com/robotframework/robotframework/blob/master/src/robot/libraries/OperatingSystem.py in get_file there is a call to
````
encoding = self._map_encoding(encoding)
````
This pre-processing is missing in grep_file - might this be the cause of the issue?

Workaround for SYSTEM is to use ${NONE} for encoding:
````
| ${matchLine} | Grep File | test.txt | myPattern | ${NONE}
````

Found with Robotframework 3.2.2 (Python 3.9.0 on win32)

**Comment by pekkaklarck** [comment]
Good catch! Great timing as well as this can be still fixed before RF 4.0 final.

You are right that using `${NONE}` is a good workaround. It basically means opening the file using the default encoding and with Python 3 that means the OS default system encoding. It wouldn't work with Python 2.
