### ISSUE TITLE
BuiltIn: Support collapsing whitespaces with `Should Be Equal` and other comparison keywords

### ISSUE THREAD

**Issue by vokiput** [robotframework/robotframework#3884]
Based on requirements in #3240

collapse_spaces
- False - do not collapse whitespaces
- True - Collapse consecutive whitespaces into one space

**Comment by pekkaklarck** [comment]
Sounds good. Should be added to the same keywords that got `strip_spaces` in RF 4.0 as part of #3240. I'll add this to RF 4.1 scope but it still needs someone to implement it.

**Comment by vokiput** [comment]
Ok, I can do it. Should be trivial after strip_spaces

**Comment by pekkaklarck** [comment]
Great!

**Comment by vokiput** [comment]
Ready for review

**Comment by pekkaklarck** [comment]
Commented the great PR!

**Comment by pekkaklarck** [comment]
PR #3949 merged after updates. Thanks for contribution @vokiput!
