### ISSUE TITLE
Global CONTINUE_ON_FAILURE state/swich

### ISSUE THREAD

**Issue by oboehmer** [robotframework/robotframework#3885]
We would like to achieve a behaviour where we can control continue_on_failure behaviour using a keyword, i.e. 

```
mytest
     continue on failure enabled
     Fail    this fails
     Log   this is executed
     continue on failure disabled
     Fail    this fails
     Log   this is not executed
```

we have patched robotframework 3.x run_step() to achieve this behaviour by checking for a `${CONTINUE_ON_FAILURE}` runtime variable (which we set through the `continue on failure .. ` keywords), but this, not surprisingly, no longer works with the new executor in rf 4.x

We see our internal test writers making use of this functionality quite often, so we would want to check if we could add something like this as a documented feature. 

We are of course aware of setting err.CONTINUE_ON_FAILURE, but this won't achieve the behaviour for builtin or other 3rd party keywords we don't control. 

Comments/Flames?

**Comment by pekkaklarck** [comment]
I agree this would sometimes be a useful feature and it has also been proposed earlier. We have #2285 that proposes adding new keyword tag `robot:continue-on-failure`  that would enable this mode for a certain keyword. Test tag making that a default for the test could also be considered. That functionality wouldn't directly support the usage in the above test, but then again not needing to use separate keywords to enable/disable the behavior would make the test a lot simpler.

I prefer the functionality discusses in #2285 over that's proposed here. If that functionality is implemented, adding this wouldn't bring much real benefits anymore. I thus close this issue and direct all efforts to #2285. Implementing it shouldn't be too complicated, but so far nobody has considered it important enough to provide a PR or to sponsor the development. Hopefully that changes!

**Comment by oboehmer** [comment]
thanks for the comments, @pekkaklarck .. I agree, the approach in 2285 would be able to address our requirements (as long as the tagging would be "hierarchic", i.e. a test case or keyword tagged with robot:continue-on-failure would affect all keywords executed from within this test case or within the keyword. 
Pekka, if we took 2285 up within Cisco, can you point us to some developer docs which explains the overall execution and parsing/model structure to get our devs started?   Looks this changed quite significantly in 4.0, and not sure if there is more than the API docs? We can develop keyword libs just fine, but have limited experience with robotframework itself..

**Comment by pekkaklarck** [comment]
It would be awesome if you could help! I think it would be best to chat about this on the `#devel` channel on our Slack (you can find it via https://robotframework.org). The coming week I'm busy due to [RoboCon](https://robocon.io) (hopefully someone from Cisco is joining as well), but on Friday we actual have [sprints](https://robocon.io/#sprints) and this would be an excellent sprint topic!
