### ISSUE TITLE
Enhance documentation of programmatically modifying setups and teardowns

### ISSUE THREAD

**Issue by jkyto-n** [robotframework/robotframework#3889]
Since 'keywords' property under TestSuite class is deprecated in release 4.0, I tried to use new setters 'setup' and 'teardown'. Purpose is to create via robot.api test suite with suite setup and teardown.

In 3.2.2 this worked with below lines:
- suite = TestSuite('NewTestSuite')
- suite.keywords.create('New Suite Setup', type='setup')
- suite.keywords.create('New Suite Teardown', type='teardown')

After installing 4.0 I used new 'setup' and 'teardown' setters
- suite = TestSuite('NewTestSuite')
- suite.setup('New Suite Setup')
- suite.teardown('New Suite Teardown')

Now I get below error indicating that 'Keyword' object is not callable. I attached example python code to reproduce this error.
- TypeError: 'Keyword' object is not callable

Am I missing something from the documentation or could this be real bug?

[example_create_suite_via_api.zip](https://github.com/robotframework/robotframework/files/6142450/example_create_suite_via_api.zip)

**Comment by pekkaklarck** [comment]
`setup` and `teardown` are objects and you cannot call them like this. You can, however, set their attributes either separately or by calling their `config()` method. This should work:
```python
suite = TestSuite('NewTestSuite')
suite.setup.name = 'New Suite Setup'    # Set only name
suite.teardown.config(name='New Suite Teardown', args=['a1', 'a2'])    # Set multiple attributes in one go
```
Assuming the above works for you, this is mostly a documentation problem. Do you have ideas which docs should be updated?

**Comment by jkyto-n** [comment]
It indeed works when using setup and teardown as objects. I would suggest adding some examples under robot.running documentation. TestSuite class documentation doesn't either have any documentation for setup and teardown. 
- https://robot-framework.readthedocs.io/en/v4.0/autodoc/robot.running.html
- https://robot-framework.readthedocs.io/en/v4.0/autodoc/robot.running.html#robot.running.model.TestSuite

**Comment by pekkaklarck** [comment]
Ok, let's enhance docs related to this in RF 4.0.1.

**Comment by pekkaklarck** [comment]
The example in the [module level docs](https://robot-framework.readthedocs.io/en/latest/autodoc/robot.running.html) actually has example configuring test setup. Actual `setup` and `teadown` attributes didn't have any docs, tough, and I added them in the above commit. Still want to check how they look at Read The Docs before closing this issue.

**Comment by pekkaklarck** [comment]
Docs look good to me. See here for an example:
https://robot-framework.readthedocs.io/en/master/autodoc/robot.running.html#robot.running.model.TestSuite.setup

I close this issue now, but you can still comment it if you see typos etc. or have ideas how the docs could still be enhanced.
