### ISSUE TITLE
String: Rename `should_be_uppercase` to `should_be_upper_case` (and same with `lower`)

### ISSUE THREAD

**Issue by mnojek** [robotframework/robotframework#3890]
I see that in the built-in String library there are some keywords related to case of the string. Some of them are written together and some separate. Examples:
```
Convert To Lower Case
Should Be Lowercase
Convert To Title Case
Should Be Title Case
Should Be Uppercase
```
I think these should be unified. How we want them to be named: together (like Lowercase) or separate (like Lower Case)? Fortunately, this change is backward compatible so it shouldn't be a problem.

**Comment by miktuy** [comment]
Hi everyone! I try to solve this issue https://github.com/robotframework/robotframework/pull/3922.

**Comment by pekkaklarck** [comment]
PR #3932 by @miktuy looks good. I'll merge it once we start RF 4.1 development.
