### ISSUE TITLE
FORs and IFs aren't omitted when generating only report based on output.xml

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#3903]
Keywords, FORs and IFs inside tests aren't needed when generating only the report file, not log, as part of execution or separately using Rebot. Because they aren't needed, they are omitted already early during output.xml parsing to avoid the need to create matching model objects. This can save a considerably amount of memory with bigger output.xml files.

RF 4.0 changed output.xml so that FORs and IFs aren't anymore saved as `<kw>` elements but instead as `<for>` and `<if>` elements, respectively. In comments to #3423 @Lemonlemmings noted that currently only keywords, not FORs and IFs, are omitted due to this change. This isn't a big problem because it doesn't affect functionality, we just unnecessarily handle FORs and IFs even though they aren't used for anything. These structures ought to also be rare on the test case level so not too many is affected in general. Anyway, should be fixed.

**Comment by Lemonlemmings** [comment]
Hi, thanks for making this issue. 

I know this relates a little bit more to the JSON execution format I'm looking at, but is this better described as `__omit_body` than `__omit_keywords` now? If that is the case, it makes it far clearer what the function is doing.

**Comment by pekkaklarck** [comment]
The internal helper method name doesn't matter much but `ExecutionResultBuilder` has `include_keywords` argument that controls this behavior. We cannot rename that in a bug fix release and I'm not sure would `include_body` be good name when the functionality affects also setups and teardowns which aren't part of the body. At least with the argument it's probably best to just document that it affects also FORs and IFs. For consistency reasons it might then be better to leave `_omit_keywords` as is as well and only document/comment the behavior.

**Comment by pekkaklarck** [comment]
Turned out that when you use `ExecutionResult`, FORs and IFs will eventually be omitted. They are not omitted during output.xml parsing but after processing possible suite teardown failures all body items are removed (again) and FORs and IFs end up being removed. Still good to change output.xml parsing so that they are removed already at that point.
