### ISSUE TITLE
Usong `pathlib.Path` when saving programmatically modified results does not work

### ISSUE THREAD

**Issue by mhwaage** [robotframework/robotframework#3904]
Markupwriters currently only check for strings when determining whether they need to open a file for output or if they have been given an outputstream. This fails when they are fed a Path object, e.g. when an `ExecutionResult.save()` command is used. This can be remedied by also checking if the input object is pathlike. See also #3899.

**Comment by pekkaklarck** [comment]
Supporting also `Path` objects, not only strings, when saving `Result` objects back to disk is definitely a good idea, especially because the  `ExecutionResult` factory method already accepts `Path`. I actually consider this inconsistency a bug.
