### ISSUE TITLE
	UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa6 in position 2632017: invalid start byte

### ISSUE THREAD

**Issue by RasnaT** [robotframework/robotframework#3906]
while doing cat <filename> in robot the below errors reported. This issue is not permanent however seen multiple times in run. Any help in finding the root cause is really appreciated. Thanks.

KEYWORD ${Val} = SSHLibrary . Execute Command sed -n ''7627','33065'p' /var/log/master/log >my_log
KEYWORD ${retVal} = SSHLibrary . Execute Command cat my_log
Documentation:	
Executes command on the remote machine and returns its outputs.

Start / End / Elapsed:	20210324 14:51:20.083 / 20210324 14:51:22.036 / 00:00:01.953
14:51:20.083	TRACE	Arguments: [ 'cat my_log' ]	
14:51:20.083	INFO	Executing command 'cat my_log'.	
14:51:20.084	DEBUG	[chan 10] Max packet in: 32768 bytes	
14:51:22.035	TRACE	Return: None	
14:51:22.035	INFO	${retVal} = None	
14:51:22.036	FAIL	UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa6 in position 2632017: invalid start byte	
14:51:22.036	DEBUG	Traceback (most recent call last):

  File "python3.6/site-packages/SSHLibrary/library.py", line 1031, in execute_command
    stdout, stderr, rc = self.current.execute_command(command, sudo, sudo_password, timeout)
  File "python3.6/site-packages/SSHLibrary/abstractclient.py", line 293, in execute_command
    return self.read_command_output(timeout=timeout)
  File "python3.6/site-packages/SSHLibrary/abstractclient.py", line 333, in read_command_output
    return self._started_commands.pop().read_outputs(timeout)
  File "python3.6/site-packages/SSHLibrary/pythonclient.py", line 279, in read_outputs
    stderr, stdout = self._receive_stdout_and_stderr(timeout)
  File "python3.6/site-packages/SSHLibrary/pythonclient.py", line 292, in _receive_stdout_and_stderr
    stdout = (b''.join(stdouts) + stdout_filebuffer.read()).decode(self._encoding)

**Comment by pekkaklarck** [comment]
Either there's a but in SSHLibrary or you don't specify encoding correctly. In the latter case SSHLibrary should nevertheless report the error better. Anyway, this should be reported to SSHLibrary's tracker, not here.
