### ISSUE TITLE
Problem using option -E

### ISSUE THREAD

**Issue by Williamsbsa** [robotframework/robotframework#3907]
I was searching about the ```-v``` option in the ```robot --help``` guide and I found a example about the use of space between words: ```-v hi:Hi_World -E space:_ => ${hi} = `Hi World` ```.
But when I try this with my specific parameters I always receive this error message: ```[ ERROR ] option -E not recognized ```.
My robot's version is: 3.2.2

**Comment by pekkaklarck** [comment]
That option was deprecated in RF 3.1 and removed in RF 3.2 (#3085).
