### ISSUE TITLE
Expanding keywords recursively in log.html is broken

### ISSUE THREAD

**Issue by aaltat** [robotframework/robotframework#3911]
In RF 3, if I expand the log file I see this:
![image_rf3](https://user-images.githubusercontent.com/2665023/112793673-60d05380-906e-11eb-8b1d-375629d6a41b.png)

But in RF 4 I see this
![image_rf4](https://user-images.githubusercontent.com/2665023/112793693-6a59bb80-906e-11eb-91fd-aef13122e623.png)

I would prefer to keep the old functionality.

**Comment by pekkaklarck** [comment]
This was broken when keywords in log started to store their child keywords and messages in same list to preserve their order (#2086). Expanding keywords fails if any of the children happens to be a message. Easy to fix by explicitly excluding messages.
