### ISSUE TITLE
`Run Keyword If Test Failed` is executed when test is skipped

### ISSUE THREAD

**Issue by Pakkanen1** [robotframework/robotframework#3913]
Robot version: 4.0
Python: 3.9
OS: Windows 10

When using the `run keyword if test failed`-keyword in a test teardown and the test case is skipped, robot incorrectly recognizes this as a failed test case and executes whatever keyword `run keyword if test failed` points to.

Steps to reproduce:
1. Create a test suite with at least 1 test case that is skipped by the `skip if` or `skip` keywords.
2. Set test teardown to execute `run keyword if test failed` with any valid keyword name as parameter.
3. Run the test and check logs. Test teardown has executed the given keyword.

```
*** Settings ***
Test Teardown   Run keyword if test failed   Log  THIS SHOULD NOT BE EXECUTED

*** Test Cases ***
TestToSkip
	skip  skipping...
	Log  not gonna see this
```

**Comment by pekkaklarck** [comment]
We clearly forgot to take this into account when the SKIP status was introduced. Ought to be easy to fix.
