### ISSUE TITLE
robot.tidy removes indent within IF/ELSE IF/ELSE blocks

### ISSUE THREAD

**Issue by Ethernet-Packet** [robotframework/robotframework#3915]
With Robot Framework 4.0 (Python 3.7.2 on win32). The following code will be formatted incorrectly.

```robot
*** Test Cases ***
Test
    IF    True
        Log    x
    ELSE
        Log    y
    END
```

Result will be:

```robot
*** Test Cases ***
Test
    IF    True
    Log    x
    ELSE
    Log    y
    END
```

Tidy is called like:

```python
def format_robot_file(path):
    tidy = Tidy(use_pipes=False, space_count=4, line_separator='\n')
    tidy.inplace(path)
```

Nested FOR loops are formatted correctly.

**Comment by pekkaklarck** [comment]
First of all, I recommend you to test the new external [Tidy](https://github.com/MarketSquare/robotframework-tidy/). The Tidy included with RF itself isn't anymore developed further, but particular problem is a bug and needs to be fixed.

**Comment by Ethernet-Packet** [comment]
@pekkaklarck Thank you for this quick response. I know the new external Tidy but we need some time to make the transition. Right know we are using robot.tidy in pre-commit hooks and we are checking commits against it before merge.
