### ISSUE TITLE
Libdoc does not support libraries having name ending with valid spec or resource file extension

### ISSUE THREAD

**Issue by fabioz** [robotframework/robotframework#3919]
As a note, in my particular use-case, the library is named `RPA.JSON` and calling:

`python -m "robot.libdoc" RPA.JSON out.libspec`

gives an output such as:

`Spec file 'RPA.JSON' does not exist.`

If the library is renamed to something else it does work.

This seems to be happening because at:

https://github.com/robotframework/robotframework/blob/master/src/robot/libdocpkg/builder.py#L63

it's trying to treat the library name as if it was some file on the filesystem -- that doesn't seem to make sense based on the actual command line, so, I guess it's reusing that logic from some other use case?

**Comment by pekkaklarck** [comment]
Libdoc accepts earlier generated spec files as inputs and whenever it sees an input like `x.json` or `x.xml` it assumes its a spec file. It has never occurred that a library could have a name like that as well.

This ought to be pretty easy to fix. We could, for example, always import the given input if it doesn't exist regardless its name.

**Comment by pekkaklarck** [comment]
Same problem also with names ending with `.java` or with any valid resource file extensions `.robot`, `.resource`, `.txt`, `.tsv`, `.rst` or `.rest`. At least `Lib.REST` could actually occur in real life.
