### ISSUE TITLE
Sending `signal.CTRL_C_EVENT` to a Process also stops Robot Script

### ISSUE THREAD

**Issue by dschiller** [robotframework/robotframework#3924]
I want to send `signal.CTRL_C_EVENT` to a Process without stopping the Robot Script from Executing.

### MyTest.robot

```robot
*** Settings ***
Library  Libraries/LibProcess.py

*** Test Cases ***
Test End Process with CTRL C
  ${handle}  Start Process  myConsoleApp.exe
  Sleep  5
  Send Keys to Process  ${handle}
```

### Libraries / LibProcess.py

```py
from subprocess import Popen, PIPE
import signal, os, time, subprocess

def start_process(*args, stdout=PIPE):
    if stdout != PIPE:
        stdout = open(stdout, 'w')
    return Popen([*args], stdin=PIPE, stdout=stdout, stderr=PIPE)

def send_keys_to_process(process):
    os.kill(process.pid, signal.CTRL_C_EVENT)
```

### Execution

Actually the Behaviour is that the Robot Script also stops after executing `Send Keys to Process  ${handle}`.

```cmd
==============================================================================
MyTest
==============================================================================
Test End Process with CTRL C                                          Second signal will force exit.
Test End Process with CTRL C                                          | FAIL |
Execution terminated by signal
------------------------------------------------------------------------------
MyTest                                                                | FAIL |
2 critical tests, 1 passed, 1 failed
2 tests total, 1 passed, 1 failed
==============================================================================
Output:  D:\Work\Coding\Python\QALibs\Tests\Results\output.xml
Log:     D:\Work\Coding\Python\QALibs\Tests\Results\log.html
Report:  D:\Work\Coding\Python\QALibs\Tests\Results\report.html

Press Enter..
```

### Versions

```
Python 3.9.1
robotframework==4.0
Windows 10 x64
```

### Different other Tries

I also tried those Signals with same Behaviour:

```py
signal.SIG_DFL
```

All other provided Signals ( https://docs.python.org/3/library/signal.html#module-signal ) will not provoke `CTRL+C` nor be available on Windows.

I also tried `process.send_signal(signal.CTRL_C_EVENT)` instead of `os.kill(process.pid, signal.CTRL_C_EVENT)` with same Behaviour.

### Change Core

If I play a bit with `C:\Python39\Lib\site-packages\robot\running\signalhandler.py` and it's `_StopSignalMonitor().__call__()` method then there is a way to fix it. Unfortunately I don't know how to distinguish between a real `CTRL+C` within Robot Runner and the invoked one for the Child Process.

If I make the following Changes then it works as expected **randomly** ( No Run Stop on Process Signaling but on pressing `CTRL+C` inside the Robot Runner ):

#### robot / running / signalhandler.py ( Excerpt - Changed - Lines 2 to 3 )

```py
 1    def __call__(self, signum, frame):
 2        if not self._running_keyword:
 3            return
 4        self._signal_count += 1
 5        LOGGER.info('Received signal: %s.' % signum)
 6        if self._signal_count > 1:
 7            sys.__stderr__.write('Execution forcefully stopped.\n')
 8            raise SystemExit()
 9        sys.__stderr__.write('Second signal will force exit.\n')
10        if self._running_keyword and not JYTHON:
11            self._stop_execution_gracefully()
```

#### robot / running / signalhandler.py ( Excerpt - Original )

```py
1    def __call__(self, signum, frame):
2        self._signal_count += 1
3        LOGGER.info('Received signal: %s.' % signum)
4        if self._signal_count > 1:
5            sys.__stderr__.write('Execution forcefully stopped.\n')
6            raise SystemExit()
7        sys.__stderr__.write('Second signal will force exit.\n')
8        if self._running_keyword and not JYTHON:
9            self._stop_execution_gracefully()
```

If I don't press `CTRL+C` sometimes `self._running_keyword` is `True` sometimes it is `False`. Not sure why this happens. If I press `CTRL+C` instead it is reliable and `self._running_keyword` is always `True`.

**Comment by dschiller** [comment]
I also tried those Signals with same Behaviour:

```
signal.SIG_DFL
```

All other provided Signals ( https://docs.python.org/3/library/signal.html#module-signal ) will not provoke CTRL+C nor be available on Windows.

**Comment by pekkaklarck** [comment]
I believe the problem is that the signal you sent is sent to the whole process group which includes also the Robot process. You ought to be able to avoid that by using the [subprocess.CREATE_NEW_PROCESS_GROUP](https://docs.python.org/3/library/subprocess.html#subprocess.CREATE_NEW_PROCESS_GROUP) flag when starting the process.

Notice that the standard Process library sets that flag but its `Send Signal To Process` doesn't work on Windows. Enhancing it to support `CTRL_C_EVENT` event and `CTRL_BREAK_EVENT` (which you can send using `Terminate Process`) on Windows could be possible.

**Comment by dschiller** [comment]
Thanks a lot Pekka. That works!

### Libraries / LibProcess.py

#### Changed:

```py
from subprocess import Popen, PIPE
import signal, os, time, subprocess

def start_process(*args, stdout=PIPE):
    if stdout != PIPE:
        stdout = open(stdout, 'w')
    return Popen([*args], stdin=PIPE, stdout=stdout, stderr=PIPE, creationflags=subprocess.CREATE_NEW_PROCESS_GROUP)

def send_keys_to_process(process):
    os.kill(process.pid, signal.CTRL_C_EVENT)
```

#### Origin:

```py
from subprocess import Popen, PIPE
import signal, os, time, subprocess

def start_process(*args, stdout=PIPE):
    if stdout != PIPE:
        stdout = open(stdout, 'w')
    return Popen([*args], stdin=PIPE, stdout=stdout, stderr=PIPE)

def send_keys_to_process(process):
    os.kill(process.pid, signal.CTRL_C_EVENT)
```

**Comment by pekkaklarck** [comment]
Great that I was able to help! This stuff is really wonky and I only learned about it when working with the aforementioned Process library.

You might also want to change `stderr=PIPE` to `stderr=STDOUT` or `stderr=DEVNULL` to avoid possible deadlock if lot of content is written to the stderr stream.

**Comment by dschiller** [comment]
Unfortunately the Flag `creationflags=subprocess.CREATE_NEW_PROCESS_GROUP` forces the Process to not stop correctly with `process.send_signal(signal.CTRL_C_EVENT)` which doesn't happen if I don't use the `CREATE_NEW_PROCESS_GROUP` flag.
