### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1) on Robot > 3.2.2

### ISSUE THREAD

**Issue by Rantzur1992** [robotframework/robotframework#3932]
While running the following keywords:

```
Headless Chrome
    ${chrome_options} =     Evaluate    sys.modules['selenium.webdriver'].ChromeOptions()    sys, selenium.webdriver
    Call Method    ${chrome_options}    add_argument    headless
    Call Method    ${chrome_options}    add_argument    disable-gpu
    [Return]       ${chrome_options}
```

On version 4.0.1 with the latest selenium library, I get the following:

```
Submit Form                                                           | FAIL |
Parent suite setup failed:
ValueError: not enough values to unpack (expected 2, got 1)
```

It is thrown when running:
`    ${chrome_options} =     Evaluate    sys.modules['selenium.webdriver'].ChromeOptions()    sys, selenium.webdriver
`

**This is working correctly on Robot framework version 3.2.2**

**Comment by pekkaklarck** [comment]
Could you run tests with `--loglevel debug` and include traceback you get in log.html here?

**Comment by Rantzur1992** [comment]
I found it happens when I accept custom  capabilities like so:

`desired_capabilities: Union[str, dict, None] = None`

If I change it to

`desired_capabilities=None`

It works fine.

Note it does not happen on older versions of Robot.

**Comment by pekkaklarck** [comment]
Cannot help with this information only. Please provide the traceback. If you use something else than `Evaluate`, show the whole code.

**Comment by pekkaklarck** [comment]
Closing due to lack of information.
