### ISSUE TITLE
Remote: Support Unicode characters in range 0-255, not only 0-127, in binary conversion

### ISSUE THREAD

**Issue by v8sharma** [robotframework/robotframework#3934]
Attempting to pass a value u'\x88\x13' from python remote server causes a "ValueError: Cannot represent u'\x88\x13' as binary."

> pekkaklarck:
The problem here is that \x13 is a control character that's not allowed at all in XML and since the remote interface uses the XML-RPC protocol underneath it cannot be sent as-is. You are passing that character as a string and the Remote library tries to convert it into bytes that could then be transferred over the XML-RPC channels as a special Binary object.
Conversion to bytes is done simply by encoding the string to bytes using ASCII encoding. In your case that fails because the string also contains character \x88 that isn't in the ASCII range. I haven't tested this, but I believe you would be able to send these characters if you'd convert them to bytes yourself using, for example, Convert To Bytes keyword first.
It could also be argued that converting strings to bytes inside Remote should be enhanced. The current ASCII encoding approach means only bytes 0-127 are supported and 128-255 aren't. Arguably a better approach would be using Latin-1 encoding because then all Unicode characters 0-255 would be mapped to bytes with same ordinal:
'\x88\x13'.encode('latin-1')
b'\x88\x13'
This conversion might cause strange results, though, because the remote server on the other end wouldn't get a string but instead a Binary object. Explicit conversion to bytes and the sending bytes over might be better. Anyway, you can submit an issue about enhanced automatic conversion and we can think more about it when starting RF 4.1 development.

**Comment by pekkaklarck** [comment]
Converting all Unicode characters in range 0-255 to bytes using same ordinal would probably be a good idea. I consider that an enhancement rather than a bug fix so better wait until RF 4.1.

**Comment by pekkaklarck** [comment]
I don't consider this too high priority as you can already now pass bytes just fine. If you originally have a string, you just need to convert it to bytes first.
