### ISSUE TITLE
Skip entire test suite if condition is met

### ISSUE THREAD

**Issue by triblex** [robotframework/robotframework#3935]
The new skip feature in robot 4.0 is very handy and already being used - but it is only possible to skip a test case.
As far as i can see, there is no way to skip an entire test **suite**.
Right now (correct me if I'm wrong) dynamic exclude is not possible and skipping a test suite would need a skip condition in every test case in the suite that needs to be skipped dynamically.
A conditional keyword, like the `Skip If`, but for skipping entire test suite, would be a great enhancement to the already implemented skip functionality. This could either be a new keyword that potentially could only be used in `Suite Setup` or an expansion of the `Skip If` by adding an optional argument that allows for recursive skip.

Is this something that we would want to add, or are there other thoughts about this?

**Comment by Ethernet-Packet** [comment]
If you put the `Skip` or `Skip If` keyword into a `Suite Setup` every test will be skipped.

At least this suite:

```robot
*** Settings ***
Suite Setup    Skip

*** Test Cases ***
Test 1
    No Operation
    
Test 2
    No Operation
    
Test 3
    No Operation
```

Gives this result:
```
robot test.robot
==============================================================================
Test
==============================================================================
Test 1                                                                | SKIP |
Skipped in parent suite setup:
Skipped with Skip keyword.
------------------------------------------------------------------------------
Test 2                                                                | SKIP |
Skipped in parent suite setup:
Skipped with Skip keyword.
------------------------------------------------------------------------------
Test 3                                                                | SKIP |
Skipped in parent suite setup:
Skipped with Skip keyword.
------------------------------------------------------------------------------
Test                                                                  | SKIP |
Skipped in suite setup:
Skipped with Skip keyword.

3 tests, 0 passed, 0 failed, 3 skipped
==============================================================================
```

The same works if the `Skip` is placed in a higher `Suite Setup` in an `__init__.robot` file.

**Comment by pekkaklarck** [comment]
Yeah, skip in suite setup skips all tests in the suite.
