### ISSUE TITLE
Unable to filter tests based on tags if tags are added using 'Set Tags' Keyword

### ISSUE THREAD

**Issue by sumanth-manchala** [robotframework/robotframework#3936]
I am trying to add tags for each test by pulling up data from excel and I am unable to filter the test based on the tags from the command line using (--include or --exclude).  However, I see the tags assigned to tests in the report file.

Is this a caveat of the current implementation? If so, what would be a better approach to achieve this functionality.

Ps: I cannot use a third-party library.

**Comment by Ethernet-Packet** [comment]
Depending where you add these extra tags, I think you should be able to filter based on them during runtime, using a listener library.

**Comment by sumanth-manchala** [comment]
Initial Test
    ${test_data}=    Read Excel    Test.xlsx    testID
    Set Tags    ${test_data}[tags]

@Ethernet-Packet This is how I am adding the tests. When I use the start_suite listener, I couldn't find any of the tags attached to the test.

**Comment by Ethernet-Packet** [comment]
@sumanth-manchala `Set Tags` sets the tags of the currently running test or to all test in a suite if it is called from a `Suite Setup`.

> Adds given tags for the current test or all tests in a suite.
>
> When this keyword is used inside a test case, that test gets the specified tags and other tests are not affected.
>
> If this keyword is used in a suite setup, all test cases in that suite, recursively, gets the given tags. It is a failure to use this keyword in a suite teardown.

You call it from a test, which is running and at that point filtering is not possible. You cannot prevent a test from running at a point when the test is already running.

If you would call `Set Tags` from a `Suite Setup`  you could call a listener library method within the same `Suite Setup` right after setting the tags and do a filtering, before the tests start. In theory. In this case you would have to pass the filter expression as a separate variable to the execution to be able to filter as at this point the `--include` and `--exclude` values are not available.

**Comment by sumanth-manchala** [comment]
@Ethernet-Packet Thank you for the response, I misread that "the tags are added to current running test". I will try your approach
