### ISSUE TITLE
Rebot removes sourcename attribute from kw tag

### ISSUE THREAD

**Issue by rasjani** [robotframework/robotframework#3941]
Output.xml has kW tag with sourcename attribute.  This gets stripped away when rebot is used to reformatting the log.

Noticed this initially with robotstatuschecker: 

https://github.com/robotframework/statuschecker/issues/30

**Comment by pekkaklarck** [comment]
This was fixed in PR #3953 by @miktuy.

**Comment by pekkaklarck** [comment]
The `sourcename` attribute was added in RF 4.0 (#3750). It will be renamed to `source_name` in RF 7.0 (#4884).
