### ISSUE TITLE
Can't run winform exe

### ISSUE THREAD

**Issue by vb123er951** [robotframework/robotframework#3943]
Hi, I am testing a winform exe with robot-framework, but I cannot run the winform exe using `Run` (if use SciTE write au3 script and it executes successfully), can someone help about this problem?

I use Anaconda Python 3.6 with newest robot framework and autoitlibrary v1.1

here is my script
```
*** Settings ***
Library           AutoItLibrary

*** Variables ***
${winformexe}     D:\\practice\\HelloWorld\\HelloWorld\\bin\\Release\\netcoreapp3.1\\HelloWorld.exe

*** Test Cases ***
TC0
    [Documentation]    My first test case in ride
    Run    ${winformexe}
    Win Wait Active    Form1
    Control Set Text    Form1    \    [NAME:textBox1]    test
```

the command: `robot -d output -t TC4 Automating_program_1.robot`
and the result is
![image](https://user-images.githubusercontent.com/15091938/115692102-43528900-a391-11eb-8a3a-2ff904b88883.png)

p.s. I program the winform exe myself, it is a simple app that only contain a button and a textbox, some text will appear in textbox when push the button.

**Comment by pekkaklarck** [comment]
This seems to be AutoItLibrary problem rather than a problem in Robot Framework core.
