### ISSUE TITLE
`Run Keyword If Test Failed` does not work correctly if it is not first keyword in teardown and test is skipped

### ISSUE THREAD

**Issue by Pakkanen1** [robotframework/robotframework#3951]
Robot version: 4.0.1
Python: 3.9
OS: Windows 10

I found a bug month ago which was dealt with in issue #3913, but having a teardown keyword execute multiple `run keyword if test failed`-keywords still executes the given keyword when a test is skipped.

Steps to reproduce:

1. Create a test suite with at least 1 test case that is skipped by the skip if or skip keywords.
2. Set test teardown to execute a custom keyword that executes multiple `run keyword if test failed`-keywords.
3. Run the test and check logs. Only the first execution of `run keyword if test failed` didn't execute the given keyword.

```
** Settings ***
Test Teardown  Tear it down

*** Test Cases ***
Test that skips
    skip  Skipping...
    log   No gonna do this

*** Keywords ***
Tear it down
    run keyword if test failed  log  Now you dont!
    run keyword if test failed  log  Now you see me...
    run keyword if test failed  log  And now too...
```

![image](https://user-images.githubusercontent.com/5936882/116243636-d0ba2280-a76f-11eb-9de1-7b7551e4b7e3.png)

**Comment by pekkaklarck** [comment]
Looks strange. Need to investigate before RF 4.0.2.

**Comment by mihajlotomic** [comment]
We see the same when using `Run Keywords` in the `[Teardown]`  - we see that the teardown treats the test as failing when in fact it is skipped.
Failing:
```
*** Test Cases ***
Test 1
    Skip If  ${True}
    [Teardown]   Run Keywords  Log  1  AND  Log  2  AND  Run Keyword If Test Failed  Fatal Error  Shouldn't be here

Test 2
    Skip If  ${True}
    [Teardown]   Run Keywords  Log  3  AND  Log  4
```
![image](https://user-images.githubusercontent.com/4898894/116621186-a6936c80-a8f7-11eb-9c30-05dbf666bb5c.png)


Fatal error isn't triggered in the event that test passed:

```*** Test Cases ***
Test 1
    Skip If  ${True}
    [Teardown]   Run Keywords  Log  1  AND  Log  2  AND  Run Keyword If Test Passed   Fatal Error  Shouldn't be here

Test 2
    Skip If  ${True}
    [Teardown]   Run Keywords  Log  3  AND  Log  4
```
![image](https://user-images.githubusercontent.com/4898894/116621241-bca12d00-a8f7-11eb-8b3e-77f41b5256d8.png)

**Comment by pekkaklarck** [comment]
I was able to reproduce the problem. The simplest way to do that is this:

```robotframework
*** Test Cases ***
Example
    Skip
    [Teardown]    Teardown

*** Keywords ***
Teardown
    No Operation
    Run Keyword If Test Failed    Fail    Should not be executed!
```

Without that `No Operation` keyword everything works as expected, so basically executing any keyword in teardown changes the test status that remaining keywords see from SKIP to FAIL.
