### ISSUE TITLE
RobotFramework default keywords are not displayed in the project in Version 4.0.1

### ISSUE THREAD

**Issue by amithrchandran** [robotframework/robotframework#3956]
Mac OS - 10.15.7
RobotFramework - 4.0.1
Python - 3.7.7
Eclipse - Version: 2020-12 (4.18.0)

After installing the V4.0.1 using the command - pip3 install robotframework, the default keywords are missing. Refer screenshot attached.

<img width="699" alt="Screenshot 2021-04-29 at 12 42 00 PM" src="https://user-images.githubusercontent.com/54177098/116844582-1ad45580-ac01-11eb-8305-bc2c4fc57f6e.png">

After that i downgraded the robotframework to 3.2.2 using the command - pip3 install robotframework==3.2.2, the default keywords are displayed in the project. Refer screenshot attached

<img width="439" alt="Screenshot 2021-05-03 at 11 22 40 AM" src="https://user-images.githubusercontent.com/54177098/116844857-f0cf6300-ac01-11eb-8a23-90435d9c7a3e.png">

**Comment by pekkaklarck** [comment]
This is an issue with the editor/plugin, not with RF itself.

**Comment by amithrchandran** [comment]
You mean the RED Editor ?

**Comment by pekkaklarck** [comment]
Yes.
