### ISSUE TITLE
can't find tests.robot file

### ISSUE THREAD

**Issue by kailichou** [robotframework/robotframework#3963]
python: 3.8.9
OS: windows 10

I tried to run ` python -m robot tests.robot` but can't find tests.robot file.

robotframework installed via `python -m pip install robotframework`
```
[ ERROR ] Parsing 'tests.robot' failed: File or directory to execute does not exist.
```

**Comment by pekkaklarck** [comment]
Did you create such a file? If you did, it clearly isn't in the same directory where you run tests.

**Comment by kailichou** [comment]
@pekkaklarck I find it thanks.

Didn't use the same directory.
