### ISSUE TITLE
how to fix this problem?

### ISSUE THREAD

**Issue by hhhhhhogan** [robotframework/robotframework#3964]
I have add robotframework2selenium and occur this error unfortunately

FAIL : No keyword with name 'Select Window By Handle' found.

**Comment by pekkaklarck** [comment]
Yeah, there's clearly some problem with library installation or with taking the library into use. Hard to tell exactly what based on this information only. If you haven't been able to resolve the problem, you can try asking help on our Slack or other support forums listed at http://robotframework.org.
