### ISSUE TITLE
User keywords in parallel

### ISSUE THREAD

**Issue by rajeshkumartv** [robotframework/robotframework#3966]
We tried to run user keywords(written in ROBOT) in parallel with multithreading and looks like the internal context or state is messed up.

Ex:  
Thread1:
CALL_RO:
         CALL_R0_KW1
	CALL_R0_KW2
	CALL_R0_KW3

Thread2:
CALL_R1:
	CALL_R1_KW1
	CALL_R1_KW2
	CALL_R1_KW3

When the above threads which calls ROBOT nested KW’ are called, the robot framework is messing up execution by calling R1 KW inside R0 KW

Observed call sequence:
CALL_RO:
	CALL_R0_KW1
		CALL_R1:
			CALL_R1_KW1	
			CALL_R0_KW2
		CALL_R1_KW3

We need this feature and blocking us. 

Please let me know when can we expect this support?

Thanks,

**Comment by tw39124-1** [comment]
There are a number of issues with your post:

1) It doesn't contain enough information to help diagnose the problem. You claim "Robot is messing up" but you are using multi-threading, so by definition there is no guarantee that your keywords will be called in a specific order between the two threads. The CPU is free to schedule processing time between the two threads however it likes, and it may interrupt Thread 1 to execute Thread 2 (or vice versa) in whatever manner it chooses. That's just the nature of multi-threading I'm afraid. If you need to ensure something done by Thread 1 happens strictly before or after something done by Thread 2, then you need to synchronise them yourself. This is a pretty fundamental concept of multi-threaded programs.

2) Your post comes across as pretty rude, by saying things like "We need this feature and blocking us. Please let me know when can we expect this support?".  This is _your_ issue and nobody on this project (a lot of whom are volunteers giving up their time for free) is obligated to provide you with help when you clearly don't properly understand the concept of threading and cross-thread synchronisation.

I suggest you update the thread with more information about exactly what your code is doing, what keywords it is calling in what order, and how it is invoking them in a multi-threaded environment. Only then will anyone have enough information to begin to help you out.

**Comment by pekkaklarck** [comment]
Yes, Robot isn't thread safe in general and especially running user keywords in parallel is pretty much impossible. It would be a nice feature, but getting the framework into a shape where it would be possible will take time. We are working towards it but it's not too high priority. If this is very important feature for you, you can consider sponsoring development, but unfortunately I cannot immediately give any estimates how big/expensive task this would be. Anyway, if you are interested, a good first step would be joining [Robot Framework Foundation](https://robotframework.org/foundation/).

We already have #1792 tracking this particular enhancement so I close this issue.
