### ISSUE TITLE
option to abort if import library has an exception

### ISSUE THREAD

**Issue by KotlinIsland** [robotframework/robotframework#3975]
In my opinion I would much rather robot aborts immediately when an import can't be found instead of trying to continue and getting a confusing "keyword could not be found" later.

**Comment by pekkaklarck** [comment]
Have you tested `--exitonerror` option?

**Comment by KotlinIsland** [comment]
Thats exactly what I want, thankyou.

**Comment by KotlinIsland** [comment]
This option is documented very vaguely, it will exit running if anything logs as error, ie `robot.api.logger.error`. 

To anyone that finds this, you can use `BuiltIn()._context.fail(msg)` to report a failure instead of an error.

**Comment by pekkaklarck** [comment]
`logger.error()` signals that an error has occurred. You can use `logger.warn()` if that's a problem. Anything starting with an underscore is at least somewhat private and may change in the future.

**Comment by KotlinIsland** [comment]
I need to be able to log multiple failures within a keyword that's implemented in python, and `BuiltIn.fail` will exit the keyword immediately. see #3706
