### ISSUE TITLE
Support an exception hook/listenable or exception re-raise option

### ISSUE THREAD

**Issue by KotlinIsland** [robotframework/robotframework#3977]
I use PyCharm with my robot and find that the "Python Exception Breakpoint" feature doesn't work when debugging robot tests.

If there was some way to re-raise the exception at some point, PyCharm will then drop into a post mortem debug session with stack / local variables available.

The current way that robot stores the exception object (HandlerExecutionFailed/ExecutionFailures) strips the traceback object and type making a post mortem debug impossible.

[Heres something similar implemented in pytest-pycharm](https://github.com/jlubcke/pytest-pycharm/blob/master/pytest_pycharm.py)

And I'm sure there's plenty of other uses for an exception listener interface.

**Comment by pekkaklarck** [comment]
Could you clarify this? Did you add breakpoint to a library keyword or where?

**Comment by KotlinIsland** [comment]
While debugging python code PyCharm has a 'breakpoint on uncaught exception' feature. Robot captures all exceptions, so when debugging a keyword that is implemented in python any exception will not be caught by PyCharm.

**Comment by KotlinIsland** [comment]
I have managed to hack around in robot to bubble up the exception with original traceback in tact and re-raise it in `robot.utils.application.Application._execute` and this works the way I want, PyCharm is able to catch the exception and enter post mortem debugging.

**Comment by KotlinIsland** [comment]
@pekkaklarck I made a pr with some crude hacks to demonstrate the functionality.

**Comment by pekkaklarck** [comment]
I don't personally use debuggers much or at all so don't know how useful this would be. If more active debugger users find this useful and this could be added in non-hackish way, I don't have any objections about that. Have you @KotlinIsland worked with this lately and are you interested to continue the work?

**Comment by pekkaklarck** [comment]
No updates in over two years. Closing.
