### ISSUE TITLE
Defined in *.robot kw is used instead kw from library with another signature

### ISSUE THREAD

**Issue by miktuy** [robotframework/robotframework#3984]
lib.py
```
from robot.api.deco import keyword


class lib:
    @keyword("Do smth with ${smth} by ${handler}")
    def foo(self, smth: str, handler: str):
        print(smth, handler)
```

test.robot
```
*** Settings ***
Library  ./lib.py

*** Variables ***
${smth}=   lol
${handler}=   kek

*** Test Cases ***
Test
    Do smth with ${smth} by ${handler}

*** Keywords ***
Do smth with ${smth}
    Log  ${smth}
    Log  Whaaaaaaaaaaaaaaaaaaaaaaaaat!!!!!!!!!!!!!!!!!!
```

**Supposed result:**
Keyword "Do smth with ${smth} by ${handler}" from lib.py is used

**Actual result:**
![image](https://user-images.githubusercontent.com/56407674/119488390-2976de00-bd63-11eb-92ed-9644403835c2.png)

@pekkaklarck Hi! Is this expected behavior or bug?

Founded in robot 3.2.1
Reproduced in robot 4.0.2
![image](https://user-images.githubusercontent.com/56407674/119489288-35af6b00-bd64-11eb-89d4-a00ec1f5158d.png)

P.S. maybe this problem was described early and this issue is duplicate.

**Comment by pekkaklarck** [comment]
This is by design. User keywords have higher precedence than library keywords and since there's a matching user keyword library keywords aren't matched at all. Notice that if library keywords were matched, there would be two matching keywords which would itself be an error.
