### ISSUE TITLE
Add typings

### ISSUE THREAD

**Issue by KotlinIsland** [robotframework/robotframework#3990]
SeleniumLibrary has typings, can these be added to robotframework?

**Comment by pekkaklarck** [comment]
You mean type hints in code? We can start adding them when Python 2 support is gone. That will be done in RF 5 that we hopefully can start developing after the summer holiday season.

I don't think it's a meaningful goal to add type hints to all code base. They are often pretty ugly and verbose and don't always provide concrete benefits. Anyway, they make sense at least in the public APIs and when arguments are complex objects. Separate issues/PRs should be submitted about individual APIs there to add them.
