### ISSUE TITLE
Displayed paths in generated output files should not be absolute

### ISSUE THREAD

**Issue by mathze** [robotframework/robotframework#3992]
When executing a test suite or generating test documentation the full qualified path to the related source files is exposed.
This become a problem when sharing this output in issue reports (or anywhere else), because this paths may contain sensitive user/system information.

As far as I can see the `href`-paths itself are already relative. E.g. `testdoc` generates them like:
``` html
<a href="../Test.robot"><fullQualifiedPath>/Test.robot</a>
```
It would be nice if the display text could be reduced to most common root-directory or to the execution dir.
E.g. executing in dir `<rest of path>/mytests/` will give displayed source paths as `<a href="<whateverRealtivePath>/Test.robot">mytests(/<subdirs>)*/Test.robot</a>`

I hope I could express myself clear enough😊

P.S. I know this will not avoid the case where `inputs` and `outputs` have nothing in common or only the sensitive part. But from my perspective this is more a usage problem😉

**Comment by pekkaklarck** [comment]
I don't think this is a good idea for the following reasons:
- It's true that paths may contain sensitive information, but just showing relative paths doesn't fully avoid that problem. There could be sensitive information in the visible part anyway.
- Relative paths can be ambiguous. 

In other words, this change wouldn't fully fix the problem but would make usability worse. If you are concerned about sensitive information in outputs files, you can use e.g. `--prerebotmodifier` to remove it regardless where it is used.
