### ISSUE TITLE
`--exitonfailure` incorrectly initiated if test skipped in teardown

### ISSUE THREAD

**Issue by damienklotz77213** [robotframework/robotframework#3996]
Considering following Robot framework code (python 3.8.5 on Ubuntu 20.04)

```
*** Settings ***
Test Teardown  Should Be True  ${mybool}

*** Test Cases ***
Test1
    [Tags]  skip
    ${mybool}  Set Variable  False
    Set Global Variable  ${mybool}

Test2
    ${mybool}  Set Variable  True
    Set Global Variable  ${mybool}
```

With Robot Framework 3.2.2
`python -m robot --exitonfailure --noncritical skip .`

![image](https://user-images.githubusercontent.com/85257917/120552748-e9b19580-c3f7-11eb-83c1-7f15e355a546.png)

With Robot Framework 4.0.3
`python -m robot --exitonfailure --skiponfailure skip .`

![image](https://user-images.githubusercontent.com/85257917/120552763-f2a26700-c3f7-11eb-83e8-c21b8598d22e.png)

Test2 is PASS on Robot Framework 3.2.2 and FAIL on Robot Framework 4.0.3.
Is this behavior difference intentional ?

**Comment by pekkaklarck** [comment]
It's a bit strange the problem occurs only if the failure occurs in teardown. That also makes this issue less severe.

**Comment by pekkaklarck** [comment]
This problem occurs if a test is skipped in teardown regardless the approach. For example, using the `Skip` keyword in teardown is enough.
