### ISSUE TITLE
Unable to verify the response of my API where the text is in french language. Geeting error: UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 1: ordinal not in range(128)

### ISSUE THREAD

**Issue by Manisha0421** [robotframework/robotframework#3998]
The response of the API looks like this is Postman:
HTTP/1.0 400 Impossible d'obtenir les transactions [la date de début ne doit pas être supérieure à la date]

But in robot framework, the response is:
HTTP/1.0 400 Impossible d'obtenir les transactions [la date de d\xc3\xa9but ne doit pas \xc3\xaatre sup\xc3\xa9rieure \xc3\xa0 la date]

**Comment by Manisha0421** [comment]
@pekkaklarck I need to verify an API response which is in French language and contains some special characters. The response for the request looks like this in the Postman:
<?xml version="1.0" encoding="UTF-8"?>
<ccare>
    <response>
        <menu name="" ref=""></menu>
        <page title="" pageRef="">
            <table resizable="true">
                <tableHead currentPage="1" nbPages="1" nbRecords="0">
                    <cell size="200" filter="no-filter">
                        <text>ErrorMessage</text>
                    </cell>
                </tableHead>
                <tableData>
                    <row>
                        <cell size="200" filter="no-filter">
                            <text>HTTP/1.0 400 Impossible d'obtenir les transactions [de Date ne peut pas être vide si à Date est présent]</text>
                        </cell>
                    </row>
                </tableData>
            </table>
        </page>
    </response>
</ccare>
But when the same request is run in Ride IDE for robot framework, the response looks like:
<?xml version="1.0" encoding="UTF-8"?>
			<ccare>
			<response><menu name="" ref=""></menu>
							<page title="" pageRef="">
							<table resizable="true">
							<tableHead currentPage="1" nbPages="1" nbRecords="0">
							<cell size="200" filter="no-filter"><text>ErrorMessage</text></cell></tableHead>
							<tableData>
							<row><cell size="200" filter="no-filter"><text>HTTP/1.0 400 Impossible d'obtenir les transactions [de Date ne peut pas \xc3\xaatre vide si \xc3\xa0 Date est pr\xc3\xa9sent]</text></cell></row>
						</tableData>
						</table>
						</page>
						</response>
						</ccare>
So, when I try to use Parse XML method to parse the received response, I get the error:

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 452: ordinal not in range(128)
Because of which I am unable to proceed with the verification.
The Ride ide is not able to encode the special characters which is why the parsing is failing. Could you suggest a solution for this

**Comment by pekkaklarck** [comment]
As I wrote earlier, this problem isn't in Robot Framework itself simply because it doesn't support REST testing itself. It's not in RIDE either because it's only an editor. The problem could be in the library you use or its possible that you use the library wrong. It's hard to tell anything more about that because you didn't tell what library you use and how you use it.

I close this issue due to it not being related to RF itself. If you haven't already been able to resolve the problem, asking more help on our Slack or other such support forums is a good idea.
