### ISSUE TITLE
--tagstatcombine fails when combining with an unexisting tag

### ISSUE THREAD

**Issue by leeuwe** [robotframework/robotframework#3999]
[CombiningUnexistingTag.zip](https://github.com/robotframework/robotframework/files/6597470/CombiningUnexistingTag.zip)
when running `rebot --tagstatcombine KnownTagANDUnexistingTag output.xml` the combined tag stats remain empty.

I'd expect to see the KnownTag count in the combined stats.

**Comment by pekkaklarck** [comment]
I extracted the attached zip and executed the mentioned command in the created directory. Tag statistic show "KnownTag AND UnexistingTag" without any match tests and nothing more. In the generated report and log there's only test named "Faling test without tag" which doesn't, as the name implies, have any tags. For me all this looks fine. Could you clarify what doesn't work as you expect?

**Comment by leeuwe** [comment]
Closing this as I don't remember what the problem was I ran in to
