### ISSUE TITLE
`@{EMPTY}` is not a list

### ISSUE THREAD

**Issue by Noordsestern** [robotframework/robotframework#4000]
**Affected module: robotframework==4.0.3**

Considering the following exmaple:

```robot
*** Settings ***
Library     Collections

*** Variables ***
${CACHE}    @{EMPTY}

*** Test Cases ***
Add items to empty list
    FOR    ${i}    IN RANGE    0    10
        Append to List    ${CACHE}    ${i}
    END
```

`Append to List` keyword throws: 
```
20210604 13:47:17.352 - INFO - +----- START KEYWORD: Collections.Append To List [ ${CACHE} | ${i} ]
20210604 13:47:17.353 - FAIL - TypeError: Expected argument 1 to be a list or list-like, got string instead.
20210604 13:47:17.354 - DEBUG - Traceback (most recent call last):
  None
```

I expected the global variable `${CACHE}` be initialized with an empty, mutuable list. Is that expectation correct?

**Comment by pekkaklarck** [comment]
`@{EMPTY}` is a list (well, technically it's a tuple to make it certain it cannot be mutated), but when used like `@{EMPTY}` it is expanded and being an empty list expanding yields nothing. Bascailly
