### ISSUE TITLE
RobotFramework portable after version 3.1.2

### ISSUE THREAD

**Issue by LikHait** [robotframework/robotframework#4002]
Version 3.1.2 has possibility to add `robotframework/src/bin/` folder to PATH  variable to use RF without installation.
Folder `robotframework/src/bin/` was removed in version 3.2. Is there any way to use RF on newer versions without installation? (4.x)

**Comment by pekkaklarck** [comment]
This ought to be covered by the installation instructions. Notice also that this issue tracker is for bug reports and enhancement requests, Slack, email, etc. listed at robotframework.org should be used for questions.

**Comment by LikHait** [comment]
@pekkaklarck it looked for me as lost functionality that may be interpreted as defect. INSTALL.rst has just common information " it is recommended to add the locations where the runner scripts are installed into the PATH" but `robot` and `rebot` are not part of repo anymore

**Comment by pekkaklarck** [comment]
Did you see sections "Executing installed robot module" and "Executing installed robot directory"?

**Comment by LikHait** [comment]
Yes, it is another way. In 3.1.2 you can call just "robot" or "rebot" or run ./test.robot. Using the approach described sections "Executing installed robot module" and "Executing installed robot directory" you cannot do this
