### ISSUE TITLE
Deprecate built-in Tidy tool in favor of external Robotidy

### ISSUE THREAD

**Issue by bhirsz** [robotframework/robotframework#4004]
Code formatter robotidy - which is based on robot.tidy - is developing well. It's good time to deprecate built-in robot.tidy in favour of robotidy in RF 4.1.

Robotidy project url: https://github.com/MarketSquare/robotframework-tidy

It will require notes in the docs and deprecation warning when using robot.tidy.

**Comment by pekkaklarck** [comment]
I agree we can deprecate the built-in Tidy in favor of the much better external Tidy. If we deprecate it in RF 4.1, we probably can remove it already in RF 5.0. This ought to be enough for deprecation:

- [ ] Print a deprecation warning when Tidy is used.
- [ ] Add a note about deprecation to the Tidy section in the User Guide.
- [ ] Add a note about deprecation to Tidy's `--help` text.

In addition to the above, this deprecation needs to be mentioned in RF 4.1 release notes. The `deprecation` label helps with that.

**Comment by pekkaklarck** [comment]
The new Tidy now has docs at https://robotidy.readthedocs.io/. I assume that should be used when referring to the project instead of the project URL https://github.com/MarketSquare/robotframework-tidy/?
