### ISSUE TITLE
Testing Webview2 app using robot framework

### ISSUE THREAD

**Issue by Bhavnasewani** [robotframework/robotframework#4005]
I have an application developed using webview2.
It is a web application that would be driven by Microsoft Edge(Chromium). It would give a feel of Native/Desktop app
instead of web app to the end user.

I want to automate testing for this app using Robot framework. I have tried desktop libraries for scripting the test
cases but I am facing issue while locating the elements on screen.

I have tried Zoomba, Sikuli, Flaui, White but each one is failing, but when I researched more in this component I found an documentation which uses Dotnet, Selenium and Edge drivers for testing it.

https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/webdriver

Can someone help how do use Robotframework here

**Comment by pekkaklarck** [comment]
I don't know this domain well enough to be able to help. This issue tracker is for bug reports and enhancement requests so I close this issue.

**Comment by Bhavnasewani** [comment]
Maybe this can be considered as an enhancement request for Robot Framework?
Currently I believe we don't have anything for this latest feature

**Comment by Bhavnasewani** [comment]
So Can we consider this as an Enhancement to Robot Framework. This framework has been choice for many automation testers so am I but this new application is road blocker.

If it can be done using Selenium.. It should be possible for Robor framework

I just need initial guidance for communicating to Edge driver that I am using Webview2 (A desktop container)  and the application path as they have done it in this sample app:

        
This is a Dotnet code, I am sure this could be possible in Robot framework too. Just need your valuable guidance/direction as I am new to Robotframework.

        EdgeOptions edgeOptions = new EdgeOptions(false, "webview2");
	edgeOptions.BinaryLocation = @"C:\path\to\your\webview2\project.exe";
	string msedgedriverDir = @"C:\path\to\your\msededriver.exe's\directory";
	string msedgedriverExe = @"msedgedriver.exe";
	EdgeDriverService service = EdgeDriverService.CreateDefaultService(msedgedriverDir, msedgedriverExe, false);

	EdgeDriver e = new EdgeDriver(service, edgeOptions);
	e.Url = @"https://www.microsoft.com";

**Comment by pekkaklarck** [comment]
If it's possible with Selenium on Python, it certainly is possible with Robot as well. Possible enhancements related to it don't belong to RF core, though, but to SeleniumLibrary. If it doesn't support this already, it ought to be possible to enhance it. If that's not possible, they you at least ought to be able to create a plugin for SeleniumLibrary. Anyway, this issue isn't really related to RF core.
