### ISSUE TITLE
Keyword documentation scrollbar issues in a small browser window

### ISSUE THREAD

**Issue by asonkeri** [robotframework/robotframework#4012]
Small issue but nevertheless annoying one. When library documentation is opened in a small browser window, the scrollbar in the keyword shortcut menu is partly hidden under the main page scrollbar. This happens at least with Chrome 91 and Firefox 89. 
**Example of the issue in latest String library keyword documentation:**
<img src="https://user-images.githubusercontent.com/19153764/121562537-37468780-ca22-11eb-953e-b2cc6f6f7cc2.png" width=50% height=50%>

Additional irritating behavior in this setup happens when scrolling the keyword shortcuts. When reaching the end of the scrollbar the page underneath the opened keyword shortcuts menu keeps scrolling. The user loses the scroll position on the page if they close the shortcuts menu without clicking a shortcut link.

**Comment by pekkaklarck** [comment]
I can reproduce the problem and the fix looks good too. Do you @mkorpela have any comments about the issue or the fix?

**Comment by mkorpela** [comment]
About the issue: great that mobile/small screen use of docs is getting attention!
The fix seems to be ok.

**Comment by pekkaklarck** [comment]
Thanks for review @mkorpela and even bigger thanks for the PR @asonkeri!
