### ISSUE TITLE
robot test are running as non-critical by default

### ISSUE THREAD

**Issue by vinodimdevops** [robotframework/robotframework#4014]
We are running robot tests, as we know by default all tests would be considered as critical tests, until create a tag and  matched '--SkipOnFailure'.
However we haven't passing --SkipOnFailure, but still result of robot for the failed tests are not under critical row but coming under All tests, below is the screenshot:
<img width="352" alt="2021-06-16_15-46-14" src="https://user-images.githubusercontent.com/76451799/122242128-fb487200-ceba-11eb-9796-69f56d0c09c7.png">

This is happening with all of the jenkins jobs.

script running:
python robotTest.py master_si \
    --SFTC \
    --outputdir results \
    --output output.xml \
    --exclude FailingTest \
    --exclude some_value \
    --variable USERNAME:"xxxxxxx@x.com" \
    --variable PASSWORD:"xxxx" \
    --variable BROWSER:headlesschrome \
	--test "Some string" \
	tests/saa/some_script.robot

Really appreciate, looking into this, we don't find any issue at infra and code level, thought checking here, if this known issue and if there is any workaround or suggestion, would be really helpful

**Comment by pekkaklarck** [comment]
That screenshot clearly isn't from Robot Framework's own logs or reports because we have removed the criticality concept altogether. What tool are you using that has this kind of output? Most likely this issue belongs to its tracker.

**Comment by vinodimdevops** [comment]
Thanks of your response, we are aware that criticality concept has been removed, by default all test should run as critical tests.
Above tool are based on jenkins robotframework plugin, this results are similar what fetched in outpul.xml /report.html.

Here is the report.html
What expected: <img width="864" alt="2021-06-17_17-43-48" src="https://user-images.githubusercontent.com/76451799/122440593-9cefc200-cf94-11eb-81dc-9b6f8a856074.png">

What is currently behaving? No count in **Critical Tests** but showing all tests as 1.
<img width="840" alt="2021-06-17_17-53-25" src="https://user-images.githubusercontent.com/76451799/122441085-1be4fa80-cf95-11eb-8d88-6d5054965c67.png">

As you can see 2nd screenshot , there is no Critical Tests row, as there in first screenshot, first shows total as 1, if there is any workaround or suggestion, would be really helpful

Let me know if you need any specific details.

**Comment by pekkaklarck** [comment]
The latter screenshot clearly is from RF 4.0.x and the earlier from some earlier RF version. Both look exactly as expected. In the former there are Critical Tests and All Tests rows that contain the exact same test. In the latter there's only All Tests because the whole criticality concept has been removed. Could you clarify what problem you see here?

**Comment by vinodimdevops** [comment]
Both are the report generated by two different machines with same OS version, running with RF 4.0.X, here is the screenshot of package installed:
<img width="801" alt="2021-06-18_21-49-23" src="https://user-images.githubusercontent.com/76451799/122614811-4317f680-d07f-11eb-8286-02ef6a5fcde2.png">

Previously we were getting Critical Test as row in the robot test report, so same we were expecting here too, but as you confirmed criticality concept has been removed from RF4.0.X onwards, so second screenshot is correct report. So I think we are good now.
But still why report on first machine i.e. first screenshot report, still shows Critical Tests row. We have few machines where we upgraded to latest RF4.0.X and few one where we are directly installing latest RF4.0.X, so after upgrade from RF3 to RF4 or by installing RF4 on any machine, in both cases there should be No Critical Tests row should be visible.

**Comment by pekkaklarck** [comment]
Report with Critical Tests and All Tests has for certain been created by RF < 4.0. If you still have the report, you can view the source and find the generator header from the head section.

Is there still something unclear or can this issue be closed?

**Comment by vinodimdevops** [comment]
Hi @pekkaklarck, Thanks for all clarifications, really appreciate, yes we are good to close this issue 👍
