### ISSUE TITLE
An abnormal interrupt occurred during operation ,based on win10's cmd

### ISSUE THREAD

**Issue by paopaoaichouchou** [robotframework/robotframework#4017]
An abnormal interrupt occurred during operation ,based on win10's cmd.
![image](https://user-images.githubusercontent.com/77908773/122718998-30303c80-d2a0-11eb-9e1d-5c76f9b069dd.png)

**Comment by paopaoaichouchou** [comment]
This question comes up occasionally

**Comment by pekkaklarck** [comment]
I'm sorry but it's impossible to help you with this information alone. Notice also that if you aren't certain this is a bug in Robot Framework itself and are mainly looking for help, it would be better to send question to actual support forums such as our Slack and email list. This issue tracker is for bug reports and enhancement requests in Robot Framework core.
