### ISSUE TITLE
Auto adapt column width in log.html

### ISSUE THREAD

**Issue by jin-harmoney** [robotframework/robotframework#4025]
Current view:

![image](https://user-images.githubusercontent.com/73221968/123661981-4c4e5380-d835-11eb-8373-9d960ec76db4.png)

More readable view:

![image](https://user-images.githubusercontent.com/73221968/123662118-730c8a00-d835-11eb-842a-2ad6882ead4d.png)

I would gladly provide a PR if desired.

With some fiddling around locally, I found that adding the following in https://github.com/robotframework/robotframework/blob/681d359d39adc8418873e3eec05adade185a166d/src/robot/htmldata/rebot/common.css should be sufficient:

```
table {
    table-layout: auto;
    white-space: nowrap;
    empty-cells: show;
    font-size: 1em;
}
```

**Comment by pekkaklarck** [comment]
Could you please clarify the problem you have with tables? Is it only with statistics or with all? The proposed fix changes all tables which most likely isn't a good idea. In addition to that, `white-space: nowrap` is generally problematic with long values. Long values is the reason we currently use `word-wrap: break-word`.

**Comment by jin-harmoney** [comment]
@pekkaklarck sorry for the late response, I was on holiday.

All tables now have a fixed width (65em), causing word wrapping (see first screenshot in my first comment). Removing `width: 65em` from the `.statistics` class also fixes the issue for me. The table stays small when it can, but it expands up to the window size when necessary due to long suite/test names.

**Comment by jin-harmoney** [comment]
@pekkaklarck changing `width` to `min-width` also fixes the readability of the statistics table when having long suite names, while keeping the advantage of having a word-wrap on smaller screens. I provided a PR for the proposed change.

**Comment by pekkaklarck** [comment]
I tested this locally and didn't like it too much. Two problems:
- Different statistic tables can end up having different widths.
- There's no upper limit. This would be easy to fix with `max-width`, but the above issue still remains.

There are plans to redo the whole log and report in somewhat near future and I wouldn't like to spend too much time enhancing the current ones. A simple solution to give a bit more room for longer suite names would be increasing the width from `65em` to `70em` or `75em`. That should then be also done for `#header`.

**Comment by jin-harmoney** [comment]
@pekkaklarck thank you for validating my proposal.

- When all your tables are smaller than `65em`, they all have the same width, so it doesn't look weird visually. Only in the more extreme cases (like mine), you'll have different sizes for the tables. Personally, my wrapping problem makes the log file near useless. The only thing you can do is `ctrl+F`. Imo readability is more important than equal table width.
- Why would you need an upper limit? The table sizes with the screen size, so you're giving control to your users (they can resize their screen) instead of making the decision for them.
- As a developer, I fully understand you don't want to spend time on something you're planning to refactor, but it's a single line of css. Unless you see more impact. I'll gladly extend my PR.

**Comment by jin-harmoney** [comment]
Closing this based on the feedback on my PR: https://github.com/robotframework/robotframework/pull/4764#issuecomment-1789411803.

**Comment by pekkaklarck** [comment]
Names in the suite statistics often grow long, they contain also the parent suite name, so the 65em limit is often hit. Suite names typically wrap well, so this typically doesn't cause much problems. With the proposed change, tables would have different widths which in my opinion doesn't look good.

I believe a max-width would be good, because otherwise on wide monitors the actual statistics can end up being very far away from tag and suite names.

Could you clarify your wrapping problem a bit more? If it's really bad, I can be convinced that table widths being different is a smaller issue. We could also consider other alternatives like making tables a bit wider than the current 65em.

**Comment by jin-harmoney** [comment]
@pekkaklarck we have around 1000 tests, so the statistics table is very long. If the suite names are not wrapped, you can still see the structure while scrolling through the table.

This is an example with only 4 tests, which are largely structured under api, gateway and UI.

With wrapping:

![image](https://github.com/robotframework/robotframework/assets/73221968/cff650c9-76a8-4f2b-a887-7a25240bf839)

Without wrapping

![image](https://github.com/robotframework/robotframework/assets/73221968/95bce058-21e4-4f98-a525-f18a91df23b7)

What I'm trying to indicate is that this part:

![image](https://github.com/robotframework/robotframework/assets/73221968/305c4eef-d5b0-41ff-b9e3-fe1c6a8d01af)

remains stable while scrolling. If you enable wrapping, it is not stable, so you get quickly lost during the scroll.

**Comment by jin-harmoney** [comment]
@pekkaklarck it's been a long time, but I'd like to reopen this issue anyway, since it keeps bugging me.

This is what I see right now (which is not too exceptional I think, just 2 tests in a nested suite structure):

<img width="1698" height="1291" alt="Image" src="https://github.com/user-attachments/assets/d3a711b2-4ba1-4321-9c1f-1451db2319cc" />

With my proposed change (#4764 ) , this changes in the following:

<img width="1698" height="1291" alt="Image" src="https://github.com/user-attachments/assets/2c14c59a-0085-41cc-b15c-8d53f51d83da" />

Yes, the tables do not have the same width, but the first screenshot is just impossible to read and it only contains 2 tests.

Could you reconsider merging the PR?
