### ISSUE TITLE
robotframework-pythonlibcore==3.0.0 

### ISSUE THREAD

**Issue by emerisier** [robotframework/robotframework#4029]
this version of pythonlibcorre blocks loading of robotframework-seleniumlibrary
error message is : Importing test library 'SeleniumLibrary' failed: ImportError: cannot import name 'PY2'

the solution is downgrade to robotframework-pythonlibcore==2.2.1

**Comment by tysonite** [comment]
Why don't you report it to https://github.com/robotframework/PythonLibCore ? :-)

**Comment by pekkaklarck** [comment]
This is actually a problem in SeleniumLibrary. Its last Python 2 compatible version should have pinned PythonLibCore version it uses to a version that is certain to support Python 2. Anyway, this isn't the right tracker.

**Comment by emerisier** [comment]
sorry tysonite, thanks pekkaklarck
