### ISSUE TITLE
`log.html` doesn't render html or new line in document section

### ISSUE THREAD

**Issue by zeeshanyshaikh** [robotframework/robotframework#4031]
Initial documentation of testcase/testsuite is always shown in single line in `log.html` even if text is added in multi line.
For eg if added multi line string in initial documentation. 
```
*** Settings ***
Documentation            Testing some initial documentation
...                      Making sure the documentation spans multiple lines
...                      Because trying to see changed behavior.
```

Tried with multiline variable string and `Set Suite Documentation` keyword
```
${data}      Set Variable     this is set
...                multiline variable
...                values
Set Suite Documentation     ${data}     append=True
```
Tried with appending *\*HTML\**
```
${htmldata}      Set Variable     *HTML* <b>Hello!</b>
Set Suite Documentation     ${htmldata}     append=True     top=True
```
Tried with `Catenate`
```
${data} =      Catenate     SEPARATOR=\n    
...    this is set
...    multiline variable
...    values
Set Suite Documentation     ${data}     append=True     top=True
```

But the new line is not rendered in `log.html` 's documentation section.

![image](https://user-images.githubusercontent.com/6223015/124110680-1c49bf00-da86-11eb-8e42-cb9f412b6e68.png)

**Comment by zeeshanyshaikh** [comment]
This worked.. using global variable for `\n` =>`${\n}`

```
${data} =      Catenate     SEPARATOR=${\n}    
...    this is set
...    multiline variable
...    values
Set Suite Documentation     ${data}     append=True     top=True
```

**Comment by pekkaklarck** [comment]
It may sounds strange, but this behavior is exactly as designed. You can read more about documentation formatting here:
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#documentation-formatting

It's strange that `${\n}` works. Most likely you are on Windows where it is replaced by `\r\n` and code somewhere considers that `\r` to be a newline as well. This isn't a feature you can rely on, though. If you want to force individual lines, use `\n\n` as the separator or leave empty lines (i.e. lines with just `...`) where needed.
