### ISSUE TITLE
Support for `typing.Callable` used in decorators that transform signatures and `typing.ParamSpec`

### ISSUE THREAD

**Issue by KotlinIsland** [robotframework/robotframework#4032]
Decorators that transform function signatures are not considered properly.
In this example robot will send a string to the keyword, not an integer as the actual type specifies:
```py
from functools import wraps
from typing import Callable

def some_decorator(fn: Callable[[str], None]) -> Callable[[int], None]:
    @wraps(fn)
    def wrapper(a: int) -> None:
        print(type(a))
        fn(str(a * 2))

    return wrapper


@some_decorator
def some_keyword(a: str) -> None:
    print(type(a))
```

Also perhaps `typing.ParamSpec` should be considered when this functionality is implmenented:
ParamSpec([PEP-612](https://www.python.org/dev/peps/pep-0612/)) describes a method of typing the forwarding of a functions parameters in a generic way.

**Comment by pekkaklarck** [comment]
The reason Robot sends that keyword a string is that `typing.get_type_hints(some_keyword)` returns the type hints of the original function. [functools.wraps](https://docs.python.org/3/library/functools.html#functools.wraps) preservers original `__annotations__` similarly as it preserves e.g. `__name__` and `__doc__`. If you want to override the original type hints, but preserve name etc., you need to use something like this:

```python
def some_decorator(fn: Callable[[str], None]) -> Callable[[int], None]:
    def wrapper(a: int) -> None:
        print(type(a))
        fn(str(a * 2))
    annotations = wrapper.__annotations__
    wrapper = wraps(fn)(wrapper)
    wrapper.__annotations__ = annotations
    return wrapper
```
