### ISSUE TITLE
 --listener RobotStackTracer results in different semantics

### ISSUE THREAD

**Issue by DirkRichter** [robotframework/robotframework#4033]
Using parameter **--listener RobotStackTracer** in regular robot run results in different test result (pass vs fail):

running **robot Test.robot**
![grafik](https://user-images.githubusercontent.com/20930315/124252792-a26a1200-db27-11eb-9ab2-8d7d083d28e4.png)

running **robot --listener RobotStackTracer Test.robot**
![grafik](https://user-images.githubusercontent.com/20930315/124253002-dcd3af00-db27-11eb-9a02-395609f02688.png)

This --listener RobotStackTracer is now used in latest pabot version and i wonder, why my tests fail with pabot but pass in robot.

**Versions**:
Windows 10
python 3.9.6
robotframework-pabot           2.0.0
robotframework                 4.0.3

**Comment by pekkaklarck** [comment]
Does this work with some RF version or why you consider this regression? Are you sure the problem isn't in RobotStackTracer?

**Comment by DirkRichter** [comment]
You are right: The problem could just be RobotStackTracer. I updated the title. The workaround is this:
${res} =  pop from dictionary  ${d}  x
Thus variable evaluation semantic is different in case of RobotStackTracer...

**Comment by pekkaklarck** [comment]
Most likely RobotStackTracer is evaluating variables it sees which isn't a good idea. Please submit an issue to its tracker.

**Comment by DirkRichter** [comment]
thx. moved to https://github.com/MarketSquare/robotframework-stacktrace/issues/2
