### ISSUE TITLE
`@{varargs}` with default value in user keyword arguments not reported as error correctly

### ISSUE THREAD

**Issue by NeodaTech** [robotframework/robotframework#4034]
I have the following keywords
```
dummy keyword
    [Arguments]  @{param}
    ${len} =  get length  ${param}
    FOR  ${Item}  IN  @{param}
        log to console  ${Item}
    END

dummy keyword with default
    [Arguments]  @{param}=@{EMPTY}
    ${len} =  get length  ${param}
    FOR  ${Item}  IN  @{param}
        log to console  ${Item}
    END
```
and a Testcase
```
dummy
    @{List} =  create list  Hello  World
    ${status}  ${unused} =  run keyword and ignore error  dummy keyword  ${List}
    ${status}  ${unused} =  run keyword and ignore error  dummy keyword  @{List}
    ${status}  ${unused} =  run keyword and ignore error  dummy keyword with default  ${List}
    ${status}  ${unused} =  run keyword and ignore error  dummy keyword with default  @{List}
```
This leads to the following output:
```
['Hello', 'World']
Hello
World
Hello
World
| FAIL |
Keyword 'dummy keyword with default' expected 0 to 1 arguments, got 2.
```

I encountered the following issue, that a List-Argument i pass to a Keyword is interpreted differently depending on if i define a Default-Parameter or not. Can someone explain this behavior ?

The attached file is a robot HTML Logfile but for GitHub i added a ".log" so it can be uploaded.

[log.html.log](https://github.com/robotframework/robotframework/files/6763230/log.html.log)

I use python 3.9 and robotframework 4.03 on Windows 10

**Comment by pekkaklarck** [comment]
List arguments do not accept default values. The problem here is that such situation isn't detected and reported as an error correctly.
