### ISSUE TITLE
Support `${var}[key]` syntax with lists that allow also key access

### ISSUE THREAD

**Issue by VernonCrabtree** [robotframework/robotframework#4037]
While variable expansion like this:
    ${config['browser']}
works fine on my ${config} object, it fails when indexed like this:
    ${config}[browser]
with error: 
    robot.errors.ExecutionFailed: Series '${config}' used with invalid index 'browser'.

I would have expected this to work

**Comment by pekkaklarck** [comment]
Can you create a concrete, but simple, example demonstrating the problem?

**Comment by VernonCrabtree** [comment]
```
*** Test cases ***
X
    ${X}    Evaluate    pandas.Series(data={'a': 1, 'b': 2, 'c': 3}, index=['a', 'b', 'c'])
    Log     ${X['a']}   console=True
    Log     ${X}[a]     console=True    # This fails currently

```

**Comment by VernonCrabtree** [comment]
Result from above is:
```
PS C:\Users\a480438\s> robot .\Pandas.robot
==============================================================================
Pandas
==============================================================================
X                                                                     .1
X                                                                     | FAIL |
Series '${X}' used with invalid index 'a'. To use '[a]' as a literal value, it needs to be escaped like '\[a]'.
------------------------------------------------------------------------------
Pandas                                                                | FAIL |
1 test, 0 passed, 1 failed
==============================================================================
Output:  C:\Users\a480438\s\output.xml
Log:     C:\Users\a480438\s\log.html
Report:  C:\Users\a480438\s\report.html
```

**Comment by pekkaklarck** [comment]
Thanks, I was able to reproduce the problem with the example above.

In my case the failure was a bit worse, though, and I got this error:
> AttributeError: 'NoneType' object has no attribute 'islower'

The above error occurred in code that was trying to get the name of the Series object to be used in the error message you got. Not sure why you didn't get that, but I suspect it has something to do with Robot or Pandas version. Anyway, that particular problem I already fixed locally and now I get the exact problem you see.

The reason for the "invalid index" error is that [Series]https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html) is not technically a mapping but an array. More precisely, it doesn't implement [collections.abc.Mapping](https://docs.python.org/3/library/collections.abc.html#collections.abc.Mapping) and thus Robot's [is_dict_like](https://github.com/robotframework/robotframework/blob/master/src/robot/utils/robottypes3.py#L72) returns False. It's detected to be a list by [is_list_like](https://github.com/robotframework/robotframework/blob/master/src/robot/utils/robottypes3.py#L66), though, and thus the code handling `${x}[y]` assumes `y` to be an index, not a key.

Although Series isn't a Mapping, it still supports accessing values by keys and thus that not being possible using the `${x}[y]` syntax is unfortunate. Some ideas that we could possibly do:
1. When we detect that something is a list and items are accessed with something that's not an index (or slice), try to access the item with the given value anyway. This ought to solve the issue with Series and, if we do this extra step only when index detection fails, this ought to be backwards compatible as well.
2. Detect that the object supports "mixed mode" and in that mode try both key and index access. I'm afraid this kind of detection is not possible in generic manner, but we possibly could special case Series and then other similar objects in the future.

I'll prototype the approach 1. above and see how it could work. If it works nicely and isn't overly complicated, it could be still included into RF 4.1. The aforementioned fix for getting the type name will nevertheless be included.

**Comment by VernonCrabtree** [comment]
I much prefer option 1.  Better to ask forgiveness and all that

I already have another weird difference (both error situations, so doesn't matter so much) with this syntax and a custom object (so in this case I can customize the object behavior) - the point being that adding Series specifically won't help general use of this nice feature.

**Comment by pekkaklarck** [comment]
Supporting "mixed mode" wasn't overly complicated. I try to get RF 4.1 rc 1 out tomorrow. Hopefully you @VernonCrabtree can test that it works with Pandas as you expect.
