### ISSUE TITLE
Unable to run dry mode since 4.1 if "Set Tags" keyword contains variables defined on runtime

### ISSUE THREAD

**Issue by krassowski** [robotframework/robotframework#4044]
Starting with obligatory ["it affects my workflow" xkcd](https://xkcd.com/1172/), I wanted to let you know that #4007 (#3985) hit us on https://github.com/krassowski/jupyterlab-lsp/pull/647 - our tags use variables which are only defined by other keywords that are not run in the dry mode, which led to our dry checks failing since 4.1 release. In a way dry runs became incompatible with codebases with runtime-generated tags. I wonder how to proceed beyond pinning the version to 4.0 for now:
- is there a way to disable running "set tags" (and friends) in dry mode?
- is there anything else I can do to ignore failures in "set tags" if I don't care about absence of specific variables in dry mode? I guess I could conditionally defined variables to be have an empty/dummy string for dry mode - is such a conditional definition possible without writing custom Python plugin?

**Comment by pekkaklarck** [comment]
Dry-run shouldn't care about variables so this is definitely a regression. I don't think this is severe enough to warrant an immediate RF 4.1.1 release, though.
