### ISSUE TITLE
When using `--exitonfailure` and `Skip If` keyword is being used in a test setup, the rest of the test cases within the test suite fail

### ISSUE THREAD

**Issue by chezkasalvador** [robotframework/robotframework#4046]
**Pre requisite:**
Fail option should include `--exitonfailure`

**Steps to reproduce:**
1. Write a test case with a setup that skips if the condition is true
2. Write a valid test case after test case no. 1
3. Run and observe if test case no. 2 would proceed to run

**Expected:**
Test case no. 1 will skip but test case no. 2 will proceed to run since the rest of the test cases are valid and passing individually

**Actual:**
Test case no. 1 skips but test case no. 2 exits upon failure

**Notes:**
1. The rest of the test cases that ran after the test case with setup containing `skip if` keyword also failed and exited upon failure.
2. When `--exitonfailure` is not used, all the test cases runs as expected.

**See attached recording:**
https://user-images.githubusercontent.com/51893264/127142692-e1f87aed-6be7-43a9-83a9-50627670bdc8.mov

To replicate this issue, you can run the following:
```*** Settings ***
Default Tags    skip-test

*** Test Cases ***

Skipped Test
    [Setup]	skip if     True
    log     this test ran  

Failed Test One
    log     failed test one

Failed Test Two
    log     failed test two

**Comment by pekkaklarck** [comment]
Which RF version did you use? Some related problems, sichs as #3996, were fixed in RF 4.1.

**Comment by chezkasalvador** [comment]
I was using the older version. I already updated RF to 4.1 and it now works. Thanks for the response!

**Comment by pekkaklarck** [comment]
Thanks for the update. I was worried I had missed some corner case when fixing #3996.
