### ISSUE TITLE
Problem with newline \n at end of string

### ISSUE THREAD

**Issue by FrankHGW** [robotframework/robotframework#4048]
Hello, 
I will read a string as the following:
**${stag}    yash.Execute Command   ${id}   show evcs evc inband-evc stag**
After this,  ${stag} is:
stag : 16
As I am only interested in the number ( range from 0 -4095), I do the following:
${stag_result} =    Fetch From Right    ${stag}    :${SPACE}
stag_result=16

This is at first sight what I want, but unfortunately there is (invisible) a newline at the end of the number '16'.

And therefore the following command does not work:
${integer} = Convert To Integer ${stag_result}

I have not been able to remove the newline so far. the following is unfortunately without effect:
${stag_result}= Remove String ${stag_result} \n

Does anyone have an idea ?

thanks in advance

**Comment by pekkaklarck** [comment]
I tested that
```
Convert To Integer    10\n
```
works fine so newline at the end doesn't seem to matter. Are you certain you have a newline there and not, for example, the null byte? What exact error do you get from conversion?

**Comment by FrankHGW** [comment]
Ok, thanks. I will check this.

**Comment by FrankHGW** [comment]
I have figured it out now, this is how it works.
The only stupid thing is that you can't really see \n\r.
Therefore one does not recognize the problem immediately

    ${stag} is:   'stag : 16\r\t'

    ${result} =    Fetch From Right    ${stag}    :${SPACE}
    log   result1=${result}    console=y

    ${result} =    Fetch From Left    ${result}    \r\n
    log   result2${result}    console=y

    ${integer}=  Convert To Integer  ${result}\r\n
    log   integer=${integer}    console=y

**Comment by pekkaklarck** [comment]
It cannot be just due to `\r\n` because `int('16\r\n')` works just fine. You showed error

> ValueError: invalid literal for int() with base 10: '1256

which contains an extra `'` so most likely the value is something like `'1256\r\n`.

You can use `formatter=repr` with the Log keyword to see special characters like `\r` and `\n` better.

It seems to me there's no problem on RF side so I close this issue.

**Comment by FrankHGW** [comment]
Thanks

**Comment by FrankHGW** [comment]
When  ${stag}  =  '1256\r\n'
I am not able to remove the quotation marks  '
${result} = Remove String ${stag}   '
has no effect.
