### ISSUE TITLE
Libdoc: Using python decorator for keyword generates incorrect documentation

### ISSUE THREAD

**Issue by amittendulkar** [robotframework/robotframework#4058]
I am using a python library with a decorator for the purpose of logging all arguments passed to any keyword like below (using RobotFramework 4.0.1),

```python
# MyLib.py
from robot.api.logger import info, debug

def log_func(func):
  def inner1(*args, **kwargs):
    info(f'Inside {func.__name__}')
    debug(f'Arguments: {args}, {kwargs}')
    r_val = func(*args, **kwargs)
    info(f'Exiting {func.__name__}')
    return r_val

  return inner1


class MyLib:
  @staticmethod
  @log_func
  def activate_config_file(arg1: str = 'val1', arg2: int = 0):
    # Do something with the arguments

  # other keywords
```

When I try to generate the documentation for `activate_config_file` keyword I get the following documentation,
![image](https://user-images.githubusercontent.com/18111340/128841645-e7923645-c04f-42be-970b-41a212e2591d.png)

It seems the decorator is coming in the way while deciding the arguments. How can we overcome this issue?

**Comment by pekkaklarck** [comment]
Use `functools.wraps` as explained in the User Guide:
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#using-custom-decorators
