### ISSUE TITLE
[Question] How to substitute ${/} variable?

### ISSUE THREAD

**Issue by wasteland-rider** [robotframework/robotframework#4067]
Hello. For my project I parse variables from robot resource file and put them into instance of Variables class.
My script looks something like this:
```python
FILENAME = '/path/to/Paths.robot'
import_variables = RobotParser().parse_resource_file(FILENAME).variables
vars_ = Variables()
vars_.set_from_variable_table(import_variables)
print(vars_.as_dict())
```
Paths.robot file looks like this:
```robot
*** Variables ***
${suite_tree}   ${CURDIR}/../suite_tree
${real_tree}    ../real_suite
${real_resource}    ${real_tree}/resource/
${real_resource_2}    ${real_resource}/resource2
${some_resource}    ${CURDIR}${/}..
```
So, the problem is when there is built in robot framework variable **${/}** I got my script crashed with "Variable not found error":
`[ ERROR ] Error in file '/path/to/Paths.robot' on line 9: Setting variable '${some_resource}' failed: Variable '${/}' not found.`
I thought built in variable ${/} should be substituted by os-specific path separator at the moment when variable value including ${/} is put into Variables.
What am I miss? Can you please help me?

**Comment by pekkaklarck** [comment]
I think you need to use `GlobalVariables` to get `${/}` and others to work. Notice that these aren't public or stable APIs so things may change in the future. Notice also that this issue tracker is for bug reports and enhancement requests, Slack, mailing list, and other such forums should be use for questions.
