### ISSUE TITLE
xUnit outputs: Add `timestamp` attribute for `testsuite` elements

### ISSUE THREAD

**Issue by aaltat** [robotframework/robotframework#4074]
Python [junitparser](https://pypi.org/project/junitparser/) expects that there is  timestamp attribute testsuite element. 

Also Pytest puts timestamp attribute testsuite element. Example Pytest has: 
`<testsuite name="pytest" errors="0" failures="0" skipped="2" tests="46" time="18.169" timestamp="2021-09-01T04:43:16.364650" hostname="something">` 

In Robot Framework there is: `<testsuite name="Test" tests="435" errors="0" failures="4" skipped="0" time="244.974">`

Is somewhat related to: #2982 and #3944

**Comment by pekkaklarck** [comment]
This is definitely a valid enhancement. Having timestamps sounds like a good idea in general and being compatible with the [junitparser](https://pypi.org/project/junitparser/) module is important on its own right as well. Probably should enhance the current tests to use junitparser to make sure we stay compatible. The main problem with all xunit output enhancements is that there's no official schema for that format. Using junitparser a reference is a good idea in that sense as well.

This needs to be implemented together with #2982 and should also look at #3944 at the same time.

**Comment by rikerfi** [comment]
Hi, I would like to give a try for this one as well as #2982

**Comment by pekkaklarck** [comment]
Great, go ahead!

**Comment by rikerfi** [comment]
Seems that output.xml file is 'single source of truth' for xunit output file as well. Timestamp attribute could be parsed relatively easy from testsuite's starttime. That leads implementation options to consider:

1. We just 1:1 convert timestamp from testsuite's starttime. E.g. `20211101 10:02:24.107` becomes `2021-11-01T10:02:24.107`
2. Adjust timestamp to `isoformat` precision  rounded e.g. `20211101 10:02:24.107` becomes `2021-11-01T10:02:24.107000`
3. We'll re-format output.xml starttime/endtime having full precision e.g. `20211101 10:02:24.107123` becomes `2021-11-01T10:02:24.107123`
4. Something else?

I am not sure how breaking change option 3 is. Options 1 & 2 are Robot Framework 'flavors' anyway. So, I would keep compatibility to junitparser and choose option 2.

Comments welcome!

**Comment by aaltat** [comment]
I don't have strong opinion, but option 2 feels best.

**Comment by pekkaklarck** [comment]
Compatibility with junitparser is very important so option 2 is clearly the best.

Changing output.xml timestamp format is a subject of a different issue. I doubt times below milliseconds really matter in acceptance testing (there's e.g. overhead by the framework itself), but we should at least consider switching to ISO 8601 format. I'd like to change how times are handled internally as well, but I doubt that's important enough to make it into RF 5.0.

**Comment by pekkaklarck** [comment]
As I commented #4144, we need to decide how to handle suites not containing start time. Typically suites have it, but at least when combining results with `rebot` the root suite doesn't. I believe alternatives are not having `timestamp` at all or having `timestamp=''`. I'd prefer the former because it makes it explicit you need to handle that case separately, but I guess always having a timestamp has its benefits as well.

I already tested that `junitparser` doesn't actually require the `timestamp` attribute. It can parse our current xunit.xml file just fine and the resulting `TestSuite.timestamp` will be `None`.

**Comment by pekkaklarck** [comment]
Implemented in PR #4074 by @rikerfi. Thanks for contribution!
