### ISSUE TITLE
Can I get the list of Keywords which are deprecated in Robot Framework V 4.0 please?

### ISSUE THREAD

**Issue by Test-Hassan** [robotframework/robotframework#4081]
Can I get the list of Keywords which are deprecated in Robot Framework V 4.0 please?

**Comment by pekkaklarck** [comment]
No keywords were deprecated. For list of backwards incompatible changes in RF 4.0 see the release notes:
https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-4.0.rst
