### ISSUE TITLE
.libspec generated incorrect line info for keyword definition if keyword using nested decorator 

### ISSUE THREAD

**Issue by Massukio** [robotframework/robotframework#4094]
I had reported this issue on **robotframework-lsp** , and the author suggested me to raise an issue here.
https://github.com/robocorp/robotframework-lsp/issues/424#issuecomment-921662166

> the language server is mostly a consumer of the .libspec which is generated by robot.libdoc from Robot Framework itself. The .libspec contains the filename/line for each definition, so, the fix here so that the correct filename/line is collected is something that needs to be done in Robot Framework itself.

**Issue Description**
I has an issue at Go To Definition ..
This is my special case, but I want to ask if Go To Definition works with decorators?

I had modified robotkeyword for my own purpose
```
def keyword(name=None, tags=(), types=()):

    def _method_wrapper(func):

        def _passargs(self, *args, **kwargs):    <<--  Go To Definition always stuck here
            .. some codes ..
            return func(self, *args, **kwargs)

        _passargs.robot_name = name
        _passargs.robot_tags = tags
        _passargs.robot_types = types

        return pass_argument

    return _method_wrapper
```

With this change, the Go To Definition always go to the def _passargs .. line instead of real function location.
Is there any chance I can have Go To Definition works fine with this decorators?

**Comment by pekkaklarck** [comment]
Have you tested using `functools.wraps`?

**Comment by Massukio** [comment]
@pekkaklarck thanks for the hint!

I did try the functools.wraps but it still got the wrong source file location (`func.__code__.co_filename`). 
```
from functools import wraps

def keyword(name=None, tags=(), types=()):

    def _method_wrapper(func):

        @wraps(func)               <---- with this, the source file still stuck at keyword file.
        def _passargs(self, *args, **kwargs):  
            .. some codes ..
            return func(self, *args, **kwargs)

        _passargs.robot_name = name
        _passargs.robot_tags = tags
        _passargs.robot_types = types

        return pass_argument

    return _method_wrapper
```

After read lots of articles, I realized that `functools.wraps` won't preserve all the attributes of functions.
Then I use inspect.unwrap to preserve all the attributes before adding more attributes to the func. And it works!!!
```
import inspect
def keyword(name=None, tags=(), types=()):

    def _method_wrapper(func):

        def _passargs(self, *args, **kwargs):  
            .. some codes ..
            return func(self, *args, **kwargs)

        _passargs = inspect.unwrap(func)
        _passargs.__signature__ = inspect.signature(func)
        _passargs.robot_name = name
        _passargs.robot_tags = tags
        _passargs.robot_types = types

        return pass_argument

    return _method_wrapper
```

Documented this here to help ppl like me who modified the keyword decorator.
