### ISSUE TITLE
Multilanguage support for markers used in data

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#4096]
Currently we can only use English with section headers, settings, and other such markers in the data. For example:
```
*** Settings ***
Documentation     Some doc here.
```
Supporting other languages would be great. For example, the above could look like this in Finnish:
```
*** Asetukset ***
Dokumentaatio    Jotain dokua täällä.
```

Getting this done requires:
1. Deciding how to enable support for different languages. Probably with a command line option like `--language FI`.
2. Deciding how to handle multiple languages in one execution. Could be `--language FI --language EN` to allow customizing how a certain language is used e.g. like `--language FI:some:config`.
3. Deciding what to translate. Section headers and settings for sure, but what about control structures like IF/ELSE? Perhaps we should allow translating everything and let translators to select do they want to use common IF/ELSE or some local variant. Could also be customizable when enabling support for a certain language.
4. Getting translations for built-in support for common languages. These can be added in future releases.
5. Deciding how to use languages that don't have built-in support. Perhaps `--language mylang.txt`.

I hope the wider community can help with translations when we get that far. Comments about the design decisions above are appreciated as well.

I consider making Robot Framework more native in non-English speaking languages pretty important and thus assign this to RF 5.0 scope with critical priority. The old issue about non-English Given/When/Then prefixes (#519) is highly related and already in RF 5.0 scope.

There are many other related enhancements like translating log and report, translating error message, translating keywords used in generic libraries, and so on. They all require their own issues and probably need to wait for future RF versions.

**Comment by bhirsz** [comment]
Leaving myself here so I will remember to add option for robotidy to autotranslate tokens. And it would be interesting to add support for polish. Although I don't have idea how to translate some of the keywords such as [Teardown] (probably not `[Zburzyć]` :D). Maybe to avoid problems with not accurate translations it would be good idea to let people vote on certain translations? Or use https://crowdin.com .

**Comment by pekkaklarck** [comment]
Yeah, coming up with good translations for some of these terms is going to be hard. No idea what Teardown could be in Finnish either. A major problem related to this is that changing terms would be backwards incompatible. Perhaps we should support English always so that hard-to-translate terms could be initially skipped.

**Comment by Snooz82** [comment]
Great Idea.

**Comment by pekkaklarck** [comment]
We decided to move this one and highly related non-English Given/When/Then support (#519) to RF 5.1. That wasn't done because we don't consider these issues important, on the contrary, but simply because RF 5.0 already contains lot of great new features and we want to get it out as soon as possible. These translation related issues will be the highest priority issues in RF 5.1 and the plan is to start its development right after RF 5.0 has been released.

**Comment by yanne** [comment]
We need to do some technical choices before proceeding with the implementation.
The goals here are:
 * offer simple way for users to provide translations
 * use a file format which can be parsed easily with the Python standard library
 * introduce no performance penalty

Since this is mostly a lookup problem (does a given string, say `*** testitapaukset ***`, represent a valid token), some kind of configuration file is most likely appropriate. A full-blown translation framework like [gettext](https://docs.python.org/3/library/gettext.html) might be too complicated.

In addition, it needs to be decided whether we support multiple forms for some tokens. For example, currently the table headers allow both singular and plural English form (`test case` and `test cases`). For the sake of simplicity and clarity, it might be better to allow just one form in the translations. 

Based on all the above, some options for the configuration file format are:
 * [INI files](https://en.wikipedia.org/wiki/INI_file)
 * [JSON](https://www.json.org/json-en.html)
 * [YAML](https://yaml.org)
 * [TOML](https://github.com/toml-lang/toml)

Of these, INI files and JSON are the ones having parsers in the Python standard library. 
JSON is quite unwieldy to edit by hand and it does not support comments, and additionally no benefit is gained by it's support for a wider range of data types than INI files.

**Comment by mkorpela** [comment]
I would really like to also results be considered. How does log.html look like
and could we allow to some extent results automatic translations.

**Comment by mkorpela** [comment]
@yanne one thing I would also think are the existing standards and work beyond Python standard libs.
JSON is pretty much used in projects like i18next and all over the content of internet (like in headless cms).
It might actually result in best tooling for content creation for the translations.

**Comment by pekkaklarck** [comment]
Translating log and report is important but it would most likely be better to update their underlying tech first. We are planning to do such tech update with Libdoc already in RF 5.1 (#4304) and if that goes well then log/report could be next.

**Comment by d-biehl** [comment]
Regarding  technical choices:

What about the python [gettext ](https://docs.python.org/3.10/library/gettext.html) API, it comes with python and is a well established [standard](https://www.gnu.org/software/gettext/manual/index.html), editing and handling [PO files](https://localizely.com/po-file/) is easy and there are several tools wich helps you to write your translations.

**Comment by MoreFamed** [comment]
> Yeah, coming up with good translations for some of these terms is going to be hard. No idea what Teardown could be in Finnish either. A major problem related to this is that changing terms would be backwards incompatible. Perhaps we should support English always so that hard-to-translate terms could be initially skipped.

This supporting English forever would solve (or work-around) the problem of deciding what to translate and what to leave in English. I rather wish RF not to enforce using translations even if they are available---then everyone can decide whether e.g. whether they will write *RETURN* in English or in their language. (This is Robocop what I probably wish to (optionally) check whether a translation was used wherever possible.)

**Comment by pekkaklarck** [comment]
`gettext` is an option later but an overkill now. We just need to match strings during parsing.

The plan is to support English as an alternative automatically. In the future we may make that configurable if there are needs. Notice also that at least in the beginning we don't plan to support translating control structures like `RETURN` or `IF`. Support for that can be added later.

**Comment by pekkaklarck** [comment]
Markers to translate, that are covered by this issue, are just headers and settings. With headers we support both singular and plural formats in English and we can support them also with other languages. For test related headers and settings we have task related aliases.

Headers:
- Settings, Setting
- Variables, Variable
- Test Cases, Test Case
- Tasks, Task
- Keywords, Keyword

Settings in the Settings section:
- Documentation
- Metadata
- Suite Setup
- Suite Teardown
- Test Setup
- Test Teardown
- Test Template
- Test Timeout
- Task Setup
- Task Teardown
- Task Template
- Task Timeout
- Force Tags
- Default Tags
- Library
- Resource
- Variable

Settings for tests/tasks:
- Documentation
- Tags
- Setup
- Teardown
- Template
- Timeout

Settings for keywords:
- Documentation
- Arguments
- Teardown
- Timeout
- Tags
- Return (this will be deprecated in somewhat near future and can be omitted)

**Comment by pekkaklarck** [comment]
We obviously need help from the community with translations. We have decided to use the `#localication` channel on our [Slack](https://robotframework.slack.com/) as the main collaboration place and separate language specific channels can be created for each language. If you are interested to help, join the channel! If you aren't yet on our Slack, you can get an invite [here](https://rf-invite.herokuapp.com/).

**Comment by leeuwe** [comment]
If anyone wants to join in on the translation of RF please submit your translation here https://robotframework.crowdin.com/robot-framework

**Comment by pekkaklarck** [comment]
I added initial translations for Finnish for testing and demonstration purposes in bfec5a53346b2cfb1a537aeb3814bab748272910. Everything that was needed is the new `Fi` class in the [languages](https://github.com/robotframework/robotframework/blob/master/src/robot/conf/languages.py) module. I would prefer additional languages to be added via pull requests by their respective authors to have contact info for them automatically stored. It's fine to leave some of the terms untranslated, the English terms will nevertheless work. You many also decide not to translate `[Return]` because it will be deprecated and removed in the somewhat near future anyway.

**Comment by pekkaklarck** [comment]
Notice that the class in the [languages](https://github.com/robotframework/robotframework/blob/master/src/robot/conf/languages.py) module will be the name of the language to use from the command line. Matching name is case-insensitive so, for example, the aforementioned `Fi` class can be used like `--language fi`.

Language variants such as Brazilian Portuguese could have a class name like `PtBr` and be used like `--language ptbr`. If the usage would be more convenient like `pt-br` or `pt_br`, we can ignore `-` and/or `_` when matching. Alternatively we could make it possible for each class to provide a custom name to be used with them. Do you @HelioGuilherme66 have a preference?

**Comment by HelioGuilherme66** [comment]
Better use the hyphen then. The following should be accepted:  `pt` (this is the preferable, nice to have a lookup for regional LANG code page, and switch to it, otherwise, default would be `pt-pt`),  `pt-pt` and  `pt-br`.
There may be more regional variants, like for example, Angola.
(I haven't looked at code, but maybe a specific Robot Framework language environment variable could exist):

 No `--language` option ==> Lookup ROBOT_LANG ==> English (`en´) If None else ROBOT_LANG
 With `--language pt` ==> Lookup ROBOT_LANG ==> `pt-pt` If None else ROBOT_LANG (user would need `--language en` to bypass ROBOT_LANG)
 With `--language pt-pt` ==> no lookup for ROBOT_LANG ==> `pt-pt`
 With `--language pt-br` ==> no lookup for ROBOT_LANG ==> `pt-br`
 With `--language fi` ==> no lookup for ROBOT_LANG ==> `fi`  (applicable for all languages with no regional variants)

**Comment by pekkaklarck** [comment]
I don't think we need an environment variable to control the language. We already support `ROBOT_OPTS` and giving it a value like `--language pt` has the same effect as the proposed `ROBOT_LANG` with value `pt`. I'd also rather think about adding support for config files than add more environment variables. I'm not entirely against the idea, though, so you can submit a separate issue to discuss it further.

**Comment by pekkaklarck** [comment]
I don't want to make handling language codes too complicated at least in RF 5.1. For example, I don't want to do any extra lookups if someone uses `pt` and not `pt-pt`. We just need to decide which one to use or make it so that both mean the same thing.

The hyphen in `pt-br` is easiest to handle so that we simply ignore it when matching the given language code to the available ones. Then the class name can be just `PtBr` and matching it works. Alternatively we could require the class name to be `Pt_Br` in this case or require the class to have an attribute telling the language code to use. I don't think these have any concrete benefits over simply ignoring the hyphen in matching. That obviously means that `ptbr` works in addition to `pt-br`, but I don't think that really matters.

**Comment by pekkaklarck** [comment]
Big thanks for @leeuwe for setting up [Crowdin](https://robotframework.crowdin.com/robot-framework) to have a place where the community can work together with translations. Thanks also to everyone who has already participated in translation efforts.

If you want to test translations created at Crowdin, you need to download the language file (seems to be named `Core.yml`) and convert it to Python that Robot Framework understands. I have [created a script](https://gist.github.com/pekkaklarck/fd348b7eb59f35a26f2fdc1e7b0f008d) that can do conversion automatically. Just download the script and run it like this:

    python crowdin.py Core.yml lang.py

The generated Python code can be used directly with Robot Framework like `robot --language lang.py tests.robot`. The generated class can also be added to Robot's [languages](https://github.com/robotframework/robotframework/blob/master/src/robot/conf/languages.py) module via a pull request to get it included as a built-in language.

**Comment by pekkaklarck** [comment]
The support for localized markers ought to be done now. We still need to add actual translations and document all this, but that's covered by #4390.
