### ISSUE TITLE
Auto-Hide for Results Table

### ISSUE THREAD

**Issue by biju-aramban** [robotframework/robotframework#4097]
In our organization we have more than 10K tests running in multiple service components using RF.

RF Results table lists all the test cases.
Each test case has Test Case ID as the minimum tag. So we are talking about 10K test case tags (minimum).

Issues:
1. Results table is not collapsible. When someone wants to triage results, to reach the results details is a long traversal.
Results tags are not clickable. So even if you find a failed test in a 10K table, you will still have to browse through/search for the failed case until you reach the detailed test case step execution listing.

It would be nice if:
RF follows the same behavior used for keyword execution html logging. 
A failed keyword node is expanded by default
A passed test case/keyword is collapsed by default.

So RF could list the tests (with test case tag | id) in PASSED first / FAILED later style.
Passed table is collapsed by default.
Test case tags are clickable.

Thanks.

**Comment by pekkaklarck** [comment]
What exactly do you mean with "results table"? Statistics shown in log and report or the dynamically generated table with tests in report? Have you considered using `--tagstatinclude` or `--tagstatexclude`?
