### ISSUE TITLE
Robotframework doesn't have any parallel test execution feature in built

### ISSUE THREAD

**Issue by cookbook87** [robotframework/robotframework#4110]
Robotframework doesn't have any parallel test execution feature in built. It sometimes become very crucial especially when the test cases take longer time to execute. there should be some inbuilt hook from framework side to enable such an option. BDD framework such as pytest or behave has such option.

This would really optimize the number of hours a big test cycle takes.

**Comment by pekkaklarck** [comment]
Parallel execution of tests/tasks is on purpose left away from RF core, but we have great [Pabot](http://pabot.org) tool for that purpose. Parallel execution of keywords would be handy in some cases but unfortunately rather complicated to implement properly. We already have issues related to that (see #1791 and #1792) and hopefully someway get that done. Not in the foreseeable future, though.
