### ISSUE TITLE
Support to run a keyword from different geo location 

### ISSUE THREAD

**Issue by cookbook87** [robotframework/robotframework#4113]
Scenario: 
There could be many application where user can login from different geo location at the same time or different time. this is mostly hits some api and assess the load of a system.

If a provision could be made to do such operations via framework, would be amazing.

**Comment by pekkaklarck** [comment]
This ought to be possible already now via custom libraries. In some context could be possible to create generic libraries as well. Anyway, definitely not something that belongs to Robot Framework core.
