### ISSUE TITLE
New `format` option to `Log To Console` to control alignment, fill characters, and so on

### ISSUE THREAD

**Issue by IlfirinPL** [robotframework/robotframework#4115]
In some cases its look nice to print msg on center of screen with some padding

default values for new arguments
align=left    
padding=' '

example use after changes
Log To Console    ${msg}    align=center    padding=*

current workaround but it`s not easy to get actual screen width
Log To Console    ${msg.center(78, '*')}

links
https://www.programiz.com/python-programming/methods/string/center
https://docs.python.org/3/library/stdtypes.html#str.center

**Comment by pekkaklarck** [comment]
We cannot expose only console width but exposing all command line options somehow is possible. Not sure should there be a built-in variable like `${SETTINGS}` or some API to get this info. We may already have an issue about that and if not, one can be submitted. This issue can be about possibly adding formatting option to `Log To Console`. Getting either of them implemented in foreseeable future will require external contribution. I have other issues to look at for RF 5.0 that have a lot higher priority.

**Comment by pekkaklarck** [comment]
Anyone interested to add `format` option to `Log To Console`? As explained in the [docs](https://docs.python.org/3/library/string.html#formatspec), it would support alignment, fill characters, and so on. Implementation ought to be very easy so this is a good first issue for anyone interested to contribute!

**Comment by makeevolution** [comment]
@pekkaklarck I'm interested to implement this, do you mind assigning me?

**Comment by pekkaklarck** [comment]
Go ahead @makeevolution! Just create a PR and I'll review it.

**Comment by nick-grout1** [comment]
Hi @makeevolution , I was wondering what the status of this was - I would be happy to take this issue on it sounds really interesting.

Just let me know if you don't have time for this issue/would like me to take it on. 

Thank you!

**Comment by makeevolution** [comment]
Hey @nick-grout1 thanks for the offer but I'm still actively working on it, already made pull requests and working on the feedback now

**Comment by pekkaklarck** [comment]
Implemented in PR #4162 by @makeevolution. Thanks for contribution!
