### ISSUE TITLE
Broken variable assignment with like `${oops =` crashes parsing

### ISSUE THREAD

**Issue by d-biehl** [robotframework/robotframework#4118]
Hi,

this piece of code:

```python
from robot.api import get_tokens


data = r"""\
*** Test Cases ***
first
    ${=  do something    
"""

for e in get_tokens(data):
    print(e)
```

throws an exception `robot.errors.VariableError: Variable '${' was not closed properly` right after the get_token call and no tokens 'till the keyword call are returned. 
I think it should behave like the other errorrenous expression if the variable is not closed properly, so that we can still get the tokens.

Thanks Daniel

**Comment by pekkaklarck** [comment]
Merged the PR. This fix is luckily so simple that we don't need a new release candidate.
