### ISSUE TITLE
Should Be Uppercase/Lowercase/Titlecase keywords to String library

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#412]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=412) by tookko on 12 Oct 2009_

Keywords for checking letter case would be useful:
- Should Be Lower Case -&gt; all letters non-capitalized
- Should Be Upper Case -&gt; ALL LETTERS CAPITALIZED
- Should Be Proper/Title Case -&gt; Sentences Written in Proper Case
- Should Be Sentence Case -&gt; Only beginning letter is capitalized

Case conversion functions could be added too, but not maybe as much needed 
for _verification_ purposes.

**Comment by kenlyle2** [comment]
It looks like this didn't happen.  As of today, can't find Titlecase in Robot Framework String Library.
