### ISSUE TITLE
`rebot --merge` doesn't merge suite setups or teardowns

### ISSUE THREAD

**Issue by luciab038** [robotframework/robotframework#4120]
We're currently running our tests with pabot and when there are failures we rerun them by passing the argument -R (--rerunfailed) and the output.xml from the first run.
At the end of the rerun we use rebot to merge the results with the following command:

`rebot -d $folder -o output.xml -R $firstRun\output.xml $secondRun\output.xml`

Everything works fine, except when on the first run a suite fails for the Setup Suite, and then on the second run the Setup Suite and the tests pass: the merged robot report still shows the Setup Suite as failed, and its tests as passed, while the setup should also be green.

**First run with Setup failure:**
![image](https://user-images.githubusercontent.com/57198139/137284126-6929f32e-4815-4dd8-8b1b-8767d9fd0979.png)

**Second run without Setup failure:**
![image](https://user-images.githubusercontent.com/57198139/137284217-0051f25b-6edc-4df2-9ba9-416d12a59276.png)

**Result of the merge between the first and the second run:**
![image](https://user-images.githubusercontent.com/57198139/137283454-4bed63b9-77cc-49e4-aef3-ab52e1efdd0c.png)

Are we missing something? Can someone help us?

We're currently using:
```
robotframework                 3.2.2
robotframework-pabot           1.10.1
```

**Comment by luciab038** [comment]
It would be nice to have it soon as possible but it isn't critical for us. We can wait for the RF 5.0, thanks!

**Comment by pekkaklarck** [comment]
Leaving bugs unfixed is so annoying that decided to include this in RF 4.1.2. I'll create rc 3 today or latest tomorrow and then final on Monday.
