### ISSUE TITLE
Escaping for special characters isn't consistent for built in ${PREV_TEST_NAME} variable and listener model

### ISSUE THREAD

**Issue by ArtemRudenia** [robotframework/robotframework#4125]
### Bug description
______________________

During test case development was found that backslash(\) in test case name cause an error.
If we use backslash(\) in test case name, for example, 'Test Case With Backslash \ Foo', 
then we get 'Test Case With Backslash  Foo' in automatic variable ${PREV_TEST_NAME}. 
But, if we verify it in ROBOT_LIBRARY_LISTENER method (for example, in _end_test), 
which use ${PREV_TEST_NAME} automatically, we could see that now we have two backslashes, 
which cause an error due to different number of backslashes.
So, error is appeared due to different names.

![image](https://user-images.githubusercontent.com/23409033/138294858-893bf8e3-e35b-4a37-b407-d999c185b7af.png)

If we tried to escape backslash by doubled it in test case name, then we will have one backslash in ${PREV_TEST_NAME},
but four backslashes during verification in ROBOT_LIBRARY_LISTENER method.

![image](https://user-images.githubusercontent.com/23409033/138294733-81c6df47-f0f7-4026-978a-9278ceb7561f.png)

### Reproduction
___________________
Robot code:
``` 
*** Settings ***
Library             backslash_listener.py
Force Tags          backslash_issue

*** Variables ***

*** Test cases ***
Test Case With Backslash \ Foo
    No Operation

Second Test Case
    Log    ${PREV_TEST_NAME}
    # Here we have 'Test Case With Backslash  Foo' in ${PREV_TEST_NAME}

    Should Be Equal As Strings    ${PREV_TEST_NAME}    Test Case With Backslash \ Foo
    # Should Be Equal As Strings will be PASS because 'Test Case With Backslash \ Foo' 
    # will be convert to 'Test Case With Backslash  Foo'

    Test Case Should Be Completed    ${PREV_TEST_NAME}
    # This verification will be FAIL because will be compared 'Test Case With Backslash  Foo' 
    # and 'Test Case With Backslash \\ Foo'

*** Keywords ***
```
Listener code:
```
from robot.api import logger


class backslash_listener(object):
    ROBOT_LISTENER_API_VERSION = 3
    ROBOT_LIBRARY_SCOPE = "GLOBAL"

    def __init__(self):
        self.ROBOT_LIBRARY_LISTENER = self
        self._completed_test_cases = []

    def _end_test(self, data, attributes):
        # Here will be 'Test Case With Backslash \\ Foo' in data.name but should be the same as in ${PREV_TEST_NAME}
        self._completed_test_cases.append(data.name)

    def test_case_should_be_completed(self, test_name):
        logger.info("Test case name: {}".format(test_name))
        logger.info("Completed test cases: {}".format(self._completed_test_cases))
        if not test_name in self._completed_test_cases:
            raise AssertionError("Test case name should be in _completed_test_cases list, but it is not")
```

**Comment by pekkaklarck** [comment]
It's a bit unfortunate that `result.name` and `data.name` can look different, but that's a direct byproduct of #2962. I don't think we can really do anything to that so I'm closing this issue.
