### ISSUE TITLE
Installation instructions using poetry

### ISSUE THREAD

**Issue by kishaningithub** [robotframework/robotframework#4130]
When using robot frameork we inevitabby use seleneium and install browser drivers

It would be great if there can be an example using poetry

https://github.com/python-poetry/poetry

I am hoping this would simplify the installation and usage

**Comment by pekkaklarck** [comment]
Could you clarify what these instructions should contain?

**Comment by pekkaklarck** [comment]
I believe we should just use `pip` in our "official" instructions. There can be separate instructions at docs.robotframework.org.
