### ISSUE TITLE
FOR-Loop won't continue after failing IF Statement

### ISSUE THREAD

**Issue by EckoSystem** [robotframework/robotframework#4135]
Below is the Keyword that doesn't work for me. The IF Statement is false at the first entry of the @tracks list which is correct but the FOR-Loop doesnt continue after that. The Error message just says "First Entry" != "Argument" (not literally but just doesn't want to share the specific work related data)

```
Select Track
    [Arguments]   ${track_name}
    @{tracks}=   Get WebElements   //div[@role="listbox"]/mat-option 
    FOR    ${track}    IN    @{tracks}
        ${text}=    Get Text    ${track}
        IF  '${text}' == '${track_name}'
            Scroll Element Into View    ${track}
            Set Focus To Element    ${track}
            Click Element  ${track}
        END
    END
```

Had this discussion in the Slack Channel with Liviu Avram and @pekkaklarck  and adding an ELSE with the "Continue For Loop" Keyword fixed that but its not the expected behaviour of a FOR-Loop. I'm using mostly the SeleniumLibrary.

**Comment by pekkaklarck** [comment]
This looks pretty strange but I've seen strange bugs earlier. The problem with the example is that it requires external library and certain system under test. Could you please add an example that I could run locally directly? If the problem is in RF, it ought to be possible to reproduce it using only BuiltIn library keywords.

**Comment by EckoSystem** [comment]
Well with only the BuiltIn Library it seems to be working. I've tried this simple example:

```
Test
    [Arguments]   ${animal_arg}
    FOR    ${animal}    IN    cat   dog   mouse     
        IF  '${animal}' == '${animal_arg}'
            Log   Found the animal
        END
    END
```

Could be an issue in combination with the other Libraries as you already suggested.

**Comment by pekkaklarck** [comment]
It's hard to believe external libraries could change how Robot handles FOR loops and IFs. I'm fairly certain there's something else going on. I hope you are able to debug this further so we know is the problem on Robot or somewhere else.

**Comment by pekkaklarck** [comment]
Any updates? If this cannot be reproduced by using only BuiltIn keywords, I'm fairly certain there was something else wrong in the original case. That said, if someone can create an example demonstrating this with any publicly available library against any publicly available system, I'd be happy to test this further.

**Comment by EckoSystem** [comment]
Sorry i didn't had the time to test this further. But i've tested the original Keyword without the 'Continue For Loop' and it worked. So i think that was an error on my side. I think for now the issue can be closed. If i ever encounter this again i'll let you know.

**Comment by pekkaklarck** [comment]
Thanks for the update!
