### ISSUE TITLE
"Should contain any" does not parse a predefined list correctly

### ISSUE THREAD

**Issue by yyz-lab** [robotframework/robotframework#4137]
Hello,
As the members of a list defined in robot variable table always including the "" marks (No way to remove them), "Should contain any" will get failed.

e.g.
variable:
@{TrialSubscriptionStatus}          Your trial period is valid until           Kokeilujaksosi on voimassa              
message got: 
${msg}       Kokeilujaksosi on voimassa 04.12.2021 saakka.

Should contain any     "${msg}"   @{TrialSubscriptionStatus}

results:
'"Kokeilujaksosi on voimassa 04.12.2021 saakka."' does not contain any of '"Your trial period is valid until"',  '"Kokeilujaksosi on voimassa"'

**Comment by pekkaklarck** [comment]
Closing due to lack of information.
