### ISSUE TITLE
General question about robotframework

### ISSUE THREAD

**Issue by DevStreamLine** [robotframework/robotframework#4139]
Hello,

I have been looking for a way to automate an Android App that we use.  Will this framework allow us to do that?  We do not want to add any code to the app, we would like to simply have a method of launching the app if need be and then login in with supplied credentials and navigate the app based on some passed in parameters.  If this will not allow that does anyone know of another open source method to accomplish our automation?

**Comment by tysonite** [comment]
It makes sense to ask such questions on various Robot's forums: https://github.com/robotframework/robotframework#support-and-contact 

Probably, Slack is the best one.

**Comment by pekkaklarck** [comment]
Yeah, questions should be asked on aforementioned forums. This tracker is for bug reports and enhancement requests.
