### ISSUE TITLE
Import of BuiltIn library directly from Python 3.8 throws an Import error, Possible circular import

### ISSUE THREAD

**Issue by mrrosenhahn** [robotframework/robotframework#4145]
When using Python 2.7 and RobotFramework 3.0.2, from Python I was able to import BuiltIn using the following import statement. from robot.libraries.BuiltIn import BuiltIn. I was using to BuiltIn class to get some variable data using the following method to locate the location of the log file directory.

```
        from robot.libraries.BuiltIn import BuiltIn
        from robot.libraries.BuiltIn import RobotNotRunningError

        try:
            variables = BuiltIn().get_variables()
            return variables['${OUTPUTDIR}']
        except RobotNotRunningError:
            return os.getcwd()
```

After upgrading my Python environment to 3.8 and RobotFramework to 4.1.2, an Import error is raised (stack trace below). 

```
Traceback (most recent call last):
  File "/root/git/cafe/misc/tshark_sandbox/tshark_sandbox.py", line 1, in <module>
    from robot.libraries.BuiltIn import BuiltIn
  File "/usr/local/lib/python3.8/site-packages/robot/libraries/BuiltIn.py", line 23, in <module>
    from robot.api import logger, SkipExecution
  File "/usr/local/lib/python3.8/site-packages/robot/api/__init__.py", line 72, in <module>
    from robot.parsing import (get_tokens, get_resource_tokens, get_init_tokens,
  File "/usr/local/lib/python3.8/site-packages/robot/parsing/__init__.py", line 25, in <module>
    from .model import ModelTransformer, ModelVisitor
  File "/usr/local/lib/python3.8/site-packages/robot/parsing/model/__init__.py", line 18, in <module>
    from .statements import Statement
  File "/usr/local/lib/python3.8/site-packages/robot/parsing/model/statements.py", line 19, in <module>
    from robot.running.arguments import UserKeywordArgumentParser
  File "/usr/local/lib/python3.8/site-packages/robot/running/__init__.py", line 99, in <module>
    from .builder import TestSuiteBuilder, ResourceFileBuilder
  File "/usr/local/lib/python3.8/site-packages/robot/running/builder/__init__.py", line 16, in <module>
    from .builders import TestSuiteBuilder, ResourceFileBuilder
  File "/usr/local/lib/python3.8/site-packages/robot/running/builder/builders.py", line 20, in <module>
    from robot.parsing import SuiteStructureBuilder, SuiteStructureVisitor
ImportError: cannot import name 'SuiteStructureBuilder' from partially initialized module 'robot.parsing' (most likely due to a circular import) (/usr/local/lib/python3.8/site-packages/robot/parsing/__init__.py
```

 During my debugging I created a new Python project and only added the import statement to rule out that my existing project had a  circular reference and executed the Python module. I still hit the same error with the import statement only.

**OS Information**
```
CentOS Linux release 7.9.2009 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.9.2009 (Core)
CentOS Linux release 7.9.2009 (Core)
```
 
**PYTHONPATH**
`/usr/local/lib/python38.zip:/usr/local/lib/python3.8:/usr/local/lib/python3.8/lib-dynload:/usr/local/lib/python3.8/site-packages`

**Comment by pekkaklarck** [comment]
Hard to tell what's going on, but I'm fairly certain the problem is related to your installation or environment. The reason I believe so is that we have several tests doing `from robot.libraries.BuiltIn import BuiltIn` without problems and it's also used widely by the community. If there would be more common problems, it ought to be reported earlier. Anyway, strange things have happened earlier so I'll leave this issue open for a while in case you can find more information and it turns out there's actually problem on Robot side. Because I cannot reproduce the problem, I cannot debug it further myself.

**Comment by mrrosenhahn** [comment]
My test environment is on a VM. I will reset my environment back to the virgin state and walk through the machine setup process one step at a time to see is somewhere in my setup process is causing this issue. I will them post to you what I find.

**Comment by mrrosenhahn** [comment]
I ended up trying to uninstall the reinstall robot framework to the affected VM and this fixed the issue. I suspect that while debugging some other issue in my project I had inadvertently made a change to the robot libraries that caused the issue.
