### ISSUE TITLE
Screenshot acceptance tests fail when run on not supported platform 

### ISSUE THREAD

**Issue by Robtom5** [robotframework/robotframework#4151]
Currently screenshots fail if there are being run on a non supported platform (see log below). 
Ideally we should see these tests either raise warnings or skip if they detect they are being run
on a platform that we know they wont work on.

`FAIL: Robot.Standard Libraries.Screenshot.Set Screenshot Directory.Set Screenshot Directory
Test 'Set Screenshot Directory' was expected to PASS but it FAILED.
                                                    
Error message:                                                                                           
File '/tmp/robotatest/Python-3.9.2-Linux/robot_atest_screenshots/screenshot_1.jpg' does not exist.
----------------------------------------------------------------------------------------------------     
FAIL: Robot.Standard Libraries.Screenshot.Take Screenshot.Screenshot Is Embedded in Log File
Test 'Screenshot Is Embedded in Log File' was expected to PASS but it FAILED.                            
                                                                                                         
Error message:                                                                                           
Lengths are different: 0 != 1                                                                            
----------------------------------------------------------------------------------------------------
FAIL: Robot.Standard Libraries.Screenshot.Take Screenshot.Each Screenshot Gets Separate Index
Test 'Each Screenshot Gets Separate Index' was expected to PASS but it FAILED.

Error message:                                      
Lengths are different: 0 != 1
----------------------------------------------------------------------------------------------------
FAIL: Robot.Standard Libraries.Screenshot.Take Screenshot.Basename May Be Defined
Test 'Basename May Be Defined' was expected to PASS but it FAILED.

Error message:                                      
Lengths are different: 0 != 2
----------------------------------------------------------------------------------------------------
FAIL: Robot.Standard Libraries.Screenshot.Take Screenshot.Basename With Extension Turns Off Index Generation
Test 'Basename With Extension Turns Off Index Generation' was expected to PASS but it FAILED.

Error message:                                      
Lengths are different: 0 != 2
----------------------------------------------------------------------------------------------------
FAIL: Robot.Standard Libraries.Screenshot.Take Screenshot.Screenshot Width Can Be Given
Test 'Screenshot Width Can Be Given' was expected to PASS but it FAILED.

Error message:                                      
Lengths are different: 0 != 1
----------------------------------------------------------------------------------------------------
FAIL: Robot.Standard Libraries.Screenshot.Take Screenshot.Without Embedding
Wrong log message: Taking screenshot failed: Taking screenshots is not supported on this platform by default. See library documentation for details.
Make sure tests are run with a physical or virtual display. != Screenshot saved to '<a href="no_embed.jpeg">/tmp/robotatest/Python-3.9.2-Linux/output/no_embed.jpeg</a>'.
`

**Comment by pekkaklarck** [comment]
If dependencies for some acceptance test cannot be met, it's possible to exclude them from the execution. For example, screenshot related tests can be excluded with `--exclude require-screenshot`. For more details see:
https://github.com/robotframework/robotframework/blob/master/atest/README.rst#test-tags
