### ISSUE TITLE
Support line breaks <br> for libdoc generated html documentation

### ISSUE THREAD

**Issue by Mavnus04** [robotframework/robotframework#4154]
Add support for lines breaks, < b r >, for generated html documentation with libdoc. 
Currently, if you want an intentional line break, you have to break up your in code documentation, which does not look great in code or in html:

    ...  Line 1
    ...
    ...  Line 2
vs

    ...  Line 1
    ...  Line 2

Example:

MyResource.resource

    *** Settings ***
    Documentation  
    ...     Testing for new lines
    ...     Here is a second one
    ...
    ...     And new paragraph\n
    ...     New line in the new paragraph
    
    *** Keywords ***
    Test Case for checking documentation
        [Documentation]
        ...     First line which goes on and on for quite some time\n
        ...     Second line cause the first was too long
        ...
        ...     New Paragraph
        ...     Another new line for the new paragraph
        ...     | Test | Table |
        ...     | Works | fine |
        ...     V Look at that line V
        ...     ---
        ...     My list
        ...     - item 1
        ...     - item 2
        No Operation

The HTML output:
[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/qvW9h.png

HTML source code

    <script type="text/javascript">
    libdoc = {"name": "MyResource", "doc": "<p>Testing for new lines Here is a second one</p>\n<p>And new paragraph New line in the new paragraph</p>", "version": "", "generated": "2021-11-24 11:10:06", "type": "RESOURCE", "scope": "GLOBAL", "docFormat": "HTML", "source": "MyResource.resource", "lineno": 1, "tags": [], "inits": [], "keywords": [{"name": "Test Case for checking documentation", "args": [], "doc": "<p>First line which goes on and on for quite some time Second line cause the first was too long</p>\n<p>New Paragraph Another new line for the new paragraph</p>\n<table border=\"1\">\n<tr>\n<td>Test</td>\n<td>Table</td>\n</tr>\n<tr>\n<td>Works</td>\n<td>fine</td>\n</tr>\n</table>\n<p>V Look at that line V</p>\n<hr>\n<p>My list</p>\n<ul>\n<li>item 1</li>\n<li>item 2</li>\n</ul>", "shortdoc": "First line which goes on and on for quite some time Second line cause the first was too long", "tags": [], "source": "MyResource.resource", "lineno": 10}], "dataTypes": {"enums": [], "typedDicts": []}}
    </script>

My execution line:

    libdoc .\MyResource.resource MyResoure.html

Running RobotFramework version 4.1.2

My expected output
    
    Testing for new lines
    Here is a second one

**Comment by pekkaklarck** [comment]
As you can read in the [User Guide](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#newlines-in-test-data), this behavior is by design. I think Libdoc has always worked that way and #1135 changed logs and reports to behave consistently. I personally consider this the current behavior fine and due to backwards compatibility reasons we couldn't easily change it anyway.
