### ISSUE TITLE
Intermittent issue - High level keywords having IF-ELSE block are marked as failed rather than Skipped in the results published in reportportal

### ISSUE THREAD

**Issue by prajeeth07** [robotframework/robotframework#4158]
**Scenario:**
We are using reportPortal to capture the test results that we execute on Docker.
When an IF-ELSE block is executed, at times when either block executes successfully, the other is marked as failed (the code inside the block is shown as skipped) in the reportportal results.
A similar issue is observed sometimes on the high-level keyword having IF-ELSE block which is marked as Failed when none of the lower level keywords has failed - only on reportportal results.

The HTML report generated by Robotframework shows the same tests as passed.

**Expected behavior**
- For the IF-ELSE block, the block not executed should be marked as Skipped similar to robotframework HTML results
- The Higher level keywords containing an IF-ELSE block should not be marked as failed when either IF or ELSE block is skipped

I assumed there can be an issue with the reportportal listener for robotframework - however, the reportportal team confirmed that the listener sends exactly what it receives from the Robot Framework. There is no additional logic hidden in the agent that may impact keyword/test/suite status.

Is there a possibility that robotframework is sending an incorrect status to the reportportal agent since the issue is observed in the IF-ELSE keyword which is a new feature?

Screenshot:
ReportPortal screenshot for the test executed on docker:
![124786521-adfe7400-df3f-11eb-8e14-f895f7eb7dfb](https://user-images.githubusercontent.com/41963549/144230160-ecdb2c3c-6951-4035-8ea5-1207b0cd04c0.png)

Robotframework HTML report of the same run:
![124785960-392b3a00-df3f-11eb-92ad-fe90f82d01d9](https://user-images.githubusercontent.com/41963549/144230825-7b90418e-d229-4487-8970-e8084dd4c0b4.png)

**Comment by pekkaklarck** [comment]
My guess is that reportportal or the tool sending information to it doesn't handle either the new IF/ELSE structure or the new NOT RUN status that keywords can have correctly. Robot itself doesn't directly send any information to it, but there could obviously be a big in the listener interface or somewhere else. 

I have never used reportportal nor have any idea how the reportportal integration works. I hope you can debug the problem further and contact people responsible on the integration.

**Comment by pekkaklarck** [comment]
No new info. Closing.
