### ISSUE TITLE
Tags are Ignored in Template-Based Test Cases

### ISSUE THREAD

**Issue by dc95ie** [robotframework/robotframework#4163]
Version Information
- Robot Framework: 4.1.1
- Interpreter: Python 3.7.3
- OS: Raspbian 10

Issue:
If test cases are developed using keyword templates defined with [Template], then any tags in those test cases (specified with [Tag]) are ignored. 

Issue Manifestation:
I use a tag called 'skip' to exclude certain test cases. If I use '--exclude skip' as a command-line argument when launching robot, any template-based test cases with the 'skip' tag still run. The 'skip' tag only appears to work on **non**-template-based test cases.

**Comment by pekkaklarck** [comment]
Are you using RF directly or via a tool like DataDriver? With RF there's shouldn't be any difference regarding to how tags are handled depending on is a test using a template or not.

**Comment by dc95ie** [comment]
Yes I am calling Robot Framework directly. Let me put together some example code showing my issue.

**Comment by pekkaklarck** [comment]
Did you get the example done?

**Comment by dc95ie** [comment]
I can't reproduce it. Closing.
