### ISSUE TITLE
Encode special characters is not working in Robot framework

### ISSUE THREAD

**Issue by aryalakshmi** [robotframework/robotframework#4167]
I have a requirement to encode special characters such as + and send it in an API request.
While trying to code it using RF with below script:

${b}	Encode String To Bytes	+	UTF-8

I see output of variable ${b} is + and it is not encoded.

RF version:
robotframework==3.1.2
robotframework-ride==1.7.4.1

Platform:
Windows 10

May i know if RF has a limitation for special characters.

**Comment by hello2ray** [comment]
it is converting to byte. Please use below line after this and check the type
${type string}=    Evaluate     type($b)

**Comment by pekkaklarck** [comment]
`Encode String To Bytes` does exactly what the name says, encodes a string to bytes. This is what happens in Python:
```python
>>> '+'.encode('UTF-8')
b'+'
```

**Comment by hello2ray** [comment]
@pekkaklarck. I agree with you.

**Comment by pekkaklarck** [comment]
No new info. Closing.
