### ISSUE TITLE
how do i get the traceback from a `HandlerExecutionFailed` in 5.0?

### ISSUE THREAD

**Issue by DetachHead** [robotframework/robotframework#4169]
the `traceback` property seems to have been removed. i tried using `get_error_details(full_traceback=True)` but it just returns an empty string
![image](https://user-images.githubusercontent.com/57028336/146115257-0e5a6476-393a-4dd1-9b8a-c849620573a1.png)

**Comment by pekkaklarck** [comment]
You need to provide some more details about what you are doing for me to understand this. Notice also that although `robot.utils` is considered to be part of the public API, internal exceptions like `HandlerExecutionFailed` are not.

**Comment by DetachHead** [comment]
nevermind, turns out we don't need it
