### ISSUE TITLE
Deprecate `Run Keyword Unless`

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#4174]
`Run Keyword Unless` has always been somewhat useless because `Run Keyword If` could have just been used with an opposite condition. Since `Run Keyword If` got support for `ELSE` (ages ago), it became even less useful and now that RF 4.0 brought native `IF/ELSE` syntax there's in practice no use for it.

`Run Keyword If` cannot be deprecated simply because it's so widely used and because it has some valid use cases. It's documentation should nevertheless be updated to make sure it doesn't recommend `Run Keyword Unless`.

**Comment by pmamico** [comment]
It's a closed issue, nevertheless I would like to share my point of view.
`Run Keyword Unless` totally make sense in an acceptance testing tool, where your goal is to make readable tests, not just working tests. 
`Run Keyword If`  `not ${Bool}` is less expressive in many cases, using `ELSE` is indirect and not a good alternative.
I understand that the same result can be achieved in other ways, but `Run Keyword Unless` was a simple but great attempt to make expressive lines.
However on the other hand, I don't see any negative impact of the `Run Keyword Unless` which would justify its deletion.

I also have many tests using this keyword. Now all my reports are full of `deprecated` warnings.
My current solution for that is creating my own `Run Keyword Unless` keyword, which seems very unnecessary to me.
Refactoring to IF/ELSE etc. is possible but you need to put some effort and the result is slightly worse code.

**Comment by pekkaklarck** [comment]
The keyword has only been deprecated, not removed, and we could still preserve it and remove deprecation if there are users who prefer it over `Run Keyword If` and native `IF/ELSE`. The main reason to remove it is to keep BuiltIn library small(ish). Having a keyword there that only very few people use doesn't make much sense, especially when there are alternatives that provide same functionality, but if it turns out there are several users for it we can think about this again.

**Comment by djwaxi** [comment]
> It's a closed issue, nevertheless I would like to share my point of view. `Run Keyword Unless` totally made sense in an acceptance testing tool, where your goal is to make readable tests, not just working tests. `Run Keyword If` `not ${Bool}` is less expressive in many cases, using `ELSE` is indirect and not a good alternative. I understand that the same result can be achieved in other ways, but `Run Keyword Unless` was a simple but great attempt to make expressive lines. However on the other hand, I don't see any negative impact of the `Run Keyword Unless` which would justify its deletion.
> 
> I also have many tests using this keyword. Now all my reports are full of `deprecated` warnings. My current solution for that is creating my own `Run Keyword Unless` keyword, which seems very unnecessary to me. Refactoring to IF/ELSE etc. is possible but you need to put some effort and the result is slightly worse code.

@pmamico Can you please post the by your own created keyword `Run Keyword Unless` ? Thanks.
