### ISSUE TITLE
Jenkins Plugin < Do not show critical tests

### ISSUE THREAD

**Issue by rosatarraga** [robotframework/robotframework#4183]
Hello folks!

Is there any way to not show the critical tests on the pipeline home page?

In our project we don't have critical tests and for quality reasons this "parameter" hinders our task. 

I have not been able to figure out a way to not show the critical tests in the pipeline.

I would appreciate any help, thanks!

**Comment by pekkaklarck** [comment]
This issue tracker is for bug reports and enhancement requests related to Robot Framework itself. Jenkins plugin has its own issue tracker. I don't know how it handles criticality nowadays, but RF 4 haven't even had that concept anymore.
