### ISSUE TITLE
User Guide: Update section about external tools

### ISSUE THREAD

**Issue by emanlove** [robotframework/robotframework#4186]
[Section 5.4 "External Tools" ](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#external-tools)references an old, broken link to the robotframework homepage.

> These tools are developed as separate projects independently from Robot Framework itself. For a list of the available tools see http://robotframework.org/#tools.

**Comment by pekkaklarck** [comment]
True. Is there any other link target we could use? The section is also otherwise pretty outdated and would be good to enhance it. For example, I don't think we should mention RIDE as the primary tool example anymore.

**Comment by pekkaklarck** [comment]
Ooops, wrong button.

**Comment by pekkaklarck** [comment]
Decided to link just to robotframework.org. It ought to be able to find tools from there anyway and any more direct link has a risk of breaking if the site is reorganized again. Decided not to enhance the section much otherwise. That can be done if/when we have a larger User Guide refresh project.
