### ISSUE TITLE
Listener interface: add hook for test end (pre-teardown)

### ISSUE THREAD

**Issue by tw39124-1** [robotframework/robotframework#4187]
It would be really useful if the Listener interface had a hook that is called when a test finishes but _prior_ to any test teardown being executed. The existing `end_test()` function is invoked _after_ teardown is complete. 

Consider the use case where if the test has failed for some reason and we want to store debugging information (such as the state of the host or the unit under test) _before_ the Teardown has come along and 'cleaned up' ready for the next test case. Of course, we could do this logging in the Teardown itself using `Run Keyword If Test Failed` keyword, but that requires modifying all Teardowns to do this - it would be nice to support this globally using the Listener interface too.

I'm thinking of an additional function called `end_test_pre_teardown()` or similar. I'd be happy to work on a PR for this if you agree it is a worthwhile addition to RF.

**Comment by pekkaklarck** [comment]
If you are using listener v. 2, you can use this:

**Comment by pekkaklarck** [comment]
Because listener v2 already support this and we already have plans for an enhancement that brings this also to v3, I close this issue. Let me know if you have a use case where the approach above wouldn't work.

**Comment by tw39124-1** [comment]
Hmmmm. I can see that it might be possible to do what I want using the method you suggest, but it seems a bit ugly to require the listener to do a load of internal stateful logic. Also how would I distinguish between Teardowns that are test teardowns, vs keyword teardowns?
