### ISSUE TITLE
Remove deprecated `--critical` and `--noncritical` options

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#4189]
When the criticality concept was removed in RF 4.0 (#3624), `--critical` and `--noncritical` were preserved as deprecated aliases for `--skiponfailure` to make the change less backwards incompatible. Now in RF 5.0 these options can be removed.

**Comment by makeevolution** [comment]
I'd like to try this one out

**Comment by pekkaklarck** [comment]
Thanks for the offer! Probably easier if I do it myself, though. This is mostly/only about removing traces of these options from various places (incl. docs) and it's hard for others to find them all.
