### ISSUE TITLE
Increase the limit of started keywords and control structures

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#4191]
Robot Framework limits how many keywords or control structures can be started to avoid hard crashes due to recursion (#551). The limit was initially 100, but due to that being too little on some platforms (at least Jython on Windows caused problems) it was lowered to 42. There have been proposals to increase it earlier (#2175) and now when we don't anymore support Jython it ought to be safe to do that. Let's raise the limit back to 100 and see does everything work fine.

**Comment by PBM86** [comment]
Hello Team,
We are working on building automated regression test suite with ROBOT +Python since more than an year (800+ test scripts). Recently while automating few test scenarios with many steps/validation, we are facing **Maximum limit of started keywords exceeded** error for **Set Variable** keyword.
So I wanted to check if the limit is increased to 100 or not?

**Comment by cmin764** [comment]
Hi, can we make this limit configurable in the robot run? (like a parameter or something)

**Comment by rm919** [comment]
I'm facing the issue of 'Maximum limit of started keywords and control structures exceeded'.
May i ask for the increase of the limit. Else can we make the limit editable?

**Comment by pekkaklarck** [comment]
RF 7.2 changes recursion prevention so that instead of there being a hard limit of started keywords and control structures, execution is stopped if we are close to Python's [recursion limit](https://docs.python.org/3/library/sys.html#sys.getrecursionlimit) (#5272). On my system this change raised the allowed number of started keywords and control structures to roughly 150. If that's not enough, you can increase Python's recursion limit to allow even deeper recursion.
