### ISSUE TITLE
The 'include' (probably also 'exclude' and 'noncritical') argument of 'robot.run()' doesn't work as expected

### ISSUE THREAD

**Issue by deathjest3r** [robotframework/robotframework#4198]
Calling, e.g.,
```
import robot
robot.run(..., include = ["basic_tests", "basic_commands"])
```
doesn't behave in the same way as, e.g., `robot ... --include basic_tests --include basic_commands`. The names are not properly handled and all the containing tests are skipped:

```
[ DataDriver ] Initialized in csv-mode.
[ DataDriver ] Reader Module: <module 'DataDriver.csv_reader' from '/usr/local/lib/python3.6/dist-packages/DataDriver/csv_reader.py'>
[ DataDriver ] Opening file 'xxxx/basic_commands/basic_commands.csv'
[ DataDriver ] 14 Test Cases loaded...
[ DataDriver ] data Table created
[ DataDriver ] 0 tests added.
tests on ubuntu1604.Basic Commands.Basic Commands :: Run Basic... | SKIP |
```
I tried, to replace `<underscores>` with `<spaces>` or (remove all special characters), i.e.,

```
import robot
robot.run(..., include = ["basic_tests".replace("_", " "), "basic_commands".replace("_", " ")])
```
But same behaviour.  Also removing the special characters altogether doesn't solve the problem. But when I just pass a single test in the list, e.g.,

```
robot.run(..., include = ["basic_tests"]
 ```
 my tests are correctly detected and executed:
 
 ```
[ DataDriver ] Initialized in csv-mode.
[ DataDriver ] Reader Module: <module 'DataDriver.csv_reader' from '/usr/local/lib/python3.6/dist-packages/DataDriver/csv_reader.py'>
[ DataDriver ] Opening file 'xxxx/basic_commands/basic_commands.csv'
[ DataDriver ] 14 Test Cases loaded...
[ DataDriver ] data Table created
[ DataDriver ] 14 tests added.
 ```

**Comment by pekkaklarck** [comment]
Just tested this myself and it worked fine. You seem to be using DataDriver. Can you test this without it?

**Comment by deathjest3r** [comment]
Sorry, you're right. It has to do with DataDriver. I will have a closer look what's the problem! Thank you, anyway for your quick reply!
