### ISSUE TITLE
Using `Set Test Variable` in suite setup or teardown should be a normal error, not a syntax error

### ISSUE THREAD

**Issue by MaximeAbout** [robotframework/robotframework#4204]
Hello, 

I'm facing an issue on Suite Teardown. From what I read in the documentation, the teardown should always been run:
![image](https://user-images.githubusercontent.com/97884384/150752902-aadb2994-0cfd-4497-957c-d28021a2f712.png)

But I just discover than, in case of keyword issue (not a test failure) it is not the case. Here a simple example inspired from my test suite:
```
*** Settings ***

Suite Setup         Setup
Suite Teardown      Release

Force Tags          robot:recursive-continue-on-failure
Default Tags        all

*** Test Cases ***

Test1
    Log  test1

*** Keywords ***
Setup
    Log  setup

Release
    SubRelease
    Log  Release 4

SubRelease
    Log  release 1
    Set Test variable   ${toto}   4
    Log  Release 3

```

Here the result
![image](https://user-images.githubusercontent.com/97884384/150753442-011e5e4f-4515-471a-afd7-afc6b904a74c.png)

I know that do a Set Test variable in a teardown is a mistake but still, teardown should not continue ?

Thank you. 
Best regards, 
Maxime

**Comment by pekkaklarck** [comment]
You are right that execution in general continues after failures in teardowns, but there's an exception to that rule that execution is not continued after syntax errors. To be honest I'm not sure is that a good exception and we could consider changing that. I am, however, sure that using `Set Test Variable` outside a test shouldn't be considered a syntax error. I can easily change that and then execution will continue in this particular case. If you believe execution should continue also after syntax errors, please submit a separate issue about that.
