### ISSUE TITLE
Parsing differences in try/except statements with get_model and data_only parameter

### ISSUE THREAD

**Issue by d-biehl** [robotframework/robotframework#4208]
Hi there,

In the new version 5.0 alpha1 there is a difference in parsing code with `robot.api.get_model` for try/except statements.

Given this piece of code:

```python
import ast
from robot.api.parsing import get_model


test = r"""
*** Test Cases ***
first
    Log    hi   

    TRY
        Fail    huch
    EXCEPT    huch    AS  ${a}
        Log    except ${a}  
    FINALLY
        Log    finally
    END
"""

for node in ast.walk(get_model(test, data_only=False)):
    if node.errors:
        print(node.errors)
```

If I set the data_only parameter to False (which is the default value) i will get:
```
("EXCEPT's AS marker must be second to last.", "EXCEPT's AS variable '\n' is invalid.")
```

which is not correct, because it is valid code. If I set the data_only parameter to True, then everything is ok.

I think the implementation is wrong in this case:

see here https://github.com/robotframework/robotframework/blob/b135d6ae56348d69fd64fb99ecdbbaf46beb997e/src/robot/parsing/model/statements.py#L950

The test for the AS token and the variable should not be done by index, because the tokens differs if we are parsing with `data_only= False` mode.

Also I think the message `EXCEPT's AS marker must be second to last.` is not really necessary, it should be enough to say that there is no variable or a wrong variable.

**Comment by pekkaklarck** [comment]
Great catch!

**Comment by pekkaklarck** [comment]
I'll assign this issue to RF 5.0 scope as a task with high priority. Being a task means it won't be included in to release notes unnecessarily.

There's PR #4209 to fix this.

**Comment by pekkaklarck** [comment]
Instead of assigning this issue to RF 5.0 scope I decided to reopen the original TRY/EXCEPT issue. This one can be closed now.
