### ISSUE TITLE
Argument validation fails in dry-run if arguments contain `&{dict}` variables

### ISSUE THREAD

**Issue by amoxuk** [robotframework/robotframework#4221]
a keyword is in a .py file as Variable, like arg.py
and a keyword is also in a .py file as Library, like xx.py

i want to pass a dict argument to a method.

when i use --dryrun, it will be error with `Keyword 'xx.Somkeyword' expected 3 arguments, got 0.
`.
when i not use --dryrun, it will be success.

i found that when `somkeyword` is in .robot file, this result is also success.

arg.py
```
somedict = {"a":{"a1":{"a":"1","b":2,"c":3}},"b":{"a1":{"a":"1","b":2,"c":3}},"c":{"a1":{"a":"1","b":2,"c":3}}}

```
xx.py
```
class xx:
    def somkeyword(self, a, b, c):
        print(a, b, c)
```

xx.robot
```
*** Settings ***
Suite Setup       some_setup
Library         xx.py
Variables        arg.py
*** Test Cases ***
some_case
    log     1

*** Keywords ***
some_setup
    FOR    ${name}    ${val}    IN    &{somedict}
        somkeyword    &{val["a1"]}
    END

```

**Comment by pekkaklarck** [comment]
I can reproduce the problem. Because variables aren't available in dry-run, we shouldn't do any argument validation if there are dictionary variables in arguments. It seems list variables are already handled that way.

**Comment by pekkaklarck** [comment]
You can @amoxuk edit the the description or any of your comments if you want to. Just click the `...` button in the top right corner.

**Comment by amoxuk** [comment]
Got it! thank you very much.
