### ISSUE TITLE
Issue when modifying a list of dictionaries

### ISSUE THREAD

**Issue by Uberr** [robotframework/robotframework#4223]
Hello, 
I've ran into the following issue while testing with robot framework 4.1.3

For the below code I create two lists list_1 and list_2 and then we append dict_1 to both the lists.
After that we are creating a second dictionary dict_2 and setting one of the keys in dict_2 as list_2.
Then we try and modify dict_2 

```
Testing list of dictionaries
	[Arguments]    ${var1}=${True}    ${var2}=${10}    ${var3}=${True}
	${list_1} =    Create List
	${list_2} =    Create List
	FOR    ${index}    IN RANGE    ${1}
            ${dict_1} =    Create Dictionary    itemId=123    itemValue=5
            Append To List    ${list_1}    ${dict_1}
            IF    '${var1}' == '${True}'
                Append To List    ${list_2}    ${dict_1}
            END
	END
	Log    list1: ${list_1}
	Log    list2: ${list_2}
	${dict_2} =    Create Dictionary    minimumValue=${var3}
	IF    '${var3}' == '${True}'
            Set To Dictionary    ${dict_2}    itemAmounts=${list_2} 
            IF    '${var2}' != '${EMPTY}'
                FOR    ${index}    IN RANGE    ${1}
                    Set To Dictionary    ${dict_2}[itemAmounts][${index}]        itemValue=${var2}
		END
            END
	END
	Log    list1: ${list_1}
	Log    list2: ${list_2}
```

The way I understand things is that the two list ( list_1 and list_2) are independent of each other but contain the same dictionary (dict_1). 
Also dict_2 contains list_2 under key itemAmounts
When I try to modify dict_2[itemAmounts] and retrieve the values for list_1 and list_2 it is apparently modifying the corresponding value for the key 'itemValue' in both list_2 and list_1.

![list of dictionaries](https://user-images.githubusercontent.com/6614724/153456620-f5733755-8a80-455b-ab9e-1fdb843837de.PNG)

**Comment by peerasut** [comment]
> @Uberr It's not a bug. It is how Python works.
> 
> From your code, `dict_2` contains `list_2` and `list_2` contains `dict_1`. <- This means that dict_2 contains dict_1 While `list_1` contains `dict_1`. Overall, this means that `list_1` and `list_2` depend on `dict_1`. If you change the value of `dict_1` both of `list_1` and `list_2` will be changed.
> 
> However, your understanding about independency of `list_1` and `list_2` is quite right but not all. Consider these examples. If you change something in `list_1` (BUT NOT the `dict_1`), it will affect only `list_1` not `list_2`.
> 
> ```
> Testing list of dictionaries
> 	${var1}    set variable    ${True}
> 	${var2}    set variable    ${10}
> 	${var3}    set variable    ${True}
> 	${list_1} =    Create List
> 	${list_2} =    Create List
> 	FOR    ${index}    IN RANGE    ${1}
>             ${dict_1} =    Create Dictionary    itemId=123    itemValue=5
>             Append To List    ${list_1}    ${dict_1}
>             IF    '${var1}' == '${True}'
>                 Append To List    ${list_2}    ${dict_1}
>             END
> 	END
> 	Log    list1: ${list_1}
> 	Log    list2: ${list_2}
> 	
>         # Add new item in list_1
> 	Append To List    ${list_1}    ${100}
> 	Log    list1: ${list_1}
> 	Log    list2: ${list_2}
> ```
> 
> results <img alt="image" width="787" src="https://user-images.githubusercontent.com/68002612/155840032-91b6cba0-a5c6-43e4-bbea-8f73ffce6f23.png">
> 
> On the contrast, if you change dict_1 inside of list_1, it will affect both `list_1` and `list_2`.
> 
> ```
> Testing list of dictionaries
> 	${var1}    set variable    ${True}
> 	${var2}    set variable    ${10}
> 	${var3}    set variable    ${True}
> 	${list_1} =    Create List
> 	${list_2} =    Create List
> 	FOR    ${index}    IN RANGE    ${1}
>             ${dict_1} =    Create Dictionary    itemId=123    itemValue=5
>             Append To List    ${list_1}    ${dict_1}
>             IF    '${var1}' == '${True}'
>                 Append To List    ${list_2}    ${dict_1}
>             END
> 	END
> 	Log    list1: ${list_1}
> 	Log    list2: ${list_2}
> 
>         # Change itemId in dict_1 which is inside of list_1
> 	Set To Dictionary    ${list_1}[0]        itemId=${1000}
> 	Log    list1: ${list_1}
> 	Log    list2: ${list_2}
> ```
> 
> result <img alt="image" width="722" src="https://user-images.githubusercontent.com/68002612/155840132-4f036a0c-af38-40a7-ac20-799afe15c7bd.png">
> 
> In this line of code, you make change of `dict_1` which is inside of `dict_2`. `Set To Dictionary ${dict_2}[itemAmounts][${index}] itemValue=${var2}`
> 
> As I illustrated above, this line of code will change both dict_1 and dict_2. Plus, it will affect list_1 and list_2 too.
> 
> **More info about how Python works this way** Since you use `Set To Dictionary` and `Append To List` keywords, it will create a shallow copy of that object. Read more about shallow copy [here](https://www.programiz.com/python-programming/shallow-deep-copy)

test

**Comment by pekkaklarck** [comment]
As already explained thoroughly above, your list has references to same dictionary. When you modify that dictionary, changes are seen everywhere. If that's not desired, you should copy the dictionary as also explained above.
