### ISSUE TITLE
Support importing Python variable files as modules, not only using a path

### ISSUE THREAD

**Issue by JockeJarre** [robotframework/robotframework#4226]
Normally you would use Python Variable files by adding ".py" to the ending:

`Variables    PythonModule.py    parameters`

But it does not allow writing 

`Variables    PythonModule    parameters`

instead you get the error: Variable file "PythonModule" does not exist.

Currently it is possible to have a Python Variable file without ".py" when you define a python package with a `__init__.py` file inside.

`Variables    PythonPackage    parameters`

**Comment by pekkaklarck** [comment]
Yeah, variable files can nowadays be imported only by giving a path to them. Typically the path is either absolute or relative to the directory where the test data file is, but variable files are actually also searched from locations in PYTHONPATH. Also in those cases the variable file must be given with the extension and it's not searched using Python's normal import mechanism. Being able to use a Python package (i.e. directory with `__init__.py`) as a variable "file" is actually a bug.

I don't remember exactly why we decided to support importing variable files only using a path, not as a module. Possibly the idea was to somehow separate them from libraries that typically are imported as a module, but actually also do support importing using a path. Also everything else that can be imported like listeners and pre-run modifiers can be imported both using a path and as a module.

I don't see any reason why we should keep the current behavior. For example, being able to install a module that provides reusable variables could be handy. In some cases it could also be convenient if a library could expose variables as well. Finally, being consistent with other imposts is good in general.

Implementing this functionality is pretty easy. For the actual imports we can use the same functionality that we already use libraries and other imports.

**Comment by pekkaklarck** [comment]
This was implemented in the above commit. Docs still need to be updated before we can close this issue.

**Comment by pekkaklarck** [comment]
Thanks @JockeJarre for helping with docs. I enhanced them further in a commit above.
