### ISSUE TITLE
Allow Python Variables file packaged as PythonPackage.Module

### ISSUE THREAD

**Issue by JockeJarre** [robotframework/robotframework#4228]
Currently it is possible to have a Python Variables file packaged as PythonPackage with a `__init__.py` file inside.

`Variables    PythonPackage    parameters`

But it does not allow writing 

`Variables    PythonPackage.Module    parameters`

instead you get the error: Variable file "PythonPackage.Module" does not exist.

Might be related to #4226

**Comment by pekkaklarck** [comment]
This is covered fully by #4226 If we make it possible to import variable files as modules, not only using a path, our import functionality handles packages and submodules automatically.
