### ISSUE TITLE
Add `&{OPTIONS}` to automatic variables to expose command line options

### ISSUE THREAD

**Issue by nicobucher** [robotframework/robotframework#4229]
It would be beneficial to be able to access command line options like "exclude tags" and "include tags" from within test cases.

This enhancement was sort of already requested in #3255 but this is a more general request.

As described also by @pekkaklarck in PR #4052 , a disctionary called "SETTINGS" containing these options would be best. Starting off with only exclude and include tags, the number of exposed options can be extended in the future.

**Comment by pekkaklarck** [comment]
Sounds good to me. Starting only with include and exclude info is ok, but I think it would be good to ask the community what else they'd like to be exposed. Not everyone is following this tracker so closely. Could you @nicobucher, or someone else, start a thread about this on the #devel channel in our Slack? Could obviously ask on other forums as well.

**Comment by pekkaklarck** [comment]
There seems to be PR #4230 implementing this. It refers this issue but apparently mentioning it only in the title doesn't create an automatic link.

**Comment by pekkaklarck** [comment]
I looked at PR #4230 quickly and it looks pretty good. I added few comments to it, though, and I hope they can be addressed soon.

I add this into RF 5.0 scope, but there's bit of hurry to get it actually included. We try to get the first RF 5.0 release candidate out this week or latest next week, and all features need to be in before that.

**Comment by pekkaklarck** [comment]
I started a discussion about other things to possible expose via this variable on the #devel channel on our Slack. No other requests at least yet, but there was a _very_ good point that `SETTINGS` can be easily associated with the `*** Settings ***` section which isn't good. There was discussion about alternative names, and my current thinking is that `OPTIONS` is best. It doesn't have direct association with the Settings section and will work also if other than command line options are exposed via this variable. The name is also consistent with other built-in variable names.

**Comment by pekkaklarck** [comment]
RF 5.0 rc 1 is now scheduled for Monday, February 21. That's also the deadline for getting this feature in to have it in RF 5.0 final.

**Comment by nicobucher** [comment]
@pekkaklarck I udpated the PR #4230 since the deadline is approaching. I think all the comments should be adressed including renaing the dictionary to OPTIONS and using robot.model.Tags instead of a plain list. Maybe it will be possible to merge before tomorrow?

**Comment by pekkaklarck** [comment]
The release candidate is a bit late for various reasons. This is now anyway in and will be included in the rc once its out.

Thanks for contribution @nicobucher!

**Comment by nicobucher** [comment]
Perfect, my pleasure!
