### ISSUE TITLE
Update screenshots in User Guide

### ISSUE THREAD

**Issue by rikerfi** [robotframework/robotframework#4235]
We should handle `FIXME: new screenshots of report / log.` statement away from the user guide: See: https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#report-file

**Comment by rikerfi** [comment]
Maybe renew together with PR #4190 : `Draft: Dark mode for report and log #4190 `

**Comment by pekkaklarck** [comment]
Yeah, screenshots need to be updated. Especially log screenshot is badly outdated.

**Comment by pekkaklarck** [comment]
I think UG contains also example log/report files. Need to update them as well.
