### ISSUE TITLE
Question of async process in Robot Test Case

### ISSUE THREAD

**Issue by nba2023** [robotframework/robotframework#4238]
Hi, i want to run a socket linstener in a test case,
the test case as following:
```
Submit Test Event
    ${task}  Run Keyword Async  Socket Listen
    Sleep  1s
    # trigger event
    Redfish.Post  /redfish/v1/EventService/Actions/EventService.SubmitTestEvent
    ...  body={'OriginOfCondition':'/redfish/v1/Systems/1/LogServices/StandardLog'}
    ...  valid_status_codes=[${HTTP_NO_CONTENT}]
    Sleep  1s
    ${resp}  Get Async Return  ${task}
    log  ${resp}
    ${line} =  Get Lines Containing String  ${resp}
    ...  Event Counter for Host ${OPENBMC_HOST} =
    should not be empty  ${line}
    [Teardown]  run keywords  Stop All Async
    ...  AND  Test Teardown Execution
```
The keyword `Run Keyword Async` will new a process to create socket server and listen from another keyword `Socket Listen`.
But sometimes output.xml parsing got error, the cause exists two XML tag names - `Submit Test Event`.
So does robot write xml thread safe or not?
If not how to avoid this error?
Thanks.

**Comment by databobek** [comment]
From my experience running asynchronously will most often than not break the output.xml, so I would recommend against it. Better idea is to run the asynchronous code in python and jsut call it from Robot.

**Comment by nba2023** [comment]
@databobek 
Yes, i do this in python file.
`Run Keyword Async` and `Socket Listen` define in python,
`Run Keyword Async` will create a thread pool to execute `Socket Listen` of socket server .bind() and .accept().
But still write duplicated tag name in report.xml probability.
```
...
...
...
<kw name="Run Keyword Async" library="runKeywordAsync">
<arguments>
<arg>Socket Listen</arg>
</arguments>
<assign>
<var>${task}</var>
</assign>
<msg timestamp="20220207 18:04:52.808" level="INFO"></doc>
<arguments>
...
...
...
<kw name="Run Keyword Async" library="runKeywordAsync">
<arguments>
<arg>Socket Listen</arg>
</arguments>
<assign>
<var>${task}</var>
</assign>
<kw name="Socket Listen" library="EventListener">${task} = 1</msg>
<status status="PASS" starttime="20220207 18:04:52.788" endtime="20220207 18:04:52.808"></status>
</kw>
...
...
...
```

**Comment by databobek** [comment]
Sorry I think I wasn't clear. You should have the entire async logic in python, and call the whole Python thing from Robot
def my_async_stuff():
    ....
    assert result


My Asynchronous Test Case
     My Async Stuff



Basically you have to omit a situation in which your test might cause Robot to write stuff to output asynchronously. It's not even Robot's fault tbh, it's just how those data files work (XML/json)

**Comment by pekkaklarck** [comment]
Writing output.xml isn't thread safe. If you need to leave keywords running on background, you must make sure they don't use things like `BuiltIn.run_keyword` when other keywords are executing. Basically such keywords should work silently until there's another keyword querying results. It seems you have `Get Async Return` for querying results so the overall setup looks fine.

With this example only it's impossible to tell where the problem is. This issue tracker probably isn't the best place for this kind of discussion either. It's reserved mainly for bug reports and concrete enhancement requests and, for example, our Slack is better for general discussion.

**Comment by nba2023** [comment]
Well, i refer to @databobek.
All test step write in .py file and remove `BuiltIn.run_keyword()`.
But still keep `logger.info()`
Run 50 rounds and get the error:
`robot.errors.DataError: Reading XML source 'output.xml' failed: Incompatible XML element 'doc'.`
When replace `logger.info()` to `logger.debug()`, it'll be pass for 200 rounds.
P.S. from robot.api import logger
