### ISSUE TITLE
ValueError: Argument 'arg' got value 'x.y' (x) that cannot be converted to x

### ISSUE THREAD

**Issue by naeimeh69** [robotframework/robotframework#4243]
Hi,
I have updated my robotframework to v4.1.0.
Now, I get error for enums.
I have an enum like below:

@enum.unique
class x(enum.Enum):
    y= 0x00
    z= 0x01

and I have arg defined as below:
arg = x.y

And I get below error when I run robot testcase
ValueError: Argument 'arg' got value 'x.y' (x) that cannot be converted to x

Could you please let me why the error occurred and what is the solution?

**Comment by pekkaklarck** [comment]
1. Which RF version did you use earlier?
2. Did you change anything else than RF version?
3. Could you provide a full, but simple, example demonstrating the problem I could try to run locally? Enums certainly should work and I cannot see any problems in the above example.

**Comment by pekkaklarck** [comment]
Closing due the lack of new info.
