### ISSUE TITLE
Suites with double underscore at end of filename results in a suite with no name

### ISSUE THREAD

**Issue by d-biehl** [robotframework/robotframework#4249]
A suite folder or suite file with double underscore at the end of the name, like 'test__.robot' or 'folder__', results in a suite with no name. 

Steps to reproduce:

- create a new RobotProject
- create a folder with name 'suite__'
- create a file with name 'first__.robot' in folder 'suite__'
- add a simple testcase to file 'first__.robot_ like:
```robotframework
*** Test Cases ***
simple
    Log    hello
```
- execute the suite with 'robot .'

the resulting output is:
```
==============================================================================
Rt1
==============================================================================
Rt1.
==============================================================================
Rt1..
==============================================================================
first                                                                 | PASS |
------------------------------------------------------------------------------
Rt1..                                                                 | PASS |
1 test, 1 passed, 0 failed
==============================================================================
Rt1.                                                                  | PASS |
1 test, 1 passed, 0 failed
==============================================================================
Rt1                                                                   | PASS |
1 test, 1 passed, 0 failed
==============================================================================
```

I expect that the correct suite names are in there like:
Rt1.Suite.First

Also the log and report doesn't show the correct suite name.

I assume that robot suitebuilder thinks, that the suite name is a prefix, see [here] (https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#test-suite-name-and-documentation) for explanations. But I think, if the name after the prefix is empty, it should be handled as a normal name, without a prefix.

Used Versions:
RobotFramework 4.1.3 and 5.0 beta 1

**Comment by pekkaklarck** [comment]
Yeah, `__` is considered a separator between the prefix and the name. I'm fine changing this so that if the name part is empty, the whole thing is considered a name. Do you @d-biehl have interest to look at changing it?
