### ISSUE TITLE
Suites with an underscore at the end can lead to ambiguous suite names

### ISSUE THREAD

**Issue by d-biehl** [robotframework/robotframework#4253]
Assuming that i have 2 files `first.robot` and `first_.robot`  and both have identical content, means a test case with the same name.

because undescores where converted to spaces and the name is stripped, both files leads to the same suite name "test"
if i want to execute the test "first.simple" with from command line like:
`robot -x xunit.xml -t "*.first.simple" .` always both tests are executed:

output is like this:
```
==============================================================================
Rt1
==============================================================================
Rt1.First
==============================================================================
simple                                                                | PASS |
------------------------------------------------------------------------------
Rt1.First                                                             | PASS |
1 test, 1 passed, 0 failed
==============================================================================
Rt1.First
==============================================================================
simple                                                                | PASS |
------------------------------------------------------------------------------
Rt1.First                                                             | PASS |
1 test, 1 passed, 0 failed
==============================================================================
Rt1                                                                   | PASS |
2 tests, 2 passed, 0 failed
==============================================================================
```

report looks the same and the xunit output is like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Rt1" tests="2" errors="0" failures="0" skipped="0" time="0.032" timestamp="2022-03-04T21:56:07.923000">
    <testsuite name="First" tests="1" errors="0" failures="0" skipped="0" time="0.004" timestamp="2022-03-04T21:56:07.945000">
        <testcase classname="Rt1.First" name="simple" time="0.001"></testcase>
    </testsuite>
    <testsuite name="First" tests="1" errors="0" failures="0" skipped="0" time="0.004" timestamp="2022-03-04T21:56:07.950000">
        <testcase classname="Rt1.First" name="simple" time="0.001"></testcase>
    </testsuite>
</testsuite>
```

After looking at the report, I dont know why 2 testcases are executed and also statics are incorrect if the xunit file is analysed and so on...

I think, if there is another suite with the same name allready added to the suite structure, then a warning should be shown at execution, like if there are multiple testcases with the same name.

**Comment by pekkaklarck** [comment]
Because all lower case file names are title cased and underscores are converted to spaces, you get same suite name also with all these file names `suite_name.robot`, `Suite_Name.robot`, `suite name.robot`, and `Suite Name.robot`. That can cause problems, but naming files like this is pretty much a user error and I don't think it's too severe. Possibly a warning could be emitted as proposed in the description, though.

**Comment by pekkaklarck** [comment]
Kind of related, it could sometimes be convenient to specify the suite name in the data. We could consider supporting this:

```
*** Settings ***
Name           Suite name!
```

**Comment by d-biehl** [comment]
I don't want to introduce something like a new setting or so. Just showing a warning, like it was shown if there are 2 test cases with the same name in a suite. That's enough I think.

**Comment by pekkaklarck** [comment]
Showing a warning is fine. Can be do in RF 5.0 still if you provide a PR. :smiley:

The support for `Name` setting isn't directly related to this. It could be handy, though, but would need its own issue. And it's not something we want to add anymore in RF 5.0.

**Comment by pekkaklarck** [comment]
This is now covered by #4268.
