### ISSUE TITLE
Update installation instructions

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#4259]
Installations instructions need to basically be rewritten now that we only support Python 3 (#3457).

**Comment by arunjunaigowtham** [comment]
I could take this up and wish to start contributing from here. Could you please let me know if there is anything specific need to be updated, or just we need to update INSTALL.rst with Python 3 references and remove Jython, Ipython references expect for RF 4.1?

**Comment by pekkaklarck** [comment]
At minimum we need to remove stuff related to versions we don't anymore support, probably should leave a link to old installation instructions for those still using them, but there's also many other things that could be enhanced. It's probably best I take care of this myself. Thanks anyway @arunjunaigowtham and hopefully there's something else you can help with!

**Comment by pekkaklarck** [comment]
I think instructions should still cover Python installation and I can update instructions related to Linux and Windows. I don't have recent OSX experience, though, and I have understood the Python situation there can be confusing. Earlier you could use Python version that was bundled in, but I think that's still Python 2.7. I've understood many OSX users have used homebrew, but I recently read somewhat that version you get from python.org would be good and even recommended nowadays. Any OSX users here who could comment about this? Ping @Snooz82 and @yanne at least.
