### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#4260]
README needs to be updated now that we support only Python 3 (#3457).

**Comment by pekkaklarck** [comment]
Sounds good. Main things to be done:
- Remove references to Python 2, Jython, etc. from descriptions, examples, etc.
- Mention that RF 5.0 requires Python 3.6 or newer.
- Mention that RF 4.1 still supports Python 2, Jython and IronPython. There should be a link either to the PyPI page or GitHub tag of the latest RF 4.1 release.

**Comment by suchdeep** [comment]
Thankyou @pekkaklarck  for listing the detailed expectations, Will start on it.

**Comment by suchdeep** [comment]
@pekkaklarck Can you tell the expected date by which you need this to be done?

**Comment by pekkaklarck** [comment]
Thanks for the PR @suchdeep. It seems to cover everything listed above. I nevertheless keep this issue open because I want to myself still go through the whole README once.
