### ISSUE TITLE
Invalid BREAK usage with dryrun

### ISSUE THREAD

**Issue by d-biehl** [robotframework/robotframework#4269]
Given this piece of code:

```robotframework
*** Test Cases ***
first test
    WHILE    True
        BREAK
    END
```

If I run this with in "dry run" mode like this:

`robot -d .\results\ --dryrun .\tests\playground.robot`

then I get an `Invalid 'BREAK' usage.` and the test fails with this output:

```
==============================================================================
Playground
==============================================================================
first test                                                            | FAIL |
Invalid 'BREAK' usage.
------------------------------------------------------------------------------
Playground                                                            | FAIL |
1 test, 0 passed, 1 failed
==============================================================================
Output:  C:\tmp\rt1\results\output.xml
Log:     C:\tmp\rt1\results\log.html
Report:  C:\tmp\rt1\results\report.html
```

I would expect that there is no error, also if I run this in dry run mode.

Versions:
Robot Framework 5.0rc1 (Python 3.10.2 on win32)

**Comment by yanne** [comment]
Thanks for the report! This is indeed a bug.

**Comment by d-biehl** [comment]
Thanks for fixing ;-)

**Comment by pekkaklarck** [comment]
Changed from `bug` to `task` to not get this listed in final 5.0 release notes. The fix is rather simple so I'm not sure is this big enough change to warrant rc 2. Let's at least wait a little time for other possible reported problems.
