### ISSUE TITLE
Differences in parsing IF/ELSE.. and TRY/EXCEPT statements with get_model(..., data_only=False)

### ISSUE THREAD

**Issue by d-biehl** [robotframework/robotframework#4270]
Given this piece of code: 

```python
import ast
from io import StringIO
from robot.api import get_model


DATA = """\
*** Test Cases ***
first
    IF  0

    ELSE

    END
"""

with StringIO(DATA) as data:
    model = get_model(data, data_only=True, curdir=".") # << data_only is not default value

for node in ast.walk(model):
    if node.errors:
        print(node.errors)
```

If I run this, i get:

```
('IF has empty body.',)
('ELSE has empty body.',)
```

But if I set data_only parameter to False, which is the the default value, I get no output.
I would expect, the output would be the same, like I set data_only to True.

I get the same behaviour, if I use TRY/EXCEPT statement like:

```robotframework
DATA = """\
*** Test Cases ***
first
    TRY

    EXCEPT

    END
"""
```

Tried it with robotframework 4.1.3 and 5.0rc1, both the same.

Another question I ask me is, why robot must check that a body is empty? I think this should be done by code analysis tools like robocop.

**Comment by d-biehl** [comment]
Also with inline IF with assignment I get different results:

```robotframework
DATA="""\
*** Test Cases ***
  first

    ${a}   IF    0    Evaluate    1    ELSE
"""
```

Output with data_only=False

```
('Inline IF with assignment can only contain keyword calls.',)
```

Output with data_only=True

```
('ELSE branch cannot be empty.',)
```

**Comment by pekkaklarck** [comment]
The problem with IF/ELSE and TRY/EXCEPT is due to those branches technically not being empty with `data_only=False`. Unlike when using `data_only=True`, they contain `EmptyLine` nodes. You would get the same error with both modes if there weren't those empty lines at all. On the other hand, the same problem would appear if you would have commented lines in the body. This problem isn't limited to IF/ELSE and TRY/EXCEPT, also FOR and WHILE are affected.

**Comment by pekkaklarck** [comment]
In the inline IF case there ends up being an `EmptyLine` in the ELSE block as well. Then in validation there's a check that body can only contain a keyword call when there's assignment and that fails. The idea of the validation is to disallow using e.g. BREAK in this case. Possibly validation could be enhanced but probably it would be better if there wasn't that `EmptyLine` in this case.

**Comment by pekkaklarck** [comment]
It seems that fixing the inline IF problem is pretty easy. Checking do IF, TRY, etc. blocks contain any data shouldn't be too complicated either, but I'm a bit worried would it have some performance effect. I don't consider this a too big problem in general, but obviously consistency would be good.

**Comment by pekkaklarck** [comment]
I'm a bit surprised you question the parsing time validation. In my opinion Robot itself recognizing actual syntax errors during parsing is important because it makes these errors visible to all consumers of the parsing APIs. RoboCop's main job is finding style problems and other similar issues.

**Comment by d-biehl** [comment]
Yeah, fixing this seems really easy, I think just replacing the:

```python
if not self.body:
   ...
```

with something like:

```python
if not any(s for s in self.body if not isinstance(s, (EmptyLine, Comment))):
   ...
```

in the `_validate_body` method is enough.
But that's my first impression...

It's a little bit more then just checking if body is not empty, but I think it should not really slow down the performance.

Regarding the validation of empty if/try/... I think, exactly this is the reason: Because it is a style problem. From parsers and most users view a block statement with an empty body is a correct statement. 

In other languages you can write something like 
```c
if (a==b) ;

if (a==b)  {} 
```

or

```ruby
if a == b
# empty body
end
```

```python
if a==b:
   pass  # empty body
```
In Robot know where the statement starts (IF) and we know where it ends (END), from parsing perspective this is valid and not a really syntax error. Except INLINE IF if there is an ELSE or the INLINE IF is an assignment, then these bodies must not be empty.

So again, from my view, empty bodies should be valid (except in exceptional cases) and a user should be warned by a `style checking` tool. That's how it works most languages.

But I can also live wit, that it is not possible to have empty bodies.  Just asked for the sake of interest.

**Comment by pekkaklarck** [comment]
I didn't realize you meant that it shouldn't be an error that a block is empty in the first place. I guess the syntax could be like that as well, but I see no real benefit from it. Empty blocks being an error is also consistent with empty tests and keywords being an error. These latter errors aren't yet recognized at parsing time, though.

Notice also that in Python
```python
if expr:
```
is an error and you need to add `pass` there to make it valid. Same way you need to add e.g. `No Operation` to Robot's blocks.

**Comment by pekkaklarck** [comment]
Fixed both of the problems and in general enhanced testing parsing with `data_only=False` in commits above. Thanks for the report!

**Comment by d-biehl** [comment]
Thanks for fixing it. That's exactly what I meant, what should be fixed ;-)

Just to make it clear again:

I was just wondering in general why it is necessary in IF/TRY/EXCEPT/FOR.... To check for an empty body and if it is empty to generate an error.

It seems a bit duplicated to me. Because the END is already there, why do I have to write "No Operation" there now? It makes the language a bit bumpy.

`pass` in Python is a statement, so part of the language, unlike "No Operation" which is a BuiltIn keyword/method and thus not part of the language.
`pass` in Python is used when syntactically a statement is expected, see also the [Python documentation](https://docs.python.org/3/tutorial/controlflow.html#pass-statements), and does not mean "no operation", it means for the parser, no action is required here.

"No Operation" is not really needed syntactically, because IF...END describes syntactically enough what I mean, even if I don`t want to execute an operation. The check for an empty body is just a tool to force the user not to write empty bodies. 

It is unusual when I start writing "IF a==b" then <kbd>Enter</kbd> then "END" and then I get an error displayed in the IDE. That feels so big right away, an error!!! I'm not even done yet!!!

I would rather expect a hint like 'Add a nested comment explaining why this keyword/block/... is empty, or complete the implementation' or something like 'Either remove or fill this block of code'.

Ok, but there are exceptions where it doesn't make sense that the body is empty, like test cases and keywords.

But this is just my opinion.
