### ISSUE TITLE
New &{OPTIONS} feature breaks test cases with existing ${options} variables

### ISSUE THREAD

**Issue by oboehmer** [robotframework/robotframework#4274]
I noticed the following test case to fail when run with robot 5.0rc1, i.e. with the #4230 changes introducing OPTIONS as a reserved variable. 

```
$ cat /tmp/o.robot
*** Variables ***
${options}   123

*** Test Cases ***
test
    Should be Equal   ${options}   123

$ robot /tmp/o.robot 
==============================================================================
O                                                                             
==============================================================================
test                                                                  | FAIL |
{'include': [], 'exclude': [], 'skip': [], 'skip_on_failure': []} != 123
------------------------------------------------------------------------------
O                                                                     | FAIL |
1 test, 0 passed, 1 failed
==============================================================================
```

It looks user-defined variables do NOT overwrite it, not even when specifying it on the command line, which should overwrite all:

```
$ robot --variable options:123 /tmp/o.robot 
==============================================================================
O                                                                             
==============================================================================
test                                                                  | FAIL |
{'include': [], 'exclude': [], 'skip': [], 'skip_on_failure': []} != 123
------------------------------------------------------------------------------
O                                                                     | FAIL |
1 test, 0 passed, 1 failed
==============================================================================
```

If this special variable affects robot tests where users defined options, I would strongly opt to rename it to use a different name, as failures can be difficult to troubleshoot (as I just witnessed it as one obscure tests failed in our integration run)

**Comment by pekkaklarck** [comment]
This is pretty bad. I was thinking user created variables would override `&{OPTIONS}`. RF 5 being a major release, we could do a change like this, but I don't think it's a good idea. Renaming the variable isn't a good solution either because any short name can be used. Adding a prefix like `&{ROBOT:OPTIONS}` would be inconsistent with other such variables and also rather ugly.

Probably the best solution would be changing the logic so that user variables would override the built-on ones.
