### ISSUE TITLE
Run Keyword And Return Status keyword should not produce FAIL badges in report

### ISSUE THREAD

**Issue by sebastianciupinski** [robotframework/robotframework#4287]
Currently, contructions like
```
${is_equal}=     Run keyword and return status      Should Be Equal       ${a}   ${b}
```

are producing FAIL messages in log, when internal keyword fails. In fact, when using `Run Keyword and Return Status` we are not interested of result of internal keyword, but we want to have this result mapped to variable.

Now, Internal Keyword produces red FAIL badge in log, which is confusing, especially when log is flattened.

**Comment by pekkaklarck** [comment]
The keyword that was executed failed and I see no problem it getting FAIL status. The higher level keyword nevertheless passes. If you want, you can use `--prerebotmodifier` to change keyword statuses.

**Comment by sebastianciupinski** [comment]
@pekkaklarck - unfortunately, it is hard to track parent keyword when flattening keywords...

simple prerebotmidifier like this:
```
    def visit_keyword(self, kw):
        if "BuiltIn.Run Keyword And Return Status" in str(kw.parent) :
            kw.messages[0].level = "INFO"
```
 works fine and removes red FAIL badge when executing `robot --prerebotmodifier /some/location/ResultModifier.py someTest.robot`
 
![image](https://user-images.githubusercontent.com/40261029/159742801-e224aed3-9bbf-4efc-9eba-d3c0c5da36b3.png)


but does not work when adding keyword flattening: `robot --flattenkeywords NAME:* --prerebotmodifier /some/locationResultModifier.py  someTest.robot` (because parent of Should Be Equal As Strings is not Run Keyword And Return Status anymore)

![image](https://user-images.githubusercontent.com/40261029/159743245-9d577945-da85-4fc2-9b2d-751e1ea480ce.png)
