### ISSUE TITLE
Best way to detect time out on run process?

### ISSUE THREAD

**Issue by Harm10** [robotframework/robotframework#4288]
Hi! I have a question (is this the right platform for this?):

What is the best way to detect a time out from run process?
If I return in ${result} then ${result.rc} contains huge minus number but those numbers are different on different machines.
Is there somewhere in the ${result} I can detect a time out situation?

**Comment by pekkaklarck** [comment]
`${result.rc}` is got directly from [Popen.returncode](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.returncode).

**Comment by Harm10** [comment]
For other readers: the link specifies this: A negative value -N indicates that the child was terminated by signal N (POSIX only).

So any negative value means a time-out!

**Comment by Harm10** [comment]
@pekkaklarck I would like to reopen this one (but do not see how to do that)
I am running on Windows and I inadvertently wrote that I get a huge minus number when timing out the process. But this is not exactly true. I get a huge positive number (which is different on other Windows machines).

I do not know exactly what POSIX means but it looks as something on another platform then Windows.

So how to detect a timeout on a process started on Windows?

**Comment by pekkaklarck** [comment]
As I wrote above, we get `rc` directly from `Popen.returncode`. I'm not sure where it gets it or how different operating systems handle return codes in general.

This issue tracker is for bug reports and enhancement requests, not for general questions. If you cannot find solution yourself, I recommend asking more help on our Slack or Forum. How to interpret `Popen.returncode` isn't really related to Robot Framework either, so you could ask about that e.g. on StackOverflow as well.

**Comment by Harm10** [comment]
OK. Fine. I think it is weird that you get uncontrollable return codes from Popen on timeout and even different depending on the Windows machine you are on executing the exact same code. So as an user I cannot trust this return of run process.
Although I understand this cannot be classified as a bug any Windows user should be aware of it. So perhaps a warning in the documentation could be in order?

In the meantime I have set up a work around for the timeout principle of run process.
I am now using start process, wait process and after that is process running to conclude that a time out has occurred but this only works when on_timeout=continue is selected.
So anyone knows.
