### ISSUE TITLE
Unable to launch the Mainframe Terminal via RobotFramework on Mac

### ISSUE THREAD

**Issue by sayom88** [robotframework/robotframework#4300]
Hello Team, need one help running Mainframe scripts on Mac platform…i am using MacOS Monterey(v 12.2.1) and want to run my Mainframe automation script created using RobotFramework keywords…the same script is perfectly working fine on Windows machine…in my Mac, I have installed Xquartz (https://www.xquartz.org/), now when I run the script, it is throwing error of not able to launch the terminal…can anyone let me know what extra settings needs to be done please?

**Comment by pekkaklarck** [comment]
If it works on Windows and not on MacOS, it's clearly not a problem with RF itself.
