### ISSUE TITLE
Robot Framework is not compatible with rpaframework; robotframework-assertion-engine

### ISSUE THREAD

**Issue by joaogoncalves83** [robotframework/robotframework#4301]
Hi everyone,

I tryed to install the version 5.0, but seems there are some conflicts.
![image](https://user-images.githubusercontent.com/4416357/161941362-4a385255-6bee-4c6a-a124-23b955a15fb1.png)

Thank you for your work.

Joao

**Comment by oboehmer** [comment]
I guess you want to raise this issue with the rpaframework and robotframework-assertion-engine maintainers, they are imposing the restrictions?

**Comment by pekkaklarck** [comment]
Yeah, sounds like these projects would explicitly limit RF version to < 5.0. You should submit issues to their trackers about the limitation. If there is a concrete regression in RF preventing using 5.0, please submit new issue(s) describing the actual problem.

When including text output in nug reports, please copy the text to the issue. Images are hard to read on mobile in general, but red text on black background is nearly unreadable.
