### ISSUE TITLE
Remove `Reserved` library

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#4302]
The Reserved library contains keywords `For`, `While`, `Break`, `Continue`, `End`, `If`, `Else`, `Elif`, `Else If`, and `Return`. Using them fails with a message telling that the keyword name is reserved and some keywords also instruct how to use the actual `FOR`, `IF`, etc. syntax.

We added the library ages ago to avoid problems if new syntax is added. Now all the syntax there (and more!) has been added so there's no need to reserve anything. When we added `IF` in RF 4.0, we also made a decision to require all this kind of syntax to be upper case. That makes it mostly unnecessary to reserve possible new syntax because even if we'd add something like `CASE`, there would be no problem using keyword `Case`.

When this library is removed, using a keyword like `Continue` will continue to fail, but the error message changes from `'Continue' is a reserved keyword.` to `No keyword with name 'Continue' found.`. With keywords containing usage instructions, like `If` that currently fails like `'If' is a reserved keyword. It must be an upper case 'IF' when used as a marker.`, the new error isn't as informative as earlier. I would say we can nowadays expect users to know that this kind of syntax must be upper case so this isn't a big deal. If we were to report such errors to users, we should detect them already at parsing time anyway to make errors easily available for IDEs and other tools using Robot's parsing modules.

A benefit of removing the Reserved library is that in some contexts the current custom error message is pretty confusing. For a concrete example, see #4297.

**Comment by Pratapreddy1188** [comment]
Instead of removing, May be we  could  simply make all of the keywords to Uppercase and keep appending newly added.

**Comment by pekkaklarck** [comment]
What benefits would that bring?

**Comment by yorgoA** [comment]
so technically we can't use IF anymore ?

**Comment by pekkaklarck** [comment]
This issue doesn't affect using `IF` at all. It's recognized as a control structure already by the parser and never considered a keyword. If you use `If` (not all caps), the error message will change as explained above. If you happen to actually have your own keyword with name `If`, using it will work exactly as earlier.
