### ISSUE TITLE
New technology for Libdoc HTML outputs

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#4304]
Libdoc HTML outputs, similarly as log.html and report.html, use [jQuery Templates](https://github.com/BorisMoore/jquery-tmpl) for generating HTML content based on the date embedded to the outputs when they are created by Libdoc. In practice there's [libdoc.html](https://github.com/robotframework/robotframework/tree/master/src/robot/htmldata/libdoc) file that contains template code as well as JavaScript. It also uses external styles and some external JavaScript files used also by Rebot.

The explained setup has worked fine for us, but there's a problem that jQuery Templates have been unmaintained for years. We need to find a replacement for it and at the same time we should enhance our HTML/JavaScript setup in general. At least the following tasks should be done:

- [x] Find a replacement for jQuery Templates. We could use its successor [JsRender](https://www.jsviews.com/) or some totally new technology like [Svelte](https://svelte.dev).
- [x] Separate JavaScript code from HTML templates as much as possible.
- [x] Add tests for JavaScript model code. A precondition is deciding what test tool(s) to use.
- [x] Set up GitHub actions to run JavaScript tests.
- [x] Decide and document JavaScript coding conventions. Using an automated code formatter could be a good idea.
- [x] Take localization into account. See #3676.
- [x] Take accessibility into account. See #3879.

**Comment by pekkaklarck** [comment]
This issue is a precondition for modernizing the tech used by log.html and report.html. They contain a lot more JavaScript code and having better JavaScript setup (test system, CI, conventions, ...) in place will help. Enhancing log.html and report.html requires its own issue and is probably so big task that it needs to wait for RF 6.0.

**Comment by mkorpela** [comment]
I would consider using plane vanilla js for templating. Current techs like Svelte, Vue, React, Angular etc. are in my opinion towards dynamic sites.
We do not need them.
Modern Js is very good for templating.

**Comment by pekkaklarck** [comment]
As #4497 explains, it would be convenient to be able to use custom styles with Libdoc. Injecting custom styles to generated HTML files wouldn't be hard, but the problem is that then the whole HTML structure becomes part of the public API and changes to it can break external styles. If we allow that, we probably should decide what parts of the structure (ids, classes, etc.) would be considered stable and only changed if absolutely needed and only in major versions.

**Comment by pekkaklarck** [comment]
There hasn't been too much interest towards this lately. I'll move this from RF 7 scope to 7.1.

**Comment by yanne** [comment]
This is now done and will be released in RF 7.2
