### ISSUE TITLE
[Listener] Attributes["type] returning teardown only for KW,Testcase and Suite

### ISSUE THREAD

**Issue by hemachnadra** [robotframework/robotframework#4310]
Attributes["type] returning teardown only the kind of KW, Testcase and Suite Teardown 

In end_keyword method the attributes['type'] returning the Teardown only,
if type values should be like for different kind teardown. that should be great  

KW-teardown        ------------ ---------Attributes["type]=="keyword_teardown"
Testcase teardown ---------------------Attributes["type]=="testcase_teardown"
Suite Teardown      ---------------------Attributes["type]=="suite_teardown".

**Comment by pekkaklarck** [comment]
You can pretty easily keep track is the teardown part of suite, test or keyword by implementing `start/end_suite/test/keyword` methods. Changing the reported type would be backwards incompatible and not worth the problems it would cause.
