### ISSUE TITLE
RF5: AttributeError: 'HandlerExecutionFailed' object has no attribute 'full_message'

### ISSUE THREAD

**Issue by oianson** [robotframework/robotframework#4316]
In RF5.0 when using 'rfshell' or either the 'DebugLibrary' when I am using keywords which are failing/raising exceptions I am getting the following error `AttributeError: 'HandlerExecutionFailed' object has no attribute 'full_message'`

```
root@012d6b95697e:/home/cisco/cxta# rfshell
==============================================================================
Robot-Debug-Fybfasw9
==============================================================================
RFDEBUG REPL
>>>>> Enter interactive shell
Only accepted plain text format keyword separated with two or more spaces.
Type "help" for more information.
> should contain  foo   bar
! keyword: should contain  foo   bar
RFDEBUG REPL                                                          | FAIL |
AttributeError: 'HandlerExecutionFailed' object has no attribute 'full_message'
------------------------------------------------------------------------------
Robot-Debug-Fybfasw9                                                  | FAIL |
1 test, 0 passed, 1 failed
==============================================================================
Output:  None
```

I do not see this on RF4.0

**Comment by jsteltze** [comment]
@oianson have you solved this problem? I am experiencing the same issue. Using rfdebug with RF5.0.
This error causes the Browser to crash :-(

**Comment by oianson** [comment]
> @oianson have you solved this problem? I am experiencing the same issue. Using rfdebug with RF5.0. This error causes the Browser to crash :-(

I raised a possible fix here .. https://github.com/xyb/robotframework-debuglibrary/pull/67  not sure if the repo maintainer is inactive though

**Comment by jsteltze** [comment]
I applied your fix in my local `DebugLibrary/debugcmd.py` (removed __pycache__ folder to force re-compile).
Works fine :-) Thank you very much!!
