### ISSUE TITLE
Run robot with sudo

### ISSUE THREAD

**Issue by lifang-zhang** [robotframework/robotframework#4320]
Robot is installed into `~/.local/bin/robot` by default, it works fine after I added `~/.local/bin/robot`  to PATH. But if I run it with sudo e.g. `sudo robot --version`, it says `sudo: robot: command not found` which I believe is because it is not contained in the PATH of the superuser or root. So I ran `sudo ~/.local/bin/robot --version` it gave me `from robot.run import run_cli
ModuleNotFoundError: No module named 'robot'`. Regarding this problem, I am wonering first, why robot is not installed to standard location like `/usr/local/bin`? And how should I install it there? I tried to install with `sudo pip install --upgrade --install-option=/usr/local/bin/ robotframework` but failed. So how can I run robot with sudo?

**Comment by pekkaklarck** [comment]
Robot is installed by default to whatever location Python/pip you use installs stuff by default. On Linux machines that's nowadays typically under the current user. You can configure that but I don't remember exactly how. You need to consult pip and/or OS docs for details.

I'm not sure what's the problem using sudo. Most likely configs aren't right when you use it with user installed package. You could try installing using sudo as well.

This issue tracker is for bug reports and enhancement reports and I close this issue. If you need more help, please use our Slack, Forum, or other such support channels listed at robotframework.org.
