### ISSUE TITLE
DateTime: Enhance documentation related to the epoch time format

### ISSUE THREAD

**Issue by UliSei** [robotframework/robotframework#4322]
I'd suggest to keep the sentence in the **Epoch time** abstract:
"Notice that epoch time itself is independent on timezones and thus same around the world at a certain time. What local time a certain epoch time matches obviously then depends on the timezone."

Then append
"See also Python [datetime ](https://docs.python.org/3/library/datetime.html#aware-and-naive-objects) library."

And finally show these examples:
![grafik](https://user-images.githubusercontent.com/89480399/165138462-08f49b51-6907-40bd-bc40-48c5b347c142.png)

---
Source that can be copied for testing:
```
** Settings ***
Library    DateTime

*** Test Cases ***
Epoch time in RF refers to local time
    ${date_TS}    Get Current Date    time_zone=local    result_format=timestamp    exclude_millis=True
    ${dateEp1}    Convert Date    ${date_TS}    epoch    exclude_millis=True
    ${dateEp2}    Get Current Date    time_zone=UTC    increment=+ 0 hours    result_format=epoch        exclude_millis=True    # UTC is ignored
    Should Be Equal As Integers    ${dateEp1}    ${dateEp2}    # Always True, wherever on the world the test case is started

    ${dateEp3}    Get Current Date    time_zone=UTC    increment=+ 1 hours    result_format=epoch        exclude_millis=True    # UTC is ignored
    ${dateEp2}    Evaluate    ${dateEp2} + 3600
    Should Be Equal As Integers    ${dateEp2}    ${dateEp3}    # Always True, wherever on the world the test case is started
```

**Comment by pekkaklarck** [comment]
I agree documentation related to epoch time can be enhanced. I don't think adding a link to the discussion about aware vs. naïve `datetime` objects really help in this context, though, and believe that the proposed example is somewhat complicated as well. I've done some other enhancements and will commit them shortly. Hopefully you @UliSei can take a look at them and comment if there's something that can still be enhanced.
