### ISSUE TITLE
Script fails when variable is set in command line. Workaround is to Evaluate the variable.

### ISSUE THREAD

**Issue by UliSei** [robotframework/robotframework#4323]
I don't understand why I need to use the workaround in line 12:

```
*** Settings ***
Library    DateTime


*** Variables ***
${EPOCHDATE}    ${60}


*** Test Cases ***
Convert Given Epoch
    Log To Console    \n\${EPOCHDATE}=${EPOCHDATE}
    ${EPOCHDATE}    Evaluate    ${EPOCHDATE}*1     # workaround
    ${epochTS}    Convert Date    ${EPOCHDATE}
    Log To Console    \n${EPOCHDATE} was converted to ${epochTS}

```

Given line 12 is active 
When I call **robot --variable EPOCHDATE:60 callWithArgument.robot**
Then the result is PASS.

Given line 12 is commented 
When I call **robot --variable EPOCHDATE:60 callWithArgument.robot**
Then the result is FAIL.

Given line 12 is commented 
When I call **robot callWithArgument.robot**
Then the result is PASS.

**Comment by Pratapreddy1188** [comment]
workout is just making that string to convert to proper variable.

Difference 
Convert Date 60

Convert Date  ${60}

https://robotframework.org/robotframework/latest/libraries/DateTime.html#Epoch%20time

**Comment by UliSei** [comment]
I'd suggest to add one further line as example:
![grafik](https://user-images.githubusercontent.com/89480399/165489244-9ff08d2b-b57b-4ec9-a5b5-5a2c2de28e4d.png)

How do you think about it?

**Comment by pekkaklarck** [comment]
Values you give from the command line are strings. Thus if you want a value you pass like `--variable EPOCHDATE:60` to be considered an integer, it needs to be converted. Some keywords do conversion automatically, but `Convert Date` explicitly handles strings an numbers differently so you need to do conversion yourself.

Being able to pass non-string values from the command line would be sometimes handy. We already have #2946 about that so this issue can be closed.
