### ISSUE TITLE
List should return non matching elements from 2 comparing lists

### ISSUE THREAD

**Issue by Wankhede** [robotframework/robotframework#4326]
Library  Collections
@{list1} =  create list  a   b   c   d   e
@{list2} =  create list  a   b   d   e   h

    Log     ${list1}
    Log     ${list2}
    ${c1}   Get Length  ${list1}
    ${c2}   Get Length  ${list2}

I want those elements from list which are not in common
How do i get it?
Pls help

**Comment by peerasut** [comment]
If I understand your question correctly. From the given example, you want to get letter `c` and `h` which are two letters that are distinct, right?

If so, there are a lot of methods to solve this. Basicly, you could just Google it. I'll give you a pythonic way to solve the problem.

**Using XOR operator for set**
If you don't care about order of each element in your lists, you could use this method.

``` Robot Framework
	@{list1}     Create List    a    b    c    d    e
	@{list2}     Create List    a    b    d    e    h
	${diff_elements}    Evaluate    list(set($list1) ^ set($list2))
	Log    ${diff_elements}
```

**Result**
<img width="577" alt="image" src="https://user-images.githubusercontent.com/68002612/165768769-78bfcb92-01a8-4368-85fc-763dd42fd8df.png">


**Explanation**
First, we use `Evaluate` keyword, which will execute the given command as Python command.
In Python command: 
- I used `set()` to clear out duplicates element if any.
- ^ operator is XOR operator in Python. Technically, we might say it's a symmetric difference for two sets. Basically, given set A XOR set B, it returns what's not common for both set A and set B, just like what you need.
- Output of XOR operator for set is a set. So, I convert the output set to a list in order that you could index the elements in the result.
- Be aware that set in Python is an unordered collection. So the result would be either `['c', 'h']` or `['h', 'c']`

Other method, you could FOR loop and check for each element. But beware of performance aspect.

**Comment by pekkaklarck** [comment]
I don't think there's any ready-made keyword for this. Implementing a custom keyword in Python would be pretty easy and, as examples above demonstrate, its possible to also use `Evaluate`.

If you need more help, please ask on the discussion forum, Slack, or other support channel listed at robotframework.org. If you think we should add a keyword implementing this e.g. to the Collections library, please submit a new issue.
