### ISSUE TITLE
async run throwing exception

### ISSUE THREAD

**Issue by sankonam** [robotframework/robotframework#4329]
I am trying to run user keywords asynchronously using AsyncLibrary in robot framework.
it is throwing exception. is this library working or we have any other way to do the same

20220429 17:51:36.803 - INFO - +-- START KEYWORD: AsyncLibrary.Async Run [ Files Create | arg1 | arg2 ]
20220429 17:51:36.819 - INFO - Exception in thread Thread-5:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3312.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap_inner
20220429 17:51:36.819 - INFO - ${handle} = 0
20220429 17:51:36.819 - INFO - +-- END KEYWORD: AsyncLibrary.Async Run (16)

**Comment by pekkaklarck** [comment]
You need to report this issue to the AsyncLibrary. I have no experience from it myself.
