### ISSUE TITLE
Test passed, but should have failed - using "should contain"

### ISSUE THREAD

**Issue by ggeyer** [robotframework/robotframework#4334]
I run a command on a remote machine and set a variable.
The variable(string) should contain a certain string. 
If it does not contain the string the test should fail, but for some reason it pass. 

Test:
Ping 
  ${v4output}=          Execute Command       ip netns exec vlan_807_101 ping -I 10.255.12.104 10.255.12.3 -c 10 -f      sudo=True
  ${v6output}=          Execute Command       ip netns exec vlan_807_101 ping -I 10:255:12::104 10:255:12::3 -c 10 -f      sudo=True
  Should Contain      ${v4output}             0% packet loss
  Should Contain      ${v6output}             0% packet loss
  Log                 ${v4output}
  Log                 ${v6output}

This is from the log:

KEYWORD ${v4output} = SSHLibrary . Execute Command ip netns exec vlan_807_101 ping -I 10.255.12.104 10.255.12.3 -c 10 -f, sudo=True
Documentation:	
Executes command on the remote machine and returns its outputs.

Start / End / Elapsed:	20220505 21:20:53.318 / 20220505 21:20:56.415 / 00:00:03.097
21:20:53.318	INFO	Executing command 'sudo ip netns exec vlan_807_101 ping -I 10.255.12.104 10.255.12.3 -c 10 -f'.	
21:20:56.415	INFO	Command exited with return code 1.	
21:20:56.415	INFO	${v4output} = PING 10.255.12.3 (10.255.12.3) from 10.255.12.104 : 56(84) bytes of data.
..........EEEEEEEEEE
--- 10.255.12.3 ping statistics ---
10 packets transmitted, 0 received, +10 errors, 100% packet...

**Comment by pekkaklarck** [comment]
If your output contains `100% packet loss`, it also contains `0% packet loss`. If that's not the case, please include the actual error message here. Now you seem to only include part of the output returned by Execute Command.

**Comment by ggeyer** [comment]
you are absolutely right. 
rookie mistake.
Thanks
