### ISSUE TITLE
Pass more information about control structures to `start/end_keyword` listener methods

### ISSUE THREAD

**Issue by osrjv** [robotframework/robotframework#4335]
### Why

In listener API v2, control structures such as IF or FOR use the same `start_keyword` and `end_keyword` methods as regular keywords. Additional fields specific for those statements are lost, such as the conditional statements for an IF branch, or the assigned variables for a FOR loop.

Parsing these is possible, to some degree, from the string representation marked as the name for these "keywords". However having them available directly in the attributes would help many use-cases.

### What

I propose that additional attributes are available based on the `type` attribute, which should be backwards compatible to previous versions.

The attributes would be as follows (same as in the models):

**FOR**: `variables`, `flavor`, `values`
**WHILE**: `condition`, `limit`
**IF / ELSE_IF**: `condition`
**EXCEPT**: `patterns`, `pattern_type`, `variable`
**RETURN**: `values`

### How

The attributes/arguments for listeners are defined [here](https://github.com/robotframework/robotframework/blob/master/src/robot/output/listenerarguments.py#L128). A look-up for extra attributes could be done based on the `repr_args` field of the control structure model, for instance. Alternatively a separate map of type to extra attributes could be maintained.

**Comment by pekkaklarck** [comment]
Sounds good to me. Are you @osrjv interested to create PR?

**Comment by osrjv** [comment]
I think I can make a draft PR with a suggestion and we can continue the discussion there.

**Comment by pekkaklarck** [comment]
Are you @osrjv still working with the PR?

**Comment by osrjv** [comment]
> Are you @osrjv still working with the PR?

Sorry, I was busy with vacation season and other priorities after your response to the PR. I'll try to pick this up again now and get it finished.

**Comment by pekkaklarck** [comment]
Thanks for a great PR @osrjv!
