### ISSUE TITLE
A syntax error in suite teardown should not stop the entire teardown 

### ISSUE THREAD

**Issue by MaximeAbout** [robotframework/robotframework#4338]
Hello, 
Following the suggestion https://github.com/robotframework/robotframework/issues/4204#issuecomment-1119830928 I do think it is important to make sure the Suite Teardown is entirely executed, even after a syntax errors. It could just jump to the next keyword.

Thanks !
Maxime

**Comment by MaximeAbout** [comment]
Hello, 
Could someone tell me if it is possible to consider this ticket please ?

**Comment by pekkaklarck** [comment]
I believe actual syntax errors should prevent execution, but the problem has been that we have considered many situations where the syntax hasn't been a problem syntax errors. The situation should be much better nowadays, though. If you have concrete examples of cases where execution nowadays doesn't continue but should, please submit separate issues.
