### ISSUE TITLE
Enhance documentation of the `--timestampoutputs` option

### ISSUE THREAD

**Issue by UliSei** [robotframework/robotframework#4346]
RF 5.0, User Guide,
[6.2.1   Command line options for test execution](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#toc-entry-618)
"-T, --timestampoutputs
   Adds a timestamp **to all** output files."
   
I'd suggests a more specific description:
"-T, --timestampoutputs
   Adds a timestamp to the output files log.html, output.xml and report.html.
   In general the timestamp is not added to output files written by libraries." 
   
(Example of an output file that is not influenced by -T option: **Browser Library**, playwright-log.txt [see closed issue 2050](https://github.com/MarketSquare/robotframework-browser/issues/2050))

**Comment by pekkaklarck** [comment]
I'm fine making this more explicit but the proposed wording isn't exactly correct. Timestamps are added also to xunit and debug files. Perhaps it would be enough to just change the documentation to this:

> Adds a timestamp to all output files generated by Robot Framework itself.

Then possibly a more detailed explanation could be added to the [actual documentation](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#timestamping-output-files) of this option that's linked from the list of command line options.

**Comment by UliSei** [comment]
Yes, I like the separation in the overview and the more detailed explanation.
The more detailed docu could show examples for positive and negative cases, something like this:
"Adds a timestamp to log, output, report, xunit and debug files.
Some output files generated by libraries like playwright-log.txt are not affected by the timestamp option."

**Comment by pekkaklarck** [comment]
The actual documentation of the `--timestampoutputs` option already was pretty explicit about this. I'll do small adjustment anyway.
