### ISSUE TITLE
Continuable failures terminate WHILE loops

### ISSUE THREAD

**Issue by oboehmer** [robotframework/robotframework#4355]
I would expect `robot:continue-on-failure` to continue a `WHILE` loop, however it only continues the current iteration and then aborts

```
*** Test Cases ***
Continue in WHILE loop with continue tag
    [Tags]   robot:continue-on-failure
    ${val}=   Set Variable   ${0}
    WHILE    ${val} < 3
        Fail   while-loop1-${val}
        Log    this is executed, but only once (for val==0)
        ${val}=    Evaluate   ${val} + 1
    END
```

<img width="588" alt="image" src="https://user-images.githubusercontent.com/22439451/171798122-215030bd-0537-4a50-9648-ee8b8e3292da.png">

**Comment by pekkaklarck** [comment]
It seems WHILE loops don't take continuable failures into account otherwise either. For example, if you use
```
Run Keyword And Continue On Failure    Fail   while-loop1-${val}
```
in the loop the execution stops after the first iteration as well.
