### ISSUE TITLE
Robotframework python

### ISSUE THREAD

**Issue by Spartan0027** [robotframework/robotframework#4356]
Import not found is showing when calling resource in setting with file path of keywords.robot file 

#code 

*** Setting *** 
Library         SeleniumLibrary
Resource          ../Resources/LoginKeywords.robot

**Comment by pekkaklarck** [comment]
You seem to have configuration issue with your IDE but with this information it's impossible to help. This tracker is for bug reports and enhancement requests so please ask, with more details, on some actual support forum such as Slack. You can find links to various forums at robotframework.org.

**Comment by Spartan0027** [comment]
> You seem to have configuration issue with your IDE but with this information it's impossible to help. This tracker is for bug reports and enhancement requests so please ask, with more details, on some actual support forum such as Slack. You can find links to various forums at robotframework.org.

I just added versions of the software I am using please tell me what more details are needed for getting a solution.
