### ISSUE TITLE
Parsing model: Creating `TRY` and `WHILE` statements using `from_params` is not possible

### ISSUE THREAD

**Issue by osrjv** [robotframework/robotframework#4357]
`Token` objects for control structures have a default value, since they are effectively static. This is handled [here](https://github.com/robotframework/robotframework/blob/master/src/robot/parsing/lexer/tokens.py#L154).

How this is handled is possibly a bit... questionable, but without commenting on the current implementation the `TRY/EXCEPT/FINALLY` tokens are missing defaults.

This is an issue made worse by the fact that the [factory method](https://github.com/robotframework/robotframework/blob/master/src/robot/parsing/model/statements.py#L926) does not supply an explicit value, and it can't be set by the caller.

**Comment by pekkaklarck** [comment]
We apparently forgot to add new automatic values when TRY/EXCEPT was added and didn't remember that with WHILE either. Should thus add defaults for TRY, EXCEPT, FINALLY and WHILE. ELSE is already covered.

Could you clarify the possibly questionable part?

**Comment by pekkaklarck** [comment]
Yeah, all token values don't match the value of the type constant (enum) value. Could first have a check for those values that match and then have a separate for those who don't, but having all in a single dictionary is simpler.

I started to add tests for `from_params` and noticed that `TryHeader.from_params` is totally broken. It has apparently been blindly copied from some other `from_parems` without creating tests. Kind of embarrassing and luckily something that haven't happened too often in our code base. I'll add tests and fix it now (or latest after lunch).

Also noticed that `Token.AS` needs a default value in addition to others listed earlier.

**Comment by osrjv** [comment]
Gonna use this to file some additional findings:

The `from_params` for `ExceptHeader` takes in patterns, but does not automatically create `ARGUMENT` tokens for them ([link](https://github.com/robotframework/robotframework/blob/master/src/robot/parsing/model/statements.py#L930)). You need to manually give in a list of tokens instead of values. This is different from other similar arguments.

The `Variable` token for suite variables is a bit broken (in my opinion) for values in general. It has a property `value` for getting its value, but for list/dict type values it will return a tuple. The matching `from_params` assumes it will only ever be a single scalar value, but that's not true for the aforementioned types.

Here's an example of a tokenized list variable:
```python
Variable(tokens=[
    Token(VARIABLE, '@{LIST}', 3, 0),
    Token(SEPARATOR, '           ', 3, 7),
    Token(ARGUMENT, '${1}', 3, 18),
    Token(SEPARATOR, '    ', 3, 22),
    Token(ARGUMENT, '${2}', 3, 26),
    Token(SEPARATOR, '    ', 3, 30),
    Token(ARGUMENT, '${3}', 3, 34),
    Token(EOL, '\n', 3, 38)]
)
```
Which is not compatible with [this method](https://github.com/robotframework/robotframework/blob/master/src/robot/parsing/model/statements.py#L523).

**Comment by pekkaklarck** [comment]
Yeah, `ExceptHeader.from_params` was broken in various ways. Hopefully you can test the fix that I'll commit shortly.

`Variable.from_params` seems to be broken as well. It should always accept a list of values because it needs to support also cases like this:
```
${VAR}    SEPARATOR=\n    first line    second line
```
Please submit a separate issue about that.
