### ISSUE TITLE
Provide possibility to add "auto-reload"-command into log.html on demand

### ISSUE THREAD

**Issue by KASTRobert** [robotframework/robotframework#4362]
When developing I would like to see the log.html is automatically reloaded. 
It would be nice to add a piece of javascript at the end telling any browser to periodically reload the log.html.
When doing the 'real' test run, the auto-reload should not be  int the log.html

**Comment by pekkaklarck** [comment]
This sounds more like a browser feature for me, and personally I'm fine pressing Ctrl-R, but if it would be opt-in I don't see problems adding such functionality. Do you have idea how to implement it? Interested to provide a PR?

**Comment by pekkaklarck** [comment]
No updates. Closing.
