### ISSUE TITLE
unable to pick --rerunfailed xml with version 5.0 and above

### ISSUE THREAD

**Issue by aliasgerkw** [robotframework/robotframework#4370]
Hello Team,

We are trying to upgrade to version 5.0.1 version from 4.1.3 and found an issue when we are using --rerunfailed tag after first execution with output.xml during jenkins execution:

$xvfb_cmd pabot --verbose --processes 7 --pabotlib ${VARIABLE_PARAMS} --output firstAttempt.xml tests/ || $xvfb_cmd pabot --verbose --processes 7 --pabotlib ${VARIABLE_PARAMS} --rerunfailed firstAttempt.xml --output secondAttempt.xml tests || true

Getting
12:48:36 Collecting failed tests or tasks from 'firstAttempt.xml' failed: Reading XML source 'firstAttempt.xml' failed: No such file or directory

where as its working fine in version 4.1.3. We tried on both version 5.0 and 5.0.1, 5.2 but facing same issue.

Logs:
**12:48:36 Output: /home/ubuntu/workspace/TestSuite/sdet/FE-Suite-Test/dashboard-testsuite-browser-library/pabot_results/46/firstAttempt.xml**
12:48:36 Invalid options 'skip', 'skiponfailure', 'variable', 'variablefile', 'listener' and 'prerunmodifier'.
12:48:36 Stopping PabotLib process
12:48:36 Robot Framework remote server at [127.0.0.1:8270](http://127.0.0.1:8270/) started.
12:48:36 Robot Framework remote server at [127.0.0.1:8270](http://127.0.0.1:8270/) stopped.
12:48:36 PabotLib process stopped
12:48:36 Total testing: 13 hours 29 minutes 4.40 seconds
12:48:36 Elapsed time: 2 hours 18 minutes 29.34 seconds
12:48:36 + xvfb-run '--server-args=-screen 0 1920x1080x24 -ac' pabot --verbose --processes 7 --pabotlib  --variable ${VARIABLE_PARAMS} HEADLESS_MODE:true --rerunfailed firstAttempt.xml --output secondAttempt.xml tests
**12:48:36 Collecting failed tests or tasks from 'firstAttempt.xml' failed: Reading XML source 'firstAttempt.xml' failed: No such file or directory**

**Comment by pekkaklarck** [comment]
Seems more like a problem with Pabot for me. Have you updated it when you updated Robot?

**Comment by aliasgerkw** [comment]
Pabot was 2.0.1, shall I update pabot to latest (2.5.3) and try?

**Comment by pekkaklarck** [comment]
Yeah, could be that older Pabot versions aren't compatible with RF 5.

**Comment by aliasgerkw** [comment]
Thanks @pekkaklarck 
working with latest version of pabot.
