### ISSUE TITLE
Loop breaks on IF evaluation failure

### ISSUE THREAD

**Issue by chaosseed** [robotframework/robotframework#4383]
robotframework==5.0.1

Test suite:

```robotframework
*** Test Cases ***
test
    FOR    ${x}    IN RANGE    5
        My Keyword
    END

*** Keywords ***
My Keyword
    ${var}    Set Variable
    IF    $var[0] == 1
        Pass Execution    PASS
    END
```

Got below error on execution and breaks loop at first iteration:

    FAIL : Evaluating IF condition failed: Evaluating expression '$var[0] == 1' failed: IndexError: string index out of range.

Is this behavior expected? If yes could someone please suggest a workaround?

**Comment by pekkaklarck** [comment]
This behavior is expected. Evaluating the expression fails and that fails the test. There is, however, a related real problem that this kind of failure exits `TRY/EXCEPT` structures as well. I'll submit a separate issue about that.
