### ISSUE TITLE
Change the parsing model object produced by `Test Tags` (and `Force Tags`) to `TestTags`

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#4385]
We are gong to rename `Force Tags` to `Test Tags` (#4365) and as the first step adding `Test Tags` as an alias for `Force Tags` in RF 5.1 (#4368). There were no other code changes and currently `Test Tags` (and `Force Tags`) is parsed into a `ForceTags` object. This should be changed to `TestTags` in RF 5.2.

The change doesn't affect test execution at all, but tools working with the parsing model are affected. Luckily it's pretty easy to handle both objects by having both `visit_ForceTags` and `visit_TestTags` in a model visitor.

**Comment by wangliyao518** [comment]
in robot v3.1.2 I want to change/add the Froce Tags value, which API I can use?  it seems I can use visit_test, but can't change the source code. 
    def visit_test(self, node):
        node.tags.add('CDT')
        print(node.tags)  # this print show already add
        return node     # have return and not have
but in latest robot v5.0.1, the below code can change the force tags
    def visit_ForceTags(self, node):
        self.model = get_model(self.case_full_path)
        for i in node.tokens:
            if i.value == self.old_name:
                i.value = self.new_name
        self.model.save()

**Comment by pekkaklarck** [comment]
Better to wait until a major version before making this backwards incompatible change.

**Comment by pekkaklarck** [comment]
I realized it's pretty easy to add backwards compatibility to our `ModelVisitor` so that old `visit_ForceTags` will continue to work. I'll commit that enhancement shortly.
