### ISSUE TITLE
Parsing of output xml failed from robot plugin

### ISSUE THREAD

**Issue by denerkr** [robotframework/robotframework#4386]
This issue is being caught in a build of test cases for a website that mainly uses "seleniumlibrary" along with some tests by CLI using "sshlibrary" at the end of the build which takes around 12h the report generation always fails after finishing all compilation that is very annoying as you can see the error message bellow. So please, could someone help on this issue?

Environment:
OS where Jenkins, python and plugins has been installed: Ubuntu Desktop 20.04
Jenkins 2.346.1

Robot Framework plugin 3.2.0
robotframework 4.1
robotframework-pythonlibcore 3.0.0
robotframework-requests 0.9.1
robotframework-seleniumlibrary 5.1.3
robotframework-sshlibrary 3.7.0

We saw an old bug that seems to be the same issue going back to this latest robot plugin version: https://issues.jenkins.io/browse/JENKINS-62359

The report generation is failing Always with bellow error messages:

16:03:31 Robot results publisher started...
16:03:31 -Parsing output xml:
16:04:44 Failed!
16:04:44 java.io.IOException: Parsing of output xml failed!
16:04:44 	at hudson.plugins.robot.RobotParser$RobotParserCallable.invoke(RobotParser.java:102)
16:04:44 	at hudson.plugins.robot.RobotParser$RobotParserCallable.invoke(RobotParser.java:52)
16:04:44 	at hudson.FilePath.act(FilePath.java:1200)
16:04:44 	at hudson.FilePath.act(FilePath.java:1183)
16:04:44 	at hudson.plugins.robot.RobotParser.parse(RobotParser.java:48)
16:04:44 	at hudson.plugins.robot.RobotPublisher.parse(RobotPublisher.java:245)
16:04:44 	at hudson.plugins.robot.RobotPublisher.perform(RobotPublisher.java:267)
16:04:44 	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
16:04:44 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:79)
16:04:44 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
16:04:44 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:816)
16:04:44 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:765)
16:04:44 	at hudson.model.Build$BuildExecution.post2(Build.java:179)
16:04:44 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:709)
16:04:44 	at hudson.model.Run.execute(Run.java:1922)
16:04:44 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:44)
16:04:44 	at hudson.model.ResourceController.execute(ResourceController.java:101)
16:04:44 	at hudson.model.Executor.run(Executor.java:442)
16:04:44 Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[9043286,41397]
16:04:44 Message: JAXP00010004: The accumulated size of entities is "50.000.001" that exceeded the "50.000.000" limit set by "FEATURE_SECURE_PROCESSING".
16:04:44 	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:652)
16:04:44 	at hudson.plugins.robot.RobotParser$RobotParserCallable.processArgs(RobotParser.java:519)
16:04:44 	at hudson.plugins.robot.RobotParser$RobotParserCallable.processKeyword(RobotParser.java:475)
16:04:44 	at hudson.plugins.robot.RobotParser$RobotParserCallable.processKeyword(RobotParser.java:482)
16:04:44 	at hudson.plugins.robot.RobotParser$RobotParserCallable.processKeyword(RobotParser.java:482)
16:04:44 	at hudson.plugins.robot.RobotParser$RobotParserCallable.processKeyword(RobotParser.java:482)
16:04:44 	at hudson.plugins.robot.RobotParser$RobotParserCallable.processKeyword(RobotParser.java:482)
16:04:44 	at hudson.plugins.robot.RobotParser$RobotParserCallable.processKeyword(RobotParser.java:482)
16:04:44 	at hudson.plugins.robot.RobotParser$RobotParserCallable.processKeyword(RobotParser.java:482)
16:04:44 	at hudson.plugins.robot.RobotParser$RobotParserCallable.processKeyword(RobotParser.java:482)
16:04:44 	at hudson.plugins.robot.RobotParser$RobotParserCallable.processTest(RobotParser.java:302)
16:04:44 	at hudson.plugins.robot.RobotParser$RobotParserCallable.processSuite(RobotParser.java:153)
16:04:44 	at hudson.plugins.robot.RobotParser$RobotParserCallable.processSuite(RobotParser.java:151)
16:04:44 	at hudson.plugins.robot.RobotParser$RobotParserCallable.processSuite(RobotParser.java:151)
16:04:44 	at hudson.plugins.robot.RobotParser$RobotParserCallable.processSuite(RobotParser.java:151)
16:04:44 	at hudson.plugins.robot.RobotParser$RobotParserCallable.processSuite(RobotParser.java:151)
16:04:44 	at hudson.plugins.robot.RobotParser$RobotParserCallable.parseResult(RobotParser.java:121)
16:04:44 	at hudson.plugins.robot.RobotParser$RobotParserCallable.invoke(RobotParser.java:97)
16:04:44 	... 17 more
16:04:44 Build step 'Publish Robot Framework test results' changed build result to FAILURE

**Comment by pekkaklarck** [comment]
My guess is that your output.xml size is so big that Java XML libraries don't handle it. The reason I believe so is this part of the error:
> 16:04:44 Message: JAXP00010004: The accumulated size of entities is "50.000.001" that exceeded the "50.000.000" limit set by "FEATURE_SECURE_PROCESSING".

I'm not sure could you possibly configure the system to accept such big files or is this something that should be changed in the plugin itself.

This issue tracker is for Robot Framework core, not for the Jenkins plugin, and I don't think there's anything that could be changed in RF itself to avoid this issue. You may want to submit an issue to the Jenkins plugin issue tracker. I'd recommend you to include a bit more information to such report such as the output.xml file size.

**Comment by denerkr** [comment]
Thanks for the help on that. I'll open a issue on Jenkins plugin issue tracker.
