### ISSUE TITLE
Add and document translations

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#4390]
RF ~5.1~ 6.0 starts localization efforts with these ~two~ three enhancements:

- #4096
- #519
-  #4400 

The issues above cover adding the support for translations. This issue exists for these purposes:
- Actually adding translations for various languages.
- Documenting what languages we support in the User Guide and elsewhere.
- Collecting information about who has provided translations so that we can acknowledge them in the release notes.

The translation efforts have been lead by @leeuwe who also set a [Crowdin page](https://robotframework.crowdin.com/robot-framework) for collaboration. We also have a dedicated `#localization` channel on our [Slack](http://slack.robotframework.org).

**Comment by pekkaklarck** [comment]
As mentioned above, we use [Crowdin](https://robotframework.crowdin.com/robot-framework) for collaboration and the #localization Slack channel for general discussion. You may also create your own language specific Slack channels for discussion if needed.

Translations at Crowdin are stored to YAML files in format `Language.yml`. This format isn't directly supported by Robot Framework, but you can convert them to suitable format using our [crowdin.py](https://gist.github.com/pekkaklarck/fd348b7eb59f35a26f2fdc1e7b0f008d) script. If you have a language file from Crowdin like `Czech.yml`, you can convert it with the script like this:

    python crowdin.py Czech.yml Czech.py

After that you can use the generated language file with Robot Framework like this:

    robot --language Czech.py example.robot

The generated class can also be added to Robot's [languages](https://github.com/robotframework/robotframework/blob/master/src/robot/conf/languages.py) module via a pull request to get it included as a built-in language.

**Comment by pekkaklarck** [comment]
PR #4377 added translations for these languages:
- PT by @HelioGuilherme66 
- BT-BR by @HelioGuilherme66 
- DE by @Snooz82 and @Noordsestern
- NL by @Heatzone87 and @leeuwe
- CS by @MoreFamed
- FR by @lesnake

Thanks all for contributions!

**Comment by HelioGuilherme66** [comment]
> **BT**-BR by @HelioGuilherme66
PT-BR

:)

**Comment by pekkaklarck** [comment]
Two new translations:

- Thai (TH) by @up1 
- Polish (PL) by @bhirsz

**Comment by pekkaklarck** [comment]
Two more translations:

- Spanish by Miguel Angel Apolayo Mendoza
- Simplified Chinese by @mawentao119 and @nixuewei

Thank you both! These and everything above will be included in RF 5.1 alpha 2.

**Comment by pekkaklarck** [comment]
Ukrainian (UK) :ukraine: by Yana Olefir @Sunshine0000000 added. It will be included in beta 1. Thanks for contribution!

**Comment by pekkaklarck** [comment]
We are planning some changes to the language definition syntax used a bit. Currently headers, settings and BDD prefixes are specified like this:
```python
class En(Language):
    setting_headers = {'Settings', 'Setting'}
    variable_headers = {'Variables', 'Variable'}
    ...
    library = 'Library'
    resource = 'Resource'
    ...
    bdd_prefixes = {'Given', 'When', 'Then', 'And', 'But'}
```

The plan is to change it to this:
```python
class En(Language):
    settings_header = 'Settings'
    setting_header = 'Setting'
    variables_header = 'Variables'
    variable_header = 'Variable'
    ...
    library_setting = 'Library'
    resource_setting = 'Resource'
    ...
    given_prefix = {'Given'}
    when_prefix = {'When'}
    ...
```

**Comment by MoreFamed** [comment]
@pekkaklarck , I'd like to make an objection to your second point regarding limiting headers to singular and plural only. There are several languages where dual number of nouns is mandatory. From European languages, it is e.g. Slovenian; but it is mandatory also in Arabic with about half a billion of native speakers. By "mandatory" I mean that the speakers are obliged to use the form of a noun other than singular or plural when they are refering to exactly two things (test cases, variables etc.). I am afraid it can be confusing for them if they will be forced to use either singular, or plural form for exactly two variables. The situation in settings is different: one can state exactly one thing after the 'Library' or 'Resource' statement, so one possible form (denoting singular) only is perfect here.

If we allow people to use their own language which is written in their own script, why not to allow them to use their own grammatical rules?

Or, from a totally different point of view: if there really are some problems with unlimited number of grammatical numbers, limit them to only one. The rationale is: you can write unlimited and indefinite count of variables/settings/... into a header; thus the only allowed form of header name would denote 'many', 'indefinitely' things. This corresponds to plural in English (and in Slovenian and Arabic as well, AFAIK). 

That exactly-two-grammatical-numbers approach seems rather 'language-centric' to me... :(

**Comment by pekkaklarck** [comment]
If I was to decide what headers to accept now, I'd go with the plural formats only. There's no real benefit in supporting `Test Case` in addition to `Test Cases`.

The main reason we have supported the singular form is that originally Robot's data was in HTML tables and they typically had headers like this:

| Test Case | Keyword | Argument | Argument |
| -- | ------- | ------- | ------- |
| Example | Log | Message | INFO |

We have preserved singular forms for backwards compatibility reasons. Removing them would require long deprecation period and I'm honestly not sure would it be worth it. That said, we could easily make a decision that we only allow exactly one header with translations. English being more "special" would be a bit

**Comment by MoreFamed** [comment]
I like your idea: translation of header parts can have just one form (plural), except for English which can have singular forms as well as a legacy (for now). I am not afraid of deprecating and removing English singulars much: I guess singulars are used much less then plurals (would not a short survey in the community help?), Robotidy can do a good job and RF and its users yet survived several limitations of its original almost boundless freedom in writing things (I guess `*** Settings ***` was allowed to be written as `* S_E t_t_i_N G s *` years ago) :)

**Comment by pekkaklarck** [comment]
Yeah, limiting header translations to just one form sounds like a good idea. What we do with English can be then be decided separately, but having a long term plan to support only the plural form sounds fine. At this point we could just announce that plan and start emitting actual deprecation warnings only in RF 7 or later. Do you @leeuwe have any comments related to this? What about @yanne?

**Comment by leeuwe** [comment]
Reading the thread I've been educated by @MoreFamed and since you both reached an agreement, I have no further comments

**Comment by pekkaklarck** [comment]
Ok, let's allow translating only the plural headers and deprecate singular headers in general. The former is covered by this issue and will be done by @yanne when he updates the class attributes of the `Language` class otherwise. The latter is covered by #4431 that I just submitted.

**Comment by pekkaklarck** [comment]
Russian translation by @axxyhtrx added. It will be part of beta 1. Thanks for contribution!

**Comment by pekkaklarck** [comment]
PR #4450 adds Bosnian provided by @Delilovic. It will be merged still before the beta that ought to be released today. Thanks for contribution!

**Comment by pekkaklarck** [comment]
Turkish added by PR #4463. It will be included in beta 2. Thanks for a contribution @yusufcanb!

**Comment by pekkaklarck** [comment]
French TRUE/FALSE words added in PR #4487 by @mmalorni. Will be included in rc 1.

**Comment by pekkaklarck** [comment]
PR #4499 brought us following translations:

- Swedish by @JockeJarre 
- Bulgarian by @naschenez
- Romanian by @zastress

Thanks you all for contributions! These will be included in RF 6.0 due to it being delayed a bit and we anyway needing another release candidate.

**Comment by pekkaklarck** [comment]
Italian was added in PR #4502 by @lugi0 and will be included in rc 2. Thanks for contribution!

**Comment by pekkaklarck** [comment]
PR #4506 added Hind and it still makes it to RF 6.0. Thanks for contribution @bharat.2001!
