### ISSUE TITLE
Collections: `Get From Dictionary` should accept a default value

### ISSUE THREAD

**Issue by Eli-Black-Work** [robotframework/robotframework#4398]
[Pop From Dictionary](https://robotframework.org/robotframework/latest/libraries/Collections.html#Pop%20From%20Dictionary) has support for returning a default value if the key isn't found in the dictionary. e.g.
```robot
Pop From Dictionary  ${myDict}  myKey  myDefaultValue
````

I think it'd be great if `Get From Dictionary` also support having a default value passed to it. 🙂

e.g.
```robot
Get From Dictionary  ${myDict}  myKey  myDefaultValue
```

**Comment by pekkaklarck** [comment]
This is certainly true. Adding the default value would also be pretty easy. Anyone interested to provide a pull request?

**Comment by Bosch-Eli-Black** [comment]
Wow, that was quick! 🙂  Thank you guys! ^_^

**Comment by pekkaklarck** [comment]
I didn't expect this to make it to RF 5.1 alpha 1 but @oboehmer was very quick with a PR. :smile:

**Comment by Bosch-Eli-Black** [comment]
Indeed! 😀
