### ISSUE TITLE
Allow passing flags to regexp related keywords using explicit `flags` argument

### ISSUE THREAD

**Issue by oboehmer** [robotframework/robotframework#4429]
The use of regex flags as part of the expression (i.e. `(?i)fooBAR` to do a case-insensitive lookup) is an advanced regex feature not obvious to all users. It would be convenient to also pass optional arguments to `Get Regexp Matches` and other regexp keywords, i.e.

```
${result}=   Get Regexp Matches     FOObar  foo    flags=I
${result}=   Get Regexp Matches     FOO\n123\nbar  foo.*bar    flags=DOTALL|I
```

**Comment by pekkaklarck** [comment]
Implemented by @oboehmer in PR #4430. Thanks for another great contribution!
