### ISSUE TITLE
Convert and validate collection contents when using generics in type hints

### ISSUE THREAD

**Issue by JFoederer** [robotframework/robotframework#4433]
The [supported conversions](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#toc-entry-525) section of the documentation states:

> Also types in in the typing module that map to the supported concrete types or ABCs (e.g. List) are supported. With generics also the subscription syntax (e.g. List[int]) works, **but no validation is done for container contents**.

It seems like a good enhancement to include these conversions as well, but the current code actually also contains a defect in this area. The `converter_for` method of `TypeConverter` strips the `__origin__` information for all types but `Union`. As a result it is not possible to write any custom converters for generic types. Asuming you would typically need the nested types to do the proper conversions.

![image](https://user-images.githubusercontent.com/32476108/184913083-e18d2303-de46-4f99-b5d2-42c119ec27b7.png)

A pull request will follow to clarify the issue and demonstrate the suggested enhancement.

**Comment by pekkaklarck** [comment]
Interesting! I don't have time to look at this now, but I add this to RF 5.1 scope to not forget about it. Would be a nice enhancement to get into that release.

**Comment by JFoederer** [comment]
That would be great! I will try a Linux system with python 3.6 as well, to see what the unit test failures are about over there. I also gained some better insights in the LibDoc failures. A proposal will follow.

**Comment by pekkaklarck** [comment]
I've been busy with non-work stuff lately (mostly studying interpreters and compilers so it's been highly related) and haven't had time to look at this yet. I try to get beta out today but will look at this afterwords. This is in v5.1 milestone and won't be forgotten.

**Comment by JFoederer** [comment]
No problem, thanks for the update. I'll just consider it a compliment that you don't see it as a risk to integrate it that late in the process ;-) Although I also hope the tests I added are clear enough to show the exact impact.

The current status is that the Libdoc issues are solved without regression or changes. The Python 3.6 unit tests are fixed, but the 3.6 acceptance tests aren't. I haven't tried 3.7, but was able to run successful from Python 3.8 upward on Windows and Linux. The offer to disable the tests for Python 3.6 starts to look tempting. The issue originates from somewhere in the surrounding code, where the None-converter gets in the way. I lacked the time to deep dive into this part.

**Comment by pekkaklarck** [comment]
This has been now implemented based on the excellent PR #4434 by @JFoederer. Thanks a lot for your hard work!

**Comment by pekkaklarck** [comment]
That line is there, but converters nowadays get the used type, not the origin, as an argument. Possible origin is only used for finding the right converter. If you have examples where the current design causes problems, let me know!

**Comment by pekkaklarck** [comment]
In RF 6.0 Libdoc doesn't handle parameterized types too well, but that is fixed in RF 6.1 (#4538)

**Comment by pekkaklarck** [comment]
This functionality unfortunately has a bug that when the used argument is an object, not a string, items are not converted (#4705). It will be fixed in RF 6.1.
