### ISSUE TITLE
Allow using `None` as custom argument converter to enable strict type validation

### ISSUE THREAD

**Issue by mikkuja** [robotframework/robotframework#4440]
I would like to use python type hints to validate that keywords arguments are of correct type.

Related to #3690

## Background
When using type hints on library keywords, Robot Framework already ensures that most of the arguments are of defined type. For example:

```python
def my_keyword(time: timedelta) -> float:
    return time.total_seconds()
```

will fail cleanly during runtime if user tries to pass something incompatible like a list:

```
ValueError: Argument 'time' got value '[1]' (list) that cannot be converted to timedelta.
```
instead of
```
AttributeError: 'list' object has no attribute 'total_seconds'
```

However, this validation only exists for [supported types](https://robotframework.org/robotframework/5.0/RobotFrameworkUserGuide.html#supported-conversions) and types that has user defined [custom converters](https://robotframework.org/robotframework/5.0/RobotFrameworkUserGuide.html#custom-argument-converters).

## Proposal

As discussed in issue #3690 backwards compatibility limits us for enabling type guarding on default. One option would be adding a library level toggle but having too many options in `@library` is not desirable either.

Other option would be adding a special [custom converter](https://robotframework.org/robotframework/5.0/RobotFrameworkUserGuide.html#custom-argument-converters) that only validates that argument [is instance](https://docs.python.org/3/library/functions.html#isinstance) of the type. For example like this:

```python
ROBOT_LIBRARY_CONVERTERS = {
    CustomType1: None,
    CustomType2: None
}
```

where `None` would be a shortcut for this pattern:

```python
def _typechecked(_):
    raise ValueError()

ROBOT_LIBRARY_CONVERTERS = {
    CustomType1: _typechecked,
    CustomType2: _typechecked
}
```

For more implementation details see this [comment](https://github.com/robotframework/robotframework/issues/3690#issuecomment-1220547740).

**Comment by pekkaklarck** [comment]
Adding support for `None` as a special "strict converter" is easy and has no backwards compatibility concerns. Let's add it already in RF 5.1. If this isn't convenient enough, we can consider adding a toggle to `@library` to make this a default behavior in future versions.

**Comment by pekkaklarck** [comment]
Done in above commit.

**Comment by mikkuja** [comment]
Thank you @pekkaklarck. That was extremely fast and the solution looks excellent. There was one small typo in the documentation which I commented to the commit.
