### ISSUE TITLE
robotframework 5.0.1 fails when --include option is blank

### ISSUE THREAD

**Issue by zmoose** [robotframework/robotframework#4441]
I updated my python3 robotframework package from 5.0 to 5.0.1 and now the robot command fails when the "--include=" parameter is blank.  Its always worked fine before.  

`robot -v OPENBMC_HOST:myhost --include= templates/test_openbmc_setup.robot
[ ERROR ] Suite 'Test Openbmc Setup' contains no tests matching tag ''.

Try --help for usage information.`

**Comment by pekkaklarck** [comment]
I was able to reproduce the problem and according to `git bisect` the issue was introduced in commit 8b6d54cabb04340aa4843688f9d9339a6f3887f8 that fixed #3862. I'll study this a bit more later and hopefully can fix it for RF 5.1.
