### ISSUE TITLE
Robot cannot find chrome driver in PATH

### ISSUE THREAD

**Issue by openSourceBugs** [robotframework/robotframework#4442]
Seems like Robot is completely broken for me.  I have used webdrivermanager (the command line tool) to download the latest webdriver for chrome on windows.  I have added this executable's parent bin folder to the path.  I have restarted the terminals that run the robot command.  I have googled forever on this issue.  This feels like a super blocking P0 bug.  Feels like Robot Framework is willfully ignoring the path/driver.  

![image](https://user-images.githubusercontent.com/5646010/185860024-68f2b836-ee40-4f41-a1c8-c5948927373a.png)

![image](https://user-images.githubusercontent.com/5646010/185860142-28a6ca59-2f90-418e-b7da-0a8af9c4c192.png)

![image](https://user-images.githubusercontent.com/5646010/185859733-657e5127-4cde-4be0-882e-f6f8457ea2fb.png)

![image](https://user-images.githubusercontent.com/5646010/185859879-cb210b07-fc0e-4b8b-bc32-4de5a539ce1c.png)

(RobotSelenium) C:\Users\Alex\PycharmProjects\RobotSelenium>robot firstRobot.robot
==============================================================================
firstRobot :: My First Test This test will Verify Google
==============================================================================
Open Google & Verify Google
DevTools listening on ws://127.0.0.1:60982/devtools/browser/102de287-77a8-4cf1-a65c-444076a55a18
Open Google & Verify Google                                           | FAIL |
SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 91
Current browser version is 104.0.5112.101 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Stacktrace:
Backtrace:
        Ordinal0 [0x005E3733+2504499]
        Ordinal0 [0x0057C401+2081793]
        Ordinal0 [0x00482628+1058344]
        Ordinal0 [0x004A071A+1181466]
        Ordinal0 [0x0049C58C+1164684]
        Ordinal0 [0x00499DC3+1154499]
        Ordinal0 [0x004C9B82+1350530]
        Ordinal0 [0x004C97DA+1349594]
        Ordinal0 [0x004C5D4B+1334603]
        Ordinal0 [0x004A22B4+1188532]
        Ordinal0 [0x004A3149+1192265]
        GetHandleVerifier [0x0075FB8C+1512252]
        GetHandleVerifier [0x0080B0DF+2214031]
        GetHandleVerifier [0x00664BC3+484211]
        GetHandleVerifier [0x00663E69+480793]
        Ordinal0 [0x0058218D+2105741]
        Ordinal0 [0x005866E8+2123496]
        Ordinal0 [0x00586827+2123815]
        Ordinal0 [0x0058FB73+2161523]
        BaseThreadInitThunk [0x7673FA29+25]
        RtlGetAppContainerNamedObjectPath [0x771A7A9E+286]
        RtlGetAppContainerNamedObjectPath [0x771A7A6E+238]
------------------------------------------------------------------------------
firstRobot :: My First Test This test will Verify Google              | FAIL |
1 test, 0 passed, 1 failed
==============================================================================
Output:  C:\Users\Alex\PycharmProjects\RobotSelenium\output.xml
Log:     C:\Users\Alex\PycharmProjects\RobotSelenium\log.html
Report:  C:\Users\Alex\PycharmProjects\RobotSelenium\report.html

**Comment by pekkaklarck** [comment]
Robot does absolutely nothing to PATH. You most likely have multiple drivers around and a wrong one is in PATH first.
