### ISSUE TITLE
visit_keyword function is never called

### ISSUE THREAD

**Issue by eldaduzman** [robotframework/robotframework#4443]
When I run the following python code:
```
from robot.api import TestSuiteBuilder
from robot.running.model import TestSuite
from robot.running.suiterunner import SuiteRunner
from robot.running.namespace import IMPORTER
from robot.conf.settings import RobotSettings
from robot.output import Output, LOGGER


class MyVisitor(SuiteRunner):
    def visit_suite(self, suite):
        print("visiting suite...")
        return super().visit_suite(suite)

    def visit_test(self, test):
        print("visiting test case")
        return super().visit_test(test)

    def visit_keyword(self, kw):
        print("visiting keyword...")
        return super().visit_keyword(kw)


def main():
    path = r"tests/simple-test.robot"
    suite: TestSuite = TestSuiteBuilder().build(path)

    settings = RobotSettings()  # {"quiet": True}
    with LOGGER:
        LOGGER.register_console_logger(**settings.console_output_config)
        IMPORTER.reset()
        output = Output(settings)
        runner = MyVisitor(output=output, settings=settings)
        suite.visit(visitor=runner)


if __name__ == "__main__":
    main()
```

and "tests/simple-test.robot" contains:
```

*** Test Cases ***
Test 1
    KW 1
    Sleep    200ms


*** Keywords ***
KW 1
    Log To Console    do nothing
```

The expectation was that with every keyword being called, the overridden method `visit_keyword` will be invoked and print out "visiting keyword..." before running the keyword.

The actual outcome was as follow:

```
visiting suite...
==============================================================================
Simple-Test
==============================================================================
visiting test case
Test 1                                                                do nothing
Test 1                                                                | PASS |
------------------------------------------------------------------------------
Simple-Test                                                           | PASS |
1 test, 1 passed, 0 failed
==============================================================================
```
It invoked the overrides for 'visit suite' and 'visit_test' but the 'visit_keyword' was ignored.

A deeper dive into the code, I saw that the parent visitor, SuiteRunner, instantiates a BodyRunner objects, which instatiates a KeywordRunner object for each of the kewords, and therefore it loses reference to the original SuiteRunner and the visit method is never called.

Details:

robotframework - 5.0.1
python - 3.10.2
OS - Windows 10 Pro

**Comment by pekkaklarck** [comment]
`SuiteRunner` implements `visit_test` which, by design, prevents visiting keywords. This class is nor part of the public API and I see no reason to change it. The whole execution logic will probably be rewritten at some point, and the changes to this class or more than likely then.

If there's something you try to do but the current design doesn't facilitate, please explain that a bit more thoroughly. Starting a thread on the #devel channel on our Slack might be a better way to discuss than using this tracker, though.

**Comment by eldaduzman** [comment]
Thanks @pekkaklarck I'll move on to slack.
