### ISSUE TITLE
robotframework 5.0.1 produces nested testsuite tags in xunit output file

### ISSUE THREAD

**Issue by pkomarov** [robotframework/robotframework#4444]
Greetings,

After moving to robotframework 5.0.1 recently I've faced the issue with uploading a robot xunit result file to Smartbear Zephyr Scale. It was unable to find my test cases. I've opened a ticket for them and after an investigation they replied that there is a nested testsuite tags in a xml file produced by robot. Looks like JUNIT XML format doesn't support nested tests suites like robot. They stated that according to this [specification](https://www.ibm.com/docs/en/developer-for-zos/9.1.1?topic=formats-junit-xml-format) testsuite tag could not have child testsuite tags, but only testcase. Looks like robot 4.1 did not produce such nested tags and uploading results was working fine.

Could you please look into that? Will that be fixed or I should fix a file by myself before uploading to Zephyr Scale API?

Results file attached:
[robot-results_fixed.xml.txt](https://github.com/robotframework/robotframework/files/9400075/robot-results_fixed.xml.txt)
 
Best Regards, Pavel.

**Comment by pkomarov** [comment]
Ok, I got your point. It's totatlly fine for me to customize output to the format Zephyr wants to have. Just ask for a developer opinion.

**Comment by rikerfi** [comment]
Hi Pavel, Pekka.

I think we should study the xunit configuration as it seems there are many dialects of xunit around.

@pkomarov: Please, check this modifier I have made if it is suitable for your purposes: https://github.com/rikerfi/robotframework-xunitmodifier
And flat implementation reference is here: https://github.com/rikerfi/robotframework/blob/v4.1.2/src/robot/reporting/xunitwriter.py

**Comment by pkomarov** [comment]
Hi,

@rikerfi thank you for your suggsetion. I was able to produce a file, Zephyr required with your modifier. This ticket could be closed.

Best regards, Pavel.

**Comment by csantune** [comment]
Just for information, same problem with Allure, it doesn't accept nested testsuites

**Comment by sanatzzz** [comment]
> Hi Pavel, Pekka.
> 
> I think we should study the xunit configuration as it seems there are many dialects of xunit around.
> 
> Meanwhile, @pkomarov: Please, check this modifier I have made if it is suitable for your purposes: https://github.com/rikerfi/robotframework-xunitmodifier And flat implementation reference is here: https://github.com/rikerfi/robotframework/blob/v4.1.2/src/robot/reporting/xunitwriter.py
> 
> Best, Risto



> Hi Pavel, Pekka.
> 
> I think we should study the xunit configuration as it seems there are many dialects of xunit around.
> 
> Meanwhile, @pkomarov: Please, check this modifier I have made if it is suitable for your purposes: https://github.com/rikerfi/robotframework-xunitmodifier And flat implementation reference is here: https://github.com/rikerfi/robotframework/blob/v4.1.2/src/robot/reporting/xunitwriter.py
> 
> Best, Risto

@rikerfi  If I use the flat xunitwriter.py  from the 4.1.2 version with rebot command in robot fraemwork 6, will it generate the flat xml file that was generated in 4.1 version and thereby not have the nested tags? Apologies if the question sounds dumb as I am new to this.
