### ISSUE TITLE
Evaluating expressions that modify evaluation namespace (locals) fail

### ISSUE THREAD

**Issue by apteryks** [robotframework/robotframework#4447]
Hi,

I stumbled on the following failure `TypeError: 'EvaluationNamespace' object does not support item assignment` when attempting either of:

```
Evaluate    pdb.Pdb(stdout=sys.__stdout__).set_trace()    modules=sys, pdb
```

```
Evaluate    breakpoint() 
```

in a RobotFramework .robot file.

This was discussed here: https://robotframework.slack.com/archives/C07PJBN64/p1661906204160279?thread_ts=1661870574.100769&cid=C07PJBN64, and is apparently a regression; quoting Pekka's answer:

> This is a bug and actually a regression. We changed EvaluationNamespace from MutableMapping to Mapping in RF 5.0 when removing Python 2 compatibility code. Evaluating list comprehensions required the namespace to be mutable with Python 2 but not anymore with Python 3. It didn't occur to us that there could be other cases where mutability would be needed.

**Comment by pekkaklarck** [comment]
It requires exact same interaction by default. Which is problematic in an automated test we want to run unattended. Turned out just `locals().__setitem__('name', 'value')` demonstrates the same issue so creating a test isn't too hard.
