### ISSUE TITLE
How do I save my screenshot in GitHub folder path from robot framework?

### ISSUE THREAD

**Issue by IshanChakraborty96** [robotframework/robotframework#4449]
I am using Robot Framework and GitHub workflow and want to save images/screenshots from the workflow. what kind of path I really need to give ?

I used 

```
Capture Page Screenshot
Set Screenshot Directory
```

**Comment by pekkaklarck** [comment]
I don't know.

This issue tracker is for bug reports and enhancement requests. Questions should be asked on our Slack or other such forums found via robotframework.org.
