### ISSUE TITLE
'While' is a reserved keyword.

### ISSUE THREAD

**Issue by bishopds** [robotframework/robotframework#4451]
version: robotframework 5.0.1

example
    WHILE    ${day}   IN   monday    tuesday    wednesday    thursday    friday    saturday    sunday
        Log to console  ${day}
    END
    
    
![image](https://user-images.githubusercontent.com/31470350/188401324-66e6faeb-572c-4108-a525-ad832ec731ba.png)

**Comment by pekkaklarck** [comment]
The syntax you use is wrong. WHILE only accepts a condition, for looping items you should use FOR.

I don't think you are using RF 5.0.1. With it this should fail with the following error:
> WHILE cannot have more than one condition.

**Comment by aliGu85** [comment]
I use Robot Framework 5.0.1 (Python 3.11.2 on win32), but i steel have the issue 'While' is a reserved keyword.
