### ISSUE TITLE
Standard libraries don't support `pathlib.Path` objects

### ISSUE THREAD

**Issue by aaltat** [robotframework/robotframework#4455]
OperatingSystem library should support also Python Path objects. Currently OperatingSystem library keyword which uses path or file path as argument, expect the argument to be as a string. Would it be possible to enhance library keyword to support also Python [Path](https://docs.python.org/3/library/pathlib.html) as arguments. 

This could be useful when library keywords returns a path object and that object is example used in [Get File](https://robotframework.org/robotframework/latest/libraries/OperatingSystem.html#Get%20File). Currently users are required to do: 
```robot framework
${path}    Library Keyword Return Path Object
${path}    Convert To String    ${path}
${data}    Get File    ${path}
```
But it could be handy to just do
```robot framework
${path}    Library Keyword Return Path Object
${data}    Get File    ${path}
```

**Comment by pekkaklarck** [comment]
All our libraries (and APIs) certainly should accept `Path` objects as paths. Which keywords have you had problems with?

A related question is that should keywords also return `Path` objects. For backwards compatibility reasons that's probably not a good idea in general, but if a keyword gets `Path` as an argument it could also return one.

**Comment by pekkaklarck** [comment]
OperatingSystem now supports `pathlib.Path`. Need to check are there other libs, especially XML and Process, that need this support as well.

**Comment by pekkaklarck** [comment]
Somewhat related, we probably should add type conversion support for `pathlib.Path`.

**Comment by pekkaklarck** [comment]
Added `pathlib.Path` support to Process and XML. With the former it was possible to give `stdout` and `stderr` as `pathlib.Path` but not `stdin` or `cwd`. WIth the later parsing worked but saving didn't. Still need to check do other libs use paths.

**Comment by pekkaklarck** [comment]
Also Screenshot used paths and that's now fixed as well. That ought to be all.
