### ISSUE TITLE
`Wait Until Keyword Succeeds` with `robot:recursive-continue-on-failure` --> errors catched

### ISSUE THREAD

**Issue by ThomasGitProjects** [robotframework/robotframework#4456]
Hi, when `Set Tags    robot:recursive-continue-on-failure` is set/executed before `Wait Until Keyword Succeeds`, the failing keyword in `Wait Until Keyword Succeeds` result in a failing testcase, even if the keyword succeeds before "timeout conditions" of `Wait Until Keyword Succeeds` are fulfilled.
My expectation would be, that the `fails` within `Wait Until Keyword Succeeds` are not catched.

Currently I'm using version 4.1.3, because currently I cannot update to newest version.

If this "issue" is already solved in version 5.x, feel free to cancel the issue.

**Comment by pekkaklarck** [comment]
I tried to reproduce this with the following example that ought to match your description but it worked just fine.

```robotframework
*** Variables ***
${RERUN}    True

*** Test Cases ***
Example
   [Tags]    robot:recursive-continue-on-failure
   Wait until keyword succeeds   1min    1ms    Keyword

*** Keywords ***
Keyword
    IF    ${RERUN}
        Set Suite Variable    ${RERUN}    False
        Fail    Should be re-run.
    END
```

Could you create a simple example demonstrating the problem that I could run locally? Having such an example in bug reports is generally a good idea for the reasons explained at http://sscce.org/.

**Comment by pekkaklarck** [comment]
Any updates?

**Comment by ThomasGitProjects** [comment]
Hi Pekka, I'm affraid, I cannot reproduce the error, not even with my environment. However I will keep track of the issue on my side.
I'm closing this issue now if that's ok for you and would create a new one, if it appears again and really seems to be a RFW issue

**Comment by pekkaklarck** [comment]
You can also reopen this one if you have more info.
