### ISSUE TITLE
Implement Assertion keywords

### ISSUE THREAD

**Issue by agusjaimez** [robotframework/robotframework#4460]
I believe it would be worth adding a set of Assertion keywords that could be used in the Test Cases section in order to perform validations there with human-readable language and avoid editing python code. This keywords should require the necessary arguments and a custom error message(optional).
The assertions can be:

- Hard Assertions: should raise an exception and stop the execution.
- Soft Assertions: should not raise exceptions nor stop the execution, all the exceptions should be raised at the end.

Some useful examples:

- Assert Equals: validates that two values are equal to each other
- Assert True: validates that a value is true, this can be used with a keyword referencing a function that returns a boolean value
- Assert False: validates that a value is true, this can be used with a keyword referencing a function that returns a boolean value

If you like the idea I can work on this.

**Comment by pekkaklarck** [comment]
We already have several keywords for this kind of validation in the BuiltIn library and other standard libraries. Check out keywords with `Should` in their name like `Should Be Equal`. Is there something special you are missing?

All asserts in our standard libraries are stop test execution by default. It is, however, possible to enable the continue-on-failure mode to let execution continue regardless of failures. It would be possible to create keywords that use continuable failures (a.k.a. soft failures), but I don't think it would be a good idea to have two sets of asserts.

**Comment by pekkaklarck** [comment]
No updates. Closing.
