### ISSUE TITLE
Execution hang after reports being generated and doesn't exit until aborted

### ISSUE THREAD

**Issue by YevgenyFarber** [robotframework/robotframework#4466]
Sometimes execution hangs after reports being generated and doesn't exit until aborted
robotframework version - 5.0.1
python 3.10.7

`14:07:45 ------------------------------------------------------------------------------
14:07:45 RobotFrameworkSVG.TestCases.HO.HO :: IODT HO                          | PASS |
14:07:45 1 test, 1 passed, 0 failed
14:07:45 ==============================================================================
14:07:45 RobotFrameworkSVG.TestCases.HO                                        | PASS |
14:07:45 1 test, 1 passed, 0 failed
14:07:45 ==============================================================================
14:07:45 RobotFrameworkSVG.TestCases                                           | PASS |
14:07:45 1 test, 1 passed, 0 failed
14:07:45 ==============================================================================
14:07:45 RobotFrameworkSVG                                                     | PASS |
14:07:45 1 test, 1 passed, 0 failed
14:07:45 ==============================================================================
14:07:45 Debug:   C:\jenkins\workspace\RobotFrameworkSVG\debugfile.txt
14:07:45 Output:  \\192.168.127.231\AutomationResults\old_runs\ASIL-SATURN\7122\results\results_SIR-44201\output.xml
14:07:51 Log:     \\192.168.127.231\AutomationResults\old_runs\ASIL-SATURN\7122\results\results_SIR-44201\log.html
**14:07:51** Report:  \\192.168.127.231\AutomationResults\old_runs\ASIL-SATURN\7122\results\results_SIR-44201\report.html
**15:27:17** Build was aborted`

**End of debugfile**:
`20220919 14:07:45.097 - INFO - +-------- END KEYWORD: RobotFrameworkSVGInfra.ElasticSearchPackage.ElasticSearchReporter.Create Execution (171)
20220919 14:07:45.097 - INFO - +------- END TRY:  (172)
20220919 14:07:45.097 - INFO - +------- START EXCEPT:  [ ]
20220919 14:07:45.098 - INFO - +-------- START KEYWORD: RobotLogs.Infra Log [ Create Execution failed ]
20220919 14:07:45.098 - INFO - +-------- END KEYWORD: RobotLogs.Infra Log (0)
20220919 14:07:45.098 - INFO - +------- END EXCEPT:  (1)
20220919 14:07:45.098 - INFO - +------ END TRY/EXCEPT ROOT:  (173)
20220919 14:07:45.099 - INFO - +------ START KEYWORD: RobotFrameworkSVGInfra.ResetAllObjects.ObjectsKiller.Kill Objects [ ]
20220919 14:07:45.099 - INFO - +------ END KEYWORD: RobotFrameworkSVGInfra.ResetAllObjects.ObjectsKiller.Kill Objects (0)
20220919 14:07:45.099 - INFO - +----- END TEARDOWN: TestTearDown.Create Test Results Execution (447760)
------------------------------------------------------------------------------
20220919 14:07:45.100 - INFO - +---- END TEST: Handovers SVGA-21135: SIR-44201 - Xn Inter Frequency Handover by Iperf 1 UEs - 15 Min (4118498)
------------------------------------------------------------------------------
20220919 14:07:45.102 - INFO - +--- END SUITE: RobotFrameworkSVG.TestCases.HO.HO (4125012)
==============================================================================
20220919 14:07:45.104 - INFO - +-- END SUITE: RobotFrameworkSVG.TestCases.HO (4125018)
==============================================================================
20220919 14:07:45.105 - INFO - +- END SUITE: RobotFrameworkSVG.TestCases (4125021)
==============================================================================
20220919 14:07:45.106 - INFO - + END SUITE: RobotFrameworkSVG (4125062)
==============================================================================`

We running robot with:
p = subprocess.Popen(command, shell=True)
p.wait(timeout)

**Comment by pekkaklarck** [comment]
Is output.xml really big?

**Comment by YevgenyFarber** [comment]
Not at all, the log.html was already in folder, the xml was something like 7M, later will provide the exact size

**Comment by pekkaklarck** [comment]
If log file is created, this sounds more like an issue with how you use subprocess. Could be that steams get full, aren't closed properly, or something like that. I would try running the process directly, not via shell. Unless you run processes in parallel, you could simply use `robot.run` or `robot.run_cli` instead as well.

**Comment by pekkaklarck** [comment]
I cannot debug this myself at all so you either need to do that yourself or provide me a simple example I can run locally.

**Comment by YevgenyFarber** [comment]
Thank you for your reply, what is preferred, run or run_cli?

**Comment by pekkaklarck** [comment]
Depends on your API needs. `run` is more Pythonic (`run('tests.robot', log='example.hmlt', dryrun=True)` but `run_cli` makes it easier to convert scripts currently using the `robot` command (`run_cli(['--log', 'example.html', '--dryrun', 'tests.robot'])`.

**Comment by pekkaklarck** [comment]
No updates. Closing.
