### ISSUE TITLE
Enhance `Keyword Should Exist` performance by not looking for possible recommendations

### ISSUE THREAD

**Issue by JFoederer** [robotframework/robotframework#4470]
In one project I am working on, they ran into an issue where checks were failing because Robot framework was taking up too much time. Analysis showed that the time was taken by calls to the Built in keyword `Keyword should exist`. In that particular situation it could take more than a second for a single call to `Keyword should exist` to return, with an average of 400ms. Anything above 500ms was causing failures.

Further analysis revealed the time to be spend on finding keyword recommendations. Finding these recommendations is a very useful feature when you misspell a keyword during test case development. However, when explicitly checking for a keyword's existence at runtime, the boolean answer suffices. In fact, in the current implementation the recommendations are disposed and not included in the reported failure.

A proposed solution is available in [PR#4457](https://github.com/robotframework/robotframework/pull/4457).

**Comment by pekkaklarck** [comment]
Makes sense. I wasn't sure should we consider this a bug or enhancement but went with the latter. Either way, this will be included in RF 5.1 and hopefully already in beta 2.

**Comment by pekkaklarck** [comment]
This was fixed in PR #4457 by @JFoederer .
