### ISSUE TITLE
Robot debugger is not stopped at "IF" and "ELSE IF"

### ISSUE THREAD

**Issue by granicayv** [robotframework/robotframework#4473]
Steps to reproduce:
1) Create test case with **false** If-condition, for example:
```
1   Test_if
2      IF     9 % 2 == 0
3           ...
4       ELSE IF     9 % 4 == 0
5           ...
6       ELSE 
7           ...
8       END
```
2) Set breakpoints at lines 2 and 4, they are both false
3) Launch debug of this test case

Expected result: Debugger will be stopped at line 2, after user clicks "Continue" button, debugger will be stopped at line 4.
Actual result: Debugger will **not** be stopped at lines 2 and 4.

Another case:
Create test case with **true** If-condition, for example:
```
1   Test_if
2      IF     9 % 3 == 0
3           ...
4       ELSE IF     9 % 4 == 0
5           ...
6       ELSE 
7           ...
8       END
```
2) Set breakpoints at lines 2 and 4, condition of "IF" is true, condition of "ELSE IF" is false
3) Launch debug of this test case

Expected result: Debugger will be stopped at line 2, after user clicks "Continue" button, debugger will be stopped at line 4.
Actual result: Debugger will be stopped at lines 2, after user clicks "Continue" button, debugger will **not** be stopped at line 4.

So debugger is stopped only at true IF conditions. The same with true ELSE IF conditions - debugger is stopped at true-condition and is **not** stopped at false-conditions.

Version of robotframework python lib - 5.0.1

**Comment by pekkaklarck** [comment]
Which debugger do you use? You should report this issue to that project. RF itself doesn't have built-in debugger.

**Comment by granicayv** [comment]
Thank you
