### ISSUE TITLE
Multiple Keyword Error 

### ISSUE THREAD

**Issue by krishnapython** [robotframework/robotframework#4475]
Hi All,

We have 2 repos with same resource file name in the git. While running testcases from one repo we are hitting multiple keywords error. Could any one give the solution for it.

Multiple keywords with name 'SSH-Set-Timeout' found. Give the full name of the keyword you want to use:
    SSH-Wrapper.SSH-Set-Timeout
    SSH-Wrapper.SSH-Set-Timeout

Thanks 
Krishna

**Comment by pekkaklarck** [comment]
Do I get it right that you have two resource files with same name and same keywords in use? That results to an unresolvable conflict. You need to either rename either files or keywords.
