### ISSUE TITLE
Explain the default value of `Sleep` keyword better in its documentation

### ISSUE THREAD

**Issue by F3licity** [robotframework/robotframework#4485]
Explain in the docstring of the keyword `Sleep`, that when a value is provided, as argument, without specifying minutes or seconds, that the default is seconds. 

Related PR: https://github.com/robotframework/robotframework/pull/4479

**Comment by pekkaklarck** [comment]
Good idea to make the keyword documentation more explicit about this. Already fixed in PR #4479. Thanks @F3licity!
