### ISSUE TITLE
Log.html and Report.html not returning Data when executing for large test cases

### ISSUE THREAD

**Issue by SelinMaryK** [robotframework/robotframework#4486]
Log.html and Report.html not returning Data when executing for large test cases

Keywords part of the test cases are not returned in log.html resulting in returning NaN data in report.html page
this is seen when executing large test cases.
Only the suite level data is returned in the log file. Test cases within the suite are not returned.

Version used: robotframework==3.2.2

![ReportHtmlError](https://user-images.githubusercontent.com/55212925/192970041-b8e8a947-f6f9-4327-898e-29aec862f392.png)
![LogHtmlError](https://user-images.githubusercontent.com/55212925/192973840-f3262973-520c-430f-8a6d-e620d0e0991a.png)

**Comment by pekkaklarck** [comment]
Could you please clarify.

**Comment by SelinMaryK** [comment]
In the log generated, i am unable to see the test cases. Only data at test suite level are returned. Resulting in the report to give error data. The issue is not seen always.

**Comment by pekkaklarck** [comment]
Do you get any errors in javascript console or elsewhere?

**Comment by SelinMaryK** [comment]
I have not been able to reproduce the issue when running locally. The issue is seen when the tests are run via bamboo pipeline. There are no errors in logs.
Currently i have upgraded the RF version to 5.0 in Bamboo to see if its an issue with the old version and so far the issue has not reproduced after the upgrade. Will continue observing and will update, in case its back. Thanks

**Comment by pekkaklarck** [comment]
Ok. Let's hope the issue doesn't occur anymore with the newer version. Or that if it occurs, you get some debug information that can help us understand the problem. With this information alone we cannot do anything.

I leave this issue open and wait if you got more info. If there's none, I'll eventually close it.
