### ISSUE TITLE
Invalid use of prefix in suite name is not validated

### ISSUE THREAD

**Issue by Tattoo** [robotframework/robotframework#4503]
One can [force execution order](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#test-suite-name-and-documentation) by naming suite files with prefix. 

If user fails to give empty suite name (eg. `01__.robot`), the `name` attribute is missing from output.xml. Although rebot doesn't mind this (log and report just show empty suite name), it causes problems to other ecosystem tooling (eg. [Jenkins plugin](https://issues.jenkins.io/browse/JENKINS-69807))

It would be nice if RF would consider this as invalid suite name.

**Comment by pekkaklarck** [comment]
We should in general require that suites have a name. We do that already with tests and keywords.

**Comment by mihacoding** [comment]
This is a duplicate of #4249  which was fixed in Robot Framework 5.0 (fixed in #4250).

**Comment by pekkaklarck** [comment]
Good catch!
