### ISSUE TITLE
Can we remove tablesorter.js from Robot Framework 5.0

### ISSUE THREAD

**Issue by nethra-pandappilav** [robotframework/robotframework#4509]
I would like to know if there is a way to remove tablesorter.js and still make Robot Framework 5.0 work without issues.
I am okay if the sorting functionality in report.html does not work anymore.

**Comment by nethra-pandappilav** [comment]
Sonatype Nexus Vulnerability Scanner identifies tablesorter.js as having copyleft license.

**Comment by pekkaklarck** [comment]
It's easiest for you to test it yourself.

**Comment by pekkaklarck** [comment]
According to the [docs](https://mottie.github.io/tablesorter/docs/) tablesorter is dual licensed, MIT and GPL, so there shouldn't be any issues with it.

**Comment by nethra-pandappilav** [comment]
Thanks for the quick turnaround. 
I would prefer not removing tablesorter if at all possible. 
The docs say I can pick one of the licenses. Is there a way to do this?
