### ISSUE TITLE
Deprecate `accept_plain_values` argument used by `timestr_to_secs`

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#4522]
This argument was added in 579667dfc0dcdeaa62863dc4ce690d06739ae521 when adding limit to WHILE loops. WHILE loop limits were changed in 628d405eb622918778791997efadcbe23cf7d486 so that the argument isn't anymore used for anything by Robot itself. It's not that useful in the public API and it's behavior hasn't been documented. Best to deprecate it now and remove later.

**Comment by KACHIDA** [comment]
Hi @pekkaklarck , I'm interested to work on above issue, can you please assign me this task.

**Comment by pekkaklarck** [comment]
Thanks for the offer @KACHIDA! Unfortunately this issue cannot yet be implemented because our master branch is still in RF 6.0.x and it's not possible to add code targeting RF 6.1. We could create a maintenance branch for 6.0.x or a development branch for 6.1, but it would then require merging fixes between branches that I'd like to avoid. We'll start more active 6.1 development most likely in January.

The above said, if you want to work on this you can simply create a PR with the required changes.
