### ISSUE TITLE
Feature Request:  Robot file in json style to support easier dynamic creation

### ISSUE THREAD

**Issue by norbertwie** [robotframework/robotframework#4529]
Didn't found this to be available or already requested yet.

### Request:
It would be helpful if json as input format of a robot file is supported.
E.g. with specific extension '.robot.json' like 'mytest.robot.json'

Example based on TestSuite.robot from the front page (https://robotframework.org) could look like this

<pre>
{
  "Settings": {    "Documentation": [  "A test suite for valid login.",
                                        "", 
                                        "Keywords are imported from the resource file"
                                                       ],
                         "Resource": [      "keywords.resource"    ],
                         "Default Tags": [      "positive"         ],
                      },

  "Test Cases":  [ {    "Headline": "Login User with Password",
                           "Steps": [      "Connect to Server",
                                           "Login User            ironman    1234567890",
                                           "Verify Valid Login    Tony Stark",
                                            "[Teardown]    Close Server Connection"
                                        ]
                                },
                      ],
}
</pre>

* 'Test Cases' shows only the first TC.
*   Teardown could be provided as "Teardown": 'Close Server Connection'
*  And further elements like "variables:", "key words:", ...

### Benefit:

* Parsing might speed up because a more structured format is provided. 
* Scripts/Tools e.g. jsonnet could easier create dynamic testcases.

### One vs. more spaces:

`"Login User            ironman    1234567890"` could be provided as `[ "Login User",  "ironman", "1234567890" ]`
This might improve the readability (beside the pipe notation) of what is concatenated and what is a separate parameter (or similar).

### Story:
My intention is to create robot files (or at least the test cases in it) dynamically.
Several [approaches](https://gerg.dev/2018/09/dynamically-create-test-cases-with-robot-framework/) can be found to do this inside the robot script or RFW, but my goal is to this outside being not limited by RFW.
Based on my background know how of creating gitlab jobs dynamically with jsonnet, I thought to do the same with robot by writing a script converting json to robot. Afterwards the idea was born to directly use json as input format for robot.

**Comment by manykarim** [comment]
There is an open issue which goes into that direction
https://github.com/robotframework/robotframework/issues/3902

**Comment by pekkaklarck** [comment]
Yeah, #3902 already proposes using JSON as a data format. The idea is to map executable objects, not `*.robot` files, to JSON meaning that the result will be something like this:
```json
{"name": "Suite", "doc": "Example", "tests": [{"name": "T1", "body": [{"type": "KEYWORD", "name": "Log", "args": ["Hi!"]}]}, {"name": "T2"}]}
```
That format ought to be a lot easier for tools to handle than the format proposed here.

**Comment by norbertwie** [comment]
@pekkaklarck  yes, #3902 looks good. 👍
