### ISSUE TITLE
Robot Framework - Countdown timer that logs to console in the same line

### ISSUE THREAD

**Issue by edgarwebster** [robotframework/robotframework#4531]
Hi people, I'd like to create a countdown timer such as a stopwatch. However I'd like to log to console in the same line, like a digital clock. I've created this in Python. However I don't know how to do the same in Robot Framework. I would be glad if someone could help me. Thank you.

**Comment by pekkaklarck** [comment]
You'd need to create a library to that does it. This issue tracker is a for bug reports and enhancement requests. If you need help creating a library, please use our Slack, discussion forum, or other such support channels listed at robotframework.org.
