### ISSUE TITLE
JSON variable file support

### ISSUE THREAD

**Issue by Xdomen** [robotframework/robotframework#4532]
### Problem

`robot --variablefile burek.json -i smoke ROBOT/` returns the following error:
`failed: Importing variable file ’burek.json’ failed: Not a valid file or directory to import.`

while `burek.py` containing the same JSON content seem to work just fine. 

`--variablefile (-V)` only seems to support Python and YAML file types. 
We would like to use JSON file as a variablefile to pass on certain variables that are used by other frameworks as well.

Thanks for all the help!

**Comment by pekkaklarck** [comment]
Adding support for JSON variable files wouldn't be too complicated. It would have a benefit that Python has a built-in `json` module but using YAML requires installing `PyYYAML`. I can add this to RF 6.1 scope and we can see is someone interested to look at it.

The reason I don't consider this super important is that you can already now pretty easily use JSON files as variable files. You can, for example, create a generic Python variable file that loads the JSON file. My understanding is that can also losslessly convert between JSON and YAML, so you could convert your JSON file to YAML before running Robot. It could even possible that just renaming your `burek.yaml` to `burek.json` would work. Anyway, being able to use JSON variable files directly and without installing `PyYAML` would be handy.

**Comment by sunday2** [comment]
Is anyone working on this.

**Comment by pekkaklarck** [comment]
Thanks for a great PR @sunday2! Sorry for the review taking so long. There were few simple changes to be done to code and tests. I hope you can take a look at them, but I can also merge the PR as-is and make changes myself. Another thing to do is writing documentation.

**Comment by sunday2** [comment]
> Thanks for a great PR @sunday2! Sorry for the review taking so long. There were few simple changes to be done to code and tests. I hope you can take a look at them, but I can also merge the PR as-is and make changes myself. Another thing to do is writing documentation.

Thank you for the review and all the comments, I have updated the code and pls help review again.

**Comment by pekkaklarck** [comment]
Thanks again for a great and now finally merged PR @sunday2! I wrote documentation for this feature (see commit f7ee913622e60c0cf630e1580c2bb58c57100187) so we can consider this issue done.

**Comment by pekkaklarck** [comment]
If you want to see how the documentation actually looks, you can generate the User Guide locally with this command:

    doc/userguide/ug2html.py create

**Comment by sunday2** [comment]
> If you want to see how the documentation actually looks, you can generate the User Guide locally with this command:
> 
> ```
> doc/userguide/ug2html.py create
> ```
> 
> If you see a typo or have enhancement ideas, just comment here or create another PR.

Thank you for the help, that's helpful.
