### ISSUE TITLE
Defining PRIVAT|LOCAL library/resource imports do narrow proposed keywords

### ISSUE THREAD

**Issue by Snooz82** [robotframework/robotframework#4534]
For test designers it would be very helpful that only "functional keywords" are proposed in the test suites by Editors.

Bigger projects have a high demand of keyword layers and rules to improve maintainability and readability.
So for example no Library keywords shall be used in test suites! 

the problem is, that even if a functional_keywords.resource is imported, rf and therefore also lsp proposes all keywords also those that are imported indirectly. Like Browser keywords. Even though the users shall not use them.

There is no way to define that keywords from a specific import shall only be used in the file where it is imported to.

Ideas (not necessarily good ones 😉 )
```robotframework
*** Settings ***
Library    Browser    PRIVAT
LocalLibrary    Browser
LocalResource     keywords.resource

```

**Comment by pekkaklarck** [comment]
Something like this would be really useful. We already have  #4472 that proposes same functionality and I close this as its duplicate. Also #2581 is somewhat related.

I thought we had some really old issue related to this as well, but I couldn't find anything. Perhaps I was thinking about #430 that was implemented in RF 6.0.
