### ISSUE TITLE
Clearing text doesn't work on Mac OS

### ISSUE THREAD

**Issue by luke-h1** [robotframework/robotframework#4535]
When trying to clear an input field with text already present, it seems that it occasionally doesn't work when using the `Clear Element Text` keyword (on both Windows, Linux & Mac). To get around this, I use the following to clear text fields which works fine on Linux & Windows but not on Mac OS: 

```robotframework
user clears element text
    [Arguments]    ${selector}
    click element   ${selector}
    press keys    ${selector}    CTRL+a+BACKSPACE
    sleep    0.3
```

when changing the keys to `CMD+a+BACKSPACE`, it doesn't seem to make a difference & the text isn't cleared on Mac OS, causing the test to fail. 

Is there any way to get around this problem and make it work on all 3 platforms?

**Comment by pekkaklarck** [comment]
This issue tracker is for bug reports and enhancement requests related to Robot Framework core. The problem you have seems to be with some external library.

**Comment by luke-h1** [comment]
So is this issue related to [SeleniumLibrary](https://github.com/robotframework/SeleniumLibrary)? afaik `click element` and `press keys` are a part of robot framework. No custom library is being used here

**Comment by pekkaklarck** [comment]
Robot itself doesn't have those keywords. If SeleniumLibrary is what you use, then the problem is most likely in it or in the tested system itself.
