### ISSUE TITLE
Support creating assigned variable name dynamically like `${x ${y}} =    Keyword`

### ISSUE THREAD

**Issue by zastress** [robotframework/robotframework#4545]
Apparently, it is not possible do return values into nested variables in RF, for cases like:

```
${x${y}} =    Keyword
${x}[a] =    Keyword
```

These can be quite handy aswell while using FOR loops, to populate values inside, like:

```
FOR    ${INDEX}    IN RANGE    1    4
        Keyword1    ${user${INDEX}-email}    ${user${INDEX}-fullname}    gender=${INDEX}
        ${short-id-${INDEX}}    API - Get User ID    ${user${INDEX}-fullname}
END
```

**Comment by pekkaklarck** [comment]
This is true. Notice, though, that
```
${x ${y}} =    Keyword
```
and
```
${x}[a] =    Keyword
```
are totally different features and thus need separate issues. The former is about creating the name of the assigned variable dynamically and the latter is about setting an item to a list, a dictionary, or anything else that has `__setitem__`. Both would be useful, but their implementation is different and most likely the latter is easier. I also consider the latter more useful and thus more important.

The example in the description uses the `${x${y}}` style so I guess we could consider this issue to be dedicated to that. The other enhancement then needs a separate issue. I can submit it myself.

**Comment by pekkaklarck** [comment]
The proposed
```
${x ${y}} =    Keyword
```
syntax is interesting because something like that isn't directly possible in Python. You can do it with `setattr`, but that doesn't really work on module level.

Until this functionality is implemented, you ought to be able to use the `Set Local Variable` keyword as a workaround:
```
${ret} =    Keyword
Set Local Variable    $x ${y}    ${ret}
```

**Comment by pekkaklarck** [comment]
The proposed
```
${x}[a] =    Keyword
```
syntax is the same as
```
x[a] = keyword()
```
in Python. For it the current workaround is using Collections keywords to add items to a dictionary or list, depending on the type of `${x]`:
```
${ret} =    Keyword
Set To Dictionary    ${x}    a    ${ret}
```

**Comment by pekkaklarck** [comment]
New #4546 now covers the item assignment syntax `${x}[a] =  Keyword`. I added both of these issues initially to RF 6.1 milestone.
