### ISSUE TITLE
RPA.Outlook.Application library not working

### ISSUE THREAD

**Issue by cdocfp** [robotframework/robotframework#4549]
Tried the sample code in documentation, it passes with no issue. Not sending any email. Open application when set to visible not opening.

Anyone else have this issue?

![image](https://user-images.githubusercontent.com/119360244/204377613-2348e5a3-498f-4cf5-816d-7312727dcbe7.png)

*** Settings ***
Library                 RPA.Outlook.Application
Task Setup              Open Application
Suite Teardown          Quit Application

*** Variables ***
${RECIPIENT}            address@domain.com

*** Tasks ***
Send message
    Send Message       recipients=${RECIPIENT}
    ...                subject=This is the subject
    ...                body=This is the message body
    ..                 attachments=approved.png

**Comment by pekkaklarck** [comment]
Please submit this issue to the RPA library issue tracker. This tracker is only for Robot Framework core.
