### ISSUE TITLE
Issue with auth in RequestsLibrary GET keyword

### ISSUE THREAD

**Issue by RYANTTA** [robotframework/robotframework#4550]
This should work but does not:
```
${auth}=      Create List     myuser    mypasswd
GET      https://google.com/        auth=${auth}
```
The error is:
>TypeError: ‘list’ object is not callable 

Note that this is a local error, no request was sent out of the box.

I’m using Robot Framework 5.0.1 (Python 3.8.10 on linux).

The root cause was discussed in this Robot Framework forum thread https://forum.robotframework.org/t/how-to-use-auth-parameter-in-get/4977/6, repeated here with minor editing.

In the Requests library, the creation of a `HTTPBasicAuth` object is restricted to a 2-length tuple only. That’s a bit inconsistent since e.g. `files` is documented to take file-tuples that can in fact be lists.

Now looking at the documentation for RequestsLibrary, a list is supported for basic auth when creating a Session, but only a tuple is supported for auth on non-session operations.

So this is how RequestsLibrary `Create Session` auth is handled:
`auth = requests.auth.HTTPBasicAuth(*auth) if auth else None`

So any iterable with length 2 will work with it… but it’ll try to convert an instance of another supported Auth object to a HTTPBasicAuth instance… which makes it hard to use other authentication types with the RequestsLibrary Sessions.
[End of Quote]

The not so nice workaround is to directly create a tuple then pass it to GET:
```
With auth
    ${auth} =     Evaluate    ("myuser",  "mypasswd")
    GET     https://someURL/mytestfile.txt     auth=${auth}
```

**Comment by pekkaklarck** [comment]
If this is still a problem, an issue should be submitted to RequestLibrary tracker. This tracker is only for Robot Framework core.
