### ISSUE TITLE
How do I pass a nested dictionary from robotframework to a python library that has **kwargs as in parampeter

### ISSUE THREAD

**Issue by hnyugyen** [robotframework/robotframework#4552]
Hi I have a library with a function:

func(**kwarg):
... if type(kwargs["key_for_mydictionary"]) == dict:
...        for key, value in kwargs[key_for_mydictionary].items():
...               parse each key values
...
...
How should I do to send in a dictionary/list where the keys in the dictionary can be a dictionaryas well?
How should the parameter from the robot framework look like?

I tried to send in something like: 
${D}    Create Dicitonary    A = a, B = { A = a, B = b}, C = c for example? How do I do this in Robot framework?

Then i wish to pass in the dictionary like:
...
...
...    func    &{d}

**Comment by MalikMlitat** [comment]
@hnyugyen you can do the following:
python func to print dict:

```python
#!/usr/bin/env python3

from robot.api.logger import console


def print_my_dict(**kwargs):
    console(kwargs)
```

```robot
*** Settings ***
Library     ./Dict.py
Library     Collections

*** Test Cases ***

T1:
    &{dict1} = 	Create Dictionary 	key1=value1 	foo1=bar1
    &{dict2} = 	Create Dictionary 	key2=value2 	foo2=&{dict1}
    print_my_dict     &{dict2}
```


output:

```bash
$ robot -P . Dict.robot 
==============================================================================
Dict                                                                          
==============================================================================
T1:                  ..{'key2': 'value2', 'foo2': {'key1': 'value1', 'foo1': 'bar1'}}
T1:                                                                   | PASS |
------------------------------------------------------------------------------
Dict                                                                  | PASS |
1 test, 1 passed, 0 failed

```

**Comment by pekkaklarck** [comment]
We use this tracker is for bug reports and enhancement requests and questions are better asked on our Slack or other such support forums listed at robotframework.org. The answer above looks fine, though, but I'm not sure is it a good idea in general to accept a nested dict like this.
