### ISSUE TITLE
Utests for rf 5.0.1 are getting failed

### ISSUE THREAD

**Issue by shruti729** [robotframework/robotframework#4555]
The utests for robot framework 5.0.1 are getting failed with error **ImportError: cannot import name 'Language' from 'robot.api'** .
Could you please help?

**Comment by pekkaklarck** [comment]
That `Language` class is a new addition in RF 6.0 so there's likely something wrong with your setup. How did you get the code and run those tests?

**Comment by shruti729** [comment]
Its RF 5.0.1 . I have downloaded the code from github and executing these tests within pipeline. Is there any particular configuration for this new class
