### ISSUE TITLE
Bug in `--reportbackgroundcolor` documentation in the User Guide

### ISSUE THREAD

**Issue by adiralashiva8** [robotframework/robotframework#4557]
_Observation_: User guide and robot mismatching in #setting-background-colors section

_User Guide_: If you specify three colors, the first one will be used when all the tests pass, the second when all tests have been skipped, and the last when there are any failures. (pass:skip:fail)

_Robot Command Line Help_: '--reportbackground': Expected format 'pass:fail:skip'

**Comment by pekkaklarck** [comment]
The correct order if `pass:fail:skip`.
