### ISSUE TITLE
Add some more logging

### ISSUE THREAD

**Issue by kbogineni** [robotframework/robotframework#4560]
We need to know how many test cases are going to be triggered and which test case is running through the robot logging when we execute the robot suite as below

For example, if we have 12 tests in a suite, we want to see the below kind of logging

12/12 test cases are scheduled
1/12 is running

**Comment by peerasut** [comment]
I don't think Robot Framework works that way. It does not read the whole test suite before executing the script. So, implementing this function would cause a lot of effort. 

From my experience of using Robot Framework at work, I find this function will be in need (but not that much) only for manually running the script. After finishing up the script, when the script is automatically executed (for my project ,it's daily), I don't really care how many test cases are scheduled or what number of test cases is being run. Eventually, I only care about the result.

However, if you could explain in which situation you would need this function, I think the maintainer would might consider to implement it.

**Comment by MalikMlitat** [comment]
you can use the dryrun option: http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#dry-run

**Comment by pekkaklarck** [comment]
I believe dry-run handles this well enough.
