### ISSUE TITLE
Apostrophe ( `'` ) in `Documentation` settings lead to errors

### ISSUE THREAD

**Issue by dschiller** [robotframework/robotframework#4566]
This code works without issues.

```robot
** Settings **
Documentation  Test Apps

** Test Cases **
Open App
  ${vars}  Get Variables
  IF  "\${SuT}" not in "${vars}"
    Fail  Variable `SuT` not found.
  END
```

This one leads to an `Token` error: `Evaluating IF condition failed: Evaluating expression '"${SuT}" not in "{ ..., '${SUITE_DOCUMENTATION}': "Test App's", ..."' failed: TokenError: ('EOF in multi-line statement', (2, 0))`

```robot
** Settings **
Documentation  Test App's

** Test Cases **
Open App
  ${vars}  Get Variables
  IF  "\${SuT}" not in "${vars}"
    Fail  Variable `SuT` not found.
  END
```

`Robot Framework 6.0.1 (Python 3.10.8 on darwin)`

**Comment by pekkaklarck** [comment]
Have you read the [Evaluating expressions](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#evaluating-expressions) appendix from the User Guide? Especially the Using variables section there is likely related to this issue.

**Comment by dschiller** [comment]
Hey Pekka, no I didn't but I did now. I was thinking about any kind of escaping and tried two quotes, but didn't try three.

Here the correct usage:

```robot
** Settings **
Documentation  Test App's

** Test Cases **
Open App
  ${vars}  Get Variables
  IF  "\${SuT}" not in '''${vars}'''
    Fail  Variable `SuT` not found.
  END
```

**Comment by pekkaklarck** [comment]
I'd actually use `$vars`, but using triple quotes works fine in this case as well.
