### ISSUE TITLE
Add `on_limit_message` option to WHILE loops to control message used if loop limit is exceeded

### ISSUE THREAD

**Issue by asaout** [robotframework/robotframework#4575]
Currently, the error raised when the limit of the WHILE loop is reached isn't customizable. As a result of the issue #4562, we decided to add an option named `on_limit_message` on the WHILE loop.

Here is an example :

```
*** Test Cases ***
On limit message
    WHILE    True    limit=5    on_limit_message=Custom error message
        Log     Test
    END
```

**Comment by pekkaklarck** [comment]
This enhancement sounds good to me. The only design decision is the name of the new config option. We are planning to add `on_limit` as part of #4562 and `on_limit_message` is consistent with that. It possibly could be `on_limit_error` but perhaps `message` is more explicit.

There's already PR #4561 implementing this issue. Is it @asaout already ready for review?

**Comment by asaout** [comment]
Yes, I have made some updates and it is ready for review now.

**Comment by yanne** [comment]
Pr has been emerged in bf589e6b428640357bc9e4c055709d652e9d0401
