### ISSUE TITLE
Make the WHILE loop condition optional

### ISSUE THREAD

**Issue by asaout** [robotframework/robotframework#4576]
As discussed in issue #4562, if no condition is set on the WHILE loop, the condition should be `True` by default.

Here is an example :
```
*** Test Cases ***
Optional WHILE loop condition
    WHILE
        Log     Test
    END
```

**Comment by pekkaklarck** [comment]
The main use case is avoiding unnecessary `True` if/when we add support to continue execution if the loop limit is reached (#4562). That allows usages like this:
```
WHILE    limit=1 minute    on_limit=pass
    Keyword
END
```

Not needing `True` is nice also with BREAK:
```
WHILE
    Keyword
    IF    ${condition}    BREAK
END
```

**Comment by xylix** [comment]
I find this a bit confusing syntax and don't really see it offering much benefit. It saves one word in the cases where it is useful, but adds more implicit behaviour that users need to learn.

**Comment by pekkaklarck** [comment]
I find it convenient that you don't need to specify a condition when it's always true. Among other things, it means you don't need to know should use use `true` or `True`. The change is also very easy to implement and is totally backwards compatible.

**Comment by Snooz82** [comment]
I do not like that whole feature imho. That makes the feature too implicit. I would say an explicit `${True}` should be there
