### ISSUE TITLE
Provide API to be able to add Robot Framework listeners at runtime

### ISSUE THREAD

**Issue by fabioz** [robotframework/robotframework#4586]
This would be interesting to add a debugger at runtime (i.e.: it could be started from a keyword without any previous setup).

**Comment by sebastianciupinski** [comment]
@fabioz - since libraries can register listeners, there is a option to register listener in runtime, e.g. https://github.com/sebastianciupinski/robotframework-listenerlibrary

**Comment by fabioz** [comment]
Thanks, I think that should suffice for me. Closing this issue.
