### ISSUE TITLE
RF doc links should be able to open to a new page

### ISSUE THREAD

**Issue by glueologist** [robotframework/robotframework#4588]
The HTML of the RF documentation is such one can only open a doc on the same page.  Most of the time I need to open a number of them so have to open multiple pages.  The current design breaks a very common use pattern of allowing the user to choose how to open a link.

http://robotframework.org/robotframework/

**Comment by pekkaklarck** [comment]
I wouldn't personally like that behavior, but being able to open docs to background tabs using the common `Ctrl + click` like you can do with normal links would be nice. If someone can figure out how to do that, please submit a PR or explain changes here and I can do them myself. Notice that this whole page is likely to be recreated in the future so not too much effort should be spent on updating it.

**Comment by pekkaklarck** [comment]
No updates. Closing.
