### ISSUE TITLE
robotframework logging

### ISSUE THREAD

**Issue by alexshagiev** [robotframework/robotframework#4591]
I understand that robotframework does  bunch of things intercepts of stdout and anything log.info python based logging. This makes it very difficult to just get things from lets say robot library being developed to just print to the console. Am i missing a trick that would allow me to configure robot to just let my python's code to print log.info to stdout of my terminal or this would need to be a feature request?

**Comment by pekkaklarck** [comment]
This tracker is for bug reports and enhancements requests and questions should be asked on our Slack or other such forumns listed at robotframework.org. The description doesn't make it clear how you'd like to log to console either. If you use `print` you can use `file=sys.__stdout__` with it.
