### ISSUE TITLE
Breaking changes on RF master: format_name is not defined in `robot.running.builder.parsers.RobotParser.build_suite`

### ISSUE THREAD

**Issue by fabioz** [robotframework/robotframework#4593]
There's a bug in `robot.running.builder.parsers.RobotParser.build_suite` because `format_name` is not defined, which gives me a `NameError: name 'format_name' is not defined`.

-- side note: even a really basic linter such as pyflakes would get this, so, maybe it'd be worth integrating it into robotframework.

**Comment by fabioz** [comment]
Note: my usage is the following:

```
    model = get_model(
        """
*** Settings ***
Library    Collections

*** Test Case ***
Some Test
    Log    Something
"""
    )

    test_suite = TestSuite.from_model(model)
```

**Comment by pekkaklarck** [comment]
Yeah, this is a regression caused by 63162438bd492b89557b305813462f33f4a65b7c and also noticed by our tests. It wasn't fixed immediately because it wasn't clear what's the best way to do that and both @yanne and I have been busy. I now have it fixed locally and will commit the fix soon.

**Comment by pekkaklarck** [comment]
It's awesome that you @fabioz are testing against the master branch and can report regressions and problematic backwards incompatible changes. Much appreciated!
