### ISSUE TITLE
Deprecate `name` argument of `TestSuite.from_model`

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#4598]
It's a bit odd to be able to configure the name of the creates suite when using `TestSuite.from_model` but no other attributes like `doc`. It doesn't make sense to support configuring others, because it's easy to do that after the suite is created either by setting attributes normally or by using the convenient `TestSuite.config` method like `TestSuite.from_model(model).config(name='X', doc='Y')`. Let's deprecate the name argument to make API more uniform.

**Comment by fabioz** [comment]
Note: although the effort is small on the RF side, I don't see the breakage on clients as a good thing. I'd rather have RF more backward compatible than trying to clear such small wrinkles for really minor gains (keeping as is is probably less effort than doing the change even in the long run and existing clients won't break).

**Comment by pekkaklarck** [comment]
Do you think `name` is actually used?

**Comment by fabioz** [comment]
Well, if it's there someone definitely uses it (I know I use it now to do some workarounds due to the recent breakages/source changes).

**Comment by pekkaklarck** [comment]
It's possible that someone uses it, but users of `TestSuite.from_model` are pretty rare in general and I would assume that for most of them the name being automatically set based on `model.source` is enough. It's easy for those users to change their code at some point.

**Comment by pekkaklarck** [comment]
One reason to deprecate `name` is that I'm about to add separate `TestSuite.from_string` method (#4601) and it should have same API as `from_model` (except that the former needs parameters to configure `get_model`).
