### ISSUE TITLE
Passing --form data as part of request body issue 

### ISSUE THREAD

**Issue by KGhonim** [robotframework/robotframework#4602]
*** Settings ***
Library    RequestsLibrary
Library    JSONLibrary
Resource    ../Resources/Environment.resource

*** Keywords ***

User Login
    [Arguments]    ${Username}    ${Password}
    ## Get the access token
    Create Session  xwe ${host}   
    ${data}=    Create dictionary    Username=${Username}    Password=${Password}
    ${form_data}=   Evaluate     {'mldata': str(${data})}

    Log To Console  ${data}
    ${response}=   Post Request     xwe  ${login_serviceName} 
    Log To Console  ${response.content}
    Should Be Equal As Strings    ${response.status_code}    200

getting error:  b'{"status":"failed","Message":"User not found. Please contact system administrator"}'

**Comment by pekkaklarck** [comment]
This issue tracker is for bug reports and enhancement requests related to Robot Framework core. Questions are better asked on our Slack or other support forums listed at robotframework.org.
