### ISSUE TITLE
Timeout is not taken into account when using Datadriver concept.

### ISSUE THREAD

**Issue by Eya-Mh** [robotframework/robotframework#4606]
**While using data-driven approach as well as templates the timeout configured in the testcase is not taken into account.
taking this example, the testcases will be passed as if i didn't set a timeout despite that i'm configuring it for 5 seconds.**
```
*** Settings ***

Library    DataDriver    file=data.csv
Variables    dynamic_test_naming.py    ${SUITE_NAME}
Test Template   TTM25_LCE_355_keyword

# Test Timeout    5 seconds

*** Test Cases ***
TTM25_LCE_355
    [Setup]   Sleep    1
    [Teardown]    Sleep    1
    [Timeout]    5
    ${szl}
    
    
*** Keywords ***
TTM25_LCE_355_keyword
    [Arguments]    ${szl}
    Sleep    10 
 
```

**Comment by Snooz82** [comment]
@Eya-Mh 

Which version do you have of DataDriver?
There was this issue in 1.6.1 but that is fixed.

Please update to 1.7.0

Regards

**Comment by Eya-Mh** [comment]
@Snooz82 Thank you, i have upgraded to the last version and the problem is solved.
