### ISSUE TITLE
`robot.running.model.Import` using wrong `directory` if `source` is set to a non-existing file.

### ISSUE THREAD

**Issue by fabioz** [robotframework/robotframework#4607]
When the `source` for a `robot.running.model.Import` is set internally to a non existing file, the `directory` considered is returning the `source` unchanged, which isn't correct.

It should always use the dirname.

The background is that the interactive console creates in-memory structure (so that the proper cwd would be expected but with a non-existing file internally) and this is now failing because it considers the directory the same as the source.

**Comment by fabioz** [comment]
Just adding a note to myself here (revert https://github.com/robocorp/robotframework-lsp/commit/1cb3cfbafa6ff56e9b5f0e724c7d64bef676ef3a when this is fixed).

**Comment by pekkaklarck** [comment]
Changed the behavior to same as earlier in the above commit. I decided to fix this myself and not merge PR #4623 because it lacked tests.

**Comment by pekkaklarck** [comment]
No worries!
