### ISSUE TITLE
Log Values are not shown in Report of Python Robot framework we have to expand it

### ISSUE THREAD

**Issue by YenikeRaghuRam** [robotframework/robotframework#4615]
Log Values are not shown in Report of Python Robot framework we have to expand it

For instance

KEYWORD BuiltIn . Log ${resp.status_code} 00:00:00.000
KEYWORD BuiltIn . Log ${resp.url}

But expected 
Log 200 
Log http://url

**Comment by pekkaklarck** [comment]
Argument values cannot be automatically shown because they can be big and contain confidential information. Certain keywords themselves log them and in this case you see the message when you open the keyword.
