### ISSUE TITLE
Automation Desktop Applications using Robot Framework

### ISSUE THREAD

**Issue by FWDQK** [robotframework/robotframework#4616]
Hi Team,
We need to automate desktop applications which are based on below technology:
1. Java application: We have one URL which when launch opens Java application page.
2. wpf file extension

Please suggest which Robot Framework libraries we can use to automate such applications.

**Comment by pekkaklarck** [comment]
I personally don't know which library to use in this case. I recommend asking on our Slack or Forum. This tracker is for bug reports and enhancement requests.
