### ISSUE TITLE
Add keyword to delete variables

### ISSUE THREAD

**Issue by Joxd1** [robotframework/robotframework#4617]
I would be nice if there was a keyword to delete variables (especially global variables or suite variables when a directory is executed).

**Comment by pekkaklarck** [comment]
Is there a special reason to delete a variable? Isn't setting it to some special value enough?

**Comment by Joxd1** [comment]
Yes, you are right. I don't think that this is needed anymore as there are enough ways around this with variable scopes or other keywords. We can close this issue.

**Comment by pekkaklarck** [comment]
Conceptually deleting a variable makes sense. Our current variable namespace implementation just makes that unnecessarily hard compared to benefits.

**Comment by Joxd1** [comment]
Yes, my use case was fixed with better variable namespace handling. If you think it would be a good feature we can reopen this issue. But I don't know if it is worth the effort to implement when in almost all cases it is not really needed.

**Comment by pekkaklarck** [comment]
No need to open a new one. We can return to after variable handling has been improved in Robot itself.
