### ISSUE TITLE
OperatingSystem library docs have broken link / title

### ISSUE THREAD

**Issue by xylix** [robotframework/robotframework#4621]
https://robotframework.org/robotframework/latest/libraries/OperatingSystem.html contains three broken HTML snippets I could identify:
One in Table of Contents:
<img width="301" alt="Screenshot 2023-01-24 at 14 58 38" src="https://user-images.githubusercontent.com/13387304/214297779-7e728790-f913-4392-b824-2e4155698b9d.png">
And two in the actual section where that link should go to. (one is the title of the section, other is the `[https://docs.python.org/3/library/pathlib.html pathlib.Path]` link showing inline)
<img width="1120" alt="Screenshot 2023-01-24 at 14 58 52" src="https://user-images.githubusercontent.com/13387304/214297847-152ea93f-de57-4d8a-b956-5230d1a9dd60.png">

**Comment by pekkaklarck** [comment]
It seems our documentation syntax doesn't handle formatting in titles and/or in links. Easiest to fix by not using formatting in the title. I also noticed the section having this title has a broken link as well. Clearly the rendered documentation wasn't read when the section was written.

I don't know how we had missed this issue for so long. Well, good to be fixed later than never.
