### ISSUE TITLE
Warnings about private keywords appear when used as setups or teardowns even though the keywords are in the same file

### ISSUE THREAD

**Issue by Pakkanen1** [robotframework/robotframework#4622]
When setting a private keyword that is located in the suite file as suite/test setup or teardown, warnings about each keyword being private appear. 

**RF version:** 6.0.2
**Python:** 3.10
**OS:** Windows 10 Pro 21H2 build 19044.2486

You can reproduce the problem with a simple suite like this:
```
*** Settings ***
Suite Setup    PrivateSetup
Suite Teardown    PrivateTeardown

*** Test Cases ***
Calling Private Keywords From Setup/Teardown In The Same File As The Test Case
    [Setup]    PrivateSetup
    log    Do something!
    [Teardown]    PrivateTeardown

*** Keywords ***
PrivateSetup
    [Tags]    robot:private
    Log    This will raise warning!

PrivateTeardown
    [Tags]    robot:private
    Log    This will raise warning!
```

Output:
```
[ WARN ] Keyword 'PrivateSetup' is private and should only be called by keywords in the same file.
==============================================================================
Poista Dataa                                                                  
==============================================================================
Calling Private Keywords From Setup/Teardown In The Same File As T... | PASS |
------------------------------------------------------------------------------
Poista Dataa                                                          | PASS |
1 test, 1 passed, 0 failed
==============================================================================
Output:  C:\robotti\lokit\output.xml
Log:     C:\robotti\lokit\log.html
Report:  C:\robotti\lokit\report.html
[ WARN ] Keyword 'PrivateSetup' is private and should only be called by keywords in the same file.
[ WARN ] Keyword 'PrivateTeardown' is private and should only be called by keywords in the same file.
[ WARN ] Keyword 'PrivateTeardown' is private and should only be called by keywords in the same file.

Process finished with exit code 0
```

**Comment by pekkaklarck** [comment]
This is actually by design. Private keywords can be used without a warning only by _keywords_ in the same file. Using a private keyword directly in a test causes the same warning as you get when using them as test/suite setups/teardowns. Using private keywords as keyword teardown is fine.

I don't see big problems making it possible to use private keywords defined in a test case file as suite/test setup/teardown without a warning, though, and the change wouldn't be backwards incompatible either. It can be considered if you have a good use case for it and especially if you would be interested to provide a PR.

**Comment by Pakkanen1** [comment]
Its actually really common for me to have suite specific keywords such as setup/teardown in the suite file itself. It isolates test-specific logic from commonly used keywords. Those keywords usually just call public keywords elsewhere, but with varying sequences based on the test at hand.
Of course I could always just move those keywords to another resource file, but then it would seem like that the resource file would be ok to use with other suites, when in fact the keywords were meant for a specific suite.
I can try to find time this month and familiarize myself with the codebase for a PR.

**Comment by pekkaklarck** [comment]
Having setup/teardown keywords in the suite file is fine and often a very good idea. What use case you have for making them private?

**Comment by Pakkanen1** [comment]
> Having setup/teardown keywords in the suite file is fine and often a very good idea. What use case you have for making them private?

Hmm... yeah I guess this is kinda niche 😅 
My first thought was that since the keywords were are supposed to be used by the suite-file only, I should private them. But I don't import keywords from other suite-files anyway, so I guess there is no real use case. 
The reason I made this issue was because **robotframework-lsp** kept suggesting keywords from .robot files, but I realize now that privating them doesn't help either. I'm closing this issue, since it's more of an issue with robotframework-lsp or it's configuration.
