### ISSUE TITLE
Add Pop From List to Collections

### ISSUE THREAD

**Issue by kstine** [robotframework/robotframework#4625]
Seemingly missing from Collections is the pop() functionality for lists.

This would pair with the existing "Pop From Dictionary".

**Comment by pekkaklarck** [comment]
I didn't notice it initially either, but there actually is `Remove From List` that implements this functionality.

**Comment by kstine** [comment]
True.
If a user truly wants the pop() python functionality they can do an inline expression or Evaluate.

`${{$list.pop()}}`

pop() has the advantage of defaulting to the last item in a collection.

**Comment by pekkaklarck** [comment]
We could enhance `Remove From List` to remove from the end by default, but using `-1` does that as well so I'm not sure how big benefit it would have.
