### ISSUE TITLE
"Custom converters must accept exactly one positional argument" error when the second argument to a custom converter is optional

### ISSUE THREAD

**Issue by DetachHead** [robotframework/robotframework#4627]
see https://github.com/robotframework/robotframework/issues/4088#issuecomment-986367405

**Comment by pekkaklarck** [comment]
Have you tested this with RF 6?

**Comment by KotlinIsland** [comment]
omg, my comment didn't appear. This is still an issue in 6, but when it comes to var args
```py
def foo(*args): ...
```

**Comment by KotlinIsland** [comment]
I'll submit a PR ASAP!

**Comment by KotlinIsland** [comment]
#4629

**Comment by pekkaklarck** [comment]
Yeah, the code requires positional arguments but varargs would be fine as well. I'm fine with changing that, but the issue title and preferably also description should be updated accordingly. Can you @yanne take a look at the PR?

**Comment by yanne** [comment]
I took the commit provided in PR, made a couple of smallish improvements and this is now done. The PR commit can be found in mater at  524b871ad337d5004465dbdea3e5995b12d647f8

**Comment by yanne** [comment]
The main change I made is that converters with signature `*varargs` will be passed both the value and the library instance, the latter of which was added as a new optional converter argument during 6.1 development.

**Comment by KotlinIsland** [comment]
> The main change I made is that converters with signature `*varargs` will be passed both the value and the library instance, the latter of which was added as a new optional converter argument during 6.1 development.

So it will be inconsistent with other converters and won't work with any third party functions/ constructors?

We raised this issue mainly because we were trying to use:

```py
{Path: Path}
```
Which was giving the false error regarding signature compatibility. Now it will pass the value and the library, which will make it break.

I would recommend reverting this change.

**Comment by KotlinIsland** [comment]
@yanne Even looking at the example in the documentation:
```md=
The `library` argument to converter function is optional, i.e. if the converter function
only accepts one argument, the `library` argument is omitted. Similar result can be achieved
by making the converter function accept only variadic arguments, e.g. `def parse_date(*varargs)`..
```

This example seems like a very strange signature, why not write it as `def parse_date(value, library)`?

**Comment by pekkaklarck** [comment]
I honestly cannot think any reason why anyone would create a converter that accepts a varargs. Anyway, now that converters accepts 1-2 arguments, it's natural that if you implement a converter accepting unlimited number of arguments, we pass it as many arguments as possible. If that's not ok for you, we can revert the change can close this issue as wontfix.

**Comment by KotlinIsland** [comment]
@pekkaklarck Sounds good, I didn't realize `Path` was already supported.
