### ISSUE TITLE
Deprecate Python 3.7

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#4637]
We have already deprecated Python 3.6 (#4295) and plan to remove support for it in RF 7.0 (#4294). Python 3.7 will reach its end-of-life in [June 2023](https://peps.python.org/pep-0537/) and it's clear RF 7.0 won't be released before that. In this situation it makes sense to drop also Python 3.7 support in RF 7.0 and thus we need to deprecate it now.

Similarly as with Python 3.6 deprecation, it doesn't make sense to emit deprecation warnings or make any other code changes. We only need to make sure info about supported versions in the README and in the UG is correct and mention this in RF 6.1 release notes.

**Comment by pekkaklarck** [comment]
The main reason we have supported Python 3.6 quite long after its end-of-life in [December 2021](https://peps.python.org/pep-0494/) is that it is the default Python version in RHEL 8 that is supported until [May 2029](https://endoflife.date/rhel). RHEL uses Python 3.9 by default and with newer RHEL versions upgrading Python ought to be easier as well.

**Comment by KotlinIsland** [comment]
Is the 'v6.1' milestone correct here? shouldn't it be 'v7.0'?

**Comment by KotlinIsland** [comment]
- PR here #4641

**Comment by pekkaklarck** [comment]
The idea of this issue is just to explicitly mention that RF 7 won't support Python 3.7 anymore. RF 6.x will still support it so there shouldn't be any code changes, changes to CI, etc. I believe only two things are needed:

- Updating installation instructions to mention that the forthcoming RF 7 will only support Python 3.8+. I already have done that locally but apparently didn't yet push changes. I'll do that later today.
- Mentioning that Python 3.7 is deprecated in RF 6.1 release notes. This issue having `deprecation` label covers that.

Do others see where else this should be mentioned?
