### ISSUE TITLE
Error Generating libspec

### ISSUE THREAD

**Issue by Antimatterr** [robotframework/robotframework#4650]
So I have created an External keyword using python file for image text extraction and when I try to import that keyword into robot file , it works fine but there are warnings on my VScode editor
`Unresolved library: ../Libraries/imageMatching.py.
Error generating libspec:
Importing library 'imageMatching' failed: FileNotFoundError: [Errno 2] No such file or directory: '/Users/sidhant/wsui-automation/Libraries/config.json'
Consider adding the needed paths to the "robot.pythonpath" setting
and calling the "Robot Framework: Clear caches and restart" action.`

**Comment by pekkaklarck** [comment]
This looks like an issue in the VSCode plugin you use or in your plugin configuration. Either way, I cannot help with the issue. This tracker is for bug reports and enhancement requests related to Robot Framework itself so I close this issue.
