### ISSUE TITLE
Is it possible to use `run_keyword` for a specific Library ?

### ISSUE THREAD

**Issue by dschiller** [robotframework/robotframework#4652]
I have two libraries with the same keyword and I would like to use the builtin `run_keyword` but it fails with an keyword not found error.

#### src/QALibs/core/platform/mac/AppleScript.py
```python
@keyword
def get_window_title(self, application: str, timeout=1) -> str:
    """Returns the window title of an application.."""
    Platform.fail_if_not_os('Darwin')
    script = 'osascript -e \'with timeout of ' + str(timeout) \
        + ' seconds\' -e \'set myWindow to a ref to window 1 of application "' \
        + application + '"\' -e \'name of myWindow\' -e \'end timeout\''
    process = subprocess.run([script], stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)
    if 'AppleEvent timed out' in process.stderr.decode('utf-8').strip():
        print('Timeout')
    else:
        print(process.stdout.decode('utf-8').strip())
```

#### src/QALibs/Window.py
```python
@keyword
def get_window_title(self, application: str) -> str:
    """Returns the window title of a given application."""
    # If Darwin
    title = self.builtin.run_keyword('AppleScript.Get Window Title', application)
    # If Windows
    # Not implemented
    self.logger.warn(title)
```

```shell
No keyword with name 'AppleScript.Get Window Title' found.
```

Or is it better to call the class method `AppleScript.get_window_title()` directly ?

Like:

```python
from QALibs.core.platform.mac.AppleScript import AppleScript
...
    title = AppleScript().get_window_title(application)
...
```

**Comment by pekkaklarck** [comment]
Have you imported the `AppleScript` library in the test that uses the `Windows` library? If not, Robot cannot know about such library.

I would say importing the library class and calling its method in Python is generally a better solution but hard to know exactly based on only this information.

Notice also that this tracker is for bug reports and enhancement requests and we have Slack and other forums for general questions. I leave this issue open in case there a bug somewhere although it doesn't look like that.

**Comment by dschiller** [comment]
Thank you Pekka and sorry for the Noise. Will use Slack and the other Forums in the future for questions alike.

**Comment by dschiller** [comment]
How can I access Slack ? When entering my Mail adresse to register that fails as I need a @robotframework.org address, which I don't have. Also further there is written: 
```
Contact the workspace administrator at RobotFramework for an invitation.
```
Who is that an how to get the address of this person ?

**Comment by dschiller** [comment]
Found it via the forum https://forum.robotframework.org/t/robot-framework-roadmap-discussion/5090 at https://slack.robotframework.org. Maybe its worth updating the message on https://robotframework.slack.com/signup#/domain-signup from

```
Don’t have an email address from one of those domains?
Contact the workspace administrator at RobotFramework for an invitation.
```

to:

```
Don’t have an email address from one of those domains?
Get an invitation at https://slack.robotframework.org.
```

**Comment by pekkaklarck** [comment]
Yeah, https://slack.robotframework.org is our newish landing page where you can get an invitation and that also contains a link to https://robotframework.slack.com for existing users. When you don't have an account, info at https://robotframework.slack.com isn't that useful and adding a link to https://slack.robotframework.org would be good. I don't know can we add such info, though, but I can ask about that.

**Comment by pekkaklarck** [comment]
I asked around and apparently we have no control on the content at https://robotframework.slack.com/. We cannot thus do anything else than make sure we use https://slack.robotframework.org/ everywhere.
