### ISSUE TITLE
Exit code 252 on remote ssh session with PSEXEC

### ISSUE THREAD

**Issue by Mavnus04** [robotframework/robotframework#4657]
We have a Jenkins server which connects to Windows 10 computers via SSH. We want to run some automation testing on these machines with robot framework. I am using PSEXEC with a session ID so that the execution can be visually seen and we can capture screenshots/video. 

Example robot code we are running:
```
robot -d Output/now -T ^
-v NOW_DIR:now ^
--variablefile ../GameCommon/VariableFiles/FilePaths.py ^
-s Suites.TestSuites.RecordTest .
```

When we run this code locally on the remote machine, it passes.
When we run this code over the SSH session, it passes, but since it is on session 0, all the screenshots/vidoes are black.
When we put this code into a bat file on the remote machine, then call it remotely with PSEXEC over SSH, it runs and records fine.
When we run this code over the SSH session with PSEXEC, it throws back error code 252.

```
psexec -s -i %sessionId% robot -d Output/now -T ^
More? -v NOW_DIR:now ^
More? --variablefile ../GameCommon/VariableFiles/FilePaths.py ^
More? -s Suites.TestSuites.RecordTest .

PsExec v2.2 - Execute processes remotely
Copyright (C) 2001-2016 Mark Russinovich
Sysinternals - [www.sysinternals.com](http://www.sysinternals.com/)

robot exited on *** with error code 252.
```
I have tried this simpler code which only uses the suite parameter, but still get the same error:
```
psexec -s -i %sessionId% robot -s Suites.TestSuites.RecordTest .

PsExec v2.2 - Execute processes remotely
Copyright (C) 2001-2016 Mark Russinovich
Sysinternals - www.sysinternals.com

robot exited on *** with error code 252.
```
When I try the --help or --version command, it returns with code 251, `Help or version information printed.` 
```
psexec -s -i %sessionId% robot --help

PsExec v2.2 - Execute processes remotely
Copyright (C) 2001-2016 Mark Russinovich
Sysinternals - www.sysinternals.com

robot exited on *** with error code 251.
```

It would be easier if I could run the code directly with PSEXEC and NOT have to put into a bat file on the remote machine.  
Ideas of what might be going wrong?  Suggestions of other things to try? 
Let me know if you need other details to help me solve this. 

robot --version
Robot Framework 5.0.1 (Python 3.7.9 on win32)

**Comment by Mavnus04** [comment]
@pekkaklarck , what I originally posted is the only error message I am seeing.  Hence why I am asking for help.  

Could there be a bug in Robot Framework for not reporting back more information on what is causing the issue? 

I'll try generating more output

**Comment by pekkaklarck** [comment]
I have no idea why the error message isn't shown anywhere. It could be due to a bug in Robot, but I consider a problem with psexec integration/configuratoin more likely. Anyway, this is something you need to debug. Notice that these errors are written by Robot to stderr.

**Comment by pekkaklarck** [comment]
No updates. Closing.
