### ISSUE TITLE
BuiltIn.Log Keyword Documentation contains a defect

### ISSUE THREAD

**Issue by alagierx** [robotframework/robotframework#4663]
This is rather a typo more than a bug, but in the very last line of docstring for `BuiltIn.Log` Keyword, there is an annotation that one can choose between `type` and `log` formatter options. 
Looking at `_get_formatter` method ( [HERE](https://github.com/robotframework/robotframework/blob/572f1e412a14c125e2098ce79e37dd45c2c0f990/src/robot/libraries/BuiltIn.py#LL3019) ), there is no such key in the dictionary. I believe that the latter option should be `len`.

Robot Framework version: 6.0.2
![image](https://user-images.githubusercontent.com/102961347/220547427-40426d55-7d01-4187-b2f9-ce8d93aad566.png)

**Comment by pekkaklarck** [comment]
Looks like a typo. Thanks for a report!
