### ISSUE TITLE
Importing custom library not working if module name differ class name

### ISSUE THREAD

**Issue by Redysz** [robotframework/robotframework#4669]
Hello, the documentation says:
> Python classes are always inside a module. If the name of a class implementing a library is the same as the name of the module, Robot Framework allows dropping the class name when importing the library. [...] **If the module name and class name are different**, libraries must be taken into use using both module and class names, such as **mymodule.MyLibrary** or parent.submodule.MyLib.

Simple reproduction code:
**CustomLibrary.py**
```python
from robot.api.deco import library, keyword

@library
class Lib:
    @keyword
    def add(self, a, b):
        return a+b

def some_method(a, b):
    return a+b
```

**test.robot**
```
*** Settings ***
Library    CustomLibrary.Lib

*** Test Cases ***
Example Test
    ${result}    add   ${1}    ${2}
    Log to Console    result = ${result}
```

Both files are on the same level (for simplify demonstration purpose)
I'm getting `No keyword with name 'add' found.` error.

However changing `Library    CustomLibrary.Lib` into `Library    CustomLibrary.py` and `add` into `Some Method` works perfectly. I found [some old examples](https://www.youtube.com/watch?v=Y8pD5-SP_0c) that shows that my way should work.

Python: 3.11 64bit
Windows: 10 64bit
robotframework: 6.0.2

**Comment by pekkaklarck** [comment]
Does importing the library fail? What error do you get?

**Comment by Redysz** [comment]
>I'm getting No keyword with name 'add' found. error.

Full traceback:
```
[ ERROR ] Error in file 'C:\Users\kurekkar\PycharmProjects\private\rf\test.robot' on line 2: Importing library 'CustomLibrary.Lib' failed: ModuleNotFoundEr
ror: No module named 'CustomLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Programy\Programowanie\Python\private_venv\Scripts\robot.exe
  C:\Programy\Programowanie\Python\WPy64-38100\python-3.8.10.amd64\python38.zip
  C:\Programy\Programowanie\Python\WPy64-38100\python-3.8.10.amd64\DLLs
  C:\Programy\Programowanie\Python\WPy64-38100\python-3.8.10.amd64\lib
  C:\Programy\Programowanie\Python\WPy64-38100\python-3.8.10.amd64
  c:\programy\programowanie\python\private_venv
  c:\programy\programowanie\python\private_venv\lib\site-packages
==============================================================================
Test
==============================================================================
Example Test                                                          | FAIL |
No keyword with name 'add' found.
------------------------------------------------------------------------------
Test                                                                  | FAIL |
1 test, 0 passed, 1 failed

```

**Comment by pekkaklarck** [comment]
As the error mentions, the `CustomLibrary` module cannot be imported which means its not in the module search path. When you use `CustomLibrary.py` approach, Robot imports the library based on path and this issue doesn't occur. If you'd use just `CustomLibrary`, you'd get the same error.

**Comment by Redysz** [comment]
Yes. I don't see how I can use my class `Lib` from module `CustomLibrary`. Documentation says precisely that I should use `CustomLibrary.Lib` in my case and that way was working in the past (like in example from youtube).
Changich to `Library  CustomLibrary.py` does not solve the problem. It sees `Some Method ` then, but still does not `Add` or `Lib.Add`.

**Comment by Redysz** [comment]
So... when changing to `Library  CustomLibrary.py`:

**CustomLibrary.py**
```Python
*** Settings ***
Library    CustomLibrary.py

*** Test Cases ***
from robot.api.deco import library, keyword

@library
class Lib:
    @keyword
    def add(self, a, b):
        return a+b

def some_method(a, b):
    return a+b
```

**test.robot**
```
*** Settings ***
Library    CustomLibrary.py

*** Test Cases ***
Example Test
    ${result}    Some Method   ${1}    ${2}
    ${result}    Add   ${1}    ${2}
    Log to Console    result = ${result}
```
The consol output:
```
Test                                                                          
==============================================================================
Example Test                                                          | FAIL |
No keyword with name 'Add' found.
------------------------------------------------------------------------------
Test                                                                  | FAIL |
1 test, 0 passed, 1 failed
```

The same for Lib.Add  (`No keyword with name 'Lib.Add' found.`

**Comment by pekkaklarck** [comment]
The documentation ought to also tell that `CustomLibrary` module should be in the module search path. In your case it's not and that's why importing it faila.

**Comment by Redysz** [comment]
I was running the test with:
`robot -d results --pythonpath C:\Users\kurekkar\PycharmProjects\private\rf\ test.robot` where both tests are. I understood from the documentation that this (`pythonpath`) does the thing. Tried also `robot -d results --pythonpath . test.robot` (as I run the tests from folder where the library is).

However, after your last comment I've tried to add this path to `PYTHONPATH` (what I understood is equivalent) and that works. The class-library works with `CustomLibrary.Lib` not `CustomLibrary.py` and if I want to use both (class and normal function) I need to write:
```
Library    CustomLibrary.Lib
Library    CustomLibrary.py
```

Do you know why `--pythonpath` parameter wasn't helpful here? Can you add that info to the documentation to make it clear then? Of course if you explain me I can also do that.

**Comment by pekkaklarck** [comment]
`--pythonpath` certainly should work. The value needs to point to the directory containing the library.

If the module is in the search path, you can import it like
```
Library    CustomLibrary
```
without the `.py` extension as well.

**Comment by Redysz** [comment]
Ok, after deleting it now (from PYTHONPATH in the system) it works with `--pythonpath` with the same command that it didn't before. Probably something refreshed in the system. Closing then.
