### ISSUE TITLE
String Comparison failes when the string contains square braces []

### ISSUE THREAD

**Issue by madhuryadas** [robotframework/robotframework#4671]
Hi Team,

The string comparison fails when I compare strings containing square brackets.

Error -  does not contain match for pattern.

String - The string is -  "phy-interface [test] of type [Control] with port [1] and slot [1] has invalid name"

Keyword used - 
Should Contain Match   ${config_results}      phy-interface [test] of type [Control] with port [1] and slot [1] has invalid name

<img width="957" alt="image" src="https://user-images.githubusercontent.com/46935702/223075777-5f0a7e59-3558-4458-8ab7-8932950ba5ae.png">

Please provide an update on this

**Comment by damies13** [comment]
There is a sample robot file for reproducing this issue in this forum post:

https://forum.robotframework.org/t/string-comparison-with-list/5371/2?u=damies13

**Comment by pekkaklarck** [comment]
This keyword uses [glob patterns](https://en.wikipedia.org/wiki/Glob_(programming)) for matching and with them `[]` have a special meaning so that, for example, `[abc]` matches either `a`, `b` or `c`. If you want to have literal `[abc]` in a glob pattern, you need to escape it like `[[]abc]`.
