### ISSUE TITLE
Unable to access methods from object after it is saved in a variable

### ISSUE THREAD

**Issue by adathatri** [robotframework/robotframework#4675]
I have created a Python library with a method that returns the object self. I saved this object into a robot variable. But I am unable to access the method present in this object by using syntax `${var}.method_name`

Python library:
```
class sing():
    def __init__(self):
        pass
    def init(self):
        return self
    def name(self):
        return "hi"
```
Robot code:
```
Test
   ${val}=  Init
   Log To Console  \n${val}
   ${word}=  Run Keyword  ${val}.name
   Log To Console  ${word}
```

Result:
```
==============================================================================
Test                                                                  .
<sing.sing object at 0x7ffff06584e0>
Test                                                                  | FAIL |
No keyword with name '<sing.sing object at 0x7ffff06584e0>.name' found.
------------------------------------------------------------------------------
```

**Comment by pekkaklarck** [comment]
The syntax to access the attribute is `${val.name}`. I doubt that works as you expect in this case, though. This issue tracker is for bug reports and enhancement requests and this particular issue is more like a question. I recommend asking help on our Forum or Slack. You can find them both via robotframework.org.
