### ISSUE TITLE
Encoding issue when generating user guide in windows platform

### ISSUE THREAD

**Issue by sunday2** [robotframework/robotframework#4680]
env: 
platform: Windows 10 Pro
python: 3.7
RF: master branch

problem: when calling the script ug2html.py to generate the RF user guide, encoutered the following encoding issue, 
![image](https://user-images.githubusercontent.com/20227068/224522445-08e798de-37ba-4279-8e0f-3cfa74b00e0e.png)
this may due to this function:

`doc.userguide.translations.update`
```python
def update(path: Path, content):
    source = path.read_text(encoding='UTF-8').splitlines()
    with open(path, 'w') as file:
        write(source, file, end_marker='.. START GENERATED CONTENT')
        file.write('.. Generated by translations.py used by ug2html.py.\n')
        write(content, file)
        write(source, file, start_marker='.. END GENERATED CONTENT')
```
when calling the open function, does not specify the encoding, the default encoding will be platform dependent. In my case, the encoding cp1252 will be used, this issue happened when write the content that was Bg language and other languages will also meet this issue if cp1252 not support them.

possible solution:  
specify the encoding to be 'utf-8' when open the file.

**Comment by pekkaklarck** [comment]
Thanks for the report and the fix @sunday2. We've apparently only been running this on Linux and OSX since translations were added and haven't encountered the problem.

**Comment by sunday2** [comment]
> Thanks for the report and the fix @sunday2. We've apparently only been running this on Linux and OSX since translations were added and haven't encountered the problem.

Understood, i think most engineers like unix-like systems.
