### ISSUE TITLE
Deprecate `SHORTEST` mode being default with `FOR IN ZIP` loops

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#4685]
RF 6.1 made it possible to configure what to do if lengths of lists iterated using `FOR IN ZIP` are different (#4682). The old default behavior to silently ignore items in longer lists (i.e. `SHORTEST` mode) was preserved, but we plan to require lengths to match (i.e. `STRICT` mode) by default in the future. Before changing the default, we should deprecate the old behavior. What needs to be done is to check that list lengths are same also if mode isn't set. If lengths don't match, there should be a deprecation warning instead of a failure, though.

**Comment by MobyNL** [comment]
I worked on this in https://github.com/robotframework/robotframework/pull/4806
I also asked some questions in the #devel channel

I also added a warning in case one or more of the items to zip through has no length (as is checked for STRICT mode as well) and no mode is set. 
Those cases will also fail when default mode is changed to STRICT
