### ISSUE TITLE
[Builtin library] [ Should Contain]  argument variable chops off the content of data while finding a phrase in it

### ISSUE THREAD

**Issue by efankan** [robotframework/robotframework#4696]
i have a variable which store "ifconfig" result of a ubuntu system.  the response of ifconfig is more than 100 lines.  when i log the variable it prints all the received response correctly but when i use the keywork  `Should Contain   ${response}  'text'`  it chops of the content of `${response}` up to few lines. say 15-20.
i can see my desired text exists in the response but due to this but it fails the result because the desired text does not exist in firt 20 lines. 

it a very visible issue, i dont think i need to put any logs in here. 

my robot version is 
Robot Framework 6.0.2 (Python 3.11.0 on win32)

**Comment by pekkaklarck** [comment]
You mean the error message the test gets, right? The reason we cut them from the middle is that they can be arbitrary long and mess up logs and reports pretty badly. The whole message ought to nevertheless be visible in the log file under the failed keyword. If I understood your issue correctly, you can find a command line option that controls this behavior. If I didn't, please clarify.

**Comment by pekkaklarck** [comment]
I don't think you understood what I meant. We cut the error messages tests get because they can be overly long. It doesn't matter is the error due to ifconfig config message being compared or something else. This behavior won't change, but you can configure it yourself with a command line option.
