### ISSUE TITLE
Inconsistent parsing of strings with escape sequences when argument is converted to python dict

### ISSUE THREAD

**Issue by callumnobleintel** [robotframework/robotframework#4700]
I'm having a hard time trying to figure out how when parsing of escape sequences in strings happens

I have a variable:
```robot
*** Variables ***
${args}    {'newline': '***\\n***', 'backslash': '***\\***', 'tab': '***\\t***', 'emoji': '***\\u2603***' }
```

A simple test case:
```robot
*** Test Cases ***
Test 1 
    Test Convert    ${args}    ${args}
```

And the keyword in python:
```py
@keyword(types={'arg1': str, 'arg2': dict})
def test_convert(arg1, arg2):
    print(type(arg1)); print(arg1)
    print(type(arg2)); print(arg2)
```

The output is unexpected. I can't understand why the backslash and emoji appear the way they do when the argument is converted to a python dictionary.

```text
<class 'str'>
{'newline': '***\n***', 'backslash': '***\***', 'tab': '***\t***', 'emoji': '***\u2603***' }
<class 'dict'>
{'newline': '***\n***', 'backslash': '***\\***', 'tab': '***\t***', 'emoji': '***☃***'}
```

I can't even find a way to get a literal `\u2603` to appear in my dict at all!
`\\u2603` gives `☃`
`\\\u2603` gives `\\☃`
`\\\\u2603` gives `\\u2603`
`\\\\\u2603` also gives `\\☃`

**Comment by pekkaklarck** [comment]
It's a double escaping issue. `\` is an escape character both in Robot data and in Python. If there's Robot data that's evaluated in Python, you needed to use `'\\\\'` to get a single backslash. An alternative is using Python's raw strings like `r'\\'`.

Another thing that happens is that when you use `print(arg2)` and `arg2` is a dict, the result will show `repr` of the strings inside the dict. If you'd use `print(repr(arg1))` you'd get a `repr` also with the string argument and results ought to look more logical.

I agree this can be confusing. Have you noticed places in the User Guide where this could be explained better?
