### ISSUE TITLE
Use parallel libaray to accelerate the report generate

### ISSUE THREAD

**Issue by Superyunkai** [robotframework/robotframework#4707]
I have a project which will produce thounds xml result need to merge into a report. For some business reason, I hope the report could finish in 5 min, even 1 min.Thus, I use distributed work queue celery to acclerate . After use distributed, the total time comes to 10 min. I check the log, found that still 50% time spend in stage of merge the report, which can perform by master node by on single thread only. So I trying to use parallel technogical to make it quickly

**Comment by Superyunkai** [comment]
Any Good Idea? I try use joblib to parallelly perform the loop in  resultbuilder.py:52 __combine_results() and jsmodelbuilders.py:110.

**Comment by pekkaklarck** [comment]
Optimizing result generation would be nice but this issue is pretty vague. If you a concrete proposal, please submit a new issue explaining that and preferably also provide a pull request.
