### ISSUE TITLE
Add `__repr__()` method to NormalizedDict

### ISSUE THREAD

**Issue by Snooz82** [robotframework/robotframework#4709]
I see the problem, that with the RobotDebug REPL i am updating right now, the NormalizedDict are just shown like this:

`${SUITE_METADATA} = <robot.utils.normalizing.NormalizedDict object at 0x1048063e0>`

Could we do it like this?
```python
def __repr__(self):
    return '%s(%s)' % (self.__class__.__name__, str(self))
```
or:
```python
def __repr__(self):
    return f'{self.__class__.__name__}({self.__str__()})'
```
Then it would be :
`${SUITE_METADATA} = NormalizedDict({'Hello': 'World', 'Test': '123'})`

We could also write it like this?
`robot.utils.NormalizedDict({'Hello': 'World', 'Test': '123'})`

But i think the former version would be good enough 

What do you think?

**Comment by pekkaklarck** [comment]
Sounds good to me. We have in general added meaningful `__str__` and `__repr__` to model objects. We've typically used format `ClassName(params)` where `params` represent the object state. With the `TestSuite` structure we include the package name like `robot.running.TestSuite(params), though, but we do that to separate classes with same name under `robot.model`, `robot.running` and `robot.result`.

The code example looks good, except that `type(self).__name__` is preferred over `self.__class__.__name__` (and `str(self)` is better than `self.__str__()` unless the code is super performance critical). We've moved to f-strings where feasible, but with them them internal Python expressions can grow complicated and require extracting variables. They can also look pretty strange if the template involves lot of literal `()` and `{}`. Not an issue here, but if `NormalizedDict.__repr__` uses f-strings, also `NormalizedDict.__str__` should use them for consistency, and with that code formatting can be a bit tricky.

In addition to the new code, this will need a new unit test.

Do you @Snooz82 want to create a PR or should I do this myself? Ought to be trivial either way.
