### ISSUE TITLE
Support library keywords with both embedded and normal arguments

### ISSUE THREAD

**Issue by oianson** [robotframework/robotframework#4710]
In https://github.com/robotframework/robotframework/issues/4234 / https://github.com/robotframework/robotframework/pull/4319 support for user keywords with embedded and normal arguments was added. 

It would be useful if we could do the same for library keywords in the same manor e.g.

```python
@keyword('Number of ${animals} should be') 
def example(animals, count):
    ...
```

```
Number of horses should be    2
Number of horses should be    count=2
Number of dogs should be    3

**Comment by pekkaklarck** [comment]
I guess this would be handy but let's first see how user keywords with both kind of arguments work. Implementing this is likely a bit more complicated than it was with user keywords, but shouldn't be overly complicated anyway. I cannot make promises when the core team would have time to implement this, but if some is interested to look at this, I'm happy to help and review PRs.

One thing to decide is how to handle this kind of usage:

    Number of dogs should be    animals=horses    count=2

I believe it should be an error.

**Comment by oianson** [comment]
I would agree that should give an error.

**Comment by peerasut** [comment]
This would be great for my work! I'd like to look into this if you could suggest where to enhance this feature.

**Comment by pekkaklarck** [comment]
There's clear demand for this. Let's try to get it implemented in RF 7.

**Comment by pekkaklarck** [comment]
I've been prototyping this and got the basic implementation ready. Unfortunately there were some tests related to handling `@{list}` and `&{dict}` variables that failed, and after closer inspection they seem to be related to #4364.I tried to fix them, but even a partial fix is rather complicated and fixing this properly would probably require either a large rewrite or some ugly hacks. A much simpler solution would be simply disallowing usages like
