### ISSUE TITLE
__init__.txt not being read but __init__.robot works fine

### ISSUE THREAD

**Issue by digoo** [robotframework/robotframework#4713]
Hello!

I'm returning to robot from a long pause and my old project stopped working in a specific location.

I have few calls in the Suite setup from a ComponentTestSuite and executing the test now I realized that the data there are not being loaded, resulting in a failure in a call inside the test.

I was able to debug and investigate what happened. 
Before my code was using __init__ file with the txt extension format. I have now changed the format to use the robot extension format and doing that managed to fix my test.

RIDE allowed me to create the init file with the txt extension and still does allow (v.2).

Just fyi, before I was executing Python 2.7 with robot 2.8.7 release version , now it's Python 3.10+ with robot 6.0.2 release version.

Below a sketch of the issue.
```
tests/
-- ComponentTestSuite
    |-- __init__.txt            <- Contains Suite Setup (Not being executed)
    |-- TestSuite.robot          <- Contains Suite Setup (Being executed)
    |   |-- TestCase-1
    |   `-- TestCase-2
```

With the fix:
```
tests/
-- ComponentTestSuite
    |-- __init__.robot            <- Contains Suite Setup (being executed)
    |-- TestSuite.robot          <- Contains Suite Setup (Being executed)
    |   |-- TestCase-1
    |   `-- TestCase-2
```

What I was expecting to happen and the reason I'm opening this issue:

I believe robot framework should be able to read __init__.txt files as it reads __init__.robot files.

**Comment by pekkaklarck** [comment]
The change to only parse `*.robot` files is by design. See #3084 for more information and for instructions how to enable using the `*.txt` extension.
