### ISSUE TITLE
support singleton library class instance

### ISSUE THREAD

**Issue by rock0528** [robotframework/robotframework#4731]
singleton library class instance keeps the consistent context for the keywords dependent with other keywords.
for example
it doesn't work without the context
```
from robot.libraries.Process import Process

handle = Process().start_process('python', '-c', 'print("hello")')
result = Process().wait_for_process(handle=handle, timeout='1min')
```
but it works
```
from robot.libraries.Process import Process

process = Process()
handle = process.start_process('python', '-c', 'print("hello")')
result = process.wait_for_process(handle=handle, timeout='1min')
```

**Comment by pekkaklarck** [comment]
Robot libraries have scope that they can control themselves. That affects how often Robot creates instances of them. I see no point in making libraries themselves singletons, especially when it's virtually impossible in Python and generally considered a bad practice. If you want to preserve object state, just create one instance.
