### ISSUE TITLE
Is there a robot code hub？

### ISSUE THREAD

**Issue by hrz394943230** [robotframework/robotframework#4733]
I want to train a model which can generate .robot code automatically.
So I need a mount of high quality .robot code dataset,Is there a robot code hub？or how can I get this kind of dataset?

**Comment by pekkaklarck** [comment]
I'm not aware of any repository containing just Robot Framework tests. We have MarketSquare, but that's mostly for tools/and libraries in the ecosystem. They most likely have some Robot tests as well, but they may be pretty low level and not good as examples. In general I believe that the majority of Robot tests are in private repositories.

This issue tracker is for bug reports and enhancement requests. I recommend asking this from the community on our Slack and/or Forum.
