### ISSUE TITLE
'Parse Xml ' failed by checking whether xml path or not if the XML download from Web which usually contain file header.

### ISSUE THREAD

**Issue by Jessie-sunny** [robotframework/robotframework#4741]
1. The XML file is downloaded from the web, the XML source  which usually contain the file header such as 
xml_source_str = `ZWNBSP   <?xml version="1.0" encoding="utf-8"?>`
xml_source_byte= `b'\xef\xbb\xbf   <?xml version="1.0" encoding="utf-8"?>`

2. Invoke the keyword: Parse Xml and 'source' is a xml string, error.
${element1} =  Parse Xml  ${xml_source_str}
${element2} =  Parse Xml  ${xml_source_byte}

The root cause is the method: **_is_path()** in the **etreewrapper.py**,  `source.lstrip().startswith(prefix)` is not a good way to check is a XML path or not.
As below:
    def _is_path(self, source):
        if is_pathlike(source):
            return True
        elif is_string(source):
            prefix = '<'
        elif is_bytes(source):
            prefix = b'<'
        else:
            return False
        return not **source.lstrip().startswith(prefix)**

**Comment by pekkaklarck** [comment]
Do I get it right that the "header" is a byte-order mark, not a MIME header or something like that? I agree a BOM shouldn't affect parsing.

When submitting issues, please make sure that formatting looks good. The code example above is currently somewhat messed up. You can edit the description by clicking the `...` in the top left corner and selecting `Edit`. The edit box has a link to formatting instructions, but you can find them here as well:
