### ISSUE TITLE
MFA from Microsoft

### ISSUE THREAD

**Issue by matheusbarcelos** [robotframework/robotframework#4742]
I need to develop the login in a test automation, where there is authentication in the second factor (oauth2) from Microsoft(Microsoft Authenticator).

I searched in several places, I didn't find any documentation or examples about oauth2.

Kindly, has anyone ever needed to implement something similar? Any libraries to recommend?

**Comment by pekkaklarck** [comment]
I have no idea. This issue tracker is for bug reports and enhancement requests and questions should be asked on our Slack, Forum, or other such support channel.
