### ISSUE TITLE
Report the correct status of the test in the console output

### ISSUE THREAD

**Issue by nicolasbillamboz-flowbird** [robotframework/robotframework#4755]
When we use the tags `robot:exclude` and `robot:skip-on-failure` on tests, the console output gives the test as PASSED, instead of EXCLUDED or SKIPPED. This provides misleading information about the real status of the test execution.
For instance: `2023-05-04 04:58:36.220473 [PID:240] [0] [ID:34] PASSED MyTest in 4.9 seconds`
The status of the test is obviously correct in the `log.html` or `report.html`, but having the good status in the console output is interesting, when we have long runs on CI, and we want a quick feedback about specific tests by reading the console output during the execution.

Robot Framework Version: 6.0.2

**Comment by pekkaklarck** [comment]
Cannot reproduce.

```robotframework
*** Test Cases ***
Exclude
    [Tags]    robot:exclude
    Fail   Message

Skip-on-failure
    [Tags]    robot:skip-on-failure
    Fail   Message
```

```
==============================================================================
Example                                                                          
==============================================================================
Skip-on-failure                                                       | SKIP |
Test failed but skip-on-failure mode was active and it was marked skipped.

Original failure:
Message
------------------------------------------------------------------------------
Example                                                               | SKIP |
1 test, 0 passed, 0 failed, 1 skipped
==============================================================================
```

**Comment by nicolasbillamboz-flowbird** [comment]
Sorry, my bad. Actually I get this output when using pabot. The issue is probably related to it.

**Comment by pekkaklarck** [comment]
Ok. Please report the issue to Pabot's tracker. If there's a need this issue can be reopened.
