### ISSUE TITLE
Combine optional `msg` and `values` arguments of comparison keyword of BuiltIn library

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#476]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=476) by @yanne on 24 Feb 2010*

Many if the BuiltIn library keywords that assert equality or unequality
take two optional arguments which define optional error message and whether
the values should be shown or not. These could be combined so that if the
error message ends with e.g. ':', values are shown, otherwise not.

**Comment by pekkaklarck** [comment]
This ship has sailed. Changing the signature of these very widely used keywords would require long deprecation period and lot of work updating tests. That's not worth the effort. Specifying are values needed will anyway be easier in RF 2.9 when Boolean argument handling is standardized (#2038).
