### ISSUE TITLE
Unresolved library: CourseService.modules.courseServiceAPIHelper. Error generating libspec: Importing library 'CourseService.modules.courseServiceAPIHelper' failed: ModuleNotFoundError: No module named 'CourseService' Consider adding the needed paths to the "robot.pythonpath" setting and calling the "Robot Framework: Clear caches and restart" action.

### ISSUE THREAD

**Issue by vinayakvardhan** [robotframework/robotframework#4762]
Hi I am getting this error in my robot class:
Unresolved library: CourseService.modules.courseServiceAPIHelper. Error generating libspec: Importing library 'CourseService.modules.courseServiceAPIHelper' failed: ModuleNotFoundError: No module named 'CourseService' Consider adding the needed paths to the "robot.pythonpath" setting and calling the "Robot Framework: Clear caches and restart" action.

**Comment by pekkaklarck** [comment]
This seems to be an IDE configuration issues, not a bug in Robot Framework. If you cannot get the issue resolved, you can try asking help on our Slack or other support forums listed at robotframework.org. This tracker is only for bug reports and enhancement requests related to Robot Framework itself.
