### ISSUE TITLE
Methods in the Listener API 2 doesn't work when generating output

### ISSUE THREAD

**Issue by brianle19** [robotframework/robotframework#4768]
I want to handle 3 output files: output.xml, log.html, report.html and upload them to JIRA as execution evidence by using Robot listener version 2. But it doesn't seem to work with provided methods such as: output_file, log_file, report_file from RobotFramework documentation. Below is my implementation

MyCustomListener

`    
   ROBOT_LISTENER_API_VERSION = 2

    def __init__(self):
        self.ROBOT_LIBRARY_LISTENER = self 

    def output_file(self, path):
        arr = os.listdir(self.log_directory)
        print("Output called: " + str(arr))

    def log_file(self, path):
        arr = os.listdir(self.log_directory)
        print("Log called: " + str(arr))

    def report_file(self, path):
        arr = os.listdir(self.log_directory)
        print("Report called: " + str(arr))

    def close(self):
        arr = os.listdir(self.log_directory)
        print("List files: " + str(arr))`
        

Running test with command line, pass -d tmp for output directory

`robot -d tmp ..\test_sample_demo.robot`

Terminal logs:
Only close() method is triggered, but only output.xml is generated with empty data:
![Screenshot 2023-05-16 162225](https://github.com/robotframework/robotframework/assets/21083736/def42cd9-3b3e-4bd8-b197-32ba78d5e86e)

Ref: http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#listener-version-2
Python: 3.9

**Comment by pekkaklarck** [comment]
Based on your code you are using a library listener. As the [documentation explains](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#called-listener-methods), `xxx_file` methods aren't called with them. `close` is called when the library goes out of scope, but the execution hasn't finished then. That means there's no log or report and output.xml is not complete. It's probably easiest to implement this using a regular listener you register from the command line.
