### ISSUE TITLE
Ability to override dictionary variable items

### ISSUE THREAD

**Issue by oboehmer** [robotframework/robotframework#4776]
We have a use case where we load a large dictionary into a test suite (using `Variables   defaults.yaml`), and we want to give the user an ability to overwrite specific keys/values within the dictionary. 

Ex: `defaults.yaml` would contain something like the below (in practice this file defines several hundred of values in the dict):
 
```
defaults:
  var1: 1
  subvar1:
    var2: 2
```

The ask for our use case is to **overwrite** specific values (rather than to augment the dict), i.e. through something like

`robot --variable defaults.subvar1.var2:999 testsuite.robot` 

to set `${defaults}[subvar1][var2]` to `999`? 

I understand that this could be problematic as I would not know how to handle such a overwriting behaviour using `--variablefile` as we DO want to retain the ability to overwrite the complete `defaults` top-level dict using `--variablefile`, so we would have a somewhat inconsistent behaviour?

**Comment by pekkaklarck** [comment]
This looks too complicated to me. I believe you should handle this in your variable files somehow. Possibly you could use a dynamic Python variable file that makes the needed adjustments. Or perhaps you can use the `*reference` syntax supported by YAML itself.
