### ISSUE TITLE
The Parser between a feature files and the corresponding step definition is not working smoothly when the " (double quotation mark) is present

### ISSUE THREAD

**Issue by OswaldGitHub** [robotframework/robotframework#4785]
**VERSION INFORMATION**

Robot framework version: Robot Framework 5.0 (Python 3.10.4 on win32)
Python version: Python 3.10.4
OS: Windows 10

**THE PROBLEM**
If 2 step definitions that use " character have similar definition the parser take both as identical.

2 steps definitions
![image](https://github.com/robotframework/robotframework/assets/48608466/f2507074-8263-4f34-bdb8-ea20c8855df1)

The step definition invoked inside a feature file
![image](https://github.com/robotframework/robotframework/assets/48608466/08c2a50f-c916-454e-8af1-c3be12521234)

The message error
![image](https://github.com/robotframework/robotframework/assets/48608466/0c924b7c-a144-478d-a255-a42c350bb2e6)

**CONCLUSION**
We are thinking the " character sometimes is causing confusing during the parser about which text is limited by the double quotation marks.

The possible behavior highlighting how the parser might it be taking the steps definitions
![image](https://github.com/robotframework/robotframework/assets/48608466/e3ba9f60-1fa0-47fd-80f2-b0fabdf3d4f8)

**Comment by pekkaklarck** [comment]
No updates. Closing.
