### ISSUE TITLE
Robot 6.1rc1: Listener errors?

### ISSUE THREAD

**Issue by pianofab** [robotframework/robotframework#4786]
We have an internal application that uses Robot Framework 6.0.2 and I was trying to test it with 6.1rc1 to ensure that everything still works. It looked OK but then I realized that the live feedback was missing, and then I went to the log and found this:

<html>
<body>
<h2 style="clear: left; color: rgb(0, 0, 0); font-family: Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Test Execution Errors</h2>

20230607 10:36:36.972 | ERROR | Calling method 'start_suite' of listener 'RobotListener' failed: AttributeError: Protocol message SuiteResultsObject has no "_setter__suites" field. |  
-- | -- | -- | --
20230607 10:36:36.974 | ERROR | Calling method 'start_suite' of listener 'RobotListener' failed: AttributeError: Protocol message SuiteResultsObject has no "_setter__suites" field. |  
20230607 10:36:36.976 | ERROR | Calling method 'start_suite' of listener 'RobotListener' failed: AttributeError: Protocol message SuiteResultsObject has no "_setter__suites" field. |  
20230607 10:36:36.987 | ERROR | Calling method 'start_suite' of listener 'RobotListener' failed: AttributeError: Protocol message SuiteResultsObject has no "_setter__suites" field. |  
20230607 10:36:36.988 | ERROR | Calling method 'start_test' of listener 'RobotListener' failed: AttributeError: Protocol message TestResultsObject has no "_setter__body" field. |  
20230607 10:36:36.990 | ERROR | Calling method 'end_test' of listener 'RobotListener' failed: AttributeError: Protocol message TestResultsObject has no "_setter__body" field. |  
20230607 10:36:36.991 | ERROR | Calling method 'start_test' of listener 'RobotListener' failed: AttributeError: Protocol message TestResultsObject has no "_setter__body" field. |  
20230607 10:36:36.996 | ERROR | Calling method 'end_test' of listener 'RobotListener' failed: AttributeError: Protocol message TestResultsObject has no "_setter__body" field. |  
20230607 10:36:36.998 | ERROR | Calling method 'end_suite' of listener 'RobotListener' failed: AttributeError: Protocol message SuiteResultsObject has no "_setter__suites" field. |  
20230607 10:36:36.999 | ERROR | Calling method 'end_suite' of listener 'RobotListener' failed: AttributeError: Protocol message SuiteResultsObject has no "_setter__suites" field. |  
20230607 10:36:37.000 | ERROR | Calling method 'end_suite' of listener 'RobotListener' failed: AttributeError: Protocol message SuiteResultsObject has no "_setter__suites" field. |  
20230607 10:36:37.001 | ERROR | Calling method 'end_suite' of listener 'RobotListener' failed: AttributeError: Protocol message SuiteResultsObject has no "_setter__suites" field.

</body>
</html>

Now, I noticed that in my listener I have used type hints to clarify what is going on:

```python
class RobotListener():
    """Standard Robot Listener to intercept Robot events live.
https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#listener-interface
https://github.com/robotframework/robotframework/blob/master/doc/userguide/src/ExtendingRobotFramework/ListenerInterface.rst

    Raises:
        KeyboardInterrupt: awkward attempt at stopping Robot run.
    """
    ROBOT_LISTENER_API_VERSION = 3

    def __init__(self,
                 robot_queue: RobotMsgQueue,
                 stop_event: MP_Event,
                 maxmsglen: int):
# etc

    def start_suite(self,
                    suite: _running.model.TestSuite,
                    result: _result.model.TestSuite):
        """Robot hook

        Args:
            suite (_running.model.TestSuite): input suite
            result (_result.model.TestSuite): input result
        """

```
Could that be the issue?

**Comment by pianofab** [comment]
I found the issue. There was no stack trace, and I remembered that there was a way to get more info, and sure enough: ROBOT_SYSLOG_FILE=robot_syslog.txt gave the stack trace. There has been a subtle API change that is causing the result object to be immutable and I am calling setattr() on the result object from within the listener. Will look for a workaround.

**Comment by pekkaklarck** [comment]
First is all, thanks for testing the rc!

If I got it right, the error comes from `setattr()` that is setting an attribute to `SuiteResultsObject`. Is there any chance that this object would have been changed? For example, if it had got `__slots__` there would be an `AttributeError` like this.

**Comment by pekkaklarck** [comment]
Copying whatever is in `result.__slots__` feels somewhat risky in general. It would be safer to explicitly list attributes you want to copy.

**Comment by pianofab** [comment]
> Copying whatever is in `result.__slots__` feels somewhat risky in general. It would be safer to explicitly list attributes you want to copy.

Yes, but I do not mind because my objects are closely mirroring yours, and if you add new useful items to your Robot object, I would like to know about it so that I can add support for the new feature (or not). I should probably skip anything that starts with an underscore though... like these new items which are clearly internal use only.
Thanks for your quick feedback. I am going to close since I do not consider this a problem.

**Comment by pianofab** [comment]
To clarify: adding the following code (which skips the new item) makes the issue go away:
```python
_theslots.remove('_setter__suites')
```
