### ISSUE TITLE
Add Vietnamese translation 

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#4792]
We added translation infrastructure and as well as translations for various languages in RF 6.0 (#4390). We now have PR #4791 adding Vietnamese translation.

**Comment by pekkaklarck** [comment]
Thanks Hưng Trịnh for the actual translation and @leeuwe for creating the PR.

**Comment by leeuwe** [comment]
Confirming that [Hưng Trịnh](https://github.com/hungtrinh) made these translations available. Thanks again @hungtrinh!
