### ISSUE TITLE
Unable to add new line at the end of the test case name being printed during execution

### ISSUE THREAD

**Issue by eduvfalc** [robotframework/robotframework#4794]
I have been facing a scenario in which I want to be able to have clean logs in the console, each of which filling its own line. During a test execution, I notice that the Robot Framework prints the test case name when it is going to execute that particular test but it looks like a new line is not being appended after it. This results in any logs being printed right after the test case name also occupying the same line. Would it be possible to print the test case name and append a new line at the end?

**Comment by pekkaklarck** [comment]
The default console output certainly could be enhanced, but I don't think just adding a newline after the test name is a good idea because it makes output a lot longer. Good news is that you can disable the output with `--quiet` and create a custom output using a listener.
