### ISSUE TITLE
task : add the possibility to log timestamp (start/ end /elapsed) of every keyword 

### ISSUE THREAD

**Issue by saifjarboui** [robotframework/robotframework#4797]
Hi,
is there a possibility to add the (start/ end /elapsed) time of every executed keyword (green/red) in the log.html
 even it does not have logging or printing 
![image](https://github.com/robotframework/robotframework/assets/73231863/e317b3e1-1fba-4eab-8038-b6b8009e6713)
this example here **Should Start With** do not have any timestamp (tho it is obvious to tell the time, but with accumulation you can lose track on the time)

**Comment by MobyNL** [comment]
![image](https://github.com/robotframework/robotframework/assets/59473010/cb3b9090-2af5-439c-9cbe-ba75693c000e)
What version are you one? I don't think have any special settings or whatever, and I can see Start/End/Elapsed

**Comment by pekkaklarck** [comment]
Yeah, this information is there already.
