### ISSUE TITLE
`--removekeywords passed` doesn't remove test setup and teardown

### ISSUE THREAD

**Issue by ghost** [robotframework/robotframework#4798]
I'm using the following commands `rebot --removekeywords passed --output removed.xml output.xml`.
**Robotframework** and **Rebot** version is `6.1`

- It's work for `Suite Setup` and `Suite Teardown` but it's doesn't work in `Test Setup` and `Test Teardown`

![Capture](https://github.com/robotframework/robotframework/assets/90506821/2e9555e9-53d1-4399-8ffc-716f4c12a879)

**Comment by pekkaklarck** [comment]
Thanks for the report. I had missed this earlier, but it's so easy to fix that I can still do that in RF 7.0.
