### ISSUE TITLE
Update Polish translations to use title case

### ISSUE THREAD

**Issue by mnojek** [robotframework/robotframework#4800]
English (original) variants of headers and settings follow a title case format, where each word starts with a capital letter, and all the next that follow are lowercase. I noticed that this rule does not apply to the localized variants, e.g. `Test Timeout` in Polish is `Limit czasowy testu`, while I think it should be `Limit Czasowy Testu`.

Although I know (I guess?) this is not strictly indicated anywhere in the User Guide, the translated versions should follow the same rule for consistency.

When working with RF in VS Code with Robocop linting enabled, if I use autocomplete for the settings, I immediately end up with a Robocop rule violation W0306 (`setting-name-not-in-title-case`), and I need to fix the case on my own, which is unfortunate:

<img width="563" alt="image" src="https://github.com/robotframework/robotframework/assets/7412964/3f02cd3b-42ed-4eff-87e0-a3c3ab266a78">

I think all translated headers and settings should follow the title case, as it was originally implemented with English variants.

**Comment by mnojek** [comment]
One more question... Isn't it overlooked that there is no translation for `Default Tags` and `Force Tags`?
I know they are deprecated, but they are currently not recognized at all in languages other than English. I think they should be translated until it is removed completely from RF.

**Comment by pekkaklarck** [comment]
If I remember correctly, we discussed this during RF 6.0 development, but the problem was that title case isn't appropriate with all languages and thus we decided to use whatever format translators consider best. Was it @HelioGuilherme66 you who brought that up? Do you @leeuwe remember this?

Even if converting all languages to title case wouldn't be a good idea, we certainly can do that with languages where it is fine and probably should also recommend it as the default. For example, I can merge the above PR updating Polish translations. These markers are case-insensitive for Robot, so we can change the case even in RF 6.1.1.

**Comment by pekkaklarck** [comment]
It was an explicit decision not to support translating `Default Tags` and `Force Tags`. They are going away anyway and especially `Force Tags` would have been complicated to translate with many languages. The primary reason we introduced `Test Tags` in RF 6.0 was to ease translations.

I can see the point in supporting also `Default Tags` and `Force Tags` translation and if we were still developing RF 6.0 and collecting initial translations we could consider that. I don't think spending any effort for that makes sense anymore, though. It wouldn't be too hard to support them, but I doubt we'd get too many translations before they are deprecated and removed. We didn't get that many translations for the new `Name` setting either.

**Comment by HelioGuilherme66** [comment]
@mnojek I don't know how can you enforce some rule for this. I find several examples where articles should not be capitalized (in persons names). But in the case of Robot content, it is a small set of phrases, maybe you can have rules per language.

Here are some examples of non-capitalized names:
```
Ludwig van Beethoven
Leonardo di Ser Piero da Vinci
Hélio do Carmo Guilherme
```

**Comment by mnojek** [comment]
> @HelioGuilherme66 Does the meaning of the phrase change when you title case `Casos de Teste` or is it just grammatically incorrect (which is also with `Test Cases`?

@leeuwe That's a valid point. I was thinking about this regarding different languages. For example, in German all nouns are written capitalized. Probably there are some rules in other languages which may require to write some words using lowercase. In Polish it doesn't matter that much, since it's a name of the setting and it may be capitalized.

@HelioGuilherme66 In Robocop we have a rule 0302 `wrong-case-in-keyword-name` which by default checks if the keyword name has each word capitalized, but it may be configured to only first word capitalized. The default configuration causes a violation for most of the translated settings.
I get the point that there are cases where it's hard to enforce having all words capitalized, so probably we shouldn't do it, but in any other cases where it is allowed, I would say we should go with it for consistency. 

@pekkaklarck I totally get that there is not much value in translating something that is going to be deprecated soon, and I agree with that decision.

**Comment by HelioGuilherme66** [comment]
@leeuwe `Casos De Teste` is grammatically incorrect, but the meaning remains understandable. Whereas `Casos Teste` seems incorrect (it is incomplete).

@mnojek  About your rule:
>which by default checks if the keyword name has each word capitalized, but it may be configured to only first word capitalized. 
Maybe you could have another option, a more relaxed rule, to ignore words of size 1-3, not when first word (for "articles").
Or, consider a rule dependent on the language setting.

En - `Test Case For Testing And Validation` => `Test Case for Testing and Validation` 
Pt - `Caso De Teste Para Testar E Validar` => `Caso de Teste para Testar e Validar`  ---- Oh, look the verb `para` is `to` so the rule would need to consider 1-4 characters.

**Comment by mnojek** [comment]
When talking about Robocop rules, I would go with simplicity most of the time. So having a rule that depends on language or ignore 1-3 letter-long words is not something I would introduce. That's why we have `each-word-capitalized` and `first-word-capitalized`. But, having a list of the words that will be ignored when this rule is doing its job is not a bad idea. We can add a configurable list of words for this rule.

Anyway, as for the original PR, I think for Polish translation it would be fine if it goes with each word capitalized, and for the rest of the translations it's up to the translators. I agree that it should probably not be enforced for all the languages.

**Comment by leeuwe** [comment]
@mnojek Would you like me to take up capitalizing or will you be providing it yourself?

**Comment by mnojek** [comment]
@leeuwe There's a PR #4801 linked to this issue that changes that. @pekkaklarck @leeuwe Please review :)

Should I also update it on Crowdin?

**Comment by leeuwe** [comment]
Yes please also update crowding too

**Comment by pekkaklarck** [comment]
The consensus seems to be that
- it's not a good idea to force translations to use title case,
- each translator can choose the appropriate format, and
- with Polish title cases works fine and #4801 should be merged.

I'll update the title of this issue accordingly and merge #4801. Not enforcing title case makes things a bit more complicated for external tools, but that shouldn't be too big a problem.
