### ISSUE TITLE
__init__ called twice for Dynamic library with SUITE scope

### ISSUE THREAD

**Issue by WisniewskiP** [robotframework/robotframework#4805]
I have prepared library that is allocating resources in constructor.
When I start the suite resources are allocated twice.

Short example that shows the behavior:
Test file:
```robot
*** Settings ***
Library  test_lib.py

*** Test Cases ***
test
    test keyword
```

test_lib:
```python
from robot.api import logger

class test_lib:
    ROBOT_LIBRARY_SCOPE = 'SUITE'
    ROBOT_LISTENER_API_VERSION = 3

    def __init__(self):
        self.ROBOT_LIBRARY_LISTENER = self
        logger.console(f"__init__: {self}", stream="stderr")

    def _close(self):
        logger.console(f"_close: {self}", stream="stderr")

    def run_keyword(self, name, args, kwargs):
        logger.console(f"run_keyword {self}: {name}", stream="stderr")

    def get_keyword_names(self):
        logger.console(f"get_keyword_names {self}", stream="stderr")
        return ["test_keyword"]
```

output on stderr:
```
__init__: <test_lib.test_lib object at 0x0000020EC1CBC4F0>
get_keyword_names <test_lib.test_lib object at 0x0000020EC1CBC4F0>
__init__: <test_lib.test_lib object at 0x0000020EC1CBCEB0>
run_keyword <test_lib.test_lib object at 0x0000020EC1CBCEB0>: test_keyword
_close: <test_lib.test_lib object at 0x0000020EC1CBCEB0>
```

the first instance is used only to get_keyword_names, second is used in test run.
How can I cleanup the first instance? Is there any callback that I can use?
in current implementation I'm using _close for this but it is not called for the first instance.

**Comment by pekkaklarck** [comment]
Whenever Robot imports a library, it needs to figure out what keywords it contains and that requires initializing it. With libraries having the global scope, Robot uses that initial instance also during execution, but with suite and test scopes it needs to create new instances whenever new suites and tests, respectively, start. I don't think there's much we can do to this.

If you want your library to be instantiated exactly once, you need to give it the global scope. If you want its state to be cleared between suites, you can make it a listener, like you've already done, and implement `start/end_suite` methods.
