### ISSUE TITLE
Robot Framework gets stuck after writing reports when used together with AutoRecorder and Filehandling promises

### ISSUE THREAD

**Issue by lasselindqvist** [robotframework/robotframework#4814]
(Originally from https://github.com/MarketSquare/robotframework-browser/issues/2864)

**Describe the bug**
Robot Framework gets stuck after writing reports when used together with AutoRecorder (https://github.com/sebastianciupinski/robotframework-autorecorder) and file handling promises.
I have managed to reproduce this with both Firefox and Chrome, so it does not seem to be dependent on any specific browser.

**To Reproduce**
Have resources file:
```
*** Settings ***
Library     AutoRecorder

```
and a test file

```
*** Settings ***
Library    Browser
Resource   ${CURDIR}/resources.robot

*** Test Cases ***
Promisetest
    New Browser     firefox    headless=False
    New Context     ignoreHTTPSErrors=True    acceptDownloads=True
    New Page    https://google.com

    ${dl_promise}        Promise To Wait For Download    filename.txt
    Wait For     ${dl_promise}      timeout=3

Promisetest2
    New Browser     firefox    headless=False
    New Context     ignoreHTTPSErrors=True    acceptDownloads=True
    New Page    https://google.com
    ${dl_promise}        Promise To Wait For Download    filename.txt
    Wait For     ${dl_promise}      timeout=3
```

Execute all tests:
`python -m robot .`

This only happens when you execute multiple tests. It does not matter if the other tests immediately skip the test execution by having a Skip statement in them.
Now if you move the AutoRecorder import away from the resource file and directly into the test file this does not happen.
Also if you remove AutoRecorder import or Promise To Wait For Download it also does not get stuck.
In this example there is not file to actually download, but the same problem happens even if the file was properly downloaded.
This happens for both file download and upload promises.

**Expected behavior**
The Robot test execution ends properly.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows/Linux
 - Browser: Chrome/Firefox

**Additional context**
I am not sure if this is a problem with Robot framework itself, browser library or Autorecorder. But I think the framework itself.

**Comment by lasselindqvist** [comment]
I can recheck the mode=suite, but the Wait For does not need to be the last keyword of the test. Whatever is put after those is run normally. It is only after the tests are run and report files created that the Robot framework gets stuck.

The weirdest thing is that it only happened when AutoRecorder is added via Resources and not directly.

**Comment by pekkaklarck** [comment]
Sounds like some process would be left running on background. I don't think Root itself is responsible on that nor do I have ideas how it could resolve the situation. If I'm wrong and we can change Robot to avoid or fix the situation let us know.

**Comment by pekkaklarck** [comment]
No new info. Closing.

**Comment by lasselindqvist** [comment]
I did some debugging/logging for this and using

`--loglevel DEBUG --debugfile debugfile.txt`

does print debug log and the last statement is

```
==============================================================================
20241003 11:59:18.221 - INFO - + END SUITE: MySuite (118089)
==============================================================================

```

and it stalls after that. syslog file contains
```

20241003 12:15:12.776 | INFO  | Tests execution ended. Statistics:
4 tests, 4 passed, 0 failed
20241003 12:15:13.299 | INFO  | Log: C:\Users\***\robot\log.html
20241003 12:15:13.407 | INFO  | Report: C:\Users\***\robot\report.html
```

at the end.

Running with python -m trace with some ignores, the end is:

```
template.py(63):             for item in file:
template.py(64):                 yield item.rstrip()
 --- modulename: template, funcname: __iter__
template.py(63):             for item in file:
template.py(62):         with path.open(encoding='UTF-8') as file:
Report:  C:\Users\***\report.html
```

I cannot really get more information yet, since pystack does not work on Windows, but maybe later I could reproduce this on Linux as it does happen in our CI which runs on Linux.
