### ISSUE TITLE
TRY/CATCH fails

### ISSUE THREAD

**Issue by erikapapp** [robotframework/robotframework#4817]
Hi, 

I am using rpaframework==16.3.0 and the following coda fails with the error: [FAIL] Evaluating IF condition failed: Evaluating expression ' == 2023-12-31' failed: SyntaxError: invalid syntax (<string>, line 1)

Is it by design that EXCEPT does not catch syntax errors?

```
TRY
        ${x} =   Set Variable    ${EMPTY}     
        IF    ${x} == 2023-12-31
            Log   End       
        END
        
EXCEPT    AS    ${ERROR_DETAIL}
        Log   ${ERROR_DETAIL}
END
```

Thank you

**Comment by KannappanChida** [comment]
Hi @erikapapp , as variable ${x} is empty, it results in DataError while evaluating this invalid expression (  == "2023-12-31" ) , DataErrors are not caught with Try/Except blocks and stops the execution flow.

If you want to evaluate the empty string with value , try using double quotes enclosing the variable, below IF condition gets properly evaluated.

*** Keywords ***
execute-test
    TRY
        ${x} =   Set Variable    ${EMPTY}
        IF    "${x}" == "2023-12-31"
            Log To Console   End
        ELSE
            Log To Console  <<< x is empty >>>
        END
    EXCEPT    AS    ${ERROR_DETAIL}
            Log   ${ERROR_DETAIL}
    END

**Comment by pekkaklarck** [comment]
This behavior was changed already in RF 6.0 (#4348).
