### ISSUE TITLE
Get Cookies from Network tab --> Cookies Tab

### ISSUE THREAD

**Issue by erikapapp** [robotframework/robotframework#4818]
Hi, 

The Get Cookies gets information from Chrome Application tab: 
![image](https://github.com/robotframework/robotframework/assets/86724995/852227fc-c01b-44bc-82e0-b7101f9b6fe5)

If there is an API request that uses cookies with not the default / path, how can I get those cookies information, from the Newtork Tab --> Cookies Tab
![image](https://github.com/robotframework/robotframework/assets/86724995/36423b03-5a5f-4491-bf86-f62ead689aaf)

Thank you.

**Comment by Snooz82** [comment]
Hi @erikapapp,

This question maybe related to a library like SeleniumLibrary, or Robot Framework Browser.
But it is not related to Robot Framework itself.

You may want to ask this in one of our community channels:
https://robotframework.org/#community
