### ISSUE TITLE
Pass test data structure object directly to TestSuite.run()

### ISSUE THREAD

**Issue by luv-deluxe** [robotframework/robotframework#4824]
Currently, one can substitute RF suite variables programmatically by sending it as list of strings:

`run(variable=["varname:value", "foo:bar")`, what seems to be working with scalar types only. 

For list/dict type variables, so it is better to dump it to JSON/YAML and pass as `variablefile` argument.
However, if one generates variables as a `dict` type, it is required to dump it to a file first, and then pass source path `variablefile=source.yml`. This reads vars and passes it to VariablesStore()` object.

Proposal is to add extra argument, e.g. `run(variablesdata)` as:
1. `Optional[dict]`: data in pass as a regular dictionary  `variabledata={var:value, var2:[1,2,3]}`  
2. `Optional[str]`: requires serialized dict, e.g. using `variabledata=json.dumps({})`

What is the gain here? For systems generating lots of list/dict test data dynamically, it would remove the need of intermediate file saving.
Programmatically, one generates data, loads ROBOT as model and passes it as `model.run(variablesdata=data)` - clean and easy.

Effort-wise, does not seem to be complicated, since `variablefile`, e.g. YAML, is loaded to dictionary anyway - so `variabledata` skipps file loading part - would load `dict` directly to `VariableStore()`.

**Comment by pekkaklarck** [comment]
Do I get it right that you want to pass variables as actual objects, not only as strings, to `TestSuite.run()`? The issue title talks about "test data structure" so I'm a bit confused.

**Comment by pekkaklarck** [comment]
Instead of adding a new argument, I think we could change how the existing `variable` argument is handled. We could make it so that in addition to specifying variables as a string like `'name:value'`, you could use tuples like `('name', 'value')` which would then allow also non-string values like `('example', 42)`. We've used similar approach elsewhere and it has worked well.

**Comment by pekkaklarck** [comment]
No updates, closing.
