### ISSUE TITLE
What about adding support of !import to yaml variables

### ISSUE THREAD

**Issue by sebastianciupinski** [robotframework/robotframework#4827]
By default yaml does not have any include statement and RF YamlImporter class loader does not support it neither, however adding import can be simply added:

https://gist.github.com/joshbode/569627ced3076931b02f

**Comment by pekkaklarck** [comment]
I don't think supporting custom YAML syntax is that a good idea. Looking at the gist, there seem to be issues with the implementation as well. Good news is that if you need it, you can easily implement a generic variable file that can load such YAML files.
