### ISSUE TITLE
Test cases with tag 'robot:skip' will fail when whole suite is skipped

### ISSUE THREAD

**Issue by thomasverweij** [robotframework/robotframework#4829]
I have a testsuite that checks a precondition in the `Suite Setup` in a `__init__.robot` file. If the check on the precondition fails, all the tests in the suite are skipped by running `Skip`. All the tests are skipped as expected, except for tests that have the tag `robot:skip`, these tests are marked as failed. Is this expected behaviour or a bug?

I am using Robot Framework 6.1. 
This is an example of how the issue can be reproduced:
```
suite1\
    __init__.robot
    test1.robot
    test2.robot
```

\_\_init\_\_.robot:

```
*** Settings ***
Suite Setup      Check precondition


*** Keywords ***
Check precondition
    # do some stuff, if it fails then skip:
    Skip

```

test1.robot
```
*** Test Cases ***
Test1
    [Tags]    robot:skip
    Log    hello, world
```

test2.robot
```
*** Test Cases ***
Test2
    Log    hello, world
```

Test 1 will fail when I run `robot suite1`.  When I remove `test2.robot` and run `robot suite1` again, test 1 will skip as expected.

**Comment by pekkaklarck** [comment]
This is a regression caused by #4571. Thanks for a report and a good example. Notice that if your `test1.robot` would have any test that's not skipped using `robot:skip` (or `--skip`), status would be set correctly.
