### ISSUE TITLE
Libdoc: Error when generating docs for Python library with `BuiltIn` function call in `__init__()`

### ISSUE THREAD

**Issue by DjMike238** [robotframework/robotframework#4832]
I'm trying to use `libdoc` on Robot Framework 6.1 (with Python 3.11.3) to generate docs for the following library:
```python
from robot.api.deco import keyword, library
from robot.libraries.BuiltIn import BuiltIn

@library(scope="GLOBAL")
class test_lib:
    """
    <omitted>
    """

    def __init__(self, lib):
        """
        <omitted>
        """
        path = f"/Libraries/libs/{lib}.py"
        BuiltIn().import_library("${EXECDIR}" + path)
```

Since I have a call to a `BuiltIn` function, when I try running `libdoc`, I get the following error:
```cmd
(venv) D:\TestSuite> libdoc -n "TestLib" Libraries\test_lib.py Docs\test_lib.html

Initializing library 'modem' with arguments [ test ] failed: RobotNotRunningError: Cannot access execution context
Traceback (most recent call last):
  File "D:\TestSuite\Libraries\test_lib.py", line 27, in __init__
    BuiltIn().import_library("${EXECDIR}" + path)
  File "D:\TestSuite\venv\Lib\site-packages\robot\libraries\BuiltIn.py", line 3160, in import_library
    self._namespace.import_library(name, args, alias)
    ^^^^^^^^^^^^^^^
  File "D:\TestSuite\venv\Lib\site-packages\robot\libraries\BuiltIn.py", line 69, in _namespace
    return self._get_context().namespace
           ^^^^^^^^^^^^^^^^^^^
  File "D:\TestSuite\venv\Lib\site-packages\robot\libraries\BuiltIn.py", line 64, in _get_context
    raise RobotNotRunningError('Cannot access execution context')
robot.libraries.BuiltIn.RobotNotRunningError: Cannot access execution context

Try --help for usage information.
```

Is there any way I can tell `libdoc` to ignore any `BuiltIn` method calls?

If I try commenting out the line which calls `BuiltIn().import_library()` I can generate the docs without any problem, but it's not the best solution for me, since I'm planning to have an automatic job which automatically generates these docs.

**Comment by pekkaklarck** [comment]
Libdoc needs to initialize the library to be able to read the documentation. This means that `__init__` cannot have side-effects that prevent initialization when Robot isn't running. There are generally two solutions:

1. Hide the offending code behind a method or a property that keywords can call when needed.
2. Add an optional parameter to `__init__` that can be used when running the offending code isn't desired. You then need to pass that with Libdoc.

If you need help, please ask on our Slack, Forum, or other such support channel. This issue tracker is for bug reports and enhancement requests.
