### ISSUE TITLE
Bug in evaluating compound expressions [BUG]

### ISSUE THREAD

**Issue by vfuksa-cen89549** [robotframework/robotframework#4837]
```
    ${s}  Create Dictionary  b=1
    IF  "a" in ${s} and "x" in ${s}[a]
        Log To Console  Something
    END
```
fails with `Invalid IF condition: Evaluating expression '"a" in ${s} and "x" in ${s}[a]' failed: Dictionary '${s}' has no key 'a'.`, as if there is not lazy evaluation.

The most similar expression in pure Python, i.e. 
```
if "a" in {"b":"1"} and "x" in {"b":"1"}["a"]:
```
passes (and the condition is evaluated as False). Lazy evaluation works well here. I consider this discrepancy to be a bug.

NB: the workaround is 
```
IF  "a" in ${s} and "x" in $s[a]
```
i.e. to use Pythonic dictionary, not Robotic one.

***RF 6.1***

**Comment by pekkaklarck** [comment]
This is expected. Variables using the `${x}` format are replaced before the expression is evaluated. As you already noticed, using the `$x` format avoids this issue because then variables are resolved as part of expression evaluation.

**Comment by vfuksa-cen89549** [comment]
They are replaced, I know, look at my Python code above. I do not see a reason why the RF code above should not pass. Why is the fail expected, @pekkaklarck?
