### ISSUE TITLE
variable file `get_variables` func of variables cannot coexist with global variables

### ISSUE THREAD

**Issue by delav** [robotframework/robotframework#4839]
the variable file myvariable.py write as follows:

`def get_variables(env, region):
    variables = {'cur_env': env, 'cur_region': region}
    return variables

VARIABLE = "An example string"
`

when i execute, and ${cur_env} is normal, but ${VARIABLE } not found.

**Comment by pekkaklarck** [comment]
This is by design. When you use a dynamic variable file, only items returned by `get_variables` become variables.
