### ISSUE TITLE
Add typing to all modules under `robot.api`

### ISSUE THREAD

**Issue by robinmackaij** [robotframework/robotframework#4841]
Currently, the `@keyword` and `@library` functions exposed through the `robot.api` module have no annotations. This limits the type-checking that tools like mypy and Pylance / pyright can perform, in turn limiting what types of issues language servers can detect.

Adding annotations to these functions (and, ultimately, all public-facing interfaces of the Robot Framework) would enable better IDE / tool integration.

Note that the improvements with regards to automatic type conversion also closely relate to this issue since the framework uses the signatures of methods decorated with the `@keyword` decorator to attempt automatic type conversion, while the missing annotations limit static analysis of the decorated methods.

**Comment by pekkaklarck** [comment]
Yeah, adding more typing especially to public APIs is a good idea. I first thought we should concentrate on `robot.api.deco` with this issue, but I guess it would be better to cover the whole `robot.api` instead. Below is a list of modules currently missing types altogether, but existing typing can also be enhanced:

- [ ] `deco`
- [ ] `exceptions`
- [ ] `logger`

As I already commented PR #4842, it's anyway better to have separate PRs for each module to make reviewing easier. If there are trivial changes, they can be combined, though.

**Comment by pekkaklarck** [comment]
This was implemented in PR #4842. Thanks for a great contribution @robinmackaij!

I made some fixes and cleanup in 3b2144a9553a48d5a2ab6ce796fc6bdaefd6deef. Let me know Robin if any of the changes looks problematic. One last thing to do is adding the `py.typed` files to package data so that it's included in distributions.
