### ISSUE TITLE
Importing library 'AppiumLibrary' failed | PyCharm

### ISSUE THREAD

**Issue by baselalali** [robotframework/robotframework#4850]
**Issue Summary:**
Unresolved library: AppiumLibrary. Importing library 'AppiumLibrary' failed: ModuleNotFoundError: No module named 'AppiumLibrary'. Consider adding the needed paths to the "robot.pythonpath" setting and calling the "Robot Framework: Clear caches and restart" action.

**Issue Description:**
I am encountering an issue when attempting to import the AppiumLibrary in my Robot Framework project. The error message indicates that the module cannot be found and there is a suggestion to modify the "robot.pythonpath" setting.

**Environment:**
- Robot Framework version:  3.1.1
- Python version: [version number]
- Operating System: Mac
- Installed libraries:
![image](https://github.com/robotframework/robotframework/assets/82577381/95273172-a4df-4417-a25c-cfcc92e8596c)

**Steps to Reproduce:**
1. Install Robot Framework and AppiumLibrary using pip.
2. Create a new Robot Framework test suite.
3. Add the import statement for the AppiumLibrary in the test suite settings.
4. Execute the test suite.

**Expected Result:**
The test suite should import the AppiumLibrary successfully and execute without any errors.

**Actual Result:**
The test suite fails to import the AppiumLibrary, and the mentioned error message is displayed.

**Additional Information:**
- I have confirmed that the AppiumLibrary is installed at [path to the AppiumLibrary installation directory].
- I have verified that the Python interpreter being used matches the one where the AppiumLibrary is installed.
- I have attempted to set the "robot.pythonpath" setting with the path to the AppiumLibrary directory, but the issue persists.

Any guidance on resolving this issue would be greatly appreciated.

Thank you for your assistance.

Best regards,

**Comment by kalyani1902** [comment]
@baselalali did you find any work around for this issue? I am facing similar issue .

**Comment by baselalali** [comment]
No, i don't find any solution for this problem. I tried with other python version, but i get the same problem. Any help library developer side?

**Comment by pekkaklarck** [comment]
This issue tracker is for Robot Framework and the issue seems to be related to AppiumLibrary and/or PyCharm plugin.

**Comment by evgeniy-zudin-ext-orion** [comment]
@baselalali did you find any solution?

**Comment by Nico2795** [comment]
Any solution yet?

**Comment by u001157** [comment]
I have the same problem here. Did anyone was able to find any solution?

**Comment by u001157** [comment]
I my case, I found that issue open https://github.com/serhatbolsu/robotframework-appiumlibrary/pull/418 and I was able to solve my problem doing downgrade of the library Appium-Python-Client.

python -mpip install --force-reinstall Appium-Python-Client==3.2.1
