### ISSUE TITLE
SSHLibrary.Get Pre Login Banner timeout is not working

### ISSUE THREAD

**Issue by wolfred24** [robotframework/robotframework#4852]
Hi guys, im using the following keyword:

`  Run Keyword And Ignore Error   SSHLibrary.Get Pre Login Banner      host=${server_data}[hostname]
`

And it is working fine with some servers, but with other servers it takes like 2 minutes to fail, is there any way to put a timeout to "`Get Prelogin Banner host=X`" keyword? 

I have already tried with "`SSHLibrary.Set Default Configuration    timeout=5 seconds`" and it isnt working

I have also tried with "Open Connection" first, then running `Get prelogin Banner` and it is not working, seems like if i whant to work like that i have to also do a `SSHlibrary.Login` and i dont whant to login.

This is my full code:
```
Get Code Label From All Hydras
    ${servers_data}=    Get All Servers Data
    ${index}    Set Variable    1
    Log To Console    ${\n}
    SSHLibrary.Set Default Configuration    timeout=5 seconds
    FOR    ${server_data}    IN    @{servers_data}
        TRY
            ${index}=   Evaluate    ${index}+1
            ${pre_login_banner}=    Run Keyword And Ignore Error   SSHLibrary.Get Pre Login Banner      host=${server_data}[hostname]
            Log To Console    ${pre_login_banner}
            ${fail_or_pass}=    Convert To String    ${pre_login_banner}[0]
            IF       '${fail_or_pass}'=='FAIL'    CONTINUE
            ${matches}=    Get Regexp Matches      string=${pre_login_banner}[1]    pattern=\\b\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\b
            Log To Console    ${index}. ${server_data}[name]: ${matches}[0]
        EXCEPT    message
            Log To Console    Cant retrieve server Base Level.


        END


    END
```

**Comment by pekkaklarck** [comment]
This issue tracker is for Robot Framework only and SSHLibrary is an external library. I also have no idea what could be causing this.
