### ISSUE TITLE
Skipping teardown on test / suite failure

### ISSUE THREAD

**Issue by Pratapreddy1188** [robotframework/robotframework#4856]
I want to skip the teardown if the test/suite fails. I can use --skipteardownonexit with --exitonfailure. My requirement is that I do not want to exit on the first failure, I want to run all the tests in the suite.  When a test fails I manually restart/make my system under test to an idle state. I can use the --stop-on-failure tag for the Teardown keyword, But I have already 100 test cases and teardowns defined. I want to have a generalized solution where Teardown will be skipped if the test /suite is failed.

**Comment by Pratapreddy1188** [comment]
Do we have a listener callback called just before the teardown start, so we can check for the test status and modify testdata to clear the teardown or skip it.

**Comment by pekkaklarck** [comment]
The whole point of teardowns is running something regardless are there failures or not. If you want a keyword to be run at the end of a test only when it passes, you can simply have it there as the last keyword. With suites you can wrap the actual teardown with the BuiltIn keyword `Run Keyword If All Tests Passed` like this:

```robotframework
*** Settings ***
Suite Teardown          Run Keyword If All Tests Passed    The Real Teardown
```
