### ISSUE TITLE
add a kind of progression bar

### ISSUE THREAD

**Issue by bouda1** [robotframework/robotframework#4860]
Hi,

We use Robotframework for our tests. Would it be possible to have, during tests, an output like this:
`(18/358) test_name :: Test documentation`
The idea would be to add (X/Y) at the beginning of the line to know how many tests have already been executed and the total of tests.

Another idea would be an output like this:
`(14%) test_name :: Test documentation`

For people using CMake, we get such outputs during compilations with make/ninja.

Thanks for your feedback.
Cheers.
David.

**Comment by pekkaklarck** [comment]
This would be nice, but I don't think it makes sense to enhance the current console output. It has various flaws like messages logged to console messing up the output. I believe we should totally re-design and re-implement it. In this situation keeping individual enhancements related to enhancing the console output open doesn't make sense. It would be better to have one issue for the new output and list features it should contain there. I think there's no such issue yet, but you can submit one if you want @bouda1.
