### ISSUE TITLE
"Run Keyword If Test Failed/Passed" is not working with Templated Based Tests

### ISSUE THREAD

**Issue by Pratapreddy1188** [robotframework/robotframework#4863]
Hi,
 I have template-based tests with test teardown.
The Teardown would use "Run Keyword If Test Failed" to just return from the Teardown Keyword.

This is raising error when executing Teardown.

**Comment by oliszymanski** [comment]
Could you show your error that you're getting?

**Comment by pekkaklarck** [comment]
I don't understand the problem and there's no new info even though it has been asked. Closing.
