### ISSUE TITLE
Control continue-on-failure mode by using recursive and non-recursive tags together

### ISSUE THREAD

**Issue by Noordsestern** [robotframework/robotframework#4872]
By default, test case teardowns implicitly run on `robot:recursive-continue-on-failure` mode. As I rely on keywords that are not only used in teardowns, I need `robot:continue-on-failure` mode. But setting the tag on teardown-keyword does not have any effect.

Example:
```robot
*** Test Cases ***
Demo Continue On Failure In Teardown
    Log    Hello World
    [Teardown]    Cleanup Test Case


*** Keywords ***
Cleanup Test Case
    [Tags]    robot:continue-on-failure
    Step 1
    Step 2

Step 1
    Log    All good.

Step 2
    Fail    When this fails
    Fail    Then this 2nd FAIL must not be executed!!!
```

I do want the teardown keyword to continue on failure, just not recursively. The only workaraound is to add `robot:stop-on-failure` to all keywords.

Easiest way would be, if `robot:continue-on-failure` would override the default behaviour of teardown keywords.

**Comment by pekkaklarck** [comment]
If you'd use `robot:recursive-stop-on-failure` in `Cleanup Test Case`, execution would stop for the first failure in `Step 2`. If `Step 1` would fail, `Step 2` wouldn't be executed at all, though. Did I get it right that this is not the behavior you want?

**Comment by pekkaklarck** [comment]
If I got it right, you'd want to continue in the top level keyword but stop in child keyword. That's the mode templates use and what you can enable normally with `robot:continue-on-failure`. This doesn't work with teardowns, because they continue recursively by default. I guess the mode you want could be set by using both `robot:recursive-stop-on-failure` and `robot:continue-on-failure`. The former would disable the default teardown behavior and the latter enable continuing on the top level. This doesn't work now, but it ought to be easy to change.

**Comment by Noordsestern** [comment]
Exactly, I need to coninue-on-failure only in the teardown keyword, not in the sub-keyword. 

why would it require to set `robot:recursive-stop-on-failure` together with `robot:continue-on-faliure` ?

Can't `robot:continue-on-failure` override `robot:recursive-continue-on-failure` like in #4303 ?

**Comment by pekkaklarck** [comment]
At the moment `robot:continue-on-failure` and `robot:stop-on-failure` affect only the keyword where they are defined, they don't change the behavior of the lower level keywords. Changing that behavior in this case would feel somewhat odd to me and it would also be hard to explain. Explaining that `recursive-stop-on-failure` changes the behavior recursively but `continue-on-failure` overrides it in that context would be a lot more straightforward.

**Comment by Noordsestern** [comment]
I find it intuitive to set the mode where it happens :D  the teardown sets `recoursive-continue-on-failure` implicitly, so i want to override it.

Combining the tags on the other hand is quite confusing. Anyways, if it works that way i only need to get used to :)

**Comment by pekkaklarck** [comment]
If you explicitly use `recursive-continue-on-failure` and then use `stop-on-failure` in a lower level keyword, the latter configuration affects _only_ the keyword where it is used. The initial recursive configuration is active on the keywords below that. It would be somewhat inconsistent if implicitly set recursive mode would be overridden by `recursive-continue-on-failure` also in the lower level keywords. I guess we could make teardowns an exception, but it would still be confusing in my opinion. That said, I can see that using
```
Example
    [Tags]    robot:recursive-stop-on-failure    robot:continue-on-failure
    Keyword 1
    Keyword 2
```
would be somewhat odd too. I would assume that this is a pretty rare need so it ought to be fine.

**Comment by pekkaklarck** [comment]
I made a quick prototype and supporting the above wasn't too complicated. I'm in the middle of something else and won't have time to create tests for this, and we haven't yet agreed is this the best way to solve the issue, but here's the patch for future reference and if someone wants to try the change locally:
```diff
diff --git a/src/robot/running/context.py b/src/robot/running/context.py
index c5764aa1f..b8f045752 100644
--- a/src/robot/running/context.py
+++ b/src/robot/running/context.py
@@ -171,11 +171,13 @@ class _ExecutionContext:
     def continue_on_failure(self, default=False):
         parents = ([self.test] if self.test else []) + self.user_keywords
         for index, parent in enumerate(reversed(parents)):
-            if (parent.tags.robot('recursive-stop-on-failure')
-                    or index == 0 and parent.tags.robot('stop-on-failure')):
+            if index == 0 and parent.tags.robot('stop-on-failure'):
                 return False
-            if (parent.tags.robot('recursive-continue-on-failure')
-                    or index == 0 and parent.tags.robot('continue-on-failure')):
+            if index == 0 and parent.tags.robot('continue-on-failure'):
+                return True
+            if parent.tags.robot('recursive-stop-on-failure'):
+                return False
+            if parent.tags.robot('recursive-continue-on-failure'):
                 return True
         return default or self.in_teardown
```

**Comment by pekkaklarck** [comment]
I had forgotten this issue and now noticed it when going through the issue tracker before finalizing RF 7.0. This isn't a super important issue, but the code above works so implementing this only requires writing some tests and documentation. That's so little work that it's worth doing and getting this issue closed.
