### ISSUE TITLE
saving a `log.html` from the browser causes all the html elements to be duplicated

### ISSUE THREAD

**Issue by DetachHead** [robotframework/robotframework#4875]
when viewing a `log.html` from a CI artifact or something, i often want to save the html file from the browser, but i think this causes some js to run on the saved copy that generates the html elements even though they are already there.

# to reproduce
1. open a `log.html` in the browser
2. press `ctrl+s` and save a copy
3. open the saved copy

# before
![image](https://github.com/robotframework/robotframework/assets/57028336/78c2be25-5ae2-469a-88a2-dce58ecbb948)

# after
![image](https://github.com/robotframework/robotframework/assets/57028336/e13f7471-15d8-46cb-bd4e-6e60ab17cae3)

**Comment by pekkaklarck** [comment]
I don't know why that happens but I don't consider it too big a problem. Instead of saving the page like that, you can just download the file directly.

**Comment by pekkaklarck** [comment]
We are also planning to totally reimplement logs and reports at some point. Making any bigger enhancements to the current ones doesn't make much sense. That said, if someone can figure out why this happens and fixing the issue is easy, I'd be happy to review a PR.
