### ISSUE TITLE
Robot hangs up using any king of sh or terminal call

### ISSUE THREAD

**Issue by allanrodriguezh** [robotframework/robotframework#4893]
robotframework==6.1.1
Macos: 14.0 (23A344)
Python: 3.8.10

Whenever I try to call an executable script from a test it hangs up and the terminal crashes.
I tried these different methods:
- Using run process
`Run Keyword                   Run Process  ./scripts/mysql-reset-seed.sh  shell=yes`

- Using a Python script
```python
@keyword('Reset Database')
def reset_database():
  subprocess.call("./mysql-reset-seed.sh", shell=True) 
``` 

With this robot code:
```robotframework
Suite Setup
    # Initialize Test Data
    Log To Console    'hehe'
    Reset Database
    Log To Console    'hehe'
``` 
This is not failing in our Jenkins environment so it could be a macOS version issue (I recently update to 14).
It stays here:
![image](https://github.com/robotframework/robotframework/assets/124798450/d84082a9-ad81-436d-87e5-c3a3089fb714)

**Comment by pekkaklarck** [comment]
Processes can hang for various reasons but one common problem is that output buffers get full. That can be avoided by redirecting outputs to files or `/dev/null`. See the Process library documentation for information how to do that with `Run Process` and `subprocess` docs for how to do it with `call`.

I doubt this is caused by Robot Framework itself. If you believe it is, you would need to create a simple example demonstrating the issue that doesn't involve databases or anything like that.

**Comment by allanrodriguezh** [comment]
> Processes can hang for various reasons but one common problem is that output buffers get full. That can be avoided by redirecting outputs to files or `/dev/null`. See the Process library documentation for information how to do that with `Run Process` and `subprocess` docs for how to do it with `call`.
> 
> I doubt this is caused by Robot Framework itself. If you believe it is, you would need to create a simple example demonstrating the issue that doesn't involve databases or anything like that.

Actually the script that i am using just has two echo lines with a dummy text:
```
echo 'Mysql reset started'
echo 'Mysql reset finished'
``` 
The subprocess call from the python script also hangs.

**Comment by AntonShopin** [comment]
+1
Have exactly the same issue, it just hangs up.
Tried different keywords from Process library and OperatingSystem. 

- robotframework==6.1.1
- Macos: 14.0 (23A344)
- Python 3.11.5

Simple example: 

`*** Test Cases ***
Run Command Directly
    ${output}=    Run Process   command=pwd 
    Log    ${output}`

`*** Test Cases ***
Run Command Directly
    ${rc}    ${output}=    Run And Return RC And Output    ${consoleCommand}
    Log   ${output}`

**Comment by AntonShopin** [comment]
Looks to be fixed in https://github.com/MarketSquare/robotframework-browser/pull/3155

**Comment by pekkaklarck** [comment]
@allanrodriguezh I don't have MySQL installed so your example won't work. Can you create an example without such external dependencies?

**Comment by allanrodriguezh** [comment]
> @allanrodriguezh I don't have MySQL installed so your example won't work. Can you create an example without such external dependencies?

The problem is with any script call, as I said, I just had a script with two echo functions.
But it seems solved in the @AntonShopin comment's link. Thanks Anton!
