### ISSUE TITLE
Remove parallel execution of keywords (`:PARALLEL` ) because it doesn't work correctly and requires special syntax

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#490]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=490) by @pekkaklarck on 26 Feb 2010_

Parallel execution of keywords using the special `:PARALLEL` syntax is
currently pretty buggy. The root cause for these problems is that the
keywords are executed in separate threads and the framework or libraries
aren't thread safe. If the keywords, for example, manipulate variables or
other internal state of the framework the end results may vary between
different runs, and in worst cases the result is crash or hang.

Making the framework fully thread safe would be a huge task, and it could
be that some of the current functionality even cannot be made thread safe.
On the other hand, handling parallel execution on test libraries based on
the actual needs is normally pretty easy and allows better customization. 

Another problem with `:PARALLEL` is that this special case requires special
syntax. For example RIDE doesn't currently support it too well, and adding
the support would be quite a big task. 

Because of these problems the core team has decided to remove `:PARALLEL`
in RF 2.5 unless someone comes up with very good counter arguments.

**Comment by xczhang07** [comment]
Is there a way to run robot keyword on parallel ?
