### ISSUE TITLE
new feature: Import test cases to suite as importing resource files

### ISSUE THREAD

**Issue by Humppa69** [robotframework/robotframework#4902]
There is no option to add test cases to suite from another test suite file.

I want to combine tests to same test run before executing test cases. Using rebot, tags or loops when executing tests makes it more difficult when executing many suites that share same common tests from one suite. And copying same test to different suites is not the option.

Same kind of functionality than importing resource files but importing files that has *** Test Cases *** section. And then test cases are also executed as tests when running this main test suite. Like dynamically add tests to execution.

It is more easier to execute one test suite that already combines all the test you want to run, than use loops, scripts, and rebot for having same result, and use many test runs.

For example, you have test suites like common.robot, set1.robot, set2.robot.set3.robot...
How to run tests so that common.robot is always executed as a part of every test suite execution?  
Normally it is easy to run tests using one command that execute all suite files at once, but in that case you need to combine results somehow in loop structure. But if you can import tests from 'common.robot' to different sets, then you need only one basic shell command to execute tests.

**Comment by pekkaklarck** [comment]
Test case files not being importable as resource files is by design and won't change. If there's certain tests that you'd like to run e.g. as a setup for another test or suite, you need to create a new user keyword with that functionality.

**Comment by Humppa69** [comment]
Yes I understand, but there is a reason why test case and keywords are not the same. You cannot call test cases from another file or you cannot call keywords by tags and that is ok. Also when you run tests you can call tests but no keywords. As you said, I can do kind of abstraction for test cases and call them as a keyword. That is not a good option for me, but possible of course. I would like to have my test cases in test case .robot files and keywords in resource files. This is a litte bit hard to explain, but I try to avoid abstraction, that makes cases more messy. Thanks for the quick answer.
