### ISSUE TITLE
Timeout issue

### ISSUE THREAD

**Issue by HimaAne** [robotframework/robotframework#4907]
Hey I am using 5.1 library, i think this issue still exits in latest library as well. 

Issue is, 
used  timeout as 30 seconds in test cases development: 
    Wait Until Element Is Not Visible id=${autoaction_name}, 30

On prerequisites used: 
    Set Browser Implicit Wait     60 seconds
    Set Selenium Implicit Wait    15 seconds 

    or  with 60 sec

Here Set selenium implicit wait is overall configuration, but testcase is still considering the overall wait 15 seconds instead of 30 seconds which i configured, basically it should be overwritten with testcase implementation. otherwise this leads serious issue for objects we expect longer time to wait. I think this issue is the for element should be visible as well. 

Fix ASAP.

**Comment by pekkaklarck** [comment]
Please report the issue to SeleniumLibrary's issue tracker, this issue tracker is only for Robot Framework core. I recommend you to also explain the issue in a bit more detail. I read the description twice and didn't really understand what the problem is.
