### ISSUE TITLE
Trace log level logs arguments twice for embedded arguments

### ISSUE THREAD

**Issue by bhirsz** [robotframework/robotframework#4913]
Using following code:

```
*** Test Cases ***
Test
    Keyword With Arguments    1    2
    Keyword With Embedded 1
    Keyword With Mixed 1    2


*** Keywords ***
Keyword With Arguments
    [Arguments]    ${arg}    ${arg2}
    Log    ${arg}

Keyword With Embedded ${arg}
    Log    ${arg}

Keyword With Mixed ${arg}
    [Arguments]    ${arg2}
    Log    ${arg}

```

and with log level trace:

```
robot --loglevel TRACE test.robot
```

Arguments are logged twice:
![image](https://github.com/robotframework/robotframework/assets/8532066/280bb6dc-3136-48cd-8621-6ffc888b8f9f)

It could be because we have embedded variables, but there is not difference for the source of the argument in the log or any indication of that.

**Comment by pekkaklarck** [comment]
This looks odd. The bug has most likely been introduced when the support for mixed arguments was added and we wanted to log both embedded and normal arguments.

**Comment by pekkaklarck** [comment]
Arguments were logged both by the UserKeyword runner and by EmbeddedArgumentsRunner that extends it. Removing logging from the latter fixed the issue. We had tests for logging, but they didn't check for unnecessary messages. Now tests are more strict as well.
