### ISSUE TITLE
Can't connect to MySQL db that has SSL, can you please help? 

### ISSUE THREAD

**Issue by romanbelov-e18441** [robotframework/robotframework#4923]
*** Settings ***
Library           DatabaseLibrary
Library           Collections
Library           OperatingSystem
Library           String
Library           DateTime

*** Variables ***
${DB Host}              ABC.us-east-1.rds.amazonaws.com
${DB Port}              3306
${DB Name}              dispatch
${DB User}              mayname
${DB Password}         mypass
${SSL Ca}               ./Certificates/us-east-1-bundle.pem
${SSL Cert}             ./Certificates/us-east-1-bundle.pem
${SSL Key}              ./Certificates/us-east-1-bundle.pem

*** Test Cases ***
Connect to MySQL Database with SSL
    ${db_params}=  Create Dictionary
    Set To Dictionary  ${db_params}  host=${DB Host}
    Set To Dictionary  ${db_params}  port=${DB Port}
    Set To Dictionary  ${db_params}  database=${DB Name}
    Set To Dictionary  ${db_params}  user=${DB User}
    Set To Dictionary  ${db_params}  password=${DB Password}
    Set To Dictionary  ${db_params}  use_unicode=true
    Set To Dictionary  ${db_params}  charset=utf8mb4
    Set To Dictionary  ${db_params}  ssl_ca=${SSL Ca}
    Set To Dictionary  ${db_params}  ssl_cert=${SSL Cert}
    Set To Dictionary  ${db_params}  ssl_key=${SSL Key}

    Connect To Database     pymysql     server=${db_params}
    Check If Exists In Database    SELECT first_name FROM dispatch.admin WHERE id=15157727
    Disconnect From Database
    
    
    Getting the below error
    Connect to MySQL Database with SSL                                    | FAIL |
OperationalError: (2003, 'Can\'t connect to MySQL server on \'"ABC.us-east-1.rds.amazonaws.com"\' ([Errno 11001] getaddrinfo failed)')

**Comment by test-fullautomation** [comment]
Hi, 
did you check proxy settings. Looks like you are behind a proxy.
Regards, 
 Thomas

**Comment by pekkaklarck** [comment]
This doesn't look like a bug report or an enhancement request related to Robot Framework itself. If you believe you've encountered an issue in some library or tool, please report the problem to its issue tracker. If  you are looking for help, try our Slack, Forum, or other support channels listed at robotframework.org.
