### ISSUE TITLE
Automatically expanding keywords using --expandkeywords does not function

### ISSUE THREAD

**Issue by adamweld** [robotframework/robotframework#4925]
The cli argument --expandkeywords does not seem to be working for me.

[Relevant documentation link](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#automatically-expanding-keywords)

Robot version: `Robot Framework 5.0.1 (Python 3.10.7 on win32)`

### Steps to replicate:

using file ExampleSuite.robot:
```
*** Test Cases ***
Test that should be expanded
    [Tags]    expand
    Log    Now you see me

Test That should not be expanded
    Log    Now you don't!
```

`$ robot --expandkeywords TAG:expand .\ExampleSuite.robot`

The log output does not have the tagged test case expanded by default.

<img width="641" alt="log_screenshot" src="https://github.com/robotframework/robotframework/assets/525911/a5a8ebbf-9940-45b0-9ba6-fade55b413a2">

**Comment by adamweld** [comment]
Whoops, test != keyword.

**Comment by pekkaklarck** [comment]
Yeah, this behavior is by design because expanding wors based on keyword tags. If there are use cases where looking for test tags would be useful, that enhancement could be considered.
