### ISSUE TITLE
I want to use RF (V6.1.1) in my project, Which verison of Python do you recommander? 

### ISSUE THREAD

**Issue by yifei325325** [robotframework/robotframework#4946]
Hi Gentlemen,

I want to update the RF to V6.1.1 in my project which was 3.2.2 before. and I want to update the Python version at the same time. Could you give me some advice? Which Python version RF v6.1.1 is built based on and running the test on?

Thanks so much for your hearing and look forward to your reply.

**Comment by pekkaklarck** [comment]
This issue tracker is for bug reports and enhancement requests. Please use our Slack, Forum, or other support forums listed at robotframework.org for questions. That said, RF 6.1.x supports Python 3.6-3.12 and has been tested with all these versions.
