### ISSUE TITLE
Feature: "robot:expand" tag for keywords

### ISSUE THREAD

**Issue by richardstone** [robotframework/robotframework#4951]
It would be great to have "robot:expand" as an option for the cases when we have a top level keyword flattened, but still would want some sub-keywords to show up.

**Comment by pekkaklarck** [comment]
`robot:flatten` was added in RF 6.1 (#4584). Is that what you are looking for or do you propose enhancing the current functionality somehow? If the latter, please explain what you want a bit more thoroughly.

**Comment by pekkaklarck** [comment]
No new info, closing.
