### ISSUE TITLE
RPA.Browser.Selenium opens Chrome as x86_x64 translated instance on arm64 machine

### ISSUE THREAD

**Issue by niknaylos** [robotframework/robotframework#4953]
This issue blocks me for past 2 days increasing my test execution times by 10-20 times. 
Every time I run .robot script with RPA.Browser.Selenium in chrome it opens x86_x64 instance instead of running native arm64.

Same issue with Firefox however it is working at fine speeds. But I am interested in Chrome as well.
Help me fix this

**My machine is:**

Macbook Air M1 8gb
Ventura 13.2.1
chromedriver is 100% arm64

I use VSCode and my **conda.yaml content**:

```
dependencies:
  - python=3.10.12              
  - truststore=0.8.0
  - pip=23.2.1                  
  - pip:
    - rpaframework==27.4.2      
    - rpaframework-recognition==5.2.3
    - robotframework-screencaplibrary==1.6.0
    - sauceclient==1.0.0
    - saucebindings==1.3.0
```

**Comment by pekkaklarck** [comment]
No idea what's causing this. This issue tracker is for Robot Framework core so I close this issue. I recommend you to submit an issue to the RPA framework issue tracker or asking help on some of the support forums.
