### ISSUE TITLE
count the wait time

### ISSUE THREAD

**Issue by ajadach** [robotframework/robotframework#4969]
Hi,

I have request for feature that RFW keyword like "Wait Until Keyword Succeeds" should count all wait time for each test case? suite? and present this data in the log on TC/suite level?
We, as users use this keyword when we would like to do something but the endpoint (does not metter what is the endpoint, REST API, equipment etc) is not ready but will be. This global counter will deliver data how long scripts lose the time on the waits because endpoint is not ready. It will be helpful to know that test case takes 5 min but we lose 2 min because of waits. That data gives arguments  to QA ppl to open discussion about quality and availability to the endpoint.

Br,
Artur Ziółkowski @JitTeam/Nordea

**Comment by pekkaklarck** [comment]
This sounds like a pretty special need. I doubt that all users of Wait Until Keyword Succeeds would want this information to be shown and, on the other hand, others could be interested to get this kind of information with other keywords as well. Here are some ideas you can consider:
- Create a custom library that keeps track on times and reports them appropriately.
- Use a listener that checks times.
- Use a separate tool to inspect output.xml that contains all execution times. You can use Robot's own result models for this.

Without knowing your actual context better it's impossible to tell what's the best approach for you. If you need more help, I recommend asking on our Slack, Forum, or other support channel listed at robotframework.org.
