### ISSUE TITLE
Loading tests and resources from archives (zip, egg, jar)

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#498]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=498) by kai.hackemesser on 11 Mar 2010_

Use case:
I want to use a resource file that I don't want to copy into the test
source tree as it is maintained and managed in another source repository,
another project.

Possible solution:
I could load it from a supplied zip file and add a library entry that
resolves into a zip file like Java's JarURL:
./lib/myResources.zip/!commons.html

**Comment by RonnyPfannschmidt** [comment]
for the python side it would be fabulous to load resources from python packages,
so one could make custom local packages and distribute them via an company internal pypi server (like devpi)

**Comment by pekkaklarck** [comment]
Sounds good to me. If someone is interested in working with this, I'm happy to help with design, review PRs, etc. There probably isn't enough time to get this into RF 2.9, but if there are no backwards incompatibility issues we can include it in RF 2.9.x and RF 3.0 is already planned for autumn.

**Comment by RonnyPfannschmidt** [comment]
i just noticed that it is already possible to do this by accident

since robotframework looks for ressources on the pythonpath, it's already possilbe to package Ressources, one simply needs to make a package with a __init__.py

in my oppinion the reuse of pythonpath is a bit problematic as a general design choice,
but its not clear if there is a better variant and how people should transition to it

**Comment by pekkaklarck** [comment]
Yes, looking resources from `sys.path` is not that clean solution. The fact that Python, Jython and IronPython all use different environment variables to configure it has also lead to problems like in #1983. As I commented in that issue, it would probably be a good idea to add environment variable `ROBOTPATH` and look resources from it instead. We probably should add its contents to `sys.path`, though, to be able to use that also to specify where libraries are located. That's definitely a topic for a separate issue, though.

**Comment by RonnyPfannschmidt** [comment]
could you create a appropriate issue for discussion of the handling of the different kinds of search path,
i'm not deep enough in the details to create a proper description

**Comment by pekkaklarck** [comment]
Just create an issue that makes sense from your point of view. We can update the title and even the description if needed. Or just create new one if we want something else.

**Comment by pekkaklarck** [comment]
Closing due to lack of interest in recent years. Can be reopened if someone actually want to implement this.

**Comment by stevemit** [comment]
I've come to this issue looking for a way to manage test suites as versioned artifacts (zip, jar, egg) in a repository.  A workaround is to launch robot with a shell script that unpacks archives on first execution.  It would be slicker if the robot executable could run a test archive directly.  Is there an alternate best practice?
