### ISSUE TITLE
${OUTPUT DIR} returned as PosixPath type

### ISSUE THREAD

**Issue by oboehmer** [robotframework/robotframework#4992]
We noticed that RF 7.0rc1 returns ${OUTPUT_DIR} variable as PosixPath, likely a consequence of https://github.com/robotframework/robotframework/issues/4988.

I feel this is something we should either change (to return the string representation), or clearly document as backward-incompatible change.

```
(v)  $ cat /tmp/o.robot 
*** Test Cases ***
Test Outputdir type
    ${outputdir}=    Get Variable Value    ${OUTPUT_DIR}
    ${type}=         Evaluate    str(type($outputdir))
    Should be Equal    ${type}    <class 'str'>


(v) $ robot /tmp/o.robot 
==============================================================================
O                                                                             
==============================================================================
Test Outputdir type                                                   | FAIL |
<class 'pathlib.PosixPath'> != <class 'str'>
------------------------------------------------------------------------------
O                                                                     | FAIL |
1 test, 0 passed, 1 failed
==============================================================================

```

**Comment by pekkaklarck** [comment]
Yes, this is an accidental side-effect of the aforementioned change. I changed the paths used internally from `str` to `Path`, but the intention wasn't to change also built-in variables. `Path` has benefits over `str` so this might be a good change, but it should have been done much earlier in RF 7 development cycle. Now I believe it's better to change the variables to be stringns again.
