### ISSUE TITLE
Issue with libdoc HTML Generation: Type Errors in libdoc Output (7.0rc1)

### ISSUE THREAD

**Issue by d-biehl** [robotframework/robotframework#4997]
Current Behavior:
When attempting to generate a libdoc HTML file using the latest 7.0rc1, the resulting file does not display properly, just a white background is shown. This seems to be caused by 'type errors' present in the generated HTML.

To Reproduce:

Execute the command `libdoc BuiltIn BuiltIn.html` in the command line using the latest 7.0rc1.
Open the generated HTML file in any browser.

Expected Behavior:
The generated HTML file should display without any issues.

**Comment by pekkaklarck** [comment]
Thanks for the report. This bug was introduced in 8c08ac0b7f8ebfffc1fbbb5b998f5695bb876557 and #4998 ought to fix it. That commit has some other things that may need to be changed as well. I'll comment the commit separately. Ping @Snooz82.
