### ISSUE TITLE
Open Browser 'Options' object has no attribute ''

### ISSUE THREAD

**Issue by manosnoam** [robotframework/robotframework#5001]
When calling `open browser` with `options` that ends with `;` such as:

    add_argument("--ignore-certificate-errors");add_argument("window-size=1920,1024");add_argument('--no-sandbox');add_argument('--disable-gpu');add_argument('--disable-dev-shm-usage');

Then the browser will fail to open with error:

    robot.errors.HandlerExecutionFailed: AttributeError: 'Options' object has no attribute ''

Once I removed the last `;` then the browser was launched with the required options.

Found in RF version 6

**Comment by pekkaklarck** [comment]
Are you sure the problem is in Robot Framework itself and not in SeleniumLibrary or whatever library you use? In the latter case the problem should be reported to the issue tracker of that library.

**Comment by manosnoam** [comment]
Right, can we move it to https://github.com/robotframework/SeleniumLibrary ?
(Usually it is optional to move Github issue for a sibling project)
Or shall I close and reopen there ?

**Comment by pekkaklarck** [comment]
I could move this to SeleniumLibrary project, but that would preserve all comments and that would look a bit odd. Probably best you submit a new one there instead.

**Comment by manosnoam** [comment]
Opened https://github.com/robotframework/SeleniumLibrary/issues/1877
