### ISSUE TITLE
Robot hangs on result output when used inside a Github Action

### ISSUE THREAD

**Issue by Ahzed11** [robotframework/robotframework#5006]
## Version

- `python3 --version`: Python 3.9.2
- `robot --version`: Robot Framework 6.1.1 (Python 3.9.2 on linux)
- ubuntu latest (docker image)

## Reproduce the problem
[Here](https://github.com/Ahzed11/pixelwar/actions/runs/7438630457) is a link to a run that has failed. The robot ran during 6 hours before Github killed it. 
With that link, you can see the content of my workflow and the output it generated.

**Comment by pekkaklarck** [comment]
Execution can hang for various reasons and this isn't enough information for use to investigate this further. We'd basically needed to be able to reproduce the issue ourselves to be able to debug it. If you have more information, and preferably an example we could run, please reopen this issue or create a new one.
