### ISSUE TITLE
Command line option --splitlog Split log based on test suite?

### ISSUE THREAD

**Issue by Northxw** [robotframework/robotframework#5009]
## 1. Problem background

&emsp; In my automated testing project, the number of test cases is higher than 1500, and the size of the log file generated by Robot is larger every time it is fully executed. The problem was that not only was it slow to build, but it was also slow to view using a browser, so I found the `--splitlog`  option using `robot -h`.

## 2. Practical problems

&emsp; As I said above, the number of test cases in my project is relatively large. Therefore, when using the robot --splitlog option, the log is split according to test cases by default, so many log-index.js files are generated. This is a bit unacceptable to me.

&emsp; Therefore, I would like to know how to make the `--splitlog`  option split logs according to test suite files or test suite directories instead of splitting logs according to the default test cases.

![image](https://github.com/robotframework/robotframework/assets/38708989/237b101f-5d31-4637-8bc8-d6054b544080)

Looking forward to the answer, thank you very much.

**Comment by pekkaklarck** [comment]
There's no support for splitting based on suites. It would basically require a new command line option and reimplementing the current test based splitting with suites. That's doable, the old implementation could be used as a reference, but a relatively big task anyway.

I personally don't consider implementing this worth the effort in general. Because we are planning to re-implement log and report in the somewhat near future, I don't think this would be a good idea even if someone would provide a pull request. 

Could you clarify why the amount of js files is a problem for you?

**Comment by Northxw** [comment]
> There's no support for splitting based on suites. It would basically require a new command line option and reimplementing the current test based splitting with suites. That's doable, the old implementation could be used as a reference, but a relatively big task anyway.
> 
> I personally don't consider implementing this worth the effort in general. Because we are planning to re-implement log and report in the somewhat near future, I don't think this would be a good idea even if someone would provide a pull request.
> 
> Could you clarify why the amount of js files is a problem for you?

Thank you for your answer. I personally fully understand the problem that --splitlog cannot be split based on suites.

Continuing to answer your question, the number of JS files is not a problem. I just think that when the number of test cases increases, the number of JS files will become more and more. 😄

Thanks again for your reply, I will close this issue directly.

**Comment by pekkaklarck** [comment]
We use `--splitlog` with Robot's own acceptance tests. There are close to 7000 tests and we haven't had problems. Modern hard drives and file systems shouldn't in general have problems with huge amount of files per directory. If the are turn out to be concrete problems, we can return to this.
