### ISSUE TITLE
v7 fails to find the tests when sub-suites are used

### ISSUE THREAD

**Issue by realtimeprojects** [robotframework/robotframework#5019]
Given the following directory layout

```
tests/
   suite1/
       suite11/
           test1.robot
           test2.robot
   suite2/
       test3.robot
``` 

When running the following command line:

```
robot ... --suite suite1 tests/
```

robot successfully finds and executes `test1` and `test2`, however, when using:

```
robot ... --suite suite1.suite11 tests/
```

will fail to find the tests and produce an output

```
Suite 'Tests' contains no tests or tasks matching tag... in suite 'suite1.suite11'.
```

The following commands, however, will successfully find and run the tests:

```
robot ... --suite tests.suite1.suite11 tests/
robot ... --suite *.suite1.suite11 tests/
```
This misbehavour was introduced with `Robot Framework 7.0 (Python 3.11.2 on linux)` of robot framework. Using robot `Robot Framework 6.1.1 (Python 3.11.2 on linux)` the command above works fine.

**Comment by pekkaklarck** [comment]
This behavior was changed to make `--suite` and `-test` behave consistently. For details see #4720.
