### ISSUE TITLE
Extent Report Integration

### ISSUE THREAD

**Issue by FWDQK** [robotframework/robotframework#5028]
Hi Team,
Is it possible to integrate Extent report with Robotframework?
Please suggest which reporting format can be used with robotframework.

**Comment by pekkaklarck** [comment]
I haven't hear about [Extent Reports](https://www.extentreports.com/) earlier, but it seems to be some kind of a reporting tool or API. Most likely you'd need to implement a dedicated plugin to it. What Robot's API to use etc. is something you can ask on our Slack or Forum, this issue tracker is for bug reports and enhancement requests related to Robot Framework core. Possibly plugin for Extent would be a separate projects.
