### ISSUE TITLE
Cannot open application when use Library   AppiumFlutterLibrary with flutter app

### ISSUE THREAD

**Issue by apatheticL** [robotframework/robotframework#5040]
Hi Robotframework team
Proplem:  
- I want open app flutter use Library    AppiumFlutterLibrary but when i usse it this show error "No application is open"
This is my code 
https://gist.github.com/apatheticL/cd76e2ce743f6af8cd5326a2e3cc12ee
this is log error
https://gist.github.com/apatheticL/e4e57542318628287b8f15271f5f916d
I cann't find log in appium server.
Please help me fix it. thank so much

**Comment by pekkaklarck** [comment]
Please send questions to our Slack or Forum which you can find via robotframework.org. If you believe you have encountered a bug in AppiumFlutterLibrary, submit an issue to its own issue tracker. This tracker is only for bug reports and enhancements requests related to Robot Framework itself.
