### ISSUE TITLE
Update Test Cases Setup args using Pre-run Modifiers 

### ISSUE THREAD

**Issue by MoSedky** [robotframework/robotframework#5044]
I am trying to update test cases in suites to pass params like name and `setup.args` in `start_suite()`  but actually it's getting reflected to all tests in suite. My Pre-run modifier looks like this:

`
from robot.api import SuiteVisitor

class ExecuteTestsXTimes(SuiteVisitor):

    def __init__(self, x_times):
        self.x_times = x_times

    def visit_suite(self, suite):
        """Remove tests that match the given pattern."""
        suite.tests = [t for t in suite.tests]
        for testcase_index in range(len(suite.tests)):
            if 'MultipleTestData' in suite.tests[testcase_index].tags:
                for x_time in range(int(self.x_times) - 1):
                    suite.tests.append(suite.tests[testcase_index])
                    print("Added")
        suite.tests[0].setup.args = (suite.tests[0].name, 0)
        suite.tests[1].setup.args = (suite.tests[1].name, 1)
`
test.robot have 1 Test Cases and to be duplicated after running `robot --prerunmodifier /ExecuteTestsXTimes.py:2 -d reports "/test.robot"`. 

This getting all Test setup args to be (test name and 1) which means all Tests are getting updated . I need to find a way to apply some modifications for specific tests and not to all of it in Suite. How this can be achieved ?

**Comment by pekkaklarck** [comment]
Probably you should implement `visit_test` and then do modifications for adequate tests. If you have further questions, please use our Slack or Forum, both linked from http://robotframework.org. This tracker is for bug reports and enhancement requests.
