### ISSUE TITLE
While loop iteration stops when run keyword continue on failures is used for a keyword and keyword fails

### ISSUE THREAD

**Issue by hgupta891** [robotframework/robotframework#5045]
```
Test While with error
    ${curr_time}=    Get Time  epoch
    ${End_time}=    Evaluate    ${curr_time} + 5

    WHILE    ${End_time} > ${curr_time}
        Sleep   1s
        ${curr_time}=   Get Time  epoch
        Run Keyword And Continue On Failure    Fail   To fail the keyword
    END

```
If the run keyword and continue on failure is used then while loop should not exit until condition value is false.

Robot Framework 5.0.1 (Python 3.7.5 on win32)

**Comment by pekkaklarck** [comment]
I can reproduce the issue with RF 5.0.1 but not with RF 7.0 so this bug has already been fixed. If you are interested to find out when, test different versions or search the issue tracker.
