### ISSUE TITLE
Reflect optional WHILE loop condition in documentation

### ISSUE THREAD

**Issue by p-zander** [robotframework/robotframework#5068]
Changes made for #4576 and the resulting behavior are not documented starting with
https://robotframework.org/robotframework/6.1/RobotFrameworkUserGuide.html#while-loops 
Depending on which form you want to encourage, either existing examples should drop the optional condition or a note should be added on the fact.

**Comment by pekkaklarck** [comment]
There's this note in the beginning explaining that the condition is optional:

> Starting from Robot Framework 6.1, the condition in a WHILE statement can be omitted. This is interpreted as the condition always being true, which may be useful with the limit option described below.

You are right that all examples seem to use `True` as a condition unnecessarily. I guess they could be changed either to use some other condition or the condition could be removed altogether. Are you interested to provide a PR?

**Comment by p-zander** [comment]
You are right, my bad. I was too drawn to the examples. I guess I would prefer it being shown in the first `limit` examples
```robotframework
*** Test Cases ***
Limit as iteration count
    WHILE    True    limit=100
        Log    This is run 100 times.
    END

Limit as time
    WHILE    2 == 2    limit=10 seconds
        Log    This is run 10 seconds.
    END

No limit
    WHILE    limit=NONE    # Omitting optional condition
        Log    This must be forcefully stopped.
    END
```
(https://robotframework.org/robotframework/6.1/RobotFrameworkUserGuide.html#limiting-while-loop-iterations)

an then being omitted after that, but maybe you have a different opinion on it. Would you want to change the documentation starting with 6.1 or only latest? I guess I should go and read up on how to contribute.
