### ISSUE TITLE
Typo in listener interface documentation in the User Guide

### ISSUE THREAD

**Issue by petr-kus** [robotframework/robotframework#5070]
"Called when a keyword starts." is written in the documentation for the **end_keyword** method in the listener's V3

In (latest - 7.0 version)
[https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#listener-interface-versions](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#listener-interface-versions)

for listener version 3. Is this tiny 'copy-paste' bug: 
![small_bug](https://github.com/robotframework/robotframework/assets/66471396/b94813a0-ae9b-48d3-8b80-4b3a3976f394)

**Comment by pekkaklarck** [comment]
Seems like a copy-paste bug. Good catch and thanks for reporting!
