### ISSUE TITLE
Prompt that the driver cannot be used

### ISSUE THREAD

**Issue by WunYun** [robotframework/robotframework#5071]
Open the browser using robotframework, Prompt that the driver cannot be used
<img width="1685" alt="image" src="https://github.com/robotframework/robotframework/assets/126845906/88d0acb6-ff13-4971-ae4a-4533d8270adc">

macOS 14.3.1 Intel
python 3.8
robotframework 7.0
robotframework-seleniumlibrary 6.2.0
selenium 4.18.1

**Comment by WunYun** [comment]
I can open the browser using selenium
<img width="335" alt="image" src="https://github.com/robotframework/robotframework/assets/126845906/b3daf697-6329-4bfe-b270-b327da4db36c">

**Comment by pekkaklarck** [comment]
This is likely a configuration or network issue. Even if it there would be a bug, it would be in Selenium or SeleniumLibrary, and this issue tracker is for Robot Framework core.

Please ask more help on our Slack or Forum. If you suspect there's a bug, please submit an issue with more information to appropriate issue tracker.
