### ISSUE TITLE
Browser is not launching in the headless mode

### ISSUE THREAD

**Issue by KrishnaKamakshi** [robotframework/robotframework#5073]
Hello Team, 

I am observing an issue while executing the Automation script by using Python with Robot Framework, I noticed that the browser is not launching in the headless mode. 

Version:

- robotframework-seleniumlibrary : 6.2.0
- selenium : 4.16.0
- robotframework : 7.0

Code Snippet:
`options.headless = True`

It used to work fine, I was able to launch the browser in Headless mode before upgrading the packages, but I noticed that the Browser is not launching in the headless mode after upgrading the packages with the latest versions.

Can someone look into this issue, please?

CC: @pekkaklarck 

Regards, 
Krishna Kamakshi Brahma

**Comment by pekkaklarck** [comment]
This certainly isn't a bug in Robot Framework itself. If you suspect it's a bug in SeleniumLibrary, please submit an issue to its tracker. Asking help either on Slack or Forum could be a better idea, though.
