### ISSUE TITLE
Move code related to persistent settings used by RIDE and Mabot to the core framework

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#508]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=508) by @pekkaklarck on 25 Mar 2010*

Both RIDE and Mabot need to store settings persistently and we've
implemented generic code for that purpose. Currently both RIDE and Mabot
have their own versions of this code stored in their code base. It would be
better to move it to the core framework so that they, and other tools,
could use simply use it from `robot.utils`. 

The version of this code in RIDE's code base can be found behind the URL
below. Notice that it uses external, BSD licensed, configobj module that is
located in the same directory.

<a href="https://code.google.com/p/robotframework-ride/source/browse/src/robotide/context/settings.py" rel="nofollow">https://code.google.com/p/robotframework-ride/source/browse/src/robotide/context/settings.py</a>

**Comment by pekkaklarck** [comment]
I don't think this makes sense unless Robot itself uses these settings. Python packaging system has improved and this logic could be made available separately if needed. We should rather try removing extra functionality from the core framework.
