### ISSUE TITLE
Enhance result package to expose generated attribute from output.xml

### ISSUE THREAD

**Issue by aaltat** [robotframework/robotframework#5087]
The `output.xml` has  `<robot generated="year-month-dayTHH:MM:SS.milliseconds" …>` in the xml. It would be handy to expose the `generated` attribute from the RF result package. We have a need to  use the `generated` attribute when reading test result from multiple runs in CI and plotting the results in time series manner.

**Comment by pekkaklarck** [comment]
Is this still relevant in your project @aaltat or should we move it to RF 7.2 or close altogether?

**Comment by aaltat** [comment]
This is relevant, I will look this and the other my issue when I get the ongoing Browser library PR done.

**Comment by pekkaklarck** [comment]
This ought to be an easy issue to implement, at least compared to `Should Be Equal` enhancement we discussed, and would be good to get it closed.

**Comment by aaltat** [comment]
I can do this first and then the second one. This has clear need from my company.
