### ISSUE TITLE
Allow listeners to change execution status 

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#5090]
Listeners using the v3 API can set the status and message of each executed keyword and a control structure, but these changes do not affect the actual test execution. For example, changing keyword status from PASS to FAIL changes the status of the keyword in the log file, but subsequent keywords are executed normally as if the keyword would PASS. Similarly, changing keyword status from FAIL to PASS changes keyword status in the log file, but the failure still propagates and the test fails.

We should enhance the execution logic so that if the test status or message is altered by listeners, that change is taken into account. This would allow failing or skipping test, suppressing failures and so on.

**Comment by cj36457** [comment]
I see this is created for keywords. Is this already working for test cases?

for example in the start_test hook?

**Comment by pekkaklarck** [comment]
This only works with keywords. Being able to do, for example,
```python
def start_test(data, result):
    if some_condition():
        result.status = 'SKIP'
```
and get the test skipped would be convenient. Please submit a separate issue about that with a reference to this related issues.
