### ISSUE TITLE
Creating user keywords with programmatic API

### ISSUE THREAD

**Issue by Tattoo** [robotframework/robotframework#5119]
We have a case where we want to produce different output.xml's. Best way to do bunch of these is to programmatically create different test suites and then run them. However, currently the API only allows you to create test cases whose body is composed entirely of keywords in existing libraries or resource files; it is not possible to create user keyword programmatically.

What we would like to be able to do:

```python
from robot.api import TestSuite

for index in range(10):
    suite = TestSuite('Example Suite')
    test = suite.tests.create('Example Test')
    kw = test.body.create_keyword('Example User Keyword')
    kw.create_keyword('Pass Execution', 'msg')  # this is not currently possible

    suite.run(output=f'output-{index}.xml')
```

**Comment by kkotenko** [comment]
Would your scenario be solved by any of these?

1) Create a resource file with [arguments embedded in the keyword name](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#embedding-arguments-into-keyword-name), load said resource file and overwrite the variable by whatever you are generating dynamically

2) Another approach would be to write your own keyword library, and overwrite the keyword name to use embedded arguments like [so](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#embedding-arguments-into-keyword-names).

If not, could you say why these don't help?

**Comment by Tattoo** [comment]
@kkotenko ,

I don't even need embedded arguments, I can just add my keywords to a resource file or a library:

```robotframework
# res.resource
*** Keywords ***
Example user keyword
    [Arguments]    ${arg}
    Pass execution    msg
```
```python
# gen.py
from robot.api import TestSuite

for index in range(10):
     suite = TestSuite('Example Suite')
     suite.resource.imports.resource('res.resource')
     test = suite.tests.create('Example Test')
     kw = test.body.create_keyword('Example User Keyword', args=['my arg'])

    suite.run(output=f'output-{index}.xml')
```

But the point here is that this is cumbersome, compared to doing this directly from API.

**Comment by DimonLavron** [comment]
@Tattoo hi!

First of all - thank you for this issue. I started using robot framework recently, especially using programmatic API approach, so it helped me with a better understanding of programmatic API.

From my experience so far, I found out that all user keywords related to suite are stored in `suite.resource.keywords`, so you can easily add your user keywords there, for example:

```
from robot.api import TestSuite
from robot.running import UserKeyword

for index in range(10):
    suite = TestSuite('Example Suite')
    user_keyword = UserKeyword('Example User Keyword', args=('${arg}',))
    user_keyword.body.create_keyword('Pass Execution', args=('msg',))
    suite.resource.keywords.append(user_keyword)
    test = suite.tests.create('Example Test')
    test.body.create_keyword('Example User Keyword', args=('my arg',))

    suite.run(output=f'output-{index}.xml')
```

or you can pass your user keyword as dict:

```
from robot.api import TestSuite

for index in range(10):
    suite = TestSuite('Example Suite')
    suite.resource.keywords.append({
        "name": 'Example User Keyword',
        "args": ('${arg}',),
        "body": [
            {
                "name": 'Pass Execution',
                "args": ('msg',),
            },
        ],
    })
    test = suite.tests.create('Example Test')
    test.body.create_keyword('Example User Keyword', args=('my arg',))

    suite.run(output=f'output-{index}.xml')
```

I hope that I understand you correctly and it'll be helpful for you. Let me know if I misunderstand you, maybe I can find another solution that suits better for your needs!

**Comment by pekkaklarck** [comment]
It is true that it isn't currently possible to define a higher level keyword with child keywords in the execution model. Basically a keyword in the execution model represents a keyword call with name and arguments. The keyword to actually run is resolved during execution and can either be a user keyword with child keywords or a library keyword.

Being able to define higher level keywords directly would be convenient in some cases. In addition to making it easier to programmatically create tests with suitable abstraction levels, it would make it easier for library keywords and listeners to create keywords with child keywords. We already have some other related enhancements initially planned to be done in RF 8, so I add this issue to its initial scope as well.

**Comment by pekkaklarck** [comment]
We got a new issue #5257 about adding a BLOCK syntax. If it would be added, it could be used programmatically like this:
```python
block = test.body.create_block(name='Example name. This could be optional.')
block.body.create_keyword('Log', ['Hello!'])
block.body.create_if().body.create_branch(condition='$expr').body.create_keyword('Log', ['Hello in IF!'])
```

The example from the description would then look like this:
```python
from robot.api import TestSuite

for index in range(10):
    suite = TestSuite('Example Suite')
    test = suite.tests.create('Example Test')
    block = test.body.create_block('Example Block')
    block.create_keyword('Pass Execution', 'msg')

    suite.run(output=f'output-{index}.xml')
```

I believe this would be a better programmatic API than making it possible to create user keywords directly. It would mean that `robot.running.Keyword` would continue to represent just a keyword call, we didn't need to make it a hybrid object that could also have its own body, nor would we need to think how arguments work if the keyword isn't even called.

What do @Tattoo and others think about this? I personally think this issue should be closed and #5257 implemented instead.

**Comment by Tattoo** [comment]
I think that would fit the bill, yes

**Comment by pekkaklarck** [comment]
The more I think about this, the more I think that `robot.running.Keyword` having keywords of its own (i.e. having a `body`) would be confusing. The proposed BLOCK syntax would provide a lot better API. Even if we decided not to implement it, I'm sure we can support the functionality requested here with some other approach than changing `robot.running.Keyword`.
