### ISSUE TITLE
Request to set implicit wait as a basic parameter to a keyword

### ISSUE THREAD

**Issue by vyvy3** [robotframework/robotframework#5121]
Our team uses 1.5 min as a basic implicit wait. Sometimes, we need to get results immediately (e.g., is there an element on the page). Since implicit wait is set globally we are failing to structurize scripts nicely and are forced to proceed with the following workaround where we change the global wait, run the keyword, and set it back:
```
${orig}=  Get Selenium Implicit Wait
Set Browser Implicit Wait    1s
${check_abc}=  Run Keyword And Return Status    Element Should Be Visible    xpath=%xpath%
Set Browser Implicit Wait    ${orig}
```
or
```
Set Browser Implicit Wait    1s
${status}=    Run Keyword And Return Status    Page Contains Text    IMAGE_1.png
Set Browser Implicit Wait    ${orig}
```
Can you please suggest ways to accomplish the same logic without waiting for 1.5 minutes and not playing with that "Set Browser Implicit Wait"? Or maybe there is a possibility to add an implicit wait for a specific keyword execution?

Thank you in advance!

**Comment by pekkaklarck** [comment]
This issue tracker is for Robot Framework core, SeleniumLibrary has its own tracker. Please submit the issue there or, if you are mainly trying to find ways to accomplish this conveniently and not proposing new functionality, consider starting a discussion on our Slack or Forum.
