### ISSUE TITLE
Named-only arguments are not trace logged with user keywords

### ISSUE THREAD

**Issue by steradjan** [robotframework/robotframework#5128]
Hi
in robotframework==6.0.2
If arguments are given as shown on the screenshot, the values after list are not displayed in traces, but the values are processed and everything works.

This is the line
```
    Combobox should have options             ${EMPTY}      Range 1    Range 2     convert_unit=ovca
```
![thumb-Clipboard - May 9, 2024 3_35 PM](https://github.com/robotframework/robotframework/assets/169369145/1238f437-0b3d-426f-abe6-1ad327adeb9d)

**Comment by pekkaklarck** [comment]
Thanks for the report. The problem is that named-only arguments aren't trace logged with user keywords. A simple example demonstrating the issue is below. When it's run currently, `${z}='Z'` is missing from the trace log message with `Keyword`.

```robotframework
*** Test Cases ***
Example
    Keyword    X    Y1    Y2    z=Z

*** Keywords ***
Keyword
   [Arguments]  ${x}    @{y}    ${z}
   Log many    ${x}    ${y}    ${z}
```
