### ISSUE TITLE
Collections: Value of `ignore_case` argument accidentally logged

### ISSUE THREAD

**Issue by rauttiz** [robotframework/robotframework#5130]
Some Collections library keywords log info about the ignore_case argument value (e.g. "INFO False") without mentioning what that logged value means. It could be interpreted incorrectly e.g. meaning that the keyword failed.

E.g. "Dictionaries Should Be Equal" keyword logs "INFO False" if the ignore_case argument is False.

That logging seems to come from Collections.py line 1127:        print(ignore_case)

**Version information**
Robot Framework 7.0 (Python 3.11.3 on win32)

**Steps to reproduce the problem**
Running this test will log "INFO foo":
*** Settings ***
Library    Collections

*** Variables ***
&{DICT1}    a=1
&{DICT2}    a=1

*** Test Cases ***
Compare dictionaries
    Dictionaries Should Be Equal    ${DICT1}    ${DICT2}    ignore_case=foo

**Comment by pekkaklarck** [comment]
Thanks for the report. This is caused by a `print(ignore_case)` that I must have used for debugging purposes and accidentally left in 6aec6db03adb82a1639c920f7e6787754ee78919.
