### ISSUE TITLE
Add support for time strings containing "week" values

### ISSUE THREAD

**Issue by ChristopherJHart** [robotframework/robotframework#5135]
Currently, the largest unit of time supported by [time formats](https://robotframework.org/robotframework/latest/libraries/DateTime.html#Time%20string) in Robot Framework is `day`. This issue proposes adding `weeks`/`week`/`w` as supported units of time.

Our primary use case for this is that certain network devices will display uptime values with a maximum value of weeks. For example:
```
switch#show version
<snip>
Cisco IOS Software, C3560 Software (C3560-IPSERVICESK9-M), Version 12.2(55)SE11, RELEASE SOFTWARE (fc3)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2016 by Cisco Systems, Inc.
Compiled Wed 17-Aug-16 13:07 by prod_rel_team
Image text-base: 0x01000000, data-base: 0x02F00000

switch uptime is 11 weeks, 5 days, 3 hours, 7 minutes    <<<
System returned to ROM by power-on
System restarted at 13:16:45 EDT Sat Mar 9 2024
System image file is "flash:c3560-ipservicesk9-mz.122-55.SE11.bin"
```
As it stands right now, we must use a custom keyword to handle this time format. It'd be nice if a keyword like `Convert Time` could handle it effortlessly.

From our perspective, it doesn't make sense to add larger units of time (e.g. months, years, etc.) since the "real length" of those units could be debated and context-sensitive. For example, is a month 30 days or 31 days (or 28, in the case of February?) Is a year 365 days, or 364.25? etc. The "week" unit of time doesn't suffer from this issue, as it tends to be universally considered to be 7 days long.

**Comment by pekkaklarck** [comment]
Implemented in PR #5136 by @ChristopherJHart. Thanks for contribution!
