### ISSUE TITLE
Extended variable syntax does not take effect

### ISSUE THREAD

**Issue by Northxw** [robotframework/robotframework#5137]
Question: Cannot access variables of instantiated objects of classes in variables file in test suite.

Environment: Windows 10 22H2 19045.4412, Python 3.8.10, RobotFramework 5.0, PyCharm 2022.1.4.

My directory structure:
```
D:\PYTHON\LEARNING\LEARN_ROBOT_FRAMEWORK\FORISSUE
│  MyObj.py
│  Test.robot
│
└─__pycache__
        MyObj.cpython-38.pyc
```

My variables file：
```python
# MyObj.py

class MyObj:
    def __init__(self):
        self.status_code = [200, 302, 404, 500, 503]

OBJECT = MyObj()

def get_variables():
    return {
        "OBJECT": OBJECT
    }

if __name__ == "__main__":
    vars = get_variables()
    print(vars)
```

My test case file:
```robotframework
*** Settings ***
Variables    ${CURDIR}${/}MyObj.py

*** Test Cases ***
My TestCase
    # Import Variables    ${CURDIR}${/}MyObj.py
    Log    ${CURDIR}${/}MyObj.py
    Log Variables
    Log Many    @{OBJECT.status_code}
```

PyCharm console output results:
```
D:\Python\virtualenvs\robot2\Scripts\robot.exe -d ../Reports Test.robot
==============================================================================
Test                                                                          
==============================================================================
My TestCase                                                           | FAIL |
Resolving variable '@{OBJECT.status_code}' failed: Variable '${OBJECT}' not found.
------------------------------------------------------------------------------
Test                                                                  | FAIL |
1 test, 0 passed, 1 failed
==============================================================================
Output:  D:\Python\learning\learn_robot_framework\Reports\output.xml
Log:     D:\Python\learning\learn_robot_framework\Reports\log.html
Report:  D:\Python\learning\learn_robot_framework\Reports\report.html
```

Test report screenshot:
![image](https://github.com/robotframework/robotframework/assets/38708989/1955c548-c31c-4c51-bddc-beed585ed84e)

It's not clear to me why when I use the ${OBJECT.status_code} expanded variable syntax in my test case, it doesn't take effect.

If my understanding is wrong, please give me some advice. I look forward to your reply. thanks.

**Comment by pekkaklarck** [comment]
Your module and class both have the same name and in this case Robot [reads variables from the class](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#implementing-variable-file-as-a-class). Changing either name ought to fix the issue.

Incidentally #5141 had exactly the same issue. I believe that's just a coincidence, but if there are more reports related to this, we need to think is there some way to avoid the confusion.
