### ISSUE TITLE
list the IP addresses of all connected devices

### ISSUE THREAD

**Issue by Benyamin-AI-Blox** [robotframework/robotframework#5139]
Hi. Is there any way to list all the ip addresses of connected devices to the local switch ? 
A mechanism/command similar to arp -a to list all the ip addresses.

**Comment by JFoederer** [comment]
I suggest asking this question on one of the active [support channels](https://github.com/robotframework/robotframework?tab=readme-ov-file#support-and-contact). Entering an issue is not the fastest way to receive an answer.

**Comment by pekkaklarck** [comment]
No standard library distributed with Robot has a keyword for this purpose, but it is possible that some external library has. As noted above, questions should be asked on the various support channels, this issue tracker is for bug reports and concrete enhancement requests.
