### ISSUE TITLE
Python global variables not visible if class is created

### ISSUE THREAD

**Issue by dzvancuks** [robotframework/robotframework#5141]
Consider following scenario.
You have a python file with variables and a function
```
helper.py:

MY_VAR = "My variable"

def my_function():
  return MY_VAR

test.robot:

*** Settings ***
Library    helper.py
Variables  helper.py

*** Test Cases ***
Check My Lib
  ${var}=  My Function
  Should Be Equal As Strings  ${var}  ${MY_VAR}  # all good, the MY_VAR is visible for Robot FW after Variable import
```
But if I define a class in Python file then variables are no longer visible outside class definition:
```
helper.py:

MY_VAR = "My variable"

class helper:
  def my_function():
    return MY_VAR

test.robot:

*** Settings ***
Library    helper.py
Variables  helper.py  # now MY_VAR will not be visible in Robot

*** Test Cases ***
Check My Lib
  ${var}=  My Function
  Should Be Equal As Strings  ${var}  ${MY_VAR}  # Fail: Variable '${MY_VAR}' not found.
```
Workaround is to move `MY_VAR` into `class helper` in `helper.py`

_Is there a way to make global variables visible in both Python class and RobotFW?_

I need this so that multi class Python helpers can be created. E.g. gRPC server requires Service class, and I want to define a class that will store handler, all in one .py file. At the same time variables or enums should be shared between those 2 classes and be visible in Robot test.

**Comment by pekkaklarck** [comment]
Your module and class both have the same name and in this case Robot [reads variables from the class](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#implementing-variable-file-as-a-class). Changing either name ought to fix the issue.
