### ISSUE TITLE
`Evaluate` keyword doesn't take attributes added into `builtins` module into account

### ISSUE THREAD

**Issue by mithunmithra** [robotframework/robotframework#5151]
The keyword fails for a particular usecase as follows :
helper file:
```
import builtins

class dummy:
    def __init__(self):
        self.name = 'abc'
        builtins.s = self

    
    def foo(self):
        print('in foo module')
    
    def initialize(self):
        print(self.name)


def dummy_initiliaze():
    dummy().initialize()
```

Testcase file:
```
*** Settings ***
Library           String
Library           Collections
Library           BuiltIn
Library           helper.py

*** Test Cases ***
TC6
   Dummy Initiliaze
   ${res} =    Evaluate    s.foo()
```

When I run this in Robot framework 3.1.2 , the function s.foo() is called and works
But in Robot framework 3.2.2, its erroring out with "Evaluating expression 's.foo()' failed: NameError: name 's' is not defined nor importable as module"
Have discussed the same in slack forum, thread : https://robotframework.slack.com/archives/C3C28F9DF/p1718686445500879

**Comment by pekkaklarck** [comment]
I don't think modifying `builtins` like this is a good idea in general, but because fixing the issue seems to be easy, I don't see why it shouldn't be done either.

**Comment by pekkaklarck** [comment]
Raised the priority slightly because this usage used to work so it being broken is a regression. It cannot be too bad a regression, though, because nobody had reported it earlier.
