### ISSUE TITLE
Option like --rerunfailed but to rerun failed tests automatically x number of times

### ISSUE THREAD

**Issue by kumaraish** [robotframework/robotframework#5162]
A user can run the same test suite(s) multiple times - but only re-run the failed tests. 
Afterwards she can merge the results into a single results file using rebot as documented in [Robot Framework User Guide](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#merging-outputs)

```
robot --output original.xml tests                          # first execute all tests
robot --rerunfailed original.xml --output rerun.xml tests  # then re-execute failing
rebot --merge original.xml rerun.xml                       # finally merge results
```

Add an option like --rerunfailed(2) so that robot can automatically retry failed tests N number of times and produced a final report
For example:

1. Let's say there are 2 suites and 5 tests in each suite
2. Execution is started with `robot --rerunfailed(2) tests/` 
3. During initial run, all tests in first suites pass, while 3 tests failed in second suite
4. Once initial run completes, robot should automatically retry tests once again - only the 3 failed tests in second suite.
5. Let's say 1 test pass in second run, 2 still are failed
6. Robot should retry a second time (since we gave --rerunfailed(2)) 
7. Let's say 1 test pass again. 1 remain failed
8. Robot should produce a final report which has 1st test with all tests passed, 2nd suite with 4 pass and 1 passed

**Comment by automatewithsunny** [comment]
This will cause an issue if you are using data driver with robot framework. 
Alternatively you can create a listener and call it in the robot or pabot command. 
`sudo pabot --testlevelsplit --processes 100 --variable TESTDATA_FILENAME:testdata.xlsx ---variable DEVICE_NAME:$DEVICE_NAME --variable TESTDATA_FILENAME:testdata.xlsx --variable APPLICATION_URL:https://preprod.tripjack.com/nav/ --variable TESTDATA_FOLDER:Automation --listener RetryFailed:2 -d output ./TestCases`
