### ISSUE TITLE
Some keywords are not fetched from variables section

### ISSUE THREAD

**Issue by isar99** [robotframework/robotframework#5166]
When I am trying to call 'Get File' method or 'Split to lines' method from the variables section, I am not able to add it and use it.

`*** Variables ***
${abc}=    Get File    ./abc.txt
${abc_line_split}    Split to lines    ${abc}`

This are lot more keywords that are not allowed. 
So, user should be given flexibilty.

**Comment by pekkaklarck** [comment]
Variable definitions in the Variables section are static and you cannot use keywords there. We have plans to add inline keyword call support (#3187) and that would allow keyword calls also here.
