### ISSUE TITLE
[Bug] Testcase with [...] cannot specify through "--test" option

### ISSUE THREAD

**Issue by Zoupers** [robotframework/robotframework#5174]
With Test.robot like below:
```robotframework
*** Test Cases ***
TestName-Contain-[1,1]
    Log To Console    message
```

When I run `robot --test "Test.TestName-Contain-[1,1]" ./Test.robot`, it failed to find the testcase.
![image](https://github.com/user-attachments/assets/ecb774e8-0607-4ac0-b664-2aa5c2d5a691)

**Comment by pekkaklarck** [comment]
This is due to matching using glob patterns and `[...]` being a wildcard. See the [User Guide](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#simple-patterns) for more information and for details how to escape special characters.

**Comment by Zoupers** [comment]
Thanks, adding `[]` around the special characters helps me fix the problem.
