### ISSUE TITLE
Rounding error leads to bad display of status color bar

### ISSUE THREAD

**Issue by gohierf** [robotframework/robotframework#5177]
Observed on RF7.

When I have: 1 successful test, 4 failed and 1 skipped; the report badly rounds the proportion of each status, ending up in this weird display:
![image](https://github.com/user-attachments/assets/1e8d74d8-52c4-495f-a09e-13265db7d9e0)

Here is the HTML element:
![image](https://github.com/user-attachments/assets/3877b2eb-f296-4d85-8bae-4856deee6645)

The same issue is present on both report and log files.
It can be reproduced on my own installation and online playground.

It seems caused by a bad rounding of 1/6, which is slightly less than 16.7%, so that 1/6+4/6+1/6 = 100.1% when 1/6 is rounded to 16.7%.

Interestingly enough, the report is produced properly in case of 4 success, 1 fail and 1 skip.

Here is the code to reproduce:
```robot
*** Test Cases ***
Test 1
    Pass Execution    message
Test 2
    Fail
Test 3
    Fail
Test 4
    Fail
Test 5
    Fail
Test 6
    Skip
```

**Comment by pekkaklarck** [comment]
Thanks for the report. Need to think what's the best way to update the algorithm to avoid this.

**Comment by pekkaklarck** [comment]
The algorithm that calculates widths actually has logic to avoid widths adding up to over 100% due to rounding errors, but due to floating point math being imprecise it doesn't work properly in some cases.
