### ISSUE TITLE
A process stops printing data in a while loop when I use "Process" library to start this process in background

### ISSUE THREAD

**Issue by fon1105** [robotframework/robotframework#5185]
OS: Windows 10
Python: 3.12.0
Robotframework: 7.0.1

I use "Process" library to start this process(print.py) in background. The process will keep writing data to a file in a while loop.
**Start Process     python     print.py**

However, the process will suddenly stop print data to a file due to unknown reason while running test cases.

Could you help check and solve this issue? Thanks.

**Comment by fon1105** [comment]
@pekkaklarck 

Thank you for your reply.

You are right, the issue should be caused by the output buffers getting full.
If I redirect both stdout and stderr to file the issue will not happen.
Is there any limitation about the output buffers with robotframework?

If I manually run the original print.py in another terminal instead of robotframework, the issue will not happen.

**Comment by pekkaklarck** [comment]
The output buffer size is determined by the operating system. The reason there's no problem when you run it from the cli is that the terminal consumes the output from the buffer so it doesn't get full. When you use the process library, nobody consumes it until the process has finished. We probably could implement some system for consuming the content, but it would likely require threads and be fairly complicated. Redirecting outputs to files solves the issue so easily that spending time for it hasn't been considered worth the effort.
