### ISSUE TITLE
Different behaviour in local machine and pipeline

### ISSUE THREAD

**Issue by shantosh123** [robotframework/robotframework#5197]
I am working on one project where i ahve setup everything and running my test cases using Pycharm which is perfectly running in my local machine and when i am trying to run that test cases on pipeline some of those xpath are not found. Why this is happening on pipeline? what is the best solution to fix that issues? is there any straight way to do that? 
This is happening only on some xpath. I have tried to fix using different ways (running without headless mode) still not working. 

Thanks in advance

**Comment by oboehmer** [comment]
I would suggest you raise this question in Slack, please join the robotframework channels [here](http://slack.robotframework.org/).. I would suspect a config issue somewhere, rather than a robotframework bug

**Comment by shantosh123** [comment]
Hi, 
Thank you @oboehmer

**Comment by pekkaklarck** [comment]
Seems to be an environment related issues, not a bug in Robot Framework.
