### ISSUE TITLE
Add `--console-width` value from CLI option to built-in variable  `&{OPTIONS}`

### ISSUE THREAD

**Issue by gohierf** [robotframework/robotframework#5200]
I heavily use the built-in keyword [`Log To Console`](https://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Log%20To%20Console) with `no_newline` true and a carriage return (\r) to keep the user informed about what is going and to not worry that the test is stuck.
To keep it clean and to refresh the line properly, I would need to know the ["console width"](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#console-width) value.
But it does not seem available from the built-in variables.
Would it be possible to add it to built-in variable &{OPTIONS}, even if the default value is used?
For now, it seems I can only get it by setting an environment variable. (edited)

**Comment by pekkaklarck** [comment]
This was trivial enough to be added in RF 7.1.
