### ISSUE TITLE
Use ```Execute JavaScript navigator.clipboard-writeText``` to copy the value in the input tag, but the clipboard does not have any data

### ISSUE THREAD

**Issue by siyiyimiaozhong** [robotframework/robotframework#5207]
When using the **robotframework-seleniumlibrary**, I tried using the **Click Button** to click on the copied button on the website. But there is no data in the cutting board.
Finally, I executed the method triggered by the click event of the copy button on the website using **Execute JavaScript**, but still did not write the corresponding data to the clipboard.

Here is my code:
```
${checksum_value}=     Get Element Attribute    id=checksumvalue    value
Execute JavaScript  navigator.clipboard.writeText(document.getElementById('checksumvalue').value);
Sleep    1s
${pasted_text}=     Get Clipboard Text
Should Be Equal    ${checksum_value}    ${pasted_text}
```
he implementation of the keyword **Get Clipper Text** is as follows
```
from robot.api.deco import keyword

import pyperclip
 

@keyword('Get Clipboard Text')
def get_clipboard_text():
    return pyperclip.paste()

```

According to the log, it can be seen that the data was not successfully written to the clipboard, and the data obtained from the clipboard is still the manually copied data previously.

I am curious about where the problem lies that led to the current situation

**Comment by siyiyimiaozhong** [comment]
After reviewing the information, it was found that the reason for the failure of **navigator.clipboard.writeText** may be:
In the process of automated testing, when the browser runs in headless mode, it usually does not support interaction with the system clipboard, as this may involve cross domain security issues and headless environments do not have context for user operations.
Causing this API to fail.

Is there any way in the **robot-framework** to allow browsers to interact with the system clipboard in headless mode?

**Comment by pekkaklarck** [comment]
This issue tracker is for Robot Framework core and SeleniumLibrary has it's own tracker where issues related to it should be submitted. For questions it is generally better to use our Slack or Forum.
