### ISSUE TITLE
TestCase Hang when using SeleniumLibrary Choose File after upgrading the robot framework from 3.1.2 to 3.2.2

### ISSUE THREAD

**Issue by frank007love** [robotframework/robotframework#5213]
We launched the robot framework with java.
Recently, we upgraded the robot framework from 3.1.2 to 3.2.2.
We found the test cases will hang and timeout of executing the SeleniumLibrary.Choose File with 1MB file.

**Here are my environment:**
RobotFramework: 3.2.2
Selenium: 3.141.0
SeleniumLibrary: 3.3.1
Remote Selenium Version: selenium-server-standalone-3.141.59

I used wireshark to observe the packages. It seems the newer version lost some data.
![image](https://github.com/user-attachments/assets/7edd7ec1-4a74-46be-a341-c642282ec9b8)

I also traced the code, and found the issue might cause by the socket.sendall. Note that the data is no different between 3.1.2 and 3.2.2.
![image](https://github.com/user-attachments/assets/f55e8400-ae69-4707-a6b3-277e84f0b57a)

Is there idea to fix the issue?

**Comment by frank007love** [comment]
[testfile.txt](https://github.com/user-attachments/files/17082529/testfile.txt)
Here is my test file. Only 167KB but can duplicate the issue. 
Maybe it's caused by the Content-Length over 65536?
![image](https://github.com/user-attachments/assets/bc7ae989-ae7b-445d-807d-fba8acf8f1ce)

**Comment by pekkaklarck** [comment]
I don't have any idea what could cause this problem. It sounds more like a SeleniumLibrary or Selenium problem, but if you have only upgraded Robot Framework, then the issue could also be in it. Anyway, these are old Robot Framework and SeleniumLibrary versions that we don't support anymore. If you are using Jython, a related problem is that we don't support Jython (or Python 2) anymore either.

In this situation you unfortunately need to debug this further yourself. If there turns out to be something in Robot that could be fixed, we can consider creating a new maintenance release. The last Jython compatible release is 4.1.3 and the new one would then be 4.1.4.

**Comment by frank007love** [comment]
I putted the _socket.py from robot framework 3.1.2 in Lib folder, fixed compile error, and the issue is fixed.
![image](https://github.com/user-attachments/assets/f3c0b47b-a939-4859-af46-88336edbae7e)

I found the issue is caused by self.channel.bytesBeforeUnwritable() in _socket.py, and I fixed by checking the remaining data length.
![image](https://github.com/user-attachments/assets/901afe9f-8264-4166-bc3d-e95a38491468)

`    @raises_java_exception
    def send(self, data, flags=0):
        # FIXME this almost certainly needs to chunk things
        self._verify_channel()
        if isinstance(data, memoryview):
            data = data.tobytes()
        data = str(data)  # FIXME temporary fix if data is of type buffer
        log.debug("Sending data <<<{!r:.20}>>>".format(data), extra={"sock": self})

        if self.socket_type == DATAGRAM_SOCKET:
            packet = DatagramPacket(Unpooled.wrappedBuffer(data), self.channel.remoteAddress())
            future = self.channel.writeAndFlush(packet)
            self._handle_channel_future(future, "send")
            return len(data)

        if not self._can_write:
            raise error(errno.ENOTCONN, 'Socket not connected')

        total_sent = 0
        while total_sent < len(data):
            bytes_writable = self.channel.bytesBeforeUnwritable()
            if bytes_writable == 0:
                break  

            if bytes_writable > len(data) - total_sent:
                bytes_writable = len(data) - total_sent

            sent_data = data[total_sent:total_sent + bytes_writable]
                                                   
                                                                                     

            future = self.channel.writeAndFlush(Unpooled.wrappedBuffer(sent_data))
            self._handle_channel_future(future, "send")
            log.debug("Sent data <<<{!r:.20}>>>".format(sent_data), extra={"sock": self})

            total_sent += len(sent_data)

        return total_sent`

**Comment by pekkaklarck** [comment]
Great that you got the problem fixed!

That `_socket.py` isn't part of Robot Framework itself. It's most likely from Jython, either from your local Jython installation or from the standalone robotframework.jar that contains embedded Jython.
