### ISSUE TITLE
Python3.13 remove telnetlib

### ISSUE THREAD

**Issue by honglei** [robotframework/robotframework#5217]
https://peps.python.org/pep-0594/#telnetlib
Deprecated since version 3.11, will be removed in version 3.13: The [telnetlib](https://docs.python.org/3/library/telnetlib.html#module-telnetlib) module is deprecated (see [PEP 594](https://peps.python.org/pep-0594/#telnetlib) for details and alternatives).

```
￼ File "D:\PythonPrj\gms\ncc_check\robot\robot_main.py", line 11, in <module>
  from robot.libraries import Telnet
File "C:\Python313\Lib\site-packages\robot\libraries\Telnet.py", line 21, in <module>
  import telnetlib

builtins.ModuleNotFoundError: No module named 'telnetlib'
```

**Comment by pekkaklarck** [comment]
Yes, `telnetlib` will be removed in Python 3.13, but there already exists an external [telnetlib-313-and-up](https://pypi.org/project/telnetlib-313-and-up) that can be used instead. We are also planning to make Robot's Telnet library an external library (#3537), but it requires setting up the new external project first.
