### ISSUE TITLE
[Improvement] - Use markdown standard for bold text in Documentation section

### ISSUE THREAD

**Issue by harmin-parra** [robotframework/robotframework#5218]
According to the markdown specification (https://www.markdownguide.org/basic-syntax/#bold), bold text should be surrounded by double asterisks `**bold text**` while RobotFramework (https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#inline-styles) only uses a single asterisks `*bold text*`

Could RobotFramework comply with the markdown specification for bold text ?

**Comment by pekkaklarck** [comment]
I guess we could support Markdown style `**bold**`, but for backwards compatibility `*xxx*` would be bold as well.

It could be better to add full Markdown support for documentation instead. There are two problems with that, though:
1. We need to agree on how to specify the format. It would be easy to allow using a dedicated prefix like `MARKDOWN This doc uses **Markdown**!`, but needing to use it with all docs would be annoying and a file level or global configuration would be better. 
2. Python doesn't have built-in Markdown support and we needed to use an external module for parsing it. This causes some more problems:
   - We don't want Robot to have mandatory dependencies to keep installing it easy. This requires making Markdown an optional dependency (using Markdown docs would fail without a suitable module being installed) or including it in our code base to make it always available.
   - There are multiple Python modules supporting Markdown. Someone needed to investigate which one would work best for us.

If you think full Markdown support would be useful, please submit a separate issue!

**Comment by harmin-parra** [comment]
As first step, maybe we can start supporting bold text with these 2 notations:
```
**bold**
__bold__
```

**Comment by harmin-parra** [comment]
To tell the truth, i don't feel capable of implementing the bold support

**Comment by emanlove** [comment]
How would using markdown for documentation work with docstrings and Python tooling around documentation using docstrings? I would be interested in seeing what the current state of Python documentation tools allow for having docstrings be in markdown format instead of reST and whether this severely limits common tools and practices? Or if markdown has become widely accepted within docstrings and all that one could do with them previously?

**Comment by pekkaklarck** [comment]
@emanlove , Markdown is getting more an more popular also with Python projects. For example, [mkdocstrings](https://mkdocstrings.github.io) only supports Markdown and here's a [concrete example from Pydantic source code](https://github.com/pydantic/pydantic/blob/bb7bd963e206a3a2eb0676e4de92d53eedb26332/pydantic/networks.py#L115). We'll also switch to Markdown with Robot's API docs as part of the User Guide refresh project.

**Comment by pekkaklarck** [comment]
@harmin-parra Adding the support for bold would be pretty easy, but syntax changes always have a backwards incompatibility concerns. I believe it's best to spend all efforts for adding real Markdown support instead.
