### ISSUE TITLE
Support stopping execution using `robot:exit-on-failure` tag

### ISSUE THREAD

**Issue by douglasdotc** [robotframework/robotframework#5219]
The command line argument `--exitonfailure` has been very useful. If we can have a reserved tag `robot:exit-on-failure` that would be great so that the same behavior can be enabled in individual test suite. For example:

`suite1.robot`:
```
*** Settings ***
Test Tags    robot:exit-on-failure

*** Test Cases ***
Pass
    Pass Execution    Pass this

Scenario 1
    Simple Task 1
    Fail
    Simple Task 2     # Will not execute

Scenario 2    # Will not execute
    Simple Task 1
    Fail
    Simple Task 2

Scenario 3    # Will not execute
    Simple Task 1
    
*** Keywords ***
Simple Task 1
    Log To Console     ${\n}Simple Task 1...${\n}

Simple Task 2
    Log To Console     ${\n}Simple Task 2...${\n}
```

Output, something like this:
```
==============================================================================
Suite1                                                                       
==============================================================================
Suite1.Test                                                                  
==============================================================================
Pass                                                                  | PASS |
Pass this
------------------------------------------------------------------------------
Scenario 1                                                            
Simple Task 1...

Scenario 1                                                            | FAIL |
AssertionError
------------------------------------------------------------------------------
Scenario 2                                                            | SKIP |
Skipped due to exit-on-failure
------------------------------------------------------------------------------
Scenario 3                                                            | SKIP |
Skipped due to exit-on-failure
------------------------------------------------------------------------------
Suite1.Test                                                           | FAIL |
4 tests, 1 passed, 1 failed, 2 skipped
==============================================================================
Suite1                                                                | FAIL |
4 tests, 1 passed, 1 failed, 2 skipped
==============================================================================

**Comment by pekkaklarck** [comment]
Sounds useful. I added this to RF 7.2 scope and already checked that implementing this requires changing only one line. This also needs some tests and documentation update, but the work is nevertheless very small.

**Comment by omn32** [comment]
Hello Everyone,
I use robotframework==7.3.2 and this behavior seems not work.
After FAIL, the others Tests should be SKIP

<img width="891" height="451" alt="Image" src="https://github.com/user-attachments/assets/d89ed8c0-7be8-4a43-99dd-8a67bb81fe88" />

<img width="485" height="648" alt="Image" src="https://github.com/user-attachments/assets/9336cfce-99a8-47a7-90e1-13ccfc3837e7" />

Thx

**Comment by pekkaklarck** [comment]
Unfortunately tests that aren't run due to the exit-on-failure functionality get the FAIL status instead of SKIP. The reason is that the exit-on-failure functionality predates the SKIP status and we haven't yet changed the status tests get on this case. That sounds like a trivial change, but there are subtle design decisions to be made in some cases. There's an issue about the change (#4170) and I hope we get it sorted out in RF 8.

**Comment by sgaraiEN** [comment]
I have a few questions. @pekkaklarck or whoever the best person is, please answer.
1. This robot:exit-on-failure tag doesn't affect suite teardown? Or the suite teardown steps also got skipped?
2. putting this tag on the last test case of the suite dosen't make any sense right? 
3. Can we put some other customised tag with this built in reserved tag for a single test case?
