### ISSUE TITLE
Allow setting variables with TEST scope in suite seup/teardown (they should not be be visble for tests)

### ISSUE THREAD

**Issue by gohierf** [robotframework/robotframework#5223]
**Description**
For better readability, I sometimes use variables with TEST scope, which allows passing a value to multiple keywords within a single test, ensuring that the value is not misused in another test.

Unfortunately, when I want to reuse the keywords that rely on this scope, in Suite Setup and Suite Teardown, I encounter this error:  `Cannot set test variable when no test is started.`

**Current Workaround**
The workaround I have found is to use SUITE scope. This allows the keywords to be reused in Suite Setup and Teardown. However, this makes the use of the SUITE scope confusing, as one might wonder why SUITE scope is used when TEST scope would be more appropriate.

**Enhancement Proposal**
Would it be possible to allow TEST scope in Suite Setup and Suite Teardown as well?

Variables with TEST scope used in these setups should not be accessible outside of Suite Setup or Suite Teardown. If broader access is required, then SUITE scope should be used.

**Example Code**
In this [example](https://robotframework.org/code/?codeProject=N4IgdghgtgpiBcIDCBXAzgFwPZQAQGMsATOAGhBLXwCcBLABw1qzARBHIDNaAbGNBAG1Q3PgDlocRBn4YAdNSwAjLBg4hCYGVrYAqfbgDKMDEzABzNLn26AOmEMpaMoyZT1cn3AFEAHtHo+XABpGABPAHcsaiJcABUsXAAlGHQYe0dnGHiYCBisCLAvH38oQOzQyOjYhOTUtHSwONlXDHdivwCgyqiY+MSUtPtmzBy8ogKir06y7vDemoH6xvsbHNGkCAarG2HZew7S8pD56v66obBVgx7qnf0Mk1wAWTDcADU82gglPgOvd4AQSSXgAJMBngBNXAAfSBSQAkoCAEIAGW8AF8vK9cAA3L4-IL4ngobKeKhYegwAC8cW8hji9nsqKw5heb0+dEJjWKLLZtSQLDQWCCnnBUNh8KRaMxTLAM2Otz6tUGDX+nmMGHZHwJvx5Xj52s53z19hAGIAuuQSHRcTAiAAFRQAKxg+DU8E4EB4DXIihUGHeMGoaGYrEQAHY5ABGdT+1SA6iWBDADF+mAARyc1BgsC0AngggtGKAA), I need to use SUITE scope otherwise I get  `Cannot set test variable when no test is started.`

```robot
*** Settings ***
Suite Setup    Example Keyword To Reuse
Suite Teardown    Example Keyword To Reuse
Test Setup    Example Keyword To Reuse
Test Teardown    Example Keyword To Reuse

*** Test Cases ***
Test
    Example Keyword To Reuse

*** Keywords ***
Set My Variable
    VAR   ${MY _VARIABLE}   My variable value   scope=TEST

Log My Variable
    Log To Console   ${MY _VARIABLE}

Example Keyword To Reuse
    Set My Variable
    Log My Variable
```

**Comment by m-usmani** [comment]
How do you handle a variable with same name but a different value added to test scope in multiple tests?

**Comment by gohierf** [comment]
> How do you handle a variable with same name but a different value added to test scope in multiple tests?

Wellm it does not change anything to the Test scope. Values for each variable are still only available within each test only.
I don't want the value from the test to be available in Suite Setup or Suite Teardown. But I want the value defined in a Suite Setup keyword to be available to other keywords in the Suite Setup. Same for Suite Teardown.

**Comment by m-usmani** [comment]
What should be logged in suite teardown?

`*** Settings ***
Suite Setup    Example Keyword To Reuse
Suite Teardown    Log My Variable
Test Setup    Example Keyword To Reuse
Test Teardown    Example Keyword To Reuse

*** Test Cases ***
Test
    Example Keyword To Reuse

Test 2
    Another Keyword To Reuse

*** Keywords ***
Set My Variable
    VAR   ${MY _VARIABLE}   My variable value   scope=TEST

Set My Other Variable
    VAR   ${MY _VARIABLE}   My other variable value   scope=TEST

Log My Variable
    Log To Console   ${MY _VARIABLE}

Example Keyword To Reuse
    Set My Variable
    Log My Variable`

Another Keyword To Reuse
    Set My Other Variable
    Log My Variable`

**Comment by gohierf** [comment]
> What should be logged in suite teardown?

Same thing as if you were doing it in a test case:  it should throw the usual error `Variable '${MY _VARIABLE}' not found.`

This situation is not specific to teardown, you would get it in test cases too, if you are trying to use a TEST scope variable but do not define it before. For instance:

```robotframework
Test 3
    Log My Variable
```

To not get this error, one should set the variable previously (aka use the keywords properly), or use SUITE scope (which is not the same need).

[Currently](https://robotframework.org/code/?codeProject=N4IgdghgtgpiBcIDCBXAzgFwPZQAQGMsATOAGhBLXwCcBLABw1qzARBHIDNaAbGNBAG1Q3PgDlocRBn4YAdNSwAjLBg4hCYGVrYAqfbgDKMDEzABzNLn26AOmADEhlLRlGTKerm+4AogA9oej5cAGkYAE8AdyxqIlwAFSxcACUYdBh7BycXNwSYCDisKLAfXAAZLHNcAFkI3AA1QtoIJT4s-Mx3DE8ygKCQ8OjY+KTU9LRMx06MRIKikr7AqGCYMMiYuMTktIz7exs5rqQISasbexn7JYG1oc3RnYmpy9lcACZrnwBBMFUACxg1HWwy2Y12k32YBmuAAzF9vJVqnVGs1Wu0wAcDPcRud9PZjLMUU06OipmUGt8Uj4ACTAGoATVwAH1KSkAJLfABC5V8AF8fCiAG5otprEU8FBrbxULD0GAAXgSvkMCShhNq9QA8hhAcCSS0xQjGlTafSmayqZyefzBfUAUDcCLSWKnRBJdLcLL5UqVWrMWAkZrUS6MWUg2MkCw0FgQt46YyWWzrby+VD+itBhsRttxntSj4NcTRWGfEHi6GXmBfg7gTiwU982Ui9rdY6DWTjeX6h2xSA+QBdcgkOhCmBEAAKigAVjB8Gp4Jx3ZNyIoVBgGkC0MxWIgAOxyACM6jXqm+1EsCGAfNXMAAji5qDBYFoBPBBAO+UA), I get `Setting variable '${MY _VARIABLE}' failed: Cannot set test variable when no test is started.`, for the suite setup, test setup and test teardown where the keywords are used properly.

**Comment by pekkaklarck** [comment]
I think this is a good idea, but I'd actually extend the proposal a bit. I believe it would be convenient if a variable set with a TEST scope in a suite setup would be available in a suite teardown. This is the same approach we handle libraries using the TEST scope: suite setup/teardown share the same library instance and each test gets their own instance.

This could be fairly easy to implement so I'll add this tentatively to RF 7.2 scope. If it's not easy, I'll move it to some later release or, if it's really complicated, close the issue altogether.

**Comment by pekkaklarck** [comment]
It wasn't as easy to implement as I thought, but my prototype worked and I decided to polish it, add tests and write documentation to get this done.

**Comment by gohierf** [comment]
Hello, I was testing this fix, and came across an unexpected (at least to me) behaviour.

At first, everything looks as expected: the suite setup, suite teardown, test setup and test teardown can now use TEST scope without failing. Moreover, if I try to get the value of the variable before setting it, I get the “default” value I defined at SUITE scope in the `*** Variables ***` section.

However, I notice that if I **set** the variable with TEST scope in the suite setup, then it somehow “disappears” from SUITE scope. I don't get the “default” value any more. I think this might be considered a bug. I don't know if there is any practical usage for that situation, but I definitely did not expect it to behave like that (I expected the default suite value).

For instance, with this code ([here on playground](https://robotframework.org/code/?codeProject=N4IgdghgtgpiBcIDCBXAzgFwPZQAQGMsATOAGhBLXwCcBLABw1qzARBHIDNaAbGNBAG1Q3PgDlocRBn4YAdNSwAjLBg4hCYGVrYAqfbgDKMDEzABzNLn26AOmADEhlLRlGTKerm+4AUugxcABksc1wAWQBPXAA1CDoIJT57Z1cYdwxPHwzcAEEwImDQiOi4hKT0n1S3Y0z6FJc3ABUYeKIsAHcwbJz8wpCwqNj42kS+bOr0lrbOsHt7FswMrKqTPIKiwdKRscrvRcDazwXZXGnqdq6e2vX+4qGy0Yrsg7PWi9n5sBth8r4rGz2AAkwHCAE0APpNACihiaEMMSAA8gAFaEQmK5ABKAF8et4SJwICgeIEAG4QHgodKcRR4NCNdJULD0GBfH6vJAQND8az6E5LACM9gmaz6mxKvye4x8AElugcBYEAEwinz+JYDSWPXZfew-ADSMEiHSwFwB-LAGsCWoeOwqau8WqaWFwSBYaCwMu8+BQ1GoMC0uApVJg8FwIPBUNh8MRqPRmNxX2yKTFG1t2z+bO6PkEuWo5hQsC0aAAutkQSHqTjHRKXW6PV69rgvYUq2GI6DITC4QjkWiMdiaznvImfJHuzG+-HB7iK8B23jsszWQBeHtNWvO13usCe724MAwDrBynU8MT6O9uMDxPDkA40vkEh0MkwIgoxQAKxg+DU8CJHgeXIRQVAwGIYGoNBmFYRAAHY5GVRD1FA1R80sBBgBxECYAARxcANiwwAR4EEUscSAA)), I get these errors in test setup and teardown:

> Setup failed:
> Variable '${MY_TEST_SCOPE_VAR}' not found.
>
> Also teardown failed:
> Variable '${MY_TEST_SCOPE_VAR}' not found.

```robot
*** Settings ***
#Suite Setup    Just Log My Variable
Suite Setup    Set And Log My Variable    Suite Setup
Suite Teardown     Set And Log My Variable    Suite Teardown

Test Setup    Set And Log My Variable    Test Setup
Test Teardown     Set And Log My Variable    Test Teardown

*** Variables ***
${MY_TEST_SCOPE_VAR}       default value from suite scope

*** Test Cases ***
Test 1
    Set And Log My Variable    In Test
Test 2
    Just Log My Variable


*** Keywords ***
Just Log My Variable
    Log To Console    current value: ${MY_TEST_SCOPE_VAR}

    
Set And Log My Variable
    [Arguments]    ${value}
    Log To Console    old value: ${MY_TEST_SCOPE_VAR}
    VAR   ${MY_TEST_SCOPE_VAR}    ${value}     scope=TEST
    Log To Console    new value: ${MY_TEST_SCOPE_VAR}

```

Just switch `Suite Setup` to `Just Log My Variable` and test setup and teardown work as expected.

**Comment by pekkaklarck** [comment]
I can reproduce the issue you mentioned @gohierf and created issue #5399 about it.

Please next time create an issue directly instead of only commenting an already closed issue. I got so many notifications about issues that I often miss comments and this one I just noticed by accident. Anyway, I hope that fixing the problems isn't too big task and we can do that already in RF 7.3.
