### ISSUE TITLE
[Feature] Gherkin and BDD

### ISSUE THREAD

**Issue by 42sol-eu** [robotframework/robotframework#5225]
We are evaluating the use of Robot-Framework for our new requirement and acceptance tests that will be implemented via Jira, Confluence and XRay.
The test cases will be implemented in the Gherkin language and need not only the Given-When-Then keywords but also scenarios and scenario outlines like

```
Feature: GPS Location Validation
  In order to verify the accuracy of the GPS system
  As a user
  I want to ensure the correct GPS coordinates are returned for known cities

Scenario Outline: Verify GPS coordinates for cities
  Given I request the GPS coordinates for "<city>"
  When the system returns the coordinates
  Then the latitude should be "<latitude>"
  And the longitude should be "<longitude>"

Examples: Cities and their GPS coordinates
  | city           | latitude  | longitude   |
  | New York       | 40.7128   | -74.0060    |
  | Los Angeles    | 34.0522   | -118.2437   |
  | London         | 51.5074   | -0.1278     |
  | Tokyo          | 35.6762   | 139.6503    |
  | Paris          | 48.8566   | 2.3522      |
  | Sydney         | -33.8688  | 151.2093    |
  | Berlin         | 52.5200   | 13.4050     |
```

Will this be supported in the Robot-Scripting-Language in the active release or is it planned to be implemented in the upcoming future?

**Comment by d-biehl** [comment]
This is implemented in a very early state with a custom parser, see here

https://github.com/robotcodedev/robotframework-gherkin-parser

**Comment by pekkaklarck** [comment]
There are no concrete plans to add full Gherkin syntax support to Robot at the moment, but I recommend you to look at the custom Gherkin parser by @d-biehl mentioned above. If it gets popular, we could consider integrating with with the core a bit more tightly. I don't know what else we could really do than add support for install extras like `pip install robotframework[gherkin]` and mentioning this in the User Guide. The latter is something we could do very easily already now.

**Comment by 42sol-eu** [comment]
Thank you @pekkaklarck for the fast and complete response. We are on the fence with robot framework because of this major feature. 

Behave - the second candidate would not require to switch the pytest runner we are currently using. 

I will have a closer look and maybe discuss with @d-biehl if his solution would meet our requirements.
