### ISSUE TITLE
How to hide robot framework code base and share only binary file to client

### ISSUE THREAD

**Issue by kaushikp-office-account** [robotframework/robotframework#5233]
I want to convert the robot code into binary executable file. And execute this binary executable file on clients end. So that client will not able to see my code. and execution will done clients end

**Comment by pekkaklarck** [comment]
This is not supported by Robot Framework itself and in general, as already commented above, pretty hard with Python. There are various tools that allow creating executables from Python code and you ought to be able to package tests there as well. The hard part will be preventing those who get the executable from opening it and seeing the code if they want to.

If you have further questions related to this, please use our Slack or Forum. This issue tracker is for bug reports and enhancement requests.

**Comment by kaushikp-office-account** [comment]
> Is it about the confidentiality of your code ? Because Python is not very good at it. And it is not easily done with other languages neither. What goal are you trying to achieve ? Just shipping a binary (without any dependencies) ? Or preventing users to tamper with the code ? Or even to know that it is Robot Framework inside ?

we have certain test-cases robot scripts and we don't want them to replicate those test cases and test steps on their own,also if possible we wanted to hide the fact that we are using robot framework.
