### ISSUE TITLE
Test Case metadata or something similar

### ISSUE THREAD

**Issue by ilfirin-ms** [robotframework/robotframework#5234]
Greetings,

I am wondering, if there is better way to add "metadata" to test case for later evaluation/parsing.

Right now I am forced to provide own test message and in it use some own format (json?) for mandatory information, as measured values and such.

I am looking for something like [pseudo code]

```
Test Case Board Voltages
    [Documentation]    Main supply voltages according to 1.5.3 section of document EAS5161 test requirement
    ${v3V3} =     Library.Measure      something
    ${result} =     test value somehow
    RECORD     "1.5.3 3V3 Power Supply"    ${v3V3}    ${result}
    ${v5V0} =     Library.Measure      something
    ${result} =     test value somehow
    RECORD     "1.5.3 5V0 Power Supply"    ${v5V0}    ${result}
   ...
```

And such.
Then look into XML output and be able to find these record and parse them out easily, with known format provided by RF, instead of I do it somehow by appending to test message, which could lead and leads to bloated test messages.

**Comment by Lenormju** [comment]
You can use Listeners ([link](https://docs.robotframework.org/docs/extending_robot_framework/listeners_prerun_api/listeners)).
> v3 also allows you to read and modify the attributes of the test case

So you can edit the tests after they have run for example, so that the data you need is only in the output.xml file.
Or you can write it into other files, or do anything you want.

**Comment by pekkaklarck** [comment]
We are planning to add metadata to tests in RF 7.2 (#4409).
