### ISSUE TITLE
One case where logical operators evaluation precedence different from Python, 

### ISSUE THREAD

**Issue by HelioGuilherme66** [robotframework/robotframework#5236]
I was expecting Robot Framework to have the same evaluation as in Python, but it does not.
In this case the first expression results in False in Python, but in Robot Framework causes the second expression to be evaluated. Simple example:
```
from math import sqrt
if len("")>0 and sqrt(-1):
  print('OK')
```
In Python can be parsed, because `sqrt` would not be evaluated after a negative value in the `and` expression.

This is my test in Python:
```
Python 3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> result=""
>>> a=len(result)>8 and "password" in result.splitlines()[-1]
>>> print(a)
False
>>> result="""
... line one
... line two
... this line contains password in it.
... """
>>> a=len(result)>8 and "password" in result.splitlines()[-1]
>>> print(a)
True
>>> result=""
>>> b=True and "password" in result.splitlines()[-1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: list index out of range
```
In my real test case, I was using direct condition, but then went to try with Evaluate, in the hope it would use Python evaluation precedence.
![image](https://github.com/user-attachments/assets/afe62c7a-b329-45b0-9ed1-a6e2613a1aae)

```
*** Test Cases *** 
Positive Evaluation
    ${result}=    Catenate    SEPARATOR=${\n}    line one    line two    this line contains password in it.
    ${condition}=    Evaluate    len("$result.strip()")>8 and "password" in "${result.splitlines()[-1]}"
    IF    ${condition}
        ${pass}=    Log    ${\n}${result}    console=True
    END

Negative Evaluation
    ${result}=    Set Variable    One
    ${condition}=    Evaluate    len("$result.strip()")>8 and "password" in "${result.splitlines()[-1]}"
    IF    ${condition}
        ${pass}=    Log    ${result}    console=True
    END

Error Evaluation
    ${result}=    Set Variable    ${EMPTY}
    ${condition}=    Evaluate    len("$result.strip()")>8 and "password" in "${result.splitlines()[-1]}"
    IF    ${condition}
        ${pass}=    Log    ${result}    console=True
    END
```

Could this be a special case of how `len` is implemented in Roibot Framework?

Robot Framework: 7.1, Python 3.12 in Windows 10 Professional 64bit.

**Comment by pekkaklarck** [comment]
I didn't test this, but I think the problem is that you used `"${result.splitlines()[-1]}"` what contains the normal variable syntax and thus is resolved before the expression is even evaluated. This part of the expression would probably work if you'd change it to `$result.splitlines()[-1]`.

It seems there's an other issue as well. You have `len("$result.strip()")` and because `$result` is in quotes, it is not considered a variable, This code takes length of a string `"$result.strip()"` which is 15 and thus always greater than 8. Removing the quotes and using `len($result.strip())` ought to work.

For more details about differences between `"${result}"`, `"$result"` and `$result` see the [Evaluating expression](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#evaluating-expressions) appendix in the User Guide.

**Comment by HelioGuilherme66** [comment]
You are correct (as usual ;) ).
I did try different ways of using the variables, but got some errors, that is why I ended with that example test cases.

Here is the corrected test suite:
```
*** Test Cases ***
Positive Evaluation
    ${result}=    Catenate    SEPARATOR=${\n}    line one    line two    this line contains password in it.
    ${condition}=    Evaluate    len($result.strip())>8 and "password" in $result.splitlines()[-1]
    IF    ${condition}
        ${pass}=    Log    ${\n}${result}    console=True
    END

Negative Evaluation
    ${result}=    Set Variable    One
    ${condition}=    Evaluate    len($result.strip())>8 and "password" in $result.splitlines()[-1]
    IF    ${condition}
        ${pass}=    Log    ${result}    console=True
    END

Error Evaluation
    ${result}=    Set Variable    ${EMPTY}
    ${condition}=    Evaluate    len($result.strip())>8 and "password" in $result.splitlines()[-1]
    IF    ${condition}
        ${pass}=    Log    ${result}    console=True
    END
```
