### ISSUE TITLE
Document return codes in `--help`

### ISSUE THREAD

**Issue by Lenormju** [robotframework/robotframework#5238]
I regularly use the `robot` and `rebot` scripts, notably in CI. When reading their `--help`, they give no clear indication of what their `exit_code`/`return_status` will be.
They both have a `--nostatusrc` :
> Sets the return code to zero regardless are there failures. Error codes are returned normally.

It's not clear to me what it means that "Error codes are returned normally" when "Sets the return code to zero". I think I don't know the nuance between "error code" and "return code".

And if I am not setting this option, what should be the normal error codes ?

I have found [3.1.3 Test results / Return codes](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#return-codes) in the UserGuide, which states the expected results codes for `robot` :
* 0 = all pass
* 1-249 = corresponding number of failing tests
* 250 = more than 250 tests have failed
* 251 = help
* 252 = bad command
* 253 = ctrl+C
* 254 unused ?
* 255 = unexpected internal error

Could a summary of that be included in the Robot help message ? [robot/run.py#L46](https://github.com/robotframework/robotframework/blob/master/src/robot/run.py#L46)
I can open a PR if you are interested.

Also, the same applies to `rebot`. There is *note* in [3.1.3 Test results / Return codes](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#return-codes) that indicates that it is the same for `rebot`, so could it be added to its help message too ? [robot/rebot.py#L46](https://github.com/robotframework/robotframework/blob/master/src/robot/rebot.py#L46)

**Comment by pekkaklarck** [comment]
`--no-status-rc` makes `robot` to return 0 if execution can be done regardless are there failing tests or not. You'll get a non-zero return code if tests cannot be run at all due to, for example, invalid command line options or non-existing files.

If you have ideas how to make the documentation more clear, please submit a PR. I guess documenting the return codes also in `--help` would be a good idea.

**Comment by Lenormju** [comment]
Thank you very much !
