### ISSUE TITLE
[Setup] and [Teardown] in test steps overrides Test Setup and Test Teardown from Settings

### ISSUE THREAD

**Issue by MarcinGmurczyk** [robotframework/robotframework#5240]
Hi, given below example

```
*** Settings ***
Test Setup          Log To Console    test setup in settings
Test Teardown       Log To Console    test teardown in settings


*** Test Cases ***
Test
    [Setup]    Log To Console    test setup in test steps
    Comment    just testing
    [Teardown]    Log To Console    test teardown in test steps
```

the console output would be
```
====================================================
Test                                                       test setup in test steps
..test teardown in test steps
Test                                                                                        | PASS |
----------------------------------------------------------------------------------------
Tests.Helpers.Test                                                                          | PASS |
1 test, 1 passed, 0 failed
====================================================
```

meaning that steps from Settings declared Test Setup and Test Teardown keywords were overridden by [Setup] and [Teardown] from the test itself.

I've found that behavior described in documentation 
https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#test-setup-and-teardown 

My proposal is to extend that behavior to make it more controllable.
adding new command line argument for robot execution

```
   --testsetupandteardown preservetests|preservesettings|merge  Changes how setup and teardown are parsed.
                          preservetests (default):   [Setup] or [Teardown] from test will override Test Setup or Test Teardown from ***Settings***
                          preservesettings: Test Setup or Test Teardown from ***Settings*** will override [Setup] or [Teardown] from test  
                          merge:  if both Test Setup or Test Teardown and [Setup] or [Teardown] are declared they will be executed one after another. [Setup] or [Teardown] will be executed first.
```

Rationale: there are cases when for convenience one would declare a common Test Teardown in Settings for several test cases in the suite. But one test case would have a special [Teardown] logic doing something extra. Current implementation would override Test Teardown and only [Teardown] logic would be executed for that tests which might not be wanted outcome.

**Comment by pekkaklarck** [comment]
I can see some usages for this kind of functionality, but controlling the behavior with a command line option doesn't sound like a good idea to me. If you can come up with some syntax that would allows this, it could be considered, but the syntax needed to be simpler than what you can do already now with a new keyword that calls your two setup keywords or with `Run Keywords`.

```robotframework
*** Test Cases ***
Example
    [Setup]    Run Keywords 
    ...    Log    first part of the setup
    ...    Log    second part of the setup
    Keyword 
```

A bigger limitation with setups and teardowns is that they must be keywords and using, for example, `VAR` or inline `IF` isn't possible. If syntax is changed to support them, this functionality could possibly be taken into account as well.

**Comment by pekkaklarck** [comment]
The proposed functionality won't be implemented so I close this issue. If there are ideas for syntax that allows same behavior, please submit new issues or start a discussion on Slack or on Forum.
