### ISSUE TITLE
--dryrun should accept values or have a variant that does accept values

### ISSUE THREAD

**Issue by Tattoo** [robotframework/robotframework#5258]
As documented, `--dryrun` expects no arguments. However, it would be useful if it also would. 

Often one ends up wrapping `robot` command into a script of somekind. In these cases, one would want enable the user of the script to pass along arguments to `robot`.

Easy way to do this would be something like this:
```python

import sys

def run_robot(**rf_args):
    # do some other stuff
    rf_args = ' '.join(f'--{arg_name}="{arg_value}"' for arg_name, arg_value in rf_args.items())
    run_command_line(f'robot --log NONE --report NONE {rf_args} my_suite/')

if __name__ == '__main__':
    run_robot(variablefile='some.file', include='mytag')
```

However, one is unable to support `--dryrun` this way, as one cannot write something like: `run_robot(dryrun='yes')`

Alternatively, `--dotted` and `--quiet` have alternative way to set them with `--console="dotted"` and `--console="quiet"`, so similar would work as well

**Comment by pekkaklarck** [comment]
In my opinion you should accept `dryrun=True` and handle that in your code. It ought to be very easy.

I don't think rhe command line option handling could support both `robot --dryrun tests` and `robot --dryrun true tests`, because the latter cannot be differentiated from `robot --dryrun tests more_tests` which is also valid.

Adding a separate option that accepts a value would work, but I don't think it's worth the effort or added complexity.

**Comment by pekkaklarck** [comment]
```python
def format_arg(name, value):
    if value is True:
        return f'--{name}'
    if value is False:
        return f'--no{name}'
    return f'--{name}={value}

rf_args = ' '.join(format_arg(name, value) for name, value in rf_args.items())
```
The above is untested, but ought to handle both `dryrun=True` and also `statusrc=False`.

**Comment by pekkaklarck** [comment]
Notice also that Robot itself has `robor.run()` that you could possibly use directly like `robot.run('tests.robot`, dryrun=True)`.

**Comment by Tattoo** [comment]
Yes, this is definitely a very minor thing as it is quite easy to handle yourself. I just found it surprising that `--dryrun` and `--statusrc` work this way apart from other arguments.

Given there is no value, I'll close this issue. Thanks for insight!
