### ISSUE TITLE
Error when executing keywords in debug console during Robot Framework breakpoint in VS Code

### ISSUE THREAD

**Issue by gbhandarkavathe** [robotframework/robotframework#5263]
**Issue Summary**:  
When debugging a Robot Framework test case in Visual Studio Code, attempting to execute a line in the debug console at a breakpoint results in an unexpected error instead of the expected behavior.

**Detailed Description**:  
I am running a test case using Robot Framework within Visual Studio Code and have set a breakpoint at a specific line for debugging purposes. When the execution pauses at the breakpoint, I attempt to manually execute the following line in the debug console:

```robot
Should Be Equal    ${PREFERRED_DATE_TITLE}    ${PREFERRED_DATE}
```

However, instead of running as expected, this action triggers an error message in the debug console:

```
TypeError: Keyword.run() missing 1 required positional argument: 'context'
```

**Environment**:
- **IDE**: Visual Studio Code
- **Robot Framework Version**: 7.1
- **Library in Use**: `robotframework-browser`
- **Python Version**: 3.12.5
- **Operating System**: Mac Os Ventura 13.7.1 (22H221)

**Additional Information**:  
- This issue specifically arises when attempting to manually execute commands during a paused debug session.
- The `Should Be Equal` keyword is expected to compare the values of `${PREFERRED_DATE_TITLE}` and `${PREFERRED_DATE}` but fails due to a missing context error.

**Expected Behavior**:  
When executing commands in the debug console at a breakpoint, the keywords should run as if they were in the regular test flow, allowing for verification or inspection of variable values without triggering context-related errors.

**Actual Behavior**:  
The debug console throws a `TypeError`, which seems related to a missing `context` argument, possibly due to how Robot Framework is handling the command execution within the debug environment.

**Steps to Reproduce**:
1. Set up a test case in Visual Studio Code with the `robotframework-browser` library.
2. Add a breakpoint at the line where you intend to pause execution.
3. Run the test case in debug mode.
4. When the execution stops at the breakpoint, open the debug console.
5. Manually enter a line such as `Should Be Equal ${PREFERRED_DATE_TITLE} ${PREFERRED_DATE}`.
6. Observe the error message.

**Possible Causes and Hypothesis**:  
The issue may be related to how Robot Framework manages context for keywords during interactive debugging sessions in Visual Studio Code, especially with libraries like `robotframework-browser`.

**Request for Assistance**:  
Any guidance on resolving this error or insight into managing Robot Framework contexts within the debug console would be appreciated. If there is a workaround or a specific setting to enable interactive execution at breakpoints, please advise.

**Comment by pekkaklarck** [comment]
This is most likely a bug in the VSCode plugin you use. If you are using Robot Framework Language Server, I recommend switching to RobotCode. Either way, if the problem persist, please report the issue to the plugin you use. You may also want to ask help on our Slack or Forum.
