### ISSUE TITLE
rebot combining results error

### ISSUE THREAD

**Issue by Pratapreddy1188** [robotframework/robotframework#5270]
I am using latest Robot Framework version 5.0 for automated tests.

I use rebot tool to aggregate my test result ran in multiple stages.

rebot --nostatusrc --name Integrated -x full_results.xml */*/output.xml

it usually works fine. 

I have a particular scenario where one the test fails with error "Maximum limit of started keywords and control structures exceeded"

when i try to combine this result with other successful test resutls it gives me error.
"failed: Incompatible child element 'errors' for 'test'."

I would like to get the combined report even if the errors are present in one of the it.

please find the attached output.txt (rename it to output.xml
[Uploading output.txt…]()
)

**Comment by pekkaklarck** [comment]
No new info. Closing.
