### ISSUE TITLE
Upgrade of Robot framework from 4.1.3

### ISSUE THREAD

**Issue by RatiGupta1** [robotframework/robotframework#5271]
Hi, 

We are using Robot framework version 4.1.3 in our automation project. Currently, automation is done for apis only.
We are planning to upgrade it now. And after the upgrade, we will include the UI automation testcases also.
 
Could you please suggest us to which version we can upgrade it to? 
We see 6.1.1 is the lts version (but this is more than one year old). And we also see now version 7.1.1 which is recently released.
Need your sincere guidance here.

Please suggest.
Thank you!

**Comment by pekkaklarck** [comment]
This issue tracker is for bug reports and enhancement requests. Please use support forums such as Slack and Forum, both linked from robotframework.org, for questions like this.
