### ISSUE TITLE
What happened to robotdiff.py?

### ISSUE THREAD

**Issue by nogjam** [robotframework/robotframework#5273]
I noticed a tool from way back in v2.1.2: https://robotframework.org/robotframework/2.1.2/tools/robotdiff.html 

What happened to this tool? Do we have a modern equivalent?

**Comment by pekkaklarck** [comment]
It's here but it's not maintaned:
https://bitbucket.org/robotframework/robottools/src/master/

This issue tracker is for bug reports and enhancement requests. Please use support forums such as Slack and Forum, both linked from robotframework.org, for questions like this.
