### ISSUE TITLE
Add arguments used to start Robot Framework to the test report, to give insight in provided arguments that produced the results

### ISSUE THREAD

**Issue by wvanmourik-uwv** [robotframework/robotframework#5284]
When test reports are shared among team members, it can be quite useful if the report itself contains the commandline arguments that were used to start Robot Framework.
The use cases I see are:
- debugging
- referencing older test reports compared to a recent one

The most important values I want to be able to see in the report, are the values passed to:
--argumentfile
--include
--exclude
--variable

Is there already a way I could (programmatically) grab all the arguments provided to Robot Framework and add them to the log myself?
If not, I think this is an enhancement regarding traceability.

**Comment by sebastianciupinski** [comment]
there already is variable named ${OPTIONS} https://github.com/robotframework/robotframework/issues/5201

**Comment by wvanmourik-uwv** [comment]
Indeed. Unfortunately, it does not yet give/contain all the information that I am looking for.
But, thanks for the link. I see I can add feature requests for enhancements op OPTIONS in that topic. Thanks!
