### ISSUE TITLE
Variables should not leak to lower level keywords

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#532]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=532) by @pekkaklarck on 14 Apr 2010*

Currently this is passes:

```robotframework
*** Test Case ***
Example
    ${x}=    Set Variable    hello
    My keyword

*** Keywords ***
My keyword
    Should be equal    ${x}    hello
    ${y}=    Set Variable    world
    Second keyword

Second Keyword
    Should be equal    ${x}    hello
    Should be equal    ${y}    world
```  

This has definitely been a bad design decision, and a person who
has designed it years ago I can call it a bug rather than a feature.
Instead of variables leaking to lower level keywords like this, they should
be passed as argument or, in special cases, set explicitly using Set Test
Variable keyword.

Even though this is a misfeature, we cannot remove it without deprecating
first it because existing tests may depend on it. Unfortunately the current
variable implementation is so naïve that deprecation cannot be easily done
without larger changes that don't fit into RF 2.5 scope. We thus probably
need to deprecate this in 2.6 and remove fully in 2.7.

---

**EDIT:** Deprecation wasn't easy in RF 2.9 where this bug finally was fixed and we decided not to do it. We can reconsider that if there are lot of complaints during the preview releases.

**Comment by edbrannin** [comment]
Thankfully, the previous comment's concern should be moot after #1905 is complete.

**Comment by pekkaklarck** [comment]
5ce6db7510f4cd7b2c2d5f12d575da14d515b517 implemented this and handling variable scopes was cleaned up in 87f0ce172da83b38a9c9fb305d05b09d39d60cbd and 0078f2f1c5434eb5480a3342149b2e10a23b9819. Still need to look what User Guide says about variable scopes but otherwise this issue ought to be done.

**Comment by pekkaklarck** [comment]
Enhanced documentation in 2c1917b91621b4cfd1506719188b9edb4996578f. Could you @jussimalinen review and close this issue when done.

Also noticed that the original description said we cannot change the behavior without a deprecation period. Deprecation would have been so much work that our plan is to "just do it". We can still reconsider this if there are enough complaints during preview releases.

**Comment by jussimalinen** [comment]
Looks good. Lets hope this wont break too much old tests...
