### ISSUE TITLE
Test parser should retain source line numbers

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#549]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=549) by bryan.oakley on 7 May 2010_

It would be nice if the internal robot data model could remember line
numbers from the original file, so that error reports could reference back
to the original file.

Even if exact numbers aren't possible it would still be useful. For
example, if a single keyword call is extended over several lines it might
only save the line number of the first line. 

This would make it easy(ish) to write a grep utility that is keyword aware,
and can return file and line numbers to make it easy to jump to the keyword
via a text editor.

**Comment by iacopy** [comment]
Up!

**Comment by Richard-Haven-AOL** [comment]
YES!

This lack makes debugging a tiresome slog

**Comment by nikhilrajgarhia** [comment]
It would be great benefit if we have line numbers published in the error file. Scanning the whole 'log' file to locate the error becomes a heavy task when we have huge number of TCs.

**Comment by pekkaklarck** [comment]
I'd really like this too, but I don't think it makes sense with the current parsing architecture and as long as we support the HTML format. We are most likely going to deprecate other than the plain text format in RF 3.1, which would allow us to re-implement parsing in RF 3.2. I cannot make any promises when RF 3.2 would be created (most likely not during 2017) nor will this feature be included then. If this is an important feature for you, please contact me and we can see how you could help getting it done via code contributions or direct sponsorship.

**Comment by keithdtyler** [comment]
I really would love to know how you can track down test code errors without line numbers. Not only is it massively time consuming not to be able to nail down where a problem is, but it's also decades behind every single other development paradigm in existence. Hell, even BASIC had "?SYNTAX ERROR IN 20".

**Comment by Tattoo** [comment]
@keithdtyler When test code (ie. library code) fails, it spits out Python's stack trace which has exactly what line and what module is failing and what the exception was.  This issue is more about having that information embedded in the data model to enable writing eg. your own debuggers

**Comment by stonerzju** [comment]
@Tattoo 
From your comments, it seems it is possible to print the python's stack when a failure happens in python code. Can you tell me how to do that? thanks

**Comment by pekkaklarck** [comment]
New parser (#3076) ought to make this possible.

**Comment by pekkaklarck** [comment]
The new parser already produced tokens with line and column information. The commit
050ec500f9d802dde82455fccb76ea2e6f74f3dd adds them to the higher level parsing model and 6dc30a76aa94b93cf478dcd6c30965921514d08a adds line numbers to the execution model. Finally 3db6aa17e68f317159ce1ac93a9c3f0b10e3eb38 adds line numbers to various error messages.

I guess we can consider this issue done. It was submitted on May 7, 2010, so it was open nearly ten years.

**Comment by Snooz82** [comment]
This is an awesome feature!
Allows to show this in IDEs and jump to the issue!!

**Comment by SullyJHF** [comment]
Is it at all possible to get line number information out of a dry-run generated output.xml file?

It does show line numbers for things like unknown variables in the Settings area when importing like
```robot
Library    ${test.py}
```
where `${test.py}` should be passed in from the cli and if a library does not exist. But for some reason the other errors like keywords not existing and duplicate keywords don't have any line number information in the outputted xml file.

**Comment by pekkaklarck** [comment]
Line numbers aren't in general saved to output.xml some error messages contain them. Is the problem here that there's an error without them?

**Comment by SullyJHF** [comment]
Yeah, I'm basically trying to something that can identify where in the script file syntax errors occur - at the moment I'm just showing the html log file generated from a dry-run to the user, however, I'd like to do some inline styling to show exactly where the errors are in the robot ace editor I'm working on. I've tried some hacky ways to parse the dry-run output.xml to grab anything with a line number (which works fine) and then any other kw nodes with a status of FAIL, but these latter ones don't have line number information so I can't display where they are in the editor.

You can see an example output.xml here: https://gist.github.com/SullyJHF/012409a06ab8aa0095448013abd11f22
And the script that goes along with this here: https://gist.github.com/SullyJHF/eb4f46eb6b653055cd88effabe015063

As you can see in the xml file, some things in the `<errors>` node have line endings (but some don't, see the duplicate keyword message). And also typo'd or just plain missing keywords aren't even in the errors node, and also don't have any line numbers attached to them.

Any assistance on this would be greatly appreciated.

**Comment by pekkaklarck** [comment]
Sounds like an interesting use case. Perhaps you can tell us more about that on Slack or elsewhere.

It seems we missed errors related to creating user keywords when adding line numbers to error messages as part of this issue. I submitted #4201 about that and will fix it soon.

Non-existing keywords are only detected at execution time. Source information hasn't been added to them because you can also see where the error occurred in log file. I'm afraid adding that would make these errors pretty verbose but we can experiment with that. Please submit a separate issue if you think that would be a good idea.

**Comment by SullyJHF** [comment]
Perfect thanks for this!
