### ISSUE TITLE
processing argument files: Expected at least 1 argument, got 0

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#620]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=620) by kai.hackemesser on 24 Aug 2010_

Please tell me, is something missing in this command line

C:\Java\jython-2.5.1\bin\jybot.bat --argumentfile C:\WINDOWS\TEMP\jybot7695937814215883153.args

given the args file attached is placed in the given location? Is the argument file formed well?

This just returns this output message:

[ ERROR ] Expected at least 1 argument, got 0.

**Comment by ammar-ux** [comment]
TypeError: index expected at least 1 argument, got 0

**Comment by mkorpela** [comment]
ZeroDivisionError: division by zero
