### ISSUE TITLE
Empty rows should not be discarded during parsing

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#645]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=645) by @yanne on 6 Sep 2010_

Currently, empty rows are not preserved and this affects e.g. RIDE.

We could save empty rows in similar manner as rows with only comments.

**Comment by pekkaklarck** [comment]
New parser (#3076) ought to support this. Adding to RF 3.2 scope.

**Comment by pekkaklarck** [comment]
This has been implemented by the new parser (#3076). APIs related to parsing are still partly under development, but the underlying lexer can preserve all tokens. This issue can be considered done.
