### ISSUE TITLE
Document that whitespace characters are ignored after `\n` except inside extended variable syntax

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#667]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=667) by @pekkaklarck on 20 Sep 2010_

We ignore one whitespace character after the literal \n in the test data. This is done to allow having real newline (or space) so that values can be wrapped. This whitespace is not, however, ignored inside the extended variable syntax:

```
*** Test Cases ***
Example
    Fail    ${TESTNAME.replace('x', '\n ').replace(' ', '_')}
```

The above example test will fail with this error message:

```
Ex
_mple
```

This wouldn't be such a big deal otherwise, but RIDE adds real newline after \n automatically. It might be that RIDE needs to be changed, but we should also investigate could whitespace be ignored after \n regardless where it is used.

A workaround is using Evaluate keyword instead, but then the newline needs to be surrounded with triple quotes:

```
*** Test Cases ***
Example2
    ${msg} =    Evaluate    '${TESTNAME}'.replace('x', '''\n ''').replace(' ', '_')
    Fail    ${msg}
```

**Comment by pekkaklarck** [comment]
This strange syntax was somewhat useful with the HTML format but provides no real benefits when using plain text.  It will be deprecated in RF 3.2 (#3333) and removed later.
