### ISSUE TITLE
Command line option to report skipped test data files as warnings

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#691]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=691) by @pekkaklarck on 1 Nov 2010_

Currently when a directory is executed, files that don't contain test data are ignored. A message is written into syslog using info level, so in practice files are skipped silently. This is done to prevent spurious warnings when there are non-test files in the executed directory, but as a result also test data files with invalid content are silently ignored.

To make it easier to detect invalid files, we can add a command line option to report skipped files as warnings. After that the messages are displayed on console and log files.

I think it's better to report warnings only from files that are actually parsed. Files that are skipped because they cannot even contain test data (e.g. 'foo.jpg', 'no_extension', '.config.txt') can still be skipped silently.

**Comment by pekkaklarck** [comment]
This functionality was implemented so that it can be enabled using `--warnonskippedfiles` command line option. In RF 3.1 the plan is to start reporting errors if parsing a file fails (#2857), so this option will be redundant and will be deprecated.
