### ISSUE TITLE
Failed tests can be re-executed with `--runfailed` option

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#702]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=702) by ThomasKl... on 11 Nov 2010_

Motivation:

There are several occasions where test suites are kind of expected to have tests failing as false-positives. This might be due to timing issues or left overs of previously executed tests. However the typical process is to manually restart those tests to see if they pass when executed solely.

Request:

Add a command option to pybot/jybot that takes one or multiple output.xml files as an argument, parses these files to get a list of the failed tests, reruns only these failed tests and generates a new merged output.xml with the old and new results.

Suggested implementation details: (those might be a matter of taste though)
- The pybot option, e.g. "--RerunFailed" should take multiple output xmls
- New generated output xmls files should be the output xmls used as imput, but the reexecuted tests get replaced with the log data from the rerun
- If multiple xmls were specified for rerunning also multiple new output.xmls should be written, an additional option might be added to specify this behavior (log into multiple / one file(s))
- New output.xml might get automagically suffixed with e.g. "_rerun"
- Pybot or rebot could support a command line option that takes multiple output.xml files expecting that one of the files is the original run and the other ones are reruns
  -- Every test that appears in at least one of the files should appear only once in the new output
  -- Every test that appears in multiple of those files and fails in all occurrences should be marked as failed in the new output
  -- Every test that appears in multiple of those files and passes in at least one occurence should be marked as passed in the new output.

**Comment by vinay1717** [comment]
# first execute all tests
pybot --output original.xml tests 
# then re-execute failing
pybot --rerunfailed original.xml --output rerun.xml tests 
# finally merge results
rebot --merge original.xml rerun.xml
