### ISSUE TITLE
Support writing test libraries with C# on IronPython

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#721]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=721) by @pekkaklarck on 2 Dec 2010_

Now that we have initial <a href="https://code.google.com/p/robotframework/wiki/DotNetSupport" title="Running Robot Framework on .NET with IronPython">DotNetSupport</a> (see also <a class="closed_ref" href="https://code.google.com/p/robotframework/issues/detail?id=154" title="Initial IronPython compatibility"> issue 154 </a>), it would be great if it would be possible to use C# for writing test libraries directly.

**Comment by pekkaklarck** [comment]
I close this issue because we are going to drop Python 2 support in somewhat near future and the situation with IronPython 3 doesn't look too good. Can be re-opened, or a new issue submitted, if the situation changes.
