### ISSUE TITLE
Add `initialize` listener method

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#722]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=722) by bryan.oakley on 2 Dec 2010_

I would like to see a new method added to the listener interface. This method would be called exactly once prior to any tests being run. I propose the name "initialize".

It is useful for being able to do some initialization prior to the test running (think: telling a remote listening GUI to initialize the display, or a debugger to let let the user set breakpoints before a test runs).

I would like this method to pass as one of the parameters a list of all test suites and their test cases. It doesn't need to include the actual test case data per se, but a tree of names and longnames would be nice. The data needs to be in a format that can be easily parsed to create a hierarchical tree (nested tuples are the obvious choice here)

Again, imagine a test runner or debugger GUI that wants to be able to create a hierarchical tree of all tests, with an indicator beside them for not run yet, running, pass, fail, etc.

**Comment by pekkaklarck** [comment]
Are you @boakley still interested in this? Want to provide a pull request?

**Comment by pekkaklarck** [comment]
No interest related to this lately. The latest comment about actual implementation is actually from 2010. Closing.
