### ISSUE TITLE
Jython start-up performance optimization

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#919]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=919) by @mkorpela on 25 Jul 2011_

Currently Robot Framework acceptance tests with Jython take about 5 times as much time as same tests with CPython. And I would expect that the difference in execution time is similar with other test sets.

I suggest that we measure where the time is consumed when running in Jython. We could afterwards code the time critical parts in a language that produces native JVM bytecode (for example in Scala or Clojure).

**Comment by badjolo** [comment]
anyone tried to nailgun jython startup?

**Comment by mardukbp** [comment]
@badjolo Yes. It works wonders! This is what I did:

* `git clone https://github.com/facebook/nailgun.git`
* `cd nailgun`

To generate `nailgun-server.jar` (assuming Maven is in your PATH):

* `mvn -Dmaven.javadoc.skip=true package`
* `cp nailgun-server/target/nailgun-server-1.0.1-uber.jar nailgun-server.jar`

Run the server with:

`java -cp "robotframework.jar;nailgun-server.jar" com.facebook.nailgun.NGServer`

To run Robot Framework:

* `cd nailgun-client/py`
* `python ng.py org.robotframework.RobotFramework`

The first time it takes some seconds. Afterwards it is lightning fast.

Note: WIth JRE 11 (and maybe any version greater than 8) you will get some warnings regarding the use of reflection by Jython.
