### ISSUE TITLE
Keyword categorization (i.e. tagging) support

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#925]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=925) by imranoftherings on 4 Aug 2011_

Many time you can bunch keywords in natural categories. In these cases you want to be able to specify the category and the usage doc to be created in a categorized manner.

Keyword 1
  [Category]  category1
Keyword 2
  [Category]  category1
Keyword New 1
  [Category]  category2

Documentation

category1
|---- Keyword 1
|---- Keyword 2

category2
|---- Keyword New 1

**Comment by edbrannin** [comment]
A related idea (should this be its own issue?):

Once keywords can be tagged, it would be nice if we could use `tag:` with the [`--flattenkeywords` and `--removekeywords` options](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#removing-and-flattening-keywords).

**Comment by pekkaklarck** [comment]
Using tags w/ flatten/remove is a good idea. Would be good to have it as a separate issue. Can you submit it?

**Comment by jussimalinen** [comment]
We still need to document this, but otherwise it should be ready.

**Comment by pekkaklarck** [comment]
Small doc enhancements in a1378ee350dd4c0801dc7ad36d9e0f15605282b4. This issue is done!!
