### ISSUE TITLE
Running selected cases from multiple test suite

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#948]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=948) by SOURABHKT on 7 Sep 2011_

Hi,

I am using Robot Framework 2.6.0 (Python 2.6.4 on win32) on Windows XP.

I tried to run selected test cases from different test suites by using command :

pybot --test TC1 Suite1.html --test TC2 Suite2.html

But instead of running TC1 from Suite1 and TC2 from Suite2 it is running TC1 from Suite1 two times.

One more thing i want to include here.I also tried to run following command for multiple test suites which all contains a test cases name TC1 and TC2 :

pybot --test TC1 Suite1.html --test TC2 Suite2.html

But in this condition TC1 from Suite1 and TC1 also from Suite2 is running.

I thought this is a major bug and need to be fixed soon.

Regards

Sourabh

**Comment by vinay1717** [comment]
pybot -t testcasename Testname should work
